RobotLocomotion/drake

bindings/pydrake/systems/meshcat_visualizer.py
tools/workspace/meshcat/repository.bzl
tools/workspace/meshcat_python/repository.bzl

(Transparency support is a new feature in the latest meshcat and meshcat-python version.)
@jwnimmer-tri lmk if you want me to split these, I saw the new feature and was excited :P
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10785)

Updates meshcat and meshcat-python, and adds meshcat-vis transparency support

---

solvers/mathematical_program.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10795)

fix examples in mathematical program doxygen to reflect updated API

---

automotive/maliput/doc/maliput-design.org

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/9487)

Begin documenting the math involved in maliput's `multilane` backend.

---

bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/meshcat_visualizer.py

Addresses #10777. FYI @RussTedrake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10784)

Support scaling for meshes visualized with meshcat-vis

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py

(and add some argument names)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10803)

add additional AddLinearConstraint bindings 

---

automotive/maliput/api/BUILD.bazel
automotive/maliput/api/intersection.cc
automotive/maliput/api/intersection.h
automotive/maliput/base/BUILD.bazel
automotive/maliput/base/intersection.cc
automotive/maliput/base/intersection.h
automotive/maliput/base/test/intersection_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10796)

Adds Skeletal Intersection Class to Maliput

---

common/test/value_test.cc
common/value.h

Until C++17 `template <auto...>` arrives, it is somewhat difficult to unpack non-type template parameter packs.  In the meantime, we can detect this condition and report a failure to hash.  In practice such templates being used in `Value<T>` are rare -- currently there is only one example in Drake (`Image<PixelType kPixelType>`).
Improves #10718.  See #10727 for how this ends up being used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10799)

common: Add TypeHasher test for non-type templates

---

automotive/maliput/multilane/loader.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10815)

Fixes grammar in maliput/multilane/loader.h

---

tools/workspace/doxygen/Dockerfile
tools/workspace/doxygen/build_binaries_with_docker

Closes #10666.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10717)

Add scripts for building Doxygen binaries with Docker

---

bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/framework_py_values.cc
bindings/pydrake/systems/test/custom_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10817)

add binding for AllocateTimeDerivatives

---

common/test_utilities/BUILD.bazel

Closes #10820.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10821)

common: Mark limit_malloc_test as no_tsan and no_memcheck

---

automotive/maliput/api/rules/traffic_lights.cc
automotive/maliput/api/rules/traffic_lights.h
automotive/maliput/api/test/traffic_lights_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10828)

Adds check verifying Maliput BulbGroup size is > 0

---

automotive/maliput/api/test_utilities/rules_test_utilities.h

Removes some unnecessary calls to unused().
Adds a couple const keywords.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10832)

Cleans up rules_test_utilities.h

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py

Toward #10824
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10835)

Add python binding for symbolic matrix Evaluate

---

automotive/maliput/api/rules/traffic_lights.cc
automotive/maliput/api/rules/traffic_lights.h
automotive/maliput/api/test/traffic_lights_test.cc
automotive/maliput/api/test_utilities/rules_test_utilities.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10827)

Adds TrafficLight to Maliput

---

automotive/maliput/api/rules/traffic_lights.cc
automotive/maliput/api/rules/traffic_lights.h
automotive/maliput/api/test/traffic_lights_test.cc
automotive/maliput/api/test_utilities/rules_test_utilities.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10802)

Adds BulbState to Maliput

---

examples/manipulation_station/test/manipulation_station_test.cc
examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
multibody/plant/BUILD.bazel
multibody/plant/contact_jacobians.cc
multibody/plant/contact_jacobians.h
multibody/plant/implicit_stribeck_solver_results.cc
multibody/plant/implicit_stribeck_solver_results.h
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/test/box_test.cc
multibody/plant/test/inclined_plane_test.cc

Resolves #10741.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10783)

Cache contact computations.

---

common/trajectories/piecewise_polynomial.cc
common/trajectories/piecewise_polynomial.h

Resolves #7399
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10844)

Updates the documentation for PiecewisePolynomial.

---

solvers/mosek_solver.cc
solvers/test/mosek_solver_test.cc
solvers/test/scs_solver_test.cc
solvers/test/semidefinite_program_examples.cc
solvers/test/semidefinite_program_examples.h

Resolves #10791 
cc @pangtao22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10805)

Do not add additional variables to Mosek when solving semidefinite program.

---

systems/framework/system_constraint.h

It's already done in #10391 #10613 #10684
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10867)

Remove a TODO in SystemConstraint documentation

---

automotive/maliput/multilane/BUILD.bazel
automotive/maliput/multilane/test/2x2_intersection_test.cc

This test confirms that the names and positions of the lanes are as
expected. Followup PRs will add additional checks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10841)

Adds a unit test for 2x2_intersection.yaml

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
solvers/BUILD.bazel
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/sos_constraint_test.cc

Resolves #10202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10873)

change the return type of AddSosConstraint.

---

common/yaml/dev/BUILD.bazel
common/yaml/dev/test/yaml_read_archive_test.cc
common/yaml/dev/visitor.h
common/yaml/dev/yaml_read_archive.cc
common/yaml/dev/yaml_read_archive.h
tools/install/libdrake/build_components.bzl

Relates #10869.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10870)

common/yaml: Copy files from TRI's Anzu repository

---

automotive/maliput/multilane/test/2x2_intersection_test.cc

This confirms the branching structure is as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10891)

Adds unit test to 2x2_intersection_test.cc

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/all.py
bindings/pydrake/drawing.py
bindings/pydrake/math_py.cc
bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/drawing_test.py
bindings/pydrake/test/math_test.py
bindings/pydrake/test/symbolic_test.py

related to #10863
also adds the bindings for the quadratic form tools that I almost used, in case they are useful in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10884)

add support for plotting ellipses from their quadratic form.

---

automotive/maliput/api/BUILD.bazel
automotive/maliput/api/road_network.cc
automotive/maliput/api/road_network.h
automotive/maliput/api/test/mock.cc
automotive/maliput/api/test/mock.h
automotive/maliput/api/test/road_network_test.cc
automotive/maliput/api/test/rules_right_of_way_test.cc

Resolves #10848.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10881)

Adds RoadNetwork to Maliput

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10902)

add binding and test for contact_info.contact_pair()

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
solvers/BUILD.bazel
solvers/mathematical_program_result.h
solvers/test/mathematical_program_result_test.cc

Resolves #10720 
@mposa
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10896)

Add MathematicalProgramResult::EvalBinding

---

automotive/maliput/api/rules/traffic_lights.cc
automotive/maliput/api/rules/traffic_lights.h
automotive/maliput/api/test/traffic_lights_test.cc
automotive/maliput/api/test_utilities/rules_test_utilities.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10906)

Adds bounding box to Maliput Bulb

---

solvers/snopt_solver_common.cc
solvers/test/snopt_solver_test.cc

Relates #10918.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10923)

solvers: Add fortran/f2c/unavailable to SNOPT name

---

common/BUILD.bazel
common/drake_nodiscard.h
common/test/drake_nodiscard_test.cc
tools/vector_gen/lcm_vector_gen.py
tools/vector_gen/test/goal/sample.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10926)

common: Add DRAKE_NODISCARD

---

geometry/proximity_engine.cc
geometry/test/proximity_engine_test.cc

FCL currently doesn't support signed distance queries with halfspaces (and other primitives). Rather than exploding in a segfault, we're catching the failure condition in drake and throwing an exception with some guidance-offering message.
This is a short-term bandaid (replace a segfault with an intelligible message). The long-term solution is part of fcl and is encapsulated in the issue: https://github.com/flexible-collision-library/fcl/issues/383.
Relates to #10905 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10920)

Signed distance with halfspace - replace segfault with message

---

common/test/copyable_unique_ptr_test.cc
common/test/drake_nodiscard_test.cc
common/test/is_cloneable_test.cc
examples/humanoid_controller/humanoid_status.h
systems/framework/basic_vector.h
systems/framework/event.h
systems/framework/test/diagram_test.cc
systems/framework/test/value_checker_test.cc
systems/framework/test_utilities/my_vector.h
systems/lcm/test/translator_test.cc
systems/plants/spring_mass_system/spring_mass_system.h
systems/rendering/frame_velocity.h
systems/rendering/pose_vector.h
tools/vector_gen/lcm_vector_gen.py
tools/vector_gen/test/goal/sample.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10929)

Use DRAKE_NODISCARD on bare-pointer Clone methods

---

common/symbolic_rational_function.cc
common/test/symbolic_rational_function_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10922)

Only call RationalFunction::CheckIndeterminates in debug mode.

---

multibody/plant/BUILD.bazel
multibody/plant/contact_jacobians.cc
multibody/plant/implicit_stribeck_solver_results.cc
multibody/plant/implicit_stribeck_solver_results.h
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h

This fixes some things missed in #10783 and #10889.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10928)

multibody/plant: Resolve code review defects

---

examples/compass_gait/BUILD.bazel
examples/rimless_wheel/BUILD.bazel
examples/valkyrie/BUILD.bazel
systems/lcm/BUILD.bazel
systems/lcm/lcm_publisher_system.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10936)

systems/lcm: Reduce spurious dependencies

---

bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/meshcat_visualizer.py
bindings/pydrake/systems/test/meshcat_visualizer_test.py
examples/manipulation_station/end_effector_teleop_sliders.py

A system to visualize point clouds in meshcat. It can be called with a MeshcatVisualizer system or with an independent meshcat Visualizer instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10911)

Visualize meshcat pointclouds

---

common/eigen_types.h
systems/primitives/BUILD.bazel
systems/primitives/affine_system.cc
systems/primitives/symbolic_vector_system.cc
systems/primitives/symbolic_vector_system.h
systems/primitives/test/symbolic_vector_system_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10913)

adds `SymbolicVectorSystem` as a primitive

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/CPPLINT.cfg
bindings/pydrake/attic/BUILD.bazel
bindings/pydrake/attic/multibody/BUILD.bazel
bindings/pydrake/attic/solvers/BUILD.bazel
bindings/pydrake/attic/systems/BUILD.bazel
bindings/pydrake/common/BUILD.bazel
bindings/pydrake/common/test_utilities/BUILD.bazel
bindings/pydrake/doc/BUILD.bazel
bindings/pydrake/examples/BUILD.bazel
bindings/pydrake/examples/multibody/BUILD.bazel
bindings/pydrake/maliput/BUILD.bazel
bindings/pydrake/manipulation/BUILD.bazel
bindings/pydrake/multibody/BUILD.bazel
bindings/pydrake/pydrake.bzl
bindings/pydrake/solvers/BUILD.bazel
bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/third_party/BUILD.bazel
bindings/pydrake/util/BUILD.bazel
tools/lint/cpplint.bzl

Fixes #10886.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10952)

pydrake: Disable cpplint warnings subsumed by clang-format

---

examples/pendulum/pendulum_plant.h

Resolves #10818
Not sure if there's really any value to testing this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10955)

pendulum: Use `InputPort.Eval`

---

bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/custom_test.py
bindings/pydrake/systems/test/general_test.py

Resolves #10466
\cc @robert-verkuil 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10957)

py systems: Bind parameter declaration

---

common/symbolic_polynomial.cc
common/test/symbolic_polynomial_test.cc
common/test/symbolic_rational_function_test.cc

Related to #10229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10940)

call symbolic::Polynomial::CheckInvariant only in debug mode.

---

bindings/pydrake/attic/systems/controllers_py.cc
bindings/pydrake/attic/systems/sensors_py.cc
bindings/pydrake/systems/analysis_py.cc
bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/framework_py_values.cc
bindings/pydrake/systems/systems_pybind.h
bindings/pydrake/systems/test/general_test.py
systems/framework/value_to_abstract_value.h

Adds pydrake bindings atop #10759.  ~For now, just for CI testing.~
Relates #10692.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10945)

pydrake: Add InputPort.FixValue bindings

---

doc/python_bindings.rst
setup/mac/binary_distribution/install_prereqs.sh
setup/mac/source_distribution/install_prereqs.sh
setup/mac/source_distribution/install_prereqs_user_environment.sh
setup/ubuntu/16.04/install_prereqs.sh
setup/ubuntu/18.04/install_prereqs.sh
setup/ubuntu/binary_distribution/install_prereqs.sh
setup/ubuntu/source_distribution/install_prereqs.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10961)

 Warn if Anaconda is installed when running install_prereqs

---

bindings/pydrake/solvers/BUILD.bazel
bindings/pydrake/solvers/gurobi_py.cc
bindings/pydrake/solvers/mosek_py.cc
bindings/pydrake/solvers/solvers_pybind.h
bindings/pydrake/solvers/test/gurobi_solver_test.py
bindings/pydrake/solvers/test/mosek_solver_test.py

Per f2f with @hongkai-dai
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10962)

py solvers: Bind `AcquireLicense` for `GurobiSolver` and `MosekSolver`

---

systems/primitives/BUILD.bazel
systems/primitives/symbolic_vector_system.cc
systems/primitives/symbolic_vector_system.h
systems/primitives/test/symbolic_vector_system_test.cc

Includes #10913 (which should land shortly).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10937)

add Expression support for SymbolicVectorSystem

---

automotive/maliput/api/test_utilities/rules_right_of_way_compare.cc
automotive/maliput/base/BUILD.bazel
automotive/maliput/base/right_of_way_rules_loader.cc
automotive/maliput/base/right_of_way_rules_loader.h
automotive/maliput/base/test/right_of_way_rules_loader_test.cc
automotive/maliput/multilane/2x2_intersection.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10949)

Adds Maliput RightOfWayRule Loader

---

common/yaml/BUILD.bazel
tools/install/libdrake/BUILD.bazel
tools/install/libdrake/build_components.bzl
tools/install/libdrake/drake.cps

Closes #10869.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10954)

common/yaml: Mark public and add to Drake install

---

systems/primitives/BUILD.bazel
systems/primitives/discrete_time_delay.cc
systems/primitives/discrete_time_delay.h
systems/primitives/test/discrete_time_delay_test.cc

@sherm1 for feature review (since he reviewed the rest of DiscreteTimeDelay, please reassign if someone else should review).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10958)

Add AbstractValue support to DiscreteTimeDelay system

---

math/rotation_matrix.h
math/test/rotation_matrix_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10931)

Add .row() and .col() methods to RotationMatrix class (with tests)

---

bindings/pydrake/systems/primitives_py.cc
bindings/pydrake/systems/test/primitives_test.py
systems/primitives/BUILD.bazel
systems/primitives/symbolic_vector_system.cc
systems/primitives/symbolic_vector_system.h
systems/primitives/test/symbolic_vector_system_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10994)

add autodiff & python bindings to SymbolicVectorSystem

---

third_party/com_github_pybind_pybind11/mkdoc.py

Resolves #10154
Could've used [`ctx.var["GENDIR"]`](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#var), but meh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11002)

mkdoc: Stop using TMPDIR

---

bindings/pydrake/doc/gen_sphinx.py
bindings/pydrake/doc/serve_sphinx.py
doc/BUILD.bazel
doc/gen_sphinx.py
doc/serve_sphinx.py

Resolves #10996
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10998)

doc: Use absolute imports

---

attic/systems/sensors/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11000)

Disable rgbd_renderer_ospray_test under ThreadSanitizer

---

geometry/proximity_engine.cc
geometry/query_object.h
geometry/test/proximity_engine_test.cc

Fix issue #10753 compute signed distance function between a sphere (point) to a cylinder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10813)

geometry: signed distances for point-cylinder and sphere-cylinder.

---

README.md

Follow-up to #10963 
Old look:
> ![image](https://user-images.githubusercontent.com/26719449/54936698-66cc5080-4ef9-11e9-85b6-b84d058ce1d8.png)
New look:
> ![image](https://user-images.githubusercontent.com/26719449/54936720-7186e580-4ef9-11e9-8f4d-78439206083a.png)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11016)

README: De-duplicate from `docs`

---

doc/index.rst
doc/index_images.rst

Make other HTML specify units, and specify attributes in same order
Resolves #11031
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11032)

doc: Make front page logo not use a hyperlink; fix the width

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/drawing_graphviz_example.py
common/proto/test/call_python_test.py
examples/van_der_pol/BUILD.bazel
examples/van_der_pol/plot_limit_cycle.py
tools/bazel.rc

Resolves #11029
\cc @jwnimmer-tri @RussTedrake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11030)

py: Use --test_env to permit easier usage of matplotlib in tests

---

automotive/maliput/doc/maliput-design.org

Resolves #11022.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11038)

Updates Maliput DesignDoc to allow discontinuity at road boundaries

---

tools/install/libdrake/build_components.bzl

(Motivated by confusion in #10933.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11048)

libdrake: Clarify build_components comment

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11050)

add a few argument names to the mathematical program bindings

---

doc/python_bindings.rst

Meta-follow-up to #11045
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11054)

doc python: Move Anaconda disclaimer back, but under intro text

---

automotive/steering_command_driver.py

Related: #8745
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11063)

Fix the bug introduced by #8745

---

automotive/maliput/api/lane_data.h
automotive/maliput/api/test/lane_data_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11040)

[DSIM-1823] - add basic vector operations to GeoPositionT class

---

automotive/maliput/api/rules/phase_ring.cc
automotive/maliput/api/rules/phase_ring.h
automotive/maliput/api/test/phase_ring_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11058)

Adds next phases info to PhaseRing

---

tools/skylark/drake_py.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11071)

skylark: Add "py" tag for `drake_py*` tests

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11082)

add binding for plant.get_generalized_contact_forces_output_port

---

doc/clion.rst

The material about downgrading Bazel Plugin might be too ad hoc.  I'll be happy to remove them. Please let me know.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11066)

Update versions of CLion and Bazel Plugin.

---

bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/test/trajectory_optimization_test.py
bindings/pydrake/systems/trajectory_optimization_py.cc
multibody/benchmarks/pendulum/make_pendulum_plant.h
systems/trajectory_optimization/BUILD.bazel
systems/trajectory_optimization/direct_collocation.cc
systems/trajectory_optimization/direct_collocation.h
systems/trajectory_optimization/test/direct_collocation_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11076)

support multiple inputs and additional state in direct collocation

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
multibody/plant/multibody_plant.h
multibody/tree/multibody_tree.h

Resolves #11051.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11069)

Implements binding to add a gravity field

---

common/symbolic_expression_cell.cc

Close #11007
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11099)

Use distributive law to handle differentiation of products

---

solvers/mathematical_program.h

Resolves #11097
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11102)

change the size check in SetInitialGuess to DRAKE_DEMAND

---

bindings/pydrake/manipulation/simple_ui.py
bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/meshcat_visualizer.py
bindings/pydrake/systems/test/custom_test.py
bindings/pydrake/systems/test/lcm_test.py

Resolves #9651
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11073)

py systems: Use `{NAME}` for protected methods; deprecate `_{NAME}`

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py

Also bindings FindDecisionVariableIndices, for convenience.
@EricCousineau-TRI, would you be willing to take a look? (Cool with any other volunteers too)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11088)

Python bindings for MathematicalProgram Autodiff EvalBinding

---

automotive/maliput/api/BUILD.bazel
automotive/maliput/api/rules/traffic_light_book.h
automotive/maliput/base/BUILD.bazel
automotive/maliput/base/test/traffic_light_book_test.cc
automotive/maliput/base/traffic_light_book.cc
automotive/maliput/base/traffic_light_book.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11108)

Adds TrafficLightBook

---

tools/workspace/meshcat/repository.bzl
tools/workspace/meshcat_python/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11106)

workspace: Bump meshcat to latest commits

---

automotive/maliput/base/phase_ring_book_loader.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11115)

Polishes docstring of phase_ring_book_loader.h

---

automotive/automotive_demo.cc
automotive/automotive_simulator.cc
automotive/automotive_simulator.h
automotive/test/automotive_simulator_test.cc
bindings/pydrake/lcm_py.cc
bindings/pydrake/systems/lcm_py.cc
bindings/pydrake/systems/test/lcm_test.py
bindings/pydrake/test/lcm_test.py
lcm/drake_lcm.h
lcm/lcm_receive_thread.h
systems/lcm/BUILD.bazel
systems/lcm/lcm_interface_system.cc
systems/lcm/lcm_interface_system.h
systems/lcm/lcm_subscriber_system.cc
systems/lcm/lcm_subscriber_system.h
systems/lcm/test/connect_lcm_scope_test.cc
systems/lcm/test/lcm_interface_system_test.cc
systems/lcm/test/lcm_publisher_system_test.cc
systems/lcm/test/lcm_subscriber_system_test.cc
systems/sensors/BUILD.bazel
systems/sensors/lcm_image_array_receive_example.cc

Relates #10895.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/10935)

systems/lcm: Add LcmInterfaceSystem

---

automotive/maliput/base/phase_ring_book_loader.cc
automotive/maliput/base/phase_ring_book_loader.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11112)

Polishes includes for PhaseRingBookLoader

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/BUILD.bazel
solvers/solve.cc
solvers/solve.h
solvers/test/solve_test.cc

This is a long-missed feature by former developers of mathematical programs in the Matlab versions of drake.  
Resolves #3130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11103)

Provide GetInfeasibleConstraints

---

systems/lcm/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11121)

systems/lcm: Disable lcm_interface_system_test for now

---

bindings/pydrake/math_py.cc
bindings/pydrake/test/math_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11095)

add python bindings for continuous and discrete Riccati and Lyapunov equations

---

solvers/snopt_solver.cc

Before this change, I was noticing a lot of snopt threads (when doing
parallel solves with openmp) sitting in getrusage in backtraces while
working on `enabling-anzu#2047` (like 31 of 32 threads).
It turns out that the kernel takes a lock when calling `getrusage`
with `RUSAGE_SELF` (see
https://github.com/torvalds/linux/blob/master/kernel/sys.c#L1732 )
which is what's happening in libgfortran, see
https://github.com/gcc-mirror/gcc/blob/master/libgfortran/intrinsics/time_1.h#L149
so we probably shouldn't do that during parallel solves.  For extra
fun, `RUSAGE_SELF` returns the total for all threads, so the
measurement would be garbage anyway.
This change seems to make the issue go away in subsequent backtraces.
--- …

Set "timing level" to zero when calling into snopt.

---

doc/buildcop.rst

Closes RobotLocomotion/drake-external-examples#57.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11126)

Add instructions for dealing with drake-external-examples failures to the build cop playbook

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py
common/symbolic_expression.h
common/test/symbolic_substitution_test.cc

Close #11105
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11123)

Add Substitute functions for symbolic matrix

---

attic/multibody/rigid_body_plant/test/drake_visualizer_test.cc
attic/multibody/rigid_body_plant/test/frame_visualizer_test.cc
examples/acrobot/run_plant_w_lcm.cc
examples/acrobot/spong_controller_w_lcm.cc
examples/acrobot/test/acrobot_lcm_msg_generator.cc
examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
examples/double_pendulum/double_pendulum_demo.cc
examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc
examples/kuka_iiwa_arm/kuka_simulation.cc
examples/particles/uniformly_accelerated_particle.cc
examples/pr2/pr2_passive_simulation.cc
examples/schunk_wsg/schunk_wsg_simulation.cc
examples/valkyrie/test/valkyrie_simulation_test.cc
examples/valkyrie/valkyrie_pd_ff_controller.cc
examples/valkyrie/valkyrie_simulation.cc
examples/valkyrie/valkyrie_simulator.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11124)

examples: Port to LcmInterfaceSystem

---

multibody/inverse_kinematics/test/angle_between_vectors_constraint_test.cc
solvers/constraint.h
solvers/test/mathematical_program_test.cc

Resolves #2969
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11129)

check if the constraint lower bound is no larger than the upper bound

---

bindings/pydrake/doc/pydrake_sphinx_extension.py
setup/mac/source_distribution/requirements.txt

Regarding Slack discussion:
https://drakedevelopers.slack.com/archives/C270MN28G/p1554297248047400
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11141)

mac: Constrain Sphinx version

---

automotive/maliput/base/intersection.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11137)

Adds missing include to intersection.cc

---

tools/dynamic_analysis/tsan.supp

Closes #11136.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11140)

tsan: Suppress lcm_memq false positive

---

automotive/maliput/base/phase_based_right_of_way_state_provider.h

In PhaseBasedRightOfWayStateProvider.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11144)

Initializes pointer member variables

---

automotive/maliput/base/BUILD.bazel
automotive/maliput/base/test/traffic_light_book_loader_test.cc
automotive/maliput/base/traffic_light_book_loader.cc
automotive/maliput/base/traffic_light_book_loader.h
automotive/maliput/multilane/2x2_intersection.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11133)

Adds TrafficLightBook loader

---

bindings/pydrake/systems/meshcat_visualizer.py
examples/manipulation_station/manipulation_station_hardware_interface.cc
examples/manipulation_station/mock_station_simulation.cc
examples/manipulation_station/test/manipulation_station_hardware_interface_test.cc

Relates #10981.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11119)

manipulation_station: Use LcmInterfaceSystem

---

bindings/pydrake/systems/test/custom_test.py
bindings/pydrake/systems/test/general_test.py

Polish comment in overload deprecation test
Follow-up to #11150 
\cc @RussTedrake  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11161)

py systems: Explicitly test default instantiations

---

automotive/maliput/base/phase_ring_book_loader.cc
automotive/maliput/base/road_rulebook_loader.cc
automotive/maliput/base/traffic_light_book_loader.cc

For extra safety.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11168)

Adds additional checks to Maliput loaders

---

solvers/test/mathematical_program_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11169)

Fix a minor bug in mathematical_program_test

---

common/BUILD.bazel
common/test/symbolic_expression_matrix_test.cc

As promised in #11173.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11176)

Add a test for Matrix<Expression>::inverse

---

automotive/maliput/api/rules/traffic_lights.h
automotive/maliput/api/test/traffic_lights_test.cc

This is needed for phases to identify a specific bulb when defining
its state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11160)

Adds UniqueBulbId

---

multibody/benchmarks/acrobot/make_acrobot_plant.cc
multibody/parsing/detail_ignition.cc
multibody/parsing/detail_ignition.h
multibody/parsing/detail_scene_graph.cc
multibody/parsing/detail_scene_graph.h
multibody/parsing/detail_sdf_parser.cc
multibody/parsing/detail_tinyxml.cc
multibody/parsing/detail_tinyxml.h
multibody/parsing/detail_urdf_parser.cc
multibody/plant/multibody_plant.h

Towards #11064
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11180)

multibody: Deprecate Isometry3 usages of `AddJoint`

---

multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/test/multibody_plant_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11143)

Adds AutoDiffXd support for CalcPointPairPenetrations when there are no collisions.

---

automotive/maliput/api/rules/phase.h
automotive/maliput/api/test/phase_ring_test.cc
automotive/maliput/api/test/phase_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11163)

Updates Phase to use UniqueBulbId

---

examples/bouncing_ball/bouncing_ball.h
examples/compass_gait/compass_gait.cc
examples/rimless_wheel/rimless_wheel.cc
systems/analysis/test/simulator_test.cc
systems/analysis/test_utilities/logistic_system.h
systems/analysis/test_utilities/stateless_system.h
systems/framework/leaf_system.h
systems/framework/test/leaf_system_test.cc
systems/framework/witness_function.h

Related to #11184
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11195)

DeclareWitnessFunction => MakeWitnessFunction

---

bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/custom_test.py
systems/framework/leaf_system.h
systems/framework/test/leaf_system_test.cc
systems/framework/witness_function.h

Related to #11184 and #11185.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11186)

Python bindings for witness functions

---

automotive/maliput/api/test/traffic_lights_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11203)

Runs clang-format on traffic_lights_test.cc

---

automotive/maliput/api/BUILD.bazel
automotive/maliput/api/road_network.cc
automotive/maliput/api/road_network.h
automotive/maliput/api/rules/right_of_way_rule.h
automotive/maliput/api/rules/rule_state_provider.h
automotive/maliput/api/test/mock.cc
automotive/maliput/api/test/mock.h
automotive/maliput/api/test/road_network_test.cc
automotive/maliput/api/test/rule_state_provider_test.cc
automotive/maliput/api/test_utilities/rules_right_of_way_compare.cc
automotive/maliput/api/test_utilities/rules_right_of_way_compare.h
automotive/maliput/base/BUILD.bazel
automotive/maliput/base/manual_rule_state_provider.cc
automotive/maliput/base/manual_rule_state_provider.h
automotive/maliput/base/phase_based_rule_state_provider.cc
automotive/maliput/base/phase_based_rule_state_provider.h
automotive/maliput/base/test/manual_rule_state_provider_test.cc
automotive/maliput/base/test/phase_based_rule_state_provider_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11151)

Simplifies names of various rule state providers

---

examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc
examples/kuka_iiwa_arm/kuka_simulation.cc
examples/manipulation_station/mock_station_simulation.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11206)

examples: Stop using deprecated IIWA "command_message" port

---

automotive/maliput/api/test/phase_ring_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11209)

Applies clang-format to phase_ring_test.cc

---

automotive/maliput/api/type_specific_identifier.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11210)

Fixes TypeSpecificIdentifier<T> std::less specialization

---

solvers/BUILD.bazel
solvers/scs_solver.cc
solvers/scs_solver_common.cc
solvers/test/exponential_cone_program_examples.cc
solvers/test/exponential_cone_program_examples.h
solvers/test/scs_solver_test.cc

This is related to #11101 , as requested by @pangtao22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11199)

Scs exponential cone

---

doc/code_style_guide.rst
third_party/com_github_pybind_pybind11/mkdoc.py
tools/lint/drakelint.py
tools/lint/python_lint.bzl
tools/workspace/metadata.py

Will remove "do not review" depending on the resolution of #9615
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/9765)

doc: Update style guide to minimize number of executable Python scripts

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/lcm_py.cc
bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/test/lcm_test.py
bindings/pydrake/test/lcm_test.py
lcm/BUILD.bazel
lcm/drake_lcm.cc
lcm/drake_lcm.h
lcm/drake_mock_lcm.cc
lcm/drake_mock_lcm.h
lcm/lcm_receive_thread.h
lcm/test/drake_lcm_test.cc
lcm/test/drake_lcm_thread_test.cc
systems/lcm/lcm_driven_loop.cc
systems/lcm/test/lcm_publisher_system_test.cc

Relates #10981.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11166)

lcm: Deprecate many APIs

---

automotive/maliput/base/BUILD.bazel
automotive/maliput/base/manual_phase_ring_book.cc
automotive/maliput/base/manual_phase_ring_book.h
automotive/maliput/base/phase_ring_book_loader.cc
automotive/maliput/base/test/manual_phase_ring_book_test.cc
automotive/maliput/base/test/phase_based_rule_state_provider_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11218)

Renames SimplePhaseRingBook to be ManualPhaseRingBook

---

automotive/maliput/api/road_network.cc
automotive/maliput/api/road_network.h
automotive/maliput/api/test/mock.cc
automotive/maliput/api/test/mock.h
automotive/maliput/api/test/road_network_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11221)

Adds TrafficLightBook to RoadNetwork

---

solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/exponential_cone_program_examples.cc
solvers/test/exponential_cone_program_examples.h
solvers/test/scs_solver_test.cc

This is requested by @pangtao22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11220)

MathematicalProgram maximizes log determinant.

---

systems/framework/leaf_system.h
systems/framework/system.h
systems/framework/test/leaf_system_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11213)

Implements DeclareForcedDiscreteUpdateEvent for LeafSystem.

---

examples/acrobot/test/run_swing_up_traj_optimization.cc

Having the initial guess for q0 be the straight down position makes `//example/acrobot/test/run_swing_up_traj_optimization` very brittle. This was recently exposed by #11207, in which changing the order in which the decision variables were declared caused failures on Mac nightly builds (e.g. https://drake-cdash.csail.mit.edu/testDetails.php?test=27815250&build=1152534). This PR moves the initial guess for q0 to be epsilon away from straight down.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11241)

acrobot: Move initial guess for swing up away from straight down

---

math/rotation_matrix.h
math/test/rotation_matrix_test.cc

Closes #5274.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11226)

RotationMatrix::ToQuaternion supports symbolic

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11232)

add python binding for log det cost.

---

common/test/symbolic_expression_matrix_test.cc
common/test_utilities/eigen_matrix_compare.h
geometry/dev/test/geometry_state_test.cc
geometry/test/geometry_state_test.cc
multibody/plant/test/contact_results_to_lcm_test.cc
systems/rendering/test/pose_aggregator_test.cc

... because if you call this function you should care about its result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11254)

common: Add DRAKE_NODISCARD to CompareMatrices().

---

geometry/proximity/BUILD.bazel
geometry/proximity/distance_to_point.h
geometry/proximity/distance_to_point_with_gradient.cc
geometry/proximity/test/distance_to_point_test.cc
geometry/query_results/signed_distance_to_point.h
geometry/query_results/signed_distance_to_point_with_gradient.h
geometry/test/proximity_engine_test.cc

Also add a flag is_grad_W_well_defined in the query result.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11249)

Add test on the gradient for point to box/sphere signed distance query.

---

common/test_utilities/eigen_geometry_compare.h
common/test_utilities/is_dynamic_castable.h
common/test_utilities/is_memcpy_movable.h
common/test_utilities/measure_execution.h
common/test_utilities/symbolic_test_util.h

DRAKE_NODISCARD was already added to `CompareMatrices()` in #11254.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11255)

common: Add DRAKE_NODISCARD to test utility functions.

---

bindings/pydrake/systems/test/custom_test.py
systems/analysis/integrator_base.h
systems/analysis/simulator.h
systems/analysis/test/simulator_test.cc

Resolves #11185.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11196)

Fixes witness functions causing periodic triggers to trigger early. 

---

examples/manipulation_station/differential_ik.py
examples/manipulation_station/end_effector_teleop_mouse.py

Resolves #11070
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11258)

manipulation_station: Do not open window for mouse teleop test

---

bindings/pydrake/math_py.cc
bindings/pydrake/test/math_test.py

@EricCousineau-TRI for feature review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11263)

pydrake math: Add bindings for RpyDt to angular velocity conversion

---

bindings/pydrake/examples/multibody/BUILD.bazel
bindings/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis.py
bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/tree_py.cc
bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/analysis_py.cc
bindings/pydrake/systems/test/monte_carlo_test.py

Not quite ready for full review yet, but it's definitely build server time. Never tried the magic WrapCallbacks thing before!
@RussTedrake (or anyone else) -- any preference if that Pendulum test should maybe live as an example instead? It's maybe a little involved (and long-ish running) for a unit test...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11256)

Python bindings for Monte Carlo analysis

---

automotive/maliput/base/manual_phase_provider.cc
automotive/maliput/base/manual_phase_provider.h
automotive/maliput/base/test/manual_phase_provider_test.cc

Resolves #9993.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11279)

Updates ManualPhaseProvider to Support Next Phase

---

systems/framework/cache_doxygen.h
systems/framework/context_base.cc
systems/framework/images/cache_doxygen_trackers.dot
systems/framework/test/dependency_tracker_test.cc
systems/framework/test/leaf_context_test.cc

Relates #9171.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11271)

framework: Add conservative cache dependency on z

---

automotive/maliput_railcar.cc
automotive/maliput_railcar.h
examples/pendulum/pendulum_plant.cc
examples/quadrotor/quadrotor_plant.cc
examples/quadrotor/quadrotor_plant.h
examples/scene_graph/bouncing_ball_plant.cc
examples/scene_graph/bouncing_ball_plant.h
examples/scene_graph/dev/bouncing_ball_plant.cc
examples/scene_graph/dev/bouncing_ball_plant.h
examples/scene_graph/dev/solar_system.cc
examples/scene_graph/dev/solar_system.h
examples/scene_graph/solar_system.cc
examples/scene_graph/solar_system.h
systems/controllers/test/linear_model_predictive_controller_test.cc
systems/controllers/test/pid_controlled_system_test.cc
systems/estimators/luenberger_observer.cc
systems/estimators/luenberger_observer.h
systems/framework/leaf_system.h
systems/framework/test/leaf_system_test.cc
systems/primitives/discrete_derivative.cc
systems/primitives/discrete_derivative.h
systems/primitives/discrete_time_delay.cc
systems/primitives/discrete_time_delay.h
systems/primitives/test/discrete_derivative_test.cc
systems/primitives/zero_order_hold.h

Closes #11194.  Relates #11179.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11201)

framework: Use LeafOutputPort declared feedthrough

---

automotive/maliput/api/test_utilities/rules_test_utilities.h
automotive/maliput/base/phase_ring_book_loader.cc
automotive/maliput/base/test/phase_ring_book_loader_test.cc
automotive/maliput/multilane/2x2_intersection.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11268)

Adds next phases to phase_ring_book_loader

---

examples/kuka_iiwa_arm/BUILD.bazel
examples/kuka_iiwa_arm/iiwa_controller.cc
examples/manipulation_station/manipulation_station_hardware_interface.cc
lcm/drake_lcm_interface.cc
lcm/drake_lcm_interface.h
lcm/test/drake_lcm_interface_test.cc

A portion of #11281.  Relates #10981 and #10714.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11274)

iiwa_controller: Stop using lcm_driven_loop

---

bindings/pydrake/systems/test/trajectory_optimization_test.py
bindings/pydrake/systems/trajectory_optimization_py.cc
systems/trajectory_optimization/BUILD.bazel
systems/trajectory_optimization/direct_transcription.cc
systems/trajectory_optimization/direct_transcription.h
systems/trajectory_optimization/test/direct_transcription_test.cc

Related to #11089 and #6858
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11264)

Add support for continuous time systems to DirectTranscription

---

math/BUILD.bazel
math/compute_numerical_gradient.h
math/test/compute_numerical_gradient_test.cc

Resolves #11267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11282)

compute numerical gradient

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11293)

add bindings for getting the actuation matrix from mbp

---

systems/controllers/linear_model_predictive_controller.h
systems/trajectory_optimization/test/direct_transcription_test.cc

Resolves #11286
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11314)

doc: Use `\sum` instead of incorrect control sequence `\Sum`

---

solvers/constraint.cc
solvers/constraint.h
solvers/gurobi_solver.cc
solvers/mosek_solver.cc
solvers/scs_solver.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11289)

LorentzCone and RotatedLorentzCone stores sparse A.

---

automotive/maliput/api/intersection.h
automotive/maliput/api/test/mock.cc
automotive/maliput/base/intersection.h

Also moves some TODO comments to parent class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11311)

Moves Intersection::SetPhase() into parent class

---

bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/custom_test.py
systems/framework/leaf_system.cc
systems/framework/leaf_system.h

Closes #11297.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11298)

systems: Deprecate DoHasDirectFeedthrough

---

automotive/maliput/api/BUILD.bazel
automotive/maliput/api/intersection_book.h
automotive/maliput/base/BUILD.bazel
automotive/maliput/base/intersection_book.cc
automotive/maliput/base/intersection_book.h
automotive/maliput/base/test/intersection_book_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11312)

Adds IntersectionBook

---

automotive/maliput/base/BUILD.bazel
automotive/maliput/base/intersection_book_loader.cc
automotive/maliput/base/intersection_book_loader.h
automotive/maliput/base/test/intersection_book_loader_test.cc
automotive/maliput/multilane/2x2_intersection.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11316)

Adds IntersectionBook Loader

---

bindings/pydrake/attic/multibody/rigid_body_tree_py.cc
third_party/com_github_pybind_pybind11/mkdoc.py
tools/workspace/pybind11/test/sample_header.h
tools/workspace/pybind11/test/sample_header_documentation.expected.h

Closes #11324.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11325)

mkdoc: Don't discard docs of deprecated overloads

---

multibody/optimization/BUILD.bazel
tools/install/libdrake/build_components.bzl

(Add missing multibody/optimization pacakge library, first.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11328)

install: Run build_components_refresh

---

bindings/pydrake/attic/multibody/test/rigid_body_tree_test.py
bindings/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis.py
bindings/pydrake/systems/test/trajectory_optimization_test.py
bindings/pydrake/systems/trajectory_optimization_py.cc
examples/pendulum/Pendulum.urdf
examples/pendulum/print_symbolic_dynamics.cc
systems/trajectory_optimization/BUILD.bazel
systems/trajectory_optimization/direct_transcription.cc
systems/trajectory_optimization/direct_transcription.h
systems/trajectory_optimization/test/direct_transcription_test.cc

* Updates DirectTranscription to support multiple inputs (e.g., to support MBP).
* Adds PendulumPlant and MBP direct transcription pendulup swingup examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11089)

Updates DirectTranscription to support multiple inputs.

---

automotive/maliput/api/test_utilities/rules_test_utilities.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11332)

Applies clang-format to rules_test_utilities.h

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
examples/kuka_iiwa_arm/controlled_kuka/controlled_kuka_multibody_demo.cc
examples/manipulation_station/manipulation_station.cc
examples/multibody/acrobot/run_lqr.cc
manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/test/applied_generalized_force_test.cc
multibody/plant/test/multibody_plant_test.cc

Resolves #11315.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11323)

Deprecate MBP::get_continuous_state_output_port()

---

systems/analysis/BUILD.bazel
systems/analysis/integrator_base.h
systems/analysis/test/explicit_euler_integrator_test.cc
systems/analysis/test/implicit_euler_integrator_test.cc
systems/analysis/test/runge_kutta2_integrator_test.cc
systems/analysis/test/runge_kutta3_integrator_test.cc
systems/analysis/test_utilities/explicit_error_controlled_integrator_test.h

to throw on failure to step.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11338)

Converted IntegrateWithFixedStepToTime(.) to return false rather than

---

common/find_resource.cc
common/test/resource_tool_installed_test.py

Do not fail entirely, since either the "Bazel runfiles" or the "Drake CMake installation directory" is likely to still work, and its fair for users to assume that malformed environment variables should be ignored.
Amends #11261.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11336)

find_resource: When DRAKE_RESOURCE_ROOT is invalid, only warn

---

multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/test/multibody_plant_test.cc
multibody/tree/multibody_tree-inl.h
multibody/tree/multibody_tree.h

Hotfix for #11257
@amcastro-tri I have to jet; if you can fix the compilation error and push it here, that'd be totes awesome. Otherwise, I can fix it later.
Closes #11343.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11344)

mbp: Ensure that all API entry points for adding joints registers topology

---

bindings/pydrake/systems/test/general_test.py
bindings/pydrake/test/math_overloads_test_utilities.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11352)

fix a few typos and remove a print to stdout in python bindings

---

bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/general_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11354)

pybind FixInputPortsFrom

---

tools/workspace/fcl/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11355)

workspace: Update fcl to latest commit

---

systems/primitives/BUILD.bazel
systems/primitives/port_switch.cc
systems/primitives/port_switch.h
systems/primitives/test/port_switch_test.cc

Resolves #11287
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11290)

Adds primitive PortSwitch system

---

bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/test/general_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11353)

pybind Context::SetTimeStateAndParametersFrom

---

doc/clion.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11329)

Nuke macOS instructions for setting up CLion that break the build

---

doc/developers.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11357)

Update support matrix with full Mojave support

---

systems/primitives/BUILD.bazel
systems/primitives/signal_logger.cc
systems/primitives/signal_logger.h
systems/primitives/test/signal_logger_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11340)

signal_logger: Support scalar conversion

---

systems/analysis/implicit_euler_integrator-inl.h
systems/analysis/implicit_euler_integrator.h
systems/analysis/implicit_integrator.h

Toward reuse with the in-review Radau3 integrator.
Improved the documentation on the underlying Newton-Raphson process too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11333)

Refactors code from ImplicitEulerIntegrator into ImplicitIntegrator.

---

doc/developers.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11366)

Fix formatting of support matrix

---

common/find_runfiles.cc

Closes #11368.  Broken in #11261.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11369)

runfiles: Fix argv0 handling on macOS

---

tools/workspace/pybind11/BUILD.bazel

Relates https://github.com/bazelbuild/bazel/issues/7308.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11367)

Migrate to new Bazel Python version API

---

multibody/parsing/package_map.cc
multibody/parsing/package_map.h
multibody/parsing/test/package_map_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11364)

multibody/parsing: Support direct add of package.xml

---

geometry/BUILD.bazel
geometry/geometry_state.h
geometry/proximity/BUILD.bazel
geometry/proximity/test/contact_surface_test.cc
geometry/proximity_engine.cc
geometry/proximity_engine.h
geometry/query_object.cc
geometry/query_object.h
geometry/query_results/BUILD.bazel
geometry/query_results/contact_surface.cc
geometry/query_results/contact_surface.h
geometry/query_results/mesh_field.cc
geometry/query_results/mesh_field.h
geometry/query_results/mesh_field_linear.cc
geometry/query_results/mesh_field_linear.h
geometry/query_results/surface_mesh.cc
geometry/query_results/surface_mesh.h
geometry/test/query_object_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11034)

geometry: ContactSurface API.

---

solvers/constraint.cc
solvers/constraint.h
solvers/snopt_solver.cc
solvers/snopt_solver_f2c.cc
solvers/test/constraint_test.cc
solvers/test/nonlinear_program_test.cc
solvers/test/optimization_examples.cc
solvers/test/optimization_examples.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11345)

solvers::Constraint accept sparsity pattern. Snopt uses this sparsity pattern

---

geometry/query_results/surface_mesh.h

Closes #11387. FYI @DamrongGuoy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11388)

Fix implicit instantiation of undefined template std::array from libc++

---

bindings/pydrake/multibody/test/plant_test.py

Relates #11193.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11393)

pydrake: Remove unused imports

---

multibody/parsing/detail_urdf_geometry.cc
multibody/parsing/test/detail_scene_graph_test.cc
multibody/parsing/test/detail_sdf_parser_test.cc
multibody/parsing/test/detail_tinyxml_test.cc
multibody/parsing/test/detail_urdf_geometry_test.cc

Relates #11193.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11390)

multibody/parsing: Stop using Isometry3

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/attic/multibody/BUILD.bazel
bindings/pydrake/attic/multibody/rigid_body_plant_py.cc
bindings/pydrake/automotive_py.cc
bindings/pydrake/common/BUILD.bazel
bindings/pydrake/common/default_scalars_pybind.h
bindings/pydrake/common/value_pybind.h
bindings/pydrake/geometry_py.cc
bindings/pydrake/multibody/BUILD.bazel
bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/perception_py.cc
bindings/pydrake/pydrake_pybind.h
bindings/pydrake/solvers/BUILD.bazel
bindings/pydrake/solvers/osqp_py.cc
bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/analysis_py.cc
bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/framework_py_values.cc
bindings/pydrake/systems/lcm_py.cc
bindings/pydrake/systems/primitives_py.cc
bindings/pydrake/systems/rendering_py.cc
bindings/pydrake/systems/sensors_py.cc
bindings/pydrake/systems/systems_pybind.h
bindings/pydrake/systems/test/test_util_py.cc

Towards #11382 (#11240)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11383)

py systems: Split and hoist general header utilities

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/gurobi_solver_test.cc
solvers/test/mosek_solver_test.cc
solvers/test/scs_solver_test.cc
solvers/test/second_order_cone_program_examples.cc
solvers/test/second_order_cone_program_examples.h

Resolves #11372
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11381)

Mathprog maximizes geometric mean

---

tools/workspace/cmake_configure_file.bzl
tools/workspace/lcm/lcm.bzl

Relates bazelbuild/bazel#7347.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11399)

Do not return struct from starlark rule implementation functions

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/common/BUILD.bazel
bindings/pydrake/common/test/numpy_compare_test.py
bindings/pydrake/common/test_utilities/BUILD.bazel
bindings/pydrake/common/test_utilities/numpy_compare.py
bindings/pydrake/pydrake_doxygen.h
bindings/pydrake/test/algebra_test_util.py
bindings/pydrake/test/autodiffutils_test.py
bindings/pydrake/test/symbolic_test.py

Towards #11385
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11386)

py: Add `numpy_compare` testing utilities

---

geometry/proximity/distance_to_shape.h
geometry/proximity/test/distance_sphere_to_shape_test.cc

1. A geometry pair that was filtered was still be analyzed for scalar
support. By definition, if the pair isn't considered, it doesn't matter
if it's supported or not.
- includes test supporting this principle.
2. Fallback shape-to-shape computation for double was _not_ setting
geometry ids. Now it does (with test to support).
3. Incidental clean up along the way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11408)

Correct two issues in shape-shape signed distance

---

solvers/test/scs_solver_test.cc
tools/dynamic_analysis/valgrind.supp

Resolves #11405
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11407)

increase the tolerance on a scs_solver_test a little bit to make it pass on Mac CI.

---

bindings/pydrake/common/BUILD.bazel
bindings/pydrake/common/eigen_geometry_py.cc
bindings/pydrake/common/test/eigen_geometry_test.py
bindings/pydrake/common/test/numpy_compare_test.py
bindings/pydrake/common/test_utilities/numpy_compare.py

Addresses checkbox in #11240
~Will require clean-up to happen first~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11382)

py eigen: Expose default scalars

---

automotive/maliput/api/road_network.cc
automotive/maliput/api/road_network.h
automotive/maliput/api/test/mock.cc
automotive/maliput/api/test/mock.h
automotive/maliput/api/test/road_network_test.cc

Resolves 11412. Removes vectors of SpeedLimitRule and DirectionUsageRule.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11413)

Adds IntersectionBook to RoadNetwork.

---

bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/test/general_test.py

(needed for implementing unrestricted updates from python)
High priority as it is needed for a 6.832 final project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11416)

add missing bindings for State<T> abstract values. 

---

bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/custom_test.py
bindings/pydrake/systems/test/general_test.py
systems/framework/system_base.h

Closes #11423.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11426)

pydrake: Bind DependencyTicket accessors

---

automotive/maliput/api/road_network.cc
automotive/maliput/api/road_network.h
automotive/maliput/api/test/mock.cc
automotive/maliput/api/test/road_network_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11422)

Corrects const oversight in IntersectionBook.

---

automotive/maliput/utility/BUILD.bazel
automotive/maliput/utility/generate_string.cc
automotive/maliput/utility/generate_string.h
automotive/maliput/utility/test/generate_string_test.cc

This facilitates offline inspection of a RoadGeometry object.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11397)

Adds GenerateString(RoadGeometry)

---

multibody/benchmarks/free_body/free_body.cc
multibody/benchmarks/free_body/free_body.h
multibody/benchmarks/free_body/test/multibody_plant_free_body_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11348)

Improve free body test for Evan's new integrator

---

bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/custom_test.py
bindings/pydrake/systems/test/general_test.py

needed for python direct transcription hacking
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11440)

add bindings for CalcDiscreteVariableUpdates.

---

automotive/maliput/base/intersection_book_loader.cc
automotive/maliput/base/intersection_book_loader.h
automotive/maliput/base/test/intersection_book_loader_test.cc

Resolves #11437.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11438)

Updates intersection_book_loader to add PhaseRings to PhaseProvider

---

automotive/maliput/base/intersection_book_loader.cc
automotive/maliput/base/phase_ring_book_loader.cc
automotive/maliput/base/road_rulebook_loader.cc
automotive/maliput/base/traffic_light_book_loader.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11439)

Modifies loaders to use DRAKE_THROW_UNLESS

---

multibody/inverse_kinematics/minimum_distance_constraint.h

This file had multiple styles of API comments. I'd like to standardize them here to reduce noise in the PR that makes functional changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11442)

Standardize comment style in minimum_distance_constraint.h.

---

bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/custom_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11447)

add bindings for AllocateDiscreteVariables

---

bindings/pydrake/geometry_py.cc
geometry/proximity/distance_to_point.h
geometry/proximity/distance_to_shape.h
geometry/proximity/test/distance_sphere_to_shape_test.cc
geometry/proximity/test/distance_to_point_test.cc
geometry/query_results/signed_distance_pair.h
geometry/query_results/signed_distance_to_point.h

Fix #10747.  Most of the work was done by @SeanCurtis-TRI as a part of #11379 already.  I just added `is_nhat_BA_W_unique` to `SignedDistancePair` and set up unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11435)

[geometry] Return normal for touching sphere-{sphere, box, cylinder}.

---

geometry/query_results/contact_surface.h
geometry/query_results/surface_mesh.h

Improvement regarding `const` functions and `const T&` return type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11456)

[geometry] minor improvement to ContactSurface API.

---

manipulation/planner/differential_inverse_kinematics.cc
multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h
multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_model.cc
multibody/math/BUILD.bazel
multibody/math/spatial_vector.h
multibody/math/test/spatial_algebra_test.cc
multibody/plant/test/external_forces_test.cc
multibody/plant/test/frame_kinematics_test.cc
multibody/plant/test/inclined_plane_test.cc
multibody/plant/test/kuka_iiwa_model_tests.h
multibody/plant/test/multibody_plant_jacobians_test.cc
multibody/plant/test/multibody_plant_test.cc
multibody/tree/body.h
multibody/tree/body_node.h
multibody/tree/frame.h
multibody/tree/test/multibody_tree_test.cc

This PR helps address part of issue #11193.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11414)

Removes more Isometry3. Adds operator*(RotationMatrix, SpatialVector).

---

CMakeLists.txt
attic/multibody/approximate_ik.cc
cmake/modules/FindGurobi.cmake
doc/bazel.rst
solvers/gurobi_solver.cc
solvers/gurobi_solver.h
solvers/solver_options.h
solvers/test/mixed_integer_optimization_test.cc
tools/dynamic_analysis/tsan.supp
tools/workspace/gurobi/package-macos.BUILD.bazel.in
tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in
tools/workspace/gurobi/repository.bzl

Closes #9829.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11269)

Upgrade supported Gurobi version to 8.0.1

---

doc/buildcop.rst

Closes #11225.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11460)

Update buildcop playback about when to restart Mac nightly builds

---

doc/developers.rst
setup/ubuntu/source_distribution/install_prereqs.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11444)

Update to Bazel 0.25.2 recommended

---

geometry/proximity/BUILD.bazel
geometry/proximity/test/volume_mesh_test.cc
geometry/proximity/volume_mesh_field.cc
geometry/proximity/volume_mesh_field.h
geometry/query_results/BUILD.bazel
geometry/query_results/mesh_field_linear.h

Define VolumeMeshField from MeshField and VolumeMesh.  Set up unit tests of VolumeMeshField on top of unit tests of VolumeMesh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11462)

[geometry] VolumeMeshField for hydroelastic contact model.

---

manipulation/util/geometry_inspector.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11459)

add meshcat support to geometry inspector

---

tools/workspace/drake_visualizer/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11465)

Update drake-visualizer binary for Mac

---

multibody/plant/BUILD.bazel
multibody/plant/multibody_plant.cc
multibody/plant/test/externally_applied_spatial_force_test.cc

Resolves #11410.
Bug fix for MBP with discrete updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11415)

Adds missing call to AddAppliedExternalSpatialForces().

---

examples/atlas/atlas_run_dynamics.cc
multibody/plant/BUILD.bazel
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/test/multibody_plant_introspection_test.cc
multibody/plant/test/multibody_plant_test.cc
multibody/tree/body.h
multibody/tree/mobilizer.h
multibody/tree/multibody_tree-inl.h
multibody/tree/multibody_tree_topology.h
multibody/tree/quaternion_floating_mobilizer.h
multibody/tree/space_xyz_mobilizer.h
multibody/tree/test/free_rotating_body_plant.h
multibody/tree/test/free_rotating_body_test.cc

Resolves the first three items in #10736.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11464)

Introduces API for the introspection of floating bodies.

---

CMakeLists.txt
WORKSPACE

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11479)

Require at least bazel 0.25

---

bindings/pydrake/examples/test/compass_gait_test.py
examples/compass_gait/compass_gait.cc
examples/compass_gait/compass_gait.h
examples/compass_gait/simulate.cc
examples/compass_gait/test/compass_gait_test.cc

(a much requested feature for 6.832 final projects)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11472)

adds hip torque to the compass gait.

---

doc/clion.rst
tools/clion/aspect.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11483)

Add flag_hack_label to semantics struct in clion environment and update documentation

---

geometry/proximity/test/contact_surface_test.cc
geometry/query_results/contact_surface.h
geometry/query_results/mesh_field_linear.h

We need a copy constructor of ContactSurface for visualization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11481)

[geometry] Added copy constructor of ContactSurface.

---

multibody/plant/multibody_plant.h
multibody/tree/multibody_tree.cc
multibody/tree/multibody_tree.h
multibody/tree/test/multibody_tree_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11471)

Deprecate CalcRelativeFrameGeometricJacobian for CalcJacobianSpatialVelocity

---

examples/compass_gait/compass_gait.cc
examples/compass_gait/test/compass_gait_test.cc

related to #11496 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11498)

declare compass gait outputs as non direct feedthrough

---

multibody/inverse_kinematics/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11506)

inverse_kinematics: Don't depend on particular solvers

---

systems/framework/vector_system.h

Closes #11496.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11500)

framework: Improve VectorSystem feedthrough documentation

---

bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/test/general_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11510)

Add remaining bindings to Context

---

solvers/BUILD.bazel
solvers/csdp_solver.cc
solvers/csdp_solver.h
solvers/csdp_solver_common.cc
solvers/csdp_solver_internal.h
solvers/no_csdp.cc
tools/BUILD.bazel
tools/workspace/BUILD.bazel
tools/workspace/csdp/BUILD.bazel
tools/workspace/csdp/package.BUILD.bazel
tools/workspace/csdp/repository.bzl
tools/workspace/default.bzl
tools/workspace/github.bzl

This PR should be merged before #11489
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11504)

Bring in CSDP build file

---

automotive/maliput/dragway/test_utilities/BUILD.bazel
automotive/maliput/dragway/test_utilities/fixtures.cc
automotive/maliput/dragway/test_utilities/fixtures.h
automotive/maliput/multilane/branch_and_merge.yaml
automotive/maliput/multilane/dual_non_intersecting_lanes.yaml
automotive/maliput/multilane/long_start_and_end_lanes.yaml
automotive/maliput/multilane/loop.yaml
automotive/maliput/multilane/multi_branch.yaml
automotive/maliput/multilane/test_utilities/BUILD.bazel
automotive/maliput/multilane/test_utilities/fixtures.cc
automotive/maliput/multilane/test_utilities/fixtures.h
automotive/maliput/routing/BUILD.bazel
automotive/maliput/routing/find_lane_sequences.cc
automotive/maliput/routing/find_lane_sequences.h
automotive/maliput/routing/test/find_lane_sequences_test.cc

Useful for finding routes within a RoadGeometry.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11492)

Adds FindLaneSequences()

---

bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/general_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11511)

add python bindings for GetUniquePeriodicDiscreteUpdateAttribute

---

common/BUILD.bazel
common/symbolic_formula.h
common/symbolic_formula_cell.cc
common/symbolic_formula_cell.h
common/test/symbolic_formula_test.cc
solvers/BUILD.bazel

We should avoid physical dependency cycles between package libraries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11512)

common: Do not depend on math

---

bindings/pydrake/autodiffutils_py.cc
bindings/pydrake/test/autodiffutils_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11513)

bind more autodiff utils

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/_autodiffutils_extra.py
bindings/pydrake/autodiffutils_py.cc
bindings/pydrake/test/autodiffutils_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11517)

Add python implementation of initializeAutoDiffTuple

---

multibody/plant/multibody_plant.h
multibody/tree/multibody_tree.cc
multibody/tree/multibody_tree.h
multibody/tree/test/multibody_tree_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11495)

CalcBiasForPointsGeometryJacobianExpressedInWorld() -> CalcBiasForJacobianTranslationalVelocity()

---

multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.cc
multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc
multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_inverse_dynamics_test.cc
multibody/benchmarks/kuka_iiwa_robot/test/kuka_iiwa_robot_kinematics_test.cc
multibody/test_utilities/BUILD.bazel
multibody/test_utilities/spatial_kinematics.h

Relates to #9865, #11193.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11509)

Remove isometry from SpatialKinematicsPVA class.

---

automotive/maliput/routing/BUILD.bazel
automotive/maliput/routing/derive_lane_s_routes.cc
automotive/maliput/routing/derive_lane_s_routes.h
automotive/maliput/routing/test/derive_lane_s_routes_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11514)

Adds DeriveLaneSRoutes()

---

tools/workspace/snopt/package.BUILD.bazel

Running into some strange issue in #11505 so breaking it into two PR's. Toward #11501.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11528)

Do not use BLAS vendored with SNOPT/F2C

---

bindings/pydrake/math_py.cc
bindings/pydrake/systems/framework_py_systems.cc
geometry/geometry_frame.h
math/rigid_transform.h
multibody/plant/multibody_plant.h
multibody/tree/fixed_offset_frame.h
multibody/tree/weld_joint.h
setup/mac/binary_distribution/install_prereqs.sh
systems/framework/leaf_system.h

Obeying the intermediate dates is not an efficient use of our time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11533)

Round up deprecation dates to first of the month

---

.dockerignore
setup/ubuntu/source_distribution/packages-bionic.txt
setup/ubuntu/source_distribution/packages-xenial.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11530)

Various docker-related fixes

---

tools/workspace/snopt/fortran-macos.bzl
tools/workspace/snopt/fortran-ubuntu.bzl
tools/workspace/snopt/package.BUILD.bazel

Closes #11501.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11505)

Do not use BLAS vendored with SNOPT/Fortran

---

attic/multibody/dev/test/global_inverse_kinematics_collision_avoidance_test.cc
attic/multibody/dev/test/global_inverse_kinematics_feasible_posture_test.cc
attic/multibody/dev/test/global_inverse_kinematics_reachable_test.cc
attic/multibody/dev/test/global_inverse_kinematics_test.cc
attic/multibody/dev/test/global_inverse_kinematics_test_util.cc
attic/multibody/dev/test/global_inverse_kinematics_test_util.h
attic/multibody/global_inverse_kinematics.cc
attic/multibody/global_inverse_kinematics.h

_(Jeremy edited to add: Relates to #11532.)_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11547)

switch to new solvers::Solve interface for global IK.

---

setup/mac/source_distribution/requirements.txt
setup/ubuntu/source_distribution/packages-bionic.txt
tools/workspace/BUILD.bazel
tools/workspace/mirror_to_s3.py

Life is slightly easier, more transparent, and improves the bus factor, if the script is in Drake.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11548)

Add script for mirroring source archives to S3

---

attic/manipulation/planner/BUILD.bazel
examples/kinova_jaco_arm/BUILD.bazel
examples/kinova_jaco_arm/jaco_controller.cc
examples/kuka_iiwa_arm/BUILD.bazel
examples/kuka_iiwa_arm/lcm_plan_interpolator.cc
manipulation/planner/BUILD.bazel
manipulation/planner/robot_plan_interpolator.cc
manipulation/planner/robot_plan_interpolator.h
manipulation/planner/test/robot_plan_interpolator_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11556)

Convert RobotPlanInterpolator to MBP

---

bindings/pydrake/manipulation/simple_ui.py

Changes to simple_ui.py were added in #11560
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11561)

Add missing whitespace in simple_ui.py

---

tools/workspace/ignition_math/package.BUILD.bazel
tools/workspace/ignition_math/repository.bzl

(Per monthly review of externals' releases.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11565)

workspace: Update ignition_math to latest release

---

multibody/optimization/BUILD.bazel
multibody/optimization/contact_wrench_evaluator.h
multibody/optimization/static_equilibrium_constraint.cc
multibody/optimization/static_equilibrium_constraint.h
multibody/optimization/static_equilibrium_problem.cc
multibody/optimization/static_friction_cone_complementarity_constraint.cc
multibody/optimization/test/contact_wrench_evaluator_test.cc
multibody/optimization/test/static_equilibrium_constraint_test.cc
multibody/optimization/test/static_friction_cone_complementarity_constraint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11569)

Use SortedPair instead of std::pair in static equilibrium problem

---

attic/manipulation/dev/BUILD.bazel
attic/multibody/BUILD.bazel
attic/multibody/rigid_body_plant/BUILD.bazel
attic/perception/estimators/dev/BUILD.bazel
attic/systems/controllers/qp_inverse_dynamics/BUILD.bazel
attic/systems/estimators/dev/BUILD.bazel
examples/cubic_polynomial/BUILD.bazel
examples/rod2d/BUILD.bazel
manipulation/planner/BUILD.bazel
multibody/optimization/BUILD.bazel
solvers/BUILD.bazel
systems/analysis/BUILD.bazel
systems/controllers/BUILD.bazel
systems/trajectory_optimization/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11568)

solvers: Start the rename transition for bazel labels

---

common/yaml/test/yaml_read_archive_test.cc
common/yaml/yaml_read_archive.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11577)

yaml: Add support for loading std::map<string, Foo>

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11583)

pydrake geometry: Add bindings for FramePoseVector functions

---

bindings/pydrake/common/test/eigen_geometry_test.py

`npc` -> `numpy_compare`
[Towards this.](https://reviewable.io/reviews/robotlocomotion/drake/11563#-LgUu8jH8Ql7g_psUqTm)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11584)

Replace npc with numpy_compare in eigen_geometry_test.py

---

systems/analysis/BUILD.bazel
systems/analysis/bogacki_shampine3_integrator.cc
systems/analysis/bogacki_shampine3_integrator.h
systems/analysis/integrator_base.h
systems/analysis/test/bogacki_shampine3_integrator_test.cc
systems/analysis/test/runge_kutta3_integrator_test.cc

Addresses issue #11453
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11486)

Bogacki-Shampine 3/2 integrator

---

bindings/pydrake/multibody/BUILD.bazel
bindings/pydrake/multibody/math_py.cc
bindings/pydrake/multibody/test/math_test.py

Towards #11240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11590)

py multibody/math : Expose scalars for SpatialAcceleration, SpatialForce and SpatialVelocity

---

multibody/optimization/BUILD.bazel
multibody/optimization/static_friction_cone_complementarity_constraint.cc
multibody/optimization/static_friction_cone_complementarity_constraint.h
multibody/optimization/static_friction_cone_constraint.cc
multibody/optimization/static_friction_cone_constraint.h
multibody/optimization/test/static_friction_cone_constraint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11582)

Add StaticFrictionConeConstraint.

---

multibody/optimization/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11601)

static_friction_cone_constraint should link to mathematical_program_lite rather than mathematical_program

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11602)

Add python binding for symbolic::Polynomial::EvalPartial

---

bindings/pydrake/common/test/numpy_compare_test.py
bindings/pydrake/test/autodiffutils_test.py
bindings/pydrake/test/symbolic_test.py

Latent clean up - sorry for delay! (encountered while working with #11604)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11605)

numpy_compare: Expand all remaining usages of `npc`

---

bindings/pydrake/solvers/BUILD.bazel
bindings/pydrake/solvers/ipopt_py.cc
bindings/pydrake/solvers/test/ipopt_solver_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11613)

Add python binding IpoptSolverDetails.

---

solvers/sdpa_free_format.cc
solvers/sdpa_free_format.h
solvers/test/csdp_test_examples.cc
solvers/test/csdp_test_examples.h
solvers/test/sdpa_free_format_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11594)

SdpaFreeFormat parses second order cones.

---

systems/primitives/port_switch.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11624)

primitives: Clarify model vs dummy value in PortSwitch

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py

Towards #11240
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11614)

py geometry : Expose scalars in geometry

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/mathematical_program_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11606)

Add equality constraint between two polynomials.

---

bindings/pydrake/solvers/BUILD.bazel
bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/scs_py.cc
bindings/pydrake/solvers/test/scs_solver_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11626)

Add python binding for SCS

---

bindings/pydrake/solvers/BUILD.bazel
bindings/pydrake/solvers/snopt_py.cc
bindings/pydrake/solvers/test/snopt_solver_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11617)

Add SnoptSolverDetails python binding.

---

tools/workspace/dreal/repository.bzl
tools/workspace/dreal/versions.bzl

EDIT(eric): Resolves #11635
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11635)

Update dReal and ibex-lib

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/automotive_py.cc
bindings/pydrake/maliput/BUILD.bazel
bindings/pydrake/maliput/api_py.cc
bindings/pydrake/maliput/dragway_py.cc
bindings/pydrake/maliput/test/maliput_test.py
bindings/pydrake/test/automotive_test.py

Towards #11603.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11637)

automotive: Add deprecation warnings to pydrake ctors

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11630)

bind more functions for SolverOptions

---

bindings/pydrake/solvers/BUILD.bazel
bindings/pydrake/solvers/nlopt_py.cc
bindings/pydrake/solvers/test/nlopt_solver_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11639)

add python binding for nlopt

---

tools/workspace/numpy/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11636)

Fix typo in error message in numpy/repository.bzl 

---

multibody/plant/multibody_plant.h

Resolves #11640
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11641)

multibody plant: Ensure that size is checked for state mutation

---

setup/mac/binary_distribution/install_prereqs.sh
setup/mac/source_distribution/install_prereqs.sh

Relates #11631. FYI @RussTedrake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11646)

Scream loudly when pip2 and pip3 are not installed on Mac

---

geometry/query_results/signed_distance_pair.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11652)

Updates SignedDistancePair documentation.

---

common/symbolic_polynomial.cc
common/symbolic_polynomial.h
common/test/symbolic_polynomial_test.cc

Fix #11023
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11643)

Use std::map for symbolic::Polynomial::MapType

---

tools/workspace/pybind11/repository.bzl

Closes #11638.  Incorporates RobotLocomotion/pybind11#30.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11650)

pybind11: Update to latest master

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py

@EricCousineau-TRI, mind taking a look?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11654)

[Py]Bind MBP::AddModelInstance and AddRigidBody with model instance

---

solvers/BUILD.bazel
solvers/sdpa_free_format.cc
solvers/sdpa_free_format.h
solvers/test/sdpa_free_format_test.cc

This text file can be used by all the open-sourced SDP solvers I know of (CSDP, DSDP, SDPA, SeDeMi, SDPT3).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11618)

Write SDPA to a text file.

---

tools/bazel.rc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11662)

Set --incompatible_use_python_toolchains=false

---

third_party/com_github_google_protobuf/README.md
third_party/com_github_google_protobuf/protobuf.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11656)

Update vendored files from protobuf

---

solvers/BUILD.bazel

Relates #11657.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11666)

Do not run ThreadSanitizer on snopt_solver_test

---

multibody/tree/weld_joint.cc
multibody/tree/weld_joint.h

Resolves #11673
Supersedes #11672
\cc @ggould-tri @jwnimmer-tri
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11674)

multibody: Ensure WeldJoint is instantiated for Expression

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
multibody/optimization/test/optimization_with_contact_utilities.cc
multibody/parsing/detail_sdf_parser.cc
multibody/parsing/detail_urdf_parser.cc
multibody/parsing/test/common_parser_test.cc
multibody/parsing/test/detail_urdf_parser_test.cc
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/test/multibody_plant_test.cc
systems/rendering/test/multibody_position_to_geometry_pose_test.cc

Closes #11663.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11664)

multibody: Officially deprecate vestigial scene_graph arguments

---

multibody/tree/weld_mobilizer.cc
multibody/tree/weld_mobilizer.h

Inspired by #11674.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11675)

multibody: Add missing Expression support for WeldMobilizer

---

geometry/proximity_engine.cc
tools/workspace/tinyobjloader/double_precision.patch
tools/workspace/tinyobjloader/repository.bzl

Closes #11677.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11681)

workspace: Compile tinyobjloader in double-precision mode

---

multibody/inverse_kinematics/BUILD.bazel
multibody/optimization/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11687)

multibody: Remove dead loads from BUILD.bazel

---

manipulation/planner/robot_plan_interpolator.cc
manipulation/planner/robot_plan_interpolator.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11690)

adds @system doxygen to RobotPlanInterpolator and adds port names

---

tools/lint/BUILD.bazel
tools/lint/buildifier.py
tools/lint/drakelint.py
tools/lint/test/buildifier_test.py

Closes #11661.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11693)

lint: Improve fix tool advice messages

---

tools/workspace/osqp/package.BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11682)

Always link OSQP to avoid finding symbols from other libraries

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/lcm_py.cc
bindings/pydrake/systems/primitives_py.cc
tools/workspace/pybind11/repository.bzl

Closes #9398
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11409)

Remove py_reference from a few casts

---

multibody/inverse_kinematics/BUILD.bazel
multibody/inverse_kinematics/angle_between_vectors_constraint.cc
multibody/inverse_kinematics/angle_between_vectors_constraint.h
multibody/inverse_kinematics/gaze_target_constraint.cc
multibody/inverse_kinematics/gaze_target_constraint.h
multibody/inverse_kinematics/kinematic_constraint_utilities.cc
multibody/inverse_kinematics/kinematic_constraint_utilities.h
multibody/inverse_kinematics/position_constraint.cc
multibody/inverse_kinematics/position_constraint.h
multibody/inverse_kinematics/test/angle_between_vectors_constraint_test.cc
multibody/inverse_kinematics/test/gaze_target_constraint_test.cc
multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.h
multibody/inverse_kinematics/test/position_constraint_test.cc

Rewrite PositionConstraint, AngleBetweenVectorsConstraint and GazeTargetConstraint, such that these constraints can be constructed from MBP<ADS>.
There will be another PR to rewrite OrientationConstraint, MinimumDistanceConstraint and DistanceConstraint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11669)

Kinematic constraint constructed from MultibodyPlant<AutoDiffXd>

---

examples/kuka_iiwa_arm/kuka_simulation.cc
examples/schunk_wsg/test/schunk_wsg_lift_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11712)

Resolve some memcheck issues

---

multibody/inverse_kinematics/test/position_constraint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11715)

relax the tolerance on PositionConstraintTest to pass the nightly build.

---

systems/framework/diagram_builder.cc
systems/framework/leaf_system.h
systems/framework/system_base.h
systems/framework/system_scalar_conversion_doxygen.h

Closes #11179.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11684)

framework: Improve direct-feedthrough documentation

---

solvers/BUILD.bazel
solvers/mathematical_program_result.h
solvers/solver_base.cc
solvers/test/mathematical_program_result_test.cc

Fixes #11699
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11707)

Set the x_val and optimal cost to nan by default in MathematicalProgramResult

---

bindings/pydrake/common/cpp_template.py
bindings/pydrake/common/test/cpp_template_pybind_test.cc
bindings/pydrake/common/test/cpp_template_test.py
bindings/pydrake/common/test/eigen_geometry_test.py

Add simple test for Eigen geometry
Resolves #11667
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11705)

py cpp_template: Permit pseudo-template arugment deduction

---

doc/bazel.rst
tools/macos.bazelrc
tools/ubuntu-bionic.bazelrc
tools/ubuntu-xenial.bazelrc

Towards #10606
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11728)

tools: Update bazelrc's to add explicit `--config=python2`

---

bindings/pydrake/common/default_scalars_pybind.h
bindings/pydrake/geometry_py.cc
bindings/pydrake/math_py.cc
bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/test/math_test.py

Closes #11575
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11717)

pydrake: Handle `py_reference_internal` for `ndarray[object]` cases

---

doc/developers.rst

Towards #10606
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11729)

doc: Add links to platform support roadmaps

---

solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/mathematical_program_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11726)

Overload MathematicalProgram::NewNonnegativePolynomial

---

doc/python_bindings.rst

Towards #10606
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11731)

doc python: Emphasize more on Python 3

---

bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/BUILD.bazel
solvers/choose_best_solver.cc
solvers/csdp_solver.cc
solvers/csdp_solver.h
solvers/csdp_solver_common.cc
solvers/csdp_solver_internal.cc
solvers/csdp_solver_internal.h
solvers/mathematical_program_doxygen.h
solvers/solver_type.h
solvers/solver_type_converter.cc
solvers/test/choose_best_solver_test.cc
solvers/test/csdp_solver_internal_test.cc
solvers/test/csdp_solver_test.cc
solvers/test/solver_type_converter_test.cc

Resolves #9922
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11711)

Fully support CSDP solver

---

solvers/csdp_solver.cc
solvers/test/csdp_solver_test.cc

To address #11749
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11751)

Fix CI failure from csdp_solver_test

---

multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.cc
multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h
multibody/benchmarks/kuka_iiwa_robot/MG/test/MG_kuka_iiwa_robot_test.cc
multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h

Inspired by #7252's first post.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11696)

benchmarks: Remove using-statements from headers

---

tools/workspace/fcl/repository.bzl
tools/workspace/lcm/repository.bzl
tools/workspace/optitrack_driver/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11759)

workspace: Update externals to new releases

---

solvers/test/sos_constraint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11761)

Increase tolerance for SosConstraintTest.AddSosConstraintUnivariate2

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py
geometry/geometry_visualization.cc
geometry/geometry_visualization.h
geometry/scene_graph.h
geometry/test/geometry_visualization_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11763)

add a role param to ConnectDrakeVisualizer.

---

math/rigid_transform.h
math/rotation_matrix.h
math/test/rotation_matrix_test.cc
multibody/tree/multibody_tree.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11766)

Improve RotationMatrix::operator* to handle generic 3 x n matrices

---

common/BUILD.bazel
common/symbolic_expression.cc
common/symbolic_expression.h
common/symbolic_expression_cell.cc
common/symbolic_expression_cell.h
common/test/symbolic_expansion_test.cc

Close #11741
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11747)

Add is_expanded and use it in Expand() to catch redundant calls

---

geometry/proximity/BUILD.bazel
geometry/proximity/mesh_field.h
geometry/proximity/mesh_field_linear.h
geometry/proximity/mesh_intersection.cc
geometry/proximity/mesh_intersection.h
geometry/proximity/surface_mesh.h
geometry/proximity/test/contact_surface_test.cc
geometry/proximity/test/mesh_field_test.cc
geometry/proximity/test/mesh_intersection_test.cc
geometry/proximity/test/surface_mesh_test.cc
geometry/proximity/test/volume_mesh_test.cc
geometry/proximity/volume_mesh.h
geometry/proximity/volume_mesh_field.h
geometry/query_results/BUILD.bazel
geometry/query_results/contact_surface.h

Solve #11154 for soft geometry v.s. rigid geometry.  The other case, soft geometry v.s. soft geometry, will be in the future PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11612)

[geometry] Compute ContactSurface between soft and rigid geometries.

---

multibody/tree/rotational_inertia.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11773)

Provide rigorous mathematical definition of inertia tensor/dyadic/matrix (address issue #5765)

---

tools/install/libdrake/drake.cps

Closes #11771.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11774)

Remove drake_RESOURCE_ROOT from drake.cps

---

solvers/BUILD.bazel
solvers/mosek_solver.cc
solvers/mosek_solver_common.cc
solvers/test/mosek_solver_test.cc

Resolves #11101
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11755)

Mosek supports exponential cone.

---

solvers/test/snopt_solver_test.cc

Resolves #11781
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11782)

snopt: Completely disable test use of "Print file" under ASan

---

examples/schunk_wsg/BUILD.bazel
systems/analysis/BUILD.bazel
tools/skylark/drake_cc.bzl

Relates #11760.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11778)

Add tags disabling dynamic analysis when disable_in_compilation_mode_dbg is set

---

multibody/tree/rotational_inertia.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11787)

Connect inertia dyadic to angular momentum, kinetic energy, moment of forces.

---

solvers/constraint.cc
solvers/constraint.h
solvers/evaluator_base.cc
solvers/evaluator_base.h
solvers/test/constraint_test.cc
solvers/test/evaluator_base_test.cc

Resolves #6808
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11776)

Move sparsity pattern from constraint to evaluator.

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/examples/acrobot_py.cc
bindings/pydrake/examples/test/acrobot_test.py
examples/acrobot/BUILD.bazel
examples/acrobot/spong_controller.cc
examples/acrobot/spong_controller.h
examples/acrobot/spong_controller_params.named_vector
tools/install/libdrake/build_components.bzl

Exposes the parameters of the Spong swing up controller.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11792)

Spong parameters

---

solvers/fbstab/BUILD.bazel
solvers/fbstab/components/BUILD.bazel
solvers/fbstab/components/dense_data.cc
solvers/fbstab/components/dense_data.h
solvers/fbstab/components/dense_variable.cc
solvers/fbstab/components/dense_variable.h
solvers/fbstab/components/test/dense_component_unit_tests.cc
solvers/fbstab/components/test/dense_component_unit_tests.h

First files for an implementation of the FBstab quadratic programming solver (https://arxiv.org/pdf/1901.04046.pdf)
This commit contains classes for storing and manipulating problem data and primal-dual variables.
+@frankpermenter for feature review, please
+@soonho-tri for platform review, please
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11775)

Fbstab Dense data and variables classes

---

geometry/geometry_state.cc
geometry/test/geometry_state_test.cc

Each modification of properties would duplicate a geometry *in the engine*. The test has been extended to detect this and the problem has been alleviated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11799)

Fix error in modifying ProximityProperties

---

doc/developers.rst
setup/ubuntu/source_distribution/install_prereqs.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11794)

Update recommended Bazel version to 0.28

---

attic/multibody/rigid_body_plant/contact_force.h
attic/multibody/rigid_body_plant/test/compliant_contact_model_test.cc
attic/multibody/rigid_body_plant/test/compute_contact_result_test.cc
attic/multibody/rigid_body_plant/test/contact_force_formula_test.cc
attic/multibody/rigid_body_plant/test/contact_resultant_force_test.cc
common/eigen_types.h
examples/valkyrie/robot_state_encoder.cc
examples/valkyrie/robot_state_encoder.h
examples/valkyrie/test/robot_state_encoder_decoder_test.cc
multibody/triangle_quadrature/BUILD.bazel
multibody/triangle_quadrature/triangle_quadrature.cc

Resolves #6731
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11806)

Deprecate `drake::SpatialForce`

---

examples/double_pendulum/sdf_helpers.cc
examples/scene_graph/dev/solar_system.cc
examples/scene_graph/solar_system.cc
examples/valkyrie/robot_state_encoder.cc
examples/valkyrie/test/robot_state_encoder_decoder_test.cc
manipulation/planner/differential_inverse_kinematics.cc
multibody/inverse_kinematics/angle_between_vectors_constraint.cc
multibody/inverse_kinematics/orientation_constraint.cc
multibody/parsing/detail_sdf_parser.cc
multibody/parsing/test/detail_scene_graph_test.cc
multibody/plant/test/frame_kinematics_test.cc
multibody/plant/test/multibody_plant_jacobians_test.cc
multibody/tree/frame.h
multibody/tree/mobilizer.h
multibody/tree/rigid_body.h
multibody/tree/uniform_gravity_field_element.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11808)

Remove RotationMatrix.linear(), change Matrix3 to RotationMatrix, lose some Isometry."

---

multibody/plant/contact_results.h
multibody/plant/test/box_test.cc

Repairs #11804.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11811)

plant: Repair broken contact_results method

---

multibody/plant/BUILD.bazel
multibody/plant/multibody_plant.h
multibody/plant/test/multibody_plant_com_test.cc
multibody/tree/multibody_tree.cc
multibody/tree/multibody_tree.h

Added function CalcCenterOfMassPosition to compute Center of Mass position for MultibodyPlant.
Added test file for CalcCenterOfMassPosition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11740)

Added function to compute MultibodyPlant CoM position

---

doc/credits.rst

Acknowledge two new Drake contributors in the credits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11813)

Add new contributors to Drake credits

---

multibody/hydroelastics/hydroelastic_engine.cc
multibody/hydroelastics/test/hydroelastic_engine_test.cc

Bug fix in `HydroelasticEngine`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11812)

Fixes normal direction for level set vs. rigid case

---

examples/scene_graph/dev/solar_system.cc
examples/scene_graph/solar_system.cc
geometry/proximity/test/distance_to_point_with_gradient_test.cc
manipulation/perception/test/optitrack_pose_extractor_test.cc
manipulation/planner/test/differential_inverse_kinematics_test.cc
manipulation/util/test/bot_core_lcm_encode_decode_test.cc
systems/controllers/setpoint.h
systems/controllers/test/setpoint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11816)

Improve code towards rotation matrix and rigid transform

---

attic/systems/sensors/accelerometer.cc
attic/systems/sensors/accelerometer.h
attic/systems/sensors/test/accelerometer_test/accelerometer_test.cc

The measured acceleration caused by gravity should point upward (to positive z axis).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11821)

Fix a bug in Accelerometer

---

multibody/optimization/BUILD.bazel
multibody/optimization/contact_wrench_evaluator.h
multibody/optimization/manipulator_equation_constraint.cc
multibody/optimization/manipulator_equation_constraint.h
multibody/optimization/static_equilibrium_constraint.h
multibody/optimization/test/manipulator_equation_constraint_test.cc

needed for contact implicit trajectory optimization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11815)

Adds the ManipulatorEquationConstraint class

---

multibody/optimization/BUILD.bazel
multibody/optimization/sliding_friction_complementarity_constraint.cc
multibody/optimization/sliding_friction_complementarity_constraint.h
multibody/optimization/test/optimization_with_contact_utilities.cc
multibody/optimization/test/optimization_with_contact_utilities.h
multibody/optimization/test/sliding_friction_complementarity_constraint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11772)

Sliding friction complementarity constraint

---

solvers/fbstab/BUILD.bazel
solvers/fbstab/components/BUILD.bazel
solvers/fbstab/components/dense_data.h
solvers/fbstab/components/dense_feasibility.cc
solvers/fbstab/components/dense_feasibility.h
solvers/fbstab/components/dense_linear_solver.cc
solvers/fbstab/components/dense_linear_solver.h
solvers/fbstab/components/dense_residual.cc
solvers/fbstab/components/dense_residual.h
solvers/fbstab/components/dense_variable.cc
solvers/fbstab/components/dense_variable.h
solvers/fbstab/components/test/dense_component_unit_tests.cc
solvers/fbstab/components/test/dense_component_unit_tests.h

Part 2
+@frankpermenter for feature review, please
+@soonho-tri for platform review, please
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11797)

Residual, feasibility, and linear solver classes for dense QPs

---

bindings/pydrake/trajectories_py.cc
common/trajectories/piecewise_polynomial.h

Closes #11800
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11833)

Fix docstring in trajectories_py.cc

---

attic/manipulation/planner/rbt_differential_inverse_kinematics.cc
manipulation/planner/differential_inverse_kinematics.cc
manipulation/planner/differential_inverse_kinematics.h
manipulation/planner/test/differential_inverse_kinematics_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11828)

Improve differential_inverse_kinematics with RotationMatrix and RigidTransform

---

systems/framework/BUILD.bazel
systems/framework/test/diagram_builder_test.cc

(Inspired by user questions on slack.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11834)

framework: Add test for polymorphic port types

---

systems/trajectory_optimization/BUILD.bazel
systems/trajectory_optimization/integration_constraint.cc
systems/trajectory_optimization/integration_constraint.h
systems/trajectory_optimization/test/integration_constraint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11837)

Add constraint for midpoint integration

---

systems/trajectory_optimization/integration_constraint.h

Resolves #11852
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11854)

Fix a bug in integration_constraint.h

---

manipulation/planner/differential_inverse_kinematics.cc
manipulation/planner/test/differential_inverse_kinematics_test.cc
multibody/plant/multibody_plant.h
multibody/plant/test/external_forces_test.cc
multibody/tree/multibody_tree.cc
multibody/tree/multibody_tree.h
multibody/tree/test/multibody_tree_test.cc
perception/depth_image_to_point_cloud.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11836)

Start deprecating CalcFrameGeometricJacobianExpressedInWorld()

---

geometry/render/test/render_engine_vtk_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11858)

geometry: Delete stale test comment

---

bindings/pydrake/systems/test/trajectory_optimization_test.py
bindings/pydrake/systems/trajectory_optimization_py.cc
systems/trajectory_optimization/multiple_shooting.h

Follow up to #11835. Do not review/merge until it has merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11845)

Clean up MultipleShooting bindings and docs

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py

Partially resolves #11863
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11870)

bind AddLinearCost(a, b, vars)

---

solvers/fbstab/BUILD.bazel
solvers/fbstab/components/BUILD.bazel
solvers/fbstab/components/dense_linear_solver.cc
solvers/fbstab/components/dense_linear_solver.h
solvers/fbstab/components/dense_residual.cc
solvers/fbstab/components/dense_residual.h
solvers/fbstab/components/dense_variable.cc
solvers/fbstab/components/dense_variable.h
solvers/fbstab/components/test/dense_component_unit_tests.h
solvers/fbstab/fbstab_algorithm.h
solvers/fbstab/fbstab_dense.cc
solvers/fbstab/fbstab_dense.h
solvers/fbstab/test/fbstab_dense_unit_tests.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11830)

Added API for FBstab for Dense QPs, unit tests, and algorithm code

---

geometry/render/test/render_engine_vtk_test.cc

Collect constants together
Minor stuff, but found the label -> color conversion to be an opaque indirection. For debugging (copied this for Godot), easier to have concrete colors used consistently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11867)

render_engine_vtk_test: Get rid of abuse of label colors

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/test/geometry_test.py
geometry/frame_kinematics_vector.cc
geometry/frame_kinematics_vector.h
geometry/test/frame_kinematics_vector_test.cc
multibody/math/spatial_vector.h
multibody/math/test/spatial_algebra_test.cc
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11843)

multibody: Remove deprecated methods (2019-08)

---

setup/mac/binary_distribution/install_prereqs.sh

Closes #11884.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11887)

Remove deprecated lines from prerequisites install script for macOS

---

tools/workspace/fcl/BUILD.bazel
tools/workspace/fcl/package.BUILD.bazel
tools/workspace/fcl/repository.bzl
tools/workspace/fcl/version-from-xml.sed
tools/workspace/json/repository.bzl
tools/workspace/meshcat/repository.bzl
tools/workspace/pycps/repository.bzl

N.B. This does not update `scs` yet (even though there is a new release) due to #11883.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11882)

workspace: Update externals to latest

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/__init__.py
bindings/pydrake/geometry_py.cc
bindings/pydrake/manipulation/planner_py.cc
bindings/pydrake/pydrake_pybind.h
bindings/pydrake/systems/sensors_py.cc
bindings/pydrake/systems/test/sensors_test.py
bindings/pydrake/systems/trajectory_optimization_py.cc
bindings/pydrake/test/_pydrake_pybind_test_extra.py
bindings/pydrake/test/geometry_test.py
bindings/pydrake/test/pydrake_pybind_test.cc
tools/skylark/pybind.bzl

Resolves #11865
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11866)

pydrake: Add `ParamInit` and add a focused test for `pydrake_pybind`

---

bindings/pydrake/systems/primitives_py.cc
bindings/pydrake/systems/test/primitives_test.py

@EricCousineau-TRI for feature review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11897)

Add bindings for DiscreteTimeDelay system

---

bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/sensors_py.cc
bindings/pydrake/systems/test/sensors_test.py
systems/sensors/rgbd_sensor.cc
systems/sensors/rgbd_sensor.h
systems/sensors/test/rgbd_sensor_test.cc

For both intrinsics and separate renderers
Resolves #11878
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11879)

rgbd_sensor: Support setting separate properties for color and depth

---

solvers/fbstab/components/BUILD.bazel
solvers/fbstab/components/mpc_data.cc
solvers/fbstab/components/mpc_data.h
solvers/fbstab/components/mpc_variable.cc
solvers/fbstab/components/mpc_variable.h
solvers/fbstab/components/test/mpc_component_unit_tests.cc
solvers/fbstab/components/test/mpc_component_unit_tests.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11875)

Added data, and variable classes for MPC problems

---

bindings/pydrake/attic/BUILD.bazel
bindings/pydrake/attic/test/attic_forwarding_test.py
bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/_controllers_extra.py
bindings/pydrake/systems/_sensors_extra.py
bindings/pydrake/systems/controllers_py.cc
bindings/pydrake/systems/sensors_py.cc

Resolves #11885
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11905)

py systems: Remove 2019-06-01 deprecations

---

bindings/pydrake/math_py.cc
bindings/pydrake/test/math_test.py
common/test_utilities/expect_throws_message.h
math/rigid_transform.h
math/rotation_matrix.h
math/test/rigid_transform_test.cc
math/test/rotation_matrix_test.cc

Resolves #11902
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11903)

rigid_transform: Add Matrix4 construction

---

automotive/BUILD.bazel
automotive/test/trajectory_optimization_test.cc
common/proto/BUILD.bazel
common/proto/call_python.h
common/proto/call_python_client.py
doc/developers.rst
examples/acrobot/BUILD.bazel
examples/acrobot/run_lqr_w_estimator.cc
examples/zmp/BUILD.bazel
examples/zmp/zmp_example.cc
solvers/BUILD.bazel
solvers/test/plot_feasible_rotation_matrices.cc
solvers/test/plot_rotation_mccormick_envelope.cc
solvers/test/rotation_constraint_visualization.cc
systems/controllers/BUILD.bazel
systems/controllers/test/dynamic_programming_test.cc
systems/sensors/BUILD.bazel
systems/sensors/test/beam_model_test.cc

Relates #11753.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11907)

Use call_python instead of call_matlab

---

manipulation/perception/pose_smoother.cc

As part of removing Eigen::Isometry from Drake,
migrate pose_smoother_cc code towards RigidTransform.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11862)

Migrate pose_smoother_cc towards RigidTransform

---

geometry/proximity/BUILD.bazel
geometry/proximity/make_box_mesh.h
geometry/proximity/test/make_box_mesh_test.cc
geometry/proximity/test/make_unit_sphere_mesh_test.cc
geometry/proximity/test/volume_mesh_test.cc
geometry/proximity/volume_mesh.h

Related to issue #11152. This is for the hydroelastic contact model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11881)

[geometry] Generate a tetrahedral volume mesh of a box.

---

solvers/fbstab/components/BUILD.bazel
solvers/fbstab/components/dense_data.h
solvers/fbstab/components/dense_feasibility.h
solvers/fbstab/components/dense_linear_solver.h
solvers/fbstab/components/dense_residual.h
solvers/fbstab/components/dense_variable.h
solvers/fbstab/components/mpc_data.h
solvers/fbstab/components/mpc_feasibility.cc
solvers/fbstab/components/mpc_feasibility.h
solvers/fbstab/components/mpc_residual.cc
solvers/fbstab/components/mpc_residual.h
solvers/fbstab/components/mpc_variable.h
solvers/fbstab/components/riccati_linear_solver.cc
solvers/fbstab/components/riccati_linear_solver.h
solvers/fbstab/components/test/mpc_component_unit_tests.cc
solvers/fbstab/components/test/mpc_component_unit_tests.h
solvers/fbstab/fbstab_algorithm.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11904)

Added MPC residual, feasibility, and linear solver for FBstab

---

bindings/pydrake/common/eigen_geometry_py.cc
bindings/pydrake/common/test/eigen_geometry_test.py
bindings/pydrake/math_py.cc
bindings/pydrake/test/math_test.py
math/rotation_matrix.h

Resolves #11920
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11921)

py math: Enable multiplication for lists of points

---

solvers/fbstab/BUILD.bazel
solvers/fbstab/README.md
solvers/fbstab/fbstab_mpc.cc
solvers/fbstab/fbstab_mpc.h
solvers/fbstab/test/fbstab_mpc_unit_tests.cc
solvers/fbstab/test/ocp_generator.cc
solvers/fbstab/test/ocp_generator.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11926)

Added MPC interface and unit tests

---

doc/documentation_instructions.rst
doc/doxygen_main.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11930)

doxygen: Provide better errors for bad arguments

---

solvers/dreal_solver.cc
solvers/dreal_solver.h
solvers/test/dreal_solver_test.cc

EDIT (eric): Towards #11941
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11940)

Do not include dreal/dreal.h in dreal_solver.h

---

bindings/pydrake/common/BUILD.bazel
bindings/pydrake/common/eigen_geometry_py.cc
bindings/pydrake/common/test/eigen_geometry_test.py
bindings/pydrake/test/math_test.py

Follow-up items to #11920
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11929)

py math, eigen_geometry: Address follow-up comments

---

solvers/BUILD.bazel
solvers/no_dreal.cc
solvers/test/dreal_solver_test.cc
tools/BUILD.bazel
tools/install/libdrake/BUILD.bazel
tools/workspace/BUILD.bazel

Per request from @RussTedrake.
EDIT (eric): Resolves #11941 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11942)

Add no_dreal configuration to make the dReal solver optional

---

bindings/pydrake/solvers/BUILD.bazel
bindings/pydrake/solvers/test/nlopt_solver_test.py
bindings/pydrake/solvers/test/scs_solver_test.py
solvers/test/mathematical_program_result_test.cc
solvers/test/scs_solver_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11945)

Fixes for various no_{solver} configurations

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/math_py.cc
bindings/pydrake/test/math_test.py
math/rigid_transform.h
math/test/rigid_transform_test.cc

Follow-up to #11922
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11948)

 py math: Update bindings for RigidTransform(pose)

---

tools/workspace/snopt/fortran-ubuntu.bzl
tools/workspace/snopt/package.BUILD.bazel

Also use deterministic `$(AR)` output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11972)

snopt: Silence build warnings

---

common/BUILD.bazel
common/find_runfiles_stub.cc
common/test/find_runfiles_stub_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11981)

common: Provide a stub for find_runfiles

---

bindings/pydrake/common/BUILD.bazel
bindings/pydrake/common/sorted_pair_pybind.h
bindings/pydrake/multibody/BUILD.bazel
bindings/pydrake/multibody/inverse_kinematics_py.cc
bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/inverse_kinematics_test.py
bindings/pydrake/multibody/test/plant_test.py
multibody/inverse_kinematics/angle_between_vectors_constraint.cc
multibody/inverse_kinematics/angle_between_vectors_constraint.h
multibody/inverse_kinematics/distance_constraint.h
multibody/inverse_kinematics/gaze_target_constraint.cc
multibody/inverse_kinematics/gaze_target_constraint.h
multibody/inverse_kinematics/minimum_distance_constraint.h
multibody/inverse_kinematics/orientation_constraint.cc
multibody/inverse_kinematics/orientation_constraint.h
multibody/inverse_kinematics/position_constraint.cc
multibody/inverse_kinematics/position_constraint.h

Resolves #11239
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11959)

py inverse_kinematics: Add constraint bindings

---

tools/workspace/pybind11/repository.bzl

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11950)

pybind11: Merge latest upstream

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/common/BUILD.bazel
bindings/pydrake/common/eigen_geometry_py.cc
bindings/pydrake/common/test/cpp_template_test.py
bindings/pydrake/common/test/eigen_geometry_test.py
bindings/pydrake/common/test_utilities/BUILD.bazel
bindings/pydrake/common/test_utilities/pickle_compare.py
bindings/pydrake/test/autodiffutils_test.py
bindings/pydrake/test/math_test.py

Clarify minor implementation comment
Follow-up to #11976
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11989)

py: Add test utilities for checking pickle-ability

---

doc/developers.rst
setup/ubuntu/source_distribution/install_prereqs.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11988)

Update recommended bazel version to 0.29

---

multibody/plant/contact_results.h
multibody/plant/test/box_test.cc

Repairs #11901.  See also #12002.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12001)

plant: Repair "Hydroelastic contact surface visualization" link error

---

tools/jupyter/BUILD.bazel
tools/jupyter/README.md
tools/jupyter/__init__.py
tools/jupyter/example.ipynb
tools/jupyter/example_library.py
tools/jupyter/jupyter_bazel.py
tools/jupyter/jupyter_py.bzl
tools/jupyter/test/failing_notebook.ipynb
tools/jupyter/test/failing_notebook_test.py
tools/workspace/default.bzl
tools/workspace/os.bzl

Resolves #9650
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11960)

jupyter: Add support for running / testing notebooks

---

geometry/proximity/BUILD.bazel
geometry/proximity/make_box_mesh.h
geometry/proximity/sorted_triplet.cc
geometry/proximity/sorted_triplet.h
geometry/proximity/test/make_box_mesh_test.cc
geometry/proximity/test/sorted_triplet_test.cc
geometry/proximity/test/volume_to_surface_mesh_test.cc
geometry/proximity/volume_to_surface_mesh.h

Create SurfaceMesh from VolumeMesh. This PR is related to Hydroelastic model Spiral I #9905.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11967)

[geometry] Convert VolumeMesh to SurfaceMesh.

---

bindings/pydrake/symbolic_py.cc

Closes #11997.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12006)

Add doc for pydrake.symbolic.Expression and pydrake.symbolic.Monomial

---

common/find_resource.cc
common/find_runfiles.cc
common/find_runfiles.h
common/find_runfiles_stub.cc
common/test/find_runfiles_fail_test.cc
common/test/find_runfiles_stub_test.cc
common/test/find_runfiles_test.cc

Resolves #11296.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11995)

common: Promote find_runfiles to public

---

setup/ubuntu/source_distribution/packages-bionic.txt

Related PR: https://github.com/RobotLocomotion/drake/pull/11689
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12013)

Use libstdc++6-7-dbg in Bionic

---

common/test/drake_throw_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12015)

Fix include statements in drake_throw_test.cc

---

bindings/pydrake/systems/primitives_py.cc
bindings/pydrake/systems/test/primitives_test.py
systems/primitives/symbolic_vector_system.cc
systems/primitives/symbolic_vector_system.h
systems/primitives/test/symbolic_vector_system_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12012)

Support parameters in SymbolicVectorSystem

---

bindings/pydrake/__init__.py

Resolves #11999
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12000)

pydrake: Permit downstream projects to use `ExecuteExtraPythonCode`

---

bindings/pydrake/systems/controllers_py.cc
bindings/pydrake/systems/test/controllers_test.py
systems/controllers/pid_controlled_system.h

@EricCousineau-TRI for feature review (if you are the right person, add yourself on Reviewable since I can't, if not feel free to reassign).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12020)

Add bindings for PidController and PidControlledSystem

---

bindings/pydrake/systems/controllers_py.cc
bindings/pydrake/systems/test/controllers_test.py
examples/kuka_iiwa_arm/kuka_torque_controller.h
examples/qp_inverse_dynamics/manipulator_joint_space_controller.h
manipulation/schunk_wsg/schunk_wsg_plain_controller.h
systems/controllers/inverse_dynamics_controller.h
systems/controllers/pid_controller.h

py controllers: Minor touch-ups for testing
Resolves #12027
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12030)

pid_controller: Reorder inheritance order to workaround pydrake errors

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/multibody/tree_py.cc
multibody/plant/multibody_plant.h
multibody/plant/test/multibody_plant_test.cc
multibody/tree/multibody_tree-inl.h
multibody/tree/multibody_tree.cc
multibody/tree/multibody_tree.h

Fixes #11080
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11987)

Remove deprecated overload of AddForceElement

---

systems/primitives/BUILD.bazel
systems/primitives/symbolic_vector_system.h
systems/primitives/test/symbolic_vector_system_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12048)

Add accessors to SymbolicVectorSystem and its Builder

---

solvers/osqp_solver.cc
tools/workspace/cmake_configure_file.bzl
tools/workspace/cmake_configure_file.py
tools/workspace/osqp/package.BUILD.bazel
tools/workspace/osqp/repository.bzl
tools/workspace/qdldl/README.md
tools/workspace/qdldl/package.BUILD.bazel
tools/workspace/qdldl/repository.bzl

Relates #11883.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12047)

workspace: Update qdldl and osqp to latest release

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12056)

Trampoline SolverInterface in python binding.

---

doc/from_binary.rst
solvers/mathematical_program_doxygen.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12062)

doc: Improve SNOPT citations and credits

---

doc/from_source.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12074)

doc: Suggest Bionic as our preference (not Xenial)

---

tools/workspace/default.bzl
tools/workspace/osqp/package.BUILD.bazel
tools/workspace/scs/package.BUILD.bazel
tools/workspace/scs/private.h.diff
tools/workspace/scs/repository.bzl
tools/workspace/suitesparse/BUILD.bazel
tools/workspace/suitesparse/package.BUILD.bazel
tools/workspace/suitesparse/repository.bzl

Closes #11697.  Relates #11883.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12071)

workspace: Add suitesparse for osqp and scs

---

bindings/pydrake/examples/multibody/cart_pole_passive_simulation.py
bindings/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis.py
bindings/pydrake/examples/test/acrobot_test.py
bindings/pydrake/examples/test/compass_gait_test.py
bindings/pydrake/examples/test/pendulum_test.py
bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/systems/test/controllers_test.py
bindings/pydrake/systems/test/custom_test.py
bindings/pydrake/systems/test/general_test.py
bindings/pydrake/systems/test/lcm_test.py
bindings/pydrake/systems/test/lifetime_test.py
bindings/pydrake/systems/test/meshcat_visualizer_test.py
bindings/pydrake/systems/test/perception_test.py
bindings/pydrake/systems/test/primitives_test.py
bindings/pydrake/systems/test/rendering_test.py
bindings/pydrake/systems/test/sensors_test.py
doc/credits.rst

Towards #11341 
@sherm1 for feature review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12079)

bindings: Change context.FixInputPort() to port.FixValue()

---

bindings/pydrake/pydrake_doxygen.h
bindings/pydrake/systems/controllers_py.cc
doc/Doxyfile_CXX.in
systems/controllers/pid_controlled_system.h
third_party/com_github_pybind_pybind11/mkdoc.py
tools/workspace/pybind11/test/sample_header.h
tools/workspace/pybind11/test/sample_header_documentation.expected.h

Closes #12016.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12081)

mkdoc: Enable the developer to specify docstring names

---

examples/manipulation_station/manipulation_station.cc
examples/manipulation_station/test/manipulation_station_test.cc

The old extrinsics were not looking at the robot and table.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12089)

update camera extrinsics in manipulation station class setup

---

multibody/hydroelastics/hydroelastic_engine.cc
multibody/hydroelastics/hydroelastic_engine.h
multibody/hydroelastics/test/hydroelastic_engine_test.cc
multibody/plant/BUILD.bazel
multibody/plant/hydroelastic_traction_calculator.cc
multibody/plant/hydroelastic_traction_calculator.h
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/test/multibody_plant_hydroelastic_test.cc

This PR effectively brings the computation of contact forces with the hydroelastic model into MultibodyPlant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11928)

Wire up HydroelasticEngine to MultibodyPlant.

---

bindings/pydrake/systems/meshcat_visualizer.py
bindings/pydrake/systems/test/meshcat_visualizer_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12090)

draw body frames in meshcat visualizer

---

multibody/plant/BUILD.bazel
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/test/multibody_plant_hydroelastic_test.cc

Small follow up to #11928 to compute accelerations due to hydro contact forces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12094)

Hydroelastics produces accelerations

---

solvers/test/scs_solver_test.cc
tools/workspace/osqp/package.BUILD.bazel
tools/workspace/qdldl/README.md
tools/workspace/qdldl/package.BUILD.bazel
tools/workspace/scs/package.BUILD.bazel
tools/workspace/scs/private.c.diff
tools/workspace/scs/private.h.diff
tools/workspace/scs/repository.bzl
tools/workspace/suitesparse/package.BUILD.bazel
tools/workspace/suitesparse/repository.bzl

Closes #11883.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12084)

workspace: Update scs to latest release

---

tools/workspace/snopt/repository.bzl

Drake will always use Drake's BUILD files.  Upstream sources don't have BUILD files -- to my awareness the only time our snopt fetch did have BUILD files was when we were using our RobotLocomotion/snopt fork, instead of the pristine upstream sources.  Now that we use upstream sources unmodified, we don't need to handle stray BUILD files.
Relates RobotLocomotion/snopt#22.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12098)

workspace: Remove snopt support for upstream BUILD files

---

tools/workspace/pypi.bzl
tools/workspace/semantic_version/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12041)

Refactor pypi_archive and generate JSON repository metadata and update semantic_version to latest version

---

multibody/plant/implicit_stribeck_solver.cc
multibody/plant/multibody_plant.cc
multibody/plant/test/implicit_stribeck_solver_test.cc
multibody/plant/test/multibody_plant_test.cc

Resolves #12066.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12070)

[MBP] Allow discrete updates on empty worlds

---

tools/workspace/new_release.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12120)

workspace: Add new archive types to new_release report

---

bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/sensors_py.cc
bindings/pydrake/systems/test/sensors_test.py

I'd like to use this class in a multiprocessing context, so I'd like to be able to pass this around via pickling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12131)

py sensors: Make CameraInfo support pickling

---

tools/workspace/optitrack_driver/optitrack_client
tools/workspace/optitrack_driver/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12126)

Switch to python3 version of the optitrack client

---

geometry/proximity/make_box_mesh.h
geometry/proximity/make_sphere_mesh.h

We previously had some kind of "edge length" or "target length" in the API
for creating a mesh. After consideration, it was deemed better to make it
more generic as a "resolution hint". Each function takes a resolution hint
as a consistent API and provides a definition of how that hint guides the
tesselation. It is not required to be exactly the same interpretation, but
they should at least be in the same ballpark.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12114)

Reframe mesh creation with "resolution hint"

---

multibody/plant/BUILD.bazel
multibody/plant/test/multibody_plant_tamsi_test.cc

Leftover from discussion in #12070.
As promised, we'd push this test once #12053 merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12132)

[MBP] TAMSI unit test for worlds with anchored geometry and zero DoFs

---

tools/macos.bazelrc

Closes #12107 (I guess).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12133)

Work around incompatibilities between Eigen <= 3.3.7 and Apple LLVM 11.0.0

---

attic/perception/estimators/dev/test/articulated_icp_test.cc
examples/acrobot/run_plant_w_lcm.cc
examples/acrobot/test/acrobot_lcm_msg_generator.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12139)

Add missing #include <thread> throughout

---

multibody/plant/multibody_plant.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12135)

Improve Jacobian documentation per issue #12119

---

setup/BUILD.bazel

Fixes drake-external-examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12147)

Install requirements-py2.txt

---

tools/workspace/os.bzl
tools/workspace/python/repository.bzl

Relates #11692.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12148)

Do not error when building on macOS Catalina

---

tools/bazel.rc

Relates #12137.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12150)

Set incompatible_remove_legacy_whole_archive to false

---

tools/install/libdrake/build_components.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12152)

Refresh build_components.bzl

---

tools/workspace/numpy/repository.bzl
tools/workspace/python/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12155)

Fix numpy_repository for python3-only builds

---

multibody/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12159)

multibody: Remove deprecated attic aliases

---

multibody/plant/multibody_plant.h
multibody/plant/test/kuka_iiwa_model_tests.h
multibody/tree/multibody_tree.cc
multibody/tree/multibody_tree.h

_Edit: Relates #12154._
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12157)

Step 1  to remove deprecated Jacobian methods 2019-10-01, per issue #12154

---

geometry/proximity/BUILD.bazel
geometry/proximity/make_sphere_mesh.h
geometry/proximity/test/make_sphere_mesh_test.cc
geometry/proximity/volume_to_surface_mesh.cc
geometry/proximity/volume_to_surface_mesh.h

Creates SurfaceMesh for a sphere. It is intended for a rigid sphere in hydroelastic contact model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12163)

[geometry] Add MakeSphereSurfaceMesh().

---

examples/BUILD.bazel
examples/planar_gripper/BUILD.bazel
tools/install/libdrake/build_components.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12176)

Install sdf data of the planar gripper

---

attic/manipulation/util/BUILD.bazel
attic/manipulation/util/world_sim_tree_builder.cc
attic/multibody/parsers/BUILD.bazel
attic/multibody/parsers/test/parsers_frames_test/parsers_frames_test.cc
attic/multibody/parsers/test/urdf_parser_test.cc
attic/multibody/shapes/BUILD.bazel
attic/multibody/shapes/geometry.cc

Relates #12104.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12179)

attic: Remove uses of spruce

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/test/geometry_test.py
geometry/scene_graph_inspector.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12177)

Add python binding for functions in SceneGraphInspector.

---

geometry/geometry_state.h
geometry/proximity_engine.h
geometry/query_object.h
geometry/scene_graph.h

Closes #10050 
I wasn't too sure about what was considered a common section for Signed Distance Queries so I didn't change much there - open to suggestions!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12168)

Update redundant/inconsistent documentation around SceneGraph API

---

systems/sensors/BUILD.bazel
systems/sensors/image_writer.cc
systems/sensors/image_writer.h
systems/sensors/test/image_writer_test.cc

Relates #12104.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12180)

sensors: Remove uses of spruce

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12185)

bind functions in geometry::Shape

---

common/trajectories/BUILD.bazel
common/trajectories/piecewise_polynomial.cc
common/trajectories/piecewise_polynomial.h
common/trajectories/piecewise_trajectory.h
common/trajectories/test/piecewise_polynomial_test.cc

Closes #8759.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12183)

#8759:  Correct misleading error message / documentation

---

setup/mac/binary_distribution/Brewfile
setup/mac/binary_distribution/install_prereqs.sh
solvers/BUILD.bazel
solvers/dreal_solver.cc
tools/install/libdrake/BUILD.bazel
tools/workspace/BUILD.bazel
tools/workspace/cds/BUILD.bazel
tools/workspace/cds/repository.bzl
tools/workspace/default.bzl
tools/workspace/dreal/repository.bzl
tools/workspace/dreal/versions.bzl
tools/workspace/github.bzl
tools/workspace/ibex/BUILD.bazel
tools/workspace/ibex/package-ubuntu.BUILD.bazel
tools/workspace/ibex/repository.bzl
tools/workspace/ibex/version.bzl
tools/workspace/picosat/BUILD.bazel
tools/workspace/picosat/repository.bzl
tools/workspace/rules_pkg/BUILD.bazel
tools/workspace/rules_pkg/repository.bzl

It's a pain point to have C++ libraries in the build that are not compiled directly from source.
Relates #12136.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12186)

workspace: Build dreal from source

---

geometry/shape_specification.cc
geometry/shape_specification.h
geometry/test/shape_specification_test.cc
manipulation/models/jaco_description/urdf/j2s7s300.urdf
multibody/plant/test/block_on_halfspace.sdf

Closes #12038
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12172)

Add numerical validation for shape specifications

---

CMakeLists.txt
doc/developers.rst
doc/getting_help.rst
doc/jenkins.rst
setup/mac/binary_distribution/requirements-py2.txt
setup/mac/source_distribution/Brewfile
tools/macos.bazelrc
tools/workspace/os.bzl
tools/workspace/python/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12194)

Add Catalina support and drop High Sierra support

---

systems/sensors/test/image_writer_test.cc

Closes #9960
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12198)

Create explicitly permissioned directory for ImageWriter test

---

bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/custom_test.py
bindings/pydrake/systems/test/general_test.py
examples/manipulation_station/end_effector_teleop_sliders.py

Relates #11073.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12181)

py systems: Remove deprecated protected aliases

---

tools/workspace/README.md

Follow-up to #12014
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12021)

workspace: Add notes for release / branch usage

---

bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/multibody/tree_py.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12209)

add functions binding for RigidBody

---

multibody/plant/multibody_plant.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11686)

adds @system doxygen block for MBP

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12219)

bind coulomb friction

---

geometry/proximity/mesh_field_linear.h
geometry/proximity/surface_mesh.h
geometry/proximity/test/contact_surface_test.cc
geometry/proximity/test/mesh_field_linear_test.cc
geometry/proximity/test/surface_mesh_test.cc
geometry/query_results/contact_surface.h
multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc

Closes #12173
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12193)

Move equal functions from test into their respective classes

---

bindings/pydrake/multibody/test/plant_test.py
manipulation/planner/differential_inverse_kinematics.h
multibody/constraint/constraint_doxygen.h
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/test/kuka_iiwa_model_tests.h
multibody/tree/body_node.h
multibody/tree/body_node_impl.h
multibody/tree/mobilizer.h
multibody/tree/multibody_tree.cc
multibody/tree/multibody_tree.h
multibody/tree/multibody_tree_system.cc
multibody/tree/multibody_tree_system.h
multibody/tree/test/multibody_tree_test.cc

This is part of the Jacobian epic, issue #10155.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12192)

Remove methods/language for GeometricJacobian, AnalyticJacobian.

---

geometry/proximity/mesh_intersection.h
geometry/proximity/penetration_as_point_pair_callback.cc
geometry/query_object.h
geometry/render/render_engine_ospray.cc

tesselate --> tessellate
insure -> ensure
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12225)

Collection of spelling corrections

---

geometry/geometry_state.h
geometry/proximity/BUILD.bazel
geometry/proximity/collisions_exist_callback.cc
geometry/proximity/collisions_exist_callback.h
geometry/proximity/test/collisions_exist_callback_test.cc
geometry/proximity_engine.cc
geometry/proximity_engine.h
geometry/query_object.cc
geometry/query_object.h
geometry/test/proximity_engine_test.cc
geometry/test/query_object_test.cc

Closes #10227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12211)

Add query for whether any collisions exist

---

doc/code_style_guide.rst
doc/doxygen.py
manipulation/util/convert_to_visualize_collisions.py
tools/clion/bazel_wrapper
tools/clion/test/bazel_wrapper_test.py
tools/dev/add_cpplint.py
tools/install/install.bzl
tools/install/install.py.in
tools/install/libdrake/build_components_refresh.py
tools/lint/drakelint.py
tools/ubuntu-xenial.bazelrc

Toward #11692 and #10606.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12146)

Change Python shebangs to point to python3, etc.

---

tools/install/libdrake/BUILD.bazel
tools/install/libdrake/test/find_package_drake_install_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12208)

Add install test checking generated drake-config.cmake

---

bindings/pydrake/autodiffutils_py.cc
bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/test/autodiffutils_test.py

and initializeAutoDiffGivenGradientMatrix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12229)

Add python binding for CalcJacobianAngular/TranslationalVelocity

---

bindings/pydrake/multibody/inverse_kinematics_py.cc
bindings/pydrake/multibody/test/inverse_kinematics_test.py
bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12232)

Bind IK context, bind evaluator gradient sparsity.

---

systems/analysis/BUILD.bazel
systems/analysis/bogacki_shampine3_integrator.h
systems/analysis/runge_kutta2_integrator.h
systems/analysis/runge_kutta3_integrator.h
systems/analysis/runge_kutta5_integrator.cc
systems/analysis/runge_kutta5_integrator.h
systems/analysis/test/bogacki_shampine3_integrator_test.cc
systems/analysis/test/explicit_euler_integrator_test.cc
systems/analysis/test/runge_kutta2_integrator_test.cc
systems/analysis/test/runge_kutta3_integrator_test.cc
systems/analysis/test/runge_kutta5_integrator_test.cc
systems/analysis/test/semi_explicit_euler_integrator_test.cc
systems/analysis/test_utilities/BUILD.bazel
systems/analysis/test_utilities/generic_integrator_test.h
systems/analysis/test_utilities/quartic_scalar_system.h
systems/analysis/test_utilities/quintic_scalar_system.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12223)

Adds the Dormand-Prince (RK45) integrator.

---

tools/vector_gen/lcm_vector_gen.py

See https://msg.pyyaml.org/load for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12244)

vector_gen: Use yaml.safe_load

---

bindings/pydrake/__init__.py
bindings/pydrake/common/cpp_const.py
bindings/pydrake/common/cpp_template.py
bindings/pydrake/common/test/cpp_template_test.py
bindings/pydrake/common/test/deprecation_test.py
bindings/pydrake/common/test/eigen_geometry_test.py
bindings/pydrake/common/test/module_test.py
bindings/pydrake/common/test_utilities/pickle_compare.py
bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/systems/test/lcm_test.py
bindings/pydrake/test/math_test.py
bindings/pydrake/test/mock_torch/torch.py
bindings/pydrake/test/rtld_global_warning_test.py
bindings/pydrake/test/symbolic_test.py
common/proto/call_python_client.py
common/test/cpplint_wrapper.py
common/test/cpplint_wrapper_test.py
doc/doxygen_main.py
doc/sphinx_base.py
tools/clion/test/bazel_wrapper_test.py
tools/install/cpsutils.py
tools/lint/drakelint.py
tools/lint/formatter.py
tools/workspace/new_release.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12248)

Remove most usage of six

---

geometry/geometry_state.cc
geometry/geometry_visualization.cc
geometry/proximity/proximity_utilities.h
geometry/proximity_engine.cc
geometry/render/render_engine_ospray.cc
geometry/render/render_engine_ospray.h
geometry/render/render_engine_vtk.cc
geometry/render/render_engine_vtk.h
geometry/shape_specification.cc
geometry/shape_specification.h
geometry/shape_to_string.cc
geometry/shape_to_string.h
geometry/test/geometry_state_test.cc
geometry/test/proximity_engine_test.cc
geometry/test/shape_specification_test.cc
geometry/test/shape_to_string_test.cc
geometry/test_utilities/dummy_render_engine.h
multibody/hydroelastics/hydroelastic_engine.cc
multibody/hydroelastics/hydroelastic_engine.h

Related to #10153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12235)

Add capsule shape specification and enable visualization

---

tools/install/libdrake/drake.cps
tools/install/libdrake/test/find_package_drake_install_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12250)

Fix drake::drake-common-text-logging-gflags target

---

multibody/parsing/detail_scene_graph.cc
multibody/parsing/test/detail_scene_graph_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12258)

Support capsule parsing in sdf with custom drake:capsule tag

---

multibody/plant/test/floating_body_test.cc
multibody/tree/quaternion_floating_mobilizer.cc
multibody/tree/quaternion_floating_mobilizer.h
multibody/tree/space_xyz_mobilizer.cc
multibody/tree/space_xyz_mobilizer.h
multibody/tree/test/quaternion_floating_mobilizer_test.cc
multibody/tree/test/space_xyz_mobilizer_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12259)

Fix mobilizer::SetRotationMatrix() to take RotationMatrix argument (not Matrix3).

---

attic/manipulation/planner/test/rbt_differential_inverse_kinematics_test.cc
attic/manipulation/scene_generation/random_clutter_generator.cc
attic/manipulation/scene_generation/random_clutter_generator.h
attic/multibody/rigid_body_plant/compliant_material.h
attic/multibody/rigid_body_plant/rigid_body_plant.h
attic/systems/sensors/rgbd_camera.cc
attic/systems/sensors/rgbd_renderer.cc
attic/systems/sensors/rgbd_renderer.h
attic/systems/sensors/rgbd_renderer_ospray.cc
attic/systems/sensors/rgbd_renderer_ospray.h
attic/systems/sensors/rgbd_renderer_vtk.cc
attic/systems/sensors/rgbd_renderer_vtk.h
bindings/pydrake/examples/manipulation_station_py.cc
bindings/pydrake/lcm_py.cc
bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/tree_py.cc
bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/primitives_py.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12271)

Use std::optional instead of drake::optional in attic and bindings

---

perception/depth_image_to_point_cloud.cc
perception/depth_image_to_point_cloud.h
perception/test/depth_image_to_point_cloud_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12275)

Use std::optional instead of drake::optional in perception

---

common/drake_path.cc
common/drake_path.h
common/find_loaded_library.cc
common/find_loaded_library.h
common/find_resource.cc
common/find_resource.h
common/hash.h
common/symbolic_simplification.cc
common/test/find_loaded_library_test.cc
common/test/find_resource_test.cc
common/test/hash_test.cc
common/yaml/test/yaml_read_archive_test.cc
common/yaml/yaml_read_archive.h
examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
examples/allegro_hand/run_allegro_constant_load_demo.cc
examples/manipulation_station/manipulation_station.cc
examples/manipulation_station/manipulation_station.h
examples/manipulation_station/proof_of_life.cc
examples/multibody/inclined_plane_with_body/inclined_plane_with_body.cc
examples/planar_gripper/planar_gripper_simulation.cc
examples/van_der_pol/van_der_pol.cc

Depends on #12276 and #12277.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12272)

Use std::optional instead of drake::optional in common and examples

---

tools/skylark/pybind.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12279)

Do not use -Wno-unused-lambda-capture with GCC

---

common/BUILD.bazel
common/drake_variant.h

Depends on #12281.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12282)

Deprecate drake_variant.h header

---

geometry/geometry_state.cc
geometry/geometry_visualization.cc
geometry/proximity/proximity_utilities.h
geometry/proximity_engine.cc
geometry/render/render_engine_ospray.h
geometry/render/render_engine_vtk.h
geometry/shape_specification.cc
geometry/shape_specification.h
geometry/shape_to_string.cc
geometry/shape_to_string.h
geometry/test/geometry_state_test.cc
geometry/test/shape_specification_test.cc
geometry/test_utilities/dummy_render_engine.h
multibody/hydroelastics/hydroelastic_engine.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12256)

Add ellipsoid shape specification

---

attic/manipulation/dev/BUILD.bazel
attic/systems/controllers/BUILD.bazel
attic/systems/controllers/InstantaneousQPController.h
attic/systems/controllers/QPCommon.h
attic/systems/controllers/README.md
attic/systems/controllers/controlUtil.h
attic/systems/controllers/polynomial_encode_decode.h
attic/systems/controllers/side.h
attic/systems/controllers/yaml_util.h
attic/systems/controllers/zmpUtil.h
attic/systems/robotInterfaces/BUILD.bazel
attic/systems/robotInterfaces/BodyMotionData.h
attic/systems/robotInterfaces/QPLocomotionPlan.h
attic/systems/robotInterfaces/README.md
attic/systems/robotInterfaces/atlasUtil.h
attic/systems/robotInterfaces/convex_hull.h
attic/systems/robotInterfaces/verify_subtype_sizes.h

Relates #12283.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12291)

attic: Deprecate robotInterfaces and some of controllers

---

attic/perception/BUILD.bazel
attic/perception/README.md
attic/perception/estimators/dev/BUILD.bazel
attic/perception/estimators/dev/README.md
attic/perception/estimators/dev/articulated_icp.h
attic/perception/estimators/dev/pose_closed_form.h
attic/perception/estimators/dev/scene.h
attic/perception/rigid_body_point_cloud_filter.h
attic/perception/transform_point_cloud.h

Relates #12283.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12292)

attic: Deprecate perception

---

geometry/render/BUILD.bazel
geometry/render/render_engine_ospray.cc
geometry/render/render_engine_ospray.h
geometry/render/render_engine_vtk.cc
geometry/render/render_engine_vtk_base.cc
geometry/render/render_engine_vtk_base.h
geometry/render/test/render_engine_ospray_test.cc
geometry/render/test/render_engine_vtk_test.cc
tools/workspace/vtk/repository.bzl

Represented using a cylinder and two spheres
Relates to #10153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12293)

Render capsule in vtk and ospray engines

---

manipulation/models/xtion_description/BUILD.bazel

This fixes commit 0f6a52696b4e444645e2c717a50c455163ed3b2d ( #12294) titled "Deprecate most of manipulation".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12298)

models: Avoid attic deprecation warnings

---

attic/multibody/rigid_body_plant/rigid_body_plant_bridge.cc
bindings/pydrake/geometry_py.cc
examples/pendulum/pendulum_geometry.cc
examples/scene_graph/solar_system.cc
geometry/frame_kinematics_vector.cc
geometry/frame_kinematics_vector.h
geometry/geometry_instance.cc
geometry/geometry_instance.h
geometry/scene_graph_inspector.h
geometry/test/frame_kinematics_vector_test.cc
geometry/test/scene_graph_inspector_test.cc
multibody/plant/multibody_plant.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12300)

geometry: Remove deprecated methods 2019-11-01

---

common/eigen_types.h
math/rigid_transform.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12301)

common: Remove deprecated methods 2019-10-15

---

multibody/plant/multibody_plant.h

Addresses #12252
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12269)

Add documentation on model instances to MultibodyPlant.

---

manipulation/models/allegro_hand_description/BUILD.bazel
manipulation/models/allegro_hand_description/LICENSE.TXT
manipulation/models/iiwa_description/BUILD.bazel
manipulation/models/jaco_description/BUILD.bazel
manipulation/models/wsg_50_description/BUILD.bazel
tools/workspace/models/files.bzl

Closes #9790.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12312)

models: Install license files

---

bindings/pydrake/math_py.cc
bindings/pydrake/test/math_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12313)

Add Python bindings for RotationMatrix::ToAngleAxis() for issue #12307.

---

bindings/pydrake/autodiffutils_py.cc
bindings/pydrake/common/eigen_geometry_py.cc
bindings/pydrake/math_py.cc
bindings/pydrake/pydrake_pybind.h
bindings/pydrake/systems/sensors_py.cc
doc/code_style_guide.rst
doc/python_bindings.rst
multibody/plant/images/README.md
tools/dynamic_analysis/asan.sh
tools/dynamic_analysis/drd.sh
tools/dynamic_analysis/helgrind.sh
tools/dynamic_analysis/kcov.sh
tools/dynamic_analysis/lsan.sh
tools/dynamic_analysis/msan.sh
tools/dynamic_analysis/tsan.sh
tools/dynamic_analysis/ubsan.sh
tools/dynamic_analysis/valgrind.sh
tools/install/install.py.in
tools/install/test/install_test_helper_test.py
tools/lint/bazel_lint.bzl
tools/lint/python_lint.bzl
tools/workspace/lcm/package.BUILD.bazel
tools/workspace/models/files.bzl
tools/workspace/pycodestyle/package.BUILD.bazel
tools/workspace/vtk/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12320)

Miscellaneous Python 2 to 3 cleanup

---

third_party/com_github_finetjul_bender/BUILD.bazel
third_party/com_github_finetjul_bender/NOTICE
third_party/com_github_finetjul_bender/README.md

Follow-up on #12305.
\CC @tehbelinda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12327)

third_party: Fix license installation for bender

---

doc/developers.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12331)

Update supported Xcode version to 11.2

---

bindings/pydrake/examples/multibody/BUILD.bazel
bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py
bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/all.py
bindings/pydrake/systems/meshcat_visualizer.py
bindings/pydrake/systems/planar_scenegraph_visualizer.py
bindings/pydrake/systems/pyplot_visualizer.py
bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py
bindings/pydrake/systems/test/pyplot_visualizer_test.py

Originally known as planar_multibody_visualizer. Examples were separated into their own section under multibody.
Mesh support is removed for now. Follow up bindings to come
For #11104.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12218)

Port planar_scenegraph_visualizer from underactuated

---

examples/planar_gripper/gripper_brick.cc
examples/planar_gripper/gripper_brick.h
examples/planar_gripper/planar_brick.sdf
examples/planar_gripper/planar_gripper.sdf
examples/planar_gripper/planar_gripper.xacro
examples/planar_gripper/planar_gripper_common.cc
examples/planar_gripper/planar_gripper_common.h
examples/planar_gripper/postures.txt
examples/planar_gripper/test/gripper_brick_test.cc

Also updates the planar_brick.sdf model to match the 100x100x70 mm physical brick.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12308)

Updates the planar_gripper model to match the hardware. 

---

common/symbolic_polynomial.cc
common/symbolic_polynomial.h
examples/cubic_polynomial/backward_reachability.cc
solvers/sos_basis_generator.cc

Fix #10229.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/11790)

Store indeterminates and decision variables in symbolic::Polynomial as members

---

tools/workspace/mosek/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12337)

workspace: Add missing pthread linkopts for MOSEK

---

setup/mac/source_distribution/requirements.txt
setup/ubuntu/source_distribution/packages-bionic.txt

Bionic: https://pandas.pydata.org/pandas-docs/stable/install.html#installing-using-your-linux-distribution-s-package-manager
OSX: https://pandas.pydata.org/pandas-docs/stable/install.html#installing-from-pypi
We want it for #12040
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12328)

Add pandas as a source dependency

---

multibody/tree/multibody_tree.h

I introduce the notation and equations we use in the forward dynamics I'll push next.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12317)

Documents forward dynamics algorithm and notation in MBT

---

geometry/proximity_engine.cc
geometry/test/proximity_engine_test.cc

Relates to #10153
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12343)

Support collision queries with capsule

---

multibody/parsing/detail_scene_graph.cc
multibody/parsing/test/detail_scene_graph_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12324)

Add sdf parsing for ellipsoids

---

bindings/pydrake/multibody/inverse_kinematics_py.cc
bindings/pydrake/multibody/test/inverse_kinematics_test.py
multibody/inverse_kinematics/inverse_kinematics.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12346)

Add python binding for DistanceConstraint.

---

examples/planar_gripper/gripper_brick.cc
examples/planar_gripper/gripper_brick.h
examples/planar_gripper/planar_gripper.sdf
examples/planar_gripper/planar_gripper.xacro
examples/planar_gripper/planar_gripper_common.cc
examples/planar_gripper/postures.txt
examples/planar_gripper/test/gripper_brick_test.cc

at the force sensor interface, splitting link 2 into two separate links.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12338)

Adds a weld joint to the planar_gripper fingers

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/geometry_py.cc
bindings/pydrake/systems/planar_scenegraph_visualizer.py
bindings/pydrake/test/geometry_test.py
geometry/proximity/obj_to_surface_mesh.cc
geometry/proximity/obj_to_surface_mesh.h
geometry/proximity/test/obj_to_surface_mesh_test.cc

Closes #11104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12349)

Complete visualizer port with obj to mesh bindings

---

systems/analysis/simulator.h
systems/framework/event_collection.h
systems/framework/test/diagram_test.cc
systems/framework/test/leaf_system_test.cc

Resolves #10119
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12357)

Renames event collection merge methods.

---

tools/workspace/meshcat_python/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12365)

workspace: Upgrade meshcat_python to latest commit

---

tools/install/dockerhub/.dockerignore
tools/install/dockerhub/.gitignore
tools/install/dockerhub/Dockerfile
tools/install/dockerhub/README.md

Relates #10554.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12364)

Add Dockerfile for building images for Docker Hub

---

multibody/plant/multibody_plant.cc

Addresses #12359.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12361)

Change MBP's TAMSI solver success assertion into an exception

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12375)

Pybind an overloaded AddQuadraticCost.

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12371)

Pybind add constraint

---

geometry/proximity_engine.h
geometry/shape_specification.h

Closes #12265
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12372)

Update stale instructions on subclassing Shape specification

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py
examples/planar_gripper/gripper_brick.cc
examples/planar_gripper/planar_gripper_simulation.cc
geometry/geometry_visualization.cc
geometry/proximity/hydroelastic_internal.cc
geometry/proximity/make_cylinder_field.h
geometry/proximity/make_cylinder_mesh.h
geometry/proximity/make_ellipsoid_field.h
geometry/proximity/make_ellipsoid_mesh.h
geometry/proximity/make_sphere_field.h
geometry/proximity/make_sphere_mesh.h
geometry/proximity/test/make_sphere_mesh_test.cc
geometry/proximity_engine.cc
geometry/render/render_engine_ospray.cc
geometry/render/render_engine_vtk.cc
geometry/shape_specification.h
geometry/shape_to_string.cc
geometry/test/geometry_state_test.cc
geometry/test/proximity_engine_test.cc
geometry/test/shape_specification_test.cc
multibody/hydroelastics/hydroelastic_engine.cc
multibody/parsing/test/detail_scene_graph_test.cc
multibody/parsing/test/detail_urdf_geometry_test.cc

Closes #12290
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12373)

Simplify and deprecate get_ accessors in shape specification API

---

tools/lint/test/util_test.py
tools/lint/util.py

Related to #12367.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12369)

lint: Make find_all_sources more paranoid

---

CMakeLists.txt

Not that we run a linter, but if we did...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12381)

Fix various CMake lint issues

---

examples/scene_graph/solar_system.cc
examples/scene_graph/solar_system.h

Relates to #10153 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12374)

Add capsule to the solar system visualisation

---

tools/cc_toolchain/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12394)

Do not run Valgrind Memcheck on print_host_settings_test

---

systems/analysis/explicit_euler_integrator.h
systems/analysis/implicit_integrator.h
systems/analysis/integrator_base.h
systems/analysis/radau_integrator.h
systems/analysis/runge_kutta2_integrator.h
systems/analysis/semi_explicit_euler_integrator.h
systems/analysis/simulator.h
systems/analysis/test/explicit_euler_integrator_test.cc
systems/analysis/test/implicit_euler_integrator_test.cc
systems/analysis/test/radau_integrator_test.cc
systems/analysis/test/runge_kutta2_integrator_test.cc
systems/analysis/test/semi_explicit_euler_integrator_test.cc
systems/analysis/test/simulator_test.cc
systems/analysis/test_utilities/generic_integrator_test.h
systems/analysis/test_utilities/implicit_integrator_test.h

Resolves #11365
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12392)

Changed dt to h in integrator documentation and internals.

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/multibody/tree_py.cc
bindings/pydrake/test/geometry_test.py
geometry/geometry_properties.cc
geometry/geometry_properties.h
geometry/scene_graph.h

Replaces #12386
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12389)

py geometry: Bind properties and role assignment

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py
doc/index.rst
tutorials/BUILD.bazel
tutorials/rendering_multibody_plant.ipynb

@manuelli Here's an example of how. It was easier than I thought (because I had forgotten about #11824).
Requires:
Can benefit from: #12388
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12388)

tutorials: Add example of rendering which uses MultibodyPlant

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py
multibody/inverse_kinematics/distance_constraint.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12408)

Pybind ComputeSignedDistancePairClosestPoints.

---

doc/doxygen_main.py
doc/release_notes/v0.10.0.rst
doc/release_notes/v0.11.0.rst
doc/release_notes/v0.12.0.rst

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12416)

doc: Add release download links; fix doxygen dot path

---

common/BUILD.bazel
common/symbolic_environment.cc
common/symbolic_environment.h
common/test/symbolic_environment_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12409)

Add matrix version of Environment::insert

---

tools/lint/buildifier.py
tools/lint/clang_format_includes.py
tools/lint/test/util_test.py

Better to ask for a confirmation, versus trying to guess in util.py whether or not find_all_sources did the right thing.
A new spin on #12369.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12424)

lint: Ask before rewriting thousands of files

---

geometry/proximity_engine.cc
geometry/test/proximity_engine_test.cc

Relates to #10153 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12332)

Tests for capsule support for distance to shape in proximity engine

---

bindings/pydrake/symbolic_py.cc
common/symbolic_expression.cc
common/symbolic_expression.h
common/test/symbolic_expression_matrix_test.cc

Also rewrite GetDistinctVariables using Eigen's `visit` method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12406)

Add Evaluate for symbolic SparseMatrix

---

systems/framework/context.h

Provides the final piece to resolve @RussTedrake's issues in #8489. (Resolves #8489)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12428)

Updates the documentation on the use of accuracy in the Context.

---

bindings/pydrake/common/eigen_geometry_py.cc
bindings/pydrake/common/test/eigen_geometry_test.py
bindings/pydrake/math_py.cc
bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/test/math_test.py
common/proto/call_python.cc
common/proto/call_python.h
geometry/proximity/surface_mesh.h
geometry/query_results/contact_surface.h
geometry/shape_specification.h
math/rigid_transform.h
math/test/rigid_transform_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12431)

Remove deprecated methods (2019-12-01)

---

tutorials/BUILD.bazel
tutorials/mathematical_program_multibody_plant.ipynb

Focused on custom evaluators.
This is super terse, but is catered to answer @mposa's Slack question:
https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1575412174070900
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12433)

tutorials: Add brief tutorial for optimization using MultibodyPlant

---

tutorials/dynamical_systems.ipynb
tutorials/mathematical_program.ipynb
tutorials/mathematical_program_multibody_plant.ipynb
tutorials/rendering_multibody_plant.ipynb
tutorials/solver_parameters.ipynb

Also save with newest Python (3.6.9) for Ubuntu Bionic
Follow-up from #12433 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12437)

tutorials: Remove last cells from notebooks

---

examples/planar_gripper/BUILD.bazel
examples/planar_gripper/planar_manipuland_lcm.cc
examples/planar_gripper/planar_manipuland_lcm.h
examples/planar_gripper/test/planar_manipuland_lcm_test.cc
lcmtypes/BUILD.bazel
lcmtypes/lcmt_planar_manipuland_status.lcm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12439)

Add the lcm utility for planar manipuland.

---

doc/docker.rst
doc/from_binary.rst

Resolves #10554.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12446)

docker: Add link to published images in documentation

---

tools/workspace/drake_visualizer/plugin/show_time.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12444)

Fixes negative real time factors in Drake visualizer.

---

lcm/test/drake_lcm_test.cc

Relates #12448 and https://github.com/lcm-proj/lcm/issues/301.
(I have confirmed locally that when I upgrade LCM to latest, this test fails.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12451)

lcm: Add acceptance test to rule out IP address crosstalk

---

tutorials/mathematical_program_multibody_plant.ipynb

Follow-up to #12433.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12443)

tutorials: Updating wording in MP + MBP tutorial

---

tools/workspace/lcm/repository.bzl

Closes #12448.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12457)

workspace: Upgrade lcm to latest commit

---

multibody/tree/body_node.h

Make use of the new operators introduced in #12436.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12462)

Make effective use of SpatialAcceleration's addition operators

---

bindings/pydrake/doc/pydrake_sphinx_extension.py

Resolves #11954
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12452)

'Fix' sphinx to get __init__ documentation.

---

examples/planar_gripper/BUILD.bazel
examples/planar_gripper/planar_gripper_lcm.cc
examples/planar_gripper/planar_gripper_lcm.h
examples/planar_gripper/test/planar_gripper_lcm_test.cc
lcmtypes/BUILD.bazel
lcmtypes/lcmt_planar_gripper_command.lcm
lcmtypes/lcmt_planar_gripper_finger_command.lcm
lcmtypes/lcmt_planar_gripper_finger_status.lcm
lcmtypes/lcmt_planar_gripper_status.lcm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12449)

Adds LCM message utilities for the planar gripper.

---

.gitattributes

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12465)

gitattributes: Update for modern bazel spellings

---

bindings/pydrake/doc/pydrake_sphinx_extension.py
setup/mac/source_distribution/requirements.txt

Towards:
https://github.com/RobotLocomotion/drake/pull/11141/files
(@jamiesnape found the issue and suggested the fix.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12467)

Un-pin sphinx for OSX

---

systems/primitives/symbolic_vector_system.cc
systems/primitives/symbolic_vector_system.h
systems/primitives/test/symbolic_vector_system_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12466)

Add SymbolicVectorSystemBuilder::LinearizeDynamics

---

geometry/query_results/contact_surface.h
multibody/hydroelastics/contact_surface_from_level_set.h
multibody/hydroelastics/test/contact_surface_from_level_set_test.cc
multibody/plant/hydroelastic_traction_calculator.cc
multibody/plant/multibody_plant.cc
multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc

Resolves #12454.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12463)

Reverses the surface normal convention in ContactSurface.

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
examples/scene_graph/simple_contact_surface_vis.cc
geometry/geometry_roles.h
geometry/proximity_properties.cc
geometry/proximity_properties.h
geometry/test/proximity_properties_test.cc
multibody/parsing/detail_scene_graph.cc
multibody/parsing/detail_scene_graph.h
multibody/parsing/detail_sdf_parser.cc
multibody/parsing/detail_urdf_geometry.cc
multibody/parsing/detail_urdf_geometry.h
multibody/parsing/detail_urdf_parser.cc
multibody/parsing/test/detail_scene_graph_test.cc
multibody/parsing/test/detail_urdf_geometry_test.cc
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h

Reverts RobotLocomotion/drake#12464
Dear @SeanCurtis-TRI,
@jamiesnape believes that your PR #12464 may have
*  https://drake-jenkins.csail.mit.edu/job/linux-bionic-clang-bazel-continuous-address-sanitizer/1649/
* https://drake-jenkins.csail.mit.edu/job/linux-bionic-clang-bazel-continuous-everything-address-sanitizer/1650/
problem. If that build passes, this revert PR will be merged 60 …

Revert "Adding drake contact material properties to sdf/urdf parsing"

---

BUILD.bazel
tools/install/bazel/BUILD.bazel
tools/install/bazel/README.md
tools/install/bazel/drake.BUILD.bazel
tools/install/bazel/drake__bindings__pydrake.BUILD.bazel
tools/install/bazel/drake__common.BUILD.bazel
tools/install/bazel/drake__examples.BUILD.bazel
tools/install/bazel/drake__manipulation.BUILD.bazel
tools/install/bazel/generate_installed_files_manifest.bzl
tools/install/bazel/repo_gen.py
tools/install/bazel/repo_template.bzl
tools/install/bazel/test/drake_bazel_installed_test.py
tools/install/install.bzl

In support of https://github.com/RobotLocomotion/drake-external-examples/pull/152.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12402)

install: Add drake_bazel_installed support

---

examples/allegro_hand/test/allegro_lcm_test.cc
examples/bead_on_a_wire/test/bead_on_a_wire_test.cc
examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc
examples/kuka_iiwa_arm/test/kuka_torque_controller_test.cc
examples/manipulation_station/end_effector_teleop_sliders.py
examples/manipulation_station/joint_teleop.py
examples/manipulation_station/proof_of_life.cc
examples/manipulation_station/test/manipulation_station_hardware_interface_test.cc
examples/manipulation_station/test/manipulation_station_test.cc
examples/multibody/acrobot/run_lqr.cc
examples/multibody/cart_pole/cart_pole_passive_simulation.cc
examples/multibody/cart_pole/test/cart_pole_test.cc
examples/particles/test/particle_test.cc
examples/particles/test/utilities_test.cc
examples/pendulum/pendulum_parameters_derivatives.cc
examples/pendulum/print_symbolic_dynamics.cc
examples/pendulum/test/urdf_dynamics_test.cc
examples/quadrotor/quadrotor_plant.cc
examples/rod2d/rod2d_sim.cc
examples/rod2d/test/rod2d_test.cc

Towards #11341
@sherm1 for feature review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12482)

examples: Change context.FixInputPort() to port.FixValue()

---

tools/dev/BUILD.bazel
tools/dev/relnotes.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12477)

tools: Add relnotes helper tool

---

common/text_logging.h
tools/workspace/fmt/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12487)

workspace: Upgrade fmt to latest release 6.1.2

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.h
solvers/test/mathematical_program_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12490)

Get binding variable values

---

examples/planar_gripper/BUILD.bazel
examples/planar_gripper/README.md
examples/planar_gripper/planar_gripper_common.cc
examples/planar_gripper/planar_gripper_common.h
examples/planar_gripper/planar_gripper_lcm.cc
examples/planar_gripper/planar_gripper_simulation.cc
examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc
examples/planar_gripper/test/planar_gripper_common_test.cc
multibody/plant/multibody_plant.cc

Also adds a fix to properly order keyframe joints according
to MBP velocity index ordering.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12469)

Adds LCM messaging to the planar-gripper simulation.

---

examples/planar_gripper/planar_gripper_common.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12494)

Fixing Mac CI failure.

---

multibody/plant/multibody_plant.cc

Related to #12498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12499)

More helpful message on joint limit support in MBP

---

.binder/.dockerignore
.binder/Dockerfile
.binder/README.md
.binder/binder-entrypoint
doc/index.rst
tools/install/dockerhub/README.md
tutorials/README.md
tutorials/dynamical_systems.ipynb
tutorials/mathematical_program.ipynb
tutorials/mathematical_program_multibody_plant.ipynb
tutorials/rendering_multibody_plant.ipynb

Relates #11962.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12472)

Add Dockerfile for Binder

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/systems/drawing_graphviz_example.py
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/test/multibody_plant_test.cc
systems/framework/system.h

Resolves #11441
Also updated the expired url reference in system.h
Here is an example output:
[test.pdf](https://github.com/RobotLocomotion/drake/files/3964334/test.pdf)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12485)

Add graphviz visualization of multibodyplant topology

---

bindings/pydrake/examples/manipulation_station_py.cc
bindings/pydrake/examples/test/manipulation_station_test.py
bindings/pydrake/manipulation/simple_ui.py
examples/manipulation_station/end_effector_teleop_sliders.py
examples/manipulation_station/joint_teleop.py

and necessary python bindings.
Try `bazel run //examples/manipulation_station:joint_teleop -- --setup=planar` to have the full experience.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12503)

Add planar iiwa joint teleop example

---

manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc
manipulation/kuka_iiwa/test/iiwa_command_sender_test.cc
manipulation/kuka_iiwa/test/iiwa_status_receiver_test.cc
manipulation/kuka_iiwa/test/iiwa_status_sender_test.cc
manipulation/perception/test/optitrack_pose_extractor_test.cc
manipulation/perception/test/pose_smoother_test.cc
manipulation/planner/test/robot_plan_interpolator_test.cc
manipulation/schunk_wsg/test/schunk_wsg_controller_test.cc
manipulation/schunk_wsg/test/schunk_wsg_lcm_test.cc
manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
manipulation/schunk_wsg/test/schunk_wsg_trajectory_generator_test.cc
multibody/constraint/test/constraint_solver_test.cc
multibody/plant/test/box_test.cc
multibody/plant/test/contact_results_to_lcm_test.cc
multibody/plant/test/joint_limits_test.cc
multibody/plant/test/multibody_plant_symbolic_test.cc
multibody/plant/test/multibody_plant_test.cc
perception/test/depth_image_to_point_cloud_test.cc

Towards #11341.  Commits are curated.
@sherm1 for feature review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12504)

manipulation, multibody, perception: Change context.FixInputPort() to port.FixValue()

---

.binder/Dockerfile

Relates #11962 and moby/moby#35018.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12510)

Fix Binder Dockerfile for Docker versions before 19.03

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/test/parse_models_test.py
examples/kuka_iiwa_arm/models/desk/transcendesk55inch.sdf
examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table_surface_only_collision.sdf
examples/quadrotor/office.urdf
manipulation/models/wsg_50_description/sdf/schunk_wsg_50_ball_contact.sdf

Per comment in #12505
Changes to models were necessary for current test to pass
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12508)

pydrake: Test parsing all models

---

bindings/pydrake/examples/manipulation_station_py.cc

Fix #12512
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12513)

Add binding for RegisterRgbdSensor in manipulation station.

---

bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/systems/analysis_py.cc
solvers/BUILD.bazel
systems/analysis/simulator.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12515)

Remove deprecated code (2020-01)

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/forwarddiff.py
bindings/pydrake/test/forward_diff_test.py

Resolves #12484
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12511)

pydrake: Use np.asarray in gradient and jacobian

---

tools/workspace/drake_visualizer/plugin/show_hydroelastic_contact.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12493)

Added traction and slip vector visualization for hydroelastic contact.

---

attic/multibody/joints/drake_joint.cc
attic/multibody/joints/drake_joint.h
attic/multibody/joints/fixed_axis_one_dof_joint.h
attic/multibody/joints/fixed_joint.cc
attic/multibody/joints/fixed_joint.h
attic/multibody/joints/quaternion_ball_joint.cc
attic/multibody/joints/quaternion_ball_joint.h
attic/multibody/joints/quaternion_floating_joint.cc
attic/multibody/joints/quaternion_floating_joint.h
attic/multibody/joints/roll_pitch_yaw_floating_joint.cc
attic/multibody/joints/roll_pitch_yaw_floating_joint.h
attic/multibody/kinematics_cache-inl.h
attic/multibody/kinematics_cache.h
attic/multibody/parsers/urdf_parser.cc
attic/multibody/parsers/urdf_parser.h
attic/multibody/rigid_body.cc
attic/multibody/rigid_body.h
attic/multibody/rigid_body_tree.cc
attic/multibody/rigid_body_tree.h
attic/multibody/rigid_body_tree_alias_groups.h
attic/multibody/test/rigid_body_tree/rigid_body_tree_creation_test.cc
attic/systems/controllers/rbt_inverse_dynamics.cc
attic/systems/controllers/rbt_inverse_dynamics.h
attic/systems/controllers/rbt_inverse_dynamics_controller.cc
attic/systems/controllers/rbt_inverse_dynamics_controller.h
bindings/pydrake/attic/multibody/BUILD.bazel
bindings/pydrake/attic/multibody/rigid_body_tree_py.cc
examples/kuka_iiwa_arm/kuka_torque_controller.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12514)

attic: Remove deprecated methods (2020-01)

---

tools/dev/relnotes.py
tools/workspace/new_release.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12518)

workspace: Move GitHub token filename to command line, not environ

---

setup/mac/binary_distribution/install_prereqs.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12517)

setup: Remove ipopt,mumps uninstall on macOS

---

tools/workspace/sdformat/Converter.cc.diff
tools/workspace/sdformat/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12533)

sdformat: Hotfix for memory leak in Converter.cc

---

third_party/com_github_pybind_pybind11/mkdoc.py
tools/workspace/pybind11/BUILD.bazel
tools/workspace/pybind11/test/mkdoc_test.py
tools/workspace/pybind11/test/sample_header.h
tools/workspace/pybind11/test/sample_header_documentation.expected.h

Closes #12445
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12519)

mkdoc: Fix comment handling edge cases

---

geometry/proximity/BUILD.bazel
geometry/proximity/bounding_volume_hierarchy.cc
geometry/proximity/bounding_volume_hierarchy.h
geometry/proximity/surface_mesh.h
geometry/proximity/test/bounding_volume_hierarchy_test.cc
geometry/proximity/test/surface_mesh_test.cc
geometry/proximity/volume_mesh.h
multibody/hydroelastics/contact_surface_from_level_set.h
multibody/hydroelastics/test/contact_surface_from_level_set_test.cc

- pass transform for comparing the AABBs using OBB intersection test
- early exit option as soon as a potential collision pair is found
- accumulator wrapper helper function for getting a list of all the pairs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12418)

Collide BVHs using OBB intersection test with callback on the resulting pairs

---

attic/multibody/test/rigid_body_tree/rigid_body_tree_clone_test.cc
bindings/pydrake/systems/analysis_py.cc
examples/bouncing_ball/test/bouncing_ball_test.cc
examples/contact_model/bowling_ball.cc
examples/contact_model/rigid_gripper.cc
examples/contact_model/sliding_bricks.cc
examples/kuka_iiwa_arm/iiwa_wsg_simulation.cc
examples/multibody/acrobot/passive_simulation.cc
examples/multibody/pendulum/passive_simulation.cc
examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc
examples/pr2/pr2_passive_simulation.cc
examples/quadrotor/run_quadrotor_dynamics.cc
examples/rod2d/rod2d_sim.cc
examples/schunk_wsg/test/schunk_wsg_lift_test.cc
examples/simple_gripper/simple_gripper.cc
multibody/plant/test/box_test.cc
multibody/plant/test/floating_body_test.cc
multibody/plant/test/inclined_plane_test.cc
multibody/plant/test/multibody_plant_reaction_forces_test.cc
multibody/tree/test/free_rotating_body_test.cc
systems/analysis/simulator.h
systems/analysis/test/simulator_test.cc

Resolves #5265.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12520)

Updated Simulator's interface for changing integrators.

---

common/BUILD.bazel
common/scope_exit.h
common/test/scope_exit_test.cc
solvers/BUILD.bazel
solvers/gurobi_solver.cc
solvers/snopt_solver.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12537)

common: Add scope_exit class

---

doc/developers.rst
setup/ubuntu/source_distribution/install_prereqs.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12526)

Update recommended Bazel version to 2.0

---

common/BUILD.bazel
common/polynomial.cc
common/proto/BUILD.bazel
common/trajectories/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12540)

common: Remove stale TODOs

---

common/BUILD.bazel
common/drake_nodiscard.h
common/test/copyable_unique_ptr_test.cc
common/test/is_cloneable_test.cc
common/test_utilities/eigen_geometry_compare.h
common/test_utilities/eigen_matrix_compare.h
common/test_utilities/is_dynamic_castable.h
common/test_utilities/is_memcpy_movable.h
common/test_utilities/measure_execution.h
common/test_utilities/symbolic_test_util.h
geometry/proximity/bounding_volume_hierarchy.h
geometry/proximity/mesh_field.h
geometry/proximity/mesh_field_linear.h
geometry/proximity/test/mesh_field_test.cc
systems/analysis/integrator_base.h
systems/framework/basic_vector.h
systems/framework/event.h
systems/framework/test/diagram_test.cc
systems/framework/test/value_checker_test.cc
systems/framework/test_utilities/my_vector.h
systems/plants/spring_mass_system/spring_mass_system.h
systems/rendering/frame_velocity.h
systems/rendering/pose_vector.h
tools/vector_gen/lcm_vector_gen.py
tools/vector_gen/test/goal/sample.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12539)

common: Deprecate drake_nodiscard.h

---

systems/analysis/implicit_euler_integrator-inl.h
systems/analysis/implicit_integrator.h
systems/analysis/radau_integrator.h
systems/analysis/test/implicit_euler_integrator_test.cc
systems/analysis/test/radau_integrator_test.cc

Resolves #11936.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12524)

Adds ability to do full-Newton to implicit integrators.

---

solvers/BUILD.bazel
solvers/no_snopt.cc
tools/BUILD.bazel
tools/bazel.rc
tools/skylark/drake_cc.bzl

Instead, use `--config=snopt` for the same effect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12549)

tools: Error out on now-unsupported --config=snopt_fortran

---

geometry/render/BUILD.bazel
geometry/render/render_engine_ospray.cc
geometry/render/render_engine_ospray.h
geometry/render/render_engine_vtk.cc
geometry/render/render_engine_vtk.h
geometry/render/render_engine_vtk_base.cc
geometry/render/render_engine_vtk_base.h
geometry/render/test/render_engine_ospray_test.cc
geometry/render/test/render_engine_vtk_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12547)

Support ellipsoid rendering

---

systems/analysis/implicit_integrator.h

Minor fix to the docs removing duplicated copy/pasta.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12550)

Removes duplicated @name from integrator docs.

---

attic/manipulation/util/test/frame_pose_tracker_test.cc
attic/multibody/rigid_body_plant/test/drake_visualizer_test.cc
attic/multibody/rigid_body_plant/test/frame_visualizer_test.cc
attic/multibody/rigid_body_plant/test/rigid_body_plant_test.cc
attic/perception/test/rigid_body_point_cloud_filter_test.cc
attic/perception/test/transform_point_cloud_test.cc
attic/systems/controllers/test/rbt_inverse_dynamics_controller_test.cc
attic/systems/controllers/test/rbt_inverse_dynamics_test.cc
attic/systems/sensors/test/accelerometer_test/accelerometer_test.cc
attic/systems/sensors/test/depth_sensor_test.cc
attic/systems/sensors/test/depth_sensor_to_lcm_point_cloud_message_test.cc
attic/systems/sensors/test/gyroscope_test.cc
bindings/pydrake/attic/multibody/test/rigid_body_plant_test.py
bindings/pydrake/attic/systems/rgbd_camera_example.py
bindings/pydrake/attic/systems/test/controllers_test.py

Towards #11341
@sherm1 for feature review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12555)

attic: Change context.FixInputPort() to port.FixValue()

---

bindings/pydrake/examples/pendulum_py.cc
bindings/pydrake/examples/test/pendulum_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12569)

add python bindings for PendulumGeometry

---

common/yaml/BUILD.bazel
common/yaml/test/yaml_write_archive_test.cc
common/yaml/yaml_write_archive.cc
common/yaml/yaml_write_archive.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12568)

yaml: Add yaml_write_archive from Anzu

---

bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py
bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/systems/test/meshcat_visualizer_test.py
bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py
bindings/pydrake/test/all_test.py
bindings/pydrake/test/parse_models_test.py
doc/python_bindings.rst
examples/planar_gripper/gripper_brick.cc
manipulation/models/ycb/test/parse_test.cc
multibody/hydroelastics/test/hydroelastic_engine_test.cc
multibody/inverse_kinematics/inverse_kinematics.h
multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc
multibody/optimization/test/optimization_with_contact_utilities.cc
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/test/contact_results_to_lcm_test.cc
multibody/plant/test/hydroelastic_traction_test.cc
multibody/plant/test/multibody_plant_hydroelastic_test.cc
multibody/plant/test/multibody_plant_test.cc
tutorials/rendering_multibody_plant.ipynb

Second pass to resolve #12498.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12558)

AddMultibodyPlantSceneGraph() requires time_step argument.

---

attic/systems/sensors/test/accelerometer_test/accelerometer_test_logger.cc
examples/bead_on_a_wire/bead_on_a_wire-inl.h
systems/analysis/test_utilities/implicit_integrator_test.h
systems/framework/context.h
systems/framework/context_base.h
systems/framework/diagram.h
systems/framework/leaf_system.h
systems/framework/system.h
systems/framework/system_base.cc
systems/framework/system_base.h
systems/framework/test/cache_entry_test.cc
systems/framework/test/leaf_system_test.cc
systems/framework/test/system_base_test.cc
systems/framework/test/system_test.cc
systems/framework/witness_function.h
systems/primitives/linear_system.cc

_Edit: Prior title was "Checks that the Context passed into System functions was created by ("belongs to") the System."_
Resolves #11801
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12551)

Systems reject Contexts that they did not create

---

bindings/pydrake/examples/acrobot_py.cc
bindings/pydrake/examples/test/acrobot_test.py
tools/install/libdrake/build_components.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12574)

Add python bindings for AcrobotGeometry

---

tools/install/bazel/drake.BUILD.bazel
tools/install/bazel/generate_installed_files_manifest.bzl
tools/install/bazel/repo_template.bzl
tools/install/bazel/test/drake_bazel_installed_test.py

An option towards https://github.com/RobotLocomotion/drake-external-examples/issues/154
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12573)

install: Ensure drake lcmtypes are exposed in repository

---

tools/workspace/pybind11/repository.bzl

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12572)

workspace: Upgrade pybind fork to use merge with latest upstream

---

doc/from_binary.rst
doc/jenkins.rst

Closes #11446.
@EricCousineau-TRI for feature and platform review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12586)

Add instructions for building experimental binary packages using Jenkins

---

geometry/proximity/BUILD.bazel
geometry/proximity/hydroelastic_callback.h
geometry/proximity/hydroelastic_internal.h
geometry/proximity/mesh_half_space_intersection.h
geometry/proximity/mesh_intersection.cc
geometry/proximity/mesh_intersection.h
geometry/proximity/test/mesh_half_space_intersection_test.cc
geometry/proximity/test/mesh_intersection_test.cc
geometry/proximity/test/mesh_to_vtk_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12552)

Wire in bounding volume hierarchy to compute contact surfaces

---

doc/doxygen.h
geometry/benchmarking/BUILD.bazel
geometry/benchmarking/README.md
geometry/benchmarking/render_benchmark.cc
geometry/geometry_doxygen.h
geometry/geometry_infrastructure_doxygen.h
geometry/geometry_roles.h
geometry/proximity/proximity_doxygen.h
geometry/render/render_doxygen.h
geometry/render/render_engine.cc
geometry/render/render_engine.h
geometry/render/render_engine_ospray.cc
geometry/render/render_engine_ospray.h
geometry/render/render_engine_ospray_factory.h
geometry/render/render_engine_vtk.cc
geometry/render/render_engine_vtk.h
geometry/render/test/render_engine_ospray_test.cc
tools/workspace/default.bzl
tools/workspace/googlebenchmark/BUILD.bazel
tools/workspace/googlebenchmark/no_deprecated_declarations.patch
tools/workspace/googlebenchmark/repository.bzl

- add google benchmark to the build
- add shadow configuration to Ospray params
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12440)

Benchmark render engines with google benchmark and add documentation

---

bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py
bindings/pydrake/systems/pyplot_visualizer.py
bindings/pydrake/systems/test/pyplot_visualizer_test.py
tutorials/BUILD.bazel
tutorials/pyplot_animation_multibody_plant.ipynb

Relates to #12546
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12582)

Add recording functionality back in to pyplot visualizer

---

bindings/pydrake/examples/acrobot_py.cc
bindings/pydrake/examples/test/acrobot_test.py
examples/acrobot/acrobot_geometry.h
examples/acrobot/run_lqr.cc
examples/acrobot/run_lqr_w_estimator.cc
examples/acrobot/run_passive.cc
examples/acrobot/run_plant_w_lcm.cc
examples/acrobot/run_swing_up.cc
examples/acrobot/test/acrobot_geometry_test.cc
examples/acrobot/test/run_swing_up_traj_optimization.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12601)

support default parameters for AcrobotGeometry

---

tutorials/pyplot_animation_multibody_plant.ipynb

Alternative to #12603
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12615)

tutorials: Update HTML5 animation to be conditional

---

bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/general_test.py
systems/framework/system.h
systems/framework/test/diagram_test.cc
systems/framework/test/leaf_system_test.cc
systems/framework/test/system_test.cc
systems/primitives/linear_system.cc
systems/primitives/test/linear_system_test.cc
systems/trajectory_optimization/direct_transcription.cc

This is an attempt to simplify a pattern that is beginning to get repeated (and somewhat inconsistently).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12579)

Adds System::IsDifferenceEquationSystem

---

systems/analysis/integrator_base.h

Fixes broken links in the Doxygen docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12625)

Fixes broken links to the minimum step size section in IntegratorBase.

---

tools/workspace/pybind11/repository.bzl

Resolves #11424 with RobotLocomotion/pybind11#37
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12589)

pybind11: Prevent false cache hits for overloads

---

bindings/pydrake/geometry_py.cc
common/BUILD.bazel
common/identifier.h
common/test/identifier_test.cc
geometry/BUILD.bazel
geometry/geometry_ids.h
geometry/identifier.cc
geometry/identifier.h

Towards #12560.  Used by #12622.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12621)

common: Move geometry::Identifier here

---

multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h

Resolves #12606.
cc @RussTedrake @SeanCurtis-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12619)

Exclude z from MBP::get_state_output_port()

---

doc/jenkins.rst
setup/README.md

Came up in #12603
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12614)

doc: Add instructions for updating prerequisites

---

bindings/pydrake/systems/test/primitives_test.py
tools/workspace/pybind11/repository.bzl

Resolves #12633
Requires:
FYI @RussTedrake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12641)

workspace: Update pybind11 fork to latest commit

---

bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/primitives_py.cc
bindings/pydrake/systems/test/general_test.py
bindings/pydrake/systems/test/primitives_test.py
systems/primitives/BUILD.bazel
systems/primitives/affine_system.cc
systems/primitives/affine_system.h
systems/primitives/linear_system.h
systems/primitives/test/affine_system_test.cc
systems/primitives/trajectory_affine_system.h
systems/primitives/trajectory_linear_system.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12637)

Support Gaussian initial conditions in Affine/Linear systems.

---

tutorials/BUILD.bazel
tutorials/linear_program.ipynb
tutorials/mathematical_program.ipynb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12659)

Add linear program tutorial.

---

bindings/pydrake/examples/manipulation_station_py.cc

Towards #12604
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12675)

py manipulation_station: Add missing class docstrings

---

attic/manipulation/util/BUILD.bazel
attic/manipulation/util/README.md
attic/manipulation/util/robot_state_msg_translator.h
attic/manipulation/util/sim_diagram_builder.h
attic/manipulation/util/world_sim_tree_builder.h
examples/allegro_hand/BUILD.bazel
examples/allegro_hand/test/allegro_lcm_test.cc
examples/kuka_iiwa_arm/kuka_simulation.cc
examples/kuka_iiwa_arm/test/iiwa_lcm_test.cc

This includes robot_state_msg_translator, sim_diagram_builder, and world_sim_tree_builder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12679)

attic: Deprecate manipulation/util

---

tools/workspace/spdlog/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12669)

workspace: Upgrade spdlog to latest release 1.5.0

---

tutorials/rendering_multibody_plant.ipynb

Relates #12645
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12646)

tutorials: Add example of using meshcat visualizer

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
multibody/plant/multibody_plant.h
solvers/no_snopt.cc
solvers/snopt_solver.cc
solvers/snopt_solver.h

Follow-up from #12299 and #12197.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12685)

Remove deprecated code (2020-02)

---

geometry/benchmarking/render_benchmark.cc
geometry/proximity/make_box_field.h
geometry/proximity/test/hydroelastic_internal_test.cc
geometry/proximity/test/surface_mesh_test.cc
geometry/proximity_engine.cc
manipulation/models/ycb/test/parse_test.cc
multibody/parsing/detail_scene_graph.cc
multibody/plant/test/multibody_plant_test.cc
tools/workspace/styleguide/repository.bzl

Resolves #12577
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12687)

cpplint: Update sha and reformat to support structured bindings

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/BUILD.bazel
solvers/binding.h
solvers/constraint.cc
solvers/constraint.h
solvers/cost.cc
solvers/cost.h
solvers/evaluator_base.cc
solvers/evaluator_base.h
solvers/test/binding_test.cc
solvers/test/constraint_test.cc
solvers/test/cost_test.cc
solvers/test/evaluator_base_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12693)

print solvers::Binding.

---

tutorials/linear_program.ipynb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12700)

Print out added linear cost and constraint in the tutorial.

---

geometry/geometry_state.cc
geometry/geometry_state.h
geometry/geometry_visualization.cc
geometry/scene_graph.cc
geometry/scene_graph_inspector.h
geometry/test/geometry_state_test.cc
geometry/test/scene_graph_inspector_test.cc

Relates to #10082
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12626)

Rename GeometryState methods to match public API

---

bindings/pydrake/__init__.py

Towards #12655
Did a partial job of applying something like this to each module in #12670 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12671)

pydrake: Add better package overview

---

systems/primitives/affine_system.cc
systems/primitives/affine_system.h
systems/primitives/test/linear_system_test.cc

Add test in linear_system
Closes #12706 (as a workaround)
Assuming the main work to address this would happen in #12709
\cc @TobiaMarcucci 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12712)

affine_system: Do not add D*u to output if D==0

---

examples/pendulum/BUILD.bazel
examples/pendulum/test/urdf_dynamics_test.cc

Relates #12158.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12723)

pendulum: Update urdf_dynamics_test to use MultibodyPlant

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/attic/BUILD.bazel
bindings/pydrake/attic/multibody/BUILD.bazel
bindings/pydrake/attic/multibody/collision_py.cc
bindings/pydrake/attic/multibody/joints_py.cc
bindings/pydrake/attic/multibody/rigid_body_plant_py.cc
bindings/pydrake/attic/multibody/rigid_body_py.cc
bindings/pydrake/attic/multibody/rigid_body_tree_py.cc
bindings/pydrake/attic/multibody/shapes_py.cc
bindings/pydrake/attic/solvers/BUILD.bazel
bindings/pydrake/attic/solvers/ik_py.cc
bindings/pydrake/attic/systems/BUILD.bazel
bindings/pydrake/attic/systems/controllers_py.cc
bindings/pydrake/attic/systems/sensors_py.cc
bindings/pydrake/pydrake_doxygen.h
third_party/com_github_pybind_pybind11/mkdoc.py
tools/install/libdrake/BUILD.bazel
tools/skylark/pybind.bzl

This is towards #12040 (https://github.com/RobotLocomotion/drake/pull/12040#pullrequestreview-356689433).
We're trying to split the PR (#12040).
This code was added by @EricCousineau-TRI in #12040.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12727)

pydrake doc: Use separate attic/documentation_pybind.h

---

common/drake_copyable.h
geometry/proximity/volume_mesh.h
multibody/plant/contact_results.h
multibody/plant/coulomb_friction.h
multibody/plant/hydroelastic_contact_info.h
multibody/plant/point_pair_contact_info.h
multibody/tree/acceleration_kinematics_cache.h
multibody/tree/articulated_body_inertia.h
multibody/tree/articulated_body_inertia_cache.h
multibody/tree/multibody_forces.h
multibody/tree/position_kinematics_cache.h
multibody/tree/rotational_inertia.h
multibody/tree/spatial_inertia.h
multibody/tree/unit_inertia.h
multibody/tree/velocity_kinematics_cache.h
systems/framework/basic_vector.h
systems/framework/context.h
systems/framework/event.h
systems/framework/leaf_output_port.h
systems/framework/output_port.h
systems/framework/single_output_vector_source.h
systems/framework/system.h
systems/framework/system_output.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12735)

Remove extern template work-arounds for GCC 6.3

---

examples/allegro_hand/joint_control/BUILD.bazel
examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
examples/allegro_hand/joint_control/run_twisting_mug.cc
examples/allegro_hand/joint_control/test/run_twisting_mug_test.py

Closes #12722.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12734)

allegro_hand: Use correct timestep and add regression test

---

bindings/pydrake/solvers/gurobi_py.cc
bindings/pydrake/solvers/ipopt_py.cc
bindings/pydrake/solvers/mosek_py.cc
bindings/pydrake/solvers/nlopt_py.cc
bindings/pydrake/solvers/osqp_py.cc
bindings/pydrake/solvers/scs_py.cc
bindings/pydrake/solvers/snopt_py.cc
bindings/pydrake/solvers/test/ipopt_solver_test.py
bindings/pydrake/solvers/test/osqp_solver_test.py
bindings/pydrake/solvers/test/scs_solver_test.py
bindings/pydrake/solvers/test/snopt_solver_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12737)

add pybind11/eigen.h to pydrake/solvers

---

doc/credits.rst

This change adds Rick Cory, Damrong Guoy, Belinda Teh, and me to the credits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12741)

Add Rick, Damrong, Bel, and me to the Credits

---

manipulation/util/geometry_inspector.py
manipulation/util/test/geometry_inspector_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12736)

Add the capability to visualize collisions in geometry_inspector

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/test/geometry_test.py
geometry/test/geometry_visualization_test.cc

Carved out from #12702
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12733)

geometry_visualization: Add Python test of publishing

---

geometry/benchmarking/BUILD.bazel
geometry/benchmarking/README.md
geometry/benchmarking/mesh_intersection_benchmark.cc
geometry/benchmarking/render_benchmark.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12597)

Benchmark mesh intersection without vs with BVH

---

multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.h
multibody/plant/BUILD.bazel
multibody/plant/calc_distance_and_time_derivative.cc
multibody/plant/calc_distance_and_time_derivative.h
multibody/plant/test/calc_distance_and_time_derivative_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12720)

compute the time derivative of signed distance between a pair of geometries

---

attic/manipulation/planner/BUILD.bazel
attic/manipulation/planner/constraint_relaxing_ik_rbt.cc
attic/manipulation/planner/constraint_relaxing_ik_rbt.h
attic/manipulation/planner/test/constraint_relaxing_ik_rbt_test.cc
examples/kuka_iiwa_arm/BUILD.bazel
examples/kuka_iiwa_arm/iiwa_common.cc
examples/kuka_iiwa_arm/iiwa_common.h
examples/kuka_iiwa_arm/iiwa_lcm.h
examples/kuka_iiwa_arm/kuka_plan_runner.cc
examples/kuka_iiwa_arm/move_iiwa_ee.cc
manipulation/planner/BUILD.bazel
manipulation/planner/constraint_relaxing_ik.cc
manipulation/planner/constraint_relaxing_ik.h
manipulation/planner/test/constraint_relaxing_ik_test.cc

Also switches the only user of the RBT version to the new implementation.
_(Edit by jwnimmer-tri: Relates #12158.)_
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12732)

 Add a MultibodyPlant version of ConstraintRelaxingIk 

---

math/continuous_algebraic_riccati_equation.h
math/discrete_algebraic_riccati_equation.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12761)

render riccati equation properly in CARE doc

---

tools/workspace/styleguide/repository.bzl

Towards https://github.com/RobotLocomotion/styleguide/pull/26
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12765)

styleguide: Update sha to use cpplint changes

---

common/nice_type_name.cc
geometry/geometry_set.h
solvers/equality_constrained_qp_solver.cc
solvers/linear_system_solver.cc
solvers/sdpa_free_format.cc
systems/framework/vector_base.h

Towards getting https://github.com/RobotLocomotion/styleguide/pull/27 in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12768)

IWYU: Include initializer_list when it's used

---

tools/workspace/fcl/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12762)

Upgrade Drake's FCL to v0.6.1

---

setup/mac/binary_distribution/Brewfile
setup/ubuntu/binary_distribution/packages-bionic.txt

In a future commit, this will be used by tools/workspace/eigen.
Prep for #12780.
Relates #11758.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12784)

setup: Add eigen as a binary dependency

---

bindings/pydrake/systems/primitives_py.cc
bindings/pydrake/systems/test/primitives_test.py

Add bindings for DiscreteDerivative and StateInterpolatorWithDiscreteDerivative.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12770)

Add bindings for DiscreteDerivative

---

tutorials/BUILD.bazel
tutorials/mathematical_program.ipynb
tutorials/nonlinear_program.ipynb

I will add the tutorial on IK and trajectory optimization in the next PRs. Since both IK and trajectory optimization are special cases of NLP, I add the NLP tutorial first.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12744)

Add a tutorial on nonlinear programming.

---

bindings/pydrake/examples/acrobot_py.cc
bindings/pydrake/examples/test/acrobot_test.py
bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/general_test.py
examples/pendulum/pendulum_plant.cc
examples/pendulum/pendulum_plant.h

and make pendulum/acrobot examples use that api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12794)

bind kinetic and potential energy system method in python

---

tools/workspace/styleguide/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12800)

workspace: Upgrade styleguide latest commit

---

tools/workspace/ghc_filesystem/package.BUILD.bazel
tools/workspace/ghc_filesystem/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12799)

workspace: Upgrade ghc_filesystem to latest release 1.3.0

---

third_party/com_github_pybind_pybind11/mkdoc.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12818)

Remove unused code from mkdoc.py

---

tools/workspace/styleguide/BUILD.bazel

@jwnimmer-tri pointed out here:
https://github.com/RobotLocomotion/drake/pull/12776#issuecomment-595315508
Closes #12821.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12822)

Add no_kcov to cpplint_unittest

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py
geometry/render/gl_renderer/BUILD.bazel
geometry/render/gl_renderer/defs.bzl
geometry/render/gl_renderer/no_render_engine_gl_factory.cc
geometry/render/gl_renderer/opengl_context.cc
geometry/render/gl_renderer/opengl_context.h
geometry/render/gl_renderer/opengl_includes.h
geometry/render/gl_renderer/render_engine_gl.cc
geometry/render/gl_renderer/render_engine_gl.h
geometry/render/gl_renderer/render_engine_gl_factory.cc
geometry/render/gl_renderer/render_engine_gl_factory.h
geometry/render/gl_renderer/test/no_render_engine_gl_test.cc
geometry/render/gl_renderer/test/render_engine_gl_test.cc
tools/install/libdrake/build_components.bzl
tools/workspace/default.bzl
tools/workspace/opengl/BUILD.bazel
tools/workspace/opengl/package-macos.BUILD.bazel
tools/workspace/opengl/repository.bzl

Relates to #12594
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12623)

Platform conditional build of a skeleton OpenGL render engine

---

multibody/tree/spatial_inertia.h
multibody/tree/test/spatial_inertia_test.cc

Massless bodies are commonly defined in URDF/SDF models as a proxy for "frames". Algorithms such at the Composite Body Inertia for computing the mass matrix fail if the user provides a kinematic chain of massless bodies. This use case is so common that we decided to support it. 
This PR allows combining the spatial inertia for massless bodies, solving the issue with kinematic chains of massless bodies.
cc'ing @mitiguy 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12809)

SpatialInertia support for massless bodies.

---

math/matrix_util.h
math/test/matrix_util_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12813)

adds math::IsPositiveDefinite

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py
common/symbolic_expression.h
common/symbolic_polynomial.cc
common/symbolic_polynomial.h
common/test/symbolic_polynomial_matrix_test.cc
common/test/symbolic_polynomial_test.cc

See https://github.com/RobotLocomotion/drake/issues/12832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12835)

Add more methods to symbolic::Polynomial

---

tools/workspace/buildifier/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12836)

workspace: Update buildifier to latest release 2.0.0

---

bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/analysis_py.cc
bindings/pydrake/systems/controllers_py.cc
bindings/pydrake/systems/test/analysis_test.py
systems/analysis/BUILD.bazel
systems/analysis/region_of_attraction.cc
systems/analysis/region_of_attraction.h
systems/analysis/test/region_of_attraction_test.cc
systems/controllers/dynamic_programming.h
systems/primitives/symbolic_vector_system.h

Implements the convex formulation of searching for a maximal level set of a Lyapunov candidate.
Working towards #10863
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12827)

First implementation of general region of attraction code.

---

CMakeLists.txt
bindings/pydrake/autodiff_types_pybind.h
doc/bazel.rst
doc/developers.rst
doc/getting_help.rst

Wait for #12846 before merging this one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12845)

doc: Note that GCC 7.5 is now Ubuntu's default compiler

---

geometry/render/gl_renderer/BUILD.bazel
geometry/render/gl_renderer/render_engine_gl.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12850)

Build and lint fixes for the OpenGL render engine

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py
bindings/pydrake/visualization/BUILD.bazel
bindings/pydrake/visualization/plotting.py
bindings/pydrake/visualization/test/plotting_test.py

generalizes beyond the polynomial of degree two case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12854)

Plot sub-level sets of symbolic::Expression

---

bindings/pydrake/test/trajectories_test.py
bindings/pydrake/trajectories_py.cc
common/trajectories/test/piecewise_polynomial_test.cc
common/trajectories/trajectory.h

This is a little sugar to make it easier to evaluate a trajectory at many times in a single call. (it's particularly helpful in python).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12855)

Adds Trajectory::vector_values

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/mathematical_program_test.cc

Related:  #12833
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12847)

Add MathematicalProgram::MakePolynomial

---

math/matrix_util.h
systems/analysis/region_of_attraction.cc
systems/analysis/test/region_of_attraction_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12864)

Support region of attraction when Vdot is indefinite at the origin.

---

geometry/proximity/bounding_volume_hierarchy.cc

to capture the work done on using the volume heuristic as an alternate splitting algorithm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12860)

Add documentation for alternate bvh heuristics

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.h
solvers/test/mathematical_program_test.cc

Close #12841 
It uses the existing method `AddConstraint(Eigen::Array<Formula>)`. So I add only a single test case which shows its use case. Let me know if you want more tests.
+@hongkai-dai for feature-review, please.
+@RussTedrake for platform-review, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12858)

Add MathematicalProgram::AddConstraint(Eigen::Matrix<Formula>)

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/test/geometry_render_engine_gl_test.py
bindings/pydrake/test/geometry_test.py

This has been split up from render-gl-port to keep PR size down
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12861)

Refactor Python binding test for render engine gl

---

multibody/benchmarks/acrobot/acrobot.urdf
multibody/parsing/detail_urdf_parser.cc
multibody/parsing/test/acrobot_parser_test.cc
multibody/parsing/test/detail_urdf_parser_test.cc
multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf

Fixes #12859
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12863)

Parse joint effort limits from URDF

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py

Closes #12880 
@EricCousineau-TRI  for feature review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12883)

pydrake multibody: Add bindings for MultibodyPlant output ports

---

tutorials/mathematical_program.ipynb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12885)

Add MakeSolver to mathematical program tutorial.

---

multibody/plant/BUILD.bazel
multibody/plant/test/multibody_plant_forward_dynamics_test.cc
multibody/tree/articulated_body_inertia.h

Closes #12640.
cc'ing @edrumwri
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12879)

Fix ABI::IsPhysicallyValid() to avoid false negatives.

---

bindings/pydrake/doc/LICENSE.TXT
bindings/pydrake/doc/conf.py
bindings/pydrake/doc/pydrake_sphinx_extension.py
bindings/pydrake/doc/sphinx.LICENSE.txt

Resolves: https://github.com/RobotLocomotion/drake/issues/12604
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12787)

pybind11 docs: Monkey patch sphinx to get custom sorted docs

---

bindings/pydrake/multibody/inverse_kinematics_py.cc
bindings/pydrake/multibody/test/inverse_kinematics_test.py
multibody/inverse_kinematics/BUILD.bazel
multibody/inverse_kinematics/inverse_kinematics.cc
multibody/inverse_kinematics/inverse_kinematics.h
multibody/inverse_kinematics/point_to_point_distance_constraint.cc
multibody/inverse_kinematics/point_to_point_distance_constraint.h
multibody/inverse_kinematics/test/inverse_kinematics_test.cc
multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
multibody/inverse_kinematics/test/point_to_point_distance_constraint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12896)

Add PointToPointDistanceConstraint.

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py
common/symbolic_polynomial.cc
common/symbolic_polynomial.h
common/test/symbolic_polynomial_test.cc
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/mathematical_program_test.cc
systems/analysis/region_of_attraction.cc

Related #12848
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12902)

Add MathematicalProgram::Reparse

---

systems/analysis/BUILD.bazel
systems/analysis/antiderivative_function.cc
systems/analysis/antiderivative_function.h
systems/analysis/bogacki_shampine3_integrator.h
systems/analysis/dense_output.cc
systems/analysis/dense_output.h
systems/analysis/explicit_euler_integrator.cc
systems/analysis/explicit_euler_integrator.h
systems/analysis/hermitian_dense_output.cc
systems/analysis/hermitian_dense_output.h
systems/analysis/implicit_euler_integrator.cc
systems/analysis/implicit_integrator.cc
systems/analysis/integrator_base.cc
systems/analysis/radau_integrator.cc
systems/analysis/runge_kutta2_integrator.cc
systems/analysis/runge_kutta2_integrator.h
systems/analysis/scalar_dense_output.cc
systems/analysis/scalar_dense_output.h
systems/analysis/scalar_view_dense_output.cc
systems/analysis/scalar_view_dense_output.h
systems/analysis/semi_explicit_euler_integrator.cc
systems/analysis/semi_explicit_euler_integrator.h
systems/analysis/stepwise_dense_output.cc
systems/analysis/stepwise_dense_output.h
systems/analysis/velocity_implicit_euler_integrator.cc
systems/analysis/velocity_implicit_euler_integrator.h

Inspired by #12904.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12908)

analysis: Add default_scalars annotations where still absent

---

bindings/pydrake/systems/analysis_py.cc
bindings/pydrake/systems/test/general_test.py

@EricCousineau-TRI for feature review
cc @mntan3 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12920)

pydrake simulator: Bind simulator realtime rate accessors
