geometry/proximity/bounding_volume_hierarchy.cc, geometry/proximity/bounding_volume_hierarchy.h, geometry/proximity/test/bounding_volume_hierarchy_test.cc
A BVH can now be collided against a half space. Ultimately, this will support hydroleastic contact between a *soft* half space and a rigid mesh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12840)
=> [geometry] Add half space-BVH collision support

geometry/proximity/BUILD.bazel, geometry/proximity/mesh_plane_intersection.cc, geometry/proximity/mesh_plane_intersection.h, geometry/proximity/plane.h, geometry/proximity/test/mesh_plane_intersection_test.cc
This is the atomic operation to support rigid half space vs soft volume mesh intersection. It robustly intersects a single tet with a plane in such a way that no redundant edge-plane intersection tests are performed and (as a by-product) doesn't introduce duplicate vertices in the resulting contact surface mesh.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12802)
=> [geometry] Add plane-tet intersection

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic_polynomial.cc, common/symbolic_polynomial.h, common/test/symbolic_polynomial_test.cc
A syntax sugar to compare if two polynomials are almost equal.
Resolves #12817
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12853)
=> Add Polynomial::CoefficientsAlmostEqual function.

multibody/plant/hydroelastic_contact_info.h
Documents conventions in HydroelasticContactInfo regarding frames and how bodies A and B associate to geometries M and N respectively.
Per review discussion in #12745.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12806)
=> Documents conventions in HydroelasticContactInfo

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py
to enable:
```
deriv = f.EvalTimeDerivatives(context).CopyToVector()
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12865)
=> bind CopyToVector for ContinuousState

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/solver_base.h, solvers/test/solver_base_test.cc
Users shouldn't have to pass in {} and/or None everywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12866)
=> Add default std::nullopt arguments to SolverBase::Solve()

bindings/pydrake/systems/test/general_test.py, common/test_utilities/drake_py_unittest_main.py
This used to be the case for python2, but was lost in the transition to python3 due to changes to `unittest.main` semantics.
The python3 `unittest.main` added the following new semantics:
```python
if warnings is None and not sys.warnoptions:
self.warnings = 'default'
```
Because we apply our warning filters prior to calling `unittest.main()`, the unittest filter for any and all `Warning` instances trumps our more custom filters.
Towards #12873.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12874)
=> test_utilities: Promote deprecations to errors in pydrake unit tests

multibody/parsing/package_map.cc, multibody/parsing/test/parser_test.cc
This relates to issue #12870. It illustrates what the issue documents and is using CI to test the effect of the two deleted lines more globally across the Drake ecosystem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12871)
=> [parsing] Add unit test to cover Parser's automatic search for packages

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py, math/BUILD.bazel, math/matrix_util.h, math/quadratic_form.cc, math/quadratic_form.h, math/test/quadratic_form_test.cc, systems/analysis/BUILD.bazel, systems/analysis/region_of_attraction.cc, systems/analysis/test/region_of_attraction_test.cc
and uses it in RegionOfAttraction.
Rederived (much more carefully/thoroughly) from
https://github.com/RobotLocomotion/drake/blob/last_sha_with_original_matlab/drake/matlab/util/balanceQuadForm.m
with more documentation and testing.
adds python bindings for this and the main matrix_util methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12875)
=> Adds utility to "balance" two quadratic forms

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/inverse_kinematics/inverse_kinematics.cc, multibody/inverse_kinematics/inverse_kinematics.h, multibody/inverse_kinematics/test/inverse_kinematics_test.cc
As mentioned in https://github.com/RobotLocomotion/drake/issues/12849
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12872)
=> InverseKinematics allows ignoring joint limits in the constructor.

systems/analysis/test/region_of_attraction_test.cc
It is known to fail with Mosek (#12876), but it passes with CSDP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12881)
=> Adds the "star" region of attraction test

systems/analysis/test/region_of_attraction_test.cc
Related to #12876.
Apparently, running with
```
CC=clang CXX=clang++ bazel  test --compilation_mode=dbg --config=memcheck_everything  region_of_attraction_test
```
caused mosek to simply fail to solve the problem.  I've disabled this test entirely for mosek now.
Disconcerting for sure.  Would be good to root cause this.  #12876 has all of the discussion/details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12899)
=> Hotfix for #12898

geometry/proximity/BUILD.bazel, geometry/proximity/bounding_volume_hierarchy.cc, geometry/proximity/bounding_volume_hierarchy.h, geometry/proximity/mesh_half_space_intersection.h, geometry/proximity/mesh_intersection.h, geometry/proximity/mesh_plane_intersection.cc, geometry/proximity/plane.h, geometry/proximity/posed_half_space.h, geometry/proximity/test/bounding_volume_hierarchy_test.cc, geometry/proximity/test/contact_surface_utility_test.cc, geometry/proximity/test/mesh_half_space_intersection_test.cc, geometry/proximity/test/mesh_intersection_test.cc, geometry/proximity/test/mesh_plane_intersection_test.cc, geometry/proximity/test/plane_test.cc, geometry/proximity/test/posed_half_space_test.cc
Plane was originally internal::HalfSpace. It had previously pulled out to be used more widely. To avoid collision with the geometry::HalfSpace name it was renamed Plane. However, this led to confusion due to the fact that it was reporting a *signed distance*. The resolution was to rename it to be a *posed half space*. I.e., rather than strictly defined in its canonical frame, it could be defined in any frame.
This performs the renaming, updates usages and documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12820)
=> [geometry] rename internal::Plane to internal::PosedHalfSpace

systems/trajectory_optimization/BUILD.bazel, systems/trajectory_optimization/direct_transcription.cc, systems/trajectory_optimization/direct_transcription.h, systems/trajectory_optimization/test/direct_transcription_test.cc
First step towards generalizing DirectTranscription to use a user-specified integrator.  This one just replaces the hard-coded Euler integrator with the IntegratorBase version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12889)
=> Use IntegratorBase in DirectTranscription

tools/workspace/dreal/repository.bzl
It uses `-Wfoo` instead of `-Werror=foo` in dreal.bzl file. Then, it includes `-Werror` in its `.bazelrc` file which is not loaded when dReal is built as an external.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12905)
=> Use dReal 4.20.03.4

geometry/geometry_state.h, multibody/plant/multibody_plant.h, multibody/plant/test/kuka_iiwa_model_tests.h, multibody/plant/test/multibody_plant_jacobians_test.cc, systems/framework/cache_entry.cc, systems/framework/framework_common.h, systems/framework/input_port.h, systems/framework/output_port.h, systems/framework/system_base.h, systems/framework/test/system_base_test.cc
In #12551 we added a fast new method to `SystemBase` for validating contexts, and deprecated the old ones.  However, one old method was also exposed via `internal::SystemMessageInterface` but the commit did not update that API.  We do that here now, along with some TODOs to enable the checks in Release mode later.
This turns up a bug in unit test code where a `MultibodyPlant<AutoDiffXd>` had conflicting `system_id` values during calculation, because we were accidentally transmogrifying it implicitly(!) while passing it into a function but supplying a `Context` created by a correctly-transmogrified plant.  The implicit conversion was allowed because `MultibodyPlant`'s scalar-converting copy constructor was not marked `explicit`.
This is very bad, so we also add `explicit` to …
=> framework: Update internal for ValidateContext rename

systems/framework/BUILD.bazel, systems/framework/diagram.cc, systems/framework/diagram_output_port.h, systems/framework/input_port.h, systems/framework/leaf_output_port.h, systems/framework/output_port.h, systems/framework/port_base.cc, systems/framework/port_base.h, systems/framework/system_base.h, systems/framework/test/input_port_test.cc, systems/framework/test/output_port_test.cc
This brings it in line with how InputPort is phrased.
Also fix a related misleading pervasive use of system_base to refer to a SystemMessageInterface instead of a SystemBase.
As noted in #12891.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12906)
=> framework: OutputPort should not depend on SystemBase

systems/framework/BUILD.bazel, systems/framework/input_port.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/output_port.h, systems/framework/witness_function.cc, systems/framework/witness_function.h
Also clean up a few oddities (dead code, etc.) in `WitnessFunction` along the way.
Towards #12814.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12894)
=> framework: Break WitnessFunction dependency cycle

solvers/snopt_solver.cc
As of C++17, we can use "inline" to avoid repeating ourselves.
In a stackoverflow [error message](https://stackoverflow.com/questions/60289642/error-while-compiling-project-with-drake-using-bazel-on-mac) we see:
```console
drake/solvers/snopt_solver.cc:197:36: error: variable 'g_iprint' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
```
This tidy might fix that error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12914)
=> snopt: Tidy up storage declaration

bindings/pydrake/systems/pyplot_visualizer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12915)
=> Improve args and doc for pyplot_visualizer

bindings/pydrake/solvers/osqp_py.cc, bindings/pydrake/solvers/test/osqp_solver_test.py, solvers/osqp_solver.cc, solvers/osqp_solver.h, solvers/test/osqp_solver_test.cc
cc @pangtao22
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12916)
=> Add dual solution to OsqpSolverDetails.

bindings/pydrake/doc/LICENSE.TXT, bindings/pydrake/doc/conf.py, bindings/pydrake/doc/pydrake_sphinx_extension.py, bindings/pydrake/doc/sphinx.LICENSE.txt
Towards: https://github.com/RobotLocomotion/drake/issues/12604
PR #12787 was reverted (#12910), due to failures on Mac.
This PR fixes them.
The Mac failures can be reproduced on Linux by:
- `apt-get remove python3-sphinx`.
- `python3.6 -m pip  install sphinx sphinx_rtd_theme`
- `bazel test --test_output=all --nocache_test_results //bindings/pydrake/doc:gen_sphinx_test`
The first commit `652aa39`, has already been reviewed in #12787 .
Please review the  the second one.
Closes #12604 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12921)
=>  pybind11 docs: Fix sphinx patch for versions > 1.6.7

geometry/proximity/BUILD.bazel, geometry/proximity/contact_surface_utility.cc, geometry/proximity/contact_surface_utility.h, geometry/proximity/test/contact_surface_utility_test.cc
In working on (future) hydroelastic features, I found that we needed to handle centroid calculation more elegantly than simply returning a vector full of NaN. That led to making the computation more robust to dependencies as well as adding utilities for validating "good" parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12909)
=> [geometry] Utility for adding polygon to contact surface handles degeneracies

examples/multibody/rolling_sphere/README.md, examples/multibody/rolling_sphere/make_rolling_sphere_plant.cc, geometry/proximity/BUILD.bazel, geometry/proximity/hydroelastic_callback.h, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/hydroelastic_internal.h, geometry/proximity/mesh_plane_intersection.cc, geometry/proximity/mesh_plane_intersection.h, geometry/proximity/plane.h, geometry/proximity/test/hydroelastic_callback_test.cc, geometry/proximity/test/hydroelastic_internal_test.cc, geometry/proximity/test/mesh_plane_intersection_test.cc, geometry/proximity/test/plane_test.cc, geometry/proximity/test/posed_half_space_test.cc, geometry/test/proximity_engine_test.cc
Previous commits introduced the mathematical basis for intersecting a half space boundary plane with a tetrahedron. This builds on that atomic operation:
- Allow instantiation of hydroelastic representation of rigid half space.
- Define internal representation of rigid half space.
- Evaluation of ContactSurface from intersection of VolumeMesh with rigid half space.
- Restore the rolling sphere demo to use a rigid half space as ground instead of the box previously used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12901)
=> Enable use of rigid half space in hydroelastic contact

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
The struct was previously a nested class. However, it interfered with the logic for hashing drake::Value instances of the type. This moves it from being nested to the internal namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12932)
=> Move HydroelasticFallbackCacheData out of MultibodyPlant

multibody/tree/test/door_hinge_test.cc, systems/analysis/antiderivative_function.h, systems/analysis/initial_value_problem.cc, systems/analysis/initial_value_problem.h, systems/analysis/scalar_initial_value_problem.h, systems/analysis/test/antiderivative_function_test.cc, systems/analysis/test/initial_value_problem_test.cc, systems/analysis/test/scalar_initial_value_problem_test.cc
and similar for ScalarInitialValueProblem and AntiderivativeFunction
+ adds deprecations
because SpecifiedValues is very generic, and drake already has a better name for this concept.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12931)
=> Rename `InitialValueProblem::SpecifiedValues` to `ODEContext`

attic/multibody/rigid_body_plant/drake_visualizer.cc, bindings/pydrake/BUILD.bazel, bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/piecewise_quaternion.h, common/trajectories/test/piecewise_polynomial_generation_test.cc, common/trajectories/test/piecewise_polynomial_test.cc, common/trajectories/test/piecewise_quaternion_test.cc, examples/kuka_iiwa_arm/iiwa_world/multi_arm_with_gripper_demo.cc, examples/kuka_iiwa_arm/kuka_plan_runner.cc, examples/planar_gripper/run_planar_gripper_trajectory_publisher.cc, manipulation/planner/robot_plan_interpolator.cc, manipulation/util/test/trajectory_utils_test.cc, manipulation/util/trajectory_utils.h, systems/analysis/hermitian_dense_output.h, systems/analysis/test/hermitian_dense_output_test.cc, systems/controllers/test/zmp_test_util.cc, systems/trajectory_optimization/direct_collocation.cc, systems/trajectory_optimization/direct_collocation.h, systems/trajectory_optimization/direct_transcription.cc, systems/trajectory_optimization/direct_transcription.h, systems/trajectory_optimization/multiple_shooting.h, systems/trajectory_optimization/test/direct_collocation_test.cc
We've had a long-running incorrect use of notation in our trajectory code.
Correct:
- breaks and knots both mean the time indices.
- sample points (or sometimes "control points") indicate the values at those times.
We've been writing e.g. Cubic(breaks, knots).
I've changed all instances (apart from the IK code) to replace knots with either breaks (when time was intended) or samples (when the values were intended).
Deprecating pybind argument names... woohoo!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12939)
=> trajectories: rename knots to samples

.gitignore
CLion's lack of full symbol support and constant freezing is driving me to try another.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12943)
=> add /.vscode/ to .gitignore

tools/dynamic_analysis/asan.sh
Because we use C++ binary libraries from the host OS (instead of compiling all C++ code from source) there can be false positives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12945)
=> tools: Disable container_overflow checks under asan

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/all.py, bindings/pydrake/systems/system_sliders.py, bindings/pydrake/systems/test/system_sliders_test.py
Pass in an arbitrary port for a Drake system and it produces tk sliders to control them. Useful for testing simulation models quickly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12925)
=> Add slider-based controller for input ports

bindings/pydrake/polynomial_py.cc, common/polynomial.cc, common/polynomial.h, common/test/polynomial_test.cc, common/test_utilities/random_polynomial_matrix.h, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_generation_test.cc, common/trajectories/test/piecewise_polynomial_test.cc, common/trajectories/test/random_piecewise_polynomial.h, common/trig_poly.h, solvers/system_identification.h
instead of CoefficientType and a multitude of typedefs; now closer to comforming to drake standard notation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12948)
=> cleanup: use typename T in polynomial classes

geometry/render/gl_renderer/BUILD.bazel, geometry/render/gl_renderer/defs.bzl, geometry/render/gl_renderer/opengl_context.cc, geometry/render/gl_renderer/opengl_context.h, geometry/render/gl_renderer/opengl_includes.h, geometry/render/gl_renderer/render_engine_gl.cc, geometry/render/gl_renderer/test/opengl_context_test.cc, setup/ubuntu/binary_distribution/packages-bionic.txt, setup/ubuntu/source_distribution/packages-bionic.txt, tools/install/libdrake/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/x11/BUILD.bazel, tools/workspace/x11/package-macos.BUILD.bazel, tools/workspace/x11/repository.bzl
This has been split up from render-gl-port to keep PR size down
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12862)
=> Add opengl context and X11 dependency for use in render engine gl

geometry/proximity/BUILD.bazel, geometry/proximity/mesh_half_space_intersection.cc, geometry/proximity/mesh_half_space_intersection.h, geometry/proximity/test/mesh_half_space_intersection_test.cc
The previous mesh-half space mesh intersection had been written in an isolated context. This updates the interface/APIs to provide slightly different functionality:
- The resultant contact surface *mesh* is defined in the world frame.
- Every intersected polygon uses the common centroid-generating algorithm for adding itself into the data.
- Modify the interface to be compatible with broadphase culling.
- Modification that input meshes are *strictly* double-valued.
- Found and corrected indexing error; face-local indices [0, 3) were being passed to access mesh-local vertex positions (indexed in the range [0, N)). This was discovered only indirectly in debug build because the polygon constructed had the wrong normal compared to the face it came from.
Furthermore, the implementation has …
=> [geometry] update mesh-half space intersection for full hydroleastic compatibility

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
MBP has a nested class that is stored in a cache entry. The hash logic associated with the drake::Value type doesn't work well with nested classes of templated classes (it introduces a "namespace" with a template parameter). This clutters up the console with warnings that don't help the end user at all. SO, for now, we'll pull the nested class out and put it in an internal namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12953)
=> Move MBP::HydroelasticContactInfoAndBodySpatialForces into internal

.gitignore
because it turns out that having .vscode symlinked to a remote directory simplifies my multi-machine workflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12956)
=> ignore /.vscode instead of /.vscode/

geometry/render/gl_renderer/BUILD.bazel
See #12962.
https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-nightly-valgrind-memcheck/493/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12963)
=> gl_renderer: Disable opengl_context_test under memcheck

systems/analysis/test_utilities/implicit_integrator_test.h, systems/analysis/velocity_implicit_euler_integrator.cc, systems/analysis/velocity_implicit_euler_integrator.h
Add Error Control to Velocity-Implicit Euler Integrator, third PR of #12528
This commit:
1. Implements error control by taking two half-sized steps and estimating the error as the difference between the solution from the large step and the solution from two half-sized steps.
2. Changes IntegratorBase to report statistics on the small steps for any steps "taken", while the error control and step-size limit logic still operates on the large step size.
3. Updates documentation to explain the statistics and derive the error estimation order.
4. (Passive) Enables the error-control tests for VelocityImplicitEulerTest, by turning on the supports_error_estimation() flag.
--- …
=> Add Error Control to Velocity-Implicit Euler Integrator, third PR of #12528

systems/framework/system.h
I'm faced with adding a bunch of comments for new methods in System and tired of wrestling with the old-school comments there. For easy review, this PR does nothing but change the comment style; I didn't even realign the text to take advantage of the 2500 characters of meaningless line noise that I got rid of.
This makes the comment style in `system.h` the same as in `system_base.h` (among many other framework headers). There is still an eclectic set of commenting styles in systems/framework, but this is a step in the right direction.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12968)
=> Change system.h comment style to the more-compact form

common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_test.cc
Got a little hairy, but I needed to handle the case with scale = -1.0 because I need this for the tvlqr implementation.  (I need to integrate the riccati equation backwards in time, but our simulators don't support it, so I have to reverse the solution).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12966)
=> trajectories: Add ScaleTime to PiecewisePolynomial

geometry/proximity/BUILD.bazel, geometry/proximity/mesh_half_space_intersection.cc, geometry/proximity/mesh_half_space_intersection.h, geometry/proximity/test/mesh_half_space_intersection_test.cc
This adds one more API where an actual `ContactSurface` is computed (not just the mesh of the contact surface).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12954)
=> Add compute contact surface computation to mesh half space code

.gitignore
gitkraken doesn't support global .gitignore
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12985)
=> ignore .history -- for vscode + gitkraken workflow

systems/framework/leaf_system.h
I have to add comments for new methods in LeafSystem. Before I do I want to convert the whole file from the verbose `/// ` form to the more-compact `/**` form. For easy review, this PR does nothing but change the comment style; I didn't even realign the text to take advantage of the 3200 characters of line noise that are now gone. (In two places I also moved a `// TODO` comment to above the doxygen comment to avoid interfering with the Python docs generator.)
This makes the comment style in leaf_system.h the same as in system.h and system_base.h (among many other framework headers). There is still an eclectic set of commenting styles in systems/framework, but this is a step in the right direction.
Relates #12968
--- …
=> Change leaf_system.h comment style to the more-compact form

WORKSPACE, tools/workspace/bazel_skylib/repository.bzl, tools/workspace/rules_pkg/repository.bzl, tools/workspace/rules_python/repository.bzl
Upgrade bazel_skylib to latest release 0.9.0.
Upgrade rules_pkg to latest release 0.2.5.
Upgrade rules_python to latest commit.
Respell a `load()` because `lib.bzl` is deprecated now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12978)
=> workspace: Upgrade imported bazel rules to latest

common/trajectories/BUILD.bazel, common/trajectories/exponential_plus_piecewise_polynomial.cc, common/trajectories/exponential_plus_piecewise_polynomial.h, common/trajectories/piecewise_polynomial.h, common/trajectories/piecewise_quaternion.h, common/trajectories/piecewise_trajectory.cc, common/trajectories/piecewise_trajectory.h, common/trajectories/test/piecewise_trajectory_test.cc, common/trajectories/trajectory.h
note: the signature of one virtual method changed in a way that I did not know how to deprecate properly:
```
MatrixX<T> value(double) const
```
is now
```
MatrixX<T> value(const T& t) const
```
and derived classes will need to update this to compile.  (unfortunately, the compiler gives a relatively verbose and unhelpful stream of errors because the derived classes become abstract classes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12986)
=> trajectories: support default scalars in PiecewiseTrajectory

tools/workspace/cc/repository.bzl, tools/workspace/expat/repository.bzl, tools/workspace/gfortran/repository.bzl, tools/workspace/ibex/repository.bzl, tools/workspace/libblas/repository.bzl, tools/workspace/liblapack/repository.bzl, tools/workspace/numpy/repository.bzl, tools/workspace/openblas/repository.bzl, tools/workspace/opengl/repository.bzl, tools/workspace/pkg_config.bzl, tools/workspace/python/repository.bzl, tools/workspace/snopt/repository.bzl, tools/workspace/which.bzl, tools/workspace/x11/repository.bzl, tools/workspace/zlib/repository.bzl
Rules that interrogate the host system (e.g., compiler paths, pkg-config paths, python library paths) should be marked with "configure = True" so that "bazel sync --configure" knows where to look for possible changes.
This is helpful to recover from homebrew include paths changing out from under us (#12989).
Running "bazel sync" finds several typos in our repository.bzl files, now fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12988)
=> workspace: Annotate repository rules with configure=True

geometry/proximity/contact_surface_utility.cc, geometry/proximity/contact_surface_utility.h, geometry/proximity/mesh_half_space_intersection.cc, geometry/proximity/mesh_intersection.h, geometry/proximity/test/mesh_half_space_intersection_test.cc
For the same reason we cull faces in the contact surface mesh between soft and rigid meshes, the potential contact surface between rigid mesh and soft half space requires the same functionality. This commit:
- Refactors the core culling logic for reuse.
- Adds the culling to mesh - half space intersection
- Adds a test showing culling is happening.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12976)
=> [geometry] Soft half space - rigid mesh contact must cull backfaces

common/trajectories/BUILD.bazel, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_test.cc, examples/kuka_iiwa_arm/kuka_plan_runner.cc
No virtual methods nor type-specific shenanigans this time.  Just straight up double => T (or const T&, ...).
I've deprecated a typedef that was used only sometimes and imho obscured readability rather than helped it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12991)
=> trajectories: support default scalars in PiecewisePolynomial

geometry/proximity/BUILD.bazel, geometry/proximity/make_box_mesh.cc, geometry/proximity/make_box_mesh.h
If the make_box_mesh.h file is included into multiple compilation units all of the in-header functions get compiled into each unit. Many of the functions are declared `static` so they don't collide. However, one is not and that actually causes linker-errors.
Rather than just declaring the single offending function static/inline, this moves the implementation into a .cc file to improve overall compilation time. There are three functions that only exist to serve the implementation of the mesh generation. Their declarations have been kept in the header file because they are directly tested in make_box_mesh_test.
Also, the function comments were changed from /** */ to /* */ reflecting their non-doxygen, internal:: status.
Otherwise, this introduces no new code and doesn't change the text of …
=> Refactor make box mesh code

systems/analysis/hermitian_dense_output.h, systems/analysis/test/hermitian_dense_output_test.cc
now with support for default scalars.
(I should have done this version in #12957, but didn't realize it until I was able to push forward the default scalar support for PiecewisePolynomail).  This technically changes the API that I introduced last week; i think it's safe to assume that nobody was using it yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13006)
=> trajectories: construct HermitianDenseOutput from PiecewisePolynomial

solvers/BUILD.bazel, solvers/constraint.cc, solvers/constraint.h, solvers/test/constraint_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13004)
=> throw error when the constraint lower and upper bounds size don't match.

examples/multibody/rolling_sphere/README.md, examples/multibody/rolling_sphere/make_rolling_sphere_plant.cc, examples/multibody/rolling_sphere/make_rolling_sphere_plant.h, examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc, geometry/proximity/BUILD.bazel, geometry/proximity/hydroelastic_callback.h, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/hydroelastic_internal.h, geometry/proximity/test/hydroelastic_callback_test.cc, geometry/proximity/test/hydroelastic_internal_test.cc, geometry/proximity_properties.cc, geometry/proximity_properties.h, geometry/test/proximity_properties_test.cc, multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
This exercises the underlying geometric logic to implement a soft half space.
- Introduce the soft half space hydroelastic reprepsentation.
- Add dispatch logic for soft half space-rigid mesh.
- updates the rolling sphere demo so it can exercise the soft half space.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12975)
=> [geometry] Adding soft half space into contact query

systems/analysis/BUILD.bazel, systems/analysis/initial_value_problem.cc, systems/analysis/integrator_base.cc, systems/analysis/integrator_base.h, systems/analysis/test/runge_kutta2_integrator_test.cc, systems/analysis/test_utilities/generic_integrator_test.h
This breaks an API (without deprecation) by changing the return type of `IntegratorBase::StopDenseIntegration` and `IntegratorBase::get_mutable_dense_output` to be a `PiecewiseTrajectory`.  After dicussion with @sammy-tri, we decided that this API was officially deep and obscure to warrant this change.  `InitialValueProblem` was the only known consumer of this method (in general, we do not have workflows that would work with the `Integrator` directly, and these APIs were not exposed through `Simulator`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13008)
=> integrators: replace DenseOutput with PiecewiseTrajectory

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/all.py, bindings/pydrake/solvers/branch_and_bound_py.cc, bindings/pydrake/solvers/test/branch_and_bound_test.py, bindings/pydrake/test/all_test.py, solvers/BUILD.bazel, solvers/branch_and_bound.cc
Resolves #12997 cc @TobiaMarcucci
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13002)
=> Add python binding for branch_and_bound

tools/install/bazel/repo_template.bzl
There's no particular need to insist that install_prereqs exists, and as it happens our Docker images do not contain it.
Closes #13010.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13016)
=> install: Fix drake_bazel_installed use in docker

examples/kinova_jaco_arm/jaco_lcm.cc, examples/kinova_jaco_arm/jaco_simulation.cc, examples/kinova_jaco_arm/test/jaco_lcm_test.cc, lcmtypes/lcmt_jaco_status.lcm
This is a breaking change as the LCM message does not have a
deprecation period.  Due to the lack of external users I think this is
OK.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13017)
=> Add external torque fields for the jaco status message

examples/kuka_iiwa_arm/BUILD.bazel, examples/kuka_iiwa_arm/iiwa_common.cc, examples/kuka_iiwa_arm/iiwa_common.h, examples/kuka_iiwa_arm/move_iiwa_ee.cc, manipulation/util/BUILD.bazel, manipulation/util/robot_plan_utils.cc, manipulation/util/robot_plan_utils.h, manipulation/util/test/robot_plan_utils_test.cc
These are items I've used in personal branches exploring planning/sim
with different robots that don't currently have drake examples (or at
least hadn't used this functionality yet).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13015)
=> Move some helper functions from iiwa to manipulation/util

attic/BUILD.bazel, attic/multibody/BUILD.bazel, attic/multibody/rigid_body_tree.cc, attic/warning.cc, attic/warning.h, tools/install/libdrake/build_components.bzl
Relates #12158.
It seems like almost all attic code must create a RBT before being used, so this warning should catch most uses.  If we later find uses not covered here, then we can invoke this new function from those locations as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13030)
=> attic: Add once-per-process deprecation warning

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/revolute_spring_parsing_test.sdf
If `<spring_stiffness>` is defined in the sdf, then we add a RevoluteSpring on the joint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12992)
=> Added support for revolute joint spring in multibody plant parser

bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/general_test.py, systems/analysis/BUILD.bazel, systems/analysis/integrator_base.h, systems/analysis/radau_integrator.h, systems/analysis/simulator.h, systems/analysis/simulator_flags.cc, systems/analysis/simulator_flags.h, systems/analysis/simulator_gflags.cc, systems/analysis/test/simulator_flags_test.cc
Closes #12873.  Relates #12903.
This extends `pydrake.systems.Simulator.reset_integrator`'s deprecation window because up to this point there was no viable replacement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13013)
=> analysis: Add simulator_flags helper

common/polynomial.cc
Add to the polynomial.cc file the inclusion of the `numeric` header  and  of the `using std::accumulate` directive as it uses the `accumulate` function.
The code that invokes `accumulate` was moved in PR https://github.com/RobotLocomotion/drake/pull/12950 from the `common/symbolic_expression_cell.cc` that already had the correct include and using directives. 
I guess that this not created in the platforms covered in CI due to some transitive include.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13046)
=> common: Fix includes and using in polynomial.cc

common/trajectories/piecewise_trajectory.cc, common/trajectories/piecewise_trajectory.h, common/trajectories/test/piecewise_polynomial_test.cc, examples/rimless_wheel/test/rimless_wheel_test.cc, systems/analysis/BUILD.bazel, systems/analysis/integrator_base.cc, systems/analysis/integrator_base.h, systems/analysis/test/integrator_base_test.cc, systems/analysis/test_utilities/explicit_error_controlled_integrator_test.h
- Adds a series of tests checking the dense output for error-controlled integration and witness isolation.
- Fixes a few curiousities in the PiecewiseTrajectory / PiecewisePolynomial stack, including the unexplained large tolerance required between successive segments in a piecewisetrajectory.
- IntegratorBase::DoDenseStep is no longer virtual, because the logic within has gotten more complicated and we need a more narrow entry point for any subclasses which eventually want to override the default dense output interpolation strategy.  [THIS IS TECHNICALLY A CHANGE TO THE PUBLIC API, BUT I BELIEVE IT IS ONE THAT HAS NO CONSUMERS].
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomo …
=> integrators: dense integration works with witness isolation

examples/kuka_iiwa_arm/iiwa_world/BUILD.bazel
These started hitting timeouts in coverage tests after #13015 merged,
which confuses me since none of the code which moved in that PR
appears to be invoked by these tests.  Since the entire directory is
scheduled for deprecation in a couple of weeks, I don't think it's
worth further investigation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13059)
=> Disable coverage tests on deprecated iiwa modules

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/tree/BUILD.bazel, multibody/tree/ball_rpy_joint.cc, multibody/tree/ball_rpy_joint.h, multibody/tree/joint.h, multibody/tree/test/ball_rpy_joint_test.cc
Creates `BallRpyJoint`, a three degree of freedom rotational joint that uses `SpaceXYZMobilizer` under the hood (and therefore defines orientation with Euler Angles).  The joint includes damping but not any spring force (much like `RevoluteJoint`).  In addition, joint limits in MBP are not enforced for this joint and there is no parsing added in this pr.  I would love to discuss fixing either/both of these deficiencies.
Relates #12404 
cc @sherm1 @amcastro-tri
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13039)
=> multibody: Implement BallRpyJoint

setup/mac/source_distribution/Brewfile
Mac unprovisioned jobs began failing on April 14th. For example:
[mac-catalina-unprovisioned-clang-bazel-nightly-release](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-catalina-unprovisioned-clang-bazel-nightly-release/128/console)
[mac-mojave-unprovisioned-clang-bazel-continuous-snopt-packaging](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-mojave-unprovisioned-clang-bazel-continuous-snopt-packaging/929/console)
with the following error message:
```
[4:02:28 AM]  Tapping homebrew/cask-fonts
[4:02:28 AM]  Using robotlocomotion/director
[4:02:36 AM]  Error: Cask 'font-dejavu-sans' is unavailable: No Cask with this name exists. Did you mean one of these?
[4:02:36 AM]  font-dejavu-sans-mono-for-powerline
[4:02:36 AM] …
```
=> Fix Mac setup script: Rename DejaVu fonts

bindings/pydrake/systems/lcm_py.cc, bindings/pydrake/systems/test/lcm_test.py, systems/lcm/lcm_interface_system.h
I want this for usage in Anzu, but it seems that this wasn't bound in Python.
I guess I saw this review go by, and I should have raised an issue with multiple inheritance (I think the same thing could have been accomplished with composition?). Meh, too late, and deprecation for an inheritance structure sounds nigh impossible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13067)
=> py systems: Bind LcmInterfaceSystem

bindings/pydrake/systems/test/lcm_test.py
This reverts commit 102a7f577cc22b41cf8a69aee61ccc17f5bde004 from #13067 but leaves its new file overview comment intact.
Also remove another `memq` that snuck in in the subsequent commit.
Running tests via `bazel run` is it is brittle and unsupported; we should not pretend otherwise, especially when doing so would add copypasta into dozens of unit test source files.
If we want to move towards supporting it, we should enhance `drake_cc_googletest_main` and `drake_py_unittest_main` to partially re-implement the test environment that bazel sets up for us, not change individual unit tests to cope.
Use `--test_output` to control output, not `bazel run`.
--- …
=> Partially revert "Make lcm_test pass under ... bazel run ..."

bindings/pydrake/systems/lcm_py.cc
Follow-up to #13607
Messed up the `keep_alive` ordering - oops!
(Ran into this while tinkering with it Anzu)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13075)
=> py systems: Fix keep_alive bug for lcm

systems/analysis/test_utilities/discontinuous_spring_mass_damper_system.h, systems/analysis/test_utilities/implicit_integrator_test.h, systems/analysis/test_utilities/spring_mass_damper_system.h, systems/analysis/velocity_implicit_euler_integrator.cc, systems/analysis/velocity_implicit_euler_integrator.h
Add Automatic Differentiated Jacobians to Velocity-Implicit Euler Integrator, fourth PR of #12528
This commit:
1. Adds automatic differentiation as a velocity-Jacobian computation scheme for the velocity-implicit Euler integrator, by following the model of ImplicitIntegrator<T>::ComputeAutoDiffJacobian().
2. Refactors ComputeLOfY() based on the templated <U> IntegratorBase<T>::EvalTimeDerivatives() to enable this computation.
3. Fixes the tests so that they reset integrators between testing the different Jacobian computation schemes, to force Jacobian recomputations.
4. Removes the boolean flags that skip tests that require AutoDiff'd Jacobians.
--- …
=> Add Automatic Differentiated Jacobians to Velocity-Implicit Euler Integrator, fourth PR of #12528

systems/analysis/BUILD.bazel, systems/analysis/implicit_integrator.cc, systems/analysis/test/implicit_euler_integrator_test.cc, systems/analysis/test/radau_integrator_test.cc, systems/analysis/test/velocity_implicit_euler_integrator_test.cc, systems/analysis/test_utilities/BUILD.bazel, systems/analysis/test_utilities/implicit_integrator_test.h, systems/analysis/test_utilities/stationary_system.cc, systems/analysis/test_utilities/stationary_system.h
This commit:
1. Adds a QuadraticSystemAccuracy test to verify that the implicit Euler and velocity-implicit Euler integrators have second-order error estimation (by halving the step size and comparing the error estimate) and that they achieve the exact right error on a quadratic system.
2. Adds a few lines to verify that the implicit integrators support error estimation.
3. Tests the StationarySystem with an Autodiff'd Jacobian Computation scheme, to make sure AutoDiff Jacobians function properly when the derivative does not depend on the state.
4. Fixes a bug in the AutoDiff Jacobian Computation where if the derivative does not depend on the state, implicit integrators segfault because the iteration matrix adds a Jacobian matrix with 0 width to an identity square matrix.
Also tagging …
=> Add missing implicit integration tests for error control and autodiff

doc/developers.rst, setup/ubuntu/source_distribution/install_prereqs.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13032)
=> Update recommended Bazel version to 3.0

common/polynomial.cc, common/polynomial.h, common/test/polynomial_test.cc, common/trajectories/piecewise_polynomial.cc
When `T = symbolic::Expression` and `T = AutoDiffXd`, `Polynomial<T>(0)` does not
compile as there are two possible candidates.
```
1. Polynomial(const T& scalar);
2. explicit Polynomial(const std::string& varname, const unsigned int num = 1);
```
This commit addresses the problem by:
A. Make 2 have no default arguments.
B. Provide Polynomial<double>(const std::string&) not to break code using the current API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13076)
=> Fix drake::Polynomial<T>(0) problem

systems/primitives/symbolic_vector_system.cc, systems/primitives/test/symbolic_vector_system_test.cc
It was previously possible to get incorrect gradients out if the derivative vectors passed in were uninitialized for some elements of the context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13077)
=> primitives: fix SymbolicVectorSystem autodiff when some derivatives are empty

multibody/parsing/package_map.cc, multibody/parsing/test/package_map_test.cc
This change is done for uniformity with the rest of drake codebase, that already uses the explicit conversion: 
* https://github.com/RobotLocomotion/drake/blob/v0.16.1/multibody/parsing/package_map.cc#L86
* https://github.com/RobotLocomotion/drake/blob/v0.16.1/common/drake_path.cc#L22
* https://github.com/RobotLocomotion/drake/blob/325b90cb5788164d1fd71a0f9f515d95221827f2/multibody/parsing/test/detail_path_utils_test.cc#L66
Furthermore according to the C++ standard, the implicit conversion from std::filesystem::path to std::string is only supported on POSIX-based systems, see https://stackoverflow.com/questions/57377349/implicit-conversion-between-stdfilesystempath-and-stdstring-should-it-hap ,  so this fixes the  compilation of these files on  non-POSIX configuration, see discussion in …
=> parsing: Avoid to use implicit conversion from std::filesystem::path to std::string

doc/python_bindings.rst
Everywhere else in Drake says 3.8/bin which apparently always exists, whereas 3/bin reportedly only sometimes exists.
Amends #13031 per https://github.com/RobotLocomotion/drake/pull/13031#pullrequestreview-396064297.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13093)
=> doc: Use python@3.8/bin not python@3/bin

bindings/pydrake/systems/meshcat_visualizer.py, geometry/proximity/test/volume_mesh_test.cc, multibody/plant/multibody_plant.h
Some things I came across while reading documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13095)
=> Made typo fixes in documentation

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py
Since this assert has bitten me multiple times when I add geometry programmatically and try to visualize it in Meshcat, I wanted to propose a fix.  This was the solution proposed in a [slack discussion](https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1572984455042100) but given that the above TODO references a closed issue, there might be a better solution.
@EricCousineau-TRI for discussion/feature review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13018)
=> pydrake meshcat: Fix name parsing bug

bindings/pydrake/pydrake_doxygen.h
As mentioned in the slack thread https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1587349559014100?thread_ts=1587344554.013800&cid=C3YB3EV5W
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13101)
=> Fix the broken link to py_reference in pydrake_doxygen.h

common/trajectories/exponential_plus_piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_test.cc, systems/framework/test/diagram_builder_test.cc
There should not be anything special about zero here.
The Riccati solver in the finite-horizon LQR sometimes starts at negative time, and should be able to use these constant trajectories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13096)
=> trajectories:  PiecewisePolynomial constant trajectory is ∀t ∈ [-∞, ∞]

systems/primitives/demultiplexer.cc, systems/primitives/multiplexer.cc
As these files use `std::accumulate` it is necessary to include `<numeric>` . 
Problem detected compiling the files on [`clang-cl`](https://clang.llvm.org/docs/UsersManual.html#clang-cl) with [MSVC's `STL`](https://github.com/microsoft/STL).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13104)
=> primitives: Fix missing include in multiplexer.cc and demultiplexer.cc

geometry/geometry_state.cc, geometry/scene_graph.h, geometry/test/geometry_state_test.cc, geometry/test_utilities/dummy_render_engine.h, multibody/parsing/detail_scene_graph.cc, multibody/parsing/detail_scene_graph.h, multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/detail_urdf_geometry.h, multibody/parsing/test/detail_scene_graph_test.cc, multibody/parsing/test/detail_urdf_geometry_test.cc, multibody/parsing/test/urdf_parser_test/accepting_renderer.urdf, multibody/plant/multibody_plant.cc, multibody/plant/test/multibody_plant_test.cc
This allows for a geometry to define a property in its perception properties which determines whether a RenderEngine will implement it or not. It works by matching the renderer's name with an optionally whitelisted set of "accepting" renderers.
Add new tag to the SDF and URDF files.
- URDF:
```
<visual>
...
<drake:accepting_renderer name="renderer_name"/>
</visual>`
```
- SDF: 
```
<visual>
...
<drake:accepting_renderer>renderer_name
</drake:accepting_renderer>
</visual>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13053)
=> [render] Allow a geometry to target a renderer

bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py, systems/controllers/BUILD.bazel, systems/controllers/dynamic_programming.cc, systems/controllers/dynamic_programming.h, systems/controllers/test/dynamic_programming_test.cc
Takes the input port as an argument, and can ignore the scene graph abstract state (related to #9501)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13113)
=> controllers: FittedValueIteration supports MBP+SceneGraph

geometry/proximity/mesh_intersection.cc, geometry/proximity/mesh_intersection.h
Move mesh_intersection code from .h to .cc.
1. Rename mesh_intersection.cc to mesh_intersection-orig.cc. Change BUILD.bazel.
2. Copy mesh_intersection.h to mesh_intersection.cc. No change to BUILD.bazel.
mesh_intersection.cc is dead code at this step.
(No step to de-indent mesh_intersection.cc by two spaces because there is no `class`.)
3. Finally edit mesh_intersection.h, mesh_intersection.cc, BUILD.bazel,
remove mesh_intersection-orig.cc.  This is the step needed review the most.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13086)
=> Move mesh_intersection code from .h to .cc

multibody/inverse_kinematics/BUILD.bazel, solvers/ipopt_solver.cc
Calling memcpy on nullptr is undefined.
Closes #9475.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13111)
=> solvers: Fix memcpy undefined behavior in unconstrained optimization

systems/framework/context_base.cc, systems/framework/framework_common.h, systems/framework/system_base.h, systems/framework/test/dependency_tracker_test.cc, systems/framework/test/leaf_context_test.cc
The default prerequisite set for an output port is `{all_sources_ticket()}`, which is the most conservative choice. In a System with multiple input ports, this can lead to an apparent algebraic loop in the containing Diagram since it will appear that every output port depends on every input port. This occurred recently in practice and fixing it was awkward since it required the author to unpack the contents of "all sources" to leave off just the input ports. That creates a maintenance problem since the meaning of "all sources" will likely change over time. 
This PR provides a new ticket `all_sources_except_input_ports()` and redefines `all_sources_ticket()` to be `{all_sources_except_input_ports(), all_input_ports()}`.
--- …
=> Add a dependency ticket for all sources excluding input ports

bindings/pydrake/BUILD.bazel, bindings/pydrake/common/module_py.cc, bindings/pydrake/common/test/module_test.py, bindings/pydrake/polynomial_py.cc, bindings/pydrake/test/polynomial_test.py, bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/constants.h, common/polynomial.cc, common/polynomial.h, common/test/polynomial_test.cc, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_generation_test.cc, common/trajectories/test/piecewise_polynomial_test.cc
Also generalizes Polynomial::IsApprox to support multivariate polynomials.
NOTE: The behavior of IsApprox has changed from the previous implementation for univariate polynomials in two ways:
1) IsApprox will now fail if the polynomials have different variables.
2) The comparison is now absolute instead of relative.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13108)
=> common::polynomial : Add Subsitute(var, Polynomial)

common/trajectories/piecewise_polynomial.cc
Fixes commit c523f2aae3bc073cd42fee45a21ee255dc1a5ba6 (#13108).
Example of the error:
https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-continuous-address-sanitizer/2065/
```
[6:35:29 PM]  FAIL: //common/trajectories:piecewise_polynomial_test (see /media/ephemeral0/ubuntu/workspace/linux-bionic-clang-bazel-continuous-address-sanitizer/_bazel_ubuntu/e359602e3b676a6fb93325203587fb48/execroot/drake/bazel-out/k8-dbg/testlogs/common/trajectories/piecewise_polynomial_test/test.log)
[6:35:29 PM]  INFO: From Testing //common/trajectories:piecewise_polynomial_test:
[6:35:29 PM]  ==================== Test output for //common/trajectories:piecewise_polynomial_test:
[6:35:29 PM]  Using drake_cc_googletest_main.cc
[6:35:29 PM]  
[6:35:29 PM]  [==========] Running 10 …
```
=> trajectories: Fix use-after-free

geometry/benchmarking/mesh_intersection_benchmark.cc, geometry/proximity/BUILD.bazel, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/make_ellipsoid_mesh.h, geometry/proximity/make_sphere_mesh.h, geometry/proximity/tessellation_strategy.h, geometry/proximity/test/bounding_volume_hierarchy_test.cc, geometry/proximity/test/hydroelastic_internal_test.cc, geometry/proximity/test/make_ellipsoid_field_test.cc, geometry/proximity/test/make_ellipsoid_mesh_test.cc, geometry/proximity/test/make_sphere_field_test.cc, geometry/proximity/test/make_sphere_mesh_test.cc, multibody/hydroelastics/hydroelastic_field_sphere.h, multibody/hydroelastics/test/contact_surface_from_level_set_test.cc
Rather than creating a sphere by sub-dividing *all* edges of the previous level of refinement, we refine only those edges on the surface of the sphere.
The resultant mesh has a single interior vertex (at the sphere origin) and all of the resolution increases curvature. In contrast to the interior vertices which increases the number of tets by a factor of 8 each time, this only increases it by a factor of 4.
It retains an option to tessellate on the interior as well, but no longer defaults to that.
This also provides a mechanism through proximity properties to toggle what type of sphere tessellation is used. An optional parameter (kHydroGroup, "sparse_mesh") has been added which will control whether the sphere gets tessellated on the interior or not (defaults to not).
This cascaded to a …
=> Add alternate Sphere volume mesh generation

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/BUILD.bazel, multibody/plant/propeller.cc, multibody/plant/propeller.h, multibody/plant/test/propeller_test.cc
Includes python bindings.
Partially resolves #12401.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13135)
=> multibody: adds a Propeller model for use with MultibodyPlant

common/trajectories/BUILD.bazel, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_test.cc
Prior to this PR, evaluating a `PiecewisePolynomial<AutoDiffXd>` at `t == end_time()` would return a `MatrixX<AutoDiffXd>` with empty derivatives, due to the way that Eigen's implementation of `min` for `AutoDiffXd` handles the case where the arguments are equivalent. After this PR, the `MatrixX<AutoDiffXd>` will contain the derivatives for the final segment evaluated at `end_time()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13080)
=> trajectories: Preserve time derivatives when evaluating PiecewisePolynomial at end time

multibody/tree/ball_rpy_joint.cc, multibody/tree/ball_rpy_joint.h, multibody/tree/joint.h, multibody/tree/prismatic_joint.cc, multibody/tree/prismatic_joint.h, multibody/tree/revolute_joint.cc, multibody/tree/revolute_joint.h, multibody/tree/test/ball_rpy_joint_test.cc, multibody/tree/test/prismatic_joint_test.cc, multibody/tree/test/revolute_joint_test.cc
This is a PR to have the `Joint` class store a default value and to pass the value to its mobilizer implementation upon construction of the joint implementation.
- Solves the issue of mobilizers storing default joint positions (#13065)
\cc @amcastro-tri @EricCousineau-TRI @sherm1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13105)
=> Make joint store default value

geometry/query_object.h, geometry/test/query_object_test.cc, geometry/test/scene_graph_test.cc
This doesn't change the *nature* of the test. Merely the spelling. It eliminates some of the overhead cruft such that the test harness has direct access to the private/protected elements of `QueryObject`.
A follow-up PR will be breaking up the QueryObject and the decomposed instances will follow this same testing pattern.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13136)
=> [geometry] Refactor QueryObject test to a more efficient spelling.

math/bspline_basis.cc, math/bspline_basis.h, math/test/bspline_basis_test.cc
This enables implicit conversion from `BsplineBasis<double>` to `BsplineBasis<T>`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13057)
=> Add BsplineBasis<T>(const BsplineBasis<double>&)

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py
Enables writing Python LeafSystems which declare ports using this object
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13156)
=> py geometry: Bind QueryObject constructor

common/trajectories/BUILD.bazel, common/trajectories/bspline_trajectory.cc, common/trajectories/bspline_trajectory.h, common/trajectories/test/bspline_trajectory_test.cc
This fixes the behavior of `BsplineTrajectory<AutoDiffXd>::value()`, when its input has non-empty derivatives.
Resolves #13150.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13149)
=> common: Use BsplineBasis<T> in BsplineTrajectory<T>

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/gurobi_py.cc, bindings/pydrake/solvers/ipopt_py.cc, bindings/pydrake/solvers/mosek_py.cc, bindings/pydrake/solvers/nlopt_py.cc, bindings/pydrake/solvers/osqp_py.cc, bindings/pydrake/solvers/scs_py.cc, bindings/pydrake/solvers/snopt_py.cc, bindings/pydrake/solvers/test/gurobi_solver_test.py
Backwards-incompatible: This changes all `*SolverDetails` structures to be read-only for Python. This was deemed OK to break for now.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13152)
=> Add python binding for GurobiSolverDetails.

bindings/pydrake/trajectories_py.cc, common/trajectories/BUILD.bazel, common/trajectories/bspline_trajectory.cc, common/trajectories/bspline_trajectory.h, common/trajectories/exponential_plus_piecewise_polynomial.h, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/piecewise_quaternion.cc, common/trajectories/piecewise_quaternion.h, common/trajectories/test/piecewise_trajectory_test.cc, common/trajectories/test/trajectory_test.cc, common/trajectories/trajectory.cc, common/trajectories/trajectory.h
I've started the NVI pattern here, rather than adding another public virtual.
It's inconsistent with the rest of the class, but the goal is to move this direction.
Also started trajectory.cc => trajectory is now @tparam default_scalar, instead of @tparam ANY
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13144)
=> trajectories: add Trajectory::has_derivative and EvalDerivative

examples/acrobot/BUILD.bazel, examples/acrobot/acrobot_plant.cc, examples/acrobot/acrobot_plant.h, examples/acrobot/test/acrobot_plant_test.cc, systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/leaf_system.h, systems/framework/system.cc, systems/framework/system.h, systems/framework/system_base.h, systems/framework/test/diagram_test.cc, systems/framework/test/leaf_system_test.cc
Introduces System API for the implicit form of the system equations:
```c++
System::CalcImplicitTimeDerivativesResidual(context, proposed_derivatives, &residual);
VectorX = System::AllocateImplicitTimeDerivativesResidual();
```
The default is that the residual is the same length as the continuous state. A LeafSystem can change that during construction via
```
LeafSystem::DeclareImplicitTimeDerivativesResidualSize(n);
```
Provides a residual form of the Acrobot example reimplemented from #12828.
Resolves #12869.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13068)
=> Add System support for implicit equations

bindings/pydrake/common/test/wrap_pybind_test.py, bindings/pydrake/common/test/wrap_test_util_py.cc, bindings/pydrake/common/wrap_pybind.h, bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py, systems/controllers/finite_horizon_linear_quadratic_regulator.cc, systems/controllers/finite_horizon_linear_quadratic_regulator.h, systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
as discussed on slack, this uses a work-around to binding the std::unique_ptr member variables in FiniteLQRResult.
also includes a few small improvements to finite-horizon LQR, in preparation for the supporting discrete-time systems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13145)
=> controllers: add python bindings for finite-horizon LQR

geometry/profiling/BUILD.bazel, geometry/profiling/README.md, geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc, tools/workspace/models/files.bzl, tools/workspace/models/package.BUILD.bazel, tools/workspace/models/repository.bzl
I have been keeping this example for kcachegrind profiling in my own branch.  Now I am becoming confused because I am experimenting off my own branch in multiple ways.
It will help me streamline my workflow if I can push this example into master.  It is not intended for general users.  I can remove this example when my profiling work is done.
@sherm1 @SeanCurtis-TRI for discussion about pushing this example into master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13138)
=> [geometry] Example for contact-surface profiling: rigid bowl, soft ball.

geometry/render/gl_renderer/dev/BUILD.bazel, geometry/render/gl_renderer/dev/buffer_dim.h, geometry/render/gl_renderer/dev/load_mesh.cc, geometry/render/gl_renderer/dev/load_mesh.h, geometry/render/gl_renderer/dev/test/buffer_dim_test.cc, geometry/render/gl_renderer/dev/test/load_mesh_test.cc
1. LoadMeshFromObj made more testable by given a std::istream overload.
2. Documentation in `load_mesh.*` and `buffer_dim.h` updated.
2. Unit tests added for LoadMeshFromObj and BufferDim.
This beefs up the state of the code in dev, prepatory to moving it out of dev.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13174)
=> [geometry/dev] Cosmetic clean up and missing tests

attic/multibody/parsers/BUILD.bazel, attic/multibody/parsers/xml_util.cc, multibody/parsing/BUILD.bazel, multibody/parsing/package_map.cc, multibody/parsing/test/package_map_test.cc, tools/workspace/BUILD.bazel, tools/workspace/tinydir/BUILD.bazel, tools/workspace/tinydir/package.BUILD.bazel, tools/workspace/tinydir/stub.cc
The tinydir external is now deprecated and will be removed on 2020-08-01.
Closes #13173.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13180)
=> parsing: Rewrite package.xml crawl to avoid using @tinydir

attic/build_macros.bzl
The attic code is deprecated and is not receiving many (if any) updates, so the chance of breaking these variants is small.  We'll conserve CI resources by skipping them.
In particular, coverage builds and pre-merge lsan builds should benefit; the (few) macOS sanitizer builds should also benefit.
A straw poll in `#platform_review` slack favors this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13184)
=> attic: Reduce CI coverage of extra variants

tools/ubuntu-bionic.bazelrc
On Ubuntu, we purposefully do not use pip.  By removing the homedir from imports, we can ensure more reproducible builds and tests.
Closes #8475.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13190)
=> tools: Disable python imports from ~/.local (pip -U)

third_party/com_github_finetjul_bender/BUILD.bazel
The default include paths are already correct.  Adding an extra suffix results in "undeclared inclusion" warnings downstream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13189)
=> third_party: Remove spurious include path

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/BUILD.bazel, geometry/perception_query_object.cc, geometry/perception_query_object.h, geometry/proximity_query_object.cc, geometry/proximity_query_object.h, geometry/query_object.cc, geometry/query_object.h, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/perception_query_object_test.cc, geometry/test/proximity_query_object_test.cc
This breaks up the monolithic QueryObject into three classes. Ultimately, it decouples proximity queries from perception queries. This is necessary for an up-coming feature: mesh painting. With all
queries in a single port, it increases the chance for a false algebraic loop.
This does *not* deprecate the queries on QueryObject yet (there is a follow-up PR that will do that).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13161)
=> [geometry] Parcel QueryObject queries into unique classes

bindings/pydrake/pydrake_doxygen.h, doc/python_bindings.rst
Motivated by this StackOverflow question:
https://stackoverflow.com/questions/61346034/is-it-possible-to-support-python-binding-for-addjoint-that-takes-x-pf-x-bm-as-a
Also, for the fact that I had to make mods to C++ APIs to enable this, e.g. 04e20b8a (#9345) and 3f1547f4 (#12389) ;)
FYI @RussTedrake @sherm1 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13134)
=> pydrake doc: Add user and dev docs for C++ template considerations

bindings/pydrake/common/__init__.py, bindings/pydrake/common/module_py.cc, bindings/pydrake/common/test/module_test.py, bindings/pydrake/solvers/test/mathematicalprogram_test.py
From follow-up comment: https://github.com/RobotLocomotion/drake/pull/13183#issuecomment-622195628
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13195)
=> py common: Use kDrakeAssertIsArmed instead of _DRAKE_ASSERT_IS_ARMED

doc/getting_help.rst
When asking on here, saw these small issues:
https://stackoverflow.com/q/61536025/7829525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13203)
=> getting_help: Remove stray asterisk, add template on helper commands

bindings/pydrake/systems/test/custom_test.py, bindings/pydrake/systems/test/system_sliders_test.py, common/test/cpplint_wrapper.py, manipulation/util/meshlab_to_sdf.py, third_party/com_github_pybind_pybind11/mkdoc.py, tools/lint/bazel_lint.bzl, tools/lint/buildifier.py, tools/lint/library_lint.bzl, tools/lint/python_lint.bzl, tools/skylark/drake_cc.bzl, tools/workspace/deb.bzl, tools/workspace/github.bzl, tools/workspace/pycodestyle/repository.bzl, tools/workspace/semantic_version/repository.bzl
Fix new formatting nits and invalid string literals that it now flags.
Upgrade semantic_version to latest release 2.8.5.
The W514 (must place binary operator like `+` to start a line, instead of at end of prior line) is tripped everywhere in drake, so I'm deferring it to a separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13197)
=> workspace: Upgrade pycodestyle to latest release 2.5.0

common/test_utilities/drake_py_unittest_main.py
This change implies stricter error checking for future tests.
Previously, Drake deprecations that occurred at import-time in a module (not when running a unittest) did not get translated into an error. This causes them to be an error.
Split off from https://github.com/RobotLocomotion/drake/pull/12430#issuecomment-621830535
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13191)
=> drake_py_unittest: Force Drake deprecation warnings at import to be errors

tools/skylark/pybind.bzl
Came across this while working on #13225 
I saw a duplication of an error for `value_py.cc`:
```
==================== Test output for //bindings/pydrake/common:py/pybind_coverage_data_clang_format_lint:
...
clang_format_lint.py: Linting bindings/pydrake/common/value_py.cc
ERROR: bindings/pydrake/common/value_py.cc needs clang-format
note: fix via /usr/bin/clang-format-6.0 -style=file -i bindings/pydrake/common/value_py.cc
================================================================================
...
==================== Test output for //bindings/pydrake/common:py/value.so_clang_format_lint:
clang_format_lint.py: Linting bindings/pydrake/common/value_py.cc
ERROR: bindings/pydrake/common/value_py.cc needs clang-format
note: fix via /usr/bin/clang-format-6.0 -style=file -i …
```
=> pybind: Avoid duplicate linting with `add_pybind_coverage_data`

geometry/test/geometry_properties_test.cc
As part of https://github.com/robotlocomotion/drake/pull/13166
Keeping this simple for now. I don't want to generalize this at the moment, but it would be good to confirm copy / move stats for `Value<>`. (I don't see anything explicitly testing that). I assume we have similar tests elsewhere.
Kinda creeps towards what `pybind11` has:
https://github.com/pybind/pybind11/blob/a54eab92d265337996b8e4b4149d9176c2d428a6/tests/constructor_stats.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13232)
=> geometry_properties: Explicitly test number of copies / moves

doc/developers.rst, doc/stackoverflow_notifications.rst
Adds to the Drake "For Developers" guidance instructions for how to get an email notification when a user asks a `drake`-tagged question on Stackoverflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13216)
=> Add instructions for getting Stackoverflow drake-tag notifications.

tools/workspace/BUILD.bazel, tools/workspace/fcl/package.BUILD.bazel, tools/workspace/octomap/BUILD.bazel, tools/workspace/octomap/package.BUILD.bazel, tools/workspace/octomap/stub.cc
Closes #13227.
On my laptop, a `bazel build @fcl//:fcl` went from:
Release mode:
- total child process down from 130 to 71
- total cpu-seconds down from 315 to 170 (so -46%)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13230)
=> tools: Trim FCL to only compile the parts we need

examples/acrobot/BUILD.bazel, examples/acrobot/test/run_swing_up_traj_optimization.cc, systems/controllers/finite_horizon_linear_quadratic_regulator.cc, systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
Also had to remove support for symbolic::Expression in the finite horizon LQR controller, pending resolution of #12253.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13250)
=> controllers: add example of finite horizon LQR working on the acrobot

doc/issues.rst
This PR proposes three new component label descriptions for organizing GitHub issues:
- component: multibody plant
- component: system framework
- component: simulator (includes integrators)
These are some big, mostly disjoint areas typically addressed by the Dynamics team. There are more under geometry but we haven't settled on the component names yet. These three seem natural and map fairly well to people's specialties so are likely to be useful in assigning work. We will add more when it's clear what would be useful.
I'll wait to create the actual GitHub labels until this PR is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13256)
=> Add some Dynamics component labels for GitHub issues

geometry/proximity/BUILD.bazel, geometry/proximity/mesh_field_linear.cc, geometry/proximity/mesh_field_linear.h, geometry/proximity/test/mesh_field_linear_test.cc
Use linear functions:
f(x,y,z) = ∇f⋅(x,y,z) + D, where D = f(0,0,0)
on tetrahedra directly, instead of converting (x,y,z) to barycentric coordinates and perform barycentric interpolation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13140)
=> Use linear f(x,y,z) on tetrahedron directly instead of barycentric interpolation.

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/tree/BUILD.bazel, multibody/tree/ball_rpy_joint.h, multibody/tree/prismatic_joint.h, multibody/tree/space_xyz_mobilizer.h, multibody/tree/test/free_rotating_body_test.cc, multibody/tree/test/universal_joint_test.cc, multibody/tree/universal_joint.cc, multibody/tree/universal_joint.h, multibody/tree/weld_joint.h
Creates `UniversalJoint`, a two degree of freedom rotational joint. The joint includes damping but not any spring force (much like RevoluteJoint). In addition, joint limits in MBP are not enforced for this joint and there is no parsing added in this pr. I would love to discuss fixing either/both of these deficiencies.
Towards #12404 
Also removes unused friend class `JointTester` from several joints and fixes a bug that made `SpaceXYZMobilizer` a floating mobilizer.
cc @sherm1 @amcastro-tri
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13055)
=> multibody: Implement UniversalJoint

setup/ubuntu/source_distribution/packages-bionic.txt, setup/ubuntu/source_distribution/packages-focal.txt, tools/workspace/default.bzl, tools/workspace/ruby/repository.bzl, tools/workspace/sdformat/3bbd303.patch, tools/workspace/sdformat/BUILD.bazel, tools/workspace/sdformat/embed_sdf.py, tools/workspace/sdformat/package.BUILD.bazel, tools/workspace/sdformat/repository.bzl
Cherry-pick a patch from sdformat upstream to make the data embedding easier, and then re-implement the embedder in python.
Deprecate the `@ruby` external.
Closes #13231.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13262)
=> workspace: Remove dependency on ruby

multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/very_old_version.sdf
Follow-up from #13262.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13265)
=> parsing: Add regression test for libsdformat version upgrades

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/BUILD.bazel, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_generation_test.cc, common/trajectories/test/piecewise_polynomial_test.cc
These are in service of the implementation of the affine terms in the finite-horizon LQR code (which will be PR'd once this lands).
also includes the python bindings (and some bindings that I had skipped in my previous commit).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13269)
=> trajectories: add Lagrange Interpolating Polynomial and Block(i,j,p,q)

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py
Motivation is to be able to make an "auto" printer system.
Using the `FunctionSystem` [prototype I mentioned in Slack](https://drakedevelopers.slack.com/archives/C2CK4CWE7/p1588895156032800), I can do something like this:
```py
def make_printer(cls, fmt=None, print=print):
if fmt is None:
fmt = "{}"
def print_value(value: cls) -> None:
print(fmt.format(value))
printer = FunctionSystem(print_value, set_name=False)
return printer
def connect_printer(builder, output, dt, fmt=None):
cls = type(output.Allocate().get_value())
printer = make_printer(cls, fmt=fmt)
builder.AddSystem(printer)
builder.Connect(output, printer.get_input_port(0))
...
connect_printer(builder, system.get_output_port(0), 0.1)
```
--- …
=> py systems: Bind OutputPort.Allocate(), DiagramBuilder.empty(), .GetMutableSystems()

tools/workspace/sdformat/BUILD.bazel, tools/workspace/sdformat/package.BUILD.bazel
Don't install extra files (closes #13025).
Remove unused boost dependency.
Remove unused BUILD rules.
Update license to add BSL-1.0 for the boost code vendored into sdformat directly now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13268)
=> workspace: Remove vestigial sdformat build rules

doc/doxygen.h, systems/analysis/integrator_base.h
Per issue #12890, this Doxygen-only PR does the following:
- Adds a top-level `Module` to collect Drake conventions for terminology and notation.
- Moves the existing "Multibody Terminology and Conventions" module under the new one.
- Adds a new module defining Drake's conventions and terminology for "accuracy" and "tolerance". 
The intent with the new section is that using these terms differently (or using other terminology like "precision" instead) would be a defect in new Drake code, and that there is now an `@ref` link we can use in Drake documentation rather than having to explain it all repeatedly.
The Modules section will look like this:
Resolves #12890.
--- …
=> Add module for "accuracy" and "tolerance" conventions

attic/multibody/kinematics_cache.cc, tools/lint/clang_format.py, tools/lint/drakelint.py, tools/lint/formatter.py, tools/lint/test/formatter_test.py
Towards #13236.  Requires #13260.
Remove test cases for the inl pattern.  Drake does not permit this pattern anymore, and supporting it under clang-format-9 is difficult.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13259)
=> tools: Upgrade to clang-format-9 for includes

tools/workspace/meshcat_python/repository.bzl
Per request from @rdeits: https://github.com/RobotLocomotion/drake/pull/13050#issuecomment-620339421
Also, includes caching fix from: https://github.com/rdeits/meshcat-python/issues/55
Requires: 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13155)
=> workspace: Bump meshcat_python to latest commit

multibody/parsing/BUILD.bazel, multibody/parsing/detail_common.cc, multibody/parsing/detail_common.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc
WIP to parse a custom tag to specify `LinearBushingRollPitchYaw` force elements from an SDF or URDF file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13255)
=> Parses custom LinearBushingRollPitchYaw tag in SDF/URDF

common/schema/dev/BUILD.bazel, common/schema/dev/stochastic.cc, common/schema/dev/stochastic.h, common/schema/dev/test/stochastic_test.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13295)
=> schema: Add stochastic types

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/module_py.cc, bindings/pydrake/common/test/module_test.py, bindings/pydrake/common/test/value_test.py, bindings/pydrake/common/test/value_test_util_py.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py, bindings/pydrake/systems/test/general_test.py, bindings/pydrake/systems/test/scalar_conversion_test.py, common/BUILD.bazel, common/nice_type_name.cc, common/nice_type_name.h, common/nice_type_name_override.cc, common/nice_type_name_override.h, common/test/nice_type_name_test.cc
Resolves #13237
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13194)
=> pydrake: Override NiceTypeName::Get(ptr) when possible

attic/multibody/joints/fixed_joint.cc, attic/multibody/joints/helical_joint.cc, attic/multibody/joints/prismatic_joint.cc, attic/multibody/joints/quaternion_ball_joint.cc, attic/multibody/joints/quaternion_floating_joint.cc, attic/multibody/joints/revolute_joint.cc, attic/multibody/joints/roll_pitch_yaw_floating_joint.cc, geometry/proximity/make_sphere_mesh.h, multibody/tree/ball_rpy_joint.cc, multibody/tree/joint.h, multibody/tree/prismatic_joint.h, multibody/tree/revolute_joint.cc, multibody/tree/revolute_spring.cc, multibody/tree/universal_joint.cc, multibody/tree/weld_joint.cc, systems/analysis/test/scalar_view_dense_output_test.cc
A function return that looks like
```c++
SomeType f() {
SomeType local_variable;
// ...
return std::move(local_variable);  // DON'T DO THIS
}
```
is called a "pessimizing" move and prevents copy ellision, where the space for the return value can be used for the local variable so no copying is required. See [here](https://developers.redhat.com/blog/2019/04/12/understanding-when-not-to-stdmove-in-c/) for an explanation. Pessimizing moves will generate compiler warnings in the near future.
Thanks to @jwnimmer-tri for pointing this out.
There are also many other cases return `return std::move(something);` is simply redundant.
To avoid future warnings and cargo culting, this PR removes all the pessimizing and redundant `return std::move`s I could find in Drake.
--- …
=> Remove redundant and pessimizing return std::moves

geometry/geometry_state.h, geometry/query_object.cc, geometry/query_object.h, geometry/render/render_engine.cc, geometry/render/render_engine_vtk.cc, geometry/render/render_engine_vtk.h, geometry/render/test/render_engine_test.cc, geometry/render/test/render_engine_vtk_test.cc, geometry/shape_specification.h, geometry/test/geometry_state_test.cc, geometry/test/query_object_test.cc
These are the required changes to Drake to support Anzu PR 4729.
1. GeometryState can release pointers to RenderEngine implementaitons
- It is generally accessed via SceneGraphInspector.
2. RenderEngineVtk is changed to be sub-classable
- It's *private* copy constructor has been made protected so sub-classes
can use it.
- It gives derived classes access to the actors.
- Fixes a bug that previously went unnoticed; `SetDefaultLightPosition`
didn't declare override of the virtual RenderEngine method.
3. Allow for customization of unsupported geometry messages in
ShapeReifier.
TODO:
Consider python bindings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13288)
=> [geometry] Support more RenderEngineVtk and ShapeReifier customizations

manipulation/BUILD.bazel, manipulation/__init__.py, manipulation/util/BUILD.bazel, manipulation/util/__init__.py, manipulation/util/geometry_inspector.py, manipulation/util/show_model.py
Add explicit --find_runfiles
Motivated by / extracted from #13050
Initially, this was to add the `--find_resource` command. However, I noticed there to be shareable functionality that wasn't shared, so I made it common.
(I disprefer opening slider bars if I only need to preview the models.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13148)
=> manipulation: De-duplicate model preview functionality

geometry/scene_graph.h
Follow-up to this comment:
https://github.com/RobotLocomotion/drake/issues/13280#issuecomment-627632500
Basically, updates the text to (I think) reflect some of the changes effectively enabled by #9754 (but I guess they were possibly before then anywho).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13292)
=> scene_graph: Mention adding geometry in the context of collision filters

doc/issues.rst
Added Labels:
- https://github.com/RobotLocomotion/drake/labels/component%3A%20jupyter
- https://github.com/RobotLocomotion/drake/labels/component%3A%20pydrake
(No sorting has been done yet)
\cc @SeanCurtis-TRI 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13208)
=> doc issues: Add pydrake and jupyter components

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/_mathematicalprogram_extra.py, bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, bindings/pydrake/test/autodiffutils_test.py
Resolves #13181 (again)
Follow-up to #13183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13234)
=> py mathematical_program: Add friendlier-er errors for dtype mismatch

multibody/parsing/detail_scene_graph.cc, multibody/parsing/detail_scene_graph.h, multibody/parsing/test/detail_scene_graph_test.cc
Per discussion here:
https://github.com/RobotLocomotion/drake/pull/13201#issuecomment-622620721
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13206)
=> detail_scene_graph: Do not throw on missing sub-elements of //surface

geometry/render/gl_renderer/dev/render_engine_gl.cc, geometry/render/gl_renderer/dev/shape_meshes.cc, geometry/render/gl_renderer/dev/shape_meshes.h, geometry/render/gl_renderer/dev/test/shape_meshes_test.cc
- Refactors Sphere tessellation into a "revolute" shape function.
- Express sphere in terms of revolute.
- Express cylinder in terms of revolute.
- RenderEngineGl now uses the new function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13293)
=> [geometry/dev] Add Unit Cylinder to shape_meshes

attic/systems/sensors/depth_sensor_to_lcm_point_cloud_message.cc, attic/systems/sensors/test/rgbd_camera_test.cc, bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/planar_scenegraph_visualizer.py, bindings/pydrake/systems/rendering_py.cc, bindings/pydrake/systems/test/rendering_test.py, geometry/scene_graph.cc, systems/rendering/BUILD.bazel, systems/rendering/pose_aggregator.cc, systems/rendering/pose_bundle.cc, systems/rendering/pose_bundle.h, systems/rendering/pose_bundle_to_draw_message.cc, systems/rendering/pose_vector.cc, systems/rendering/pose_vector.h, systems/rendering/render_pose_to_geometry_pose.cc, systems/rendering/test/pose_aggregator_test.cc, systems/rendering/test/pose_bundle_to_draw_message_test.cc, systems/rendering/test/pose_vector_test.cc, systems/rendering/test/render_pose_to_geometry_pose_test.cc
- PoseBundle::{set|get)_pose deprecated; replaced with (set_)transform()
- get_pose() no longer returns a reference to an Isometry3.
- PoseVector::get_isometry deprecated; replaced with transform()
- Also added set_transform() based on old TODO.
- Multiple downstream consumers (and their tests) updated to use new API.
- Bindings updated (with deprecations) and test
- pose_bundle_to_draw_message_test
Resolves #11888
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13327)
=> Deprecate the Isometry3 in systems/rendering

geometry/query_object.h
Clarify that this does not apply to the `Convex` shape class
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13331)
=> query_object: Update doc to warn about ignoring Mesh shapes

multibody/plant/multibody_plant.h, multibody/tree/force_element.h, multibody/tree/multibody_tree.h, multibody/tree/uniform_gravity_field_element.cc, tutorials/mathematical_program.ipynb
Programmers use "Foo" as the conventional stand-in name; "XXX" is (at best) a Vin Diesel movie.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13341)
=> Remove use of XXX in comments

tools/workspace/ibex/repository.bzl
We do have a Focal package, but `setup_new_deb_archive` needs reworking to be able to use it. 
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13345)
=> Do not error when downloading ibex on Focal

tools/workspace/drake_visualizer/drake_visualizer_bazel.py
Relates #13102. I think it is reasonable for us to assume that Bionic and Focal are running under 3.6 and 3.8 for these purposes (drake-visualizer would be broken anyway, if not).
When I build VTK 9 (#13253) and start packaging Drake (#12783), I hope to switch us to an unversioned python3 directory (`lib/python3.8/site-packages -> lib/python3/{dist|site}-packages`) with correctly versioned suffixes (e.g., `$(python3-config --extension-suffix) == .cpython-38-x86_64-linux-gnu.so`) for the shared libraries in avoid having to worry so much about issues like this.
(BTW this change is covered by CI.)
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13339)
=> Fix location of VTK on Focal in drake-visualizer launcher

solvers/BUILD.bazel, solvers/binding.h, solvers/test/binding_test.cc
Add equal_to and hash function for Binding<C>
This is the first step to address the issues in #13285 . I plan to store the mapping from each `Binding<C>` to the dual variable solutions in `MathematicalProgramResult`. To this end, we need to use `Binding<C>` as the key in an unordered_map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13322)
=> Allow using Binding<C> as key in unordered_map.

tools/workspace/libjpeg/package-macos.BUILD.bazel, tools/workspace/libjpeg/package-ubuntu.BUILD.bazel, tools/workspace/libjpeg/repository.bzl, tools/workspace/yaml_cpp/package-macos.BUILD.bazel, tools/workspace/yaml_cpp/package-ubuntu-18.04.BUILD.bazel, tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel, tools/workspace/yaml_cpp/repository.bzl
Relates #13309. I imagine there is some refactoring to support the general case of #13309, but this is in earlier to support #13102.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13335)
=> Do not use pkg-config to find libjpeg and yaml-cpp

geometry/render/gl_renderer/dev/BUILD.bazel, geometry/render/gl_renderer/dev/render_engine_gl.cc, geometry/render/gl_renderer/dev/shape_meshes.cc, geometry/render/gl_renderer/dev/shape_meshes.h, geometry/render/gl_renderer/dev/test/shape_meshes_test.cc
- Adds two utility functions for generating meshes for a square patch and a unit box.
- Modify RenderEngineGl to make use of the shapes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13334)
=> [dev] Add HalfSpace and Box generation to shape_meshes.*

bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/general_test.py
Bindings and tests for:
- `PrintSimulatorStatistics`
- `ResetStatistics` in simulator
For the test, I just called the commands in some of the existing simulator tests
I put the `PrintSimulatorStatistics` under a heading labeled Simulator Flags, since I didn't know where else to put it. If you want me to put it somewhere else or make a new section, I can
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13343)
=> pydrake: Added some simulator bindings

examples/multibody/strandbeest/BUILD.bazel, examples/multibody/strandbeest/README.md, examples/multibody/strandbeest/model/LegAssembly.xacro, examples/multibody/strandbeest/model/LegPair.xacro, examples/multibody/strandbeest/model/Macros.xacro, examples/multibody/strandbeest/model/Strandbeest.xacro, examples/multibody/strandbeest/run_with_motor.cc, examples/multibody/strandbeest/test/run_with_motor_test.py
Adds a parameterized strandbeest example that tests out the new URDF parsing capabilities for creating `LinearBushingRollPitchYaw` (#13255).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13302)
=> Strandbeest example

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
Towards prototype mentioned here: https://github.com/RobotLocomotion/drake/issues/13177#issuecomment-629708238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13355)
=> py mbp: Bind MultibodyPlant.time_step()

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
Resolves https://github.com/RobotLocomotion/drake/issues/11648
The test is technically not testing out the Expression type because the Simulator doesn't have the Expression type.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13359)
=> Added support for all types in VectorExternallyAppliedSpatialForce

geometry/render/render_engine_ospray.cc, geometry/render/render_engine_vtk.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, perception/test/depth_image_to_point_cloud_test.cc
Relates #13102. Not entirely sure what changed in the stdlib headers with regard `<fstream>`, but everything should have been IWYU anyway.
Pretty much just the attic left to fix as far the compiler goes. A few linker issues and plenty of test issues, though. 
(Well, apparently, clang has a whole different set of copy-move related warnings, so still lots of compiler fun to be had.)
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13348)
=> Fix shadow warning and include <fstream> for std::ifstream and std::ofstream

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, examples/manipulation_station/test/manipulation_station_test.cc, systems/primitives/discrete_derivative.cc, systems/primitives/discrete_derivative.h, systems/primitives/test/discrete_derivative_test.cc
All current uses (but one) in Drake and Anzu for `DiscreteDerivative` and `StateInterpolatorWithDiscreteDerivative` go to great lengths to remove the first step's transient  velocity estimate, often completely breaking the System-Context abstraction by routing q0 through obscure callbacks.  (And the one place that doesn't do so is a bug, too.)
If we want state estimation to use zero velocity until it has two measurements, then we should just implement that process directly.
~This is a **backwards-incompatible** change to semantics `DiscreteDerivative`.  Users can opt-in to the old behavior by calling `set_input_history` or `set_initial_state` with all zeros.  In that case, the old behavior and new behavior are identical.~  _(Edit: No longer true as of the latest push.)_
---
This change …
=> primitives: Disable DiscreteDerivative transient by default

multibody/plant/multibody_plant.h
Nowadays all bodies have a FrameId assigned to them. This PR updates a snippet of docs that we forgot to update. Thanks @rcory for reporting this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13014)
=> Updates the developer notes of MBP::RegisterGeometry().

.binder/README.md
This is easier to stop
Came across this here:
https://github.com/RobotLocomotion/drake/pull/13182#issuecomment-632225526
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13373)
=> binder: Update local instructions to use `--rm -it`

bindings/pydrake/examples/manipulation_station_py.cc, bindings/pydrake/examples/test/manipulation_station_test.py, examples/manipulation_station/manipulation_station.h, examples/manipulation_station/manipulation_station_hardware_interface.cc, examples/manipulation_station/manipulation_station_hardware_interface.h
The teleop scripts in examples/manipulation_station work over LCM again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13372)
=> Fix missing member in ManipulationStationHardwareInterface

tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel
Maybe you could call it a bug that several classes (including `EmitFromEvents`) are arbitrarily missing a `YAML_CPP_API` decoration, but upstream do not consider symbol visibility at all and `YAML_CPP_API` is defined to nothing (except on Windows) until Debian decided to do differently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13366)
=> Use static library for yaml-cpp on Focal due to hidden visibility patch

systems/estimators/BUILD.bazel, systems/estimators/kalman_filter.cc, systems/estimators/luenberger_observer.cc, systems/estimators/luenberger_observer.h, systems/estimators/test/luenberger_observer_test.cc
instead of mutable member variables.
related to #13131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13307)
=> systems: Luenberger observer uses cache entries

bindings/pydrake/systems/test/general_test.py, systems/framework/test/basic_vector_test.cc, systems/framework/test/continuous_state_test.cc, systems/framework/vector_base.h
This reverts commit ac9316f3c8addd0bd692f669b6d4ff07347ef8c0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13384)
=> Revert "systems: Use Eigen's formatting in VectorBase::operator<<() output (#13365)"

doc/index.rst, tutorials/README.md
Use source tree directory names more explicitly
README: Cross-reference docs
I made this PR because I've found myself wanting to reference both `drake.mit.edu` and `drake/tutorials/README.md` because I find browsing through nbviewer, *then* clicking on the Binder button, to be a more bearable workflow.
For example, I cited it in this StackOverflow comment:
https://stackoverflow.com/a/61924814/7829525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13386)
=> doc: Update tutorials section to mention nbviewer

bindings/pydrake/geometry_py.cc, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/test/geometry_test.py
Added pydrake bindings needed for basic collision filtering in MBP and included a test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13358)
=> pydrake: Collision filtering bindings

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/frame_kinematics_test.cc, multibody/plant/test/multibody_plant_reaction_forces_test.cc, multibody/plant/test/multibody_plant_test.cc
#13137 introduced ports for body poses. This PR now introduces the ports for spatial velocity and acceleration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13364)
=> Spatial velocity and acceleration ports

systems/controllers/finite_horizon_linear_quadratic_regulator.cc, systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc, systems/framework/cache_entry.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/test/cache_entry_test.cc, systems/framework/test/leaf_system_test.cc
Currently if the cache dependency graph shows direct feedthrough from an input port to an output port, the System framework doesn't believe it and attempts a symbolic analysis to make its own determination. That makes sense when a user hasn't provided explicit prerequisites for that output port, because the default is "all sources" so always shows feedthrough. However, if a user _has_ provided prerequisites then we should believe the result and not bother with the symbolic analysis, which brings its own set of problems. For example, @RussTedrake had to suppress symbolics for his FiniteHorizonLinearQuadraticRegulator because the System's use case for feedthrough analysis stomped through forbidden territory (see discussion in #12253).
This PR modifies the feedthrough determination …
=> Suppress symbolic feedthrough check if non-default output prerequisites were specified.

bindings/pydrake/common/test/deprecation_example/README.md, bindings/pydrake/common/test/deprecation_example/sub_module.py, bindings/pydrake/pydrake_doxygen.h, doc/code_review_checklist.rst
Joe reached out to me about this, and I think it's the 5th time I've provided this link in about 1 month ;) Codifying it.
Also:
* We don't have a discoverable link from our code review checklist. I've added briefly links.
* If you go to `pydrake_doxygen.h`, it has no reference to the actual section. I've added the relevant `@ref`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13389)
=> pydrake doc: Add pointers to deprecation code

examples/kuka_iiwa_arm/kuka_simulation.cc, examples/manipulation_station/end_effector_teleop_mouse.py, examples/manipulation_station/end_effector_teleop_sliders.py, examples/manipulation_station/joint_teleop.py, examples/manipulation_station/manipulation_station.cc, examples/manipulation_station/mock_station_simulation.cc, manipulation/kuka_iiwa/iiwa_command_receiver.cc, manipulation/kuka_iiwa/iiwa_command_receiver.h, manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc, manipulation/schunk_wsg/schunk_wsg_position_controller.cc, manipulation/schunk_wsg/schunk_wsg_position_controller.h, manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
This changes the iiwa- and wsg-related classes; similar classes such as jaco are unchanged.
Current uses go to great lengths to remove the first step's current position command and transient velocity estimate, often completely breaking the System-Context abstraction by routing q0 through obscure callbacks.  By populating the "default position command" input with the "current position" output, we're sure that the command is always a no-op, no matter how the user set up the State for their plant.  Very important when state is a random variable!
Builds atop (requires) #13336 and #13378 and #13380.
Relates to #9859 somewhat.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drak …
=> manipulation: Use input (not parameter) for no-op IIWA command

solvers/snopt_solver.cc, solvers/test/snopt_solver_test.cc
Quick addition, adding use of SNOPT's `snset` to set string values. I wasn't sure if a 7.4 workaround was also needed, like some of the other methods, and so did not add that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13397)
=> Add parsing of string options to SNOPT.

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/cpp_template.py, bindings/pydrake/common/test/cpp_template_test.py
Towards #13407 (PR)
Necessary to deprecate (the, uh, misspelled) `VectorExternallyAppliedSpatialForced` opaque binding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13410)
=> py cpp_template: Enable deprecating instantiations

attic/multibody/dev/BUILD.bazel
After #13377, this test consistently times out for everything-debug builds. As it is
"attic + dev" code, switch off the test for debug builds.
Examples of failing builds:
https://drake-jenkins.csail.mit.edu/job/linux-bionic-clang-bazel-continuous-everything-debug/2246/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-gcc-bazel-continuous-everything-debug/2250/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13412)
=> Disable global_inverse_kinematics_feasible_posture_test in debug

multibody/plant/BUILD.bazel, multibody/plant/test/frame_kinematics_test.cc, multibody/test_utilities/add_fixed_objects_to_plant.h, multibody/tree/body_node.h, multibody/tree/multibody_tree.cc
Addresses the bug fix for the revert on #13399.
I will push the original #13364 after this PR merges.
cc'ing @jwnimmer-tri 
The problem in #13364 was indirectly caused by a velocity kinematics computation from a unit test on a model with zero dofs. It turns out that we never tested that. 
This PR fixes the bug and introduces a new test to ensure we can do kinematics even on non-empty models consisting of anchored bodies only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13405)
=> Enable kinematics computations on models with zero dofs

tools/skylark/pybind.bzl
Useful for passing `copts = ["-g", "-UNDEBUG"]`
Towards #13408
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13419)
=> pybind: Allow specifying copts

multibody/parsing/detail_scene_graph.cc, multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/test/detail_common_test.cc
Use NVRO (or RVO) in lambdas to avoid false positives on `std::optional` initialization.
The warnings are visible at [linux-focal-unprovisioned-gcc-bazel-continuous-release](https://drake-jenkins.csail.mit.edu/view/Linux%20Focal%20Unprovisioned/job/linux-focal-unprovisioned-gcc-bazel-continuous-release/) until this PR merges.
Closes #13367.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13418)
=> parsing: Work around some GCC 8 maybe-uninitialized warnings

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/frame_kinematics_test.cc, multibody/plant/test/multibody_plant_reaction_forces_test.cc, multibody/plant/test/multibody_plant_test.cc
This is the original PR #13364 (no changes at all from #13364) which was reverted in #13399. 
The CI failure was caused by an indirect request to perform velocity kinematics on a model with zero dofs. The bug fix was merged in #13405.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13423)
=> Implements spatial velocity and acceleration ports

bindings/pydrake/__init__.py, bindings/pydrake/common/cpp_template.py, bindings/pydrake/common/test/cpp_template_test.py, bindings/pydrake/systems/scalar_conversion.py, bindings/pydrake/systems/test/scalar_conversion_test.py
Towards #13407
Resolves #11706
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13409)
=> py cpp_template: Fix badly scoped name overrides

tools/workspace/drake_visualizer/drake_visualizer_bazel.py
Per discussion in #13421 , this would be a simple work-around, when combined with https://github.com/DAIRLab/dairlib/pull/150 to continue supporting a fully featured visualizer external workflow.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13428)
=> Do not add pydrake stub if pydrake already on path.

attic/multibody/shapes/element.h, attic/multibody/shapes/visual_element.h
A possible solution to the following:
```
ERROR: /media/ephemeral0/ubuntu/workspace/linux-focal-unprovisioned-gcc-bazel-continuous-release/src/attic/multibody/BUILD.bazel:164:1: Couldn't build file attic/multibody/_objs/rigid_body/rigid_body.pic.o: C++ compilation of rule '//attic/multibody:rigid_body' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 172 argument(s) skipped)
In file included from /usr/include/x86_64-linux-gnu/c++/9/bits/c++allocator.h:33,
from /usr/include/c++/9/bits/allocator.h:46,
from /usr/include/c++/9/string:41,
from /usr/include/c++/9/bits/locale_classes.h:40, …
```
=> Do not delete VisualElement move constructor

common/test_utilities/is_memcpy_movable.h
A possible solution to the following:
```
ERROR: /media/ephemeral0/ubuntu/workspace/linux-focal-unprovisioned-gcc-bazel-continuous-release/src/common/test_utilities/BUILD.bazel:200:1: Couldn't build file common/test_utilities/_objs/is_memcpy_movable_test/is_memcpy_movable_test.pic.o: C++ compilation of rule '//common/test_utilities:is_memcpy_movable_test' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 103 argument(s) skipped)
In file included from common/test_utilities/test/is_memcpy_movable_test.cc:1:
bazel-out/k8-opt/bin/common/test_utilities/_virtual_includes/is_memcpy_movable/dra …
```
=> Ignore class-memaccess warning in IsMemcpyMovable

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/inclined_plane_test.cc
Addresses #13416.
This allows `MBP::set_penetration_allowance()` pre- and post-finalize. Therefore it is entirely backwards compatible with the functionality in master today.
Minimum work needed to address this. Lots of this code will get properly cleaned up and exposed per #13064 as outlined in the TODO introduced in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13435)
=> Allows calling MBP::set_penetration_allowance() pre-finalize.

solvers/gurobi_solver.cc
#13357 fixed these in the open-source-only builds, so may as well fix the additional ones when the commercial solvers are enabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13450)
=> Fix range-loop-construct warnings in gurobi_solver.cc

systems/analysis/implicit_euler_integrator.h, systems/analysis/implicit_integrator.cc, systems/analysis/implicit_integrator.h, systems/analysis/radau_integrator.h, systems/analysis/simulator_print_stats.cc, systems/analysis/test/implicit_integrator_test.cc, systems/analysis/test_utilities/implicit_integrator_test.h, systems/analysis/velocity_implicit_euler_integrator.h
VIE Integrator should reset cached matrices when user changes Jacobian scheme
1) This commit fixes issue #13069, where the VelocityImplicitEulerIntegrator still keeps an old Jacobian after the computation scheme changes.
2) This change also adds a line to simulator print stats to print the number of derivative evaluations for explicit integrators; otherwise, there is no metric on how much work explicit integrators are performing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13392)
=> VIE Integrator should reset cached matrices when user changes Jacobian scheme

common/test/value_test.cc, common/value.h
`__PRETTY_FUNCTION__` changed between GCC 7 and 9 as follows:
* GCC 7:
```cpp
drake::test::{anonymous}::NiceAnonEnumTemplate<(drake::test::<unnamed>::AnonEnum)0>
```
* GCC 9:
```
drake::test::{anonymous}::NiceAnonEnumTemplate<drake::test::<unnamed>::AnonEnum::kFoo>
```
So it similar to Clang modulo `{anonymous}` and `<unnamed>` both mapping to `(anonymous namespace)`:
```
drake::test::(anonymous namespace)::NiceAnonEnumTemplate<drake::test::(anonymous namespace)::AnonEnum::kFoo>
```
This therefore means that the `drake::test::<unnamed>::AnonEnum` is no longer discarded since it is not parenthesized and the difference between `<unnamed>` and `{anonymous}` matters, not least because the (unexpected) `<>` causes `hash_template_argument_from_pretty_func` to fail.
----
This …
=> Fix hash_template_argument_from_pretty_func for GCC 9

bindings/pydrake/common/module_py.cc
Found this in the course of #13454
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13455)
=> py common: Use `py::object_api::get_type()`, not indirect Python C++ API

third_party/com_github_pybind_pybind11/mkdoc.py
Relates https://github.com/RobotLocomotion/drake/pull/13437#pullrequestreview-421254225.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13451)
=> Ensure build fails if parsing headers with libclang fails

doc/bazel.rst, setup/ubuntu/install_prereqs.sh, setup/ubuntu/source_distribution/install_prereqs.sh, setup/ubuntu/source_distribution/packages-bionic.txt
This resolves the immediate problem of `drake-apt.csail.mit.edu` certificate "expiry" (for buggy clients).
However, it is also a useful improvement towards #13168 optional prerequisites.  While the mechanism of this may change (`--with-kcov` spelling), the idea that extra developer tools should be opt-in is one that should remain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13462)
=> setup: On Bionic, the kcov dependency is now opt-in

bindings/pydrake/test/all_test.py
For #13433
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13467)
=> pydrake: Make all_test catch warnings rather than promote to errors

bindings/pydrake/systems/test/general_test.py, systems/framework/test/basic_vector_test.cc, systems/framework/test/continuous_state_test.cc, systems/framework/vector_base.h
This restores PR #13365
This reverts commit fca17492ebb64e1d634d3422e376769e99238a0d (#13384)
Resolves #13395
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13464)
=> systems: Use Eigen's formatting in VectorBase::operator<<() output

multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_urdf_parser_test.cc
Fixes #13471
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13472)
=> Fix loading multiple model instances with collision filter groups

systems/analysis/simulator.cc, systems/analysis/test/simulator_test.cc, systems/framework/context.cc, systems/framework/context.h, systems/framework/diagram.cc, systems/framework/diagram_context.h, systems/framework/system.cc, systems/framework/test/leaf_context_test.cc
Implements solution (2) to the event timing problem reported and discussed in #13296.
- Adds an std::optional `true_time` field to Context, and internal PerturbTime() method for setting it.
- Modifies Simulator::Initialize() to use PerturbTime().
- Modifies System::CalcNextUpdateTime() to report true_time rather than the perturbed time.
- Adds unit tests that duplicate the reported problem.
- Cleans up some time-related Context code.
Resolves #13296
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13438)
=> Make CalcNextUpdateTime() "right now" returns work during initialization

setup/ubuntu/source_distribution/packages-bionic.txt, setup/ubuntu/source_distribution/packages-focal.txt, tools/dynamic_analysis/drd.sh, tools/dynamic_analysis/helgrind.sh, tools/dynamic_analysis/valgrind.sh
I was not intending to pull the trigger on clang-9 for bionic, but may as well add it to the scripts so we can start to iron out any issues. CI will need an update to actually use `/usr/bin/clang-9` instead of `/usr/bin/clang`.
Relates #13434.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13477)
=> Add clang-9 compiler to prerequisites

bindings/pydrake/common/test/type_safe_index_pybind_test.cc, bindings/pydrake/common/type_safe_index_pybind.h, bindings/pydrake/geometry_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, bindings/pydrake/test/geometry_test.py
Motivated by subgraph prototype code:
* `__repr__` for easier debugging
* `__lt__` for sorting in Python lists
Towards #8586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13489)
=> py mbp, geometry: Bind __repr__ for indices + elements, __lt__ for indices

common/symbolic_rational_function.h, manipulation/schunk_wsg/schunk_wsg_plain_controller.h, multibody/tree/door_hinge.h, perception/point_cloud.h, solvers/constraint.h, solvers/test/semidefinite_program_examples.h, systems/analysis/bogacki_shampine3_integrator.h
As part of #13461 (but also good as a standalone)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13492)
=> Make minor C++ docstring adjustments

common/test/type_safe_index_test.cc, common/type_safe_index.h
When comparing an unsigned integral value with a TypeSafeIndex, we needed to account for the possibility that the unsigned integral value could contain larger values than the TypeSafeIndex. This was done by comparing the unsigned integer with the maximum int (the largest type safe
index value). This is intrinsically a signed-unsigned comparision which is problematic.
Instead, we cast the maximum int to the unsigned integral type. If the unsigned type is larger (more bits), the relationship will be fully preserved and unsigned values that are larger than can be represented will be detected.
If the unsigned type has fewer bits, the maximum int (01111.1111) will be truncated to a number consisting of all 1s, the maximum unsigned value of that number of bits. We are guaranteed that the …
=> Resolve signed-unsigned comparison issues in TypeSafeIndex

bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/BUILD.bazel, solvers/constraint.cc, solvers/constraint.h, solvers/test/constraint_test.cc
So as to improve the convergence of solving nonlinear gradient based optimization with Lorentz cone constraint.
This PR is motivated by the Slack discussion https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1590795131052300
cc @mposa
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13458)
=> Add alternative convex Eval functions to LorentzConeConstraint.

bindings/pydrake/symbolic_py.cc
Relates #13102 and #13434.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13502)
=> Fix clang versions for which -Wself-assign-overloaded should be ignored

common/symbolic_expression_cell.cc, common/test/symbolic_expansion_test.cc
In `ExpandMultiplication(e1, e2)`, it returns `e1 * e2` if both `e1` and `e2` are non-additive expressions. However, if at least one of them is a division expression, it is possible that `e1 * e2` is not an expanded expression.
For example, let `e1 = (x + 1) / y` and `e2 = (x + 3) / z`, `e1 * e2` becomes `(x + 1) * (x + 3) / yz` whose numerator is not expanded yet.
This commit fixes this problem by handling those cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13503)
=> Fix symbolic::Expression::Expand()

systems/analysis/implicit_euler_integrator.cc, systems/analysis/implicit_euler_integrator.h, systems/analysis/implicit_integrator.cc, systems/analysis/implicit_integrator.h, systems/analysis/radau_integrator.cc, systems/analysis/radau_integrator.h
This commit
1) moves function comments from CC to H files for ImplicitEulerIntegrator, ImplicitIntegrator, and RadauIntegrator, and
2) moves the implementation of ResetCachedJacobianMatrices() from the H file to the CC file, to keep the style consistent with the other Reset functions.
Everything is a copy paste, except for the comments for ComputeAndFactorImplicitEulerIterationMatrix, which didn't exist before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13510)
=> Clean up integrator comments

systems/analysis/implicit_euler_integrator.cc, systems/analysis/implicit_euler_integrator.h, systems/analysis/implicit_integrator.cc, systems/analysis/implicit_integrator.h, systems/analysis/test/radau_integrator_test.cc, systems/analysis/test_utilities/implicit_integrator_test.h
This PR implements Implicit Euler with step doubling for error estimation. This change is very similar to error estimation for Velocity-Implicit Euler (VIE) Integrator, and if Evan has time, it would be great if he can review the high-level decisions made here. The VIE step-doubling error estimation is well-documented here, and the same documentation will apply for Implicit Euler: https://drake.mit.edu/doxygen_cxx/classdrake_1_1systems_1_1_velocity_implicit_euler_integrator.html
Brief justification:
After running some tests with a pile of 3 objects and typical friction parameters, we found that step doubling works much better than implicit Trapezoid (IE+ITR) error estimation from the master branch. Under various accuracy settings (using a large max time step), IE+ITR performs very …
=> Step doubling for Implicit Euler Error Estimation

tools/install/dockerhub/.gitignore, tools/install/dockerhub/bionic/.dockerignore, tools/install/dockerhub/bionic/Dockerfile, tools/install/dockerhub/bionic/README.md, tools/install/dockerhub/focal/.dockerignore, tools/install/dockerhub/focal/Dockerfile, tools/install/dockerhub/focal/README.md
Relates #13102. There are duplicate Dockerfiles here rather than a single parameterized Dockerfile to match Docker Hub conventions. Building Focal-based Docker images on CI is currently disabled.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13508)
=> Add Focal-based Dockerfile for Docker Hub

doc/bazel.rst, doc/developers.rst, doc/getting_help.rst, doc/ubuntu.rst, setup/ubuntu/binary_distribution/install_prereqs.sh, tools/workspace/ibex/repository.bzl, tools/workspace/os.bzl
Depends on #13486 (hopefully). Relates #13102. Will need some provisioned images (#13488) and probably a Focal build running against pull requests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13487)
=> Add GCC 9.3 on Focal to the support matrix

doc/bazel.rst
Change the example invocation to run one test -- running the whole source tree takes 10+ hours.
Relates #8466.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13521)
=> doc: Clarify that kcov is not supported on macOS

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py
Add some missing Pydrake bindings for ContextBase methods for expert mucking around with the cache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13528)
=> Bind ContextBase cache control methods

common/yaml/test/yaml_read_archive_test.cc, common/yaml/yaml_read_archive.cc, common/yaml/yaml_read_archive.h
This paves the way for dealing with parser options in a future commit.
Thread the Options through the Serialize/Visit flow but don't use it for anything yet.
Rename ReportMissingYaml to ReportError to avoid being overly specific; this was already used for error messages beyond just missing stuff.
While we're here, also import the unit test with helpful comments and extracting some literal strings into named variables.
This builds on #13533 and is a prerequisite for #13532 towards #13251.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13537)
=> yaml: Add read_archive Options struct (currently a no-op)

bindings/pydrake/pydrake_doxygen.h, geometry/geometry_doxygen.h, geometry/geometry_infrastructure_doxygen.h, geometry/proximity/contact_surface_doxygen.h, geometry/proximity/penetration_doxygen.h, geometry/proximity/proximity_doxygen.h, geometry/render/render_doxygen.h, multibody/constraint/constraint_doxygen.h, multibody/multibody_doxygen.h, multibody/plant/contact_model_doxygen.h, solvers/mathematical_program_doxygen.h, systems/framework/cache_doxygen.h, systems/framework/system_scalar_conversion_doxygen.h
In searching Doxygen for `proximity`, one of the first things to come up was `proximity_doxygen.h`. On master, this is currently a blank page.
This makes the pages at least a bit more useful.
Searched for this as part of https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1591895065204300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13547)
=> doc: Make sure each doxygen-only file has a xref to defined sections

systems/framework/diagram_context.h, systems/framework/test/diagram_test.cc
DiagramContext used the continuous variable object type DiagramContinuousState but failed to keep the discrete variables in a DiagramDiscreteValues object, instead flatting them into a plain DiscreteValues object. In contrast diagram.AllocateDiscreteVariables() does return a DiagramDiscreteValues object, of the kind required for doing discrete variable updates. The result is that you can't do an update directly into the discrete state of a diagram context, as would reasonably be expected.
This PR fixes that and adds missing unit tests that would have caught this. There are no visible behavior changes in normal operation since DiscreteVariables and DiagramDiscreteVariables have nearly-identical interfaces.
This change affects the discrete variable object returned by …
=> Make DiagramContext use the DiagramDiscreteValues type

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/all.py, bindings/pydrake/solvers/csdp_py.cc, bindings/pydrake/solvers/gurobi_py.cc, bindings/pydrake/solvers/ipopt_py.cc, bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/mosek_py.cc, bindings/pydrake/solvers/nlopt_py.cc, bindings/pydrake/solvers/osqp_py.cc, bindings/pydrake/solvers/scs_py.cc, bindings/pydrake/solvers/snopt_py.cc, bindings/pydrake/solvers/test/csdp_solver_test.py
Changes one of the dependencies of all solvers from `//bindings/pydrake/systems:framework_py` to `//bindings/pydrake:value_py` as a side update.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13544)
=> pydrake solvers: Add bindings for CsdpSolver

manipulation/models/franka_description/urdf/hand.urdf, manipulation/models/franka_description/urdf/panda_arm.urdf, manipulation/models/franka_description/urdf/panda_arm_hand.urdf
Issues: 
1) Some of the collisions are defined for the wrong link. See the following two pictures of link1
Before:
After:
2) One contact geometry on the hand extended too much. Moving it a little bit expands the workspace of the wrist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13550)
=> Fix some collision geometries of the panda arm urdf

examples/acrobot/dev/BUILD.bazel, examples/acrobot/dev/acrobot_io.py
* pyyaml changed its default flow semantics in https://github.com/yaml/pyyaml/pull/256
* We must override the default with the magic tribool value `None`
* Fixes #13541
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13543)
=> Force older and newer yaml.dump to give the same output

examples/manipulation_station/BUILD.bazel
Fix test timeout of  //examples/manipulation_station:manipulation_station_test on linux-bionic-clang-bazel-nightly-coverage.
Nightly Production has https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-bionic-clang-bazel-nightly-coverage/ failed four times in the past seven days (June 9 - 15, 2020) due to timeout in the coverage test of manipulation_station_test.
Added `timeout = "moderate"` in BUILD.bazel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13563)
=> examples: Fix timeout in manipulation_station_test.

bindings/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis.py, examples/acrobot/test/multibody_dynamics_test.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_hydroelastic_test.cc, multibody/plant/test/multibody_plant_scalar_conversion_test.cc, multibody/plant/test/multibody_plant_test.cc
Addresses #13530.
- Declares the SceneGraph ports for MultibodyPlant in the constructor so that they have consistent ordering with the ScalarConverting constructor.
- Removes the requirement that `this` MBP has been registered with a SceneGraph to access SG input/output ports
- Adds tests for port indexing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13558)
=> Declare MultibodyPlant's SceneGraph ports in constructor.

geometry/geometry_visualization.h
In the past (#11763), the markdown table got mangled so it no longer rendered correctly. Currently it looks like this:
https://drake.mit.edu/doxygen_cxx/group__visualization.html#ga20c8d0e933cfdd8684cf77b15d8bef15
This fix makes it look like this again:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13566)
=> [doc] Fix formatting on mangled markdown table

multibody/plant/test/multibody_plant_jacobians_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h
This PR helps address part of issue #12592, submitted by user Evan Drumwright -- CalcBiasSpatialAcceleration() methods throw assertions if measured-in-frame Frame A is not the world frame.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13453)
=> Enable CalcBiasSpatialAcceleration() to have a measured-in-frame that is not the World.

geometry/render/gl_renderer/dev/BUILD.bazel, geometry/render/gl_renderer/dev/opengl_geometry.h, geometry/render/gl_renderer/dev/shader_program.cc, geometry/render/gl_renderer/dev/shader_program.h, geometry/render/gl_renderer/dev/test/opengl_geometry_test.cc, geometry/render/gl_renderer/dev/test/shader_program_test.cc
- OpenGlGeometry and OpenGlInstance get their documentation extended and clarified.
- missing unit tests added.
- ShaderProgram gets updated:
- extended documentation
- improved error messages
- evolved semantics
- unit tests
- buffer_dim_test loses superfluous vtk_tags()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13573)
=> [gl_renderer/dev] Clean up documentation and add unit tests

doc/clion.rst
Updates the instructions to suggest the latest version for which there is a Bazel plugin.
I updated both of my Ubuntu machines (Puget and a VM on my laptop) with no ill effects. Symbols are working fine. Performance seems better than the previous release I had (2019.2.5) but that may be an illusion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13588)
=> Update CLion instructions to recommend CLion 2019.3.6

common/yaml/test/yaml_read_archive_test.cc
We had been using NAN to indicate "unset default value", but it leads to awkward test phrasing because it does not compare equal with itself. Instead, we'll just use a magic sentinel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13589)
=> yaml: Remove NANs from unit test

bindings/pydrake/math_py.cc
In #13595, the replacement stubs were calling the wrong methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13607)
=> Fix deprecated pydrake Isometry3 stubs

bindings/pydrake/test/math_test.py
This tests the fixes in #13607, for #13595.
This test passes as of cacac0aa107dcc63d37d21104efd1357377de78b (pre-#13595), modulo the the "expect 1 warning" lines being removed.  Therefore, it shows that the code (after #13607 hotfix) preserves the prior behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13608)
=> pydrake: Add regression test for deprecated Isometry3 stubs

geometry/proximity/BUILD.bazel, geometry/proximity/bounding_volume_hierarchy.cc, geometry/proximity/bounding_volume_hierarchy.h, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/hydroelastic_internal.h, geometry/proximity/test/bounding_volume_hierarchy_test.cc, geometry/proximity/test/hydroelastic_internal_test.cc
When copy RigidMesh or SoftMesh, we will copy their BoundingVolumeHierarchy too. Right now we rebuild BoundingVolumeHierarchy.
Details:
- Add {copy, move}{constructor, assignment operator} of RigidMesh and SoftMesh.
They will use the copy constructor of BoundingVolumeHierarchy instead of rebuilding.
- Change the assignment operators of RigidGeometry and SoftGeometry to use the copy constructors of RigidMesh and SoftMesh.
The motivation is that the assignment operators of RigidGeometry and SoftGeometry are called multiple times during context creation by Simulator.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13564)
=> Copy {Rigid/Soft}Mesh without rebuilding BoundingVolumeHierarchy.

geometry/render/gl_renderer/dev/buffer_dim.h, geometry/render/gl_renderer/dev/render_engine_gl.cc, geometry/render/gl_renderer/dev/render_engine_gl.h, geometry/render/gl_renderer/dev/test/render_engine_gl_test.cc
- Depth computation made more efficient
- previously, we computed *inverse* depth on the GPU and then inverted
it on the CPU requiring another linear pass on the image. The reason
for this is that the depth image was being initialized to 0. That
means any pixel that wasn't drawn on by geometry was reporting that
there was something that was too close. In fact, that's the inverse of
the answer we actually wanted.
- Instead, we know explicitly clear the depth image to be all "too far"
values. So, we if we don't draw, we have the expected depth value. And
where we do draw, we're computing the actual depth.
- Clean up documentation
- Clean up various method and member names (e.g.
SetupFBO --> CreateRenderTarget)
- Clean up some const sloppiness and cache members.
- Clean up depth shader.
- …
=> [dev] Bring RenderEngineGl up to full Drake standards

CMakeLists.txt, setup/mac/source_distribution/install_prereqs.sh, tools/workspace/cc/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13611)
=> tools: Remove deprecated version support 2020-07-01

geometry/render/gl_renderer/BUILD.bazel
There are a number of Mac CI failures due to #13616.  E.g.,
https://drake-jenkins.csail.mit.edu/job/mac-catalina-clang-bazel-nightly-debug/259/
https://drake-jenkins.csail.mit.edu/job/mac-mojave-clang-bazel-nightly-release/352/
etc.
The `render_engine_gl_test` build target was *not* configured to be ubuntu only. This changes it to be so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13629)
=> Patch Mac CI - switch render_engine_gl_test to be ubuntu only

systems/sensors/BUILD.bazel, systems/sensors/beam_model.cc, systems/sensors/beam_model.h, systems/sensors/test/beam_model_test.cc
The header declared its signature but no implementation was provided.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13615)
=> Implement BeamModel's scalar conversion constructor

bindings/pydrake/systems/sensors_py.cc, geometry/render/BUILD.bazel, geometry/render/render_camera.cc, geometry/render/render_camera.h, geometry/render/test/render_camera_test.cc, systems/sensors/camera_info.h, systems/sensors/rgbd_sensor.cc, systems/sensors/rgbd_sensor.h, systems/sensors/test/camera_info_test.cc, systems/sensors/test/rgbd_sensor_test.cc
This is the first of a sequence of PRs to allow full intrinsics specification of cameras for rendering.
This represents a top-down approach. We introduce the public API components of specifying the camera. In this PR, if "complex" intrinsics are provided, a warning will be spewed and the camera
will be "simplified". Subsequent PRs will fill in the required rendering infrastsructure.
- CameraInfo used for full intrinsics (DepthCamera extended from it).
- RenderCameraProperties used to carry RenderEngine-specific, per-camera properties (e.g., clipping planes).
- RgbdSensor given new constructor for handling fully-specified camera model.
relates #11880
--- …
=> [render] Add base infrastructure for declaring full camera intrinsics

systems/sensors/test/camera_info_test.cc
Conversion from field-of-view to focal length and back is not perfectly invertible on mac. This changes the test from "equals" to "near".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13634)
=> Fix Mac CI - exact comparison fails in camera_info_test

systems/framework/BUILD.bazel, systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/system.cc, systems/framework/system.h, systems/framework/system_visitor.cc, systems/framework/system_visitor.h, systems/framework/test/system_visitor_test.cc
Provides a visitor pattern to introspect into Diagrams (as Diagrams) and LeafSystems (as Systems) from a const System<T>&.  This is very useful for looping through a nested diagram.
This will be used in my next PR for the javascript diagram visualization.  (It allows me to write that as a workspace method instead of polluting the System class).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13628)
=> Implement SystemVisitor

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/planar_scenegraph_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py
Provides the same syntactic sugar that we've given to ConnectDrakeVisualizer and ConnectPlanarSceneGraphVisualizer.  (the implementation here is almost identical to the planar scene graph version)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13632)
=> Add ConnectMeshcatVisualizer

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py
I've named them here, instead of passing kwargs, to improve readability/usability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13643)
=> Pass animation arguments through to meshcat.

geometry/geometry_state.cc, geometry/geometry_state.h, geometry/query_object.cc, geometry/query_object.h, geometry/render/render_engine.cc, geometry/render/render_engine.h, geometry/render/test/render_engine_test.cc, geometry/test/query_object_test.cc, geometry/test_utilities/dummy_render_engine.h, systems/sensors/rgbd_sensor.cc, systems/sensors/rgbd_sensor.h
This ties the intrinsics API defined in #13557 into `geometry`. 
- RenderEngine given new API to handle full camera model specification.
- handles sub-classes that haven't implemented full intrinsics by defaulting to legacy rendering (with a warning about throwing out information).
- The "simple" camera model now invokes the full-intrinsics version.
- Geometry infrastructure extended to exercise render engine API
- QueryObject and GeometryState have appropriate APIs.
- New API essentially duplicates old API. Deprecation of old API will come in follow up PR.
- RgbdSensor now assumes RenderEngine handles full intrinsics and no longer protects it.
--- …
=> [render] Extend camera intrinsics into geometry and geometry/render

multibody/plant/multibody_plant.h
Fixes the documentation for MultibodyPlant::CalcBiasCenterOfMassTranslationalAcceleration():
- the J vdot term was written incorrectly as Jdot v, and
- asterisks were used for multiply rather than centered dots (inconsistent with other docs in that class).
This caused confusion for a user on [Stackoverflow](https://stackoverflow.com/questions/62757744/how-to-calculate-center-of-mass-acceleration).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13645)
=> Fixed method comment for CalcBiasCenterOfMassTranslationalAcceleration

geometry/render/gl_renderer/opengl_context.cc, geometry/render/gl_renderer/opengl_context.h, geometry/render/gl_renderer/render_engine_gl.cc, geometry/render/gl_renderer/render_engine_gl.h, geometry/render/gl_renderer/test/opengl_context_test.cc, geometry/render/gl_renderer/test/render_engine_gl_test.cc
The `RenderEngine` API has the ability to request showing the display for color and label images. Up to this point, `RenderEngineGl` hasn't supported that. This adds the infrastructure necessary to display the images.
Currently only exercised in test. Its inclusion now facilitates the development of label and color rendering in subsequent PRs; it's
nice to be able to see the images.
(Incidentally changes opengel_context.h documentation to `/*` from `/**` because it is in `internal::` namespace.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13626)
=> RenderEngineGl gets ability to "show_window"

setup/ubuntu/source_distribution/packages-bionic.txt, setup/ubuntu/source_distribution/packages-focal.txt
Needed for sanitizer builds (e.g., for `llvm-symbolizer`). Needs CI update, but no reason it cannot merge beforehand.
Relates #13434 and  #13650.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13656)
=> Add missing tools relating to LLVM 9

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/geometry_properties.cc, geometry/geometry_properties.h, geometry/geometry_state.cc, geometry/internal_geometry.h, geometry/proximity/test/hydroelastic_internal_test.cc, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/geometry_properties_test.cc, geometry/test/geometry_state_test.cc, geometry/test/internal_geometry_test.cc, geometry/test/proximity_properties_test.cc
This PR has two curated commits:
1. The first extends `GeometryProperties` functionality to make it easier to modify properties. A mutable instance of `GeometryProperties` can have properties removed, updated, or overwritten.
2. The second enables `AssignRole(..., IllustrationProperties, AssignRole::kReplace)`. Previously, that would throw. Due to issues in the greater ecosystem, this added functionality comes with limitations and warnings.
- there are warnings in the documentation.
- Warnings will likewise get printed to the console.
resolves #13126
(While not the total solution, it is sufficient to empower workflows to change visual appearance of parsed geometry.)
--- …
=> [geometry] IllustrationProperties can be updated after parsing

doc/python_bindings.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13660)
=> doc: Modernize advice regarding PYTHONPATH

common/yaml/BUILD.bazel, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_write_archive.h, third_party/com_github_jbeder_yaml_cpp/BUILD.bazel, third_party/com_github_jbeder_yaml_cpp/src/emitfromevents.cpp
Previously yaml_read_archive could read variants using tags, but could only ever write out the default (first) variant type.  This brings yaml_write_archive up to par.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13631)
=> yaml: Permit writing variant values beyond the 0'th index

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
According to [multibody_tree.cc:1726](https://github.com/RobotLocomotion/drake/blob/master/multibody/tree/multibody_tree.cc#L1726), `CalcJacobianTranslationalVelocity` expects an output matrix
```
Js_v_ABi_E->rows() == 3 * num_points
```
However, in [plant_py.cc:418](https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/multibody/plant_py.cc#L418):
```
Matrix3X<T> Js_v_ABi_E(
3, GetVariableSize<T>(*self, with_respect_to));
self->CalcJacobianTranslationalVelocity(context, with_respect_to,
frame_B, p_BoBi_B, frame_A, frame_E, &Js_v_ABi_E);
```
shows that an output matrix of size 3 is always created.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13653) …
=> Fix binding for CalcJacobianTranslationalVelocity output matrix not sized correctly

bindings/pydrake/examples/_manipulation_station_extra.py, examples/manipulation_station/manipulation_station.cc
…to dramatically improve kinematic feasibility.  (Teleoping was annoying/impossible before because diff IK would constantly hit singularities)
You can see the new arrangement in http://people.csail.mit.edu/russt/uploads/clutter.html
(btw -- that file is slow to load because the ycb object meshes are enormous;[ it's not the iiwa](http://people.csail.mit.edu/russt/uploads/iiwa.html)).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13666)
=> manipulation_station: Move clutter clearing bins lower relative to robot

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
I needed the python bindings for [`CalcBiasForJacobianSpatialVelocity`](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html#ab1acb4f78f307092671567a002b39c4b) which I believe has been renamed to `CalcBiasSpatialAcceleration` as per 653c35dfc7.
I suppose support for `JacobianWrtVariable::kQDot` is not available yet, so the test fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13638)
=> Python bindings for CalcBiasSpatialAcceleration, CalcBiasTranslationalAcceleration

geometry/render/render_engine_vtk.cc, geometry/render/render_engine_vtk.h, geometry/render/shaders/depth_shaders.h, geometry/render/test/render_engine_vtk_test.cc
- RenderEngineVtk - implements full camera intrinsics
- Implement simple camera model in terms of full camera model.
- Also cleaned up the old zombie code in its depth shader.
- Tests extended accordingly.
- Incidental clean up on depth shader code.
This is the final step in making full camera intrinsics actually functional (as detailed in #11880). There are several subsequent steps for finishing the software engineering. But this represents the minimum change to make intrinsics available for use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13655)
=> [render] RenderEngineVtk now uses full camera intrinsics

geometry/render/gl_renderer/BUILD.bazel, geometry/render/gl_renderer/opengl_geometry.h, geometry/render/gl_renderer/render_engine_gl.cc, geometry/render/gl_renderer/render_engine_gl.h, geometry/render/gl_renderer/shader_program.cc, geometry/render/gl_renderer/shader_program.h, geometry/render/gl_renderer/test/opengl_geometry_test.cc, geometry/render/gl_renderer/test/render_engine_gl_test.cc, geometry/render/gl_renderer/test/shader_program_test.cc
Implement RenderLabelImage in RenderEngineGl
The implementation is straight forward. It provides a springboard for also adding the color label, because the infrastructure no longer assumes all depth all the time.
- Adds infrastructure to distinguish shaders (depth vs label).
- Adds a new shader for label images.
- Stores per-geometry render labels (OpenGlGeometry)
- Extend ShaderProgram to set a new kind of uniform value (vec4).
- Also cleans up the otherwise inconsistent ~ShaderProgram.
relates #13617 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13659)
=> [render] Implement RenderImageLabel in RenderEngineGl

multibody/plant/tamsi_solver.h, multibody/plant/test/tamsi_solver_test.cc, multibody/plant/test/tamsi_solver_test_util.h
As the number of active contact points increases (larger than 128) we found out TAMSI was not reallocating its workspace. This PR fixes that.
cc'ing @BenBurchfiel-TRI (I hope this solves the problem you brought up yesterday)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13676)
=> Bug fix on workspace allocation by TAMSI.

geometry/proximity_properties.cc, geometry/proximity_properties.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
This PR adds functionality to store penalty method contact parameters on a per-geometry basis in SceneGraph, as well as use these parameters in MBP contact computations. This effectively allows a user to modify these parameters in a Context, via SceneGraph (GeometryState).
See #13289.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13630)
=> Use penalty method contact parameters stored in SceneGraph

common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_write_archive.h
When a child structure did not have any elements, we were recording it as Null which trips an assertion in the emitter.  Fix and add a test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13679)
=> yaml: Correctly write out empty sub-structs

geometry/proximity_properties.cc, geometry/proximity_properties.h, geometry/test/proximity_properties_test.cc, multibody/parsing/detail_common.cc, multibody/parsing/test/detail_common_test.cc
Adds parsing capabilities for the new `point_contact_stiffness` property in `ProximityProperties` (added in #13630).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13686)
=> Adds point_contact_stiffness parsing 

multibody/plant/test/multibody_plant_test.cc
The effect of gravity alone is much better accessed through `MBP::CalcGravityGeneralizedForces()` or alternatively `MBP::gravity_field().CalcGravityGeneralizedForces()`. 
However, given that #13460 reports what seems a bug, this PR introduces unit tests to verify that `CalcForceElementsContribution()` does include the effect of gravity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13474)
=> Unit test CalcForceElementsContribution() includes gravity.

systems/framework/system_html.cc
Big diagrams, like the manipulation station example, were giving an initial render that was barely visible on the screen.  Now it looks like this:
https://people.csail.mit.edu/russt/uploads/manip_station.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13704)
=> Tell gojs to autoscale for javascript system diagrams

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/tamsi_solver.cc, multibody/plant/tamsi_solver.h, multibody/plant/test/tamsi_solver_test.cc
This PR is a refactor of the math TAMSI does so that the solver is agnostic to whether the point pair info corresponds to penetration pairs (point contact) or quadrature pairs (e.g. hydro). 
This follows the math in the draft paper I shared with the dynamics team. The refactor is simply swapping `phi0` with `fn0 = k * phi0` so that the solver does not think anymore in terms of distances but in terms of (undamped) normal forces at the previous step, i.e. fn0.
I used the word "refactor" because this simply is a change of variables, all unit tests in master should result in the same results from the TAMSI solver.
cc'ing @DamrongGuoy, @SeanCurtis-TRI 
--- …
=> Prep TAMSI for discrete hydro info

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Adds a check for strictly positive penetration allowance, and throws an exception if not.
Adds simple test to verify the exception.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13694)
=> checks for strictly positive penetration_allowance in MBP::set_penetration_allowance()

systems/framework/system_html.cc, systems/framework/system_html.h, tutorials/dynamical_systems.ipynb
The implementation of `GenerateHtml` has been temporarily removed from Drake due to licensing restrictions.  The function will return valid HTML, but will not produce any useful rendering.
Revert the dynamical systems tutorial to use matplotlib again.
Relates #13705.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13720)
=> framework: Remove GoJS from GenerateHtml; rendering is now broken

geometry/benchmarking/README.md
Came across per Jeremy's mention in Slack:
https://drakedevelopers.slack.com/archives/C2NN588UA/p1595350566134800?thread_ts=1595350442.134600&cid=C2NN588UA
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13723)
=> geometry: Fix minor broken URL for benchmarking

doc/getting_help.rst
I forgot about this and was reminded by @RussTedrake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13728)
=> getting_help: Add note about inviting people directly to Slack

common/yaml/yaml_write_archive.cc, common/yaml/yaml_write_archive.h
Generally we should prefer cc file for compilation speed, but it was overlooked during the initial implementation.
Prep for #13699.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13732)
=> yaml: Move method definition to cc file

common/yaml/BUILD.bazel, common/yaml/test/example_structs.h, common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_test.cc
Tidy up the struct a little bit to resolve differences between the two copies: Serialize as first thing in struct, use kNominalDouble not NAN, always have a non-zero, non-empty default value, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13733)
=> yaml: Factor out example_structs for unit tests

bindings/pydrake/multibody/tree_py.cc, multibody/tree/BUILD.bazel, multibody/tree/multibody_tree.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/spatial_inertia_test.cc
Identified CalcJacobianTranslationalVelocity and MultibodyTree inertia calculations as hotspots in MultibodyPlant Profiling. This PR contains three changes:
On Cassie, as evaluated by callgrind, this reduced the estimated cycles per call from 4313 to 3076. Results in a >10% runtime reduction for benchmark trajectory optimization tasks.
This change uses auto instead of Vector3<T> to avoid resolving Eigen expressions (Eigen's dense assignment loop was identified as the bulk of the computational cost. It also avoids the very common multiplication by the identity matrix, whenever the Jacobian is w.r.t. v.
MultibodyTree.CalcSpatialInertiaInBodyFrame() should be a free operation, but by calling SpatialInertia.cast(), it was triggering a re-validation of the inertia.
Added a flag to skip …
=> Performance tweak to MultibodyTree.CalcJacobianAngularAndOrTranslationalVelocityInWorld

bindings/pydrake/BUILD.bazel, bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/module_py.cc, bindings/pydrake/common/text_logging_pybind.cc, bindings/pydrake/common/text_logging_pybind.h, bindings/pydrake/test/text_logging_example.py, bindings/pydrake/test/text_logging_test.py, bindings/pydrake/test/text_logging_test_py.cc
sdplog output will appear in the Jupyter window instead of in the terminal.
Relates to #13215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13568)
=> Provide a spdlog sink that connects to Python's `logging` module

geometry/proximity/hydroelastic_callback.h, geometry/proximity/penetration_as_point_pair_callback.cc, geometry/proximity/penetration_as_point_pair_callback.h, geometry/proximity/test/penetration_as_point_pair_callback_test.cc, geometry/proximity_engine.cc, geometry/query_object.h, geometry/test/proximity_engine_test.cc
This encompasses two things:
1. Guarantees that if objects A and B make contact, that the result is identical regardless of which is "first" or "second".
2. For multiple contacts, the results will be ordered in a reliable ordering (for a fixed set of poses).
This impacts the following queries documented in QueryObject:
- ComputePointPairPenetration()
- ComputeContactSurfaces()
- ComputeContactSurfacesWithFallback()
- FindCollisionCandidates()
resolves #13736
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13737)
=> [geometry] Making contact results deterministic

multibody/tree/BUILD.bazel, multibody/tree/planar_mobilizer.cc, multibody/tree/planar_mobilizer.h, multibody/tree/test/planar_mobilizer_test.cc
Adds a 3 dof planar mobilizer that allows motion in the xy plane and rotation about the z-axis of the parent frame.
Towards #12404
Relates #12401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13711)
=> multibody: Implement PlanarMobilizer

multibody/plant/BUILD.bazel, multibody/plant/discrete_contact_pair.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
This essentially is a refactor on how MBP collects data to be passed to our discrete solver. Nothing changes in terms of functionality. This prepares the internal infrastructure so that in a following PR, enabling discrete hydro only requires a very localized change within `MBP::CalcDiscreteContactPairs()` (introduced in this PR). This localized change is possible due to the fact that we made TAMSI agnostic to the discrete model in, #13696.
The Jacobian computation fixes an old TODO and therefore contact results are expected to change so slightly (in the right direction). Not a breaking change, but probably users should be notified in the next release.
--- …
=> Introduce discrete contact pairs for agnostic treatment of discrete contact models

solvers/test/csdp_solver_test.cc
One possible explanation is that they use different BLAS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13759)
=> CSDP on mac should have a different numerical tolerance.

multibody/tree/ball_rpy_joint.h, multibody/tree/joint.h, multibody/tree/prismatic_joint.h, multibody/tree/revolute_joint.h, multibody/tree/universal_joint.h, multibody/tree/weld_joint.h
Solution to #13756.
Turns `set_default_positions()` into an NVI and adds the pure virtual `do_set_default_positions()` to the `Joint` class.
Adds implementations of `do_set_default_positions()` to all current `Joint` subclasses.
cc'ing @mpetersen94. I, @amcastro-tri,  found out this bug when reviewing your PR, so thanks for that!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13757)
=> Make set_default_positions an NVI

bindings/pydrake/test/all_test.py
When a warning does occur, its str does not explain it; instead, we should print the message to improve debugging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13761)
=> pydrake: Improve unit test error message

CPPLINT.cfg
In preparation for enabling C-style comment linting, we disable the whitespace rules for TODOs.  They go beyond what GSG demands, and it is unclear how to apply them to C-style comments.
Related to #13762 and RobotLocomotion/styleguide#31.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13763)
=> cpplint: Disable whitespace/todo

bindings/pydrake/common/text_logging_pybind.cc
Change the order of include statements to avoid the SPLOG_ACTIVE_LEVEL
redefined warning.
Resolves #13771
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13781)
=> Remove spdlog warning

math/rigid_transform.cc, math/rigid_transform.h, math/roll_pitch_yaw.h, math/rotation_matrix.cc, math/rotation_matrix.h
Motivations:
1. Just for speed, 'cause why not?
2. As part of #7889, one way to know to bind an instantiation is to use it in actual C++ code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13798)
=> math: Declare explicit class instantiations for SO(3) and SE(3)

bindings/pydrake/systems/test/custom_test.py, tools/workspace/pybind11/repository.bzl
Add test checking for missing `LeafSystem.__init__`
Resolves #13792
FYI @RussTedrake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13801)
=> workspace: Update pybind11 fork with cherry-pick from upstream

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py, examples/manipulation_station/end_effector_teleop_dualshock4.py, examples/manipulation_station/end_effector_teleop_mouse.py, examples/manipulation_station/end_effector_teleop_sliders.py, examples/manipulation_station/joint_teleop.py, tools/workspace/meshcat/repository.bzl, tools/workspace/meshcat_python/repository.bzl
And uses it in the ManipulationStation planar demos
Also sets a different background color for meshcat (now that I finally can!) to match drake-visualizer.
See http://people.csail.mit.edu/russt/uploads/planar_iiwa_teleop.html for a preview.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13755)
=> Adds support for "planar visualization" in meshcat

solvers/cost.cc, solvers/test/cost_test.cc
Motivated by #13674
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13752)
=> Fix specialized QuadraticCost Eval with AutoDiff scalar.

common/yaml/BUILD.bazel, common/yaml/test/example_structs.h, common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_defaults_test.cc, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_write_archive.cc, common/yaml/yaml_write_archive.h
This allows for emitting a minimal yaml representation when loaded with `retain_map_defaults` set on the eventual reader.  This is the minimal API to accomplish that.  I intend to provide better usability shims for this in a future commit.
See Anzu 5040 for an example use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13699)
=> yaml: Add SubtractDefaults to YamlWriteArchive

bindings/pydrake/test/all_test.py, tools/workspace/meshcat_python/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13806)
=> Bump meshcat_python SHA to get generalized "start server" methods.

common/schema/dev/test/stochastic_test.cc, common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_defaults_test.cc, common/yaml/test/yaml_write_archive_test.cc, geometry/render/gl_renderer/render_engine_gl.cc, geometry/render/gl_renderer/test/shader_program_test.cc, geometry/render/gl_renderer/test/shape_meshes_test.cc, geometry/render/shaders/depth_shaders.h, multibody/parsing/test/detail_scene_graph_test.cc, multibody/parsing/test/detail_urdf_geometry_test.cc, systems/framework/system_html.cc, tools/vector_gen/test/sample_test.cc
To help naive readers better understand this unusual construction, we'll use a marker similar to Python's multi-line literal and apply the style uniformly across the codebase.
Relates #13699.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13811)
=> Prefer triple-quote for C++ multi-line string literals

multibody/tree/BUILD.bazel, multibody/tree/planar_joint.cc, multibody/tree/planar_joint.h, multibody/tree/test/planar_joint_test.cc
Adds a 3 dof planar joint that allows motion in the xy plane and rotation about the z-axis of the parent frame.
Towards #12404
Relates #12401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13747)
=> multibody: Implement PlanarJoint

bindings/pydrake/common/cpp_template.py, bindings/pydrake/common/deprecation.py, bindings/pydrake/common/deprecation_pybind.h, bindings/pydrake/common/test/cpp_template_test.py, bindings/pydrake/common/test/deprecation_example/__init__.py, bindings/pydrake/common/test/deprecation_example/cc_module_py.cc, bindings/pydrake/common/test/deprecation_test.py, bindings/pydrake/math_py.cc
Resolves #13729
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13730)
=> py deprecation: Require YYYY-MM-DD to be present in message

geometry/render/gl_renderer/BUILD.bazel, geometry/render/gl_renderer/defs.bzl
Split the renderer out from the factory, for clarity.
Closes #13700.
Closes #13702.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13807)
=> gl_renderer: Do not install private headers

tools/workspace/styleguide/repository.bzl
This incorporates cpplint.py changes to enable checking c-style comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13804)
=> workspace: Upgrade styleguide latest commit

bindings/pydrake/common/eigen_geometry_py.cc, bindings/pydrake/common/test/eigen_geometry_test.py, math/quaternion.h
Resolves #13809
quaternion: Deprecate drake::math::Slerp in lieu of Eigen's
The motivation here is that I'm lazy, and I want access to Slerp in Python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13810)
=> py eigen_geometry: Bind Quaternion.slerp

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
Follow up to #13747.  Adds the bindings for Planar Joint.
Relates #12404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13813)
=> pydrake multibody: Add bindings for PlanarJoint

common/schema/dev/stochastic.cc, common/schema/dev/stochastic.h, common/schema/dev/test/stochastic_test.cc
This copies into Drake some small fixups that have been applied in Anzu since these files were originally forked.
Relates #13251.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13822)
=> schema: Incorporate some Anzu nit fixes

setup/BUILD.bazel
We missed this in 06604c29e3c9c276646b0a5a7fbfd651d8e7049b (#13753).
TRI's Anzu needs the full lists to slurp it into our setup procedures.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13827)
=> setup: Export all of the package list txt files

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py
Relates #12754.  Builds atop #13814.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13826)
=> bindings: Bind pydrake.multibody.Parser.AddModelFromString

examples/irb140/README.md, examples/kuka_iiwa_arm/models/objects/README.md
These are unused, untested, and have large meshes that do not follow the `RobotLocomotion/models` policy (#11913).  Git remembers.
Drake is not a clearinghouse for models, it's a repository of software.  All model files on master should be actively used by some demo or test case.
This is short-changing the 3-months-round-up rule of thumb by one week, but given that it's only removing some data files that are easy to copy for any users who still need these, I'd rather keep the more aggressive timeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13831)
=> examples: Deprecate IRB140 and big_robot_toy models

multibody/plant/multibody_plant.h
Per PR# 12804, we originally considered CalcJacobianSpatialVelocity() to allow an input argument with multiple position vectors and return an output argument with multiple JacobianSpatialVelocities (one for each point).  We decided that that CalcJacobianTranslationalVelocity() was more efficient and better suited for that purpose.  This PR allows PR#12804 to be deleted and also fixes a small deficiency in documentation for CalcJacobianSpatialVelocity() that alludes the no-longer-allowable idea of multi-point input/output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13837)
=> Fix documentation for CalcJacobianSpatialVelocity() and also kill PR# 12804.

manipulation/util/show_model.py
It was referring to a urdf file that does not exist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13847)
=> Fix doc string in show_model.py

bindings/pydrake/systems/planar_scenegraph_visualizer.py, bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py
Now meshes that are in mm shouldn't show up as enormous geometries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13836)
=> pydrake: Respect mesh scaling in PlanarSceneGraphVisualizer

tools/install/dockerhub/bionic/Dockerfile, tools/install/dockerhub/focal/Dockerfile
On prebuilt Docker images, rename `drake-visualizer` to
`drake-visualizer.image`. Create a `drake-visualizer` script that prints a
warning message with a pointer to the renamed file.
Resolves #12483 and #13639
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13764)
=> Replace drake-visualizer with warning script on prebuilt Docker images

tools/workspace/sdformat/no-console-file.patch, tools/workspace/sdformat/repository.bzl
Log messages still appear on `std::cerr`, just not in a file anymore.
Libraries should not unconditionally open non-standard files nor create non-standard directories.
This removes the "No HOME defined in the environment. Will not log." message when running tests in bazel's hermetic sandbox.
Relates #9087 and https://github.com/osrf/sdformat/issues/334.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13850)
=> parsing: Disable $HOME/.sdformat/sdformat.log

systems/framework/context.h
User Story:
- Went to doxygen for `Simulator` to review #13851 
- Clicked on `Context` to review caching
- Remember there was a design doc, saw no mention of it here
- Remembered that we have a Technical Notes (as an "expert" drake user)
This should make things more traceable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13852)
=> context: Add cross-reference to cache design docs

examples/rimless_wheel/test/rimless_wheel_test.cc, multibody/plant/test/joint_limits_test.cc, systems/analysis/simulator.cc, systems/analysis/simulator.h, systems/analysis/test/simulator_test.cc, systems/controllers/dynamic_programming.cc
Related to #13741.
* remove a false member
* add time jump check as one-time warning
* adjust tests that use time jumps
* adjust doc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13851)
=> simulator: Warn about time jumps

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/tree/multibody_tree_system.h
MBP's generalized acceleration (vdot) cache is unneeded since vdot is also cached in the AccelerationKinematicsCache. All uses of the vdot cache simply evaluated the AccelerationKinematicsCache and then copied vdot out of it. This PR gets rid of that and instead makes use of the AccelerationKinematicsCache directly.
This is a lemma PR toward #13854.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13855)
=> Remove redundant generalized_acceleration cache from MultibodyPlant

bindings/pydrake/systems/planar_scenegraph_visualizer.py
Prior to this commit, we stored all of the vertices of each mesh and then took
their convex hull after projecting them to the visualization plane every dt. Now
we only store the vertices of the 3D convex hull of each mesh. The 2D convex
hull must still be computed at each dt, but, for meshes with lots of interior
vertices, it will now be over a much smaller set of points.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13857)
=> PlanarSceneGraphVisualizer: Store convex hulls of meshes

examples/multibody/cassie_benchmark/BUILD.bazel, examples/multibody/cassie_benchmark/README.md, examples/multibody/cassie_benchmark/cassie_v2.urdf, examples/multibody/cassie_benchmark/copy_results_to, examples/multibody/cassie_benchmark/record_results.sh, examples/multibody/cassie_benchmark/test/cassie_bench.cc
This PR subsumes a snapshot of #13770. I'm publishing it so we can compare the two benchmark programs and discuss how to go forward.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13782)
=> Cassie bench gbench

examples/multibody/cassie_benchmark/BUILD.bazel
Valgrind runs were detecting that lsb_release is written in Python, and
complaining about all the usual things.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13865)
=> cassie_benchmark: Fix nightly build break

systems/framework/diagram_builder.cc, systems/framework/diagram_builder.h
Towards #12814.
Also remove the now-unnecessary internal impl forwarding.
Also remove a TODO that's already done.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13866)
=> framework: Relocate diagram_builder method bodies to cc file

bindings/pydrake/geometry_py.cc
When a DrakeLcm object is constructed in Python, within the call to ConnectDrakeVisualizer, nothing was keeping it alive which lead to a seg fault when the diagram was initialized ([see minimal reproduction](https://github.com/mpetersen94/drake/commit/d8b97d5b0f7c7cd6cf564cc97d779a74ecb69cf9)).  This ensures that the DrakeLcm object is kept alive so long as the diagram it is apart of is alive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13868)
=> bindings: Fix ConnectDrakeVisualizer keep_alive behavior

multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/frame_kinematics_test.cc, multibody/tree/body.h, multibody/tree/frame.h, multibody/tree/multibody_tree.h
Per issue #13754, the Frame and Body classes currently have methods to calculate Pose and SpatialVelocity such as Frame::CalcSpatialVelocityInWorld().  It is natural that these classes have corresponding methods for SpatialAcceleration, e.g., Frame::CalcSpatialAccelerationInWorld().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13773)
=> Implement Frame::CalcSpatialAccelerationInWorld()

common/autodiff_overloads.h, common/copyable_unique_ptr.h, common/identifier.h, multibody/math/spatial_vector.h, multibody/tree/rotational_inertia.h, multibody/tree/spatial_inertia.h, perception/point_cloud.h, perception/point_cloud_flags.h, systems/controllers/setpoint.h, systems/primitives/symbolic_vector_system.cc
- The only time we _should_ use `inline` is for non-templated functions defined at namespace scope in a header file, so that they link correctly (ala ODR).
- Methods defined within a class definition are automatically inline, no need for the keyword.
- Templated methods are automatically inline, no need for the keyword.
As inspired by https://github.com/RobotLocomotion/styleguide/pull/33.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13887)
=> Remove spurious uses of the inline keyword

common/BUILD.bazel, common/symbolic.h, common/symbolic_chebyshev_basis_element.cc, common/symbolic_chebyshev_basis_element.h, common/symbolic_monomial_basis_element.cc, common/symbolic_monomial_basis_element.h, common/symbolic_polynomial_basis_element.h, common/test/symbolic_chebyshev_basis_element_test.cc, common/test/symbolic_monomial_basis_element_test.cc
This PR is a step to #13803. 
This PR is large, but most of the code is just copy from `symbolic_monomial.h, symbolic_monomial.cc` and `symbolic_monomial_test.cc`.
The major change is
1. The return type of `operator*` is different in `MonomialBasisElement` vs `Monomial`. To keep the API consistent with `ChebyshevBasisElement`, the return type is `std::map<MonomialBasisElement, double>` instead of a single `Monomial`.
2. I added `Differentiate` and `Integration` to `MonomialBasisElement`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13867)
=> Add MonomialBasisElement.

bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/general_test.py, systems/analysis/simulator.cc, systems/analysis/simulator.h, systems/analysis/test/simulator_test.cc
Closes #13858.
* Add defaulted parameter struct arg to Initialize(). This yields legible call
sites and leaves room for adding further parameters.
* Adjust existing test to cover a no-init simulator reuse.
* Add python bindings, and extend existing tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13872)
=> simulator: Optionally suppress initialization events

systems/framework/vector_system.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13896)
=> framework: remove redundant get_input_port() and get_output_port()

examples/pendulum/pendulum_plant.cc, examples/pendulum/pendulum_plant.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13894)
=> examples: remove redundant get_input_port() and get_output_port()

common/yaml/yaml_read_archive.cc, common/yaml/yaml_read_archive.h
It's now an error for yaml data to remain unparsed, unless the user opts-in to allowing it.
The syntax to opt-in was added in Drake v0.19.0 released on 2020-06-15.  Now that v0.22.0 release 2020-08-17 is available, it seems safe enough to flip the default on master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13900)
=> yaml: Change allow_yaml_with_no_cpp's default to false

manipulation/kinova_jaco/jaco_command_receiver.cc, manipulation/kinova_jaco/jaco_command_receiver.h, manipulation/kinova_jaco/jaco_command_sender.cc, manipulation/kinova_jaco/jaco_command_sender.h, manipulation/kinova_jaco/jaco_status_receiver.cc, manipulation/kinova_jaco/jaco_status_receiver.h, manipulation/kinova_jaco/jaco_status_sender.cc, manipulation/kinova_jaco/jaco_status_sender.h, manipulation/kuka_iiwa/iiwa_command_sender.cc, manipulation/kuka_iiwa/iiwa_command_sender.h, manipulation/kuka_iiwa/iiwa_status_receiver.cc, manipulation/kuka_iiwa/iiwa_status_receiver.h, manipulation/kuka_iiwa/iiwa_status_sender.cc, manipulation/kuka_iiwa/iiwa_status_sender.h, manipulation/schunk_wsg/schunk_wsg_plain_controller.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13895)
=> manipulation: remove redundant get_input_port() and get_output_port()

systems/rendering/multibody_position_to_geometry_pose.cc, systems/rendering/multibody_position_to_geometry_pose.h, systems/rendering/render_pose_to_geometry_pose.cc, systems/rendering/render_pose_to_geometry_pose.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13897)
=> systems/rendering: remove redundant get_input_port() and get_output_port()

bindings/pydrake/BUILD.bazel, bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/__init__.py, bindings/pydrake/common/eigen_geometry_py.cc, bindings/pydrake/common/eigen_pybind.h, bindings/pydrake/common/test/eigen_geometry_test.py, bindings/pydrake/math_py.cc, bindings/pydrake/pydrake_doxygen.h, bindings/pydrake/test/math_test.py
Resolves #13885
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13886)
=> pydrake math: Ensure that .multiply preserves input shape

examples/rod2d/BUILD.bazel, examples/rod2d/rod2d.cc, examples/rod2d/rod2d.h, examples/rod2d/rod2d_geometry.cc, examples/rod2d/rod2d_geometry.h, examples/rod2d/rod2d_sim.cc, examples/rod2d/test/rod2d_test.cc
Supplant the old visualization mechanism with the standard used in examples. examples/rod2d is no longer dependent on attic code.
resolves #13316
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13890)
=> [examples] Connect rod 2d to SceneGraph for visualization

tools/workspace/cc/BUILD.bazel, tools/workspace/cc/identify_compiler.cc
Add a build rule so identify_compiler gets built the same way as the rest of Drake. It was also missing a final newline.
See #13902.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13906)
=> Add a build rule and a final newline for identify_compiler

systems/lcm/lcm_publisher_system.h, systems/lcm/lcm_subscriber_system.h, systems/plants/spring_mass_system/spring_mass_system.cc, systems/plants/spring_mass_system/spring_mass_system.h, systems/primitives/adder.h, systems/primitives/discrete_derivative.cc, systems/primitives/discrete_derivative.h, systems/primitives/discrete_time_delay.cc, systems/primitives/discrete_time_delay.h, systems/primitives/pass_through.cc, systems/primitives/pass_through.h, systems/primitives/port_switch.h, systems/primitives/saturation.cc, systems/primitives/saturation.h, systems/primitives/signal_logger.cc, systems/primitives/signal_logger.h, systems/primitives/symbolic_vector_system.cc, systems/primitives/symbolic_vector_system.h, systems/primitives/zero_order_hold.cc, systems/primitives/zero_order_hold.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13898)
=> primitives: remove redundant get_input_port() and get_output_port()

examples/multibody/cassie_benchmark/BUILD.bazel
Closes #13910.
This makes the benchmark program more structurally similar to most Drake
executables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13913)
=> cassie_bench: Force static linking

examples/multibody/cassie_benchmark/record_results.sh
Prior options were stripping raw data out of the json file, which is
worth keeping for statistical comparisons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13914)
=> cassie bench: Fix blunder in benchmark configuration

multibody/tree/frame.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/test/frames_test.cc
This PR helps progress on issue #13754.
Much of the code created for CalcBiasSpatialAcceleration() is also useful for CalcSpatialAcceleration().  
I started by creating a large PR that implements both what is done in this PR (splitting generally useful spatial acceleration code from bias-only spatial acceleration code) as well as implementing new functionality for CalcSpatialAcceleration().  However, it was unnecessarily large and complex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13838)
=> Consolidate code for both bias and regular (unbias) spatial accelerations.

geometry/benchmarking/mesh_intersection_benchmark.cc, geometry/proximity/mesh_half_space_intersection.cc, geometry/proximity/mesh_intersection.cc, geometry/proximity/mesh_intersection.h, geometry/proximity/mesh_plane_intersection.cc, geometry/proximity/test/contact_surface_test.cc, geometry/proximity/test/mesh_half_space_intersection_test.cc, geometry/proximity/test/mesh_intersection_test.cc, geometry/proximity/test/mesh_plane_intersection_test.cc, geometry/query_results/contact_surface.h, geometry/test/proximity_engine_test.cc, geometry/test/query_object_test.cc
1. Introduce new (optional) data for ContactSurface.
- The gradients of the constituent fields sampled once per *triangle*.
2. Extend API to allow for addition of new data in results.
- QueryObject
- GeometryState
- ProximityEngine
- HydroelasticCallback
- Soft-rigid mesh intersection
- rigid half space-soft mesh intersection
- soft half space-rigid mesh intersection
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13864)
=> [geometry] Geometry support for discrete hydroelastic contact

multibody/plant/propeller.h, systems/systems.h
I noticed that the Propeller system was sitting in a very odd place in the doxygen hierarchy.  This cleans that up.
Also resolves a stale reference to simple_car.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13929)
=> Add doxygen group for multibody systems

common/BUILD.bazel, common/symbolic.h, common/symbolic_monomial_util.h, common/symbolic_polynomial_basis.h, common/test/symbolic_polynomial_basis_test.cc
This function is the same as `ComputeMonomialBasis` function in https://github.com/RobotLocomotion/drake/blob/617396edf592997731604fa16030470e92548d20/common/symbolic_monomial_util.h#L138-L177, but it works for different PolynomialBasisElement class. Also this new function is in `drake::symbolic` namespace instead of `drake::symbolic::internal` namespace, as I plan to call this function directly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13870)
=> add a function to compute polynomial basis up to a given order.

common/test_utilities/limit_malloc.cc, common/test_utilities/limit_malloc.h, common/test_utilities/test/limit_malloc_test.cc, examples/multibody/cassie_benchmark/test/cassie_bench.cc
* expose allocation count from LimitMalloc
* track allocations with some simple stats
* separate first run to expose steady state allocation
* lower some Limitmalloc ceilings from observations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13930)
=> cassie_bench: Improve allocation tracking

common/test_utilities/test/limit_malloc_test.cc
On macOS, the device under test is inoperative, so it can't track allocation counts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13932)
=> Fix limit_malloc_test on macOS

multibody/solvers/BUILD.bazel, multibody/solvers/linear_operator.cc, multibody/solvers/linear_operator.h, multibody/solvers/sparse_linear_operator.cc, multibody/solvers/sparse_linear_operator.h, multibody/solvers/test/linear_operator_test.cc, multibody/solvers/test/sparse_linear_operator_test.cc
Our contact solvers usually won't need the explicit expression for matrices describing the system's dynamics. Providing the operator form, ie. y = A*x instead of the explicit form of A is enough to form our Schur-complements and Delassus operators. In addition, if the linear operator allows for sparsity, these operations can be performed efficiently. 
This PR introduces the LinearOperator concept and provides a specific implementation for when a sparse matrix is available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13911)
=> Implements a LinearOperator class to be used by contact solvers.

examples/multibody/cassie_benchmark/test/cassie_bench.cc, multibody/tree/body_node.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/multibody_tree_system.cc, multibody/tree/multibody_tree_system.h
This is the first in a long series of changes to eliminate heap allocations and other performance issues in MBPlant. 
Changes here:
- Adds a cache entry for composite body inertias so CalcMassMatrix() doesn't have to heap allocate them. That removes just one heap allocation from each CalcMassMatrix() call.
- Updated the heap limit in cassie_benchmark accordingly (from 175 to 174; I verified it fails at 173).
- Modernized the MBTreeSystem cache allocation code to make it more readable. That requires having some inline methods defined in MBTreeSystem that can be provided as the cache entries' Calc() methods. Made some (internal) name changes for consistency.
- Changed terminology for composite body inertias from "R" to "Mc" since R means rotation matrix and "M" is used for spatial inertias …
=> Reduce heap allocation in CalcMassMatrix()

examples/multibody/cassie_benchmark/README.md, examples/multibody/cassie_benchmark/record_results.sh
Relevant to #13902.
On linux only, invoke the benchmark under the `taskset` command. Add a
bit of documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13936)
=> cassie bench: Add processor affinity control for Linux

bindings/pydrake/systems/jupyter_widgets.py
clearly it should have been there.  it was somehow not needed in most cases, but mac nbconvert seemed to miss it.  (go figure)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13941)
=> Adds missing import for jupyter widgets

examples/multibody/cassie_benchmark/test/cassie_bench.cc, multibody/math/BUILD.bazel, multibody/math/spatial_force.h, multibody/math/test/spatial_algebra_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/spatial_inertia.h
This is a follow-up from #13928 that gets rid of the rest of the heap allocation for CalcMassMatrix().
Also:
- Eliminates unnecessary work done for weld (fixed) joints.
- Adds a SpatialForce::ShiftInPlace() method and uses it in place of SpatialForce::Shift(). In-place is more efficient since translational forces don't change, and the method uses no heap space. 
- Reimplemented SpatialForce::Shift() in terms of ShiftInPlace() to eliminate its heap use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13933)
=> Eliminate remaining heap use from CalcMassMatrix()

common/yaml/test/yaml_write_archive_defaults_test.cc, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_write_archive.cc, common/yaml/yaml_write_archive.h
This PR allows the Emitter to dump the internal root node directly. This is useful if the user only wants to dump an accepted schema as it is rather than assigning it to a key name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13915)
=> Allow yaml write to dump the node without a keyname

examples/multibody/cassie_benchmark/record_results.sh
Relevant to #13902.
Prior patches to enable CPU affinity were effectively no-op, since the
relevant assignment was done within a subshell (parentheses). However,
the only thing in the subshell was a case block, so the redirection
grouping happens for free anyway.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13946)
=> cassie_bench: Fix defect affecting affinity

common/schema/dev/stochastic.cc, common/schema/dev/stochastic.h, common/schema/dev/test/stochastic_test.cc
This merges up a recent patch from Anzu.
Towards #13251.  Noted by #13943.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13948)
=> schema: Rename gaussian std to stddev

common/schema/dev/rotation.h, common/schema/dev/stochastic.cc, common/schema/dev/stochastic.h, common/schema/dev/transform.h
Per discussion in #13943 for GSG.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13947)
=> schema: Use 'class' not 'struct' for more complex types

common/test_utilities/limit_malloc.cc, common/test_utilities/test/limit_malloc_test.cc, examples/multibody/cassie_benchmark/test/cassie_bench.cc, systems/framework/cache_entry.cc, systems/framework/cache_entry.h, systems/framework/diagram_output_port.h, systems/framework/leaf_output_port.cc, systems/framework/leaf_output_port.h, systems/framework/output_port.cc, systems/framework/output_port.h, systems/framework/test/output_port_test.cc
Reworks two Debug-mode validations that were done using heap-allocated value objects for cache entries to avoid heap use.
The difference in heap allocations between Debug and Release builds made it hard to track down spurious use of the heap in MultibodyPlant, which is best done in Debug builds; this makes the Debug and Release heap use the same (and also makes the validations less expensive).
Also:
- Moves one method definition from the output_port.h header to the .cc file to follow our updated style guidelines.
- Updates cassie_bench to unconditionally limit heap allocation to zero.
- Enforces heap limits in both Release and Debug for the non-AutoDiff tests; AutoDiff allocations are still greater in Debug.
- Added counts to the LimitMalloc error message.
--- …
=> Revise Debug-mode cache value validation to avoid heap allocation.

examples/multibody/cassie_benchmark/BUILD.bazel, examples/multibody/cassie_benchmark/README.md, examples/multibody/cassie_benchmark/conduct_experiment, examples/multibody/cassie_benchmark/record_results.sh
Relevant to: #13902
This patch allows passing additional cassie_bench arguments when using
the :record_results target, or the conduct experiment script. In
addition, it exploits the new capability to waste less build time
running the :record_results test in debug mode.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13963)
=> cassie_bench: Pass optional arguments to benchmark program

bindings/pydrake/examples/manipulation_station_py.cc, examples/manipulation_station/end_effector_teleop_dualshock4.py, examples/manipulation_station/end_effector_teleop_mouse.py, examples/manipulation_station/end_effector_teleop_sliders.py, examples/manipulation_station/manipulation_station.cc, examples/manipulation_station/manipulation_station.h, manipulation/models/wsg_50_description/BUILD.bazel, manipulation/models/wsg_50_description/README.md, manipulation/models/wsg_50_description/sdf/schunk_wsg_50_no_tip.sdf, manipulation/models/wsg_50_description/sdf/schunk_wsg_50_with_tip.sdf, manipulation/models/wsg_50_description/sdf/test/wsg_50_sdf_test.cc, tools/workspace/models/files.bzl, tools/workspace/models/package.BUILD.bazel, tools/workspace/models/repository.bzl
A fix to #13875 , adds two more realistic looking Schunk grippers for better visualization (+ perhaps some improvements to modeling collision geometry for the real schunk) 
The first model consists of real-looking schunk without the fingertip. 
The second model includes fingertip with some collision spheres.
Includes changes to manipulation_station, its bindings, and end_effector_teleop codes so that different schunks can be called at runtime. 
`./bazel-bin/examples/manipulation_station/end_effector_teleop_mouse --schunk_model=box_schunk`
`./bazel-bin/examples/manipulation_station/end_effector_teleop_mouse --schunk_model=real_schunk_no_tip`
`./bazel-bin/examples/manipulation_station/end_effector_teleop_mouse --schunk_model=real_schunk_with_tip`
Same function is added to …
=> Better schunk models in manipulation station

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py, tools/workspace/meshcat_python/repository.bzl
Adds an argument to the constructor to avoid deleting the entire tree on every run.
Sets uuids deterministically based on the mesh file so that they can be recognized as identical on the server.
See https://github.com/rdeits/meshcat-python/pull/75
This makes a *dramatic* improvement in the workflow of using meshcat on colab (at least as we use it in drake), because we don't have to repeatedly download large meshfiles from repeated simulations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13971)
=> MeshcatVisualizer: Tweaks to support caching mesh geometry on the zmqserver

multibody/benchmarks/acrobot/make_acrobot_plant.cc, multibody/benchmarks/acrobot/make_acrobot_plant.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc, multibody/tree/BUILD.bazel, multibody/tree/body.h, multibody/tree/multibody_element.h, multibody/tree/multibody_tree.h, multibody/tree/multibody_tree_system.cc, multibody/tree/multibody_tree_system.h, multibody/tree/parameter_conversion.h, multibody/tree/rigid_body.h, multibody/tree/rotational_inertia.h
- Make RigidBody declare/store a NumericParameter for SpatialInertia parameters
- Declare cache dependencies 
- Fleshed out `Body` methods to access parameters from context
- `get_mass(const systems::Context<T> &)`
- `CalcCenterOfMassInBodyFrame(const systems::Context<T>&)`
- `CalcSpatialInertiaInBodyFrame(const systems::Context<T>&)`
- Creates an API in RigidBody for parameters:
- `RigidBody::SetMass(Context<T>*, const T& mass)`
- `RigidBody::SetCenterOfMassInBodyFrame(Context<T>*, const Vector3<T>& com)`
- `RigidBody::SetSpatialInertiaInBodyFrame(Context<T>*, const SpatialInertia<T>& M_BBo_B)`
- Small bug fix in `multibody/benchmarks/acrobot/make_acrobot_plant`
--- …
=> Parameterizes rigid bodies in MBP

bindings/pydrake/systems/framework_py_semantics.cc, systems/framework/framework_common.h, systems/framework/input_port_base.h, systems/framework/output_port.cc, systems/framework/port_base.cc, systems/framework/port_base.h
The mention of an unimplemented feature is a distraction for users.
In pydrake, remove it immediately.  (As of Python 3.6, there is no official support for deprecating attributes; it's new as of 3.7.) This is a breaking change.
Closes #3109.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13981)
=> framework: Deprecate kAutoSize

doc/index.rst, doc/installation.rst, tutorials/README.md
Update URLs in drake from
`https://mybinder.org/v2/gh/RobotLocomotion/drake/nightly-release` to
`https://mybinder.org/v2/gh/RobotLocomotion/drake/nightly-release-binder`.
Drake-ci pull request [#115](https://github.com/RobotLocomotion/drake-ci/pull/115)
Resolves #13209
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13979)
=> Update references to binder release URL

common/name_value.h, common/schema/rotation.h, common/schema/stochastic.cc, common/schema/stochastic.h, common/schema/test/rotation_test.cc, common/schema/test/stochastic_test.cc, common/schema/test/transform_test.cc, common/schema/transform.h
In #13943 and #13949 there were some clean-ups suggested.  This realizes those requests.
Commits are separate for review, but will be squashed before merging.
Closes #13251.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13991)
=> Tidy up nits on schema classes

setup/BUILD.bazel, setup/mac/install_prereqs.sh, setup/mac/source_distribution/Brewfile, setup/mac/source_distribution/Brewfile-doc-only, setup/mac/source_distribution/install_prereqs.sh, setup/ubuntu/install_prereqs.sh, setup/ubuntu/source_distribution/install_prereqs.sh, setup/ubuntu/source_distribution/packages-bionic-doc-only.txt, setup/ubuntu/source_distribution/packages-bionic.txt, setup/ubuntu/source_distribution/packages-focal-doc-only.txt, setup/ubuntu/source_distribution/packages-focal.txt
Relates #12783 and #13168. In two minds about whether to add the `--without-doc-only` flag, but it is here in this PR will can be tested during the CMake and/or packaging builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13984)
=> Separate out dependencies related to documentation generation

bindings/pydrake/manipulation/planner_py.cc, bindings/pydrake/manipulation/test/planner_test.py, manipulation/planner/differential_inverse_kinematics_integrator.cc, manipulation/planner/differential_inverse_kinematics_integrator.h, manipulation/planner/test/differential_inverse_kinematics_integrator_test.cc
This significantly improves the robustness of the teleoperation demo on colab.  Currently, if a user drives the robot into singularity (and it is relatively common mistake), then the diff IK spews so many warnings that the sliders disappear (and so does the "stop simulation" button).  This allows users to recover from it without closing/crashing their kernel.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14004)
=> DifferentialIKSystem: Add (optional) discrete state to "warn once"

doc/developers.rst, setup/ubuntu/source_distribution/install_prereqs.sh
I actually went and tested 2.0.1 (our minimum per WORKSPACE), and it appeared to still work.  Thus, I'm not bumping the minimum.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14005)
=> setup: Upgrade recommended Bazel version to 3.5

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/scene_graph_inspector.h, geometry/test/geometry_state_test.cc, geometry/test/scene_graph_inspector_test.cc
This introduces a new API. Given a frame id, the ids of the frame's geometries can be returned. It can be filtered on a particular role.
This includes the C++ and python interface.
(In the process of adding tests to the new pydrake bindings, I noticed that there were tests missing for previously existing python APIs. They were added and the *order* of the existing tests were changed to match the order of the bindings to ease future reading.)
This is the alternate solution to issue #13970.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13999)
=> [geometry] API to get a frame's geometries

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc
This is all pattern-matched off of the bindings for `AffineSystem()`. This also adds a binding for `PiecewisePolynomial` addition, which is useful when preparing the trajectories to be passed to `TrajectoryAffineSystem`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14009)
=> pydrake: Bind TrajectoryAffineSystem

multibody/tree/BUILD.bazel, multibody/tree/linear_bushing_roll_pitch_yaw.h, multibody/tree/test/linear_bushing_roll_pitch_yaw_test.cc
- Adds 4 parameters, one for each of (torque/force stiffness/damping) to `LinearBushingRollPitchYaw`.
- Moves parameters related tests from `multibody/test/multibody_plant_test.cc` to `multibody/test/multibody_plant_parameters_test.cc`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14000)
=> adds parameters for LinearBushingRollPitchYaw

systems/primitives/affine_system.cc, systems/primitives/test/affine_system_test.cc
Return early from `TimeVaryingAffineSystem::DoCalcTimeDerivatives()` if `this` is a discrete-time system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14008)
=> systems: Fix #14006

geometry/geometry_state.cc, geometry/proximity_engine.cc, geometry/proximity_engine.h, geometry/render/render_engine_vtk.cc, geometry/render/test/render_engine_test.cc, geometry/test/geometry_state_test.cc, geometry/test/proximity_engine_test.cc, geometry/test_utilities/dummy_render_engine.h
Geometry world pose as up to date as possible after Registration
Prior to this, the world pose of the geometry was ignored upon registration. It was assumed that any query that depended on geometry world pose would be preceded by a call that updates the frames' poses.
However, it is possible to
- Update frame poses
- Add a geometry
- perform a query
In that case, the added geometry will not have the correct world pose.
This change stores a value for X_WG based on the assumption that X_WF is meaningful. If the assumption is correct, X_WG will likewise be meaningful. If the assumption is wrong, we are not harmed.
Furthermore, for the queries (e.g., illustration, perception, and proximity) to work, those values need to propagate downwards. Work for proximity and perception has been done. The …
=> Geometry world pose as up to date as possible after Registration

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py
The {Proximity|Illustration|Perception}Properties now have a copy constructor in pydrake. This facilitates the ability to update/replace properties.
This is the second piece necessary to meaningfully enable #13970.
resolves #13970.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14010)
=> [pydrake] Enable GeometryProperty copy construction in pydrake

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/planar_scenegraph_visualizer.py
Fixes #13846 by modifying the meshcat and planar scenegraph visualizers to ignore visual geometry with non-positive `geom.float_data` entries.
See #13846 for a picture of `drake/manipulation/models/jaco_description/urdf/j2s7s300.urdf` as visualized in meshcat before this change. After this change, all seems well:
And the planar visualizer is happy as well (before this change, it threw an error at a convex hull computation during init):
And the manipulation station looks good too, which I believe stresses all of the other geometry types:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14013)
=> Ignore geometry with invalid sizes in meshcat and pyplot visualizers.

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/all.py, bindings/pydrake/common/schema_py.cc, bindings/pydrake/common/test/schema_test.py, bindings/pydrake/test/all_test.py, common/schema/transform.cc, common/schema/transform.h
This only binds the variable-sized stochastic vector types.
The fixed-size stochastic vector type are not yet available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14014)
=> pydrake: Add bindings for common.schema

bindings/pydrake/systems/sensors_py.cc, bindings/pydrake/systems/test/sensors_test.py
Resolves #8919
Test does not indicate a difference in Drake, but fixes a segfault in Anzu PR 5371
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14015)
=> py sensors: Ensure keep_alive for Image[].data is honored

bindings/pydrake/common/jupyter.py
my bazel test script on travis ubuntu has been failing because get_ipython() returns an object, but not one that has a usable kernel.
https://github.com/RussTedrake/manipulation/runs/1077702318?check_suite_focus=true
This makes it more robust.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14025)
=> jupyter: more robust fail fast when running as non-interactive kernel

bindings/pydrake/manipulation/simple_ui.py, bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, bindings/pydrake/multibody/jupyter_widgets.py
Restores #13884
With one modification: the Jupyter notebook is moved to the  ``examples`` subdirectory. It seems that the Jupyter infrastructure includes the current directory in the path. When the notebook is in the ``pydrake/multibody`` directory, this causes ``import math`` to use ``pydrake.multibody.math`` rather than the Python standard library.
Follow-up to: #13901
Resolves #13918
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14017)
=> Add jupyter widget version of JointSliders

common/symbolic_expression.cc, common/symbolic_expression.h, common/symbolic_expression_cell.cc, common/symbolic_expression_cell.h, common/symbolic_formula.h, common/symbolic_formula_cell.cc, common/symbolic_formula_cell.h, common/test/symbolic_expansion_test.cc, common/test/symbolic_expression_differentiation_test.cc, solvers/test/bilinear_product_util_test.cc
- Add `[[nodiscard]]` attribute. Update the affected test cases.
- Mark deleted methods public
- [modernize-pass-by-value](https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html)
- `auto&` => `const auto&` in for-loop
- Remove redundant declarations in `symbolic_{expression,formula}_cell.h` as they
are already in `symbolic_{expression,formula}.h`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14020)
=> Refactor symbolic expression / formula

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_generation_test.cc
for incremental construction of first-order polynomial trajectories.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14030)
=> trajectories: Adds PiecewisePolynomial::AppendFirstOrderSegment

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
As discussed with @gizatt and @SeanCurtis-TRI in #13971.  The change does seem painless, and only an improvement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14024)
=> multibodyplant: tell scenegraph my name when registering as a source

common/symbolic_chebyshev_basis_element.h, common/symbolic_chebyshev_polynomial.h, common/symbolic_codegen.h, common/symbolic_environment.cc, common/symbolic_environment.h, common/symbolic_generic_polynomial.cc, common/symbolic_generic_polynomial.h, common/symbolic_monomial_basis_element.h, common/symbolic_monomial_util.h, common/symbolic_polynomial_basis.h, common/symbolic_polynomial_basis_element.cc, common/symbolic_polynomial_basis_element.h, common/symbolic_rational_function.cc, common/symbolic_rational_function.h, common/symbolic_simplification.cc, common/symbolic_variable.h, common/symbolic_variables.cc, common/symbolic_variables.h, common/test/symbolic_generic_polynomial_test.cc, common/test/symbolic_monomial_basis_element_test.cc, common/test/symbolic_polynomial_basis_element_test.cc
- Add `[[nodiscard]]` attribute. Update the affected test cases.
- [modernize-pass-by-value](https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html)
- Remove implicit Boolean conversion for readability
- `RationalFunction::operator-`: change parameter types
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14021)
=> Refactor other symbolic classes

geometry/render/gl_renderer/render_engine_gl.cc, geometry/render/gl_renderer/render_engine_gl.h, geometry/render/gl_renderer/shape_meshes.cc, geometry/render/gl_renderer/shape_meshes.h, geometry/render/gl_renderer/test/render_engine_gl_test.cc, geometry/render/gl_renderer/test/shape_meshes_test.cc
- mesh generation (shape_meshes.*)
- Generate an arbitrary capsule.
- incidental typos corrected in header file.
- unit tests to confirm capsule geometry satisfies certain invariants.
- unit tests slightly refactored to re-use code; an invariant for all convex shapes centered on the origin placed into its own function. (This function will expand in the future.)
- mesh rendering
- RenderEngineGl models an Ellipse with a Sphere and non-uniform scale.
- Treats every Capsule as unique.
- unit tests are copied verbatim from render_engine_vtk_test.cc for capsule and ellipse.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14001)
=> [render] Adds Capsule and Ellipse to RenderEngineGl

common/BUILD.bazel, common/test/autodiffxd_heap_test.cc, common/test_utilities/limit_malloc.cc, common/test_utilities/limit_malloc.h, common/test_utilities/test/limit_malloc_test.cc
Relevant to: #13985
Extend and use LimitMalloc to measure and enforce heap use of AutoDiffXd
math operators. These limits will help clarify the effect of subsequent
changes on the implementation of AutoDiffXd.
Summary of changes
* LimitMalloc:
* Add params() accessor and .min_num_allocations parameter
* Adjust error messages for clarity
* Extend unit tests to cover new features
* autodifxd_*_test.cc:
* Add LimitMalloc guards to enforce exact heap usage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14018)
=> autodiffxd tests: Establish heap use baselines

manipulation/models/jaco_description/urdf/j2n6s300.urdf, manipulation/models/jaco_description/urdf/j2n6s300_col.urdf
An upcoming PR will mention this model in a `data=` line, which will
cause it to be validity checked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14042)
=> Remove invalid geometry from the jaco model

common/test_utilities/limit_malloc.cc, common/test_utilities/limit_malloc.h, tools/dynamic_analysis/drd.sh, tools/dynamic_analysis/helgrind.sh, tools/dynamic_analysis/valgrind.sh
Fixes a nightly build failure seen here:
https://drake-cdash.csail.mit.edu/viewTest.php?onlydelta&buildid=1336134
This solution may seem like overkill, when I could have just set tags in
bazel rules. Here are some reasons why I didn't do that:
* bazel tags don't (yet^) propagate up dependency chains, so any
library module that induces the need for tags just sets off an
endless game of whack-a-mole.
^yet: see https://github.com/bazelbuild/bazel/issues/8830
* solving LSAN at the source but not similar valgrind problems seems
inconsistent.
Another alternative not taken: checking RUNNING_ON_VALGRIND from
valgrind.h. This solution would have required a bunch of apple-aware
build hacks and/or fighting with Homebrew to ensure that valgrind.h was
installed and available.
Summary of changes:
* …
=> limit_malloc: Disarm under valgrind

common/symbolic_generic_polynomial.cc, common/symbolic_generic_polynomial.h, common/symbolic_monomial_basis_element.h, common/test/symbolic_generic_polynomial_test.cc, common/test_utilities/symbolic_test_util.h
We don't guarantee that the coefficient of the polynomial is expanded (which is not enforced in symbolic_polynomial.h anyway).
A lot of the change in this PR is to move the function from `symbolic::Polynomial` to `symbolic::GenericPolynomial`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14036)
=> Construct polynomial from expression

bindings/pydrake/systems/controllers_py.cc, systems/controllers/inverse_dynamics_controller.cc, systems/controllers/inverse_dynamics_controller.h, systems/controllers/test/inverse_dynamics_controller_test.cc
This PR is trying to resolve the [issue](https://github.com/RobotLocomotion/drake/issues/14011).
This is still a work-in-progress. It's up for discussion purposes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14037)
=> Add a construtor to allow IDC to own the input plant

tools/workspace/pybind11/repository.bzl
Reverts RobotLocomotion/drake#14028
Dear @EricCousineau-TRI ,
The on-call build cop, @DamrongGuoy , believes that your PR #14028 may have
[RobotLocomotion » drake-external-examples » macos catalina 10.15:](https://github.com/RobotLocomotion/drake-external-examples/runs/1098871545?check_suite_focus=true)
now. You …
=> Revert "workspace: Update pybind11 fork to latest commit"

tools/workspace/pybind11/repository.bzl
**Downstream Warning**:
If you are using CMake to consume `pydrake` and you compile your own bindings using `pybind11_add_module`, you must now reset your target's default visibility to "default" (not "hidden").
See [drake_cmake_installed](https://github.com/RobotLocomotion/drake-external-examples/blob/9a70157/drake_cmake_installed/src/simple_bindings/CMakeLists.txt#L45) for an example of doing so.
This reverts commit 690a7eacd136c842d2a7aeda7a5228cfa9d7af95.
Resolves #14047
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14048)
=> Restore "workspace: Update pybind11 fork to latest commit"

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc
These methods were moved from `PiecewiseTrajectory` to its parent class a while ago in C++, but the bindings weren't updated. I'd like to have these as methods of `Trajectory` so that I don't need to repeat the bindings for other children that don't inherit from `PiecewiseTrajectory`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14049)
=> pydrake: Move {start,end}_time() to Trajectory

common/autodiffxd.h, common/test/autodiffxd_heap_test.cc
Relevant to: #13985, #14039
Rewrite various global-scope math functions on AutoDiffScalars to
exploit pass-by-value optimizations; demonstrate resulting improvements
via lowered allocation counts in the heap test. The issues noted above
give more context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14045)
=> AutoDiffScalar: move-aware rewrites of more math

doc/release_notes/v0.23.0.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14061)
=> doc: Fix typo in v0.23 release notes

setup/ubuntu/binary_distribution/install_prereqs.sh, setup/ubuntu/source_distribution/install_prereqs.sh
Rewrite the `apt-get` command lines to fail-fast if there is a filename typo in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14074)
=> setup: Fix typo in Ubuntu maintainer-only code

common/yaml/test/example_structs.h, common/yaml/test/yaml_read_archive_test.cc, common/yaml/yaml_read_archive.h
This change allows the `allow_cpp_with_no_yaml = true` option to correctly return `std::optional` objects that are valid, even when the yaml string does have have the given field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14076)
=> yaml: Bugfix in std::optional handling

examples/manipulation_station/manipulation_station.cc
It has no impact on the manipulation station behavior, but avoids the noisy warnings about unsupported joint limits for continuous time models.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14079)
=> manipulation_station: change controller plant to discrete time

geometry/proximity/BUILD.bazel, geometry/proximity/obb.cc, geometry/proximity/obb.h, geometry/proximity/test/obb_test.cc
A part of solution to issue #13321.
Add Obb (Oriented Bounding Box) to replace Aabb (Axis-aligned Bounding Box). The general structures of the code for Obb and Aabb are similar, so we will try to simplify the code review by having two commits.
Commit1. Copy Aabb to Obb as starting point.
The code of class Aabb is in `bounding_volume_hierarchy*.*`, so we'll copy it to `obb*.*` as the starting point. This commit is a straightforward file copying.
```
cp bounding_volume_hierarchy.h obb.h
cp bounding_volume_hierarchy.cc obb.cc
cp bounding_volume_hierarchy_test.cc obb_test.cc
git add obb.h obb.cc test/obb_test.cc
```
Commit2. Remove Bvh, keep only Aabb that will change to Obb in the next commit.
Commit3. Add content of Obb.
Manually replace class Aabb in obb.h, obb.cc, and obb_test.cc with …
=> [geometry] Add Obb (Oriented Bounding Box).

tools/skylark/drake_cc.bzl, tools/workspace/cc/repository.bzl
Relates #14085. This is the minimal solution to make Xcode 12 users happy again. I will follow up fixing the warnings since they are trivial to fix, but this will stay in place until Ubuntu users can reproduce the same set of compiler warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14091)
=> Disable range-loop-analysis warnings for Clang 10 and Apple Clang 12

multibody/parsing/package_map.cc, multibody/parsing/package_map.h, multibody/parsing/test/package_map_test.cc
As best I can tell, this bug has been around ~forever.
Closes #14032.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14089)
=> parsing: Don't warn when re-discovering the same package.xml

common/eigen_types.h, common/symbolic_decompose.cc, common/test/eigen_types_test.cc, examples/acrobot/acrobot_plant.cc, examples/mass_spring_cloth/cloth_spring_model.cc, examples/mass_spring_cloth/cloth_spring_model.h, math/barycentric.cc, math/barycentric.h, multibody/math/spatial_force.h, multibody/plant/multibody_plant.h, multibody/plant/tamsi_solver.cc, multibody/plant/test/multibody_plant_forward_dynamics_test.cc, multibody/tree/model_instance.cc, multibody/tree/rotational_inertia.h
This is a small installment along the long path to improving MultibodyPlant performance as tracked in #13902. My ultimate goal is to have all inner-loop computations in MBPlant inlined. To achieve that requires that the very lowest-level tiny methods (e.g. accessors, dot products) inline successfully, otherwise they prevent their callers from inlining.
Studying the timings and generated assembly code in kcachegrind for the InverseDynamics subtest, I discovered some unexpected failures-to-inline for some low-level methods:
- EigenPtr operator* and operator-> (implemented via private get_reference())
- Eigen's comma initializer operator as used in RotationalInertia::ReExpressInPlace (see #13962).
EigenPtr had a release-mode error check that I've replaced with a prerequisite checked only in …
=> Improve inlining for EigenPtr and RotationalInertia::ReExpress

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/math_py.cc, bindings/pydrake/multibody/test/math_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14104)
=> py mbp: Allow SpatialVector's to be pickled

bindings/pydrake/common/test_utilities/numpy_compare.py, bindings/pydrake/multibody/math_py.cc, bindings/pydrake/multibody/test/math_test.py
Towards #14086
Intermediate version of #14087
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14096)
=> py mbp: Make SpatialVector's default constructor initialize to NaN

lcmtypes/BUILD.bazel, tools/vector_gen/BUILD.bazel, tools/vector_gen/vector_gen.bzl
This renames some macros (providing deprecation stubs in the meantime).
Closes #14068.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14092)
=> vector_gen: Clarify which macros are to be used outside of Drake

common/identifier.h, common/type_safe_index.h
Asking reviewers to defect (and so authors to obey) a special-cased style rule is a maintenance burden.
Co-requisite of #14094.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14105)
=> common: Don't defect use of TypeSafeIndex or Identifier references

bindings/pydrake/multibody/math_py.cc, multibody/math/BUILD.bazel, multibody/math/spatial_acceleration.cc, multibody/math/spatial_force.cc, multibody/math/spatial_momentum.cc, multibody/math/spatial_velocity.cc
Encapsulates linking artifacts due to dependency cycle
Addresses linking issue in #14097
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14113)
=> multibody/math: Merge all targets into :spatial_algebra

systems/framework/BUILD.bazel, systems/framework/basic_vector.h, systems/framework/subvector.h, systems/framework/supervector.h, systems/framework/test/basic_vector_test.cc, systems/framework/test/continuous_state_test.cc, systems/framework/test/subvector_test.cc, systems/framework/test/supervector_test.cc, systems/framework/vector_base.h
In preparing to move some methods into cc files (#12814), it became clear that a good code split between h and cc would be difficult given the current idioms for bounds checking.
This commit adjusts `operator[]` access to not check bounds (it was already documented not to check, but was doing so anyway) and unifies the exception formatting into the `VectorBase` class.
This is a breaking change in the sense that the exception subclass being thrown may be different now; the API promises are weakened to only promise to throw a `std::exception`, not any specific kind of exception.  The unit tests are weakened to reflect this.
This is breaking change in demoting `BasicVector::DoGetAtIndex` from protected to private.
Also add a Doxygen comment to specify `SetZero`.
Also adjust `#include` …
=> framework: Regularize VectorBase bounds checking

examples/multibody/cassie_benchmark/test/cassie_bench.cc
These gains resulted from @sherm1's PR #13962 but went unclaimed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14115)
=> cassie_bench: Catch up on audodiff allocation improvements

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/tree/unit_inertia.h
For consistency with rotational_inertia and spatial_inertia
Follow-up to #14111
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14112)
=> unit_inertia: Change ReExpress to use frame A instead of frame F

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.h
Add some overloaded AddLorentzConeConstraint to pydrake. Also improve the documentation for AddPositiveSemidefiniteConstraint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14119)
=> add pybind for AddLorentzConeConstraint.

bindings/pydrake/multibody/jupyter_widgets.py
Before this, the planar joint sliders came out as 3 sliders with identical names
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14130)
=> jupyter: better description for joints with multiple positions (but just one joint name)

geometry/benchmarking/README.md, geometry/benchmarking/mesh_intersection_benchmark.cc, geometry/proximity/bvh.cc, geometry/proximity/bvh.h, geometry/proximity/mesh_intersection.cc, geometry/proximity/mesh_intersection.h, geometry/proximity/obb.cc, geometry/proximity/obb.h, geometry/proximity/test/bvh_test.cc, geometry/proximity/test/mesh_intersection_test.cc, geometry/proximity/test/mesh_to_vtk_test.cc
For historical reasons, computing intersection between a soft volume mesh and a rigid surface mesh had two separate APIs. One used broadphase acceleration with a bounding volume hierarchy (BVH) one did not. Both APIs were propagated as a basis for measuring improvement. The need for both APIs is long gone. So, we'll simplify the API and eliminate the slow version. Going forward, improvements should be against strictly the best possible results. This change had several implications:
- mesh_intersection_benchmark now only considers one case -- it reports the performance of queries with the *current* BVH implementation.
- Unit tests in mesh_intersection_test would exploit the BVH-free API to shorten the tests. They needed to be expanded to use the BVH API.
- One test in particular would …
=> [geometry] Remove the non-BVH interface for rigid-soft mesh intersection

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/BUILD.bazel
* Weld error support omitted for simplicity.
* Follow-up to #14038
* Completes #13282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14144)
=> Add pydrake bindings for model directives.

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/plant/test/multibody_plant_test.cc, multibody/tree/fixed_offset_frame.h
Towards [#13289](https://github.com/RobotLocomotion/drake/issues/13289).
Implements MultibodyElement Parameterization (started in [#13860](https://github.com/RobotLocomotion/drake/pull/13860)) for FixedOffsetFrame.
Introduces API for mutating FixedOffsetFrame given a context:
- `FixedOffsetFrame::SetPoseInBodyFrame`
Adds python binding for:
- `Frame::CalcPoseInBodyFrame()`
- `Frame::CalcRotationMatrixInBodyFrame()`
- `FixedOffsetFrame::SetPoseInBodyFrame()`
Relevant issues that this may partially/completely solve:
[#14084](https://github.com/RobotLocomotion/drake/issues/14084)
[#13520](https://github.com/RobotLocomotion/drake/issues/13520)
[#13517](https://github.com/RobotLocomotion/drake/issues/13517)
--- …
=> Adds parameters for FixedOffsetFrame

systems/analysis/BUILD.bazel
Removes a warning when building introduced by #14135.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14149)
=> simulator: Squelch deprecation warning when building.

examples/multibody/cassie_benchmark/test/cassie_bench.cc
Relevant to: #10991, #13902
I finally realized that LimitMalloc counting was contributing significant
overhead to autodiff benchmark timings, owing to necessary synchronization
primitives in that module. This patch separates the two measurements, to
clarify the things we want to focus on.
Notice that this change of measurement will require some revision of our
timings for older versions, to keep comparisons sensible. Reviewers should look
for updates to the tracking issue #13902.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14146)
=> cassie_bench: Separate autodiff malloc counts from benchmark timing

systems/framework/system_constraint.h
Eigen introduces [Eigen::all](http://eigen.tuxfamily.org/dox-devel/group__Core__Module.html#ga790ab6c4226ef5f678b9eb532a3eab14) and we need this patch to avoid name conflicts
with drake::all.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14159)
=> Make compatible with Eigen-3.3.8

systems/analysis/BUILD.bazel, systems/analysis/simulator.cc, systems/analysis/simulator.h, systems/analysis/simulator_config.h, systems/analysis/simulator_gflags.cc, systems/analysis/test/simulator_config_functions_test.cc
Towards #12903 
- Removed duplication of integrator defaults.
- Updated test to check if SimulatorConfig defaults are congruent with
integrator defaults.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14150)
=> simulator: resolved mismatch of simulator integrator defaults

math/roll_pitch_yaw.cc, math/roll_pitch_yaw.h, math/test/roll_pitch_yaw_test.cc, multibody/tree/linear_bushing_roll_pitch_yaw.cc, multibody/tree/linear_bushing_roll_pitch_yaw.h, multibody/tree/test/linear_bushing_roll_pitch_yaw_test.cc
Resolves #14114 which requested a better error message when users encounter gimbal lock during use of class LinearBushingRollPitchYaw.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14126)
=> Versatile error message for gimbal-lock singularity (helps debug bushings).

tools/skylark/drake_cc.bzl
Dear @dmcconachie-tri,
The on-call build cop, @BetsyMcPhail , believes that your PR #14155 may have
https://drake-jenkins.csail.mit.edu/job/mac-mojave-clang-cmake-continuous-release/1471/
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.
If you believe your original PR …
=> Revert "build: Wcpp warnings to errors"

systems/framework/context.h, systems/framework/test/diagram_context_test.cc
Resolves #14138.
Add the method Context::SetStateAndParametersFrom() to allow
copying state and parameters from another context to a non-root
context.
Change the documentation for
Context::SetTimeStateAndParametersFrom() to reflect what it does.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14156)
=> Add Context::SetStateAndParametersFrom()

common/autodiffxd.h
Relevant to: #10991, #13902
It turns out that relying on eigen's Matrix::operator*= too heavily results in
slower code. Rewrite AutoDiffXd::operator*= for autodiff inputs so that it gets
better optimization and inlining from Eigen.
Supporting benchmark measurements will be provided in #13902.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14171)
=> autodiffxd: Optimize `operator*=` a bit more

systems/framework/system.cc, systems/framework/system.h, systems/framework/test/system_test.cc
If a class exposes a `Foo& GetFoo(string)` method that throws if
there is no Foo of that name, then it must expose a corresponding
`HasFoo` method that allows a caller to know whether the getter
will throw.  Otherwise the no-catches standard makes safe use of
the getter impossible.
We've stomped most of these in the codebase but I just found these
two stragglers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14176)
=> Fix throwing-Get methods missing Has counterparts

tools/workspace/snopt/repository.bzl
The argument 'recursive_init_submodules' was added in Bazel 3.6
This fixes CI failing jobs:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-mojave-unprovisioned-clang-bazel-continuous-snopt-packaging/1589/
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-catalina-unprovisioned-clang-bazel-nightly-release/303/
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-mojave-unprovisioned-clang-bazel-nightly-release/452/
https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-mojave-unprovisioned-clang-bazel-nightly-snopt-packaging/546/
Example error:
```
[4:35:12 AM]  Repository rule _snopt_repository defined at:
[4:35:12 AM]    /Users/mojave/workspace/mac-mojave-unprovisioned-clang-bazel-nightly-release/src/tools/works …
```
=> Add (unused) attribute to snopt rule

multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc
Trying to fix #14180 
The test fails on Mac. Unfortunately I can't reproduce it on my own machine. I just change the initial guess of the optimization and see if the CI will be happy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14182)
=> Fix unit_quaternion_constraint_test failure on CI

systems/sensors/BUILD.bazel, systems/sensors/accelerometer.cc, systems/sensors/accelerometer.h, systems/sensors/accelerometer_sensor.h, systems/sensors/gyroscope.cc, systems/sensors/gyroscope.h, systems/sensors/gyroscope_sensor.h, systems/sensors/test/accelerometer_test.cc, systems/sensors/test/gyroscope_test.cc
While attic was alive, we had `attic/systems/sensors/foo.h`. To create versions that were compatible with MBP, we created `attic/systems/sensors/foo_sensor.h` to distinguish them via build systems (although they included classes of the same name).
Now that attic is gone, we can remove the `_sensor` suffix.
This has two curated commits. The first renames the header files and changes all Drake references to be consistent; this preserves the blame/history on the files. The second commit adds back the `foo_sensor.h` files. The restored files emit a deprecation warning and include the renamed header.
resolves #14123
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14185)
=> [sensors] Deprecate the old `foo_sensor.h` to become `foo.h`

doc/directory_structure.rst
This came up as a point of confusion recently.
Here are the changes:
- We now require that they must be named `dev`; a README alone will not suffice.
- This allows Reviewable to easily know the difference.
- Back away from "unit test" rules specifically; just talk about testing at all.
- Back away from 24 hours policy for build breaks; in practice, we enforce a faster turn-around time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14186)
=> doc: Clarify policy on dev directories

common/test/symbolic_chebyshev_basis_element_test.cc, common/test/symbolic_expression_test.cc, common/test/symbolic_formula_test.cc, common/test/symbolic_monomial_test.cc, common/test/symbolic_rational_function_test.cc
See https://github.com/google/googletest/blob/master/googletest/docs/faq.md#why-should-test-suite-names-and-test-names-not-contain-underscore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14191)
=> Remove underscores in Googletest test names

bindings/pydrake/multibody/math_py.cc, bindings/pydrake/multibody/test/math_test.py, bindings/pydrake/multibody/test/plant_test.py
We choose not to bind these on `SpatialVelocity` and `SpatialForce` because their performance micro-optimization makes no sense in Python.
Also remove some dead `plant_test` code while we're here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14194)
=> pydrake: Remove the recently-added ShiftInPlace bindings

tools/skylark/pybind.bzl, tools/workspace/pybind11/BUILD.bazel
The subpackages (e.g., multibody) were not being counted, because they were omitted from the coverage rule's filegroup's srcs.
Also remove a stray dependency that caused the bindings to be rebuilt unnecessarily when the coverage reporting tool changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14187)
=> Fix pydrake's bindings coverage report

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/parsing_test.py, bindings/pydrake/multibody/test/plant_test.py, multibody/parsing/package_map.cc, multibody/parsing/package_map.h
Other than `MultibodyPlant` itself, this beings everything useful in the `//multibody/plant` folder up to 100% bindings coverage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14192)
=> pydrake: Bind some missing multibody plant-related items

systems/analysis/BUILD.bazel, tools/skylark/drake_cc.bzl
Addresses #14151 and #14163, converting `#warnings` to errors and keeping both `gcc` and `clang` happy on both Mojave and Bionic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14174)
=> Convert #warnings to errors

geometry/proximity/BUILD.bazel, geometry/proximity/proximity_utilities.cc, geometry/proximity/proximity_utilities.h, geometry/proximity/test/make_cylinder_mesh_test.cc, geometry/proximity/test/proximity_utilities_test.cc, geometry/proximity/test/volume_mesh_test.cc, geometry/proximity/volume_mesh.h
Solves #14205. 
-------------------------------------------------
Moves:
- ComputeEulerCharacteristic(const VolumeMesh<>&)
- CountEdges(const VolumeMesh<>&)
- CountFaces(const VolumeMesh<>&)
from `geometry/proximity/test/make_cylinder_mesh_test.cc`  to `geometry/proximity/proximity_utilities.cc`.
Creates unit tests for the migrated function in `geometry/proximity/test/proximity_utilities_test.cc`.
-------------------------------------------------
Moves:
- CalcTetrahedronMeshVolume(const VolumeMesh<double>& mesh)
from `geometry/proximity/test/make_cylinder_mesh_test.cc` to `VolumeMesh::CalcVolume()`.
Adds unit tests for `VolumeMesh::CalcVolume()` in `geometry/proximity/test/volume_mesh_test.cc`.
--- …
=> Migrates volume mesh testing utilities

common/find_runfiles.cc, common/test/find_runfiles_test.cc
Otherwise, we can get different runfiles paths if you run a binary
via `./bazel-bin/target` vs. `bazel-bin/target`
See Anzu issue 5653 for concrete motivation.
\cc @siyuanfeng-tri 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14211)
=> model_directives: Use normalized path when comparing old vs. new paths

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/general_test.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py
I looked more closely at the code because I hit a bug where the contact force IDs were incrementing unstably even though my scene was in steady state.  It caused flickering contact forces, and ground the performance in meshcat to a halt.
I found the current implementation to be unnecessarily complex and inefficient.  This PR cleans it up.
As a bonus, I've also added arrow heads to the cylinders, and changed the colors to match the contact forces in drake visualizer.  The overall result improves the visualization quite a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14210)
=> Rewrite of MeshcatContactVisualizer

geometry/render/gl_renderer/BUILD.bazel, geometry/render/gl_renderer/gl_common.h, geometry/render/gl_renderer/opengl_context.cc, geometry/render/gl_renderer/opengl_context.h, geometry/render/gl_renderer/opengl_geometry.h, geometry/render/gl_renderer/render_engine_gl.cc, geometry/render/gl_renderer/render_engine_gl.h, geometry/render/gl_renderer/shader_program.cc, geometry/render/gl_renderer/shader_program.h, geometry/render/gl_renderer/shader_program_data.h, geometry/render/gl_renderer/test/opengl_geometry_test.cc, geometry/render/gl_renderer/test/render_engine_gl_test.cc, geometry/render/gl_renderer/test/shader_program_test.cc
This refactors how RenderEngineGl works with OpenGl Shaders and Programs. The `ShaderProgram` class is given more intelligence and takes a greater burden of the work than previously, This is in preparation for adding shaders to do color rendering (and color with textures).
- ShaderProgram is now an abstract class; it provides interfaces for shader program implementations to interact with the RenderEngine but mask many of the details.
- Geometries are grouped by the shader they use so that we can reduce changes in the OpenGl context during rendering.
- Each shader knows what properties of an instance are important and can extract them and provide them in a type-erased container to be associated with that instance.
- Change the depth and label to be derived classes of ShaderProgram
- …
=> [render] Refactor RenderEngineGl shader logic

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py
don't call set_object unless a new contact pair appears in the contact results
draw both contact forces (equal and opposite)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14218)
=> meshcat: tweak contact visualization

geometry/render/gl_renderer/shape_meshes.cc, geometry/render/gl_renderer/shape_meshes.h, geometry/render/gl_renderer/test/shape_meshes_test.cc, geometry/render/render_engine_vtk_base.cc
- Meshes: texture coordinates, like normals, are required for all objs.
- In the future, relax this requirement so that it's only an error if a texture map is applied to an obj without texture coordinates.
- Primitives
- Texture coordinates are generated for all primitives.
- MakeRevoluteShape now introduces a seam in vertex positions around the revolute axis. On each ring, the first and last vertex positions are identical. This allows for discontinuities in texture coordinates when going around that axis.
- Testing is nominal
- Almost impossible to create real tests without duplicating the code under the test. Instead, we have some token smoke tests and will rely on *obvious* visual artifacts to reveal if texture coordinates are broken.
- Special note:
- The texture coordinates on the …
=> [render] Add texture coordinates for all RenderEngineGl shapes

geometry/geometry_visualization.cc, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/geometry_visualization_test.cc, geometry/test/query_object_test.cc, geometry/test/scene_graph_test.cc, systems/sensors/test/rgbd_sensor_test.cc
While this provides the ability to choose whether the giant geometry data blob for SceneGraph is stored as Parameter or State, the default behavior remains State to maintain backwards compatibility.
In support of this endeavor, the LeafSystem interface is extended to declare an abstract Parameter by passing ownership of a pre-instantiated object. This enables SceneGraph to hang on to a pointer and mutate it post declaration.
Tests are extended accordingly.
Resolves #9501
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14189)
=> [geometry] SceneGraph can store geometry data as State or Parameter

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_values.cc, bindings/pydrake/systems/test/general_test.py, bindings/pydrake/systems/test/value_test.py, systems/framework/discrete_values.h
Addresses two check boxes for #14223
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14231)
=> pydrake systems: Add missing bindings to ContinuousState, DiscreteValues, VectorBase, and BasicVector

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py
Resolves #13834
FYI @thduynguyen and @SeanCurtis-TRI Review will be coming y'all's way once this is ready ;)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13835)
=> py geometry: Expose RenderEngine API and trampoline for inheritance

geometry/proximity/BUILD.bazel, geometry/proximity/make_box_mesh.cc, geometry/proximity/make_box_mesh.h, geometry/proximity/test/make_box_field_test.cc, geometry/proximity/test/make_box_mesh_test.cc
Solve #11906. Partially solve #12128.
The following picture shows examples of this kind of meshes. Some tetrahedra are hidden to show how the meshes look inside.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14216)
=> [geometry] New tetrahedral mesh of Box conforms to its medial axis.

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/BUILD.bazel, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/geometry_version.cc, geometry/geometry_version.h, geometry/scene_graph.h, geometry/scene_graph_inspector.h, geometry/test/geometry_state_test.cc, geometry/test/geometry_version_test.cc, geometry/test/scene_graph_inspector_test.cc
Resolves #13176. 
GeometryState owns a GeometryRevision that enables a easy query when the underlying geometries change.
Downstream systems may query the revision numbers through SceneGraphInspector.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14196)
=> Add GeometryRevision.

bindings/pydrake/test/geometry_test.py
Came across during #13835 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14233)
=> py geometry_test: Fix existing flake8 defects

manipulation/models/BUILD.bazel, manipulation/models/realsense2_description/BUILD.bazel, manipulation/models/realsense2_description/test/realsense_parse_test.cc, tools/workspace/default.bzl, tools/workspace/intel_realsense_ros/BUILD.bazel, tools/workspace/intel_realsense_ros/files.bzl, tools/workspace/intel_realsense_ros/package.BUILD.bazel, tools/workspace/intel_realsense_ros/repository.bzl
This supersedes both https://github.com/RobotLocomotion/models/pull/14 and [RobotLocomotion/drake#14080](https://github.com/RobotLocomotion/drake/pull/14080). This was done in order to take into account review recommendations to utilize the upstream source code.
This PR provides Drake the ability to fetch the `realsense-ros` upstream repository during build: [IntelRealSense/realsense-ros](https://github.com/IntelRealSense/realsense-ros)
- It gives Drake access to the realsense d415 xacro and mesh files
- After the download, xacro files are modified to cleanly stitch into a URDF in a Drake environment (rather than their native ROS environment)
- A test is provided that is closely based (copied + slightly modified) on the YCB meshes simple parsing tests
--- …
=> Adds realsense-ros dependency for URDF and meshes

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14249)
=> pydrake.multibody: add binding for CalcCenterOfMassPosition taking model instances

geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/geometry_visualization_test.cc, geometry/test/scene_graph_test.cc, systems/sensors/test/rgbd_sensor_test.cc
This changes the default behavior in SceneGraph; a default-constructed SceneGraph stores its geometry data as a Parameter (previously it was State).
This leaves a stop-gap constructor in place (marked as deprecated) to explicitly request the data to be stored as State.
Related to #9501 and #14189.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14245)
=> [geometry] Deprecate geometry data as State in SceneGraph

math/quadratic_form.h, solvers/BUILD.bazel, solvers/mosek_solver.cc, solvers/test/mosek_solver_test.cc, solvers/test/second_order_cone_program_examples.h, solvers/test/semidefinite_program_examples.cc, solvers/test/semidefinite_program_examples.h
Convert the quadratic cost to a linear cost with rotated Lorentz cone
constraint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14237)
=> MosekSolver supports quadratic cost with nonlinear conic constraints.

geometry/render/gl_renderer/BUILD.bazel, geometry/render/gl_renderer/buffer_dim.h, geometry/render/gl_renderer/gl_common.h, geometry/render/gl_renderer/no_render_engine_gl_factory.cc, geometry/render/gl_renderer/opengl_geometry.h, geometry/render/gl_renderer/render_engine_gl.cc, geometry/render/gl_renderer/render_engine_gl.h, geometry/render/gl_renderer/render_engine_gl_factory.cc, geometry/render/gl_renderer/render_engine_gl_factory.h, geometry/render/gl_renderer/render_engine_gl_params.h, geometry/render/gl_renderer/test/opengl_geometry_test.cc, geometry/render/gl_renderer/test/render_engine_gl_test.cc
This adds basic color rendering to RenderEngineGl. It provides for phong-illuminated, Rgba-colored objects. (Textured objects will follow.)
- RenderEngineGl
- Introduces the color shader program, updates the RenderColorImage to use it.
- Reformulate vertex buffer objects to account for normals.
- Tests pick up color rendering infrastructure from RenderEngineVtk tests.
- OpenGlGeometry constructor includes shader data for color shader.
- Add RenderEngineGlParameters
- contains: default label, default diffuse color, and clear color
- integrated into RenderEngineGl, RenderEngineGlFactory, and tests.
- Extend RenderType with kColor (gl_common.h)
- Clean up
- update comments in buffer_dim.h
--- …
=> [render] Add base-line color images to RenderEngineGl (no textured objects)

multibody/fem/dev/BUILD.bazel, multibody/fem/dev/constitutive_model.h, multibody/fem/dev/deformation_gradient_cache.h, multibody/fem/dev/fem_indexes.h, multibody/fem/dev/linear_elasticity_model.cc, multibody/fem/dev/linear_elasticity_model.h, multibody/fem/dev/linear_elasticity_model_cache.cc, multibody/fem/dev/linear_elasticity_model_cache.h, multibody/fem/dev/test/linear_elasticity_model_cache_test.cc, multibody/fem/dev/test/linear_elasticity_model_test.cc
The ConstitutiveModel class takes in a DeformationGradientCache and
calculates energy and stress using the material's constitutive
relationship. ConstitutiveModel is the "const method" and
DeformationGradientCache is the "data".
This concept is illustrated with the concrete instance pair
LinearElasticityModel and LinearElasticityModelCache.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14236)
=> Add ConstitutiveModel and DeformationGradientCache.

manipulation/models/allegro_hand_description/sdf/allegro_hand_description_left.sdf, manipulation/models/allegro_hand_description/sdf/allegro_hand_description_right.sdf, manipulation/models/allegro_hand_description/urdf/allegro_hand_description_left.urdf, manipulation/models/allegro_hand_description/urdf/allegro_hand_description_right.urdf, manipulation/util/show_model.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14252)
=> Use package instead of relative path for allegro model files

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, examples/scene_graph/BUILD.bazel, examples/scene_graph/bouncing_ball_run_dynamics.cc, examples/scene_graph/simple_contact_surface_vis.cc, examples/scene_graph/solar_system_run_dynamics.cc, geometry/BUILD.bazel, geometry/drake_visualizer.cc, geometry/drake_visualizer.h, geometry/geometry_roles.h, geometry/geometry_version.cc, geometry/geometry_version.h, geometry/scene_graph_inspector.h, geometry/test/drake_visualizer_test.cc, geometry/test/geometry_version_test.cc
A new leaf system that supplants the old `geometry::ConnectDrakeVisualizer` functionality. The introduction of this `System` improves Drake in several ways.
1. It provides a visualizer example that make use of the `QueryObject` and `SceneGraphInspector` public API (the old version exercised internal code).
2. It has the ability to update the visualization based on changes to the geometry.
3. It is a single system (rather than an entire diagram).
4. It frees `SceneGraph` to remove the out-dated `PoseBundle` output port that is currently used to visualize to `drake_visualizer`.
This
- Includes the C++ and python versions of the new `System`.
- Updates `examples/scene_graph` to make use `DrakeVisualizer`.
- Adds upgraded unit tests over those for the old interface.
- It also tweaks …
=> [geometry] Add new geometry::DrakeVisualizer system

bindings/pydrake/systems/test/analysis_test.py, common/test/text_logging_test.cc, common/text_logging.h, common/trajectories/test/discrete_time_trajectory_test.cc, common/yaml/yaml_write_archive.h, multibody/parsing/test/detail_scene_graph_test.cc, tools/workspace/fmt/repository.bzl
> Changed the default floating point format to not include .0 for consistency with std::format and std::to_chars. It is possible to get the decimal point and trailing zero with the # specifier.
-- https://github.com/fmtlib/fmt/releases/tag/7.1.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14272)
=> workspace: Upgrade fmt to latest release 7.1.0

doc/developers.rst, setup/ubuntu/source_distribution/install_prereqs.sh
At the moment, claiming 3.7 on macOS is a small lie but will soon become true, because we need to refresh the CI images there to fix python and director.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14246)
=> setup: Upgrade recommended Bazel version to 3.7

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/drake_visualizer.cc, geometry/geometry_state.h, geometry/query_object.cc, geometry/query_object.h, geometry/scene_graph_inspector.h, geometry/test/query_object_test.cc, geometry/test/scene_graph_inspector_test.cc, geometry/test/scene_graph_test.cc, systems/sensors/rgbd_sensor.cc
As per issue 14258, we want all public APIs that take Identifiers as parameters to have names representing their id type (source_id and not simply id). This handles what is termed "Category 3" APIs in that issue. This includes deprecations of some APIs that have been renamed and some deprecations on only the bindings.
resolves #14258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14280)
=> Clean up and deprecation of SceneGraphInspector/QueryObject bindings

geometry/render/gl_renderer/BUILD.bazel, geometry/render/gl_renderer/render_engine_gl.cc, geometry/render/gl_renderer/render_engine_gl.h, geometry/render/gl_renderer/shader_program.cc, geometry/render/gl_renderer/shader_program.h, geometry/render/gl_renderer/test/render_engine_gl_test.cc, geometry/render/gl_renderer/test/shader_program_test.cc, geometry/render/gl_renderer/texture_library.cc, geometry/render/gl_renderer/texture_library.h, multibody/multibody_doxygen.h
This introduces a shader to render textured objects (diffuse only).
- New class: TextureLibrary
- depends on the OpenGl context and owns all of the textures created in the OpenGl context.
- RenderEngineGl
- acquires an instance of TextureLibrary
- Defines a new ShaderProgram -- diffuse textured.
- Implements the VTK "default texture" logic (i.e., for an mesh.obj, look for mesh.png and apply it as texture -- unless one has already been defined.)
- Adds texture vertices to the vertex array buffer.
- Expand tests to include textures on various objects (not all, not yet). Further pushes the tests to conform to those for RenderEngineGl in anticipation of test refactoring.
Relates to #13617
--- …
=> Add color images with textured objects

perception/test/point_cloud_flags_test.cc
This avoids an obscure kcov bug when using GCC and Ubuntu 20.04.
Filed upstream as https://github.com/SimonKagstrom/kcov/issues/339.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14283)
=> perception: Split unit test cases

geometry/profiling/BUILD.bazel, geometry/profiling/README.md, geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/hydroelastic_internal.h, geometry/proximity/test/hydroelastic_internal_test.cc
Complete the solution for issue #11906 by using the new mesh from PR #14216 in the hydroelastic contact model.
The compliant box will use the new volume mesh conforming to its medial axis, and the rigid box will use the coarsest surface mesh.
I also added a rigid box and a soft box to the contact-surface profiling example to visually verify that the newer coarser meshes still give good quality pressure distribution on the contact surface.  The first picture below shows the contact surface between the coarsest rigid box's mesh (grey) against the new medial-axis mesh of a soft box (pink).  The second picture below shows the contact surface between the coarsest rigid box's mesh (grey) and a soft ball's  mesh (pink).
--- …
=> [geometry] Use the new box mesh in hydroelastic contact model.

bindings/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis.py, bindings/pydrake/manipulation/simple_ui.py, examples/manipulation_station/differential_ik.py
Command-line:
```
$ flake8 --select=F821 **/*.py \
| grep -v _extra.py | grep -v drake_visualizer | grep -v schunk_buttons.py
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14293)
=> Minor fixes for flake8's F821 (undefined name) error

geometry/drake_visualizer.cc, geometry/drake_visualizer.h, geometry/test/drake_visualizer_test.cc
This enables calls to DrakeVisualizer::Publish(context) to broadcast the draw message (with a load message as necessary). This enables the workflow where users can publish arbitrary configurations as defined in contexts (independent of the simulator).
relates to #13597, #14282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14304)
=> [visualization] Allow force publish calls on DrakeVisualizer

multibody/parsing/package_map.cc, multibody/parsing/package_map.h, multibody/parsing/test/package_map_test.cc
As discussed in the comments of https://github.com/RobotLocomotion/drake/issues/10531#issuecomment-722501505, this PR creates a `PackageMap::Remove` method for removing package keys (and paths) that have been previously added to a `PackageMap`.
In terms of testing, I extended the `TestManualPopulation` to now test both `Add` and `Remove` methods of the `PackageMap`, including the error case of requesting a package that doesn't exist.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14301)
=> Adds PackageMap Remove method

multibody/fem/dev/BUILD.bazel, multibody/fem/dev/constitutive_model.h, multibody/fem/dev/deformation_gradient_cache.h, multibody/fem/dev/elasticity_element_cache.h, multibody/fem/dev/element_cache.h, multibody/fem/dev/fem_elasticity.cc, multibody/fem/dev/fem_elasticity.h, multibody/fem/dev/fem_element.cc, multibody/fem/dev/fem_element.h, multibody/fem/dev/fem_indexes.h, multibody/fem/dev/fem_state.h, multibody/fem/dev/isoparametric_element.h, multibody/fem/dev/linear_elasticity_model.cc, multibody/fem/dev/linear_elasticity_model.h, multibody/fem/dev/linear_elasticity_model_cache.h, multibody/fem/dev/linear_simplex_element.h, multibody/fem/dev/quadrature.h, multibody/fem/dev/test/fem_elasticity_test.cc, multibody/fem/dev/test/fem_state_test.cc, multibody/fem/dev/test/linear_elasticity_model_cache_test.cc, multibody/fem/dev/test/linear_elasticity_model_test.cc
FemState stores the node-wise states in a FEM simulation as well as
ElementCache that contains state-dependent quantities that are
associated with the FEM elements. FemElement consumes FemState and
performs the element routine in a FEM solver. Currently, the only
element routine we support is calculating the residual.
Concrete instance of ElementCache (ElasticityElementCache) and concrete
instance of FemElement (FemElasticity) are added to illustrate how
these two classes work together.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14263)
=> Add FemElement and FemState.

multibody/fem/dev/BUILD.bazel, multibody/fem/dev/deformation_gradient_cache.h, multibody/fem/dev/fem_state.h, multibody/fem/dev/linear_elasticity_model_cache.h, multibody/fem/dev/test/fem_elasticity_test.cc, multibody/fem/dev/test/fem_state_test.cc, multibody/fem/dev/test/linear_elasticity_model_cache_test.cc
Remove usage of uninitialized values in FemState and
LinearElasticityModelCacheTest. Fixes issue #14312.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14313)
=> Remove usage of unintialized values.

bindings/pydrake/geometry_py.cc, geometry/render/BUILD.bazel, geometry/render/gl_renderer/render_engine_gl.cc, geometry/render/gl_renderer/render_engine_gl.h, geometry/render/gl_renderer/shader_program.h, geometry/render/gl_renderer/test/render_engine_gl_test.cc, geometry/render/gl_renderer/test/shader_program_test.cc, geometry/render/render_camera.cc, geometry/render/render_camera.h, geometry/render/render_engine_vtk.cc, geometry/render/test/render_camera_test.cc, geometry/render/test/render_engine_vtk_test.cc
- Refactor the mapping from `RenderCamera` --> OpenGl Projection matrix previously defined in `RenderEngineVtk` into `RenderCameraCore`.
- Add convenience constructors for `*RenderCamera` instances from `CameraProperties` instances.
- Add `RenderCamera`-based rendering to `RenderEngineGl`
- Implement `DoRender*Image(*RenderCamera)` API from `RenderEngine`
- Express `Render*Image(*CameraProperties)` in terms of the `DoRender*Image` API. This is about 95% cut-and-paste and 5% changing `CameraProperties` declarations to `RenderCamera` declarations.
- tweak `ShaderProgram` to consume new camera type.
- Copy-and-paste `render_engine_vtk_test.cc` code for testing intrinsics into `render_engine_gl_test.cc`.
resolves #13617
--- …
=> [rendering] Give RenderEngineGl access to full camera intrinsics

lcmtypes/BUILD.bazel, lcmtypes/lcmt_scope.lcm, systems/lcm/BUILD.bazel, systems/lcm/connect_lcm_scope.h, systems/lcm/lcm_scope_system.cc, systems/lcm/lcm_scope_system.h, systems/lcm/test/lcm_scope_system_test.cc
This provides a rewrite of LCM scoping using a new message type, so that we can get microsecond timestamps instead of milliseconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14308)
=> systems/lcm: Add LcmScopeSystem

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/render/render_engine.h
The `RenderEngine` API has a `Render*Image(CameraProperties)` API. The `CameraProperties` classes are being supplanted by the `RenderCamera` API (which gives support for a fully specified pinhole camera intrinsic model). Rather than bind these soon-to-be-deprecated methods, we'll omit them to ease the pain of deprecation.
We're assuming that since these binding have only existed for about two weeks (as of the submission of this PR -- see #13835), a hard removal is acceptable. 
See [this conversation](https://github.com/RobotLocomotion/drake/pull/13835#issuecomment-723314350) from #13835.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14300)
=> [pydrake] Update RenderEngine python trampoline - omit soon-to-be-removed API

bindings/pydrake/geometry_py.cc
Previously, we had the return value keeping the provided lcm alive. If the return value isn't *captured* (e.g. vis = DrakeVis.AddToBuilder(....)) then that keep alive won't work and the lcm can be subsequently destroyed. This has been observed in the wild.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14314)
=> [pybind] Correct bindings for DrakeVisualizer.AddToBuilder

bindings/pydrake/systems/meshcat_visualizer.py
```
File "/github/home/.cache/bazel/_bazel_root/2c6ecbd5334a25ecb6695496eb26484b/execroot/manipulation/bazel-out/k8-fastbuild/bin/clutter.runfiles/drake/.lib/python3.6/site-packages/pydrake/systems/meshcat_visualizer.py", line 562, in DoPublish
date="2021-03-01.")
File "/github/home/.cache/bazel/_bazel_root/2c6ecbd5334a25ecb6695496eb26484b/execroot/manipulation/bazel-out/k8-fastbuild/bin/clutter.runfiles/drake/.lib/python3.6/site-packages/pydrake/common/deprecation.py", line 142, in _warn_deprecated
_format_deprecation_message(message, date=date),
File "/github/home/.cache/bazel/_bazel_root/2c6ecbd5334a25ecb6695496eb26484b/execroot/manipulation/bazel-out/k8-fastbuild/bin/clutter.runfiles/drake/.lib/python3.6/site-packages/pydrake/common/deprecation.py", line 121, in …
```
=> hotfix: typo in _warn_deprecated caused error outside of drake that was masked inside of drake

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc
Modifies the SDF and URDF parser to take two custom tags:
- `drake:rotor_inertia`
- `drake:gear_ratio`
Used to set `JointActuator::default_rotor_inertia_` and `JointActuator::default_gear_ratio_`.
In SDF, these custom tags are expected to appear within the `<joint>` tag, e.g.:
```
<model>
...
<joint name="joint" type="revolute">
...
<drake:rotor_inertia>1.5</drake:rotor_inertia>
<drake:gear_ratio>300</drake:gear_ratio>
...
```
In URDF, these custom tags are expected to appear within the `<actuator>` tag within a `<transmission>` tag, e.g.:
```
<robot>
...
<transmission>
...
<actuator>
...
<drake:rotor_inertia value="1.5" />
<drake:gear_ratio value="300" />
...
```
Related to #12335
--- …
=> Add parsing for reflected inertia parameters

bindings/pydrake/systems/framework_py_values.cc, bindings/pydrake/systems/test/general_test.py
Resolves #14341
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14343)
=> pydrake: Fix type bug in BasicVector::set_value for non-float types

common/schema/BUILD.bazel, common/schema/test/stochastic_test.cc, common/yaml/test/example_structs.h, common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_defaults_test.cc, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_write_archive.h
We need to discard the template arguments; they are not valid tag syntax.
Also add a stochastic acceptance test that would have caught this issue.
Closes #14322.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14327)
=> yaml: Correctly emit variants with templated inner types

multibody/tree/ball_rpy_joint.cc, multibody/tree/planar_joint.cc, multibody/tree/prismatic_joint.cc, multibody/tree/revolute_joint.cc, multibody/tree/test/ball_rpy_joint_test.cc, multibody/tree/test/planar_joint_test.cc, multibody/tree/test/prismatic_joint_test.cc, multibody/tree/test/revolute_joint_test.cc, multibody/tree/test/universal_joint_test.cc, multibody/tree/universal_joint.cc
Addresses #14344. This PR fixes a bug where joints' default positions were not being preserved upon scalar conversion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14347)
=> Propagate joint default positions through scalar conversion

examples/allegro_hand/allegro_common.cc, examples/allegro_hand/allegro_common.h, examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
Modeling reflected inertia for a real robotic system.
In this case, modeling reflected inertia allow us to use a time step 67 times larger, which leads to a sim running at about 20X.
~~Now dependent on #14167. Thus, right now pushed for discussion with a concrete use case.~~
cc'ing @joemasterjohn, @mitiguy, @sherm1, @alexalspach
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14204)
=> Allegro with reflected inertia

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/render/gl_renderer/render_engine_gl.cc, geometry/render/gl_renderer/render_engine_gl.h, geometry/render/gl_renderer/test/render_engine_gl_test.cc, geometry/render/render_engine.cc, geometry/render/render_engine.h, geometry/render/render_engine_vtk.cc, geometry/render/render_engine_vtk.h, geometry/render/test/render_engine_test.cc, geometry/render/test/render_engine_vtk_test.cc, geometry/test_utilities/dummy_render_engine.h
This revisits the implementation of `RenderEngine` in preparation for deprecating the old `CameraProperties` and `DepthCameraProperties` in favor of the new `ColorRenderCamera` and `DepthRenderCamera`.
- We implement the `CameraProperties` `RenderEngine` API by delegating to the `RenderCamera` API (it was previously purely abstract).
- This introduces circular delegation in the default behavior and we add a *temporary* mechanism for catching the defective case where the circle gets entered.
- A collection of tests have been added to validate all transitional delegation logic.
- `RenderEngineGl`, `RenderEngineVtk`, `DummyRenderEngine` remove their `CameraProperties`-related APIs in favor of inheriting `RenderEngine`'s.
- Tests that compare equivalency between images created by the two APIs …
=> [render] Fully account for full camera intrinsics in RenderEngine ecosystem

multibody/fem/dev/BUILD.bazel, multibody/fem/dev/constitutive_model.h, multibody/fem/dev/deformation_gradient_cache.h, multibody/fem/dev/elasticity_element.cc, multibody/fem/dev/elasticity_element.h, multibody/fem/dev/elasticity_element_base.h, multibody/fem/dev/elasticity_element_cache.h, multibody/fem/dev/elasticity_model.cc, multibody/fem/dev/elasticity_model.h, multibody/fem/dev/element_cache.h, multibody/fem/dev/fem_element.h, multibody/fem/dev/fem_model.cc, multibody/fem/dev/fem_model.h, multibody/fem/dev/fem_state.h, multibody/fem/dev/isoparametric_element.h, multibody/fem/dev/linear_elasticity_model.cc, multibody/fem/dev/linear_elasticity_model.h, multibody/fem/dev/linear_elasticity_model_cache.cc, multibody/fem/dev/linear_elasticity_model_cache.h, multibody/fem/dev/linear_simplex_element.h, multibody/fem/dev/quadrature.h, multibody/fem/dev/test/elasticity_element_test.cc, multibody/fem/dev/test/elasticity_model_test.cc, multibody/fem/dev/test/fem_state_test.cc, multibody/fem/dev/test/linear_elasticity_model_cache_test.cc
FemModel helps calculate quantities used in solving the FEM discretized system of equations. It
1. owns FemElements and assembles residual and tangent matrix using their element counterparts, and 
2. builds FemState.
See [this google doc](https://docs.google.com/document/d/1RqeR-K2_TKaxEp9e7_qSykL6QWN6bI2tHxZ1BL7v5ao/) for the design for FemModel and its dependent classes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14317)
=> Add FemModel and the concrete ElasticityModel.

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, examples/scene_graph/bouncing_ball_run_dynamics.cc, geometry/benchmarking/render_benchmark.cc, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/query_object.cc, geometry/query_object.h, geometry/render/gl_renderer/test/render_engine_gl_test.cc, geometry/render/render_engine.cc, geometry/render/render_engine.h, geometry/render/render_engine_vtk.cc, geometry/render/test/render_engine_test.cc, geometry/render/test/render_engine_vtk_test.cc, geometry/scene_graph.h, geometry/test/query_object_test.cc
- RenderEngine
- Deprecate the api.
- Modify documentation on DoRender*Image API to reflect deprecation implications.
- Guard tests from deprecation warnings.
- QueryObject
- Deprecate corresponding API
- Add documentation for the new API.
- deprecate bindings
- GeometryState
- Deprecate corresponding API (functionally internal, but not technically internal, so I'm simply deprecating it and allowing it to evaporate with all the rest of in the spring).
- Clean up numerous call sites to upgrade from CameraProperties to RenderCamera
- benchmarks, examples, documentation, and tests.
Towards resolving checklist in #11880.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14 …
=> [render] Deprecate RenderEngine::Render*Image(CameraProperties) API

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/controllers_test.py, bindings/pydrake/systems/test/lifetime_test.py
This is a workaround to ensure we propagate keep_alive relationships
Resolves #14355
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14356)
=> py systems: Add keep_alive cycle to DiagramBuilder.AddSystem

examples/kinova_jaco_arm/BUILD.bazel, examples/kinova_jaco_arm/jaco_controller.cc, examples/kinova_jaco_arm/move_jaco_ee.cc, examples/kuka_iiwa_arm/BUILD.bazel, examples/kuka_iiwa_arm/iiwa_controller.cc, examples/kuka_iiwa_arm/kuka_plan_runner.cc, examples/kuka_iiwa_arm/move_iiwa_ee.cc, lcmtypes/BUILD.bazel, lcmtypes/lcmt_robot_plan.lcm, lcmtypes/lcmt_robot_state.lcm, manipulation/planner/BUILD.bazel, manipulation/planner/robot_plan_interpolator.cc, manipulation/planner/robot_plan_interpolator.h, manipulation/planner/test/robot_plan_interpolator_test.cc, manipulation/util/BUILD.bazel, manipulation/util/move_ik_demo_base.cc, manipulation/util/move_ik_demo_base.h, manipulation/util/robot_plan_utils.cc, manipulation/util/robot_plan_utils.h, manipulation/util/test/robot_plan_utils_test.cc
This is a breaking change.
EncodeKeyFrames, MoveIkDemoBase, and RobotPlanInterpolator and their associated demos (move_iiwa_ee, move_jaco_rr, kuka_plan_runner, etc.), now operate on lcmt_robot_plan messages, not robot_plan_t messages.
EncodeKeyFrames no longer takes an "info" argument -- the message no longer contains the unused snopt integer.
This begins to remove Drake's dependency on bot_core.
We do not have a license to use the openhumanids code, so we must stop doing so (https://github.com/openhumanoids/bot_core_lcmtypes/issues/33).  Furthermore, there is no longer any real inter-operability reason to try to share these message structures across collaborating projects, so the dependency is adding no value for the cost of maintaining and redistributing it.
Towards #14362.  Carved out …
=> Replace robotlocomotion.robot_plan_t with drake.lcmt_robot_plan

bindings/pydrake/systems/test/analysis_test.py, common/trajectories/test/discrete_time_trajectory_test.cc, common/yaml/yaml_write_archive.h, multibody/parsing/test/detail_scene_graph_test.cc
The default string formatting of integer-valued floating-point values changed as of fmt 7.1.0.  In anticipation of Drake releases (or at least some Drake users) building against older revisions of fmt, we adjust magic string literals in tests to allow for either spelling.
Relates #14220.  Amends #14272.
\CC @hidmic FYI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14379)
=> Allow tests to pass with both fmt < 7.1 and fmt >= 7.1

bindings/pydrake/examples/BUILD.bazel, bindings/pydrake/examples/manipulation_station_py.cc, bindings/pydrake/examples/test/manipulation_station_test.py, examples/manipulation_station/manipulation_station.cc, examples/manipulation_station/manipulation_station.h, examples/manipulation_station/test/manipulation_station_test.cc
- Deprecate the old RegisterRgbdSensor (update tests)
- Add RegisterRgbdSensor that is compatible with RenderCamera.
- add tests.
- Refactor the default D415 camera (and actually *include* the full, documented intrinsics, differentiating between color and depth).
- Update bindings
- use the Class, cls_doc style to make it more compact
- bind new methods, deprecate old.
- update tests
Towards resolving checklist in #11880.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14375)
=> [render] Deprecate ManipulationStation CameraProperties API

bindings/pydrake/examples/test/manipulation_station_test.py, bindings/pydrake/geometry_py.cc, bindings/pydrake/systems/test/sensors_test.py, bindings/pydrake/test/geometry_test.py, examples/manipulation_station/test/manipulation_station_test.cc, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/query_object.cc, geometry/query_object.h, geometry/render/camera_properties.h, geometry/render/render_camera.cc, geometry/render/render_camera.h, geometry/render/render_engine.cc, geometry/render/render_engine.h, geometry/render/test/render_camera_test.cc, geometry/render/test/render_engine_test.cc, geometry/test/query_object_test.cc, systems/sensors/rgbd_sensor.h, systems/sensors/test/rgbd_sensor_test.cc
This deprecates the old camera properties classes themselves. As part of that endeavor:
- bindings deprecate the constructors.
- A slew of deprecation warning suppressions everywhere.
- In some cases, test cases were moved around to facilitate deprecation
suppression en masse (see render_camera_test.cc)
- Updated python tests to expect deprecation warnings.
Towards resolving checklist in #11880.
Closes #11880
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14376)
=> [render] Deprecate CameraProperties and DepthCameraProperties

bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_reflected_inertia_test.cc
We have a very common recurring hazard in student workflows -- they pass a diagram context into a multibodyplant method (via pydrake) and the python kernel crashes.  This PR aims to address it.
(I caught one recent failure in a test on master, too).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14389)
=> multibody: add ValidateContext() to methods that take a context

tools/workspace/os.bzl
Relates #13648. I am not doing anything to fix the several errors anytime soon, unfortunately, but this at least does not put up an artificial block if someone wants to help me out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14391)
=> workspace: warn instead of error for macOS Big Sur

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py
Add arguments and docs
In #13835, I had tried out using the `autopybind11` tool (#7889), but it didn't have all the bells and whistles, and I was too lazy to reformat. This goes back and applies minimal changes to bring the bound `RenderCamera` properties.
Came across this while helping to upgrade Anzu usages (Anzu PR 6027)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14394)
=> py geometry: Fix bindings for RenderCamera classes

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py, examples/kuka_iiwa_arm/kuka_torque_controller.cc, examples/kuka_iiwa_arm/kuka_torque_controller.h, manipulation/schunk_wsg/schunk_wsg_controller.cc, manipulation/schunk_wsg/schunk_wsg_plain_controller.cc, manipulation/schunk_wsg/schunk_wsg_plain_controller.h, systems/controllers/inverse_dynamics_controller.cc, systems/controllers/inverse_dynamics_controller.h, systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/diagram_builder.cc, systems/framework/diagram_builder.h, systems/framework/system_html.cc, systems/framework/test/diagram_builder_test.cc, systems/framework/test/diagram_test.cc, systems/framework/test/system_html_test.cc, systems/primitives/discrete_derivative.cc
Closes #3555.
Expands diagram and builder to support implicit fan-out of diagram input ports,
replacing the old work-around of using a pass-through system.
Summary of changes:
* Allow repeated ExportInput calls to implement implicit fan-out
* requires more bookkeeping in diagram and builder
* Deprecate diagram.get_input_port_locator() API
* replaced with fan-out-aware GetInputPortLocators()
* port clients of deprecated API; all within systems/framework
* Add necessary test coverage
* Port various diagrams to use fan-out instead of pass-throughs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14361)
=> diagram/builder: Implement fan-out of diagram inputs

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py, systems/framework/diagram_builder.h, systems/framework/test/diagram_builder_test.cc
Closes #5895.
This patch provides an potentially more fluent alternative to the common
AddSystem/set_name idiom.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14404)
=> diagram builder: introduce AddNamedSystem sugar

setup/mac/source_distribution/requirements-test-only.txt, setup/ubuntu/source_distribution/packages-bionic-test-only.txt, setup/ubuntu/source_distribution/packages-focal-test-only.txt
At least on Mac we are no longer getting `six` transitively. We may still be fine on Linux, but does not hurt to be explicit. Looks like it would be easy to exorcise `six` from the tool without causing additional conflicts of any substance., but I don't have time for that at present.
(see https://github.com/RobotLocomotion/styleguide/blob/4b76baf0fdf78154c3b72cdd713c2247d2a43e3a/cpplint/cpplint.py#L56-L58)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14390)
=> setup: explicitly add six for cpplint

setup/mac/binary_distribution/Brewfile, setup/ubuntu/binary_distribution/packages-bionic.txt, setup/ubuntu/binary_distribution/packages-focal.txt, setup/ubuntu/source_distribution/packages-bionic.txt, setup/ubuntu/source_distribution/packages-focal.txt
Relates in part #14339 and in part continued Mac Python 3.8 support. Ultimately will resolve a few TODOs in the `vtk` `repository.bzl` and shift some of the compilation time onto Homebrew and Ubuntu. Note that `libtbb2` needs to be removed, but that would require the rebuild of `vtk` to be in this commit. Part 1 of either 2 or 3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14392)
=> setup: add double-conversion, sqlite3, and lzma for vtk

math/test/gray_code_test.cc
* This is a trivial disturbance to the test to correct
a spurious kcov error; see
https://github.com/SimonKagstrom/kcov/issues/339
* Closes #14424
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14425)
=> Separate out the unit test for the degenerate case

bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Fixes #14346. Adds `MultibodyGraph` accounting for bodies and joints that is missed during plant scalar conversion. This accounting is usually done in `MultibodyPlant::AddRigidBody` and `MultibodyPlant::AddJoint`, but those are not called during scalar conversion, they are cloned from the underlying `MultibodyTree`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14411)
=> fixes missing multibody graph accounting

geometry/proximity/bvh.h, geometry/proximity/mesh_field_linear.h, geometry/proximity/mesh_to_vtk.cc, geometry/proximity/surface_mesh.h, geometry/proximity/volume_mesh.h
Deprecate kDim in SurfaceMesh and VolumeMesh.
Use kVertexPerElement for kDim+1 instead. Fixes #12756.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14420)
=> [geometry] Deprecate kDim in SurfaceMesh and VolumeMesh.

setup/mac/binary_distribution/install_prereqs.sh
Fixes an issue seen in https://github.com/RobotLocomotion/drake-external-examples/runs/1519981618?check_suite_focus=true:
```
+ /usr/local/bin/brew uninstall --force robotlocomotion/director/vtk@8.2 robotlocomotion/director/ospray@1.8 robotlocomotion/director/embree@3.5
Error: No available formula with the name "robotlocomotion/director/vtk@8.2".
Please tap it and then try again: brew tap robotlocomotion/director
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14428)
=> setup: do not error when robotlocomotion/director is not tapped

multibody/plant/test/multibody_plant_test.cc
Closes #9118.
Prior to #10581, MbP used a custom context subclass.  I suspect that was a necessary condition for the segfault, but in any case I've now added a regression test that MbP context cloning works as expected.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14433)
=> plant: Add unit test for context cloning

setup/ubuntu/binary_distribution/packages-focal.txt
Adding in anticipation of compiling against the host library, instead of our own separate copy, in #14427.
Towards #14220.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14429)
=> setup: Add libspdlog-dev on Ubuntu 20.04 Focal

bindings/pydrake/geometry_py.cc, bindings/pydrake/systems/meshcat_visualizer.py, examples/manipulation_station/manipulation_station.h, geometry/geometry_state.h, geometry/geometry_visualization.h, geometry/query_object.h, geometry/render/camera_properties.h, geometry/render/render_engine.h, geometry/render/test/render_engine_test.cc, geometry/scene_graph.h, geometry/scene_graph_inspector.h, solvers/symbolic_extraction.h, systems/framework/diagram.h, systems/sensors/rgbd_sensor.h
Because we did not tag a release during November, we should not count that month toward the deprecation sunset.  Deprecations that we added subsequent to v0.24.0 should expire no earlier than 2021-04-01.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14430)
=> Push unreleased deprecations back to 2021-04-01

tools/bazel.rc
As of bazel 4.0, we get a hard error without this nerf.
Once we've fixed our code to comply, we should remove the nerf.
Relates #14440.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14441)
=> tools: Use incompatible_restrict_string_escapes for now

tools/workspace/pkg_config.bzl
As of bazel 4.0, the user_link_flags changes from a list to a depset.
Therefore, when we used -Wl,-rpath /foo/bar as our spelling, the first instance survived but a second instance would skips the -Wl,-rpath part but keep the /quux/bar part, leaving a stray directory on the link line
By consolidating each rpath addition as a single list element even after whitespace tokenization, it will remain intact.
This was biting us when fetching ipopt.pc, which has several junk compiler paths thrown into it on Ubuntu 18.04.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14439)
=> workspace: Avoid using whitespace in pkg-config rpaths

CMakeLists.txt, WORKSPACE, third_party/com_github_bazelbuild_rules_cc/whole_archive.bzl
Several cc_info data structures got reorganized.  This function supports bazel 3.x and 4.0 now, but no longer support 2.x.
Drake's new minimum bazel version is 3.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14442)
=> rules_cc: Adapt whole_archive for bazel 4.0

examples/acrobot/BUILD.bazel, examples/acrobot/benchmark_autodiff.cc, examples/acrobot/test/benchmark_autodiff_test.sh
Relevant to: #8482
This patch rewrites Hongkai's original program (from an old branch) to use
google benchmark, removes some obsolete measurements (RigidBodyTree,
AutoDiffUpTo73d), and adds some new ones (MBP vanilla CalcMassMatrix()).
This benchmark set is nice because is captures the small-problem (only four
derivatives!) end of the autodiff problem space.
A possible plan would be to wrap this program with controlled-experiment
scripts, similar to those in examples/multibody/cassie_benchmark, and use it to
help drive further autodiff optimization work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14432)
=> examples/acrobot: Add an autodiff benchmark

multibody/fem/dev/README.md, multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/README.md, multibody/fixed_fem/dev/quadrature.h, multibody/fixed_fem/dev/simplex_gaussian_quadrature.h, multibody/fixed_fem/dev/test/simplex_gaussian_quadrature_test.cc
Refactor the FEM quadrature implementation in Drake. Add additional
template parameter so that the size of the quadrature points and the
weights are available at compile time. The unit tests are the same as
in the previous implementation except for syntactic changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14448)
=> Refactor quadrature to remove heap allocations

systems/framework/context_base.h
User-facing APIs should prefer const-ref (not unique_ptr) when the user provides new values for the framework to use (per #8904).  We will adjust the advice in the class further in the future (#14453), but for now with a release in flight, this is the minimal change to allow users to keep using the forward-looking API.
This reverts one of the deprecations from #14093.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14454)
=> framework: Un-deprecate FixInputPort taking an const ref

setup/ubuntu/source_distribution/packages-bionic-doc-only.txt, setup/ubuntu/source_distribution/packages-focal-doc-only.txt
Working towards #13832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14349)
=> Add jekyll and ruby as docs-only dependency

bindings/pydrake/systems/framework_py_systems.cc, examples/compass_gait/compass_gait.cc, examples/rimless_wheel/rimless_wheel.cc, geometry/scene_graph.cc, manipulation/perception/optitrack_pose_extractor.cc, manipulation/perception/pose_smoother.cc, manipulation/planner/robot_plan_interpolator.cc, systems/framework/context.cc, systems/framework/context_base.cc, systems/framework/context_base.h, systems/framework/input_port.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/test/diagram_context_test.cc, systems/framework/test/diagram_test.cc, systems/framework/test/fixed_input_port_value_test.cc, systems/framework/test/leaf_context_test.cc, systems/framework/test/leaf_system_test.cc, systems/framework/test/vector_system_test.cc, systems/lcm/lcm_subscriber_system.cc, systems/optimization/test/system_optimization_test_util.h, systems/primitives/discrete_time_delay.cc, systems/primitives/random_source.cc, systems/primitives/zero_order_hold.cc
This commit adjusts FixInputPort and DeclareAbstractState to use pass-by-const-ref.
Part of #8904.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14453)
=> systems: Use const-ref arguments, not unique_ptr

tools/bazel.rc
This reverts commit fce3bdb591a6deb97e6414dcd82aa0eb4b67c7bb (#14441).
Closes  #14440.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14458)
=> tools: No need for incompatible_restrict_string_escapes anymore

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/isoparametric_element.h, multibody/fixed_fem/dev/linear_simplex_element.h, multibody/fixed_fem/dev/quadrature.h, multibody/fixed_fem/dev/simplex_gaussian_quadrature.h, multibody/fixed_fem/dev/test/isoparametric_element_test.cc, multibody/fixed_fem/dev/test/linear_simplex_element_test.cc, multibody/fixed_fem/dev/test/simplex_gaussian_quadrature_test.cc
Refactor the FEM isoparametric element implementation to eliminate heap
allocation and virtual methods. Change to a CRTP pattern for
compile-time polymorphism. The unit tests are the same as in the
previous implementation except for syntactic changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14452)
=> Refactor IsoparametricElement to remove heap allocation

geometry/proximity/mesh_field_linear.h
Fix #13257 "Improve documentation of MeshFieldLinear about the choice of calculating gradient."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14460)
=> [geometry] Documentation of MeshFieldLinear() about calculate_gradient parameter.

geometry/render/gl_renderer/BUILD.bazel, tools/skylark/drake_cc_per_os.bzl
This keeps us aligned the the pattern in #14470.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14471)
=> tools: Move cc macros for per_os support to common skylark

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py
Adds a flag to MeshcatVisualizer to toggle between the geometry role type that is illustrated. (Hope I didn't miss some obvious existing way to do this!)
Setting it to "illustration" draws the usual visual geometry, and shouldn't change functionality at all. This is the default arg.
Setting it to "proximity" instead draws the collision geometry (i.e. proximity-role geometry), with random colors to make them easier to distinguish:
(Since a fair amount of my collision geometry is `Convex`-type, I also enabled drawing of that type using the `Mesh` codepath.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14467)
=> Add MeshcatVisualizer option to draw collision geometry

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/constitutive_model.h, multibody/fixed_fem/dev/deformation_gradient_cache_entry.h, multibody/fixed_fem/dev/fem_indexes.h, multibody/fixed_fem/dev/linear_constitutive_model.h, multibody/fixed_fem/dev/linear_constitutive_model_cache_entry.h, multibody/fixed_fem/dev/test/linear_constitutive_model_cache_entry_test.cc, multibody/fixed_fem/dev/test/linear_constitutive_model_test.cc
Refactor the FEM constitutive model implementation to eliminate heap
allocation and virtual methods. Change to a CRTP pattern for
compile-time polymorphism. The unit tests are the same as in the
previous implementation except for syntactic changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14473)
=> Refactor the FEM constitutive model

manipulation/schunk_wsg/schunk_wsg_constants.h, manipulation/schunk_wsg/schunk_wsg_lcm.h, manipulation/schunk_wsg/schunk_wsg_position_controller.h, systems/systems.h
This at least makes sure that all of our schunk wsg variants appear in the same places in doxygen.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14412)
=> doxygen: add @ingroup tags to schunk wsg systems

doc/bazel.rst, solvers/mosek_solver.cc, solvers/mosek_solver.h, solvers/solver_options.h, solvers/test/linear_program_examples.h, solvers/test/mosek_solver_test.cc, solvers/test/quadratic_program_examples.cc, solvers/test/semidefinite_program_examples.h, tools/dynamic_analysis/tsan.supp, tools/workspace/mosek/repository.bzl
Drake currently supports mosek 9.0, which has a bug in pre-solve the problem to get the dual variable solutions (as shown in our PR #14383. I contacted with Mosek developer and confirmed that Mosek 9.2 resolves this bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14484)
=> upgrade mosek to mosek 9.2

common/schema/stochastic.h
While using the stochastic schema, found three places in the examples that `std` is still used instead of `stddev`. This PR attempts to clear the confusion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14494)
=> Correct stochastic schema comments

doc/developers.rst
Per @zachfang's DM question regarding review for #14494
In the case that the author does not know who the most appropriate
feature reviewer may be.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14495)
=> doc/developers: Mention leaving review unassigned for feature review

solvers/mathematical_program_result.h, solvers/mosek_solver.cc, solvers/test/exponential_cone_program_examples.cc, solvers/test/exponential_cone_program_examples.h, solvers/test/mosek_solver_test.cc, solvers/test/scs_solver_test.cc, solvers/test/second_order_cone_program_examples.cc, solvers/test/second_order_cone_program_examples.h
As a step towards #13285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14383)
=> Retrieve dual solution for conic constraint in Mosek.

common/trajectories/BUILD.bazel, common/trajectories/piecewise_pose.cc, common/trajectories/piecewise_pose.h, common/trajectories/piecewise_quaternion.cc, common/trajectories/piecewise_quaternion.h, common/trajectories/test/piecewise_pose_test.cc, common/trajectories/test/piecewise_quaternion_test.cc, manipulation/util/BUILD.bazel, manipulation/util/trajectory_utils.h
Also deprecates `PiecewiseCartesianTrajectory` and `PiecewiseCubicTrajectory`
Closes #13973
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14337)
=> trajectories: Refactor PiecewiseCartesianTrajectory to PiecewisePoseTrajectory

multibody/plant/multibody_plant.h
Resolves #14498
Using latest commit (033687858b) from https://github.com/RobotLocomotion/drake/pull/13461#pullrequestreview-423280837, using this command:
```
bazel-bin/tools/lint/cpp_docstring_lint multibody/plant/multibody_plant.h
```
I cherry-picked the diff for class overview, then left everything else the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14499)
=> mutlibody_plant: Convert class overview to javadoc

bindings/pydrake/multibody/plant_py.cc, examples/allegro_hand/joint_control/allegro_single_object_simulation.cc, examples/simple_gripper/simple_gripper.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_introspection_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h
In addition, implement MBP::SetFreeBodyPose(Context*,
ModelInstanceIndex, const RigidTransform&).
Fix #9747. Resolve the third item in #10736.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14450)
=> Implement MBP::GetUniqueBaseBody()

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/element_cache_entry.h, multibody/fixed_fem/dev/fem_element.h, multibody/fixed_fem/dev/fem_state.h, multibody/fixed_fem/dev/test/dummy_element.h, multibody/fixed_fem/dev/test/fem_element_test.cc, multibody/fixed_fem/dev/test/fem_state_test.cc
Refactor FemState and FemElement to eliminate heap allocation and
virtual methods. Change to a CRTP implemention for compile-time
polymorphism.
Change ElementCacheEntry class to fit it into the new design.
Add an additional attribute, ODE order, to FemElement so that PDEs that
are spatially discretized into ODEs of different orders get a unified
treatment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14491)
=> Refactor FemState and FemElement

setup/ubuntu/source_distribution/packages-bionic-doc-only.txt, setup/ubuntu/source_distribution/packages-focal-doc-only.txt
'libjs-imagesloaded' is not available on Focal.
Remove both javascript packages from setup script.  The Jekyll website source is still under construction and can be modified to work around or use different packages.
Fixes  PR #14507, in place of revert PR #14510.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14512)
=> Doc Setup: Remove js packages

examples/acrobot/dev/BUILD.bazel, examples/acrobot/dev/acrobot_io.py, examples/acrobot/dev/metrics.py, examples/acrobot/dev/spong_sim.py, examples/acrobot/dev/test/metrics_test.py, examples/acrobot/dev/test/spong_sim_lib_py_test.py, examples/acrobot/dev/test/spong_sim_main_test.py
This PR brings the full acrobot monte carlo example from downstream into Drake.
In addition it adds a simple demonstration program, since the downstream code that uses this example is not ported.
Co-authored-by: Jeremy Nimmer <jeremy.nimmer@tri.global>
Co-authored-by: Andrés K. Valenzuela <andres.valenzuela@tri.global>
Co-authored-by: Eric Cousineau <eric.cousineau@tri.global>
Co-authored-by: Sam Creasey <sam.creasey@tri.global>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14478)
=> examples: Fully port monte carlo acrobot and add a demo program

common/text_logging.h, tools/install/libdrake/drake.cps, tools/workspace/fmt/package-create-cps.py, tools/workspace/fmt/package.BUILD.bazel, tools/workspace/fmt/repository.bzl, tools/workspace/new_release.py, tools/workspace/spdlog/package-create-cps.py, tools/workspace/spdlog/package.BUILD.bazel, tools/workspace/spdlog/repository.bzl
On Ubuntu 18.04, we downgrade to spdlog 5.1.0 and fmt 6.1.2, but we still compile them from github source releases.
On Ubuntu 20.04, fmt and spdlog are obtained from the host now.  (The host copy of fmt is also installed by Drake, because Ubuntu's packaging is deficient.) The versions are spdlog 5.1.0 with bundled fmt 6.1.2.
On macOS, fmt and spdlog are obtained from homebrew now.  The versions are the latest available, per the usual homebrew policy.
Closes #14220.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14427)
=> workspace: Change how fmt and spdlog dependencies are obtained

bindings/pydrake/doc/BUILD.bazel
Hotfix for #14500
As found by @jamiesnape  on Slack: https://drakedevelopers.slack.com/archives/C270MN28G/p1610478253294000
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14520)
=> pydrake/doc: Ensure any deps on sphinx have `tags = ["manual"]`

examples/acrobot/dev/BUILD.bazel
* This is an sh_test that invokes python.
* Python is supposed to be memcheck-exempt for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14526)
=> Don't run memcheck builds on optimizer_demo_smoke_test

multibody/parsing/model_directives.h, multibody/parsing/process_model_directives.cc
Package URIs are controlled by PackageMap, not in-band directives.
This is a breaking change.
Closes Anzu 4989.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14529)
=> multibody: Remove add_package_path from model directives

tools/workspace/common_robotics_utilities/repository.bzl, tools/workspace/voxelized_geometry_tools/repository.bzl
Updates versions of externals `common_robotics_utilities` and `voxelized_geometry_tools` with fixes in voxel grid lookups. Changes are purely bugfixes and do not change API.
Changes in externals:
- `common_robotics_utilities` - fixes in dense voxel grid and spatial hashed voxel grid lookups
- `voxelized_geometry_tools` fixes in OpenCL and CUDA implementations of dense voxel grid lookups
+@ggould-tri for feature review, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14530)
=> Update externals CRU and VGT for bugfix to voxel grid lookup functions

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/constitutive_model.h, multibody/fixed_fem/dev/deformation_gradient_cache_entry.h, multibody/fixed_fem/dev/elasticity_element.h, multibody/fixed_fem/dev/fem_state.h, multibody/fixed_fem/dev/isoparametric_element.h, multibody/fixed_fem/dev/linear_constitutive_model_cache_entry.h, multibody/fixed_fem/dev/quadrature.h, multibody/fixed_fem/dev/simplex_gaussian_quadrature.h, multibody/fixed_fem/dev/static_elasticity_element.h, multibody/fixed_fem/dev/test/elasticity_element_test.cc, multibody/fixed_fem/dev/test/linear_constitutive_model_cache_entry_test.cc, multibody/fixed_fem/dev/test/linear_constitutive_model_test.cc, multibody/fixed_fem/dev/test/static_elasticity_element_test.cc
Refactors the old implementation in `multibody/fem/dev/elasticitiy_element.h`.
Towards #14330.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14515)
=> Refactor ElasticityElement & Add StaticElasticityElement

doc/system_doxygen.py
Default behavior changed between 3.6 and 3.8 so this ensures behavior is the same. For whatever reason is this causing issues for the Bionic apt build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14536)
=> Explicitly set encoding when opening files in system_doxygen.py

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/topology/BUILD.bazel, multibody/topology/multibody_graph.cc, multibody/topology/multibody_graph.h, multibody/topology/test/multibody_graph_test.cc
Closes #14518.
Indicate SDF-inserted welds by using an elaborate joint name. Since this
defeats the fail-fast error induced by having duplicate joint names (for
redundant welds), implement a more robust fail-fast error that complains
about any two joints that connect the same two bodies, regardless of
direction or other details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14534)
=> multibody: Give better errors when joints overlap with SDF static welds

lcmtypes/README.md, lcmtypes/lcmt_robot_state.lcm
This snuck in during #14372 after it was rebased over #14377.  Previously the plan was to deprecate this message, but after the rewrite we decided to keep it.  The BUILD.bazel file was correct (no deprecation) but the stale comments were overlooked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14539)
=> lcmtypes: Remove stray deprecation notice

geometry/benchmarking/BUILD.bazel, geometry/benchmarking/render_benchmark.cc
I was directly referencing the `render_engine_foo.h` headers. I did this
to template a function on RenderEngine subclass. However, there is no
render_engine_gl.h for mac os. There *is* a MakeRenderEngineGlFactory that
I use; it throws under mac.
Solution:
1. Stop referencing the header file at all.
2. Make the gl benchmarks conditional on a macro that says whether
or not the gl renderer is supported.
3. Put the macro in the benchmark's build configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14558)
=> [hotfix] Fix render_benchmark build error under mac 

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/eigen_conjugate_gradient_solver.h, multibody/fixed_fem/dev/linear_system_solver.h, multibody/fixed_fem/dev/test/eigen_conjugate_gradient_solver_test.cc
- Creates the LinearSystemSolver class that provides minimal API
required to solve the linear systems that arise from FEM solver.
- Creates an concrete implementation of LinearSystemSolver,
EigenConjugateGradientSolver that wraps around the
Eigen::ConjugateGradient solver.
- Implements EigenMatrixProxy which turns
multibody::contact_solvers::internal::LinearOperator into Eigen objects
and facilitates implementation of EigenConjugateGradientSolver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14548)
=> Add LinearSystemSolver and EigenConjugateGradientSolver

doc/BUILD.bazel, doc/_config.yml, doc/_js/drake.js, doc/_layouts/default.html, doc/documentation_instructions.rst, doc/gen_jekyll.py, doc/index.md, doc/jekyll_base.py, doc/serve_jekyll.py
Working toward #13832 (bullet 4)
Generates or serves an empty page (index.html)
``bazel run //doc:serve_jekyll`` will serve page locally at http://127.0.0.1:8000
``bazel run //doc:gen_jekyll -- --out_dir <output directory>`` will create output in specified <output directory>
Note: It is not necessary to build drake prior to running either command above.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14531)
=> Add Jekyll framework

doc/documentation_instructions.rst
Came across while reviewing #13832
Before:
> ![image](https://user-images.githubusercontent.com/26719449/105904149-c95b6f80-5fee-11eb-988c-d7df3f7cd3e8.png)
After:
> ![image](https://user-images.githubusercontent.com/26719449/105904253-e728d480-5fee-11eb-9a11-381211aba81d.png)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14572)
=> doc: Escape 'templated' URL with port number for Jekyll instructions

bindings/pydrake/doc/BUILD.bazel, doc/BUILD.bazel, examples/cubic_polynomial/BUILD.bazel, examples/kuka_iiwa_arm/BUILD.bazel, examples/manipulation_station/BUILD.bazel, examples/scene_graph/BUILD.bazel, tools/skylark/drake_cc.bzl, tools/skylark/drake_py.bzl
Adding test-specific tags to non-test programs is misleading.
(This is a prerequisite for housecleaning our doc tests.)
This PR temporarily increases the `tags = ["manual"]` copy-pasta in our doc folders.  That will evaporate in the next PR #14583.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14581)
=> tools: Distinguish test_rule_tags vs tags

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/piecewise_quaternion.h
Relates to #14561
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14585)
=> Expose piecewise quat slerp's orientation getters.

bindings/pydrake/doc/BUILD.bazel, doc/BUILD.bazel
This enables us to do https://github.com/RobotLocomotion/drake-ci/pull/122 and move entropy from `drake-ci` back into `drake`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14583)
=> doc: Define groupings to smooth our CI integration

bindings/pydrake/test/trajectories_test.py
Follow-up to #14585
Supersedes #14588
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14589)
=> py trajectories: Handle numeric precision difference on Mac

examples/multibody/cassie_benchmark/BUILD.bazel, examples/multibody/cassie_benchmark/conduct_experiment, examples/multibody/cassie_benchmark/copy_results_to, examples/multibody/cassie_benchmark/record_results.sh, tools/performance/BUILD.bazel, tools/performance/README.md, tools/performance/benchmark_tool, tools/performance/record_results.py
Relevant to: #14464
Gather the sharable bits of experiment execution scripting and port the cassie
benchmark to use it.
This is a WIP branch, exploring the idea of factoring some experiment-execution
machinery out of the cassie_benchmark example.  I'm not greatly sold on how it
looks so far, though I think it is potentially useful enough and solves enough
distracting subproblems to be worth some sort of better expression.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14505)
=> tools/performance: Start gathering sharable infrastructure

tools/workspace/voxelized_geometry_tools/package.BUILD.bazel, tools/workspace/voxelized_geometry_tools/repository.bzl
Updates `voxelized_geometry_tools` external to new device pointcloud voxelizer interface that reduces duplication between CUDA and OpenCL voxelizers (and simplifies stubbing them out).
+@ggould-tri for feature review, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14600)
=> Update VGT external for new device voxelizer interface

systems/primitives/affine_system.cc, systems/primitives/first_order_low_pass_filter.cc, systems/primitives/integrator.cc, systems/primitives/linear_system.cc
These checks are not performance-critical, and are checking user input (not internal invariants), so we should always leave them armed.
Having these off by default let a bug slip through into Anzu.
(Of course, we could work to improve the error messages & etc; this is just the minimum delta from the current state of affairs.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14615)
=> primitives: Promote some ASSERT to DEMAND

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/deprecation.py, bindings/pydrake/common/module_py.cc, bindings/pydrake/common/test/module_test.py, bindings/pydrake/test/polynomial_test.py, bindings/pydrake/test/trajectories_test.py
Do dumb deferred deprecation gymnastics for pydrake.common._module_py
Make assertion error for descriptor deprecator more useful
Resolves #14591
Relates #7912 due to pulling hair out
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14592)
=> py common: Deprecate bad alises for Tolerance Type

CMakeLists.txt, doc/developers.rst, tools/macos.bazelrc, tools/workspace/cc/repository.bzl, tools/workspace/os.bzl
Toward #13648.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14608)
=> Allow for new macOS versioning scheme and sync minimum compiler and CMake versions for macOS

multibody/fixed_fem/dev/dynamic_elasticity_element.h, multibody/fixed_fem/dev/elasticity_element.h, multibody/fixed_fem/dev/elasticity_model.h, multibody/fixed_fem/dev/fem_model.h, multibody/fixed_fem/dev/static_elasticity_element.h, multibody/fixed_fem/dev/static_elasticity_model.h, multibody/fixed_fem/dev/test/dynamic_elasticity_element_test.cc, multibody/fixed_fem/dev/test/elasticity_element_test.cc, multibody/fixed_fem/dev/test/static_elasticity_element_test.cc, multibody/fixed_fem/dev/test/static_elasticity_model_test.cc
- Move mass matrix calculation from DynamicElasticityElement to the base
class, ElasticityElement.
- Provide methods set gravity vector.
- Provide methods to precompute the gravity force on the element.
- Modify existing tests to accomodate for the new term that appears in
residual calculation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14595)
=> Implement external force in ElasticityElement/Model

tools/lint/drakelint.py
In service of #14431, code including OpenMP will become part of drake. Since OpenMP support varies depending on compiler and platform, uses must be guarded by the `_OPENMP` define. This PR adds an additional check to drakelint for OpenMP includes `#include <omp.h>` and directives `#pragma omp` to ensure they are preceded by `#if defined(_OPENMP)` and followed by `#endif`.
+@jwnimmer-tri for feature review, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14472)
=> Add lint check for unguarded OpenMP uses

setup/mac/binary_distribution/install_prereqs.sh, setup/mac/install_prereqs.sh, setup/mac/source_distribution/install_prereqs.sh, setup/ubuntu/binary_distribution/install_prereqs.sh, setup/ubuntu/install_prereqs.sh, setup/ubuntu/source_distribution/install_prereqs.sh
Things I could do:
1. Remove the retries and assume that If you are bothered that you do your one and only update beforehand (modulo `kcov`) you will pass `--without-update`.
2. Add some logic (not difficult, but verbose) to check that the `kcov`-related update really is needed.
I don't mind doing (1.) , just a couple of `sed` calls to fixup. Probably not worth doing (2.).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14492)
=> Add retry to brew and apt-get update calls and add flag to skip update altogether

examples/kuka_iiwa_arm/kuka_simulation.cc
Noticed this while trying out the demo. This demultiplexer output port should be 1 for velocity (0 for position).
Signed-off-by: Stephen Brawner <brawner@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14631)
=> Fix output port index for kuka_simulation example

tools/performance/benchmark_tool
There is great interest in experimenting with various modifications to
default build options. One example is to enable modern instruction set
extensions. This patch to benchmark_tool permits callers to pass
arbitrary bazel options to the build and run steps, to allow such
experiments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14624)
=> benchmark_tool: pass extra build args

examples/multibody/rolling_sphere/README.md, examples/multibody/rolling_sphere/make_rolling_sphere_plant.cc, examples/multibody/rolling_sphere/make_rolling_sphere_plant.h, examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc, multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc, multibody/plant/test/multibody_plant_hydroelastic_test.cc
Incorporates the discrete approximation of hydroelastics using our discrete solver.
Closes #14230.
N.B. This is the same as PR #14574. Unfortunately I typed `git push -d` instead of `git push -f` and that deleted my remote branch, effectively closing the PR. Apparently impossible to recover from this in github. This branch addresses the last comments in the original #14230.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14630)
=> Implements the discrete hydroelastics approximation

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/dynamic_elasticity_element.h, multibody/fixed_fem/dev/dynamic_elasticity_model.h, multibody/fixed_fem/dev/elasticity_element.h, multibody/fixed_fem/dev/elasticity_model.h, multibody/fixed_fem/dev/fem_element.h, multibody/fixed_fem/dev/newmark_scheme.h, multibody/fixed_fem/dev/state_updater.h, multibody/fixed_fem/dev/static_elasticity_model.h, multibody/fixed_fem/dev/test/dynamic_elasticity_model_test.cc, multibody/fixed_fem/dev/test/newmark_scheme_test.cc, multibody/fixed_fem/dev/test/zeroth_order_state_updater_test.cc, multibody/fixed_fem/dev/zeroth_order_state_updater.h
- DynamicElasticityModel implements ElasticityModel.
- NewmarkScheme implements StateUpdater.
- Add a new method to StateUpdater, IntegrateTime.
- Add a new helper method to FemElement, ExtractElementDofs.
- Fix a bug in DynamicElasticityElement that the entire state (instead
of the state dofs corresponding to the element) multiplies the
mass/damping matrix when calculating the element residual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14619)
=> Implement DynamicElasticityModel and NewmarkScheme

geometry/proximity_engine.cc, geometry/proximity_engine.h, geometry/test/proximity_engine_test.cc
We have other tests/functionality that rely on the fact that the Mesh shape is represented by an fcl::Convex under the hood. This gives those downstream tests the ability to query that this is still happening and condition the test outcomes accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14640)
=> [proximity] Increase ProximityEngine introspection for unit tests

geometry/proximity/penetration_as_point_pair_callback.cc, geometry/proximity/test/penetration_as_point_pair_callback_test.cc, geometry/query_object.h
The very special case of `HalfSpace`-`HalfSpace` was not considered. This should throw an error as being a meaningless query. Before this patch, the fcl query would be dispatched and we were at the mercy of how fcl handled it -- it handles it poorly. Now, we officially report a problem.
This also cleans up the documentation in `QueryObject` to reflect the current state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14639)
=> [proximity] Fixes bug in HalfSpace-HalfSpace support for point-pair penetration

doc/release_notes/template.txt
Came across during #14646
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14647)
=> release notes: Remove `attic` from template

doc/code_review_checklist.rst
Split off from #14546 
Relates https://github.com/RobotLocomotion/styleguide/pull/41
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14653)
=> doc: Add example of searching for commits that modify deprecations

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/test/deprecation_example/README.md, bindings/pydrake/common/test/deprecation_example/cc_module_py.cc, bindings/pydrake/common/test/deprecation_example/example_class.cc, bindings/pydrake/common/test/deprecation_example/example_class.h, bindings/pydrake/common/test/deprecation_test.py, bindings/pydrake/common/test/deprecation_utility_test.py, bindings/pydrake/pydrake_doxygen.h
Show `catch_drake_warnings` be used next to non-deprecated API
Adds arguments names to methods
Make the goal of ExampleCppStruct deprecation more clear in code (not
just comments)
~To partially address @mitiguy's pain points here:~
A very scoped-down change motivated by:
https://githu1.com/robotlocomotion/drake/pull/14538#pullrequestreview-571747122
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14546)
=> pydrake: Make explicit / orthogonal unittest for `catch_drake_warnings`

math/rigid_transform.h, math/test/rigid_transform_test.cc
Optimization (e.g., AVX instructions for multiplying rigid transforms) can leverage a continuous memory layout of RigidTransform<double> as 12 sequential doubles starting with a 3x3 RotationMatrix<double> (9 doubles) immediately followed by a 3x1 position vector (3 doubles).
A unit test verifies the order is always R_AB_followed by  p_AoBo_A_.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14643)
=> Tests to ensure RigidTransform<double> can work with optimization instructions.

doc/_config.yml, doc/_includes/header.html
Use `contains` for explicit nested config check for one missing var
See: https://github.com/Shopify/liquid/issues/1034#issuecomment-590121750
From failure: https://drake-cdash.csail.mit.edu/test/129053560
```
Liquid Exception: Liquid error ({runfiles}/drake/doc/_includes/header.html line 15): undefined variable subfolderitems included in /_layouts/default.html
jekyll 3.8.6 | Error:  Liquid error ({runfiles}/drake/doc/_includes/header.html line 15): undefined variable subfolderitems included 
/usr/lib/ruby/vendor_ruby/liquid/variable_lookup.rb:62:in `block in evaluate': Liquid error ({runfiles}/drake/doc/_includes/header.html line 15): undefined variable subfolderitems included  (Liquid::UndefinedVariable)
```
--- …
=> jekyll: Do not use strict mode

geometry/proximity/BUILD.bazel, geometry/proximity/test/make_capsule_mesh_test.cc
Closes #14673.
- Adds size="medium" to `make_capsule_mesh_test`
- Removes one unused dependency from `make_capsule_mesh_test`
- Fixes typo with wrong resolution hint in `make_capsule_mesh_test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14674)
=> [geometry] Fix-forward for CI failures on `make_capsule_mesh_test`.

tools/skylark/pybind.bzl
We know that our hard-coded libclang handles Drake's minimum C++ standard revision, so we can just hard-code that spelling for mkdoc.  This allows users to build object code using -std=c++20 mode without angering libclang.
I confirmed that on both Ubuntu and macOS, in a default configuration, the _only_ cxxopts coming in through the fragment was `-std=c++17`.
Closes #14654.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14669)
=> pybind: Hard code -std=c++17 option spelling

geometry/proximity/obj_to_surface_mesh.cc, geometry/proximity_engine.cc, geometry/render/gl_renderer/shape_meshes.cc, geometry/render/gl_renderer/test/shape_meshes_test.cc, tools/workspace/tinyobjloader/faster_float_parsing.patch, tools/workspace/tinyobjloader/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14656)
=> Update to latest tinyobjloader with patched tryParseDouble

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/dirichlet_boundary_condition.h, multibody/fixed_fem/dev/dynamic_elasticity_element.h, multibody/fixed_fem/dev/eigen_conjugate_gradient_solver.h, multibody/fixed_fem/dev/elasticity_element.h, multibody/fixed_fem/dev/elasticity_model.h, multibody/fixed_fem/dev/fem_model.h, multibody/fixed_fem/dev/fem_solver.h, multibody/fixed_fem/dev/fem_state.h, multibody/fixed_fem/dev/linear_system_solver.h, multibody/fixed_fem/dev/static_elasticity_element.h, multibody/fixed_fem/dev/test/dynamic_elasticity_element_test.cc, multibody/fixed_fem/dev/test/eigen_conjugate_gradient_solver_test.cc, multibody/fixed_fem/dev/test/fem_solver_test.cc, multibody/fixed_fem/dev/test/static_elasticity_element_test.cc, multibody/fixed_fem/dev/test/static_elasticity_model_test.cc
FemSolver provides the minimum functionalities needed to solve the
system of equations that arise from FEM space discretization by
integrating components such as FemModel, LinearSystemSolver and
DirichletBoundaryCondition.
FemSolverTest serves as an integration test for FEM. It generates
an arbitrary set of forces on the vertices of a model by setting
arbitrary displacements for the vertices of the model. It then verifies
that under those forces, the solution provided the solver matches the
prescribed displacements.
To enable the test mentioned above, the capability to set an explicit
external force directly on the vertices of the model has been added.
Furthermore, the API for LinearSystemSolver has been slightly changed
to allow LHS of the system to be modified.
Bug fix: fix the sign of …
=> [FEM] FemSolver and static elasticity test

doc/BUILD.bazel, doc/README.txt, doc/_layouts/release.html, doc/_pages/installation.md, doc/_release-notes/release_notes.md
This matches the index URL in Jekyll flavor to what the Sphinx flavor had, to avoid breaking users' bookmarks.
Relates #14577.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14683)
=> jekyll: Move release_notes index into the collection

multibody/plant/test/multibody_plant_test.cc, multibody/tree/multibody_tree_topology.h
Relevant to: #14641
This just addresses the immediate symptom of #14641 -- an obtuse error
message. The matter of making WeldFrames() less error-prone will be the
subject of a later PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14655)
=> multibody: Give better error when mobilizers clash

doc/_pages/clion.md, doc/_pages/code_style_guide.md, doc/_pages/from_binary.md, doc/_pages/from_source.md
Fix HTML escaping for green CLion +.
Fix links to older_releases.
Add style guide footnote marker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14684)
=> jekyll: Misc fixes

geometry/benchmarking/render_benchmark.cc, geometry/benchmarking/render_benchmark_doxygen.h
In order to avoid measuring the cost warm starting a `RenderEngine`, each of the tests explicitly evaluates the render query multiple times before entering the measurement loop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14677)
=> [render] Allow for RenderEngine implementations that require warm starting

doc/_pages/getting_help.md, doc/_pages/release_playbook.md, doc/_release-notes/v0.27.0.md, doc/release_playbook.rst
The following commits port the recent changes merged into *.rst files (#14646, #14651 , #14660)  into their new *md Markdown counterparts. Each commit is a self-contained port, and this could easily be split into multiple PR's if that is preferable.
While performing the port, I found a typo in the source material of  `doc/release_playbook.rst`, which I fixed in both the rst and md files.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14687)
=> jekyll: Ports recent .rst changes to Markdown

tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_pair_contact.py
This is a baby step towards solving #14680.
It allows users to choose one of the three vector scaling modes (default Fixed Length) as Sean explained in #14680:
- __Fixed Length__: All force vectors are drawn as a fixed length arrows. Direction is clear, but there is no way to assess relative magnitude.
- __Scaled__: All force arrows' lengths are drawn proportional to the force magnitude.
- __Auto Scaled__: The largest *instantaneous* force is rendered with a fixed length arrow. All other force arrows are scaled smaller, based on their relative proportion to the maximum magnitude.
Users can also set the `global scale of all vectors` and the threshold of `minimum vectors` to draw.
However, these settings apply to all kinds of vectors (force, moment, traction, and slip velocity) at the same …
=> [tools:drake_visualizer] Simple vector menu for hydroelastic contact.

doc/index.md
On Drake's [current website](https://drake.mit.edu/#tutorials), the tutorials block looks like this:
On the contractor's [refresh of the website](https://drake.sky.a2hosted.com/#Tutorials), the tutorials block looks like this:
That is, the buttons and links to the tutorial previews have gone missing.
This PR adds back the buttons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14685)
=> jekyll: Add landing page links to binder and nbviewer

doc/_pages/documentation_instructions.md, doc/documentation_instructions.rst
Propagate some rst diffs from [2290ae0](https://github.com/RobotLocomotion/drake/commit/2290ae07e4b7c9064af9742caa644487ebab8e6c#diff-c2ffe499c54c8af6910c806e91891cacff54b74144d801dade6c35b23d6f772d) back into the md copy of the site.
Remove the stale "serves an empty page" disclaimer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14696)
=> doc: Tidy up Jekyll instructions

systems/analysis/integrator_base.h, systems/analysis/simulator.cc, systems/analysis/simulator.h, systems/framework/system.cc, systems/framework/system.h, systems/framework/test/leaf_system_test.cc, systems/framework/test/system_test.cc, systems/lcm/lcm_interface_system.cc
When an overridden `DoCalcNextUpdateTime()` reported a trigger time but didn't return any Event object to serve as a handler, the trigger time was being ignored with time advancing as though nothing happened. But that could cause time-triggered events that should have occurred later in that same step to be missed entirely. LcmInterfaceSystem wasn't returning an Event object from its DoCalcNextUpdateTime() override and caused problems.
This PR changes the behavior to treat a no-Event timed trigger as an error. A subsystem that reports a finite trigger time must provide at least one Event object, even if that Event does nothing. (LcmInterfaceSystem is fixed here.) Also, failure to set the trigger time or returning NaN was always prohibited but was just a DRAKE_ASSERT before; now it is a …
=> Make sure DoCalcNextUpdateTime() timed trigger is accompanied by an Event object.

multibody/fixed_fem/dev/element_cache_entry.h, multibody/fixed_fem/dev/fem_state.h, multibody/fixed_fem/dev/newmark_scheme.h, multibody/fixed_fem/dev/test/dummy_element.h, multibody/fixed_fem/dev/test/dynamic_elasticity_model_test.cc, multibody/fixed_fem/dev/test/elasticity_element_test.cc, multibody/fixed_fem/dev/test/fem_solver_test.cc, multibody/fixed_fem/dev/test/fem_state_test.cc, multibody/fixed_fem/dev/test/newmark_scheme_test.cc, multibody/fixed_fem/dev/test/static_elasticity_model_test.cc, multibody/fixed_fem/dev/zeroth_order_state_updater.h
- Create a staleness flag for each element cache entry that defaults to true. When the element data is requested, if the staleness flag is true, then recompute the element data and set the staleness flag to false; if the staleness flag is false, return the element data without recalculating.
- *Any* modification to the state sets the staleness flags of all element cache entry to true.
- Modify element data of DummyElement to be non-constant to facilitate testing.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14698)
=> Enable simple caching for FEM state dependent quantities

doc/_pages/gallery.md, doc/gallery.rst
RenderEngineOspray had been removed in the past. It no longer makes sense
to have an example that advertises it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14716)
=> [doc] Remove example using RenderEngineOspray

lcmtypes/BUILD.bazel, lcmtypes/experimental_lcmt_deformable_tri.lcm, lcmtypes/experimental_lcmt_deformable_tri_mesh_init.lcm, lcmtypes/experimental_lcmt_deformable_tri_mesh_update.lcm, lcmtypes/experimental_lcmt_deformable_tri_meshes_init.lcm, lcmtypes/experimental_lcmt_deformable_tri_meshes_update.lcm, multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/deformable_visualizer.cc, multibody/fixed_fem/dev/deformable_visualizer.h, multibody/fixed_fem/dev/run_scripted_deformable_motion.cc, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/BUILD.bazel, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/__init__.py, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/experimental_show_deformable_mesh.py, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/use_builtin_scripts.py
The deformable visualizer was originally author by @SeanCurtis-TRI. I
have since made modifications to allow it to visualize more than one
object.
A simple demo `run_scripted_deformable_motion` is added to visually test
the deformable visualizer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14697)
=> Add deformable visualizer

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/dirichlet_boundary_condition.h, multibody/fixed_fem/dev/dynamic_elasticity_model.h, multibody/fixed_fem/dev/elasticity_model.h, multibody/fixed_fem/dev/fem_model.h, multibody/fixed_fem/dev/fem_model_base.cc, multibody/fixed_fem/dev/fem_model_base.h, multibody/fixed_fem/dev/fem_solver.h, multibody/fixed_fem/dev/fem_state.h, multibody/fixed_fem/dev/fem_state_base.h, multibody/fixed_fem/dev/newmark_scheme.h, multibody/fixed_fem/dev/state_updater.h, multibody/fixed_fem/dev/static_elasticity_model.h, multibody/fixed_fem/dev/test/dirichlet_boundary_condition_test.cc, multibody/fixed_fem/dev/test/dynamic_elasticity_model_test.cc, multibody/fixed_fem/dev/test/fem_solver_test.cc, multibody/fixed_fem/dev/test/newmark_scheme_test.cc, multibody/fixed_fem/dev/test/static_elasticity_model_test.cc, multibody/fixed_fem/dev/test/zeroth_order_state_updater_test.cc, multibody/fixed_fem/dev/zeroth_order_state_updater.h
- Create AbstractFemModel and AbstractFemState that are only templated
on the scalar type but not the FemElement type that concrete FemModel
and FemState inherit from.
- Remove the template on FemSolver.
- Let FemModel own the StateUpdater and DirichletBoundaryCondition it
uses.
- Fix a few minor bugs in documentation of FemSolver.
- Fixes #14667.
- Fixes #14668.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14681)
=> [FEM] Add abstract base class for FEM model and state

tools/workspace/common_robotics_utilities/repository.bzl, tools/workspace/voxelized_geometry_tools/repository.bzl
Updates `common_robotics_utilities` and `voxelized_geometry_tools` to latest. Changes in the externals:
- Change in CRU to properly handle varying Eigen alignment requirements in Eigen alignment enforcement
- Adds backend enumeration in VGT to enumerate possible voxelizers, and uses that enumeration to run voxelizer test case on all possible voxelizers (note - only the basic CPU implementation is available here).
+@ggould-tri for feature review, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14728)
=> Bump CRU and VGT externals to latest

geometry/proximity/BUILD.bazel, geometry/proximity/test/make_cylinder_mesh_test.cc
Resolve the long running time of make_cylinder_mesh_test on CI `mac-catalina-clang-bazel-nightly-everything-address-sanitizer` as report in Console output of this one:
[mac-catalina-clang-bazel-nightly-everything-address-sanitizer/506](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-catalina-clang-bazel-nightly-everything-address-sanitizer/506/console)
[6:38:22 AM]  //geometry/proximity:make_cylinder_mesh_test                             PASSED in 1038.5s
<h3>Update</h3>
Now it's
[12:57:24 PM] //geometry/proximity:make_cylinder_mesh_test                            PASSED in 114.0s
I also removed "size=medium" from BUILD.bazel for make_capsule_mesh_test, which is so fast that it didn't need the flag.
--- …
=> [geometry] Remove 50-million-tetrahedron test of the old cylinder mesh.

common/value.cc
Closes #14566.
---
Here is an example of the new report, taken from the output of ValueTest.NonTypeTemplateParameter:
[console] [warning] The drake::test::(anonymous)::UnadornedAnonEnumTemplate<(drake::test::(anonymous)::AnonEnum)0> class is incompatible with the typename hasher that provides the type-erasure checking for AbstractValue casts, most likely because the problematic class mixes template parameters with nested classes or non-type template parameters. As a result, operations on Value<drake::test::(anonymous)::UnadornedAnonEnumTemplate<(drake::test::(anonymous)::AnonEnum)0>> will suffer from slightly impaired performance. If the problem relates to nested classes, you may be able to resolve it by un-nesting the class in question. If the problem relates to a single non-type …
=> common: Improve AbstractValue error message suggestions

tools/skylark/pybind.bzl, tools/workspace/lcm/package.BUILD.bazel, tools/workspace/python/repository.bzl
I hoped this was going to be part of a fix for the bigger colab problems, but it did not work out. However, it is an improvement and closes #14050, so not wasted work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14730)
=> Use correct suffix for Python C extensions

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/fem_model.h, multibody/fixed_fem/dev/fem_model_base.cc, multibody/fixed_fem/dev/fem_model_base.h, multibody/fixed_fem/dev/fem_solver.h, multibody/fixed_fem/dev/fem_state.h, multibody/fixed_fem/dev/fem_state_base.cc, multibody/fixed_fem/dev/fem_state_base.h, multibody/fixed_fem/dev/test/dirichlet_boundary_condition_test.cc, multibody/fixed_fem/dev/test/fem_solver_test.cc, multibody/fixed_fem/dev/test/fem_state_test.cc
- Move all state related API from FemState to FemStateBase for easier
access. FemState now only handles state-dependent quantities whereas
FemStateBase handles all state quantities.
- Add a missing API: get_highest_order_state().
- Minor bug fixes in FemModelBase API:
- ApplyDirichletBoundaryConditions->ApplyDirichletBoundaryCondition
- MakeFemStateBase is turned into a proper NVI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14723)
=> [FEM] Improve API for FemStateBase

systems/framework/diagram.cc, systems/framework/system.h, systems/framework/system_base.cc, systems/framework/system_base.h
Part of #12560.
Specifically, fix up EvalTimeDerivatives and GetSubsystemDerivatives.
Also relocate the exception message implementation into the cc file to improve build size and time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14738)
=> framework: Add more checks that a Context matches its System

tools/workspace/pybind11/BUILD.bazel
Noted while debugging #14739.
This is a follow-up from #14187.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14743)
=> pybind11: Remove stray coverage deps from mkdoc

bindings/pydrake/common/jupyter.py
The `runAll` behavior of jupyter notebooks, which we effectively have no mechanism to unit test in drake, is broken in python 3.6 and above when calling my `process_ipywidget_events` method.  This patch removes the problematic code.
To test, use 
```
bazel run //bindings/pydrake/systems:jupyter_widgets_examples
```
and change the first line to `True` as instructed in the first cell, and then use the dropdown menu to perform a 'kernel=>restart and run all'.  you will have to press 'stop simulation' in the second cell to move to execution of the remaining cells, and will see the error.
After this PR, you will see the remaining cells run successfully.
The change here removes the "abort" handling logic that was based on a "private" variable which was removed.  So if you were to "runAll", and …
=> fix for jupyter runAll when using process_ipywidget_events

examples/acrobot/acrobot_io.py
Apparently not every binary wheel has `yaml.CLoader` enabled, and if `libyaml` is not available when built from source, it does not appear that `yaml.CLoader` is available either.
Relates https://github.com/RobotLocomotion/drake/issues/1183.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14750)
=> Do not use yaml.CLoader in acrobot example

tools/workspace/pybind11/package-create-cps.py
The scope of this PR is to unblock fix basic CI errors on `drake-external-examples`, not to be correct in terms of mirroring CMake logic across the hoops of CPS + Bazel.
See: https://drakedevelopers.slack.com/archives/C270MN28G/p1615308431035600
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14755)
=> pybind11: Inject CPS nonce to make pybind11Tools happy

multibody/tree/test/string_view_map_key_test.cc
This includes the missing <unordered_map> header which ubuntu is letting
slide but mac is justifiably angry about.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14756)
=> [patch] Adds the missing std header causing mac to fail

bindings/pydrake/multibody/math_py.cc
Was doing visuomotor whatev things, came across this minor typo:
https://drake.mit.edu/pydrake/pydrake.multibody.math.html#pydrake.multibody.math.SpatialVelocity_.SpatialVelocity_[float].Rotate
Typo zoom-on:
> ![image](https://user-images.githubusercontent.com/26719449/110703857-466b2e80-81c2-11eb-9230-94b0c245f127.png)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14765)
=> py mbp: Fix typo on docstring for SpatialVelocity.Rotate

doc/_pages/getting_help.md
Came across due to: https://github.com/RobotLocomotion/drake-external-examples/pull/198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14764)
=> getting_help: Fix typo (should be all-caps)

tools/install/colab/setup_drake_colab.py
Reverts RobotLocomotion/drake#14693.
The hard-coding did not resolve the problem, and technically the major.minor spelling is less incorrect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14766)
=> Revert "Hardcode python version to 3.6 in setup_drake_colab"

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/deformable_contact.cc, multibody/fixed_fem/dev/deformable_contact.h, multibody/fixed_fem/dev/test/deformable_contact_test.cc
Provide the public API:
- DeformableContactSurface: a representation of the contact between a
volume (tetrahedral) mesh and a surface (triangle) mesh. The result
is an implicit polygon mesh where only the contact data on each
polygon can be queried, but not the mesh itself. Each polygon data
can report: normal, area, centroid (in Cartesian and Barycentric
coordinates) and the tet index in the volume mesh that produced the
polygon. This is similar to the idea proposed for hydroelastic contact
query in #14579.
- Defines the function: ComputeTetMeshTriMeshContact.
Co-authored-by: Sean Curtis <sean.curtis@tri.global>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14767) …
=> [FEM] Add support for basic deformable contact

tutorials/BUILD.bazel, tutorials/mathematical_program_multibody_plant.ipynb, tutorials/nonlinear_program.ipynb, tutorials/updating_costs_and_constraints.ipynb
While going through tutorials, I noticed that the `quadratic_program` and `updating_costs_and_constraints` tutorials were missing from the bazel build file.  I couldn't find any obvious reason why these two are missing so supposed I should add them.
Also fix spelling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14722)
=> Add missing tutorials to build file

geometry/scene_graph.cc, geometry/test/scene_graph_test.cc
The old error message strictly reported source *id*, which is not incredibly helpful for the end user. So, now, it includes both source id and registered name. It further elaborates on the condition when not connecting is erroneous.
It also removes the lambda function which served purely a speculative role -- it was waiting for the day when velocities or
accelerations were also available. When we start consuming velocities, we can restore the generality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14773)
=> [geometry] Improve SceneGraph error for unconnected input ports

doc/build.py
Something strange happened to the indent, so we have three broken tags and three urls missing.
From Google:
```
Sitemap can be read, but has errors
Missing XML tag   3 instances
This required tag is missing. Please add it and resubmit.
Examples
Line 5859    Parent tag: url
Tag: loc
Line 9490    Parent tag: url
Tag: loc
Line 9518    Parent tag: url
Tag: loc
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14780)
=> Fix sitemap generation

geometry/proximity/BUILD.bazel, geometry/proximity/distance_to_shape_callback.cc, geometry/proximity/distance_to_shape_callback.h, geometry/proximity/test/distance_sphere_to_shape_test.cc
The distance-to-shape callback was entirely defined in the header file. This moves as much as possible into the .cc file. This is solely a compiler optimization.
The `ComputeNarrowPhaseDistance` method is still defined in the header file to faciltiate the logic for when it invokes the fallback. The test specializes the fallback function on a unique scalar (`float`). The `float` implementation signals invocation. Then we call the otherwise undefined `CompupteNarrowPhaseDistance<float>` and watch when the special implementation gets triggered.
A note has been added to a test to find an alternate formulation of this test to detect when the fallback is invoked.
--- …
=> [geometry] Move elements of distance_to_shape.h into .cc

systems/framework/diagram.cc
We can compute the map once per system and reuse it as we search, instead of once per possible input.  This removes some super-linear growth factor in diagram size that ends up being problematic.
The key observation is that `HasDirectFeedthrough` was always computing the full `GetDirectFeedthroughs` and then throwing away all but the one map entry.
Closes #14787 (by replacing it with a different implementation).
This is a step towards #14774, which would refine the implementation further.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14788)
=> systems: Avoid redundantly computing subsystem feedthrough maps

CMakeLists.txt
This was broken in #14605.
Closes #14796.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14798)
=> cmake: Fix python3 search for CMake 3.10 (Ubuntu 18.04)

math/rotation_matrix.h
- ToQuaternion is a static method. Make that explicit
- Use `<T>` consistently
- Use `your_matrix3` vs. `your_Matrix3`
Context: Came across this while writing response here:
https://github.com/RobotLocomotion/drake/pull/14799#issuecomment-802988977
\cc @mitiguy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14801)
=> rotation_matrix: Minor fix for message on matrices that fail SO(3) check

doc/pydrake/BUILD.bazel, doc/pydrake/sphinx_base.py, tools/workspace/default.bzl, tools/workspace/sphinx/repository.bzl, tools/workspace/which.bzl
Our documentation tools are Ubuntu-only, so we don't need to ask Bazel to locate the correct binary -- we can just hard-code it.
This is prep work for #14803.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14804)
=> workspace: Deprecate the @sphinx repository

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, bindings/pydrake/systems/test/meshcat_visualizer_test.py, multibody/plant/multibody_plant.h, multibody/tree/weld_joint.h, tutorials/rendering_multibody_plant.ipynb
Closes #14641.
The parameter names were variously confusing (WeldFrames, see #14641)
and/or inconsistent with other joints (WeldJoint constructor).
This patch moves both entry points to use naming consistent with other
joint APIs, clarifies monogram notation issues in documentation, and
deprecates the old parameter names in python bindings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14805)
=> multibody: Rename parameters of WeldJoint() and WeldFrames()

geometry/proximity/distance_to_shape_callback.cc, geometry/proximity/distance_to_shape_callback.h, geometry/proximity/test/distance_sphere_to_shape_test.cc
Previous efforts to push the implementation of the `shape_distance::Callback` implementation into the .cc file have been constrained. The logic or determining if calling the fallback was required was buried in `ComputeNarrowPhaseDistance`. So, to confirm that the classification logic was right, we had to use indirect tricks on secializing `ComputeNarrowPhaseDistance` (using the otherwise unsupported `float` scalar type). This worked, but was unwieldy and required a fair amount of the code to remain in the header (in order to instantiate on double).
The simple solution was to move the classification logic (fallback required or not) into its own stand-alone function and test that explicitly.
This led to a change in the unit tests to test this new function directly. Part of this effort led …
=> [geometry] Push `distance_to_shape_callback` implementation into .cc

bindings/pydrake/BUILD.bazel
Context: https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1616474859009900
This is one possible solution.
> hongkai.dai:
> May I ask why the package `//bindings/pydrake/common/test_utilities:numpy_compare_py` is only visible inside drake? I would like to use this package in anzu but I can't do it due to visibility restriction
> 
> eric.cousineau:
> b/c it was for testing, and isn't installed.But that being said, I'm totes fine with it being exposed as a public bazel target, esp. if you're prototyping on this stuff w/in Anzu (TRI private codebase). (edited)
> 
> eric.cousineau:
> Oooohhhhhhhh shewt, forgot about weird interplays btw granular targets in Bazel and our encapsulated super-target, `//bindings/pydrake` ...Hm...
\cc @hongkai-dai
--- …
=> pydrake: Expose some testing utilities to drake_bazel_external workflows

geometry/proximity/test/characterization_utilities.cc, geometry/proximity/test/characterization_utilities.h, geometry/proximity/test/characterization_utilities_test.cc, geometry/proximity/test/penetration_as_point_pair_characterize_test.cc
This does the following:
1. Introduces shapes `Capsule` and `Ellipsoid` into the analysis.
- `penetration_as_point_pair_characterize_test` now evaluates (capsule, capsule), (capsule, ellipsoid), (capsule, sphere), (ellipsoid, ellipsoid), (ellipsoid, sphere) and (sphere, sphere)
2. The increase in pairings calls for efficient configuration construction
- We create configurations by:
1. Selecting a set of curated tangent planes to the various shapes.
2. We pose the shapes relative to each other by posing the planes relative to each other and then offsetting along the planes' shared normals.
3. Unit tests for the additional framework code.
4. Add some macros in penetration_as_point_pair_characterize_test to further make the expression of tests compact.
Follow up PR will complete the …
=> [geometry] Extend characterization framework, apply to point-pair penetration (2 of 4)

geometry/proximity/test/penetration_as_point_pair_characterize_test.cc
#14795 had an error when running on mac -- the precision was too tight. This loosens the precision to pass on mac.
Replaces #14819
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14821)
=> [fix forward] Patch for mac difference in mac precision

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, tutorials/BUILD.bazel, tutorials/debug_mathematical_program.ipynb, tutorials/mathematical_program.ipynb
Resolves #13091 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14815)
=> Add a tutorial on the debugging tips for MathematicalProgram.

multibody/plant/test/multibody_plant_scalar_conversion_test.cc
Fixes #14824.
Changes a few `DRAKE_DEMANDS` into equivalent `EXPECT_EQ` statements to perturb the binary.
The first 80 bytes of the binary are now:
```
00000000   7F 45 4C 46  02 01 01 00  00 00 00 00  00 00 00 00  .ELF............
00000010   03 00 3E 00  01 00 00 00  B0 1A 0D 00  00 00 00 00  ..>.............
00000020   40 00 00 00  00 00 00 00  08 96 68 1B  00 00 00 00  @.........h.....
00000030   00 00 00 00  40 00 38 00  09 00 40 00  28 00 27 00  ....@.8...@.(.'.
00000040   06 00 00 00  04 00 00 00  40 00 00 00  00 00 00 00  ........@.......
00000050   40 00 00 00  00 00 00 00  40 00 00 00  00 00 00 00  @.......@.......
```
Avoiding the issue described in SimonKagstrom/kcov#339.
--- …
=> Perturbs multibody_plant_scalar_conversion_test to fix kcov failure

doc/styleguide/_config.yml
Our config file asked for the "minima" theme, which does not exist on either Bionic nor Focal -- but on Focal a missing theme is a hard error, while on Bionic it seems to be silently ignored.
Hotfix for #14811.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14831)
=> doc: Fix styleguide publication on Focal

geometry/proximity/test/characterization_utilities.cc, geometry/proximity/test/characterization_utilities.h, geometry/proximity/test/characterization_utilities_test.cc, geometry/proximity/test/penetration_as_point_pair_characterize_test.cc, geometry/query_object.h
This entails:
- Extending the framework to include missing geometry types: box, cylinder, convex, half space, and mesh. Including tests for that infrastructure.
- Finish instantiating all QueryInstances for the penetration as point pair charcterize test.
- Update QueryObject (all values are now in place, they can be used in the documentation).
The next two PRs will do the same for distance to shape and distance to point.
Relates #10907
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14818)
=> Finish characterization of point-pair penetration

systems/trajectory_optimization/test/direct_transcription_test.cc
Minor follow-up to #14840 
This wouldn't have solved all the problems I created there (PEBKAC and not reading surrounding code), but would've helped a bit in resolving it faster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14847)
=> direct_transcript_test: Warn when test is skipped b/c of no SNOPT

systems/trajectory_optimization/BUILD.bazel, systems/trajectory_optimization/test/direct_transcription_test.cc
This commit replaces the first-aid fix of #14854, which addressed test
timeouts introduced at #14840.
Run the test in 2 shards. Most of the cases are vanishingly fast, but
the discrete- and continuous-mode SNOPT solves of Multibody*Test are
quite long under slow tooling (ASAN). This reshuffle should bring the
test latency down enough to avoid timeouts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14859)
=> direct_transcription: Parallelize test cases

geometry/proximity/BUILD.bazel, geometry/proximity/test/distance_to_shape_characterize_test.cc, geometry/query_object.h
This applies the framework defined in `characterization_utilities.{h|cc}` to the signed distance computation between shapes.
Introduces the test and updates the documentation.
Relates #10907
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14856)
=> [proximity] Characterize shape-shape signed distance query

BUILD.bazel
`./bin/drake-visualizer --help` from install tree returns a non-zero
error code, for reasons presently unknown.
Context: https://drakedevelopers.slack.com/archives/C270MN28G/p1617722383078400
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14869)
=> install_test: Skip for kcov due to failure in drake visualizer

geometry/proximity/BUILD.bazel, geometry/proximity/test/characterization_utilities.cc, geometry/proximity/test/characterization_utilities.h, geometry/proximity/test/distance_to_point_characterize_test.cc, geometry/query_object.h
Extend the framework defined in `characterization_utilities.{h|cc}` to accommodate shape-point signed distance:
- introduce a "point" primitive
- Introduce the concept of "symmetry" in the test -- for this test we always test "point-shape" and *never* "shape-point".
Add the supporting test and update the documentation accordingly.
Relates #10907
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14857)
=> [proximity] Characterize point-shape signed distance query

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/scene_graph_inspector.h, geometry/test/geometry_state_test.cc, geometry/test/scene_graph_inspector_test.cc
The ability to convert also includes the ability to filter based on role. This includes the public-facing inspector API as well as the GeometryState implementation.
closes #13493
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14871)
=> Add ability to convert GeometrySet into unordered_set<GeometryId>

geometry/proximity/BUILD.bazel, geometry/proximity/distance_to_point_callback.cc, geometry/proximity/distance_to_point_callback.h
This simply relocates existing code out of the header and into a .cc file. It makes sure that there are sufficient definitions of the "public" API on the supported numerical scalars.
Otherwise, no functionality has changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14872)
=> [geometry] Moving distance-to-point callback code into .cc file

bindings/pydrake/test/geometry_render_engine_subclass_test.py
- This had some documentation referencing no longer valid deprecated APIs.
Relates to: #14686 and #14855.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14870)
=> [bindings] Update documentation missed in previous code removal

common/symbolic_formula.h, common/test/symbolic_expression_test.cc
This is needed for Eigen >= 3.3.5. not_equal_strict relies on an
implicit conversion to bool. Since Expression has an explicit bool()
operator, we need to specialize the call. As of Eigen 3.3.5, this
function is called at least as part of triangular vector solve.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14868)
=> Add template specialization of not_equal_strict for symbolic::Expression

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic_decompose.cc, common/symbolic_decompose.h, common/test/symbolic_decompose_test.cc
First implementation of lumped parameter decomposition for full symbolic::Expressions.
This updates (and will soon replace) our related implementation in solvers/system_identification.h .  That implementation used the old (to be expunged) Polynomial class, and required a manual step to substitute trig functions into polynomial functions.  This substitution is difficult in general, and is not compatible with MultibodyPlant.  Furthermore, there is no fundamental reason to restrict the lumped-parameter decomposition to polynomials.
The follow-up work after this PR is to:
1) implement the numerical linear algebra logic for finding "identifiable lumped parameters"
2) provide a full system identification example using MultibodyPlant (i have a WIP of this in the sysid chapter of my underactuated …
=> DecomposeLumpedParameters from VectorX<Expression>

math/rotation_matrix.h, multibody/tree/BUILD.bazel, multibody/tree/test/rotational_inertia_test.cc, multibody/tree/test/unit_inertia_test.cc
The `RotationMatrix` class only supports Drake's default scalars.
Instantiating `RotationMatrix<AutoDiff1d>` is an API violation.
This is a prerequisite of #14860.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14862)
=> multibody: Adjust unit test to avoid scalar type violations

math/BUILD.bazel, math/rotation_matrix.cc, math/rotation_matrix.h
Inline functions are supposed to be short, but these functions are long.
I noticed in #14816 the inline getting out of hand, so this will help bring it back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14860)
=> math: Move RotationMatrix functions to cc file

lcmtypes/BUILD.bazel, lcmtypes/lcmt_header.lcm, lcmtypes/lcmt_image.lcm, lcmtypes/lcmt_image_array.lcm, lcmtypes/lcmt_point.lcm, lcmtypes/lcmt_quaternion.lcm
These are copied from https://github.com/RobotLocomotion/lcmtypes/tree/821ff4b, with edits to change the package and message names to match Drake conventions.
This is in preparation for #14884 towards #14362.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14885)
=> Add renamed copies of RobotLocomotion/lcmtypes used by Drake

bindings/pydrake/BUILD.bazel, bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc, bindings/pydrake/systems/test/lcm_test.py, bindings/pydrake/test/lcm_test.py, examples/manipulation_station/end_effector_teleop_sliders.py, examples/manipulation_station/manipulation_station_hardware_interface.cc, examples/manipulation_station/proof_of_life.cc, examples/planar_gripper/BUILD.bazel, examples/scene_graph/bouncing_ball_run_dynamics.cc, lcmtypes/BUILD.bazel, manipulation/planner/BUILD.bazel, systems/sensors/BUILD.bazel, systems/sensors/image_to_lcm_image_array_t.cc, systems/sensors/image_to_lcm_image_array_t.h, systems/sensors/lcm_image_array_receive_example.cc, systems/sensors/lcm_image_array_to_images.cc, systems/sensors/lcm_image_array_to_images.h, systems/sensors/lcm_image_traits.h, systems/sensors/robotlocomotion_compat.h, systems/sensors/test/image_to_lcm_image_array_t_test.cc, systems/sensors/test/lcm_image_array_to_images_deprecated_test.cc, tools/install/libdrake/BUILD.bazel, tools/install/libdrake/drake.cps, tools/workspace/drake_visualizer/repository.bzl, tools/workspace/lcmtypes_bot2_core/package.BUILD.bazel, tools/workspace/lcmtypes_robotlocomotion/package.BUILD.bazel
Port existing Drake code to use the new types.
Add helper header `drake/systems/sensors/robotlocomotion_compat.h` to alias the old names onto the new names, along with a deprecation warning.
Requires #14885 first.  Towards #14362.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14884)
=> Deprecate robotlocomotion_lcmtypes and bot2_core_lcmtypes

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/proximity/distance_to_shape_callback.cc, geometry/proximity/test/distance_sphere_to_shape_test.cc, geometry/proximity/test/distance_to_point_callback_test.cc, geometry/query_results/signed_distance_pair.h, geometry/query_results/signed_distance_to_point.h, geometry/test/proximity_engine_test.cc
The signed distance to point and signed distance pair query results had a flag indicating whether the returned gradient value was unique or not. While motivated by the best of intentions, it is not used and not correctly implemented (as extensively documented in #14781). The agreed-upon resolution is to simply deprecate that field.
This deprecates the fields in the two structs (and handles the downstream ramifcations).
It is authored as *two* commits -- one for each query result type, to afford the reviewer some convenience in mentally separating the two tasks. The idea is that there is value in keeping all the deprecations in the same PR (as they have enough in common to share mental context), but keep the two slices separate to provide locality). The commits will be treated as curated …
=> [geometry] Deprecate the "is grad unique" flag from query results

doc/BUILD.bazel, doc/defs.bzl, doc/doxygen_cxx/BUILD.bazel, doc/pydrake/BUILD.bazel, doc/styleguide/BUILD.bazel
There are no repository rules anymore that fail when `--with-doc-only` is absent (as of #14804), so it's always safe to compile our documentation tooling.
Note that building the tooling does not actually generate the output by default -- the tests are still tagged as manual.
Towards #14803.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14892)
=> doc: Remove manual tag from documentation binaries

tools/workspace/drake_visualizer/repository.bzl
Remove console spam, e.g., https://drake-jenkins.csail.mit.edu/view/Unprovisioned/job/linux-bionic-unprovisioned-clang-bazel-continuous-release/1810/consoleText.
Hotfix for #14884.
Towards #14362.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14908)
=> drake_visualizer: Silence deprecation warning

doc/_release-notes/template.txt
To avoid #14921 happening again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14922)
=> doc: Fix release notes template to unpin old version

systems/analysis/simulator.cc, systems/analysis/simulator.h, systems/analysis/test/simulator_limit_malloc_test.cc
This is the second of a long PR train to make heapless simulation
possible, with careful system construction. Inspired by @edrumwri's PR
This patch just moves some method-level heap use into longer-lived
object data; the data flows are the same, but storage gets reused over
successive AdvanceTo() steps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14912)
=> simulator: Remove allocations in AdvanceTo()

tools/dynamic_analysis/valgrind.supp
Closes #14932.
Addresses nightly build failures following PR #14894.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14933)
=> valgrind suppressions for system version of libclp

geometry/query_object.h
Update documentation of QueryObject::ComputeContactSurfaces() that Capsule is already supported.
It's a one-line documentation change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14935)
=> [geometry]Document QueryObject::ComputeContactSurfaces support Capsule.

multibody/parsing/package_map.cc
The spelling of a package path in the map isn't
standardized/normalized at all, so this can happen fairly easily
(e.g. if a trailing / is present or not).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14939)
=> Suppress PackageMap warning on different directory spellings

geometry/shape_specification.h
There were some semantics of the capsule parameters which were *not*
spelled out.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14941)
=> [doc] Extend capsule documentation

multibody/inverse_kinematics/position_constraint.cc
Presumably this version of the Jacobian  wasn't available when the constraint was first authored.  But this should only be better.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14945)
=> ik: use translational jacobian for position constraint

examples/scene_graph/simple_contact_surface_vis.cc, geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc, geometry/proximity/BUILD.bazel, geometry/proximity/mesh_field_linear.h, geometry/proximity/mesh_traits.h, geometry/proximity/surface_mesh.h, geometry/proximity/test/contact_surface_test.cc, geometry/proximity/test/mesh_field_linear_test.cc, geometry/proximity/test/mesh_intersection_test.cc, geometry/proximity/test/mesh_plane_intersection_test.cc, geometry/proximity/test/mesh_traits_test.cc, geometry/proximity/test/surface_mesh_test.cc, geometry/proximity/test/volume_mesh_test.cc, geometry/proximity/volume_mesh.h, geometry/query_results/contact_surface.h, multibody/plant/contact_results_to_lcm.cc, multibody/plant/hydroelastic_traction_calculator.cc, multibody/plant/hydroelastic_traction_calculator.h, multibody/plant/multibody_plant.cc, multibody/plant/test/hydroelastic_traction_test.cc, multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
The key principle is that a mesh (and related calculations) can get unique scalar types from various quantities:
- Position of vertices stored in the mesh.
- Barycentric coordinates as parameter to methods.
- Cartesian coordinates as parameter to methods.
In the current implementation they must all be the same. But that doesn't support flexible computation. For example, a `double`-valued mesh, posed with `AutoDiffXd`-valued transform should produce `AutoDiffXd`-valued results in the posed frame. This is the kind of functionality we need to support.
To this end:
1. Introduce the `mesh_traits.h` providing a compile-time utility for reconciling what the return type should be based on the various scalar types included in the calculation.
2. Reformulate the meshes so that the appropriate …
=> [geometry] Allow meshes and fields to handle mixed-scalar calculations

systems/analysis/test/simulator_limit_malloc_test.cc, systems/framework/diagram.cc, systems/framework/diagram.h
This is the third of a long PR train to make heapless simulation
This patch, like the last, just moves some method-level heap use into
longer-lived object data; the data flows are the same, but storage gets
reused over successive simulation steps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14929)
=> diagram: Refactor allocation for analyzing events by time

geometry/proximity/test/volume_mesh_test.cc
- The field value wasn't properly initialized for the autodiff-valued field (only the derivatives were initialized).
- Also removed spurious references to capture values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14955)
=> Hotfix: volume_mesh_test valgrind error

doc/BUILD.bazel, doc/_pages/documentation_instructions.md, doc/build.py, doc/doxygen_cxx/BUILD.bazel, doc/doxygen_cxx/build.py, doc/pages.py, doc/pydrake/BUILD.bazel, doc/pydrake/build.py, doc/styleguide/BUILD.bazel, doc/styleguide/build.py
Remove manual_binaries filegroup; it is no longer used by drake-ci.
Change regression tests to use submodules for quicker turn-around.
(This is the final step of #14803.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14954)
=> doc: Rewrite generation instructions and top-level build script

tools/workspace/tinyobjloader/faster_float_parsing.patch, tools/workspace/tinyobjloader/repository.bzl
Rewrite the faster_float_parsing patch to use a simple `#if` / `#endif` to disable upstream code instead of a deleting it, so the patch doesn't need to track upstream bugfixes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14958)
=> workspace: Upgrade tinyobjloader to latest commit

bindings/pydrake/geometry_py.cc, bindings/pydrake/perception_py.cc, bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/analysis_test.py, bindings/pydrake/systems/test/controllers_test.py, bindings/pydrake/systems/test/general_test.py, bindings/pydrake/test/geometry_test.py, bindings/pydrake/test/perception_test.py
Specifically, add `__repr__` for:
- pydrake.geometry.DrakeVisualizerParams
- pydrake.perception.Fields
- pydrake.systems.analysis.InitializeParams
- pydrake.systems.analysis.RegionOfAttractionOptions
- pydrake.systems.controllers.FiniteHorizonLinearQuadraticRegulatorOptions
- pydrake.systems.framework.UseDefaultName
Closes #13987.
I finally got fed up with commits like https://github.com/RobotLocomotion/RobotLocomotion.github.io/commit/8940aefddd1dfbe275fba1eaa9da2df5ee052367 being filled with spam, so I decided to break out some repr learning.
Using dataclasses or `__dict__` might be superior for frequently-changing types, but the boring thing seems sufficient for now.
--- …
=> pydrake: Add `__repr__` to several classes

systems/analysis/test/simulator_limit_malloc_test.cc
This is the fourth of a long PR train to make heapless simulation
This patch characterizes the heap allocations induced by all forms of
PublishEvents. It also improves naming and commentary.
Subsequent patches will reduce the measured heap usage from simulator
run-time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14950)
=> simulator_limit_malloc_test: Expand coverage of PublishEvents

multibody/tree/BUILD.bazel, multibody/tree/mobilizer_impl.cc, multibody/tree/space_xyz_floating_mobilizer.cc, multibody/tree/space_xyz_floating_mobilizer.h, multibody/tree/test/space_xyz_floating_mobilizer_test.cc
Towards #14949.
Mobilizer to model free bodies using rpy angles instead of quaternions. 
Joint + bindings and parsing will come in separate PRs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14961)
=> Implements SpaceXYZFloatingMobilizer

bindings/pydrake/geometry_py.cc, geometry/proximity/obj_to_surface_mesh.cc, geometry/proximity/obj_to_surface_mesh.h, geometry/proximity/test/obj_to_surface_mesh_test.cc
When reusing a visual mesh for collision purposes, we would get warning logspam while skipping the mtl files.  This was a regression as of #14656.
See also [slack discussion](https://app.slack.com/client/T0JNB2DS4/C2WBPQDB7/thread/C2WBPQDB7-1619718920.052300).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14974)
=> proximity: Don't warn when parsing meshes with mtl files

geometry/proximity/BUILD.bazel, geometry/proximity/mesh_half_space_intersection.cc, geometry/proximity/test/mesh_half_space_intersection_test.cc
This work is about 5% tweaking the implementation and 95% testing.
1. Modifications to the underlying algorithm
- making sure use of scalars is consistent.
- Guaranteeing that even with `T = AutoDiffXd`, BVH usage still works.
- deleting the "AutoDiff throws" implementation.
2. Modifications to unit tests
- Incidental renaming of test fixture to to `...ValueTest` to have a clearer relationship to the new test.
- Elimination of "Autodiff throws" unit test.
- Introduction of tests on the derivatives of various quantities:
- Area, vertex position, normal direction, pressure.
relates #14136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14943)
=> [geometry] Make soft half space/rigid mesh hydroelastic differentiable
