manipulation/util/geometry_inspector.py, manipulation/util/test/geometry_inspector_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12918)
=> Adds pyplot to geometry_inspector

bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/analysis_test.py, systems/analysis/explicit_euler_integrator.cc, systems/analysis/explicit_euler_integrator.h, systems/analysis/integrator_base.cc, systems/analysis/integrator_base.h, systems/analysis/runge_kutta2_integrator.cc, systems/analysis/runge_kutta2_integrator.h, systems/analysis/test/explicit_euler_integrator_test.cc, systems/analysis/test/runge_kutta2_integrator_test.cc
Completes #12904
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12922)
=> analysis: adds support for symbolic expression to integrators

systems/analysis/bogacki_shampine3_integrator.h, systems/analysis/explicit_euler_integrator.h, systems/analysis/implicit_euler_integrator.h, systems/analysis/integrator_base.h, systems/analysis/radau_integrator.h, systems/analysis/runge_kutta2_integrator.h, systems/analysis/runge_kutta3_integrator.h, systems/analysis/runge_kutta5_integrator.h, systems/analysis/semi_explicit_euler_integrator.h, systems/analysis/velocity_implicit_euler_integrator.h
It's an impressive list!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12900)
=> Add doxygen group for our suite of integrators

common/yaml/test/yaml_read_archive_test.cc, common/yaml/yaml_read_archive.cc, common/yaml/yaml_read_archive.h
See https://yaml.org/type/merge.html for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12924)
=> yaml: Add read support for merge keys

systems/framework/system_symbolic_inspector.h, systems/framework/test/system_symbolic_inspector_test.cc, systems/trajectory_optimization/direct_transcription.cc, systems/trajectory_optimization/direct_transcription.h
No functional changes to the `DirectTranscription` API, only the backend, so it's covered by the existing tests.
Next step will be to take the integrator as an argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12929)
=> Use symbolic integrator in direct transcription

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic_expression.cc, common/symbolic_expression.h, common/test/symbolic_expression_matrix_test.cc, solvers/create_constraint.cc, systems/framework/system_symbolic_inspector.cc, systems/trajectory_optimization/direct_transcription.cc
Close #12928
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12933)
=> Add and use symbolic::IsAffine

bindings/pydrake/systems/planar_scenegraph_visualizer.py, bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py
Throws file not found error if no obj exists (used to report "obj has no faces")
If the mesh is requested with a non-obj extension, check for an .obj with the same name in the same directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12917)
=> Find obj files in PlanarSceneGraphVisualizer

bindings/pydrake/examples/pendulum_py.cc, bindings/pydrake/examples/test/pendulum_test.py
@EricCousineau-TRI for feature review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12940)
=> pydrake examples: Bind missing functions for pendulum example

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/polynomial.h, common/test/polynomial_test.cc, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_test.cc
Methods to evaluate the derivatives at a point (with out have to make a new object that is the derivative of the original).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12951)
=> trajectories: add derivative methods to Polynomial, PiecewisePolynomial

bindings/pydrake/math_py.cc, bindings/pydrake/polynomial_py.cc, bindings/pydrake/polynomial_types_pybind.h, bindings/pydrake/symbolic_py.cc, common/polynomial.cc, common/polynomial.h, common/test/polynomial_test.cc, common/test/trig_poly_test.cc, common/trig_poly.h, geometry/proximity/test/hydroelastic_internal_test.cc, multibody/optimization/sliding_friction_complementarity_constraint.cc, solvers/constraint.cc, solvers/mixed_integer_rotation_constraint.cc, solvers/system_identification.cc, solvers/system_identification.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12946)
=> Move Polynomial and TrigPoly into drake namespace

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_generation_test.cc, common/trajectories/test/piecewise_polynomial_test.cc
This will be used in the integrators to build the "dense output".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12952)
=> trajectories: adds incremental construction of CubicHermite

systems/analysis/hermitian_dense_output.h, systems/analysis/test/hermitian_dense_output_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12957)
=> trajectories: construct HermitianDenseOutput from PiecewisePolynomial

geometry/render/gl_renderer/opengl_context.cc
When calling functions via glXGetProcAddressARB, give them a real symbol name so that dynamic analysis tools can report them in the call stack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12964)
=> gl_renderer: Refactor for better stack traces

multibody/tree/test/door_hinge_test.cc
DoorHinge test had some workarounds for missing MBPlant implementations of System energy and power methods. This PR removes those now that #12895 landed. I also renamed a few internal methods to avoid confusion with the similar System names, removed the last mention of MultibodyTree, and expanded the scalar conversion test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12955)
=> Use System energy and power methods to remove some DoorHinge test TODOs.

tools/jupyter/BUILD.bazel, tools/jupyter/jupyter_bazel.py, tools/jupyter/jupyter_py.bzl
Quick workaround / mitigation for #12536.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12958)
=> jupyter_py: Add workaround / notes for common ZMQError flake on CI

bindings/pydrake/systems/planar_scenegraph_visualizer.py, bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12961)
=> visualizer: add ConnectPlanarSceneGraphVisualizer

bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py
Closes #12969.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12970)
=> visualizer: hotfix for #12969

common/BUILD.bazel, common/polynomial.cc, common/polynomial.h, common/symbolic_expression.cc, common/symbolic_expression.h, common/symbolic_expression_cell.cc, common/symbolic_expression_cell.h, common/test/polynomial_test.cc, common/test/symbolic_expression_test.cc, solvers/create_cost.cc, systems/framework/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12950)
=> Make drake::symbolic::Expression::ToPolynomial => ::ToPolynomial

bindings/pydrake/math_py.cc, bindings/pydrake/systems/pyplot_visualizer.py, common/proto/call_python.h, math/rigid_transform.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12974)
=> Remove deprecated code 2020-04-01

common/BUILD.bazel, common/polynomial.cc, common/polynomial.h, common/test/polynomial_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12973)
=> common: support default scalars in drake::Polynomial

tools/workspace/buildifier/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12977)
=> workspace: Upgrade buildifier to latest release 2.2.1

tools/workspace/ghc_filesystem/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12979)
=> workspace: Upgrade ghc_filesystem to latest release 1.3.2

geometry/geometry_properties.h, geometry/proximity/mesh_field_linear.h, geometry/proximity_engine.h, geometry/query_object.h, geometry/render/render_engine.h, manipulation/perception/pose_smoother.h, math/continuous_lyapunov_equation.h, solvers/branch_and_bound.h, solvers/fast_qp.h, solvers/integer_inequality_solver.cc, solvers/sos_basis_generator.cc, systems/analysis/runge_kutta2_integrator.h, systems/framework/system.h
An [upcoming cpplint revision](https://github.com/jwnimmer-tri/styleguide/commits/c-style-80) will flag these violations automatically:
- line length
- ending in whitespace
- inconsistent alignment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12990)
=> Format C-style comments correctly

solvers/gurobi_solver.cc, solvers/solver_base.cc, solvers/test/gurobi_solver_test.cc, solvers/test/solver_base_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12995)
=> Check x_init size for all solvers.

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13005)
=> Add python binding for generic_costs and generic_constraints.

multibody/tree/linear_bushing_roll_pitch_yaw.cc, multibody/tree/linear_bushing_roll_pitch_yaw.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13001)
=> Move bushing code from .h file to .cc file

tools/workspace/meshcat/repository.bzl, tools/workspace/meshcat_python/repository.bzl
Upgrade meshcat and meshcat_python to latest commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12993)
=> workspace: Upgrade meshcat family to latest

common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_test.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13011)
=> trajectories:  Add tests and documentation on the behavior of PiecewisePolynomial<Expression>

systems/primitives/pass_through.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13023)
=> Fixed spelling

tools/workspace/pkg_config.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13019)
=> pkg-config: blacklist various macOS system include paths

bindings/pydrake/common/test/cpp_template_test.py, bindings/pydrake/systems/planar_scenegraph_visualizer.py
Commit cherry-picked from: #13027
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13035)
=> pydrake: Minor code fixes for preliminary Python 3.8 support

tools/workspace/pybind11/repository.bzl
Resolves #13026
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13027)
=> workspace: Update pybind11 fork to latest commit (Python 3.8)

bindings/pydrake/examples/rimless_wheel_py.cc, bindings/pydrake/examples/test/rimless_wheel_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13048)
=> rimless wheel: bind calc_alpha method

bindings/pydrake/solvers/mixed_integer_optimization_util_py.cc, bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py, solvers/mixed_integer_optimization_util.cc, solvers/mixed_integer_optimization_util.h, solvers/test/mixed_integer_optimization_util_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13043)
=> Logarithmic sos1

doc/index.rst, doc/installation.rst, doc/python_bindings.rst
This came about by talking with @IanTheEngineer about some ways to tinker with Drake without installing.
FYI @RussTedrake 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12971)
=> doc/installation: Add mention for previewing

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/analysis_test.py, tools/workspace/pybind11/repository.bzl
EDIT(eric): Resolves #13056
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13044)
=> integrators: add python bindings for dense integration

systems/analysis/integrator_base.h, systems/analysis/test_utilities/generic_integrator_test.h
(e.g. if you start your simulation from time = -2.0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13061)
=> integrators: integrators support negative times

common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13062)
=> trajectories: add reshape() to piecewise polynomial

common/trajectories/piecewise_polynomial.cc, common/trajectories/test/piecewise_polynomial_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13072)
=> Effectively reverts #4854, but leaves an updated version of the test

tools/workspace/drake_visualizer/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13081)
=> Rebuild drake-visualizer for macOS with Python 3.8 support

setup/mac/source_distribution/install_prereqs.sh
Relates #13071.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13098)
=> Force uninstall font-dejavu-sans

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13092)
=> multibody: add python binding for AddJointActuator

math/matrix_util.h, math/test/matrix_util_test.cc, systems/controllers/BUILD.bazel, systems/controllers/dynamic_programming.h, systems/controllers/finite_horizon_linear_quadratic_regulator.cc, systems/controllers/finite_horizon_linear_quadratic_regulator.h, systems/controllers/linear_quadratic_regulator.cc, systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
First version -- continuous-time only, Q and R are time-invariant.
Resolves #9013.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13078)
=> Adds finite horizon linear quadratic regulator

solvers/mathematical_program_doxygen.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13090)
=> Add naive branch-and-bound to solver matrix documentation.

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
Some bindings that I want/need for my project :) This is my first pr for bindings, so I'd appreciate any feedback
I didn't write an automatic test for `set_penetration_allowance` because there's didn't seem to be a good way to do that. I did test it manually and it seems to work. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13094)
=> Pybind plant bindings

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13100)
=> Add python binding for HasJointActuatorNamed

doc/release_notes/v0.17.0.rst
Amends #13020.
Relates #13097.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13107)
=> doc: Highlight v0.17.0's macOS warning

common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13109)
=> trajectories: add piecewisepolynomial unary minus

common/autodiffxd.h, common/test/autodiffxd_max_test.cc, common/test/autodiffxd_min_test.cc
Resolves #13082.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13112)
=> common: Add implementations of {min,max}(AutoDiffXd, AutoDiffXd)

common/autodiffxd.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13119)
=> common: Add Eigen issue link for {min,max}(AutoDiffXd, AutoDiffXd)

tools/workspace/dreal/repository.bzl
nlopt-2.6.2 introduces new enum value `NUM_RESULTS` and this version handles it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13133)
=> Use dReal-4.20.04.1

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/frame_kinematics_test.cc
Implements port for the pose of all bodies in the model, indexed by BodyIndex.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13137)
=> MBP port for body poses.

tutorials/README.md
Update developer notes section
This came about when speaking with @IanTheEngineer when discussing stuff about #13084.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13120)
=> tutorials: Explicitly refer to nbviewer for best browsing experience

tools/workspace/meshcat/repository.bzl
To get @gizatt's fix for the skydio parsing issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13141)
=> Update meshcat (only)

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/mosek_py.cc, bindings/pydrake/solvers/osqp_py.cc, bindings/pydrake/solvers/test/mosek_solver_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13151)
=> Add python binding for MosekSolverDetails

math/bspline_basis.cc, math/bspline_basis.h, math/test/bspline_basis_test.cc
Hotfix to avoid #13154.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13158)
=> math: Fix BsplineBasis<Expression>::operator==()

doc/issues.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13159)
=> doc: Begin to define issue components

multibody/tree/BUILD.bazel, multibody/tree/test/universal_mobilizer_test.cc, multibody/tree/universal_mobilizer.cc, multibody/tree/universal_mobilizer.h
Adds the mobilizer for a 2 dof Universal Joint.  Joint PR coming soon.
Towards #12404
cc @sherm1 @amcastro-tri
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13054)
=> multibody: Implement UniversalMobilizer

geometry/render/gl_renderer/BUILD.bazel, geometry/render/gl_renderer/dev/BUILD.bazel, geometry/render/gl_renderer/dev/buffer_dim.h, geometry/render/gl_renderer/dev/load_mesh.cc, geometry/render/gl_renderer/dev/load_mesh.h, geometry/render/gl_renderer/dev/opengl_geometry.h, geometry/render/gl_renderer/dev/render_engine_gl.cc, geometry/render/gl_renderer/dev/render_engine_gl.h, geometry/render/gl_renderer/dev/shader_program.cc, geometry/render/gl_renderer/dev/shader_program.h, geometry/render/gl_renderer/dev/test/render_engine_gl_test.cc
We're porting code from another source into Drake. This is "step 1" (slightly muddied because we'd started with an alternate strategy). This copies the code over into a dev folder with private settings. The second commit in the PR updates the references to acknowledge that they exist in the dev folder; it updates headers to reference /dev/ and puts everything in the dev namespace.
Otherwise, there is (more or less) no new code from how it was in the originating source.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13129)
=> Porting RenderEngineGl Step 1 - copy code to dev

lcmtypes/BUILD.bazel, lcmtypes/lcmt_panda_command.lcm, lcmtypes/lcmt_panda_status.lcm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13163)
=> Add lcmtypes for panda command/status

common/trajectories/test/bspline_trajectory_test.cc
Hotfix for #13149.
The compilation errors are shown at https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-mojave-clang-bazel-continuous-release/663/.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13167)
=> trajectories: Fix unit test compilation error on macOS

common/trajectories/BUILD.bazel, common/trajectories/discrete_time_trajectory.cc, common/trajectories/discrete_time_trajectory.h, common/trajectories/test/discrete_time_trajectory_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13157)
=> trajectories: add DiscreteTimeTrajectory

bindings/pydrake/common/__init__.py, bindings/pydrake/common/module_py.cc, bindings/pydrake/common/test/module_test.py, bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
Also makes checks stricter
Resolves #13181
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13183)
=> py mathematical_program: Add friendlier errors for user-functions

tools/workspace/ignition_math/repository.bzl, tools/workspace/sdformat/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13188)
=> workspace: Switch sdformat and ignition_math to GitHub

systems/analysis/simulator.h, systems/framework/system.cc, systems/framework/system.h, systems/framework/system_base.h, systems/framework/test/system_base_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13172)
=> systems: Remove deprecated code 2020-05

tools/lint/buildifier-tables.json, tools/workspace/README.md, tools/workspace/bitbucket.bzl, tools/workspace/github.bzl, tools/workspace/mirrors.bzl, tools/workspace/new_release.py
Follow-up from #13188.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13193)
=> workspace: Deprecate bitbucket.bzl

tools/workspace/buildifier/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13198)
=> workspace: Upgrade buildifier to latest release 3.0.0

common/text_logging.h, tools/workspace/fmt/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13200)
=> workspace: Upgrade fmt to latest release 6.2.0

tools/workspace/new_release.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13196)
=> tools: Improve new_release checking heuristics

tools/workspace/models/files.bzl, tools/workspace/models/package.BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13223)
=> models: Sort lists alphabetically for better maintainability

bindings/pydrake/common/test/wrap_pybind_test.py, bindings/pydrake/common/test/wrap_test_util_py.cc, bindings/pydrake/common/wrap_pybind.h, bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py, systems/controllers/BUILD.bazel, systems/controllers/finite_horizon_linear_quadratic_regulator.cc, systems/controllers/finite_horizon_linear_quadratic_regulator.h, systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13178)
=> controllers: Support for Finite-Horizon LQR result as a System

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13229)
=> multibody: add python binding for get_body_poses_output_port()

bindings/pydrake/BUILD.bazel, bindings/pydrake/attic/multibody/BUILD.bazel, bindings/pydrake/attic/multibody/rigid_body_tree_py.cc, bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/eigen_geometry_py.cc, bindings/pydrake/common/module_py.cc, bindings/pydrake/examples/BUILD.bazel, bindings/pydrake/examples/manipulation_station_py.cc, bindings/pydrake/geometry_py.cc, bindings/pydrake/lcm_py.cc, bindings/pydrake/math_py.cc, bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/lcm_py.cc, bindings/pydrake/systems/test/custom_test.py, bindings/pydrake/systems/trajectory_optimization_py.cc, bindings/pydrake/test/geometry_test.py
Most of these are 6+ months old.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13233)
=> pydrake: Remove old (undated) deprecations

setup/ubuntu/source_distribution/install_prereqs.sh
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13235)
=> setup: Install /usr/bin/python for Focal source builds

common/test/nice_type_name_test.cc
Came across this during #13194
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13239)
=> nice_type_name: Update test for anonymous namespaces

tutorials/mathematical_program.ipynb
Notebooks Preview: https://nbviewer.jupyter.org/github/hongkai-dai/drake/blob/mp_tutorial_visual_callback/tutorials/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13211)
=> Add tutorial on AddVisualizationCallback

examples/acrobot/BUILD.bazel, examples/acrobot/test/run_swing_up_traj_optimization.cc, systems/trajectory_optimization/direct_collocation.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13252)
=> examples: make Acrobot swing-up with trajectory optimization SNOPT only

doc/issues.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13254)
=> doc issues: component tag for geometry-related kitware issues

examples/acrobot/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13263)
=> Temporarily remove //examples/acrobot:run_swing_up_traj_optimization_test

CMakeLists.txt, cmake/modules/FindGurobi.cmake, doc/bazel.rst, doc/python_bindings.rst, solvers/gurobi_solver.cc, solvers/gurobi_solver.h, solvers/solver_options.h, solvers/test/gurobi_solver_test.cc, tools/bazel.rc, tools/dynamic_analysis/tsan.supp, tools/workspace/gurobi/package-macos.BUILD.bazel.in, tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in, tools/workspace/gurobi/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13049)
=> Update to gurobi9.

tools/workspace/fcl/repository.bzl
Fixes seg-fault for contact between convex and half space
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13274)
=> [geometry] Update FCL to latest commit

manipulation/util/test/meshlab_to_sdf_test.py, tools/lint/test/formatter_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13273)
=> Remove unittest deprecation warnings

doc/doxygen.h
Oops -- these slipped through in #13267.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13277)
=> Fix a couple of typos in accuracy/tolerance doc.

multibody/plant/multibody_plant.cc, multibody/plant/test/multibody_plant_test.cc
Resolves #13280
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13281)
=> mbp: Allow CollectRegisteredGeometries to be called pre-finalize

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
Towards some Anzu work
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13294)
=> py mbp: Bind set_stiction_tolerance, get_contact_penalty_method_time_scale

doc/issues.rst
Define four new github compopnent tags
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13290)
=> [doc] Add four new components that are all geometry related

doc/issues.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13305)
=> Add mathematicalprogram component to issues.rst

bindings/pydrake/test/autodiffutils_test.py
Resolves #13317
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13318)
=> autodiffutils_test: Use numpy version check for error message

lcm/BUILD.bazel, lcm/drake_lcm_interface.h, lcm/lcm_messages.cc, lcm/lcm_messages.h, lcm/test/lcm_messages_test.cc, manipulation/kinova_jaco/jaco_command_receiver.cc, manipulation/kinova_jaco/test/jaco_command_receiver_test.cc, manipulation/kuka_iiwa/iiwa_command_receiver.cc, manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc, manipulation/schunk_wsg/BUILD.bazel, manipulation/schunk_wsg/schunk_wsg_lcm.cc, manipulation/schunk_wsg/test/schunk_wsg_lcm_test.cc
Towards #9859
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13311)
=> manipulation: Check for whole default message, not just utime==0

common/test_utilities/drake_py_unittest_main.py, doc/python_bindings.rst
I keep on having to manually set `PYTHONUNBUFFERED` because I will lose stuff, because `sys.stdout = sys.stderr` is effectively useless in Python 3.
This explicitly updates the text to handle this case.
I would still very much prefer that this code remain standalone, as I don't to have people (myself included) have to trace Python code to use it in non-`pydrake` code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13238)
=> doc python: Update debugging tips

tools/workspace/ros_xacro/disable-console-print.patch, tools/workspace/ros_xacro/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13319)
=> tools: Remove stray xacro console output

setup/mac/binary_distribution/Brewfile, setup/mac/source_distribution/Brewfile, setup/mac/source_distribution/install_prereqs.sh, tools/lint/clang_format.py
Closes #13310. Relates #13284.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13323)
=> setup: use clang-format@9 and other cleanup

systems/analysis/integrator_base.h
This method is not used anywhere.
cc'ing @edrumwri
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12624)
=> Removes dead code; IntegratorBase::InitializeAccuracy().

multibody/plant/contact_model_doxygen.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13329)
=> doc: Fix typo in Contact Modeling section

manipulation/util/BUILD.bazel, manipulation/util/test/move_ik_demo_base_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13344)
=> Disable move_ik_demo_test case which causes timeouts

attic/multibody/rigid_body.cc, solvers/nlopt_solver.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13346)
=> Fix more GCC 8/9 warnings

bindings/pydrake/common/test/type_safe_index_pybind_test.cc, bindings/pydrake/common/type_safe_index_pybind.h, bindings/pydrake/geometry_py.cc, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, bindings/pydrake/test/geometry_test.py, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Also towards prototype mentioned here: https://github.com/RobotLocomotion/drake/issues/13177#issuecomment-629708238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13342)
=> py geom, mbp: Add GetDefaultFreeBodyPose, bind joint accessors, update type index wrappers

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/BUILD.bazel, geometry/scene_graph_inspector.cc, geometry/scene_graph_inspector.h, geometry/test/scene_graph_inspector_test.cc
Towards prototype mentioned here: https://github.com/RobotLocomotion/drake/issues/13177#issuecomment-629708238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13338)
=> geometry: Add SceneGraphInspector::CloneGeometryInstance

multibody/tree/linear_bushing_roll_pitch_yaw.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13106)
=> Guidance for picking bushing stiffness/damping constants

tools/workspace/yaml_cpp/package-macos.BUILD.bazel, tools/workspace/yaml_cpp/package-ubuntu-18.04.BUILD.bazel, tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel
Relates #13335. Tested locally on Mac (though I thought I tested #13335 too).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13353)
=> Add missing yaml-cpp headers

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py
Towards prototype mentioned here: #13177 (comment)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13352)
=> py geometry: Bind Mesh and Convex accessors

doc/python_bindings.rst
Follow-up to #13238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13356)
=> doc: Minor fix to Python debugging tips

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/geometry_instance.cc, geometry/geometry_instance.h, geometry/test/geometry_instance_test.cc
Towards prototype mentioned here: https://github.com/RobotLocomotion/drake/issues/13177#issuecomment-629708238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13351)
=> geometry: Add and bind GeometryInstance::set_name

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py
Towards prototype mentioned here: https://github.com/RobotLocomotion/drake/issues/13177#issuecomment-629708238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13361)
=> py geometry: Bind Shape.Clone()

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/general_test.py
- Diagram.GetSystems()
- InputPort.get_system()
- OutputPort.get_system()
For programmatic introspection in Python beyond graphviz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13363)
=> py systems: Bind system accessors

systems/framework/leaf_system.cc
Relates #13102. I think this is the last one for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13360)
=> Fix pessimizing-move warning in LeafSystem

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/test/multibody_tree_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13063)
=> Rename BiasForJacobian methods, new notation and documentation, plan expansion of CalcBiasSpatialAcceleration

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/osqp_solver_test.py, solvers/BUILD.bazel, solvers/mathematical_program_result.h, solvers/osqp_solver.cc, solvers/test/mathematical_program_result_test.cc, solvers/test/osqp_solver_test.cc, solvers/test/quadratic_program_examples.cc, solvers/test/quadratic_program_examples.h
This is the first step to address #13285 
cc @RussTedrake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13347)
=> Get dual solution for OSQP solver

tutorials/mathematical_program.ipynb, tutorials/update_constraint_cost.ipynb, tutorials/updating_costs_and_constraints.ipynb
Resolves #13249
EDIT(eric): Preview links:
* https://nbviewer.jupyter.org/github/hongkai-dai/drake/blob/mp_tutorial_update_constraint/tutorials/updating_costs_and_constraints.ipynb
* https://nbviewer.jupyter.org/github/hongkai-dai/drake/blob/mp_tutorial_update_constraint/tutorials/mathematical_program.ipynb#Advanced-tutorials
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13328)
=> Add a tutorial on updating costs/constraints in mathematical program.

examples/manipulation_station/end_effector_teleop_mouse.py, examples/manipulation_station/end_effector_teleop_sliders.py, examples/manipulation_station/joint_teleop.py, examples/manipulation_station/print_station_context.py
This makes all three demo teleop programs share a coding style, which will make it easier to start to de-duplicate their copied code and add tests.
(It's also un-pythonic to write main code outside of functions.)
First step towards adding tests that would have found #13340's issues.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13378)
=> manipulation_station: Put code into main() functions

bindings/pydrake/systems/test/general_test.py, systems/framework/test/basic_vector_test.cc, systems/framework/test/continuous_state_test.cc, systems/framework/vector_base.h
Resolves #12257.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13365)
=> systems: Use Eigen's formatting in VectorBase::operator<<() output

examples/manipulation_station/end_effector_teleop_sliders.py, examples/manipulation_station/joint_teleop.py
Current joint velocities reach 35 deg/s with no user input, so I've set the limit at 40.
Towards #13340.
I've not added a regression test to the mouse flavor, due to #13379.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13380)
=> manipulation_station: Add initialization regression tests

bindings/pydrake/symbolic_py.cc, common/test/symbolic_monomial_test.cc, examples/manipulation_station/manipulation_station.cc, geometry/proximity/mesh_half_space_intersection.cc, geometry/proximity/mesh_plane_intersection.cc, geometry/proximity/test/make_box_field_test.cc, geometry/proximity/test/make_cylinder_field_test.cc, geometry/proximity/test/make_ellipsoid_field_test.cc, geometry/proximity/test/make_sphere_field_test.cc, geometry/proximity/test/mesh_field_linear_test.cc, geometry/proximity/test/mesh_plane_intersection_test.cc, geometry/proximity_engine.cc, geometry/render/render_engine_vtk_base.cc, geometry/test/proximity_engine_test.cc, manipulation/planner/robot_plan_interpolator.cc, math/test/rotation_conversion_test.cc, multibody/tree/test/multibody_tree_test.cc, solvers/test/mathematical_program_test.cc, tools/workspace/ignition_math/package.BUILD.bazel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13357)
=> Fix range-loop-construct warnings

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/frame_kinematics_test.cc, multibody/plant/test/multibody_plant_reaction_forces_test.cc, multibody/plant/test/multibody_plant_test.cc
Reverts RobotLocomotion/drake#13364.
Dear @amcastro-tri,
The stand-in build cop (me) believes that your PR #13364 may have broken one or more of Drake's continuous integration builds [1]. It is possible to break a build even if your PR passed continuous integration pre-merge because additional platforms are tested post-merge.
- https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-nightly-undefined-behavior-sanitizer/
- https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-nightly-everything-undefined-behavior-sanitizer/
- https://drake-jenkins.csail.mit.edu/view/Production/job/linux-bionic-clang-bazel-weekly-gurobi-undefined-behavior-sanitizer/
- …
=> Revert "Spatial velocity and acceleration ports"

solvers/gurobi_solver.cc, solvers/test/gurobi_solver_test.cc, solvers/test/linear_program_examples.cc, solvers/test/linear_program_examples.h, solvers/test/osqp_solver_test.cc, solvers/test/quadratic_program_examples.cc, solvers/test/quadratic_program_examples.h
As part of the steps to #13285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13377)
=> Gurobi gets dual solution for QP and LP

solvers/test/linear_program_examples.cc
Fix the CI failure mentioned in #13403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13404)
=> Fix the CI failure for LPDualSolution1.

examples/manipulation_station/BUILD.bazel, examples/manipulation_station/end_effector_teleop_mouse.py, setup/ubuntu/source_distribution/packages-focal.txt, tools/workspace/default.bzl, tools/workspace/mirrors.bzl, tools/workspace/pygame_py/BUILD.bazel, tools/workspace/pygame_py/package-stub.BUILD.bazel, tools/workspace/pygame_py/repository.bzl, tools/workspace/pypi_wheel.bzl
Closes #13379.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13381)
=> workspace: Add dependency on pygame

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13415)
=> py mbp: Bind accessors for inertias

BUILD.bazel, common/yaml/BUILD.bazel, common/yaml/yaml_write_archive.cc, common/yaml/yaml_write_archive.h, third_party/com_github_jbeder_yaml_cpp/BUILD.bazel, third_party/com_github_jbeder_yaml_cpp/LICENSE, third_party/com_github_jbeder_yaml_cpp/include/yaml-cpp/emitfromevents.h, third_party/com_github_jbeder_yaml_cpp/src/emitfromevents.cpp, tools/install/libdrake/build_components.bzl, tools/workspace/yaml_cpp/package-ubuntu-20.04.BUILD.bazel
Relates #13102 and #13366.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13383)
=> Use EmitFromEvents from emitfromevents.{cpp,h} vendored from yaml-cpp

bindings/pydrake/_math_extra.py, bindings/pydrake/_symbolic_extra.py, bindings/pydrake/examples/_manipulation_station_extra.py, bindings/pydrake/solvers/_mathematicalprogram_extra.py, bindings/pydrake/systems/_lcm_extra.py, bindings/pydrake/test/_pydrake_pybind_test_extra.py
Towards #13408
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13420)
=> pydrake/*_extra.py: Ensure all files have consistent boilerplate comment

tools/workspace/mirrors.bzl, tools/workspace/new_release.py, tools/workspace/pypi_wheel.bzl
This is a follow-up from 2b70de6f5114f74dde94f387f3e6591d1f687cb2 (#13381).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13422)
=> workspace: Fix pypi_wheel support in release tooling

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13414)
=> py geometry: Bind HalfSpace.MakePose

tools/workspace/mirror_to_s3.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13424)
=> Improve robustness and diagnostic messages of S3 mirroring script

solvers/BUILD.bazel, solvers/equality_constrained_qp_solver.cc, solvers/test/equality_constrained_qp_solver_test.cc
As one step to #13285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13394)
=> Get dual solution for EqualityConstrainedQPSolver.

bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/analysis_test.py, bindings/pydrake/systems/test/custom_test.py, bindings/pydrake/systems/test/general_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13413)
=> py systems: Bind Simulator.set_monitor

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/_value_extra.py, bindings/pydrake/common/cpp_param.py, bindings/pydrake/common/cpp_param_pybind.h, bindings/pydrake/common/test/cpp_param_pybind_test.cc, bindings/pydrake/common/test/cpp_param_test.py, bindings/pydrake/common/test/value_test.py, bindings/pydrake/common/test/value_test_util_py.cc, bindings/pydrake/common/value_py.cc, bindings/pydrake/common/value_pybind.h, bindings/pydrake/common/wrap_pybind.h
Towards #13407 (PR)
Towards #13387 (issue)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13408)
=> py value: Allow binding Value<vector<T>> to Value[List[T]]

common/test/filesystem_test.cc, multibody/parsing/package_map.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13425)
=> std::filesystem-related fixes for Focal

tools/install/check_licenses.bzl, tools/install/install.bzl, tools/workspace/pycodestyle/repository.bzl
Fix new style nits that it now flags.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13430)
=> workspace: Upgrade pycodestyle to latest release 2.6.0

common/text_logging.h, tools/workspace/fmt/repository.bzl, tools/workspace/spdlog/repository.bzl
Upgrade fmt to latest release 6.2.1
Upgrade spdlog to latest release 1.6.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13431)
=> workspace: Upgrade fmt and spdlog to latest release

setup/ubuntu/source_distribution/packages-bionic.txt, setup/ubuntu/source_distribution/packages-focal.txt
Toward #13426. Relates #13102.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13432)
=> Add libclang-9-dev to prerequisites

common/test/value_test.cc, common/value.h
Split off from #13398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13444)
=> value: Disallow cv/ref/array/pointer types

bindings/pydrake/math_py.cc, bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/_plant_extra.py, bindings/pydrake/multibody/math_py.cc, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/math_test.py, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/test/math_test.py
Resolves #13387
Requires:
\cc @mntan3 @amcastro-tri 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13407)
=> py math, multibody: Bind Value[List[T]] for needed types

tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/BUILD.bazel, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/__init__.py, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/limit_clipping_range.py, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/use_builtin_scripts.py
Resolves #13446
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13447)
=> drake_visualizer: Prevent clipping volume from going to infinity

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/framework_py_values.cc, bindings/pydrake/systems/test/general_test.py, bindings/pydrake/systems/test/value_test.py
Towards #13395
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13454)
=> py systems: Make BasicVector use Pythonic string formatting

setup/ubuntu/source_distribution/packages-bionic.txt, setup/ubuntu/source_distribution/packages-focal.txt, tools/workspace/pybind11/libclang_setup.py
Closes #13426. Relates #13102.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13437)
=> mkdoc: switch to libclang-9-dev on Ubuntu

multibody/plant/images/test/scripts_test.py
Follow-up from oops: https://github.com/RobotLocomotion/drake/pull/13463#issuecomment-637023398
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13468)
=> mbp images: Use sys.executable for macOS

CMakeLists.txt, setup/BUILD.bazel, tools/workspace/README.md
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13469)
=> Support Focal in the CMake wrapper

geometry/BUILD.bazel, geometry/rgba.cc, geometry/rgba.h, geometry/test/rgba_test.cc
Towards #13442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13441)
=> geometry: Add basic Rgba class

bindings/pydrake/manipulation/BUILD.bazel, bindings/pydrake/manipulation/all.py, bindings/pydrake/manipulation/schunk_wsg_py.cc, bindings/pydrake/manipulation/test/schunk_wsg_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13470)
=> pydrake manipulation: Add bindings for schunk wsg systems

solvers/ipopt_solver.cc, solvers/test/ipopt_solver_test.cc, solvers/test/optimization_examples.cc, solvers/test/optimization_examples.h, solvers/test/quadratic_program_examples.cc
As a step to #13285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13402)
=> Get dual solution for IpoptSolver

bindings/pydrake/systems/meshcat_visualizer.py, tools/workspace/meshcat/README.md, tools/workspace/meshcat/repository.bzl, tools/workspace/meshcat_python/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13433)
=> workspace: Bump meshcat to latest commit

bindings/pydrake/multibody/math_py.cc, bindings/pydrake/multibody/test/math_test.py, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
Also adds bindings for SpatialMomentum.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13478)
=> pydrake multibody: Add bindings for SpatialInertia methods

common/test_utilities/drake_py_unittest_main.py, examples/multibody/strandbeest/README.md, geometry/render/gl_renderer/dev/shape_meshes.cc, multibody/tree/test/ball_rpy_joint_test.cc, multibody/tree/test/prismatic_joint_test.cc, multibody/tree/test/revolute_joint_test.cc, multibody/tree/universal_mobilizer.h
A first PR to exercise those Drake contributor muscles.
Other typos were ignored for various reasons: attic (why bother),
third-party (preserve comparisons), changelog (preserve history).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13479)
=> Repair typos.

geometry/BUILD.bazel, geometry/geometry_properties.h, geometry/test/geometry_properties_test.cc, multibody/parsing/test/detail_scene_graph_test.cc
Towards #13442 (WIP PR: #13443)
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13456)
=> geometry_properties: Store diffuse color using Rgba, not Vector4d

.editorconfig
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13483)
=> Fix .editorconfig for Markdown, Bazel, and Python

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py
Towards #13442
Requires:
~WIP of what it may look like. Currently incomplete~
~Alternative regarding discussion~ The correct solution from https://github.com/RobotLocomotion/drake/pull/13398#pullrequestreview-420579995
\cc @SeanCurtis-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13443)
=> py geometry: Bind Rgba, test with GeometryProperties

common/yaml/BUILD.bazel
This yields notably faster rebuilds within this directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13497)
=> yaml: Narrow unit test deps to avoid symbolic

lcmtypes/BUILD.bazel, tools/workspace/buildifier/repository.bzl, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13484)
=> workspace: Update buildifier to latest release 3.2.0

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, examples/planar_gripper/gripper_brick.cc, examples/planar_gripper/gripper_brick_planning_constraint_helper.cc, examples/planar_gripper/test/gripper_brick_planning_constraint_helper_test.cc, multibody/optimization/sliding_friction_complementarity_constraint.cc, multibody/optimization/static_friction_cone_complementarity_constraint.cc, multibody/optimization/static_friction_cone_constraint.cc, multibody/optimization/test/sliding_friction_complementarity_constraint_test.cc, multibody/parsing/test/common_parser_test.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Part of #13064 and #13289.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13371)
=> Remove default_coulomb_friction from MBP

.binder/README.md
I derp'd while trying out this PR: https://github.com/RobotLocomotion/drake/pull/13498#issuecomment-639177227
I think this helps minimize PEBKAC
\cc @BetsyMcPhail
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13504)
=> binder: Update README to mention `docker pull`

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf
With the new ball and universal joints, this allows those joints to be parsed from an sdf file
Assign @sherm1 for triage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13427)
=> Ball and universal joint sdf parser

bindings/pydrake/solvers/test/gurobi_solver_test.py, solvers/gurobi_solver.cc, solvers/mathematical_program_result.h, solvers/test/gurobi_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13490)
=> add dual solution for Gurobi QCP.

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py, tutorials/rendering_multibody_plant.ipynb
Relates to #12645.  This is our current best solution given the discussion with @rdeits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13513)
=> Add meshcat animation (and binder tutorial)

multibody/plant/test/multibody_plant_jacobians_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13406)
=> Simple planar two degree-of-freedom test for CalcBiasAcceleration().

multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf, multibody/parsing/test/urdf_parser_test/joint_parsing_test_tag_mismatch_1.urdf, multibody/parsing/test/urdf_parser_test/joint_parsing_test_tag_mismatch_2.urdf
Also made parsing tests more complete
Co-authored-by: Michelle Tan <mtan123456789@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13516)
=> parsing: Added ball and universal joints to urdf parser

bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/analysis_test.py
Towards debugging in #13505
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13525)
=> py analysis: Bind Simulator.get_system

solvers/snopt_solver.cc, solvers/test/ipopt_solver_test.cc, solvers/test/linear_program_examples.cc, solvers/test/linear_program_examples.h, solvers/test/snopt_solver_test.cc
As mentioned in #13285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13511)
=> Retrieve dual solutions for SnoptSolver.

examples/acrobot/dev/BUILD.bazel
Hotfix for #13375.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13538)
=> acrobot/dev: Temporarily disable failing unit test

setup/mac/source_distribution/requirements.txt
A temporary workaround for #13529.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13535)
=> Pin Sphinx to versions below 3.1 on macOS

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/sdpa_free_format_py.cc, bindings/pydrake/solvers/test/sdpa_free_format_test.py
As discussed on slack https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1591892432083000?thread_ts=1591883812.079900&cid=C3L92BM2Q
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13546)
=> Add python binding for GenerateSDPA

common/yaml/test/yaml_read_archive_test.cc, common/yaml/yaml_read_archive.cc, common/yaml/yaml_read_archive.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13532)
=> yaml: Add configurable policies for missing items

doc/developers.rst, doc/docker.rst, doc/from_binary.rst, doc/jenkins.rst, doc/python_bindings.rst
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13553)
=> Add more mentions of Focal to the documentation

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/test/geometry_test.py
Also adds tests for a few untested bindings.  Helps with #13162 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13559)
=> pydrake geometry: Add bindings for SceneGraphInspector and Shapes

bindings/pydrake/examples/acrobot_py.cc, bindings/pydrake/examples/test/acrobot_test.py, examples/acrobot/acrobot_plant.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13556)
=> pydrake examples: Add bindings for AcrobotPlant

lcmtypes/BUILD.bazel, lcmtypes/lcmt_planar_gripper_finger_face_assignment.lcm, lcmtypes/lcmt_planar_gripper_finger_face_assignments.lcm, lcmtypes/lcmt_planar_plant_state.lcm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13554)
=> Adds additional lcm message types for the planar gripper example.

tools/workspace/sphinx/repository.bzl
Closes #13551.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13575)
=> Prefer Python 3 sphinx-build on Ubuntu

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13577)
=> Add python binding for MPResult.set_x_val

doc/developers.rst
Relates #13514.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13592)
=> Add a note about arm64 support

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
Requesting review from @EricCousineau-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13594)
=> Added binding for MBP.CalcCenterOfMassPosition

common/yaml/test/yaml_read_archive_test.cc, common/yaml/yaml_read_archive.cc, common/yaml/yaml_read_archive.h
Builds atop #13589.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13590)
=> yaml: Add retain_map_defaults to YamlReadArchive::Options

systems/sensors/BUILD.bazel, systems/sensors/accelerometer.cc, systems/sensors/accelerometer.h, systems/sensors/accelerometer_sensor.h, systems/sensors/test/accelerometer_test.cc
Adds an accelerometer sensor and unit test. 
Still needs a second unit test where the accelerometer is rotated w.r.t. the world.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13501)
=> Add accelerometer sensor

manipulation/util/BUILD.bazel, manipulation/util/bot_core_lcm_encode_decode.h
Toward #9865.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13596)
=> manipulation/util: Deprecate bot_core_encode_decode

bindings/pydrake/BUILD.bazel, bindings/pydrake/math_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/systems/perception.py, bindings/pydrake/systems/test/perception_test.py, bindings/pydrake/test/math_test.py, examples/pendulum/test/pendulum_geometry_test.cc, manipulation/planner/test/differential_inverse_kinematics_test.cc, math/rigid_transform.h, math/test/rigid_transform_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_tinyxml_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/plant/test/multibody_plant_test.cc, systems/controllers/test/setpoint_test.cc, systems/rendering/test/pose_aggregator_test.cc, systems/rendering/test/pose_vector_test.cc, systems/rendering/test/render_pose_to_geometry_pose_test.cc, systems/sensors/optitrack_sender.cc, systems/sensors/test/optitrack_sender_test.cc, systems/sensors/test/rgbd_sensor_test.cc
Towards #9865.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13595)
=> Deprecate RigidTransform/Isometry3 automatic conversion

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic_monomial_util.cc, common/symbolic_monomial_util.h, common/test/symbolic_monomial_test.cc
This is the first step to address #13601
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13605)
=> Create even or odd degree monomial basis

bindings/pydrake/trajectories_py.cc, common/polynomial.h, common/symbolic_expression.h, common/test/polynomial_test.cc, common/test/symbolic_expression_test.cc, common/test/trig_poly_test.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/piecewise_quaternion.h, common/trig_poly.h, systems/analysis/antiderivative_function.h, systems/analysis/initial_value_problem.h, systems/analysis/scalar_initial_value_problem.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13610)
=> trajectories: Remove deprecated methods 2020-07-01

examples/kuka_iiwa_arm/BUILD.bazel, examples/kuka_iiwa_arm/iiwa_common.cc, examples/kuka_iiwa_arm/iiwa_common.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13612)
=> examples: Remove deprecated methods 2020-07-01

tools/workspace/buildifier/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13620)
=> workspace: Update buildifier to latest release 3.3.0

tools/workspace/googlebenchmark/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13623)
=> workspace: Upgrade googlebenchmark to latest release

tools/workspace/fcl/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13621)
=> workspace: Upgrade fcl to latest commit

systems/sensors/BUILD.bazel, systems/sensors/accelerometer.cc, systems/sensors/accelerometer_sensor.h, systems/sensors/gyroscope.cc, systems/sensors/gyroscope_sensor.h, systems/sensors/test/accelerometer_test.cc, systems/sensors/test/gyroscope_test.cc
Adds a gyroscope sensor, and fixes minor typos in accelerometer from #13501 .
Request review from @amcastro-tri
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13604)
=> Add gyroscope sensor

tools/workspace/nlopt/package-macos.BUILD.bazel, tools/workspace/nlopt/package-ubuntu-18.04.BUILD.bazel, tools/workspace/nlopt/package-ubuntu-20.04.BUILD.bazel, tools/workspace/nlopt/repository.bzl
Toward #13606.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13633)
=> Link to nlopt_cxx on Focal and do not use pkg-config

bindings/pydrake/solvers/sdpa_free_format_py.cc, bindings/pydrake/solvers/test/sdpa_free_format_test.py, solvers/sdpa_free_format.cc, solvers/sdpa_free_format.h, solvers/test/sdpa_free_format_test.cc
This is one step in #13599, now GenerateSDPA function can work with `MathematicalProgram` with free variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13636)
=> GenerateSDPA supports removing free variables.

multibody/plant/multibody_plant.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13652)
=> Remove old TODO comments as CalcBiasAcceleration issues were addressed.

common/type_safe_index.h, geometry/proximity/distance_to_shape_callback.h, multibody/parsing/detail_scene_graph.h, multibody/parsing/detail_urdf_geometry.h, multibody/plant/test/multibody_plant_test.cc
Improve wording in TypeSafeIndex comments and a few other places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13658)
=> Tidy up documentation for TypeSafeIndex

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/general_test.py, examples/manipulation_station/manipulation_station.h, systems/framework/BUILD.bazel, systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/system.h, systems/framework/system_html.cc, systems/framework/system_html.h, systems/framework/test/system_html_test.cc, tutorials/dynamical_systems.ipynb
Also updates the example in tutorials/dynamical_system.ipynb
We should definitely make this much prettier, but this shows what's possible and is already better than graphviz for navigating large diagrams
Here is an example rendering of the manipulation station:
http://people.csail.mit.edu/russt/uploads/manip_station.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13644)
=> implement javascript system diagram visualization

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, common/symbolic_monomial_util.h, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/sos_constraint_test.cc
As mentioned in #13601
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13637)
=> MathematicalProgram add even and odd polynomial

setup/mac/binary_distribution/Brewfile, tools/install/install_test_helper.py
Closes #13661.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13668)
=> Remove TODOs related to python@3.8 formula

common/text_logging.h, tools/workspace/fmt/repository.bzl, tools/workspace/spdlog/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13667)
=> workspace: Upgrade spdlog and fmt

CMakeLists.txt, doc/bazel.rst, doc/developers.rst, setup/ubuntu/source_distribution/packages-bionic.txt, setup/ubuntu/source_distribution/packages-focal.txt, tools/dynamic_analysis/asan.sh, tools/dynamic_analysis/bazel.rc, tools/dynamic_analysis/drd.sh, tools/dynamic_analysis/helgrind.sh, tools/dynamic_analysis/lsan.sh, tools/dynamic_analysis/tsan.sh, tools/dynamic_analysis/ubsan.sh, tools/dynamic_analysis/valgrind.sh, tools/workspace/cc/repository.bzl
Relates #13434.  Needs an update to the configuration in drake-ci.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13650)
=> Upgrade to Clang 9 on Bionic

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
As mentioned in #13601 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13641)
=> MathematicalProgram adds NewEvenDegreeNonnegativePolynomial

doc/developers.rst
Per platform reviewer's meeting 2020/07/01.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13677)
=> Join list of platform reviewers

bindings/pydrake/solvers/sdpa_free_format_py.cc, solvers/csdp_solver.cc, solvers/sdpa_free_format.cc, solvers/sdpa_free_format.h, solvers/test/csdp_solver_internal_test.cc, solvers/test/csdp_solver_test.cc, solvers/test/csdp_test_examples.cc, solvers/test/csdp_test_examples.h, solvers/test/sdpa_free_format_test.cc
Resolves #13599
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13669)
=> SdpaFreeFormat can remove free variable by using a slack variable and a Lorentz cone constraint

solvers/test/csdp_solver_test.cc
Resolves #13684
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13685)
=> Fix CI failure on csdp_solver_test.

solvers/csdp_solver.cc, solvers/sdpa_free_format.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13687)
=> CsdpSolver only warn once.

geometry/render/gl_renderer/BUILD.bazel, setup/ubuntu/binary_distribution/packages-bionic.txt, setup/ubuntu/binary_distribution/packages-focal.txt, setup/ubuntu/source_distribution/packages-bionic.txt, setup/ubuntu/source_distribution/packages-focal.txt, tools/workspace/default.bzl, tools/workspace/drake_visualizer/repository.bzl, tools/workspace/glx/BUILD.bazel, tools/workspace/glx/package-macos.BUILD.bazel, tools/workspace/glx/package-ubuntu.BUILD.bazel, tools/workspace/glx/repository.bzl, tools/workspace/opengl/package-macos.BUILD.bazel, tools/workspace/opengl/package-ubuntu.BUILD.bazel, tools/workspace/vtk/Dockerfile, tools/workspace/vtk/repository.bzl
Closes #13606.
---
We need either `libOpenGL.so`, `libOpenGL.so.0`, `libGLX.so`, `libGLX.0`, `GL/gl.h`, and
`GL/glx.h` (modern, vendor neutral) or `libGL.so`, `libGL.so.1`, `GL/gl.h`, and `GL/glx.h`
(legacy). Vendor neutral is preferable, for NVIDIA users and others, so we choose `libOpenGL.so` and `libGLX.so`
rather than `libGL.so`.
Also rebuild VTK and drake-visualizer to ensure they are correctly linked to
`libOpenGL.so` and `libGLX.so` rather than `libGL.so`.
**Ubuntu 18.04 (Bionic)**
*package contents:*
| package           | libraries                                            | headers               | pkg-config  |
|-------------------|------------------------------------------------------|-----------------------|-------------|
| libgl1-mesa-dev   | …
=> Fix and/or cleanup OpenGL dependencies

manipulation/models/wsg_50_description/README.md
As discussed in #13690.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13693)
=> wsg_50_description: Deprecate the URDF and meshes

bindings/pydrake/pydrake_doxygen.h
Towards #12055
Was motivated by discussion w/ @BenBurchfiel-TRI about correspondence to (slowly) start this work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13555)
=> pydrake doc: Elaborate on how to discover C++ Python bindings

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13703)
=> Add python binding for AddLinearEqualityConstraint overload.

doc/release_notes/v0.20.0.rst
Relates #13705.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13721)
=> doc: Add v0.20.0 warning about GoJS

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
Fixes freshly introduced bug in #13696.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13712)
=> Fixes sub-stepping update of fn0.

bindings/pydrake/__init__.py, bindings/pydrake/test/rtld_global_warning_test.py
Resolves #13707 
See this comment for investigation / conclusion: https://github.com/RobotLocomotion/drake/issues/13707#issuecomment-660552196
FYI @kunimatsu-tri @siyuanfeng-tri 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13708)
=> pydrake: Relax RTLD_GLOBAL warning for torch>=1.5.0

systems/controllers/inverse_dynamics.cc, systems/controllers/inverse_dynamics.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13706)
=> Makes inverse dynamics system const

bindings/pydrake/pydrake_doxygen.h, bindings/pydrake/pydrake_pybind.h
Follow-up from #13716
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13727)
=> pydrake doc: Simplify cross-references and symbol discovery for pydrake

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/scene_graph.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13731)
=> py geometry: Bind overload of SceneGraph.RemoveRole

tools/workspace/pybind11/test/mkdoc_comment_test.py
Follow-up to #13651
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13740)
=> Reformat text in mkdoc comment text

solvers/BUILD.bazel, solvers/test/csdp_solver_test.cc, solvers/test/mosek_solver_test.cc, solvers/test/scs_solver_test.cc, solvers/test/sos_examples.cc, solvers/test/sos_examples.h
Test sum-of-squares programming with CSDP, Mosek and SCS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13719)
=> Add examples on sum-of-squares.

tools/workspace/spdlog/package-create-cps.py, tools/workspace/spdlog/package.BUILD.bazel
Closes #12393.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13698)
=> Rename libspdlog.so to libdrake_spdlog.so

common/BUILD.bazel, common/symbolic.h, common/symbolic_chebyshev_polynomial.cc, common/symbolic_chebyshev_polynomial.h, common/test/symbolic_chebyshev_polynomial_test.cc
This only implements a univariate Chebyshev polynomial.
This is the first step to #13602
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13751)
=> add symbolic ChebyshevPolynomial.

solvers/test/csdp_solver_test.cc, solvers/test/mosek_solver_test.cc, solvers/test/scs_solver_test.cc, solvers/test/sos_examples.cc, solvers/test/sos_examples.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13746)
=> Add two more examples on SOS optimization.

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/BUILD.bazel, solvers/mathematical_program_result.cc, solvers/mathematical_program_result.h, solvers/test/mathematical_program_result_test.cc, solvers/test/sos_examples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13748)
=> MPResult::GetSolution also works for a polynomial.

doc/developers.rst, setup/ubuntu/source_distribution/install_prereqs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13743)
=> setup: Update recommended Bazel version to 3.4

attic/multibody/approximate_ik.cc, attic/multibody/global_inverse_kinematics.h, attic/multibody/ik_options.h, attic/multibody/rigid_body.h, attic/multibody/rigid_body_ik.h, common/trajectories/discrete_time_trajectory.h, examples/scene_graph/solar_system.h, geometry/geometry_roles.h, geometry/proximity/contact_surface_utility.h, geometry/query_object.h, math/autodiff_gradient.h, multibody/parsing/detail_scene_graph.h, multibody/plant/propeller.h, multibody/plant/tamsi_solver.h, multibody/tree/multibody_tree.h, multibody/tree/multibody_tree_system.h, solvers/test_utilities/check_constraint_eval_nonsymbolic.h, systems/analysis/implicit_euler_integrator.h, systems/analysis/integrator_base.h, systems/analysis/velocity_implicit_euler_integrator.h, systems/framework/system_html.h
Remove commented-out attic code that defeats the new cpplint.
These problems were highlighted by forthcoming changes to cpplint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13762)
=> Fix line length and whitespace nits throughout

solvers/test/mosek_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13765)
=> Relax the tolerance on the Motzkin example for mosek test.

tools/workspace/sdformat/BUILD.bazel, tools/workspace/sdformat/ign_sdf_main.cc, tools/workspace/sdformat/package.BUILD.bazel, tools/workspace/sdformat/test/ign_sdf_test.py
Relates #13758
It's not perfect, but I think it's good to at least capture the current setup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13767)
=> sdformat: Add simple interface to `ign sdf` tool

tools/install/colab/BUILD.bazel, tools/install/colab/README.md, tools/install/colab/setup_drake_colab.py
Towards #13683
Add setup script to provision colab notebooks
Add provisioning preamble to dynamical_systems.ipynb
Update Readme
(Once we are happy with the setup/preamble, I will follow-up with the other tutorials).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13697)
=> Add support in one tutorial for Google Colab

tools/workspace/models/repository.bzl
Closes #13663.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13786)
=> workspace: Upgrade models to latest commit

common/text_logging.h, tools/workspace/fmt/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13788)
=> workspace: Upgrade fmt to latest release 7.0.2

tools/workspace/scs/package.BUILD.bazel, tools/workspace/scs/private.c.diff, tools/workspace/scs/private.h.diff, tools/workspace/scs/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13789)
=> workspace: Upgrade scs to latest release 2.1.2

tools/workspace/ros_xacro/package.BUILD.bazel, tools/workspace/ros_xacro/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13790)
=> workspace: Upgrade ros_xacro to latest release 1.13.6

tools/workspace/buildifier/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13791)
=> workspace: Upgrade buildifier to latest release 3.4.0

multibody/plant/multibody_plant.cc
Resolves #13775
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13802)
=> Fix format in TAMSIs exception message

tools/install/colab/setup_drake_colab.py
as discussed in https://colab.research.google.com/drive/1c4A_Pvk_sLeLx0DpV0ak8dIaP2xT-ZO1#scrollTo=mfq5HDd_Ig3u
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13795)
=> setup_drake_colab avoids reinstall if version info is unchanged.

doc/code_style_guide.rst, tools/workspace/styleguide/repository.bzl
Realized I hadn't updated this when reviewing #12218.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12236)
=> doc: Update code style guide for Python 3 and docstrings

bindings/pydrake/multibody/test/plant_test.py
Resolves #13816
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13817)
=> py tree: Improve testing for random distributions and accessors

multibody/parsing/detail_common.cc, multibody/parsing/detail_common.h, multibody/parsing/detail_path_utils.cc, multibody/parsing/detail_path_utils.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_sdf_parser.h, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/detail_urdf_parser.h, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/test/detail_path_utils_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/parser_test.cc
Closes #12754.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13814)
=> parsing: Add support for parsing SDF and URDF from strings

solvers/choose_best_solver.cc, solvers/choose_best_solver.h, solvers/test/choose_best_solver_test.cc
This will help prune Anzu's `GetSolverIdFromName` function down to size.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13821)
=> solvers: Add GetKnownSolvers

common/schema/dev/BUILD.bazel, common/schema/dev/rotation.cc, common/schema/dev/rotation.h, common/schema/dev/test/rotation_test.cc, common/schema/dev/test/transform_test.cc, common/schema/dev/transform.cc, common/schema/dev/transform.h
Relates #13251.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13823)
=> schema: Copy rotation,transform from Anzu

setup/BUILD.bazel
I typo'd this in 04e15ce3a4607917b2cc05592eb0c00116b91fe3 (#13827).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13830)
=> setup: Really export the package list text files

tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/BUILD.bazel, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/__init__.py, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/grid_wireframe.py, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/use_builtin_scripts.py
Fixes weird round-off issues for wireframes
Resolves #13828
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13829)
=> drake_visualizer: Add grid_wireframe for --use_builtin_scripts

common/symbolic_expression.h, common/symbolic_formula.h
Related: #12923
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/12938)
=> Clarify documentation of symbolic::isnan

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13848)
=> Pass kwargs through MeshcatVisualizer to meshcat.Visualizer

doc/clion.rst
Resolves #13815.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13840)
=> CLion doc: Add section on debugging arbitrary programs

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf, multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf
Follow up to #13747. Adds parsing for Planar Joint.
Relates #12404
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13824)
=> multibody: Add parsing for PlanarJoint

common/symbolic_chebyshev_basis_element.cc, common/symbolic_chebyshev_basis_element.h, common/symbolic_polynomial_basis_element.cc, common/symbolic_polynomial_basis_element.h, common/test/symbolic_chebyshev_basis_element_test.cc, common/test/symbolic_polynomial_basis_element_test.cc
Also allow using ChebyshevBasisElement as scalar type in Eigen matrix, and add Differentiation and Integration to ChebyshevBasisElement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13845)
=> Add ToExpression to ChebyshevBasisElement. 

common/BUILD.bazel, common/symbolic_chebyshev_basis_element.cc, common/symbolic_chebyshev_basis_element.h, common/symbolic_polynomial_basis_element.cc, common/symbolic_polynomial_basis_element.h, common/test/symbolic_chebyshev_basis_element_test.cc, common/test/symbolic_polynomial_basis_element_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13856)
=> Add more constructors and EvaluatePartial to ChebyshevBasisElement.

systems/sensors/image_writer.cc, systems/sensors/image_writer.h, systems/sensors/test/image_writer_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13871)
=> add depth16u and grey8u to image writer.

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/jupyter_widgets.py, bindings/pydrake/systems/test/general_test.py
and use it in the jupyter widget system.
=> bind `LeafOutputPort::disable_caching_by_default`

bindings/pydrake/examples/pendulum_py.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/rendering_py.cc, bindings/pydrake/systems/test/general_test.py, systems/framework/system.h, systems/framework/test/system_test.cc
Just a spoonful of sugar...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13883)
=> Provide System::get_input_port() and get_output_port()

bindings/pydrake/manipulation/schunk_wsg_py.cc, bindings/pydrake/manipulation/test/schunk_wsg_test.py, examples/manipulation_station/manipulation_station.h, examples/manipulation_station/manipulation_station_hardware_interface.h, manipulation/schunk_wsg/schunk_wsg_lcm.cc, manipulation/schunk_wsg/schunk_wsg_lcm.h, manipulation/schunk_wsg/schunk_wsg_position_controller.cc, manipulation/schunk_wsg/schunk_wsg_position_controller.h, manipulation/schunk_wsg/test/schunk_wsg_lcm_test.cc, manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13878)
=> Make force limit input port for Schunk WSG optional

bindings/pydrake/manipulation/simple_ui.py, bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/jupyter_widgets.py, bindings/pydrake/multibody/jupyter_widgets_examples.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13884)
=> Add jupyter widget version of JointSliders

manipulation/planner/differential_inverse_kinematics.h
Per conversation with @takuya-ikeda-tri
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13892)
=> differential_inverse_kinematics: Fix docstring formatting

bindings/pydrake/systems/jupyter_widgets.py, bindings/pydrake/systems/jupyter_widgets_examples.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13882)
=> Widget system

bindings/pydrake/manipulation/planner_py.cc, bindings/pydrake/manipulation/test/planner_test.py, manipulation/planner/BUILD.bazel, manipulation/planner/differential_inverse_kinematics_integrator.cc, manipulation/planner/differential_inverse_kinematics_integrator.h, manipulation/planner/test/differential_inverse_kinematics_integrator_test.cc
Cleaner version of the python LeafSystem DifferentialIK from the manipulation_station folder, now in c++.
Resolves #11581
Will send a follow-up PR to convert the manipulation station to this version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13877)
=> Adds DifferentialInverseKinematicsIntegrator

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py
Per quick f2f with @takuya-ikeda-tri (just for prototyping purposes)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13893)
=> geometry: Bind RenderEngineOspray factory

solvers/ipopt_solver.cc
Inspired by #13841.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13891)
=> Change IPOPT eval_g to use double version of constraint evaluation.

examples/multibody/cassie_benchmark/BUILD.bazel, examples/multibody/cassie_benchmark/record_results.sh, tools/workspace/cc/BUILD.bazel
Closes #13905.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13909)
=> cassie_bench: Record compiler name and version

examples/allegro_hand/BUILD.bazel, examples/bead_on_a_wire/BUILD.bazel, examples/bouncing_ball/BUILD.bazel, examples/fibonacci/BUILD.bazel, examples/kuka_iiwa_arm/BUILD.bazel, examples/rod2d/BUILD.bazel, multibody/benchmarks/free_body/BUILD.bazel
If the only thing we need from analysis is the simulator, then depend on only that much (not the whole package).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13912)
=> examples: Stop depending on region of attraction, etc.

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc
Towards #13903.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13908)
=> multibody: Support parsing massless bodies

systems/trajectory_optimization/sequential_expression_manager.cc, systems/trajectory_optimization/sequential_expression_manager.h, systems/trajectory_optimization/test/sequential_expression_manager_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13925)
=> Add SequentialExpressionManager::GetSequentialExpressionNames

examples/multibody/cassie_benchmark/README.md, examples/multibody/cassie_benchmark/conduct_experiment
Relevant to #13902.
Add a script to run controlled experiments, and refuse to run on unsupported
configurations. Update documentation to describe the new capability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13917)
=> cassie_bench: More support for experiments

multibody/parsing/test/detail_urdf_parser_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13927)
=> Fix a mac build error introduced in #13908

common/test_utilities/test/limit_malloc_test.cc
Hotfix for #13930.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13935)
=> Fix limit_malloc_test on valgrind

common/schema/dev/rotation.h, common/schema/dev/stochastic.h, common/schema/dev/transform.h
Toward #13251.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13937)
=> schema: Add Doxygen for stochastic, rotation, translation

common/schema/BUILD.bazel, common/schema/dev/BUILD.bazel, common/schema/dev/rotation.h, common/schema/dev/transform.h, common/schema/stochastic.cc, common/schema/stochastic.h, common/schema/test/stochastic_test.cc, examples/acrobot/dev/BUILD.bazel, examples/acrobot/dev/spong_sim.cc, tools/install/libdrake/build_components.bzl
Note that as a "move files out of dev" PR, this _only_ needs platform review, but the reviewer _must_ review all the files as if they were newly written.  So the PR is not only 56 lines of changes, but rather more like 1,000 lines.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13943)
=> schema: Move stochastic out of dev

examples/multibody/cassie_benchmark/test/cassie_bench.cc, multibody/plant/BUILD.bazel, multibody/plant/test/atlas_with_fixed_joints.urdf, multibody/plant/test/multibody_plant_mass_matrix_test.cc, multibody/tree/multibody_tree.cc
This repairs the broken optimization I introduced in #13933 and adds two unit tests that fail with the bug in place and succeed now.
Thanks to @huihuaTRI for noticing the problem and @amcastro-tri for identifying the bug.
Priority is Emergency since master is broken until this lands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13953)
=> Fix fixed-joint CalcMassMatrix() bug introduced in PR #13933.

bindings/pydrake/doc/_static/css/custom.css, doc/doxygen_extra.css
Closes #13950.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13952)
=> Explicitly set font-family for all monospaced HTML elements

tools/workspace/ros_xacro/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13967)
=> workspace: Upgrade ros_xacro to latest release 1.13.8

tools/workspace/bazel_skylib/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13969)
=> workspace: Upgrade bazel_skylib to latest release 1.0.3

common/trajectories/piecewise_quaternion.cc, common/trajectories/piecewise_quaternion.h, common/trajectories/test/piecewise_quaternion_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13972)
=> trajectories:  implement derivatives for PiecewiseQuaternion

common/BUILD.bazel, common/symbolic.h, common/symbolic_generic_polynomial.cc, common/symbolic_generic_polynomial.h, common/symbolic_polynomial.h, common/test/symbolic_generic_polynomial_test.cc, common/test_utilities/symbolic_test_util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13940)
=> Generic polynomial

tools/workspace/ghc_filesystem/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13966)
=> workspace: Upgrade ghc_filesystem to latest release 1.3.4

common/text_logging.h, tools/workspace/fmt/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13968)
=> workspace: Upgrade fmt to latest release 7.0.3

bindings/pydrake/BUILD.bazel, bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/piecewise_quaternion.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13974)
=> trajectories: add bindings for PiecewiseQuaternionSlerp

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/test/yaml_test.py, bindings/pydrake/common/yaml.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13982)
=> pydrake: Copy and adapt yaml utilities from Anzu

multibody/multibody_doxygen.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13959)
=> Add SpatialMomentum to documentation for multibody_quantities_html.

doc/release_notes/template.txt, tools/dev/relnotes.py
Automatically bootstrap from our project template.
Automatically read and update commit ranges in the document.
Automatically place new commits into sections.
Automatically update PR hyperlinks.
For example output, see r1 and r2 of https://github.com/RobotLocomotion/drake/pull/13956:
- https://github.com/RobotLocomotion/drake/pull/13956/commits/87c5f72c0a6227021170efd30f8fd6359cf8cdd4
- https://github.com/RobotLocomotion/drake/pull/13956/commits/d7881e2086ed19f86c7533973f2ceff07fb6ab19
There's many more small things we could automate, but auto-sorting is a big chunk of progress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13955)
=> tools: Improve relnotes tooling

systems/framework/test/diagram_builder_test.cc, systems/framework/test/system_html_test.cc, systems/primitives/BUILD.bazel, systems/primitives/constant_value_source.h, systems/primitives/pass_through.cc, systems/primitives/pass_through.h, systems/primitives/test/pass_through_test.cc
I originally wrote this as a brand new system for optional values, but realized I was almost completely duplicating the PassThroughSystem.  I *think* this is the best place for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13976)
=> Allow PassThroughSystem to emit default values

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13996)
=> pydrake.primitives: add binding for new PassThrough constructor

examples/manipulation_station/manipulation_station.cc, examples/manipulation_station/manipulation_station.h, examples/manipulation_station/test/manipulation_station_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13995)
=> manipulation_station: make iiwa feedforward torques input optional

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py
Closes #13368
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13993)
=> pydrake math: Add bindings for random rotations

common/symbolic_generic_polynomial.cc, common/symbolic_generic_polynomial.h, common/test/symbolic_generic_polynomial_test.cc
Add AddProduct and RemoveTermsWithSmallCoefficients to GenericPolynomial
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13980)
=> Add Evaluate and EvaluatePartial to GenericPolynomial.

tools/dynamic_analysis/ubsan.supp, tools/workspace/BUILD.bazel, tools/workspace/bullet/BUILD.bazel, tools/workspace/bullet/package.BUILD.bazel, tools/workspace/bullet/stub.cc, tools/workspace/freetype2/repository.bzl
Follow-up from #13889.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13986)
=> workspace: Deprecate now-unused bullet,freetype2

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13997)
=> pydrake multibody: Add bindings for CalcJacobianCenterOfMassTranslationalVelocity and CalcBiasCenterOfMassTranslationalAcceleration

common/symbolic_monomial_basis_element.cc, common/symbolic_monomial_basis_element.h, common/test/symbolic_monomial_basis_element_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13994)
=> Convert a monomial basis element to the sum of chebyshev basis elements.

multibody/tree/rotational_inertia.h
Replaces RotationalInertia::ReExpressInPlace() with a much faster method due to Featherstone.
This operation is heavily used so the roughly 2x speedup of this one method here has a noticeable effect on overall multibody computations. Cassie benchmark timing improvements (approximate):
mass matrix: 22.4μs -> 19.2 (14%)
inverse dyn:  30.9 -> 28.0 (9%)
forward dyn: 61.0 -> 57.6 (6%)
I'll record more precise timings in #13902 when this merges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13962)
=> Use a faster inertia matrix rotation method

.clang-tidy
Just reformat the list of checks into multiple lines and then alpha-sort them. No entries are added or removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14007)
=> Reformat .clang-tidy

bindings/pydrake/systems/jupyter_widgets.py
Follow-up to #14025
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14027)
=> jupyter_widgets: Make testing instructions more explicit

bindings/pydrake/BUILD.bazel, bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/piecewise_quaternion.cc, common/trajectories/piecewise_quaternion.h, common/trajectories/test/piecewise_quaternion_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14031)
=> trajectories: implement Append for PiecewiseQuaternionSlerp

common/symbolic_chebyshev_basis_element.h, common/symbolic_chebyshev_polynomial.h, common/symbolic_environment.h, common/symbolic_expression.h, common/symbolic_expression_visitor.h, common/symbolic_formula.h, common/symbolic_formula_cell.h, common/symbolic_formula_visitor.h, common/symbolic_monomial.h, common/symbolic_monomial_basis_element.h, common/symbolic_monomial_util.h, common/symbolic_polynomial.h, common/symbolic_polynomial_basis.h, common/symbolic_polynomial_basis_element.h, common/symbolic_rational_function.h, common/symbolic_variable.h, common/symbolic_variables.h, tools/skylark/pybind.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14003)
=> symbolic: Change #warning to #error

common/symbolic_chebyshev_basis_element.cc, common/symbolic_chebyshev_basis_element.h, common/symbolic_monomial_basis_element.cc, common/symbolic_monomial_basis_element.h, common/symbolic_polynomial_basis_element.cc, common/symbolic_polynomial_basis_element.h, common/test/symbolic_chebyshev_basis_element_test.cc, common/test/symbolic_monomial_basis_element_test.cc, common/test/symbolic_polynomial_basis_element_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14023)
=> Add a function to merge another basis element in place.

bindings/pydrake/systems/meshcat_visualizer.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14057)
=> meshcat: replace use of deprecated .matrix()

systems/lcm/lcm_publisher_system.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14060)
=> Fix typo in doxygen comment argument name

solvers/binding.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14065)
=> Add documentation to Binding.GetNumElements()

multibody/plant/BUILD.bazel, multibody/plant/contact_solver_results.cc, multibody/plant/contact_solver_results.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/tamsi_solver_results.cc
An `internal::` refactor requested in #13958.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14069)
=> Refactors TamsiContactResults --> ContactSolverResults

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14064)
=> solvers.py: Add vectorized version of EvalBinding (for python)

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py, systems/framework/diagram_builder.cc, systems/framework/diagram_builder.h, systems/framework/test/diagram_builder_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14066)
=> framework: Add DiagramBuilder::GetSystems

multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/global_inverse_kinematics.cc, multibody/inverse_kinematics/global_inverse_kinematics.h, multibody/inverse_kinematics/test/global_inverse_kinematics_collision_avoidance_test.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_feasible_posture_test.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_reachable_test.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_test.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.h
Resolves #13819
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13921)
=> Bring global_inverse_kinematics out from attic.

bindings/pydrake/systems/lcm_py.cc, bindings/pydrake/systems/test/lcm_test.py, systems/lcm/BUILD.bazel, systems/lcm/connect_lcm_scope.cc, systems/lcm/connect_lcm_scope.h, systems/lcm/lcm_publisher_system.cc, systems/lcm/lcm_publisher_system.h, systems/lcm/test/connect_lcm_scope_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14062)
=> lcm: Add publish_period option to ConnectLcmScope

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
Would like to use this in Anzu.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14070)
=> py mpb: Add bindings for LinearBushingRollPitchYaw

bindings/pydrake/BUILD.bazel, bindings/pydrake/multibody/math_py.cc, bindings/pydrake/test/all_each_import_test.py
Resolves #14071
FYI @mpetersen94
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14072)
=> py mbp: Fix missing runtime module import

bindings/pydrake/multibody/examples/jupyter_widgets_examples.ipynb, bindings/pydrake/multibody/jupyter_widgets.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14059)
=> jupyter: Add joint sliders using publishing callback.

tools/workspace/dreal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14083)
=> Use dreal-4.20.09.1

common/symbolic_generic_polynomial.cc, common/symbolic_generic_polynomial.h, common/test/symbolic_generic_polynomial_test.cc, common/test_utilities/symbolic_test_util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14053)
=> Add operator +, -, * to GenericPolynomial

bindings/pydrake/multibody/jupyter_widgets.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14095)
=> jupyter_widgets: add missing display import

math/BUILD.bazel, math/expmap.h
Closes #14058.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14099)
=> math: Deprecate expmap.h

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/math_py.cc, bindings/pydrake/multibody/test/math_test.py
I would like to use this in Python in ANzu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14098)
=> py mbp: Bind operators for SpatialVector, shifting for velocity and force

examples/manipulation_station/manipulation_station.cc, geometry/geometry_visualization.cc, geometry/proximity/test/obb_test.cc, geometry/proximity/test/volume_to_surface_mesh_test.cc, geometry/render/render_engine.h, geometry/render/test/render_engine_test.cc, geometry/scene_graph.cc, geometry/test/geometry_state_test.cc, multibody/contact_solvers/test/multibody_sim_driver.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
Relates #14085. Gets us clean for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14094)
=> Fix range-loop-analysis warnings

common/symbolic_generic_polynomial.cc, common/symbolic_generic_polynomial.h, common/test/symbolic_generic_polynomial_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14100)
=> Add hash and divide to GenericPolynomial.

common/trajectories/BUILD.bazel, common/trajectories/bspline_trajectory.cc, common/trajectories/bspline_trajectory.h, common/trajectories/test/bspline_trajectory_test.cc, math/BUILD.bazel, math/bspline_basis.cc, math/bspline_basis.h, math/test/bspline_basis_test.cc
This allows parsing of these objects from YAML.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14106)
=> bsplines: Add Serialize() for Bspline{Basis,Trajectory}<double>

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14108)
=> py mbp: Expose ContactModel enumeration and accessor/mutators

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14111)
=> py mbp: Bind RotationalInertia and UnitInertia's ReExpress

tools/workspace/ibex/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14109)
=> Cleanup pkg-config path for ibex

tools/py_toolchain/BUILD.bazel, tools/workspace/numpy/BUILD.bazel, tools/workspace/numpy/repository.bzl, tools/workspace/numpy/stub.cc, tools/workspace/pybind11/package.BUILD.bazel
Closes #8544.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14116)
=> Deprecate the numpy repository

systems/analysis/BUILD.bazel, systems/analysis/simulator_config.cc, systems/analysis/simulator_config.h, systems/analysis/simulator_config_functions.cc, systems/analysis/simulator_config_functions.h, systems/analysis/test/simulator_config_functions_test.cc
In support of #12903.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14103)
=> Initial port of simulator configuration helpers

solvers/mathematical_program_doxygen.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14122)
=> Update solve matrix doxygen, CSDP supports socp.

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14120)
=> Add python binding for AddRotatedLorentzConeConstraint.

systems/analysis/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14125)
=> analysis: Break simulator_test dependency on MultibodyPlant

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14131)
=> meshcat: add option to set contact cylinder radius

manipulation/models/jaco_description/package.xml, manipulation/models/jaco_description/urdf/test/jaco_arm_test.cc, multibody/parsing/package_map.cc
Per discussion here:
https://github.com/RobotLocomotion/drake/pull/14038#pullrequestreview-497707499
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14134)
=> jaco: Add and test for package.xml

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14139)
=> multibody: add binding for GetFloatingBaseBodies

doc/developers.rst
Relates to #14085
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14142)
=> Upgrade to Xcode 12 on Catalina

common/schema/test/transform_test.cc, common/schema/transform.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14143)
=> schema: Remove rotation_rpy_deg backwards compatibility

multibody/parsing/test/detail_sdf_parser_test.cc, tools/workspace/sdformat/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14147)
=> workspace: Upgrade libsdformat to latest release 9.3.0

tools/workspace/buildifier/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14152)
=> workspace: Upgrade buildifier to latest release 3.5.0

tools/workspace/spdlog/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14153)
=> workspace: Upgrade spdlog to latest release 1.8.1

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/BUILD.bazel, multibody/parsing/detail_path_utils.cc, multibody/parsing/process_model_directives.cc, multibody/parsing/scoped_names.cc, multibody/parsing/scoped_names.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14145)
=> Cleanups of issues revealed in integrating model directives downstream

multibody/plant/BUILD.bazel, multibody/plant/test/frame_kinematics_test.cc, multibody/plant/test/multibody_plant_kinematics_test.cc, multibody/test_utilities/BUILD.bazel, multibody/test_utilities/spatial_derivative.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13593)
=> Test to check AutoDiff and vector differentiation in a non-world frame (for issue #13562).

tools/workspace/ignition_math/package.BUILD.bazel, tools/workspace/ignition_math/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14148)
=> workspace: Upgrade ignition_math to latest release 6.6.0

multibody/math/spatial_momentum.h, multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_momentum_energy_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/13916)
=> Code and test for spatial momentum of a plant or subset of bodies.

tools/skylark/drake_cc.bzl
Closes #14151.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14155)
=> build: Wcpp warnings to errors

examples/manipulation_station/models/package.xml, manipulation/models/ycb/package.xml
so that I can find the files in manipulation_station/models from outside of drake via the model directives.  (yeah!)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14164)
=> manipulation_station: add package.xml

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14166)
=> py multibody: add bindings for floating base accessors

tools/install/bazel/test/drake_bazel_installed_test.py, tools/workspace/rules_python/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14161)
=> workspace: Upgrade rules_python to latest release 0.0.3

bindings/pydrake/symbolic_types_pybind.h, common/symbolic_generic_polynomial.h, common/test/symbolic_generic_polynomial_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14158)
=> Add pow to GenericPolynomial.

doc/developers.rst, doc/release_playbook.rst
There are a lot of imperfections still here, but here the goal is just to transcribe the google docs draft into our project docs, so we can PR it like everything else.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14170)
=> doc: Add snapshot of current release playbook

doc/code_style_tools.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14173)
=> doc: Added git clang-format instructions for Ubuntu

doc/credits.rst
Added mention of TRI and some missing contributors to the [Drake credits list](https://drake.mit.edu/credits.html). Please let me know if you _don't_ want to be listed.
This not an attempt to be comprehensive -- these are just people I noticed were missing. If anyone wants to be added to this PR let me know.
cc @EricCousineau-TRI @xuchenhan-tri @joemasterjohn @dmcconachie-tri
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14162)
=> Update the Drake credits list

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/inverse_kinematics.cc, multibody/inverse_kinematics/test/inverse_kinematics_test.cc, multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc, multibody/inverse_kinematics/unit_quaternion_constraint.cc, multibody/inverse_kinematics/unit_quaternion_constraint.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14141)
=> Add unit length constraint on quaternion variables.

doc/gallery.rst
Adds videos as well as links to the source code for the fourbar and strandbeest examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14181)
=> Add fourbar and strandbeest to the gallery

setup/mac/source_distribution/Brewfile-doc-only, tools/workspace/doxygen/repository.bzl
Relates #13964. FYI @BetsyMcPhail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14169)
=> Use doxygen 1.8.15 on Mac

solvers/BUILD.bazel, solvers/aggregate_costs_constraints.cc, solvers/aggregate_costs_constraints.h, solvers/test/aggregate_costs_constraints_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14165)
=> Add AggregateQuadraticCosts

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/all.py, bindings/pydrake/multibody/optimization_py.cc, bindings/pydrake/multibody/test/optimization_test.py, multibody/optimization/contact_wrench.h, multibody/optimization/static_equilibrium_constraint.cc, multibody/optimization/static_equilibrium_problem.cc, multibody/optimization/static_friction_cone_complementarity_constraint.cc, multibody/optimization/test/static_equilibrium_problem_test.cc
Also use ComputeSignedDistancePairwiseClosestPoints() to avoid redundant computation.
EDIT(eric):
Towards #13473
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14140)
=> Add python binding for static equlibrium problem.

multibody/math/spatial_vector.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14188)
=> multibody: Deprecate dead code

bindings/pydrake/multibody/math_py.cc, bindings/pydrake/multibody/test/math_test.py, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14193)
=> pydrake: Bind some missing multibody math-related items

solvers/aggregate_costs_constraints.cc, solvers/aggregate_costs_constraints.h, solvers/test/aggregate_costs_constraints_test.cc
change AggregateQuadraticCosts to AggregateQuadraticAndLinearCosts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14190)
=> add AggregateLinearCosts.

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py, bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc
Closes #14132
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14201)
=> pydrake: Add bindings for BsplineTrajectory and BsplineBasis

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/tree/planar_joint.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14195)
=> pydrake: Bind some missing multibody tree-related items

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/test/optimization_test.py
Resolves a weekly build CI failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14199)
=> Call Ipopt solver explicitly when solving static equilibrium problem.

multibody/fem/dev/BUILD.bazel, multibody/fem/dev/quadrature.h, multibody/fem/dev/test/simplex_gaussian_quadrature_test.cc
Create the API for a general quadrature rule class for FEM applications.
Add a concrete class, SimplexGaussianQuadrature that implements the APIs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14202)
=> Add quadrature class for FEM.

multibody/fem/dev/BUILD.bazel, multibody/fem/dev/isoparametric_element.cc, multibody/fem/dev/isoparametric_element.h, multibody/fem/dev/linear_simplex_element.cc, multibody/fem/dev/linear_simplex_element.h, multibody/fem/dev/quadrature.h, multibody/fem/dev/test/isoparametric_element_test.cc, multibody/fem/dev/test/linear_simplex_element_test.cc
Add an abstract IsoparametricElement class for generic APIs for isoparametric FEM elements.
Add a concrete linear simplex element implementing the APIs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14213)
=> Add isoparametric element for FEM.

examples/README-MATLAB.md
- https://github.com/RobotLocomotion/drake/tree/v0.23.0/examples/compass_gait
- https://github.com/RobotLocomotion/drake/tree/v0.23.0/examples/rimless_wheel
- https://github.com/RobotLocomotion/drake/tree/v0.23.0/examples/multibody/strandbeest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14232)
=> examples: Fix the list of absent examples

common/autodiffxd.h, examples/multibody/cassie_benchmark/test/cassie_bench.cc
Get rid of some TODOs I no longer believe have any value. Where helpful, add
some issue numbers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14240)
=> autodiff, cassie_bench: Retire some TODOs.

solvers/BUILD.bazel, solvers/aggregate_costs_constraints.cc, solvers/aggregate_costs_constraints.h, solvers/test/aggregate_costs_constraints_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14248)
=> Aggregate BoundingBoxConstraint.

geometry/query_object.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14253)
=> geometry: Fix QueryObject doc typo

geometry/render/gl_renderer/BUILD.bazel, geometry/render/gl_renderer/no_render_engine_gl_factory.cc
Closes #14255.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14256)
=> gl_renderer: Fix stub factory for macOS build

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14257)
=> pydrake.multibody: add missing bindings for joint accessors

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/scene_graph_inspector.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14259)
=> add (almost all) missing py scenegraph inspector bindings

tools/workspace/intel_realsense_ros/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14274)
=> workspace: Upgrade intel_realsense_ros to latest release 2.2.18

tools/install/bazel/test/drake_bazel_installed_test.py, tools/workspace/rules_python/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14278)
=> workspace: Upgrade rules_python to latest release 0.1.0

tools/workspace/rules_pkg/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14277)
=> workspace: Upgrade rules_pkg to latest release 0.3.0

tools/workspace/ghc_filesystem/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14273)
=> workspace: Upgrade ghc_filesystem to latest release 1.3.6

tools/workspace/ros_xacro/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14276)
=> workspace: Upgrade ros_xacro to latest release 1.13.9

solvers/gurobi_solver.cc, solvers/mathematical_program_result.h, solvers/test/gurobi_solver_test.cc
Resolves #14281
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14285)
=> Throw an error when getting dual solution for a QCP in gurobi.

examples/multibody/cassie_benchmark/test/cassie_bench.cc
This patch better models collection of malloc stats from multiple invocations
of each benchmark body. The google bench framework typically invokes the
benchmark case code multiple times even in normal operation, and uses the same
storage to capture user-defined metrics. The prior arrangement of the tracker
allowed later invocations' data to overwrite earlier. This version collects
data across all invocations.
The change doesn't matter much now, but it will make it easier to follow the
evolution of malloc counts across invocations with storage pool optimizations.
The effect of this patch on results is negligible, since the changes are
outside of the magic state loop.
--- …
=> cassie_bench: Update malloc tracking

multibody/fem/dev/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14311)
=> Disable tests that are failing valgrind in CI

bindings/pydrake/doc/BUILD.bazel, doc/BUILD.bazel, doc/documentation_instructions.rst, setup/mac/install_prereqs.sh, setup/mac/source_distribution/install_prereqs.sh, setup/ubuntu/install_prereqs.sh, setup/ubuntu/source_distribution/install_prereqs.sh
Toward #13832. CI will need some tweaks once this merges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14168)
=> Make installing documentation prereqs optional

solvers/mosek_solver.cc, solvers/test/mosek_solver_test.cc, solvers/test/quadratic_program_examples.cc, solvers/test/quadratic_program_examples.h, solvers/test/semidefinite_program_examples.cc, solvers/test/semidefinite_program_examples.h
As a step to #13285
This gets the dual solution for only bounding box constraints. I will later send PRs for linear constraints and nonlinear conic constraints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14303)
=> MosekSolver result get dual solution for bounding box constraints.

solvers/mosek_solver.cc
Resolves #14336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14338)
=> Only retrieve Mosek dual solution when there is no integer variables.

tutorials/nonlinear_program.ipynb
The original tutorial ses SetDecisionVariableValueInVector, which is too terse.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14331)
=> Change to use SetInitialGuess in the nlp tutorial.

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic_variable.h, common/test/symbolic_variable_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14342)
=> Add python binding for MakeMatrixVariable and MakeVectorVariable.

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/pydrake_pybind.h, bindings/pydrake/test/pydrake_pybind_test.cc, multibody/plant/test/multibody_plant_test.cc
For use w/ Anzu stuff
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14345)
=> py mbp: Bind MultibodyPlant.GetBodiesWeldedTo

CMakeLists.txt, doc/developers.rst, doc/jenkins.rst, doc/release_playbook.rst, tools/workspace/os.bzl, tools/workspace/pkg_config.bzl
Closes #14328.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14352)
=> Remove support for macOS Mojave 10.14

multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_com_test.cc, multibody/tree/multibody_tree.cc
Per issue #13646, throw an exception if composite_mass <= 0.
This PR #14316 resolves issue #13646.
Note: Since I am currently working on center of mass methods, this is an opportune time to address issue #13646.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14316)
=> Per issue #13646, throw an exception if composite_mass <= 0.

solvers/mosek_solver.cc, solvers/test/gurobi_solver_test.cc, solvers/test/ipopt_solver_test.cc, solvers/test/linear_program_examples.cc, solvers/test/linear_program_examples.h, solvers/test/mosek_solver_test.cc, solvers/test/quadratic_program_examples.cc, solvers/test/quadratic_program_examples.h, solvers/test/snopt_solver_test.cc
As a step towards #13285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14348)
=> retrieve linear constraint dual from Mosek result.

bindings/pydrake/multibody/test/plant_test.py, geometry/geometry_state.h, geometry/proximity/hydroelastic_callback.h, geometry/proximity/mesh_intersection.cc, geometry/proximity/test/hydroelastic_callback_test.cc, geometry/proximity/test/mesh_intersection_test.cc, geometry/proximity_engine.cc, geometry/proximity_engine.h, geometry/query_object.cc, geometry/query_object.h, geometry/test/proximity_engine_test.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
Resolves #11454
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14324)
=> Remove MBP's awareness of SG<AutoDiff> support

multibody/fem/dev/BUILD.bazel, multibody/fem/dev/deformation_gradient_cache_entry.h, multibody/fem/dev/linear_constitutive_model.cc, multibody/fem/dev/linear_constitutive_model.h, multibody/fem/dev/linear_constitutive_model_cache_entry.cc, multibody/fem/dev/linear_constitutive_model_cache_entry.h, multibody/fem/dev/test/elasticity_element_test.cc, multibody/fem/dev/test/elasticity_model_test.cc, multibody/fem/dev/test/linear_constitutive_model_cache_entry_test.cc, multibody/fem/dev/test/linear_constitutive_model_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14365)
=> Rename LinearElasticityModel to LinearConstitutiveModel.

common/yaml/test/example_structs.h, common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_read_archive.h
As promised during #14327 review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14360)
=> yaml: Fix parsing bugs with zero-sized matrices

bindings/pydrake/examples/manipulation_station_py.cc
Resolves #14369
\cc @sloretz @RussTedrake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14370)
=> py examples: Ensure manipulation_station_py.cc imports dep modules

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/test/deprecation_example/cc_module_py.cc, bindings/pydrake/common/test/deprecation_test.py
Follow-up to #14358
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14371)
=> py deprecation: Correct minor error in test

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/BUILD.bazel, common/symbolic_decompose.cc, common/symbolic_decompose.h, common/symbolic_expression.h, common/test/symbolic_decompose_test.cc, solvers/BUILD.bazel, solvers/constraint.cc, solvers/create_constraint.cc, solvers/create_cost.cc, solvers/mathematical_program.cc, solvers/symbolic_extraction.cc, solvers/symbolic_extraction.h
Also add the python bindings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14353)
=> Move code from symbolic_extraction to symbolic_decompose.

bindings/pydrake/systems/test/trajectory_optimization_test.py, systems/trajectory_optimization/multiple_shooting.cc, systems/trajectory_optimization/multiple_shooting.h, systems/trajectory_optimization/test/multiple_shooting_test.cc
Stumbled across the relevant issue and realized I had already made the fix in my own branch so thought I'd upstream.
Closes #13213
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14340)
=> systems/traj opt: Return multiple shooting constraints for AddConstraintToAllKnotPoints and AddEqualTimeIntervalsConstraints

examples/manipulation_station/end_effector_teleop_dualshock4.py
Confirmed using demo program from:
https://www.pygame.org/docs/ref/joystick.html#controller-mappings
---
Playing with this for some Anzu work, using a slightly ancient controller that I've had for 10 years: `Logitech G-UF13A`
Their website ain't too informative: https://support.logi.com/hc/en-us/articles/360024782693
\cc @darshanhegde 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14388)
=> dualshock: Update example to use Logitech controller

geometry/render/gl_renderer/BUILD.bazel, geometry/render/gl_renderer/opengl_geometry.h, geometry/render/gl_renderer/render_engine_gl.cc, geometry/render/gl_renderer/shape_meshes.cc, geometry/render/gl_renderer/shape_meshes.h, geometry/render/gl_renderer/test/opengl_geometry_test.cc, geometry/render/gl_renderer/test/shape_meshes_test.cc, geometry/render/gl_renderer/texture_library.cc
See commit message for more details.
Towards Anzu PR 6027
Relates #11880
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14396)
=> render_engine_gl: Make tex_coord be effectively optional

bindings/pydrake/multibody/test/plant_test.py, geometry/geometry_state.h, geometry/proximity/BUILD.bazel, geometry/proximity/distance_to_shape_callback.h, geometry/proximity/hydroelastic_callback.h, geometry/proximity/penetration_as_point_pair_callback.cc, geometry/proximity/penetration_as_point_pair_callback.h, geometry/proximity/test/hydroelastic_callback_test.cc, geometry/proximity/test/penetration_as_point_pair_callback_test.cc, geometry/proximity_engine.cc, geometry/proximity_engine.h, geometry/query_object.h, geometry/query_results/penetration_as_point_pair.h, geometry/test/proximity_engine_test.cc
Resolves #11455
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14378)
=> make penetration query work for some simple geometries with AutoDiffScalars

geometry/proximity/test/penetration_as_point_pair_callback_test.cc
Fix the mac CI failure https://drake-cdash.csail.mit.edu/test/80036322
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14406)
=> Fix a failure on Mac on penetration test.

tutorials/mathematical_program.ipynb, tutorials/quadratic_program.ipynb
nbviewer Preview: https://nbviewer.jupyter.org/github/hongkai-dai/drake/tree/qp_tutorial/tutorials/
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14403)
=> Add a tutorial on quadratic program.

bindings/pydrake/systems/sensors_py.cc, bindings/pydrake/systems/test/sensors_test.py, systems/sensors/camera_info.cc, systems/sensors/camera_info.h, systems/sensors/test/camera_info_test.cc
No acute need, just been wanting this.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14402)
=> camera_info: Permit constructing from intrinsic matrix

tools/workspace/intel_realsense_ros/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14416)
=> workspace: Upgrade intel_realsense_ros to latest release 2.2.20

tools/workspace/ignition_math/package.BUILD.bazel, tools/workspace/ignition_math/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14415)
=> workspace: Upgrade ignition_math to latest release 6.7.0

tools/workspace/fmt/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14413)
=> workspace: Upgrade fmt to latest release 7.1.3

multibody/multibody_doxygen.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14397)
=> Update monogram notation for spatial velocity/acceleration.

tools/workspace/ghc_filesystem/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14414)
=> workspace: Upgrade ghc_filesystem to latest release 1.3.8

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14410)
=> Add UpdateBound for PYFunctionConstraint

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14438)
=> Add python binding for OutputPort::get_name

tools/workspace/dreal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14443)
=> workspace: Upgrade dreal to latest release 4.20.12.1

lcmtypes/BUILD.bazel
Closes #14118.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14444)
=> lcmtypes: Don't install stray __init__.py into site-packages

tools/workspace/optitrack_driver/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14451)
=> workspace: Update optitrack_driver to latest commit

multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_com_test.cc, multibody/plant/test/multibody_plant_jacobians_test.cc, multibody/tree/body.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/rigid_body.h
This PR #14297 should resolve issue #14268.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14297)
=> Add methods and tests for CalcCenterOfMassTranslationalVelocity().

geometry/proximity/BUILD.bazel, geometry/proximity/meshing_utilities.cc, geometry/proximity/meshing_utilities.h, geometry/proximity/test/meshing_utilities_test.cc, geometry/proximity/volume_mesh.h
Utility code for making Cylinder's tetrahedral mesh with medial axis.  I split the large PR #14335 into this prerequisite PR and another PR to come. Hopefully it will make the review process easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14421)
=> [geometry] This PR prepare for next PR "Make Cylinder mesh with medial axis."

multibody/tree/multibody_tree.h
This PR addresses the multibody_tree.h part of issue #13738.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14459)
=> Change /// to // within internal namespace within multibody_tree.h

doc/release_notes/template.txt, doc/release_playbook.rst, tools/dev/BUILD.bazel, tools/release_engineering/BUILD.bazel, tools/release_engineering/relnotes.py, tools/release_engineering/test/relnotes_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14456)
=> tools: Move relnotes out of dev, into proper support

tools/release_engineering/BUILD.bazel
Hotfix for #14456.
Closes #14463.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14466)
=> tools: Disable relnotes help test, for now

multibody/tree/mobilizer.h
This PR addresses the  mobilizer.h part of issue #13738.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14461)
=> Change /// to // within internal namespace in mobilizer.h

multibody/parsing/detail_common.h, multibody/parsing/detail_urdf_parser.h, multibody/plant/contact_jacobians.h, multibody/tree/articulated_body_force_cache.h, multibody/tree/body_node.h, multibody/tree/body_node_impl.h, multibody/tree/mobilizer_impl.h, multibody/tree/multibody_tree_topology.h, multibody/tree/prismatic_mobilizer.h, multibody/tree/quaternion_floating_mobilizer.h, multibody/tree/revolute_mobilizer.h, multibody/tree/space_xyz_mobilizer.h, multibody/tree/universal_mobilizer.h, multibody/tree/weld_mobilizer.h
This PR addresses commonly-encountered header files associated with issue #13738.
Reviewer, please ensure this is a good idea as changing // to /// is more difficult than /// to //.
Please read Sherm's comments in issue #11229.
https://github.com/RobotLocomotion/drake/issues/11229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14468)
=> Change /// to // for internal namespace in commonly-encountered header files.

bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py, systems/controllers/pid_controlled_system.cc, systems/controllers/pid_controlled_system.h, systems/controllers/test/pid_controlled_system_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14490)
=> PidControlledSystem takes in user specified plant input port.

setup/mac/binary_distribution/install_prereqs.sh, setup/mac/source_distribution/install_prereqs.sh
A subset of #14492, since I want to narrow the scope and simplify that PR.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14496)
=> Various Homebrew setup improvements

common/trajectories/piecewise_quaternion.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14503)
=> Hotfix to repair build failure caused by #14337

tools/workspace/fcl/repository.bzl
As part of platform reviewer duties, per request on Slack: https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1609951566108100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14497)
=> workspace: Bump fcl to latest commit on master

tools/release_engineering/relnotes.py
The easiest way to document commits to /dev/ directories is to ignore
them. The patch implements an idea from discussions between rpoyner-tri
and jwnimmer-tri after the v0.25.0 release cycle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14508)
=> relnotes.py: Ignore /dev/ commits

setup/ubuntu/source_distribution/packages-bionic-doc-only.txt, setup/ubuntu/source_distribution/packages-focal-doc-only.txt
Working towards #13832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14507)
=> Setup: Update packages needed to generate Jekyll website

common/symbolic_expression_cell.cc, common/test/symbolic_expression_differentiation_test.cc
Relates #8648.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14514)
=> Allow incomplete derivatives, signaling with NaN at evaluation-time where possible

tools/release_engineering/relnotes.py
Guess the package with the most lines changed is the primary for the
commit. The patch implements an idea from discussions between
rpoyner-tri and jwnimmer-tri after the v0.25.0 release cycle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14511)
=> relnotes.py: Use line counts to get better primary package guess

bindings/pydrake/doc/BUILD.bazel, bindings/pydrake/doc/pydrake_sphinx_extension.py, doc/BUILD.bazel, doc/system_doxygen.py, doc/test/system_doxygen_test.py, tools/lint/drakelint.py, tools/workspace/pybind11/mkdoc_comment.py, tools/workspace/pybind11/test/generate_pybind_coverage_test.py, tools/workspace/pybind11/test/mkdoc_comment_test.py, tools/workspace/pybind11/test/sample_header.h, tools/workspace/pybind11/test/sample_header_class_coverage_expected.csv, tools/workspace/pybind11/test/sample_header_documentation.expected.h, tools/workspace/pybind11/test/sample_header_documentation_pybind_expected.xml, tools/workspace/pybind11/test/sample_header_file_coverage_expected.csv
Have mkdoc_comment use this directive
Resolves #12590
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14500)
=> pydrake doc: Add `pydrake_system` directive to Sphinx

examples/acrobot/dev/BUILD.bazel, examples/acrobot/dev/optimizer_demo.py, examples/acrobot/dev/spong_sim.cc, examples/acrobot/dev/test/optimizer_demo_smoke_test.sh
* Also Removes a print line that becomes spammy under repeated invocation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14516)
=> Add a simple demonstration program for acrobot monte carlo

tools/dynamic_analysis/bazel.rc
See Slack conversation:
https://drakedevelopers.slack.com/archives/C270MN28G/p1610544838306100?thread_ts=1610539112.305300&cid=C270MN28G
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14523)
=> dynamic_analysis: Comment on memcheck's exception for sh filtering

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/damping_model.h, multibody/fixed_fem/dev/dynamic_elasticity_element.h, multibody/fixed_fem/dev/elasticity_element.h, multibody/fixed_fem/dev/fem_element.h, multibody/fixed_fem/dev/static_elasticity_element.h, multibody/fixed_fem/dev/test/dynamic_elasticity_element_test.cc, multibody/fixed_fem/dev/test/static_elasticity_element_test.cc
DynamicElasticityElement inherits from ElasticityElement and implements
the interface in FemElement for dynamic elasticity problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14533)
=> Add DynamicElasticityElement

multibody/fixed_fem/dev/elasticity_element.h
Closes #14549. Relates  #14533.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14550)
=> Hotfix to repair asan failure

doc/release_playbook.rst
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14554)
=> doc: Fix jenkins link to documentation build

bindings/pydrake/test/math_test.py, common/test_utilities/drake_py_unittest_main.py, tools/skylark/drake_py.bzl, tools/workspace/default.bzl, tools/workspace/xmlrunner_py/BUILD.bazel, tools/workspace/xmlrunner_py/package.BUILD.bazel, tools/workspace/xmlrunner_py/repository.bzl
Remove a stray print statement whose unicode defeats the xml runner's output scraping.
Closes #8821.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14560)
=> tools: Add xmlrunner and use it for Python unittests

tools/workspace/github3_py/package.BUILD.bazel
Remove an unused import.
Prefer the glob argument vs "or fail".
(I stumbled into these while working on #14560.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14563)
=> tools: Adjust github3_py for best practices

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/elasticity_element.h, multibody/fixed_fem/dev/elasticity_model.h, multibody/fixed_fem/dev/fem_model.h, multibody/fixed_fem/dev/state_updater.h, multibody/fixed_fem/dev/static_elasticity_model.h, multibody/fixed_fem/dev/test/dummy_element.h, multibody/fixed_fem/dev/test/fem_element_test.cc, multibody/fixed_fem/dev/test/fem_state_test.cc, multibody/fixed_fem/dev/test/static_elasticity_model_test.cc, multibody/fixed_fem/dev/test/zeroth_order_state_updater_test.cc, multibody/fixed_fem/dev/zeroth_order_state_updater.h
See the more detailed design doc [here](https://docs.google.com/document/d/1RqeR-K2_TKaxEp9e7_qSykL6QWN6bI2tHxZ1BL7v5ao/edit?ts=5fdae31b). 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14535)
=> Design StateUpdater class and FemModel class

doc/BUILD.bazel, doc/build.py, doc/doxygen_main.py
This enables us to formulate the website layout within Drake itself, instead of by tweaking untestable CI scripts.
This will be used by https://github.com/RobotLocomotion/drake-ci/pull/122.
Towards #13832.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14587)
=> doc: Add consolidated deployment tool

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/dirichlet_boundary_condition.h, multibody/fixed_fem/dev/fem_indexes.h, multibody/fixed_fem/dev/test/dirichlet_boundary_condition_test.cc
Provide basic functionalities like setting the boundary state and modifying the tangent matrix and the residual according to the Dirichlet BC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14567)
=> Implement Dirichlet boundary condition

multibody/math/spatial_vector.h, setup/mac/binary_distribution/install_prereqs.sh, systems/sensors/BUILD.bazel, systems/sensors/accelerometer_sensor.h, systems/sensors/gyroscope_sensor.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14607)
=> Remove deprecated code 2021-02

examples/acrobot/README.md, examples/acrobot/spong_controller_w_lcm.cc
Previously, we were never decoding the received xhat messages.
Closes #14524.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14525)
=> acrobot: Fix spong LCM to actually work

common/yaml/test/example_structs.h, common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_read_archive.h, common/yaml/yaml_write_archive.h
Similar patches have been floating around in other PRs like #14318, #14611, etc.  It seems like it's time to land a polished version into master.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14618)
=> yaml: Allow for operating on non-default MaxRows or MaxCols storage

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/BUILD.bazel, geometry/drake_visualizer.cc, geometry/drake_visualizer.h, geometry/test/drake_visualizer_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14569)
=> Templatize DrakeVisualizer class.

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
cc @shensquared
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14627)
=> Pybind MathematicalProgram::NewNonnegativePolynomial

solvers/osqp_solver.cc, solvers/test/osqp_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14625)
=> Pass the time limit to OSQP settings

tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
Improve hydroelastic visualization
- Fix 13665. Improve hydroelastic visualization performance by send
mesh to VTK instead of individual triangle and line segments.
- Fix 13664. Introduce color map as 1D texture and color the pressure
according to the texture map.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14622)
=> Hydroelastic visualization speedup

solvers/osqp_solver.cc, solvers/test/osqp_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14637)
=> Increase error margin for OSQP solve time in the unit test

doc/getting_help.rst
As motivated by: https://stackoverflow.com/q/66216899/7829525
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14660)
=> getting_help: Add hints for Binder / Colab

doc/_pages/clion.md, doc/_pages/gallery.md, doc/_pages/python_bindings.md, doc/_release-notes/v0.17.0.md, doc/_release-notes/v0.18.0.md, doc/_release-notes/v0.19.0.md, doc/_release-notes/v0.20.0.md, doc/_release-notes/v0.22.0.md, doc/_release-notes/v0.26.0.md
Fix some minor styling
Towards #14657
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14659)
=> doc: Update Markdown to ensure Jekyll preview can work

.gitattributes
Towards #14657
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14666)
=> gitattributes: Treat svg files as binaries

doc/BUILD.bazel
Towards #14657
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14665)
=> doc/BUILD: Carve out Sphinx images for use in Jekyll website

doc/release_playbook.rst, tools/release_engineering/BUILD.bazel, tools/release_engineering/download_release_candidate.py, tools/release_engineering/relnotes.py
Add download_release_candidate script
Use un-escaped docstring (given usage of backslash)
Should not break lines at 80-characters for PR bullet points
Be more explicit about full-symbol expansion for new bindings
Split off from #14646
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14651)
=> release_playbook: Modifications used for v0.27.0

doc/BUILD.bazel, doc/_pages/vim.md
Also fix some markup glitches.
Part of #14577.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14682)
=> jekyll: Fix sample_vimrc dowload link

tools/install/colab/setup_drake_colab.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14693)
=> Hardcode python version to 3.6 in setup_drake_colab

doc/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14700)
=> fixed two links on the homepage that were not correct

setup/mac/binary_distribution/install_prereqs.sh, tools/workspace/ipopt/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14710)
=> setup: Remove stale paths for macOS dependencies

tools/workspace/ros_xacro/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14712)
=> workspace: Upgrade ros_xacro to latest release 1.13.10

tools/workspace/intel_realsense_ros/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14713)
=> workspace: Upgrade intel_realsense_ros to latest release 2.2.22

doc/_pages/developers.md, doc/developers.rst, setup/ubuntu/source_distribution/install_prereqs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14717)
=> setup: Upgrade recommended Bazel version to 4.0

tools/workspace/ghc_filesystem/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14711)
=> workspace: Upgrade ghc_filesystem to latest release 1.5.0

tools/workspace/osqp/repository.bzl, tools/workspace/qdldl/repository.bzl
Upgrade osqp to latest release 0.6.2
Upgrade qdldl to latest release 0.1.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14714)
=> workspace: Upgrade osqp and qdldl

tools/workspace/meshcat/repository.bzl, tools/workspace/meshcat_python/repository.bzl
Note: During feature review, requires local testing per the [README](https://github.com/RobotLocomotion/drake/blob/master/tools/workspace/meshcat/README.md#upgrading-meshcat-commit).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14715)
=> workspace: Upgrade meshcat and meshcat_python to latest commit

tools/workspace/drake_visualizer/.dockerignore, tools/workspace/drake_visualizer/.editorconfig, tools/workspace/drake_visualizer/0001-dv-opengl-glvnd.patch, tools/workspace/drake_visualizer/0002-dv-externals-warnings.patch, tools/workspace/drake_visualizer/0003-dv-externals-module-linker-flags.patch, tools/workspace/drake_visualizer/Dockerfile, tools/workspace/drake_visualizer/build_binaries_with_docker
Toward #10729. This just a [slightly cleaned up] code dump at present.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14573)
=> Add script for building drake-visualizer binaries for Ubuntu

examples/allegro_hand/allegro_lcm.cc, examples/allegro_hand/allegro_lcm.h, examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14732)
=> Adds LCM period argument to AllegroCommandReceiver's constructor.

doc/_pages/clion.md, doc/_pages/code_review_checklist.md, doc/_pages/code_style_guide.md, doc/_pages/code_style_tools.md, doc/_pages/developers.md, doc/_pages/getting_help.md, doc/_pages/jenkins.md, doc/_pages/mac.md, doc/_pages/python_bindings.md, doc/_pages/release_playbook.md, doc/_pages/sublime_text.md, doc/_pages/vim.md, doc/_release-notes/older_releases.md, doc/index.md
To the moon!
Towards #14695.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14737)
=> doc: Fix 29 nits on new Jekyll website

multibody/plant/multibody_plant.h
to alert users of unused effort limit argument.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14736)
=> Updates MBP::AddJointActuator() documentation

setup/mac/binary_distribution/Brewfile, solvers/BUILD.bazel, solvers/test/clp_test.cc, tools/BUILD.bazel, tools/install/libdrake/BUILD.bazel, tools/workspace/clp/BUILD.bazel, tools/workspace/clp/repository.bzl, tools/workspace/default.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14729)
=> Add CLP to drake build.

doc/assets/css/main.css
Fixes&nbsp;https://github.com/RobotLocomotion/drake/issues/14695#issuecomment-786830105.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14753)
=> doc: Debounce Jekyll nav menus

bindings/pydrake/multibody/plant_py.cc, multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc, multibody/tree/BUILD.bazel, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree.h, multibody/tree/string_view_map_key.h, multibody/tree/test/string_view_map_key_test.cc
Closes #14703
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14719)
=> Replaces std::string with std::string_view in MBP.

tools/workspace/pybind11/repository.bzl
Incorporates https://github.com/RobotLocomotion/pybind11/pull/52
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14751)
=> workspace: Bump pybind11 fork to latest commit

doc/build.py
Part of #13832.
Marked "do not merge" until #14695 is done and we want to pull the trigger.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14708)
=> doc: Switch website to use Jekyll

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/deformable_body_config.h, multibody/fixed_fem/dev/dynamic_elasticity_element.h, multibody/fixed_fem/dev/eigen_conjugate_gradient_solver.h, multibody/fixed_fem/dev/elasticity_element.h, multibody/fixed_fem/dev/fem_indexes.h, multibody/fixed_fem/dev/fem_model.h, multibody/fixed_fem/dev/linear_system_solver.h, multibody/fixed_fem/dev/matrix_utilities.h, multibody/fixed_fem/dev/mesh_utilities.h, multibody/fixed_fem/dev/run_cantilever_beam.cc, multibody/fixed_fem/dev/softsim_system.cc, multibody/fixed_fem/dev/softsim_system.h, multibody/fixed_fem/dev/state_updater.h, multibody/fixed_fem/dev/test/softsim_system_test.cc
In addition, fix a few compiler warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14741)
=> [FEM] Add SoftsimSystem and a large deformation demo

doc/_includes/footer.html, doc/_includes/header.html, doc/_pages/from_source.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14759)
=> doc: Change Github to GitHub on the website

doc/_release-notes/template.txt, tools/release_engineering/relnotes.py
* .rst remains the default until #14708 lands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14746)
=> Add .md capability to relnotes.py

doc/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14763)
=> doc: Add cautionary comment about changing the hero text

tools/workspace/drake_visualizer/drake_visualizer_bazel.py, tools/workspace/drake_visualizer/drake_visualizer_installed.py.in, tools/workspace/drake_visualizer/repository.bzl, tools/workspace/drake_visualizer/test/drake_visualizer_bazel_test.py, tools/workspace/drake_visualizer/test/drake_visualizer_installed_test.py
Closes #14650.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14769)
=> Update and re-enable drake-visualizer for macOS

systems/sensors/camera_info.h, systems/sensors/rgbd_sensor.h
I found it difficult to find this basic information when I was looking before.
resolves #12057
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14127)
=> sensors: add documentation about the camera frame

doc/build.py
Closes #14733 and makes the googlebot a little less sad.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14778)
=> doc: Generate a minimal sitemap of HTML files

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.cc, solvers/mathematical_program.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14790)
=> Add documentation on polynomial type.

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic_polynomial.cc, common/symbolic_polynomial.h, common/test/symbolic_polynomial_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14807)
=> adds simplest case of integration for symbolic polynomial

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/all.py, bindings/pydrake/solvers/clp_py.cc, bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/clp_solver_test.py, solvers/BUILD.bazel, solvers/choose_best_solver.cc, solvers/clp_solver.cc, solvers/clp_solver.h, solvers/clp_solver_common.cc, solvers/mathematical_program_doxygen.h, solvers/no_clp.cc, solvers/solver_type.h, solvers/solver_type_converter.cc, solvers/test/choose_best_solver_test.cc, solvers/test/clp_solver_test.cc, solvers/test/clp_test.cc, solvers/test/optimization_examples.cc, solvers/test/solver_type_converter_test.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14776)
=> Add ClpSolver

bindings/pydrake/multibody/test/plant_test.py
- Ensure we cover T for deprecated MultibodyPlant_[T].WeldFrames
- Use unittest.subTest to trace back to joint factories
Follow-up to #14805
Fixes buildcop failures. One such failure:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-catalina-clang-bazel-continuous-release/291/console
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14813)
=> py mbp: Fix bindings for plant test

setup/mac/binary_distribution/requirements.txt, setup/ubuntu/source_distribution/packages-bionic.txt, setup/ubuntu/source_distribution/packages-focal.txt, tools/workspace/pycps/package.BUILD.bazel, tools/workspace/semantic_version/package.BUILD.bazel
Resolves #14749
Will need a CI update prior to merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14784)
=> Use python3-semantic-version package on Ubuntu

doc/BUILD.bazel, doc/README.txt, doc/_pages/documentation_instructions.md, doc/build.py, doc/defs.bzl, doc/defs.py, doc/styleguide/BUILD.bazel, doc/styleguide/_config.yml, doc/styleguide/_layouts/default.html, doc/styleguide/build.py, tools/workspace/styleguide/package.BUILD.bazel
Towards #14803.  (That PR contains more example uses of the new `defs.py` helpers.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14811)
=> doc: Add direct styleguide publication

multibody/optimization/contact_wrench_evaluator.h, multibody/optimization/manipulator_equation_constraint.cc, multibody/optimization/manipulator_equation_constraint.h, multibody/optimization/static_equilibrium_constraint.cc, multibody/optimization/static_equilibrium_constraint.h
#Resolves #14829
@EricCousineau-TRI , do I need to add the factory method for the struct GeometryPairContactWrenchEvaluatorBinding?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14835)
=> Put GeometryPairContactWrenchEvaluatorBinding in the public namespace.

bindings/pydrake/common/test/numpy_compare_test.py, bindings/pydrake/common/test_utilities/numpy_compare.py, bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14823)
=> Allow python binding of SignalLogger to log autodiffxd data.

bindings/pydrake/common/default_scalars_pybind.h, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/systems/primitives_py.cc
Add doxygen group
Switch docstrings from /// to use /** */
Fix minor typos in helper functions
Follow-up to #14823
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14839)
=> default_scalars_pybind: Consolidate CopyIfNotPodType functions

systems/trajectory_optimization/direct_transcription.cc, systems/trajectory_optimization/test/direct_transcription_test.cc
It turns out that it actually DID support it already, but there were some old DRAKE_DEMANDs that were erroneously blocking the execution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14840)
=> DirectTranscription class supports continuous-time MultibodyPlant

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14845)
=> bind all scalar types for wrap_to

systems/trajectory_optimization/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14854)
=> CI fix: Remove test from asan until its timeout issue is addressed.

bindings/pydrake/symbolic_py.cc, common/symbolic_decompose.h
fyi @hongkai-dai 
before
after
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14861)
=> mixed doxygen comment style was suppressing doxygen in symbolic_decompose.h

tools/workspace/pycodestyle/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14850)
=> workspace: Upgrade pycodestyle to latest release 2.7.0

tools/workspace/ghc_filesystem/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14851)
=> workspace: Upgrade ghc_filesystem to latest release 1.5.4

tools/workspace/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/ignition_utils/BUILD.bazel, tools/workspace/ignition_utils/package.BUILD.bazel, tools/workspace/ignition_utils/repository.bzl, tools/workspace/sdformat/package.BUILD.bazel
This will be required by sdformat 11.0.0 (#14852).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14853)
=> workspace: Add ignition_utils 1.0.0

solvers/clp_solver.cc, solvers/test/clp_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14820)
=> Retrieve dual solution from CLP solver.

tools/workspace/ignition_math/package.BUILD.bazel, tools/workspace/ignition_math/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14848)
=> workspace: Upgrade ignition_math to latest release 6.8.0

setup/ubuntu/binary_distribution/packages-bionic.txt, setup/ubuntu/binary_distribution/packages-focal.txt, setup/ubuntu/source_distribution/packages-bionic.txt, setup/ubuntu/source_distribution/packages-focal.txt, tools/workspace/default.bzl, tools/workspace/opencl/BUILD.bazel, tools/workspace/opencl/package-macos.BUILD.bazel, tools/workspace/opencl/package-ubuntu.BUILD.bazel, tools/workspace/opencl/repository.bzl, tools/workspace/opengl/repository.bzl, tools/workspace/voxelized_geometry_tools/package.BUILD.bazel, tools/workspace/voxelized_geometry_tools/repository.bzl
Adds OpenCL build support, and enables the OpenCL backend implementation in `voxelized_geometry_tools`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14843)
=> Add OpenCL support

geometry/proximity/test/obj_to_surface_mesh_test.cc, tools/workspace/tinyobjloader/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14866)
=> workspace: Upgrade tinyobjloader to latest commit

tools/workspace/rules_pkg/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14867)
=> workspace: Upgrade rules_pkg to latest release 0.4.0

bindings/pydrake/solvers/mathematicalprogram_py.cc
Follow up PR of #14790
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14883)
=> Fix the deprecation time of a Polynomial function.

setup/mac/binary_distribution/Brewfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14888)
=> Obtain ibex@2.7.4 formula from robotlocomotion/director tap

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py
Removes/Modifies deprecated code that was introduced in #14292.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14889)
=> Remove deprecated code in meshcat visualizer and tests

bindings/pydrake/solvers/mathematicalprogram_py.cc, solvers/mathematical_program.h, solvers/osqp_solver.cc, solvers/solver_options.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14886)
=> Expose all parameters of OSQP solver.

tools/workspace/doxygen/repository.bzl
Hotfix for #14892.
Closes #14895.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14896)
=> workspace: Nerf Doxygen on macOS

doc/_pages/release_playbook.md, doc/_release-notes/older_releases.md, doc/_release-notes/release_notes.md, doc/_release-notes/template.txt, doc/_release-notes/v0.10.0.md, doc/_release-notes/v0.11.0.md, doc/_release-notes/v0.12.0.md, doc/_release-notes/v0.13.0.md, doc/_release-notes/v0.14.0.md, doc/_release-notes/v0.15.0.md, doc/_release-notes/v0.16.0.md, doc/_release-notes/v0.16.1.md, doc/_release-notes/v0.17.0.md, doc/_release-notes/v0.18.0.md, doc/_release-notes/v0.19.0.md, doc/_release-notes/v0.20.0.md, doc/_release-notes/v0.21.0.md, doc/_release-notes/v0.22.0.md, doc/_release-notes/v0.23.0.md, doc/_release-notes/v0.24.0.md, doc/_release-notes/v0.25.0.md, doc/_release-notes/v0.26.0.md, doc/_release-notes/v0.27.0.md, doc/_release-notes/v0.28.0.md
This was a requested usability feature a little while ago.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14891)
=> doc: Add dates to list of releases

systems/analysis/BUILD.bazel, systems/analysis/test/simulator_test.cc
Relevant to: #14543, #14802
This is the beginning of a PR train to make heapless simulation
possible, with careful system construction.  All the good ideas are
inspired by @edrumwri's PR #14707; all the sketchy ones are mine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14900)
=> simulator: Add test to track heap hygiene

systems/analysis/BUILD.bazel, systems/analysis/test/simulator_limit_malloc_test.cc, systems/analysis/test/simulator_test.cc
Workaround due to #14901
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14902)
=> simulator_test: Move LimitMalloc test; skip separate test on --config=asan

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/geometry_set.h, geometry/test/geometry_set_test.cc
Resolves #14873
FYI @SeanCurtis-TRI - this is currently a WIP tho; just zombie-mode programming while watching GTC conference :grimacing:
EDIT: Began basic upstreaming; I think this could still be reviewed tho: https://github.com/pybind/pybind11/pull/2950
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14898)
=> py geometry: Bind additional GeometrySet methods

tools/workspace/pypi_wheel.bzl
Relates #14878, needed for CastXML, but probably generally useful.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14906)
=> Split out ability to download and extract a wheel from PyPI

common/test_utilities/limit_malloc.cc, common/test_utilities/test/limit_malloc_test.cc
Closes #14901.
ASAN instrumentation hooks more heap-returning API than just the basic
set. strdup() is one; there may be others. The returned heap blocks come
from a private heap and can't be returned by libc's free(). Avoid the
potential crashes by removing hooks completely when ASAN is detected at
compile time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14905)
=> limit_malloc: Avoid ASAN heap hazard

setup/mac/binary_distribution/requirements.txt, setup/mac/source_distribution/install_prereqs.sh, setup/mac/source_distribution/requirements.txt
Fixes a misclassification in #14784.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14907)
=> Move semantic-version to source distribution requirements

bindings/pydrake/manipulation/simple_ui.py, bindings/pydrake/multibody/jupyter_widgets.py, bindings/pydrake/systems/jupyter_widgets.py, bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/perception.py, bindings/pydrake/systems/system_sliders.py, examples/manipulation_station/differential_ik.py
Resolves #12590
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14915)
=> pydrake: Replace "System YAML" with proper ".. pydrake_system::" directive

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/pgs_solver.cc, multibody/contact_solvers/pgs_solver.h, multibody/contact_solvers/test/pgs_solver_test.cc
PGS solver implements the ContactSolver interface. The algorithm follows
that from the paper Realistic Haptic Rendering of Interacting
Deformable Objects in Virtual Environments by Duriez et al. in 2005.
Co-authored-by: Alejandro Castro <alejandro.castro@tri.global>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14844)
=> Implement PGS contact solver

doc/build.py
I guess I was having a bad day when I wrote this. I need add schema validation and a test at some point, obviously.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14909)
=> Fix sitemap.xml entries for index pages

doc/_release-notes/v0.29.0.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14921)
=> doc: Fix incorrect link in release notes v0.29.0

multibody/parsing/BUILD.bazel, multibody/parsing/process_model_directives.cc, multibody/parsing/test/process_model_directives_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14923)
=> parsing: Improve model directives diagnostic when file not found

tools/workspace/voxelized_geometry_tools/repository.bzl
Bumps VGT with minor change to device point cloud voxelization API that allows the raycasting process to be restructured. Improved GPU raycasting implementations offer >= 2x performance (CPU implementation performance improves as well, but not as significantly).
+@ggould-tri for review, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14919)
=> Bump VGT with raycasting performance improvements

doc/BUILD.bazel, doc/_pages/documentation_instructions.md, doc/build.py, doc/defs.py, doc/doxygen_cxx/BUILD.bazel, doc/doxygen_cxx/Doxyfile_CXX.in, doc/doxygen_cxx/build.py
Towards #14803. (That PR contains more example uses of the `defs.py` common helpers, as well as new `drake/doc/_pages/documentation_instructions.md` that show the overall UX goal.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14834)
=> doc: Refactor Doxygen builds to use common code

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/angle_between_vectors_constraint.cc, multibody/inverse_kinematics/com_position_constraint.cc, multibody/inverse_kinematics/com_position_constraint.h, multibody/inverse_kinematics/gaze_target_constraint.cc, multibody/inverse_kinematics/kinematic_constraint_utilities.h, multibody/inverse_kinematics/orientation_constraint.cc, multibody/inverse_kinematics/orientation_constraint.h, multibody/inverse_kinematics/position_constraint.cc, multibody/inverse_kinematics/test/com_position_constraint_test.cc, multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc, multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.h
One step towards #14914
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14918)
=> Add ComPositionConstraint

solvers/BUILD.bazel, solvers/gurobi_solver.cc, solvers/test/gurobi_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14930)
=> Set the string option in GurobiSolver

solvers/BUILD.bazel, solvers/choose_best_solver.cc, solvers/clp_solver.cc, solvers/clp_solver_common.cc, solvers/mathematical_program_doxygen.h, solvers/test/clp_solver_test.cc, solvers/test/quadratic_program_examples.cc
As discussed in https://github.com/RussTedrake/manipulation/issues/140#issuecomment-817383407
@hjsuh94
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14894)
=> Enable CLP to solve QP.

doc/doxygen_cxx/build.py, multibody/constraint/constraint_doxygen.h, multibody/plant/contact_model_doxygen.h, multibody/plant/multibody_plant.h, multibody/tree/door_hinge.h, multibody/tree/joint.h, multibody/tree/joint_actuator.h, multibody/tree/linear_bushing_roll_pitch_yaw.h, systems/framework/cache_doxygen.h
Hotfix for #14834.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14931)
=> doc: Restore missing C++ API images

solvers/clp_solver.cc, solvers/clp_solver.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14934)
=> Warn about the memory issue when solving a QP with CLP

bindings/pydrake/_autodiffutils_extra.py, bindings/pydrake/test/autodiffutils_test.py
Per Slack convo: https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1619004863032400
Dunno what better naming should be, though.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14937)
=> py autodiff: Add autodiff_equal_to

solvers/BUILD.bazel, solvers/snopt_solver.cc, solvers/test/snopt_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14947)
=> solvers: Report error when snopt fails to set a solver parameter

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
Fixes #14874.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14953)
=> Add Python binding for GetForceElement

bindings/pydrake/multibody/optimization_py.cc, bindings/pydrake/multibody/test/optimization_test.py, multibody/inverse_kinematics/com_position_constraint.h, multibody/inverse_kinematics/kinematic_constraint_utilities.cc, multibody/inverse_kinematics/kinematic_constraint_utilities.h, multibody/optimization/BUILD.bazel, multibody/optimization/centroidal_momentum_constraint.cc, multibody/optimization/centroidal_momentum_constraint.h, multibody/optimization/test/centroidal_momentum_constraint_test.cc
A step towards #14914
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14925)
=> add CentroidalMomentumConstraint

setup/mac/binary_distribution/install_prereqs.sh, setup/mac/source_distribution/install_prereqs.sh
Relates #14920.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14962)
=> Do not pass --upgrade to pip3.9 on macOS

tools/workspace/buildifier/repository.bzl
https://github.com/bazelbuild/buildtools/releases/tag/4.0.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14964)
=> workspace: Upgrade buildifier to latest release 4.0.1

tools/install/bazel/test/drake_bazel_installed_test.py, tools/workspace/rules_python/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14966)
=> workspace: Upgrade rules_python to latest release 0.2.0

tools/workspace/scs/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14970)
=> workspace: Upgrade scs to latest release 2.1.3

bindings/pydrake/_math_extra.py, bindings/pydrake/test/math_test.py
Closes #13987.  Relates #8586.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14993)
=> pydrake: Add repr for RotationMatrix, RigidTransform

doc/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15001)
=> add link to blog post from the drake website

systems/primitives/affine_system.cc, systems/primitives/test/affine_system_test.cc
I ran into a case where I couldn't linearize a discrete-time system that also had an LQR controller in the diagram (because there were multiple state groups), even though the LQR controller should have been stateless.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15003)
=> primitives: do not declare state variables in AffineSystem if num_states==0

systems/framework/diagram.cc, systems/framework/system.cc, systems/framework/system.h
Resolves a review comment raised in PR #14378.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14999)
=> system: Deprecate and rename ValidateChildOfContext()

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/com_in_polyhedron_constraint.cc, multibody/inverse_kinematics/com_in_polyhedron_constraint.h, multibody/inverse_kinematics/test/com_in_polyhedron_constraint_test.cc
A step towards #14914
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14946)
=> Add ComInPolyhedronConstraint

math/rotation_matrix.cc, math/rotation_matrix.h, math/test/rotation_matrix_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14816)
=> New method for forming a rotation matrix from a single unit vector.

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_com_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h
Calculate the total mass of a MultibodyPlant or designated model instances to resolve issue #14913.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14957)
=> Total mass of MBP or model instances.

bindings/pydrake/multibody/optimization_py.cc, bindings/pydrake/multibody/test/optimization_test.py, multibody/optimization/BUILD.bazel, multibody/optimization/quaternion_integration_constraint.cc, multibody/optimization/quaternion_integration_constraint.h, multibody/optimization/test/quaternion_integration_constraint_test.cc
Towards #14956
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14960)
=> Add QuaternionEulerIntegrationConstraint

bindings/pydrake/systems/sensors_py.cc, geometry/render/gl_renderer/render_engine_gl.cc, geometry/render/gl_renderer/test/render_engine_gl_test.cc, geometry/render/render_engine_vtk.cc, geometry/render/test/render_engine_vtk_test.cc, perception/depth_image_to_point_cloud.cc, systems/sensors/image.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15027)
=> sensors: Deprecate InvalidDepth and Label constants

systems/analysis/test/simulator_limit_malloc_test.cc
This is the sixth of a long PR train to make heapless simulation
This patch expands heap-allocation testing to cover all event types and
schedules.
Subsequent patches will remove the heap allocations tracked here.
Subsequent patches will expand this technique (and test coverage) to the
other event types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15010)
=> simulator_limit_malloc_test: Cover all event types

examples/scene_graph/simple_contact_surface_vis.cc, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
Fix #14578. Make sure that contact spatial force is no longer duplicated 
in hydroelastic visualization. Modify the simple_contact_surface_vis 
example so that it verifies the fix.
Make two other incremental improvements to hydroelastic visualization:
1. Instead of visualizing the contact surfaces as two offset surfaces,
visualize the actual contact surface as a single entry in scene browser
2. Give a more descriptive name to the spatial force entry in the scene
browser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15000)
=> [visualization] Fix bug in hydroelastic visualization

bindings/pydrake/solvers/test/mathematicalprogram_test.py
The prior unit test was pretending an argument-mismatch exception was a "cannot solve" message.  Here instead, we try to slightly more carefully illustrate what a solver back-end in Python should maybe look like.
Amends #12866.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15036)
=> pydrake: Clarify tests for SolverInterface::Solve

multibody/optimization/manipulator_equation_constraint.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15047)
=> optimization: resolve minor TODO in ManipulatorEquationConstraint

math/BUILD.bazel, math/rigid_transform.cc, math/rigid_transform.h, math/roll_pitch_yaw.cc, math/roll_pitch_yaw.h, math/test/rigid_transform_test.cc, math/test/roll_pitch_yaw_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14910)
=> Add human-readable output stream operator for RollPitchYaw and RigidTransform per issue  #14699.

solvers/scs_solver_common.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15053)
=> scs solver capability use never_destroyed

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/BUILD.bazel, solvers/aggregate_costs_constraints.cc, solvers/aggregate_costs_constraints.h, solvers/clp_solver_common.cc, solvers/cost.cc, solvers/cost.h, solvers/create_cost.cc, solvers/create_cost.h, solvers/gurobi_solver_common.cc, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/mosek_solver_common.cc, solvers/osqp_solver_common.cc, solvers/scs_solver_common.cc, solvers/test/aggregate_costs_constraints_test.cc, solvers/test/clp_solver_test.cc, solvers/test/cost_test.cc, solvers/test/gurobi_solver_test.cc, solvers/test/ipopt_solver_test.cc, solvers/test/mathematical_program_test.cc, solvers/test/mosek_solver_test.cc, solvers/test/nlopt_solver_test.cc, solvers/test/osqp_solver_test.cc, solvers/test/quadratic_program_examples.cc, solvers/test/quadratic_program_examples.h, solvers/test/scs_solver_test.cc, solvers/test/snopt_solver_test.cc
Resolves #15008
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15043)
=> Add is_convex flag to each QuadraticCost

solvers/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15071)
=> factor out the common component in solvers/BUILD.bazel

bindings/pydrake/multibody/test/optimization_test.py
The logic has been test in C++ with two spheres.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15076)
=> Remove two boxes static equilibrium test in Python.

solvers/aggregate_costs_constraints.cc, solvers/aggregate_costs_constraints.h, solvers/clp_solver.h, solvers/clp_solver_common.cc, solvers/gurobi_solver.h, solvers/gurobi_solver_common.cc, solvers/mosek_solver.h, solvers/mosek_solver_common.cc, solvers/osqp_solver_common.cc, solvers/scs_solver.h, solvers/scs_solver_common.cc, solvers/test/aggregate_costs_constraints_test.cc, solvers/test/optimization_examples.cc, solvers/test/quadratic_program_examples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15059)
=> Solver explains that one quadratic cost is non-convex.

multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/test/multibody_tree_test.cc
This is preparatory work for improving the error messages from these methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15078)
=> multibody: Relocate many MbT method definitions to cc file

doc/_pages/developers.md, setup/ubuntu/source_distribution/install_prereqs.sh
https://github.com/bazelbuild/bazel/releases/tag/4.1.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15086)
=> setup: Upgrade recommended Bazel version to 4.1

tutorials/quadratic_program.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15077)
=> In QP tutorial, mention the convexity check on the quadratic cost

examples/multibody/cart_pole/test/cart_pole_test.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_forward_dynamics_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/plant/test/propeller_test.cc, multibody/tree/multibody_tree_system.cc, multibody/tree/multibody_tree_system.h
Resolves #13164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15048)
=> multibody: implements DoCalcImplicitTimeDerivativesResidual for MBP

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/ipopt_solver_test.py, bindings/pydrake/solvers/test/snopt_solver_test.py
Towards #15106.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15107)
=> pydrake: Add bindings for SolverInterface::enabled

bindings/pydrake/common/module_py.cc, bindings/pydrake/common/test/module_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15108)
=> Remove deprecated code 2021-06

tools/workspace/ghc_filesystem/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15109)
=> workspace: Upgrade ghc_filesystem to latest release 1.5.6

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/analysis/test/monte_carlo_test.cc, systems/primitives/BUILD.bazel, systems/primitives/random_source.cc, systems/primitives/random_source.h, systems/primitives/test/random_source_test.cc, systems/sensors/test/beam_model_test.cc
Co-authored by jeremy.nimmer@tri.global
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15092)
=> templatize RandomSource.

tools/workspace/ros_xacro/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15111)
=> workspace: Upgrade ros_xacro to latest release 1.13.11

tools/workspace/googlebenchmark/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15110)
=> workspace: Upgrade googlebenchmark to latest release 1.5.4

tools/workspace/intel_realsense_ros/repository.bzl
Even with the minor bump, it still matches the Melodic version (see https://index.ros.org/p/realsense2_description/).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15113)
=> workspace: Upgrade intel_realsense_ros to latest release 2.3.0

bindings/pydrake/pydrake_doxygen.h
Part of this is specific to pydrake bindings, but can still be helpful
for pybind11 in general.
Motivation: @dmcconachie-tri is doing some bindings in Anzu; I mentioned this, and found it'd prolly be good to document this. Not immediately necessary for his purpose, but will most likely come up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15100)
=> pydrake doc: Add mention about binding dependencies on public API

systems/framework/BUILD.bazel, systems/framework/discrete_values.h, systems/framework/test/discrete_values_limit_malloc_test.cc
Closes: #14802.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15118)
=> discrete values: Avoid heap in non-converting SetFrom()

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15127)
=> solvers: add missing binding for AddLinearCost

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/cost.cc, solvers/cost.h, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc, tutorials/nonlinear_program.ipynb, tutorials/quadratic_program.ipynb
Resolves #15124
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15134)
=> Rename AddL2NormCost to Add2NormSquaredCost

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15136)
=> bind Monomial() constructor.

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15138)
=> Add python binding for monomil * float -> polynomial

bindings/pydrake/solvers/mathematicalprogram_py.cc
I didn't realize how many bindings we are missing from mathematical program.  This PR has no functional change... it only reorders the existing bindings to match the order in `mathematical_program.h`.  This will make it much easier to go through and systematically add the missing bindings.
Note: `mathematical_program.h` could probably use some re-ordering, too.  But this is a start.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15141)
=> solvers: reorder bindings to match order in mathematical_program.h

tutorials/BUILD.bazel, tutorials/multibody_plant_autodiff_mass.ipynb
nbviewer preview: https://nbviewer.jupyter.org/github/EricCousineau-TRI/drake/blob/feature-tutorial-mbp-inertial-diff/tutorials/multibody_plant_autodiff_mass.ipynb
Context:
- StackOverflow: https://stackoverflow.com/q/67754125/7829525
- [Drake Slack](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1622172889020700)
\cc @RussTedrake @sadraddini 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15103)
=> tutorials: Show derivatives of basic mbp computations w.r.t. mass

solvers/BUILD.bazel, solvers/gurobi_solver.h, solvers/mosek_solver.h, solvers/snopt_solver.h, solvers/solver_base.cc, solvers/solver_interface.h, solvers/test/gurobi_solver_grb_license_file_test.cc, solvers/test/mosek_solver_moseklm_license_file_test.cc, solvers/test/solver_base_test.cc
Also improve error messages in case either of them are false.
Closes #15106.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15114)
=> solvers: Improve documentation of available() vs enabled()

systems/analysis/hermitian_dense_output.h, systems/analysis/simulator.h, systems/analysis/test_utilities/implicit_integrator_test.h, systems/framework/diagram.cc, systems/framework/input_port.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/output_port.h, systems/framework/scalar_conversion_traits.h, systems/framework/system.h, systems/framework/system_base.h, systems/framework/system_type_tag.h, systems/framework/test/vector_system_test.cc, systems/framework/value_to_abstract_value.h, systems/framework/vector_system.h, systems/primitives/random_source.cc, systems/primitives/symbolic_vector_system.cc, systems/primitives/test/random_source_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15148)
=> systems: Use C++17 spellings for type_traits

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
Due to the slack discussion https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1623171903015700
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15146)
=> Add python binding for LinearMatrixInequalityConstraint.

common/BUILD.bazel, common/random.cc, common/random.h, common/test/random_test.cc, systems/primitives/BUILD.bazel, systems/primitives/linear_transform_density.cc, systems/primitives/linear_transform_density.h, systems/primitives/test/linear_transform_density_test.cc
As discussed in #15061
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15116)
=> add LinearTransformDensity.

geometry/geometry_state.h, geometry/proximity/test/penetration_as_point_pair_callback_test.cc, geometry/proximity_engine.cc, geometry/scene_graph.h, geometry/shape_specification.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15149)
=> geometry: Use C++17 spellings for type_traits

multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.h, multibody/contact_solvers/contact_solver_utils.h, multibody/fixed_fem/dev/constitutive_model.h, multibody/fixed_fem/dev/elasticity_element.h, multibody/fixed_fem/dev/isoparametric_element.h, multibody/fixed_fem/dev/quadrature.h, multibody/inverse_kinematics/kinematic_constraint_utilities.h, multibody/inverse_kinematics/test/com_position_constraint_test.cc, multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.h, multibody/optimization/contact_wrench_evaluator.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree.h, multibody/tree/rotational_inertia.h, multibody/tree/test/multibody_tree_indexes_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15153)
=> multibody: Use C++17 spellings for type_traits

solvers/binding.h, solvers/branch_and_bound.h, solvers/constraint.cc, solvers/constraint.h, solvers/create_constraint.h, solvers/create_cost.h, solvers/gurobi_solver.cc, solvers/mathematical_program.h, solvers/mathematical_program_result.h, solvers/mixed_integer_optimization_util.h, solvers/mosek_solver.cc, solvers/snopt_solver.cc, solvers/test/branch_and_bound_test.cc, solvers/test/cost_test.cc, solvers/test/mathematical_program_test.cc, solvers/test/mixed_integer_optimization_util_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15155)
=> solvers: Use C++17 spellings for type_traits

bindings/pydrake/common/deprecation_pybind.h, bindings/pydrake/common/test/type_pack_test.cc, bindings/pydrake/common/test/wrap_function_test.cc, bindings/pydrake/common/type_pack.h, bindings/pydrake/common/value_pybind.h, bindings/pydrake/common/wrap_function.h, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/solvers/mathematicalprogram_py.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15156)
=> bindings: Use C++17 spellings for type_traits

doc/_release-notes/template.txt
We've been adding this section for the past few releases; it's time to make it official.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15158)
=> doc: Add build deps section release notes template

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.h
Also reorders `mathematical_program.h` to put the similar functions next to each other.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15167)
=> Add remaining bindings for mathematical program.

multibody/contact_solvers/block_sparse_matrix.h, multibody/contact_solvers/test/block_sparse_matrix_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15162)
=> Allow to overestimate the capacity for block sparse matrices

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/module_py.cc, bindings/pydrake/common/test/module_test.py, bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, common/random.cc, common/random.h, common/test/random_test.cc, systems/primitives/linear_transform_density.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15166)
=> Add python binding for LinearTransformDensity

systems/controllers/inverse_dynamics.cc, systems/controllers/inverse_dynamics.h
Also add a missing const for clarity.
Discovered as part of #15161 audit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15175)
=> controllers: Remove redundant syntax for DeclareCacheEntry

solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
Fix a bug in GetAllConstraints(), that the exponential cone constraints are not included.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15180)
=> Move the function definition from mathematical_program.h to cc file.

geometry/render/render_doxygen.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15183)
=> :pencil: Fixed typo deend -> depend in geometry/render/render_doxygen.h 

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
Discovered as part of #15161 audit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15176)
=> multibody: Remove redundant syntax for DeclareCacheEntry

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15185)
=> Add python binding for TaylorExpand.

geometry/benchmarking/mesh_intersection_benchmark.cc, geometry/proximity/contact_surface_utility.h, geometry/proximity/hydroelastic_callback.h, geometry/proximity/mesh_intersection.cc, geometry/proximity/mesh_intersection.h, geometry/proximity/test/mesh_intersection_test.cc, geometry/proximity/test/mesh_to_vtk_test.cc
Another step for issue #14579.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15131)
=> [geometry] Parameter to select output format from mesh intersection.

solvers/non_convex_optimization_util.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15191)
=> solvers: add doxygen tag to another constraint method

common/eigen_types.h, examples/rod2d/test/rod2d_test.cc, multibody/benchmarks/kuka_iiwa_robot/MG/MG_kuka_iiwa_robot.cc, solvers/test/optimization_examples.cc, solvers/test/optimization_examples.h, solvers/test/quadratic_program_examples.cc, solvers/test/quadratic_program_examples.h, solvers/test/sdpa_free_format_test.cc, systems/framework/test/continuous_state_test.cc, systems/primitives/test/symbolic_vector_system_test.cc
It's common enough.  I was surprised that it wasn't defined by Eigen nor by us yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15192)
=> common: Add Vector6d to eigen_types

multibody/contact_solvers/test/contact_solver_test.cc, multibody/fixed_fem/dev/deformable_model.h, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/fixed_fem/dev/run_cantilever_beam.cc, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, multibody/plant/BUILD.bazel, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/physical_model.cc, multibody/plant/physical_model.h, multibody/plant/scalar_convertible_component.h, multibody/plant/test/discrete_update_manager_test.cc, multibody/plant/test/dummy_model.h, multibody/plant/test/multibody_plant_scalar_conversion_test.cc, multibody/plant/test/physical_model_test.cc, systems/framework/system_scalar_converter.cc, systems/framework/system_scalar_converter.h, systems/framework/test/system_scalar_converter_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15135)
=> Support scalar conversion for PhysicalModel and DiscreteUpdateManager

examples/manipulation_station/BUILD.bazel, examples/manipulation_station/manipulation_station.cc, examples/manipulation_station/manipulation_station.h, examples/manipulation_station/mock_station_simulation.cc, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/BUILD.bazel, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/__init__.py, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_cloud.py, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/use_builtin_scripts.py
Patch drake_visualizer to show Drake point clouds.
Resolves #14985 towards #14362.
~Requires #14982 and #14990 first.~
Screenshot at https://github.com/RobotLocomotion/drake/issues/14985#issuecomment-830468107.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14991)
=> [manipulation_station] Optionally publish point clouds in sim

multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h
Noted while adding one more forwarded function dur #15161.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15193)
=> [multibody] Tidy up attorney declaration order

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/primitives/linear_transform_density.cc, systems/primitives/linear_transform_density.h, systems/primitives/test/linear_transform_density_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15189)
=> Add an output for density in LinearTransformDensity.

tools/workspace/vtk/Dockerfile, tools/workspace/vtk/build_binaries_with_docker, tools/workspace/vtk/repository.bzl
A rebuild of the binaries will follow in the next day or so, I hope.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15171)
=> Remove compiled Python files when building VTK binaries

setup/mac/binary_distribution/install_prereqs.sh, setup/mac/source_distribution/install_prereqs.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15202)
=> Allow robotlocomotion/director to change default branch name to main

examples/kinova_jaco_arm/BUILD.bazel, examples/kinova_jaco_arm/jaco_controller.cc, examples/kinova_jaco_arm/move_jaco_ee.cc, manipulation/kinova_jaco/jaco_command_receiver.cc
Fixes #14593
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15203)
=> Fix the Jaco example to work on real hardware (not just sim)

tools/workspace/dreal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15212)
=> workspace: Upgrade dreal to latest release 4.21.06.2

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/all.py, bindings/pydrake/solvers/dreal_py.cc, bindings/pydrake/solvers/test/dreal_solver_test.py, solvers/dreal_solver.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15215)
=> solvers: Add python bindings for DrealSolver

geometry/proximity/hydroelastic_callback.h, geometry/proximity/test/hydroelastic_callback_test.cc, geometry/proximity/test/mesh_intersection_test.cc, geometry/proximity_engine.cc
Another step for  [implementation plan for 14579](https://github.com/RobotLocomotion/drake/issues/14579#issuecomment-843618123).  After this PR #15200(hydroelastic_callback), the next PR is #15204(ProximityEngine).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15200)
=> [geometry] Parameter to choose output format in hydroelastic_callback.

solvers/test/ipopt_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15230)
=> Buildcop:  Disable tests failing due to #15229

bindings/pydrake/systems/test/lcm_test.py
This illustrates how to use a Python leaf system to output messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15220)
=> [pydrake] Add test case for PythonMessageSource

multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15225)
=> Add discrete contact pairs cache entry

doc/_pages/release_playbook.md
Use `<url>` instead of `[url](url)`
Ensure `<url>` is used instead of `url`; otherwise, URL may not render
Add backticks around GitHub username
Minor fixes to follow-up on #15207
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15236)
=> release_playbook: Minor formatting fixes for URLs

doc/_pages/buildcop.md, doc/_pages/issues.md, doc/_pages/jenkins.md, doc/_pages/release_playbook.md, tools/workspace/drake_visualizer/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15239)
=> Change the name of the Kitware contact

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/test/convex_set_test.cc, tools/install/libdrake/build_components.bzl
As discussed in the design doc: https://docs.google.com/document/d/12dZ1WJVxuWHxzIIu6X4dsPnj2SRdDyknOIReiPBADw0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15194)
=> Establish geometry/optimization to facilitate optimization with and for SceneGraph geometries

solvers/constraint.h, solvers/cost.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15246)
=> solvers: add doxygen group tags to more costs/constraints

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/test/convex_set_test.cc
for the HPolyhedron class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15243)
=> geometry:optimization: implement Maximum-Volume Inscribed Ellipsoid

solvers/BUILD.bazel, solvers/test/ipopt_solver_test.cc
Closes #15229.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15249)
=> [solvers] Remove hard-coded IPOPT enums from tests

geometry/optimization/BUILD.bazel, geometry/optimization/test/convex_set_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15251)
=> geometry:optimization: small refactor to purge multibody dependency

solvers/scs_solver.cc, solvers/solve.h, solvers/test/scs_solver_test.cc
cc @RussTedrake 
As mentioned in https://github.com/RobotLocomotion/drake/pull/15251#issuecomment-870105746
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15257)
=> ScsSolver defaults not to print

multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15264)
=> [multibody] Remove CalcDiscreteContactPairs update manager forwarding

geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/test/convex_set_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15266)
=> geometry:optimization: Add Clone method to ConvexSet hierarchy.

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/csdp_py.cc, bindings/pydrake/solvers/test/csdp_solver_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15274)
=> Add python binding for the constructor argument in CsdpSolver

solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
This is very useful for writing unit tests on constraints, and parallels the existing EvalBinding methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15268)
=> solvers: Add MathematicalProgram::CheckSatisfied

solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
This bug was noticed by @jwnimmer-tri in https://github.com/RobotLocomotion/drake/issues/15178#issuecomment-865494916
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15253)
=> Check the variable type in AddDecisionVariables

multibody/parsing/test/detail_sdf_parser_test.cc
This helps to avoid spurious Mac CI failures
Resolves #15294 (as a workaround)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15295)
=> detail_sdf_parser_test: Make ParseTestString use string, not file

tools/install/bazel/test/drake_bazel_installed_test.py, tools/workspace/rules_python/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15289)
=> [workspace] Upgrade rules_python to latest release 0.3.0

tools/workspace/sdformat/repository.bzl
\cc @EricCousineau-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15301)
=> workspace: Upgrade libsdformat to latest release 11.2.2

tools/workspace/ghc_filesystem/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15293)
=> [workspace] Upgrade ghc_filesystem to latest release 1.5.8

solvers/BUILD.bazel, solvers/csdp_solver.cc, solvers/test/csdp_solver_internal_test.cc, solvers/test/csdp_solver_test.cc, solvers/test/sdpa_free_format_test.cc, tools/workspace/csdp/params_pathname.patch, tools/workspace/csdp/printlevel.patch, tools/workspace/csdp/repository.bzl
Users can use kPrintToConsole to opt-in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15281)
=> [solvers] Disable CsdpSolver console printing by default

tools/workspace/fcl/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15288)
=> [workspace] Bump fcl to latest commit

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/constraint.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15304)
=> Add python bindings for constraint constructor.

geometry/optimization/BUILD.bazel, geometry/optimization/hpolyhedron.cc, geometry/optimization/hyperellipsoid.cc, geometry/optimization/point.cc, geometry/optimization/point.h, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/hyperellipsoid_test.cc, geometry/optimization/test/point_test.cc, geometry/optimization/test_utilities.cc, geometry/optimization/test_utilities.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15302)
=> geometry:optimization: Add Point isa ConvexSet

geometry/optimization/BUILD.bazel, geometry/optimization/hpolyhedron.cc, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/test_utilities.h, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15308)
=> geometry:optimization: Add VPolytope isa ConvexSet

geometry/render/test/vtk_util_test.cc, geometry/render/vtk_util.cc, geometry/render/vtk_util.h
Towards #9865.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15303)
=> [render] Remove dead Isometry3-related utility function

tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
1. Change some default values:
- vector quantities are thicker
- initial maximum pressure is larger
- color map combo box shows images of color map.
2. The dialog is now modeless
- One doesn't have to configure and hit "Ok". Changes in the dialog are immediately reflected in the scene.
- This required a great deal of slots in the visualizer so that we would automatically trigger update information based on GUI events.
3. Coherency is maintained from frame to frame. So, if a particular contact is hidden, when the next message comes in, it remains hidden.
- We introduce the VisualModel which tracks the visual elements allowing us to strictly update.
4. Changing visual configuration affects what is currently displayed, one doesn't have to wait for the next lcm message to see the result.
- We …
=> [geometry] Multiple improvements to drake_visualizer hydroelastic contact visualization
