examples/manipulation_station/BUILD.bazel, examples/manipulation_station/mock_station_simulation.cc
This is a warm-up exercise before the next step of publishing the cameras' point clouds (#14985).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14982)
=> manipulation_station: Add LCM cameras to mock simulation

multibody/tree/joint_actuator.h
JointActuator's SetRotorInertia() and SetGearRatio() must be `const` since they only mutate the in/out context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14983)
=> Fixes constness of JointActuator's SetRotorInertia() and SetGearRatio()

geometry/proximity/BUILD.bazel, geometry/proximity/mesh_half_space_intersection.cc, geometry/proximity/test/mesh_half_space_intersection_test.cc
Dear @SeanCurtis-TRI ,
The on-call build cop, @BetsyMcPhail , believes that your PR #14943  may have
- https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-clang-bazel-continuous-address-sanitizer/3327/
- https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-clang-bazel-continuous-everything-address-sanitizer/3329/
- https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-focal-clang-bazel-continuous-release/1011/
- …
=> Revert "[geometry] Make soft half space/rigid mesh hydroelastic differentiable"

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py
The `frames_to_draw` argument in `ConnectMeshcatVisualizer` got accidentally deprecated in #14292 (this seems to be unintentional.) 
This is a tiny PR to add back the feature with the model inspector syntax.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14979)
=> Add back frame visualization in Meshcat

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/general_test.py, bindings/pydrake/systems/test/scalar_conversion_test.py, systems/framework/system.cc, systems/framework/system.h, systems/framework/system_base.cc, systems/framework/system_base.h, systems/framework/test/leaf_system_test.cc, systems/framework/test/system_test.cc
Closes: #13313.
Adds various ToScalarType<U> methods to System, after the manner of
To{AutoDiffXd,Symbolic}, and refactors all of them to use the single templated
implementation. Also adds python bindings and unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14986)
=> system: Support scalar conversion by template parameter

geometry/proximity/BUILD.bazel, geometry/proximity/plane.h, geometry/proximity/posed_half_space.h, geometry/proximity/test/plane_test.cc, geometry/proximity/test/posed_half_space_test.cc
`Plane::CalcHeight()` and `PosedHalfSpace::CalcSignedDistance()` can now support mixed numerical scalars (`double` and `AutoDiffXd`).
relates #14136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14951)
=> [geometry] Allow Plane and PoseHalfSpace to do mixed-scalar computation

geometry/proximity/BUILD.bazel, geometry/proximity/mesh_plane_intersection.cc, geometry/proximity/test/mesh_plane_intersection_test.cc
This work is about 5% tweaking the implementation and 95% testing.
1. Modifications to the underlying algorithm
- making sure use of scalars is consistent.
- Guaranteeing that even with `T = AutoDiffXd`, `Bvh` usage still works.
- deleting the "AutoDiff throws" implementation.
- incidental correction of notation error. I had frame P instead of
R.
2. Modifications to unit tests
- Elimination of "Autodiff throws" unit test.
- Introduction of tests on the derivatives of various quantities:
- Area, vertex position, normal direction, pressure.
relates #14136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14952)
=> [geometry] Make rigid plane/soft mesh hydroelastic differentiable

systems/sensors/image_to_lcm_image_array_t.cc, systems/sensors/image_to_lcm_image_array_t.h
The implementation was leaving the outer `msg->header.seq` unset.
The implementation strategy was also unclear as to why we were taking the long way around.  I suspect it was for efficiency's sake, so here we document that fact along with comments to explain its correctness, as well as removing a large inner loop heap use + redundant copy when compression was enabled.
In the header, also shuffle the constructor to the top of the class per the style guide, and also improve its API doc for clarity.
Disclaim a TODO to set the image sequence number.  Doing so would be an odd job for a feedthrough system.  Assigning a sequence number typically requires a clock.  This system should just leave it at zero.
--- …
=> sensors: Fix image_to_lcm_image_array uninitialized data

tools/workspace/voxelized_geometry_tools/BUILD.bazel
It no longer passes on macOS ([link](https://drake-cdash.csail.mit.edu/test/192474043)) after the latest Apple upgrade ([link](https://discussions.apple.com/thread/252710156)).
Later, we should re-enable this test, while ensuring that it is only tested on Ubuntu.  For now, the goal is just to put out the CI fires.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15005)
=> workspace: Disable voxelized_geometry_tools unit test

systems/controllers/test/pid_controlled_system_test.cc, systems/framework/system.cc, systems/framework/system.h, systems/framework/system_output.h
Add system-id labeling to the SystemOutput class, and use that to
implement checks using ValidateCreatedForThisSystem(). Retire the
expensive, and less-precise CheckValidOutput() method.
This should complete compatibility checking for public methods of
System<T>. Several other classes need work to be fully checked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15007)
=> system: Add compatibility checks for output using methods

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py, systems/analysis/test/simulator_limit_malloc_test.cc, systems/framework/event.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/test/leaf_system_test.cc
This is the fifth of a long PR train to make heapless simulation
This patch introduces a new callback type for PublishEvents that avoids
heap allocations induced by lambda captures.
Subsequent patches will expand this technique (and test coverage) to the
other event types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14969)
=> framework: Avoid functor allocation for PublishEvents

doc/_pages/docker.md, doc/_pages/from_binary.md
Related to #12783
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15016)
=> Website: Add `apt-get install drake-dev` instructions to Binary Installation page

math/test/rotation_matrix_test.cc
Some of the new tests depend on debug/release. The previous failures were only validated in release mode and the same bug was left in place for the debug code. This cleans that code up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15015)
=> [hotfix] Further correct mac fmt::format behavior in rotation matrix test

geometry/proximity/BUILD.bazel, geometry/proximity/mesh_intersection.cc, geometry/proximity/mesh_intersection.h, geometry/proximity/test/mesh_intersection_test.cc, geometry/proximity/test/mesh_plane_intersection_test.cc
- Update all signatures
- update the test to reflect the updated signatures
- Kill the old "AutoDiffXd throws" test
- Add full derivative testing
The unit test is a *direct* rip off of the plane-mesh intersection test. We replace the rigid plane with a rigid triangle, but otherwise all the math should be the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15012)
=> [geometry] Update mesh-mesh (rigid-soft) intersection to support AutoDiffXd

geometry/render/BUILD.bazel, geometry/render/render_engine_vtk.cc, geometry/render/test/vtk_util_test.cc, geometry/render/vtk_util.cc, geometry/render/vtk_util.h, systems/sensors/BUILD.bazel
Per the TODO in `systems/sensors`, this library is only used within `geometry/render` now so should live there.
I deem this _not_ to be a breaking change, because this header is not present in our binary releases.  If someone was using it via `drake_bazel_external`, that would be "own risk".
This gets us one step away from relying on VTK at runtime _only_ for the `RenderEngineVtk`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15025)
=> geometry/render: Move vtk_util here

multibody/plant/BUILD.bazel, multibody/plant/contact_permutation.cc, multibody/plant/contact_permutation.h, multibody/plant/test/contact_permutation_test.cc
Our current internal implementation of MultibodyPlant models orders dofs in a breadth-first traversal order. 
For everything we do today that is fine. However when building the sparse system of equations we need in our contact solvers for instance, this ordering leads to matrices (even the mass matrix) that look like gruyere cheese, with wholes (zeros) everywhere. 
Ideally we'd like depth-first ordering for these kind of operations, which leads to very nice block sparse structures we can exploit with custom algebra for this kind of sparsity (we are talking of a 10-20 X speed up here, not negligible at all).
Reordering dofs within MultibodyPlant, even if internal, is a major project. We must do it, but it's not the purpose of this PR. This PR is simply the first in a chain of PRs to offer …
=> Implements MultibodyPlant dofs permutation utility.

multibody/tree/multibody_tree.h
In Anzu, was debugging some code. I had a model `right::panda`, but code was referencing `panda`; I added `GetModelInstanceByName`, and noticed that space was missing :shrug: 
Before:
```
terminate called after throwing an instance of 'std::logic_error'
what():  There is no model instance named 'panda'in the model.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15042)
=> multibody_tree: Fix missing space for GetModelInstanceByName error

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/custom_test.py, examples/compass_gait/test/compass_gait_test.cc, systems/analysis/test/simulator_limit_malloc_test.cc, systems/framework/event.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/test/leaf_system_test.cc
This is the seventh of a long PR train to make heapless simulation
This patch extends the techniques of PR #14969 to all of the event
types.
Subsequent patches will address other sources of heap allocation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15032)
=> framework: Avoid functor allocation for all event types

geometry/proximity/test/mesh_half_space_intersection_test.cc, math/BUILD.bazel, math/fast_pose_composition_functions.cc, math/fast_pose_composition_functions.h, math/rotation_matrix.h, math/test/fast_pose_composition_functions_test.cc, math/test/rotation_matrix_test.cc
This is the first PR in a train leading up to #14768 which provides a family of AVX methods. Here we have just the infrastructure and the simplest AVX method for composition of two 3x3 rotation matrices.
Measured throughput in gigaflops (thanks to @joemasterjohn):
|              | ComposeRR() 
| ---------:|:---------:|
|   C++     |    5.38   |
|   AVX      | 14.16      |
| Speedup | **2.6X** |
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15013)
=> Add AVX infrastructure and one AVX composition method.

systems/primitives/affine_system.cc, systems/primitives/affine_system.h, systems/primitives/test/linear_system_test.cc
The output port of AffineSystem now responds to feedthrough queries without first scalar-converting itself to symbolic expressions.
This same change applies to LinearSystem, which inherits from AffineSystem.
This is likely to be more performant, and also ensures operation even for subclasses of affine or linear systems that choose not to support symbolic scalar conversion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15037)
=> primitives: Establish AffineSystem feedthrough without symbolics

bindings/pydrake/examples/quadrotor_py.cc, bindings/pydrake/examples/test/quadrotor_test.py, examples/quadrotor/quadrotor_geometry.h, examples/quadrotor/test/quadrotor_geometry_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15046)
=> quadrotor example: add getter for geometry frame

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_com_test.cc
Missed previously, perhaps owing to idiosyncratic date.
* drake::multibody::MultiBodyPlant::CalcCenterOfMassPosition
* all overloads
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15050)
=> Remove deprecated code 2021-04-21

bindings/pydrake/all.py, bindings/pydrake/test/all_test.py
Closes #15038.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15052)
=> pydrake: In pydrake.all, prefer pydrake.math over pydrake.symbolic

systems/trajectory_optimization/direct_collocation.cc
Not sure why those two variables were computed but never used.  The compiler probably optimized it out?  But I'm not sure why it didn't flag this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15051)
=> trajopt: remove unused variables from DirectCollocationConstraint

geometry/proximity/BUILD.bazel, geometry/proximity/hydroelastic_callback.h, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/test/hydroelastic_callback_test.cc, geometry/proximity_engine.cc, geometry/query_object.h, geometry/test/proximity_engine_test.cc
- Callback
- Eliminate the "unsupported" scalar code
- Correct bug in which a switch on enum had a default case.
- Unit test adds `AutoDiffXd` scalar to tests and tests for *presence* of appropriately sized derivatives (indicating derivative propagation).
- `ProximityEngine`
- Correct error that hydroelastic geometry was omitted in `ToAutoDiff()`
- Extend test to check for appropriately sized derivatives where expected. Previously, it expected an exception to be thrown.
- `QueryObject`
- Update documentation vis a vis scalar support
relates #10907, #14136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15040)
=> [geometry] Wire up hydroelastic derivatives all the way through QueryObject

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/BUILD.bazel, solvers/linear_system_solver.cc, solvers/linear_system_solver.h, solvers/osqp_solver.h, solvers/osqp_solver_common.cc, solvers/program_attribute.cc, solvers/program_attribute.h, solvers/solver_base.cc, solvers/solver_base.h, solvers/solver_interface.h, solvers/test/linear_system_solver_test.cc, solvers/test/osqp_solver_test.cc, solvers/test/program_attribute_test.cc, solvers/test/solver_base_test.cc
This is breaking change; any direct subclasses of SolverInterface need to implement the new ExplainUnsatisfiedProgramAttributes method.
Suggested order for code review:
- osqp_solver_test
- osqp_solver
- linear_system_solver_test
- linear_system_solver
- solver_interface
- solver_base and its unit test
- program_attribute and its unit test
- pydrake changes
Resolves #15019.  Closes #15020.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15028)
=> solvers: Amend SolverInterface for more detailed error messages

multibody/fixed_fem/dev/run_scripted_deformable_motion.cc
Need line continuation for it to be valid shell command
Also use `--` (POSIX) rather than vanilla `-` for flag
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15056)
=> run_scripted_deformable_motion: Fix minor typo in documentation

geometry/proximity/BUILD.bazel
Proximity used general declarations on `"//common"` a fair amount. This led to overly expansive dependencies. This simply pares down the declared dependencies to be more specific.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15057)
=> [geometry] Clean up geometry/proximity build dependencies

multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_com_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h
Resolve issue #14997.  Update CalcCenterOfMassPositionInWorld() and Make CalcCenterOfMassPositionInWorld() and CalcCenterOfMassTranslationalVelocityInWorld() so their calculations are consistent with the calculations in CalcTotalMass().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15054)
=> Make CalcCenterOfMassPositionInWorld() and CalcCenterOfMassTranslationalVelocityInWorld() consistent with CalcTotalMass().

geometry/proximity/surface_mesh.h, geometry/proximity/test/plane_test.cc, geometry/proximity/volume_mesh.h, lcm/drake_lcm_interface.h, multibody/contact_solvers/pgs_solver.h, multibody/fixed_fem/dev/damping_model.h, multibody/fixed_fem/dev/deformable_visualizer.h, multibody/fixed_fem/dev/test/fem_state_test.cc, multibody/parsing/test/process_model_directives_test/add_scoped_mid.yaml, multibody/plant/multibody_plant.h, multibody/tree/joint_actuator.h, multibody/tree/multibody_tree_system.h, multibody/tree/test/linear_bushing_roll_pitch_yaw_test.cc, solvers/mosek_solver.cc, tools/install/install_test_helper.py, tutorials/debug_mathematical_program.ipynb
These were found with `codespell`:
$ apt install codespell
$ codespell -wi3
A few false positives (binary files, identifiers that look like words) were
skipped.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15063)
=> Repair typos.

multibody/parsing/detail_scene_graph.cc, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/parser.h, multibody/parsing/test/detail_scene_graph_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/parser_test.cc, multibody/parsing/test/sdf_parser_test/all_geometries_as_collision.sdf, multibody/parsing/test/sdf_parser_test/all_geometries_as_visual.sdf, multibody/parsing/test/sdf_parser_test/include_models.sdf, multibody/parsing/test/sdf_parser_test/model_with_directly_nested_models.sdf, multibody/parsing/test/sdf_parser_test/world_with_directly_nested_models.sdf
Changes in behavior:
* Models nested via the `<include>` tag are no longer flattened, which means each included model will have its own model instance.
* `drake::multibody::Parser::AddAllModelsFromFile` now returns all added models including nested models
Note: This does not use a custom parser for URDFs via libsdformat's Interface API, and thus may incur unexpected behavior when including URDF files from SDFormat pending the full resolution of #14295.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14401)
=> parsing: Add support for SDFormat 1.8 model composition

common/symbolic_formula.h, common/test/symbolic_expression_test.cc
Specifically, specializations are added for isfinite, isinf, and isnan.
The specializations just forward to internal functions. The reason the
specializations are necessary is that the base templates rely on an
implicit conversion to bool but the internal functions return Formula
which only has an explicit conversion to bool.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15065)
=> Add template specializations for several Eigen::numext functions

geometry/proximity/BUILD.bazel, geometry/proximity/collision_filter_legacy.h, geometry/proximity/collisions_exist_callback.h, geometry/proximity/distance_to_shape_callback.h, geometry/proximity/make_box_field.cc, geometry/proximity/make_box_field.h, geometry/proximity/make_cylinder_field.cc, geometry/proximity/make_cylinder_field.h, geometry/proximity/penetration_as_point_pair_callback.h, geometry/proximity/test/characterization_utilities.h, geometry/proximity/test/penetration_as_point_pair_callback_test.cc
There are a number of header files (that directly lead to including fcl) that are marked to be installed. However, there were three header files that *are* installed that included them directly.
This removes those transitive references and shores up downstream code that lazily inherited headers via this path.
Resolves #14792
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15070)
=> [geometry] Corrects inconsistency in published/unpublished header files

bindings/pydrake/BUILD.bazel
These were added in #9603 at a time when our pydrake linking was broken.  We were linking the examples' libraries outside of libdrake.so, so their headers were not part of libdrake's headers, so for mkdoc to find them we needed to list them here individually.
Now that we link the examples correctly (i.e., directly into libdrake.so; see #9826), we no longer need to feed the redundant dependencies to mkdoc.
As of Bazel 4.1.0, the redundant headers actually break mkdoc, because we try to add these headers twice, with the second path spelling not matching any valid include path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15068)
=> pydrake: Remove spurious documentation header dependencies

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/BUILD.bazel, multibody/parsing/package_map.cc, multibody/parsing/package_map.h, multibody/parsing/test/package_map_test.cc, multibody/parsing/test/package_map_test_package_conflicting/package.xml
Adds/modifies several features to `PackageMap`:
- Makes `PackageMap` copy/move/assignable
- Changes `PackageMap::Add` to allow duplicate (package, path) to be added without throwing
- Adds `PackageMap::AddMap` to combine package maps
- Adds `PackageMap::GetPackageNames` to enumerate the packages mapped by the map
+@jwnimmer-tri for feature review, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15064)
=> Add features to PackageMap

tools/skylark/pybind.bzl
When collecting the list of package headers, in the case of the deprecation example (which has no package library) we were ending up with two different copies of the header being passed to mkdoc:
```
bazel-out/k8-opt/bin/bindings/pydrake/common/_virtual_includes/deprecation_example_class/drake/bindings/pydrake/common/test/deprecation_example/example_class.h
bindings/pydrake/common/test/deprecation_example/example_class.h
```
The first one is the path we want -- the one used while compiling, and thus the one with a matching `-I` flag.  The second one is a correct dependency, but not used for compiling, so does not have any matching `-I` flag, so breaks mkdoc.
Here, we customize our skylark header collection to ignore the second file.
(Note that #15066 and #15068 are also required for Bazel …
=> mkdoc: Work around a problematic deprecation_example header dep

systems/analysis/test/simulator_limit_malloc_test.cc, systems/framework/leaf_system.cc, systems/framework/leaf_system.h
Replace a function-scoped vector with a cache entry. Decline all
invalidation services and use manual methods to ensure no data migrates
between uses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15067)
=> LeafSystem: remove allocations during simulation

geometry/proximity/BUILD.bazel, geometry/proximity/contact_surface_utility.cc, geometry/proximity/contact_surface_utility.h, geometry/proximity/test/contact_surface_utility_test.cc
A baby step towards new query for discrete hydroelastics (issue #14579). After this PR #15034 lands, another PR #15035 for `AddPolygonToMeshDataAsOneTriangle()` will call the subroutines added in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15034)
=> [geometry] Calculate centroid and area of a convex polygon represented as an ordered list of vertex positions.

geometry/proximity/BUILD.bazel, geometry/proximity/aabb.cc, geometry/proximity/aabb.h, geometry/proximity/boxes_overlap.cc, geometry/proximity/boxes_overlap.h, geometry/proximity/obb.cc, geometry/proximity/obb.h, geometry/proximity/test/aabb_test.cc, geometry/proximity/test/obb_test.cc
1. Moves the Gottschalk box-overlap test *out* of `Obb` and into its own file. This is *just* movement, no changes in implementation.
- Note, we're still using the `Obb` tests to test this code.
2. Adds the `Aabb` bounding volume class.
3. Add overlap tests between `Aabb` and `Obb`.
4. In build, roll the bounding volumes into a single build target to mitigate interdependencies.
Relates #15080
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15058)
=> [geometry] Introduce new bounding volume: axis-aligned bounding box

tools/install/colab/setup_drake_colab.py
Related to #13779.
Also removes the default value for `build`, as recommended by @jwnimmer-tri in #13779.  The argument is already required, (by virtue of the `*` arg, and I've added an assert to check that build is a string we support.  (is that too violent?)
Demonstration notebook is here:
https://colab.research.google.com/drive/1PYqkB3ySfMVYQFRt3aXWn99KZQEAHcPH#scrollTo=3KltwlhbROHP
Note: I don't like the syntax `build = releases`  and would have preferred `build = release`, but the directory structure on the packaging server uses `releases` and the argument in this (intentionally durable) script is `build`, so I'm inclined to leave it.
--- …
=> Document setup_drake_colab from releases

multibody/fixed_fem/dev/fem_solver.h, multibody/fixed_fem/dev/softsim_system.cc, multibody/fixed_fem/dev/softsim_system.h, multibody/fixed_fem/dev/test/fem_solver_test.cc, multibody/fixed_fem/dev/test/stretch_test.cc
By having FemSolver not own the FemModel, we allow softsim to be refactored into two more-or-less independent components: a modelling component that owns FemModels and a DiscreteUpdateManager component that owns FemSolvers. We have to internally keep track of the solver/model pair so that the model outlives the solver after this change, but since we don't currently allow removing deformable objects, this does not create any actual burdens in the near future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15082)
=> Change FemSolver constructor to take a const pointer to FemModelBase

systems/framework/leaf_system.cc, systems/framework/leaf_system.h
Hotfix for #15067.
Removes this console warning:
> [console] [warning] The `std::vector<drake::systems::Event<double>const*,std::allocator<drake::systems::Event<double>const*>>` class is incompatible with the typename hasher that provides the type-erasure checking for AbstractValue casts, most likely because the problematic class mixes template parameters with nested classes or non-type template parameters. As a result, operations on `Value<std::vector<drake::systems::Event<double>const*,std::allocator<drake::systems::Event<double>const*>>>` will suffer from slightly impaired performance. If the problem relates to nested classes, you may be able to resolve it by un-nesting the class in question. If the problem relates to a single non-type template parameter, you may be able to resolve it …
=> framework: Rephrase LeafSystem cache entry to avoid hasher warning

multibody/plant/BUILD.bazel, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/multibody_plant_model_attorney.h, multibody/plant/physical_model.cc, multibody/plant/physical_model.h, multibody/plant/test/discrete_update_manager_test.cc, multibody/plant/test/dummy_model.h, multibody/plant/test/physical_model_test.cc, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree.h, multibody/tree/multibody_tree_system.cc, multibody/tree/multibody_tree_system.h
Add a DiscreteUpdateManager class that advances the discrete states for MultibodyPlant. DiscreteUpdateManager provides an interface that extends MbP and that MbP knows how to invoke. It allows more flexibility in experimenting with new solvers and can be compiled independently from MbP.
Add a PhysicalModel class that extends the physical models owned by MultibodyPlant. It allows more flexibility in experimenting new materials and models that may be simulated.
To enable DiscreteUpdateManager and PhysicalModel, introduce attorney classes MultibodyPlantModelAttorney and MultibodyPlantDiscreteUpdateManagerAttorney that grant the necessary protected/private methods in MultibodyPlant that PhysicalModel and DiscreteUpdateManager needs.
Co-authored-by: amcastro-tri <alejandro.castro@tri.global> …
=> Add DiscreteUpdateManager and PhysicalModel

tools/workspace/pybind11/mkdoc.py
Just a minor touch-up.  I tried running mkdoc without output specified (thinking it might print to the console), but it turns out that argument is actually required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15093)
=> mkdoc: output argument is not optional

multibody/plant/test/multibody_plant_forward_dynamics_test.cc
The mac (in debug) needed a bit more tolerance in the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15094)
=> [hotfix] Fix a mac ci build - test tolerance was too tight

multibody/parsing/test/detail_sdf_parser_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/tree/BUILD.bazel, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/test/multibody_tree_test.cc
Specifically, when the model instance filtering is misconfigured, provide more information about what models might have matched.
Inspired by painful debugging while diagnosing #15079.
Paves the way for improvements on the #10309 front, eventually.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15083)
=> multibody: Improve error messages on element lookups

systems/framework/context.cc, systems/framework/context_base.h, systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/diagram_context.cc, systems/framework/discrete_values.h, systems/framework/event_collection.h, systems/framework/leaf_context.cc, systems/framework/leaf_context.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/state.h, systems/framework/system.cc, systems/framework/system.h, systems/framework/test/diagram_context_test.cc, systems/framework/test/diagram_test.cc, systems/framework/test/discrete_values_test.cc, systems/framework/test/leaf_context_test.cc, systems/framework/test/leaf_system_test.cc, systems/framework/test/system_test.cc
Add system-id labeling to State, DiscreteValues, and
CompositeEventCollection types. Check compatibility of objects at public
Diagram methods. Move some methods to private access that should have
been private all along.
This patch completes compatibility checking for Diagram<T>. Further work
remains to close the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15030)
=> diagram: Finish compatibility checks

tools/workspace/voxelized_geometry_tools/BUILD.bazel
This test was previously disabled due to a bug introduced by Apple security update 2021-002 on Catalina, which caused OpenCL kernel compilation to fail. Now that the bug has been fixed by security update 2021-003, it can be reenabled.
See #15006 and #15005 for more details.
_Edit: Closes #15006._
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15095)
=> Reenable VGT test now that Catalina OpenCL is fixed

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/collision_objects.cc, multibody/fixed_fem/dev/collision_objects.h, multibody/fixed_fem/dev/test/collision_objects_test.cc
Create a CollisionObject class that manages the geometric representations of rigid objects that are two-way coupled with deformable objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15091)
=> Add CollisionObject for deformable simulation

manipulation/kuka_iiwa/iiwa_command_receiver.cc, systems/analysis/test/simulator_limit_malloc_test.cc, systems/framework/event.h, systems/framework/event_collection.h, systems/framework/leaf_system.h, systems/lcm/lcm_log_playback_system.cc, systems/lcm/lcm_subscriber_system.cc
Rewrite the storage of event collections to avoid most allocations,
while maintaining most of the pre-existing public API. To support this
change, allow fully-derived-type events to be copied and assigned. The
Clone() mechanism is still supported, primarily for interfacing with
Python.
This patch also deprecates EventCollection<E>::add_event() and any
overrides.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15081)
=> framework: Remove some allocations from event collections

math/fast_pose_composition_functions.cc, math/fast_pose_composition_functions.h, math/rotation_matrix.h, math/test/fast_pose_composition_functions_test.cc, math/test/rigid_transform_test.cc, math/test/rotation_matrix_test.cc, multibody/plant/test/frame_kinematics_test.cc, multibody/tree/multibody_tree.cc
This is the second PR (following #15013) in a train leading up to #14768 which provides a family of AVX methods. #15013 added the infrastructure and rotation matrix composition method ComposeRR(). This one adds the method for inverse-rotation composed with rotation, internal::ComposeRinvR().
Measured throughput in gigaflops (thanks to @joemasterjohn):
|              | ComposeRinvR() 
| ---------:|:---------:|
|   C++     |    5.46   |
|   AVX      | 13.02      |
| Speedup | **2.4X** |
This PR also changes (without deprecation) the signature of last week's ComposeRR() function and moves it into the internal:: namespace where it should have been in the first place. That is a breaking change if anyone was using it directly, which they should not have been doing!
We also add some missing …
=> Add AVX support for inverse-rotation matrix times rotation matrix.

geometry/benchmarking/mesh_intersection_benchmark.cc, geometry/proximity/bvh.cc, geometry/proximity/bvh.h, geometry/proximity/hydroelastic_callback.h, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/hydroelastic_internal.h, geometry/proximity/mesh_half_space_intersection.cc, geometry/proximity/mesh_half_space_intersection.h, geometry/proximity/mesh_intersection.cc, geometry/proximity/mesh_intersection.h, geometry/proximity/mesh_plane_intersection.cc, geometry/proximity/mesh_plane_intersection.h, geometry/proximity/obb.h, geometry/proximity/test/bvh_test.cc, geometry/proximity/test/hydroelastic_internal_test.cc, geometry/proximity/test/mesh_half_space_intersection_test.cc, geometry/proximity/test/mesh_intersection_test.cc, geometry/proximity/test/mesh_plane_intersection_test.cc, geometry/proximity/test/mesh_to_vtk_test.cc
The `Bvh` code is now templated on bounding volume type so the same *hierarchy* logic can be used for different bounding volume types. Furthermore, support collision *between* hierarchies of different bounding volume types (in so far as the bounding volumes themselves support overlap tests.
The majority of the meaningful changes are in:
`bvh.{h|cc}`, `obb.h` and `bvh_test.cc`.
All other changes are simply respellings of the `Bvh` invocation to account for the change in type declaration.
Relates #15080
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15084)
=> [geometry] Create general bounding volume hierarchy

systems/analysis/test/simulator_limit_malloc_test.cc, systems/framework/event.h, systems/framework/event_collection.h
Remove unnecessary heap allocations from the rest of the event system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15101)
=> framework: Remove more heap allocations from events

systems/framework/system.cc, systems/framework/system_constraint.h, systems/framework/test/system_test.cc
Add system id label to SystemConstraint. Set the correct label on admission to a system via AddConstraint(). Check compatibility of contexts at public methods of SystemConstraint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15102)
=> system constraint: Add compatibility checks

geometry/proximity/contact_surface_utility.cc, geometry/proximity/contact_surface_utility.h, geometry/proximity/test/contact_surface_utility_test.cc
This PR is a building block towards a solution for issue #14579.
It will be used for speeding up discrete hydroelastic contact model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15035)
=> [geometry] Utility to add one representative triangle for each contact polygon. 

systems/analysis/BUILD.bazel
Relevant to: #14901
Now the issue is fixed, the work-around is no longer needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15126)
=> simulator: Remove a stale work-around

geometry/BUILD.bazel, geometry/collision_filter_declaration.cc, geometry/collision_filter_declaration.h, geometry/collision_filter_manager.cc, geometry/collision_filter_manager.h, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/collision_filter_declaration_test.cc, geometry/test/collision_filter_manager_test.cc, geometry/test/scene_graph_test.cc
In anticipation of expanding the functionality relating to working with collision filters, we're changing the public API. This introduces a *parallel* API and labels the old API as "legacy". The legacy API will be deprecated in a follow up PR.
The purpose of the API is to reduce `SceneGraph`'s knowledge of working with collision filters. `SceneGraph` produces a `CollisionFilterManager`, but all manipulation of collision filter configuration now belongs to that manager (reducing the churn on `SceneGraph`'s already large API).
To achieve this end:
- Introduce new classes: `CollisionFilterManager` and `CollisionFilterDeclaration`.
- The unit tests for `CollisionFilterManager` are copied from `scene_graph_test.cc` (as the manager can only be constructed by `SceneGraph`). The source test code …
=> Adding collision filter manager API

multibody/parsing/BUILD.bazel, multibody/parsing/detail_scene_graph.cc, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/parser.h, multibody/parsing/test/detail_scene_graph_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/parser_test.cc, multibody/parsing/test/sdf_parser_test/all_geometries_as_collision.sdf, multibody/parsing/test/sdf_parser_test/all_geometries_as_visual.sdf, multibody/parsing/test/sdf_parser_test/include_models.sdf, multibody/parsing/test/sdf_parser_test/model_with_directly_nested_models.sdf, multibody/parsing/test/sdf_parser_test/world_with_directly_nested_models.sdf
This a redo of #14401 but does not create a frame for each model in the parent scope of the model. There is still a frame associated with each model, but it's named `__model__` and is found inside the model instance.
---
Description from #14401:
Changes in behavior:
* Models nested via the `<include>` tag are no longer flattened, which means each included model will have its own model instance.
* `drake::multibody::Parser::AddAllModelsFromFile` now returns all added models including nested models
Note: This does not use a custom parser for URDFs via libsdformat's Interface API, and thus may incur unexpected behavior when including URDF files from SDFormat pending the full resolution of #14295.
--- …
=> parsing: Add support for SDFormat 1.8 model composition (redo)

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf, multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf
From discussions on [slack](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1622670322026300), trying out adding support for parsing acceleration limits for some (continuous, revolute, and prismatic) joints.
I'm not sure I understand the structure of SDF parsing to know where the equivalent would be implemented for SDF models.
@sammy-tri
cc @jwnimmer-tri @ggould-tri @SeanCurtis-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15122)
=> Add support for parsing acceleration limits for some joints in URDF and SDF

multibody/tree/multibody_tree_system.h
Closes #11252.
Since all of the context-taking methods in multibody/tree lead
eventually to MultiBodyTreeSystem, ensure that all of its public methods
validate the context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15129)
=> multibody tree: Validate contexts at public methods

multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/physical_model.h, multibody/plant/test/discrete_update_manager_test.cc
DeclareCacheEntry() does not need to be exposed to DiscreteUpdateManager
through the attorney class because it is public to begin with.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15132)
=> Remove DeclareCacheEntry() from DiscreteUpdateManager attorney

bindings/pydrake/perception_py.cc, bindings/pydrake/test/perception_test.py, lcmtypes/BUILD.bazel, lcmtypes/lcmt_point_cloud.lcm, lcmtypes/lcmt_point_cloud_field.lcm, perception/BUILD.bazel, perception/point_cloud_to_lcm.cc, perception/point_cloud_to_lcm.h, perception/test/point_cloud_to_lcm_test.cc
Add new `lcmt_point_cloud` message type for it to encode into.
Towards #14985 and #14362.
Demo available in #14991.
Screenshot at https://github.com/RobotLocomotion/drake/issues/14985#issuecomment-830468107.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14990)
=> perception: Add PointCloudToLcm system

bindings/pydrake/systems/test/test_util_py.cc, systems/framework/context.h, systems/framework/context_base.h, systems/framework/continuous_state.h, systems/framework/diagram.cc, systems/framework/diagram_context.cc, systems/framework/discrete_values.h, systems/framework/event_collection.h, systems/framework/framework_common.h, systems/framework/leaf_system.cc, systems/framework/parameters.h, systems/framework/state.h, systems/framework/system.cc, systems/framework/system_base.h, systems/framework/system_compatibility_doxygen.h, systems/framework/system_constraint.h, systems/framework/system_output.h, systems/framework/test/leaf_system_test.cc, systems/framework/test/system_test.cc
Add system-id labeling to the Parameters type. Check compatibility of
objects at public methods of System, Diagram, and LeafSystem.
This patch completes compatibility checking for System and its derived
classes, including some Diagram methods missed in #15030. Further work
remains to close the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15098)
=> system: Finish compatibility checks

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h
Copy the contact solve logic for rigid dofs in MultibodyPlant to DeformableRigidManager. Add unit test to verify that when only rigid
dofs exist, the simulation results obtained through the discrete update manager is the same as that obtained from internal MultibodyPlant logic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15123)
=> Support rigid dofs update in DeformableRigidManager

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/deformable_model.cc, multibody/fixed_fem/dev/deformable_model.h, multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/fixed_fem/dev/run_cantilever_beam.cc, multibody/fixed_fem/dev/test/deformable_model_test.cc, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h
This is a step towards integration of deformable and rigid simulation through contact. SceneGraph does not support deformable geometries yet, so we delegate collision geometry management to DeformableRigidManager for the moment. To that end, this PR does the following:
- Add RegisterCollisionObjects() that registers all rigid collision geometries registered in MultibodyPlant at the corresponding DeformableRigidManager.
- Add RegisterDeformableGeometries() that registers all deformable geometries registered in DeformableModel at the corresponding DeformableRigidManager.
- Add UpdateCollisionOjbectPoses() and UpdateDeformableVertexPositions() that update the geometries based on context.
This is meant to be a temporary solution. When SceneGraph takes control of deformable geometries, much of …
=> Manage collision geometries with DeformableRigidManager

solvers/test/gurobi_solver_grb_license_file_test.cc, solvers/test/mosek_solver_moseklm_license_file_test.cc
Hotfix for #15114.
Closes #15151.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15152)
=> solvers: Fix use-after-free from getenv on macOS

geometry/proximity/BUILD.bazel, geometry/proximity/deformable_volume_mesh.cc, geometry/proximity/deformable_volume_mesh.h, geometry/proximity/mesh_deformer.cc, geometry/proximity/mesh_deformer.h, geometry/proximity/surface_mesh.h, geometry/proximity/test/deformable_volume_mesh_test.cc, geometry/proximity/test/mesh_deformer_test.cc, geometry/proximity/volume_mesh.h
- Introduce the generic `MeshDeformer` abstraction.
- It is compatible with both `SurfaceMesh` and `VolumeMesh`. Each have been modified to support the deformer.
- Add the `DeformableVolumeMesh`
- Wraps a `VolumeMesh` with a corresponding `MeshDeformer` and provides an API for updating vertex positions.
In the near future, a "deformable" bvh will be added as well.
Relates #15080
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15117)
=> [geometry] Make a deformable volume mesh

systems/framework/diagram.cc, systems/framework/system.h, systems/framework/system_scalar_converter.cc, systems/framework/system_scalar_converter.h, systems/framework/test/system_scalar_converter_test.cc
Support prohibiting scalar conversion to and from a particular scalar type at run time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15159)
=> Add SystemScalarConverter::Remove()

.gitattributes
Per https://github.com/Reviewable/Reviewable/issues/753#issuecomment-858076112.
Here's a screenshot showing the new `drake_cc_library(name = "scene_graph", ...` declaration hint now in effect for Bazel files:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15163)
=> Use Reviewable's new Bazel syntax highlighting

geometry/drake_visualizer.cc
Discovered as part of #15161 audit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15174)
=> geometry: Remove redundant type annotation for DeclareCacheEntry

multibody/tree/multibody_tree_system.h
It took me a few minutes to reason out whether or not this could ever change out from under us.  I'm saving the next reader that trouble.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15173)
=> multibody/tree: Clarify that continuous/discrete mode is invariant

multibody/plant/BUILD.bazel, multibody/plant/hydroelastic_traction_calculator.cc, multibody/plant/hydroelastic_traction_calculator.h, multibody/plant/test/hydroelastic_traction_test.cc
This PR implements an expression for the hydroelastic traction that can be automatically differentiated with AutoDiffXd (the current version leads to NaNs for zero slip velocities as @SeanCurtis-TRI discovered).
This new expression is mathematically equivalent to the atan() functional form of regularization currently used, but it simplifies the math by hand near zero in order to lead to expression that do not require the evaluation of square roots (which were responsible for division by zero when differentiated automatically).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14963)
=> Autodiffable hydroelastics traction

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/system.cc, systems/framework/system.h, systems/framework/test/leaf_system_test.cc, systems/framework/test/system_test.cc
When declaring an input or output port, users should pass a name as the first argument, or else say kUseDefaultName to default to u0, u1, ... or y0, y1, ... respectively.  The overloads that skipped the name are now deprecated.  This change was forewarned in the API documentation.
Closes #9447.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15179)
=> framework: Deprecate port declarations without names

doc/_pages/code_style_guide.md
Not sure if we follow this as written, nor why this is in Code Style Guide.
Came across while checking Code Style Guide as part of platform review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15187)
=> code_style_guide: Remove notes on version numbers

math/autodiff.h, math/autodiff_gradient.h, math/bspline_basis.h, math/convert_time_derivative.h, math/jacobian.h, math/test/gray_code_test.cc, math/test/jacobian_test.cc, perception/test/depth_image_to_point_cloud_test.cc, perception/test/point_cloud_flags_test.cc, tools/vector_gen/lcm_vector_gen.py, tools/vector_gen/test/goal/sample.h, tools/vector_gen/test/sample_test.cc
This tidies up math, perception, and vector_gen.
I think these are the last remaining uses of the pre-17 spellings within Drake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15157)
=> Use C++17 type_traits throughout

examples/allegro_hand/allegro_lcm.cc, examples/allegro_hand/allegro_lcm.h, examples/planar_gripper/planar_gripper_lcm.cc, examples/planar_gripper/planar_gripper_lcm.h, examples/planar_gripper/planar_manipuland_lcm.cc, examples/planar_gripper/planar_manipuland_lcm.h
Specifying a custom allocator for LCM message outputs is not a pattern we should encourage.
Found during #15161.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15190)
=> [examples] Remove unnecessary model_value allocation boilerplate

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/deformable_rigid_contact_pair.h, multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/test/multibody_plant_test.cc
This PR is a sequel to #15128. It provides the functionality to calculate deformable rigid contact pairs by adding a DeformableRigidManager::CalcDeformableRigidContactPair() method that calculates the contact information between a deformable body and a rigid collision geometry. It wraps around ComputeTetMeshTriMeshContact() to provide additional information about the contact such as friction, stiffness, dissipation, and the rotation matrices to transform world frame quantities into contact frames.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15160)
=> Calculate deformable rigid contact pair

doc/_pages/code_style_guide.md
Redundant w.r.t. upstream docs, not linted, etc.
Came across while checking Code Style Guide as part of platform review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15188)
=> code_style_guide: Remove section on package.xml

multibody/contact_solvers/test/contact_solver_test.cc, multibody/fixed_fem/dev/run_cantilever_beam.cc, multibody/fixed_fem/dev/test/deformable_model_test.cc, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/discrete_update_manager_test.cc, multibody/plant/test/physical_model_test.cc
* Change SetContactSolver(), AddPhysicalModel(), and SetDiscreteUpdateManager() to void methods that take a unique pointer
to the base class.
* Move definition of these methods to .cc file to comply with GSG.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15195)
=> Change MbP component setters' signature

systems/framework/system_base.h
DeclareCacheEntry is currently specified as public access, but will be demoted to protected access on or after 2021-10-01.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15197)
=> [framework] Document that DeclareCacheEntry will become protected

bindings/pydrake/BUILD.bazel, bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py, math/orthonormal_basis.h, math/test/orthonormal_basis_test.cc
This PR #15154 deprecates C++ and Python calls to ComputeBasisFromAxis() in favor of RotationMatrix::MakeFromOneVector() and is the follow-on from PR #15055.  This PR also serves a pedagogical purpose, namely to provide **_partial_** insight into how to deprecate a C++ function that has Python bindings. 
FYI:  Before I submitted this PR to CI (Continuous Integration), I issued various commands (shown below) from my local computer's operating system prompt to test C++/Python deprecation and to lint and test Python bindings.
1.  To test C++ deprecation, **_e.g.,_** in orthonormal_basis_test.cc 
bazel test  orthonormal_basis_test         
2.  To lint, I issued the following command (it executes reasonably fast).  
bazel test --config lint //...
Note: Pydrake bindings for C++ code are unusual …
=> Deprecate ComputeBasisFromAxis() in C++ and Python.

systems/framework/BUILD.bazel, systems/framework/test/system_html_test.cc
The system_html_test used ManipulationStation to demonstrate a large and complex diagram. The problem was that bazel test //systems/framework/... was therefore rebuilding a huge amount of additional code, slowing down development on patches that change the framework. I've been using a version of this patch locally as I'm working on systems, but I think its time to improve it for everyone else.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15196)
=> [framework] Remove manipulation_station dependency from test

multibody/fixed_fem/dev/deformable_contact.cc, multibody/fixed_fem/dev/test/deformable_contact_test.cc
There is a bug in calculating the area weight centroid in both Cartesian coordinates and barycentric coordinates. The area of the triangle should be used as the weight, not the accumulated area of the polygon.
Add a unit test to guard against this bug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15199)
=> Fix bug in ComputeTetMeshTriMeshContact()

systems/framework/cache_entry.h, systems/framework/diagram.cc, systems/framework/diagram_output_port.h, systems/framework/input_port.h, systems/framework/input_port_base.cc, systems/framework/input_port_base.h, systems/framework/leaf_output_port.h, systems/framework/leaf_system.cc, systems/framework/output_port.h, systems/framework/output_port_base.cc, systems/framework/output_port_base.h, systems/framework/port_base.cc, systems/framework/port_base.h, systems/framework/system.cc, systems/framework/test/input_port_test.cc, systems/framework/test/output_port_test.cc, systems/framework/test/system_test.cc
Doing this without eating a virtual function call means that we need to pass the SystemId into the Port objects so that they can perform the guard locally, without asking SystemMessageInterface.
Add some Debug-only context validation checks to CacheEntry, to help backstop the rare cases where a user might be evaluating their cache entry without first checking the Context they were given.
Closes #15177.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15181)
=> [framework] Enable context validation for ports in Release builds

doc/_pages/developers.md, doc/_pages/from_binary.md
Document that Drake builds (since v0.30.0) require AVX2 and FMA instruction support.
This does not include detailed instructions for building on pre-2013 machines, but provides enough information for doing so (perhaps with some help from stackoverflow if necessary).
Resolves #15125
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15165)
=> Document Drake's dependence on AVX2 and FMA instructions

solvers/solver_type.h, solvers/solver_type_converter.h, solvers/test/linear_program_examples.cc, solvers/test/optimization_examples.cc, solvers/test/optimization_examples.h, solvers/test/quadratic_program_examples.cc
SolverType was left intact for compatibility reasons; we should not use it in code that users might imitate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15214)
=> [solvers] Remove uses of SolverType

systems/framework/system_scalar_converter.cc, systems/framework/system_scalar_converter.h, systems/framework/test/system_scalar_converter_test.cc
This method was recently added (#15159), but ended up being unused.
Fix the implementation of Remove<T, U> to use O(1) lookup instead of O(N) search.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15211)
=> [framework] Drop SystemScalarConverter::Remove<T> method

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/deformable_contact_data.cc, multibody/fixed_fem/dev/deformable_contact_data.h, multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/fixed_fem/dev/test/deformable_contact_test.cc, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
DeformableContactData stores all contact information associated with a single deformable body. 
In particular, it stores all deforamble-rigid contact pairs associated with the deformable body. It also calculates a permuted set of vertex indexes for the deformable vertices based on contact participation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15201)
=> Add DeformableContactData

bindings/pydrake/common/test/value_test_util_py.cc, common/test/value_test.cc, common/value.h, multibody/fixed_fem/dev/deformable_model.cc, perception/point_cloud_to_lcm.cc, systems/framework/cache.h, systems/framework/leaf_system.cc, systems/framework/test/leaf_system_test.cc, systems/framework/test/system_test.cc, systems/framework/test/vector_system_test.cc, systems/rendering/render_pose_to_geometry_pose.cc
This enables a few small cleanups, but most importantly gives us a function pointer that we can use as an allocator callback, towards #15161.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15209)
=> [common] Add AbstractValue::Make overload for default construction

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc
This removes additional implicit model frames created for nested models that were missed in #15099.
/cc @EricCousineau-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15208)
=> parsing: Remove implicit frames created for nested models

multibody/plant/BUILD.bazel, multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
We query MBP's contact results to confirm that the forces have derivatives as expected. This isn't detailed (for example, it doesn't test for explicit values or for scenarios with complex derivatives). It is largely a smoke test to make sure that the values propagate as expected.
relates: #14136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15219)
=> Provide simple smoke test on hydro *forces* derivatives

doc/_pages/documentation_instructions.md
`//doc:pages_build` does not exist; `//doc:pages` does
As part of #15236, while doing #15207
\cc @jwnimmer-tri
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15237)
=> documentation_instructions: Fix incorrect build target

geometry/proximity_engine.cc, geometry/proximity_engine.h, geometry/test/proximity_engine_test.cc
Another step in the [implementation plan for 14579](https://github.com/RobotLocomotion/drake/issues/14579#issuecomment-843618123).  This PR #15204 (ProximityEngine) is after PR #15200 (hydroelastic_callback).
The next PR is #15210 (QueryObject).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15204)
=> [geometry] New queries for hydroelastics in internal::ProximityEngine.

multibody/tree/BUILD.bazel, multibody/tree/screw_mobilizer.cc, multibody/tree/screw_mobilizer.h, multibody/tree/test/screw_mobilizer_test.cc
Adds a 1 dof screw mobilizer that allows motion along and rotation about the z-axis of the parent frame.
Joint is also implemented already but is too much code for one PR.
Towards #12404
@mpetersen94
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15104)
=> add screw mobilizer

multibody/tree/BUILD.bazel, multibody/tree/screw_joint.cc, multibody/tree/screw_joint.h, multibody/tree/test/screw_joint_test.cc
Adds a 1 dof screw joint that allows motion along and rotation about the z-axis of the parent frame.
Depends on  #15104
Towards #12404
@mpetersen94
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15105)
=> add screw joint

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/deformable_contact_data.h, multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h
Add DeformableRigidManager::CalcContactJacobian() that calculates the contact jacobian for a system with rigid and deformable bodies. The way that the contact jacobian is ordered also implies an order for all deformable and rigid degrees of freedom; i.e. the order of the dofs should be compatible with that laid out in the contact jacobian.
To facilitate this effort:
* Cache deformable rigid contact query results.
* Add DeformableRigidManager::GetBodyFrameFromCollisionGeometry().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15238)
=> Calculate contact jacobian

geometry/shape_specification.h
Clone does not call an NVI DoClone anymore; it uses the fancy ShapeTag functor trick.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15247)
=> geometry: remove stale documentation line.

common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h
Also, switches from using 4 constraints per knot point to only 3 constraints per knot point by removing the trivial constraint that the constant term is equal to the knot point location.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15248)
=> trajectories: Switch to Sparse solver for constructing CubicWithContinuousSecondDerivatives

solvers/clp_solver.cc, solvers/test/clp_solver_test.cc
Users can use kPrintToConsole to opt-in.
```
[ RUN      ] ClpSolverTest.TestVerbosity
Clp1001I Initial range of elements is 1 to 2
Clp1004I Not bothering to scale as good enough
Clp0022I Absolute values of scaled rhs range from 1 to 4, minimum gap 1e+100
Clp0020I Absolute values of scaled objective range from 1 to 2
Clp0021I Absolute values of scaled bounds range from 2 to 2, minimum gap 1e+100
Clp0006I 0  Obj 6 Primal inf 0.9999999 (1) Dual inf 1e+10 (1)
Clp0006I 1  Obj 8
Clp0017I Looking optimal with tolerance of 1e-07
Clp0000I Optimal - objective value 8
[       OK ] ClpSolverTest.TestVerbosity (1 ms)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15254)
=> [solvers] Disable ClpSolver console printing by default

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/scalar_conversion.py, systems/framework/system_scalar_conversion_doxygen.h, systems/framework/system_scalar_converter.h, systems/framework/test/system_scalar_converter_test.cc, systems/framework/test/vector_system_test.cc
In its original incarnation, we imagined supporting user-defined scalars but that never came to pass (#12814).  Here, we improve the documentation to be clear about exactly what is supported and deprecate methods that were only useful for uses beyond the defaults.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15255)
=> [framework] Clarify SystemScalarConverter only supports default scalars

multibody/fixed_fem/dev/test/deformable_contact_test.cc
Spotted these by accident.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15258)
=> Fix typos in test names

multibody/contact_solvers/pgs_solver.cc, multibody/contact_solvers/pgs_solver.h
With the change in storage order, the average time spent on 100 PGS iterations for a sim with ~80 contact points reduces from ~1.3e-3 second to around ~1e-4 second, which is a ~13x improvement.
In addition, change the default number of iterations for PGS to 100.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15223)
=> Use row major Delassus operator in PGS solver

multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/plant/BUILD.bazel, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/test/discrete_update_manager_test.cc, systems/framework/BUILD.bazel, systems/framework/abstract_value_cloner.cc, systems/framework/abstract_value_cloner.h, systems/framework/cache_entry.cc, systems/framework/cache_entry.h, systems/framework/diagram.cc, systems/framework/leaf_output_port.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/system.cc, systems/framework/system_base.cc, systems/framework/system_base.h, systems/framework/test/abstract_value_cloner_test.cc, systems/framework/test/cache_entry_test.cc, systems/framework/test/output_port_test.cc, systems/framework/test/system_test.cc, systems/framework/test/value_producer_test.cc, systems/framework/value_producer.cc, systems/framework/value_producer.h
The allocation and calculation functions must always work together as a team, so it makes sense to abstract them as a single component, which then paves the way for consolidating the function wrapping sugar for reuse across cache entries, output ports, time derivatives, etc.
(The overall goal is on display at #15161.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15198)
=> [framework] Add ValueProducer

common/nice_type_name.h, common/yaml/yaml_read_archive.h, common/yaml/yaml_write_archive.h, geometry/geometry_properties.h, solvers/mathematical_program_result.cc
Approximately 0.9% of libdrake.so object code in Release builds was due to this caching, but in general practice we don't care about the cost of repeatedly naming the same type.
Code that does care about caching can still opt-in to memoization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15269)
=> [common] Change NiceTypeName's internal caching to be opt-in

geometry/BUILD.bazel, geometry/collision_filter_declaration.cc, geometry/collision_filter_declaration.h, geometry/proximity/BUILD.bazel, geometry/proximity/collision_filter.cc, geometry/proximity/collision_filter.h, geometry/proximity/test/collision_filter_test.cc, geometry/test/collision_filter_declaration_test.cc
The new collision filter differs in two ways:
1. The underlying implementation `CollisionFilter` is, essentially, an N^2 table (for a `SceneGraph` with N proximity geometries).
- Each geometry pair is explicitly enumerated with its filtered state.
- `CollisionFilterLegacy` made removing filters nearly impossible (it would consist of refactoring cliques.) This new representation allows for far simpler modifications. And, particularly, temporary modifications.
2. The state of the filters is modified via: `CollisionFilterDeclarations`.
- It is comprised of one or more *statements* (e.g., exclude between *these* pairs. Allow between *those* pairs, etc.) The collision filter evaluates a declaration and makes the corresponding modifications.
- One of the key aspects of this is that the …
=> [geometry] Add core of new collision filter system

common/filesystem.cc, common/filesystem.h
While we don't officially support GCC 8, sometimes users will still try it and need to work around this.
https://stackoverflow.com/questions/64762679/building-python-bindings-linking-of-rule-failed/64779015#64779015
https://stackoverflow.com/questions/68173726/declarevectorinputport-function-runs-with-error
Tested locally with `env CC=gcc-8 CXX=g++-8 bazel test //common:*` on Bionic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15265)
=> [common] Avoid std::filesystem with GCC 8

geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/scene_graph_test.cc, systems/rendering/pose_aggregator.cc, systems/rendering/pose_aggregator.h
The output port allocation callbacks are intended for cases where cloned values are unsuitable.  PoseBundle has a default constructor, so there's no justification to use the allocation callback.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15259)
=> [geometry] Remove PoseBundle allocation boilerplate

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
Previously `ScsSolver().solver_id() == ScsSolver().solver_id()` would return False in Pydrake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15276)
=> Add pybind for SolverId == and !=

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
Calculation functions should prefer to use output pointers anytime the return value has a non-trivial cost to make copies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15270)
=> [multibody] Reuse EvalDiscreteContactPairs storage

multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
DeformableRigidManager::CalcContactPointData() calculates the per contact point data, including friction, penetration distance, point stiffness, and damping for all rigid-rigid and rigid-deformable contact points.
Note that all penetration distance between rigid and deformable bodies are set to 0 for the moment and will be properly approximated in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15262)
=> Add DeformableRigidManager::CalcContactPointData()

geometry/proximity/BUILD.bazel, geometry/proximity/aabb.h, geometry/proximity/bvh.h, geometry/proximity/bvh_updater.h, geometry/proximity/deformable_volume_mesh.cc, geometry/proximity/deformable_volume_mesh.h, geometry/proximity/mesh_deformer.h, geometry/proximity/test/aabb_test.cc, geometry/proximity/test/bvh_updater_test.cc, geometry/proximity/test/deformable_volume_mesh_test.cc
The `BvhUpdater` is a "modifier" for a `Bvh`. Given a mesh and its corresponding `Bvh`, it causes the `Bvh` to update given the current position of the mesh's vertices -- it assumes no topological changes.
This initial implementation is simple.
- It only updates `Bvh`s built on `Aabb`.
- It only refits bounding volumes -- it doesn't change the topology at all.
This also adds a `Bvh` and `BvhUpdater` to the `DeformableVolumeMesh`. This keeps the deformable mesh in sync.
(Incidentally cleans up some redundant semantics in the `MeshDeformer` - removing `set_mesh()` and documenting why it isn't necessary.)
Relates #15080
Closes #15170
--- …
=> [geometry] Introduce BvhUpdater and add it to DeformableVolumeMesh

tools/workspace/drake_visualizer/package.BUILD.bazel, tools/workspace/drake_visualizer/repository.bzl, tools/workspace/drake_visualizer/use_drake_lcmtypes.patch, tools/workspace/lcmtypes_bot2_core/package.BUILD.bazel, tools/workspace/lcmtypes_robotlocomotion/package.BUILD.bazel
Remove support for bot_core based visualization of pointcloud and lidar.
Towards #14362 as the final step of removing use of bot_core lcmtypes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15284)
=> [drake_visualizer] Use drake's native lcmtypes for drawing

tools/workspace/tinyobjloader/repository.bzl
I believe this will make macOS builds substantially less console-spammy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15278)
=> [workspace] Upgrade tinyobjloader to latest commit

geometry/proximity/distance_to_point_callback.cc, geometry/proximity/distance_to_point_callback.h, geometry/proximity/test/distance_to_point_callback_test.cc, geometry/proximity/test/distance_to_point_characterize_test.cc, geometry/proximity_engine.cc, geometry/query_object.h
Add point-to-ellipsoid signed distance support
This extends the `ComputeSignedDistanceToPoint()` method to support `Ellipsoid` primitives. Previously, they were simply ignored. The support is partial -- `double` only.
1. Add to `DistanceToPointCallback` to exercise `fcl` in order to produce *some* answer (albeit a sloppy one).
- Test it.
2. Modify the characterization test for the callback to reflect the new support and the corresponding documentation.
3. This also removes the former warning about `Ellipsoid`s. The distance-to-point query was the only outlier; its support is now clearly documented across all of the proximity queries.
Closes #15227.
--- …
=> [geometry] Support point-to-ellipsoid results in ComputeSignedDistanceToPoint query

tools/workspace/meshcat_python/repository.bzl
Tested locally via `/bazel-bin/manipulation/util/show_model         --meshcat default         --find_resource         drake/manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15296)
=> [workspace] Upgrade meshcat_python to latest commit

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/collision_objects.cc, multibody/fixed_fem/dev/collision_objects.h, multibody/fixed_fem/dev/deformable_contact.cc, multibody/fixed_fem/dev/deformable_contact.h, multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/fixed_fem/dev/test/collision_objects_test.cc, multibody/fixed_fem/dev/test/deformable_contact_test.cc, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
This improves the performance of deformable-rigid contact computation by making use of Bvh.
- Upgraded `deformable_contact.*` API
- it consumes a `DeformableVolumeMesh` and a `Bvh` for the rigid collision object.
- `CollisionObjects` now include bvh for the surface mesh.
- `DeformableRigidManager` tracks `DeformableVolumeMesh` instead of `VolumeMesh`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15287)
=> [fem] Upgrading rigid-deformable contact to use Bvhs

tools/workspace/gtest/dont-define-test-f.patch, tools/workspace/gtest/repository.bzl
I've filed the patch upstream at https://github.com/google/googletest/pull/3472.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15291)
=> [workspace] Upgrade gtest to latest release 1.11.0

geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/hyperellipsoid_test.cc
This is another well-defined operation on convex sets, and it is the workhorse for the MIP formulation of the shortest-path problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15286)
=> geometry:optimization: AddPointInNonnegativeScalingConstraints

geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h
Subclass constructors must be marked override or final.
Eschew inline functions except for tiny getters / forwarders.
Include what you use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15283)
=> [geometry] Fix style guide nits in convex_set

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15313)
=> Add python binding for QuadraticConstraint

bindings/pydrake/solvers/mathematicalprogram_py.cc, solvers/BUILD.bazel, solvers/constraint.h, solvers/test/ipopt_solver_test.cc, solvers/test/snopt_solver_test.cc
Also add test for ipopt and snopt with Lorentz cone constraint
Resolves #15316
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15318)
=> Switch default eval_type of LorentzConeConstraint to ConvexSmooth.

examples/scene_graph/simple_contact_surface_vis.cc
Introduce some variations in the fake contact data to make testing easier. Without the variations, there is no visual difference
between the fixed-length mode and the auto-scale mode when visualizing vector quantities for hydroelastics contact.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15299)
=> Tweak simple contact surface vis example

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/point.cc, geometry/optimization/point.h, geometry/optimization/test/convex_set_test.cc, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/hyperellipsoid_test.cc, geometry/optimization/test/point_test.cc, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/test_utilities.cc, geometry/optimization/test_utilities.h, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
Also includes a ConvexSets (plural) container as my proposed solution to memory management for workflows like this:
```
ConvexSets MakeIrisObstacles(
const QueryObject<double>& query_object,
std::optional<FrameId> reference_frame = std::nullopt);
HPolyhedron Iris(const ConvexSets& obstacles,
const Eigen::Ref<const Eigen::VectorXd>& sample,
const HPolyhedron& domain,
const IrisOptions& options = IrisOptions());
```
Also includes a number of small fix-ups and style updates:
- HyperEllipsoid => Hyperellipsoid (per discussion with Sean)
- AddPointInSetConstraint => AddPointInSetConstraints
- expressed_in => reference_frame
This are API breaking changes, but we marked the classes as Experimental so that we could do this in the early stages.
This is not chopped up quite as finely as I've been …
=> geometry:optimization Implements IsBounded and Hyperellipsoid Volumes

math/test/rotation_conversion_test.cc, math/test/rotation_matrix_test.cc
Preparing for the release of Eigen 3.4, working towards #14968.
Replaced deprecated form of [LinSpaced ](https://eigen.tuxfamily.org/dox/classEigen_1_1DenseBase.html#a111ba763100d5c287ab25d1c81342501) function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15321)
=> Remove use of deprecated Eigen function

common/drake_bool.h, common/test/drake_bool_test.cc, common/trajectories/bspline_trajectory.cc
Preparing for the release of Eigen 3.4, working towards #14968.
The 'all' function was introduced to `Eigen/src/Core/util/Macros.h` at [af96018b](https://gitlab.com/libeigen/eigen/-/commit/af96018b499be64ff0b262cafc7b31f1a907b4c8)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15323)
=> Ensure we're using drake::all not Eigen::all

solvers/BUILD.bazel, solvers/csdp_solver.cc, solvers/test/csdp_solver_internal_test.cc, solvers/test/csdp_solver_test.cc, solvers/test/sdpa_free_format_test.cc, tools/workspace/csdp/params_pathname.patch, tools/workspace/csdp/printlevel.patch, tools/workspace/csdp/repository.bzl
This re-applies #15281, with a change to avoid calling `fopen()` on a NULL pathname.
For easier review, the original commit vs fixup commit are kept separate.  They will be squashed when merging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15307)
=> [solvers] Disable CsdpSolver console printing by default 

common/add_text_logging_gflags.cc, common/test/text_logging_test.cc, common/text_logging.cc, common/text_logging.h
I find myself occasionally writing `drake::log()->set_pattern("%v")` in certain entry points.
Would be nice to have easily accessible configuration.
Can be talked down from this if it admits scope / feature creep.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15240)
=> text_logging: Add set_log_pattern and --spdlog_pattern

systems/framework/diagram.cc, systems/framework/system_scalar_conversion_doxygen.h, systems/framework/system_scalar_converter.h, systems/framework/test/system_scalar_converter_test.cc, systems/primitives/random_source.cc
The subtype preservation must be declared at compile-time (in practice, it always was).  This allows for a more compact implementation in the future (the new implementation here is already somewhat more compact).
We also use "if constexpr" here for the traits dispatch now, which also removes some boilerplate.
This builds on the existing deprecations from #15255.
The overall motivation here is that almost 2% of `libdrake.so` is system scalar converter object code, because the inlined methods are too numerous and individually too fat (looking at you, ostream and NiceTypeName singletons).  This is a step along the road to moving most code to the cc file.
--- …
=> [framework] Deprecate SystemScalarConverter runtime opt-out of subtypes

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/schur_complement.cc, multibody/fixed_fem/dev/schur_complement.h, multibody/fixed_fem/dev/test/schur_complement_test.cc
Support deformable rigid contact by providing the functionality to
calculate the Schur complement of a symmetric positive definite matrix.
With Schur complement, the deformable dynamics tangent matrix can be made
into a smaller matrix involving only the dofs in contact. The velocity of
the dofs not in contact can also be solved using Schur complement  after
the contact solve.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15252)
=> Add Schur complement

systems/framework/system_scalar_converter.cc, systems/framework/system_scalar_converter.h, systems/framework/test/system_scalar_converter_test.cc
Creating ostream output in headers leads to object code bloat, in this case about 0.5% (208 KiB) of libdrake.so was for generating this one error message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15328)
=> [framework] Move SystemScalarConverter error message to cc file

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py, examples/acrobot/acrobot_plant.cc, examples/acrobot/acrobot_plant.h, examples/bead_on_a_wire/bead_on_a_wire.cc, examples/bead_on_a_wire/bead_on_a_wire.h, examples/bouncing_ball/bouncing_ball.h, examples/particles/particle.cc, examples/particles/particle.h, examples/pendulum/pendulum_plant.cc, examples/pendulum/pendulum_plant.h, examples/quadrotor/quadrotor_plant.cc, examples/quadrotor/quadrotor_plant.h, examples/rod2d/rod2d.cc, examples/rod2d/rod2d.h, examples/scene_graph/bouncing_ball_plant.cc, examples/scene_graph/bouncing_ball_plant.h, examples/van_der_pol/van_der_pol.cc, examples/van_der_pol/van_der_pol.h, systems/framework/framework_common.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/test/leaf_system_test.cc, systems/primitives/random_source.cc, systems/primitives/zero_order_hold.cc, systems/primitives/zero_order_hold.h
Even with pydrake bindings and new tests, this is still net-LOC negative.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15256)
=> [framework] Add sugar for declaring state output ports

geometry/proximity/hydroelastic_callback.h, geometry/proximity/mesh_plane_intersection.cc, geometry/proximity/mesh_plane_intersection.h, geometry/proximity/test/mesh_plane_intersection_test.cc
Support Part II of the [development plan for 14579](https://github.com/RobotLocomotion/drake/issues/14579#issuecomment-843618123). This PR for mesh_plane_intersection is similar to PR #15131 for mesh_intersection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15310)
=> [geometry] Select output format from mesh_plane_intersection in hydroelastics.

doc/_pages/reviewable.md
As requested by @EricCousineau-TRI while preparing the most recent release (v0.31.0).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15339)
=> [doc] Add process for release notes PR tags

common/drake_assert.h, common/drake_throw.h
This attribute is already used elsewhere, and it fixes compilation of
these files with MSVC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15351)
=> [common] Use [[noreturn]] instead of __attribute__((noreturn))

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/cost.cc, solvers/cost.h, solvers/test/cost_test.cc
Toward #15366.
Note: I've added the python binding for the class, but we currently don't have any `AddCost` variants that will support adding it to a `MathematicalProgram` (in python).  I looked at that, but it's more than I want to bite off now.  As is, this binding will still work for my shortest path problem code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15367)
=> [solvers] Add L2NormCost isa Cost

bindings/pydrake/solvers/mosek_py.cc, bindings/pydrake/solvers/test/mosek_solver_test.py, solvers/BUILD.bazel, solvers/mosek_solver.cc, solvers/mosek_solver.h, solvers/test/mosek_solver_test.cc
Dear @hongkai-dai,
The on-call build cop, @BetsyMcPhail , believes that your PR #15360 may have
https://drake-jenkins.csail.mit.edu/job/linux-bionic-clang-bazel-continuous-everything-leak-sanitizer/340/
https://drake-jenkins.csail.mit.edu/job/linux-bionic-clang-bazel-continuous-everything-address-sanitizer/3628/ …
=> Revert "MosekSolver sets logging using CommonSolverOption"

geometry/proximity_engine.cc, geometry/test/proximity_engine_test.cc
Tweak the error messages when attempting to load objs for collision.
Previously, many possible failure modes were indirectly detected via tinyobjs result containing "zero" objects. This mechanism provided insufficient feedback to resolve disparate causes (e.g., not an OBJ at all). Now, we distinguish various error modes and give more specific error messages.
related to #14480
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15373)
=> [geometry] Clarify obj parse error messages for proximity geometry

common/symbolic_expression.cc, common/symbolic_expression.h, common/symbolic_expression_cell.cc, common/symbolic_expression_cell.h, common/test/symbolic_expression_cell_test.cc
The prior change to remove const from the shared_ptr (#11756) left open the const propagation hole when directly accessing the member field.
Here, we introduce getters for the cell so that constness is preserved, and switch the downcasters to return direct cell references (instead of shared_ptr references) because none of the callers actually need to indirectly increment the shared_ptr count.
This is a breaking change insofar as some `ExpressionCell` signatures have changed.  We consider `ExpressionCell` to be an internal implementation detail, though we have not moved it to the `internal` namespace yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15364)
=> [common] Clean up ExpressionCell const-ness

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc
Drake does not create implicit frames for joints, so an error occurs if a joint name is referenced in `//frame/@attached_to`. The fix here is to use libsdformat to resolve for the parent body instead of searching for the frame in the plant.
This also changes uses of `node_index` to `index` as the latter is the preferred API.
/cc @EricCousineau-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15279)
=> parsing: Fix how parent bodies are resolved for frames attached to joints

common/type_safe_index.h, multibody/fixed_fem/dev/dirichlet_boundary_condition.h, multibody/fixed_fem/dev/fem_state_base.cc, multibody/fixed_fem/dev/test/stretch_test.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_reachable_test.cc, multibody/plant/multibody_plant.cc, multibody/plant/test/multibody_plant_reflected_inertia_test.cc, multibody/tree/multibody_tree.cc, solvers/csdp_solver.cc
In Eigen 3.4, implicit conversion from TypeSafeIndex to int may fail.
When needed, use the int constructor explicitly.
Working towards #14968
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15335)
=> Prepare for Eigen 3.4

manipulation/kuka_iiwa/BUILD.bazel, manipulation/kuka_iiwa/test/iiwa_command_sender_test.cc, manipulation/kuka_iiwa/test/iiwa_status_receiver_test.cc
These classes are likely to be used on the critical path for robot control, so we insist they must not perform heap operations while in steady-state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15389)
=> [kuka_iiwa] Add unit tests to lock in heap-less operation

examples/multibody/cassie_benchmark/BUILD.bazel, examples/multibody/cassie_benchmark/test/cassie_bench.cc
This only tests Expression when using constants (not variables), but still serves as a proxy for the overhead of Expression vs double in cases where not all C++ variables are necessarily symbolic variables.
I found this useful when experimenting with various simplifications of Expression's constant cells.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15379)
=> [cassie_bench] Add Expression support

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/deformable_contact_data.cc, multibody/fixed_fem/dev/deformable_contact_data.h, multibody/fixed_fem/dev/deformable_model.cc, multibody/fixed_fem/dev/deformable_model.h, multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/mesh_utilities.cc, multibody/fixed_fem/dev/mesh_utilities.h, multibody/fixed_fem/dev/reference_deformable_geometry.cc, multibody/fixed_fem/dev/reference_deformable_geometry.h, multibody/fixed_fem/dev/run_cantilever_beam.cc, multibody/fixed_fem/dev/test/deformable_contact_test.cc, multibody/fixed_fem/dev/test/deformable_model_test.cc, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, multibody/fixed_fem/dev/test/mesh_utilities_test.cc, multibody/fixed_fem/dev/test/stretch_test.cc
Approximate signed distance field for deformable bodies
* Augment reference configuration deformable geometry with an approximate signed distance field. We precompute the signed distance at each vertex of the deformable mesh at *reference* configuration and approximate the signed distance at the contact point in the *deformed* configuration by linearly interpolating the precomputed values at the vertices.
* The domain of the approximated signed distance field is strictly in the interior of the deformable mesh and the value is non-positive.
* Collect this approximated signed distance information with DeformableContactData.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/1 …
=> Deformable body distance field

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/BUILD.bazel, geometry/collision_filter_declaration.h, geometry/collision_filter_manager.cc, geometry/collision_filter_manager.h, geometry/geometry_set.h, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/scene_graph_inspector.h, geometry/test/collision_filter_manager_test.cc, geometry/test/geometry_state_test.cc, geometry/test/scene_graph_test.cc
Provides a public-facing API to access the new `CollisionFilter` mechanism.
- Adds the `CollisionFilterManager` class
- including python bindings
- Binds the previously unbound `CollisionFilterDeclaration` (now that there is a public API to consume it).
- Move some documentation from `CollisionFilterDeclaration` to `CollisionFilterManager`
- `GeometryState` completely loses its legacy API (`ExcludeCollisionsWithin`and `ExcludeCollisionBetween`). This is *technically* breaking because `GeometryState` is erroneously in the `geometry` namespace. But no one actually accesses the class.
- `SceneGraph` offers API access to the `CollisionFilterManager`
- Labels the old API as "legacy".
- old API expressed in terms of collision filter manager.
- Documentation that referenced legacy API updated.
- …
=> [geometry] Adds new public API for manipulating collision filters

common/trajectories/test/bspline_trajectory_test.cc, common/trajectories/test/discrete_time_trajectory_test.cc, common/trajectories/test/piecewise_polynomial_test.cc, common/trajectories/test/trajectory_test.cc, math/test/bspline_basis_test.cc, math/test/quadratic_form_test.cc
_"Only test for a specific subtype of `std::exception` when the subtype is **necessary** to determine whether the code behaved correctly."_
-- per https://github.com/RobotLocomotion/styleguide/pull/45/commits/c68a09ad882b81c825cf824062d3abb62487f51a which has been merged, but hasn't percolated to reach our GSG website hosting yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15377)
=> [trajectories] Update exception unit tests to match current guide

common/BUILD.bazel, common/bit_cast.h, common/test/bit_cast_test.cc, perception/BUILD.bazel, perception/test/point_cloud_to_lcm_test.cc
This is similar to https://en.cppreference.com/w/cpp/numeric/bit_cast, but we need to roll our own until we have C++20 available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15380)
=> [common] Add bit_cast function

bindings/pydrake/systems/_lcm_extra.py, bindings/pydrake/systems/lcm_py.cc, bindings/pydrake/systems/test/lcm_test.py, systems/lcm/serializer.h, systems/lcm/test/serializer_test.cc
Modernize "= default" boilerplate while we're here.
This is breaking change because we add a new pure-virtual method to the C++ SerializerInterface base class.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15394)
=> [lcm] SerializerInterface is now cloneable

bindings/pydrake/math_py.cc, math/discrete_algebraic_riccati_equation.cc, math/discrete_algebraic_riccati_equation.h, math/test/discrete_algebraic_riccati_equation_test.cc
I've been using this overload to compute the LQR gains for implicit model following (using feedback to make one model behave like another, but without extra states hence "implicit").
The relations `Q_new = (A - A_ref)^T Q (A - A_ref)`, `R_new = B^T Q B + R`, and `N_new = (A - A_ref)^T QB` I used in the tests came from equation (C.9) in appendix C of https://file.tavsys.net/control/controls-engineering-in-frc.pdf. This should probably be documented in the test itself, but I'm not sure what your guidelines are for referencing external works, or if there's some other way you'd like me to do this.
I'm also open to a simpler way of defining the cost matrices, but this was the easiest way I was able to create a set of matrices that led to a positive semidefinite DARE solution; naively choosing …
=> [math] Add DARE overload that takes Q, R, and N cost matrices

bindings/pydrake/lcm_py.cc, bindings/pydrake/test/lcm_test.py, lcm/BUILD.bazel, lcm/drake_lcm.cc, lcm/drake_lcm.h, lcm/test/drake_lcm_test.cc, lcm/test/initialization_sequence_test.py, lcm/test/initialization_sequence_test_stub.cc
This can be useful if the scheduling configuration for new threads varies between the construction time and and first use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15390)
=> [lcm] Give DrakeLcm the ability to defer launching its thread

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.h
There are a number of very similar entry points for adding costs to mathematical program.  We only binding a subset of them so far.  I elected to bind this variant because we don't currently binding the constructor for the `Binding_*` classes (although I've confirmed that this is also easy to do).
This also follows the current pattern in `AddConstraint`.  The `AddConstraint((shared_ptr)` variant was already bound, but `AddConstraint(Binding<Constraint>)` is not (yet).
For most cases, we've avoided needing this because `MathematicalProgram` provides enough sugar methods to construct and add all of the variants of costs and constraints that user have been asking for.  But `L2NormCost` is a new case (until we outwait the deprecation period) where we cannot offer the right sugar.
Related to …
=> [solvers] Add bindings for MathematicalProgram::AddCost(shared_ptr, vars)

manipulation/kuka_iiwa/iiwa_command_receiver.cc, manipulation/kuka_iiwa/iiwa_command_receiver.h, manipulation/kuka_iiwa/iiwa_command_sender.cc, manipulation/kuka_iiwa/iiwa_command_sender.h, manipulation/kuka_iiwa/iiwa_status_receiver.cc, manipulation/kuka_iiwa/iiwa_status_receiver.h, manipulation/kuka_iiwa/iiwa_status_sender.cc, manipulation/kuka_iiwa/iiwa_status_sender.h
Adjust includes to remove extra / add missing.
Add using-statements so names don't flap while syncing this to Anzu.
Stop inlining the destructors (GSG) and mark classes as final.
Remove superfluous this-> and whitespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15403)
=> [kuka_iiwa] Clean and adjust for better parity with Anzu

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/scene_graph.h, geometry/test/scene_graph_test.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
The only meaningful invocation of the old API (outsdie of tests) was in `MultibodyPlant`. Using the new API required modifying the `symbolic::Expression` stub to include a stub `CollisionFilterManager`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15396)
=> [geometry] Deprecate old collision filter API; use CollisionFilterManager

examples/multibody/cassie_benchmark/conduct_experiment, examples/multibody/cassie_benchmark/copy_results_to, tools/performance/BUILD.bazel, tools/performance/README.md, tools/performance/benchmark_tool.py
Change its invocations to match.
This is in preparation for changing it into a bazel py_binary, while preserving git history.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15420)
=> [performance] Add .py suffix to benchmark_tool

common/test/value_test.cc, common/value.h
Note that we don't need to bind this in pydrake; with dynamic typing, there is no need for a "maybe" flavor of the getters.
This new function will be used by a forthcoming `framework` optimization, to supplant a `dynamic_cast` (#15419).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15418)
=> [common] Add Value::maybe_get_mutable_value

bindings/pydrake/solvers/mathematicalprogram_py.cc
Otherwise, type signatures may have C++ types
Resolves #15407
Will be better in conjunction with #15409 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15410)
=> py mp: Reorder overall bindings for better Python type signatures

multibody/plant/multibody_plant.cc, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_point_pair_contact.py
For visualizing hydroelastic contact, the visualized quantities would label a pair of geometries and show various quantities. One was labeled simply "Spatial force" but didn't indicate which body in the pair the force was acting on. This adds the name of the body being acted on.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15416)
=> [drake_visualizer] Label spatial force on object in for hydro contact

bindings/pydrake/pydrake_doxygen.h
Encodes discussion from: https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1626366534036100
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15404)
=> pydrake: Add guidance for ambiguous const-vs-mutable overloads

examples/acrobot/BUILD.bazel, examples/acrobot/benchmark_autodiff.cc, examples/multibody/cassie_benchmark/BUILD.bazel, examples/multibody/cassie_benchmark/test/cassie_bench.cc, geometry/benchmarking/BUILD.bazel, systems/benchmarking/BUILD.bazel, systems/benchmarking/README.md, systems/benchmarking/framework_benchmarks.cc, tools/performance/BUILD.bazel, tools/performance/defs.bzl, tools/performance/fixture_common.cc, tools/performance/fixture_common.h
This first benchmark only measures the throughput of PassThroughSystem and Diagram when used with vector-valued ports.  Even so, it is enough to highlight unnecessary spending on dynamic casts.
Factor out a common cc_binary rule between the existing cassie_benchmark and the newly-added systems/benchmarking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15422)
=> [systems] Add one elementary benchmark

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/dynamic_elasticity_model.h, multibody/fixed_fem/dev/elasticity_model.h, multibody/fixed_fem/dev/fem_model.h, multibody/fixed_fem/dev/fem_model_base.cc, multibody/fixed_fem/dev/fem_model_base.h, multibody/fixed_fem/dev/fem_solver.h, multibody/fixed_fem/dev/fem_state_base.h, multibody/fixed_fem/dev/newmark_scheme.h, multibody/fixed_fem/dev/state_updater.h, multibody/fixed_fem/dev/static_elasticity_model.h, multibody/fixed_fem/dev/test/fem_solver_test.cc, multibody/fixed_fem/dev/test/newmark_scheme_test.cc, multibody/fixed_fem/dev/test/zeroth_order_state_updater_test.cc, multibody/fixed_fem/dev/zeroth_order_state_updater.h
* Remove all occurance of "highest order state" in favor of "unknown variable" because the unknown variable being solved for in FEM is *not* necessarily the highest order state. Relate RobotLocomotion#15349.
* Template StateUpdater on the scalar type instead of the State type and move it from state-templated FemModel to type-templated FemModelBase.
* Move the method State::get_highest_order_state() to StateUpdater::GetUnknowns() as the FemState by itself cannot determine which variable is the "unknown". That information is held by StateUpdater.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15357)
=> [fem] Reconcile unknown variable and highest order state

systems/framework/leaf_system.cc, systems/framework/output_port.cc, systems/framework/test_utilities/pack_value.h, systems/framework/value_checker.h
The AbstractValue implementation goes to great lengths to avoid dynamic_cast, because RTTI checking is exceedingly slow, relative to what we expect during an inner loop. We should use its built-in type checking functions, instead of casting ourselves.
The leaf_system.cc vector cast was showing up as a profiling hot spot, but even without that we should make this change, even in test code. Trying to directly cast sets a bad example for others to imitate.
This provides a minor (~5%) speed-up on the forthcoming PassThrough3 benchmark (where three vector-valued pass through systems are cascaded within a diagram) at #15422.
--- …
=> [framework] Never dynamic_cast an AbstractValue

systems/analysis/BUILD.bazel, systems/analysis/region_of_attraction.cc, systems/analysis/region_of_attraction.h, systems/analysis/test/region_of_attraction_test.cc
In response to https://stackoverflow.com/questions/68344096/is-regionofattraction-available-for-multibody-plants-from-pydrake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15425)
=> [analysis] Support fixed input ports in RegionOfAttraction

bindings/pydrake/pydrake_doxygen.h
Reverts RobotLocomotion/drake#15404.
This commit made the entire document disappear from the website (https://drake.mit.edu/doxygen_cxx/group__python__bindings.html).
The problem has something to do with the triple-backtick example at the end of the new section, but I can't figure out why Doxygen is getting upset about it.
\CC @EricCousineau-TRI FYI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15439)
=> Revert "pydrake: Add guidance for ambiguous const-vs-mutable overloads"

solvers/BUILD.bazel, solvers/mosek_solver.cc, solvers/solver_interface.h, solvers/test/mosek_solver_test.cc
As mentioned in the issue https://github.com/RobotLocomotion/drake/issues/15342#issuecomment-879038929
Fix MosekSolver first as several users are calling Mosek recently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15411)
=> MosekSolver throws a runtime error when the solver option is not set correctly

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/piecewise_polynomial.h
Related to #15427
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15433)
=> [py trajectories] support passing matrix coefficients to ZeroOrderHold

bindings/pydrake/examples/multibody/pendulum_lqr_monte_carlo_analysis.py, bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py, examples/pendulum/Pendulum.urdf, examples/pendulum/print_symbolic_dynamics.cc, examples/pendulum/test/urdf_dynamics_test.cc, systems/controllers/test/dynamic_programming_test.cc, systems/sensors/test/accelerometer_test.cc, systems/sensors/test/gyroscope_test.cc, systems/trajectory_optimization/test/direct_transcription_test.cc, tutorials/pyplot_animation_multibody_plant.ipynb
The pendulum urdf should *not* be floating by default.  This tripped me up quickly when I was testing something, and I'd like to resolve it now.
This is in some sense an API-breaking change without deprecation.  I don't know how to deprecate the urdf.
Code using the old workflow does get a quite clear error message:
```
RuntimeError: This MultibodyGraph already has a joint 'base_weld' connecting 'WorldBody' to 'base'. Therefore adding joint 'WorldBody_welds_to_base' connecting 'WorldBody' to 'base' is not allowed.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15426)
=> [examples/pendulum] Include weld joint in Pendulum.urdf

tools/skylark/drake_cc.bzl
Using missing-field-initializers has a poor true/false positive ratio.  Resolve the TODO in favor of no action.
For reference, these are the (only) three complaints that we'd see if we were to turn this on today:
```console
geometry/render/render_engine_vtk.cc:193:45: error: missing initializer for member 'drake::geometry::render::{anonymous}::RegistrationData::mesh_filename' [-Werror=missing-field-initializers]
RegistrationData data{properties, X_WG, id};
manipulation/perception/test/optitrack_pose_extractor_test.cc:168:39: error: missing initializer for member 'optitrack::optitrack_rigid_body_description_t::parent_id' [-Werror=missing-field-initializers]
message.rigid_bodies = {{"test", 10}};
solvers/scs_solver.cc:755:21: error: missing initializer for member 'SCS_INFO::status' …
```
=> [skylark] Remove TODO about -Wmissing-field-initializers

systems/framework/diagram_output_port.h, systems/framework/leaf_system.cc, systems/framework/system.h
Note that this leaves a couple more hot-path dynamic_casts still in place (currently shown in #15421 as a WIP), because they are more complicated to reason about.
The baseline performance (with #15419 already applied):
```
---------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations
---------------------------------------------------------------------------
BasicFixture/PassThrough3_mean         1233 ns         1233 ns            9
BasicFixture/PassThrough3_median       1224 ns         1224 ns            9
BasicFixture/PassThrough3_stddev       30.7 ns         30.7 ns            9
BasicFixture/PassThrough3_min          1209 ns         1209 ns            9
BasicFixture/PassThrough3_max          1308 …
```
=> [framework] Use static_cast (not dynamic_cast) in hot paths

multibody/tree/test/screw_mobilizer_test.cc
With Eigen 3.4, gtest was trying to print an Eigen expression tree using it's stl compatibility iterators, which violates an Eigen static assert related to matrixes with non-trivial layouts.
Force it to a concrete Matrix type so that printing compiles again (when using Eigen 3.4).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15445)
=> [tree] Fix screw_mobilizer_test vs Eigen 3.4

bindings/pydrake/multibody/plant_py.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_com_test.cc, multibody/plant/test/multibody_plant_jacobians_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h
New overload for MultibodyPlant::CalcJacobianCenterOfMassTranslationalVelocity() to allow for model_instances 
to resolve issue #14916.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15387)
=> Allow model_instances for MBP::CalcJacobianCenterOfMassTranslationalVelocity()

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py
As part of the effort to introduce a top-level package.xml for Drake (see #10531), the `PackageMap` will be updated to include the top-level package reference during initialization. This binding will be used in tests which currently assume that the `PackageMap` is initialized empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15430)
=> pydrake: Add binding for PackageMap.Remove

common/symbolic_formula.h, common/test/symbolic_expression_test.cc
#15065 added not_equal_strict, but we also need equal_strict for Eigen 3.4 compatibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15452)
=> [common] Add another Eigen::numext specialization for Expression

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/fixed_fem/dev/mesh_utilities.cc, multibody/fixed_fem/dev/mesh_utilities.h, multibody/fixed_fem/dev/permute_block_sparse_matrix.cc, multibody/fixed_fem/dev/permute_block_sparse_matrix.h, multibody/fixed_fem/dev/test/deformable_contact_test.cc, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc, multibody/fixed_fem/dev/test/permute_block_sparse_matrix_test.cc
* Calculate the free motion tangent matrix for all deformable bodies in
DeformableRigidManager.
* Permute the free motion tangent matrix to group dofs in contact.
* Calculate the Schur complement of the free motion tangent matrix based
on contact participation.
* Assemble the tangent matrix for contact with full mass matrix for
rigid dofs and the Schur complements of the free motion tangent matrices
for participating deformable bodies.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15417)
=> [fem] Calculate tangent matrix for contact

bindings/pydrake/__init__.py, bindings/pydrake/common/deprecation.py, bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/mathematicalprogram.py, bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
`pydrake/__init__.py`:
- Do not repeat leading `_` for ExecuteExtraPythonCode
- Allow forwarding of private `_` variables from cc modules
deprecation:
- Fix (Py 2 -> Py 3) for empty `AttributeError` messages
- Add `ModuleShim._install(*, auto_all)`
Resolves #15406
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15409)
=> py mp: Use template Binding[{Type}]; deprecate old Binding_{Type}

geometry/geometry_state.h, geometry/query_object.cc, geometry/query_object.h, geometry/test/query_object_test.cc
A step in the [implementation plan for 14579](https://github.com/RobotLocomotion/drake/issues/14579#issuecomment-843618123). This PR #15210 (QueryObject) is after PR #15204 (ProximityEngine).
After this PR, we'll move from `geometry` to `multibody` in PR #15436 (MultibodyPlant) .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15210)
=> [geometry] QueryObject's new queries for hydroelastics.

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
Follow-up fix to #15409
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15457)
=> py mp: Fix docstring spelling for forwarded module

common/symbolic_formula.h, common/test/symbolic_expression_test.cc
In various Eigen algorithms ([ec323b7](https://gitlab.com/libeigen/eigen/-/commit/ec323b7e6643d9da3d9cda86570cc7724e0a8d3c)), it uses "short-circuit when zero" guards to skip computationally expensive steps in cases where knows the end result will remain unchanged.
When we have Expressions filled with only constants, this works fine. However, when we have Expressions filled with Variables, trying to check for zero throws an exception because the resulting Formula cannot convert to back to a bool -- and in any case, we want the full expression tree anyway, without any short-circuits, for doing symbolic evaluation later.
Therefore, we tweak `Eigen::numext::not_equal_strict` to special-case its results if either of the operands is a literal zero, with no throwing even if the other operand …
=> [common] Fine tune {not_,}equal_strict<Expression> for Eigen 3.4

solvers/gurobi_solver.cc, solvers/test/gurobi_solver_test.cc
As mentioned in the comment https://github.com/RobotLocomotion/drake/issues/15342#issuecomment-879038929
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15412)
=> GurobiSolver throws errors when option is set incorrectly.

common/symbolic_expression_cell.h
We do not appear to take advantage of the copy / move construction at all (and we have const members, so I suspect move was doing copies anyway).
For optimizations like opportunistic mutation (#10900) or more careful sharing, it seems like having implicit copies available might be a bit of a hazard.
Similarly, the base class default destructor is dead code, so is removed.
Fix a stray comment on a factory default constructor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15466)
=> [common] Remove copy/move from ExpressionCell

geometry/optimization/BUILD.bazel, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
This first PR adds the graph construction / maintenance logic only.  I've separated the actual mathematical programming part to follow-up PRs, so that they can be reviewed more carefully.
The additional correctness of the added costs/constraints on an edge will be established in the next PR, once the Solve method becomes available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15413)
=> [geometry/optimization] Add GraphOfConvexSets

geometry/geometry_state.cc, geometry/test/geometry_state_test.cc
When a renderer is added to 1SceneGraph1 *after* geometry was registered, the (renderer, accepting) property wasn't respected. That led, in rare cases where the property was used, that geometries would end up in the
wrong render engines.
This makes sure that the property is respected.
Resolves #14198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15448)
=> [render] Respect (renderer, accepting) for post-hoc renderers

systems/framework/cache_doxygen.h, systems/framework/context_base.h
Add some documentation to clarify that caching is enabled by default in Drake.
Resolves #15478
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15480)
=> Clarify that caching is enabled by default

examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc, examples/simple_gripper/simple_gripper.cc, multibody/plant/test/box_test.cc, multibody/plant/test/floating_body_test.cc, multibody/tree/test/revolute_spring_test.cc
This should be enabled by default; ideally, we don't show this to users in examples unless it's explicitly for debugging caching / computation issues.
Relates #15478
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15479)
=> multibody, examples: Remove unnecessary calls to EnableCaching()

systems/framework/system.cc, systems/framework/system_base.h, systems/framework/test/cache_entry_test.cc
These overloads are not commonly necessary, so tend to clutter up the documentation and lead users to either add unnecessary boilerplate or fail to reuse context storage efficiently.
Refer to #15174, #15175, #15176, and #15190 for the kinds of boilerplate that we'll now discourage.
In cases where these signatures were important, users can fall back to using the full set of ValueProducer constructor overloads for maximum flexibility.
Towards #15161.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15443)
=> [framework] Deprecate dispreferred DeclareCacheEntry overloads

systems/framework/diagram.cc, systems/framework/framework_common.h
Towards #15421.  (This is the last of the hot spots that I've found to date.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15470)
=> [framework] Use static_cast (not dynamic_cast) in hot path

multibody/plant/test/multibody_plant_test.cc, systems/framework/system.h, systems/framework/test/system_test.cc
This PR adds a docstring and some tests confirming the behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15437)
=> [systems/framework] FixInputPortsFrom does not support type-dependent abstract ports

solvers/constraint.cc, solvers/constraint.h, solvers/test/constraint_test.cc
Before Display(ExpressionConstraint) would output
```
ExpressionConstraint with 3 decision variables x0 x1 x2
```
Now we can get beautiful output like:
```
ExpressionConstraint
0 <= (1 + pow(x0, 2)) <= 2
0 <= (x2 + pow(x1, 2)) <= 2
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15472)
=> [solvers] Implement Display for ExpressionConstraint

systems/controllers/test/linear_quadratic_regulator_test.cc
Resolves #15481.
I also tested this on top of PR #15142 , the test passes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15486)
=> Fix LQR test, use a controllable system.

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/piecewise_polynomial.h
Takes the pattern established in #15433, and implements it for the remaining construction methods.
Resolves #15427.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15442)
=> [py/trajectories] bind matrix versions of PiecewisePolynomial

systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/test/leaf_system_test.cc
This overload was not commonly necessary, so tended to clutter up the documentation and lead users to add unnecessary boilerplate.  In cases where this signature was important, users can fall back to using the most generic form of allocator callback.
Towards #15161.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15485)
=> [framework] Deprecate dispreferred DeclareOutputPort overload

geometry/shape_specification.h
The documentation for the `Mesh` `Shape` had stale documentation. The new documentation is more accurate and prefers to defer to `QueryObject` for exactly how a mesh is used in proximity queries (rather than trying to duplicate that documentation here).
Likewise clean up `Convex` documentation to match.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15491)
=> [geometry] Correct stale documentation

multibody/tree/ball_rpy_joint.h, multibody/tree/body_node.h, multibody/tree/mobilizer.h, multibody/tree/multibody_tree.cc, multibody/tree/planar_joint.h, multibody/tree/prismatic_joint.h, multibody/tree/revolute_joint.h, multibody/tree/screw_joint.h, multibody/tree/universal_joint.h
Using a pointer to a pointer is extremely prone to use-after-free errors when the interior pointer changes through the call sequence.  Just one pointer indirection is plenty to denote what we intend.
Towards #15142.  That PR's CI confirms that this change makes a handful of tests stop segfaulting and/or tripping ASan.
I'd initially labeled this as "breaking change" due to API churn, but as it turns out all of these functions are `internal` namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15451)
=> [multibody] Avoid Eigen::Block<Eigen::Ref<VectorX>>

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/frames_as_joint_parent_or_child.sdf
This fixes the case where  `//joint/parent` or `//joint/child` is a frame instead of a link and that frame has a non-identity pose. The poses of the frames were being ignored because we incorrectly computing `X_PJ` and `X_CJ`. Instead of resolving these poses relative to the parent or child **bodies**, we were resolving them relative to the names in `//joint/parent` or `//joint/child`, which may  reference frames instead of bodies.
/cc @EricCousineau-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15290)
=> parsing: Fix joint pose computation when using frames as joint parent or child

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/collision_filter_declaration.h, geometry/collision_filter_manager.h, geometry/geometry_state.cc, geometry/proximity/collision_filter.cc, geometry/proximity/collision_filter.h, geometry/proximity/test/collision_filter_test.cc, geometry/proximity/test/collisions_exist_callback_test.cc, geometry/proximity/test/distance_sphere_to_shape_test.cc, geometry/proximity/test/find_collision_candidates_callback_test.cc, geometry/proximity/test/hydroelastic_callback_test.cc, geometry/proximity/test/penetration_as_point_pair_callback_test.cc, geometry/test/collision_filter_declaration_test.cc, geometry/test/proximity_engine_test.cc
Previous API only allowed for *adding* filters on geometry pairs. This introduces the API that can allow (generally) the removal of a filter from a geometry pair.
This introduces the concept of the "permanent" filter. It supports scene graph invariants (e.g., geometries affixed to the same frame are always filtered, etc.) This concept is purely internal -- it doesn't affect the public API.
The code changes include:
- `CollisionFilterDeclaration` gets new statement methods.
- `CollisionFilter` learns how to apply them.
- `CollisionFilterManager` documents the "invariant" filters.
- Touch numerous tests that depend on having a collision filter.
- Python bindings for new API.
Relates #15089.
--- …
=> [geometry] Add declaration to *remove* collision filters

bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py, bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/planar_scenegraph_visualizer.py, bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py, examples/manipulation_station/end_effector_teleop_sliders.py, examples/manipulation_station/joint_teleop.py, manipulation/util/show_model.py, tutorials/pyplot_animation_multibody_plant.ipynb
The planar visualizer had previously used a hackneyed approach to visualize. It would generate a `DrakeVisualizer` lcm message for loading and consume pose bundle for updating poses. This updates it to make use of the `SceneGraphInspector` and `QueryObject` for those tasks (akin to what meshcat visualizer does).
This is done in a deprecated, backwards-compatible way. The old spelling will still work, but if the visualizer is connected to a `PoseBundle`-valued port, the first call to `draw()` will dispatch a deprecation warning.
This lead to the following ancillary changes:
- All uses of `PlanarSceneGraphVisualizer` in Drake have been updated to use the new API (in fact, they've been updated to prefer using `ConnectPlanarSceneGraphVisualizer`).
- The old unit tests have simply been copied …
=> [visualization] planar visualizer uses SceneGraph API to visualize

math/test/quadratic_form_test.cc
We found that the prior value of 1E-15 was too tight with Eigen 3.4.
Closes #15449.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15488)
=> [math] Loosen test tolerance for quadratic_form

examples/multibody/cassie_benchmark/test/cassie_bench.cc
Closes #15401.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15495)
=> [cassie_benchmark] Allow Eigen 3.4 to use more heap operations

geometry/proximity/hydroelastic_callback.h, geometry/proximity/mesh_half_space_intersection.cc, geometry/proximity/mesh_half_space_intersection.h, geometry/proximity/test/mesh_half_space_intersection_test.cc
Support the [development plan for 14579](https://github.com/RobotLocomotion/drake/issues/14579#issuecomment-843618123). This PR for mesh_half_space_intersection is similar to PR #15310 for mesh_plane_intersection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15358)
=> [geometry] Select output format from mesh_half_space_intersection in hydroelastics.

common/trajectories/test/piecewise_polynomial_generation_test.cc
Caught by memcheck when running against Eigen 3.4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15499)
=> [trajectories] Fix uninitialized data in unit test

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/deformable_model.cc, multibody/fixed_fem/dev/elasticity_element.h, multibody/fixed_fem/dev/isoparametric_element.cc, multibody/fixed_fem/dev/isoparametric_element.h, multibody/fixed_fem/dev/linear_simplex_element.cc, multibody/fixed_fem/dev/linear_simplex_element.h, multibody/fixed_fem/dev/test/dynamic_elasticity_element_test.cc, multibody/fixed_fem/dev/test/dynamic_elasticity_model_test.cc, multibody/fixed_fem/dev/test/elasticity_element_test.cc, multibody/fixed_fem/dev/test/fem_solver_test.cc, multibody/fixed_fem/dev/test/isoparametric_element_test.cc, multibody/fixed_fem/dev/test/linear_simplex_element_test.cc, multibody/fixed_fem/dev/test/static_elasticity_element_test.cc, multibody/fixed_fem/dev/test/static_elasticity_model_test.cc, multibody/fixed_fem/dev/test/stretch_test.cc
Misc improvements:
* Move IsoparametricElement and LinearSimplexElement into internal::
namespace.
* Add CalcGradientInSpatialCoordinates() method.
* Move implementations to .cc file and use protected DoFoo() methods in
the CRTP base class to comply with style guide rules on inline methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15440)
=> [fem] Improve IsoparametricElement

geometry/optimization/BUILD.bazel, geometry/optimization/iris.cc, geometry/optimization/iris.h, geometry/optimization/test/iris_test.cc
This is a first pass at the algorithm, using Snopt/Ipopt but not (yet) backed by Ibex/dReal.  That will come in the next PR.
There is still an open question about whether we can use ONLY Ibex/dReal, instead of Snopt.  But based on python experiments, I believe we can use Snopt first and then follow with Ibex/dReal to confirm that our sets are collision free. Furthermore, this Snopt version is useful immediately, and including Ibex/dReal will not change the interface, only the backend.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15476)
=> [geometry/optimization] Adds IrisInConfigurationSpace

solvers/osqp_solver.cc, solvers/test/osqp_solver_test.cc
Verbosity can now be controlled by either the solver-specific "verbose" flag, or the Drake common property `kPrintToConsole`.
Relates #12867
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15501)
=> [solver] OsqpSolver respects CommonSolverOptions::kPrintToConsole

solvers/ipopt_solver.cc, solvers/test/ipopt_solver_test.cc
Verbosity can now be controlled by either the solver-specific "print_level" flag, or the Drake common property `kPrintToConsole`.
Relates #12867
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15502)
=> [solver] IpOptSolver respects CommonSolverOptions::kPrintToConsole

systems/primitives/BUILD.bazel, systems/primitives/test/vector_log_limit_malloc_test.cc, systems/primitives/test/vector_log_test.cc, systems/primitives/vector_log.cc, systems/primitives/vector_log.h
Relevant to: #10228
This is step 1 of 4 to deprecate and replace SignalLogger and SignalLog
with a logging system that avoids threading hazards (SignalLogger) and
slow memory management (SignalLog).
VectorLog will eventually replace SignalLog. Improvements include
doubling reallocation on growth (similar to std::vector), a Reserve()
method to pre-allocate log space ahead of time, and adjustment of the
AddData() signature to avoid unnecessary object copying and memory
allocations.
New unit tests demonstrate basic functionality, log storage growth, and
avoidance of run-time dynamic allocations via Reserve().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15484)
=> primitives: Introduce VectorLog

bindings/pydrake/common/test/wrap_function_test.cc, bindings/pydrake/common/wrap_function.h
Resolves #15505
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15507)
=> wrap_function: Preserve return type for mutable and const class methods

multibody/parsing/BUILD.bazel, multibody/parsing/detail_ignition.cc, multibody/parsing/detail_ignition.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_sdf_parser.h, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/detail_urdf_parser.h, multibody/parsing/parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/interface_api_test/arm.forced_nesting_sdf, multibody/parsing/test/sdf_parser_test/interface_api_test/arm.urdf, multibody/parsing/test/sdf_parser_test/interface_api_test/gripper.sdf, multibody/parsing/test/sdf_parser_test/interface_api_test/mug.sdf, multibody/parsing/test/sdf_parser_test/interface_api_test/package.xml, multibody/parsing/test/sdf_parser_test/interface_api_test/table.sdf, multibody/parsing/test/sdf_parser_test/interface_api_test/table_and_mug.forced_nesting_sdf, multibody/parsing/test/sdf_parser_test/interface_api_test/top.sdf
Closes #14295.
This allows Drake to parse URDF files bypassing libsdformat's native URDF parser. It makes use of libsdformat's [Interface API](http://sdformat.org/tutorials?tut=composition_proposal&cat=pose_semantics_docs&#1-5-minimal-libsdformat-interface-types-for-non-sdformat-models) by registering a custom parser for `*.urdf` files.
This also removes additional implicit model frames created for nested models that were missed in #15099.
A large portion of this PR was taken from @EricCousineau-TRI's [prototype](https://github.com/RobotLocomotion/drake/pull/13128) 
//cc @EricCousineau-TRI
Needs: https://github.com/RobotLocomotion/drake/pull/15290
--- …
=> parsing: Use libsdformat's Interface API to parse URDF files

manipulation/planner/test/differential_inverse_kinematics_test.cc
The likelihood that `MultibodyPlant::CreateDefaultContext()` returns null is very small.
(This is the only place within Drake where we `DRAKE_THROW_UNLESS` on a bare pointer without any explicit comparison to nullptr.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15512)
=> [planner] Remove useless assertion in test

bindings/pydrake/common/test/cpp_template_test.py, common/drake_copyable.h, multibody/tree/mobilizer_impl.h
Fun fact, not all uses of "that that" are typos.
In some cases, update word wrap.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15511)
=> Remove rare typos "this this" and "that that".

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
@wualbert pointed out on Slack that this binding was missing, while the considerably less efficient CalcMassMatrixViaInverseDynamics() was available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15520)
=> Add missing pybinding for CalcMassMatrix()

common/BUILD.bazel, common/autodiff_overloads.h, common/extract_double.h, common/symbolic_expression.h, common/test/autodiff_overloads_test.cc, common/test/extract_double_test.cc, common/test/symbolic_expression_test.cc, systems/analysis/hermitian_dense_output.h
Revives and completes #13003.
I needed this method again, and my c++ foo has grown, so I decided to slay the old dragon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15518)
=> common: provides ExtractDoubleOrThrow for Eigen::MatrixBase

multibody/fixed_fem/dev/constitutive_model.h, multibody/fixed_fem/dev/corotated_model.h, multibody/fixed_fem/dev/corotated_model_data.h, multibody/fixed_fem/dev/deformation_gradient_data.h, multibody/fixed_fem/dev/element_cache_entry.h, multibody/fixed_fem/dev/linear_constitutive_model.h, multibody/fixed_fem/dev/linear_constitutive_model_data.h
Explicitly defining default destructors for non-polymorphic classes
may misleadingly suggest that the class is polymorphic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15527)
=> [fem] Remove redundant default destructor definitions

multibody/parsing/BUILD.bazel
I'm not sure why we had these partially public, so this just completely seals things.
Could possibly help for #15477, but IMO this is a standalone improvement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15535)
=> parsing: Encapsulate (make private) all detail_* libraries

multibody/fixed_fem/dev/fem_indexes.h
Fix the bug that the index aliased by `DeformableBodyIndex` doesn't follow the convention and the resulting index has the same type as the one aliased by "multibody::internal::BodyIndex".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15542)
=> [fem] Make fem indexes follow TypeSafeIndex convention

systems/framework/value_producer.h
When using Eigen 3.4 pre-release, the prior spelling ends up with inexplicable compilation errors when using Apple Clang; this new spelling seems to work better.
Closes #15498.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15517)
=> [framework] Respell SFINAE for Apple Clang

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/parser_test.cc
The previous behavior of allowing for multiple models was deprecated, and is now removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15540)
=> [parsing] Require exactly one model or world

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/proximity/distance_to_point_callback.cc, geometry/proximity/distance_to_point_callback.h, geometry/proximity/distance_to_shape_callback.cc, geometry/proximity/test/distance_sphere_to_shape_test.cc, geometry/proximity/test/distance_to_point_callback_test.cc, geometry/query_results/signed_distance_pair.h, geometry/query_results/signed_distance_to_point.h
This removes the deprecated member indicating whether the gradient of a signed distance query is "unique".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15532)
=> [geometry] Finish deprecation of "is gradient unique" from signed distance queries

multibody/fixed_fem/dev/matrix_utilities.h, multibody/fixed_fem/dev/permute_block_sparse_matrix.h, multibody/fixed_fem/dev/test/matrix_utilities_test.cc
This matrix utility method facilitates mapping velocities/contact forces
in the original order of the deformable vertices to the order where
all participating vertex quantities come first and vice versa.
Fix typo in documentation of PermuteBlockSparseMatrix().
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15536)
=> [fem] Add PermuteBlockVector()

common/drake_throw.h, common/test/drake_throw_test.cc
For a raw pointer, when checking for null we'd like to insist on an explicit mention of `nullptr`:
Example function:
`void DoStuff(Foo* foo) { ... }`
Correct:
`DRAKE_THROW_UNLESS(foo != nullptr);`
Incorrect:
`DRAKE_THROW_UNLESS(foo);`
Because the macro is intended to provide a useful exception message to users, we should err on the side of extra detail about the failure condition.  The meaning of "foo" isolated within error message text does not make it clear that a null pointer is the proximate cause of the problem.
In the future, we could imagine even better macros or improved error messages, where even saying `!= nullptr` was an anachronism.  (For example, `DRAKE_NONNULL(foo);`.)  For now, though, just linting for some minimal cases at least captures and holds _some_ ground, and will …
=> [common] Deprecate DRAKE_THROW_UNLESS on a bare pointer

tools/workspace/styleguide/repository.bzl
Missed after https://github.com/RobotLocomotion/styleguide/pull/46.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15547)
=> [workspace] Upgrade styleguide latest commit

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py, examples/manipulation_station/differential_ik.py, examples/mass_spring_cloth/cloth_spring_model.cc, examples/planar_gripper/planar_gripper_lcm.cc, examples/planar_gripper/planar_manipuland_lcm.cc, examples/rod2d/rod2d.cc, manipulation/kuka_iiwa/iiwa_command_receiver.cc, manipulation/planner/differential_inverse_kinematics_integrator.cc, multibody/fixed_fem/dev/deformable_model.cc, multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/plant/multibody_plant.cc, multibody/plant/test/discrete_update_manager_test.cc, systems/analysis/test/simulator_test.cc, systems/controllers/test/linear_model_predictive_controller_test.cc, systems/framework/BUILD.bazel, systems/framework/discrete_values.h, systems/framework/test/discrete_values_test.cc, systems/framework/test/system_symbolic_inspector_test.cc, systems/framework/vector_system.h, systems/primitives/affine_system.cc, systems/primitives/discrete_derivative.cc, systems/primitives/discrete_time_delay.cc, systems/primitives/linear_system.cc, systems/primitives/test/linear_system_test.cc, systems/primitives/zero_order_hold.cc, systems/trajectory_optimization/test/direct_transcription_test.cc
Related to #9171
Removes one level of indirection required in writing a discrete variable update method.  Now one can set/get the Eigen::VectorX directly, without having to use `discrete_values->get_vector()->set_value(...)`, etc. 
Importantly, this also makes it possible to do more things without having to ever think about `BasicVector`.
I've included a second commit applying this sugar throughout the codebase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15539)
=> [systems/framework] Sugar for setting/getting Eigen::VectorX data from DiscreteValues

common/sorted_pair.h, common/test/sorted_pair_test.cc
We can now do:
```c++
SortedPair<Foo> pair{Foo(1), Foo(2)};
const auto& [a, b] = pair;
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15551)
=> Gives SortedPair compatibility with structured bindings

multibody/fem/BUILD.bazel, multibody/fem/deformation_gradient_data.cc, multibody/fem/deformation_gradient_data.h, multibody/fem/test/deformation_gradient_data_test.cc, multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/constitutive_model.h, multibody/fixed_fem/dev/corotated_model_data.h, multibody/fixed_fem/dev/deformation_gradient_data.cc, multibody/fixed_fem/dev/linear_constitutive_model_data.h
Also move a concrete derived class of DeformationGradientData,
LinearConstitutiveModelData out of dev.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15526)
=> [fem] Move DeformationGradientData out of dev

systems/primitives/vector_log.cc
In Eigen 3.4, implicit conversion from reset_after_move to int may fail.  When needed, use the int constructor explicitly.
This is like f0cdd44674c6c4c4f05ae1b3a4e4bfc935ba0a31, but for new code written after that fix was made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15556)
=> Adapt uses of reset_after_move vs Eigen 3.4 prerelease

systems/primitives/BUILD.bazel, systems/primitives/test/vector_log_sink_test.cc, systems/primitives/vector_log_sink.cc, systems/primitives/vector_log_sink.h
Relevant to: #10228
This is step 2 of 4 to deprecate and replace SignalLogger and SignalLog
with a logging system that avoids threading hazards (SignalLogger) and
slow memory management (SignalLog).
VectorLogSink will eventually replace SignalLogger.  The chief
improvement is relocation of log storage from member data in a System(!)
to storage per-context via a scratch cache entry. The direct-to-log
accessors and mutators are removed, but access is clarified and still
convenient via {Get,Find}[Mutable]Log methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15523)
=> primitives: Introduce VectorLogSink

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/iris.cc, geometry/optimization/minkowski_sum.cc, geometry/optimization/minkowski_sum.h, geometry/optimization/test/minkowski_sum_test.cc
Adds the concept of a Minkowski sum of convex sets, which enables geoemtry optimization support for the Capsule geometry in SceneGraph.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15543)
=> [geometry/optimization] MinkowskiSum isa ConvexSet

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc, multibody/plant/test/multibody_plant_hydroelastic_test.cc
This PR provides an option for a discrete system to choose between high-resolution contact surfaces and low-resolution contact surfaces for the hydroelastic contact model. The default is still the high resolution as before.
Replace #15436. 
Final step in the [implementation plan for 14579](https://github.com/RobotLocomotion/drake/issues/14579#issuecomment-843618123) in CY21Q3. This PR is after #15210 (QueryObject).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15487)
=> [multibody] An option for discrete hydroelastics to choose the type of contact surfaces.

bindings/pydrake/solvers/mathematicalprogram_py.cc, solvers/mathematical_program.h
Closes #15579.
The symbolic transpose assertion was being incorrectly skipped, so we must rewrite the check to use `CheckStructualEquality` instead of `operator==`.
The `CheckStructualEquality` doesn't work well with `MatrixBase<Derived>`, so we must rewrite the function to take a Ref, instead. (This is an improvement in any case; we over-use `Derived` in the `MathematicalProgram` API.)
Also of note, with the Eigen 3.4 pre-release, the assertion was actually being compiled down to a `bool`, rather than skipped, leading to a type check error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15580)
=> [solvers] Fix assertion in AddPositiveSemidefiniteConstraint

multibody/plant/multibody_plant.h, multibody/tree/mobilizer_impl.h, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/multibody_tree_system.cc, multibody/tree/planar_mobilizer.cc, multibody/tree/prismatic_mobilizer.cc, multibody/tree/revolute_mobilizer.cc, multibody/tree/screw_mobilizer.cc, multibody/tree/space_xyz_floating_mobilizer.cc, multibody/tree/space_xyz_mobilizer.cc, multibody/tree/test/articulated_body_algorithm_test.cc, multibody/tree/test/model_instance_test.cc, multibody/tree/test/multibody_tree_test.cc, multibody/tree/test/tree_from_mobilizers_test.cc, multibody/tree/universal_mobilizer.cc
This PR cleans up handling of state sub-blocks in MultibodyTree and MultibodyPlant. 
- Localizes building of sub-blocks to four private methods in MBTree that know how to create sub-VectorBlocks from large VectorBlocks without ending up with double indirection.
- Modifies all methods that need sub-blocks to use the new methods.
- Removes any assumption that the velocities are at the tail of the full state, replacing that with only the assumption that they follow the positions. Currently it is not possible to add z variables to MBTree but this avoids a potential landmine if z's are added later.
- Renames MBTree methods for consistency and to make it clear which ones are expensive (those are internal so don't require deprecation).
- Eliminates redundant state access methods in MBTree.
- …
=> Clean up handling of multibody state sub-blocks

bindings/pydrake/BUILD.bazel, bindings/pydrake/__init__.py, bindings/pydrake/autodiffutils_py.cc, bindings/pydrake/common/__init__.py, bindings/pydrake/examples/__init__.py, bindings/pydrake/geometry_py.cc, bindings/pydrake/lcm_py.cc, bindings/pydrake/manipulation/__init__.py, bindings/pydrake/math_py.cc, bindings/pydrake/multibody/__init__.py, bindings/pydrake/perception_py.cc, bindings/pydrake/solvers/__init__.py, bindings/pydrake/symbolic_py.cc, bindings/pydrake/systems/__init__.py, bindings/pydrake/test/all_each_import_test.py, bindings/pydrake/test/minimal_import_test.py, bindings/pydrake/trajectories_py.cc, doc/_pages/python_bindings.md
Wait until a native module is loaded (or a native function is called) before loading our shared libraries. This will make the forthcoming `pydrake.lcmtypes` more convenient to use without forcing a dependency on native code.
Closes #7912.
Towards #15577 towards #1183.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15585)
=> [pydrake] Don't load native code upon 'import pydrake'

bindings/pydrake/test/minimal_import_test.py
The psutil library does not offer memory_maps() on macOS, so we can't easily inspect the list of loaded libraries.
Hotfix for #15585.  Tested locally on macOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15589)
=> [pydrake] Disable memory_maps acceptance test on macOS

examples/manipulation_station/models/061_foam_brick.sdf
Now that the SDF parsing is quieter, I was able to turn my log_level back to the default.  And the only warning I got this time was real:
```
Warning [Utils.cc:128] [/sdf/model[@name="foam_brick"]/link[@name="base_link"]/collision[@name="box_collision"]/material:/opt/drake/lib/../share/drake/examples/manipulation_station/models/061_foam_brick.sdf:L47]: XML Element[material], child of element[collision], not defined in SDF. Copying[material] as children of [collision].
```
This PR removes the unintentional, unused XML element.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15590)
=> [manipulation_station] remove stray XML element from 061_foam_brick.sdf

systems/framework/basic_vector.h
We recently noticed that we've been incorrectly saying that `VectorBlock<VectorX>` prevents resizing of the underlying Vector. Actually, while it does not permit `resize()` to be invoked, a determined user can get access to the underlying object and demolish it as they please. No, I'm not going to tell you how to do that!
This PR just fixes a comment about the above to be accurate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15588)
=> Fix a comment in BasicVector

bindings/pydrake/pydrake_doxygen.h
This reverts commit 90469847 (#15439), and applies a workaround.
Effectively restores #15404
Came up during #15581
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15587)
=> pydrake: Add guidance for ambiguous const-vs-mutable overloads" (#15439)

systems/primitives/test/vector_log_sink_test.cc, systems/primitives/vector_log_sink.cc, systems/primitives/vector_log_sink.h
The APIs (`GetMutableLog()` and `FindMutableLog()`) now require a mutable context to provide mutable access to the stored log (via `Context*` parameter).
This is technically a breaking change. However, it considered harmless because it tweaks an API that was introduced six days ago in #15523. It really hasn't gotten out in the wild yet.
Tests have been updated accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15592)
=> VectorLogSink API for mutable access requires mutable Context

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/test/all_each_import_test.py, bindings/pydrake/visualization/__init__.py, tools/workspace/lcm/example/BUILD.bazel, tools/workspace/lcm/example/README.md, tools/workspace/lcm/example/lcmt_bar.lcm, tools/workspace/lcm/example/lcmt_foo.lcm, tools/workspace/lcm/example/test/cc_lib_test.cc, tools/workspace/lcm/example/test/py_lib_test.py, tools/workspace/lcm/lcm.bzl
Add native code bootstrapping to `pydrake.visualization`; missed in #15585.  (The sub-modules indirectly loaded native code, so this should not have been allow-listed as an expected pure-python module.)
Enhance `lcm.bzl` to understand dots within `lcm_package` names; these need to turn into forward-slashes when used in filenames.  Add direct local acceptance testing for this macro.
Remove stray lcmtypes import from `meshcat_visualizer` (and its `BUILD.bazel` stanza).
Towards #15577 towards #1183.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15591)
=> [pydrake] Various fixes in prep for pydrake.lcmtypes

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/framework/event.h, systems/lcm/lcm_publisher_system.cc, systems/lcm/lcm_publisher_system.h, systems/primitives/vector_log_sink.cc, systems/primitives/vector_log_sink.h
Relevant to: #10228
This is step 3 of 4 to deprecate and replace SignalLogger and SignalLog
with a logging system that avoids threading hazards (SignalLogger) and
slow memory management (SignalLog).
The patch adds bindings for VectorLog, VectorLogSink, and the
LogVectorOutput convenience function, with bindings tests.
Also addressed is a loose end from prior patches: the duplication of the
type name TriggerTypeSet in systems:: and systems::lcm::. The
systems::lcm:: definition is deprecated (likely with no downstream
impact), and aliased to the identical the systems:: definition. The
surviving definition is moved to event.h to prepare for a possible
future refactoring of redundant code using TriggerTypeSet.
--- …
=> primitives: Add python bindings for VectorLogSink and friends

tools/install/dockerhub/focal/Dockerfile
The current drake docker images will not run on deepnote.  Adding these lines fulfills the requirements, as specified here:
https://docs.deepnote.com/environment/custom-environments#custom-image-requirements , and seem a small price to pay for the increased capability.
To reproduce, I have uploaded the revised images to DockerHub as robotlocomotion/drake:pr15586-bionic and robotlocomotion/drake:pr15586-focal.  Visit https://deepnote.com/project/Drake-PR-15586-mPXpOqUZTqe8JBtfj5z4xQ/%2Fnotebook.ipynb .  You will need to create an account to proceed, I'm afraid.  Then
- On the left menu, click on the Environment toolbar, and then look at the "Environment" dropdown.
- I've connected 4 docker images: robotlocomotion/drake:bionic and robotlocomotion/drake:focal and the two revisions.
- Confirm …
=> Add python and pip to Dockerfile to support running notebooks on deepnote.com

common/identifier.h, common/test/identifier_test.cc, systems/framework/diagram.cc, systems/framework/system.cc, systems/framework/system.h, systems/framework/system_base.cc, systems/framework/system_base.h, systems/framework/system_compatibility_doxygen.h, systems/framework/system_output.h, systems/framework/test/system_base_test.cc
As discussed in PR #15489, ValidateCreatedForThisSystem() wasn't lightweight enough for performance-sensitive uses. This PR fixes that by:
- Removing null pointer checks for non-pointer types,
- Performing a single test to reject either system id mismatches or an object with no system id at all.
- Moving the error-message generation out of the method body to permit inlining.
Also:
- ValidateCreatedForThisSystem() moves to SystemBase to be next to its sister method ValidateContext().
- Uses that caused a redundant null pointer check are fixed.
- Adds a new internal use method to Identifier to facilitate the combined invalid-or-mismatch test.
- Updates ValidateContext() description for completeness and consistency with ValidateCreatedForThisSystem().
- Adds some missing unit tests for both …
=> Speed up ValidateCreatedForThisSystem() for inner-loop use

multibody/parsing/test/acrobot_parser_test.cc, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree.h
Profiling revealed that a dynamic_cast used in MBTree for basic continuous state vector access was expensive (about 2% of total forward dynamics time). Fortunately it was also unnecessary.
This PR replaces it with a static_cast and an argument about its safety.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15489)
=> Replace an expensive dynamic_cast with a cheap static_cast

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
This allows the user to specify that particular edges of the graph ought to be active/inactive.
This PR also makes the order of constraints deterministic in `GraphOfConvexSets::Solve()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15572)
=> Add GraphOfConvexSets::LockEdge()

systems/framework/BUILD.bazel, systems/framework/cache.h, systems/framework/context_base.h, systems/framework/dependency_tracker.cc, systems/framework/dependency_tracker.h, systems/framework/framework_common.h, systems/framework/test/dependency_tracker_test.cc, systems/framework/test/thread_sanitizer_test.cc
Previously we used a singleton "dummy" CacheEntryValue as a /dev/null-like destination for throw-away writes. This caused trouble with Tsan in multithreaded PR #15537.
This PR switches to using a per-Context dummy rather than a singleton. This is mildly tricky due to the need to switch dummy destinations during Context cloning.
This is a prerequisite for #15537 to merge hence high priority.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15564)
=> Switch to per-context dummy CacheEntryValue for thread safety

geometry/collision_filter_manager.h, geometry/geometry_state.cc, geometry/proximity/collision_filter.cc, geometry/proximity/collision_filter.h, geometry/proximity/test/collision_filter_test.cc, geometry/proximity/test/collisions_exist_callback_test.cc, geometry/proximity/test/distance_sphere_to_shape_test.cc, geometry/proximity/test/find_collision_candidates_callback_test.cc, geometry/proximity/test/hydroelastic_callback_test.cc, geometry/proximity/test/penetration_as_point_pair_callback_test.cc, geometry/test/proximity_engine_test.cc
The public documentation refers to sets of "invariant" collision filters (e.g., geometries fixed to a common frame are always filtered). Internally, it was referred to as a "permanent" filter. This changes the internal implementation to refer to them as "invariant" filters.
(This also paves the way for adding "transient" modifications to collision filters as that uses the term "persistent". The confusion between "permanent" and "persistent" is much higher than that with "invariant"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15617)
=> [geometry] Correct internal nomenclature for collision filtering

multibody/fixed_fem/dev/deformable_contact_data.h, multibody/fixed_fem/dev/test/deformable_contact_test.cc
The bug is an obvious typo in a getter method, but hard to detect out of
context.
Update the unit test that fails to catch the bug because the index
mapping happen to be self-inverse.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15622)
=> [fem] Fix bug in DeformableRigidContactData

lcm/drake_lcm.cc, lcm/drake_lcm.h, lcm/drake_lcm_interface.h, lcm/drake_lcm_log.cc, lcm/drake_lcm_log.h, lcm/test/drake_lcm_log_test.cc, lcm/test/drake_lcm_test.cc, lcm/test/drake_mock_lcm_test.cc, systems/lcm/lcm_interface_system.cc, systems/lcm/lcm_interface_system.h
* This provides mechanisms that downstream projects have gotten
by directly accessing the native LCM rather than via the interface:
* This captures the use of a `.*` regex on the native lcm, which
was being abused downstream, behind a proper function.
* No support of more general regexps at this time, but the API
change to support that is pretty clear so we can come back to
that in the future.
* Provides a URL-like string for logging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15575)
=> Fix #15569 By adding SubscribeAllChannels and get_lcm_url

multibody/plant/BUILD.bazel, multibody/plant/contact_results_to_lcm.cc, multibody/plant/contact_results_to_lcm.h, multibody/plant/test/contact_results_to_lcm_test.cc
The original implementation of `ContactResultsToLcmSystem` had a public scalar-converting copy constructor and a unit test called "Transmogrify". It clearly had the intention to be transmogrifiable. However, the copy constructor was broken -- an instance constructed via that copy constructor would have empty tables and no ports. It also wasn't properly transmogrifiable in the system scalar conversion sense. Finally, the unit test was insufficient to show these issues and invalid in its spelling.
More generally, the organization of the unit tests were haphazard, rendering extension of those unit tests (in subsequent PRs) largely intractible.
This PR provides the full infrastructure to realize the implied intent of being transmogrifiable.  The unit tests have been completely revisited to …
=> [multibody] Fix error in ContactResultsToLcmSystem

common/BUILD.bazel, common/eigen_stl_types.h, manipulation/schunk_wsg/schunk_buttons.py, multibody/tree/position_kinematics_cache.h, tools/workspace/jsoncpp/BUILD.bazel, tools/workspace/jsoncpp/repository.bzl
* The eigen_stl_types.h header (closes #15578).
* The schunk_buttons.py helper script (closes #15583).
* The `@jsoncpp` external (closes #15623).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15639)
=> Deprecate various unused bits of code

tools/install/libdrake/BUILD.bazel, tools/install/libdrake/drake.cps, tools/workspace/ignition_math/package.BUILD.bazel, tools/workspace/sdformat/package.BUILD.bazel
It was an oddball in terms of being a shared library.  Most all of our other private dependencies are currently being linked statically.  For simplicity, we prefer that the only dependencies linked as shared are either public dependencies (such as spdlog) and/or LGPL'd (such as lcm). 
Partially reverts #7622.
Tested locally that:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15600)
=> [tools] Link ignition-math statically

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/collision_filter_manager.h, geometry/geometry_ids.h, geometry/geometry_set.h, geometry/proximity/collision_filter.cc, geometry/proximity/collision_filter.h, geometry/proximity/test/collision_filter_test.cc, geometry/test/collision_filter_manager_test.cc
This introduces the concept of a history of collision filter modifications and the ability to edit that history.
- Introduce new id type: `FilterId`.
- `CollisionFilterManager` introduces the concept and provides an API for exercising it.
- `CollisionFilter` implements the plumbing.
- Python bindings
resolves #15089
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15492)
=> [geometry] Introduce "transient" collision filter modifications

manipulation/models/ycb/sdf/003_cracker_box.sdf, manipulation/models/ycb/sdf/004_sugar_box.sdf, manipulation/models/ycb/sdf/005_tomato_soup_can.sdf, manipulation/models/ycb/sdf/006_mustard_bottle.sdf, manipulation/models/ycb/sdf/009_gelatin_box.sdf, manipulation/models/ycb/sdf/010_potted_meat_can.sdf
Each of the ycb sdf tags had irrelevant material elements inside collision elements.  The updated sdf parser (correctly) spews sdplog warnings about them, so I have removed them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15648)
=> [manipulation/models] Fix warnings generated by sdf parsing of ycb objects

geometry/drake_visualizer.cc, geometry/scene_graph_inspector.h
- SceneGraphInspector::geometry_version() was in the wrong doxygen subgroup.
- DrakeVisualizer::AddToBuilder() should std::move the parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15649)
=> [geometry] Minor fixups

systems/controllers/BUILD.bazel
Our current version of kcov on bionic has a bug
https://github.com/SimonKagstrom/kcov/issues/339
that generatues spurious failures based on the bitwise contents of
target binaries.  Temporarily deactivate kcov testing of this test to avoid
one such spurious failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15650)
=> Turn off kcov on a test that hit kcov#339

bindings/pydrake/multibody/plant_py.cc, geometry/optimization/iris.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Resolves #13735
Note that `CalcInverseDynamics` still takes a `VectorX<T>`, but changing that trips up a number of LimitAlloc tests, so i've left it alone for now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15561)
=> MBP SetPositions(.), SetVelocities(.) etc. take an Eigen::Ref rather than a VectorX

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
Closes: #11252
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15646)
=> multibody: Properly validate State at public APIs

systems/framework/system_scalar_converter.h, systems/framework/test/system_scalar_converter_test.cc
The prior implementation of this template function contained broken code, but was never compiled so we never noticed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15657)
=> [framework] Fix deprecated AddIfSupported scalar conversion helper

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc, multibody/plant/test/multibody_plant_hydroelastic_test.cc
Retain the old names for now, to avoid immediately disrupting existing users; eventually, we should deprecated the legacy names.
Towards #15565.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15656)
=> [multibody] Add new enumerator names for ContactModel

math/autodiff.h, math/autodiff_gradient.h
Per discussion in issue #15604 this PR deprecates two unused AutoDiff utility functions:
- resizeDerivativesToMatchScalar() from autodiff.h
- gradientMatrixToAutoDiff() from autodiff_gradient.h
There are no other changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15658)
=> Deprecate two unused autodiff utility functions

geometry/BUILD.bazel, geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat_types.h, geometry/shape_specification.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc, tools/workspace/default.bzl, tools/workspace/stduuid/BUILD.bazel, tools/workspace/stduuid/package.BUILD.bazel, tools/workspace/stduuid/repository.bzl
Implements the most essential elements of the Meshcat API:
- Added SceneTree data structure.
- Added stduuid
- Added SetObject from Shape, Rgba
- Supports all shapes that meshcat_visualizer.py supports (more, in fact)
- Does not support texture maps yet.
- Added SetTransform
- Added Delete
- Added SetProperty<double>
- Added HasPath, GetPacked* methods, primarily for testing.
This PR is > 500 lines, but a significant portion of this commit is relatively boilerplate management of the msgpack data structures used to communicate with the javascript client.
Updated the meshcat_manual_test to step the user through the checks.
Updated meschat_test to hammer on the new API.
--- …
=> [geometry] Establish Meshcat in C++ (step 3)

tools/dynamic_analysis/kcov.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15651)
=> kcov support: Add explicit failure for kcov:#339 situations

bindings/pydrake/_math_extra.py, bindings/pydrake/common/deprecation.py, bindings/pydrake/common/test_utilities/numpy_compare.py, bindings/pydrake/test/autodiffutils_test.py, bindings/pydrake/test/symbolic_test.py
Tests both symbolic types and AutoDiffXd
numpy_compare: Add soft_sub_test workaround
deprecation: Catch old-style deprecation elementwise != comparison
Resolves #15549
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15659)
=> py math: Add patch for rich comparison operators; test combinatorics

multibody/parsing/detail_sdf_parser.cc
Follow-up to #15672, per Slack discussion: https://drakedevelopers.slack.com/archives/C0JNB2E3S/p1630161461003200?thread_ts=1630095607.003100&cid=C0JNB2E3S
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15680)
=> detail_sdf_parser: Shift date (error on bad elements) back to 2022-01-01

geometry/BUILD.bazel, geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer.h, geometry/meshcat_visualizer_params.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_visualizer_test.cc
Resolves #13038
Adds MeshcatVisualizer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15670)
=> [geometry] Establish Meshcat in C++ (step 4)

geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/test/hpolyhedron_test.cc
This implements the special case in which the Cartesian product of two HPolyhedra is another HPolyhedron.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15608)
=> Add HPolyhedron::CartesianProduct

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm, multibody/plant/contact_results_to_lcm.cc, multibody/plant/contact_results_to_lcm.h, multibody/plant/test/contact_results_to_lcm_test.cc
tl;dr We *now* include geometry and model instance names with the previously broadcast body names in the hydroelastic contact visualization lcm message.
This fixes *two* bugs in hydroelastic visualization contact:
1. Information provided in LCM was insufficient to distinguish contact between two identically named bodies which belong to different model instances.
- Solution:
- Extend the lcm message to include model instance names.
- `ContactResultsToLcmSystem` populates model instance names the new fields.
2. Multiple independent contacts between the *same* bodies aren't handled correctly.
- Solution:
- Also provide a "name" for the *geometry*.
- Legacy constructor for ContactResultToLcmSystem takes only a MBP instance. As such, it can't resolve collision geometry *names*.
- Constructed …
=> Modify hydro contact vis to provide more information (names)

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/proximity_properties.cc
A number of useful utility functions for setting proximity properties had been omitted from binding. This adds them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15689)
=> [geometry] Binding proximty_properties.h

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/fixed_fem/dev/dynamic_elasticity_model.h, multibody/fixed_fem/dev/test/deformable_box_test.cc, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
This is the final PR to enable deformable body simulation with two-way coupled rigid contacts in `dev/`.
Update implementation for DeformableRigidManager::DoCalcDiscreteValues() to account for deformable bodies that are in contact. In addition, add an integration test that tests the integration of the deformable solver and the contact solver.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15661)
=> Implement DeformableRigidManager::DoCalcDiscreteValues()

setup/mac/binary_distribution/install_prereqs.sh, setup/mac/source_distribution/install_prereqs.sh
There is no great rush to tidy up the setup scripts, and if a user happened to pause their Drake upgrades during the summer, they would be bitten by this, with a difficult recovery.  Push the date out an extra two months to allow for more time for the transition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15700)
=> [setup] Adjust removal date further into the future

bindings/pydrake/systems/meshcat_visualizer.py
The current implementation only rotates the force cylinder by up to pi/2, which leads to wrong contact force directions when the rotation needed is more than pi/2. The fix allows rotation up to pi.
@EricCousineau-TRI could you assign a reviewer for this PR? Thanks! 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15677)
=> Fix bug in meshcat contact force visualization.

bindings/pydrake/systems/test/meshcat_visualizer_test.py
The test case opens 2-3 webbrowser tabs in the user's browser anytime the test case is run. Disable the test case to mitigate this failure mode, until a real fix is in place.
#15702 is the tracking issue to re-enable it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15703)
=> [pydrake] Disable meshcat test_warnings_and_errors

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/systems/sensors_py.cc, bindings/pydrake/systems/test/sensors_test.py, solvers/cost.h, solvers/mathematical_program.h, systems/framework/event_collection.h, systems/framework/system.h, systems/sensors/image.h
(Note that the `RandomSource` is still marked as deprecated 2020-09-01; that will be changed in a different commit.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15701)
=> Remove deprecated code 2021-09

multibody/fixed_fem/dev/test/deformable_box_test.cc
Slightly increase test tolerance to make mac builds happy.
Alternate to #15704.
Closes #15704.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15705)
=> [fem] Hot fix for deformable_box_test

bindings/pydrake/common/test/module_test.py, common/temp_directory.cc, common/temp_directory.h, common/test/temp_directory_test.cc
Modify temp_directory so the caller can always clean up.
For code that creates a temporary working directory, this cleans up the ambiguity of whether or not it is able to delete that directory. Now it can *always* clean up (modulo catastrophic system failures).
Updates the tests that confirm the behavior when `TEST_TMPDIR` is set.
resolves #15696
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15698)
=> [common] Always allow caller clean up directory from temp_directory()

geometry/BUILD.bazel, tools/install/libdrake/build_components_refresh.py
Exclude tools/performance.  The helpers for googlebenchmark should never be part of libdrake, because libdrake does not depend on googlebenchmark.
Unflag meshcat_types as excluded form libdrake.  It was always transitively included anyway, so the extra tags served no purpose.  The only important attribute was "install_hdrs_exclude", which we leave intact.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15709)
=> [tools] Restore build_components_refresh to idempotency

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/tamsi_solver.h, multibody/plant/test/multibody_plant_reaction_forces_test.cc
Closes: #15674
The storage of the TamsiSolver as member data created a thread-race hazard for
context-per-thread usage. Instead, store the solver (via shared_ptr) in a
scratch cache entry. Reorganize transmission of stiction_tolerance to be
maximally lazy, in part to avoid the absence of context access where it used to
be transmitted.
The patch also adds some minimal test coverage for context-per-thread usage in
both discrete and continuous modes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15690)
=> multibody plant: Fix TAMSI threading hazard

WORKSPACE, doc/_pages/developers.md, doc/_release-notes/v0.32.0.md, setup/ubuntu/source_distribution/install_prereqs.sh
https://github.com/bazelbuild/bazel/releases/tag/4.2.1
Set our minimum supported bazel version to `>= 4.0`.  We have not been compatible with the bazel `3.x` series since we upgraded `rules_python` on July 1st (#15289) and `rules_pkg` on August 2nd (#15548).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15711)
=> [setup] Upgrade bazel to latest release 4.2.1

tools/workspace/common_robotics_utilities/package.BUILD.bazel, tools/workspace/common_robotics_utilities/repository.bzl, tools/workspace/voxelized_geometry_tools/repository.bzl
Upgrade common_robotics_utilities to latest commit.
Upgrade voxelized_geometry_tools to latest commit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15716)
=> [workspace] Upgrade CRU and VGT to latest commit

tools/workspace/lcm/repository.bzl
Note that this upgrade contains a fix to mutex locking (https://github.com/lcm-proj/lcm/pull/354), so might warrant additional caution when monitoring for regressions after the upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15717)
=> [workspace] Upgrade lcm to latest commit

tools/workspace/googlebenchmark/repository.bzl
https://github.com/google/benchmark/releases/tag/v1.5.6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15718)
=> [workspace] Upgrade googlebenchmark to latest release 1.5.6

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
Resolves issue #14916 by adding Python binding for new variant of method
MultibodyPlant::CalcJacobianCenterOfMassTranslationalVelocity() which was merged with PR #15387.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15691)
=> Python binding for CalcJacobianCenterOfMassTranslationalVelocity() with model_instances.

examples/scene_graph/simple_contact_surface_vis.cc, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
This gives the `drake_visualizer` plugin the power to consume the new per-body fields in the lcm message: model and geometry names.
Previously, the `_Contact` class was synonymous with per-body-pair contact. That is no longer true. A body pair can have multiple contacts. This led to a refactoring where there is now `_BodyContact` (all of the contacts between a pair of bodies) and `_Contact` (a single contact between body pairs).
The names displayed in the object model for bodies and contact data now depend on a GUI configuration. Default behavior is the legacy behavior (compact, yet possibly ambiguous). Turning it on provides verbose but unambiguous names all the time.
With this change, the visualizer can now handle multiple contacts per body pair and distinguish between two bodies with …
=> [geometry] Enable drake visualizer to consume new hydro lcm fields

math/BUILD.bazel, math/autodiff_gradient.h, math/linear_solve.cc, math/linear_solve.h, math/test/autodiff_test.cc, math/test/linear_solve_test.cc
It is surprising to me that my gradient differs from autodiffing through linear solver. I checked the result from autodiffing through linear solver, and it doesn't satisfy 
```
A*∂x/∂z + ∂A/∂z * x = ∂b/∂z
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15682)
=> Differentiate Ax=b using implicit function theorem.

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py
Some preliminary bindings already exists for `SurfaceMesh`. This beefs them up (bindings on index types and defining the `SurfaceFace`) so that a `SurfaceMesh` can actually be constructed in python.
It completely creates the `VolumeMesh` binding to the same level of support.
Both are tested.
Relates #15738
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15707)
=> Add bindings for VolumeMesh and extend SurfaceMesh bindings

geometry/render/render_camera.h
Provide more guidance and information for selecting clipping planes well. Also corrected a hidden bug that phrases like "e.g." or "i.e." in the first sentence of doxygen messes up our "auto-summary" functionality.
Closes #14487
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15750)
=> [geometry] Update clipping range documentation

geometry/query_object.h
As requested by #14160, the full impact of max_distance is now elaborated. The fact that it also influences the broadphase culling and reduces the space of geometry pairs that get considered.
Closes #14160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15751)
=> [geometry] Elaborate N-squared signed distance query max_distance parameter

BUILD.bazel, tools/install/install_test.py
Closes #15710.
Example use:
```
bazel test //:py/install_test \
--test_output=streamed --nocache_test_results \
--test_arg=InstallTest.test_resource_tool_installed_test
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15758)
=> [install] Add --help and test filtering to install_test

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/BUILD.bazel, geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_test.cc
- Adds an option for taking the port in the Meshcat constructor
- Adds an option for setting the web_url (e.g. to be the web or proxy server address).
- Moves the `throw std::runtime_error` from the websocket thread to the main thread so that one can catch failures to open a requested port.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15727)
=> [geometry:meshcat] Add support for ports and public_urls

geometry/geometry_state.cc, geometry/geometry_state.h, geometry/proximity_engine.h, geometry/scene_graph_inspector.h, geometry/test/geometry_state_test.cc, geometry/test/scene_graph_inspector_test.cc
We've introduced two new methods:
- `has_hydroelastic_representation()`
- `get_hydroelastic_mesh_representation()`
Between the two, anyone will be able to determine if a geometry *has* a hydro representation and, if it is a mesh, get the mesh data.
Relates #15738
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15739)
=> [geometry] SceneGraphInspector can report hydro representation

multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h
This prevents typename hasher from spewing warning messages to the console.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15761)
=> [fem] Wrap around Eigen::SparseMatrix to avoid non-type template parameters

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/proximity/test/volume_to_surface_mesh_test.cc, geometry/proximity/volume_to_surface_mesh.cc, geometry/proximity/volume_to_surface_mesh.h, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
We're putting this in the public API so that visualizers can use this method to map `VolumeMesh` to a `SurfaceMesh` of the mesh boundary. This also includes bindings and tests on those bindings.
As part of this, we move the implementation into the .cc file and explicitly define it on the supported scalar types (with appropriate modification of doxygen to bring it up to current practices).
Relates #15738.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15762)
=> [geometry] ConvertVolumeToSurfaceMesh moves out of internal namespace

examples/scene_graph/simple_contact_surface_vis.cc, lcmtypes/lcmt_hydroelastic_contact_surface_for_viz.lcm, multibody/plant/contact_results_to_lcm.cc, multibody/plant/contact_results_to_lcm.h, multibody/plant/multibody_plant.h, multibody/plant/test/contact_results_to_lcm_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/test/multibody_tree_test.cc, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
The "minimally unique name" is predicated on whether a body has a unique name across *all* model instances. If it does, it can be displayed simply as "body" in visualization. Otherwise, it must be displayed as "model/body".
Furthermore, on a per-contact surface resolution, it determines if displaying geometry names is *necessary* or not. It is necessary if either body in contact has multiple collision geometries.
This extends the lcm message to give the visualizer sufficient information to make the display decision.
- `MultibodyPlant` provides the API to report how many bodies share a name.
- LCM message is extended to include uniqueness data.
- Visualization removes the option to toggle "full names" and just always uses the minimal names.
This has *one* regrettable artifact.
- geometry …
=> [geometry] Hydroelastic contact vis uses "minimally unique names"

multibody/parsing/detail_urdf_parser.cc, multibody/parsing/parser.h, multibody/parsing/test/detail_urdf_parser_test.cc
In a URDF file, we now allow the declaration of a link named "world". We also allow the assignment of geometry to that link (which registers geometry to `MultibodyPlant`'s world body and as "anchored" geometry in `SceneGraph`).
(Opportunistically cleans up a related typo in parser.h.)
Relates #14727 (We're deferring closure until we have decided whether we can do the same thing in SDF.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15763)
=> [parsing] Allow assigning geometries to "world" in URDF

tools/install/libdrake/drake-config.cmake, tools/workspace/ignition_math/ignition-math6-config.cmake, tools/workspace/lcm/lcm-config.cmake, tools/workspace/spdlog/spdlog-config.cmake
On macOS, we need some linker-specific mumbling for dynamic loading to operate correctly.
Hotfix for #15756.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15775)
=> [tools] Fix config.cmake files broken in pycps removal

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat_types.h, geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer.h, geometry/meshcat_visualizer_params.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc, geometry/test/meshcat_visualizer_test.cc, tools/workspace/meshcat/repository.bzl
Adds support for buttons and sliders inside the meshcat browser.  This is also the first instance of a bidirectional communication (the new direction being browser => c++).  I've been using it for class for a week or so, and it's been working well under that stress test.
Note: This contains the commits from #15727 and #15728, which are both ready to merge (I believe).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15768)
=> [geometry:meshcat] Add UI controls to Meshcat

multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
Move `ContactPointData` from nested in DeformableRigidManager to outside
of DeformableRigidManager but internal namespace. This prevents typename
hasher from spewing warning messages to the console as in #15761.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15779)
=> [fem] Un-nest ContactPointData

multibody/fixed_fem/dev/deformable_contact_data.cc, multibody/fixed_fem/dev/deformable_contact_data.h, multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/fem_model_base.h, multibody/fixed_fem/dev/test/deformable_contact_test.cc, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
Set the columns of the contact jacobian corresponding to dofs under Dirichlet boundary conditions to zero.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15693)
=> [fem] Fix bug in deformable contact jacobian

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15785)
=> [pydrake:math] Add bindings for RigidTransform comparison methods

geometry/BUILD.bazel, geometry/geometry_index.h, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/internal_frame.cc, geometry/internal_frame.h, geometry/internal_geometry.h, geometry/proximity/BUILD.bazel, geometry/test/geometry_state_test.cc
`geometry::FrameIndex` is another ancient relic in the `SceneGraph` ecosystem. It should not have been in the `geometry::` namespace. At best, it should have been in `geometry::internal`. However, upon further inspection, it provides very little value. So, we're deprecating the type entirely. Technically, this is a breaking change, but as no public API consumed or returned these indices, simply removing it should not cause difficulties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15778)
=> [geometry] Deprecate geometry::FrameIndex

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/piecewise_pose.cc, common/trajectories/piecewise_pose.h, common/trajectories/test/piecewise_pose_test.cc
- Fix: PiecewisePose was not properly initializing its base class.
- Updates the non-virtual public methods to be style-guide compliant (and deprecates the old names).
- Adds python bindings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15786)
=> [trajectories] Cleanup PiecewisePose and add python bindings

common/autodiffxd.h, math/test/autodiff_test.cc
Previously the `m_value` field in Drake's AutoDiffXd specialization was left intentionally uninitialized. However this has caused difficult to remove maybe-uninitialized warnings from gcc (see #15699 and #15722).
There should be little performance cost to initializing this field, because it is adjacent to a VectorXd field (`m_derivatives`) that requires initialization already (to a null pointer and a zero length). Here are before and after cassie_bench AutoDiff performance numbers (run on my Puget, best of 18 runs, times in μs):
_ |  Mass Matrix | Inverse Dynamics | Forward Dynamics
-----|---------------|---------------------|--------
Uninitialized | 2532 | 3719 | 5267
NaN-initialized |  2543 | 3713 | 5270
Cost | 0.4% | -0.2% | 0.06%
These numbers are the same to within measurement noise. …
=> Initialize the AutoDiffXd value field to NaN

bindings/pydrake/geometry_py.cc, bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/test/geometry_test.py, manipulation/util/show_model.py
Binds the methods `SceneGraphInspector::maybe_get_hydroelastic_mesh().
The meshcat visualizer can now take a additional arguments that will determine if proximity geometries are visualized by the declared primitive or by any available hydroelastic mesh.
It extends the arguments for parsing to include the control and modifies `show_model` to benefit from the new parameters.
To see the effect:
cd drake
bazel build \
//tools:drake_visualizer @meshcat_python//:meshcat-server \
//manipulation/util:show_model
In one terminal
./bazel-bin/external/meshcat_python/meshcat-server
In the other terminal:
./bazel-bin/manipulation/util/show_model --meshcat default \
bindings/pydrake/multibody/test/hydroelastic.sdf \
--meshcat_role proximity
Now you will see a smooth, yellow sphere (the idealized sphere …
=> [geometry] Enable hydro geometry vis in python, implement for python meshcat

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/piecewise_pose.cc, common/trajectories/piecewise_pose.h, common/trajectories/test/piecewise_pose_test.cc
Helper method when the goal is to have a first-order position trajectory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15803)
=> [trajectories] Add PiecewisePose::MakeLinear

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/ibex_py.cc, bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/ibex_solver_test.py, solvers/solver_type.h, solvers/solver_type_converter.cc, solvers/test/solver_type_converter_test.cc
Adds bindings for IbexSolver as well as some other changes to make it a more fleshed out SolverInterface.  Ibex still doesn't set solver details in MathematicalProgramResult.
Toward #15573 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15793)
=> pydrake solvers: Add bindings for IbexSolver

manipulation/util/show_model.py
When given a directory with a package.xml file to load, read only that one file; do not crawl through all of its subfolders recursively trying to find other xml files lying around to read in.
Going back through git history and code reviews, this seems to have always been the design intent, but somehow was botched from the get-go in #10156.
Crawling through all folders leads to problems when loading `runfiles/anzu/package.xml` also tries to load `runfiles/anzu/external/drake/package.xml` and its friends.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15801)
=> [manipulation] In show_model only read the top-level package_path

bindings/pydrake/_autodiffutils_extra.py, bindings/pydrake/autodiffutils_py.cc, bindings/pydrake/test/autodiffutils_test.py, common/autodiff_overloads.h, math/autodiff.h, math/autodiff_gradient.h, math/gradient.h, math/test/autodiff_test.cc
In preparation to deprecate the old non-compliant functions in math/autodiff.h and math/autodiff_gradient.h this PR introduces GSG-compliant signatures. Also updates the comments and code in the headers to bring them up to current Drake standards.
For reviewability, this is split out from draft PR #15615 which also modifies the hundreds of call sites. Refer to that PR to see what the call sites look like; this one retains the original call sites. 
Addresses part of #15604. The remaining steps (in separate PRs) are:
- update the call sites in Drake to use the new signatures (the remainder of #15615).
- update the call sites in Anzu
- uncomment the "TODO DEPRECATE" lines here for the old signatures
- (three months later) remove the deprecated methods (C++ & python)
--- …
=> Provide GSG-compatible signatures for autodiff utilities

common/extract_double.h, geometry/geometry_properties.h
In the case of ExtractDouble, it was flagged on 2021-07-29 and announced in v0.33.0 release notes, so should have said 2021-11-01 from the get-go.
In the case of Rgba, the call to deprecate is still disarmed in a comment, so should be at least T+3 months from now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15809)
=> Adjust deprecation dates that still cite last year (2020)

examples/acrobot/acrobot_plant.h
There is already a pydrake unit test for this, it's just that pybind11 always discards "const" qualifiers so we never noticed.
Closes #15810.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15812)
=> [acrobot] Remove spurious const

multibody/plant/dev/multibody_plant_config.h, multibody/plant/dev/multibody_plant_config_functions.cc, multibody/plant/dev/multibody_plant_config_functions.h, multibody/plant/dev/test/multibody_plant_config_functions_test.cc
Towards #15565.
Update the namespace to be Drake (not Anzu).
Improve documentation cross-references.
Pass string_view by-value not by-reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15805)
=> [multibody/plant] Tidy up MultibodyPlantConfig

examples/atlas/atlas_run_dynamics.cc
The error happens at time ~0.5s, which is not caught by CI.  We can't run the full-length test in CI, because in Debug builds it takes well over two minutes.
Relates to #15782.
Task failed successfully:
https://user-images.githubusercontent.com/17596505/134714161-d9bdb9bc-6f4d-4c1e-a4d2-312c7c732e2c.mp4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15814)
=> [atlas] Use a smaller time step to avoid discrete solver errors

.clang-format, bindings/pydrake/.clang-format, tools/install/libdrake/BUILD.bazel, tools/install/libdrake/test/header_dependency_test.py
Relates to #7451.  Needs #15817 to merge first.
This guards against #15535 regressing and re-introducing a header dependency on `libxml2` or `sdformat`.
This would have diagnosed the include path errors in `linear_solve.h` that were fixed #15790 but still crept into the v0.34.0 release.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15816)
=> [libdrake] Add regression test for allowed header file dependencies

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc, geometry/BUILD.bazel, geometry/drake_visualizer.cc, geometry/drake_visualizer_params.h, geometry/rgba.h, geometry/test/drake_visualizer_test.cc, geometry/test/rgba_test.cc, tools/workspace/drake_visualizer/draw_lcm_mesh.patch, tools/workspace/drake_visualizer/repository.bzl
Visualizing hydro with DrakeVisualizer
This streams the meshes for hydro geometries via a previously unused lcm mechanism. That mechanism requires a patch to `drakevisualizer.py` (it hasn't been kept up to date w.r.t. python versions).
We also expand `rolling_sphere_run_dynamics` to include a flag to exercise
this new functionality.
To see the visualization at work, run:
```
bazel run //examples/multibody/rolling_sphere:rolling_sphere_run_dynamics \
-- --vis_hydro
```
relates #15738
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15772)
=> [geometry] Visualizing hydro with DrakeVisualizer

geometry/BUILD.bazel
//geometry:meshcat_visualizer_test was failing asan+mac due to a timeout.
This PR adds no_asan to that test as a workaround.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15829)
=> Work around #15828 by turning off asan on affected test

lcmtypes/lcmt_panda_command.lcm
Allow (and require) more clarity around which fields are required vs ignored.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15784)
=> [lcmtypes] Update lcmt_panda_command

common/test/value_test.cc
Relevant to: #15802
Prior versions of apple clang leaked an inline namespace token into
names; version 13 no longer needs it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15839)
=> Narrow Apple clang fixup by version

geometry/render/test/render_engine_vtk_test.cc
Relevant to: #15802
With -O2 optimization, the apple clang 13 optimizer damages the
unrelated variable expected_outlier_label_. Use conditional compilation
and compiler attributes to disable optimization at one location.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15840)
=> Work around Apple clang 13 optimizer

geometry/BUILD.bazel, geometry/meshcat.cc
Resolves #15828
The regex that I was doing on the obj file contents was tragically
slow, especially on mac debug builds.  I have replaced it with a find,
then a more narrow regex.
Before this PR, running
```
bazel run --config=apple_debug //geometry:meshcat_visualizer_test
```
would execute in ~195 seconds.  After this PR, it executes in ~4 seconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15842)
=> [geometry:meshcat] fix #15828

tools/workspace/liblzma/repository.bzl
The [license](https://git.tukaani.org/?p=xz.git;a=blob;f=COPYING) of liblzma (which is part of [the xz project](https://tukaani.org/xz/)) is actually Public Domain. (The tools, which we aren't using, are [L]GPL. The build system, which we also don't use, as we expect the library to already be present, are GPL.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15844)
=> Fix "liblzma" (i.e. xz) license

bindings/pydrake/autodiffutils_py.cc
PR #15699 renamed both initializeAutoDiff() and initializeAutoDiffGivenGradientMatrix() to overloads of InitializeAutoDiff(). One of the new signatures was incorrect and caused an overload ambiguity in Python.
This PR:
- fixes the erroneous signature to match C++ properly
- moves the gradient signature to be adjacent to the other overload to make it easier to see what's what
- corrects the gradient signature's first argument type (was VectorXd rather than MatrixXd).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15831)
=> Fix Python InitializeAutoDiff() signature

doc/_pages/bazel.md
It took a few minutes for me to rediscover this (and it is an updated
syntax from the old instruments).  I think this will likely be useful
for others, as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15843)
=> [sphinx] Add instructions for profiling on mac.

bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py
Creating a pydrake-only Identifier<> makes life difficult as we want to improve how identifiers are bound.  We can use an existing type without any loss of test specificity.
Pre-requisite for #15846.  See #15857 for the full branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15856)
=> [pydrake] Remove FakeId from geometry_test

common/identifier.h, geometry/BUILD.bazel, geometry/geometry_frame.cc, geometry/geometry_frame.h, geometry/render/gl_renderer/shader_program.cc, geometry/render/gl_renderer/shader_program.h
This avoids baiting the ODR demons.  It's best for mutable global storage to only ever be emitted into one object file.
Towards #15845 and #15846 (this is only half of the answer).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15854)
=> [geometry] Never call get_new_id from a header

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, examples/allegro_hand/joint_control/allegro_single_object_simulation.cc, examples/atlas/atlas_run_dynamics.cc, examples/manipulation_station/proof_of_life.cc, examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc, examples/multibody/inclined_plane_with_body/inclined_plane_with_body.cc, examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc, examples/multibody/strandbeest/run_with_motor.cc, examples/planar_gripper/planar_gripper_simulation.cc, examples/simple_gripper/simple_gripper.cc, multibody/plant/contact_results_to_lcm.h, multibody/plant/test/contact_results_to_lcm_test.cc, multibody/plant/test/multibody_plant_hydroelastic_test.cc, multibody/plant/test/multibody_plant_reaction_forces_test.cc
Otherwise, we spew console warnings about non-unique contact names.
For that same reason, document that the overload without a scene_graph is dis-preferred.
Also incorporates ancillary changes for improved uniformity in examples.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15849)
=> [examples] Always connect a SceneGraph for contact visualization

bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/planar_scenegraph_visualizer.py, bindings/pydrake/systems/pyplot_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py, examples/scene_graph/simple_contact_surface_vis.cc, geometry/drake_visualizer_params.h, geometry/meshcat_visualizer_params.h, geometry/test/drake_visualizer_test.cc, multibody/fixed_fem/dev/run_scripted_deformable_motion.cc, multibody/fixed_fem/dev/run_simple_gripper.cc, multibody/fixed_fem/dev/test/deformable_box_test.cc, multibody/plant/contact_results_to_lcm.cc, multibody/plant/contact_results_to_lcm.h, multibody/plant/test/contact_results_to_lcm_test.cc
Using a period that does not have an exact representation in binary floating point (e.g., our current defaults of 1/30 or 1/60) can lead to undesirably small timesteps due to the dithering of update rates.
Relates to #15021.  That issue is about fixing this kind of problem systemically; here, we just aim the shotgun slightly off to the side of our foot, in the meanwhile.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15850)
=> [geometry] Visualize at 32 Hz or 64 Hz by default

bindings/pydrake/systems/framework_py_systems.cc, systems/framework/system_scalar_converter.cc, systems/framework/system_scalar_converter.h
Upgrade some ASSERT to DEMAND; the codepaths are not inner-loop.
Add missing docstring for IsConvertible.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15863)
=> [framework] Demote deprecated SystemScalarConverter::Add to internal

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
This resolves a TODO related to software upkeep, from #15826.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15861)
=> [multibody] Add internal cross-check for default contact model

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py.cc, bindings/pydrake/test/geometry_test.py, geometry/BUILD.bazel, geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat_types.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc
Includes a refactoring of the GeometryData msgpack type, because
adding yet another geometry type was becoming unwieldy.
Implements the TODO making many MaterialData fields optional, because
the point clouds needed to not have spurious mesh material properties
in their message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15851)
=> [geometry:meshcat] Adds visualization for Point Clouds

bindings/pydrake/common/deprecation.py, bindings/pydrake/common/test/deprecation_example/__init__.py, bindings/pydrake/common/test/deprecation_test.py
Add example
Motivated by #15875
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15877)
=> py deprecation: Expose `deprecated_callable` as decorator

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/iris.cc, geometry/optimization/iris.h, geometry/optimization/test/iris_test.cc
- Adds enable_ibex option to IrisOptions
- Refactors nonlinear programming code path to use MultibodyPlant
double instead of autodiff.
- Adds Ibex as an additional check to certify the cspace iris regions
- Adds a test for which snopt misses some counter-examples and Ibex succeeds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15789)
=> [geometry/optimization] IrisInConfigurationSpace with Ibex

common/BUILD.bazel, tools/install/libdrake/BUILD.bazel
Partially addresses #15946
Relates: #15963
The original patch suggested by @jwnimmer-tri
https://github.com/RobotLocomotion/drake/blob/610ec7f88ab8f09507d2cd382c48cb15393d9467/tools/workspace/spdlog/package.BUILD.bazel#L66-L70
Relies on
https://github.com/RobotLocomotion/drake/blob/610ec7f88ab8f09507d2cd382c48cb15393d9467/tools/workspace/spdlog/package.BUILD.bazel#L14-L18
(`config_setting(name = "linux", ...)`) being declared.  Currently this patch utilizes a selection based off of `//tools/cc_toolchain:linux`, I'm not sure if a new `config` entry should be declared or if the current selection here is valid.  I have a small SONAME verification script, prior to this change:
```
Drake specific libraries missing SONAME:
- /tmp/drake-master/lib/libdrake_ibex.so
- …
```
=> fix missing SONAME fields for libdrake.so and libdrake_marker.so

systems/controllers/BUILD.bazel, systems/controllers/setpoint.cc, systems/controllers/setpoint.h
Towards #9865.
This code is unused within Drake and Anzu, and is stale with respect to modern practices:
- RigidTransform vs Isometry3;
- SpatialAcceleration vs Vector6, etc.;
- Templates, scalar types, and inline code.
Because it's unused, we elect to remove it rather than update it.  Any projects that were using this class are welcome to copy its source files into their own codebase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16006)
=> [controllers] Deprecate CartesianSetpoint and VectorSetpoint

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py
Towards #9865.
(These were already deprecated, but lacked cutoff dates, a useful message, and any test coverage at all.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16008)
=> [pydrake] Deprecate Isometry3 in the multibody API

math/discrete_algebraic_riccati_equation.h
```
math/discrete_algebraic_riccati_equation.h:60: warning: unexpected command endverbatim
math/discrete_algebraic_riccati_equation.h:68: warning: unexpected command endverbatim
```
The `///` strings within the verbatim block confuse Doxygen.
The first function doesn't use verbatim tags, but it was changed to
maintain consistency within the same file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16010)
=> [math] Fix DARE Doxygen warnings

bindings/pydrake/solvers/mosek_py.cc, solvers/mosek_solver.cc, solvers/mosek_solver.h, solvers/test/mosek_solver_test.cc
Note that this deprecated function is also referred to by our tutorials, but that is fixed separately in #16019.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16020)
=> Remove deprecated 2021-11 solvers

tutorials/debug_mathematical_program.ipynb
The existing instructions were mostly using deprecated / dis-preferred spellings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16019)
=> [tutorials] Rewrite instructions for solver verbosity

geometry/optimization/BUILD.bazel
This patch aims to avoid test timeouts in asan and memcheck configurations.
Hotfix for #15789.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16024)
=> iris_test: Run in 4 shards

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
Replaces unordered_map and unordered_set with containers that will
provide consistent ordering.
Also
- Adds Vertices() and EdgeIds() access methods.
- Add some missing python bindings.
API breaking change: the return values of VertexIds and Edges are now
std::vector instead of std::unordered_set. This change was made
without deprecation, per the "Experimental API" warning in the
GraphOfConvexSets class documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16016)
=> [geometry:optimization] cleanup memory management in GraphOfConvexSets

multibody/optimization/BUILD.bazel, multibody/optimization/test/toppra_test.cc, multibody/optimization/toppra.cc, multibody/optimization/toppra.h
Constructs the solver to be used for all the optimizations performed and explicitly prefer Clp over Mosek as the solver for Toppra.  Also fixes a bug where input trajectories that had segments with zero velocity caused Toppra to crash.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15964)
=> Toppra: Use one solver for every optimization and fix zero velocity bug

tools/install/bazel/test/drake_bazel_installed_test.py, tools/workspace/buildifier/repository.bzl, tools/workspace/common_robotics_utilities/BUILD.bazel, tools/workspace/common_robotics_utilities/package.BUILD.bazel, tools/workspace/common_robotics_utilities/repository.bzl, tools/workspace/ghc_filesystem/repository.bzl, tools/workspace/ignition_math/repository.bzl, tools/workspace/pycodestyle/repository.bzl, tools/workspace/rules_python/repository.bzl, tools/workspace/tinyobjloader/repository.bzl, tools/workspace/uritemplate_py/package.BUILD.bazel, tools/workspace/uritemplate_py/repository.bzl, tools/workspace/uwebsockets/repository.bzl
Prepared per the new documentation in #16005.
The `task_planning_test_no_equals` is removed in order to track the relevant upstream change that also removed that test case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16004)
=> Upgrade externals to latest

bindings/pydrake/systems/lcm_py_bind_cpp_serializers.cc, bindings/pydrake/systems/lcm_py_bind_cpp_serializers.h, bindings/pydrake/systems/test/lcm_test.py, lcmtypes/BUILD.bazel
Closes #16022.
See [slack thread for consensus of binding all types](https://app.slack.com/client/T0JNB2DS4/C3YB3EV5W/thread/C3YB3EV5W-1635778071.011600).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16026)
=> [pydrake] Bind all C++ message type serializers

examples/acrobot/acrobot_io.py, examples/acrobot/optimizer_demo.py, examples/acrobot/spong_sim.cc, examples/acrobot/spong_sim.py, examples/acrobot/test/acrobot_io_test.py, examples/acrobot/test/example_scenario.yaml, examples/acrobot/test/example_stochastic_scenario.yaml
Preparation for #15902 towards #15868.  With the new sugar functions, there is no longer any affordance for parsing a YAML file halfway, guessing a scenario_name to use, and then finishing the de-serialization.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15998)
=> [acrobot] Remove optional scenario_name

manipulation/perception/BUILD.bazel, manipulation/perception/optitrack_pose_extractor.h, systems/sensors/BUILD.bazel, systems/sensors/optitrack_receiver.cc, systems/sensors/optitrack_receiver.h, systems/sensors/test/optitrack_receiver_test.cc
Towards #9865.
The new OptitrackReceiver is based on the now-deprecated OptitrackPoseExtractor.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16011)
=> [sensors] Add OptitrackReceiver, deprecate OptitrackPoseExtractor

examples/manipulation_station/differential_ik.py, examples/rod2d/rod2d.cc, examples/rod2d/test/rod2d_test.cc, manipulation/planner/differential_inverse_kinematics_integrator.cc, systems/analysis/simulator.cc, systems/controllers/inverse_dynamics.cc, systems/controllers/test/linear_model_predictive_controller_test.cc, systems/controllers/test/linear_quadratic_regulator_test.cc, systems/estimators/test/kalman_filter_test.cc, systems/framework/test/system_constraint_test.cc, systems/framework/test/vector_system_test.cc, systems/optimization/test/system_constraint_adapter_test.cc, systems/primitives/test/affine_system_test.cc, systems/trajectory_optimization/direct_collocation.cc, systems/trajectory_optimization/direct_transcription.cc
This is a minor cleanup PR to reduce ugliness at State-setting call sites by using the existing `context.SetContinuousState()` and `SetDiscreteState()` methods rather than `get_mutable_blah_blah_blah().get_mutable_vector().SetFromVector()` and the like.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16036)
=> Clean up state value setting call sites

doc/_pages/code_review_checklist.md, doc/_pages/from_source.md, doc/_pages/getting_help.md, doc/_pages/installation.md, doc/_pages/jenkins.md
Towards #16001.
Before we spin up macOS Monterey support, we need to retire the older Catalina support.  Our general policy for both macOS and Ubuntu is that we support the two most recent stable releases.
At the moment we are still running CI for Catalina, but will be turning that off soon, etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16041)
=> [doc] Withdraw support for macOS Catalina

examples/bead_on_a_wire/bead_on_a_wire.cc, examples/rod2d/rod2d.cc, systems/framework/system.cc, systems/framework/system.h, systems/framework/system_base.h, systems/framework/test/system_test.cc
Per discussion in #16031 this formerly "to be deprecated" method needs to go peacefully to its grave prior to other planned API changes.
Note that there remain several to-be-deprecated input port methods in SystemBase and System. I purged them of references to `EvalEigenVectorInput()` and added some mention of the now-preferred `InputPort::Eval()` method family but I'm not attempting true deprecation of them here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16042)
=> Deprecate System::EvalEigenVectorInput()

tools/install/libdrake/drake-config.cmake
Fixes #15004.
I could not follow the conversation about turning on or off the "toggle" for spdlog.  Currently, that CMake file assumes that `spdlog` is a hard dependency -- `find_dependency` more or less the same thing as `find_package(... REQUIRED)`.
To make spdlog optional
1. Please tell me how to actually do that with bazel :upside_down_face:
2. We'll need to `configure_file` on the `drake-config.cmake` to optionally `find_dependency` on `spdlog` and conditionally add that interface compile definition.
Sample consumer code to validate:
```cmake
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(drake-spdlog-checking)
set(CMAKE_PREFIX_PATH "/tmp/drake-install-testing/lib/cmake")
find_package(drake CONFIG REQUIRED)  # transitively brings in spdlog
add_executable(loggy main.cpp) …
```
=> include HAVE_SPDLOG compile definition for cmake consumers

bindings/pydrake/perception_py.cc, bindings/pydrake/test/perception_test.py
Inspired by a [StackOverflow question](https://stackoverflow.com/questions/69797712/pointcloud-visualization-in-drake-visualizer-in-python/69798666).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16048)
=> [pydrake] Bind DepthImageToPointCloud.camera_pose_input_port

doc/_pages/release_playbook.md
Changed in https://github.com/RobotLocomotion/drake-ci/pull/126 and in effect as of last night.  The uploaded URL pattern stays the same, so the "download_release_candidate" script does not need to change.
Towards #16001.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16053)
=> [doc] macOS releases use Big Sur now

geometry/meshcat_animation.h, geometry/test/meshcat_manual_test.cc, tools/workspace/meshcat/repository.bzl
@rdeits has fixed https://github.com/rdeits/meshcat/issues/105.
This PR bumps the meshcat sha and removes the TODO in the test
that was blocked by this issue.  Hoorah!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16062)
=> [meshcat] Upgrade meshcat to fix animation "interference" issue

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_values.cc, bindings/pydrake/systems/test/general_test.py, bindings/pydrake/systems/test/value_test.py, examples/allegro_hand/test/allegro_lcm_test.cc, examples/bead_on_a_wire/test/bead_on_a_wire_test.cc, examples/kuka_iiwa_arm/kuka_torque_controller.cc, examples/kuka_iiwa_arm/test/kuka_torque_controller_test.cc, examples/manipulation_station/test/manipulation_station_test.cc, examples/mass_spring_cloth/cloth_spring_model.cc, examples/pendulum/lqr_simulation.cc, examples/pendulum/trajectory_optimization_simulation.cc, examples/planar_gripper/planar_gripper_lcm.cc, examples/planar_gripper/planar_gripper_simulation.cc, examples/planar_gripper/planar_manipuland_lcm.cc, examples/quadrotor/quadrotor_plant.cc, examples/rod2d/rod2d.cc, examples/rod2d/test/rod2d_test.cc, examples/scene_graph/solar_system.cc, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree_system.cc, systems/controllers/pid_controller.cc, systems/framework/basic_vector.h, systems/framework/discrete_values.h, systems/framework/test/basic_vector_test.cc, systems/framework/test/discrete_values_test.cc, systems/primitives/discrete_time_delay.cc, systems/sensors/rotary_encoders.cc
As discussed in #16031, this PR adds `value() -> const VectorX<T>&` methods to BasicVector and DiscreteValues, moving `get_value() -> VectorBlock<const VectorX<T>>` methods to "to be deprecated".
Some call sites are updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16051)
=> Add VectorX-returning value methods to BasicVector and DiscreteValues

examples/kuka_iiwa_arm/BUILD.bazel, examples/kuka_iiwa_arm/kuka_plan_runner.cc, examples/kuka_iiwa_arm/kuka_simulation.cc, examples/kuka_iiwa_arm/test/kuka_simulation_installed_test.py
These are not even public to Bazel users or other programs within Drake.  They definitely should not be published for use by binary release users.  Relates #4224.
Note that the deprecation fuse on this one is only two release tags (instead of three+ like usual), because I'd like to get it out of the way in time for release pipeline improvements due in January, and because it seems unlikely to severely disrupt any users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16061)
=> [kuka_iiwa_arm] Deprecate installed use of kuka sim and plan runner

common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_doxygen.h, common/yaml/yaml_read_archive.h, common/yaml/yaml_write_archive.h
Refer to Anzu PR 8004 for the motivating use case.
Usually we require that we have a serializable struct that matches the YAML document.  However, for the special case of a C++ collection type that matches a YAML node type exactly, sometimes it's convenient to parse the document directly into that collection, without the need to define an enclosing struct.
This PR adds `std::map<std::string, Serializable>` along those lines.  In the future we _could_ imagine adding `std::vector<Serializable>` as well just for completeness, though I no examples of needing that come to mind.  Those are the only two collection types that we'd want to allow in this kind of special case.  (They are the only ones that directly align with YAML node semantics.)
--- …
=> [yaml] Allow serializing a top-level map with no enclosing struct

bindings/pydrake/geometry_py_visualizers.cc, bindings/pydrake/test/geometry_visualizers_test.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc
Provides the API necessary to push line geometry to meshcat.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16063)
=> [meshcat] Add Meshcat::SetLine and Meshcat::SetLineSegments

multibody/plant/multibody_plant.h
- Instead of using AddContactMaterial(), use
AddSoftHydroelasticProperties() or
AddSoftHydroelasticPropertiesForHalfSpace()
I think the merged PR #16009 forgot to update this small document in MultibodyPlant.
Relates #15796.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16046)
=> [multibody] Minor document how to set hydroelastic modulus.

examples/bead_on_a_wire/bead_on_a_wire.cc, examples/compass_gait/compass_gait_geometry.cc, examples/mass_spring_cloth/cloth_spring_model.cc, examples/rimless_wheel/rimless_wheel_geometry.cc, examples/rod2d/rod2d.cc, systems/controllers/inverse_dynamics.cc, systems/controllers/linear_model_predictive_controller.cc, systems/controllers/pid_controller.cc, systems/estimators/luenberger_observer.cc, systems/framework/input_port.h, systems/framework/output_port.h, systems/framework/system.cc, systems/framework/system_symbolic_inspector.h, systems/framework/vector_system.h, systems/lcm/lcm_scope_system.cc, systems/primitives/linear_transform_density.cc, systems/primitives/sine.cc, systems/primitives/vector_log.h, systems/sensors/rotary_encoders.cc, systems/sensors/rotary_encoders.h
Change `port.Eval()` methods and several other public methods to return `const VectorX<T>&` rather than `VectorBlock<const VectorX<T>>`.
This is a precursor to API cleanup work for #11346 and #15986. For motivation see Slack discussion beginning [here](https://drakedevelopers.slack.com/archives/C2CHRT98E/p1635787391010100).
Here are the changed public methods. Each previously returned `VectorBlock<const VectorX<T>>` and now returns `const VectorX<T>&`.
- InputPort::Eval() with no template argument
- OutputPort::Eval() with no template argument
- SystemSymbolicInspector:: input() output() continuous_state() discrete_state() numeric_parameters() discrete_update()
- VectorSystem:: EvalVectorInput() GetVectorState() 
- RotaryEncoders::get_calibration_offsets()
Notes:
- This is a **breaking …
=> Return const VectorX& rather than VectorBlock where possible

tools/install/bazel/README.md, tools/install/bazel/generate_installed_files_manifest.bzl
This improves compatibility with 'apt install drake-dev', towards https://github.com/RobotLocomotion/drake-external-examples/issues/209.  In any case, the licenses should not be part of runfiles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16070)
=> [install] Remove LICENSE files from drake-bazel-installed runfiles

bindings/pydrake/autodiff_types_pybind.h
I'll bet #15792 was sufficient.
Closes #11566.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16074)
=> [pydrake] Remove GCC warning suppressions

tools/workspace/snopt/repository.bzl
Modify snopt build logic to enable building on the "manylinux" platform.
Towards #15961.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16076)
=> Fix building with snopt on "manylinux"

common/autodiffxd.h
Closes #14051.
This is mostly to answer complaints about inconsistencies with similar
functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16075)
=> autodiffxd atan(): Use abs2()

bindings/pydrake/geometry_py_visualizers.cc, bindings/pydrake/test/geometry_visualizers_test.py, geometry/BUILD.bazel, geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat_types.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc
Adds support for sending triangle meshes directly to Meshcat
(e.g. without having to write them to an .obj file on disk).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16077)
=> [meshcat] Add `SetObject(TriangleSurfaceMesh)` and `SetTriangleMesh(...)`

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/lifetime_test_notebook.ipynb
In a Jupyter notebook, if a helper function creates a local context and then returns a value computed by an abstract-valued output port evaluated against that context, and if the return value is a C++ class type that is bound in pydrake, and if the function does not retain or return the context itself such that the context is garbage collected, then the storage that backs the return value would be erroneously deleted at the conclusion of the cell, thus leaving the return value pointing at garbage memory.
This commit adds a reference_internal annotation on the value into the context, so that the context will not be destroyed in this case.
There does not seem to be any way to trigger these conditions outside of a Jupyter notebook, so the regression test here takes the form of an ipynb file. …
=> [pydrake] Port values borrowed from a Context keep the Context alive

tools/install/bazel/drake.BUILD.bazel, tools/install/bazel/repo_template.bzl, tools/install/bazel/test/drake_bazel_installed_test.py
Remove deprecated py_repositories() from unit test.
Closes #12749.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16072)
=> [install] Add :drake_shared_library to drake-bazel-installed

tools/install/bazel/repo_template.bzl, tools/install/bazel/test/drake_bazel_installed_test.py
Hotfix for #16072, but disabling a recently-added test on macOS only.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16101)
=> [install] Mark :drake_shared_library as Ubuntu-only

math/test/linear_solve_test.cc
As explained in https://gitlab.com/libeigen/eigen/-/issues/2313. Eigen actually computed the right result when differentiating its solver Ax = b.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16045)
=> Compare LinearSolve result x with Eigen

bindings/pydrake/pydrake_doxygen.h
Follow-up from #15410
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15429)
=> pydrake: Add guidance that types should be bound before use in functions

tools/workspace/ibex/package.BUILD.bazel
When running as root, we should keep the workspace files owned by root.
Towards #16107.  (No closing yet, because we might want to add CI testing for this.)
See also [#build slack discussion](https://app.slack.com/client/T0JNB2DS4/C0KDGF4V9/thread/C0KDGF4V9-1637077937.035000) for evidence of local testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16108)
=> [ibex] Use --no-same-owner when untarring

multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/test/compliant_contact_manager_test.cc
Thus far this implements discrete pairs and contact Jacobian compuation.
The reason we don't use the ones currently in MultibodyPlant are:
1. This manager sets up a problem based on a linear model of dissipation instead of the currently used Hunt & Crossley model.
2. The new method to compute the Jacobian avoids unnecessary copies (about 30% faster) and cleans up sign conventions.
3. The long term solution in terms of mangers removes all contact related computation from MultibodyPlant, leading to a more modular design.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16047)
=> Implements contact manager to be used with new solvers

bindings/pydrake/geometry_py_hydro.cc, bindings/pydrake/test/geometry_hydro_test.py, geometry/proximity/test/triangle_surface_mesh_test.cc, geometry/proximity/triangle_surface_mesh.h
Tweaks the triangle surface mesh so that it will be forward compatible with the polygon surface mesh (and incidentally cleans up a formatting issue).
1. `SurfaceTriangle` can report number of vertices (hard-coded to 3).
2. Can report the centroid of each triangle.
3. The return type for `CalcBarycentric` is properly expressed as the declared barycentric type. This is a cosmetic change here to help it match `PolygonSurfaceMesh`.
relates #15796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16112)
=> [hydro] Patch triangle surface mesh

systems/framework/system_compatibility_doxygen.h
Vaguely relevant to: #12570
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16118)
=> framework: Fix a typo in system_compatibility doc

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/systems/BUILD.bazel, tools/skylark/pybind.bzl
Discussed in [drakedevelopers#python](https://app.slack.com/client/T0JNB2DS4/CAHNDSJUB/thread/C3YB3EV5W-1637277861.042200).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16129)
=> [tools] Attempt to fail-fast when violating ODR in pydrake

geometry/proximity/BUILD.bazel, geometry/proximity/polygon_surface_mesh.cc, geometry/proximity/polygon_surface_mesh.h, geometry/proximity/test/polygon_surface_mesh_test.cc
Like the `TriangleSurfaceMesh`, it represents a discrete 2D surface. Unlike it, the discrete elements can be polygons with 3 or more sides. It is designed to be basically compatible with `TriangleSurfaceMesh`.
It currently lacks the ability to iterate through faces and vertices via *range* iteration. A TODO calls that missing feature out.
Co-authored-by: Joe Masterjohn `<joe.masterjohn@tri.global>`
relates #15796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16111)
=> [hydro] Adds the PolygonSurfaceMesh

tools/release_engineering/relnotes.py, tools/workspace/github3_py/repository.bzl, tools/workspace/new_release.py
Upgrade github3_py to latest release.
Closes #16066.
I've tested both tools locally (on 20.04).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16133)
=> [tools] Declare 20.04 support for release engineering tools

multibody/contact_solvers/BUILD.bazel
Otherwise, these two CI jobs failed.
linux-bionic-clang-bazel-continuous-address-sanitizer
linux-bionic-clang-bazel-continuous-everything-address-sanitizer
Without this change, "bazel test --config=asan //multibody/..." failed on bionic with clang.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16136)
=> [multibody] Disable asan for supernodal_solver_test.

doc/_pages/from_source.md, doc/_pages/installation.md
The most recent Drake release deemed this support "experimental".
Now that we have Jenkins coverage for it, we can make it official.
Towards #16001.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16124)
=> [doc] Offically support macOS Monterey

bindings/pydrake/geometry_py_visualizers.cc, bindings/pydrake/test/geometry_visualizers_test.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc
Adds support for saving the scene (including animations) into a
standalone HTML file which can be shared and enjoyed.  It is
equivalent to the `static_html()` method from `meshcat-python`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16142)
=> [meshcat] Add Meshcat::StaticHtml()

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/iris.cc, geometry/optimization/iris.h, geometry/optimization/test/iris_test.cc
Adds several fixes that were found to speed up/improve region generation including:
- Adding a relative volume growth termination threshold
- Sorts collision pairs using separation distance in the sample configuration and add hyperplanes based on the closest obstacles first
- Check that the sample point is still in the polytope after each hyperplane is added and fail fast when sample point leave polytope
Also fixed some formatting errors in `iris.cc`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16037)
=> [geometry:optimization] Add collection of fixes to speed up Iris region generation

systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/system.h, systems/framework/system_base.cc, systems/framework/system_base.h, systems/framework/system_scalar_converter.cc, systems/framework/system_scalar_converter.h, systems/framework/test/diagram_test.cc, systems/framework/test/system_scalar_converter_test.cc
Closes #14978.
Running the issue's example now produces: `RuntimeError: System ::_ of type drake::systems::Diagram<double> does not support scalar conversion to type drake::AutoDiffXd (because System ::_::meshcat_visualizer of type pydrake.systems.meshcat_visualizer.MeshcatVisualizer does not support scalar conversion to type drake::AutoDiffXd)`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16131)
=> [framework] Improve error message for diagram scalar conversion

geometry/optimization/iris.cc
Fixes an error caused on Mac builds for not using the reference type in a loop. Supersedes #16149
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16150)
=> Fix failing Mac build caused by #16037

bindings/pydrake/geometry_py_visualizers.cc, bindings/pydrake/test/geometry_visualizers_test.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc
Resolves #16109
After reading through the uwebsockets code, I understand now that the
maxBackpressure websocket option was *only* being used to decide when
to drop packets.  We never want to drop packets, so setting that to
zero is the correct behavior.
Backpressure is still a legitmate concern.  If we keep shoving data
into the send buffer faster than the websocket can send, then
backpressure will build up (consuming memory and causing the
visualizer to fall behind the main thread).  I've provided a `Flush()`
command for Meshcat which allows users to manually sync the main
thread if it is useful/needed in their application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/ …
=> [meshcat] Avoid dropping messages due to backpressure, and provide Flush()

geometry/proximity/BUILD.bazel, geometry/proximity/mesh_field_linear.h, geometry/proximity/polygon_surface_mesh_field.cc, geometry/proximity/polygon_surface_mesh_field.h
- The mesh field has conditional barycentric behavior (as barycentric coordinates are not well defined for polygonal elements).
- Provides an alias and instantiation for `MeshFieldLinear` on `PolygonSurfaceMesh` (to parallel `TriangleSurfaceMeshFieldLinear`).
Relates #15796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16122)
=> [hydro] Make MeshFieldLinear compatible with PolygonSurfaceMesh

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/test/supernodal_solver_test.cc, tools/workspace/conex/repository.bzl
This PR addresses the problem with asan builds reported in #16136:
1. Bumps to latest Conex commit, which removes hard coded build options.
2. Fixes uninitialized data in unit test, which triggered an error with asan.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16161)
=> [multibody] Re-enable asan for supernodal_solver_test

geometry/proximity/mesh_field_linear.h, geometry/proximity/mesh_intersection.cc, geometry/proximity/test/mesh_field_linear_test.cc
The field is expressed in a frame M. When transforming it to a frame N, we call `TransformGradients()`. If the field has stored gradients, this re-expresses the gradients. However, that is insufficient. `EvaluateCartesian()` uses those gradients to evaluate the field (when they exist). But it also depends on `values_at_Mo_` -- another frame-dependent quantity.
This updates the function in question to update *both* quantities and expands the unit test to cover this previously uncovered aspect of the code.
relates #15796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16160)
=> [hydro] Correct bug in MeshFieldLinear::TransformGradients()

geometry/proximity/BUILD.bazel, geometry/proximity/contact_surface_utility.cc, geometry/proximity/contact_surface_utility.h, geometry/proximity/mesh_half_space_intersection.cc, geometry/proximity/mesh_intersection.cc, geometry/proximity/mesh_plane_intersection.cc, geometry/proximity/test/contact_surface_utility_test.cc, geometry/proximity/test/mesh_half_space_intersection_test.cc
The mesh builder classes extract the knowledge of how to add intersection polygons to mesh representations. The intersection algorithms can simply generate the polygon (using whatever logic they require) and pass the data over to the builder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16134)
=> [hydro] Add MeshBuilder -- interface for building ContactSurface meshes

geometry/proximity/test/contact_surface_test.cc, geometry/query_results/contact_surface.cc, geometry/query_results/contact_surface.h
The contact surface now supports the polygonal mesh representation. It maintains old apis (`mesh_W()` and `e_MN()`) which map to the historical triangle representation of those quantities. We'll remove calls to those prior to actually *producing* polygonal contact surfaces.
Relates #15796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16126)
=> [hydro] Extend ContactSurface to include polygonal mesh representation

systems/primitives/multiplexer.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16184)
=> primitives: Fix missed paste-o in documentation

geometry/proximity/hydroelastic_callback.h, geometry/proximity/mesh_half_space_intersection.cc, geometry/proximity/mesh_half_space_intersection.h, geometry/proximity/test/mesh_half_space_intersection_test.cc
This reframes mesh-half space intersection to use the new `MeshBuilder` so it can create either polygon or triangle mesh representations. The APIs have been modified to communicate the desired representation and the tests have been updated accordingly.
Various related call sites have been updated to *explicitly* request triangle meshes (this was implicit before).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16164)
=> [hydro] Enable polygon contact surface in mesh-half space intersection

geometry/benchmarking/mesh_intersection_benchmark.cc, geometry/proximity/hydroelastic_callback.h, geometry/proximity/mesh_intersection.cc, geometry/proximity/mesh_intersection.h, geometry/proximity/test/mesh_intersection_test.cc, geometry/proximity/test/mesh_to_vtk_test.cc
This reframes mesh-mesh intersection to use the new `MeshBuilder` so it can create either polygon or triangle mesh representations. The APIs have been modified to communicate the desired representation and the tests have been updated accordingly.
Various related call sites have been updated to *explicitly* request triangle meshes (this was implicit before).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16163)
=> [hydro] Enable polygon contact surface from mesh-mesh intersection

multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/tree/rotational_inertia.cc, multibody/tree/rotational_inertia.h, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/rotational_inertia_test.cc, multibody/tree/test/spatial_inertia_test.cc, multibody/tree/unit_inertia.h
Amends #16065.
Inline functions must be small.
Correctly indent +4 for line-wrapped expressions.
Don't abbreviate `msg`.
Don't gratuitously check the expected exception types in unit tests.
Don't use `std::endl` as a synonym for `"\n"`.
~(We should wait for #16186 to be resolved, first.)~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16187)
=> [multibody] Fix style defects in recent SpatialInertia fix

geometry/proximity/hydroelastic_callback.h, geometry/proximity/mesh_plane_intersection.cc, geometry/proximity/mesh_plane_intersection.h, geometry/proximity/test/mesh_plane_intersection_test.cc
This reframes mesh-plane intersection to use the new `MeshBuilder` so it can create either polygon or triangle mesh representations. The APIs have been modified to communicate the desired representation and the tests have
been updated accordingly.
Call sites have been updated to *explicitly* request triangle meshes (this was implicit before).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16162)
=> [hydro] Enable polygon contact surface in mesh-plane intersection

examples/scene_graph/simple_contact_surface_vis.cc, geometry/geometry_state.h, geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc, geometry/proximity/hydroelastic_callback.h, geometry/proximity/test/hydroelastic_callback_test.cc, geometry/proximity_engine.cc, geometry/proximity_engine.h, geometry/query_object.cc, geometry/query_object.h, geometry/test/proximity_engine_test.cc, geometry/test/query_object_test.cc, multibody/plant/multibody_plant.cc, multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
This adds the `HydroelasticMeshRepresentation` as a *required* parameter in the `QueryObject` contact surface API. Updates call sites to satisfy the non-optional parameter.
relates #15796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16177)
=> [hydro] Extend mesh representation into public API

bindings/pydrake/geometry_py_scene_graph.cc, bindings/pydrake/multibody/test/plant_test.py, examples/scene_graph/simple_contact_surface_vis.cc, geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc, geometry/proximity/test/mesh_to_vtk_test.cc, geometry/query_results/contact_surface.h, geometry/test/proximity_engine_test.cc, multibody/plant/compliant_contact_manager.cc, multibody/plant/contact_results_to_lcm.cc, multibody/plant/hydroelastic_contact_info.h, multibody/plant/hydroelastic_traction_calculator.cc, multibody/plant/hydroelastic_traction_calculator.h, multibody/plant/multibody_plant.cc, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/contact_results_to_lcm_test.cc, multibody/plant/test/hydroelastic_traction_test.cc, multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc, multibody/plant/test/multibody_plant_hydroelastic_test.cc
This eliminates the legacy methods (maintained for the duration of the PR train). It also captures all call sites and updates them to an appropriate alternative spelling.
relates #15796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16176)
=> [hydro] Remove the legacy e_MN() and mesh_W() apis from ContactSurface

examples/scene_graph/simple_contact_surface_vis.cc, geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc, multibody/plant/compliant_contact_manager.cc, multibody/plant/contact_results_to_lcm.cc, multibody/plant/hydroelastic_traction_calculator.cc, multibody/plant/hydroelastic_traction_calculator.h, multibody/plant/multibody_plant.cc, multibody/plant/test/hydroelastic_traction_test.cc, multibody/plant/test/multibody_plant_hydroelastic_test.cc
- `MultibodyPlant` now uses a polygonal contact surface for discrete hydro.
- This includes changes to the compliant contact manager and hydro traction calculator.
- Note: a large portion of the changed loc count is due to large blocks of code having their indentation changed due to the removal of a for loop.
- Objects that visualize contact surfaces are taught about polygonal meshes
- this includes non-dynamics related stubs in examples and geometry/profiling.
relates #15796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16175)
=> [hydro] Connect polygonal contact surface into dynamics

geometry/profiling/README.md, geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc
The rigid-bowl/soft-ball contact surfaces use polygons by default with an option to use triangles.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16197)
=> [geometry] Use polygons in a profiling example of contact surface creation.

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc
This PR allows us to use trajectories as AbstractValues in pydrake.  I need this to, e.g., write a planner in pydrake that declares a trajectory as an abstract state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16190)
=> [trajectories] Define python copy/deepcopy for trajectory classes

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc, multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h, multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc
Use Jacobi preconditioner instead of BlockJacobi for generic matrices
since PETSc's BlockJacobi preconditioner assumes SPD blocks.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16205)
=> [fixed_fem] Re-enable ubsan for PETSc tests

multibody/tree/rotational_inertia.cc, multibody/tree/test/rotational_inertia_test.cc, multibody/tree/test/spatial_inertia_test.cc
Cleanup errant comma when writing a RotationalInertia.  This was requested by @EricCousineau-TRI during recent PR for writing error messages when user has a bad RotationalInertia or SpatialInertia.  The bigger issue of a good way to consistently write matrices is not addressed here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16222)
=> Remove errant comma when writing a RotationalInertia

bindings/pydrake/geometry_py_common.cc, examples/multibody/rolling_sphere/README.md, examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc, geometry/benchmarking/mesh_intersection_benchmark.cc, geometry/profiling/README.md, geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc, geometry/proximity/triangle_surface_mesh.h, geometry/proximity_properties.cc, geometry/proximity_properties.h, geometry/query_object.h, geometry/test/proximity_engine_test.cc, multibody/contact_solvers/contact_solver.h, multibody/plant/test/multibody_plant_hydroelastic_test.cc
- No change in the code except in the comments.
- No change to the internal namespace.
- Keep the word "soft" when the context is clear. Specifically, the terms
"soft hydroelastics" and API AddSoftHydroelasticProperties() stay.
The follow-up PR #16224 will change the API like AddSoftHydroelasticProperties() to AddCompliantHydroelasticProperties() (and corresponding SDF/URDF tags).
Relates #15796.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16218)
=> [hydro] Edit most public document to use the word "compliant" instead of "soft"

geometry/test_utilities/BUILD.bazel, geometry/test_utilities/meshcat_environment.cc, geometry/test_utilities/meshcat_environment.h, manipulation/models/ycb/BUILD.bazel, manipulation/models/ycb/test/parse_test.cc
Port the ycb parsing demo to use it.
The utility ensures that the test-global meshcat object is torn down upon the completion of the tests.
Closes #16235.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16236)
=> [geometry] Add meshcat_environment test utility

geometry/render/dev/BUILD.bazel, geometry/render/dev/render_engine_vtk_minimal_example.cc
Currently, no object in the scene has a `RenderLabel` assigned to it. The only exception is `mustard_bottle` where `RenderLabel` is assigned somewhere in the pipeline, but not in this code. This PR adds `RenderLabel` to all the objects.
Also, I added image saving feature to make debugging easier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16237)
=> [geometry/dev] Assign render labels to objects and add image saving feature

multibody/contact_solvers/sap_solver.cc, multibody/contact_solvers/sap_solver.h, multibody/contact_solvers/test/sap_solver_test.cc
This resolves the mac continuous failure [here](https://drake-jenkins.csail.mit.edu/view/Production/job/mac-monterey-clang-bazel-continuous-release/81/consoleFull)
Sometimes, due to round-off errors, the optimality condition is not satisfied but the search directions is already very small (||dv||≈1e-8 to 1e-7) and dℓ/dα is close to machine epsilon. Under this circumstances, the line search cannot find the minimum and aborts (essentially it thinks the cost is a flat line and reaches the maximum number of iterations without converging). These smalls number do not cause trouble in Linux but apparently mac is more sensitive.
Still, going into the line search when dℓ/dα is close to machine epsilon is a bad idea. This PR avoids this problem by also monitoring the convergence of the cost. If the …
=> SAP: Implements stopping criteria on the cost.

examples/manipulation_station/manipulation_station.cc
Otherwise, point clouds are a lie
A short-term workaround for #12125
Motivated by review of #14991
\cc @RussTedrake @jwnimmer-tri @SeanCurtis-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15186)
=> manip. station: Use same extrinsics+intrinsics for color+depth

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py, systems/framework/leaf_system.h, systems/framework/state.h
Along with #16190 , these bindings were required to enable the following simple example:
```
from pydrake.all import (AbstractValue, EventStatus, LeafSystem, PiecewisePolynomial, Simulator)
class MySimplePlanner(LeafSystem):
def __init__(self, traj):
LeafSystem.__init__(self)
assert traj.cols() == 1
self.DeclareVectorOutputPort("value", traj.rows(), self.CalcOutput)
self.DeclareAbstractState(AbstractValue.Make(traj)) # The trajectory.
self.DeclareDiscreteState(1) # Add one more state to denote whether the trajectory been updated yet...
self.DeclarePeriodicUnrestrictedUpdateEvent(
period_sec=0.1, offset_sec=0.0, update=self.MaybeUpdatePlan)
def MaybeUpdatePlan(self, context, state):
updated = state.get_mutable_discrete_state(0)
if not updated[0] and context.get_time() > 1.0:
traj = …
```
=> [pydrake] Add missing LeafSystem and State bindings

examples/multibody/rolling_sphere/README.md, geometry/test/drake_visualizer_test.cc, multibody/parsing/detail_scene_graph.h, multibody/parsing/detail_urdf_geometry.h, multibody/plant/test/contact_results_to_lcm_test.cc
Noticed and fixed one while working on #16238; this patch fixes all the
others I could find that at least spell "hydro" correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16239)
=> [hydro] Cleanup typos of "hydroelastic"

tools/skylark/drake_py.bzl
This removes spurious warnings from Bazel when other things go wrong.
Closes #14745.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16259)
=> [tools] Set Python version to 3 explicitly

CMakeLists.txt, tools/install/BUILD.bazel, tools/install/install.bzl, tools/install/installer.py, tools/install/test/install_meta_test.py
Towards #7331.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16252)
=> [install] Use file argument for actions, not template substitution

bindings/pydrake/common/schema_py.cc, bindings/pydrake/common/test/schema_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16261)
=> Bind copyability of schema types

multibody/parsing/detail_scene_graph.cc, multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/test/detail_scene_graph_test.cc, multibody/parsing/test/detail_urdf_geometry_test.cc
Require drake:compliant_hydroelastic instead of drake:soft_hydroelastic.
Before this PR, any collision geometry with <drake:soft_hydroelastic/> tag in SDF/URDF file will be silently ignored by hydroelastics. We want to give an error and tell users to change it to <drake:compliant_hydroelastic/>. Otherwise, users won't be aware that their geometries participate in point contact instead.
Relevant to #15796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16249)
=> [multibody] Prohibit SDFormat/URDF tag drake:soft_hydroelastic

geometry/meshcat_point_cloud_visualizer.h
Relevant to #9496
Apply the guideline "move other port annotations to surrounding text";
the necessary text already exists.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16203)
=> visualization: Update doxygen block diagrams

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
Currently, invoking the method from pydrake causes runtime error `return_value_policy = copy, but type is non-copyable!`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16274)
=> [bindings] Correct return type for MbP::GetUniqueFreeBaseBodyOrThrow

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
Add the L2NormCost using a slack variable with linear cost and LorentzConeConstraint. This is suitable for conic optimization solvers (Gurobi/Mosek/SCS)
As mentioned in #15366
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16208)
=> AddL2NormCostUsingConicConstraint.

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/dynamic_elasticity_model.h, multibody/fixed_fem/dev/fem_model.h, multibody/fixed_fem/dev/fem_model_base.cc, multibody/fixed_fem/dev/fem_model_base.h, multibody/fixed_fem/dev/static_elasticity_model.h, multibody/fixed_fem/dev/test/dynamic_elasticity_model_test.cc, multibody/fixed_fem/dev/test/static_elasticity_model_test.cc
Add `FemModelBase::CalcTangentMatrix()` that populates a PETSc matrix. 
Add `FemModelBase::MakePetscSymmetricBlockSparseTangentMatrix()` that initializes the tangent matrix in PETSc format with the sparsity pattern of the problem.
The added unit tests verify that the tangent matrix calculated in PETSc form and the one calculated in Eigen::SparseMatrix form are the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16267)
=> [fem] Calculate FEM tangent matrix in PETSc format

setup/ubuntu/source_distribution/install_prereqs.sh, setup/ubuntu/source_distribution/packages-focal-satisfy.txt
xargs was hiding the [Y/n] prompt
Refs: #16233.
Edit: Link to bug report on Slack [here](https://drakedevelopers.slack.com/archives/C270MN28G/p1640183163197600)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16280)
=> fix libcurl installation

systems/controllers/inverse_dynamics.h, systems/controllers/inverse_dynamics_controller.h, systems/controllers/linear_model_predictive_controller.h, systems/controllers/pid_controlled_system.cc, systems/controllers/pid_controlled_system.h
This patch adds missing diagrams, updates some others for consistent
style, and in one case (PidControlledSystem), adds some previously
missing port names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16193)
=> controllers: Add/update doxygen block diagrams

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h, tools/workspace/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/qhull/BUILD.bazel, tools/workspace/qhull/package.BUILD.bazel, tools/workspace/qhull/repository.bzl
- Brings in qhull as an external.
- Adds an implementation for generating VPolytope from HPolyhedron using qhull
Co-authored-by: Mark Petersen <markpetersen@g.harvard.edu>
Co-authored-by: Tobia Marcucci <tobiam@mit.edu>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16272)
=> [geometry:optimization] Add VPolytope from HPolyhedron

geometry/optimization/test/graph_of_convex_sets_test.cc, solvers/clp_solver.cc, solvers/clp_solver.h, solvers/test/clp_solver_test.cc, solvers/test/ipopt_solver_test.cc, solvers/test/linear_program_examples.cc, solvers/test/linear_program_examples.h
This handles the poor scaling in the problem data.
Resolves #15341
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16281)
=> Call scaling() before solving in ClpSolver.

solvers/mathematical_program.h
Previously the documentation was
Now it is
where the matrix shows up correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16291)
=> Improve documentation for AddMaximizeLogDeterminantSymmetricMatrixCost

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/constraint.cc, solvers/constraint.h, solvers/test/constraint_test.cc
I don't remember why I made `A, b` as constant data inside LorentzConeConstraint and RotatedLorentzConeConstraint. Now I don't see a problem of updating their values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16297)
=> Add UpdateCoefficients to (rotated)LorentzConeConstraint

tools/wheel/build-wheels, tools/wheel/test/provision.sh
Don't include `user.bazelrc` in the source tarball used to build wheels; it shouldn't be needed, and its inclusion results in user environment leaking into what is supposed to be a hermetic build environment. Tweak the script used to provision the wheel test containers to use `-y` when running `apt-get update`, for consistency with similar calls in other scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16290)
=> Minor wheel fixes

tools/release_engineering/relnotes.py, tools/workspace/new_release.py
#16133 updated the Ubuntu release number but not the code name.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16305)
=> Update Ubuntu codename to match release

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/exponential_cone_program_examples.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16296)
=> Return the new cost and slack variables from AddMaximizeLogDeterminantSymmetricMatrixCost

multibody/fixed_fem/dev/BUILD.bazel, multibody/fixed_fem/dev/dirichlet_boundary_condition.h, multibody/fixed_fem/dev/fem_model_base.cc, multibody/fixed_fem/dev/fem_solver.h, multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc, multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h, multibody/fixed_fem/dev/test/dirichlet_boundary_condition_test.cc, multibody/fixed_fem/dev/test/fem_solver_test.cc
This PR contains two commits:
Commit 1: Apply Dirichlet boundary conditions to tangent matrices in PETSc format.
Commit 2: Build and solve tangent matrices in PETSc format in FemSolver when the scalar type is `double`. Fall back to the slow `Eigen::SparseMatrix` tangent matrix for other scalar types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16306)
=> [fem] Integrate PETSc matrix with FemSolver

examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc
- Add option `hydro_rep` for contact-surface representation in hydroelastics.
Relevant to #16244.
To illustrate or verify the solution to the problem of the crash in continuous hydroleastics with polygonal contact surfaces, this PR let users try:
```
bazel run //examples/multibody/rolling_sphere:rolling_sphere_run_dynamics -- --mbp_dt=0.0 --contact_model=hydroelastic --hydro_rep=poly
```
As of December 19, 2021, using the above command in this PR will crash with this error message:
```
terminate called after throwing an instance of 'std::runtime_error'
what():  Encountered singular articulated body hinge inertia for body node index 1. Please ensure that this body has non-zero inertia along all axes of motion.
```
Once we fix Issue #16244 (and rebase on the new master), the above command …
=> [examples/multibody] Hydroelastic-representation option for rolling sphere

multibody/fixed_fem/dev/BUILD.bazel
Original error reproducible locally on Ubuntu Focal:
```
export CC=clang-9 CXX=clang++-9
bazel test --config=ubsan //multibody/fixed_fem/dev:deformable_rigid_manager_test
```
Context (Slack): https://drakedevelopers.slack.com/archives/C270MN28G/p1641479669001500
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16321)
=> [fixed_fem] Disable deformable_rigid_manager_test under ubsan

examples/atlas/urdf/atlas_convex_hull.urdf, manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf, manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf, multibody/parsing/test/links_with_visuals_and_collisions.urdf, multibody/plant/test/atlas_with_fixed_joints.urdf
Relevant to: #16310
This patch modernizes the spelling of collision filter groups for all in-tree
urdf files. It makes no changes to parsing, core functions, or tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16325)
=> urdf: Modernize collision filter groups

doc/_pages/python_bindings.md
Found this to be useful in Anzu. Hoisting advice here.
Perhaps this could be placed in either `pydrake.common.debug` or `pydrake.debug`. Concrete advice here would help!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16227)
=> python_bindings: Add advice for using self-contained `ipdb.iex`

geometry/proximity/test/hydroelastic_callback_test.cc
- Use static_cast<int> on enum class HydroelasticContactRepresentation.
The failure happened on mac-big-sur-unprovisioned-clang-bazel-nightly-release as reported here:
https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=1536205
Buildcop discussion: https://drakedevelopers.slack.com/archives/C270MN28G/p1641826183010800
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16341)
=> [geometry] Fix unit tests of hydroelastic callback on macOS unprovisioned

geometry/render/test/box.sdf, manipulation/models/iiwa_description/iiwa7/iiwa7_with_box_collision.sdf, multibody/parsing/test/links_with_visuals_and_collisions.sdf, multibody/parsing/test/links_with_visuals_and_collisions.urdf, multibody/parsing/test/sdf_parser_test/all_geometries_as_collision.sdf, multibody/parsing/test/sdf_parser_test/all_geometries_as_visual.sdf, multibody/parsing/test/urdf_parser_test/all_geometries_as_collision.urdf, multibody/parsing/test/urdf_parser_test/all_geometries_as_visual.urdf, multibody/parsing/test/urdf_parser_test/convex_and_nonconvex_test.urdf, multibody/parsing/test/urdf_parser_test/non_conflicting_materials_2.urdf
For the sake of consistency among other reasons, replace the handful of model-relative file paths with absolute `package://` URIs.
Related to #10218 and #10531
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16173)
=> Replace relative paths with package URIs in models

systems/trajectory_optimization/BUILD.bazel
Otherwise, debug CI may timeout
Most likely introduced in #16333
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16346)
=> direct_transcription_test: Double shard_count

manipulation/perception/BUILD.bazel, manipulation/perception/pose_smoother.h
Closes #15929.  If someone wants to land the RigidTransform version in Drake, they can rework it from the git history.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16343)
=> [perception] Deprecate PoseSmoother

tools/wheel/Dockerfile, tools/wheel/build-wheels, tools/wheel/image/packages-bionic, tools/wheel/image/packages-focal, tools/wheel/image/provision-base.sh, tools/workspace/nlopt/repository.bzl, tools/workspace/os.bzl
Refactor wheel provisioning to allow for different packages between Bionic and Focal. Update build script to add new targets for Focal, and to account for additional changes in the wheel name.
Refactor OS detection so that "manylinux" is a subset of "ubuntu". Particularly, this means that `is_ubuntu` is true if `is_manylinux` is true, and that `ubuntu_release` is set.
Tweak logic in various packages to account for this change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16308)
=> Add wheels for Focal (Python 3.8 and 3.9)

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/BUILD.bazel, common/symbolic_latex.cc, common/symbolic_latex.h, common/test/symbolic_latex_test.cc
Now we can render our symbolic expressions beautifully in Jupyter notebooks.  :-)
Example from the underactuated intro notebook:
```
plant = MultibodyPlant(time_step=0)
parser = Parser(plant)
parser.AddModelFromFile(FindResource("models/double_pendulum.urdf"))
plant.Finalize()
q = [Variable("\\theta_0"), Variable("\\theta_1")]
v = [Variable("\\dot\\theta_0"), Variable("\\dot\\theta_1")]
(M, Cv, tauG, B, tauExt) = ManipulatorDynamics(plant.ToSymbolic(), q, v)
display(Math("M = " + ToLatex(M, precision=2)))
display(Math("Cv = " + ToLatex(Cv, precision=2)))
display(Math("\\tau_G = " + ToLatex(tauG, precision=2)))
display(Math("B = " + ToLatex(B, precision=2)))
display(Math("\\tau_{ext} = " + ToLatex(tauExt, precision=2)))
```
gives e.g. 
fyi @soonhokong .
--- …
=> [symbolic] Output symbolic::Expression/Formula as a LaTeX string

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/test/graph_of_convex_sets_test.cc, solvers/cost.cc, solvers/cost.h, solvers/test/cost_test.cc
Also binds the creation of `Bindings` from a cost/constraint and decision variables to enable adding these costs in Python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16334)
=> Add L1NormCost and LInfNormCost to GraphOfConvexSets cost options

geometry/render/render_engine_vtk.cc, geometry/render/test/render_engine_vtk_test.cc
Current tests of the background alpha value are internally inconsistent, some test for alpha=0 and some for alpha=255.  Explicitly requesting the SetBackgroundAlpha of the color renderer to 1.0 (rather than default of 0.0), and updating tests to all check for alpha=255 is the correct fix, where 1.0 in floating point color is 255 in RGBA uint8 color.
Refs: https://gitlab.kitware.com/vtk/vtk/-/commit/0546373c89227384f68c0e5acfc4d47c26f6a81b
Current code testing for alpha=255 relies on the hard-coded return alpha value of 1.0 in the FXAA shader.  Once VTK 9 is used, the above commit will break these tests as alpha will become 0.
vtkRenderWindow will have the correct background color with alpha=0, however vtkRenderWindow => vtkWindowToImageFilter => vtkImageExport will lose the background …
=> Fix internally inconsistent RenderEngineVtk opacity.

multibody/hydroelastics/hydroelastic_engine.cc, multibody/hydroelastics/test/hydroelastic_engine_test.cc, multibody/parsing/detail_common.cc, multibody/parsing/test/detail_common_test.cc
Related to #15796
- Make `HydroelasticEngine` ignore the `hydroelastic_modulus` property on geometries declared "rigid"
- Add a warning to the parser when the `drake:hydroelastic_modulus` tag is present in a geometry declared "rigid"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16322)
=> [multibody] HydroelasticEngine ignores hydroelastic_modulus of rigid geometries.

tools/workspace/os.bzl
Tweak how we detect the Linux distribution name and version to use `lsb_release` rather than directly examining `/etc/os-release` directly using sed "magic". This is more consistent with how we handle distro detection in other places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16353)
=> Use `lsb_release` for distro detection

systems/framework/system.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16361)
=> [framework] Fix a deprecation date typo

systems/primitives/random_source.h
Users should spell out `RandomSource<double>` instead.
This alias was here as part of a transition plan -- the `class RandomSource` was previously un-templated; in the process of making it be templated, we offered this helper in the meantime.  With the exception of a few key classes (`RotationMatrix`, etc.) we tend _not_ to off the `Myclassd = MyClass<double>` aliases in Drake.  We should really just be using CTAD (and/or `T = double` in more places, instead).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16359)
=> [primitives] Deprecate RandomSourced alias

geometry/render/dev/render_engine_vtk_minimal_example.cc
These viewpoints were helpful in examining various aspects of the render and cover a decent range of positions.  It takes a bit of time to toy with xyz_rpy manually, including a comment with desirable viewpoints to test is helpful to general consumption of the file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16364)
=> [geometry/dev] add comment with useful viewpoints

multibody/parsing/test/detail_scene_graph_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, tools/workspace/sdformat/package.BUILD.bazel, tools/workspace/sdformat/patches/console.patch, tools/workspace/sdformat/repository.bzl
Fixes #16344.
See also ignitionrobotics/sdformat#820.
Example output:
```
[ RUN      ] FileParserTest.BadStringTest
[2022-01-10 16:38:53.086] [console] [error] SDFormat Error [parser.cc:798] Error parsing XML from string: Error=XML_ERROR_PARSING_TEXT ErrorID=10 (0xa) Line number=1
[       OK ] FileParserTest.BadStringTest (64 ms)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16348)
=> [parsing] Redirect sdformat console messages to drake logging

tools/vector_gen/BUILD.bazel
Exclude `lcm_vector_gen_test` from being run under `valgrind` (memcheck). This test is just a shell script comparing some generated output to the expected output, so does not gain anything by being run under valgrind. However, on Focal, valgrind reports errors in `sed`, resulting in a test failure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16372)
=> Don't memcheck lcm_vector_gen_test

geometry/geometry_state.cc, geometry/geometry_state.h, geometry/scene_graph_inspector.h, geometry/test/geometry_state_test.cc, geometry/test/scene_graph_inspector_test.cc
This adds a new API `SceneGraphInspector::GetParent()` to get the parent frame given a `FrameId` of the child. The motivation is to enable RobotLocomotion/drake-ros#20 to include the parent/child relationships in the published tf tree.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16368)
=> Add SceneGraphInspector::GetParent(FrameId)

doc/_release-notes/v0.38.0.md, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/__init__.py
Per #16215.
Note that this deprecation window is tighter than usual (it would be 2022-05-01 by the usual math).  This change was already announced as of the v0.38.0 release notes and in #16215 and in slack, and is somewhat urgent to retire sooner rather than later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16386)
=> [tools] Deprecate drake-visualizer on macOS

tools/wheel/dev/README.md, tools/wheel/dev/build-wheels
https://github.com/RobotLocomotion/drake-ci/pull/132 is already finished, so the old location is no longer used anywhere.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16388)
=> [wheel] Remove vestigial dev folder

manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc
Missed test in https://github.com/RobotLocomotion/drake/pull/16003.
Adding `dual_iiwa14_polytope_collision.urdf` to the tests. 
Since this `URDF` contains two instances of the `iiwa14_polytope_collision` model, the extra test steps have been added.
@EricCousineau-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16376)
=> adding dual iiwa14 polytope collision test

manipulation/models/iiwa_description/README.md, manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf, manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc, manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14.xacro, manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf, manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf
Addresses the second task of https://github.com/RobotLocomotion/drake/issues/15613.
Provides an estimation of acceleration joint limits for the KUKA IWA14 models. Includes unit tests consistency checks and `README.md` updates.
Acceleration joint limit estimations have been derived from experimental results listed in Table 4 (page 50) of the following Master's thesis:
https://odr.chalmers.se/bitstream/20.500.12380/256658/1/256658.pdf
@EricCousineau-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16377)
=> Iiwa14 acceleration limits

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/primitives/BUILD.bazel, systems/primitives/multilayer_perceptron.cc, systems/primitives/multilayer_perceptron.h, systems/primitives/test/multilayer_perceptron_test.cc
I've been looking at various ways to interface between Drake and
Pytorch, and realized that in many workflows (at least for RL), the
networks are so small that any advantage we get from moving to PyTorch
/ GPU is probably washed away by the interface layer.
I think it will prove very useful to have this class here; I suspect
that in many relevant cases we won't need PyTorch at all.
N.B. - I will add the python bindings in a follow-up PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16396)
=> [systems] Add MultilayerPerceptron

multibody/fixed_fem/dev/deformable_rigid_manager.cc, multibody/fixed_fem/dev/deformable_rigid_manager.h, multibody/fixed_fem/dev/fem_model.h, multibody/fixed_fem/dev/test/deformable_rigid_contact_solver_test.cc, multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
This is the last PR to integrate PETSc into the deformable solver. In `double` calculations, the tangent matrix now uses PETSc symmetric block sparse matrix instead of Eigen::SparseMatrix.
Run `bazel run //multibody/fixed_fem/dev:run_cantilever_beam` and compare with base line commit `d0db6f` to observe the performance improvement. On my P53 laptop, the speedup is about 2X.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16311)
=> [fem] Use PETSc matrix in DeformableRigidManager

tools/cc_toolchain/bazel.rc, tools/skylark/drake_cc.bzl
When something depends on a unit test (in our case, the macOS dSYM generation), then Bazel as of 5.0 dies a horrible death.
Work around that by adding the dependency only in cases where the user has opted-in to debugging on macOS, and in that case also turn off the problematic trim_test_configuration feature.
Relates to https://github.com/bazelbuild/bazel/issues/14294.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16405)
=> [tools] Fix "generated by these conflicting actions" in Bazel 5.0

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
The GeometryId values for collisions come in on an input port. We need to sanity-check them prior to using them.
For two maps that were already dead code, we just kill the deadwood instead of adding guards for it.  The related `default_coulomb_friction_` was also dead code, so is also purged.
Closes #16116.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16390)
=> [multibody] Guard hazardous map access by GeometryId

bindings/pydrake/BUILD.bazel, bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/monostate_pybind.h, bindings/pydrake/geometry_py_scene_graph.cc
This is a prerequisite of #16400.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16407)
=> [pydrake] Factor out the std::monostate support for reuse

geometry/optimization/iris.cc, geometry/optimization/test/iris_test.cc
Since Iris only checks the closest point on an obstacle to see if a new hyperplane should be added, there are cases where the closest point of an obstacle is not in the region that has been constructed so far, but a different part of the obstacle is.  The old implementation would therefore result in Iris regions that overlapped obstacles.  This PR fixes the decision criteria for adding a hyperplane and adds a test that failed prior to the change to Iris.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16398)
=> [geometry/optimization] Fix Iris regions not collision free issue

common/name_value.h, common/schema/rotation.h, common/schema/stochastic.h, common/schema/transform.h, common/trajectories/bspline_trajectory.h, common/yaml/BUILD.bazel, common/yaml/test/yaml_doxygen_test.cc, common/yaml/yaml_doxygen.h, common/yaml/yaml_io.h, common/yaml/yaml_node.h, common/yaml/yaml_read_archive.h, math/bspline_basis.h
Instructions for local preview:
```
git fetch upstream pull/16083/head && git checkout FETCH_HEAD
git merge upstream/master
bazel run //doc/doxygen_cxx:build -- --serve --quick drake/common/yaml
```
That preview of the yaml-only header files will have broken links to other parts of the code.  To have working links, don't pass the `drake/common/yaml` filter on the command-line, pass `drake/common` or all of `drake`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16083)
=> [yaml] Add Doxygen overview

tools/install/dummy/BUILD.bazel
Fixes failure on Mac builds after updating to Bazel 5. 
```
[3:39:05 AM]  ERROR: file 'tools/install/dummy/libdummy.so' is generated by these conflicting actions:
[3:39:05 AM]  Label: //tools/install/dummy:libdummy.so, //tools/install/dummy:dummy
[3:39:05 AM]  RuleClass: cc_binary rule, cc_library rule
[3:39:05 AM]  Configuration: 21a5de7e367ccd7bd7015ef91735ce3d9e0fc525245b61fe7cb8b7c1d14be65c
[3:39:05 AM]  Mnemonic: CppLink, Fail
[3:39:05 AM]  Action key: ddc895ae1e57540d0f5864d077667683cbecc2a45e582d4ea839f7be56b9698d, d2b21694bd9c7986a236b5ae39648b4f403e57cdcf2d085a4136fea6ce1601c4
[3:39:05 AM]  Progress message: Linking tools/install/dummy/libdummy.so, Reporting failed target //tools/install/dummy:dummy located at /Users/bigsur/workspace/mac-big-sur-unprovisioned-clang-bazel-nightly-r …
```
=> Rename dummy library to fix Bazel 5 error

tools/install/BUILD.bazel, tools/install/test/install_meta_test.py
Relevant to: #7331
This patch doesn't directly improve testability, but it does make it
easier to capture coverage statistics (for example by #16392), and gives
some small examples of why globals hinder unit testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16414)
=> installer: Add tests that invoke by import

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/all.py, bindings/pydrake/multibody/meshcat_py.cc, bindings/pydrake/multibody/test/meshcat_test.py, bindings/pydrake/test/all_test.py, multibody/meshcat/BUILD.bazel, multibody/meshcat/joint_sliders.cc, multibody/meshcat/joint_sliders.h, multibody/meshcat/test/joint_sliders_test.cc, multibody/meshcat/test/universal_joint.sdf, tools/install/libdrake/build_components.bzl
Based on [meshcat_cpp_utils.py](https://github.com/RussTedrake/manipulation/blob/008cec6343dd39063705287e6664a3fee71a43b8/manipulation/meshcat_cpp_utils.py#L236) from Russ.
Part of #16385.
This PR only adds the System itself (and the pydrake bindings).  It does not yet offer the `Run` loop.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16400)
=> [meshcat] Add JointSliders system

bindings/pydrake/test/all_test.py, bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/all.py, bindings/pydrake/visualization/meldis.py, examples/acrobot/README.md, tools/BUILD.bazel
The server program is named "meldis".
Update the acrobot example's README to use it.
---
We need to port our demos away from `drake-visualizer` (#16216).  For many of those demos, viewing _only_ the geometry is sufficient (i.e., no need to show contact points, images, time, etc.).  This tool will allow us to immediately switch all of them to meshcat with changes to their README files, without any other code changes.
I've found it awkward to try to port their code directly to meshcat -- we need to change all of them to launch meshcat, then pause allow the user to click on the http link, and then begin the simulation.  Those tend to be more invasive changs that are a bit difficult to do quickly.  Meshcat works well in that mode for Jupyter notebooks, but for standalone C++ simulations the …
=> [tools] Add meshcat display server for drake_visualizer's protocol

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
Towards #16369
Implements the default settings as described in https://mujoco.readthedocs.io/en/latest/modeling.html#cdefault
I had originally planned to not have to support default in my initial
parser implementation.  But the DeepMind control suite (which we
switched to using for the unit tests) uses `default` heavily, and the
files cannot be parsed correctly without this support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16425)
=> [multibody/parsing] Support default geometry attributes in MuJoCo parser

multibody/parsing/detail_mujoco_parser.cc
clang on mac needed an explicit cast of char* to bool in an initializer list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16428)
=> fix detail_mujoco_parser on mac

tools/install/installer.py, tools/install/test/install_meta_test.py
Relevant to: #7331
At best, the subdirs tracking was an optimization; at worst, a
temptation to TOCTOU errors. Removing it is another baby step toward
testability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16430)
=> tools: Remove global subdirs from installer

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/augmented_lagrangian_py.cc, bindings/pydrake/solvers/test/augmented_lagrangian_test.py, solvers/BUILD.bazel, solvers/augmented_lagrangian.cc, solvers/augmented_lagrangian.h, solvers/test/augmented_lagrangian_test.cc
Turn a constrained optimization problem to the unconstrained one, by
evaluating its augmented Lagrangian, given the variable value, the
estimated Lagrangian and the penalty term.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16391)
=> Eval augmented lagrangian

bindings/pydrake/multibody/meshcat_py.cc, bindings/pydrake/multibody/test/meshcat_test.py, multibody/meshcat/BUILD.bazel, multibody/meshcat/joint_sliders.cc, multibody/meshcat/joint_sliders.h, multibody/meshcat/test/joint_sliders_test.cc
Based on [meshcat_cpp_utils.py](https://github.com/RussTedrake/manipulation/blob/008cec6343dd39063705287e6664a3fee71a43b8/manipulation/meshcat_cpp_utils.py#L330) from Russ.
This flavor does not offer the `root_context` nor `callback` arguments that the original one did.  They did not appear to be necessary in the near term -- almost all uses had a null callback, and always used a default-constructed context.  We can add them later, if we find that they are necessary.
Closes #16385.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16426)
=> [meshcat] Add JointSliders::Run

geometry/render/render_engine_vtk.h
For consistency. `bazel run //doc/doxygen_cxx:build -- --serve --quick drake.geometry.render` to check, the `Does not allow copy, move, or assignment` section is still bold as expected.  File will likely be at `http://localhost:8000/doxygen_cxx/classdrake_1_1geometry_1_1render_1_1_render_engine_vtk.html` if using that command.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16438)
=> [doxygen] use @name rather than \name

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/_plant_extra.py, bindings/pydrake/multibody/meshcat_py.cc, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/meshcat_test.py, bindings/pydrake/multibody/test/plant_test.py, geometry/BUILD.bazel, geometry/test/meshcat_manual_test.cc, multibody/meshcat/BUILD.bazel, multibody/meshcat/contact_visualizer.cc, multibody/meshcat/contact_visualizer.h, multibody/meshcat/contact_visualizer_params.h, multibody/meshcat/test/contact_visualizer_test.cc, multibody/plant/BUILD.bazel, multibody/plant/contact_results_to_meshcat.h, multibody/plant/contact_results_to_meshcat_params.h, multibody/plant/test/contact_results_to_meshcat_test.cc
... and rename it to ContactVisualizer for simplicity.
We should not contaminate the MultibodyPlant library with an unconditional dependency on MeshCat.
Relates to #15968 and #16216.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16437)
=> [multibody] Move ContactResultsToMeshcat into meshcat directory

bindings/pydrake/solvers/mathematicalprogram_py.cc, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
Previously when we pass in matrix input, it (silently) only impose
constraint on the first column of the matrix.
Resolves #16421
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16424)
=> AddFooConstraint support matrix input.

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, examples/pr2/test/load_pr2_simplified_test.cc, multibody/parsing/package_map.cc, multibody/parsing/package_map.h, multibody/parsing/parser.cc, multibody/parsing/test/detail_path_utils_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_geometry_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/package_map_test.cc
Part of #10531.
This should have been concomitant with #15947, but we overlooked it.  Since we don't have any more non-root manifests (outside of unit tests), we don't need any function or automation to find them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16434)
=> [parsing] Deprecate PopulateUpstreamToDrake

geometry/meshcat.h, multibody/meshcat/BUILD.bazel, multibody/meshcat/contact_visualizer.cc, multibody/meshcat/contact_visualizer.h, multibody/meshcat/point_contact_visualizer.cc, multibody/meshcat/point_contact_visualizer.h
Separating the logic for meshcat geometry updates (versus the framework goop and body naming) provides for a clearer and more efficient implementation, and will also allow for reusing the geometry update code as part of meldis (towards #16436).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16440)
=> [meshcat] Factor out internal::PointContactVisualizer

tools/workspace/default.bzl, tools/workspace/libcmaes/BUILD.bazel, tools/workspace/libcmaes/dev/BUILD.bazel, tools/workspace/libcmaes/dev/sample_code.cc, tools/workspace/libcmaes/package.BUILD.bazel, tools/workspace/libcmaes/repository.bzl
In the future, we might use this in production, but for getting started we only need it in the sample test.
Closes #16433.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16441)
=> [workspace] Add libcmaes as a testonly dependency

geometry/optimization/BUILD.bazel
Increase `iris_test` shard count from 4 to 12; 4 is not enough to avoid timeouts under memcheck.
Fixes #16459.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16461)
=> iris_test: Run in 12 shards (#16459)

bindings/pydrake/multibody/_plant_extra.py, bindings/pydrake/multibody/test/plant_test.py
Closes #16464.
With manual testing, I've also confirmed that the original `plant_test.py` at 2c567f482b096c6c002bd49a4caa84a034fbe8e3 (prior to any renaming changes) passes, modulo the new warnings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16465)
=> [pydrake] Add deprecation for ContactResultsToMeshcat.AddToBuilder

bindings/pydrake/visualization/meldis.py, bindings/pydrake/visualization/test/meldis_test.py
Without this, very fast simulations tend to clog up the queues and the web view falls far behind.
The [allegro joint control mug demo](https://github.com/RobotLocomotion/drake/blob/master/examples/allegro_hand/joint_control/README.md) when run at maximum speed (a realtime target rate of 0.0) is a particularly acute example.  It's what I suggest to use for local testing.  It was posting draw commands at 2000 Hz (wall clock) for me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16454)
=> [meldis] Use flushing and throttling to keep pace

tools/dynamic_analysis/bazel.rc
The extra bounds-checking in Eigen (etc.) is not very valuable here, but substantially slows down some tests. The extra assertions will still be checked in other CI configurations, just not here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16462)
=> [tools] Disable third-party assertions in memcheck

geometry/proximity/mesh_plane_intersection.cc, geometry/proximity/mesh_plane_intersection.h, geometry/proximity/test/mesh_plane_intersection_test.cc
- This lighter version will be re-used in computing contact surfaces between
two compliant hydroelastic tetrahedral meshes (see #15545).
- For compliant mesh vs. rigid plane, the existing SliceTetWithPlane requires
MeshBuilder template and interpolates field values onto vertices of the
intersected polygon. Here, we create a lighter version without those overhead.
This PR belongs to a multi-PRs strategy (some are rebased on the others), so we'll need to merge them in the right order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16458)
=> Add lightweight version of Tetrahedron/Plane intersection

geometry/proximity/BUILD.bazel, geometry/proximity/hydroelastic_callback.h, geometry/proximity/test/hydroelastic_callback_test.cc, geometry/test/proximity_engine_test.cc, multibody/plant/test/compliant_contact_manager_test.cc
This PR is supposed to rebase on PR #16365.
Once #16365 merges, this PR will change only four files: hydroelastic_callback.h, hydroelastic_callback_test.cc, proximity_engine_test.cc, and compliant_contact_manager_test.cc.  Please do not review other files.
This PR is a part of a multi-PRs strategy. They should merge in a consistent order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16366)
=> [geometry] Hydroelastic callback for compliant-compliant contact.

multibody/models/box.urdf, multibody/plant/BUILD.bazel, multibody/plant/internal_geometry_names.cc, multibody/plant/internal_geometry_names.h, multibody/plant/multibody_plant.cc, multibody/plant/test/internal_geometry_names_test.cc
This takes the information currently retrieved within `ContactResultsToLcmSystem` and changes it into a reusable abstraction.
Future PRs will port the `meshcat::ContactVisualizer` to use this (resolving a TODO) and refactor the `ContactResultsToLcmSystem` to use this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16489)
=> [plant] Add internal::GeometryNames utility

bindings/pydrake/multibody/meshcat_py.cc, multibody/meshcat/contact_visualizer.h
The documentation and template definitions said "nonsymbolic only", but the scalar conversion still accidentally allowed for Expression. Add the opt-out for Expression to the header.
Relatedly, the pydrake bindings had an if-check for Expression, but it was dead code (due to the caller's list of types) so is also removed here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16475)
=> [meshcat] Remove accidental support for Expression

systems/primitives/multilayer_perceptron.cc, systems/primitives/multilayer_perceptron.h
This is a follow-up from the discussion on slack:
- Use a struct for the backprop cache
- Use ValueProducer::NoopCalc
- Set dloss_dY to nans before passing it to the std::function callback.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16468)
=> [primitives] Clean up MultilayerPerceptron implementation

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/contact_results.cc, multibody/plant/contact_results.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/box_test.cc, multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
This enables consumers of the ContactResults to actually understand what the results mean, even in the presence of scalar conversion. Consumers cannot store a long-lived pointer to the MbP on their own, because it will be incorrect any time the Diagram gets rebuilt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16478)
=> [plant] Add MbP back-pointer into ContactResults struct

examples/kinova_jaco_arm/BUILD.bazel, examples/kinova_jaco_arm/jaco_simulation.cc, manipulation/kinova_jaco/jaco_command_receiver.cc, manipulation/kinova_jaco/jaco_command_receiver.h, manipulation/kinova_jaco/test/jaco_command_receiver_test.cc
This mirrors the approach used in IiwaCommandReceiver.
This PR doesn't fully modernize the Jaco LCM classes to mimic the
behavior of the iiwa.  I have a longer-lived development branch for
that effort.  I'm moving this change to it's own commit because it's
needed more urgently.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16483)
=> Make JacoCommandReceiver use an input port for initial position

examples/atlas/urdf/atlas_convex_hull.urdf
Updates Atlas model to avoid spurious collisions with the Hokuyo link.
In particular the "head" vs. "hokuyo_link" collision is annoying because those two links are effectively welded to each other (through a long chain of welded links). This leads to the unnecessary computation of a zero Jacobian which in some cases might cause modeling problems in sim.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16488)
=> Adds missing collision filters to Atlas model.

solvers/scs_solver.cc, tools/workspace/buildifier/repository.bzl, tools/workspace/common_robotics_utilities/repository.bzl, tools/workspace/dm_control/repository.bzl, tools/workspace/googlebenchmark/repository.bzl, tools/workspace/ignition_math/package.BUILD.bazel, tools/workspace/ignition_math/repository.bzl, tools/workspace/ros_xacro/repository.bzl, tools/workspace/scs/repository.bzl, tools/workspace/uwebsockets/repository.bzl, tools/workspace/voxelized_geometry_tools/repository.bzl
Working towards #16481
The changes to scs are from the PR [Under the hood API refactoring](https://github.com/cvxgrp/scs/pull/197). Specifically, see [glbopts.h](https://github.com/cvxgrp/scs/blob/cd4028d024972876883ed3b187076c8ef94062cb/include/glbopts.h#L12)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16484)
=> Upgrade externals to latest releases (Feb 2022)

bindings/pydrake/solvers/mathematicalprogram_py.cc, solvers/mathematical_program.cc, solvers/mathematical_program.h
Resolve #16470 
I have a simple test
```cc
#include "drake/common/symbolic.h"
#include "drake/solvers/mathematical_program.h"
#include <vector>
#include <iostream>
#include <chrono>
namespace drake {
namespace solvers {
int DoMain() {
solvers::MathematicalProgram prog;
const int count = 1000;
auto start1 = std::chrono::high_resolution_clock::now();
for (int i = 0; i < count; ++i) {
prog.NewContinuousVariables(100);
}
auto end1 = std::chrono::high_resolution_clock::now();
std::cout << "takes " << std::chrono::duration_cast<std::chrono::duration<double>>(end1 - start1).count() << " seconds\n";
return 0;
}
}  // namespace solvers
}  // namespace drake
int main() {
drake::solvers::DoMain();
}
```
to add new variables. Before this PR it takes 3.7s to run, with this PR it takes 0.054s, so there …
=> Use std::vector<Variable> instead of VectorX<Variable> for decision_variables_ and indeterminates_ in MathematicalProgram

examples/acrobot/README.md, examples/acrobot/run_lqr.cc, examples/acrobot/run_lqr_w_estimator.cc, examples/acrobot/run_passive.cc, examples/acrobot/run_swing_up.cc, examples/allegro_hand/joint_control/README.md, examples/atlas/atlas_run_dynamics.cc, examples/compass_gait/simulate.cc, examples/kinova_jaco_arm/README.md, examples/kuka_iiwa_arm/README.md, examples/multibody/acrobot/passive_simulation.cc, examples/multibody/acrobot/run_lqr.cc, examples/multibody/cart_pole/cart_pole_passive_simulation.cc, examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc, examples/multibody/four_bar/passive_simulation.cc, examples/multibody/pendulum/passive_simulation.cc, examples/particles/README.md, examples/particles/uniformly_accelerated_particle.cc, examples/planar_gripper/README.md, examples/rimless_wheel/simulate.cc, examples/simple_gripper/README.md, examples/simple_gripper/simple_gripper.cc, multibody/plant/contact_results_to_lcm.h
For now, demos of hydroelastics or demos with camera images remain pinned to drake_visualizer.  Neither `geometry::Meshcat` nor `meldis` support that data (yet).
The problem in #16454 is what motivated some of the "realtime rate = 1.0" changes to README files here.  Some of our examples were running at crazy multiples of realtime, which overloaded the visualizer.  I've already fixed the overloading issue, but I still think it doesn't make sense to run short demos at dozens of multiples of realtime -- they are difficult to watch in that case.
Towards #16216.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16452)
=> [examples] Recommend using meldis where possible

geometry/scene_graph.h, multibody/plant/multibody_plant.h
Closes: #13672
Relevant to: #16422
Write down what we do now, add a clarification and cross-reference to the
SceneGraph docs, and delete some obsolete text.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16490)
=> [multibody] Document default collision filtering

multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/detail_urdf_geometry.h, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_urdf_geometry_test.cc, multibody/parsing/test/urdf_parser_test/two_unnamed_boxes.urdf
Towards #16493.
Here's one specific example of the new names:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16499)
=> [parsing] Stop putting memory addresses into geometry names

multibody/parsing/parsing_doxygen.h, multibody/plant/multibody_plant.h
Detour from: #13314, PR #16444
@amcastro gave a very nice theory lesson on dissipation in a recent PR
discussion. This patch puts that lesson in a (somewhat) reasonable
location.
Also, the patch fixes a bunch of long-festering typos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16517)
=> [doc] Document Hunt and Crossley-inspired dissipation model

common/sorted_pair.h, geometry/meshcat_types.h, multibody/contact_solvers/supernodal_solver.h
Refer to https://drake.mit.edu/doxygen_cxx/namespaces.html to see the leaked namespaces (conex, msgpack) or https://drake.mit.edu/doxygen_cxx/annotated.html to see the leaked classname (integral_constant).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16527)
=> [doc] Remove non-drake namespaces from Doxygen output

doc/_pages/clion.md
A user thought that the instructions were saying that _branches_ had to be named drake. Misuse of the word "checkout" was to blame.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16530)
=> Clarify some text that confused a user

examples/multibody/cassie_benchmark/cassie_v2.urdf
Which previously violated https://www.w3.org/TR/xml/#sec-comments
by containing the string '--'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16536)
=> [examples] Fix a malformed XML comment

systems/primitives/multilayer_perceptron.cc, systems/primitives/multilayer_perceptron.h, systems/primitives/test/multilayer_perceptron_test.cc
These are the defaults used in PyTorch, and I find that they make a
huge difference in practice compared to the random small numbers I had
before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16529)
=> [primitives] Implement LeCun initialization for MultilayerPerceptron

tools/wheel/image/build-drake.sh, tools/wheel/image/dependencies/projects.cmake, tools/wheel/image/dependencies/projects/ipopt.cmake
Add necessary logic to build ipopt in the pip build, and enable it in Drake for the pip build.
Fixes #15971.
+@jwnimmer-tri for feature review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16532)
=> Enable ipopt in pip build

bindings/pydrake/common/test/cpp_template_pybind_test.cc, common/test_utilities/expect_throws_message.h, lcm/test/drake_lcm_interface_test.cc, lcm/test/lcm_messages_test.cc, math/test/roll_pitch_yaw_test.cc, math/test/rotation_matrix_test.cc, tools/vector_gen/test/sample_test.cc
Checking the exception class in `DRAKE_EXPECT_THROWS_MESSAGE` is just asking for trouble, when our [GSG says not to (except very rarely)](https://drake.mit.edu/styleguide/cppguide.html#Exceptions).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16514)
=> [test_utilities] Deprecate checking the specific exception subtype

tools/macos.bazelrc
Relates: https://github.com/RobotLocomotion/drake-ci/pull/135
Originally came up as [nightly mac debug build issues discussed on slack](https://drakedevelopers.slack.com/archives/C270MN28G/p1644330592185029).
Adding CI jobs to see if this will resolve us.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16546)
=> WIP [workspace] fix macOS bazel 5 builds

geometry/proximity_properties.h, multibody/parsing/parsing_doxygen.h
Closes: #15743
The module ... it is written.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16549)
=> [doc,geometry,multibody] Add refs to Hydroelastic User Guide

tools/dynamic_analysis/tsan.supp
Something is causing TSAN to report a data race whenever a `vtkNew<vtkRenderWindow>` is destroyed. As the cause is not clear at this time, suppress the warning for now so CI does not fail.
See also #16494.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16544)
=> Suppress vtkRenderWindow TSAN warning

geometry/render/dev/render_client.cc, geometry/render/dev/render_client.h, geometry/render/dev/render_client_gltf.cc, geometry/render/dev/render_client_gltf.h, geometry/render/dev/render_client_gltf_factory.h, geometry/render/dev/render_server/README.md, geometry/render/dev/render_server/gltf_render_server.py
- Remove `upload_endpoint_` and related fields from `RenderClient`,
`RenderClientGltf`, and `RenderClientGltfParams`.
- Rename `RenderClient` method `RetrieveRender` to `RenderOnServer`, simplify
parameters.
- Render server API updates:
- `<input type="file">` form field `data` renamed to `scene`.
- Field `id` renamed to `scene_sha256`.
- Added additional documentation on README about the relationship between
`"cameras"` and `"nodes"` arrays in the glTF specification.
- Render server implementation updates:
- Only implement one endpoint for the client, /render.
- Introduce `RenderRequest` and related helper classes / methods to simplify
`<form>` validation code-reuse.
- `RenderError` is the preferred form of communicating any problems.
- Add `NO_CLEANUP` developer switch, make all other …
=> [geometry/dev] Only use one endpoint between the client and server.

bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py
The example cannot run correctly if the reference is not stored.
`bazel run //bindings/pydrake/examples/multibody:run_planar_scenegraph_visualizer -- -m manip -T 10 -p true` (don't need `-T 10`, it's the `manip` and `-p true` that will make you crash without this change).
Found this by accident shopping for an example to test some unrelated changes.  Byproduct of https://github.com/RobotLocomotion/drake/pull/15456 according to the blame.
I don't think this needs a feature review, or at least, not sure who to add.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16559)
=> [pydrake/examples] store visualizer return for args.playback

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py, math/rigid_transform.h, math/rotation_matrix.h, math/test/rigid_transform_test.cc, math/test/rotation_matrix_test.cc
Resolves issue #16551
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16552)
=> Replace RotationMatrix::IsIdentityToInternalTolerance() with RotationMatrix::IsNearlyIdentity().

doc/_pages/jenkins.md, tools/dynamic_analysis/drd.sh, tools/dynamic_analysis/helgrind.sh, tools/dynamic_analysis/valgrind.sh
Update valgrind wrapper scripts to account for the name of the distro-provided Python suppressions file changing between Bionic and Focal. Update Jenkins job name in documentation.
See also #14928. Supersedes #16223.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16557)
=> Update valgrind builds to use Focal

bindings/pydrake/examples/multibody/BUILD.bazel
Closes #11303.
This doesn't fail-fast in case a future developer ever tries to install a `py_binary` again, but _shrug_.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16583)
=> [pydrake] Stop installing useless bazel py_binary stubs

doc/_pages/bazel.md, doc/_pages/from_source.md
More clearly distinguish examples (bazel run) from tests (bazel test). Update links to Bazel's documentation to avoid extra re-directions.
Also fix an (somewhat unrelated) reference to prefer Focal, not Bionic, for local development.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16588)
=> [doc] Clarify instructions for Bazel running with flags

doc/_pages/installation.md, doc/_pages/reviewable.md, doc/_pages/stable.md
Closes #16159.
The goal here is to lay out what is _incumbent_ upon Drake PR's to preserve, so as to remove impediments and friction from the development process.  (In recent cases, there has been doubt about the policy.)
Nothing here should be read as _preventing_ developers from going above and beyond the requirements written down here.
As a reminder, per https://drake.mit.edu/documentation_instructions.html you can preview this locally via:
```
git fetch upstream pull/16547/head && git checkout FETCH_HEAD
bazel run //doc:pages -- --serve
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16547)
=> [doc] Add stability policy

doc/_pages/apt.md, doc/_pages/bazel.md, doc/_pages/docker.md, doc/_pages/from_binary.md, doc/_pages/from_source.md, doc/_pages/installation.md, doc/_pages/pip.md, doc/_pages/tm.md, doc/_release-notes/v0.13.0.md, doc/_release-notes/v0.25.0.md, doc/_release-notes/v0.26.0.md, doc/_release-notes/v0.39.0.md, doc/defs.py, doc/doxygen_cxx/build.py, doc/pages.py, doc/pydrake/build.py, solvers/constraint.h, solvers/mathematical_program.h, solvers/mathematical_program_doxygen.h, solvers/mathematical_program_result.h, solvers/mosek_solver.h, solvers/solver_options.h, tools/bazel.rc, tools/install/check_licenses.bzl, tools/jupyter/jupyter_bazel.py, tools/skylark/test_tags.bzl, tools/workspace/mosek/repository.bzl, tutorials/linear_program.ipynb, tutorials/quadratic_program.ipynb
This changes Drake's published documentation and API help to follow the preferred trademark spelling. Various buried mentions in our private source files are unchanged.
For the website, automatically hyperlink ™ to a trademarks page.
Towards #16439.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16576)
=> [doc] Use ™ on MOSEK and always capitalize it

doc/defs.py, doc/pages.py
Prior to this fix, on Jekyll on Ubuntu 20 would preserve the symlinks back into the source tree when populating its --out_dir, which meant that we were failing to push those resources into git, and our GitHub Pages deployments were failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16598)
=> [doc] Fix Jekyll output to avoid symlinks

multibody/parsing/detail_common.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/collision_filter_group_parsing_test.sdf, multibody/parsing/test/urdf_parser_test/collision_filter_group_parsing_test.urdf
Closes: #16310
Previously, a typo'd element name caused only the first element of
`drake:ignored_collision_filter_group` within a group to be actually
processed.  This patch fixes the typo and extends the existing tests to
cover the error case. Regrettably, it does not attempt a more vigorous
test refactoring. That may happen in the near future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16594)
=> [parsing] Fix mis-parse of collision filter groups

multibody/hydroelastics/hydroelastic_user_guide_doxygen.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_config.h, multibody/plant/test/multibody_plant_hydroelastic_test.cc
Related to #16565 
- Switch the default contact model from point contact to hydroelastic with
fallback.
- The fallback to point contact happens between two rigid-hydroelastic
collision geometries. It also happens when one or both of the two
contacting geometries is non-hydroelastic.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16569)
=> [multibody] By default, use hydroelastic contact with fallback.

examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc, geometry/query_object.cc, geometry/query_object.h, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/scene_graph_inspector.cc, geometry/scene_graph_inspector.h, geometry/test/drake_visualizer_test.cc, geometry/test/query_object_test.cc, geometry/test/scene_graph_inspector_test.cc, geometry/test/scene_graph_test.cc, multibody/contact_solvers/test/multibody_sim_driver.cc, multibody/hydroelastics/hydroelastic_engine.cc, multibody/hydroelastics/test/hydroelastic_engine_test.cc, multibody/plant/compliant_contact_manager.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/multibody_plant_hydroelastic_test.cc, multibody/plant/test/multibody_plant_test.cc
It brings in many other header files (e.g., proximity engine) that would not typically be used by users of the model inspector, multibody plant, etc., and thus leads to bloated compile times (approximately 0.5 seconds per TU).
Move some overly-inlined code from h to cc files to match.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16591)
=> [geometry] Don't include geometry_state.h publicly

tools/install/check_licenses.bzl, tools/workspace/BUILD.bazel
Hotfix for #16185 on macOS.
Manually tested the linter:
Manually tested the lack-of-build failure now:
Closes #16612.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16613)
=> [workspace] Nerf the license checker for jar files

multibody/parsing/BUILD.bazel, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/detail_mujoco_parser.h, multibody/parsing/detail_scene_graph.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_sdf_parser.h, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/detail_urdf_parser.h, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc
Stop passing around scene graph everywhere internally. Instead, rely on
Parser to register the plant to the scene graph (if any). None of the
deeper parse modules actually need a scene graph; they instead condition
some behavior on the result of the is_registered() predicate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16608)
=> [parsing] Simplify use of scene graph in parsing

tools/wheel/image/packages-bionic, tools/wheel/image/packages-focal
The Bazel build requires that these be present in its workspace, but none of the files that end up in the wheel actually use this.
Hotfix for #16185, which added these to `drake/setup/ubuntu/...` for forgot to mimic that in the wheel prereqs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16614)
=> [wheel] Hotfix to add now-missing jchart2d dependency

systems/framework/cache_entry.h, systems/framework/context_base.h, systems/framework/test/diagram_context_test.cc
Allows cache dependency sweeps to be initiated on a const Context.
Resolves #16579
I won't attempt to add new sugar methods until we're sure we need them, but this change allows a determined programmer to get the job done.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16619)
=> Allow start_new_change_event() on const Context

geometry/proximity/BUILD.bazel, geometry/proximity/test/volume_mesh_test.cc, geometry/proximity/volume_mesh.cc, geometry/proximity/volume_mesh.h, multibody/fixed_fem/dev/mesh_utilities.cc
This is the first of the PR train to move some of the geometry utilities out of fem/dev and into geometry namespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16603)
=> [geometry] Add in place transform for volume mesh

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/cartesian_product.cc, geometry/optimization/cartesian_product.h, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/minkowski_sum.cc, geometry/optimization/minkowski_sum.h, geometry/optimization/point.cc, geometry/optimization/point.h, geometry/optimization/test/cartesian_product_test.cc, geometry/optimization/test/graph_of_convex_sets_test.cc, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/hyperellipsoid_test.cc, geometry/optimization/test/minkowski_sum_test.cc, geometry/optimization/test/point_test.cc, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16397)
=> [geometry/optimization] Add two-cycle constraint to Shortest Path formulation

bindings/pydrake/common/type_safe_index_pybind.h, bindings/pydrake/systems/test/controllers_test.py
Previously, running `type_safe_index_pybind_test` produced the following deprecation warning:
```
[  PASSED  ] 1 test.
<string>:2: DeprecationWarning: an integer is required (got type __main__.Index).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
Target //bindings/pydrake/common:py/type_safe_index_pybind_test up-to-date:
bazel-bin/bindings/pydrake/common/py/type_safe_index_pybind_test
```
In #16611, @jwnimmer-tri proposed that binding __index__ would be a
better solution, and notes that "As of Python 3.8, we could bind only
the `__index__` method (and drop the `__int__` binding) since
`__int__` automatically falls back to `__index__`. However, in Python
3.6 there is no fallback, so we need to have both methods bound for …
=> [pydrake/common] Bind __index__ for TypeSafeIndex

bindings/pydrake/common/module_py.cc, bindings/pydrake/common/test/module_test.py, common/BUILD.bazel, common/random.cc, common/random.h, common/test/random_test.cc
Copying 5000 bytes of storage during a move is wasteful; better to just swap a heap pointer.
Calculating 624 random integers in the default constructor is wasteful, if we're only trying to allocate a storage for generator that will be moved into later (e.g., when resizing a collection of generators):
https://github.com/RobotLocomotion/drake/blob/6e0c78de480f9f6fec4d3ad0448d77f20259cf08/systems/analysis/monte_carlo.cc#L47-L52
Towards #16606.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16633)
=> [common] Give RandomGenerator efficient default and move constructors

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, bindings/pydrake/solvers/mathematicalprogram_py.cc, multibody/inverse_kinematics/position_constraint.h, multibody/inverse_kinematics/test/position_constraint_test.cc, solvers/constraint.h
As requested in stackoverflow question https://stackoverflow.com/questions/71157985/how-to-update-bound-of-positionconstraint
I will add the constraint to update other kinematic constraints, these constraints are more complicated as their upper and lower bounds are computed from the kinematic parameter (like angle tolerance), so instead of using UpdateLower/UpperConstraint function, I will probably add `UpdateAngleTolerance` for example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16631)
=> PositionConstraint can update lower and upper bounds

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
Enables passing `SolverOptions` to `SolveShortestPath` in `GraphOfConvexSets`.  Also cleans up a little code formatting in the same pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16616)
=> [geometry/optimization] Add optional solver and solver options to SolveShortestPath

bindings/pydrake/geometry_py_visualizers.cc, bindings/pydrake/test/geometry_visualizers_test.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat.html, geometry/test/meshcat_test.cc
Change unknown URLs to return empty, instead of random HTML.
When connecting from JavaScript, retain the sub-directory name (if any) from the http URL.
Towards #16639.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16638)
=> [geometry] Add URL customization to Meshcat ctor

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py
Add the ability to pickle the basic convex sets to enable their use in multi-processed python code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16628)
=> [pydrake/geometry] Make ConvexSets picklable

tools/dynamic_analysis/bazel.rc
Fix some `build:asan` that were clearly meant to be `build:asan_everything`, as they appear in this section and are otherwise redundant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16646)
=> Fix asan_everything config

systems/analysis/monte_carlo.cc, systems/analysis/monte_carlo.h
This is in preparation for more substantial rework in the future (#16606).
Header:
- Add readability whitespace.
- Move file internal declarations to the bottom, out of the way.
- Re-fill comment paragraph for the allowed space.
- Remove suggestion of using operator<< on the RNG; there is no such thing.
- Fix GSG verb tense.
Implementation:
- Move canonical function (RandomSimulation) to the top of the file. Everything else in the file is just more ornamental versions of this one.
- Move utility function (IsFutureReady) to its point of use.
- Add bonus consts to definitions, to help reason about data races.
- Use num_threads vs num_parallel_executions language consistently.
- Clarify a couple implementation walk-through comments.
--- …
=> [analysis] Tidy up monte_carlo implementation

geometry/geometry_set.h
Closes: #16648
Apparently closing the comment on the same line as other directives (end
of a literal block in this case) confuses the doxygen parser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16651)
=> [geometry] Fix a doxygen doc bug

multibody/parsing/BUILD.bazel, multibody/parsing/detail_parsing_workspace.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/detail_urdf_parser.h, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/test/detail_urdf_parser_test.cc
This patch sets up some of the infrastructure for a centralized
diagnostic policy, also performs some long-languishing cleanups on the
URDF parser tests.
There should be no change in functionality (yet); future patches will
port messages to the policy, and allow API control of it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16650)
=> [parsing] Introduce parsing workspace

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/parser.h, multibody/parsing/test/parser_test.cc
This might be convenient when re-using the same Parser across an entire simulation setup, even when adding models by hand (i.e., #15804).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16655)
=> [multibody] Add plant getter to Parser

systems/analysis/simulator_gflags.cc
The user may want to alter the context before starting the simulation.
(No release notes, because this header file is private to Drake.)
Towards #15804.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16657)
=> [analysis] Don't Initialize during MakeSimulatorFromGflags

bindings/pydrake/geometry_py_visualizers.cc, bindings/pydrake/test/geometry_visualizers_test.py, bindings/pydrake/visualization/meldis.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_test.cc
The default remains to bind to "*".
Update meldis to only serve on localhost by default.
This provides the option to the user to decide where to bind.  I'd like to get this out there ASAP, so that in the future we can deprecate binding to "*" by default, giving users a smooth transition path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16654)
=> [geometry] Add host name option to MeshcatParams

bindings/pydrake/test/geometry_visualizers_test.py
Hotfix for #16654.  Apparently on macOS you can bind to the same port number on `localhost` and `*` and that's not an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16660)
=> [pydrake] Hotfix unit test for localhost vs *

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py
For expected parity between C++ and Python
C++ has default:
https://github.com/RobotLocomotion/drake/blob/4181a9ab633bbf683f463811fb7fed4d0b73b0f9/math/rotation_matrix.h#L569-L570
Minor omission in #16541 (\cc @mitiguy)
Relates Anzu PR 8468 (to fix deprecation of `.IsIdentityToInternalTolerance()`)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16661)
=> py math: Fix missing default for RotationMatrix.IsNearlyIdentity()

geometry/meshcat.cc
Follow-up from #16664.  This is in anticipation of adding thread-shutdown guards (#16659).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16667)
=> [geometry] Centralize Meshcat's checks for a null loop

setup/mac/install_prereqs.sh, setup/ubuntu/install_prereqs.sh
Array expansion should be fine as-is for empty case
Adding `:-` means it will expand to quoted form for one argument,
which is incorrect
---
Was futzing w/ Anzu stuff (PR 8471), cargo culted from here, then realized there might be an issue.
For example expansion:
https://gist.github.com/EricCousineau-TRI/c3c074de657d063b772c9fa9b355319f
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16666)
=> Replace `"${var[@]:-}"` with `"${var[@]}"`

setup/mac/install_prereqs.sh
Reverts RobotLocomotion/drake#16666
Dear @EricCousineau-TRI 
The on-call build cop, @svenevs , believes that your PR #16666 may have
- https://drake-jenkins.csail.mit.edu/job/mac-big-sur-unprovisioned-clang-bazel-continuous-snopt-packaging/1233/consoleFull
- `/Users/bigsur/workspace/mac-big-sur-unprovisioned-clang-bazel-continuous-snopt-packaging/src/setup/mac/install_prereqs.sh: line 40: binary_distribution_args[@]: unbound variable`
- Alternative to reverting could be to guarantee this variable is at least created as an empty array? …
=> Partially revert "Replace `"${var[@]:-}"` with `"${var[@]}"`"

geometry/meshcat.cc, geometry/meshcat.h
Having functions implementations on both the inner class and outer class is too difficult to maintain.
Towards #16670.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16681)
=> [geometry] Refactor Meshcat to strictly obey PIMPL

tools/install/dockerhub/focal/Dockerfile
In original commit (#16639), we didn't notice that the Docker Hub deployment process was undoing our good works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16658)
=> [pydrake] Add missing config files for MeshCat proxy on Deepnote

geometry/meshcat.cc, geometry/meshcat.h
The inner class has outgrown WebSocketPublisher, so is renamed to Impl per the usual pattern.
Outer class access to Impl is done through accessors for const correctness. This also paves the way for a future commit to mix in lifetime checks while accessing the Impl (in #16670).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16682)
=> [geometry] Rename Meshcat::Impl and use const-correct accessors

multibody/parsing/detail_common.cc, multibody/parsing/detail_common.h, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/detail_path_utils.cc, multibody/parsing/detail_path_utils.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/parser.cc, multibody/parsing/test/detail_common_test.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/parsing/test/detail_path_utils_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_geometry_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/parser_test.cc
Get rid of redundant hidden calculations of root_dir in sub-parsers.
Instead, add some path-like operations to DataSource, implemented with
drake::filesystem, and port to those. Remove some old string-fiddly path
operations.
In particular, this patch gets rid of the comingling of path algebra
with existence checking. The underlying XML parsers will report file
non-existence instead.
Also, this patch makes (somewhat) official the pseudo-filename already
in use for file_contents data sources: "<literal-string>". This will
allow diagnostics issued against such sources to be more consistent.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16677)
=> [parsing] Clean up some path handling

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/partial_permutation.cc, multibody/contact_solvers/sap/partial_permutation.h, multibody/contact_solvers/sap/test/partial_permutation_test.cc
We need to shuffle indexes back and forth as we permute cliques, velocities and impulses in #16543. 
Therefore this class encapsulates the concept of a (partial) permutation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16596)
=> Introduces PartialPermutation

examples/hydroelastic/ball_plate/ball_plate_run_dynamics.cc, examples/mass_spring_cloth/run_cloth_spring_model.cc, examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc, systems/analysis/simulator_gflags.cc, systems/analysis/simulator_gflags.h, systems/analysis/test/simulator_gflags_main.cc
It has Drake-only package visibility, is not installed, and therefore is unavailable to end users. As such, we don't want it [showing up in Doxygen](https://drake.mit.edu/doxygen_cxx/namespacedrake_1_1systems.html#a0a6e4906135fe23f2a8f8f9cd68f3385).
Follow-up from discussions in #16657.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16671)
=> [systems] Mark simulator_gflags as internal

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, multibody/inverse_kinematics/test/global_inverse_kinematics_reachable_test.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_test.cc, solvers/BUILD.bazel, solvers/gurobi_solver.cc, solvers/solution_result.cc, solvers/solution_result.h, solvers/test/diagonally_dominant_matrix_test.cc, solvers/test/gurobi_solver_test.cc, solvers/test/mathematical_program_result_test.cc, solvers/test/mixed_integer_rotation_constraint_test.cc, solvers/test/non_convex_optimization_util_test.cc, solvers/test/scaled_diagonally_dominant_matrix_test.cc
Also bind MathematicalProgramResult.set_solution_result.
The old name is deprecated.  Uses of the old name are rectified.
One test is added to ensure old code still compiles.
The bindings are updated likewise.  However we also
bind set_solution_result in order to test these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16688)
=> Fix noncompliant name kInfeasible_Or_Unbounded

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
Linear costs should be valid when other constraints ensure they don't go negative.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16680)
=> [geometry/optimization] Enable linear costs in GraphOfConvexSets

BUILD.bazel, CMakeLists.txt, cmake/external/workspace/fmt/BUILD.bazel.in, cmake/external/workspace/spdlog/BUILD.bazel.in, tools/workspace/cmake_util.bzl
Add logic (only when using the CMake wrapper) to allow the user to select and use external version(s) of fmt and/or spdlog.
Fixes #15815.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16652)
=> Allow external fmt, spdlog

CMakeLists.txt, cmake/external/workspace/eigen/BUILD.bazel.in
Add logic (only when using the CMake wrapper) to allow the user to select and use an external version of Eigen3.
Fixes #16693.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16700)
=> Allow external Eigen3

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/contact_problem_graph.cc, multibody/contact_solvers/sap/contact_problem_graph.h, multibody/contact_solvers/sap/partial_permutation.cc, multibody/contact_solvers/sap/partial_permutation.h, multibody/contact_solvers/sap/test/contact_problem_graph_test.cc, multibody/contact_solvers/sap/test/partial_permutation_test.cc
This PR updates ContactProblemGraph so that it can provide the permutation to participating cliques.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16694)
=> [SAP] ContactProblemGraph provides participating cliques

multibody/plant/multibody_plant.h
I should have done this in #16569.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16705)
=> [multibody] Correct documentation of default set_contact_model()

geometry/meshcat.cc, geometry/test/meshcat_test.cc, geometry/test/meshcat_websocket_client.py
Improve unit test tooling to tickle this kind of bug.
```console
jwnimmer@call-cps:~/jwnimmer-tri/drake$ bazel-bin/geometry/meshcat_test --spdlog_level=debug --gtest_filter='*Ignored*' 2>&1 | grep -i 'ignored'
Note: Google Test filter = *Ignored*
[ RUN      ] MeshcatTest.UnparseableMessageIgnored
[2022-03-02 20:56:49.223] [console] [debug] Meshcat ignored an unparseable message
[       OK ] MeshcatTest.UnparseableMessageIgnored (240 ms)
[ RUN      ] MeshcatTest.UnknownEventIgnored
[2022-03-02 20:56:49.463] [console] [warning] Meshcat ignored a 'no_such_type' event
[       OK ] MeshcatTest.UnknownEventIgnored (241 ms)
```
Using `kcov`, also this shows an improvement in statement coverage from the unit test.
One more step towards #16659.
--- …
=> [geometry] Fix Meshcat crash on unknown message

tools/wheel/image/provision-python.sh
Because the Dockerfile will cache based on the contents of these files only, and not the state of the internet hosts, we run the risk of security versions disappearing between the cached provision-base step and a new provision-python, resulting in the inability to build.
We must maintain the invariant that any shell script with 'apt-get install' must always do 'apt-get update' first.
+@mwoehlke-kitware for feature review, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16707)
=> [wheel] Add missing apt-get update

common/symbolic_latex.cc, common/test/symbolic_latex_test.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16720)
=> [symbolic] ToLatex displays matrix/vector variables using subscript for indices

systems/analysis/BUILD.bazel, systems/analysis/region_of_attraction.cc, systems/analysis/region_of_attraction.h, systems/analysis/test/region_of_attraction_test.cc
This PR moves one step closer to support RegionOfAttraction analysis
of MultibodyPlant systems. MultibodyPlant systems introduce two
additional complexities: (1) the dynamics are trigonometric +
polynomial, and (2) the dynamics are rational.  This PR adds support
for (2).  Support for (1) will come in the follow-up, incorporating #16690.
+@hongkai-dai for feature review
+@shensquared for additional feature review, if you're available
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16704)
=> [systems/analysis] Implements RegionOfAttraction for implicit dynamics

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/schema_py.cc, bindings/pydrake/common/test/schema_test.py, bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/analysis_test.py
Add bindings for functions that operate on them: `AddMultibodyPlant`, `ApplySimulatorConfig`, `ExtractSimulatorConfig`.
Use `DefAttributesUsingSerialize` in `pydrake.common.schema` for consistency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16717)
=> [pydrake] Add bindings for SimulatorConfig, MultibodyPlantConfig

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/test/text_logging_gil_test.py, bindings/pydrake/common/test/text_logging_test_py.cc, bindings/pydrake/common/text_logging_pybind.cc
To avoid lock order inversion, we must avoid using any mutexes in the spdlog code paths; instead we should grab the GIL once we've reached the Python sink.
This means that users will not be able to log to both a C++ sink and Python sink anymore. Users who want to do so can configure logging on their own, in which case Drake's logging reconfiguration will leave it unchanged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16724)
=> [pydrake] Ensure GIL is locked when logging from a C++ worker thread

geometry/meshcat.cc
Follow-up from #16670.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16695)
=> [geometry] Denote the Meshcat worker thread's lifecycle with an enum

multibody/tree/multibody_tree_indexes.h, multibody/tree/multibody_tree_topology.h, multibody/tree/test/multibody_tree_creation_test.cc
The topology of a multibody system can be seen as a "forest of trees", where the base of each of these trees is a child of the world (the root of the tree). This PR augments `MultibodyTreeTopology` with information regarding this forest structure.
Note: Our discrete update manager will use this information to build a `SapContactProblem` encoding this forest structure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16725)
=> MultibodyTreeTopology provides per-tree information.

geometry/render/dev/BUILD.bazel, geometry/render/dev/http_service.cc, geometry/render/dev/http_service.h, geometry/render/dev/test/http_service_test.cc
The HttpService interface serves as the primary mechanism for
facilitating client / server communications.  A given RenderClient
will maintain an HttpService for the lifetime of the application.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16702)
=> [geometry/dev] introduce HttpService helper interface

geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_test.cc
When asked to add a control with a duplicate name, throw an exception instead of trying to implicitly delete the existing control.
Deleting the existing control never worked anyway; it was checking for duplicates using the moved-from name, which was always empty. This led to duplicate names in the controls_ vector, and then segfaults.
Add more internal assertions that the controls_ vector is congruent with the buttons_ and sliders_ vectors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16726)
=> [geometry] Fix Meshcat crash with duplicated controls names

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/detail_urdf_parser.h, multibody/parsing/parser.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/parser_test.cc
This patch takes just the shallowest cut at porting URDF diagnostic
messages to use the diagnostic policy object; only two error messages
are ported.
It does introduce some necessary formatting machinery (which might be
useful elsewhere later?), and updates affected test clauses.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16687)
=> [parsing] Port URDF diagnostics to policy: first steps

common/test/trig_poly_test.cc, common/trig_poly.h, solvers/system_identification.cc, solvers/system_identification.h, solvers/test/system_identification_test.cc
Our symbolic::Expression can do this work, too, now, and with
Expression we can process trigonometric polynomials directly from
MultibodyPlant.
+@ggould-tri for feature review, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16741)
=> [common] Deprecate TrigPoly

tools/jupyter/jupyter_bazel.py, tools/jupyter/jupyter_py.bzl
Derived from Anzu PR 8537
Another thing to keep in mind (in background) is https://github.com/jupyter-server/jupyter_server/issues/711
Not important as we don't (can't?) currently use `jupyter lab`, but may be relevant then.
Also, using workaround, calling `jupyter notebook $(realpath ${notebook_path})`, is nice for UX. Not sure if we care about that yet in Drake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16740)
=> jupyter: Pull in minor Bazel improvements

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
This is a pre-requisite to remove the `scipy.spatial.ConvexHull` dependency.
Related to #14691
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16729)
=> Add ability to create a VPolytope from a non-minimal set of vertices

CMakeLists.txt
Fixes error in introduced in #16587.
Failing CI builds:
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-clang-cmake-continuous-debug/4666/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-gcc-cmake-continuous-debug/4668/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-focal-clang-cmake-continuous-debug/1378/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-focal-gcc-cmake-continuous-debug/1379/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16767)
=> CMake: --fission needs to be a build argument

geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_test.cc, geometry/test/meshcat_websocket_client.py
Without this, exceptions that leak back to `std::thread` end up in `std::terminate` and usually won't show up for Python.
With this, exceptions will be logged immediately and any additional calls on the Meshcat object will throw an exception.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16659)
=> [geometry] Be sure to print exceptions from Meshcat's worker thread

multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc
I thought I'd only remove this dead comment. But I realized that specifying smoothness when using SCS should have no effect and therefore I removed it. Would you confirm @hongkai-dai?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16777)
=> Removes unnecessary cone constraint smoothness specification

multibody/parsing/BUILD.bazel, multibody/parsing/detail_tinyxml2_diagnostic.cc, multibody/parsing/detail_tinyxml2_diagnostic.h, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_tinyxml2_diagnostic_test.cc
Split out the TinyXml2Diagnostic class, to make it available for use in
detail_urdf_geometry, and possibly elsewhere.
* split out class
* divide into header and cc file
* add tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16770)
=> [parsing] Split TinyXml2Diagnostic to its own module

geometry/render/dev/BUILD.bazel, geometry/render/dev/http_service.cc, geometry/render/dev/http_service.h, geometry/render/dev/http_service_curl.cc, geometry/render/dev/http_service_curl.h, geometry/render/dev/test/http_service_curl_test.cc, geometry/render/dev/test/http_service_test.cc
Related to the [temp directory cloning discussion](https://drakedevelopers.slack.com/archives/C02HMU7B15Y/p1647031224056499) [TL;DR: get rid of state here and disable cloning, copy, move, assign for `HttpService` and `RenderClient`].
Doing as a separate PR for bikeshedding purposes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16776)
=> [geometry/dev] make HttpService stateless

tools/ubuntu-bionic.bazelrc
This partially reverts cdd6652095c356f9c48b49fde60fbe392e465960 (https://github.com/RobotLocomotion/drake/pull/16587).
Build times for Release builds were substantially bloated as of that change, because fission turns on `-g`.  We should only do that in `-c dbg` builds.
The [linux-focal-unprovisioned-gcc-bazel-continuous-release build 2506](https://drake-jenkins.csail.mit.edu/view/Unprovisioned/job/linux-focal-unprovisioned-gcc-bazel-continuous-release/2506/) pretty clearly shows a 50% slowdown exactly when this commit landed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16788)
=> [tools] Don't enable (split) debug symbols in release builds

geometry/render/dev/BUILD.bazel, geometry/render/dev/render_client.cc, geometry/render/dev/render_client.h, geometry/render/dev/render_engine_gltf_client.cc, geometry/render/dev/render_engine_gltf_client.h, geometry/render/dev/test/render_client_test.cc, geometry/render/dev/test_utilities/BUILD.bazel, geometry/render/dev/test_utilities/test_png.cc, geometry/render/dev/test_utilities/test_png.h, geometry/render/dev/test_utilities/test_tiff.cc, geometry/render/dev/test_utilities/test_tiff.h
- RenderEngineGltfClient now has a RenderClient data member rather than multiple inheritance.
- RenderClient uses an HttpService data member to facilitate RenderOnServer interactions.  Default behavior is to create an HttpServiceCurl instance.
- Most code removed from RenderClient was previously added to HttpServiceCurl.
- RenderClient is the owner of the temp_directory(), but it is shared across clones, RenderEngineGltfClient, and HttpService.
- Add tests for RenderClient.
TODO:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16751)
=> [geometry/dev] Use new HttpService Interface with GLTF

bindings/pydrake/solvers/mathematicalprogram_py.cc, solvers/create_constraint.cc, solvers/create_constraint.h, solvers/mathematical_program.cc, solvers/mathematical_program.h
A single overload is sufficient for both `Matrix<Formula>` or `Array<Formula>`. This reduces documentation and maintenance burden.
Remove two dead private helper functions on `MathematicalProgram` (for `std::set`).
Similarly, combine the `internal::ParseConstraint` overloads and move the remaining implementation into cc file per GSG.  Note that the diffs here area not great, because it's the overload definition from the header file that still survives (now in the cc file).
Towards #16761.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16778)
=> [solvers] Combine MathematicalProgram::AddConstraint overloads

multibody/parsing/detail_common.cc, multibody/parsing/test/detail_common_test.cc
The deprecation began during the "hydro is experimental" period, so
wasn't done formally with announcements in release notes, etc. However,
the advertised deprecation period has elapsed. It can go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16786)
=> [parsing] Remove deprecated `drake:elastic_modulus`

multibody/parsing/detail_common.h, multibody/parsing/detail_sdf_geometry.cc, multibody/parsing/detail_sdf_geometry.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_geometry_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, tools/workspace/sdformat/package.BUILD.bazel, tools/workspace/sdformat/patches/no_urdf.patch, tools/workspace/sdformat/repository.bzl
Drake has its own URDF parser that we must always use, so we should disable libsdformat's automatic transmogrification of URDF files into SDFormat files.
Don't generate `sdf/sdf.hh`; it's only effect is IWYU violations.
Towards #12610.
+@EricCousineau-TRI for platform review (as SME), please.
Should we have anyone from OpenRobotics take a look here as well?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16772)
=> [workspace] Don't build libsdformat's URDF parser

multibody/contact_solvers/sap/BUILD.bazel, tools/install/libdrake/build_components.bzl
This fixes an omission from 8b96d899578e5d7f2059e9a991ecc9e4b1a393ea (#16437).
Also add an SAP solver package_library, to de-chaff the install list.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16789)
=> [multibody] Install deprecated contact_results_to_meshcat.h header

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_geometry_test.cc, tools/workspace/sdformat/patches/fix_broken_config.patch, tools/workspace/sdformat/patches/no_global_config.patch, tools/workspace/sdformat/repository.bzl
This ensures that our parsing configuration is always what we asked for.
A related issue has been filed upstream as https://github.com/ignitionrobotics/sdformat/issues/881.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16791)
=> [parsing] Stop using mutable globals

common/yaml/BUILD.bazel, common/yaml/test/yaml_io_test.cc, common/yaml/test/yaml_performance_test.cc, common/yaml/test/yaml_read_archive_test.cc, common/yaml/yaml_io.h, common/yaml/yaml_io_options.cc, common/yaml/yaml_io_options.h, common/yaml/yaml_read_archive.cc, common/yaml/yaml_read_archive.h
This is cleaner for users, and is a prerequisite of moving the archive classes to an internal namespace.
Towards #16706.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16801)
=> [yaml] Extract Options struct out of YamlReadArchive

multibody/parsing/BUILD.bazel, multibody/parsing/detail_common.cc, multibody/parsing/detail_common.h, multibody/parsing/detail_sdf_geometry.cc, multibody/parsing/detail_sdf_geometry.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/test/detail_common_test.cc, multibody/parsing/test/detail_sdf_geometry_test.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16810)
=> [parsing] Use DiagnosticPolicy instead of log_once in SDFormat

multibody/parsing/detail_common.cc, multibody/parsing/detail_common.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc
This refactoring clears the way for any implementation of parsing errors
that is not `throw`. In this case, the change in signatures is justified
by the difficulty of constructing Frame objects.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16821)
=> [parsing] Allow linear bushing parse to fail

tools/release_engineering/dev/BUILD.bazel, tools/release_engineering/dev/debian/changelog.in, tools/release_engineering/dev/debian/control, tools/release_engineering/dev/debian/copyright, tools/release_engineering/dev/repack_deb.py
Towards #16448.
The plan is to nuke https://github.com/RobotLocomotion/debian-drake and replace it with this small Python script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16602)
=> [release_engineering] Add a tool to convert tgz => deb

LICENSE.TXT
Happened to notice this while inspecting release tooling development stuff.  Maybe we should configure a reminder on slack or a GH action to update this each year?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16823)
=> update license year

geometry/render/dev/http_service.h, geometry/render/dev/http_service_curl.cc, geometry/render/dev/http_service_curl.h, geometry/render/dev/render_client.cc, geometry/render/dev/render_client.h, geometry/render/dev/render_engine_gltf_client_factory.h, geometry/render/dev/test/http_service_curl_test.cc, geometry/render/dev/test/http_service_test.cc, geometry/render/dev/test/render_client_test.cc, geometry/render/dev/test/render_engine_gltf_client_test.cc
Per discussion in Slack-
- Replace comment openers `/**` with `/*` for all the internal classes.
- Replace `int32_t` with `int` for `http_code` and `port` variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16827)
=> Change comment openers and replace int32_t with int

solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc, systems/trajectory_optimization/test/multiple_shooting_test.cc
Remove unnecessary templating.
Move function definitions to cc file.
Use fmt instead of stringstream.
Use logic_error instead of runtime_error.
Update unit tests to check message text instead of type.
Towards #16825.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16826)
=> [solvers] Clean up CheckBinding code style

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, tools/workspace/sdformat/patches/deprecation_unit_testing.patch, tools/workspace/sdformat/repository.bzl
This will allow us to more easily toggle their strictness.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16819)
=> [parsing] Route SDFormat warnings through DiagnosticPolicy

multibody/parsing/detail_urdf_parser.cc, multibody/parsing/detail_urdf_parser.h, multibody/parsing/test/detail_urdf_parser_test.cc
This is the first part of plumbing error channels into the URDF
parser. Since the whole change set will have all the grace of a snake
eating an elephant, this step is limited to introducing some
infrastructure and converting one function.
Subsequent patches will convert the rest of this module and plumb error
channels to other modules.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16824)
=> [parsing] Introduce class into urdf parser implementation

bindings/pydrake/systems/planar_scenegraph_visualizer.py, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
Related to #14691
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16765)
=> Remove scipy.spatial.ConvexHull dependency

tutorials/README.md, tutorials/_developers.md
Add new section headings for the developer docs.
Add reminder to clear cell outputs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16831)
=> [doc] Split tutorial docs into user docs vs developer docs

bindings/pydrake/_geometry_extra.py
The logger is already printing the URL (and this string lacked the f-string substitution in any case).
Hotfix for #16805.
Tested locally via `bazel run //tutorials:rendering_multibody_plant`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16830)
=> [pydrake] Remove stray print in StartMeshcat

bindings/pydrake/common/test_utilities/BUILD.bazel, bindings/pydrake/common/test_utilities/scipy_stub/scipy/__init__.py, bindings/pydrake/common/test_utilities/scipy_stub/scipy/sparse/__init__.py, bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/test/csdp_solver_test.py
In order to reduce our install footprint, pydrake will no longer depend on scipy on or after 2022-07-01.
Any users of the few scipy-returning methods in pydrake will need to add a direct dependency onto scipy to their own projects. The methods that return a sparse matrix will raise an ImportError when they are called when scipy is not installed.
Towards #16836 and #14691.  Plan detailed in https://github.com/RobotLocomotion/drake/issues/14691#issuecomment-1075658574.
Tested locally by `sudo apt remove python3-scipy` and confirming that this PR passes all pydrake tests, whereas the `master` branch fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16840)
=> [pydrake] Stub out scipy.sparse for unit testing

multibody/parsing/detail_common.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_urdf_parser_test.cc
This patch completes the conversion of detail_urdf_parser to use the
passed-in diagnostic policy for reporting warnings and errors. Some
parsing routines in related modules are not yet ported.
The patch boosts test coverage of error and warning branches to 100%, by
adding numerous (25-ish?) new test cases. It also converts test cases
from relying on throw-and-catch mechanics to message capture by a
test-only diagnostics policy.
As collateral damage, the collision filter parsing routines in
detail_common gain some ability to tolerate parsing functors that return
on error, instead of throwing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16829)
=> [parsing] Port remainder of detail_urdf_parser to diagnostics

bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py, bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_test.cc, systems/controllers/finite_horizon_linear_quadratic_regulator.cc, systems/controllers/finite_horizon_linear_quadratic_regulator.h, systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
Also implements transpose() in PiecewisePolynomial, which makes the
LQR code cleaner.
This method are needed to use time-varying LQR on the perching glider
example, and are generally good to have.  The equations are documented
at the end of section 8.2.1 in
http://underactuated.csail.mit.edu/lqr.html .
+@rcory for feature review, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16812)
=> [controllers] Implements the square-root form of finite-horizon LQR

tools/install/libdrake/header_lint.bzl
In certain configurations, libblas is shown as an interface deps.  Allow that for now.
Hotfix for #16774.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16849)
=> [tools] Add more known-defects to header lint checks

multibody/parsing/BUILD.bazel, multibody/parsing/test/process_model_directives_test.cc, multibody/parsing/test/process_model_directives_test/add_frame_without_model_namespace.yaml, multibody/parsing/test/process_model_directives_test/add_scoped_mid.yaml, multibody/parsing/test/process_model_directives_test/add_scoped_top.yaml, multibody/parsing/test/process_model_directives_test/inject_frames.yaml, multibody/parsing/test/process_model_directives_test/test_backreferences.yaml, multibody/parsing/test/scoped_names_model.sdf, multibody/parsing/test/scoped_names_test.cc
Per discussion in https://github.com/RobotLocomotion/drake/pull/16431, with @EricCousineau-TRI.
Separated tests for ModelDirectives into
* scoping (what we have currently, with some additional checks)
* back referencing during include
* frame injection from top level models
* new test showing the behavior of adding frames without a model namespace, but with different base frames
Signed-off-by: Aaron Chong <aaronchongth@gmail.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16593)
=> [multibody/parsing] Splitting up existing ModelDirectives tests

multibody/parsing/test/detail_urdf_parser_test.cc
Hotfix for #16829 ([failure](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-monterey-clang-bazel-continuous-release/446/)).
Tested locally on `macsim` already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16853)
=> [parsing] Hotfix unit test for macOS

geometry/render/dev/render_engine_gltf_client.cc, geometry/render/dev/render_engine_gltf_client.h, geometry/render/dev/render_engine_gltf_client_factory.cc, geometry/render/dev/test/render_engine_gltf_client_test.cc, geometry/render/render_engine_vtk.cc, geometry/render/render_engine_vtk.h
Update RenderEngineVtk function access modifiers and remove private friendship between RenderEngineVtk and its derived class RenderEngineGltfClient.
Tested locally with the new changes by running the new client/server pipeline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16846)
=> [geometry] Update RenderEngineVtk and remove private friendship

geometry/render/dev/http_service.h, geometry/render/dev/http_service_curl.cc, geometry/render/dev/render_client.cc, geometry/render/dev/render_client.h, geometry/render/dev/render_engine_gltf_client.cc, geometry/render/dev/render_engine_gltf_client.h, geometry/render/dev/render_engine_vtk_minimal_example.cc, geometry/render/dev/test/render_client_test.cc, geometry/render/dev/test/render_engine_gltf_client_test.cc, geometry/render/dev/test_utilities/test_png.cc, geometry/render/dev/test_utilities/test_png.h, geometry/render/dev/test_utilities/test_tiff.h
Per discussion in Slack, went through the `geometry/render/dev` folder and updated the function comments to use indicative mood.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16855)
=> [geometry] Update function comments to use indicative mood

bindings/pydrake/systems/test/trajectory_optimization_test.py, bindings/pydrake/systems/trajectory_optimization_py.cc, systems/trajectory_optimization/BUILD.bazel, systems/trajectory_optimization/multiple_shooting.cc, systems/trajectory_optimization/multiple_shooting.h, systems/trajectory_optimization/sequential_expression_manager.cc, systems/trajectory_optimization/sequential_expression_manager.h, systems/trajectory_optimization/test/multiple_shooting_test.cc, systems/trajectory_optimization/test/sequential_expression_manager_test.cc
This significantly improves the ergonomics in pydrake for adding, for
instance, bounding box constraints to the state or input at all knot
points.  (And it resolves a long-standing TODO in
`multiple_shooting.h`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16847)
=> [trajopt] Add `MultipleShooting::AddConstraintToAllKnotPoints` variants

tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
Fixes #16841
Fixes a bug that was improperly clearing the data model for the hydroelastic plugin, resulting in disabling/re-enabling the plugin not showing hydro contact surfaces.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16852)
=> [geometry:drake_visualizer] Fix for disabling/enabling hydro contact plugin

doc/index.md, tutorials/README.md
Remove all mention of binder, nbviewer, github rendering, etc. with respect to tutorials.
Reviewers can preview the new README [on my branch](https://github.com/jwnimmer-tri/drake/blob/tutorials-readme/tutorials/README.md).
\CC @RussTedrake @EricCousineau-TRI FYI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16860)
=> [doc] Switch tutorial links to point to Deepnote

multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/position_constraint_benchmark.cc
This highlights the performance difference between using the
analytical derivatives (via CalcJacobian) vs the AutoDiffXd
derivatives. I hope to follow-up with a PR that will minimize this
difference.
On my machine, I see:
```
------------------------------------------------------------------------------------------------
Benchmark                                                      Time             CPU   Iterations
------------------------------------------------------------------------------------------------
IiwaPositionConstraintFixture/EvalAutoDiffMbpDouble        43814 ns        43796 ns        15953
IiwaPositionConstraintFixture/EvalAutoDiffMbpAutoDiff    1421310 ns      1420862 ns          483
```
fyi @amcastro-tri (you said recently that …
=> [inverse kinematics] Add benchmark for position constraint.

multibody/fem/fem_element.h, multibody/fem/fem_indexes.h, multibody/fem/fem_model_impl.h, multibody/fem/test/dummy_element.h, multibody/fem/test/dummy_model.cc, multibody/fem/test/fem_element_test.cc, multibody/fem/test/volumetric_element_test.cc, multibody/fem/volumetric_element.h
They used to be important in the bespoke caching mechanism in the previous design.
We don't need them anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16843)
=> [fem] Remove element index from FemElement

doc/_pages/from_source.md, setup/ubuntu/source_distribution/install_prereqs.sh, tools/wheel/image/provision-base.sh, tools/workspace/drake_visualizer/image/provision.sh
Towards #16865
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16878)
=> setup: Upgrade recommended Bazel version to 5.1.0 for Linux

multibody/contact_solvers/sap/sap_model.cc, multibody/contact_solvers/sap/sap_model.h, multibody/contact_solvers/sap/test/sap_model_test.cc
After #16771, I integrated the latest version of `SapModel` in master into our working prototype in https://github.com/RobotLocomotion/drake/pull/16543 (FYI, it still works!)
In the process I realized:
1. Some APIs were missing, added in this PR.
2. I found a bug in the ordering of the Delassus operator entries (the diagonal approximation of it), fixed in this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16880)
=> Implements missing features in SapModel (cont.)

multibody/fem/fem_model.cc, multibody/fem/fem_model.h
In a recent refactor, we abandoned FemData in favor of FemState. The name of this function was accidentally left behind.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16888)
=> [fem] Rename FemModel::ThrowModelDataIncompatible

multibody/fem/fem_element.h, multibody/fem/fem_model.h, multibody/fem/fem_model_impl.h, multibody/fem/test/dummy_element.h, multibody/fem/test/fem_element_test.cc, multibody/fem/test/fem_model_test.cc, multibody/fem/test/volumetric_element_test.cc, multibody/fem/volumetric_element.h
Remove gravity vector stored in FemElement and refer to the one in the FemModel for single source of truth.
Separate calculations for external forces and the rest of residual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16883)
=> [fem] Simplify external force/gravity calculation

examples/kinova_jaco_arm/BUILD.bazel, examples/kinova_jaco_arm/jaco_controller.cc, examples/kinova_jaco_arm/jaco_simulation.cc, manipulation/kinova_jaco/jaco_command_receiver.cc, manipulation/kinova_jaco/jaco_command_receiver.h, manipulation/kinova_jaco/jaco_command_sender.cc, manipulation/kinova_jaco/jaco_command_sender.h, manipulation/kinova_jaco/jaco_status_receiver.cc, manipulation/kinova_jaco/jaco_status_receiver.h, manipulation/kinova_jaco/jaco_status_sender.cc, manipulation/kinova_jaco/jaco_status_sender.h, manipulation/kinova_jaco/test/jaco_command_receiver_test.cc, manipulation/kinova_jaco/test/jaco_command_sender_test.cc, manipulation/kinova_jaco/test/jaco_status_receiver_test.cc, manipulation/kinova_jaco/test/jaco_status_sender_test.cc
Splits the position and velocity ports in the Jaco LCM interface to
better match other robots' LCM systems (e.g. iiwa).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16863)
=> Update the Jaco LCM systems

multibody/parsing/test/diagnostic_policy_test_base.h
Fix errors in [mac-monterey-clang-bazel-continuous-release/474](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-monterey-clang-bazel-continuous-release/474/)
```
bazel-out/darwin-opt/bin/multibody/parsing/_virtual_includes/diagnostic_policy_test_base/drake/multibody/parsing/test/diagnostic_policy_test_base.h:56:33: error: loop variable 'record' creates a copy from type 'const drake::internal::DiagnosticDetail' [-Werror,-Wrange-loop-construct]
for (const DiagnosticDetail record : error_records_) {
^
bazel-out/darwin-opt/bin/multibody/parsing/_virtual_includes/diagnostic_policy_test_base/drake/multibody/parsing/test/diagnostic_policy_test_base.h:64:33: error: loop variable 'record' creates a copy from type 'const drake::internal::DiagnosticDetail' …
```
=> Use reference `&` to fix errors in CI mac-monterey-clang-bazel-continuous-release

examples/rimless_wheel/rimless_wheel.cc, examples/rimless_wheel/rimless_wheel.h, examples/rimless_wheel/test/rimless_wheel_test.cc
Previously, the floating-base pose that was sent to the visualizer
changed discontinuously at each step.  This is fine for forward
simulation, but in meshcat's animation the interpolation effects of
scrubbing through frames caused visual artifacts.  This PR simply
unwraps the pitch angle to make it continuous during a simulation.
It also adds some missing const specifier to the accessor functions
(which were needed to write the test).
+@aykut-tri for feature review, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16906)
=> [examples/rimless_wheel] Improve meshcat animation

bindings/pydrake/solvers/augmented_lagrangian_py.cc, bindings/pydrake/solvers/test/augmented_lagrangian_test.py, solvers/augmented_lagrangian.cc, solvers/augmented_lagrangian.h, solvers/test/augmented_lagrangian_test.cc
The slack variable s becomes a decision variable in the augmented Lagrangian. This is the same formulation used in LANCELOT.
Towards #16442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16845)
=> Add the smooth formulation of augmented Lagrangian.

multibody/plant/contact_model_doxygen.h
When using MultibodyPlant's discrete dynamics, static and kinetic coefficients of friction are assumed to be equal and the coefficient of static friction is ignored.
This PR fixes the documentation to be consistent with our code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16858)
=> Fixes documentation on the modeling of friction

multibody/parsing/BUILD.bazel, multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/detail_urdf_geometry.h, multibody/parsing/test/detail_urdf_geometry_test.cc
This patch plumbs diagnostic policy into AddMaterial...(), and (while
we're here) rewrites the tests for it from monolithic style to "fixture
and small tests" style.
Subsequent patches will finish the job of porting the rest of
detail_urdf_geometry to diagnostic policy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16904)
=> [parsing] Add diagnostic policy to AddMaterialToMaterialMap

multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/detail_urdf_geometry.h, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_urdf_geometry_test.cc
This patch finishes plumbing diagnostic policy through
detail_urdf_geometry. It also rewrites the existing tests to reduce
copy-paste, and adds numerous new tests to reach full coverage of all
the modified error and warning branches.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16910)
=> [parsing] Complete adding diagnostic policy in urdf_geometry
