tools/workspace/googlebenchmark/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15292)

[workspace] Upgrade googlebenchmark to latest release 1.5.5

---

geometry/proximity/hydroelastic_internal.cc
geometry/render/render_engine_vtk.cc
geometry/shape_specification.h
multibody/fixed_fem/dev/collision_objects.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15324)

Use static_cast in ImplementGeometry

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/BUILD.bazel
solvers/solve.cc
solvers/solve.h
solvers/test/solve_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15319)

Solve with first available solver

---

bindings/pydrake/solvers/clp_py.cc
bindings/pydrake/solvers/csdp_py.cc
bindings/pydrake/solvers/dreal_py.cc
bindings/pydrake/solvers/gurobi_py.cc
bindings/pydrake/solvers/ipopt_py.cc
bindings/pydrake/solvers/mosek_py.cc
bindings/pydrake/solvers/nlopt_py.cc
bindings/pydrake/solvers/osqp_py.cc
bindings/pydrake/solvers/scs_py.cc
bindings/pydrake/solvers/snopt_py.cc
bindings/pydrake/solvers/test/clp_solver_test.py
bindings/pydrake/solvers/test/csdp_solver_test.py
bindings/pydrake/solvers/test/dreal_solver_test.py
bindings/pydrake/solvers/test/gurobi_solver_test.py
bindings/pydrake/solvers/test/ipopt_solver_test.py
bindings/pydrake/solvers/test/mosek_solver_test.py
bindings/pydrake/solvers/test/nlopt_solver_test.py
bindings/pydrake/solvers/test/osqp_solver_test.py
bindings/pydrake/solvers/test/scs_solver_test.py
bindings/pydrake/solvers/test/snopt_solver_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15326)

Add python binding for static id() function of each solver

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/choose_best_solver.cc
solvers/choose_best_solver.h
solvers/solve.cc
solvers/solve.h
solvers/test/choose_best_solver_test.cc
solvers/test/solve_test.cc

As mentioned in https://github.com/RobotLocomotion/drake/pull/15319#issuecomment-875043969
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15325)

Use SelectFirstAvailableSolver instead of SolveWithFirstAvailableSolver

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/solver_options.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15312)

Add pybind for CommonSolverOption

---

solvers/mathematical_program.cc
solvers/mathematical_program.h

These were leftovers from 3a4e1d1716c1c9aed14e18807dca37a3f6485843 (#10483) or thereabouts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15330)

[solvers] Remove dead code from MathematicalProgram

---

solvers/choose_best_solver.cc

Inspired by #15325 as a way to avoid extra constructors.
\CC @hongkai-dai FYI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15327)

[solvers] Re-implement MakeSolver to enumerate over a table

---

geometry/optimization/BUILD.bazel
geometry/optimization/hyperellipsoid.cc
geometry/optimization/iris.cc
geometry/optimization/iris.h
geometry/optimization/test/hyperellipsoid_test.cc
geometry/optimization/test/iris_test.cc

for compute large convex regions of obstacle-free space.
A big step towards #6243 !
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15315)

geometry:optimization Implements IRIS algorithm

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py
geometry/optimization/convex_set.h
geometry/optimization/iris.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15333)

geometry:optimization: Python bindings for convex sets and Iris

---

common/never_destroyed.h
common/test/never_destroyed_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15329)

[common] Add lambda-using example to never_destroyed documentation

---

examples/allegro_hand/joint_control/README.md

Follow-up to #14204, motivated by Drake Developers discussion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/14542)

allegro_hand: Add README for joint_control sub-package

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/binding.h
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/mathematical_program_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15311)

Remove cost from MathematicalProgram

---

common/copyable_unique_ptr.h
common/test/copyable_unique_ptr_test.cc

In order to be compatble with a future copy-on-write unique pointer, `copyable_unique_ptr` made a distinction between `get()` and `get_mutable()`. The idea being that it would be nice to swap copyable with copy on write with the absolute minimum number of changes. So, by declaring that `const` distinction now, callers will think about mutable access.
However, this allowed getting a non-const *reference* via dereferencing, even from a `const copyable_unique_ptr`. Therefore, we distinguish derefencing a `copyable_unique_ptr` based on the *container's* `const`ness. Dereferencing a `const copyable_unique_ptr` will *always* return a `const` reference (and will be preserved with a copy-on-write pointer). But
dereferencing a non-`const` container, when swapped to copy-on-write, will trigger a …

Extend copyable_unique_ptr const correctness

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py
geometry/optimization/hpolyhedron.cc
geometry/optimization/hpolyhedron.h
geometry/optimization/test/hpolyhedron_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15355)

geometry::optimization Adds HPolyhedron::ChebyshevCenter()

---

math/quadratic_form.h
math/test/quadratic_form_test.cc

Add a numerical example, also clarify the number of rows in the return.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15363)

Document DecomposePositiveQuadraticForm function.

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py
geometry/optimization/convex_set.cc
geometry/optimization/convex_set.h
geometry/optimization/iris.cc
geometry/optimization/test/convex_set_test.cc
geometry/optimization/test/iris_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15345)

geometry::optimization Replace ConvexSets class with a typedef.

---

math/BUILD.bazel
math/quadratic_form.cc
math/quadratic_form.h
math/test/quadratic_form_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15365)

[math] more helpful error message in DecomposePSDmatrixIntoXtransposeTimesX

---

common/yaml/test/yaml_performance_test.cc
common/yaml/test/yaml_read_archive_test.cc
common/yaml/yaml_write_archive.h

As proposed in https://reviewable.io/reviews/RobotLocomotion/styleguide/45.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15338)

[yaml] Update exception types to match propsed new style guide

---

bindings/pydrake/solvers/mosek_py.cc
bindings/pydrake/solvers/test/mosek_solver_test.py
solvers/BUILD.bazel
solvers/mosek_solver.cc
solvers/mosek_solver.h
solvers/test/mosek_solver_test.cc

Resolves #15359
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15360)

MosekSolver sets logging using CommonSolverOption

---

doc/doxygen_cxx/doxygen_extra.css
systems/framework/BUILD.bazel
systems/framework/test/value_producer_test.cc
systems/framework/value_producer.cc
systems/framework/value_producer.h

Refer to the overall changesets in #15161 to see how this gets used, especially the "Use new ValueCalcFunction sugar".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15271)

[framework] Add ValueProducer constructor sugar

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/mathematical_program_test.cc
tutorials/debug_mathematical_program.ipynb

I found this quite useful when I was debugging my programs.  I thought I would contribute it, rather than let it get lost in a branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15370)

[solvers] print MathematicalProgram

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py

Resolves #15272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15353)

solvers: Add python bindings for MathematicalProgram::CheckSatisfied

---

bindings/pydrake/systems/lcm_py.cc
bindings/pydrake/systems/test/lcm_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15309)

[pydrake] Add bindings for LcmScopeSystem

---

solvers/dreal_solver.h
solvers/solver_options.h

Close #15383
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15384)

Document dReal options

---

tools/workspace/styleguide/repository.bzl

This is a non-functional change, because the upgrade only changes the documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15378)

[workspace] Upgrade styleguide latest commit

---

multibody/fixed_fem/dev/deformable_rigid_manager.cc
multibody/fixed_fem/dev/deformable_rigid_manager.h
multibody/plant/test/discrete_update_manager_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15376)

[multibody] Use ValueProducer sugar in DiscreteUpdateManager

---

common/reset_after_move.h
common/test/reset_after_move_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15362)

[common] Make reset_after_move be conditionally noexcept

---

tools/release_engineering/relnotes.py

Using the process documented in #15339.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15347)

[relnotes] Use pull request labels to exclude non-notable commits

---

doc/_pages/gallery.md

https://mntan3.github.io/
https://github.com/RobotLocomotion/gym/tree/master/gym/envs/robot_locomotion_group/drake/shoe
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15044)

Add shoe to gallery

---

bindings/pydrake/systems/BUILD.bazel
bindings/pydrake/systems/lcm_py.cc
bindings/pydrake/systems/test/lcm_test.py
systems/lcm/BUILD.bazel
systems/lcm/connect_lcm_scope.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15282)

[lcm] Deprecate ConnectLcmScope

---

bindings/pydrake/solvers/mosek_py.cc
bindings/pydrake/solvers/test/mosek_solver_test.py
solvers/BUILD.bazel
solvers/mosek_solver.cc
solvers/mosek_solver.h
solvers/test/mosek_solver_test.cc

This reverts commit c2a218e3d3a3ed1d680cb49db29330629744909a.
Caused failures with address-sanitizer and leak-sanitizer.
Dear Hongkai,
The on-call build cop, rpoyner-tri, believes that your PR 15382 may have
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-clang-bazel-continuous-everything-address-sanitizer/3639/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-bionic-clang-bazel-continuous-everything-leak-sanitizer/351/
Therefore, the build cop has created this revert PR and …

Revert "MosekSolver sets logging using CommonSolverOption (#15382)"

---

doc/_release-notes/v0.32.0.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15393)

[doc] Fix formatting of v0.32.0 notes

---

solvers/constraint.h

Also check if the A matrix in linear constraint is finite.
See slack discussion https://drakedevelopers.slack.com/archives/C026A3YTJN6/p1626138201163100?thread_ts=1626137961.161900&cid=C026A3YTJN6
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15391)

Check if the lower/upper bounds is nan.

---

setup/ubuntu/source_distribution/packages-bionic-test-only.txt
setup/ubuntu/source_distribution/packages-focal-test-only.txt

As used by #15390.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15392)

[setup] Add python3-psutil as test-only Ubuntu dependency

---

bindings/pydrake/systems/primitives_py.cc
bindings/pydrake/systems/test/primitives_test.py

Closes #15343.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15397)

[pydrake] Add bindings for TrajectoryLinearSystem

---

systems/framework/diagram.cc
systems/framework/leaf_system.cc
systems/framework/leaf_system.h
systems/framework/system.cc
systems/framework/system_base.h
systems/framework/test/system_test.cc

This is the next step of #15161.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15402)

[framework] Use new ValueProducer sugar

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py
geometry/optimization/point.cc
geometry/optimization/point.h
geometry/optimization/test/convex_set_test.cc
geometry/optimization/test/point_test.cc

This has proven useful in a number of unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15368)

[geometry/optimization] Make Point mutable

---

tools/performance/benchmark_tool

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15414)

benchmark_tool: Don't delete any existing files

---

geometry/optimization/convex_set.cc
geometry/optimization/convex_set.h
geometry/optimization/test/convex_set_test.cc

Not quite sure of the right way to unit test this without adding too much set implementation into `convex_set_test.cc`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15372)

geometry/opt: Add ConvexSet::IntersectsWith()

---

geometry/optimization/hpolyhedron.cc
geometry/optimization/hpolyhedron.h
geometry/optimization/test/hpolyhedron_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15371)

geometry/opt: Add HPolyhedron::CartesianPower()

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py

Resolves #15405
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15408)

py mp: Allow upcasting to Binding<Constraint>

---

bindings/pydrake/pydrake_doxygen.h

Follow-up to #15394
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15398)

pydrake: Add guidance for binding Clone() methods

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/mathematical_program_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15350)

remove constraint from MathematicalProgram

---

multibody/contact_solvers/BUILD.bazel
multibody/contact_solvers/block_sparse_linear_operator.cc
multibody/contact_solvers/block_sparse_linear_operator.h
multibody/contact_solvers/linear_operator.cc
multibody/contact_solvers/linear_operator.h
multibody/contact_solvers/test/block_sparse_linear_operator_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15164)

Implements BlockSparseLinearOperator

---

solvers/BUILD.bazel
solvers/scs_solver.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15423)

Use ScopeExit to free ScsSolver resource.

---

systems/framework/system.cc
systems/framework/test/system_test.cc

This shaves around 14% off the compute cost for the PassThrough3 benchmark, once the `dynamic_casts` in the Calc path are already gone.
Relates to #10882 somewhat.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15432)

[framework] Avoid energy-related cache updates for stateless systems

---

multibody/fixed_fem/dev/elasticity_element.h

https://eigen.tuxfamily.org/dox/TopicPitfalls.html#TopicPitfalls_auto_keyword
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15450)

[fixed_fem] Don't mix auto with Eigen, unless with eval()

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/BUILD.bazel
solvers/get_program_type.cc
solvers/get_program_type.h
solvers/program_attribute.cc
solvers/program_attribute.h
solvers/test/get_program_type_test.cc
solvers/test/program_attribute_test.cc

As mentioned in https://github.com/RobotLocomotion/drake/issues/15320#issuecomment-874724942, we need the function `GetProgramType()` to determine the right solvers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15340)

Optimization program type

---

bindings/pydrake/solvers/test/gurobi_solver_test.py
solvers/gurobi_solver.cc
solvers/gurobi_solver.h
solvers/test/gurobi_solver_test.cc

Also can compute IIS when the model is infeasible.
@TobiaMarcucci this feature can be useful when you debug infeasible Gurobi problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15438)

Gurobi write model to file.

---

solvers/constraint.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15474)

Replace the broken link to Lorentz and rotated Lorentz cone.

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/clp_solver.cc
solvers/csdp_solver.cc
solvers/mosek_solver.cc
solvers/scs_solver.cc
solvers/solver_options.cc
solvers/solver_options.h
solvers/test/solver_options_test.cc

Towards #12867.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15473)

[solvers] De-boilerplate common solver option handling

---

solvers/mathematical_program_doxygen.h

From Slack conversation https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1626898485086100?thread_ts=1626896625.081800&cid=C3L92BM2Q
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15467)

Improve the documentation for mathematicalprogram doxygen.

---

solvers/constraint.cc
solvers/constraint.h
solvers/evaluator_base.cc
solvers/test/binding_test.cc
solvers/test/constraint_test.cc
solvers/test/evaluator_base_test.cc

also touch the documentation and remove a stale detail that is no longer true.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15475)

[solvers] implement Display for Lorentz cone constraints

---

common/trajectories/piecewise_polynomial.h
common/type_safe_index.h
doc/doxygen_cxx/Doxyfile_CXX.in
doc/doxygen_cxx/build.py
geometry/query_object.h
multibody/constraint/constraint_doxygen.h
multibody/constraint/constraint_solver.h

This prevents failure like the one induced by #15404 from reaching the website.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15455)

[doxygen_cxx] Fail-fast when section anchors go missing

---

geometry/optimization/graph_of_convex_sets.cc
geometry/optimization/graph_of_convex_sets.h
geometry/optimization/test/graph_of_convex_sets_test.cc

This is the heavy lifting that I avoided including in my first PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15483)

[geometry/optimization] Adds SolveShortestPath to GraphOfConvexSets

---

geometry/optimization/test/graph_of_convex_sets_test.cc

it was introduced in the original PR only to document IPOPT's bad behavior.  turns out the behavior was worse than expected, and the test failed on mac CI https://drake-cdash.csail.mit.edu/test/320932067 .  Russ, Soonho, and Betsy were unable to reproduce it on our local macs.  I've simply removed the test, adding a textual documentation of the problem instead.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15509)

[geometry/optimization] remove problematic shortest path problem test for ipopt

---

geometry/optimization/test/graph_of_convex_sets_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15514)

[geometry/optimization] actually remove the ipopt shortest path problem test.

---

solvers/snopt_solver.cc
solvers/test/snopt_solver_test.cc

Relates to #12867 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15493)

SnoptSolver respects CommonSolverOption::kPrintFileName

---

systems/framework/diagram_builder.h

This is already tested via the two DtorOrder unit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15521)

[framework] Promise diagram systems' destruction order

---

tools/workspace/ibex/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15531)

[tools] Use libibex-dev_2.7.4.20210515

---

tools/workspace/rules_pkg/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15548)

[workspace] Upgrade rules_pkg to latest release 0.5.0

---

multibody/fixed_fem/dev/deformable_rigid_manager.cc
multibody/fixed_fem/dev/deformable_rigid_manager.h
multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
multibody/plant/discrete_update_manager.cc
multibody/plant/discrete_update_manager.h
multibody/plant/multibody_plant_discrete_update_manager_attorney.h

Also calculate the free motion rigid velocities to support the free motion velocities for contact.
Co-authored-by: Alejandro Castro <alejandro.castro@tri.global>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15459)

[fem] Calculate free motion velocities for contact

---

bindings/pydrake/common/module_py.cc
common/nice_type_name_override.cc
common/test_utilities/limit_malloc.cc
examples/allegro_hand/joint_control/allegro_single_object_simulation.cc
examples/allegro_hand/run_allegro_constant_load_demo.cc
examples/multibody/acrobot/passive_simulation.cc
examples/multibody/acrobot/run_lqr.cc
examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
examples/multibody/pendulum/passive_simulation.cc
examples/multibody/rolling_sphere/rolling_sphere_run_dynamics.cc
examples/simple_gripper/simple_gripper.cc
multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
multibody/plant/test/multibody_plant_hydroelastic_contact_results_output_test.cc
systems/lcm/lcm_publisher_system.cc

We propose that the bangbang operator is not widely enough known[1] outside of C++ experts to merit use in everyday code and error messages[2].
This PR will stay open for one week to receive comments.
If we all agree that all of the changes are improvements (or at least, if nobody disagrees within the window), the next step would be to amend the style guide to make the style choice permanent.
[1] We're excluding those who know know of it via the famous B-52's song.
[2] Just to be clear, for those who don't get the sarcasm: there is actually no `operator!!` in C++ (see https://en.cppreference.com/w/cpp/language/operators).  That's actually the whole point here.
--- …

Eschew use of operator!!

---

systems/controllers/test/inverse_dynamics_test.cc

This is to work around a bug in kcov. See #14424 for more info.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15567)

controllers: Reorder inverse dynamics test cases

---

systems/framework/leaf_output_port.h
systems/framework/value_producer.h

These fix some code review questions that were noted during the PR train.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15557)

[framework] Tidy up ValueProducer loose ends

---

solvers/mosek_solver.cc
solvers/mosek_solver.h
solvers/test/mosek_solver_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15568)

MosekSolver accepts option write to write the model file.

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/constraint.h
solvers/create_constraint.cc
solvers/create_constraint.h
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/constraint_test.cc
solvers/test/create_constraint_test.cc
solvers/test/mathematical_program_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15553)

AddLorentzConeConstraint accept eval_type.

---

solvers/BUILD.bazel
solvers/ibex_converter.cc
solvers/ibex_converter.h
solvers/ibex_solver.cc
solvers/ibex_solver.h
solvers/ibex_solver_common.cc
solvers/no_ibex.cc
solvers/test/ibex_converter_test.cc
solvers/test/ibex_solver_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15552)

[solvers] Add IbexSolver

---

multibody/fem/BUILD.bazel
multibody/fem/linear_constitutive_model_data.cc
multibody/fem/linear_constitutive_model_data.h
multibody/fem/test/deformation_gradient_data_test.cc
multibody/fem/test/linear_constitutive_model_data_test.cc
multibody/fixed_fem/dev/BUILD.bazel
multibody/fixed_fem/dev/corotated_model_data.h
multibody/fixed_fem/dev/linear_constitutive_model.h
multibody/fixed_fem/dev/linear_constitutive_model_data.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15566)

[fem] Move LinearConstitutiveModelData out of dev

---

multibody/fixed_fem/dev/matrix_utilities.h

* Avoid mixing `auto` with Eigen expression.
* Change DRAKE_DEMAND to DRAKE_ASSERT for tight inner loop calculations.
These changes lead to a ~4x performance improvement in constitutive calculations (profiled with the simple gripper demo).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15605)

[fem] FEM matrix math helpers improvements

---

multibody/fixed_fem/dev/BUILD.bazel
multibody/fixed_fem/dev/deformable_model.cc
multibody/fixed_fem/dev/deformable_model.h
multibody/fixed_fem/dev/deformable_rigid_manager.cc
multibody/fixed_fem/dev/deformable_rigid_manager.h
multibody/fixed_fem/dev/inverse_spd_operator.cc
multibody/fixed_fem/dev/inverse_spd_operator.h
multibody/fixed_fem/dev/test/deformable_rigid_contact_solver_test.cc
multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
multibody/fixed_fem/dev/test/inverse_spd_operator_test.cc

In support of this calculation:
* Introduce an inverse operator.
* Add new cache entries for convenience.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15559)

[fem] Calculate two-way coupled contact results

---

solvers/ibex_solver.cc
solvers/ibex_solver.h
solvers/ibex_solver_common.cc
solvers/test/ibex_solver_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15607)

[solvers] IbexSolver supports more constraints / costs

---

multibody/fem/BUILD.bazel
multibody/fem/constitutive_model.h
multibody/fem/test/constitutive_model_test.cc
multibody/fixed_fem/dev/BUILD.bazel
multibody/fixed_fem/dev/corotated_model.h
multibody/fixed_fem/dev/corotated_model_data.h
multibody/fixed_fem/dev/elasticity_element.h
multibody/fixed_fem/dev/linear_constitutive_model.h
multibody/fixed_fem/dev/test/constitutive_model_test_utilities.cc
multibody/fixed_fem/dev/test/constitutive_model_test_utilities.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15603)

[fem] Move ConstitutiveModel out of dev

---

multibody/fixed_fem/dev/BUILD.bazel
multibody/fixed_fem/dev/deformable_rigid_manager.cc
multibody/fixed_fem/dev/deformable_rigid_manager.h
multibody/fixed_fem/dev/run_cantilever_beam.cc
multibody/fixed_fem/dev/test/deformable_rigid_contact_solver_test.cc
multibody/fixed_fem/dev/test/deformable_rigid_manager_test.cc
multibody/fixed_fem/dev/test/rigid_update_test.cc
multibody/plant/discrete_update_manager.cc
multibody/plant/discrete_update_manager.h
multibody/plant/multibody_plant_discrete_update_manager_attorney.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15611)

[fem] Implement DeformableRigidManager::DoCalcContactSolverResults()

---

doc/_pages/platform_reviewer_checklist.md
doc/_pages/reviewable.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15624)

[doc] Add more relnotes and review assignment processes

---

solvers/get_program_type.cc
solvers/test/get_program_type_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15625)

return the right type for nonlinear program with linear complementary constraints

---

solvers/BUILD.bazel
solvers/constraint.cc
solvers/ibex_solver.cc
solvers/ibex_solver.h
solvers/solver_options.h
solvers/test/constraint_test.cc
solvers/test/ibex_solver_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15612)

[solvers] Support IBEX Solver options

---

systems/lcm/lcm_interface_system.cc
systems/lcm/test/lcm_interface_system_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15653)

Allow multiple LcmInterfaceSystems on the same URL

---

bindings/pydrake/common/test/value_test.py
bindings/pydrake/common/value_py.cc
bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py

Resolves #15640
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15641)

py value: Register Value[float] for use with ProximityProperties

---

geometry/optimization/test/graph_of_convex_sets_test.cc
solvers/BUILD.bazel
solvers/choose_best_solver.cc
solvers/get_program_type.cc
solvers/mathematical_program_doxygen.h
solvers/program_attribute.h
solvers/test/choose_best_solver_test.cc
solvers/test/solve_test.cc

Resolves #15320
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15541)

Choose best solver based on program type.

---

bindings/pydrake/solvers/BUILD.bazel
bindings/pydrake/solvers/mixed_integer_optimization_util_py.cc
bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc
bindings/pydrake/solvers/test/mixed_integer_rotation_constraint_test.py

Been using this in my research code on the Python side for a little while -- been working great!
@hongkai-dai -- any chance you could help me get this through?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15678)

Add Python bindings for mixed integer rotation constraint generator.

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/systems/test/meshcat_visualizer_test.py
bindings/pydrake/test/geometry_test.py
geometry/meshcat.h
geometry/meshcat_visualizer.cc
geometry/meshcat_visualizer.h
geometry/meshcat_visualizer_params.h
geometry/test/meshcat_manual_test.cc
geometry/test/meshcat_visualizer_test.cc

Follow-up to #13038.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15683)

[geometry] Add python bindings for Meshcat/MeshcatVisualizerCpp

---

multibody/plant/test/multibody_plant_forward_dynamics_test.cc
multibody/plant/test/multibody_plant_reaction_forces_test.cc
multibody/tree/body_node.h

Resolves #15627.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15686)

Fixes BodyNode::GetJacobianFromArray() to return an empty map when nv=0.

---

bindings/pydrake/systems/meshcat_visualizer.py
geometry/meshcat.cc
geometry/meshcat.h
geometry/meshcat.html
geometry/meshcat_types.h
geometry/test/meshcat_manual_test.cc
setup/mac/binary_distribution/requirements.txt
setup/ubuntu/binary_distribution/packages-bionic.txt
setup/ubuntu/binary_distribution/packages-focal.txt
tools/workspace/meshcat/repository.bzl
tools/workspace/meshcat_python/repository.bzl

meshcat changes the scaling of the background color
meshcat updated three.js, which required some non-trivial changes to my msgpack usage.
Resolves #15681
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15684)

[geometry:meshcat] Upgrade meshcat and meshcat-python versions

---

bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/multibody/tree_py.cc
multibody/plant/BUILD.bazel
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/tamsi_solver.h
multibody/plant/test/floating_body_test.cc
multibody/plant/test/multibody_plant_reaction_forces_test.cc
multibody/test_utilities/floating_body_plant.cc
multibody/test_utilities/floating_body_plant.h
multibody/tree/body.h
multibody/tree/joint.h
multibody/tree/multibody_element.h
multibody/tree/multibody_tree_system.h
multibody/tree/test/ball_rpy_joint_test.cc
multibody/tree/test/planar_joint_test.cc
multibody/tree/test/prismatic_joint_test.cc
multibody/tree/test/screw_joint_test.cc
multibody/tree/test/universal_joint_test.cc
multibody/tree/test/weld_joint_test.cc

Relevant to: #14200
Adapted from original implementation by Joe Masterjohn
joe.masterjohn@tri.global. See also his draft #15137. Thanks also to Joe for
serving as co-author and advisor on this patch.
This patch builds on Joe's implementation, mostly by expanding documentation
and tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15644)

multibody: Add joint locking

---

bindings/pydrake/systems/test/meshcat_visualizer_test.py

Resolves #15702.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15712)

Re-enable meshcat_visualizer_test.test_warnings_and_errors

---

tools/workspace/tinyobjloader/package.BUILD.bazel
tools/workspace/tinyobjloader/repository.bzl

Relates to https://github.com/tinyobjloader/tinyobjloader/issues/318.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15714)

[workspace] Upgrade tinyobjloader to latest commit v2.0.0-rc9

---

tools/workspace/uwebsockets/repository.bzl

https://github.com/uNetworking/uWebSockets/releases/tag/v19.4.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15719)

[workspace] Upgrade uwebsockets to latest release v19.4.0

---

bindings/pydrake/systems/primitives_py.cc
systems/analysis/test/monte_carlo_test.cc
systems/primitives/random_source.cc
systems/primitives/random_source.h
systems/primitives/test/random_source_test.cc
systems/sensors/test/beam_model_test.cc

Follow-up from #15092.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15708)

[primitives] Promote RandomSource to be templated on scalar

---

tools/workspace/intel_realsense_ros/repository.bzl

https://github.com/IntelRealSense/realsense-ros/releases/tag/2.3.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15723)

[workspace] Upgrade intel_realsense_ros to latest release 2.3.1

---

tools/workspace/rules_pkg/repository.bzl

https://github.com/bazelbuild/rules_pkg/releases/tag/0.5.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15725)

[workspace] Upgrade rules_pkg to latest release 0.5.1

---

tools/workspace/ros_xacro/repository.bzl

https://github.com/ros/xacro/compare/1.13.11...1.13.12
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15724)

[workspace] Upgrade ros_xacro to latest release 1.13.12

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/multibody/BUILD.bazel
bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/multibody/tree_py.cc
bindings/pydrake/test/geometry_test.py

Turns out I *did* need this eventually!
The subject matter being bound is a little eclectic, but I hope it's reasonable to keep these together in a PR since they're all conceptually really similar additions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15715)

Enabling pickling for Inertia types, CoulombFriction, and most Shapes

---

BUILD.bazel
doc/BUILD.bazel
geometry/BUILD.bazel
geometry/meshcat.cc
geometry/meshcat.html
tools/install/bazel/BUILD.bazel
tools/install/bazel/drake.BUILD.bazel
tools/install/bazel/drake__geometry.BUILD.bazel
tools/install/bazel/generate_installed_files_manifest.bzl
tools/workspace/meshcat/package.BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15732)

[geometry] Fix installation paths for meshcat

---

math/test/linear_solve_test.cc

Resolves #15745
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15748)

Fix the CI failure on linear_solve_test.cc

---

doc/_pages/installation.md
doc/index.md
tutorials/README.md

As discussed in https://drakedevelopers.slack.com/archives/C01879RNKQW/p1631308810003200?thread_ts=1631294733.000600&cid=C01879RNKQW
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15764)

Fix broken link to tutorials.

---

math/linear_solve.h
math/test/linear_solve_test.cc

When A contains double or symbolic::Expression, the linear solver matrix also contains the same scalar type. When A contains AutoDiffScalar, the linear solver matrix contains double scalar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15752)

Get the linear solver for generic A.

---

doc/_pages/release_playbook.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15770)

[doc] Add release instructions for Drake-owned externals

---

doc/_pages/clion.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15771)

[doc] Refresh known-good CLion versions

---

geometry/proximity_properties.h

Partially fix issue #15743. After this PR merges, we'll still keep that issue open.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15767)

[geometry] Fix documenation issue 15743 (resolution hint)

---

doc/_pages/release_playbook.md

Per #15673.
Also add more checklist items for release notes wordsmithing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15780)

[doc] Add more release instructions for Drake-owned externals

---

bindings/pydrake/systems/primitives_py.cc
bindings/pydrake/systems/test/primitives_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15794)

[primitives] Add python binding for `Integrator<T>::set_integral_value`

---

common/trajectories/piecewise_polynomial.cc

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15795)

[trajectories] more useful error messages for piecewise polynomial spline generation

---

multibody/fixed_fem/dev/BUILD.bazel
multibody/fixed_fem/dev/run_simple_gripper.cc

Add a demo where a simple gripper with two fingers squeezes a deformable box with sinusoidal forces to demonstrate the integration of the deformable solver and the contact solver.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15759)

[fem] Demo for deformable and contact solver integration

---

bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_test.py
geometry/optimization/BUILD.bazel
geometry/optimization/cartesian_product.cc
geometry/optimization/cartesian_product.h
geometry/optimization/iris.cc
geometry/optimization/minkowski_sum.h
geometry/optimization/test/cartesian_product_test.cc
geometry/optimization/test/iris_test.cc

This is a general concept from geometry, but in particular it adds support for parsing Cylinder geometry for SceneGraph.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15571)

[geometry/optimization] CartesianProduct isa ConvexSet

---

tools/workspace/pybind11/mkdoc.py

Closes #15652.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15798)

[mkdoc] Report a more specific error when libstdc++ is broken

---

multibody/optimization/BUILD.bazel
multibody/optimization/test/toppra_test.cc
multibody/optimization/toppra.cc
multibody/optimization/toppra.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15731)

multibody optimization: Add Toppra

---

multibody/plant/dev/BUILD.bazel
multibody/plant/dev/multibody_plant_config.cc
multibody/plant/dev/multibody_plant_config.h
multibody/plant/dev/multibody_plant_config_functions.cc
multibody/plant/dev/multibody_plant_config_functions.h
multibody/plant/dev/test/multibody_plant_config_functions_test.cc

Towards #15565.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15791)

[multibody/plant] Copy config functions from Anzu into dev

---

math/linear_solve.h
math/test/linear_solve_test.cc

This will be used when we declare a linear solver, such as in https://github.com/RobotLocomotion/drake/blob/c2e061f1087853fc72bb8b17bbb11ce9039ae732/multibody/plant/multibody_plant.cc#L2566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15790)

Add alias LinearSolver, rename LinearSolve.

---

tools/workspace/nlopt/repository.bzl

_Edit: Towards #15757._
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15807)

Use system nlopt for manylinux

---

multibody/fixed_fem/dev/BUILD.bazel
multibody/fixed_fem/dev/mesh_utilities.cc
multibody/fixed_fem/dev/mesh_utilities.h
multibody/fixed_fem/dev/test/mesh_utilities_test.cc

Dev code for star refinement of boundary tetrahedra for Deformables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15813)

[multibody/fixed_fem/dev] Star refinement of boundary tetrahedra.

---

tools/workspace/common_robotics_utilities/repository.bzl
tools/workspace/voxelized_geometry_tools/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15822)

[workspace] Fix common_robotics_utilities and voxelized_geometry_tools

---

geometry/meshcat.cc

Resolves #15821
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15823)

[geometry:meshcat] Resolve segfault on close for mac

---

multibody/optimization/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15824)

Increase size of Toppra test to prevent failure on mosek builds

---

geometry/meshcat.cc

Variables in WebSocketPublisher are documented for use in either the main thread or the websocket thread.  This cleans up that contract, and fixes some violations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15827)

[geometry:meshcat] clean up pass on per-thread variables

---

doc/_pages/release_playbook.md
tools/workspace/BUILD.bazel
tools/workspace/common_robotics_utilities/package.BUILD.bazel

Closes #15673.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15825)

[workspace] Add LICENSE and tagging for common_robotics_utilities

---

doc/doxygen_cxx/build.py

Closes #15619.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15832)

[doc] Remove extra quotation marks from Doxygen deprecation notes

---

geometry/optimization/iris.cc
geometry/proximity/test/mesh_half_space_intersection_test.cc
geometry/proximity/test/mesh_intersection_test.cc
geometry/proximity/test/mesh_plane_intersection_test.cc
multibody/plant/test/contact_permutation_test.cc
solvers/choose_best_solver.cc

Relevant to: #15802
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15838)

Fix warnings from apple clang 13

---

geometry/meshcat.cc

Add thread assertions, and a few others, to WebSocketPublisher. This is
mostly to benefit readers trying to verify thread properties of member
data. Developed during the review of PR #15827.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15837)

meshcat: Add more thread checks

---

tutorials/rendering_multibody_plant.ipynb

Preview:
https://nbviewer.jupyter.org/github/EricCousineau-TRI/drake/blob/feature-render-touch-up/tutorials/rendering_multibody_plant.ipynb
Before:
> ![image](https://user-images.githubusercontent.com/26719449/135177811-8a06c9f6-2128-47db-a178-bdfaf5d31d52.png)
After:
> ![image](https://user-images.githubusercontent.com/26719449/135177293-177b0a32-5e76-4e69-bed1-24fa94f83738.png)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15841)

tutorials: Fix camera + robot positioning; show depth rendering

---

math/linear_solve.h
math/test/linear_solve_test.cc

Also move the previous alias LinearSolver to internal::_LinearSolver
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15818)

Add LinearSolver class

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
multibody/plant/contact_results_to_lcm.cc
multibody/plant/contact_results_to_lcm.h
multibody/plant/test/contact_results_to_lcm_test.cc

Fix a related warning message to be correctly actionable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15848)

[plant] Add publish_period option to LCM contact results

---

multibody/optimization/BUILD.bazel
multibody/optimization/test/toppra_test.cc
multibody/optimization/toppra.cc
multibody/optimization/toppra.h

Adds the following constraint types to Toppra:
- Joint torque constraint
- Frame velocity constraint
- Frame acceleration constraint
- Frame translational speed constraint
Builds off of #15731
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15799)

multibody optimization: Add additional constraints to Toppra

---

bindings/pydrake/multibody/BUILD.bazel
bindings/pydrake/multibody/optimization_py.cc
bindings/pydrake/multibody/test/optimization_test.py

Depends on #15799
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15836)

pydrake multibody: Add bindings for Toppra

---

math/linear_solve.h

Relevant (maybe?) to: #15685
Motivated by discussions in #15818, reduce some of the syntax noise by
replacing SFINAE with a combination of type aliases, if constexpr, and
static_assert. No functionality is changed, but perhaps things are easier to
read.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15853)

linear_solve: Reduce use of SFINAE

---

setup/ubuntu/binary_distribution/install_prereqs.sh
setup/ubuntu/install_prereqs.sh
setup/ubuntu/source_distribution/install_prereqs.sh

I wanted to avoid having to sit there and babysit the script as it installs the dependencies.
Love to hear feedback on this idea.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15819)

Added a --without-asking flag which installs with apt-get install -y

---

systems/framework/system_base.h

(Per announced deprecation.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15862)

[systems] Move DeclareCacheEntry to protected access

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/test/frame_id_test.py
common/BUILD.bazel
common/identifier.cc
common/identifier.h
geometry/geometry_frame.cc
geometry/render/gl_renderer/shader_program.cc
geometry/render/gl_renderer/shader_program.h

Closes #15846.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15857)

[pydrake] Fix ODR violations in get_new_id bindings

---

tools/install/bazel/test/drake_bazel_installed_test.py
tools/workspace/rules_python/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15870)

[workspace] Upgrade rules_python to latest release 0.4.0

---

tools/workspace/metadata.py
tools/workspace/new_release.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15864)

[workspace] Add new_release tooling for automatic upgrades

---

tools/workspace/buildifier/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15880)

[workspace] Upgrade buildifier to latest release 4.2.0

---

multibody/optimization/static_equilibrium_problem.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15882)

Remove TODO in the doxygen of StaticEquilibriumProblem

---

common/test_utilities/BUILD.bazel
common/test_utilities/eigen_geometry_compare.h
manipulation/perception/test/pose_smoother_test.cc

Towards #9865.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16007)

[test_utilities] Deprecate ExpectRotMat and CompareTransforms

---

systems/controllers/setpoint.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16023)

Hotfix for deprecation build errors

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py

Towards #16013.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16015)

[pydrake] Bind symbolic.uninterpreted_function

---

bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/custom_test.py
systems/framework/value_producer.h

Resolves #14287
Requires #15979
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15983)

py framework: Expose minimal API to use DeclareCacheEntry

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py

Towards #16013.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16012)

[pydrake] Bind symbolic.Expression.get_kind

---

common/schema/BUILD.bazel
common/schema/test/rotation_test.cc
common/schema/test/stochastic_test.cc
common/yaml/BUILD.bazel
common/yaml/test/yaml_io_test.cc
common/yaml/test/yaml_performance_test.cc
common/yaml/yaml_doxygen.h
common/yaml/yaml_io.cc
common/yaml/yaml_io.h
common/yaml/yaml_write_archive.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16000)

[yaml] Add sugar to write serialized files

---

bindings/pydrake/geometry_py_optimization.cc
bindings/pydrake/test/geometry_optimization_test.py
geometry/optimization/graph_of_convex_sets.cc
geometry/optimization/graph_of_convex_sets.h
geometry/optimization/test/graph_of_convex_sets_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16017)

[geometry:optimization] Add GetGraphvizString to GraphOfConvexSets

---

examples/simple_four_bar/README.md
systems/controllers/BUILD.bazel

Relates #6269, #13326, #1713.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16028)

[controllers] Remove unused unused test data dependency

---

lcm/drake_lcm_interface.h
lcm/test/drake_lcm_interface_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16027)

[lcm] Allow handlers for Subscribe to throw exceptions

---

tools/wheel/dev/image/pip-drake.patch

Adjust the patch we apply when building wheels so that it applies after recent changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16032)

Fix patch for building wheels

---

tutorials/debug_mathematical_program.ipynb

Hotfix for #16019.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16030)

[tutorials] Reduce overwhelming solver verbosity

---

tools/wheel/dev/image/build-dependencies.sh
tools/wheel/dev/image/build-drake.sh
tools/wheel/dev/image/build-vtk.sh
tools/wheel/dev/image/build-wheel.sh
tools/wheel/dev/image/provision-base.sh
tools/wheel/dev/image/provision-python.sh
tools/wheel/dev/test/Dockerfile
tools/wheel/dev/test/provision.sh
tools/wheel/dev/test/test-wheel.sh
tools/wheel/dev/test/test-wheels.sh

Create a script to run a basic sanity test on a wheel. Create a second script to drive the first, given a wheel version. For now, the tests this runs are fairly rudimentary, but this should provide a reasonable framework for growing the tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15994)

Add scripts to test wheels

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/_symbolic_extra.py
bindings/pydrake/symbolic_py.cc
bindings/pydrake/symbolic_py_unapply.cc
bindings/pydrake/symbolic_py_unapply.h
bindings/pydrake/test/symbolic_test.py

Closes #16013.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16014)

[pydrake] Add symbolic.Expression.Unapply

---

common/schema/BUILD.bazel
common/schema/test/rotation_test.cc
common/schema/test/stochastic_test.cc
common/schema/test/transform_test.cc
common/yaml/BUILD.bazel
common/yaml/test/yaml_io_test.cc
common/yaml/test/yaml_io_test_input_1.yaml
common/yaml/test/yaml_io_test_input_2.yaml
common/yaml/yaml_doxygen.h
common/yaml/yaml_io.h
common/yaml/yaml_read_archive.cc
common/yaml/yaml_read_archive.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15902)

[yaml] Add sugar to read serialized files

---

common/yaml/test/yaml_performance_test.cc

Refer to #12830 for overall background on this test program.
The parsing change in this PR captures the intended usage pattern going forward (where we parse the document data ourselves, instead of having the user hand us a jbeder/yaml-cpp node that has already been parsed).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16050)

[yaml] Update performance test to use internal nodes

---

tools/wheel/dev/image/build-wheel.sh
tools/wheel/dev/image/pip-drake.patch
tools/wheel/dev/image/setup.py

Also copy the LCM Python bits to the [py]drake wheel, and remove the work-around patch.
Fixes #15957.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16056)

Add LCM bits to wheel

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/common/test_utilities/numpy_compare.py
bindings/pydrake/polynomial_py.cc
bindings/pydrake/polynomial_types_pybind.h
bindings/pydrake/test/polynomial_test.py
bindings/pydrake/test/trajectories_test.py
bindings/pydrake/trajectories_py.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16067)

[pydrake] Bind all scalar templates of Polynomial and Trajectory + subclasses

---

bindings/pydrake/BUILD.bazel
common/yaml/BUILD.bazel
common/yaml/test/example_structs.h
common/yaml/test/yaml_read_archive_deprecated_test.cc
common/yaml/test/yaml_read_archive_test.cc
common/yaml/yaml_read_archive.cc
common/yaml/yaml_read_archive.h
common/yaml/yaml_write_archive.cc

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16057)

[yaml] Deprecate the direct use of YAML::Node by users

---

tools/workspace/os.bzl
tools/workspace/pkg_config.bzl

Towards #16001.  Follow-up from #16055.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16068)

[tools] Allow macOS 12 Monterey

---

tools/wheel/dev/image/build-wheel.sh
tools/wheel/dev/test/test-wheel.sh

Fixes #16069.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16071)

Add missing resources to wheel

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/lcm_py.cc
bindings/pydrake/test/lcm_test.py
geometry/BUILD.bazel
geometry/test/drake_visualizer_test.cc
lcm/BUILD.bazel
lcm/drake_mock_lcm.h
systems/lcm/BUILD.bazel

Closes #14606.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16078)

[lcm] Deprecate DrakeMockLcm

---

tools/workspace/README.md
tools/workspace/fmt/repository.bzl
tools/workspace/github.bzl
tools/workspace/ibex/repository.bzl
tools/workspace/new_release.py
tools/workspace/pygame_py/repository.bzl
tools/workspace/pypi_wheel.bzl
tools/workspace/spdlog/repository.bzl

To preview of new docs, see [link](https://github.com/jwnimmer-tri/drake/blob/doc-upgrades/tools/workspace/README.md#semi-automated-monthly-upgrades).  For example results, see #16004.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16005)

[workspace] Further automate monthly externals upgrades

---

tools/wheel/dev/Dockerfile
tools/wheel/dev/build-wheels.sh
tools/wheel/dev/image/build-wheel.sh
tools/wheel/dev/image/provision-base.sh
tools/wheel/dev/image/provision-python.sh
tools/wheel/dev/test/test-wheels.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16087)

[wheel] Fix various comment nits throughout

---

setup/ubuntu/binary_distribution/install_prereqs.sh

Closes #13519.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16086)

[setup] Display a disclaimer when 'apt-get update' is broken

---

doc/_pages/apt.md
doc/_pages/docker.md
doc/_pages/from_binary.md
doc/_pages/getting_help.md
doc/_pages/pip.md

Motivated by https://github.com/RobotLocomotion/drake/issues/15954#issuecomment-967341449.
Note that I have removed the `*emphasis*` markers, because our website does not render italics anymore (sigh).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16090)

[doc] Minor improvements to installation advice

---

common/BUILD.bazel
common/test/value_test.cc
common/value.cc
systems/framework/test/leaf_context_test.cc

Closes: #15434
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16089)

Value: fix types in bad cast message

---

tools/install/colab/setup_drake_colab.py

Closes #15463.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16073)

[colab] Replace installer script with an error stub

---

common/yaml/test/example_structs.h
common/yaml/test/yaml_read_archive_test.cc
common/yaml/yaml_read_archive.cc
common/yaml/yaml_read_archive.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16096)

[yaml] Enable reading more primitive scalar types

---

examples/pendulum/pendulum_geometry.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16100)

[examples/pendulum] Add perception role for PendulumGeometry

---

doc/_pages/clion.md

Update the Drake website instructions for CLion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16081)

Update latest Drake-compatible CLion and Bazel versions

---

doc/_pages/issues.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16093)

[doc] Add  component for issues

---

multibody/plant/test/contact_results_to_lcm_test.cc
systems/framework/diagram_builder.cc
systems/framework/diagram_builder.h
systems/framework/test/diagram_builder_test.cc

Closes #11826.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16082)

[framework] DiagramBuilder fails-fast if used after Build

---

doc/_pages/buildcop.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16103)

[doc] Clarify build cop on duty hours

---

doc/_pages/release_playbook.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16110)

Fix issues noticed during 0.36.0 release process

---

math/rigid_transform.cc
math/roll_pitch_yaw.cc
math/roll_pitch_yaw.h
math/test/rigid_transform_test.cc
math/test/roll_pitch_yaw_test.cc

Closes #14926.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16097)

[math] Improve printing of symbolic RollPitchYaw and RigidTransform

---

doc/_pages/pip.md

Relates #15961.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16117)

[doc] Mention that SNOPT now exists in the pip wheels

---

tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py

Polish hydro surface visualization
1. Modify control for displaying surface edges
- width can now be controlled.
2. The intensity map creates its complementary color more generically.
- Changed the default colors of the intensity map to provide better color contrast.
3. Some function documentation cleaned up.
4. Python-ized Qt slot-signal connection.
Relates #15796
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16115)

[hydro] Refine contact surface visualization

---

bindings/pydrake/solvers/BUILD.bazel
bindings/pydrake/solvers/mixed_integer_optimization_util_py.cc
bindings/pydrake/solvers/mixed_integer_rotation_constraint_py.cc
bindings/pydrake/solvers/test/mixed_integer_optimization_util_test.py
bindings/pydrake/solvers/test/mixed_integer_rotation_constraint_test.py

Been using these, figure they might be useful to someone!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16121)

Bind AddBilinearProductMcCormickEnvelopeSos2 and some MIP rotation constraint types

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py
common/symbolic_expression.cc
common/symbolic_expression.h
common/symbolic_polynomial.cc
common/symbolic_polynomial.h

Fixes #12076.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16091)

update python symbolic bindings

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/program_attribute.cc
solvers/program_attribute.h
solvers/test/mathematical_program_test.cc

As mentioned in #15366
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16092)

Add AddL2NormCost to MathematicalProgram

---

tools/wheel/dev/Dockerfile
tools/wheel/dev/image/build-drake.sh

(Resurrected from https://github.com/RobotLocomotion/pip-drake/pull/13.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16085)

[wheel] Enable Bazel caching across rebuilds

---

common/symbolic_expression_cell.cc

Closes #8648.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16127)

[symbolic] Cite issue number in TODO

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/symbolic_py_unapply.cc
bindings/pydrake/symbolic_py_unapply.h
bindings/pydrake/test/symbolic_test.py
common/symbolic_formula.cc
common/symbolic_formula.h
common/symbolic_formula_cell.h
common/test/symbolic_formula_test.cc

Follow-up from #16014.  Closes #14880.
Also adds bindings for a few Formula constructors / factory functions that were missing and relevant here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16130)

[pydrake] Add symbolic.Formula.Unapply

---

multibody/contact_solvers/BUILD.bazel
multibody/contact_solvers/supernodal_solver.cc
multibody/contact_solvers/supernodal_solver.h
multibody/contact_solvers/test/supernodal_solver_test.cc
tools/workspace/conex/BUILD.bazel
tools/workspace/conex/repository.bzl
tools/workspace/default.bzl

Implements interface for Conex's supernodal solver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/15991)

Implements Conex-based supernodal solver

---

tools/workspace/BUILD.bazel
tools/workspace/conex/BUILD.bazel
tools/workspace/conex/package.BUILD.bazel
tools/workspace/conex/repository.bzl

I overlooked this during #15991 review.
Upgrade conex to latest commit, no reason to start out life with an old archive.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16135)

[workspace] Install the conex LICENSE file

---

multibody/contact_solvers/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16137)

Skip valgrind memcheck tests for supernodal solver

---

multibody/plant/BUILD.bazel
multibody/plant/compliant_contact_manager.cc
multibody/plant/compliant_contact_manager.h
multibody/plant/discrete_update_manager.cc
multibody/plant/discrete_update_manager.h
multibody/plant/multibody_plant_discrete_update_manager_attorney.h
multibody/plant/test/compliant_contact_manager_test.cc

Implements CompliantContactManager::CalcFreeMotionVelocities()
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16119)

Implements CompliantContactManager::CalcFreeMotionVelocities()

---

lcm/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16151)

[lcm] Exclude deprecated //lcm:real from build_components_refresh

---

doc/doxygen_cxx/system_doxygen.py
doc/doxygen_cxx/test/system_doxygen_test.py

Closes: #16148
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16152)

doc: Improve parsing and error reporting for @system diagram syntax

---

geometry/render/dev/BUILD.bazel
geometry/render/dev/render_engine_vtk_minimal_example.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16145)

Create a minimal rendering example for RenderEngineVtk

---

multibody/contact_solvers/BUILD.bazel
multibody/contact_solvers/sap_solver.cc
multibody/contact_solvers/sap_solver.h
multibody/contact_solvers/test/sap_solver_test.cc

Bare bones SAP so that we can commit boilerplate separately for smaller reviews.
Refer to #16080 for more context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16165)

[multibody] Minimum SAP solver infrastructure

---

tools/workspace/common_robotics_utilities/repository.bzl
tools/workspace/intel_realsense_ros/repository.bzl
tools/workspace/meshcat_python/repository.bzl
tools/workspace/uwebsockets/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16167)

Upgrade externals to latest releases 

---

doc/_pages/developers.md

Was reviewing docs for third-party updates (for #16140); while doing so, i think our platform reviewer list is out of date.
FYI @soonhokong (in case y'all have already discussed this and I missed it)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16141)

developers: Update platform reviewer list

---

multibody/contact_solvers/BUILD.bazel
multibody/contact_solvers/system_dynamics_data.cc
multibody/contact_solvers/system_dynamics_data.h
multibody/contact_solvers/test/system_dynamics_data_test.cc

Part of larger SAP solver PR #16080.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16169)

[multibody] SystemDynamicsData describes both forward and inverse dynamics

---

multibody/contact_solvers/BUILD.bazel
multibody/contact_solvers/block_sparse_linear_operator.cc
multibody/contact_solvers/block_sparse_linear_operator.h
multibody/contact_solvers/linear_operator.cc
multibody/contact_solvers/linear_operator.h
multibody/contact_solvers/sparse_linear_operator.h
multibody/contact_solvers/test/block_sparse_linear_operator_test.cc
multibody/contact_solvers/test/linear_operator_test.cc
multibody/contact_solvers/test/sparse_linear_operator_test.cc

Towards #16080.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16166)

[multibody] LinearOperator assembly into a BlockSparseMatrix

---

systems/primitives/port_switch.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16182)

[primitives] Add missing @ingroup doxygen tag to PortSwitch

---

multibody/parsing/test/detail_sdf_parser_test.cc
multibody/parsing/test/detail_urdf_parser_test.cc
multibody/tree/BUILD.bazel
multibody/tree/rotational_inertia.cc
multibody/tree/rotational_inertia.h
multibody/tree/spatial_inertia.cc
multibody/tree/spatial_inertia.h
multibody/tree/test/rotational_inertia_test.cc
multibody/tree/test/spatial_inertia_test.cc
multibody/tree/unit_inertia.h

Resolves #16058.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16065)

Fix error message when user sets a bad SpatialInertia.

---

multibody/tree/test/spatial_inertia_test.cc

Closes #16186.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16188)

Fix decimal-point matching across Mac/Ubuntu platforms

---

multibody/contact_solvers/BUILD.bazel
multibody/contact_solvers/sap_solver.cc
multibody/contact_solvers/sap_solver.h
multibody/contact_solvers/test/sap_solver_test.cc

Towards #16080 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16170)

[multibody] SAP data pre-processing

---

multibody/fixed_fem/dev/BUILD.bazel

Hotfix for #16174.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16198)

[fixed_fem] Disable PETSc tests under memcheck,ubsan

---

bindings/pydrake/geometry_py_render.cc
bindings/pydrake/test/geometry_render_engine_gl_test.py
bindings/pydrake/test/geometry_render_test.py
bindings/pydrake/test/geometry_scene_graph_test.py

This is replacing #14828 with an active branch intended to be merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16201)

[pydrake] Bind RenderEngineGlParams

---

doc/_pages/release_playbook.md

Relates to #16105.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16209)

[doc] Add whl release playbook

---

bindings/pydrake/geometry_py_hydro.cc
bindings/pydrake/geometry_py_scene_graph.cc
bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/test/geometry_hydro_test.py
bindings/pydrake/test/geometry_scene_graph_test.py
geometry/proximity/polygon_surface_mesh.cc
geometry/proximity/polygon_surface_mesh.h
geometry/query_object.h
geometry/query_results/contact_surface.h

Closes #16212.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16219)

[pydrake] Bind some hydroelastic-related classes and functions

---

manipulation/models/ycb/BUILD.bazel
manipulation/models/ycb/test/parse_test.cc

Towards #16216.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16220)

[ycb] Swich models demo to use meshcat

---

geometry/render/dev/render_engine_vtk_minimal_example.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16225)

[geometry/dev] Configure camera pose through gflags

---

tools/wheel/build-wheels
tools/wheel/image/provision-python.sh

A portion of #15959.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16226)

[wheel] Add support for manylinux python3.8

---

tools/BUILD.bazel
tools/lint/install_lint.bzl
tools/wheel/image/build-drake.sh
tools/workspace/BUILD.bazel
tools/workspace/drake_visualizer/BUILD.bazel
tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/BUILD.bazel
tools/workspace/drake_visualizer/drake_visualizer_disabled.py
tools/workspace/drake_visualizer/test/drake_visualizer_bazel_test.py

Relates to #16215.
At the moment, the _only_ CI coverage of this build option is the wheel builds, which are run nightly (not pre-merge).
FYI -- Anzu-master-Drake-PR has passed vs this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16221)

[tools] Offer option to disable drake-visualizer

---

multibody/contact_solvers/BUILD.bazel
multibody/contact_solvers/sap_solver.cc
multibody/contact_solvers/sap_solver.h
multibody/contact_solvers/test/sap_solver_test.cc

Implements SAP solver described [here](https://arxiv.org/abs/2110.10107).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16080)

[multibody] Implements SapSolver::SolveWithGuess()

---

doc/_pages/installation.md
doc/_pages/pip.md
doc/_pages/release_playbook.md

Missed in #16226.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16242)

[doc] Fix up documentation of Python 3.8 support

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/multibody_plant_config.h
multibody/plant/multibody_plant_config_functions.cc
multibody/plant/multibody_plant_config_functions.h
multibody/plant/test/multibody_plant_config_functions_test.cc
multibody/plant/test/multibody_plant_hydroelastic_test.cc
multibody/plant/test/multibody_plant_test.cc

Relevant to: #15796
- Add C++ API get/set_contact_surface_representation().
- Update MultibodyPlantConfig
- Add python bindings
- Add tests for above
co-authored by: DamrongGuoy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16238)

[hydro, multibody] Add public API to choose triangles or polygons.

---

multibody/fixed_fem/dev/BUILD.bazel
multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc
multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h
multibody/fixed_fem/dev/schur_complement.cc
multibody/fixed_fem/dev/schur_complement.h
multibody/fixed_fem/dev/test/deformable_box_test.cc
multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16230)

[fem] Support Schur complement in PETSc

---

multibody/contact_solvers/sap_solver.cc
multibody/contact_solvers/sap_solver.h
multibody/contact_solvers/test/sap_solver_test.cc

Given we merged #16240 quickly due to its high priority, I address here the review comments from #16240.
I like this version significantly better since we can get high accuracy while at the same time we can exit gracefully if the problem does not make any progress due to round-off errors (that is, the solver did indeed reach the best solution modulo round-off errors).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16243)

SAP: Improve stopping criteria

---

doc/doxygen_cxx/build.py

Fixes errors seen in CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16246)

[doc] Hot-fix for unimportant doxygen error leaks

---

multibody/fixed_fem/dev/BUILD.bazel
multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.cc
multibody/fixed_fem/dev/petsc_symmetric_block_sparse_matrix.h
multibody/fixed_fem/dev/schur_complement.cc
multibody/fixed_fem/dev/schur_complement.h
multibody/fixed_fem/dev/test/deformable_box_test.cc
multibody/fixed_fem/dev/test/petsc_symmetric_block_sparse_matrix_test.cc

This reverts commit 60551ef64510922df8cad7a3532ba5111f8b99ad.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16247)

Revert "[fem] Support Schur complement in PETSc (#16230)"

---

bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/custom_test.py
systems/framework/leaf_system.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16251)

[py/systems] Add missing bindings for LeafSystem::Declare*Event

---

bindings/pydrake/systems/controllers_py.cc
bindings/pydrake/systems/test/controllers_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16254)

Add binding for InverseDynamicsController::get_multibody_plant_for_control

---

systems/sensors/beam_model.h
systems/sensors/image_to_lcm_image_array_t.h
systems/sensors/image_writer.h
systems/sensors/lcm_image_array_to_images.h
systems/sensors/optitrack_sender.h
systems/sensors/rotary_encoders.h

Add missing diagrams, update others for consistency, and fix a text wrapping
problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16194)

sensors: Add/update doxygen block diagrams

---

examples/mass_spring_cloth/BUILD.bazel
examples/mass_spring_cloth/README.md
examples/mass_spring_cloth/run_cloth_spring_model.cc

Towards #16216
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16248)

[examples] Use meshcat to visualize mass spring example

---

tools/wheel/image/build-dependencies.sh
tools/wheel/image/build-drake.sh
tools/wheel/image/build-vtk.sh
tools/wheel/image/build-wheel.sh
tools/wheel/image/provision-base.sh
tools/wheel/image/provision-python.sh
tools/wheel/test/provision.sh
tools/wheel/test/test-wheel.sh

Add slightly more strict error checking to the various Wheel scripts. It's unlikely this will actually catch anything "new", but it's mostly being done to increase consistency across various scripts of this nature, particularly with the (still in progress, as of writing) refactoring work being done to the VTK scripts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16260)

"Clean up" wheel scripts

---

geometry/meshcat.cc

While using Meshcat::Flush() in my experiments, I saw the dreaded "you
should never see this message" message. After even more reading of the
uWebsockets code, it seems that drainage is not actually scheduled to
occur between loop->defer calls. My attempts to request drainage
directly also failed. I believe there are no better mechanisms
available in the public API than to simply sleep.
I've documented my attempts directly in the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16256)

[meshcat] Add sleep to Meshcat::Flush()

---

geometry/render/dev/BUILD.bazel
geometry/render/dev/test/picosha2_compile_test.cc
tools/workspace/default.bzl
tools/workspace/picosha2/BUILD.bazel
tools/workspace/picosha2/package.BUILD.bazel
tools/workspace/picosha2/repository.bzl

For render client / server validation of transmitted scene, we propose a sha256 hash.
Relates: #16234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16232)

add picosha2 dependency for computing sha256 sums

---

systems/lcm/lcm_scope_system.h
systems/lcm/lcm_subscriber_system.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16196)

message_passing: Add doxygen block diagrams

---

bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/custom_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16266)

[py/systems] Add bindings for UnrestrictedUpdate and DeclareForced*Event

---

multibody/plant/contact_results_to_lcm.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16200)

multibody: Add doxygen block diagrams

---

geometry/render/dev/BUILD.bazel
geometry/render/dev/test/libcurl_compile_test.cc
setup/mac/binary_distribution/Brewfile
setup/ubuntu/binary_distribution/install_prereqs.sh
setup/ubuntu/binary_distribution/packages-bionic.txt
setup/ubuntu/binary_distribution/packages-focal.txt
setup/ubuntu/source_distribution/install_prereqs.sh
setup/ubuntu/source_distribution/packages-bionic.txt
setup/ubuntu/source_distribution/packages-focal-satisfy.txt
tools/workspace/default.bzl
tools/workspace/libcurl/BUILD.bazel
tools/workspace/libcurl/repository.bzl

For communicating with the render server.
Fixes #16125.
What do we want to do about the `apt-get satisfy` scenario?
Relates: #16234
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16233)

add libcurl dependency

---

bindings/pydrake/geometry_py_visualizers.cc
bindings/pydrake/test/geometry_visualizers_test.py
geometry/meshcat_visualizer.cc
geometry/meshcat_visualizer.h
geometry/test/meshcat_visualizer_test.cc

Related to #16265
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16271)

[meshcat] Add option to disable SetTransform during recording

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/_geometry_extra.py
bindings/pydrake/geometry_py.cc
bindings/pydrake/test/geometry_visualizers_test.py

Resolves #16099
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16273)

[meshcat] Provides StartMeshcat() for Deepnote/Colab

---

geometry/scene_graph.h

Also, remove some stale references to LCM stuff.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16202)

SceneGraph: Update doxygen block diagram

---

tutorials/README.md
tutorials/rendering_multibody_plant.ipynb

I've almost removed DrakeVisualizer, related to #16216.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16277)

[tutorials] Update rendering_multibody_plant to new Meshcat

---

doc/_pages/bazel.md

Relates to #14928
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16276)

doc: Update example asan command

---

doc/_pages/buildcop.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16275)

doc: Update buildcop instructions for dev failures

---

tutorials/BUILD.bazel
tutorials/README.md
tutorials/index.ipynb

Towards #13683
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16279)

[tutorials] Update README.md to include deepnote/colab; add tutorial index

---

systems/sensors/beam_model.h
systems/sensors/test/beam_model_test.cc

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16282)

[sensors] Add example For BeamModel

---

examples/acrobot/acrobot_plant.h
examples/allegro_hand/allegro_lcm.h
examples/bead_on_a_wire/bead_on_a_wire.h
examples/bouncing_ball/bouncing_ball.h
examples/kuka_iiwa_arm/kuka_torque_controller.cc
examples/kuka_iiwa_arm/kuka_torque_controller.h
examples/kuka_iiwa_arm/lcm_plan_interpolator.cc
examples/kuka_iiwa_arm/lcm_plan_interpolator.h
examples/particles/particle.h
examples/planar_gripper/planar_gripper_lcm.h
examples/planar_gripper/planar_manipuland_lcm.h
examples/rimless_wheel/rimless_wheel.h
examples/rod2d/rod2d.h
examples/scene_graph/bouncing_ball_plant.h
examples/scene_graph/solar_system.h
examples/van_der_pol/van_der_pol.cc
examples/van_der_pol/van_der_pol.h

Also:
* add port names to a Diagram
* fix a doxygen comment separated from its class declaration
* fix inconsistent variable subscripts found in comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16204)

examples: Add/update doxygen block diagrams

---

geometry/optimization/test/vpolytope_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16287)

[geometry/optimization] fix vpolytope test for mosek

---

common/symbolic_environment.h

Resolves #16284 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16288)

Document the behavior of Environment::insert() when the key already exists

---

systems/controllers/BUILD.bazel
systems/controllers/test/linear_quadratic_regulator_test.cc

Resolves #10679
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16298)

Add Acrobot unit test for LQR

---

systems/controllers/linear_quadratic_regulator.h

It was documented in one of the LQR methods, but not all of them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16302)

[controllers] Document the N term in LinearQuadraticRegulator.

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/mathematical_program_test.cc
solvers/test/scaled_diagonally_dominant_matrix_test.cc

MathematicalProgram can add different types of nonnegative polynomial constraint with the same API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16289)

Add AddNonnegativePolynomialConstraint function.

---

geometry/proximity/polygon_surface_mesh.cc
geometry/proximity/polygon_surface_mesh.h
geometry/proximity/test/polygon_surface_mesh_test.cc

Relevant to issue #16244.
I have created another PR #16258 for ease of testing the rolling sphere example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16257)

[geometry] Take care of centroids of zero-area polygons in PolygonSurfaceMesh

---

tutorials/multibody_plant_autodiff_mass.ipynb

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16317)

[tutorials] intializeAutoDiff => InitializeAutoDiff in tutorial

---

tutorials/README.md
tutorials/dynamical_systems.ipynb

Render latex properly in deepnote
remove matplotlib notebook
Resolve #16285
Deepnote notebook is here: https://deepnote.com/project/Tutorials-K0_FCa7yQX2kDWBx3-2RmQ/%2Fdynamical_systems.ipynb
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16314)

[tutorials] fixup dynamical_systems tutorial

---

tutorials/linear_program.ipynb

Notebook is here:
https://deepnote.com/project/Tutorials-K0_FCa7yQX2kDWBx3-2RmQ/%2Flinear_program.ipynb/#00026-7be049a7-afc4-4dfc-901b-06032f82e884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16315)

[tutorials] fixup lp tutorial for deepnote

---

doc/_pages/python_bindings.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16323)

[doc] Link directly to pip instructions

---

bindings/pydrake/geometry_py_optimization.cc
bindings/pydrake/test/geometry_optimization_test.py
geometry/optimization/graph_of_convex_sets.cc
geometry/optimization/graph_of_convex_sets.h
geometry/optimization/test/graph_of_convex_sets_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16299)

Enable removing Vertices and Edges from GraphOfConvexSets

---

geometry/optimization/graph_of_convex_sets.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16330)

Fix sporadic segfault in RemoveVertex

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
geometry/optimization/hpolyhedron.cc
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/exponential_cone_program_examples.cc

The old name is too verbose.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16309)

Rename to AddMaximizeLogDeterminantCost.

---

multibody/fixed_fem/dev/BUILD.bazel
tools/workspace/petsc/patches/sbaijfact2.patch
tools/workspace/petsc/repository.bzl

Prevent 3x3 block Cholesky for PETSc SBAIJ matrix from going out of bound.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16328)

[fem] Fix 3x3 block Cholesky in PETSc

---

tools/install/bazel/test/drake_bazel_installed_test.py
tools/workspace/buildifier/repository.bzl
tools/workspace/common_robotics_utilities/repository.bzl
tools/workspace/json/repository.bzl
tools/workspace/petsc/repository.bzl
tools/workspace/rules_python/repository.bzl
tools/workspace/tinyobjloader/repository.bzl
tools/workspace/uwebsockets/repository.bzl
tools/workspace/voxelized_geometry_tools/package.BUILD.bazel
tools/workspace/voxelized_geometry_tools/repository.bzl

Working towards #16301
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16324)

Upgrade externals to latest releases

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
multibody/plant/contact_results_to_lcm.cc
multibody/plant/contact_results_to_lcm.h
multibody/plant/test/contact_results_to_lcm_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16329)

[plant] Remove deprecated code 2022-01

---

common/test/symbolic_polynomial_test.cc

In a dev branch, accidentally someone makes a change to `symbolic::Polynomial` in https://github.com/AlexandreAmice/drake/commit/f436034dbffbd4404baeec9d63bf8cc2da34df8d. The change is incorrect, but our symbolic_polynomial_test.cc doesn't catch the error. In this PR I add these additional tests to make sure such change on `symbolic::Polynomial` should be caught.
A dev branch accidentally changes symbolic::Polynomial incorrectly, but our unit test fails to capture that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16332)

Add more tests on symbolic::Polynomial on ndeterminates/decision_variables

---

tools/workspace/new_release.py

Address some issues found in #16301
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16335)

[workspace] Improve new_release heuristics

---

multibody/tree/test/unit_inertia_test.cc
multibody/tree/unit_inertia.h

Towards #16342.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16349)

[multibody] Add unit inertia for ellipsoid

---

geometry/geometry_properties.h

Per #15809.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16360)

[geometry] Remove date target in TODO

---

bindings/pydrake/geometry_py_common.cc
bindings/pydrake/test/geometry_common_test.py
geometry/shape_specification.cc
geometry/shape_specification.h
geometry/test/shape_specification_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16354)

[geometry] Implements `CalcVolume` for basic `Shape`s

---

CMakeLists.txt

Fixes #14238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16283)

Allow CMake build type to be case-insensitive

---

bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/general_test.py

This should enable us to explore solutions to #1387 completely in python.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16352)

[pydrake] Bind SystemVisitor and Diagram introspection methods

---

doc/_pages/bazel.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16371)

[doc] Explain the work-around for a kcov build error

---

multibody/parsing/BUILD.bazel
multibody/parsing/detail_mujoco_parser.cc
multibody/parsing/detail_mujoco_parser.h
multibody/parsing/test/detail_mujoco_parser_test.cc
tools/workspace/default.bzl
tools/workspace/dm_control/BUILD.bazel
tools/workspace/dm_control/files.bzl
tools/workspace/dm_control/package.BUILD.bazel
tools/workspace/dm_control/repository.bzl

First step towards #16369.
This PR simply establishes the class and the test files. The following
PRs will start adding more meaningful functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16370)

[multibody] Establish detail_mujoco_parser.

---

doc/_release-notes/v0.38.0.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16382)

[doc] Deprecate drake-visualizer on macOS

---

systems/framework/diagram_builder.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16384)

[doc] Add a tip for improving DiagramBuilder performance

---

tools/workspace/stduuid/repository.bzl

Working towards #16301
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16387)

[workspace] Upgrade stduuid to latest commit

---

doc/_pages/from_source.md
doc/_pages/installation.md
doc/_pages/rosetta2.md

Closes #14555.
~This PR also contains a small unrelated docs fixup for today's release notes.~
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16381)

[doc] Explain how to run Drake under Rosetta 2

---

multibody/tree/test/unit_inertia_test.cc
multibody/tree/unit_inertia.cc
multibody/tree/unit_inertia.h

Fixes #16342
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16357)

[multibody] Add unit inertia for capsule

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/mathematical_program_test.cc
solvers/test/scaled_diagonally_dominant_matrix_test.cc

As mentioned in the comment https://github.com/RobotLocomotion/drake/pull/16289#issuecomment-1007340293
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16375)

deprecate MathematicalProgram::NewNonnegativePolynomial.

---

doc/_pages/credits.md

Add myself to credits.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16395)

Modify credits

---

multibody/parsing/BUILD.bazel
multibody/parsing/detail_mujoco_parser.cc
multibody/parsing/detail_tinyxml.cc
multibody/parsing/detail_tinyxml.h
multibody/parsing/test/detail_mujoco_parser_test.cc

Towards #16369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16378)

[multibody] Parse mujoco geometry (but not meshes)

---

doc/pydrake/build.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16402)

[doc] Provide better error messages when sphinx-build isn't found

---

geometry/proximity/mesh_intersection.cc
geometry/proximity/mesh_intersection.h
geometry/proximity/test/mesh_intersection_test.cc

- Move ClipPolygonByHalfSpace() from being a static member of SurfaceVolumeIntersector
to be a free function.
- Move its helper CalcIntersection() as well.
Once this PR merges, I'll use it in #16365.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16374)

[geometry] Refactor ClipPolygonByHalfSpace() for code reuse.

---

systems/primitives/test/multilayer_perceptron_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16406)

[hotfix] fix random generator seed in multilayer_perceptron_test

---

tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16411)

[workspace] Add issue number to drake-visualizer deprecation

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/second_order_cone_program_examples.cc
solvers/test/second_order_cone_program_examples.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16373)

Return geometric mean cost

---

multibody/tree/test/unit_inertia_test.cc
multibody/tree/unit_inertia.cc
multibody/tree/unit_inertia.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16401)

Improve code and tests for UnitInertia for a capsule.

---

bindings/pydrake/lcm_py.cc
bindings/pydrake/test/lcm_test.py

Noticed via #16263.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16413)

[pydrake] Bind DrakeLcmInterface::get_lcm_url

---

tools/skylark/drake_cc.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16412)

[tools] Enable Werror=literal-conversion with Clang

---

bindings/pydrake/common/BUILD.bazel
common/test_utilities/drake_py_unittest_main.py
doc/_pages/bazel.md
tools/dynamic_analysis/BUILD.bazel
tools/dynamic_analysis/kcov.sh
tools/dynamic_analysis/kcoverage.py
tools/jupyter/jupyter_py.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16392)

[tools] Collect python test coverage data with kcov

---

common/yaml/test/yaml_doxygen_test.cc
common/yaml/yaml_doxygen.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16416)

[yaml] Fix unit test of fmt output

---

tools/wheel/README.rst

Add a brief document explaining the build-wheels tool. This includes both some basic usage information, particularly more detailed descriptions and rationale for some of the arguments, as well as some brief information on the script's internal operation.
Fixes #16105.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16417)

Add README for build-wheels

---

bindings/pydrake/systems/primitives_py.cc
bindings/pydrake/systems/test/primitives_test.py
systems/primitives/multilayer_perceptron.cc
systems/primitives/multilayer_perceptron.h
systems/primitives/test/multilayer_perceptron_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16410)

[systems/primitives] Add BatchOutput to MultilayerPerceptron

---

bindings/pydrake/geometry_py_optimization.cc
bindings/pydrake/test/geometry_optimization_test.py
geometry/optimization/test/vpolytope_test.cc
geometry/optimization/vpolytope.cc
geometry/optimization/vpolytope.h

Use qhull to compute the volume
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16409)

Compute volume of a VPolytope.

---

multibody/plant/contact_model_doxygen.h

Doxygen doesn't understand line wrap in commands.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16429)

multibody doc: Fix a broken section title

---

bindings/pydrake/systems/test/primitives_test.py

Use slicing to update output variable in place.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16443)

[hotfix] Fix bug in MLP binding test

---

bindings/pydrake/geometry_py_visualizers.cc
bindings/pydrake/test/geometry_visualizers_test.py
bindings/pydrake/visualization/BUILD.bazel
bindings/pydrake/visualization/meldis.py
bindings/pydrake/visualization/test/meldis_test.py

This probably should have been part of #16263, but oh well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16450)

[meldis] Add unit test for ViewerApplet

---

bindings/pydrake/multibody/meshcat_py.cc
bindings/pydrake/multibody/test/meshcat_test.py
bindings/pydrake/visualization/BUILD.bazel
bindings/pydrake/visualization/meldis.py
bindings/pydrake/visualization/test/meldis_test.py
examples/multibody/strandbeest/README.md
examples/multibody/strandbeest/run_with_motor.cc

Towards #16216.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16436)

[meldis] Display point contact results

---

doc/_pages/documentation_instructions.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16453)

[doc] Give better examples for previewing the documentation

---

bindings/pydrake/geometry_py_visualizers.cc
bindings/pydrake/visualization/meldis.py
geometry/meshcat.cc
geometry/meshcat.h
geometry/test/meshcat_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16445)

[meldis] Auto-quit when idle for more than 15 minutes

---

geometry/proximity/BUILD.bazel
geometry/proximity/field_intersection.cc
geometry/proximity/field_intersection.h
geometry/proximity/mesh_intersection.cc
geometry/proximity/mesh_intersection.h
geometry/proximity/test/field_intersection_test.cc
geometry/proximity/test/mesh_intersection_test.cc

This PR is supposed to rebase on #16458. ~~#16363.~~
Once #16458 ~~#16363~~ is merged, mesh_plane_intersection.h and mesh_plane_intersection.cc will "revert".  For now, please do not review those two files (since they'll be reviewed separately in #16458 ~~#16363~~.)
This PR is a part of a multi-PRs strategy. They should merge in a consistent order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16365)

[geometry] Contact surface from two compliant meshes with pressure

---

geometry/query_object.h

Review this PR after #16366 is merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16471)

[geometry] Document QueryObject to support compliant-compliant contact.

---

doc/pydrake/BUILD.bazel
doc/pydrake/conf.py
doc/pydrake/searchbox.html

Towards #7559.
The "Search all of Drake..." box is new as of this PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16473)

[doc] Add full website DDG search to pydrake search panel

---

doc/defs.py

Fixes #14077.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16474)

Ensure Doxygen runs in a UTF-8 locale

---

multibody/multibody_doxygen.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16415)

Enhance documentation and notation for offset frames.

---

bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/framework_py_systems.cc
bindings/pydrake/systems/test/general_test.py
systems/framework/diagram.h
systems/framework/diagram_builder.cc
systems/framework/diagram_builder.h
systems/framework/test/diagram_builder_test.cc

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16477)

[framework] Add DiagramBuilder::connection_map function

---

multibody/parsing/detail_mujoco_parser.cc
multibody/parsing/test/detail_mujoco_parser_test.cc

Towards #16369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16466)

[multibody] Parse mujoco inertial bodies

---

multibody/plant/compliant_contact_manager.cc
multibody/plant/multibody_plant.cc
multibody/plant/test/compliant_contact_manager_test.cc
multibody/plant/test/multibody_plant_hydroelastic_test.cc

This PR is supposed to rebase on PR #16366.
Once #16366 merges, this PR will change only compliant_contact_manager.cc and multibody_plant.cc. Please do not review other files.
This PR is a part of a multi-PRs strategy. They should merge in a consistent order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16367)

[multibody] hydroelastic compliant-compliant contact

---

multibody/parsing/test/detail_sdf_parser_test.cc
multibody/parsing/test/detail_urdf_parser_test.cc
multibody/tree/test/spatial_inertia_test.cc
multibody/tree/unit_inertia.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16469)

[multibody] Fix to enable Expression in MakeFromCentralInertia

---

tools/workspace/rules_pkg/repository.bzl

Working towards #16481
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16485)

[workspace] Upgrade rules_pkg to latest release 0.6.0

---

multibody/fem/BUILD.bazel
multibody/fem/calc_lame_parameters.cc
multibody/fem/calc_lame_parameters.h
multibody/fem/test/calc_lame_parameters_test.cc

Towards #16492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16497)

[fem] Calculate Lame parameters from Young's modulus and Poisson ratio

---

multibody/fem/BUILD.bazel
multibody/fem/damping_model.cc
multibody/fem/damping_model.h
multibody/fem/test/damping_model_test.cc

Towards #16492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16496)

[fem] Add Rayleigh damping model

---

geometry/proximity/test/contact_surface_utility_test.cc
geometry/proximity/test/distance_sphere_to_shape_test.cc
geometry/proximity/test/hydroelastic_callback_test.cc
geometry/proximity/test/hydroelastic_internal_test.cc
geometry/proximity/test/obj_to_surface_mesh_test.cc
geometry/proximity/test/penetration_as_point_pair_callback_test.cc
geometry/proximity/test/plane_test.cc
geometry/proximity/test/posed_half_space_test.cc
geometry/render/gl_renderer/test/no_render_engine_gl_test.cc
geometry/render/gl_renderer/test/opengl_geometry_test.cc
geometry/render/gl_renderer/test/render_engine_gl_test.cc
geometry/render/gl_renderer/test/shader_program_test.cc
geometry/render/gl_renderer/test/shape_meshes_test.cc
geometry/render/test/render_camera_test.cc
geometry/render/test/render_engine_test.cc
geometry/render/test/render_engine_vtk_test.cc
geometry/render/test/render_label_test.cc
geometry/test/frame_kinematics_vector_test.cc
geometry/test/geometry_frame_test.cc
geometry/test/geometry_instance_test.cc
geometry/test/geometry_properties_test.cc
geometry/test/geometry_state_test.cc
geometry/test/internal_geometry_test.cc
geometry/test/proximity_engine_test.cc
geometry/test/proximity_properties_test.cc
geometry/test/query_object_test.cc
geometry/test/rgba_test.cc
geometry/test/scene_graph_test.cc
geometry/test/shape_specification_test.cc

See https://drake.mit.edu/styleguide/cppguide.html#Exceptions.
Towards #16514.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16510)

[geometry] Don't spuriously test for exception subtypes

---

systems/analysis/test/antiderivative_function_test.cc
systems/analysis/test/hermitian_dense_output_test.cc
systems/analysis/test/initial_value_problem_test.cc
systems/analysis/test/integrator_base_test.cc
systems/analysis/test/scalar_initial_value_problem_test.cc
systems/analysis/test/scalar_view_dense_output_test.cc
systems/analysis/test/simulator_test.cc
systems/framework/test/cache_entry_test.cc
systems/framework/test/cache_test.cc
systems/framework/test/diagram_builder_test.cc
systems/framework/test/diagram_context_test.cc
systems/framework/test/diagram_test.cc
systems/framework/test/discrete_values_test.cc
systems/framework/test/input_port_test.cc
systems/framework/test/leaf_context_test.cc
systems/framework/test/leaf_system_test.cc
systems/framework/test/output_port_test.cc
systems/framework/test/system_test.cc
systems/framework/test/value_to_abstract_value_test.cc
systems/optimization/test/system_constraint_adapter_test.cc
systems/primitives/test/gain_test.cc
systems/primitives/test/linear_system_test.cc
systems/primitives/test/linear_transform_density_test.cc
systems/rendering/test/multibody_position_to_geometry_pose_test.cc
systems/sensors/test/image_writer_test.cc

See https://drake.mit.edu/styleguide/cppguide.html#Exceptions.
Towards #16514.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16512)

[systems] Don't spuriously test for exception subtypes

---

common/test/pointer_cast_test.cc
common/test/symbolic_chebyshev_basis_element_test.cc
common/test/symbolic_expression_matrix_test.cc
common/test/symbolic_generic_polynomial_test.cc
common/test/symbolic_monomial_basis_element_test.cc
common/test/symbolic_monomial_test.cc
common/test/symbolic_polynomial_basis_element_test.cc
common/test/symbolic_rational_function_test.cc
common/test/type_safe_index_test.cc
solvers/test/choose_best_solver_test.cc
solvers/test/constraint_test.cc
solvers/test/equality_constrained_qp_solver_test.cc
solvers/test/gurobi_solver_test.cc
solvers/test/mathematical_program_result_test.cc
solvers/test/mathematical_program_test.cc
solvers/test/mosek_solver_test.cc
solvers/test/solver_base_test.cc
solvers/test/solver_options_test.cc

See https://drake.mit.edu/styleguide/cppguide.html#Exceptions.
Towards #16514.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16513)

[common,solvers] Don't spuriously test for exception subtypes

---

doc/_pages/developers.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16520)

[doc] Add xuchenhan-tri as a platform reviwer

---

multibody/meshcat/contact_visualizer.cc
multibody/meshcat/contact_visualizer.h
multibody/meshcat/point_contact_visualizer.h
multibody/meshcat/test/contact_visualizer_test.cc
multibody/plant/internal_geometry_names.cc
multibody/plant/internal_geometry_names.h
multibody/plant/test/internal_geometry_names_test.cc

Towards #16476 and #15738.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16493)

[meshcat] Use body names for point contact visualization

---

multibody/plant/multibody_plant.h

Closes: #14107
Revise links to point to the parsing reference, and modernize
instances of "SDF" to "SDFormat".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16522)

[doc] Fix broken links in multibody doc

---

doc/_pages/from_source.md
setup/ubuntu/source_distribution/install_prereqs.sh
tools/wheel/image/provision-base.sh
tools/workspace/drake_visualizer/image/provision.sh

Working towards #16447.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16523)

setup: Upgrade recommended Bazel version to 5.0

---

bindings/pydrake/multibody/meshcat_py.cc
bindings/pydrake/multibody/test/meshcat_test.py
multibody/meshcat/contact_visualizer.cc
multibody/meshcat/contact_visualizer.h
multibody/meshcat/test/contact_visualizer_test.cc

Towards #15738.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16515)

[meshcat] Wire up geometry names for point contact visualization

---

examples/acrobot/Acrobot.urdf
examples/acrobot/Acrobot_no_collision.urdf
examples/pendulum/Pendulum.urdf
examples/pendulum/test/PendulumWithFriction.urdf
examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf
examples/quadrotor/quadrotor.urdf
examples/simple_four_bar/FourBar.urdf
examples/simple_four_bar/FourBar2.urdf
multibody/benchmarks/acrobot/double_pendulum.urdf

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16535)

[urdf] Delete wrong and/or unused namespace declarations

---

multibody/fem/BUILD.bazel
multibody/fem/matrix_utilities.cc
multibody/fem/matrix_utilities.h
multibody/fem/test/matrix_utilities_test.cc
multibody/fixed_fem/dev/BUILD.bazel
multibody/fixed_fem/dev/corotated_model_data.h
multibody/fixed_fem/dev/test/constitutive_model_test_utilities.cc

Follow up of #16508.
Towards #16492.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16509)

[fem] Move matrix utilities out of dev

---

solvers/mosek_solver.cc

As explained in https://docs.mosek.com/latest/capi/debugging-tutorials.html#debugging-tutorials to print the solution summary after solving mosek.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16528)

Mosek also print solution summary.

---

geometry/render/render_engine_vtk_factory.h

Closes: #13179
Also fix a nearby formatting blunder.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16531)

[geometry,doc] Clarify RenderEngineVtk texture assignment

---

bindings/pydrake/systems/primitives_py.cc
bindings/pydrake/systems/test/primitives_test.py
systems/primitives/multilayer_perceptron.cc
systems/primitives/multilayer_perceptron.h
systems/primitives/test/multilayer_perceptron_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16542)

[primitives] Add MultilayerPerceptron::GetMutableParameters()

---

multibody/fem/BUILD.bazel
multibody/fem/schur_complement.cc
multibody/fem/schur_complement.h
multibody/fem/test/schur_complement_test.cc

Towards #16492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16498)

[fem] Move SchurComplement out of dev

---

bindings/pydrake/math_py.cc
bindings/pydrake/test/math_test.py
geometry/optimization/test/hyperellipsoid_test.cc
math/rigid_transform.h
math/test/rigid_transform_test.cc

Closes #16524.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16541)

Rename RigidTransform::IsIdentityToEpsilon to IsNearlyIdentity

---

multibody/parsing/detail_mujoco_parser.cc
multibody/parsing/test/detail_mujoco_parser_test.cc

Towards #16369
The relevant XML documentation is here: https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-joint
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16525)

[multibody] Parse MuJoCo joint elements

---

doc/_release-notes/v0.39.0.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16555)

[doc] Fix markup in v0.39.0 release notes

---

geometry/render/dev/render_client_gltf.cc

Document how / why the UpdateViewpoint transform modification needs to happen, and mark when it can be removed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16533)

[geometry/dev] cleanup gltf UpdateViewpoint transform modification

---

doc/_pages/documentation_instructions.md
doc/_pages/release_playbook.md
tools/workspace/mirror_to_s3.py

Resolves #16379.
Depends on ci PR [#134](https://github.com/RobotLocomotion/drake-ci/pull/134)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16539)

Switch documentation and mirroring builds to Ubuntu 20.04 Focal

---

bindings/pydrake/systems/framework_py_semantics.cc
bindings/pydrake/systems/test/general_test.py
multibody/meshcat/contact_visualizer.cc
systems/framework/diagram_builder.cc
systems/framework/diagram_builder.h
systems/framework/test/diagram_builder_test.cc

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16563)

[framework] Add DiagramBuilder::ConnectToSame sugar

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/sap_contact_problem.cc
multibody/contact_solvers/sap/sap_contact_problem.h
multibody/contact_solvers/sap/test/sap_contact_problem_test.cc

Towards #16543.
This first PR introduces `SapContactProblem` and defines some terminology to be used throughout the PR train.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16548)

Introduce SapContactProblem

---

multibody/fem/BUILD.bazel
multibody/fem/petsc_symmetric_block_sparse_matrix.cc
multibody/fem/petsc_symmetric_block_sparse_matrix.h
multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc
multibody/fixed_fem/dev/BUILD.bazel

Towards #16492
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16550)

[fem] Move Petsc matrix out of dev

---

bindings/pydrake/systems/primitives_py.cc
bindings/pydrake/systems/test/primitives_test.py
systems/primitives/multilayer_perceptron.cc
systems/primitives/multilayer_perceptron.h
systems/primitives/test/multilayer_perceptron_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16572)

[primitives] Add (optional) gradients to MultilayerPerceptron::BatchOutput

---

multibody/fem/BUILD.bazel
multibody/fem/test/constitutive_model_test_utilities.cc
multibody/fem/test/constitutive_model_test_utilities.h
multibody/fixed_fem/dev/BUILD.bazel
multibody/fixed_fem/dev/test/corotated_model_test.cc
multibody/fixed_fem/dev/test/linear_constitutive_model_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16562)

[fem] Move constitutive model test utils out of dev

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/test/multibody_plant_scalar_conversion_test.cc

Follow-up from #16571.  Towards #16476.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16585)

[plant] Enable AddMultibodyPlantSceneGraph for Expression

---

bindings/pydrake/math_py.cc
bindings/pydrake/test/math_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16573)

[pydrake] Add bindings for InvertAndCompose

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/sap_constraint.cc
multibody/contact_solvers/sap/sap_constraint.h
multibody/contact_solvers/sap/test/sap_constraint_test.cc

Towards #16543.
This PR is self-contained. However, for documentation on cliques, please refer to PR in progress #16548.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16553)

Implements SapConstraint

---

doc/styleguide/build.py

#16598 Electric Boogaloo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16599)

[doc] Fix Jekyll output to avoid symlinks, part deux

---

doc/_pages/buildcop.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16600)

[doc] Update build cop play book to check github pages

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/contact_problem_graph.cc
multibody/contact_solvers/sap/contact_problem_graph.h
multibody/contact_solvers/sap/test/contact_problem_graph_test.cc

Implements a class to describe the connectivity graph of a SAP problem.
Towards landing the [SapSolver](https://github.com/RobotLocomotion/drake/projects/10). Full working prototype in #16543.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16570)

[SAP] Implements ContactProblemGraph

---

multibody/fixed_fem/dev/BUILD.bazel
multibody/fixed_fem/dev/test/corotated_model_data_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16597)

[fem] Add unit test for CorotatedModelData

---

multibody/fem/BUILD.bazel
multibody/fem/linear_constitutive_model.cc
multibody/fem/linear_constitutive_model.h
multibody/fem/linear_constitutive_model_data.h
multibody/fem/test/constitutive_model_test_utilities.cc
multibody/fem/test/linear_constitutive_model_test.cc
multibody/fixed_fem/dev/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16586)

[fem] Move LinearConstitutiveModel out of dev

---

bindings/pydrake/systems/primitives_py.cc
bindings/pydrake/systems/test/primitives_test.py
systems/primitives/multilayer_perceptron.cc
systems/primitives/multilayer_perceptron.h
systems/primitives/test/multilayer_perceptron_test.cc

I'm opening this PR for confirmation of the design.  @hongkai-dai -- WDYT?  The backend implementation is very narrow right now, but I tried to keep it behind a public API that I would be happy with looking forward.
If we like it I will cover it with unit tests.
fyi @AlexandreAmice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16605)

[primitives] Support sin/cos input features in MultilayerPerceptron.

---

common/symbolic_expression.cc

Add a TODO for #16393.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16637)

[common] Add TODO for IsAffine bug

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/contact_problem_graph.h
multibody/contact_solvers/sap/sap_contact_problem.cc
multibody/contact_solvers/sap/sap_contact_problem.h
multibody/contact_solvers/sap/test/contact_problem_graph_test.cc
multibody/contact_solvers/sap/test/sap_contact_problem_test.cc

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16618)

[SAP] Implements SapContactProblem::AddConstraint()

---

common/BUILD.bazel
common/drake_bool.h
common/test/drake_bool_test.cc
math/quaternion.h
math/rotation_matrix.h
systems/primitives/discrete_derivative.cc

Closes #13362.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16621)

[common] Add if_then_else overload for Eigen::Vector

---

multibody/fem/BUILD.bazel
multibody/fem/corotated_model.cc
multibody/fem/corotated_model.h
multibody/fem/corotated_model_data.cc
multibody/fem/corotated_model_data.h
multibody/fem/test/constitutive_model_test_utilities.cc
multibody/fem/test/corotated_model_data_test.cc
multibody/fem/test/corotated_model_test.cc
multibody/fixed_fem/dev/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16617)

[fem] Move corotated model out of dev

---

common/BUILD.bazel
common/diagnostic_policy.cc
common/diagnostic_policy.h
common/test/diagnostic_policy_test.cc

Co-authored-by: Jeremy Nimmer <jeremy.nimmer@tri.global>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16641)

[common] Introduce diagnostic policy module

---

geometry/render/dev/BUILD.bazel
geometry/render/dev/render_server/README.md
geometry/render/dev/render_server/gltf_render_server.py
geometry/render/dev/render_server/wsgi.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16595)

[geometry/dev] drop gunicorn for single threaded flask server

---

bindings/pydrake/_geometry_extra.py
bindings/pydrake/test/geometry_visualizers_test.py
doc/_pages/getting_help.md
tools/install/colab/README.md
tutorials/README.md
tutorials/linear_program.ipynb
tutorials/mathematical_program.ipynb
tutorials/quadratic_program.ipynb

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16568)

[doc] Withdraw tutorials from Colab

---

BUILD.bazel
bindings/pydrake/BUILD.bazel
bindings/pydrake/tutorials.py
doc/pydrake/build.py
tools/install/bazel/generate_installed_files_manifest.bzl
tools/wheel/image/build-wheel.sh
tutorials/BUILD.bazel
tutorials/README.md

Follow-up from #12461.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16644)

[tutorials] Install tutorials in binary releases

---

bindings/pydrake/geometry_py_optimization.cc
bindings/pydrake/test/geometry_optimization_test.py
geometry/optimization/BUILD.bazel
geometry/optimization/hpolyhedron.cc
geometry/optimization/hpolyhedron.h
geometry/optimization/intersection.cc
geometry/optimization/intersection.h
geometry/optimization/test/hpolyhedron_test.cc
geometry/optimization/test/intersection_test.cc

Also adds the ability to generate an HPolyhedron from the intersection of 2 HPolyhedrons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16629)

[geometry/optimization] Add Intersection Convex Set

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/_geometry_extra.py
setup/BUILD.bazel
setup/deepnote/README.md
setup/deepnote/install_nginx
setup/deepnote/nginx-meshcat-proxy.conf
tools/install/bazel/generate_installed_files_manifest.bzl
tools/skylark/pybind.bzl
tools/wheel/image/build-wheel.sh

Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16639)

[pydrake] Add proxy feature for MeshCat on Deepnote

---

multibody/parsing/detail_mujoco_parser.cc
multibody/parsing/test/detail_mujoco_parser_test.cc

Towards #16369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16630)

[parsing] Support actuator/motor tags in MuJoCo parser

---

geometry/meshcat.cc

This is also in anticipation of wrapping all callbacks with exception handlers, which will be easier if they have real names (towards #16659).
Add an implementation comment to all of the PIMPL functions clarifying their scope, now that we have a wider variety of happenings.
Fix an indentation-level snafu on some of the PIMPL functions (from #16063).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16662)

[geometry] Factor our uWS callbacks for readability

---

geometry/meshcat.cc

This is in anticipation of adding thread-shutdown guards (#16659).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16664)

[geometry] Centralize Meshcat's calls to defer()

---

doc/_pages/installation.md
doc/_pages/pip.md
doc/_pages/python_bindings.md

Demote the "known issues" warning to be later in the list; we have many of them fixed already.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16649)

[doc] Highlight Anaconda incompatibility in the installation docs

---

geometry/BUILD.bazel
geometry/meshcat.cc
geometry/meshcat.h
geometry/test/meshcat_test.cc

A lemma towards #16659.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16670)

[geometry] Add cleanup logic for unexpected websocket thread exit

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
geometry/optimization/graph_of_convex_sets.cc
geometry/optimization/test/graph_of_convex_sets_test.cc
solvers/cost.cc
solvers/cost.h
solvers/test/cost_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16679)

[solvers] Add PerspectiveQuadraticCost and include in GraphOfConvexSets cost options

---

solvers/test/linear_program_examples.cc
solvers/test/linear_program_examples.h
solvers/test/optimization_examples.cc
solvers/test/optimization_examples.h
solvers/test/quadratic_program_examples.cc
solvers/test/quadratic_program_examples.h
solvers/test/second_order_cone_program_examples.cc
solvers/test/second_order_cone_program_examples.h

See #16686 CI output for an example of the newly-detailed test failure output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16692)

[solvers] Print more details for parameterized test cases

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/math_py.cc
bindings/pydrake/test/math_test.py
bindings/pydrake/test/trajectories_test.py
bindings/pydrake/trajectories_py.cc

Also makes BsplineBasis picklable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16698)

[pydrake/trajectories] Make BsplineTrajectory picklable

---

bindings/pydrake/tutorials.py
doc/_pages/from_binary.md
doc/_pages/release_playbook.md
doc/_release-notes/v1.0.0.md
tools/release_engineering/download_release_candidate.py
tools/release_engineering/relnotes.py
tutorials/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16601)

[doc] Add release notes v1.0.0

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/sap_constraint_bundle.cc
multibody/contact_solvers/sap/sap_constraint_bundle.h
multibody/contact_solvers/sap/test/sap_constraint_bundle_test.cc

Implements a class to bundle constraints in the order dictated by graph of the problem in order to exploit sparsity. 
In addition, the SAP algorithm is agnostic to the type of constraints but all it really needs is a number of operations on the bundle. This class provides that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16697)

[SAP] Introduces SapConstraintBundle

---

multibody/fem/BUILD.bazel
multibody/fem/fem_indexes.h
multibody/fem/fem_state.cc
multibody/fem/fem_state.h
multibody/fem/fem_state_system.cc
multibody/fem/fem_state_system.h
multibody/fem/test/fem_state_system_test.cc
multibody/fem/test/fem_state_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16653)

[fem] Add FemState and FemStateManager

---

solvers/scs_solver.cc
solvers/test/optimization_examples.cc
solvers/test/scs_solver_test.cc
tools/workspace/scs/repository.bzl

Broken out from #16675, since there are meaningful code / test changes required.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16686)

[workspace] Upgrade scs to latest release 3.2.0

---

multibody/fem/BUILD.bazel
multibody/fem/discrete_time_integrator.cc
multibody/fem/discrete_time_integrator.h
multibody/fem/test/discrete_time_integrator_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16714)

[fem] Add discrete time integrator

---

bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/multibody/tree_py.cc
multibody/plant/test/frame_kinematics_test.cc
multibody/tree/frame.h

This PR helps with part of issue #16189.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16691)

New Frame methods CalcRelativeSpatialVelocity(), CalcRelativeSpatialVelocityInWorld().

---

bindings/pydrake/common/BUILD.bazel
bindings/pydrake/common/serialize_pybind.h
bindings/pydrake/common/test/serialize_pybind_test.py
bindings/pydrake/common/test/serialize_test_util_py.cc
tools/workspace/pybind11/mkdoc.py
tools/workspace/pybind11/test/sample_header.h
tools/workspace/pybind11/test/sample_header_class_coverage_expected.csv
tools/workspace/pybind11/test/sample_header_documentation.expected.h
tools/workspace/pybind11/test/sample_header_documentation_pybind_expected.xml
tools/workspace/pybind11/test/sample_header_file_coverage_expected.csv

This binds the fields of a Serialize-able struct automatically.
Towards #16717.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16718)

[pydrake] Add DefAttributesUsingSerialize helper function

---

bindings/pydrake/math_py.cc
bindings/pydrake/test/math_test.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16721)

[pydrake] add bindings for BsplineBasis::EvaluateCurve

---

doc/_pages/release_playbook.md
tools/wheel/README.rst
tools/wheel/build-wheels

Follow-up from discussions in #16707.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16710)

[doc] Update wheel release playbook to ensure fresh base images

---

multibody/fem/BUILD.bazel
multibody/fem/fem_element.cc
multibody/fem/fem_element.h
multibody/fem/fem_indexes.h
multibody/fem/test/dummy_element.cc
multibody/fem/test/dummy_element.h
multibody/fem/test/fem_element_test.cc
multibody/fem/test/fem_state_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16712)

[fem] Add FemElement

---

geometry/meshcat.cc

https://drake.mit.edu/styleguide/cppguide.html#Exceptions as noted in #16726.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16730)

[geometry] In meshcat, use logic_error not out_of_range

---

bindings/pydrake/common/BUILD.bazel
bindings/pydrake/common/test/text_logging_test_py.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16731)

[pydrake] Fix race condition in text_logging_gil_test

---

multibody/fem/discrete_time_integrator.cc
multibody/fem/discrete_time_integrator.h
multibody/fem/test/discrete_time_integrator_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16734)

[fix] Revert a git mishap

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/sap_friction_cone_constraint.cc
multibody/contact_solvers/sap/sap_friction_cone_constraint.h
multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc

Implements cone constraint for the SAP solver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16715)

[SAP] Implements contact constraint.

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/sap_model.cc
multibody/contact_solvers/sap/sap_model.h
multibody/contact_solvers/sap/test/sap_model_test.cc

Model of the contact problem built by SAP to query the cost and its derivatives.
FYI, future PRs will implement more functionality and more thorough tests. This PR introduces just the bare minimum.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16713)

[SAP] Implements SapModel.

---

geometry/render/dev/BUILD.bazel
geometry/render/dev/http_service_curl.cc
geometry/render/dev/http_service_curl.h
geometry/render/dev/test/http_service_curl_test.cc

Cannot merge until
Closes #15916.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16723)

[geometry/dev] add HttpServiceCurl implementation

---

examples/manipulation_station/manipulation_station.cc

The camera should not be visible to itself or else it obscures its own view. We only want the illustration properties so that the camera shows up in the visualizer.
Use `bazel-bin/examples/manipulation_station/mock_station_simulation --publish_cameras=true` to see the difference.
Hotfix for #16719.
Per #13689, we cannot yet do this in the SDFormat file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16754)

[manipulation_station] Remove the camera mesh from self-perception

---

multibody/parsing/BUILD.bazel
multibody/parsing/test/parser_manual_test.cc

For now, this is just a quick way to experiment with parser changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16743)

[parsing] Introduce multibody parser manual test program

---

multibody/fem/BUILD.bazel
multibody/fem/fem_element.h
multibody/fem/test/dummy_element.h
multibody/fem/test/fem_element_test.cc
multibody/fem/test/volumetric_element_test.cc
multibody/fem/volumetric_element.cc
multibody/fem/volumetric_element.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16733)

[fem] Add VolumetricElement

---

geometry/BUILD.bazel
geometry/test/meshcat_test.cc
geometry/test/meshcat_websocket_client.py
tools/dynamic_analysis/drd.sh
tools/dynamic_analysis/helgrind.sh
tools/dynamic_analysis/valgrind.sh

Towards #16659.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16757)

[geometry] Enable valgrind on Meshcat testing

---

multibody/fem/BUILD.bazel
multibody/fem/acceleration_newmark_scheme.cc
multibody/fem/acceleration_newmark_scheme.h
multibody/fem/newmark_scheme.h
multibody/fem/test/acceleration_newmark_scheme_test.cc
multibody/fem/test/velocity_newmark_scheme_test.cc
multibody/fem/velocity_newmark_scheme.cc
multibody/fem/velocity_newmark_scheme.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16737)

[fem] Add acceleration and velocity newmark schemes

---

geometry/BUILD.bazel
geometry/meshcat.cc
geometry/test/meshcat_websocket_client.py

Declare proper cpu-usage count.
Add missing punctuation.
Add more logging to test helper.
Towards #16659.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16763)

[geometry] A bit of house cleaning for Meshcat

---

CMakeLists.txt
tools/dynamic_analysis/bazel.rc
tools/ubuntu-bionic.bazelrc

See also #16500.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16587)

Enable split debug symbols on Ubuntu

---

CMakeLists.txt
doc/_pages/bazel.md
doc/_pages/python_bindings.md
solvers/gurobi_solver.cc
solvers/gurobi_solver.h
solvers/mathematical_program_result.h
solvers/solver_options.h
solvers/test/gurobi_solver_test.cc
tools/bazel.rc
tools/dynamic_analysis/tsan.supp
tools/workspace/gurobi/package-macos.BUILD.bazel.in
tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in
tools/workspace/gurobi/repository.bzl

Closes #16604.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16716)

upgrade gurobi to 9.5.1 (which includes macos arm64 support)

---

multibody/inverse_kinematics/minimum_distance_constraint.h
solvers/minimum_value_constraint.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16792)

[inverse_kinematics] minor cleanup of MinimumDistanceConstraint documentation

---

cmake/modules/FindGurobi.cmake

Follow-up to #16716.
Fixes errors in CMake builds, e.g. 
https://drake-jenkins.csail.mit.edu/job/linux-bionic-clang-cmake-continuous-everything-debug/1392/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16794)

CMake: Update Guorbi version in FindGurobi module

---

multibody/parsing/test/detail_sdf_parser_test.cc

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16790)

[parsing] Add a fixture to detail_sdf_parser_test

---

multibody/parsing/detail_sdf_parser.cc

With our particular usage pattern we're rescued by NRVO, but that's too brittle to rely on indefinitely.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16797)

[parsing] Fix dangling reference to destroyed stack variable

---

cmake/modules/FindGurobi.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16803)

CMake: Update gurobi install directory on Mac

---

setup/deepnote/nginx-meshcat-proxy.conf

Tested manually in a scratch notebook.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16804)

[setup] Adjust Deepnote NginX config for longer timeouts

---

solvers/mathematical_program.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16806)

[solvers] fix broken docstring for SetVariableScaling

---

examples/manipulation_station/joint_teleop.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16807)

[examples] add missing ConnectMeshcatVisualizer import

---

bindings/pydrake/_geometry_extra.py

Refactor ngrok support into its own helper function.
Display the URL using a clickable link.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16805)

[pydrake] StartMeshcat uses NginX when on Deepnote

---

geometry/meshcat.cc
geometry/meshcat.h
geometry/test/meshcat_test.cc

Follow-up from #16726.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16808)

[geometry] Repeated Meshcat::AddButton calls reset the click count

---

solvers/BUILD.bazel
solvers/create_constraint.cc
solvers/create_constraint.h
solvers/test/create_constraint_test.cc

As the first step towards https://github.com/RobotLocomotion/drake/pull/16761#pullrequestreview-911095580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16813)

ParseConstraint throws error for false formula.

---

geometry/render/dev/BUILD.bazel
geometry/render/dev/render_engine_gltf_client.cc
geometry/render/dev/render_engine_gltf_client.h
geometry/render/dev/test/render_engine_gltf_client_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16793)

[geometry/dev] Add RenderEngineGltfClient unit tests.

---

doc/_pages/developers.md
doc/_pages/profiling.md
geometry/profiling/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16817)

[doc] Add tips for profiling

---

bindings/pydrake/multibody/math_py.cc
bindings/pydrake/multibody/test/math_test.py
multibody/math/spatial_acceleration.h
multibody/math/spatial_velocity.h
multibody/tree/body_node.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16699)

Update SpatialAcceleration methods to parallel SpatialVelocity.

---

multibody/parsing/detail_path_utils.cc
multibody/parsing/detail_path_utils.h
multibody/parsing/detail_sdf_geometry.cc
multibody/parsing/detail_sdf_geometry.h
multibody/parsing/detail_sdf_parser.cc
multibody/parsing/detail_urdf_geometry.cc
multibody/parsing/test/detail_path_utils_test.cc
multibody/parsing/test/detail_sdf_geometry_test.cc
multibody/parsing/test/parser_test.cc

(I'll assign to feature review once a few more of the in-flight parser PRs have merged, just to avoid rebase churn.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16820)

[parsing] Use DiagnosticPolicy in ResolveUri

---

multibody/plant/test/frame_kinematics_test.cc
multibody/tree/frame.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16760)

Create new method Frame::CalcSpatialAcceleration().

---

solvers/mathematical_program.cc
solvers/mathematical_program.h
solvers/test/mathematical_program_test.cc

As mentioned in https://github.com/RobotLocomotion/drake/pull/16761#pullrequestreview-911095580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16825)

MathematicalProgram ignores the constraint if it were empty.

---

tutorials/dynamical_systems.ipynb
tutorials/mathematical_program.ipynb
tutorials/nonlinear_program.ipynb

+@hongkai-dai for feature review, please (since I changed your visualization)
cc @jwnimmer-tri .
Towards #16838.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16837)

Remove uses of interactive matplotlib from tutorials to support deepnote/colab

---

tutorials/BUILD.bazel
tutorials/_developers.md
tutorials/debug_mathematical_program.ipynb
tutorials/dynamical_systems.ipynb
tutorials/index.ipynb
tutorials/linear_program.ipynb
tutorials/mathematical_program.ipynb
tutorials/mathematical_program_multibody_plant.ipynb
tutorials/multibody_plant_autodiff_mass.ipynb
tutorials/pyplot_animation_multibody_plant.ipynb
tutorials/quadratic_program.ipynb
tutorials/rendering_multibody_plant.ipynb
tutorials/solver_parameters.ipynb
tutorials/sum_of_squares_optimization.ipynb
tutorials/test/notebook_lint_test.py
tutorials/updating_costs_and_constraints.ipynb

Canonicalize the preamble text.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16838)

[tutorials] Add linter for required styles choices

---

tools/install/libdrake/BUILD.bazel
tools/install/libdrake/header_lint.bzl

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16850)

[tools] Defer header_lint failures to lint-time, not build-time

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/multibody/tree_py.cc
multibody/parsing/test/detail_sdf_parser_test.cc
multibody/plant/multibody_plant.h
multibody/plant/test/multibody_plant_test.cc
multibody/tree/joint_actuator.cc
multibody/tree/joint_actuator.h
multibody/tree/multibody_tree.cc
multibody/tree/multibody_tree.h
multibody/tree/test/joint_actuator_test.cc
multibody/tree/test/multibody_tree_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16835)

[multibody] Add `MultibodyPlant::GetEffortLowerLimits` (and friends)

---

solvers/create_constraint.cc
solvers/create_constraint.h
solvers/test/create_constraint_test.cc

As mentioned in https://github.com/RobotLocomotion/drake/pull/16761#pullrequestreview-911095580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16854)

ParseConstraint ignores formula being always true.

---

tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16867)

[drake_visualizer] Fix message handling in hydro visualization

---

multibody/fem/BUILD.bazel
multibody/fem/fem_element.h
multibody/fem/fem_model.cc
multibody/fem/fem_model.h
multibody/fem/fem_model_impl.cc
multibody/fem/fem_model_impl.h
multibody/fem/fem_state.h
multibody/fem/fem_state_system.cc
multibody/fem/fem_state_system.h
multibody/fem/test/acceleration_newmark_scheme_test.cc
multibody/fem/test/dummy_model.cc
multibody/fem/test/dummy_model.h
multibody/fem/test/fem_model_test.cc
multibody/fem/test/fem_state_system_test.cc
multibody/fem/test/velocity_newmark_scheme_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16800)

[fem] Add FemModel and FemModelImpl

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/sap_model.cc
multibody/contact_solvers/sap/sap_model.h
multibody/contact_solvers/sap/test/sap_model_test.cc

Finishes what we started in #16713.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16771)

[SAP] Implements missing features in SapModel

---

multibody/plant/compliant_contact_manager.cc
multibody/plant/compliant_contact_manager.h
multibody/plant/test/compliant_contact_manager_test.cc

This PR updates the contact manager to compute Jacobian blocks instead of a dense Jacobian.
This is the information needed to build a `SapContactProblem` that exploits sparsity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16781)

[SAP] Computation of Jacobian blocks

---

multibody/fem/BUILD.bazel
multibody/fem/dirichlet_boundary_condition.cc
multibody/fem/dirichlet_boundary_condition.h
multibody/fem/test/dirichlet_boundary_condition_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16839)

[fem] Add Dirichlet boundary conditions

---

geometry/render/dev/BUILD.bazel
geometry/render/dev/render_server/README.md
geometry/render/dev/test/flask_import_test.py
setup/mac/source_distribution/requirements-test-only.txt
setup/ubuntu/source_distribution/packages-bionic-test-only.txt
setup/ubuntu/source_distribution/packages-focal-test-only.txt

Prerequisite for #16822, CI images will need to be updated by Kitware.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16864)

[workspace] install flask for unit tests

---

tools/workspace/drake_visualizer/image/build-lcm.sh
tools/workspace/drake_visualizer/image/package.sh
tools/workspace/drake_visualizer/image/prereqs
tools/workspace/drake_visualizer/repository.bzl

Remnant of #16185.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16884)

[workspace] fix drake-visualizer for system jchart2d

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/contact_problem_graph.cc
multibody/contact_solvers/sap/contact_problem_graph.h
multibody/contact_solvers/sap/sap_constraint.h
multibody/contact_solvers/sap/sap_contact_problem.cc
multibody/contact_solvers/sap/sap_contact_problem.h
multibody/contact_solvers/sap/sap_friction_cone_constraint.h
multibody/contact_solvers/sap/test/contact_problem_graph_test.cc
multibody/contact_solvers/sap/test/sap_constraint_bundle_test.cc
multibody/contact_solvers/sap/test/sap_constraint_test.cc
multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc
multibody/contact_solvers/sap/test/sap_model_test.cc

This essentially gives SapContactProblem Value semantics so that we can place it in the cache along with other contact quantities in the manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16874)

Make SapContactProblem and friends clonable.

---

tools/install/bazel/test/drake_bazel_installed_test.py
tools/workspace/abseil_cpp_internal/repository.bzl
tools/workspace/bazel_skylib/repository.bzl
tools/workspace/common_robotics_utilities/repository.bzl
tools/workspace/dm_control/repository.bzl
tools/workspace/github3_py/repository.bzl
tools/workspace/petsc/repository.bzl
tools/workspace/rules_python/repository.bzl

Towards #16879 (meshcat will be updated in a separate PR)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16885)

Upgrade externals to latest

---

multibody/math/spatial_vector.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16870)

Upgrade documentation for SpatialVector to be more consistent with its subclasses.

---

bindings/pydrake/multibody/math_py.cc
bindings/pydrake/multibody/test/math_test.py
multibody/math/spatial_acceleration.h
multibody/math/spatial_force.h
multibody/math/spatial_momentum.h
multibody/math/spatial_velocity.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16844)

Upgrade SpatialMomentum documentation and keyword arguments for Python.

---

bindings/pydrake/multibody/math_py.cc
bindings/pydrake/multibody/test/math_test.py
multibody/math/spatial_force.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16851)

Upgrade SpatialForce documentation and keyword arguments for Python.

---

multibody/fem/BUILD.bazel
multibody/fem/fem_element.h
multibody/fem/fem_model.cc
multibody/fem/fem_model.h
multibody/fem/fem_model_impl.h
multibody/fem/test/volumetric_model_test.cc
multibody/fem/volumetric_element.h
multibody/fem/volumetric_model.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16881)

[fem] Add VolumetricModel

---

bindings/pydrake/multibody/inverse_kinematics_py.cc
bindings/pydrake/multibody/test/inverse_kinematics_test.py
multibody/inverse_kinematics/inverse_kinematics.cc
multibody/inverse_kinematics/inverse_kinematics.h
multibody/inverse_kinematics/position_constraint.cc
multibody/inverse_kinematics/position_constraint.h
multibody/inverse_kinematics/test/position_constraint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16873)

Add a new frame Abar to specify the PositionConstraint bound.

---

bindings/pydrake/geometry_py_optimization.cc
bindings/pydrake/test/geometry_optimization_test.py
geometry/optimization/graph_of_convex_sets.h
geometry/optimization/test/graph_of_convex_sets_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16892)

[geometry/optimization] Expose the costs and constraints of an Edge in GraphOfConvexSets

---

bindings/pydrake/visualization/meldis.py

Relates https://drakedevelopers.slack.com/archives/C028F9T6MSM/p1649358385868039
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16916)

meldis: Minor style adjustment to code blocks

---

multibody/fem/BUILD.bazel
multibody/fem/fem_model.cc
multibody/fem/fem_model.h
multibody/fem/test/fem_model_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16889)

[fem] Add Dirichlet BC to FemModel

---

tools/workspace/mosek/repository.bzl

Towards #16439.
https://packages.ubuntu.com/search?keywords=libcilkrts5&searchon=names&suite=all&section=all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16928)

[workspace] Modernize mosek's libcilkrts explanation

---

tools/workspace/meshcat/repository.bzl
tools/workspace/meshcat_python/repository.bzl

Resolves #16879
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16925)

Upgrade meshcat and meshcat_python to the latest commit

---

CONTRIBUTING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16924)

Fix out-of-date filename in CONTRIBUTING.md

---

bindings/pydrake/solvers/all.py
bindings/pydrake/test/all_test.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16933)

[pydrake] Add missing module to pydrake/solvers/all

---

doc/_pages/bazel.md
setup/ubuntu/install_prereqs.sh
setup/ubuntu/source_distribution/install_prereqs.sh
tools/dynamic_analysis/kcov.sh
tools/dynamic_analysis/kcov_tool

Towards #13391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16938)

setup: Deprecate Bionic-specific option --with-kov

---

solvers/benchmarking/BUILD.bazel
solvers/benchmarking/benchmark_mathematical_program.cc

benchmark constructing a sum-of-squares program, which involves computing symbolic::Polynomial and imposing linear and semidefinite constraint.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16900)

Add a benchmark on MathematicalProgram.

---

tools/workspace/BUILD.bazel
tools/workspace/drake_visualizer/BUILD.bazel

Hotfix for #16962 and #16945.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16964)

[workspace] Fix "disable drake-visualizer on macOS" for Ubuntu again

---

tools/workspace/ros_xacro/repository.bzl

Update to v1.14.13 noetic version.
Relates: #13391, #16931.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16967)

[workspace] Remove bionic support for ros_xacro.

---

multibody/contact_solvers/sap/sap_solver.cc

Per review comment in #16930.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16968)

[SAP] Note on the choice of LLT vs LDLT in dense version of the solver

---

multibody/fem/petsc_symmetric_block_sparse_matrix.cc
multibody/fem/petsc_symmetric_block_sparse_matrix.h
multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16961)

[fem] Report status of Petsc solver

---

bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/multibody/tree_py.cc
multibody/plant/test/frame_kinematics_test.cc
multibody/plant/test/kuka_iiwa_model_tests.h
multibody/tree/frame.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16893)

Create Frame::EvalSpatialVelocityInWorld() and Frame::CalcAngularVelocity().

---

tools/install/installer.py

Modify how we adjust RPATHs in installed libraries to rewrite two types of paths:
- Paths starting with `@loader_path`.
- Paths into Bazel's private build ares (`/private/var/tmp/_bazel_$USER`).
Previously, we only rewrote the former. However, for reasons which are unclear, MOSEK gets linked using the latter, which was resulting in the installed library containing a reference to the absolute path of MOSEK as found in the build tree (which is clearly not useful).
+@jwnimmer-tri for feature review, please. I suspect there won't be much to see from CI here, so I'm not sure what's the best way to go about testing this, other than locally. (I've already verified on KW's macbook that this produces `@loader_path/libmosek64.dylib` in the installed `libdrake.so`.)
--- …

"Fix" install RPATH for MOSEK

---

multibody/fem/BUILD.bazel
multibody/fem/fem_model.h
multibody/fem/fem_solver.cc
multibody/fem/fem_solver.h
multibody/fem/test/dummy_element.h
multibody/fem/test/fem_model_test.cc
multibody/fem/test/fem_solver_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16917)

[fem] Add Femsolver

---

solvers/mathematical_program.cc
solvers/test/mathematical_program_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16983)

MathematicalProgram::NewSosPolynomial takes degree=0

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py
common/symbolic_monomial.cc
common/symbolic_monomial.h
common/test/symbolic_monomial_test.cc

Towards #16982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16984)

Add Monomial::Evaluate() for a batch of data.

---

geometry/proximity/BUILD.bazel
geometry/proximity/deformable_contact_geometries.cc
geometry/proximity/deformable_contact_geometries.h
geometry/proximity/test/deformable_contact_geometries_test.cc

This is the first of the PR train towards #16875.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16947)

[geometry] Add rigid and deformable representation for proximity

---

multibody/plant/BUILD.bazel
multibody/plant/compliant_contact_manager.cc
multibody/plant/compliant_contact_manager.h
multibody/plant/test/compliant_contact_manager_test.cc

`CompliantContactManager` instantiates a SAP solver and loads contact results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16989)

CompliantContactManager computes contact results

---

multibody/tree/frame.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16977)

Small improvement to Frame class documentation.

---

bindings/pydrake/geometry_py_visualizers.cc
bindings/pydrake/test/geometry_visualizers_test.py
geometry/meshcat.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17008)

[meshcat] Add python bindings for Meshcat::SetCamera

---

geometry/BUILD.bazel
geometry/make_mesh_for_deformable.cc
geometry/make_mesh_for_deformable.h
geometry/test/make_mesh_for_deformable_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16998)

[geometry] Add MakeDeformableMesh

---

doc/_pages/release_playbook.md

(Based on experience with the recent v1.2.0 release.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17001)

[doc] Fix some nits in the release playbook

---

doc/BUILD.bazel
doc/defs.py
doc/pydrake/BUILD.bazel
doc/pydrake/_static/css/custom.css
doc/pydrake/footer.html
doc/pydrake/layout.html

Towards #16993.
This incorporates css and html boilerplate as provided by our website contractors.
Local preview is available as:
```
bazel run //doc/pydrake:build -- --serve
```
---
Header:
Footer:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17012)

[doc] Add new pydrake header, footer, and style customizations

---

common/symbolic_expression.h
common/symbolic_generic_polynomial.cc
common/symbolic_polynomial.cc

In the SoS benchmark, for me this is approx 20% faster on case 1 and 2% faster on case 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17013)

[common] Speed up SoS using negation instead of subtraction

---

geometry/optimization/iris.cc

Resolves #17002
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17003)

Fix gradient computation in SamePointConstraint.

---

doc/_pages/release_playbook.md

For reference, here is the current [for_maintainers.ipynb](https://github.com/RobotLocomotion/drake/files/8557893/for_maintainers.ipynb.txt) at the time of this pull request.
Closes #16970.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17010)

[doc] Add instructions for tutorials deployment

---

bindings/pydrake/systems/analysis_py.cc
bindings/pydrake/systems/test/analysis_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17032)

Add implicit dynamics binding

---

bindings/pydrake/multibody/plant_py.cc
bindings/pydrake/multibody/test/plant_test.py

Fixes #17028
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17042)

[pydrake] Bind MbP::GetRigidBodyByName()

---

solvers/BUILD.bazel
solvers/ipopt_solver.cc
solvers/test/ipopt_solver_test.cc

Towards #17023 and #17035.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17034)

[solvers] Ipopt supports kPrintFileName

---

multibody/tree/ball_rpy_joint.h
multibody/tree/joint.h
multibody/tree/planar_joint.h
multibody/tree/prismatic_joint.h
multibody/tree/revolute_joint.h
multibody/tree/screw_joint.h
multibody/tree/test/ball_rpy_joint_test.cc
multibody/tree/test/planar_joint_test.cc
multibody/tree/test/prismatic_joint_test.cc
multibody/tree/test/revolute_joint_test.cc
multibody/tree/test/screw_joint_test.cc
multibody/tree/test/universal_joint_test.cc
multibody/tree/test/weld_joint_test.cc
multibody/tree/universal_joint.h

API to retrieve viscous damping at the `Joint` level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17019)

Joint API to retrieve viscous damping.

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py
common/symbolic_polynomial.cc
common/symbolic_polynomial.h
common/test/symbolic_polynomial_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17021)

Determine if a polynomial is even or odd.

---

solvers/clp_solver.cc

As mentioned in https://github.com/RobotLocomotion/drake/pull/16894#issue-1189204649
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17033)

ClpSolver uses sparse matrix in linear constraint.

---

multibody/contact_solvers/supernodal_solver.cc
multibody/contact_solvers/test/supernodal_solver_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17048)

SupernodalSolver bug fix

---

tutorials/debug_mathematical_program.ipynb

Requires:
Closes #17023.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17035)

[tutorials] Avoid kPrintToConsole in online notebooks

---

multibody/contact_solvers/sap/test/sap_solver_test.cc

Add a number of tests to verify the Newton iterations are doing the right thing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16940)

[SAP] Newton iteration tests

---

multibody/parsing/parsing_doxygen.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17064)

[doc] Fix a wording defect in parsing doc

---

solvers/cost.cc
solvers/test/cost_test.cc

Also remove the unused MakeL2NormCost.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17074)

Make2NormSquaredCost should set convex flag to true.

---

geometry/BUILD.bazel
geometry/internal_geometry.cc
geometry/internal_geometry.h
geometry/make_mesh_for_deformable.cc
geometry/make_mesh_for_deformable.h
geometry/test/internal_geometry_test.cc
geometry/test/make_mesh_for_deformable_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17036)

[geometry] InternalGeometry supports deformable representation

---

doc/doxygen_cxx/doxygen.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17075)

Fixes typo in the C++ overview section

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py
common/BUILD.bazel
common/symbolic_polynomial.cc
common/symbolic_polynomial.h
common/test/symbolic_polynomial_test.cc

Resolves #16982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17065)

Polynomial evaluates a batch of indeterminates.

---

bindings/pydrake/geometry_py_optimization.cc
bindings/pydrake/test/geometry_optimization_test.py
geometry/optimization/hpolyhedron.cc
geometry/optimization/hpolyhedron.h
geometry/optimization/test/hpolyhedron_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17056)

add PontryaginDifference to HPolyhedron

---

examples/rimless_wheel/rimless_wheel.cc

Resolves #8589. If the guard was triggered with exactly zero
penetration, then we could fail on the following step because the
wheel was positioned exactly in contact with the ground (and we are
using WitnessFunctionDirection::kPositiveThenNonPositive). The
unfortunate solution is to add machine epsilon to make the next
witness value strictly positive.
This does *not* implement the change to the double support threshold
suggested in #8589, where we use the accuracy from the context as the
threshold for detecting double support. I tried it, but it resulted in
a far too subtle interplay between the numerics of the witness
triggers and the detection of double support (and in practice led to
infinite loops). I've added an extra line of documentation to capture
that lesson, but do not consider …

[examples/rimless_wheel] Resolves subtle numerics in witness function logic

---

multibody/contact_solvers/sap/sap_solver.h
multibody/plant/BUILD.bazel
multibody/plant/compliant_contact_manager.cc
multibody/plant/compliant_contact_manager.h
multibody/plant/test/compliant_contact_manager_test.cc

Joint damping is one of the first things that will cause instabilities in a simulation. It must be treated implicitly in order to have a stable model.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17077)

[SAP] CompliantContactManager implements implicit joint damping

---

multibody/plant/test/discrete_update_manager_test.cc
multibody/plant/test/dummy_model.h
multibody/plant/test/multibody_plant_scalar_conversion_test.cc

Relates: #16937 (clang-12 will start aggressively warning on this).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17086)

[workspace] Make classes with final dtors final

---

doc/_pages/issues.md
doc/_pages/platform_reviewer_checklist.md

(A few tweaks came up while I was rolling this out.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17090)

[doc] Nitpicks on issues policy

---

doc/_pages/buildcop.md

Resolves #15835
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17092)

[doc] Update buildcop instructions to check caching is enabled

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/sap_limit_constraint.cc
multibody/contact_solvers/sap/sap_limit_constraint.h
multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17051)

[SAP] Implements limit constraint

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/sap_solver.cc
multibody/contact_solvers/sap/sap_solver.h
multibody/contact_solvers/sap/test/sap_solver_test.cc

SapSolver uess supernodal algebra by default.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17055)

[SAP] SapSolver uses supernodal sparse algebra

---

bindings/pydrake/common/eigen_geometry_py.cc
bindings/pydrake/manipulation/test/planner_test.py
bindings/pydrake/multibody/test/plant_test.py
multibody/inverse_kinematics/test/global_inverse_kinematics_collision_avoidance_test.cc
multibody/inverse_kinematics/test/global_inverse_kinematics_reachable_test.cc
multibody/inverse_kinematics/test/global_inverse_kinematics_test.cc
multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.cc

Related to #10982
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17098)

Minor clean up for Isometry3 (remove unused imports / aliases)

---

bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/multibody/tree_py.cc
multibody/plant/test/external_forces_test.cc
multibody/plant/test/frame_kinematics_test.cc
multibody/plant/test/kuka_iiwa_model_tests.h
multibody/plant/test/multibody_plant_jacobians_test.cc
multibody/tree/frame.h
multibody/tree/test/multibody_tree_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17014)

Create methods for relative spatial acceleration to parallel spatial velocity.

---

solvers/mosek_solver.cc
solvers/test/linear_program_examples.cc
solvers/test/linear_program_examples.h
solvers/test/mosek_solver_test.cc

As discussed on slack https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1651568530744449
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17089)

MosekSolver returns the solution even the problem is unbounded or infeasible

---

multibody/fixed_fem/dev/BUILD.bazel
multibody/fixed_fem/dev/deformable_body_config.h
multibody/fixed_fem/dev/test/deformable_body_config_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17099)

[fem] Add unit tests for DeformableBodyConfig

---

bindings/pydrake/multibody/test/double_pendulum.sdf
examples/hydroelastic/spatula_slip_control/models/schunk_wsg_50_hydro_bubble.sdf
examples/kuka_iiwa_arm/models/desk/transcendesk55inch.sdf
examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table.sdf
examples/kuka_iiwa_arm/models/table/extra_heavy_duty_table_surface_only_collision.sdf
manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf
manipulation/models/iiwa_description/iiwa7/iiwa7_with_box_collision.sdf
manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf
manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf
manipulation/models/wsg_50_description/sdf/schunk_wsg_50.sdf
manipulation/models/wsg_50_description/sdf/schunk_wsg_50_ball_contact.sdf
manipulation/models/wsg_50_description/sdf/schunk_wsg_50_no_tip.sdf
manipulation/models/wsg_50_description/sdf/schunk_wsg_50_with_tip.sdf
multibody/parsing/BUILD.bazel
multibody/parsing/detail_sdf_diagnostic.cc
multibody/parsing/detail_sdf_diagnostic.h
multibody/parsing/detail_sdf_geometry.cc
multibody/parsing/detail_sdf_parser.cc
multibody/parsing/test/detail_sdf_parser_test.cc
multibody/parsing/test/diagnostic_policy_test_base.h
multibody/parsing/test/sdf_parser_test/unsupported_elements.sdf

Also cleans up some models which had been incorporated into drake with
unsupported elements.
Fixes #16785
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17101)

SDF parsing: Warn about unsupported elements

---

doc/_pages/release_playbook.md
doc/index.md
tutorials/README.md
tutorials/_developers.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17110)

[doc] Fix tutorial hyperlinks; update stale deployment advice

---

bindings/pydrake/math_py.cc
bindings/pydrake/test/math_test.py
math/matrix_util.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17111)

Add python binding for ToSymmetricMatrixFromLowerTriangularColumns

---

solvers/mathematical_program_result.h
solvers/mosek_solver.cc
solvers/test/mosek_solver_test.cc
solvers/test/semidefinite_program_examples.cc
solvers/test/semidefinite_program_examples.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17106)

retrieve dual solution for positive semidefinite constraint in Mosek.

---

examples/manipulation_station/manipulation_station.h

Closes #10248.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17120)

[manipulation_station] Add a TODO comment

---

bindings/pydrake/multibody/test/plant_test.py
bindings/pydrake/multibody/tree_py.cc
multibody/plant/test/external_forces_test.cc
multibody/plant/test/frame_kinematics_test.cc
multibody/plant/test/kuka_iiwa_model_tests.h
multibody/plant/test/multibody_plant_jacobians_test.cc
multibody/tree/frame.h
multibody/tree/test/multibody_tree_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17117)

Relative spatial acceleration methods to parallel relative spatial velocity.

---

multibody/fem/BUILD.bazel
multibody/fem/deformable_body_config.h
multibody/fem/test/deformable_body_config_test.cc
multibody/fixed_fem/dev/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17108)

[fem] Move DeformableBodyConfig out of dev

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py

cc @lujieyang
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17128)

Add python binding for Polynomial::EqualToAfterExpansion

---

manipulation/util/BUILD.bazel
manipulation/util/show_model.py
manipulation/util/test/show_model_test.py
manipulation/util/test/simple_nested_model.sdf
manipulation/util/test/simple_world_with_two_models.sdf

Resolves #17118
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17129)

show_model: Test composite model; also enable usage of world files

---

tools/workspace/README.md

Inspired by #17119.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17135)

[doc] Clarify monthly upgrade procedure

---

multibody/contact_solvers/sap/sap_limit_constraint.cc
multibody/contact_solvers/sap/sap_limit_constraint.h
multibody/plant/BUILD.bazel
multibody/plant/compliant_contact_manager.cc
multibody/plant/compliant_contact_manager.h
multibody/plant/discrete_update_manager.cc
multibody/plant/discrete_update_manager.h
multibody/plant/multibody_plant_discrete_update_manager_attorney.h
multibody/plant/test/compliant_contact_manager_test.cc

Manager adds limit constraints to the SAP contact problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17083)

[SAP] Adds constraint limits

---

math/rotation_matrix.cc
math/rotation_matrix.h

https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17138)

[math] Move SVD code to cc file

---

CMakeLists.txt
doc/_pages/bazel.md
doc/_pages/clion.md
doc/_pages/code_style_tools.md
doc/_pages/from_source.md
setup/mac/source_distribution/Brewfile
setup/ubuntu/source_distribution/packages-focal-clang.txt
setup/ubuntu/source_distribution/packages-focal-test-only.txt
setup/ubuntu/source_distribution/packages-focal.txt
tools/dynamic_analysis/asan.sh
tools/dynamic_analysis/bazel.rc
tools/dynamic_analysis/drd.sh
tools/dynamic_analysis/helgrind.sh
tools/dynamic_analysis/lsan.sh
tools/dynamic_analysis/tsan.sh
tools/dynamic_analysis/ubsan.sh
tools/dynamic_analysis/valgrind.sh
tools/lint/clang_format.py
tools/skylark/drake_cc.bzl
tools/ubuntu-focal.bazelrc
tools/wheel/image/packages-focal
tools/workspace/cc/repository.bzl
tools/workspace/pybind11/libclang_setup.py

EWISOTT. This should maybe wait until we excise more of Bionic (particularly, the setup scripts).
Relates: #14652.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16937)

Use clang 12

---

math/test/quadratic_form_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17144)

Fix CI test on quardratic_form_test

---

multibody/tree/joint.h
multibody/tree/prismatic_joint.h
multibody/tree/revolute_joint.h
multibody/tree/test/prismatic_joint_test.cc
multibody/tree/test/revolute_joint_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17151)

APIs to set the default joint damping.

---

bindings/pydrake/multibody/parsing_py.cc
bindings/pydrake/multibody/test/parsing_test.py

Relevant to: #17107
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17181)

Add python binding for Parser::SetStrictParsing

---

tools/release_engineering/dev/repack_deb.py

- The name of the archive determines the output folder alien creates.  Previously the script would fail with `drake-focal-latest.tar.gz` or `foo.tar.gz`.
- Add --verbose to `alien` so that progress is logged, failed assertions (directory searches) will have output to refer to.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17183)

[tools/dev] Fix repack_deb extracted package directory path.

---

multibody/meshcat/joint_sliders.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17192)

[meshcat] Remove console spam in Run with timeout

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17200)

[bindings] Add bindings for MathematicalProgram variable scaling

---

geometry/proximity/test/penetration_as_point_pair_callback_test.cc

Towards #17009
@drake-jenkins-bot mac-m1-monterey-unprovisioned-clang-bazel-experimental-release please
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17207)

[geometry] Adjust test tolerances for mac arm64

---

multibody/meshcat/test/universal_joint.sdf
multibody/parsing/detail_sdf_parser.cc
multibody/parsing/test/detail_sdf_parser_test.cc
multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf

Closes #17179.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17178)

[parsing] Add warning for unsupported joint actuators

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/constraint.cc
solvers/constraint.h
solvers/test/constraint_test.cc

Resolves #17103
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17182)

Add LinearConstraint::RemoveTinyCoefficient

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py
common/symbolic_polynomial.cc
common/symbolic_polynomial.h
common/test/symbolic_polynomial_test.cc
common/test_utilities/symbolic_test_util.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17202)

Deprecate Polynomial::EqualToAfterExpansion

---

solvers/test/cost_test.cc
solvers/test/csdp_solver_test.cc

Towards #17009
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17205)

[solvers] Adjust test tolerances for mac arm64

---

multibody/fem/test/corotated_model_data_test.cc
multibody/plant/test/multibody_plant_reaction_forces_test.cc
multibody/plant/test/tamsi_solver_test.cc

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17204)

[multibody] Adjust test tolerances for mac arm64

---

common/copyable_unique_ptr.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17212)

[common] Add precondition checking to copyable_unique_ptr

---

geometry/BUILD.bazel
geometry/geometry_instance.h
geometry/geometry_state.cc
geometry/geometry_state.h
geometry/query_object.cc
geometry/query_object.h
geometry/scene_graph.cc
geometry/scene_graph.h
geometry/scene_graph_inspector.cc
geometry/scene_graph_inspector.h
geometry/test/geometry_state_test.cc
geometry/test/scene_graph_inspector_test.cc
geometry/test/scene_graph_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17007)

[geometry] Support registering deformable geometries

---

examples/manipulation_station/joint_teleop.py

Toward https://github.com/RobotLocomotion/drake/issues/14702, extracted parts from https://github.com/RobotLocomotion/drake/pull/16816.  Additionally, see [slack discussion here](https://drakedevelopers.slack.com/archives/C3YB3EV5W/p1652813084181929).
- Replace the deprecated pure python meshcat connection with the C++ interface.
- `args.meshcat` is now irrelevant, the meshcat visualizer is connected unconditionally.
- Add `-w` / `--open-window` to automatically open a browser to the meshcat server, argument options chosen to match meldis.
To test this PR, in one terminal run `bazel run //examples/manipulation_station:mock_station_simulation` to start the simulation.
In another terminal, two tests:
- `bazel run //examples/manipulation_station:joint_teleop -- --setup planar -w`: you will …

[examples] Update manipulation_station meshcat interface.

---

tools/workspace/cc/repository.bzl

Rewrite the logic in `cc/repository.bzl` to use a helper function for testing if the compiler is of a supported version, based on a dictionary of supported compilers. This replaces the previous logic which was heavily redundant and required the supported compiler version to be specified in multiple places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17146)

Simplify compiler checks

---

geometry/test/drake_visualizer_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17226)

[testing] Fix a bug in DrakeVisualizerTest

---

manipulation/planner/constraint_relaxing_ik.cc
manipulation/planner/constraint_relaxing_ik.h
manipulation/planner/test/constraint_relaxing_ik_test.cc

Closes #17189.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17224)

[planner] Add a keep_going option to ConstraintRelaxingIk

---

doc/_pages/release_playbook.md
tutorials/BUILD.bazel
tutorials/index.ipynb
tutorials/licensed_solvers_deepnote.ipynb

I have hosted the tutorial draft [here](https://deepnote.com/workspace/russtedrake-b58d8141-6691-43e8-ad76-0575b319c8b8/project/Enabling-licensed-solvers-on-Deepnote-7581ca0c-04be-4632-9108-f0426b6c3fbb/%2Flicensed_solvers_deepnote.ipynb) for code review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17213)

[tutorials] Add tutorial for using Mosek on Deepnote

---

multibody/parsing/detail_collision_filter_group_resolver.cc
multibody/parsing/detail_collision_filter_group_resolver.h
multibody/parsing/test/detail_collision_filter_group_resolver_test.cc

Relevant to: #14785
This patch implements a stronger enforcement of model encapsulation for
collision filters. Previously, filters defined outside any model could refer to
the world body or parts of the default model by scoped names, or to default
model bodies by unqualified names. Now, those references are parse errors, and
using a model index from outside the parse as a parameter is a programming
error.
There might ever be a reason (I couldn't think of one) to define collision
filters against the world body; I am fine for that to involve a special
privileged name and be future work.
I couldn't think of any reason why a model file should be able to refer to
bodies in the default model, which (in the current implementation of Parser),
could never be populated from model files.
---
This …

[parsing] Restrict collision filters to models within a parse operation

---

multibody/fem/BUILD.bazel
multibody/fem/fem_model.h
multibody/fem/test/volumetric_model_test.cc
multibody/fem/volumetric_model.h
multibody/plant/BUILD.bazel
multibody/plant/deformable_model.cc
multibody/plant/deformable_model.h
multibody/plant/multibody_plant_model_attorney.h
multibody/plant/physical_model.cc
multibody/plant/physical_model.h
multibody/plant/test/deformable_model_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17163)

[multibody] Add DeformableModel as a PhysicalModel

---

multibody/plant/multibody_plant.cc
multibody/plant/test/multibody_plant_test.cc

Fixes #15720.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17174)

[plant] MbP throws exceptions on NaN input port values

---

tools/wheel/wheel_builder/linux.py

Use the unique identifier as part of the image tag name when building the wheel test container. This allows us to *not* use said identifier (without collisions) when asked to preserve the tagged images, which in turn allows for inspection and debugging of the test environment.
+@svenevs for feature review, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17248)

Tweak wheel test image tag

---

systems/framework/system.cc
systems/framework/test/system_test.cc

Relates #14426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17255)

Add error guidance to Get*Port methods.

---

multibody/tree/multibody_tree.cc
multibody/tree/test/multibody_tree_test.cc

Along with #17255, resolves #14426
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17259)

Add error guidance to Get*ByName methods.

---

bindings/pydrake/solvers/mathematicalprogram_py.cc
bindings/pydrake/solvers/test/mathematicalprogram_test.py
solvers/BUILD.bazel
solvers/choose_best_solver.cc
solvers/choose_best_solver.h
solvers/test/choose_best_solver_test.cc

As discussed in #17203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17225)

add GetAvailableSolvers()

---

multibody/parsing/parsing_doxygen.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17271)

[parsing] Fix documentation typos

---

systems/primitives/BUILD.bazel
systems/primitives/shared_pointer_system.cc
systems/primitives/shared_pointer_system.h
systems/primitives/test/shared_pointer_system_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17260)

[primitives] Add SharedPointerSystem

---

manipulation/util/show_model.py

Towards #14702.
Related to #17214.
(When merging to master, we should squash down to a single commit.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17274)

[manipulation] Port show_model to meshcat C++

---

examples/quadrotor/quadrotor_plant.cc
examples/quadrotor/test/quadrotor_dynamics_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17254)

Resolves issue #17246 by fixing order of state in quadrotor_dynamics_test.cc

---

tools/workspace/json/package.BUILD.bazel

Sets the stage to revert the (never-used) #16231.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17283)

[workspace] Deprecate json external

---

setup/ubuntu/install_prereqs.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17284)

[setup] Fail fast if invoked with sudo when already root

---

tools/workspace/check_lists_consistency.bzl
tools/workspace/ignition_math/package.BUILD.bazel
tools/workspace/ignition_utils/package.BUILD.bazel

Towards #17288.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17293)

[workspace] Enhance check_lists_consistency docs and failure message

---

multibody/tree/body.h
multibody/tree/multibody_tree.cc
multibody/tree/multibody_tree.h
multibody/tree/rigid_body.h
multibody/tree/rotational_inertia.h
multibody/tree/test/multibody_tree_creation_test.cc
multibody/tree/test/rotational_inertia_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17261)

Internal function to sum default mass and check for zero rotational inertia.

---

bindings/pydrake/math_py.cc
bindings/pydrake/multibody/math_py.cc
bindings/pydrake/multibody/test/math_test.py
bindings/pydrake/test/math_test.py
common/test_utilities/expect_throws_message.h
manipulation/kinova_jaco/jaco_command_receiver.cc
manipulation/kinova_jaco/jaco_command_receiver.h
manipulation/kinova_jaco/test/jaco_command_receiver_test.cc
math/rigid_transform.h
math/rotation_matrix.h
math/test/rigid_transform_test.cc
math/test/rotation_matrix_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17296)

Remove deprecated code 2022-06

---

doc/_pages/pip.md

https://pypi.org/project/drake/#files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17316)

[doc] Remove outdated wheel version claims

---

tools/workspace/boost/repository.bzl

Follow-up from #17286.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17308)

[workspace] Deprecate boost external

---

tools/workspace/abseil_cpp_internal/repository.bzl
tools/workspace/common_robotics_utilities/BUILD.bazel
tools/workspace/common_robotics_utilities/package.BUILD.bazel
tools/workspace/common_robotics_utilities/repository.bzl
tools/workspace/dm_control/repository.bzl
tools/workspace/gz_math_internal/repository.bzl
tools/workspace/libcmaes/repository.bzl
tools/workspace/stduuid/repository.bzl
tools/workspace/voxelized_geometry_tools/repository.bzl

Towards #17306
Closes  #17321
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17322)

June 2022 upgrades

---

bindings/pydrake/solvers/BUILD.bazel
bindings/pydrake/solvers/csdp_py.cc
bindings/pydrake/solvers/test/csdp_solver_test.py
solvers/csdp_solver.cc
solvers/csdp_solver.h
solvers/csdp_solver_common.cc
solvers/sdpa_free_format.h
solvers/test/csdp_solver_test.cc
solvers/test/gurobi_solver_test.cc
solvers/test/ipopt_solver_test.cc
solvers/test/mathematical_program_test_util.cc
solvers/test/mathematical_program_test_util.h
solvers/test/mosek_solver_test.cc
solvers/test/scs_solver_test.cc
solvers/test/second_order_cone_program_examples.cc
solvers/test/second_order_cone_program_examples.h
solvers/test/semidefinite_program_examples.cc
solvers/test/semidefinite_program_examples.h
solvers/test/snopt_solver_test.cc

1. Deprecate the constructor with RemoveFreeVariableMethod argument.
2. Change the default method to kLorentzConeSlack.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17275)

CsdpSolver set RemoveFreeVariableMethod through SolverOptions.

---

bindings/pydrake/geometry_py_scene_graph.cc
bindings/pydrake/test/geometry_scene_graph_test.py

cc @SeanCurtis-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17336)

Add python binding for SceneGraph::RemoveGeometry

---

doc/_pages/installation.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17338)

[doc] Add hyperlink to broadwell flag

---

geometry/drake_visualizer.cc
geometry/drake_visualizer.h
geometry/geometry_state.cc
geometry/geometry_state.h
geometry/scene_graph_inspector.cc
geometry/scene_graph_inspector.h
geometry/test/drake_visualizer_test.cc
geometry/test/geometry_state_test.cc
geometry/test/scene_graph_inspector_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17253)

[visualization] DrakeVisualizer broadcasts deformable draw messages

---

bindings/pydrake/geometry_py_scene_graph.cc
bindings/pydrake/test/geometry_scene_graph_test.py
geometry/scene_graph.h

cc @SeanCurtis-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17342)

Add python binding for SceneGraph::RegisterGeometry with context

---

solvers/snopt_solver.cc
solvers/test/snopt_solver_test.cc

Without this, the macOS EH ABI cannot cross a C++/C boundary and would otherwise abort.
Closes #17079.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17272)

[solvers] Manually propagate exceptions within SNOPT

---

tools/release_engineering/dev/repack_deb.py

- Add __doc__ with a brief example usage description.
- Update the default of --output-dir to be the path that the user ran bazel from ('.' refers to something in the bazel sandbox).
- Fail early if the input .tar.gz or output directory cannot be found.
- Remove stale comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17317)

[tools/dev] Cleanup debian packaging script

---

doc/_pages/reviewable.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17345)

[doc] Add required "feature or fix" release notes tagging

---

common/BUILD.bazel
common/nice_type_name.cc
common/test/nice_type_name_test.cc
geometry/BUILD.bazel
geometry/kinematics_vector.cc

Update KinematicsVector to use it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17365)

[common] Add Identifier support to NiceTypeName

---

bindings/pydrake/systems/BUILD.bazel
tools/workspace/meshcat_python/BUILD.bazel
tools/workspace/meshcat_python/package.BUILD.bazel

Follow-up to #17194.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17374)

[workspace] Deprecate meshcat_python

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py
common/symbolic_trigonometric_polynomial.cc
common/symbolic_trigonometric_polynomial.h
common/test/symbolic_trigonometric_polynomial_test.cc

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17282)

[symbolic] Support half-angle formulas in sin/cos substitution.

---

geometry/render/BUILD.bazel
tools/install/libdrake/build_components.bzl
tools/install/libdrake/header_lint.bzl
tools/lint/library_lint.bzl

Successor to #17169 and #17376.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17377)

[render] Stop polluting downstream include paths with vtk

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py
common/BUILD.bazel
common/symbolic_polynomial.cc
common/symbolic_polynomial.h
common/test/symbolic_polynomial_test.cc

Resolves #17333
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17357)

Evaluate polynomial (with affine coefficients) on a batch of indeterminates

---

solvers/aggregate_costs_constraints.h
solvers/augmented_lagrangian.h
solvers/binding.h
solvers/branch_and_bound.h
solvers/choose_best_solver.h
solvers/create_constraint.h
solvers/decision_variable.h
solvers/get_program_type.h
solvers/indeterminate.h
solvers/integer_optimization_util.h
solvers/mathematical_program.h
solvers/mathematical_program_result.h
solvers/sdpa_free_format.h
solvers/sos_basis_generator.h
solvers/sparse_and_dense_matrix.h
solvers/test/branch_and_bound_test.cc
solvers/test/create_constraint_test.cc
solvers/test/mathematical_program_test.cc
solvers/test/second_order_cone_program_examples.cc
solvers/test/sos_constraint_test.cc
systems/trajectory_optimization/test/multiple_shooting_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17380)

add [[nodiscard]] to solvers folder.

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/lcm_py.cc
bindings/pydrake/test/lcm_test.py
examples/planar_gripper/planar_gripper_common.cc
lcm/BUILD.bazel
lcm/drake_lcm.cc
lcm/drake_lcm.h
lcm/drake_lcm_params.cc
lcm/drake_lcm_params.h
lcm/test/drake_lcm_test.cc
lcm/test/initialization_sequence_test_stub.cc
systems/lcm/BUILD.bazel
systems/lcm/lcm_interface_system.cc
systems/lcm/lcm_interface_system.h
systems/lcm/test/lcm_interface_system_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17337)

[lcm] Add option for a channel name suffix

---

geometry/geometry_state.cc
geometry/geometry_state.h
geometry/query_object.cc
geometry/query_object.h
geometry/scene_graph.cc
geometry/scene_graph.h
geometry/scene_graph_inspector.h
geometry/test/drake_visualizer_test.cc
geometry/test/geometry_state_test.cc
geometry/test/query_object_test.cc
geometry/test/scene_graph_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17258)

[geometry] Add configuration input ports in SceneGraph

---

multibody/benchmarking/BUILD.bazel
multibody/benchmarking/iiwa_relaxed_pos_ik.cc

This PR aims to resolve the CI issues of the reverted PR https://reviewable.io/reviews/robotlocomotion/drake/17299
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17373)

[multibody] Re-add an inverse kinematics benchmark resolving CI issues

---

bindings/pydrake/examples/quadrotor_py.cc
bindings/pydrake/examples/test/quadrotor_test.py
examples/quadrotor/quadrotor_plant.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17402)

expose parameters in QuadrotorPlant

---

tools/dynamic_analysis/bazel.rc

Towards #17268.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17405)

[build] Modernize bazel sanitizer configs

---

tools/workspace/gz_utils_internal/package.BUILD.bazel
tools/workspace/gz_utils_internal/repository.bzl
tools/workspace/new_release.py

Fix release heuristics to locate new releases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17417)

[workspace] Upgrade gz_utils to latest release 1.4.0

---

tools/workspace/sdformat_internal/embed_sdf.py

Hotfix for #17414.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17420)

[workspace] Fix libsdformat build on macOS (#17414)

---

tools/wheel/image/provision-python.sh

Hotfix for #17414.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17421)

[workspace] Fix libsdformat wheel build

---

geometry/kinematics_vector.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17411)

[geometry] Remove stale mentions of SourceId in comments

---

bindings/pydrake/examples/acrobot_py.cc
examples/acrobot/acrobot_plant.cc
examples/acrobot/acrobot_plant.h
examples/acrobot/test/acrobot_plant_test.cc

The previous input was systems::Parameters, which won't work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17423)

Use AcrobotParams for AcrobotPlant::SetMitAcrobotParameters

---

tools/workspace/abseil_cpp_internal/repository.bzl

To get the fix of abseil/abseil-cpp#1191 for #17412.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17431)

[workspace] Upgrade abseil_cpp_internal to latest commit

---

multibody/contact_solvers/BUILD.bazel
multibody/contact_solvers/newton_with_bisection.cc
multibody/contact_solvers/newton_with_bisection.h
multibody/contact_solvers/test/newton_with_bisection_test.cc

This method is used as our "exact" line search option in SAP.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17313)

Implements Newton method with bisection fallback

---

multibody/tree/multibody_tree_topology.h

Relates to #17429.
+@sherm1 for platform review, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17441)

[multibody] Clarify error message for unsupported tree structures

---

tools/release_engineering/README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17439)

[doc] Add release_engineering README

---

bindings/pydrake/math_example.py
bindings/pydrake/systems/drawing_graphviz_example.py
common/proto/call_python_client.py
examples/van_der_pol/plot_limit_cycle.py

Towards #14702. See #17438 for the big picture.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17437)

Lock down the MPLBACKEND setting for a few demo programs

---

doc/_pages/developers.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17448)

[doc] Update platform reviewer list

---

solvers/test/augmented_lagrangian_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17467)

Add AugmentedLagrangian test with an empty mathematical program

---

geometry/shape_specification.cc
geometry/shape_specification.h

- Initialize POD member fields.
- Only inline function definitions when they are used in inner loops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17473)

[geometry] Style guide tidy-ups on shape_specification

---

examples/multibody/cassie_benchmark/test/cassie_bench.cc

The AutoDiffXd heap use experiments that led to these regression tests were an incomplete, aborted experiment.
The counters were useful at the time while exploring the solution space, but now only add developer friction -- decreasing our development speed, rather than improving it.
There is no direct correlation between our computation throughout (the metric we care about) and whether we have 31,000 vs 40,000 allocations.  A guard for LimitMalloc is useful when in the process of driving the limit to zero (with incremental PRs) -- this is the case for the T==double benchmark cases.  Limits that only reflect an empirical reality rather than any algorithmic principle are change detector tests, and will tend to bog down development.
To the extent we care about having LimitMalloc test coverage …

[examples] Remove cassie AutoDiffXd change detector tests

---

multibody/plant/compliant_contact_manager.cc
multibody/plant/compliant_contact_manager.h
multibody/plant/test/compliant_contact_manager_test.cc

Manager must report accelerations to the plant so that we can compute reaction forces.
This PR implements that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17476)

CompliantContactManager computes accelerations cache

---

CMakeLists.txt

EWISOTT.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17480)

Update CMakeLists.txt to allow Jammy

---

multibody/plant/wing.h

obtained from Joe Moore.  
cc @rcory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17465)

[multibody/wing] Add more original reference for flat plate theory

---

common/autodiff.h
common/eigen_types.h
tools/workspace/eigen/repository.bzl

Add cross-referencing between workspace rule and header file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17498)

[common] Centralize Eigen minimum version requirement

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/sap_solver.cc
multibody/contact_solvers/sap/sap_solver.h
multibody/contact_solvers/sap/test/sap_solver_test.cc
multibody/plant/test/compliant_contact_manager_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17488)

SAP with exact line search

---

common/eigen_types.h
common/extract_double.h
common/symbolic/expression/expression.h
common/symbolic/polynomial.h
common/symbolic/trigonometric_polynomial.h
common/test/eigen_types_test.cc
solvers/branch_and_bound.h
solvers/mathematical_program.h
solvers/mathematical_program_result.h
solvers/test/branch_and_bound_test.cc

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17497)

[common] Add and use MatrixLikewise sugar typedef

---

common/symbolic/BUILD.bazel
common/symbolic/test/trigonometric_polynomial_test.cc
common/symbolic/trigonometric_polynomial.cc
common/symbolic/trigonometric_polynomial.h

This is the first step to introduce C_Iris into Drake.
cc @AlexandreAmice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17491)

Replace sin/cos in a symbolic polynomial with half-angle rational functions

---

tools/workspace/github.bzl

This fixes our `github_archive` macro to be compatible with the directory layout at https://github.com/mrdoob/stats.js for use in #16981.
Tested locally on macOS to confirm that it allows #16981 to build successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17534)

[tools] Don't rename github files or directories named "build"

---

geometry/benchmarking/BUILD.bazel
multibody/benchmarking/BUILD.bazel
solvers/benchmarking/BUILD.bazel
systems/benchmarking/BUILD.bazel
tools/performance/defs.bzl

Follow-up from #17526.
I do think that BUILD rules should be obvious and boring.  With an implicit default of true, this was too magical.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17535)

[benchmarking] Require an explicit choice for add_test_rule

---

doc/_pages/from_source.md
doc/_pages/installation.md

Update documentation to list Jammy as a supported platform.
(Split out from #17480.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17489)

Update documentation for Jammy

---

bindings/pydrake/BUILD.bazel

https://drake-jenkins.csail.mit.edu/job/linux-focal-gcc-bazel-experimental-debug/1661/ flaked.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17549)

[pydrake] Give a big unit test some extra time

---

multibody/plant/multibody_plant.cc
multibody/plant/multibody_plant.h
multibody/plant/multibody_plant_config_functions.cc

Closes #17524.  Follow-up from #17400.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17529)

[plant] Shore up enum-string conversion implementation

---

tools/install/dockerhub/jammy/.dockerignore
tools/install/dockerhub/jammy/Dockerfile
tools/install/dockerhub/jammy/README.md

Follow-up to https://github.com/RobotLocomotion/drake/issues/16217#issuecomment-1178416097
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17546)

[docker] Enable Jammy docker builds

---

multibody/contact_solvers/sap/sap_model.h
multibody/contact_solvers/sap/test/sap_solver_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17513)

Updates SAP's reference year

---

lcm/test/drake_lcm_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17561)

[lcm] De-flake a unit test again

---

doc/_pages/bazel.md

Per Slack: https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1657739376735959
Relates #14157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17569)

doc bazel: Mention editing Gurobi URL

---

bindings/pydrake/common/cpp_param.py
bindings/pydrake/common/test/deprecation_autocomplete_test.py
solvers/test/augmented_lagrangian_test.cc
tools/dynamic_analysis/valgrind.supp

Closes #13391.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17567)

Remove various lingering references to 18.04 support

---

common/BUILD.bazel
common/test/timer_test.cc

See https://drake-cdash.csail.mit.edu/test/780051388.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17578)

[common] Make wall-clock less flaky but still mark as flaky

---

math/autodiff.h
math/autodiff_gradient.h
math/test/autodiff_test.cc
tools/skylark/drake_cc.bzl

Requires #17497.  Towards #17492.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17516)

[math] Reduce implementation boilerplate for autodiff

---

doc/_pages/release_playbook.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17583)

Notes from v1.5.0 release experience

---

tools/dynamic_analysis/bazel.rc

CI is experiencing the OOM killer ~daily.
Towards #17560.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17593)

[tools] Reduce local_ram_resources under ASan

---

multibody/inverse_kinematics/orientation_constraint.cc
multibody/inverse_kinematics/orientation_constraint.h

This PR does not change any functionality. It only makes a few changes
to avoid some unnecessary computation and slightly clean the code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17591)

[inverse_kinematics] Speed up OrientationConstraint implementation

---

bindings/pydrake/symbolic_types_pybind.h
common/drake_assert.h
common/symbolic/expression/expression.h
common/symbolic/expression/formula.h
common/symbolic/monomial_util.h
common/symbolic/polynomial.h
common/symbolic/polynomial_basis.h

+@ggould-tri for both reviews per schedule, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17588)

[symbolic] Tidy up some comment cross-references

---

tools/dynamic_analysis/bazel.rc

Reverts RobotLocomotion/drake#17593
This did not have the impact we were hoping for.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17602)

Revert "[tools] Reduce local_ram_resources under ASan"

---

planning/BUILD.bazel
planning/robot_diagram.cc
planning/robot_diagram.h
planning/robot_diagram_builder.cc
planning/robot_diagram_builder.h
planning/test/robot_diagram_test.cc
systems/framework/diagram_builder.cc
systems/framework/diagram_builder.h
systems/framework/test/diagram_builder_test.cc
tools/install/libdrake/build_components.bzl

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17594)

[planning] Add RobotDiagram and RobotDiagramBuilder

---

geometry/proximity/BUILD.bazel
geometry/proximity/calc_distance_to_surface_mesh.cc
geometry/proximity/calc_distance_to_surface_mesh.h
geometry/proximity/test/calc_distance_to_surface_mesh_test.cc

Towards #16875.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17582)

[geometry] Calculate distance from point to triangle surface mesh

---

bindings/pydrake/common/test_utilities/numpy_compare.py
bindings/pydrake/symbolic_py.cc
bindings/pydrake/symbolic_types_pybind.h
bindings/pydrake/test/symbolic_test.py
common/drake_assert.h
common/symbolic/rational_function.cc
common/symbolic/rational_function.h
common/symbolic/test/rational_function_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17522)

Rational function python bindings

---

common/symbolic/expression/BUILD.bazel
common/symbolic/expression/all.h
common/symbolic/expression/boxed_cell.cc
common/symbolic/expression/boxed_cell.h
common/symbolic/expression/expression.cc
common/symbolic/expression/expression.h
common/symbolic/expression/expression_cell.cc
common/symbolic/expression/expression_cell.h
common/symbolic/expression/expression_kind.h
common/symbolic/expression/test/boxed_cell_test.cc

This is in preparation for refactoring Expression to use nanboxing (#17544).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17612)

[symbolic] Add BoxedCell helper class

---

common/symbolic/polynomial.cc
common/symbolic/polynomial.h
common/symbolic/test/polynomial_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17611)

Polynomial removes the term if is_zero(coeff) is true in that term.

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17617)

Add python binding of SubstituteStereographicProjection

---

systems/lcm/BUILD.bazel
systems/lcm/lcm_buses.cc
systems/lcm/lcm_buses.h
systems/lcm/lcm_config_functions.cc
systems/lcm/lcm_config_functions.h
systems/lcm/test/lcm_buses_test.cc
systems/lcm/test/lcm_config_functions_test.cc

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17614)

[lcm] Add LcmBuses and related config functions

---

bindings/pydrake/systems/lcm_py.cc
bindings/pydrake/systems/test/lcm_test.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17627)

[pydrake/lcm] Bind LcmBuses

---

examples/hardware_sim/BUILD.bazel
examples/hardware_sim/README.md
examples/hardware_sim/example_scenarios.yaml
examples/hardware_sim/hardware_sim.cc
examples/hardware_sim/scenario.cc
examples/hardware_sim/scenario.h
examples/hardware_sim/test/hardware_sim_test.py
examples/hardware_sim/test/test_scenarios.yaml

We'll also want to have a Python version of this program in the future, but for now we'll stick with C++ since that's what we have in Anzu (and so, the code will be easier to move).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17615)

Add demo program for hardware simulation

---

multibody/contact_solvers/sap/BUILD.bazel
multibody/contact_solvers/sap/sap_constraint.h
multibody/contact_solvers/sap/sap_holonomic_constraint.cc
multibody/contact_solvers/sap/sap_holonomic_constraint.h
multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc

Generic holonomic constraint. This will allow us to quickly implement welds, couplers and distance constraints in the manager.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17628)

Implements SAP holonomic constraint

---

bindings/pydrake/BUILD.bazel
bindings/pydrake/visualization/BUILD.bazel
bindings/pydrake/visualization/__init__.py
bindings/pydrake/visualization/test/config_test.py
bindings/pydrake/visualization/visualization_py.cc
bindings/pydrake/visualization/visualization_py.h
bindings/pydrake/visualization/visualization_py_config.cc
examples/hardware_sim/BUILD.bazel
examples/hardware_sim/hardware_sim.cc
examples/hardware_sim/scenario.h
examples/hardware_sim/test/test_scenarios.yaml
tools/install/libdrake/build_components.bzl
visualization/BUILD.bazel
visualization/test/visualizer_config_functions_test.cc
visualization/visualizer_config.cc
visualization/visualizer_config.h
visualization/visualizer_config_functions.cc
visualization/visualizer_config_functions.h

Towards #17112 and then (with forthcoming tweaks in #17641) towards #13673.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17645)

[visualization] Add ApplyVisualizerConfig

---

tools/wheel/image/setup.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17652)

[pydrake] Hotfix for broken wheels

---

common/ad/BUILD.bazel
common/ad/internal/standard_operations.cc
common/ad/internal/standard_operations.h
common/ad/test/standard_operations_integer_test.cc

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17657)

[ad] Add support for nearest-integer functions

---

common/ad/internal/standard_operations.h
common/ad/test/standard_operations_div_test.cc
common/ad/test/standard_operations_mul_test.cc

Amends #17622.  Towards #17492.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17656)

[ad] Fix gradients of in-place x*x and x/x

---

common/ad/BUILD.bazel
common/ad/internal/standard_operations.h
common/ad/test/standard_operations_abs2_test.cc
common/ad/test/standard_operations_abs_test.cc
common/ad/test/standard_operations_cmp_test.cc
common/ad/test/standard_operations_max_test.cc
common/ad/test/standard_operations_min_test.cc
common/ad/test/standard_operations_test.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17636)

[ad] Add support for comparison operations

---

bindings/pydrake/multibody/jupyter_widgets.py
bindings/pydrake/solvers/test/mathematicalprogram_test.py
doc/doxygen_cxx/system_doxygen.py
tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
tools/workspace/pybind11/pybind_coverage_libclang_parser.py
tools/workspace/pybind11/pybind_coverage_xml_parser.py

Fix some instances of Python keywords being styled as functions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17664)

Fix some Python code style errors

---

common/ad/BUILD.bazel
common/ad/internal/standard_operations.cc
common/ad/internal/standard_operations.h
common/ad/test/standard_operations_acos_test.cc
common/ad/test/standard_operations_asin_test.cc
common/ad/test/standard_operations_atan2_test.cc
common/ad/test/standard_operations_atan_test.cc
common/ad/test/standard_operations_cos_test.cc
common/ad/test/standard_operations_cosh_test.cc
common/ad/test/standard_operations_sin_test.cc
common/ad/test/standard_operations_sinh_test.cc
common/ad/test/standard_operations_tan_test.cc
common/ad/test/standard_operations_tanh_test.cc
common/ad/test/standard_operations_test.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17650)

[ad] Add support for trig and hyperbolic operations

---

tools/workspace/gz_math_internal/package.BUILD.bazel
tools/workspace/gz_math_internal/repository.bzl

Fixes #17665.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17673)

Upgrade gz_math_internal to latest version

---

geometry/render/dev/render_gltf_client/test/gltf_render_server.py
geometry/render_gltf_client/internal_render_client.cc
geometry/render_gltf_client/internal_render_client.h
geometry/render_gltf_client/internal_render_engine_gltf_client.cc
geometry/render_gltf_client/render_engine_gltf_client_params.h
geometry/render_gltf_client/test/internal_render_client_test.cc
geometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17675)

[geometry] reverse `no_cleanup` logic

---

bindings/pydrake/math_py.cc
bindings/pydrake/test/math_test.py
math/compute_numerical_gradient.h

Asked on stackoverflow https://stackoverflow.com/questions/73196013/troubleshooting-optimization-for-finding-a-robot-pose-in-equilibrium#comment129285124_73198325
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17684)

Add python binding for ComputeNumericalGradient

---

tools/install/bazel/test/drake_bazel_installed_test.py
tools/workspace/abseil_cpp_internal/repository.bzl
tools/workspace/common_robotics_utilities/repository.bzl
tools/workspace/dm_control_internal/repository.bzl
tools/workspace/googlebenchmark/repository.bzl
tools/workspace/pycodestyle/repository.bzl
tools/workspace/rules_python/repository.bzl
tools/workspace/styleguide/repository.bzl
tools/workspace/voxelized_geometry_tools/repository.bzl

Towards #17659.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17669)

August 2022 upgrades

---

geometry/render/dev/render_gltf_client/BUILD.bazel
geometry/render/dev/render_gltf_client/test/run_simulation_and_render.cc
geometry/render_gltf_client/BUILD.bazel
geometry/render_gltf_client/factory.cc
geometry/render_gltf_client/factory.h
geometry/render_gltf_client/test/factory_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17678)

[geometry] Move MakeRenderEngineGltfClient() from the dev folder

---

multibody/fem/fem_state.cc
multibody/fem/fem_state.h
multibody/fem/test/fem_state_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17686)

[fem] FemState supports cloning

---

bindings/pydrake/visualization/test/config_test.py
bindings/pydrake/visualization/visualization_py_config.cc
examples/hardware_sim/BUILD.bazel
examples/hardware_sim/hardware_sim.cc
examples/hardware_sim/scenario.h
examples/hardware_sim/test/test_scenarios.yaml
examples/kinova_jaco_arm/BUILD.bazel
examples/kinova_jaco_arm/jaco_simulation.cc
manipulation/util/show_model.py
visualization/BUILD.bazel
visualization/test/visualization_config_functions_test.cc
visualization/visualization_config.cc
visualization/visualization_config.h
visualization/visualization_config_functions.cc
visualization/visualization_config_functions.h
visualization/visualizer_config.cc

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17698)

[visualization] Rename AddDefaultVisualization and related

---

bindings/pydrake/solvers/solvers_py_gurobi.cc
bindings/pydrake/solvers/test/gurobi_solver_test.py

As requested from stackoverflow https://stackoverflow.com/q/72823452/1973861
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17704)

Add python binding on GurobiSolver callbacks

---

examples/hardware_sim/BUILD.bazel
examples/hardware_sim/example_scenarios.yaml
examples/hardware_sim/hardware_sim.cc
examples/hardware_sim/scenario.h
manipulation/util/BUILD.bazel
manipulation/util/apply_driver_configs.h
manipulation/util/test/zero_force_driver_functions_test.cc
manipulation/util/zero_force_driver.h
manipulation/util/zero_force_driver_functions.cc
manipulation/util/zero_force_driver_functions.h

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17694)

[manipulation] Add ZeroForceDriver for hardware_sim

---

solvers/gurobi_solver.cc

The user should change the MathematicalProgram to remove small
coefficients, rather than using this threshold hidden inside
gurobi_solver.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17648)

Remove sparseness_threshold in gurobi_solver

---

tools/workspace/common_robotics_utilities/repository.bzl
tools/workspace/voxelized_geometry_tools/repository.bzl

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17702)

Bump CRU & VGT to latest

---

multibody/fem/fem_solver.cc
multibody/fem/fem_solver.h
multibody/fem/test/fem_solver_test.cc

This replaces the scratch data kept as a mutable data member and allows FemSolver to be placed in a System.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17706)

[fem] FemSolver takes scratch as input on solve

---

common/benchmarking/BUILD.bazel
common/benchmarking/benchmark_polynomial.cc
tools/performance/BUILD.bazel

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17714)

Add benchmark on symbolic polynomial.

---

solvers/mathematical_program.cc
solvers/test/mathematical_program_test.cc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17712)

add positive_semidefinite_constraints when calling GetAllConstraints

---

bindings/pydrake/symbolic_py.cc
bindings/pydrake/test/symbolic_test.py
common/symbolic/BUILD.bazel
common/symbolic/replace_bilinear_terms.cc
common/symbolic/replace_bilinear_terms.h
common/symbolic/test/replace_bilinear_terms_test.cc
solvers/BUILD.bazel
solvers/bilinear_product_util.cc
solvers/mixed_integer_rotation_constraint.cc

As requested in stackoverflow https://stackoverflow.com/questions/72823452/how-to-use-callback-functions-of-gurobi-in-drake/72831395?noredirect=1#comment129374867_72831395
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17707)

Add python binding for ReplaceBilinearTerms

---

bindings/pydrake/geometry_py_hydro.cc
bindings/pydrake/test/geometry_hydro_test.py

Towards #17625.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17713)

[pydrake] More bindings for TriangleSurfaceMesh (hydroelastics APIs)

---

geometry/proximity/BUILD.bazel

Clean up BUILD.bazel in geometry/proximity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17722)

[geometry] Sort library names in proximity package alphabetically

---

multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
multibody/plant/compliant_contact_manager.cc
multibody/plant/multibody_plant.cc

Change references in the documentation to match our actual publication title and venue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17740)

Update paper references for discrete hydro

---

bindings/pydrake/geometry_py_hydro.cc
bindings/pydrake/test/geometry_hydro_test.py

Towards #17625.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17730)

[pydrake] More bindings for VolumeMesh (hydroelastics APIs)
