bindings/pydrake/test/trajectories_test.py, common/trajectories/piecewise_quaternion.h, common/trajectories/test/piecewise_quaternion_test.cc, systems/primitives/trajectory_source.h
The original implementation violates the contract set in the base class that the size of the result of value() is equal to rows()-by-cols().
closes #16909 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16914)
=> [trajectory] PiecewiseQuaternion returns Vector4 as values

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_solver.cc, multibody/contact_solvers/sap/sap_solver.h, multibody/contact_solvers/sap/sap_solver_results.cc, multibody/contact_solvers/sap/sap_solver_results.h, multibody/contact_solvers/sap/test/sap_solver_test.cc
The ContactSolver abstraction has been very useful to prototype and test a number of solver technologies, including SAP. However the SapSolver has now been engineered to exploit the sparsity of contact problems and no longer fits the much narrower ContactSolver abstraction. For instance, ContactSolver does not support general constraints, while SapSolver does.
In this PR:
1. SapSolver no longer inherits from ContactSolver.
2. Introduce SapSolverResults, instead of reusing the old ContactSolverResults, which does not support general constraints.
3. Refactor SapSolver unit tests in terms of the new SapSolverResults.
4. Move SapSolver files into `multibody/contact_solvers/sap`
Since Reviewable was smart enough to identify the moved files and differences, I decided to make this a single …
=> [WIP] SapSolver is no longer a ContactSolver

multibody/tree/multibody_tree_topology.h, multibody/tree/test/multibody_tree_creation_test.cc
Only trees with DOFs are considered in the multibody forest. Bodies anchored to the world do not have a tree assigned to them.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16897)
=> Tree topology only includes tress with non-zero DOFs.

doc/_pages/from_source.md
Resolves #16865.
The unprovisioned Mac builds switched to 5.1 over the weekend. For example (search for bazel 5.1 in the console ouput):
https://drake-jenkins.csail.mit.edu/view/Mac%20Monterey%20Unprovisioned/job/mac-monterey-unprovisioned-clang-cmake-weekly-release/14/consoleFull
https://drake-jenkins.csail.mit.edu/view/Mac%20Big%20Sur%20Unprovisioned/job/mac-big-sur-unprovisioned-clang-bazel-nightly-release/427/consoleFull
The provisioned Mac images are being updated now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16926)
=> [doc] Upgrade recommended Bazel version to 5.1 on Mac

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Closes: #16422
This is a generalization of the the already-existing code to filter
collisions within bodies welded to the world.  Now, we filter collisions
within any welded subgraph of the model.
On the way to constructing a test, remove some unused infrastructure and
(mostly) prefer method calls to multiple optional constructor
parameters.
Also, back-fill a test that should have accompanied PR #1116.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16920)
=> [multibody] Filter collisions within welded subgraphs

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/create_constraint.cc, solvers/create_constraint.h, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/create_constraint_test.cc, solvers/test/mathematical_program_test.cc
The conic solvers prefer rotated Lorentz cone constraint rather than the non-conic quadratic constraint.
resolves #16918 
cc @lujieyang
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16921)
=> [MathematicalProgram] Add convex quadratic constraint as rotated Lorentz cone constraint.

tools/workspace/mosek/BUILD.bazel, tools/workspace/mosek/drake_mosek_redistribution.txt, tools/workspace/mosek/repository.bzl
Towards #16439.
Tested locally that `bazel run //:install --config mosek -- --list /tmp/tmptmp` shows the new file as part of the install:
```
...
lib/libdrake_ibex.so
lib/libcilkrts.so.5
lib/libmosek64.so.9.2
share/doc/mosek/mosek-eula.pdf
share/doc/mosek/LICENSE_CilkPlus
share/doc/mosek/drake_mosek_redistribution.txt
share/doc/osqp/LICENSE
...
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16934)
=> [workspace] Add MOSEK redistribution contract to our installed docs

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic_decompose.cc, common/symbolic_decompose.h, common/test/symbolic_decompose_test.cc, solvers/constraint.cc, solvers/create_constraint.cc
Speed up parsing linear constraints by reducing number of heap memory allocation.
Resolves #16895
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16896)
=> Use std::vector instead of Eigen::Vector in ExtractAndAppendVariablesFromExpression

setup/BUILD.bazel, setup/deepnote/README.md, setup/deepnote/install_xvfb, setup/deepnote/xvfb, tools/install/bazel/generate_installed_files_manifest.bzl
Towards #16866.
Based on a mix of https://gist.github.com/dloman/8303932 and https://github.com/RobotLocomotion/drake-ci/blob/49c6ccb2955a3a8fa6a68dcce26405eb54fdc898/setup/ubuntu/install_prereqs#L79-L88
One this is available in a nightly docker image, in order for the tutorial to work, we'll need to somehow shell out to `install_xvfb` prior to doing any rendering.  My best guess for now is that `init.ipynb` should do that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16948)
=> [setup] Add xvfb init script for deepnote

doc/_pages/documentation_instructions.md, tools/workspace/doxygen/Dockerfile, tools/workspace/doxygen/build_binaries_with_docker, tools/workspace/doxygen/repository.bzl
Relates: #13391.
After running `./build_binaries_with_docker` the archives extract with a usable `doxygen` executable in a vanilla container:
```console
$ docker run --rm -it --volume "$(pwd):/data" ubuntu:focal               
root@e9fac7783533:/# tar -xf /data/doxygen-1.8.15-focal-x86_64.tar.gz              
root@e9fac7783533:/# ./doxygen --version
1.8.15
$ docker run --rm -it --volume "$(pwd):/data" ubuntu:jammy
root@c501096c7073:/# tar -xf /data/doxygen-1.8.15-jammy-x86_64.tar.gz 
root@c501096c7073:/# ./doxygen --version
1.8.15
```
Note: it may be advantageous to update to a new doxygen version at the same time that we add in jammy support.  Depending on #14670 and how quickly concepts become available in drake, it is advisable to target at least doxygen 1.9.2 (adds support for …
=> [workspace] Remove bionic doxygen build.

solvers/BUILD.bazel, solvers/sparse_and_dense_matrix.cc, solvers/sparse_and_dense_matrix.h, solvers/test/sparse_and_dense_matrix_test.cc
Use to hold a sparse matrix and an optional dense matrix.
As discussed in https://github.com/RobotLocomotion/drake/pull/16894#pullrequestreview-929279098
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16902)
=> Add SparseAndDenseMatrix class.

multibody/parsing/BUILD.bazel, multibody/parsing/detail_tinyxml.cc, multibody/parsing/detail_tinyxml.h, multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_tinyxml_test.cc, multibody/parsing/test/detail_urdf_geometry_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc
Based on my possibly flawed static analysis, this patch converts the
last message reachable from `AddModelFromUrdf()` via bad input.
Since this one routine is used many places, a few small changes require
a lot of new test cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16915)
=> [parsing] Plumb the last URDF error to diagnostic policy

tools/wheel/image/build-drake.sh, tools/wheel/image/build-wheel.sh, tools/wheel/test/test-wheel.sh
Towards #16439.
The wheel now additionally contains:
```
29054680  2022-04-07 17:24   pydrake/lib/libmosek64.so.9.2
718212  2022-04-07 17:24   pydrake/doc/mosek/mosek-eula.pdf
1515  2022-04-07 17:24   pydrake/doc/mosek/LICENSE_CilkPlus
3263032  2022-04-07 17:24   pydrake/solvers/mosek.cpython-38-x86_64-linux-gnu.so
```
(Maybe others; the above are just what matched `grep -i mosek`. Mostly to show/verify that license-related files are present.)
+@jwnimmer-tri for feature review, please
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16927)
=> Enable MOSEK in wheel builds.

setup/mac/source_distribution/Brewfile, setup/ubuntu/source_distribution/packages-focal-clang.txt, setup/ubuntu/source_distribution/packages-focal-test-only.txt, setup/ubuntu/source_distribution/packages-focal.txt
Modify setup scripts to also install clang-12. Ultimately, we want to get rid of clang-9, but this will allow us to switch CI builds to 12 without needing to lock-step changes in the main repo and CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16943)
=> Add clang-12 on Focal, macOS

examples/manipulation_station/BUILD.bazel, tools/workspace/pygame_py/package-stub.BUILD.bazel, tools/workspace/pygame_py/repository.bzl
- Bionic support removed, eliminating the need for the PyPI wheel to be obtained.
- As a result, the `@pygame_py` repository is no longer useful and is now deprecated.
For release notes:
- Release notes: removal of deprecated -- bionic support of `pygame` is removed.
- Release notes: newly deprecated -- `@pygame_py` repository is no longer meaningful and will be removed in the future.
Relates: #16945, #13391.  We should discuss this in the meeting, it also relates to #15958 and
https://github.com/RobotLocomotion/drake/blob/d57bec0c4cf87aa46604470fbe5311cd741bb903/tools/wheel/image/setup.py#L17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16959)
=> [workspace] Remove bionic pygame, deprecate @pygame_py repository.

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_solver.cc, multibody/contact_solvers/sap/sap_solver.h, multibody/contact_solvers/sap/test/sap_solver_test.cc
This PR updates the internal workings of `SapSolver` to use the better unit tested `SapModel`.
Things to note:
1. We do not unit test for pre-processed data anymore. PreProcessedData is effectively replaced by SapModel, which is much better tested elsewhere.
2. We do not unit test for number of evaluations, since SapModel now uses the `systems::` framework caching, which is also much better tested elsewhere.
3. This PR is mostly a refactor, and removes more code than what it adds new!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16930)
=> [SAP] SapSolver uses SapModel

bindings/pydrake/common/test_utilities/scipy_stub/scipy/sparse/__init__.py, bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/BUILD.bazel, solvers/constraint.cc, solvers/constraint.h, solvers/mosek_solver.cc, solvers/osqp_solver.cc, solvers/scs_solver.cc, solvers/snopt_solver.cc, solvers/test/constraint_test.cc
It can optionally also store a dense matrix A.
BoundingBoxConstraint stores the sparse identity matrix.
Since we are removing scipy dependency, I don't add the python binding for functions using sparse matrices.
The following solvers still use dense A matrix internally. I will fix them in separate PRs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16894)
=> LinearConstraint stores a sparse matrix A.

tools/workspace/intel_realsense_ros/repository.bzl
- The version of intel_realsense_ros remains unchanged.
- Add links to enable faster discovery of next release.
Relates: #13391, #16931.
It does not appear like they are producing new releases for noetic, but since officially the [bionic / melodic version](https://github.com/IntelRealSense/realsense-ros/releases/tag/2.3.2) is still there this is not "removal of deprecated". (?)  Just updating the comment so that when we `grep` for bionic / 18.04 this folder no longer shows up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16965)
=> [workspace] Update realsense comment melodic => noetic.

tools/workspace/python/repository.bzl
Currently supported: 3.8, 3.9.
Relates: #13391, #16929.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16973)
=> [wheel] manylinux 3.6 and 3.7 support dropped.

multibody/fem/petsc_symmetric_block_sparse_matrix.cc, multibody/fem/petsc_symmetric_block_sparse_matrix.h, multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc
Reverts RobotLocomotion/drake#16961
Dear @xuchenhan-tri ,
The (unofficial) build cop, @svenevs, believes that your PR #16961 may have
- https://drake-jenkins.csail.mit.edu/job/linux-focal-clang-bazel-continuous-everything-address-sanitizer/303/console
now. You can then fix the problem at your leisure, and send a …
=> Revert "[fem] Report status of Petsc solver"

tools/workspace/drake_visualizer/Dockerfile, tools/workspace/drake_visualizer/build_binaries_with_docker, tools/workspace/drake_visualizer/image/package.sh, tools/workspace/drake_visualizer/image/prereqs, tools/workspace/drake_visualizer/image/provision.sh, tools/workspace/drake_visualizer/repository.bzl
- Any non-focal distribution uses the fail-fast stub.
- Remove references to bionic artifacts.
- Rebuild and deploy new focal drake_visualizer tarball.
Relates: #13391, #16931.
Tested the new archive locally on focal and it works as expected.  In a vanilla docker container for jammy which I just installed `bazel` and a couple of packages (`lsb-release`, `gcc`, `g++`, and `python3-dev` iirc) I will get
```console
$ bazel run //tools:drake_visualizer
DEBUG: /data/tools/workspace/python/repository.bzl:127:14: 
WARNING: Python 3.10 is not a supported / tested version for use with Drake.
Supported versions on manylinux: ["3.6", "3.7", "3.8", "3.9"]
From interpreter: /usr/bin/python3
INFO: Analyzed target //tools:drake_visualizer (0 packages loaded, 0 targets configured).
INFO: Found 1 …
```
=> [workspace] Remove bionic support for drake_visualizer.

common/symbolic_expression_cell.cc, common/symbolic_expression_cell.h, common/test/symbolic_expansion_test.cc
Towards #16292.
In cases where we are operating on affine expressions over variables, notice when `is_expanded == true` must be true during construction, so that we don't need to re-expand it later.
This yields a ~2x speedup in `BenchmarkSosProgram1` (from approximately 9.8 seconds runtime to 4.3 seconds runtime, on my machine).
As of this change, all calls from the benchmark program to `Expression::Expand` are no-ops; the expression is always already known to be expanded.  Specifically, `bazel run //solvers/benchmarking:benchmark_mathematical_program` passes when using this patch to fail-fast on non-noops:
```patch
diff --git a/common/symbolic_expression.cc b/common/symbolic_expression.cc
index db191a6d0e..d12a617084 100644
--- a/common/symbolic_expression.cc
+++ …
```
=> [common] Improve symbolic polynomial performance via is_expanded

solvers/benchmarking/benchmark_mathematical_program.cc
This program computes the product between a polynomial with constant coefficients, and a polynomial with linear expression coefficients.
As mentioned in https://github.com/RobotLocomotion/drake/pull/16980#pullrequestreview-944568609
On my puget machine, before PR #16980 this test takes 15.9s. After #16980 it takes 11.2s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16986)
=> Add another SOS benchmark program.

multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
Adds notes about being able to use the `Convex` type as a compliant geometry in the hydroelastic user guide.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16995)
=> [geometry] Updates hydroelastic user guide for compliant convex feature.

tools/install/installer.py
Modify how we adjust RPATHs in installed libraries to rewrite paths to libraries that are being installed, regardless if they are already relative to `@loader_path`.
The reason for skipping already-absolute paths is unclear, since the absolute location is unlikely to be the desired path for the installed library. In particular, MOSEK, for reasons which are unclear, gets linked using an absolute path into the bowels of Bazel's private build area, which is certainly not going to exist on the machine of a user installing from a distribution tarball.
This replaces a previous, somewhat sketchy change that was rushed into production.
+@svenevs for feature review.
--- …
=> Fix install RPATH mangling

doc/doxygen_cxx/doxygen_extra.css, doc/pydrake/_static/css/custom.css
I don't know if these ever did anything, but as of today the only thing they do is slow down page loads with repeated DNS NACKs.
Towards #16993.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17005)
=> [doc] Remove broken cloudfront stylesheet links

doc/_pages/bazel.md, doc/_pages/profiling.md
Closes: #16856
Move the macOS profiling instructions from the bazel page to the profiling
instruction page; contents are otherwise unchanged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16957)
=> [doc] Move macOS profiling instructions

multibody/contact_solvers/sap/partial_permutation.cc, multibody/contact_solvers/sap/partial_permutation.h, multibody/contact_solvers/sap/sap_model.cc, multibody/contact_solvers/sap/test/partial_permutation_test.cc, multibody/contact_solvers/sap/test/sap_model_test.cc
Fixes bug in SapModel when making permutation in velocities and updates tests so that they lead to a non-trivial set of permutations.
@xuchenhan-tri, this fixes the clutter demo!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17004)
=> [SAP] Fixes bug with velocity permutations in SapModel

common/symbolic_polynomial.cc, solvers/mathematical_program.cc
1. Construct the polynomial using map instead of adding each terms.
2. Use Variables.insert instead of += to avoid redundant copying
Before this PR, BenchmarkSosProgram3 takes 14.5s. After this PR it takes 7.1s on my Puget.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17011)
=> Speedup MathematicalProgram::NewFreePolynomial.

doc/doxygen_cxx/doxygen_extra.css, doc/doxygen_cxx/footer.html, doc/doxygen_cxx/header.html.patch
Closes #16993.
Local preview is available as:
```
bazel run //doc/doxygen_cxx:build -- --serve
```
---
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16960)
=> [doc] Add new Doxygen header, footer, and style customizations

solvers/scs_solver.cc
As mentioned in https://github.com/RobotLocomotion/drake/pull/16894#issue-1189204649
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17006)
=> ScsSolver uses get_sparse_A from linear matrix.

bindings/pydrake/multibody/math_py.cc, bindings/pydrake/multibody/tree_py.cc, bindings/pydrake/symbolic_py.cc, tools/skylark/pybind.bzl
This is possible now that Clang 9 is our minimum supported version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17015)
=> [tools] Suppress pybind11 clang warning globally (not via pragmas)

systems/primitives/linear_system.cc, systems/primitives/test/linear_system_test.cc
It's funny that we didn't claim to support them before.  After all, the controllability and observability matrices are the same as for continuous-time systems. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17029)
=> [systems] Controllability and observability for discrete-time systems

tools/wheel/BUILD.bazel, tools/wheel/README.rst, tools/wheel/__init__.py, tools/wheel/wheel_builder/common.py, tools/wheel/wheel_builder/linux.py, tools/wheel/wheel_builder/main.py
Refactor wheel build script(s)
Refactor build-wheels script, moving the logic into a "package". This will ultimately simplify things if and when we want to support different (i.e. non-Docker) paradigms for building wheels, by moving key functionality into an abstracted layer that can be replaced by different logic.
One major change is that the build-wheels front end has been replaced by `bazel run //tools/wheel:builder`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16996)
=> Refactor wheel build script(s)

multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/test/parser_test.cc
Closes: #16954
Add a method to turn on strict parsing, and a test show it changes
diagnostic behavior.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17017)
=> [parsing] Add API to set strict parsing

examples/quadrotor/BUILD.bazel, examples/quadrotor/quadrotor_plant.cc, examples/quadrotor/quadrotor_plant.h, examples/quadrotor/test/quadrotor_plant_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17025)
=> [examples/quadrotor] hotfix: fix segfault when QuadrotorPlant input port was not connected

multibody/plant/test/multibody_plant_reflected_inertia_test.cc, multibody/tree/body_node.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h
This PR provides an additional set of MultibodyTree APIs to allow including diagonal inertia terms in forward dynamics computations. That is, we want to solve `v̇` from `(M+D)⋅v̇ + C⋅v = τ`, where D is an additional diagonal term. This diagonal term `D` can be used to model: reflected inertias (continuous system), implicit joint damping (discrete system), implicit joint springs (discrete system), and maybe others.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17016)
=> Include additional diagonal inertias in forward dynamics

doc/_pages/bazel.md, setup/ubuntu/install_prereqs.sh, setup/ubuntu/source_distribution/install_prereqs.sh, tools/bazel.rc, tools/macos.bazelrc, tools/ubuntu-focal.bazelrc
Add ability to select which compiler to use by passing an appropriate `--config` to Bazel. Update documentation accordingly.
In addition to being more convenient for users, this moves the specification of what clang version to use (only relevant on Ubuntu) to the Bazel configuration, rather than the user needing to specify this. This will also allow this information to be removed from the CI infrastructure.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17043)
=> Add Bazel config for compiler selection

examples/atlas/atlas_run_dynamics.cc
Reverts #15814. 
As a side effect, #16035 allows larger time step in the atlas example without making the simulation unstable, so we reverts to the original larger default timestep, 1e-3s.
Relates to #15782.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17049)
=> [atlas] Revert to a larger default time step

multibody/plant/BUILD.bazel, multibody/plant/tamsi_solver.cc, multibody/plant/test/multibody_plant_forward_dynamics_test.cc
Resolves the immediate failure identified in #17037.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17038)
=> [multibody] Replace M.ldlt() in Tamsi no-contact path with LinearSolver

bindings/pydrake/multibody/parsing_py.cc, multibody/parsing/detail_path_utils.cc, multibody/parsing/package_map.cc, multibody/parsing/package_map.h, multibody/parsing/test/detail_path_utils_test.cc, multibody/parsing/test/package_map_test.cc
The objective here is to allow the user to opt-in to throwing exceptions for deprecations via #17017.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17047)
=> [parsing] Route package deprecations into the diagnostic channel

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/BUILD.bazel, multibody/plant/test/wing_test.cc, multibody/plant/wing.cc, multibody/plant/wing.h
This initial implementation only provides flat plate aerodynamics for
now, but is written with an interface that will allow it to be
extended.
This is an updated implementation of a similar functionality that we
had in the matlab version of Drake:
https://github.com/RobotLocomotion/drake/blob/last_sha_with_original_matlab/drake/matlab/systems/plants/%40RigidBodyWing/RigidBodyWing.m
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17027)
=> [multibody] implements a Wing class to provide basic aerodynamics

tools/cc_toolchain/BUILD.bazel, tools/cc_toolchain/print_compiler_config.sh
Create a tool to capture what compiler is being requested via `--config={gcc,clang}`. This information is needed by the CI infrastructure. (Specifically, CI needs a way to extract the potentially version-dependent name of the Clang compiler that is selected by `--config=clang`, so that this information does not need to also live in the CI repository.)
+@jwnimmer-tri for feature review, please. (Unless you know someone else with deep Bazel-fu?)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17050)
=> Add tool to capture and report --config compiler

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc
Closes #15018.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17060)
=> [parsing] Invalid SDFormat syntax is now an error (not warning)

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc
Mostly, just clarify our plans for future work, and be sure to notice when SDFormat adds new joint types (via C++ switch-enum warnings).
To provide more context for the TODOs -- as discussed in slack, to the extent that we can best-effort deal with unimplemented features (while warning about it to the user), that is probably the best UX.  It will allow the user to actually create a MbP and play with it, resolving the warnings later in due course.
Closes #16784.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17054)
=> [parsing] Slightly improve joint parsing diagnostics

multibody/parsing/test/detail_urdf_parser_test.cc
Add a dummy namespace to perturb the elf header.
Closes #17070.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17071)
=> [parsing] Work around test error in coverage builds (kcov 339)

bindings/pydrake/multibody/meshcat_py.cc, bindings/pydrake/multibody/test/meshcat_test.py, bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/meldis.py, bindings/pydrake/visualization/test/meldis_test.py, multibody/meshcat/BUILD.bazel, multibody/meshcat/contact_visualizer.cc, multibody/meshcat/contact_visualizer.h, multibody/meshcat/contact_visualizer_params.h, multibody/meshcat/hydroelastic_contact_visualizer.cc, multibody/meshcat/hydroelastic_contact_visualizer.h, multibody/meshcat/point_contact_visualizer.h, multibody/meshcat/test/contact_visualizer_test.cc, multibody/meshcat/test/hydroelastic.sdf
This PR introduces the `HydroelasticContactVisualizer` helper class that publishes hydroelastic contacts to Meshcat. It does not depend on `struct ContactResults` directly and can thus be used by both `meldis` and `drake::multibody::meshcat::ContactVisualizer` for in-process Meshcat. In addition, this PR also hooks up this new class into the two consumer classes and is operational. This version currently publishes just the force and moment vectors for each hydroelastic contact.
For an easy way of visualizing the new feature, run:
```
bazel run //tools:meldis -- -w &
```
and 
```
bazel run //examples/hydroelastic/spatula_slip_control:spatula_slip_control
```
And in the meshcat controls make sure to turn on the contact results visualization by clicking the check box for  "CONTACT_RESULTS". …
=> [multibody] Adds hydroelastic force and moment vector visualization.

bindings/pydrake/common/__init__.py, bindings/pydrake/common/module_py.cc, bindings/pydrake/common/test/module_test.py, bindings/pydrake/common/test/text_logging_example.py, bindings/pydrake/common/test/text_logging_test.py, bindings/pydrake/common/text_logging_pybind.cc
Deprecate the confusing and now-superfluous pydrake `set_log_level` function.
Inspired by #16901 (as further discussed in #16941).  Closes #16942.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17069)
=> [pydrake] Changing Python logging level also changes C++ level

.bazelrc
Change `.bazelrc` to always and unconditionally import `environment.bazelrc`, which will ensure that this has been duly created by the setup process and is error-free.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17082)
=> Always import environment.bazelrc

tools/install/BUILD.bazel, tools/install/__init__.py, tools/install/install.bzl, tools/install/installer.py, tools/install/otool.py
Create a new Python module for parsing the output of (macOS) `otool` into structured data. Use this in `installer.py`.
The new module supports extraction of load commands (`otool -l`, only the "Load Command N" blocks) and linked libraries (`otool -L`), and should be slightly more robust than the prior parsing code, particularly the old load command parsing which acted on any "path" key without regard to the type of command to which the key belonged. This will also allow this logic to be reused for other tools that need to perform RPATH manipulations.
Also fix a problem that prevented `installer.py` from having dependencies (thanks to @jwnimmer-tri).
+@svenevs for feature review, please.
--- …
=> Add a module for parsing otool output

doc/_pages/issues.md, doc/_pages/platform_reviewer_checklist.md
Drop the "team" label, add more "component" labels, and add a wider assortment of individual "lead"s for the various components.
For now, this is a rough draft to serve as a basis for discussion.  My hope is that we can evolve it to reach consensus.
Actions to take if adopted:
(1) For components being removed (i.e. `geometry externals`), switch any open issues or PRs that use it to a different GH component, and then rename the GH labels to "unused component: ..." and change their color.
(2) Add new GH labels for the new components proposed here.
(3) Update all GH component label descriptions to match this document.
(4) Triage existing issues without a component, and assign one.
(5) Remove "team: ..." labels from all open issues and PRs.
(6) Rename "team ..." labels to "unused team: ..." …
=> [doc] Refresh our issues policy

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
Rewrite "count the attributes" to avoid `vector<bool>` and obey our style to always write out null checks literally.
Add a unit test that exercises the desired error condition.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17091)
=> [parsing] Mitigate mujoco valgrind error with Clang 12

math/autodiff_gradient.h, solvers/moby_lcp_solver.cc
Towards #16937.
Refer to https://reviews.llvm.org/D67122 for details.
We are not allowed (for example) to form zero-sized blocks into zero-sized matrices, at least not with Eigen 3.3.7.
Here is the relevant Eigen upstream code, same as what we have today on Ubuntu:
https://gitlab.com/libeigen/eigen/-/blob/c2f15edc43367c3a11aacbb51c7431ccb5a31bb5/Eigen/src/Core/Block.h#L349-350
In the problematic cases, we have `xpr.data() == nullptr` yet we also have `i > 0`, such that we're computing non-zero pointer offsets from null, which is UB.
This fault is detected by our forthcoming Clang 12 UBSan builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17094)
=> [math] Remove some pointer-offset UB

common/BUILD.bazel, common/test/openmp_test.cc, doc/_pages/bazel.md, tools/ubuntu-focal.bazelrc, tools/workspace/libcmaes/package.BUILD.bazel, tools/workspace/scs/package.BUILD.bazel
Towards #14858.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16606)
=> [tools] Add opt-in build flags (and unit test) for OpenMP

multibody/tree/body_node.h
Towards #16937 and #17113.
Refer to https://reviews.llvm.org/D67122 for details.
We are not allowed (for example) to form zero-sized blocks into zero-sized matrices, at least not with Eigen 3.3.7.
This fault is detected by our forthcoming Clang 12 UBSan builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17095)
=> [multibody] Remove some pointer-offset UB

solvers/integer_inequality_solver.cc
Towards #16937 and #17113.
Refer to https://reviews.llvm.org/D67122 for details.
We are not allowed (for example) to form zero-sized blocks into zero-sized matrices, at least not with Eigen 3.3.7.
This fault is detected by our forthcoming Clang 12 UBSan builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17096)
=> [solvers] Remove some pointer-offset UB

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_reaction_forces_test.cc, multibody/plant/test/multibody_plant_test.cc
Relates to #17059.
Change the semantic of the old `get_actuation_input_port()` from getting the one and only actuation input port to the input port for all actuated instances.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17107)
=> [plant] Remove stacked actuation port

geometry/render_gltf_client/render_gltf_client_doxygen.h, geometry/render_gltf_client/test/README.md
This is one of the PRs to migrate RenderRpc development code from `//geometry/render/dev` to `//geometry/render_gltf_client`. This PR promotes the high-level Doxygen file and marks it as `experimental` to provide the context of the project and facilitate code reviews. Note that the content of the file is subject to change during the upcoming pull requests.
For more information, please see the [Drake project board](https://github.com/RobotLocomotion/drake/projects/8), especially [this ticket](https://github.com/RobotLocomotion/drake/issues/15915).
Relates #16750
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17040)
=> Add temporary Doxygen doc for glTF client-sever API

tools/workspace/petsc/patches/mal.patch, tools/workspace/petsc/repository.bzl
Work around an undefined-behavior sanitizer runtime failure in PETSc, "applying zero offset to null pointer", by adjusting the logic for the case when no bytes are allocated.
Reported as https://gitlab.com/petsc/petsc/-/issues/1180.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17102)
=> Work around PETSc 1180

math/BUILD.bazel, math/differentiable_norm.cc, math/differentiable_norm.h, math/test/differentiable_norm_test.cc, multibody/optimization/quaternion_integration_constraint.cc, multibody/optimization/quaternion_integration_constraint.h, multibody/optimization/test/quaternion_integration_constraint_test.cc, multibody/plant/test/wing_test.cc, multibody/plant/wing.cc
As discussed in
https://stackoverflow.com/questions/72154972/trajectory-optimization-on-custom-quadrotor-system-nan-detected-during-differe/72160960
the `Wing` class implementation was using a vector `norm()` call that
is not differentiable at zero velocity.  For quadrotors, that's no
good.
I found `internal::DifferentiableNorm` hidden in the
`QuaternionIntegrationConstraint`. This is a gem.  I've moved it to
`math`, and called it from `Wing`.
+@hongkai-dai for feature review. 
I'm marking this as priority high, to see if it can land in time for the final project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17127)
=> [math] Move DifferentiableNorm to math; use it in Wing.

tools/macos-arch-arm64.bazelrc
Towards #17009.
At the moment, IBEX's vendored filib library is hard-coded to use x86 assembly code. Ideally, we should find a way to build it on ARM64 at which point we can re-enable IBEX and dReal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17122)
=> [tools] Disable dReal and IBEX on ARM64

solvers/gurobi_solver.cc
In the GurobiTest.TestCallbacks the cbget function was a no-op for some reason, leaving the double value uninitialized.
As of Clang 12 UBSan, this is detected now (sometimes).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17133)
=> [solvers] Fix UB in Gurobi bindings

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
When adding SOS polynomial constraint, set the name of the Gram matrix. This is useful for debugging SOS.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17114)
=> Allow the user to specify the print out name of the Gram matrix.

tools/dynamic_analysis/bazel.rc
This TODO hails from a time when we were using the `f2c` build of SNOPT.  Now that we use the Fortran build of SNOPT, apparently we are sufficiently safe now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17134)
=> [tools] Enable -fsanitize=pointer-overflow for UBSan Everything

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/analysis_test.py
I ran into this error working with `ExternallyAppliedSpatialForce`:
```
dtype = object arrays must be copied, and cannot be referenced
```
Once I understood the fix, I scanned quickly for other
`.def_readwrite` statements that could have been missing the same, and
found one more on that pass.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17126)
=> [pydrake] Add a few missing `rvp_copy` attributes

tools/workspace/petsc/patches/baij.patch, tools/workspace/petsc/repository.bzl
Work around some undefined-behavior sanitizer runtime failure in PETSc, "applying zero offset to null pointer", in the BAIJ code, by checking for some cases where a pointer might be `NULL`.
Reported as https://gitlab.com/petsc/petsc/-/issues/1183.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17136)
=> Work around PETSc 1183

bindings/pydrake/solvers/mathematicalprogram_py.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, math/quadratic_form.cc, math/test/quadratic_form_test.cc, solvers/create_constraint.cc, solvers/create_constraint.h, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/create_constraint_test.cc
When the minimal eigen value of Q is smaller than -psd_tol, then we throw an error.
This helps when Q is computed numerically and being marginally psd.
cc @lujieyang
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17125)
=> AddQuadraticAsRotatedLorentzConeConstraint takes optinal psd_tol

examples/acrobot/BUILD.bazel, examples/acrobot/acrobot_plant.h, examples/acrobot/test/acrobot_plant_test.cc, examples/compass_gait/compass_gait.cc, examples/compass_gait/compass_gait.h, examples/compass_gait/test/compass_gait_test.cc, examples/pendulum/BUILD.bazel, examples/pendulum/pendulum_plant.h, examples/pendulum/test/pendulum_plant_test.cc, examples/quadrotor/quadrotor_plant.h
The PendulumPlant, AcrobotPlant, and CompassGait examples all crashed
if the input port was not properly connected.  I've provided default
input values for them here.
Related to #17025.
Note: In jupyter (both deepnote and locally), then were manifesting as
just completely silent kernel crashes, with absolutely no
hint/diagnositics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17145)
=> [examples] fix segfaults when input ports were not connected.

multibody/fem/test/dummy_element.h, multibody/fem/volumetric_element.h
Move definition of the `Data` struct out of `FemElementTraits` and alias it instead to prevent the typename hasher's warning about nested class.
Relates #17109.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17159)
=> [fem] Suppress warning message from typename hasher in Value

tools/install/installer.py, tools/workspace/drake_visualizer/drake_visualizer_installed.py.in, tools/workspace/drake_visualizer/image/build-lcm.sh, tools/workspace/drake_visualizer/image/package.sh, tools/workspace/drake_visualizer/repository.bzl
- Inbound .deb packaging updates require the VTK-8 libraries to be able to resolve to their counterparts, this fixes it for the install
logic and therefore in the .tar.gz package as well.
- Previously installer.py was skipping the VTK-8 libraries due to their .so.1 suffix, this is now fixed.
- rpath entries in the director tarball have been fixed, including removing entries to /opt that create conflicts when the system being installed on contains the same paths.
- Installed drake-visualizer no longer needs to modify LD_LIBRARY_PATH to run bin/.drake-visualizer-real as the rpaths have been fixed.
- New director tarball uploaded to S3.
NOTE: this is the only one that seems required to fix, `shlibdeps` gives a hard error on these ones.
The S3 archive is likely to be overwritten pending some …
=> [workspace] Fix drake-visualizer install rpath entries.

perception/test/point_cloud_flags_test.cc
Apple Clang is about to start barking about our use of a deprecated trait.
Towards #17009.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17165)
=> [perception] Remove broken test case

tools/install/installer.py
This logic needs to remain after drake-visualizer is removed, mosek was also getting its rpath fix (incorrectly) skipped.
In #17105 we fixed the rpaths for drake-visualizer, but the included fix also repaired the rpath for libmosek.  In testing #17058 against the v1.2.0 tarball, in addition to resurrecting the changes in #17105 the following was needed to get past `shlibs`, it failed being unable to find `libcilkrts.so.5`:
```py
subprocess.check_call([
"patchelf",
"--set-rpath",
"$ORIGIN",
str(drake_lib / "libmosek64.so.9.2")
])
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17173)
=> [install] Correct comment from #17105

systems/analysis/runge_kutta5_integrator.h
The text said the error estimate is 2nd order but I think that was a paste-o from the RK3 integrator's doc. I also found the page with the coefficients listed and updated the documentation to refer to it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17140)
=> Fix typo in Runge Kutta 5 integrator documentation

solvers/BUILD.bazel, solvers/defs.bzl
Most solver unit tests can still build in the absence of the third-party dependency (because the test only uses SolverInterface), but tests of utility wrappers often directly use the missing third-party header(s), so we can't even compile them.
Towards #17009 to enable `--define=NO_DREAL` to pass CI.
Tested locally on Ubuntu via `bazel test //solvers/... --define=NO_DREAL=ON`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17164)
=> [solvers] Disable building certain tests when solvers are disabled

manipulation/util/show_model.py
Added a visualization to `show_model.py` for link and world frames.
This is based on Russ' [AddTriad() method](https://github.com/RussTedrake/manipulation/blob/master/manipulation/scenarios.py#L367)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17141)
=> [manipulation] add visualization of frames in show_model.py

bindings/pydrake/geometry_py_optimization.cc, geometry/optimization/graph_of_convex_sets.cc
Previously, when one called `GraphOfConvexSets::GetGraphvizString`
with `result=None`, they would see a spurious `]` in the vertex
labels. The parenthesis is now placed properly inside the conditional.
Also adds a missing default for `result` in the python binding.
+@jwnimmer-tri for both reviews, please (for Monday, per rotation).
fyi @mpetersen94 , @TobiaMarcucci
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17190)
=> [geometry/optimization] Minor cleanup of `GraphOfConvexSets::GetGraphvizString`

systems/controllers/dynamic_programming.cc, systems/controllers/finite_horizon_linear_quadratic_regulator.cc, systems/primitives/linear_system.cc, systems/primitives/test/linear_system_test.cc, systems/trajectory_optimization/direct_collocation.cc, systems/trajectory_optimization/direct_transcription.cc, systems/trajectory_optimization/test/direct_collocation_test.cc
If I had a nickel for every time somebody called,
e.g. DirectCollocation with a MultibodyPlant and did not understand
the error message...
Previously
```
from pydrake.all import MultibodyPlant, DirectCollocation, Parser, FindResourceOrThrow
plant = MultibodyPlant(0.0)
Parser(plant).AddModelFromFile(
FindResourceOrThrow('drake/examples/multibody/cart_pole/cart_pole.sdf'))
plant.Finalize()
context = plant.CreateDefaultContext()
DirectCollocation(plant, context, 10, 0.1, 1.0)
```
would result in
```
Failure at systems/framework/system.cc:40 in AllocateInputVector(): condition 'input_port.get_data_type() == kVectorValued' failed.
```
Now DirectCollocation and the related methods provide a more helpful error message string.
--- …
=> [control] Improve error message for planning and control input port selections

tools/workspace/gfortran/repository.bzl
Towards #17009, where @jwnimmer-tri commented "I just peeked at
https://packages.ubuntu.com/focal/libgfortran5 and can confirm that
quadmath is [amd64, i386] only. When we're building on ARM64, we
should neither try to find -lquadmath, nor link to it."
+@jwnimmer-tri for platform review please (both if you're ok with it).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17196)
=> Remove -lquadmath when building on mac arm64

geometry/optimization/iris.h, geometry/optimization/test/iris_in_configuration_space_test.cc
Previously the default was to have Ibex enabled, but this has fallen
out of favor -- we find that Ibex cannot solve many problems of
interest.
In addition, we allow the test that requires Ibex to pass quietly if
IbexSolver is not available + enabled.  This is required for tests to
pass on mac arm64.
fyi @mpetersen94, @AlexandreAmice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17198)
=> [geometry/optimization] Make `IrisOptions.enable_ibex = false` by default

solvers/benchmarking/benchmark_mathematical_program.cc
As mentioned in #17160 
On my P15, here is the runtime
```
Run on (12 X 5100 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x6)
L1 Instruction 32 KiB (x6)
L2 Unified 256 KiB (x6)
L3 Unified 12288 KiB (x1)
Load Average: 1.27, 0.77, 1.02
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
---------------------------------------------------------------
Benchmark                     Time             CPU   Iterations
---------------------------------------------------------------
BenchmarkSosProgram1 2562965393 ns   2562783619 ns            1
BenchmarkSosProgram2 6263067961 ns   6262941729 ns            1
BenchmarkSosProgram3 6136089087 ns   6135849605 ns            1
```
--- …
=> Add a BenchmarkSosProgram3

bindings/pydrake/_geometry_extra.py, bindings/pydrake/geometry_py_visualizers.cc, bindings/pydrake/systems/all.py, bindings/pydrake/systems/meshcat_visualizer.py, bindings/pydrake/systems/test/meshcat_visualizer_test.py, bindings/pydrake/test/geometry_visualizers_test.py, manipulation/util/show_model.py
Closes #16978.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17194)
=> [pydrake] Deprecate old Python-based meshcat implementation

setup/ubuntu/source_distribution/packages-focal-maintainer-only.txt
.tar.gz => .deb repackaging needs these tools.
Slack discussion [here](https://drakedevelopers.slack.com/archives/C01JSGRR1QS/p1652195119814329), relates to https://github.com/RobotLocomotion/drake-ci/pull/157 and https://github.com/RobotLocomotion/drake/issues/17177.
Builds testing that `--with-maintainer-only` correctly installs `alien` and `fakeroot` can be found in the description of https://github.com/RobotLocomotion/drake-ci/pull/157: successful `linux-focal-unprovisioned-gcc-bazel-experimental-snopt-mosek-packaging` builds there are built in jenkins with both PRs together, `repack_deb` would fail if `--with-maintainer-only` packages here were not working as expected).
--- …
=> [tools/dev] Install alien and fakeroot for maintainers.

common/symbolic_expression_cell.cc, common/symbolic_expression_cell.h, common/symbolic_monomial.cc, common/test/symbolic_expansion_test.cc, common/test/symbolic_monomial_test.cc
This makes almost no difference in the benchmarks for now, but could turn out to be important later (for #17160). In any case, it bothers my sense of aesthetics for a Monomial to claim to be un-expanded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17201)
=> [common] Monomial.ToExpression.is_expanded is true

examples/compass_gait/test/compass_gait_test.cc, systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
Towards #17009.
+@jwnimmer-tri for both reviews, please.  (I'm the author of both of these tests, and I approve).
@drake-jenkins-bot mac-m1-monterey-unprovisioned-clang-bazel-experimental-release please
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17208)
=> [systems, examples] Adjust test tolerances for mac arm64

examples/manipulation_station/joint_teleop.py
Running joint_teleop without `--test` will crash otherwise.
In one terminal, you can `bazel run //examples/manipulation_station:mock_station_simulation` to get the simulation running.
Prior to this change, the following will crash `bazel run //examples/manipulation_station:joint_teleop` since `iiwa_velocities` is only declared when `args.test` is `True`, otherwise it is `None`.  After this change the example will produce the desired sliders, and `--test` appears to work the same as it did before.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17216)
=> [examples] Only declare iiwa_velocities_log when args.test.

doc/_pages/release_playbook.md
In prepping for v1.3.0, was reviewing playbook. I didn't see `build-wheel`, but `tools/wheel/README.rst` indicated Bazel script was the way to go.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17215)
=> release_playbook: Update instructions for building wheel

solvers/mathematical_program.cc, solvers/test/mathematical_program_test.cc
This removes 0-term in the polynomial, so potentially could reduce the size of the monomial basis and the resulting psd matrix if there were 0-term.
As discussed in https://github.com/RobotLocomotion/drake/pull/17123#pullrequestreview-965343278
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17187)
=> Expand the polynomial before computing the monomial basis for sos constraint

tools/workspace/qhull/package.BUILD.bazel, tools/workspace/qhull/patches/disable_dead_code.patch, tools/workspace/qhull/repository.bzl
Don't build unnecessary files: Coordinates.cpp, PointCoordinates.cpp, QhullPoints.cpp, QhullStat.cpp, RboxPoints.cpp, rboxlib_r.c.
This makes our build and object code footprint smaller, and enables a [future commit](https://github.com/jwnimmer-tri/drake/commits/vendoring) to use a better technique for C++ symbol visibility.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17227)
=> [workspace] Remove globbing from qhull build

geometry/render/dev/render_gltf_client/BUILD.bazel, geometry/render/dev/render_gltf_client/internal_render_client.cc, geometry/render_gltf_client/BUILD.bazel, geometry/render_gltf_client/internal_http_service_curl.cc, geometry/render_gltf_client/internal_http_service_curl.h, geometry/render_gltf_client/test/internal_http_service_curl_test.cc, tools/install/libdrake/build_components.bzl
This PR is part of the [RenderRpc project](https://github.com/RobotLocomotion/drake/projects/8) that moves the development code of `HttpServiceCurl` class and its tests to `//geometry/render_gltf_client`. The class derives from `HttpService` and utilizes `libcurl` to transfer the data and files (if any) to a render server for rendering.
Since the code is moved out of a dev folder, please review the full file of  `render_gltf_client/internal_http_service_curl.{h, cc}` and `render_gltf_client/test/internal_http_service_curl_test.cc`.
A high-level project overview can be found [here](https://drake.mit.edu/doxygen_cxx/group__render__engine__gltf__client__server__api.html).
Close #16745
--- …
=> Move HttpServiceCurl to //geometry/render_gltf_client

multibody/parsing/BUILD.bazel, multibody/parsing/detail_collision_filter_group_resolver.cc, multibody/parsing/detail_collision_filter_group_resolver.h, multibody/parsing/detail_common.cc, multibody/parsing/detail_common.h, multibody/parsing/detail_parsing_workspace.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/parser.cc, multibody/parsing/parsing_doxygen.h, multibody/parsing/scoped_names.cc, multibody/parsing/scoped_names.h, multibody/parsing/test/detail_collision_filter_group_resolver_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/collision_filter_group_parsing_test/package.xml, multibody/parsing/test/sdf_parser_test/collision_filter_group_parsing_test/robot.sdf, multibody/parsing/test/sdf_parser_test/collision_filter_group_parsing_test/test.sdf, multibody/parsing/test/sdf_parser_test/interface_api_test/arm.forced_nesting_sdf, multibody/parsing/test/sdf_parser_test/interface_api_test/arm.urdf, multibody/parsing/test/sdf_parser_test/interface_api_test/gripper.sdf, multibody/parsing/test/sdf_parser_test/interface_api_test/top.sdf
Relevant to: #14785
This patch extends the parsing of collision filter groups so that collision
filters can be defined across multiple robots by using SDFormat model
composition.
Summary of changes:
* add CollisionFilterGroupResolver, with unit test
* port existing parser modules to use it
* modernize a few sdf_parser errors
* demonstrate multi-robot filters in sdf_parser_test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17175)
=> [parsing] Enable multi-robot collision filter groups

tools/workspace/ignition_math/repository.bzl, tools/workspace/ignition_utils/repository.bzl, tools/workspace/new_release.py, tools/workspace/sdformat/repository.bzl
The ignitionrobotics organization is now empty; development has moved to the gazebosim organization, so we should to update github_archive to point to the new organization.  For the math and utils libraries, the repository name also changed from ign to gz; that requires a checksum update as well, because the source tarballs embed that name.
Upstream also no longer uses GitHub release announcements for minor releases. Therefore, we need to use tags when checking for new releases.
Closes #17235.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17240)
=> [workspace] For sdformat and related, use gazebosim not ignition

bindings/pydrake/multibody/meshcat_py.cc, bindings/pydrake/multibody/test/meshcat_test.py, multibody/meshcat/BUILD.bazel, multibody/meshcat/joint_sliders.cc, multibody/meshcat/joint_sliders.h, multibody/meshcat/test/joint_sliders_test.cc
Relates: #16816.
- Enable the sliders to be updated using a vector of positions the same length as the MultibodyPlant::num_positions(), indices that correspond to joint sliders will update the meshcat UI.
- Add corresponding python bindings and related tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17247)
=> [multibody] Add meshcat JointSliders::SetPositions

tools/skylark/drake_cc.bzl
In support of #17250, we should fail-fast if the macro definitions change in the future.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17256)
=> [tools] Promote macro-redefined to an error

examples/manipulation_station/BUILD.bazel, examples/manipulation_station/joint_teleop.py, examples/manipulation_station/schunk_wsg_buttons.py
Toward #14702.
- Always create the `meshcat` instance regardless of `args.hardware`.
- Replace the deprecated python `JointSliders` with `multibody.meshcat`.
- Add a new meshcat specific `SchunkWsgButtons` helper class to open and close the gripper.
- Note: when using this against hardware, if the gripper is closed when we run joint_teleop then the teleop will command gripper-open and the robot would drop whatever it's holding.  However, that is the same behavior as the old code and will be fixed in a followup.
-----------------------------
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16816)
=> [examples] Add meshcat sliders / buttons to manipulation_station

bindings/pydrake/test/geometry_scene_graph_test.py, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/scene_graph.h, geometry/test/geometry_state_test.cc, geometry/test/scene_graph_test.cc
Closes: #7122
Track the set of frame names for each source, and use that to reject
duplicates. Add a unit test for the new message, and adjust some other tests
that needlessly used duplicate names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17243)
=> [geometry] Reject duplicate-named frames for same source

multibody/parsing/BUILD.bazel, multibody/parsing/detail_composite_parse.cc, multibody/parsing/detail_composite_parse.h, multibody/parsing/model_directives.h, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/process_model_directives.cc, multibody/parsing/test/model_directives_test.cc, multibody/parsing/test/process_model_directives_test.cc, multibody/parsing/test/process_model_directives_test/collision_filter_group.yaml, multibody/parsing/test/process_model_directives_test/simple_model.sdf, multibody/parsing/test/process_model_directives_test/sub_collision.yaml
Closes: #17242
Define a new directive for collision filters (equivalent to current XML
formats), and enable multi-model collision filter processing in
ProcessModelDirectives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17270)
=> [parsing] Add collision filters via model directives

bindings/pydrake/test/symbolic_test.py
Embarrassingly, one of the python unit tests (covering ToLatex) was not
actually running in CI, because the method name did not start with
"test".  Unsurprisingly, it was full of small errors.
The similar occurrence in TestSinCosSubstitution is being fixed in #17282.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17285)
=> [py/symbolic] fix: Actually run TestToLatex

examples/kuka_iiwa_arm/BUILD.bazel, tools/workspace/lcm/lcm.bzl, tools/workspace/lcm/package.BUILD.bazel
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17289)
=> [workspace] Reduce header footprint of generated LCM messages

manipulation/util/geometry_inspector.py
Relates: #14702
- Replace deprecated python only MeshcatVisualizer with the C++ multibody.meshcat.
- Meshcat is always created and used in order to create the JointSliders.
- Remove --joint_position option which has no analagous C++ method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17214)
=> [geometry] Update geometry_inspector to multibody.meshcat

examples/manipulation_station/BUILD.bazel, examples/manipulation_station/end_effector_teleop_sliders.py
Relates: #14702.
- Use C++ bound `pydrake.geometry.Meshcat` over the deprecated pure python Meshcat interface.
- Replace the tkinter sliders with Meshcat sliders.
- Remove the keyboard controls that were available as an alternate control mechanism for the sliders.  The simulation / robot can only be controlled using the Meshcat sliders now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17292)
=> [examples] Update manipulation station end_effector sliders Meshcat

geometry/meshcat.cc, tools/workspace/msgpack/repository.bzl
Fixes an unwanted dependency added in #15694.  After this, we can finally deprecate and remove our dependency on Boost.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17286)
=> [workspace] Remove msgpack boost dependency

tools/macos-arch-arm64.bazelrc
Relates: #17262, #17026.
Mosek < 10 do not support arm64 macOS.
~~Note: this PR is also being used to stress test m1 CI changes unrelated to the changes here.~~ (not possible https://github.com/RobotLocomotion/drake/pull/17269#issuecomment-1137593748)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17269)
=> [workspace] Append WITH_MOSEK=OFF for arm64 macOS

tools/wheel/image/build-dependencies.sh, tools/workspace/boost/repository.bzl, tools/workspace/double_conversion/repository.bzl, tools/workspace/fmt/repository.bzl, tools/workspace/gfortran/repository.bzl, tools/workspace/libjpeg/repository.bzl, tools/workspace/nlopt/repository.bzl, tools/workspace/openblas/repository.bzl, tools/workspace/opengl/repository.bzl, tools/workspace/os.bzl, tools/workspace/pkg_config.bzl, tools/workspace/python/repository.bzl, tools/workspace/snopt/repository.bzl, tools/workspace/spdlog/repository.bzl, tools/workspace/suitesparse/repository.bzl, tools/workspace/vtk/repository.bzl
Add support for the recently added "macos_wheel" target/platform. Add ability to override the platform on macOS, which finishes implementing the "macos_wheel" target/platform that was recently introduced. Implement support for the same. This should, with a proper environment, allow Drake to be built in a mode that can be used to produce a wheel.
(Scripts to actually perform such a build, and particularly to establish the aforementioned "proper environment", will be added in subsequent commits.)
Also, explicitly add the pkg-config paths to Bazel's search paths to allow us to find dependencies built for wheels. This is required as we cannot inject these into /usr/local on macOS, as we would in the Ubuntu Docker containers.
--- …
=> Implement macos_wheel platform

examples/manipulation_station/end_effector_teleop_mouse.py
- Use C++ bound `pydrake.geometry.Meshcat` over the deprecated pure python Meshcat interface.
- Meshcat argument `--open_browser` is now `-w` or `--open-window` for consistency with the other examples.
- Meshcat argument `--meshcat` requests the meshcat interface, previous options related to ZMQ url etc are no longer available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17298)
=> [examples] Update manipulation station end_effector mouse Meshcat

common/yaml/yaml_read_archive.cc, common/yaml/yaml_write_archive.cc, tools/workspace/BUILD.bazel, tools/workspace/vendor_cxx.bzl, tools/workspace/vendor_cxx.py, tools/workspace/vendor_cxx_test.py, tools/workspace/yaml_cpp_internal/package.BUILD.bazel
Update `@yaml_cpp_internal` to follow the new style.
For use in #17229 and #17230 and more afterwards.  (Those serve as more examples of this macro.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17278)
=> [workspace] Add reusable macro and documentation for vendor_cxx

tools/install/BUILD.bazel, tools/wheel/BUILD.bazel, tools/wheel/Dockerfile, tools/wheel/image/build-dependencies.sh, tools/wheel/image/build-drake.sh, tools/wheel/image/build-vtk.sh, tools/wheel/image/build-wheel.sh, tools/wheel/image/dependencies/patches/suitesparse/patch.cmake, tools/wheel/image/dependencies/patches/suitesparse/patch.diff, tools/wheel/image/dependencies/projects.cmake, tools/wheel/image/provision-base.sh, tools/wheel/image/provision-python.sh, tools/wheel/image/setup.py, tools/wheel/macos/build-wheel.sh, tools/wheel/macos/change_lpath.py, tools/wheel/macos/strip_rpath.py, tools/wheel/wheel_builder/linux.py
Create a script to build a wheel on macOS. Update various Bazel logic to support the `macos_wheel` platform. Add scripts to mangle library load paths on macOS. Update inner wheel build script to support macOS as well as `manylinux`. Update various inner build scripts to support a build root other than `/`, since macOS does not permit creation of arbitrary top-level directories.
Note that the wheel build requires that the user running the scripts is able to use `brew`, and has write access to `/opt`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17307)
=> Add macOS wheel build scripts

geometry/internal_geometry.h
I know, I know, internal headers don't get doxygen doc generated. Still,
our doxygen mimickry should be consistent and not misleading.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17314)
=> [geometry, doc] Move unrelated accessor out of a doc group

math/eigen_sparse_triplet.h, solvers/osqp_solver.cc
When it was given a dense matrix by mistake, it included all of the zeros in the returned triplets (and induces a compilation error vs Eigen trunk).
Fix OsqpSolver to not try to pass a dense matrix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17331)
=> [math] Fix SparseMatrixToTriplets to only permit sparse matrices

common/BUILD.bazel, common/test/identifier_test.cc, common/test/type_safe_index_test.cc, common/test_utilities/expect_throws_message.h, geometry/render/dev/render_gltf_client/test/internal_render_client_test.cc, geometry/test/meshcat_test.cc, multibody/contact_solvers/sap/test/partial_permutation_test.cc, multibody/contact_solvers/test/supernodal_solver_test.cc, multibody/tree/test/articulated_body_inertia_test.cc, systems/analysis/test/antiderivative_function_deprecated_test.cc, systems/analysis/test/initial_value_problem_deprecated_test.cc, systems/analysis/test/scalar_initial_value_problem_deprecated_test.cc, systems/analysis/test/scalar_view_dense_output_test.cc
The documentation required an expression, but the implementation accidentally allowed for a block instead. Now it fails-fast.
Also suppresses "unused result" warnings for the expressions in question. This is helpful when a function is marked "nodiscard".
Towards #17330.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17341)
=> DRAKE_EXPECT_THROWS_MESSAGE now requires an expression

tools/wheel/image/build-dependencies.sh, tools/wheel/image/build-wheel.sh, tools/wheel/image/dependencies/patches/mumps/patch.cmake, tools/wheel/image/dependencies/patches/mumps/patch.diff, tools/wheel/image/dependencies/projects.cmake, tools/wheel/image/dependencies/projects/ipopt.cmake, tools/wheel/image/dependencies/projects/mumps.cmake, tools/wheel/image/packages-focal, tools/wheel/test/test-wheel.sh
Point our wheel build of IPOPT at MUMPS. Because MUMPS is copyleft, we must consume it as a shared library. On Ubuntu, this means we can just use the distro-provided package. On macOS, we must build it from source, as it is not packaged separately in Homebrew. (Homebrew normally builds it as part of the IPOPT build.)
Fixes #17162.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17346)
=> Add MUMPS to IPOPT when building wheels

multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
The claimed precondition (#8954) was that the MbP was finalized; this was true at the time, but as of today (#13281) is neither necessary nor enforced; now it's removed from the docs.
The actual precondition is that the MbP has an associated SceneGraph, which was enforced but not documented; now it's documented.
(There is a lot of code in Anzu that goes to great lengths to Finalize a MbP prior to working with collision filters.  All of that hassle is unnecessary.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17350)
=> [plant] Fix precondition docs for CollectRegisteredGeometries

multibody/benchmarking/BUILD.bazel, multibody/benchmarking/iiwa_relaxed_pos_ik.cc
- Adds an inverse kinematics benchmark to probe nonlinear programming performance with relaxed position constraints
- Aims to evaluate the impact of the analytical gradients proposed in https://reviewable.io/reviews/robotlocomotion/drake/16635 (i.e., only for position constraints and SNOPT)
- **Local** A/B results for running the benchmark using SNOPT (applying the changes with respect to https://github.com/RobotLocomotion/drake/commit/c37e81cb0ce85d5366d0bb88243d1b36e851e667, i.e., w/o rebasing w/ the latest master):
```
-------------------------------------------------------------------------------------
Derivative           Time            CPU            Iterations
-------------------------------------------------------------------------------------
AlgoDiff          23404360 ns …
```
=> [multibody] Add an inverse kinematics benchmark

common/symbolic_formula.h
This macro is a work-around for GCC 4.3 (released March 2008!), so is of no use to us; it has been removed on Eigen trunk.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17332)
=> [common] Stop using EIGEN_EMPTY_STRUCT_CTOR

common/symbolic_polynomial.h, common/test/symbolic_polynomial_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17330)
=> Add [[nodiscard]] to symbolic::Polynomial functions.

multibody/parsing/detail_common.h, multibody/parsing/detail_ignition.h, multibody/parsing/detail_sdf_diagnostic.h, multibody/parsing/detail_sdf_geometry.cc, multibody/parsing/detail_sdf_geometry.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_geometry_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, tools/workspace/BUILD.bazel, tools/workspace/gz_math_internal/package.BUILD.bazel, tools/workspace/gz_math_internal/repository.bzl, tools/workspace/gz_utils_internal/package.BUILD.bazel, tools/workspace/gz_utils_internal/repository.bzl, tools/workspace/sdformat_internal/BUILD.bazel, tools/workspace/sdformat_internal/package.BUILD.bazel, tools/workspace/sdformat_internal/patches/1043.patch, tools/workspace/sdformat_internal/repository.bzl
When building C++ code, we can't use `-fvisibility=hidden` because it infects all #included code, even the standard library. Instead, we should wrap the third-party C++ code in a inline hidden namespace. That way, only the third-party code itself is hidden.
Requires:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17230)
=> [workspace] Use sdformat hidden visibility

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc, multibody/tree/test/door_hinge_test.cc, systems/framework/system_scalar_conversion_doxygen.h
This should be in the cc file per https://drake.mit.edu/styleguide/cppguide.html#Inline_Functions.
This is a breaking change in the sense that anyone who has accidentally called this internal-use only constructor (when building with Clang) might now receive a linker error.
C++ users should call, e.g., `System::ToAutoDiffXd` instead of this constructor. Python users are unaffected.
---
The Doxygen now says this:
> The supported method to perform scalar conversion uses the member functions on System, e.g., `System::ToAutoDiffXd`. The scalar-converting copy constructor (described below) is intended for internal use only.
The reason we need to steer people that way is because the constructor is incomplete.  The `ToAutoDiffXd` does extra work beyond the constructor:
- copies the system's name …
=> [plant] Move scalar conversion constructor to cc file

tools/workspace/common_robotics_utilities/repository.bzl, tools/workspace/voxelized_geometry_tools/repository.bzl
Upstream changes bring CRU & VGT warning-free with Clang on their set of warnings (somewhat different than Drake, including -Wconversion that Clang is pickier about).
+@jwnimmer-tri  for review, thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17359)
=> Bump CRU and VGT to address Clang warnings

tools/workspace/clang_cindex_python3_internal/repository.bzl, tools/workspace/pybind11/mkdoc.py, tools/workspace/pybind11/pybind_coverage_libclang_parser.py
The version of clang-cindex-python3 we were using breaks with Python 3.10, which will prevent us from adding Jammy support (or if we want to add 3.10 support for macOS, which we'll probably want to do eventually). Update to the "latest" upstream version (which is already almost two years old!), which works with Python 3.10.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17315)
=> Update clang-cindex-python3 to the latest version.

tools/workspace/nlopt_internal/package.BUILD.bazel, tools/workspace/nlopt_internal/patches/gen_enums.patch
The spam used to look like this:
```
[8:15:20 AM]  INFO: From Executing genrule @nlopt_internal//:nlopt_hpp_genrule:
[8:15:20 AM]  patching file bazel-out/k8-dbg/bin/external/nlopt_internal/genrule/nlopt.hpp
[8:15:20 AM]  Hunk #1 succeeded at 46 with fuzz 2 (offset 7 lines).
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17367)
=> [workspace] Remove nlopt_internal build console spam

tools/wheel/BUILD.bazel, tools/wheel/README.rst, tools/wheel/image/packages-macos, tools/wheel/macos/build-wheel.sh, tools/wheel/macos/test-wheel.sh, tools/wheel/wheel_builder/common.py, tools/wheel/wheel_builder/linux.py, tools/wheel/wheel_builder/macos.py, tools/wheel/wheel_builder/main.py
Add a macOS platform module to Drake's wheel builder, using the previously created scripts. Add a new provisioning step (only via the builder). Modify the builder to run in the actual current working directory rather than wherever `bazel run` wants to run it (fixes misinterpretation of relative paths given as arguments, particularly to `--output-dir`). Improve reporting of default arguments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17347)
=> Add macOS support to wheel builder

tools/performance/benchmark_tool.py
Closes: #17369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17371)
=> [tools] benchmark_tool: Fail fast if we can't control turbo settings

bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py, systems/controllers/linear_quadratic_regulator.cc, systems/controllers/linear_quadratic_regulator.h, systems/controllers/test/linear_quadratic_regulator_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17327)
=> Add equality constraints in LQR.

geometry/render/gl_renderer/BUILD.bazel, tools/install/libdrake/header_lint.bzl, tools/skylark/drake_cc_per_os.bzl
In #17377 coming up next, we can finally retire a lot of library pollution.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17376)
=> [gl_renderer] Stop polluting downstream include paths with opengl

solvers/BUILD.bazel, solvers/sdpa_free_format.cc, solvers/test/csdp_solver_test.cc, solvers/test/sdpa_free_format_test.cc
Or throws an error if the empty constraint is infeasible.
Resolves #17340
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17368)
=> SdpaFreeFormat ignores empty constraint.

common/yaml/test/yaml_performance_test.cc, examples/acrobot/test/multibody_dynamics_test.cc, geometry/proximity/mesh_to_vtk.cc, geometry/test/geometry_state_test.cc, geometry/test/utilities_test.cc, multibody/contact_solvers/sap/partial_permutation.cc, multibody/fixed_fem/dev/deformable_rigid_mesh_intersection.cc, multibody/tree/test/weld_mobilizer_test.cc, systems/analysis/test/hermitian_dense_output_test.cc, systems/framework/diagram.cc
Fix some code that's tripping `-Werror=range-loop-construct`. Fix a missing include. Fix a `-Werror=maybe-uninitialized`.
Specifically, new compilers don't like two things: taking a copy of the loop item where a reference will do, and taking a reference when the loop item's type is specified such as to force a conversion, since this is taking a reference to a temporary. (The latter is arguably poor form, anyway, as it effectively hides a conversion.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17378)
=> Fix some build errors on Jammy

manipulation/models/README.md
As discussed in #10531, the issue that this README was referring to
has been closed; the README is no longer relevant.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17384)
=> [manipulation/models] Zap now irrelevant README

multibody/parsing/BUILD.bazel, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/test/parser_test.cc
This adds the plumbing to parse into the MuJoCo format (MJCF) from the
main Parser class.
Resolves #16369.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17358)
=> [multibody] Add support for MJCF to Parser.

bindings/pydrake/symbolic_py.cc, common/symbolic_decompose.cc, common/symbolic_decompose.h, common/symbolic_polynomial.cc, common/test/symbolic_decompose_test.cc, solvers/create_constraint.cc, solvers/create_cost.cc
Previously we pass coeffs as a const reference, and use const_cast to modify the value of coeffs. This violates GSG.
As discussed in slack https://drakedevelopers.slack.com/archives/C2ETTRXT7/p1654617805286029
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17348)
=> DecomposeAffineExpression passes coeffs as a pointer.

tools/workspace/fmt/repository.bzl, tools/workspace/ibex/include_limits.patch, tools/workspace/ibex/repository.bzl
Patch ibex to fix some places where it was using `std::numeric_limits` without including `<limits>`. Use non-bundled libfmt.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17388)
=> Fix some third party projects to build on Jammy

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/test/deprecation_autocomplete_test.py, bindings/pydrake/common/test/deprecation_test.py
Separate the autocompletion portion of `deprecation_test.py` (from `bindings/pydrake/common`), as it causes strange things to happen to the module's reference count under Jammy (Python 3.10), resulting in that portion of the test failing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17392)
=> Split pybind deprecation test

solvers/minimum_value_constraint.cc
As discussed in https://tri-internal.slack.com/archives/C01R4DSPMCN/p1655311252815549?thread_ts=1655308892.342349&cid=C01R4DSPMCN
In the documentation of MinimumValueConstraint we said
```
This value must be finite and strictly positive, as it is used
to scale the values returned by `value_function`
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17404)
=> Check if influence_value_offset is strictly positive in MinimumValueConstrant

tools/wheel/image/build-wheel.sh
Tweak wheel generation to remove additional data files. This is necessary as recent changes have caused us to exceed the PyPI size limit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17401)
=> Remove more data from wheels

manipulation/models/jaco_description/urdf/j2s7s300.urdf, manipulation/models/jaco_description/urdf/j2s7s300_arm.urdf, manipulation/models/jaco_description/urdf/j2s7s300_arm_sphere_collision.urdf, manipulation/models/jaco_description/urdf/j2s7s300_sphere_collision.urdf
* The existing limits were placeholder values.
* For the jaco, we have documented limits from the manual.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17407)
=> Set joint velocity limits for iiwa and jaco arms

bindings/pydrake/geometry_py_scene_graph.cc, bindings/pydrake/test/geometry_scene_graph_test.py, examples/pendulum/test/pendulum_geometry_test.cc, geometry/BUILD.bazel, geometry/kinematics_vector.cc, geometry/kinematics_vector.h, geometry/test/kinematics_vector_test.cc, systems/rendering/test/multibody_position_to_geometry_pose_test.cc, tools/workspace/abseil_cpp_internal/patches/disable_int128_on_clang.patch, tools/workspace/abseil_cpp_internal/patches/fix_constexpr_storage_deprecation.patch, tools/workspace/abseil_cpp_internal/repository.bzl
Change the implementation of KinematicsVector to use a absl::flat_hash_map.
Rename KinematicsVector::ids() to KinematicsVector::GetAllIds() without
deprecation (since ids() was introduced in between releases).
The original PR was reverted due to post-merge CI failures. This reverts the reverting
PR and fixes the UBSan failures.
Co-authored-by: Jeremy Nimmer <jeremy.nimmer@tri.global>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17394)
=> [geometry] Improve KinematicsVector

solvers/fbstab/BUILD.bazel, solvers/fbstab/fbstab_algorithm.h
It is unused within Drake and has forked into a [different upstream](https://github.com/dliaomcp/fbstab) which is being actively maintained, unlike the Drake copy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17416)
=> [solvers] Deprecate fbstab

tools/workspace/sdformat_internal/BUILD.bazel, tools/workspace/sdformat_internal/embed_sdf.py
(The bloaty report names this file as the number one offender.)
When embedding the sdformat schema into our runtime library, minify the xml data first to save space (remove descriptions, comments, and whitespace).
Store the raw data in a constexpr array, to avoid unwanted inlined initialization code.
Use const char pairs when constructing the map; otherwise we get a bajilion map insertion overloads with various `char[]` array sizes.
Remove the global destructor from the resulting map (style guide).
For my current build, this reduces `libdrake.so` by 453 KiB (0.7%), or when zipped by 93 KiB (0.5%).
Relates to #17403 somewhat.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/ …
=> [workspace] Reduce the libsdformat footprint

bindings/pydrake/systems/test/sensors_test.py
Hotfix for for #17428.  Tested locally on macOS.
Here's the error from a build of `master`:
https://drake-jenkins.csail.mit.edu/view/Production/job/mac-monterey-clang-bazel-continuous-release/721/
```
[2022-06-21T19:41:42.403Z] ==================== Test output for //bindings/pydrake/systems:py/sensors_test:
[2022-06-21T19:41:42.403Z] 
[2022-06-21T19:41:42.403Z] Running tests...
[2022-06-21T19:41:42.403Z] ----------------------------------------------------------------------
[2022-06-21T19:41:42.403Z] F.....
[2022-06-21T19:41:42.403Z] ======================================================================
[2022-06-21T19:41:42.403Z] FAIL [0.004s]: test_camera_info (sensors_test.TestSensors)
[2022-06-21T19:41:42.403Z] ---------------------------------------------------------------------- …
```
=> [pydrake] Hotfix for broken sensors_test on macOS

common/BUILD.bazel, common/identifier.h, common/test/identifier_test.cc
The default hashing (delegating to std::hash) leads to an incredible amount of extra object code in the in-progress improvements to the kinematics_vector implementation when using absl::flat_hash_map.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17412)
=> [common] Add direct Abseil hashing support for Identifier

examples/manipulation_station/end_effector_teleop_sliders.py, examples/manipulation_station/joint_teleop.py
The existing Meshcat display (using Set2dRenderMode) already fully covers this use case. There's no need to pop up extra windows.
Towards #14702. See #17438 for the big picture.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17436)
=> [manipulation_station] Remove planar_scenegraph_visualizer

geometry/benchmarking/mesh_intersection_benchmark.cc, geometry/proximity/BUILD.bazel, geometry/proximity/contact_surface_utility.h, geometry/proximity/deformable_mesh_intersection.cc, geometry/proximity/deformable_mesh_intersection.h, geometry/proximity/mesh_intersection.cc, geometry/proximity/mesh_intersection.h, geometry/proximity/test/deformable_mesh_intersection_test.cc, geometry/proximity/test/mesh_intersection_test.cc
Resolve #17318 
- Reuse hydroelastic SurfaceVolumeIntersector<> for deformables.
- Its template parameter MeshBuilder specifies output MeshType and FieldType.
- Add template parameter BvType to use Obb for compliant hydroelastic geometry
and Aabb for deformable geometry.
- Factor out the virtual CalcContactPolygon() for hydroelastics. It is overridden
for deformables to collect more deformable-specific data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17339)
=> [geometry] Compute contact surfaces for deformables

multibody/plant/multibody_plant.h
Per this [Slack discussion](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1654709745193879?thread_ts=1654649774.297249&cid=C2WBPQDB7) update docs for `num_positions()`. Other methods were identified to have the same problem, `num_velocities()` and `num_multibody_states()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17445)
=> Updates some docs on MultibodyPlant's finalize preconditions

lcm/BUILD.bazel, lcm/drake_lcm.cc, lcm/drake_lcm.h, tools/install/libdrake/header_lint.bzl, tools/install/libdrake/test/header_dependency_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17442)
=> [lcm] Remove build-time transitive dependency on LCM headers

lcm/drake_lcm_params.h, lcm/test/drake_lcm_test.cc
* The previous documentation said the channel name is "unchanged"
but this could mean either "unchanged by the suffix mechanism"
or "unchanged from its suffixed form".
* Clarify that the callback does receive the suffix.
* Nail this down with a test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17455)
=> Clarify `channel_suffix` semantics for `SubscribeAllChannels`

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/process_model_directives.cc, multibody/parsing/process_model_directives.h, multibody/parsing/test/process_model_directives_test.cc
There's no need to pass a MultibodyPlant when we already have a Parser.
There's no need to use an output argument instead of a return value.
For sample use cases, see Anzu PR 9070.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17450)
=> [parsing] Add ProcessModelDirectives overload for simplicity

tools/jupyter/jupyter_bazel.py
Something odd is happening with ipywidgets on Ubuntu 22.
I have no idea what's going on, but this gets us passing CI.
Closes #17433.
This curtails the widget message processing just prior to hitting this line in the #17433 backtrace.
```
File "/usr/lib/python3/dist-packages/nbclient/client.py", line 917, in process_message
self.handle_comm_msg(cell.outputs, msg, cell_index)
```
https://github.com/jupyter/nbclient/blob/12c7f0492beb9306192b609fbdab67bbac2e2b4b/nbclient/client.py#L459-L461
The commits here will be squashed, not merged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17451)
=> [jupyter] Customize ExecutePreprocessor to fix ipywidget tests

doc/_pages/from_binary.md
This matches what our pip instructions suggest, and seems like it's the preferred way for Python 3.
The original `-m virtualenv` documentation was per #10512 circa 2019 using Python 2.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17469)
=> [doc] Update from_binary to use venv not virtualenv

geometry/render/dev/render_gltf_client/internal_render_client.cc, geometry/render/dev/render_gltf_client/internal_render_client.h, geometry/render/dev/render_gltf_client/test/internal_render_client_test.cc, geometry/render/dev/render_gltf_client/test/internal_render_engine_gltf_client_test.cc, geometry/render_gltf_client/internal_http_service.cc, geometry/render_gltf_client/internal_http_service.h, geometry/render_gltf_client/internal_http_service_curl.cc, geometry/render_gltf_client/internal_http_service_curl.h, geometry/render_gltf_client/render_engine_gltf_client_params.h, geometry/render_gltf_client/test/README.md, geometry/render_gltf_client/test/internal_http_service_curl_test.cc, geometry/render_gltf_client/test/internal_http_service_test.cc
Another prerequisite for #17449, we decided to drop `port` data member and use `base_url` as the sole place to store that information. By that, it's less error-prone and more straightforward for users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17478)
=> [geometry/render_gltf_client] remove port struct data member

tools/workspace/ibex/include_limits.patch
Patch ibex to fix more places where it was using `std::numeric_limits` without including `<limits>`. The previous patch only covered spots hit in release builds; this also covers debug.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17493)
=> Fix more ibex on Jammy issues

geometry/proximity/distance_to_point_callback.h, geometry/proximity/distance_to_shape_callback.h, geometry/proximity/penetration_as_point_pair_callback.cc, geometry/utilities.h, multibody/benchmarks/acrobot/acrobot.cc, systems/analysis/test/explicit_euler_integrator_test.cc, systems/controllers/test/inverse_dynamics_test.cc, systems/primitives/test/demultiplexer_test.cc
This code only supports `AutoDiffXd` but spells it as `AutoDiffScalar`. The conventional `AutoDiffXd` is clearer for readers in any case, but also paves the way to moving away from `AutoDiffScalar` down the road.
Relatedly, also remove unused using directives and include statements for the odd spelling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17500)
=> [misc] Tidy up weird spellings of AutoDiffXd

common/BUILD.bazel, common/autodiffxd_make_coherent.h
This code has been unused for some time.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17499)
=> [common] Deprecate autodiffxd_make_coherent

systems/analysis/implicit_integrator.cc, systems/analysis/velocity_implicit_euler_integrator.cc
`InitializeAutoDiff` is our canonical function for this purpose, and is carefully documented and optimized for performance.
These were the only two places I could find via `grep` that were failing to use the sugar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17502)
=> [systems] Use InitializeAutoDiff instead of manual looping

tools/dynamic_analysis/bazel.rc, tools/workspace/picosat/repository.bzl
Closes: #17139
Also drop disablement of UBSan checks specific to picosat; that is no
longer needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17505)
=> [build system] Update picosat to latest commit

math/test/quaternion_test.cc
The test assumed that Drake uses `Eigen::AutoDiffScalar`, but that gets in the way as we work to replace it. The more familiar `AutoDiffXd` is clearer for readers in any case, and we don't care about runtime performance in a unit test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17501)
=> [math] Avoid fixed-sized derivatives in quaternion_test

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/inverse_kinematics/global_inverse_kinematics.cc, multibody/inverse_kinematics/global_inverse_kinematics.h, multibody/inverse_kinematics/test/global_inverse_kinematics_test.cc
- Change one remaining use of Isometry3 to RigidTransform (and
deprecate old version)
- Implements AddWorldRelativePositionConstraint
- Adds Python bindings
- Makes argument naming to consistent use body_index; before we had
some body_index and some body_idx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17504)
=> [inverse_kinematics] Update global IK

multibody/parsing/detail_sdf_geometry.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/unsupported_elements.sdf
Relevant to: #16785 (already closed)
This patch adds a missed call to CheckSupportedElements() for the
SDFormat parsing of drake:proximity_properties. It fixes some typos in
the (previously unused) supported element data. It also adds new test
clauses to ensure the checking is executed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17510)
=> [parsing] Add missed check in SDFormat drake:proximity_properties

geometry/BUILD.bazel, geometry/make_mesh_for_deformable.cc, geometry/make_mesh_for_deformable.h, geometry/test/geometry_state_test.cc, geometry/test/internal_geometry_test.cc, geometry/test/make_mesh_for_deformable_test.cc, geometry/test/scene_graph_test.cc
There was a great deal of code in place to handle geometries that aren't currently supported. This makes use of the `ShapeReifier` API to reduce the boilerplate. It eliminated a bunch of functions and reduced indirection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17484)
=> [geometry] Simplify deformable mesh generation code

common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_write_archive.h
The YAML syntax requires that they begin with a leading period, e.g., `.inf` instead of `inf`.
Closes #17503.
+@dmcconachie-tri would you like to feature-review?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17517)
=> [yaml] Output special floating point values correctly

systems/benchmarking/BUILD.bazel, systems/benchmarking/multilayer_perceptron_performance.cc
This can serve to justify the enabling of BLAS proposed in #17515.  Without blas, running
```
time bazel-bin/systems/primitives/multilayer_perceptron_performance \                             
--batch_size=1000 --iterations=100
```
averaged about 4.8 seconds on my mac laptop.  With BLAS it averaged 3.2 seconds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/16683)
=> [primitives] Add performance binary for MultilayerPerceptron

geometry/proximity_properties.cc, geometry/proximity_properties.h, multibody/parsing/detail_common.cc, multibody/parsing/detail_sdf_geometry.cc, multibody/parsing/detail_sdf_geometry.h, multibody/parsing/detail_urdf_geometry.h, multibody/parsing/parsing_doxygen.h, multibody/parsing/test/detail_common_test.cc, multibody/parsing/test/detail_sdf_geometry_test.cc, multibody/parsing/test/detail_urdf_geometry_test.cc, multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/multibody_plant.h, multibody/plant/test/compliant_contact_manager_test.cc
We need to update our documentation on the contact models. 
Places that need a pretty good revision because they are out of date are:
1. `multibody_plant.h`, at mbp_contact_modeling.
2. `contact_model_doxygen.h`, at drake_contacts.
Some of it is outdated and/or repeated.
This PR does not fix that documentation just yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17512)
=> Parse dissipation_time_scale for SAP.

examples/atlas/atlas_run_dynamics.cc, examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc, multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_config.h, multibody/plant/multibody_plant_config_functions.cc, multibody/plant/multibody_plant_config_functions.h, multibody/plant/test/multibody_plant_config_functions_test.cc
Draft PR to set SAP as the contact solver in MultibodyPlant.
The user would set the solver in the `MultibodyPlantConfig::discrete_contact_solver_type`.
Two examples here show how to use it: `examples/hydroelastic/spatula_slip_control` and `examples/atlas`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17400)
=> Option to choose the SAP solver

examples/allegro_hand/joint_control/BUILD.bazel
This test has a history of randomly failing in CI (at least 3 times in the past year)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17537)
=> Mark run_twisting_mug_test as flaky

systems/primitives/test/linear_transform_density_test.cc, systems/primitives/test/multilayer_perceptron_test.cc
The new AutoDiff will have a breaking change: its `derivatives()` mutable accessor will no longer guide the conditional ternary operator to construct a temporary `Eigen::VectorXd`. There is no longer a "common type" between a constant-expression eigen xpr vector and a mutable AutoDiff derivatives vector (both a will be eigen xprs, of different types).
We plan to add sugar to make this easier down the road (i.e., without a ternary operator), but in any case forcing the constant vector to materialize in test code is not any great loss, and it's easier for the commit train to land this now and get it out of the way.
(We can't merge the sugar until we merge the new `derivatives()` first, so it's a bit of a Catch-22.)
--- …
=> [primitives] Spell ternary operator compatibly with new AutoDiff

bindings/pydrake/BUILD.bazel, bindings/pydrake/stubgen.py, bindings/pydrake/test/stubgen_test.py, tools/workspace/default.bzl, tools/workspace/mypy_extensions_internal/BUILD.bazel, tools/workspace/mypy_extensions_internal/package.BUILD.bazel, tools/workspace/mypy_extensions_internal/repository.bzl, tools/workspace/mypy_internal/BUILD.bazel, tools/workspace/mypy_internal/package.BUILD.bazel, tools/workspace/mypy_internal/repository.bzl, tools/workspace/tomli_internal/BUILD.bazel, tools/workspace/tomli_internal/package.BUILD.bazel, tools/workspace/tomli_internal/repository.bzl, tools/workspace/typing_extensions_internal/BUILD.bazel, tools/workspace/typing_extensions_internal/package.BUILD.bazel, tools/workspace/typing_extensions_internal/repository.bzl
Add pybind11-stubgen as a new external. Add a rule to generate `.pyi`s for `pydrake` using the same and a small helper script.
For now, this must be manually invoked, and some functions are being skipped (see #17520). However, this will give us the ability to manually test the generated `.pyi` files. Adding logic to install them and/or otherwise bundle them can come later.
Towards #16987.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17521)
=> Generate .pyi's using pybind11-stubgen

bindings/pydrake/visualization/meldis.py
Broken by #16981.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17548)
=> [visualization] Repair meldis --host option

examples/atlas/atlas_run_dynamics.cc, examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_config.h, multibody/plant/multibody_plant_config_functions.cc, multibody/plant/multibody_plant_config_functions.h, multibody/plant/test/multibody_plant_config_functions_test.cc
Refactor to shorten from set/get_discrete_contact_solver_type() into set/get_discrete_contact_solver(). Similarly, the enum is refactored from `DiscreteContactSolverType` to `DiscreteContactSolver`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17545)
=> Refactor to shorten into set/get_discrete_contact_solver().

lcm/drake_lcm.cc, lcm/drake_lcm_params.h, lcm/test/drake_lcm_test.cc
This PR proposes to reverse the semantics of DrakeLcm::SubscribeAllChannels
with resepect to channel suffixes.  As documented and tested by my previous
PR, SubscribeAllChannels prior to this PR provides the full, suffix-included
name of the channel.
I assert the prior behaviour was wrong for two reasons:
* First, a caller likely suspects that the channel passed to Subscribe
and the channel received by SubscribeAllChannels are the same entity.
For one to be qualified and the other not is a surprise.
* Second, this is very troublesome for clients that receive a DrakeLcm as a
DrakeLcmInterface, as they cannot determine the suffix with which the
DrakeLcm was constructed (nor could they even if we added an accessor on
the subclass).  Thus they cannot know the publisher's intended channel
name. …
=> Reverse the suffix semantics of DrakeLcm::SubscribeAllChannels

tools/workspace/drake_visualizer/BUILD.bazel
Currently the wrapper script is installed and will fail when run since ${prefix}/bin/.drake-visualizer-real is not available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17553)
=> [workspace] Skip drake-visualizer wrapper install on unsupported platforms

tools/wheel/image/setup.py
Hotfix for #17453 and #17454.
According to the internet, `setuptools.find_packages()` is like juggling knives, and we should stop using it.  (See, for example https://github.com/pypa/setuptools/issues/1509.)  In the meantime, we can add back what it's missed, to stop the bleeding.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17556)
=> [wheel] Teach setuptools about __init__.so files

doc/_pages/model_version_control.md, manipulation/models/BUILD.bazel, manipulation/models/tri_homecart/BUILD.bazel, manipulation/models/tri_homecart/README.md, manipulation/models/tri_homecart/homecart.yaml, manipulation/models/tri_homecart/homecart_bimanual.urdf.xacro, manipulation/models/tri_homecart/homecart_collision_walls.sdf, manipulation/models/tri_homecart/homecart_cutting_board.sdf.xacro, manipulation/models/tri_homecart/homecart_grippers.yaml, manipulation/models/tri_homecart/homecart_no_grippers.yaml, manipulation/models/tri_homecart/test/parse_homecart_test.cc, manipulation/models/ur3e/BUILD.bazel, manipulation/models/ur3e/README.md, manipulation/models/ur3e/test/parse_test.cc, manipulation/models/ur3e/ur.transmission.xacro, manipulation/models/ur3e/ur3e.urdf.xacro, manipulation/models/ur3e/ur3e_cylinders_collision.urdf.xacro, manipulation/models/ur3e/ur3e_spheres_collision.urdf.xacro, tools/wheel/image/build-wheel.sh, tools/workspace/models_internal/files.bzl, tools/workspace/models_internal/package.BUILD.bazel, tools/workspace/models_internal/repository.bzl
This PR only contains a test that verifies that the model can be
parsed correctly (through model directives, etc). But in a follow-up
PR I will use this as a Drake example of bimanual motion planning with
Graph of Convex Sets.
These models were derived from the Anzu versions; with a few changes:
- Anzu has "left/right" variants of the ur3e models, which set tighter
joint limits for the homecart configuration.  I felt that it was a
little inelegant to put those in the ur3e directory (they should be
homecart specific).  We can add them later if need be.
- I've used the simple wsg gripper models that were already in Drake
instead of the fancier models in anzu.
- I've named the directory `tri_homecart` instead of `homecart`.  
+@rcory for feature review, please.
fyi @ToffeeAlbina-TRI , …
=> [manipulation] Add UR3e model and TRI Homecart

examples/manipulation_station/end_effector_teleop_dualshock4.py
- Use C++ bound `pydrake.geometry.Meshcat` over the deprecated pure python Meshcat interface.
- Meshcat argument `--open_browser` is now `-w` or `--open-window` for consistency with the other examples.
- Meshcat argument `--meshcat` requests the meshcat interface, previous options related to ZMQ url etc are no longer available.
Note: I do not have a joystick to be able to test this with.  Changes here should mirror whatever decisions are made
This could alternatively be folded into the same PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17300)
=> [examples] Update manipulation station end_effector joystick Meshcat

geometry/meshcat.cc, geometry/render/test/meshes/box.obj.mtl
In https://github.com/RobotLocomotion/models/pull/18
(homecart_basecart.mtl) I ran into a texture map specification that
specified a scale option in the map_Kd line. This defeated the simple
regex expression that I had implemented in meschat.cc.
meshcat.cc doesn't need to parse these options properly; it only needs
to successfully extract the filename so that the file can be shipped
over the websocket.  I've updated the parsing line according to the
mtl specification to ignore options.
To reproduce the problem, run meshcat_manual_test with the change to
box.obj.mtl but without the fix to meshcat.cc.  You will see that the
box appears in meshcat without a texture and a warning from meshcat.cc
is printed to the console.  The change to meshcat.cc resolves the
problem.
---
This change …
=> [meshcat] More robust parsing of .mtl texture map filenames

lcm/test/drake_lcm_test.cc
Hotfix for #17470.
Locally, this gets me from a 20% flake rate down to 0% over 1000 retries.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17558)
=> [lcm] De-flake a unit test

bindings/pydrake/multibody/inverse_kinematics_py.cc, multibody/inverse_kinematics/angle_between_vectors_constraint.h, multibody/inverse_kinematics/com_in_polyhedron_constraint.h, multibody/inverse_kinematics/com_position_constraint.h, multibody/inverse_kinematics/distance_constraint.h, multibody/inverse_kinematics/gaze_target_constraint.h, multibody/inverse_kinematics/minimum_distance_constraint.h, multibody/inverse_kinematics/orientation_constraint.h, multibody/inverse_kinematics/point_to_point_distance_constraint.h, multibody/inverse_kinematics/position_constraint.h
The python bindings for many of the kinematic constraints used hard-coded doc strings in the bindings file due to a limitation in mkdoc.  That is no longer a limitation.  This updates the doc strings to use the standard workflow.
+@EricCousineau-TRI for both reviews, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17574)
=> [inverse_kinematics] Use pydrake_mkdoc_identifier

multibody/benchmarking/BUILD.bazel, multibody/benchmarking/cassie.cc
Rewrite the fixture to be templated on scalar type, remove redundant member fields, and pre-allocate all function inputs and outputs.
Avoid using zeros for any state or input; math on a zero might have a different performance profile than non-zero. This is already the case for Expression, and might be the case for AutoDiff down the road.
---
The LimitMalloc heap ceilings are no longer part of the benchmark; see #17538 for the new home.
The LimitMalloc heap telemetry is dropped from the benchmark; it will be re-added in a much better form in #17518 (to all benchmarks, not just cassie).
---
Sample output:
```
------------------------------------------------------------------------------
Benchmark                                    Time             CPU   Iterations …
```
=> [multibody] Reformulate cassie benchmark case permutations

multibody/inverse_kinematics/angle_between_vectors_constraint.cc, multibody/inverse_kinematics/gaze_target_constraint.cc, multibody/inverse_kinematics/orientation_constraint.cc, multibody/inverse_kinematics/point_to_point_distance_constraint.cc, multibody/inverse_kinematics/position_constraint.cc, solvers/minimum_value_constraint.cc, systems/trajectory_optimization/direct_collocation.cc, systems/trajectory_optimization/direct_transcription.cc
Resolves #17576.
(I tried to read all instances of InitializeAutoDiff in non-test files; but a second set of eyes on this would be highly appreciated).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17577)
=> fix #17576 -- incorrect use of InitializeAutoDiff when gradients are not needed

bindings/pydrake/BUILD.bazel, tools/workspace/mypy_internal/repository.bzl
Patch ModuleImport in mypy to increase the timeout before aborting an attempt to import a module. The default timeout of 5s is not long enough to import `pydrake` in some configurations.
Also increase the timeout on our `stubgen_test`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17552)
=> Increase timeout in mypy ModuleImport

bindings/pydrake/stubgen.py, bindings/pydrake/test/stubgen_test.py
Mypy has a timeout in its `ModuleInspect` that will trip if importing a module takes an inordinate (>30s) amount of time. This is usually not an issue, but it seems (possibly due to AWS storage quirks) that we're hitting this sometimes, more or less at random.
In order to hopefully mitigate this issue, import ourselves (i.e. `pydrake.all`) up front, so that everything is hopefully "hot" when mypy goes to do its importing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17584)
=> Try to avoid mypy timing out

doc/_pages/troubleshooting.md, multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_hydroelastic_test.cc, multibody/plant/test/multibody_plant_query_object_connect_test.cc, multibody/plant/test/multibody_plant_test.cc
relates #11448
In response to the problem where `MultibodyPlant` mysteriously, suddenly complains about an unconnected `QueryObject` port, this PR provides two tactics to lessen the pain.
1. The error message now provides a URL that can contain arbitrary guidance and checklists for understanding and addressing the error message.
2. Do our best to understand what computation is being evaluated that led to caring about the state of the input port.
- Add a test that confirms a number of public APIs that can trigger the exception and confirm the conditions under which they are sent.
- For those same APIs, fail fast on the unconnected port error condition, providing more message as to which API triggered it (e.g., evaluating an output port, asking for derivatives, etc.) Note: this effort is …
=> [multibody] Provide more feedback when MbP query object port is unconnected

geometry/benchmarking/BUILD.bazel, geometry/benchmarking/mesh_intersection_benchmark.cc, geometry/benchmarking/render_benchmark.cc, multibody/benchmarking/BUILD.bazel, multibody/benchmarking/cassie.cc, multibody/benchmarking/iiwa_relaxed_pos_ik.cc, solvers/benchmarking/BUILD.bazel, solvers/benchmarking/benchmark_mathematical_program.cc, systems/benchmarking/BUILD.bazel, systems/benchmarking/framework_benchmarks.cc, systems/benchmarking/multilayer_perceptron_performance.cc, tools/performance/BUILD.bazel, tools/performance/README.md, tools/performance/defs.bzl, tools/performance/gflags_main.cc
Drop the feature of render_benchmark where it prints filenames to the console (via a mutable global variable). Instead, users should begin from an empty output directory, so that whatever ends up there was what was written.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17581)
=> [performance] Add gflags support to benchmarks

common/autodiffxd.h
This was an internal type_trait from Eigen, to support compilations
below C++11. Eigen is dropping support for old C++ version, and
removed this type_trait:
https://gitlab.com/libeigen/eigen/-/merge_requests/732
Per https://drake.mit.edu/from_source.html
Drake requires C++17/20 and already uses std::enable_if(_t)
in other places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17590)
=> Fix missing internal::enable_if. Replace with std::enable_if

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/global_inverse_kinematics.h, multibody/inverse_kinematics/inverse_kinematics.cc, multibody/inverse_kinematics/inverse_kinematics.h, multibody/inverse_kinematics/position_cost.cc, multibody/inverse_kinematics/position_cost.h, multibody/inverse_kinematics/test/inverse_kinematics_test.cc, multibody/inverse_kinematics/test/position_cost_test.cc
Towards #17507.  This is the first half of supporting GlobalIK's
AddPostureCost in the nonlinear IK toolchain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17587)
=> [inverse_kinematics] Add PositionCost

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/inverse_kinematics.cc, multibody/inverse_kinematics/inverse_kinematics.h, multibody/inverse_kinematics/orientation_cost.cc, multibody/inverse_kinematics/orientation_cost.h, multibody/inverse_kinematics/test/inverse_kinematics_test.cc, multibody/inverse_kinematics/test/orientation_cost_test.cc
Towards #17507.  This is the second half of supporting GlobalIK's
AddPostureCost in the nonlinear IK toolchain.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17592)
=> [inverse_kinematics] Add OrientationCost

multibody/inverse_kinematics/kinematic_evaluator_utilities.h, multibody/inverse_kinematics/orientation_cost.cc, multibody/inverse_kinematics/position_cost.cc, multibody/inverse_kinematics/position_cost.h
During review of #17592, we decided that it was cleaner to have the
cost call the existing constraint implementation and only do the
incremental work.  This cleans up the PositionCost implementation to
use the same idea.
+@jwnimmer-tri for feature review (or both if you feel comfortable).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17601)
=> [inverse_kinematics] Cleanup PositionCost implementation.

multibody/parsing/BUILD.bazel, multibody/parsing/process_model_directives.cc, multibody/parsing/test/process_model_directives_test.cc, multibody/parsing/test/process_model_directives_test/bad_package_uri.yaml
The old behavior would attempt to resolve directive URIs by hand. This defers to the the utility function. Now, processing the directives no longer aborts, but throws an intelligible message.
closes #17386
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17604)
=> [parsing] Handle unknown packages gracefully while processing model directives

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/benchmarking/BUILD.bazel, multibody/benchmarking/homecart_global_ik.cc, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/global_inverse_kinematics.cc, multibody/inverse_kinematics/global_inverse_kinematics.h, multibody/inverse_kinematics/test/global_inverse_kinematics_test.cc
Towards #17507.
Adds a benchmark for GlobalInverseKinematics using the TRI Homecart
dual-arm manipulator.  The use of SetInitialGuess on the HomeCart
benchmark improves solve times on the benchmark from ~47s to ~7s.
Also fixes GlobalIK's use of WeldJoint::X_PC() as reported in #17600.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17608)
=> [inverse_kinematics] Add GlobalIK::SetInitialGuess and benchmark

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/inverse_kinematics.cc, multibody/inverse_kinematics/inverse_kinematics.h, multibody/inverse_kinematics/polyhedron_constraint.cc, multibody/inverse_kinematics/polyhedron_constraint.h, multibody/inverse_kinematics/test/inverse_kinematics_test.cc, multibody/inverse_kinematics/test/polyhedron_constraint_test.cc
This is motivated by the stackoverflow question https://stackoverflow.com/questions/72999101/slightly-different-angle-between-vectors-constraint and https://stackoverflow.com/questions/72984441/general-cone-gaze-constraint, both can be modelled with this PolyhedronConstraint.
cc @RussTedrake since you answered the stack overflow question.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17596)
=> add PolyhedronConstraint as a kinematic constraint.

geometry/proximity/BUILD.bazel, geometry/proximity/deformable_contact_internal.cc, geometry/proximity/deformable_contact_internal.h, geometry/proximity/hydroelastic_internal.h, geometry/proximity/test/deformable_contact_internal_test.cc
This PR does half of the job: currently deformable::Geometries
only supports adding, updating, and removing rigid (non-deformable)
geometries. The ability to add, update, and remove deformable geometries
and calculating the contact data will come in a separate PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17605)
=> [geometry] Data structure for geometries in deformable contact

tools/wheel/image/build-wheel.sh
5969b87e1df98c6895adf32d69565cd93ec02859 added a duplicate entry to the set of data files that are excluded from the wheel. Since this has no effect other than to potentially confuse the reader, remove it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17613)
=> Remove duplicate command in build-wheel.sh

common/symbolic/expression/expression.cc, common/symbolic/expression/expression.h, common/symbolic/expression/expression_cell.cc, common/symbolic/expression/expression_cell.h, common/symbolic/expression/test/expression_cell_test.cc, common/symbolic/expression/test/expression_test.cc
Finally resurrected from the initial attempt in #15369 last year.
This substantially speeds up symbolic evaluation by storing both the ExpressionKind and the constant literal value (if present) directly inline within the Expression object.
Piotr Duperas has a [nice overview on nanboxing](https://piotrduperas.com/posts/nan-boxing) for those who haven't seen it before.
---
Performance report (using the updated benchmark from #17539):
Benchmark name | Change in throughput | New throughput relative to T=double
--|--|--
CassieExpression/MassMatrix/0 | 7.0x | 1/20
CassieExpression/MassMatrix/3 | 1.5x
CassieExpression/InverseDynamics/0 | 8.7x | 1/16
CassieExpression/InverseDynamics/7 | 1.3x
CassieExpression/ForwardDynamics/0 | 6.8x | 1/15
CassieExpression/ForwardDynamics/10 | 1.5x …
=> [symbolic] Speed up Expression via nanboxing

bindings/pydrake/autodiffutils_py.cc, common/yaml/test/yaml_performance_test.cc, examples/bead_on_a_wire/bead_on_a_wire.h, math/autodiff.h, math/jacobian.h, math/test/autodiff_test.cc, math/test/differentiable_norm_test.cc, math/test/expmap_test.cc, math/test/jacobian_test.cc, math/test/linear_solve_test.cc, multibody/tree/rotational_inertia.h, multibody/tree/test/spatial_inertia_test.cc, multibody/tree/test/unit_inertia_test.cc, solvers/constraint.cc, solvers/constraint.h, solvers/moby_lcp_solver.cc, solvers/test/moby_lcp_solver_test.cc, systems/analysis/test/simulator_test.cc, tools/vector_gen/test/sample_test.cc
When using `AutoDiffScalar` directly (not via the `drake::AutoDiffXd` alias), include the `unsupported/Eigen` header directly. This will enable `drake::AutoDiffXd` to alias to a different type in the future.
Tidy up some comments that refer to `AutoDiffScalar` where they really meant `AutoDiffXd`.
Fix a mistake including `eigen_autodiff_types` directly.
Remove some unused code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17620)
=> [misc] Clean up unsupported/Eigen/AutoDiff include and using

doc/_pages/apt.md, doc/_pages/from_binary.md, doc/_pages/installation.md, doc/_pages/pip.md, doc/_release-notes/2016.md, doc/_release-notes/v1.1.0.md, tools/workspace/vtk/README.md
Fixes: #14938.
Possibly relates: #15958.
- Advertise nightly `.tar.gz`, `.deb`, and python wheel urls.
- Download links with YYYYMMDD in their url are available for ~56 days after their upload.  Previously these were available
for 2 years.
- Build artifacts for drake hosted in the drake-packages s3 bucket are available for 5 years from upload (e.g., ubuntu VTK tarballs).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17413)
=> [doc] Document all nightly uploads and expiration policies

doc/_pages/installation.md, doc/_pages/pip.md, doc/_pages/release_playbook.md
I've uploaded a v1.5.0 wheel using this process.
Closes #15958.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17619)
=> [doc] Add macOS stable releases for pip wheels

common/symbolic/rational_function.cc
As #17611 is merged, we can properly check whether the polynomial is structurally zero, discussed in https://github.com/RobotLocomotion/drake/pull/17522#pullrequestreview-1042025951
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17624)
=> Check if denominator is zero in RationalFunction.

multibody/parsing/BUILD.bazel, multibody/parsing/model_instance_info.h, multibody/parsing/process_model_directives.h
Relevant to: #17390, #17112
This patch opens up the physical design of model directives, clearing
the way for integration of model directives as a language for Parser
(#17390), and porting of various modules from Anzu to Drake (#17112).
There should be no changes to either functionality or existing API
surface; only the arrangement of files and dependencies is changed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17631)
=> [parsing] Extract ModelInstanceInfo to its own header file

geometry/proximity/BUILD.bazel, geometry/proximity/deformable_contact_geometries.cc, geometry/proximity/deformable_contact_geometries.h, geometry/proximity/deformable_mesh_intersection.cc, geometry/proximity/test/deformable_contact_geometries_test.cc, geometry/proximity/test/deformable_mesh_intersection_test.cc
Remove the ReferenceDeformableGeometry class and instead stores the approximate signed distance field directly in deformable geometry. With this, we unlock arbitrary volume mesh (with potentially non-convex surface mesh) as deformable geomtries. 
While doing that, we ensure that the mesh inside the SDF points to the deformable mesh held by DeformableGeometry so that we don't have to create local copies in deformable_mesh_intersection.cc. 
Towards #16875.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17603)
=> [geometry] Build deformable sdf from distance to surface mesh

bindings/pydrake/common/serialize_pybind.h
Hotfix for #17618.  This showed up in Anzu testing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17633)
=> [pydrake] Add missing include

common/ad/BUILD.bazel, common/ad/README.md, common/ad/auto_diff.h, common/ad/internal/partials.cc, common/ad/internal/partials.h, common/ad/internal/standard_operations.cc, common/ad/internal/standard_operations.h, common/ad/test/auto_diff_basic_test.cc, common/ad/test/partials_test.cc, common/ad/test/standard_operations_stream_test.cc
Towards https://github.com/RobotLocomotion/drake/pull/17492.
This is private for now; it is not used outside of its unit tests.
See #17622 for how we'll start to add actual operations (and their unit tests).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17621)
=> [ad] Add AutoDiff replacement class for AutoDiffXd

bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/meldis.py, bindings/pydrake/visualization/test/meldis_test.py
Meldis does not yet support hydroelastic meshes that are transmitted inline:
https://github.com/RobotLocomotion/drake/blob/dc6db5cd74163e67bb009aac0f79b0c69375e80d/geometry/drake_visualizer.cc#L96-L106
As #17641 is currently written (with `show_hydroelastic = true`), it crashes meldis.  With this change, it warns instead (but doesn't actually show the hydroelastic geometry).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17642)
=> [visualization] Improve meldis error message

bindings/pydrake/common/test_utilities/BUILD.bazel, bindings/pydrake/common/test_utilities/scipy_none/scipy/__init__.py, bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/test/noscipy_test.py, tools/workspace/pybind11/repository.bzl
See the tutorials test failure in #17559.
The scenario we have here is that there is an overloaded function, accepting either a sparse or dense matrix .
The [overload resolution order](https://pybind11.readthedocs.io/en/stable/advanced/functions.html#overload-resolution-order) of pybind11 means that unless the user passes _exactly_ the correct kind of ndarray (for the dense case), pybind11 will try to convert the argument into _all_ of the possible overloads, triggering the import of scipy, triggering a ModuleNotFound error.
Since our goal with Drake is to only use sparse matrices sparingly, we should skip overloads that need scipy, rather than hard-fail.
--- …
=> [pydrake] Ignore Eigen::Sparse overloads when scipy is missing

bindings/pydrake/geometry_py_hydro.cc, bindings/pydrake/geometry_py_scene_graph.cc, bindings/pydrake/test/geometry_scene_graph_test.py
This accounts for a *portion* of the missing hydroelastic bindings. It is the minimum binding required to evaluate the pressure fields associated with `ContactSurface`. This doesn't bind the full public API for the various mesh field types. The determination of whether they should be bound can happen in the future.
1. Binding the underlying mesh field types:
- `PolygonSurfaceMeshField`
- `TriangleSurfaceMeshField`
2. Bind the missing methods on `ContactSurface`.
3. Unit tests on newly bound code.
- Generally, unit tests on `ContactSurface` bindings were missing, and this adds them.
relates #17625
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17637)
=> [pydrake] Binding ContactSurface mesh fields

tools/wheel/image/dependencies/patches/mumps/patch.diff, tools/wheel/image/dependencies/projects.cmake
MUMPS has recently become unreliable as far as providing tarballs. In order to be less dependent on upstream, switch to using Ubuntu's source mirror as the preferred source for the tarball.
Note that, because Ubuntu only ships a limited set of versions, this requires downgrading to 5.4.1, which as far as I can tell has never been shipped by Homebrew. Thus, in this respect, the macOS wheels will be more similar to the Ubuntu wheels than the macOS non-wheels.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17646)
=> Use Ubuntu mirror for MUMPS (wheel builds)

geometry/proximity/deformable_contact_internal.cc, geometry/proximity/deformable_contact_internal.h, geometry/proximity/test/deformable_contact_internal_test.cc
Add the capability of adding, updating, and removing deformable geometries. 
Also add the function to compute all deformable vs. rigid geometry contact data.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17606)
=> [geometry] Complete the deformable::Geometries data structure

common/ad/test/standard_operations_sub_test.cc
Amends #17622. Towards #17492.
It would be easy to make a mistake in the implementation that lost the sign of zero; this test guards against that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17658)
=> [ad] Add unit test for -0.0 unary negation signbit

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/analysis_test.py, examples/hardware_sim/hardware_sim.cc, examples/hydroelastic/python_ball_paddle/contact_sim_demo.py, examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc, systems/analysis/simulator_config_functions.cc, systems/analysis/simulator_config_functions.h, systems/analysis/simulator_gflags.cc, systems/analysis/test/simulator_config_functions_test.cc
As more and more `Apply***Config()` functions come into play, they all have a signature that takes the config struct as the first parameter. This brings the simulator configuration in line with the other components.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17654)
=> Reverse ApplySimulatorConfig parameter order

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_solver.cc, multibody/contact_solvers/sap/sap_solver.h, multibody/contact_solvers/sap/test/sap_solver_autodiff_test.cc, multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/multibody_plant.h, multibody/plant/test/compliant_contact_manager_scalar_conversion_test.cc
- Allow CompliantContactManager to scalar convert to double and AutoDiffXd.
- SapSolver supports AutoDiffXd for solving trivial contact problems (zero constraints).
With these two items, we enable kinematic simulation with SAP + AutoDiffXd.
Closes #17647
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17651)
=> [sap] Enable kinematic AutoDiffXd simulation with SAP

bindings/pydrake/systems/lcm_py.cc, bindings/pydrake/systems/test/lcm_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17668)
=> [pydrake/lcm] Overload constructors for LcmPublisherSystem/LcmSubscriberSystem to take an LcmInterfaceSystem

common/proto/call_python_client.py, common/proto/test/call_python_server_test.cc
Ran into this when using `CallPython` in Anzu (for debugging robot stuff)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17672)
=> call_python: Allow defining functions with closures

examples/cubic_polynomial/BUILD.bazel, examples/cubic_polynomial/region_of_attraction.cc
Add gflags support (to help see which solver is being used).
Amends #6715.
```
$ bazel-bin/examples/cubic_polynomial/region_of_attraction --spdlog_level=debug
[2022-08-01 14:04:22.325] [console] [debug] solvers::Solve will use CSDP
[2022-08-01 14:04:22.325] [console] [warning] The problem has free variables, and CSDP removes the free variables by computing the null space of linear constraint in the dual space. This step can be time consuming. Consider providing a lower and/or upper bound for each decision variable.
Verified that pow(x(0), 2) < 1 is in the region of attraction.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17666)
=> [examples] Remove MOSEK requirement for region_of_attraction demo

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, examples/simple_gripper/simple_gripper.cc, examples/simple_gripper/simple_gripper.sdf, multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/constraint_specs.cc, multibody/plant/constraint_specs.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/test/compliant_contact_manager_test.cc, multibody/tree/multibody_tree_indexes.h
In addition to the corresponding unit tests, this PR updates the simple gripper demo to use coupler constraints.
cc'ing @dmcconachie-tri 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17639)
=> Implement capability to define coupler constraints

geometry/proximity/mesh_field_linear.h, geometry/proximity/test/field_intersection_test.cc, geometry/proximity/test/mesh_field_linear_test.cc
Make copy constructors of MeshFieldLinear private.
Use CloneAndSetMesh() instead of the copy constructors.
Fixes #17638
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17670)
=>  [geometry] Fix copy semantics of MeshFieldLinear

multibody/plant/BUILD.bazel, multibody/plant/make_discrete_update_manager.cc, multibody/plant/make_discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/test/make_discrete_update_manager_test.cc
As a result changes in CompliantContactManager and SAP related changes won't trigger recompiling MultibodyPlant all together.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17677)
=> [plant] Factor MakeDiscreteUpdateManager out into a separate header

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/test/hpolyhedron_test.cc, geometry/test/meshcat_manual_test.cc
Adds a method to perform hit-and-run MCMC to draw (approximately)
uniform samples from the interior of an HPolyhedron.
+@sadraddini for feature review, please.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17629)
=> [geometry/optimization] Add HPolyhedron::UniformSample

geometry/proximity/deformable_contact_internal.cc, geometry/proximity/deformable_contact_internal.h, geometry/proximity/test/deformable_contact_internal_test.cc, geometry/proximity_engine.cc, geometry/test/proximity_engine_test.cc
This also fixes a previously undetected issue that the pose of the deformable contact representation of a non-deformable geometry is quietly changed when the proximity property is replaced.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17691)
=> [geometry] Set pose of rigid geometry at registration

bindings/pydrake/multibody/meshcat_py.cc, bindings/pydrake/visualization/meldis.py, bindings/pydrake/visualization/test/meldis_test.py, examples/hydroelastic/spatula_slip_control/spatula_slip_control.cc, geometry/BUILD.bazel, geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_manual_test.cc, multibody/meshcat/BUILD.bazel, multibody/meshcat/contact_visualizer.cc, multibody/meshcat/hydroelastic_contact_visualizer.cc, multibody/meshcat/hydroelastic_contact_visualizer.h, multibody/meshcat/test/contact_visualizer_test.cc, multibody/meshcat/test/hydroelastic.sdf
This PR updates the `HydroelasticContactVisualizer` to send contact surface geometry to meshcat with each hydroelastic contact message. It also updates meldis and the in-process `ContactVisualizer` accordingly.
Related to #15738.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17599)
=> [meshcat]: Adds hydroelastic contact surface to meshcat visualization

geometry/render_gltf_client/BUILD.bazel, tools/install/libdrake/build_components.bzl
Hotfix for #17678 to unbreak the wheel builds.
\CC @zachfang @mwoehlke-kitware FYI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17697)
=> [libdrake] Demote render_gltf_client to private

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, bindings/pydrake/systems/test/meshcat_visualizer_test.py, examples/hydroelastic/python_ball_paddle/contact_sim_demo.py, multibody/inverse_kinematics/global_inverse_kinematics.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/tree/test/weld_joint_test.cc, multibody/tree/weld_joint.cc, multibody/tree/weld_joint.h, tutorials/rendering_multibody_plant.ipynb
Closes #17600
Updates `WeldJoint` to use the notation `F` for the frame on parent and `M` for the frame on child to match the notation in `Joint`.
Updates the arguments of `MultibodyPlant::WeldFrames()` to match.
Update argument names in python call sites.
Turn `WeldJoint::X_PC()` into a convenience function that returns `X_PF * X_FM * X_MC`
cc: @RussTedrake
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17696)
=> [multibody] Correct WeldJoint frame notation

examples/hardware_sim/BUILD.bazel, examples/hardware_sim/README.md, examples/hardware_sim/example_iiwa_wsg.yaml, examples/hardware_sim/example_scenarios.yaml, examples/hardware_sim/hardware_sim.cc, examples/hardware_sim/test/hardware_sim_test.py
We don't have any ID control / communication code for UR3e's in Drake.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17693)
=> [hardware_sim] Switch demo to use IIWA instead of UR3e

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/iris.cc, geometry/optimization/iris.h, geometry/optimization/test/iris_in_configuration_space_test.cc
Many users want to have additional constraints, like position and/or
orientation constraints on the end effector, as constraints on the
IRIS regions.  This PR makes that possible, and gives tests
demonstrating InverseKinematics constraints being certified via IRIS.
fyi @sadraddini, @hongkai-dai , @AlexandreAmice
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17703)
=> [geometry/optimization] Support generic constraints in IrisInConfigurationSpace

geometry/geometry_state.cc, geometry/geometry_state.h, geometry/proximity_engine.cc, geometry/query_object.cc, geometry/query_object.h, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/geometry_state_test.cc, geometry/test/query_object_test.cc
Towards #16875.
- Add ComputeDeformableRigidContact() function to QueryObject.
- Add GeometryState::FinalizeConfigurationUpdate() that propagates any configuration changes to ProximityEngine.
- Inform collision filters of deformable geometries even though no deformable contact is ever filtered.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17705)
=> [geometry] QueryObject returns deformable contact results

common/test_utilities/drake_cc_googletest_main.cc
CLion was passing a "bad" flag into gtest executions for debugging. This code provided a shim to allow that flag to be processed for drake's unit tests.
Clion has updated their code such that this shim should not be necessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17718)
=> Removes anachronistic gflag declaration

multibody/plant/test/multibody_plant_reaction_forces_test.cc
Relates to #17720.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17721)
=> [hotfix] Circumvent a race condition when baking query objects

multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc
Add a dummy namespace to perturb the elf header.
Try same trick as #17071.
Fixes CI job: https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-focal-clang-bazel-nightly-coverage/801/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17724)
=> Work around test error in coverage builds (kcov 339)

geometry/meshcat.cc, geometry/meshcat.html, geometry/test/meshcat_test.cc
The client will automatically attempt to reconnect to the meshcat url at a default 1-second cadence. The reconnect period can be tweaked by changing the url.
http://localhost:7000/?reconnect_ms=10000
sets the reconnect period to 10,000 ms.
The C++ `MeshCat` server adds the following to facilitate reconnection:
- When connecting to a client, it deletes everything in the `prefix_` path.
- While the server broadcasts the current state to a new connection, any value not *explicitly* stored in the current state doesn't get broadcast. Properties related to changing render mode have been explicitly added to the state. Previously, the initial values were implicit.
What this does *not* do: overwrite the lighting.
Closes #17085
- - - …
=> [visualization] Auto reconnect to meshcat server

tools/install/libdrake/header_lint.bzl, tools/workspace/fmt/repository.bzl
Fixes #17732.
See also `FMT_DEPRECATED_OSTREAM` in the release notes: https://github.com/fmtlib/fmt/releases/tag/9.0.0
Homebrew has updated to fmt 9, but drake's use of `fmt` relies on the deprecated ostream behavior.  Eventually drake will need to stop relying on fmt automatically discovering `std::ostream operator<<` and either specialize `fmt::formatter` to inherit from `ostream_formatter` or for simple things like `GeometryId id` we can use `id.get_value()`.
This should work with current provisioned AND unprovisioned macOS CI, currently provisioned macOS is using fmt 8.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17739)
=> [workspace] Support fmt v9 on macOS

tools/skylark/pybind.bzl
Closes #17739.
Re: [#buildcop discussion](https://drakedevelopers.slack.com/archives/C270MN28G/p1660826162888139), wheel does its own thing for dependencies via CMake, this should fix the macOS wheel build failure.
TODO:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17743)
=> [workspace] Support fmt v9 on macOS wheel

systems/controllers/linear_quadratic_regulator.h
Doc typo of a parameter name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17751)
=> [planning and control] Fix typo in documentation of LinearQuadraticRegulator

doc/_pages/troubleshooting.md, systems/framework/BUILD.bazel, systems/framework/system_base.cc, systems/framework/test/diagram_test.cc, systems/framework/test/system_base_test.cc, systems/framework/test/system_test.cc, systems/primitives/test/vector_log_sink_test.cc
When validating contexts against systems, we've added a bit more analysis for recognizing whether the system or the context are the root and provide custom messages reflecting that.
Furthermore, all error messages for `Context` validation include a URL in the troubleshooting webpage to provide elaboration.
To that end:
- Change logic in `ValidateContext()` for special cases.
- Change `ValidateCreatedForThisSystem()` to redirect to `ValidateContext()` for contexts.
- Write the troubleshooting entry.
- Tests
- For dependency reasons, the testing is distributed over two test files. `system_base_test.cc` avoids dependencies on diagram-level constructs. So, `diagram_test.cc` gets those tests.
closes #17265
- - - …
=> [framework] Updating context-system mismatch error messages

math/BUILD.bazel, math/fast_pose_composition_functions.cc, math/fast_pose_composition_functions_avx2_fma.cc, math/fast_pose_composition_functions_avx2_fma.h
Preparatory step for #17530, factors out AVX2/FMA compositions functions to a separate target.
+@ggould-tri for review, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17752)
=> Factor out AVX2/FMA composition functions

math/BUILD.bazel, math/fast_pose_composition_functions.cc, math/fast_pose_composition_functions_avx2_fma.cc, math/fast_pose_composition_functions_avx2_fma.h, math/test/fast_pose_composition_functions_test.cc
Replaces #17530 
Adds runtime detection of AVX2/FMA instruction support so that functions from `fast_pose_composition_functions_avx2_fma` are used when supported by the CPU, and falls back to portable functions when these instructions are not supported.
+@ggould-tri for feature review, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17760)
=> Add runtime detection of AVX2/FMA to support amd64 processors without those instructions

.bazeliskrc, setup/mac/source_distribution/Brewfile, setup/ubuntu/source_distribution/install_prereqs.sh
We need to maintain acute control over Bazel upgrades.
Mitigates #17763 for the moment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17764)
=> [setup] Use bazelisk on macOS

bindings/pydrake/geometry_py_common.cc, bindings/pydrake/test/geometry_common_test.py, bindings/pydrake/visualization/test/config_test.py, examples/hardware_sim/test/test_scenarios.yaml, geometry/BUILD.bazel, geometry/rgba.h, geometry/test/rgba_test.cc, visualization/BUILD.bazel, visualization/test/visualization_config_functions_test.cc, visualization/visualization_config.h, visualization/visualization_config_functions.cc
`Rgba` serializes as an array-like value. The contents must have either three or four values and must all lie in the range [0, 1].
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17762)
=> [geometry] Add Rgba::Serialize support

tools/install/bazel/test/drake_bazel_installed_test.py
When invoking bazel (i.e., bazelisk) within the unit test environment, it needs to know a tempdir where it can stash the downloaded bazel.
Hotfix for #17764.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17772)
=> [setup] Use bazelisk on macOS (part deux)

common/symbolic/expression/expression.cc, common/symbolic/expression/expression_cell.cc, common/symbolic/expression/expression_cell.h, common/symbolic/expression/test/substitution_test.cc
Towards #17701.
Running the `BenchmarkPolynomialEvaluatePartial` case from `//common/benchmarking`, we have mean±stddev as:
Branch | CPU time
-- | --
master | 1,277,255±19,435 us
PR | &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;4,049±64 us
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17727)
=> [symbolic] Add ExpressionCell::EvaluatePartial for performance

bindings/pydrake/manipulation/kuka_iiwa_py.cc, bindings/pydrake/manipulation/test/kuka_iiwa_test.py, manipulation/kuka_iiwa/iiwa_status_receiver.cc, manipulation/kuka_iiwa/iiwa_status_receiver.h, manipulation/kuka_iiwa/test/iiwa_status_receiver_test.cc
- Adds utime as an output port to the iiwa status receiver
- Adds relevant python bindings
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17761)
=> [manipulation] Expose utime as an output from received iiwa status

geometry/render/render_camera.cc, geometry/render/render_camera.h, geometry/render/test/render_camera_test.cc, systems/sensors/BUILD.bazel, systems/sensors/camera_info.cc, systems/sensors/camera_info.h, systems/sensors/test/camera_info_test.cc
1. `CameraInfo`
- Documented to throw even though it didn't.
- Throwing conditions have been extended and implementation supports it.
- Test extended to support documentation.
2. `ClippingRange` and `DepthRange`
- Previously tested for positive, now also test for finite.
- Testing supports documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17750)
=> [geometry] Camera specification does more rigorous validation

common/yaml/test/yaml_read_archive_test.cc, common/yaml/yaml_node.cc, common/yaml/yaml_read_archive.cc
- s/usign/using
- Typically the formatting is ...key 'key_name'...; one error message was missing the ticks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17773)
=> Clean up typos in yaml error messages

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py_hydro.cc, bindings/pydrake/test/geometry_hydro_test.py, geometry/proximity/polygon_surface_mesh.h, geometry/proximity/triangle_surface_mesh.h
Towards #17625.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17768)
=> [pydrake] Deprecate bindings of internal-use functions of PolygonSurfaceMesh

tools/install/installer.py, tools/install/test/install_meta_test.py
Modify `installer.py` to separately track all installed libraries versus libraries which need RPATH fixing. The former includes libraries that were already installed ("up-to-date"), which still need to be considered when fixing RPATHs for anything being (re)installed.
This fixes RPATH breakage in some instances when installing to the same location multiple times, especially if nothing else has changed in the interim.
Fixes #14224.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17779)
=> Fix install RPATH munging

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
Switches the default behavior of SolveShortestPath to `convex_relaxation=true`.
cc @RussTedrake @TobiaMarcucci
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17396)
=> [geometry/optimization] Change GCS SolveShortestPath to take configuration options

systems/sensors/BUILD.bazel, systems/sensors/camera_config.cc, systems/sensors/camera_config.h, systems/sensors/test/camera_config_test.cc
This introduces the `CameraConfig` class into Drake. This is predominantly a copy and clean up operation from Anzu.
Relates #17112
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17787)
=> [sensors] Migrate CameraConfig from anzu

multibody/parsing/BUILD.bazel
`multibody/parsing/BUILD.bazel` hides a lot of its implementation in the build (with visible = private). The package library includes six dependencies. Of those six dependencies, *five* have been explicitly declared to be public (so they can be accessed directly). This changes the sixth so it is treated the same.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17795)
=> [parsing] Unify parsing package visibility

tools/install/installer.py, tools/install/test/install_meta_test.py
Refactor the install helper script to encapsulate state information in a class instance. Mostly, this allows us to remove the ugly hack in the unit test which imports the installer and uses it multiple times.
While we're at it, simplify the implementation of `_may_be_binary`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17794)
=> Refactory installer.py

geometry/optimization/convex_set.h
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17782)
=> fix doxygen for ConvexSet::AddPointInNonnegativeScalingConstraints

geometry/proximity/deformable_contact_geometries.cc, geometry/proximity/deformable_contact_geometries.h, geometry/proximity/deformable_mesh_intersection.cc, geometry/proximity/test/deformable_contact_geometries_test.cc, geometry/proximity/test/deformable_mesh_intersection_test.cc, geometry/test/proximity_engine_test.cc
As the documentation of `SurfaceVolumeIntersector::SampleVolumeFieldOnSurface` states, the volume field to be sampled from should be based on the volume mesh in its current configuration, not any arbitrary configuration (e.g. the reference configuration). This is important because the gradient information used to interpolate values in the interior of tetrahedra depends on the configuration of the mesh.
In deformable mesh intersection, we incorrectly used the volume field based on the reference configuration of the deformable mesh and consequently were getting garbage penetration distances.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17789)
=> [geometry] Fix a bug in deformable mesh intersection

geometry/optimization/BUILD.bazel, geometry/optimization/convex_set.h, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/test/hpolyhedron_test.cc
I would imagine eventually supporting serialization for all of the
convex set classes, but HPolyhedron is a particularly important
special case since it is how we represent IRIS regions (which we
precompute offline).
+@ggould-tri for feature review, please?
fyi @mpetersen94 , @TobiaMarcucci .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17783)
=> Implements HPolyhedron::Serialize()

multibody/parsing/BUILD.bazel, multibody/parsing/model_directives.h, multibody/parsing/process_model_directives.cc, multibody/parsing/test/model_directives_test.cc, multibody/parsing/test/process_model_directives_test.cc, multibody/parsing/test/process_model_directives_test/default_positions.dmd.yaml
Adds the ability to set default joint positions and default free body
poses in the add_model directive. I would have liked to be able to
enable a tag like default_positions which takes a vector, but the
position vector is not defined until after Finalize(), so it
unavailable at parsing time.
Related to #13065, and this slack discussion:
https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1601749507024400
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17802)
=> [multibody/parsing] Add support for default positions in model directives

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Add sugar methods for setting the default position vector for all
joints / floating-bodies in a plant or model instance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17793)
=> [multibody] MultibodyPlant::SetDefaultPositions

examples/hardware_sim/hardware_sim.cc, examples/hardware_sim/scenario.cc, examples/hardware_sim/scenario.h
We don't want this to appear in our Doxygen anywhere.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17815)
=> [hardware_sim] Move header to internal namespace

systems/sensors/BUILD.bazel, systems/sensors/sim_rgbd_sensor.cc, systems/sensors/sim_rgbd_sensor.h, systems/sensors/test/sim_rgbd_sensor_test.cc
This introduces the `SimRgbdSensor` type and associated functions. For now, they are strictly internal, to be exercised by the `ApplyCameraConfig` (coming in a subsequent PR). In the future, it may come out of `internal::` namespace.
Relates #17112
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17797)
=> [sensors] Add infrastructure to support applying CameraConfig

multibody/meshcat/BUILD.bazel, multibody/meshcat/hydroelastic_contact_visualizer.cc, multibody/meshcat/test/hydroelastic_contact_visualizer_test.cc
In a rare example, we probably had one of hydroelastic force or moment almost zero but not both. Then, the meshcat code crashed.
Previously there was a guard against **both** force and moment near zero.
Now we handle the case that one of them is near zero. We draw the good one and ignore the near-zero one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17757)
=> [meshcat] no crash from visualizing almost-zero hydroelastic force or moment

solvers/mathematical_program_result.cc, solvers/test/mathematical_program_result_test.cc
Came across this while debugging QP w/ collision avoidance in Anzu.
In this formulation, collision avoidance is formulated as a set of collision avoidance queries. When using 
`GetInfeasibleConstraints()`, I was surprised to see the collision constraint printed out many times.
I think this was the intended behavior?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17818)
=> GetInfeasibleConstraints: Only return infeasible constraint once

bindings/pydrake/common/test/type_safe_index_pybind_test.cc, bindings/pydrake/common/type_safe_index_pybind.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17825)
=> [pydrake/common] Bind default constructor for TypeSafeIndex

systems/primitives/test/linear_transform_density_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17835)
=> Add unnamed namespace to prevent kcov issue #339

geometry/render_vtk/BUILD.bazel
All tests pass locally, however in CI the Horizon, Terrain, Sphere,
and TransparentSphere tests fail for undiagnosed reasons.
Closes https://github.com/RobotLocomotion/drake/issues/17566.
Note: we are going to run a handful of CI runs to try and stress test a bit given the erratic nature of the failures experienced by different audiences.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17804)
=> [render_vtk] Restore most macOS m1 tests

multibody/parsing/model_directives.h, multibody/parsing/process_model_directives.cc, multibody/parsing/test/model_directives_test.cc
Amends #17802.
The `LoadModelDirectives()` retains the default values of `struct AddModel` in case the YAML doesn't mention it.  It's OK for the YAML data to be missing fields -- they will remain at their default values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17822)
=> [parsing] Remove unnecessary optional

bindings/pydrake/test/geometry_scene_graph_test.py, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/query_object.h, geometry/test/geometry_state_test.cc
`ComputeSignedDistancePairClosestPoints()` is the only `QueryObject` API that takes `GeometryId`s. This puts the burden on the user to pass the *right* `GeometryId`s (e.g., properly registered with proximity roles). Prior to this, if they failed, they'd simply get the message:
> The geometry given by id 63 does not reference a geometry that can be used in a signed distance query
This now provides additional insight, indicating *why* it can't be used and giving insight into why they have the wrong one (e.g., it has an illustration role instead). This should help guide the user to change how they select their geometry ids.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/dr …
=> [geometry] Improve ComputeSignedDistancePairClosestPoints feedback

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
Adds an optional preprocessing step to the `SolveShortestPath`.  Currently off by default to preserve the current behaviors and it on average doubles the time to run on simple test problems.
Depends on #17396 
cc @TobiaMarcucci @RussTedrake
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17397)
=> [geometry/optimization] Enable preprocessing GCS before solving ShortestPath

systems/sensors/BUILD.bazel, systems/sensors/camera_config.h, systems/sensors/camera_config_functions.cc, systems/sensors/camera_config_functions.h, systems/sensors/test/camera_config_functions_test.cc
This provides the API for applying a `CameraConfig`. Applying a `CameraConfig` results in instantiating an `RgbdSensor` and publishers for the configured camera.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17827)
=> [sensors] Add ApplyCameraConfig function

geometry/proximity/BUILD.bazel, geometry/proximity/test/vtk_to_volume_mesh_test.cc, geometry/proximity/vtk_to_volume_mesh.cc, geometry/proximity/vtk_to_volume_mesh.h
Support #17780
Predecessor: none
Successor: #17820
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17817)
=> [geometry] Add scaling parameter for ReadVtkToVolumeMesh()

doc/_pages/release_playbook.md
Closes #17699.
[Linux staging job results here.](https://drake-jenkins.csail.mit.edu/view/Wheel/job/linux-focal-unprovisioned-gcc-wheel-staging-snopt-mosek-release/1/consoleFull)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17843)
=> [doc] Use linux wheel staging in release playbook

geometry/optimization/test/graph_of_convex_sets_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17855)
=> [geometry/optimization] Turn off preprocessing in all tests of GraphOfConvexSets except preprocessing tests

manipulation/models/jaco_description/LICENSE.TXT, manipulation/models/jaco_description/urdf/j2n6s300.urdf, manipulation/models/jaco_description/urdf/j2s7s300.urdf, manipulation/models/jaco_description/urdf/j2s7s300_arm.urdf, manipulation/models/jaco_description/urdf/j2s7s300_arm_sphere_collision.urdf, manipulation/models/jaco_description/urdf/j2s7s300_hand.urdf, manipulation/models/jaco_description/urdf/j2s7s300_hand_sphere_collision.urdf, manipulation/models/jaco_description/urdf/j2s7s300_sphere_collision.urdf, manipulation/util/BUILD.bazel
These were fixed upstream in
https://github.com/Kinovarobotics/kinova-ros/pull/222. But that PR
only fixed the 6DOF model, and made the fix by completely replacing
the mesh files.  Here I've just taken the (diffuse) color from the
mesh file and applied it in the URDF.
Before:
After:
+@sammy-tri for feature review, please (as the original contributor of these models).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17838)
=> [manipulation/models] Fix colors on kinova jaco models

manipulation/planner/BUILD.bazel, manipulation/planner/differential_inverse_kinematics_integrator.cc, manipulation/planner/differential_inverse_kinematics_integrator.h, manipulation/planner/test/differential_inverse_kinematics_integrator_test.cc, systems/framework/leaf_system.h
The integrator in Diff IK needs to be set to the initial state of the
robot in order to avoid a large delta at time zero. Previously, users
had to call SetPositions() manually; and this has to happen after
Diagram is built (when a context is created, etc). Because this occurs
in a different part of the code from where the Diff IK system is
created and the parameters configured, I often saw people copying part
of the code and forgetting the initialization, leading to strange
errors.
This PR offers a cleaner workflow where an additional port is
connected at the time that DiffIK is constructed and added to the
builder; then an Initialization event takes care of setting the
initial integrator state.
- - - …
=> [planning] Add initialization event to DiffIK Integrator

doc/_pages/apt.md, tools/install/dockerhub/focal/Dockerfile, tools/install/dockerhub/focal/README.md, tools/install/dockerhub/jammy/Dockerfile, tools/install/dockerhub/jammy/README.md
Drake is properly rpath'd and modifying LD_LIBRARY_PATH for users
is no longer necessary.
Closes #16932.
For testing, a `Dockerfile` with the following contents was built:
```docker
#
#
FROM ubuntu:20.04
RUN apt-get update && apt-get install -y firefox
RUN export uid=XXX gid=YYY && \
mkdir -p /home/developer && \
echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
echo "developer:x:${uid}:" >> /etc/group && \
mkdir /etc/sudoers.d && \
echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
chmod 0440 /etc/sudoers.d/developer && \
chown ${uid}:${gid} -R /home/developer
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install --no-install-recommends -y \
ca-certificates gnupg lsb-release wget
RUN wget -qO- …
```
=> Remove LD_LIBRARY_PATH from apt instructions and Dockerfiles

examples/hardware_sim/test/hardware_sim_test.py
In Debug builds it was flirting with the 60s timeout.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17864)
=> [examples] Reduce smoke test time for hardware_sim demo

tools/dynamic_analysis/valgrind.supp
Fixed nightly CI problems found in 
https://drake-jenkins.csail.mit.edu/view/Production/job/linux-focal-clang-bazel-nightly-everything-valgrind-memcheck/209/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17863)
=> Suppress memcheck when VTK file reader compares header line with garbage

lcmtypes/lcmt_viewer_draw.lcm, lcmtypes/lcmt_viewer_geometry_data.lcm
Also denote for position and color
Came across in #17848
Dunno how long these types will live, but useful and quick?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17867)
=> lcmtypes: Denote ordering for quaternion vectors

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
Resolves a previous TODO and lays the ground work to make the implementation of the GCS planner cleaner.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17844)
=> [geometry/optimization] Enable adding costs to vertices in GraphOfConvexSets

multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
Per suggestion by Russ, adds a link to the Medium Hydroelastic blog post to the Hydroelastic User Guide.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17875)
=> Add a link to the hydroelastic blog post to the user guide

tools/install/BUILD.bazel, tools/install/install.bzl, tools/install/libdrake/BUILD.bazel, tools/install/libdrake/test/rpath_install_test.py
Add an install test to inspect the set of libraries which libdrake.so consumes, specifically looking for any that are outside the install tree or system paths.
Closes #16990.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17858)
=> Add install test to verify library paths

examples/manipulation_station/manipulation_station.cc, examples/manipulation_station/manipulation_station.h, examples/manipulation_station/test/manipulation_station_test.cc
Test new calculations in manipulation_station.cc that employ CalcSpatialInertia() against old function MakeCompositeGripperInertia() that previously was in manipulation_station.cc and has now been moved to manipulation_station_test.cc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17847)
=> Use new CalcSpatialInertia() function in manipulation_station

doc/_pages/from_source.md, doc/_pages/installation.md, doc/_pages/rosetta2.md
Also removes the "AVX2" disclaimer, which was obsolete as of #17760.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17868)
=> [doc] Update macOS arm64 instructions

geometry/optimization/test/graph_of_convex_sets_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17883)
=> [geometry/optimization] Fix GCS vertex cost test on mac arm64

tools/install/bazel/test/drake_bazel_installed_test.py
The github.com URL occasionally flakes out, leading to spurious test failures.
Manually tested by re-running the test while commenting out each of the other URLs in turn.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17891)
=> [install] Add mirrors to bazel acceptance test

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
Re-enables preprocessing in the tests changed in #17855 and fixes a bug with the preprocessing tests.
Fix to #17397 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17876)
=> [geometry/optimization] Fix preprocessing for GraphOfConvexSets

tools/install/bazel/test/drake_bazel_installed_test.py, tools/workspace/abseil_cpp_internal/repository.bzl, tools/workspace/bazel_skylib/repository.bzl, tools/workspace/dm_control_internal/repository.bzl, tools/workspace/lcm/repository.bzl, tools/workspace/optitrack_driver/repository.bzl, tools/workspace/picosha2/repository.bzl, tools/workspace/pycodestyle/repository.bzl, tools/workspace/rules_python/repository.bzl
Towards #17807.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17872)
=> September 2022 updates

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py
In cases where the user declared a System event handler in Python but forgot to return `EventStatus.Succeeded`, they would receive a confusing message like so:
```
simulator.AdvanceTo(float(1.5))
TypeError: AdvanceTo(): incompatible function arguments. The following argument types are supported:
1. (self: pydrake.systems.analysis.Simulator_[float], boundary_time: float) -> pydrake.systems.analysis.SimulatorStatus
Invoked with: <pydrake.systems.analysis.Simulator_[float] object at 0x7f59bbf169f0>, 1.5
``` 
(Taken from [here](https://stackoverflow.com/questions/73396876/pydrake-typeerror-in-advanceto-arguments) for example.)
We could try to improve the error message, but it's even better to just allow "no return value" to mean "everything is fine", i.e., presume success.  The C++ already …
=> [pydrake] Enable return-None cases for System event handlers

tools/workspace/mosek/repository.bzl
Followup to #17870 which broke the macOS and linux wheel builds. Closes #17900.
From [slack #buildcop discussion](https://drakedevelopers.slack.com/archives/C270MN28G/p1663076706005239).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17901)
=> [workspace] Fix MOSEK wheel support for archive URLs

examples/hardware_sim/BUILD.bazel, examples/hardware_sim/example_scenarios.yaml, examples/hardware_sim/hardware_sim.cc, examples/hardware_sim/scenario.h, examples/hardware_sim/test/test_scenarios.yaml
Add the newly integrated `CameraConfig` into hardware sim. Also add an instance to the `OneOfEverything` test.
NOTE: the images produced by the hardware sim demo are *not* visible in `drake_visualizer`. The channel they are broadcast on is not the exact channel that `drake_visualizer` listens on for images.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17893)
=> [hardware_sim] Adding perception cameras to hardware sim

tools/wheel/BUILD.bazel, tools/wheel/Dockerfile, tools/wheel/image/build-python.sh, tools/wheel/image/provision-python.sh, tools/wheel/test/provision.sh, tools/wheel/wheel_builder/linux.py, tools/wheel/wheel_builder/linux_types.py, tools/workspace/python/repository.bzl, tools/workspace/vtk/repository.bzl
Add ability to build Python during wheel build environment provisioning, rather than relying on system packages. Add ability to have separate build and test platforms for wheels. Add a 3.10 wheel, built on Focal using Python 3.10.6 built from source and tested on Jammy.
Towards #17483.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17778)
=> Build wheels with self-built Python 3.10

bindings/pydrake/perception_py.cc, bindings/pydrake/test/perception_test.py, perception/BUILD.bazel, perception/point_cloud.cc, perception/point_cloud.h, perception/test/point_cloud_test.cc
Provide a simple, narrow, no-frills implementation of the voxel_down_sample algorithm in Open3d and/or the down-sampling by a VoxelGrid filter in PCL.
Towards https://github.com/RussTedrake/manipulation/issues/130.
+@calderpg-tri for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17885)
=> [perception] Implement PointCloud::VoxelizedDownSample

geometry/proximity/BUILD.bazel, geometry/proximity/make_mesh_field.cc, geometry/proximity/make_mesh_field.h, geometry/proximity/test/make_mesh_field_test.cc, geometry/query_results/contact_surface.h
Support #17780
Related but not a prerequisite: #17820
Successor: #17836
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17828)
=>  [geometry] Make pressure field for non-convex volume mesh

geometry/proximity/BUILD.bazel, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/hydroelastic_internal.h, geometry/proximity/test/hydroelastic_internal_test.cc
Support #17780.
Predecessors: #17828 and #17820.
Successor: #17837.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17836)
=> [geometry] Support compliant non-convex mesh in hydroelastic_internal.

tools/workspace/abseil_cpp_internal/patches/disable_int128_on_clang.patch, tools/workspace/abseil_cpp_internal/repository.bzl
Hotfix for #17885 to resolve UBSan linker/loader errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17921)
=> [workspace] Disable int128 support for absl

perception/BUILD.bazel, perception/point_cloud.cc
- Test case:
```
bazel test --config=clang --compilation_mode=dbg --config=tsan \
//tools/install/libdrake:drake_shared_library_test
```
- The link error was introduced by absl/container:flat_hash_map as reported by https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=1633056
- Use std::unordered_map instead (advice from Jeremy Nimmer).
Slack chat: https://drakedevelopers.slack.com/archives/C270MN28G/p1663249102991329
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17925)
=> [perception] Fixed link error reported by thread sanitizer

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
Adds an optional rounding step to the SolveShortestPath. Currently off by default to preserve the current behaviors.
Depends on #17396 
+@RussTedrake for feature review
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17796)
=> [geometry/optimization] Enable rounding of GCS solution when solving convex relaxation of ShortestPath

bindings/pydrake/perception_py.cc, bindings/pydrake/test/perception_test.py, perception/BUILD.bazel, perception/point_cloud.cc, perception/point_cloud.h, perception/test/point_cloud_test.cc, tools/workspace/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/nanoflann_internal/BUILD.bazel, tools/workspace/nanoflann_internal/package.BUILD.bazel, tools/workspace/nanoflann_internal/patches/namespace.patch, tools/workspace/nanoflann_internal/repository.bzl
Adds nanoflann as a (header-only) dependency, and implements the basic normal estimation algorithm for PointCloud, as seen in PCL and/or Open3d.
Towards https://github.com/RussTedrake/manipulation/issues/130.
+@jwnimmer-tri for feature review of the changes underneath `//tools`, please
+@calderpg-tri for feature review of the changes NOT underneath `//tools`, please
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17914)
=> [perception] Implement PointCloud::EstimateNormals

multibody/inverse_kinematics/minimum_distance_constraint.h, multibody/plant/multibody_plant.h, solvers/minimum_value_constraint.cc, solvers/minimum_value_constraint.h
Came across while reading `MinimumValueConstraint` to understand how some of Anzu's min-distance stuff works
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17939)
=> Replace 0xa0 character with space

perception/point_cloud.cc, perception/test/point_cloud_test.cc
The average of normals is not in general unit length. This fix adds the extra normalization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17945)
=> [perception] Normalize normals in PointCloud::VoxelizedDownSample

perception/point_cloud.cc, perception/test/point_cloud_test.cc
I had a bad typo in the code which only populated xyzs if has_normals() was true.  This fixes it and adds more test coverage.
(The updated test is only a minor refactor on the existing one, which runs multiple cases).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17948)
=> [perception] Fix PointCloud::Concatenate for XYZs only.

common/trajectories/discrete_time_trajectory.cc, geometry/render/test/render_camera_test.cc, geometry/render/test/render_engine_test.cc, geometry/render_gl/internal_opengl_context.cc, multibody/parsing/test/detail_sdf_geometry_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_geometry_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, solvers/program_attribute.cc
This enables the (soon to be required) compile-time checking of the pattern string by default.
+@SeanCurtis-TRI for both reviews per schedule, please +(status: single reviewer ok) +(priority: medium).
We'll use +(release notes: none) saving the release note for #17943 itself.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17949)
=> Use constexpr (not just const) for fmt strings

bindings/pydrake/geometry_py_scene_graph.cc, common/test/eigen_types_test.cc, doc/_pages/installation.md, geometry/query_results/penetration_as_point_pair.h, manipulation/kuka_iiwa/iiwa_driver.h, manipulation/schunk_wsg/schunk_wsg_driver.h
Fix deprecated-anon-enum-enum-conversion warning.
Fix aggregate initialization for C++20 semantics.
Add placeholder documentation for the C++ version we use.
Towards #14670.
We'd like to ensure that Drake's users who build in C++20 mode don't receive any errors.  In order to get that covered by CI, the plan is to build Ubuntu 20.04 in C++17 mode (unchanged), but to upgrade Ubuntu 22.04 and macOS to C++20 mode.  This PR handles the macOS side of that change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17918)
=> Fix C++20 errors on macOS

geometry/proximity/obb.cc, geometry/proximity/obb.h, geometry/proximity/test/obb_test.cc
We fit an OBB to a mesh (or cluster of features) using PCA analysis. It provides a reasonable estimate of a good OBB orientation. We have an optimization step that attempts to create a *better* orientation (and, thereby, a better fit). To optimize, we compute the partial derivative of OBB volume w.r.t. orientation of the box.
Previously, it was possible for that partial to have *zero* magnitude. This led to failures because the optimization algorithm would end up with infinite values (which could, in turn, lead to NaN values). So, we have to protect ourselves against that.
But beyond that, if the magnitude of the partial derivative is sufficiently small, there's really very little value in trying to further optimize the fit. So, we apply a threshold test for optimization to skip the …
=> [proximity] Improve/fix obb hierarchy construction

geometry/optimization/test/graph_of_convex_sets_test.cc
The Gurobi tolerance was set too tight.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17950)
=> [geometry/optimization] Hotfix for graph_of_convex_sets_test

common/symbolic/expression/expression.cc, common/symbolic/expression/expression.h, common/symbolic/expression/test/expression_test.cc, common/trajectories/bspline_trajectory.cc, common/trajectories/path_parameterized_trajectory.cc, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_trajectory.cc, common/trajectories/test/bspline_trajectory_test.cc, common/trajectories/test/path_parameterized_trajectory_test.cc, manipulation/schunk_wsg/BUILD.bazel, manipulation/schunk_wsg/schunk_wsg_position_controller.cc, math/BUILD.bazel, math/saturate.h, systems/primitives/BUILD.bazel, systems/primitives/saturation.cc
Prefer C++17 `clamp` over a pair of `min`,`max`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17942)
=> Deprecate math::saturate which is identical to std::clamp

geometry/BUILD.bazel, geometry/render_gl/factory.cc, geometry/render_gl/factory.h, geometry/render_gl/no_factory.cc, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/scene_graph_test.cc, systems/sensors/BUILD.bazel, systems/sensors/camera_config.cc, systems/sensors/camera_config.h, systems/sensors/camera_config_functions.cc, systems/sensors/test/camera_config_functions_test.cc, systems/sensors/test/camera_config_test.cc
1. `SceneGraph` supports a query to find out if a render engine *of a particular type* already exists.
2. `render_gl/factory.h` now provides a build-time `constexpr bool` reporting whether the engine is available or not.
- Incidentally cleaned up erroneous documentation.
3. `ApplyCameraConfig` extends its logic to instantiate `RenderEngine`s.
- Uses the new `SceneGraph` API and `constexpr bool kHasGl`.
- Implements default render engine type, handles availability of `RenderEngineGl`, and throws for any inconsistent act.
4. Incidentally cleans up some tests related to the units modified.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17927)
=> [config] Allow specification of render engine type in CameraConfig

geometry/BUILD.bazel, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/test/hydroelastic_internal_test.cc, geometry/proximity_engine.cc, geometry/test/proximity_engine_test.cc
- Also prevent a subtle problem that compliant hydroelastic geometries
get into registration process of deformable geometries.
Support #17780 
Predecessor: #17836
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17837)
=> [geometry] Compliant hydroelastic non-convex mesh in ProximityEngine 

bindings/pydrake/geometry_py_visualizers.cc, bindings/pydrake/test/geometry_visualizers_test.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat_types.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc, tools/workspace/meshcat/repository.bzl
This will enable, for instance, keyboard teleop through Meshcat. It will make the Deepnote teleop demos much more ergonomic.
Upgrades meshcat to the latest commit to get this feature.
To see the new features, `bazel run
//geometry:meshcat_manual_test`. The last prompt (starting with "I've added two buttons..." will now ask you to press keys in addition to using the gui button / slider for the interaction.
+@jwnimmer-tri for feature review, please.  (and platform, too, if you feel it's reasonable)
See also https://github.com/rdeits/meshcat/pull/129.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17947)
=> [meshcat] Allow keyboard events to move sliders and click buttons

common/test/text_logging_test.cc, common/text_logging.h, geometry/meshcat.cc, systems/sensors/image_writer.cc, tools/install/bazel/test/drake_bazel_installed_test.py
Relates to the "Enabled compile-time format string check by default" as described at [fmt 8.0.0](https://github.com/fmtlib/fmt/releases/tag/8.0.0).
See #17957 for examples of the CI failures this resolves ([click here](https://drake-jenkins.csail.mit.edu/job/linux-jammy-gcc-bazel-experimental-release/30/console)).
The CI for #17943 which incorporates this patch proves that it fully solves the problem.
Also adds a previously-overlooked C++17 flag to an acceptance test, now that we use `<string_view>` in one of the headers (`text_logging`) that happens to be covered by that acceptance test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17958)
=> [common] Add fmt_runtime compatibility shim for C++20

systems/sensors/BUILD.bazel
The test in camera_config_functions_test recently (#17927) added functionality that instantiated an RenderEngineGl. As such, it needed its tags updated.
Closes #17966.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17967)
=> Hotfix CI leak

tools/install/bazel/drake.BUILD.bazel, tools/install/bazel/repo_template.bzl
Closes #17965.
---
I've tested this locally by adding this patch atop https://github.com/RobotLocomotion/drake-external-examples/pull/237 ...
```
--- a/drake_bazel_installed/WORKSPACE
+++ b/drake_bazel_installed/WORKSPACE
@@ -48,7 +48,7 @@
-INSTALLED_DRAKE_DIR = None
+INSTALLED_DRAKE_DIR = "/home/jwnimmer/tmp/wakka"
new_local_repository(
```
... and then running this command:
```
(bazel run //:install -- /home/jwnimmer/tmp/wakka 2>&1 | tail) \
&& (cd ~/drake-external-examples/drake_bazel_installed && bazel test //...)
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17968)
=> [install] Add eigen support to the drake_bazel_installed workflow

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf
Closes #14747.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17956)
=> [parsing] Support parsing continuous joint in SDFormat

tools/workspace/qhull_internal/patches/cxx20.patch, tools/workspace/qhull_internal/repository.bzl
Towards https://github.com/RobotLocomotion/drake/pull/17943.  (The CI for https://github.com/RobotLocomotion/drake/pull/17943 which incorporates this patch proves that it fully solves the problem.)
See also https://github.com/qhull/qhull/pull/122.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17973)
=> [workspace] Fix Qhull build errors when in C++20 mode

solvers/test/osqp_solver_test.cc
Decrease the solve time so that the solver times out as expected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17975)
=> [solvers] Tweak OSQP solver test to satisfy CI

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/test/graph_of_convex_sets_test.cc
Handles the case where the convex relaxation is infeasible and rounding is requested as well as the case where the relaxation is feasible but all rounded solutions tried are infeasible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17974)
=> [geometry/optimization] Improve GraphOfConvexSets handling of infeasible problems

bindings/pydrake/geometry_py_optimization.cc, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/test/hpolyhedron_test.cc
Previously, it was possible for the sampler to happily return points outside of the region, if the polytope was overspecified (points outside of the set where still inside some redudant half-planes). This provides the fix and adds a test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17982)
=> [geometry/optimization] Fix corner case in HPolyhedron::UniformSample

multibody/plant/compliant_contact_manager.cc, multibody/plant/multibody_plant.cc
When printing a simulation time of type T = AutoDiff, it's not possible to use format precision specifiers. In any case, we should always use the default (round-trip) precision anyway.
The CI for #17943 which incorporates this patch proves that it fully solves the problem.
The CI for #17957 (i.e., with this patch reverted) displays the error messages we are fixing here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17994)
=> [plant] Remove fmt precision in error messages

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/iris.cc, geometry/optimization/iris.h, geometry/optimization/test/iris_in_configuration_space_test.cc
Adds options.num_infeasible_samples to support a probabilistic guarantee of correctness (with probability one as the number of samples goes to infinity) for the nonlinear-optimization-based version of IRIS.
Because this requires solving potentially many more (nearly identical) MathematicalPrograms, I've finally done the refactor which reuses the allocated programs and just updated the constraints.
BREAKING CHANGE: We have elected to remove support for Ibex from IRIS; it proved to only be useful for exceptionally toy problems and has become a footgun for users that turn it on (and wait forever). Rather than carry it through this refactor, I have elected to remove it.
+@mpetersen94 for feature review
+@cohnt for additional feature review
- - - …
=> [IRIS] New termination conditions for IrisInConfigurationSpace

bindings/pydrake/systems/lcm_pybind.h, math/autodiff.h
The `std::move` thing is because the move is _required_ for the code to compile (we need to convert the type of the object), yet the compiler also spews a false positive "redundant move" warning when it's in a single line.  Splitting it into two lines splits the difference in a way where both angles are happy.
The enum thing is just the usual C++20 "can't do math on enums anymore" deprecation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17995)
=> Fix some miscellaneous C++20 warnings

multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/contact_pair_kinematics.cc, multibody/plant/contact_pair_kinematics.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/sap_driver.h, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/compliant_contact_manager_tester.h, multibody/plant/test/deformable_driver_test.cc, multibody/plant/test/sap_driver_joint_limits_test.cc, multibody/plant/test/sap_driver_multidof_joints_test.cc, multibody/plant/test/sap_driver_test.cc, multibody/plant/test/spheres_stack.h
The purpose of this PR is to move everything related to the computation of discrete updates with SAP outside of the manager, which already contains significant functionality to evaluate discrete pairs (There might be an opportunity to split this functionality into another class, and let DiscreteUpdateManager be a thin shell that talks to MultibodyPlant).
Thus far in this PR I focused on taking all the code related to SAP into its own class.
Notes for platform review:
1. With the move of SAP related code into SapDriver, the unit tests were also split between manager specific and driver specific tests. No new functionality nor new tests were added, simply moved to new files.
2. SapDriver tests in turn were split into different files to group them into different "themes". Once again, no new …
=> Refactors SAP code outside of CompliantContactManager

multibody/plant/BUILD.bazel, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/test/deformable_driver_contact_test.cc, multibody/plant/test/deformable_driver_multiplexer_test.cc
The driver relies on QueryObject to compute the contact results. The contact results then inform the driver about contact participating for deformable dofs. For example, it enables the driver to extract participating velocities.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17969)
=> [multibody] DeformableDriver processes deformable body contacts

common/bit_cast.h, doc/_pages/installation.md, tools/macos.bazelrc, tools/ubuntu-jammy.bazelrc, tools/workspace/qhull_internal/package.BUILD.bazel
Closes #14670.
We'd like to ensure that Drake's users who build in C++20 mode don't receive any errors. In order to get that covered by CI, the plan is to build Ubuntu 20.04 in C++17 mode (unchanged), but to upgrade Ubuntu 22.04 and macOS to C++20 mode. This PR handles the Ubuntu side of that change.
Prerequisites:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17943)
=> Use C++20 on macOS and Ubuntu 22

bindings/pydrake/manipulation/BUILD.bazel, bindings/pydrake/manipulation/planner_py.cc, bindings/pydrake/manipulation/test/planner_test.py, examples/manipulation_station/end_effector_teleop_dualshock4.py, examples/manipulation_station/end_effector_teleop_mouse.py, examples/manipulation_station/end_effector_teleop_sliders.py, manipulation/planner/BUILD.bazel, manipulation/planner/differential_inverse_kinematics.cc, manipulation/planner/differential_inverse_kinematics.h, manipulation/planner/differential_inverse_kinematics_integrator.cc, manipulation/planner/test/differential_inverse_kinematics_integrator_test.cc, manipulation/planner/test/differential_inverse_kinematics_test.cc, multibody/parsing/detail_sdf_parser.cc
Resolves #9773.
There were a number of issues with the previous implementation, discussed at some length in #9773.
One implication of the cleaner formulation is that it is possible that the resulting optimization problem is an LP instead of a QP. In this case, Clp is used as a solver instead of Osqp, because Osqp cannot solve linear programs.
This change deprecates the "unconstrained degrees of freedom velocity limit" methods of the diff IK parameters class. This limit was only needed before because the formulation was bad. Since I'm already changing things on users, I've taken the chance to also deprecate the "timestep" methods in favor of "time_step", which we have agreed is the preferred form in Drake.
This PR also changes the default arguments for the Diff IK Parameters class …
=> [planner] Clean up formulation of Differential IK

doc/_pages/from_source.md, doc/_pages/installation.md, doc/_pages/mac.md
Binary artifacts produced by drake (nightly `.tar.gz` and releases) are now being compiled with Xcode 14.0.1.
Relates: #17985.
Note: release notes label may be incorrect here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18005)
=> [doc] x86_64 macOS monterey uses Xcode 14

bindings/pydrake/common/deprecation.py, bindings/pydrake/test/symbolic_test.py
Does not appear to impact functioning, but merits root-cause investigation
Towards #17898
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18017)
=> py deprecation: Ignore warnings for dtype=object operations

tools/workspace/mypy_internal/package.BUILD.bazel, tools/workspace/mypy_internal/repository.bzl
This fixes our macOS Unprovisioned builds.  See https://github.com/python/mypy/issues/13627.
Give up on the TODO for using mypy stable releases. Generally it looks like we're going to need bleeding-edge features.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18022)
=> [workspace] Upgrade mypy_internal to latest commit

bindings/pydrake/systems/drawing_graphviz_example.py, doc/_pages/documentation_instructions.md, tools/workspace/pybind11/mkdoc_comment.py
Handle dl/dt/dd tags in the pydrake doc toolchain by translating them into bold titles and stripping the rest. This fixes a visual bug in the pydrake.visualization docs.
Also fix a grammar error that was irking me and clarify that --quick in the doc build instructions only works for Doxygen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18006)
=> [doc] Fix description list handling for pydrake

CMakeLists.txt, cmake/external/workspace/conversion.bzl, cmake/external/workspace/fmt/BUILD.bazel.in, cmake/external/workspace/spdlog/BUILD.bazel.in
Closes #18025.  (Improves upon #16652 to be hermetically correct.)
Towards #16987.
For testing, I used the README from https://github.com/RobotLocomotion/drake-external-examples/tree/main/drake_cmake_external instructions after pointing it at my local Drake with this patch:
```patch
--- a/drake_cmake_external/CMakeLists.txt
+++ b/drake_cmake_external/CMakeLists.txt
@@ -148,13 +148,7 @@ set(DRAKE_INSTALL_PREREQS_USER_ENVIRONMENT
ExternalProject_Add(drake
DEPENDS eigen fmt spdlog
-  URL https://github.com/RobotLocomotion/drake/archive/master.tar.gz
-  # Or from a commit (download and use "shashum -a 256 'xxx.tar.gz'" on it to
-  # get the URL_HASH.
-  # URL https://github.com/RobotLocomotion/drake/archive/65c4366ea2b63278a286b1e22b8d464d50fbe365.tar.gz
-  # URL_HASH …
```
=> [cmake] WITH_USER_foo properly sandboxes shared libraries

multibody/plant/multibody_plant.h
The v1.5.0 release notes (#17519) failed announce the deprecation (#17445) at the time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18018)
=> [plant] Extend deprecation dates

doc/defs.py
Tested locally by running a `bazel run //doc:pages -- --serve` preview, opening up the localhost url in firefox, and then holding down Ctrl-Shift-R (aka force-reload) on the keyboard to spam the server.  (To prove that the new error handler was being run, I added a `print()` in the callback.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18009)
=> [doc] Suppress socket error messages during local preview

bindings/pydrake/manipulation/planner_py.cc, bindings/pydrake/manipulation/test/planner_test.py, manipulation/planner/differential_inverse_kinematics.cc, manipulation/planner/differential_inverse_kinematics.h, manipulation/planner/differential_inverse_kinematics_integrator.cc, manipulation/planner/differential_inverse_kinematics_integrator.h, manipulation/planner/test/differential_inverse_kinematics_integrator_test.cc, manipulation/planner/test/differential_inverse_kinematics_test.cc
Adds end-effector velocity limits for the entry point which takes a desired pose.
DiffIKIntegrator now continues to integrate even if DiffIK reports kStuck. Previously, kStuck (which means small velocity commands) resulted in the integrator commanding exactly zero velocity. This meant it was effectively impossible to get unstuck using DiffIK. The only reason for this before was because DiffIK did not return joint velocities when it was kStuck; but that limitaiton was resolved with my last PR.
Also adds a few minor improvements to the differential inverse kinematics tools:
- Minor touch-ups / todos in the documentation.
- Use the desired pose entry point in DiffIKIntegrator.
- Strengthens the TestLinearObjective test.
These changes will not impact the behavior for current users of …
=> Support end-effector velocity limits in DiffIK and integrate through kStuck

tools/workspace/osqp/repository.bzl, tools/workspace/qdldl/README.md, tools/workspace/qdldl/package.BUILD.bazel, tools/workspace/qdldl/repository.bzl
Even though the README advises not to upgrade qdldl past osqp's pin of qdldl (currently near 0.1.5), the [changes from 0.1.5 to 0.1.6](https://github.com/osqp/qdldl/compare/v0.1.5...v0.1.6) are only to the build system (and CI) so we might as well take them now to make any future feature-rich upgrades easier.
Adjust github paths to match relocated qdldl and osqp repositories.
Opt-in to strict mode for cmake configure variables.
Closes #17506.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18034)
=> [workspace] Update qdldl to latest release 0.1.6

tools/workspace/new_release.py
Somehow, the GitHub "newest first" iterator on the tags of a moved repository list the _old_ repo's tags first (from newest to oldest) followed by the _new_ repo's tags (from newest to oldest).  So, we need to filter the `gz` repositories' tags to start with `gz` in order to skip over the old tags.
I've manually tested with this PR that demoting our `gz-math` pin to the prior patch version (7.0.1) causes the tool to find 7.0.2, but running with 7.0.2 says "no upgrade required".
Closes #18033.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18036)
=> [workspace] Ignore old ignition tags when checking for a new_release

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py
Previous getter for solver_options returned a copy, preventing the user from setting individual options directly. These bindings fix the problem and add a test to confirm behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18040)
=> [bindings/optimization] Fix binding for solver_options in GraphOfConvexSetsOptions

multibody/parsing/BUILD.bazel, multibody/parsing/detail_common.cc, multibody/parsing/detail_common.h, multibody/parsing/detail_composite_parse.cc, multibody/parsing/detail_composite_parse.h, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/detail_mujoco_parser.h, multibody/parsing/detail_parsing_workspace.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_sdf_parser.h, multibody/parsing/detail_select_parser.cc, multibody/parsing/detail_select_parser.h, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/detail_urdf_parser.h, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/parsing_doxygen.h, multibody/parsing/process_model_directives.cc, multibody/parsing/test/detail_common_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_select_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/parser_test.cc
Make parser selection a general mechanism, so that (in future) model directives will not have to depend on Parser APIs directly. This is a preparation for making model directives files usable with the regular Parser APIs.
As a consesquence, this mechanism in principle allows files of any format to consume files of any other format, using Drake's parsers. This PR does not attempt to expand the currently supported combinations.
Also, public documentation is reorganized, in anticipation of support for more formats.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18003)
=> [parsing] Restructure parsers for format-agnostic recursion

tools/wheel/image/setup.py
Be clear that our binaries have more than just BSD-3-Clause licenses.
Link to pip instructions.
Remove hard-to-maintain list of supported python minor versions.
Relates to #17924.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17960)
=> [wheel] Tidy up some metadata

multibody/plant/BUILD.bazel, multibody/plant/test/joint_locking_test.cc, multibody/plant/test/multibody_plant_reaction_forces_test.cc
This PR refactors testing of joint locking by removing lock/unlock parameters from `multibody_reaction_forces_test` and adding a new test to `joint_locking_test` that verifies the physics of a locked joint matches that of a weld.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18051)
=> [multibody] remove joint locking from reaction forces test

multibody/tree/screw_joint.h, multibody/tree/screw_mobilizer.cc, multibody/tree/screw_mobilizer.h, multibody/tree/test/screw_joint_test.cc
Fixes a bug when simulating a screw joint caused by screw joint being a single dof joint but not having these methods implemented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18039)
=> [multibody] Add DoGetOnePosition and DoGetOneVelocity to ScrewJoint

multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/contact_properties.cc, multibody/plant/contact_properties.h, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/discrete_update_manager.h, multibody/plant/test/contact_properties_test.cc, multibody/plant/test/deformable_driver_contact_test.cc
In support of discrete contact pair calculation, move the logic of getting and combining point contact stiffness, dissipation time scale, and coulomb friction coefficient out from CompliantContactManager into free functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18029)
=> [multibody] DeformableDriver computes discrete contact pairs 

multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/deformable_model.cc, multibody/plant/deformable_model.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/test/deformable_driver_contact_kinematics_test.cc, multibody/plant/test/deformable_model_test.cc
In support of that
- Make vertex permutation a cache entry to avoid thrashing the results.
- Provide conversions from body id to body index and from geometry id to body id.
- Move related functions in DiscreteUpdateManager from protected to public.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18047)
=> [multibody] DeformableDriver computes ContactPairKinematics

manipulation/util/geometry_inspector.py, manipulation/util/show_model.py, manipulation/util/test/geometry_inspector_test.py, manipulation/util/test/show_model_test.py, tools/workspace/meshcat/README.md
Extend the show_model script to cover all of the capabilities of geometry_inspector and remove superfluous code from the latter script:
- show_model now provides joint sliders in meshcat.
- show_model now always provides a meshcat connection.
- show_model now visualizes both visual and collision geometry.
- show_model now supports --position for setting sliders.
- show_model now includes a --test option.
This change also removes the --meshcat and --meshcat_role options, as they are no longer required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18044)
=> Add joint sliders and dual geometry capability to show_model

geometry/optimization/BUILD.bazel, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/test/graph_of_convex_sets_test.cc
Prior to this fix adding more than one cost to the same vertex would cause the solve to fail.  Added test to confirm fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18043)
=> [geometry/optimization] Fix multiple Vertex costs bug

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/custom_test.py
This one was somehow missing from the State API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18070)
=> [pydrake/systems] Add binding for State.get_abstract_state(index)

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/test/type_safe_index_pybind_test.cc, bindings/pydrake/common/type_safe_index_pybind.h, bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/primitives/port_switch.h
These two go together; without the value instantiation, test_port_switch fails with
```
File "/home/russt/.cache/bazel/_bazel_russt/a0bdb2099cb05916281dea472bfce61b/sandbox/linux-sandbox/4037/execroot/drake/bazel-out/k8-opt/bin/bindings/pydrake/systems/py/primitives_test.runfiles/drake/bindings/pydrake/systems/test/primitives_test.py", line 299, in test_port_switch
system.get_port_selector_input_port().FixValue(context, a.get_index())
RuntimeError: This derived class of `AbstractValue`, `drake::Value<drake::TypeSafeIndex<drake::systems::InputPortTag>>`, is not exposed to pybind11, so `set_value` cannot be called. See `AddValueInstantiation` for how to bind it.
```
+@jwnimmer-tri for feature review, please
- - - …
=> [pydrake] Add bindings for PortSwitch and Value instantiations for TypeSafeIndex

manipulation/planner/differential_inverse_kinematics_integrator.cc, manipulation/planner/differential_inverse_kinematics_integrator.h, manipulation/planner/test/differential_inverse_kinematics_integrator_test.cc
This allows the DiffIK to use the current (optional) robot_state port instead of the integrated state, and to reset the integrator to that state.
I needed this because I had a more complicated controller that would switch between using DiffIK and using direct joint position commands. Without this port, switching *back* to the DiffIK controller resulted in the DiffIK integrator being far from the current true joint positions.  By setting `use_robot_state = true` during the joint position control mode, the DiffIK integrator keeps itself up to date with the current robot state.
+@siyuanfeng-tri for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drak …
=> [manipulation/planner] Add optional use_robot_state port to Diff IK Integrator

bindings/pydrake/systems/all.py, bindings/pydrake/systems/drawing.py
Defer the `pydrake.systems.drawing` imports of `pydot` and `plt` to function-call time instead of module-import time.
Even with the try-except handling, a broken `pyplot` import was still spamming the user's console with Xorg and GTK errors, which now is build-time console spam due to `stubgen`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18081)
=> [pydrake] Move import-error handling out of pydrake.all

systems/lcm/BUILD.bazel, systems/lcm/lcm_buses.cc, systems/lcm/lcm_buses.h, systems/lcm/lcm_config_functions.cc, systems/lcm/lcm_config_functions.h, systems/lcm/test/lcm_config_functions_test.cc, visualization/BUILD.bazel, visualization/test/visualization_config_functions_test.cc, visualization/visualization_config_functions.cc
Towards #18069.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18090)
=> [systems/lcm] Factor out magical lcm_buses lookup for reuse

bindings/pydrake/systems/sensors_py.cc, bindings/pydrake/systems/test/sensors_test.py, examples/hardware_sim/hardware_sim.cc, examples/hardware_sim/hardware_sim.py, examples/hardware_sim/test/hardware_sim_py_test.py, examples/hardware_sim/test/test_scenarios.yaml, systems/sensors/BUILD.bazel, systems/sensors/camera_config.h, systems/sensors/camera_config_functions.cc, systems/sensors/camera_config_functions.h, systems/sensors/test/camera_config_functions_test.cc, visualization/visualization_config.h
Requires:
This brings the nice optional argument sugar from visualization config over to camera config as well.
Update hardware_sim examples to use the new spelling.  This allows the Python enable to sucessfully use cameras now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18069)
=> [sensors] Add lcm_bus name to CameraConfig

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py
Sometimes it's convenient to be able to parse and inspect the directives from Python.
Relatedly, fix bindings order to match physical dependency order (i.e., always bind child structs prior to binding their enclosing structs) for both `ModelDirectives` and `CameraConfig`.
Towards #18109 in service of #17112.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18108)
=> [pydrake] Bind all model directives

bindings/pydrake/common/cpp_param.py, bindings/pydrake/common/cpp_param_pybind.cc, bindings/pydrake/common/test/cpp_param_pybind_test.cc, bindings/pydrake/common/test/cpp_param_test.py
The rules for uint16 and uint64 were partially and/or fully missing.
Towards #18109.
+@EricCousineau-TRI for both reviews, please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18115)
=> [pydrake] Add type canonicalization for all unsigned ints

bindings/pydrake/_math_extra.py, bindings/pydrake/math_py.cc, bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/_math_extra.py, bindings/pydrake/multibody/math_py.cc, bindings/pydrake/multibody/test/math_test.py
py math:
- Add slight adjustment to logic / imports
- Add note about where `__repr__` is defined
Motivated by doing some math for haptic stuff
Following / adapting pattern from #14993
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18112)
=> py multibody math: Add repr() for spatial vectors

tools/install/BUILD.bazel, tools/install/installer.py, tools/install/test/installer_test.py
Tweak logic to install symlinks to forcibly replace existing entities. This behavior is more consistent with installing files, which already replaces existing entities.
Also, add the start of a unit test suite for the installer, testing this function specifically.
Fixes #18007.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18107)
=> Fix installation of symlinks

geometry/geometry_state.cc, geometry/geometry_state.h
- Remove the redundant parameter (geometry_id).
- The geometry passed already has the id.
- Passing the id explicitly opens for an error in which the geometry is associated with the *wrong* geometry id.
- Change the name so it doesn't imply roles are *arbitrarily* assigned.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18120)
=> [geometry] Clean up AssignAllRoles for registering geometry

bindings/pydrake/common/cpp_param.py, bindings/pydrake/common/test/cpp_param_test.py
We still need to carefully canonicalize the parameters used for instantiation, but we don't need to re-implement the typeclasses themselves.
Add generics for Optional and Union, to be used down the road.
Towards https://github.com/RobotLocomotion/drake/pull/18109.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18117)
=> [pydrake] Use Python's typing for generic types

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/test/iris_in_configuration_space_test.cc, multibody/parsing/detail_dmd_parser.cc, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/test/parser_test.cc, multibody/plant/test/multibody_plant_query_object_connect_test.cc
This new method allows DMD format data to be read from a string, and paves the way for eventual deprecation and removal of the obsolete "singular" methods.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18110)
=> [parsing] Add Parser::AddModelsFromString

multibody/contact_solvers/sap/sap_contact_problem.cc, multibody/contact_solvers/sap/sap_contact_problem.h, multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/deformable_model.h, multibody/plant/discrete_update_manager.h, multibody/plant/sap_driver.cc, multibody/plant/sap_driver.h, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/deformable_driver_contact_test.cc, multibody/plant/test/deformable_driver_multiplexer_test.cc, multibody/plant/test/deformable_driver_test.cc, multibody/plant/test/sap_driver_test.cc
- Add DeformableDriver::CalcDiscreteStates().
- Update DeformableDriver::CalcNextFemState() to account for contact.
- Use deformable v0, v*, and tangent matrix A in CompliantContactManager
- Move Multiplexer out of DeformableDriver.
- Add a mutable variant of Multiplexer::Demultiplex.
- Modify SapDriver::PackContactSolverResults() to account for deformable bodies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18067)
=> [multibody] DeformableDriver uses contact solver results

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/plant/test/multibody_plant_reaction_forces_test.cc, multibody/tree/prismatic_joint.cc, multibody/tree/prismatic_joint.h, multibody/tree/prismatic_mobilizer.h, multibody/tree/revolute_joint.cc, multibody/tree/revolute_joint.h, multibody/tree/revolute_mobilizer.h, multibody/tree/screw_joint.cc, multibody/tree/screw_joint.h, multibody/tree/screw_mobilizer.cc, multibody/tree/screw_mobilizer.h, multibody/tree/test/screw_mobilizer_test.cc
Closes #17882.
* Adds a constructor to `ScrewJoint` that accepts a `Vector3<double>` for the axis unit vector and a `screw_axis()` accessor method to the class. The current constructor that assumes the axis unit vector is the Z-axis is retained but may be considered for deprecation in the future. I adapted the documentation based on the `revolute_joint.h` header file.
* Adds a `Vector3<double>` argument for the axis unit vector to the `ScrewMobilizer` constructor and updates the mobilizer math in [34a2dab](https://github.com/RobotLocomotion/drake/pull/18019/commits/34a2dab8c57fbf3a19419ad0ea334b6175fef631) to use this unit vector instead of the Z-axis.
- - - …
=> ScrewJoint: accept axis unit vector in constructor

multibody/tree/ball_rpy_joint.cc, multibody/tree/ball_rpy_joint.h, multibody/tree/planar_joint.cc, multibody/tree/planar_joint.h, multibody/tree/prismatic_joint.cc, multibody/tree/prismatic_joint.h, multibody/tree/revolute_joint.cc, multibody/tree/revolute_joint.h, multibody/tree/screw_joint.cc, multibody/tree/screw_joint.h, multibody/tree/universal_joint.cc, multibody/tree/universal_joint.h, multibody/tree/weld_joint.cc, multibody/tree/weld_joint.h
Excellent explanation from @rpoyner-tri in #18019:
Because this function body is in a header file and uses static never_destroyed, it in effect creates global storage that could end up having definitions in multiple object files. Having consulted the local C++ experts, we believe that a pure C++ environment could handle this hazard, but that it could potentially cause subtle multiple-definition problems for Drake's python bindings shared libraries. That is, individual libraries might build, but have symbol conflicts when loaded together in a single program.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18101)
=> Move Joint::type_name() to their source files

geometry/render_gltf_client/test/integration_test.py
Color image failure:
```
======================================================================
FAIL [21.468s]: test_integration (integration_test.TestIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/admin/workspace/mac-m1-monterey-provisioned-clang-bazel-nightly-release/_bazel_admin/3bfef0a0aa84e152ebd33dd4f2f4a7db/sandbox/darwin-sandbox/6772/execroot/drake/bazel-out/darwin_arm64-opt/bin/geometry/render_gltf_client/py/integration_test.runfiles/drake/geometry/render_gltf_client/test/integration_test.py", line 123, in test_integration
self.assert_error_fraction_less(color_diff, INVALID_PIXEL_FRACTION)
File "/Users/admin/workspace/mac-m1-monterey-provisioned-clang-bazel-nightly-release/_bazel_admin/3bfef0a0aa8 …
```
=> [render_gltf_client] Weaken test threshold (for macOS arm64)

solvers/gurobi_solver.cc, solvers/test/gurobi_solver_test.cc
When an `int` is given for a `double` option, auto-promote to `double`.
When an option is given with the wrong type, explain the mismatch.
Closes #18024.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18124)
=> [solvers] Gurobi options are handled more gracefully

multibody/parsing/test/detail_sdf_geometry_test.cc, tools/workspace/sdformat_internal/repository.bzl
Closes #18129.
There are some new overloads of the `Load()` methods that take a ParserConfig object (from https://github.com/gazebosim/sdformat/pull/1147) so that the old APIs use GlobalConfig, so pass the `StrictConfig` to those APIs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18130)
=> [workspace] Upgrade sdformat_internal to 13.1.0

doc/_pages/code_review_checklist.md, doc/_pages/jenkins.md, doc/_pages/release_playbook.md
Update the documentation to use the new names.
Towards #17869
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18143)
=> [doc] Jenkins Mac jobs have been renamed

tools/BUILD.bazel, tools/workspace/drake_visualizer/BUILD.bazel, tools/workspace/drake_visualizer/drake_visualizer_bazel.py, tools/workspace/drake_visualizer/stub/pydrake/__init__.py, tools/workspace/drake_visualizer/use_drake_lcmtypes.patch
The `pydrake.getDrakePath()` path is no longer used to populate Director's package map.
This removes the ability to send `package://drake/models/...` URIs in `lcmt_viewer_load_robot`, but no code within Drake does that anyway.  Drake only ever sends absolute filename paths to Director for our meshes.
Users who need to load Drake package URIs via that message can set either of two environment variables to enable package map searching:
```
export ROS_PACKAGE_PATH=/path/to/drake
```
or
```
export DRAKE_PACKAGE_PATH=/path/to/drake
```
Towards #18141.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18144)
=> [tools] Fully evict pydrake from drake_visualizer

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/serialize_pybind.h, bindings/pydrake/common/test/serialize_import_failure_test.py, bindings/pydrake/common/test/serialize_pybind_test.py, bindings/pydrake/common/test/serialize_test_bar_py.cc, bindings/pydrake/common/test/serialize_test_foo_py.cc, bindings/pydrake/common/test/serialize_test_foo_py.h, bindings/pydrake/common/test/serialize_test_util_py.cc, bindings/pydrake/systems/sensors_py.cc
C++ structs whose Python attributes are bound using Serialize now offer a `__fields__` static property, enabling downstream code to interrogate the static schema of the type (akin to Python's dataclasses).
One consequence of this change is that the C++ classes used as struct fields must be bound prior to binding the struct that uses them. The `CameraConfig` structs need an adjustment to accommodate this.
Requires:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18109)
=> [pydrake] Bind dataclass-like schemas for serializable structs

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/plant/test/multibody_plant_test.cc, multibody/tree/frame.h, multibody/tree/multibody_tree_indexes.h, multibody/tree/test/multibody_tree_indexes_test.cc, multibody/tree/test/tree_from_mobilizers_test.cc
Motivated by https://github.com/RobotLocomotion/drake/pull/17223#pullrequestreview-1149980403
Also adds simple checks on `num_multibody_states` and `num_actuated_dofs` for other empty world tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18149)
=> Add multibody::world_frame_index() getter

geometry/optimization/BUILD.bazel, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/test/graph_of_convex_sets_test.cc
Fixes a corner case that was [initially discussed](https://reviewable.io/reviews/robotlocomotion/drake/17796#-NC1MIxy3bAQXnkq0BiX) when rounding was added to GraphOfConvexSets. At the time, an example that triggered the failure case could not be constructed for unit testing.
This adds a simple test that triggers the corner case as well as the fix previously discussed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18063)
=> [geometry/optimization] Fix depth first search failure in GraphOfConvexSets rounding

bindings/pydrake/__init__.py, doc/_pages/pip.md, tools/wheel/.dockerignore, tools/wheel/Dockerfile, tools/wheel/content/INSTALLATION, tools/wheel/image/build-wheel.sh, tools/wheel/image/setup.py, tools/wheel/test/tests/hermetic/import-error-test.sh, tools/wheel/wheel_builder/linux.py
Modify pydrake (at least, `import pydrake.all`) to detect when it can't be loaded due to failure to load a dynamic library, and to give a somewhat more user-friendly error message. Add a brief document listing what distro packages need to be installed, which is referenced by the aforementioned error.
Fixes #16383.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18015)
=> Improve error reporting when pydrake import fails

doc/_pages/release_playbook.md
The users who previously required official releases for our first-party externals no longer need that. We can simplify our life by omitting this step from now on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18164)
=> [doc] Remove externals tagging from release playbook

geometry/optimization/cartesian_product.cc, geometry/optimization/cartesian_product.h, geometry/optimization/test/cartesian_product_test.cc
@AlexandreAmice for feature review (namely to confirm `DoIsBounded` is correct)
cc @RussTedrake @TobiaMarcucci
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18140)
=> [geometry/optimization] Remove requirement that CartesianProduct sets must be bounded

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf, tools/workspace/sdformat_internal/repository.bzl
Part of #17765.
Depends on https://github.com/gazebosim/sdformat/pull/1168 to provide the `//joint/screw_thread_pitch` parameter in SDFormat 1.10 and corresponding `Joint::ScrewThreadPitch()` that uses the same units as drake: meters / revolution. The existing `thread_pitch` parameter (exposed via `Joint::ThreadPitch()`) has been used in gazebo classic with inverse units and the opposite sign convention.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18127)
=> Parse screw joints from SDFormat

bindings/pydrake/common/cpp_template.py, bindings/pydrake/common/test/cpp_template_test.py, bindings/pydrake/common/test/value_test.py
Useful when trying to get the equivalent of `type.__module__`
py value: Add equivalent test
Resolves #18168
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18169)
=> cpp_template: Add get_module_name()

tools/wheel/image/build-wheel.sh, tools/wheel/image/provision-python.sh, tools/wheel/test/tests/hermetic/import-error-test.sh
The latest `auditwheel==5.2.0` is not compatible with our environment. We'll pin the prior version for now.
The recent commit (#18015) adding an import-error test case had a mismatch in the actual error message vs expected error message; fix that here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18165)
=> [wheel] Hotfix broken auditwheel and import error test case

multibody/parsing/test/detail_collision_filter_group_resolver_test.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/plant/test/contact_results_to_lcm_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/topology/multibody_graph.h, multibody/tree/multibody_tree.cc
More in line with conventions in URDF and SDFormat
Resolves #14638
Per #18149 and stability guidelines, shouldn't need deprecation?
(Though Anzu code, and probably other's, will need to change)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18158)
=> multibody: Change world body name from "WorldBody" to "world"

bindings/pydrake/manipulation/kuka_iiwa_py.cc, bindings/pydrake/manipulation/test/kuka_iiwa_test.py, manipulation/kuka_iiwa/iiwa_command_sender.cc, manipulation/kuka_iiwa/iiwa_command_sender.h, manipulation/kuka_iiwa/iiwa_status_sender.cc, manipulation/kuka_iiwa/iiwa_status_sender.h, manipulation/kuka_iiwa/test/iiwa_command_sender_test.cc, manipulation/kuka_iiwa/test/iiwa_status_sender_test.cc
Continues work done in #17761 to allow command publisher to use utime from received status message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18167)
=> [manipulation] Expose utime input port for IiwaCommandSender and IiwaStatusSender

common/trajectories/BUILD.bazel, common/trajectories/discrete_time_trajectory.cc, common/trajectories/piecewise_polynomial.cc, math/matrix_util.h, math/test/matrix_util_test.cc
This was a utility used in a few trajectory classes.  I'm using it in my upcoming KinematicTrajectoryOptimization PR; by the rule of 3 I'm extracting it to a common location rather than making another copy.
+@sherm1 for both reviews(?), please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18183)
=> [math] Convert between std::vector<VectorX<T>> and MatrixX<T>

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/bspline_trajectory.cc, common/trajectories/bspline_trajectory.h, common/trajectories/test/bspline_trajectory_test.cc
Error messages which formerly printed "CheckInvariants failed" now print the error (with the control_points.size == num_basis_functions check failing).
The BsplineTrajectory constructor now accepts 2d numpy arrays to describe a vector of vector control points, consistent with the PiecewisePolynomial constructors.
This is a breaking change.  Previous calls to e.g.
```
BsplineTrajectory(basis, control_points=[np.zeros(3), np.ones(3)])
```
will now be interpretted as 3 control points of size 2, when they were previously interpretted as 2 control points of size 3.  I think this is an inevitable consequence, and was already an inconsistency with the PiecewisePolynomial static methods.
- - - …
=> [pydrake] Improve BsplineTrajectory usability

bindings/pydrake/BUILD.bazel, bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic/test/trigonometric_polynomial_test.cc, common/symbolic/trigonometric_polynomial.cc, common/symbolic/trigonometric_polynomial.h, multibody/rational/rational_forward_kinematics.cc, multibody/rational/rational_forward_kinematics.h, multibody/rational/test/rational_forward_kinematics_test.cc
1. SubstituteStereogrphicProjection supports indeterminates including variables other than sin/cos.
2. Deprecate SubstituteStereogrphicProjection with the symbolic::Expression as the input.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18179)
=> Support prismatic joint in RationalForwardKinematics.

multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.cc, multibody/plant/slicing_and_indexing.cc, multibody/plant/slicing_and_indexing.h, multibody/plant/test/slicing_and_indexing_test.cc
Per request in #18170, helper methods used in the joint locking code is move outside `MultibodyPlant` into their own files.
Towards #16955 and #13888.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18186)
=> Relocate helper methods for slicing and indexing 

bindings/pydrake/systems/sensors_py.cc, bindings/pydrake/systems/test/sensors_test.py, bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/_video.py, bindings/pydrake/visualization/_visualization_extra.py, bindings/pydrake/visualization/test/video_test.py
This PR is big enough with just the feature itself.  In a follow-up, I hope to add an actual tutorial.
Note that CI here will fail until we have new provisioned images ready (#18016).
---
Example usage:
```python
sensor_pose = RigidTransform(RollPitchYaw([-np.pi/2, 0, np.pi/2]), [2, 0, 0.75])
writer = VideoWriter.AddToBuilder(
filename="output.mp4", builder=builder, sensor_pose=sensor_pose)
writer.Save()
```
---
Example unit test output:
**color.mp4**
https://user-images.githubusercontent.com/17596505/179676950-3ffe3518-0b5e-4b12-a441-28400d0dc5f5.mp4
**multi.mp4**
https://user-images.githubusercontent.com/17596505/179676957-a9b11463-eead-433e-933e-f23a23d80375.mp4
**color.gif**
---
At least in local notebooks, the user can also do this, to play the video as the cell output:
```python …
```
=> [visualization] Add VideoWriter system

tools/install/libdrake/BUILD.bazel, tools/install/libdrake/drake-config.cmake.in, tools/install/libdrake/test/drake_python_dir_install_test.py
This will provide a reliable way for downstream CMake projects to get information about the Python modules installed as part of Drake.
Resolves #18150
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18201)
=> Provide Python module information in drake-config.cmake

geometry/meshcat_types.h, geometry/test/meshcat_test.cc
I suspect this resolves the issue reported by @trowell-tri and @JoseBarreiros-TRI on TRI slack.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18213)
=> [meshcat] Fix PerspectiveCamera msgpack

bindings/pydrake/multibody/test/meshcat_test.py, multibody/meshcat/joint_sliders.cc, multibody/meshcat/joint_sliders.h, multibody/meshcat/test/joint_sliders_test.cc
As requested in https://stackoverflow.com/questions/74251312/pydrake-how-to-return-joint-positions-in-forward-kinematics-example/74254419
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18215)
=> [meshcat] JointSliders::Run() returns the final positions

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
Writing some simple torque controllers in a plant with some floating bodies and other robots. Found this was missing.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18209)
=> py plant: Bind MakeActuatorSelectorMatrix overloads

common/symbolic/expression/BUILD.bazel, common/symbolic/expression/boxed_cell.cc, common/symbolic/expression/test/boxed_cell_test.cc, common/symbolic/expression/test/sparse_test.cc
Fixes #18218.
Missed in #17612 (for boxed cell) and #17544 (when switching to use boxed cell).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18219)
=> [symbolic] Fix SparseMatrix<Expression> data loss

geometry/drake_visualizer.cc, geometry/make_mesh_for_deformable.cc, geometry/make_mesh_for_deformable.h, geometry/meshcat.cc, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/iris.cc, geometry/proximity/deformable_contact_internal.cc, geometry/proximity/deformable_contact_internal.h, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/hydroelastic_internal.h, geometry/proximity_engine.cc, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/internal_render_engine_gl.h, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/internal_render_engine_vtk.h, geometry/shape_specification.cc, geometry/shape_specification.h, geometry/shape_to_string.cc, geometry/shape_to_string.h, geometry/test/geometry_state_test.cc, geometry/test/shape_specification_test.cc, geometry/test/shape_to_string_test.cc, geometry/test_utilities/dummy_render_engine.h
The ordering of the shapes has historically been chaotic (they were ordered according to introduction order). This makes it hard to find the desired shape and interferes with assessing if a shape implementation is missing in a reifier.
The declarations of shapes are now alphabetized as well as the in the `ShapeReifier` implementation. Tests and implementations have been updated to reflect the same order.
This incidentally cleans up a couple of outliers discovered during the process.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18202)
=> [geometry] Define alphabetical order to Shapes by convention

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/solvers_py_dreal.cc, bindings/pydrake/solvers/solvers_py_ibex.cc, bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/dreal_solver_test.py, bindings/pydrake/solvers/test/ibex_solver_test.py, solvers/BUILD.bazel, solvers/dreal_solver.cc, solvers/dreal_solver.h, solvers/dreal_solver_common.cc, solvers/ibex_solver.cc, solvers/ibex_solver.h, solvers/ibex_solver_common.cc, solvers/solver_type.h, solvers/solver_type_converter.cc, solvers/test/solver_type_converter_test.cc, tools/workspace/cds/repository.bzl, tools/workspace/default.bzl, tools/workspace/dreal/repository.bzl, tools/workspace/ibex/repository.bzl, tools/workspace/picosat/repository.bzl
Deprecate the classes DrealSolver, IbexSolver, and their nested helper classes.
Deprecate the workspace externals cds, dreal, ibex, and picosat.
----
This pull request is a proposal of an idea bouncing around for a few months.  I'll leave it open for comments until **2022-10-31** at which point we'll plan to merge it (unless we hear any objections).  Feel free to reply in this issue, or Drake slack, or send me an email.
There are two thoughts behind this proposal.
(1) It is becoming increasingly difficult to keep up with the build and release tasks involved with distributing dReal and IBEX (#15872, #15970, #16882, #17231, #17869, etc.).
The code and its dependencies offers a few unique challenges -- LGPL licensing, x86 assembly code, and a very finicky version compatibility matrix across …
=> [solvers] Deprecate dReal and IBEX for removal

multibody/parsing/package_map.cc
We'd intended to deprecate this previously (#17251), but apparently I can't read and I mistakenly removed the release notes label.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18226)
=> [parsing] Deprecate PopulateFromEnvironment("ROS_PACKAGE_PATH")

bindings/pydrake/_geometry_extra.py, bindings/pydrake/test/geometry_visualizers_test.py, examples/manipulation_station/end_effector_teleop_dualshock4.py
Likewise remove MeshcatPointCloudVisualizerCpp.
Follow-up from #17462.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18225)
=> [pydrake] Remove deprecated MeshcatVisualizerCpp 2022-11

systems/sensors/camera_config_functions.h
There was a typo in #18069.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18228)
=> [sensors] Fix typo in deprecation date

math/BUILD.bazel, math/test/fast_pose_composition_functions_test.cc
Relates to #13514.
See [slack thread](https://app.slack.com/client/T0JNB2DS4/C0KDGF4V9/thread/C0KDGF4V9-1667265291.809839) for a user testimonial that this resolves a problem with their attempt to build on arm64.
We don't have Ubuntu arm64 in CI (yet?), so the updated `BUILD` logic is only covered by testimonial, not by CI.  Therefore it might regress without us noticing, but that's fine because it's not a supported build flavor. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18221)
=> [math] Don't use march=broadwell on Ubuntu arm64 machines

math/BUILD.bazel
Hotfix for #18221.
Keep the missing unit test and comment fixes intact, but revert the arm64 change to the BUILD file to unbreak CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18230)
=> Partially revert "... march=broadwell on Ubuntu arm64 machines"

tools/dynamic_analysis/valgrind.supp
Address #18223
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18231)
=> Add memory leak exception to valgrind.supp to mute mosek memory leak error

setup/mac/binary_distribution/install_prereqs.sh
As a courtesy, we were uninstalling software that's no longer needed by Drake (#16945). We assume that enough users will have run this by now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18229)
=> [setup] Remove macOS auto-cleanup for drake_visualizer's removal

tools/wheel/image/dependencies/CMakeLists.txt, tools/wheel/image/dependencies/projects.cmake, tools/wheel/image/dependencies/projects/libjpeg-turbo.cmake
Fixes #17906.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18189)
=> [wheel] Enable mac arm64 wheel builds

math/fast_pose_composition_functions.h, math/fast_pose_composition_functions_avx2_fma.h
The forward declarations of RotationMatrix etc. show up in the index in this header, but that's wrong.
For file with no public symbols, we don't need a user-facing overview.
Buggy version: https://drake.mit.edu/doxygen_cxx/fast__pose__composition__functions__avx2__fma_8h.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18239)
=> [math] Remove stray "fast pose composition" Doxygen details

geometry/meshcat.cc, geometry/meshcat_types.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc
Fixes #17149
Depends on rdeits/meshcat#116 before merging.
THREE.js added native capsule shape support in mrdoob/three.js#23586. This PR adds capsule support to the in process meshcat class and temporarily points to a fork of meshcat with an updated THREE.js version.
cc: @JoseBarreiros-TRI
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17319)
=> [meshcat] Add capsule support

multibody/inverse_kinematics/global_inverse_kinematics.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_reachable_test.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_test.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.h
Assign the pose variables forefront for all bodies, before imposing the kinematic constraint that connect the parent and the child bodies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18206)
=> Fix a bug in GlobalInverseKinematics

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/general_test.py, systems/framework/context.h, systems/framework/context_base.cc, systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/framework_common.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/system.cc, systems/framework/system.h, systems/framework/system_base.h, systems/framework/test/diagram_test.cc, systems/framework/test/leaf_context_test.cc, systems/framework/test/system_test.cc
Per request in #10909, adds a new System API: 
```c++
const DiscreteValues& System::EvalUniquePeriodicDiscreteUpdate(const Context&);
```
that determines what the effect would be if this System's periodic discrete state updates were triggered now (_without_ actually updating the discrete state). It requires that there is a single unique timing for all the periodic discrete updates in the entire Diagram and throws an error if not. The result is returned as a reference to a preallocated cache entry in the Context,
automatically invalidated if anything changes.
In addition, this PR adds a third overload of Context's `SetDiscreteState()` that accepts an entire DiscreteValues object, in case a caller wants to actually update the discrete state from the value returned by the above API.
```c++ …
```
=> Add System::EvalUniquePeriodicDiscreteUpdate()

multibody/meshcat/joint_sliders.h
This also moves the default annotation for this argument to allow the subsequent return annotation to create proper output, at the cost of mangling the pydoc output of this default directive. But at least this is semi-readable and this exact problem exists with default annotations elsewhere in our pydocs and I'm looking into it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18248)
=> Fix a missing paramname

math/BUILD.bazel, tools/cc_toolchain/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/dreal/patches/platforms.patch, tools/workspace/dreal/repository.bzl, tools/workspace/platforms/BUILD.bazel, tools/workspace/platforms/repository.bzl
Bazel 6.0 will remove the built-in copy, requiring users to BYO.
See https://github.com/bazelbuild/bazel/issues/8622 for details and current https://github.com/RobotLocomotion/drake/pull/18246 CI for sample failure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18250)
=> [workspace] Add dependency on bazelbuild/platforms

multibody/parsing/detail_urdf_parser.cc, multibody/parsing/parsing_doxygen.h, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf, multibody/parsing/test/urdf_parser_test/joint_parsing_test_missing_screw_thread_pitch.urdf, multibody/parsing/test/urdf_parser_test/joint_parsing_test_missing_screw_thread_pitch_attribute.urdf
Closes #17765.
This adds support for parsing `screw` joints from URDF using a custom `<drake:joint/>` element. The screw thread pitch is specified with a `value` attribute in a custom `<drake:screw_thread_pitch/>` element. To maintain parity with the SDFormat parsing test, a continuous joint is added to the URDF parsing test to match the changes to the SDFormat test from #17956.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18191)
=> [multibody] Parse screw joints from URDF

tools/lint/library_lint.bzl
Our genquery [scope](https://github.com/RobotLocomotion/drake/blob/b23faa4e542d8cf7ddd4c0abde29893ad1cf41f5/tools/lint/library_lint.bzl#L74-L79) opts-in to the `//foo/bar:bar` library spelling, not the `//foo/bar` abbreviation; this is flagged as an error in Bazel 6.0. Use the `//foo/bar:bar` spelling to avoid the error.
Example failure prior to this PR [here](https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-bazel-experimental-release/190/).
Example success with this PR [here](https://drake-jenkins.csail.mit.edu/job/linux-focal-unprovisioned-gcc-bazel-experimental-release/191/).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18253)
=> [lint] Tidy up genquery input

multibody/parsing/parsing_doxygen.h
It does not use the custom drake:screw_thread_pitch
Minor hotfix for #18191
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18255)
=> parsing_doxygen: Clarify that SDFormat uses screw_thread_pitch

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py, systems/framework/leaf_system.cc, systems/framework/leaf_system.h
Clarifies documentation for DeclareAbstractState(), including argument name (and matching Pydrake kwarg). Improves consistency somewhat among DeclareAbstract{State,Parameter}() and DeclareNumericParameter().
Deprecation conveniently not required because the previous python binding didn't specify a kwarg at all.
Also removes a stale TODO.
Resolves #18065
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18254)
=> Update DeclareAbstractState() doc and py kwarg names

multibody/tree/quaternion_floating_mobilizer.cc
This is a tiny merge request proposed while discovering `QuaternionFloatingMobilizer ` class
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18270)
=> Use const for quaternion used to build math::RigidTransform

tools/workspace/pybind11/libclang_setup.py
Sets the arch-specific path for libclang instead of a blanket `x86_64` path. Relates to #13514
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18264)
=> [tools] Removes pybind (libclang setup) errors on arm64

bindings/pydrake/.clang-format, bindings/pydrake/test/dot_clang_format_test.py
The config file is "last one wins" so pydrake's dotfile should be appending to the root settings, not prepending.
This hasn't mattered in the past because we had not yet overridden any settings in pydrake that were also set in the root; that might be changing soon, so we'll preemptively correct the order here now.
Towards #18175.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18281)
=> [pydrake] Switch the clang-format directives order

multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_deprecated_test.cc, multibody/plant/test/multibody_plant_test.cc, systems/framework/BUILD.bazel, systems/framework/diagram.cc, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/port_base.h, systems/framework/system.cc, systems/framework/system.h, systems/framework/system_base.cc, systems/framework/system_base.h, systems/framework/test/input_port_test.cc, systems/framework/test/leaf_system_deprecation_test.cc
Towards #12214.  This adds the _ability_ to deprecate ports in the first place.
No sugar for renaming input ports is implemented here, so I'll leave the issue open for now.
As a showcase of the feature, this deprecates MultibodyPlant's `continuous_state` port names, in lieu of just `state`.
This PR also adds an attorney for PortBase to de-clutter the public API.
---
When a port is marked as deprecated, the first user-induced attempt to use it within a process will result in a warning printed to the log.
Uses are detected as:
- Obtaining a reference to the InputPort or OutputPort handle (other than at declaration-time), with lookup either by name or index.
Using the handle after lookup does not generate additional warnings.
Note that connecting or exporting subsystem ports during Diagram …
=> [framework] Add the ability to deprecate input and output ports

bindings/pydrake/geometry_py_visualizers.cc, bindings/pydrake/test/geometry_visualizers_test.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat.html, geometry/meshcat_types.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc
The meshcat javascript reads the gamepad info and sends it to the meshcat server whenever a change is detected.  The c++ meshcat interface provides access to the most recent gamepad status.
This feature is provided primarily to support applications where Drake is running on a remote machine (e.g. in the cloud), and the Meshcat javascript in the browser is the only code running on the local machine which has access to the gamepad.
cc @pathammer .  Would love your opinion, too, if you have time.
For background: this feature will support a richer teleop interface for students running on Deepnote.  I have a version that drives around a mobile base with mecanum wheels (from @calderpg-tri) which is incredibly compelling... at least to me!  It's a …
=> [meshcat] Add support for gamepads in Meshcat

setup/ubuntu/binary_distribution/packages-focal.txt, setup/ubuntu/binary_distribution/packages-jammy.txt, setup/ubuntu/source_distribution/install_prereqs.sh
Relates to #13514. Removes `libquadmath0` as a package since it gets pulled in via `libgfortran5` anyway and is redundant. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18261)
=> [setup] Remove errors on Ubuntu arm64

multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/tamsi_driver.cc, multibody/plant/tamsi_driver.h, multibody/plant/test/square_surface.obj, multibody/plant/test/tamsi_driver_test.cc
Towards https://github.com/RobotLocomotion/drake/issues/16955 and https://github.com/RobotLocomotion/drake/issues/13888.
`TamsiDriver` split from the bigger PR #18170 where all of the TAMSI code in `MultibodyPlant` is moved into the `TamsiDriver`. 
Most of the code in `TamsiDriver` introduced in this PR is simply a copy from already tested `MultibodyPlant` code.
A simple unit test verifies we can properly use the `TamsiDriver`, though as soon as #18170, all of the MultibodyPlant unit tests using TAMSI will go through `TamsiDriver`, effectively adding more coverage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18265)
=> Implements TamsiDriver

solvers/aggregate_costs_constraints.cc, solvers/aggregate_costs_constraints.h, solvers/mosek_solver_internal.cc, solvers/mosek_solver_internal.h, solvers/test/aggregate_costs_constraints_test.cc, solvers/test/linear_program_examples.cc, solvers/test/linear_program_examples.h, solvers/test/mosek_solver_test.cc
This fixes duplicated variables in linear and conic constraints in Mosek.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18280)
=> MosekSolver aggregates duplicated variables in constraints.

tools/workspace/usockets/repository.bzl, tools/workspace/uwebsockets/repository.bzl
Reverts RobotLocomotion/drake#18259.  Re-opens #17910.
We have some evidence that a Docker image using this commit will not work with the Nginx proxy server we use for our Deepnote tutorials, yielding a "Bad Gateway" error message instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18289)
=> Revert "[workspace] Upgrade usockets and uwebsockets"

bindings/pydrake/visualization/_model_visualizer.py, bindings/pydrake/visualization/model_visualizer.py, bindings/pydrake/visualization/test/model_visualizer_test.py
Due to our C++ roots, Drake's prevailing style is getters rather than properties. Withdraw the kwarg-argparse properties from public API.
When asked for a Meshcat object, create one on demand instead of barfing. Also use StartMeshcat instead of Meshcat so that it works in Deepnote.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18288)
=> [visualization] Eschew ModelVisualizer use of properties

bindings/pydrake/trajectories_py.cc
The function takes its arguments by reference and internally copies them. There's no need to any keep_alive annotations.
Amends #17816.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18301)
=> [pydrake] Remove spurous keep-alive annotations

.github/ISSUE_TEMPLATE/BUG.yml, CMakeLists.txt, doc/_pages/code_review_checklist.md, doc/_pages/from_source.md, doc/_pages/installation.md, doc/_pages/jenkins.md, doc/_pages/pip.md, doc/_pages/release_playbook.md, examples/manipulation_station/end_effector_teleop_sliders.py, tools/release_engineering/download_release_candidate.py, tools/workspace/cc/repository.bzl, tools/workspace/os.bzl
Fixes #18294.
- Minimum supported macOS is now: Monterey.
- Minimum supported Xcode is now: 14.0.1.
- CMake will warn (rather than error) on unsupported macOS.
- Advertise existing macOS arm64 wheels (monterey and later).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18299)
=> [workspace] Drop macOS Big Sur support

tools/workspace/pybind11/repository.bzl
Relates: https://github.com/RobotLocomotion/pybind11/pull/60, #18262.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18297)
=> [workspace] Update pybind11 to include python@3.11 patches

bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py, multibody/benchmarks/acrobot/double_pendulum.urdf, systems/controllers/BUILD.bazel, systems/controllers/inverse_dynamics.cc, systems/controllers/inverse_dynamics.h, systems/controllers/inverse_dynamics_controller.h, systems/controllers/joint_stiffness_controller.cc, systems/controllers/joint_stiffness_controller.h, systems/controllers/test/inverse_dynamics_controller_test.cc, systems/controllers/test/inverse_dynamics_test.cc, systems/controllers/test/joint_stiffness_controller_test.cc
Towards #11955.
This is almost certainly a better model for the iiwa controller than the InverseDynamicsController model that we've been using forever.
+@EricCousineau-TRI for feature review, please?
cc @pangtao22 -- PTAL if you have a chance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18272)
=> [controllers] Implements JointStiffnessController

bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py
Doing this in service of making #18315 a bit easier to wrangle for Python bindings
This does not change functionality aside from ensuring scopes, attributes, and kwargs are reflected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18316)
=> [py controllers] Use `using Class` conventions

solvers/test/csdp_solver_test.cc, solvers/test/gurobi_solver_test.cc, solvers/test/linear_program_examples.cc, solvers/test/linear_program_examples.h, solvers/test/mosek_solver_test.cc, solvers/test/second_order_cone_program_examples.cc, solvers/test/second_order_cone_program_examples.h
CsdpSolver already handles duplicated variables.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18320)
=> Add test to csdp_solver_test on duplicated variables in constraints.

common/trajectories/piecewise_polynomial.h
I think this method was meant to be deprecated before; the name was changed way back in #12939. There are no tests, no uses, and no python bindings. Here we're simply marking it for removal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18319)
=> [trajectories] Deprecate PiecewisePolynomial::Cubic

geometry/optimization/test/graph_of_convex_sets_test.cc
Mosek has been failing on this test for me for weeks on my standard focal install, with mosek installed via bazel.
The big mystery for me has been "why is my setup any different?"  I still don't have a good answer. But there is certainly no great loss in adjusting this tolerance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18313)
=> [graph of convex sets] adjust test tolerance on rounding test

solvers/test/scs_solver_test.cc
ScsSolver already handles duplicated variables. This PR just adds test to confirm it.
Discussed in #18275
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18318)
=> Test ScsSolver with duplicate variables

tutorials/authoring_multibody_simulation.ipynb
Remove the old model_inspector function and replace with ModelVisualizer. Switch one example to use a model in a string buffer to demonstrate using parser methods. Rewrite surrouding prose to support the new usage and also for clarity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18249)
=> Simplify the authoring_multibody_simulation tutorial

systems/framework/system.h
This was deprecated in #18106. However, due to the long review cycle, the date on this one method slipped through the cracks when the other deprecations got updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18326)
=> [framework] Update deprecation date

bindings/pydrake/systems/pyplot_visualizer.py
In some deeply nested import situations, importing matplotlib.animation will hang a backgrounded Python program because it's reading from stderr. Deferring the import solves the issue. Resolves #18323.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18324)
=> defer import of matplotlib.animation in pyplot_visualizer

multibody/parsing/BUILD.bazel, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/box_package/mjcfs/box.xml, multibody/parsing/test/detail_mujoco_parser_test.cc
This contains #18312 as its first commit.
- All files under `drake/geometry` belong to #18312 
- All files under `drake/multibody` belong solely to this PR and need review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18317)
=> [parsing] Implements basic material and mesh support in MuJoCo parser

bindings/pydrake/visualization/_video.py, bindings/pydrake/visualization/test/video_test.py, setup/ubuntu/binary_distribution/packages-jammy.txt, setup/ubuntu/source_distribution/packages-jammy.txt, tools/workspace/vtk/build_binaries_with_docker, tools/workspace/vtk/repository.bzl
This change all builds on Jammy except for wheel builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18340)
=> [workspace] Use host OS VTK 9.1 when on Ubuntu 22.04

bindings/pydrake/systems/test/controllers_test.py, multibody/plant/test/multibody_plant_deprecated_test.cc, systems/controllers/test/inverse_dynamics_controller_test.cc, systems/controllers/test/inverse_dynamics_test.cc, systems/controllers/test/joint_stiffness_controller_test.cc
Port some more parser call sites to AddModels. These just escaped detection in prior passes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18343)
=> [parsing] Port to parser.AddModels, part 3

multibody/plant/BUILD.bazel, multibody/plant/deformable_model.cc, multibody/plant/deformable_model.h, multibody/plant/test/deformable_boundary_condition_test.cc, multibody/plant/test/deformable_model_test.cc
Add SetWallBoundaryCondition function to DeformableModel that allows putting deformable vertices whose reference positions land inside the prescribed half space under zero Dirichlet boundary condition.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18290)
=> Set wall boundary condition for deformable bodies

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
This also adds previously missing tests on those bindings.
Adds the following bindings:
drake.multibody.tree.UnitInertia.SolidEllipsoid
drake.multibody.tree.UnitInertia.SolidCapsule
resolves #18337
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18341)
=> [pydrake] Add missing bindings to UnitInertia

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/custom_test.py
Using proper workflow allows users to avoid spurious cache invalidation by exposing the proper way to get immutable access with proper updates
- Switch test to use `SimpleNamespace` to make it easier to check aliasing and mutation (int is an immutable type)
- Change style to use `allocate=model_value.Clone`
- Add test for const access. Not the best workflow, but establishes symmetry
Follow-up expanding on #15983
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18354)
=> [py framework] Bind CacheEntry.Eval for better workflow

doc/_release-notes/v1.10.0.md
Per https://github.com/RobotLocomotion/drake/pull/18263#issuecomment-1329143513
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18369)
=> [doc] Fix missing date substitution for release v1.10.0

solvers/mosek_solver_internal.h, solvers/test/mosek_solver_test.cc, solvers/test/second_order_cone_program_examples.cc, solvers/test/second_order_cone_program_examples.h
The Mosek definition of rotated Lorentz cone is different from Drake's definition by a factor of two. Hence we also need to scale the first entry of the dual solution by a factor of 1/2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18361)
=> Change the returned dual solution for rotated Lorentz cone constraint in MosekSolver

common/BUILD.bazel, common/test/scalar_casting_test.cc
I always forget this stuff, and didn't see centralized docs for it for at least C++ (from brief search).
Relates #18170
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18339)
=> [common] Add simple scalar_casting_test

bindings/pydrake/geometry_py_scene_graph.cc, bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/all.py, bindings/pydrake/multibody/fem_py.cc, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/test/geometry_scene_graph_test.py, multibody/plant/compliant_contact_manager.cc, multibody/plant/deformable_model.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_model_attorney.h, multibody/plant/physical_model.cc, multibody/plant/physical_model.h, multibody/plant/test/discrete_update_manager_test.cc, multibody/plant/test/multibody_plant_scalar_conversion_test.cc
This includes:
1. binding DeformableModel itself with a selection of functions;
2. binding SceneGraph::get_source_configuration_port()
3. binding MultibodyPlant::AddPhysicalModel which takes PhysicalModel as a parameter. As a result, PhysicalModel is moved out of internal namespace and bindings are provided.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18310)
=> [bindings] Bind DeformableModel and related functions

geometry/optimization/BUILD.bazel, geometry/optimization/iris.cc, geometry/optimization/test/iris_in_configuration_space_test.cc
IrisInConfigurationSpace now supports convex meshes via VPolytope.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18376)
=> [geometry/optimization] Add Iris support for Convex mesh geometries

tools/wheel/macos/build-wheel.sh, tools/wheel/macos/provision-test-python.sh
The `python3` executable may come from a different `brew` python or from Xcode, make sure to use the drake-supported python version by hard-coding paths to `brew --prefix python@3.10`.
Extracted from #18262, active image updates on the macOS CI front need this change escalated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18381)
=> [wheel] Use the correct python version in macOS wheel build

common/trajectories/bspline_trajectory.cc, common/trajectories/test/bspline_trajectory_test.cc
The BSplineTrajectory::value() method clamps the time to the trajectory time interval, but the EvalDerivative implementation did not. Instead it threw an error.  This PR makes the behavior consistent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18383)
=> [trajectories] BSplineTrajectory::EvalDerivative now clamps time.

multibody/tree/body.h, multibody/tree/joint.h, multibody/tree/mobilizer.h, multibody/tree/multibody_tree.h, multibody/tree/multibody_tree_system.cc
Towards #14949 and part of #18258.
This is an intermediate PR that consolidates the context parameter that handles joint/body locking in the underlying mobilizer. Once all of #18258 lands, free body APIs and `QuaternionFloatingJoint` APIs for all free bodies will affect the same underlying body. In order for joint/body locking to work correctly and communicate lock/unlock status between these redundant APIs, we move the lock parameter to the underlying mobilizer. Therefore if a user was to lock a body with `Body::Lock()` and then query the parent joint of that body with `Joint::is_locked()` it would return `true` and vice versa with `Joint::Lock()` and `Body::is_locked()` for the child body of the joint.
Since this is just changing an underlying implementation no additional tests are …
=> Move joint locking parameter to mobilizer

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/tree/BUILD.bazel, multibody/tree/geometry_spatial_inertia.cc, multibody/tree/geometry_spatial_inertia.h, multibody/tree/rotational_inertia.h, multibody/tree/test/geometry_spatial_inertia_test.cc
Provides a utility in `drake::multibody` to compute `SpatialInertia` from `geometry::Shape` and `geometry::TriangleSurfaceMesh`.
Incidental opportunistic clean up of typos encountered along the way.
Relates #18314.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18345)
=> Calculate SpatialInertia from Shape and TriangleMesh

multibody/plant/contact_properties.cc
Using "use `GetProperty<double>`" per #18396, as the contract seemed insufficiently tested
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18397)
=> [contact_properties] Use GetProperty<double>, not GetProperty<T>

multibody/tree/test/geometry_spatial_inertia_test.cc
Prior tolerance was 4.4408920985006262e-16
Testing failed on mac-arm with diff of 4x prior tolerance (1.7763568394002505e-15)
Follow-up to #18345
Per @svenevs's Drake Slack post:
https://drakedevelopers.slack.com/archives/C270MN28G/p1670023472277669
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18395)
=> [geometry_spatial_inertia] Increase tolerance for mass check

manipulation/models/allegro_hand_description/test/parse_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/kuka_iiwa_model_tests.h, multibody/plant/test/multibody_plant_forward_dynamics_test.cc, multibody/plant/test/multibody_plant_jacobians_test.cc, multibody/plant/test/multibody_plant_mass_matrix_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h
Towards #14949 and part of #18258.
- Creates a `QuaternionFloatingJoint` at finalize time for every free body in the tree.
This creates a small breaking change: MbP::num_joints() will change in all existing
plants that had previously declared at least one free body. 
- Explicitly declares `is_floating` to mean: is mobilized by a 6-dof mobilzer AND parent body of the mobilizer is world
(this was only implicitly true before)
- Fixes all of the tests to deal with the breaking change.
This PR depends on the small behavior change from #18389 and will be rebased off of that branch. The changes to `body.h`, `joint.h` and `mobilizer.h` (all in the first commit) can be ignored. All of the relevant changes are in the second commit.
- - - …
=> [multibody] Add joint for each free body

tools/wheel/macos/build-wheel.sh, tools/wheel/wheel_builder/macos.py
Xcode may arbitrarily change the default MACOSX_DEPLOYMENT_TARGET meaning that the final artifact may be for a newer macOS than the one building the wheel.  To avoid this, set the relevant environment variables and command line flags for all tools involved.
This first surfaced during a [CI update that included bumping Xcode from 14.0.1 to 14.1](https://drakedevelopers.slack.com/archives/C270MN28G/p1669900240408939).  Current CI is using 14.0.1, this fix should pass the related wheel builds with the same results.  I am also doing a full wheel rebuild locally on a macmini with Xcode 14.1 to confirm (ETA 1hr).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18408)
=> [wheel] Set macOS deployment target explicitly

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/tree/BUILD.bazel, multibody/tree/prismatic_spring.cc, multibody/tree/prismatic_spring.h, multibody/tree/test/prismatic_spring_test.cc
Following up with the conversation in the developer slack channel: https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1659970165050719
I am creating this draft PR to support springs on prismatic joints and the associated SDF parsing, for use cases such as _linear Series Elastic Actuators_, _spring-loaded foot for quadrupeds_, _spring-loaded air pistons_, etc.
With this effort, we can parse a joint in SDF similar to this:
```
<joint name="prismatic_joint" type="prismatic">
...
<axis>
...
<dynamics>
<spring_reference>0.1</spring_reference>
<spring_stiffness>1000</spring_stiffness>
</dynamics>
</axis>
</joint>
```
Here are some FAQs for this implementation:
* Q: Why bother creating a new `PrismaticSpring` class instead of using `LinearSpringDamper` and adding its SDF parsing …
=> Add PrismaticSpring and its SDF parsing

multibody/contact_solvers/sap/sap_holonomic_constraint.cc, multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc
Fixed bug for infinitely stiff SAP holonomic constraints.
Follow up to discussion started by @SeanCurtis-TRI in #18196.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18414)
=> Bug fix for SAP holonomic constraints with infinite stiffness

multibody/plant/BUILD.bazel, multibody/plant/constraint_specs.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/sap_driver.h, multibody/plant/test/sap_driver_distance_constraints_test.cc
Implements support for distance constraints when using the SAP solver.
With this PR the user can set a distance constraint with the call to `MultibodyPlant::AddDistanceConstraint()`.
cc'ing @mposa 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18196)
=> Implements support for distance constraints with SAP

bindings/pydrake/visualization/_model_visualizer.py
Also change the message that ModelVisualizer prints so that it is accurate when running in a notebook, under the theory that someone running the script from the command line will understand that they can also press Ctrl-C to quit. This brings this script more into line with JointSliders::Run.
Fixes #18348
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18411)
=> Allow pressing Escape to stop ModelVisualizer

tools/wheel/wheel_builder/linux.py
Fix naming of container image used to test wheels when not tagging stages to use a properly scoped name rather than a name with no scope. Always generate a unique identifier, so that when tagging stages, the temporary image name uses the unique identifier rather than `None`.
+@svenevs for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18426)
=> Fix docker naming issues with the wheel builder

geometry/optimization/iris.cc
Fixes a bug where `MakeGuessFeasible` returns a point outside the region causing the Hit and Run sampling algorithm to fail during IRIS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18439)
=> [geometry/optimization] Fix Iris Hit and Run failure bug

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/primitives/test/trajectory_source_test.cc, systems/primitives/trajectory_source.cc, systems/primitives/trajectory_source.h
I've seen a number of examples where a user wants to construct a Diagram in order to compute quantities for planning, then execute the planned trajectory using a TrajectorySource. This caused a chicken-and-the-egg problem -- they couldn't produce the final diagram until they had the trajectory but couldn't produce the trajectory until they had the Diagram. Constructing a completely different Diagram for the planning felt too cumbersome.
With the addition in this PR, a user can set up the Diagram with a placeholder trajectory that only needs to be the right size, then set the trajectory after the Diagram is built.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/1843 …
=> [primitives] Add TrajectorySource::UpdateTrajectory

bindings/pydrake/test/geometry_visualizers_test.py, geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer.h, geometry/meshcat_visualizer_params.h, geometry/test/meshcat_visualizer_test.cc, manipulation/models/ycb/test/parse_test.cc, visualization/test/visualization_config_functions_test.cc, visualization/visualization_config.h, visualization/visualization_config_functions.cc
Adds sliders to control geometry alpha to MeshcatVisualizer, as well as a config option to disable them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18454)
=> [visualization] Add sliders for geometry alpha in MeshcatVisualizer

multibody/tree/body.h, multibody/tree/body_node.h, multibody/tree/force_element.h, multibody/tree/frame_base.h, multibody/tree/joint.h, multibody/tree/joint_actuator.cc, multibody/tree/joint_actuator.h, multibody/tree/mobilizer.h, multibody/tree/model_instance.h, multibody/tree/multibody_element.h, multibody/tree/multibody_tree_system.h, multibody/tree/test/multibody_tree_creation_test.cc
For some reason lost to history the internal class MultibodyElement used a CRTP pattern yet never actually referenced the recursive template at all. This PR removes that parameter and hopefully some unnecessary confusion along with it.
**Release note**: this is technically a breaking change since MultibodyElement is the non-internal base class for all the elements, both internal and visible. However it is very unlikely that anyone is referencing the base class directly. If they are, they'll have to make the same (easy) change to their code also.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18460)
=> Remove unneeded CRTP parameter from MultibodyElement

doc/_pages/pip.md, doc/_pages/release_playbook.md, tools/release_engineering/download_release_candidate.py, tools/wheel/image/provision-python.sh, tools/wheel/wheel_builder/linux.py, tools/workspace/python/repository.bzl
Also build a Linux wheel against Python 3.11. Like 3.10, this uses Python built from source. Update relevant release-playbook documentation and script.
Fixes #18417.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18468)
=> Add Linux Python 3.11 wheel

planning/body_shape_description.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18472)
=> [planning] Restore move semantics to BodyShapeDescription

bindings/pydrake/geometry_py_scene_graph.cc, bindings/pydrake/test/geometry_scene_graph_test.py, examples/scene_graph/solar_system.cc, geometry/geometry_state.h, geometry/query_object.h, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/scene_graph_inspector.cc, geometry/scene_graph_inspector.h, geometry/test/geometry_state_test.cc, geometry/test/scene_graph_inspector_test.cc, geometry/test/scene_graph_test.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
Users have the ability to register a geometry in a fixed pose relative to another geometry. Ultimately, it has a fixed pose relative the common geometry::Frame. This extra layer has not proved to be useful and the concept of "parent vs frame" has only caused confusion.
This deprecates the limited public API in preparation for removing all of the supporting internal code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18448)
=> Deprecate "register w.r.t. geometry" SceneGraph APIs

geometry/render_gl/internal_shape_meshes.cc, geometry/render_gl/internal_shape_meshes.h, geometry/render_gl/test/internal_shape_meshes_test.cc, tools/workspace/tinyobjloader/repository.bzl
From investigating, [this commit](https://github.com/tinyobjloader/tinyobjloader/commit/f026a1e0b86979cb5a7d7f6f2432d02590e61dc9) from `tinyobjloader` allowed normal and texture indices to be zero, and that caused the original test to fail.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18479)
=> Upgrade tinyobjloader to the latest commit and fix tests

bindings/pydrake/visualization/_model_visualizer.py
Since the alpha sliders introduced by #18469 are optional, opt the ModelVisualizer class into showing them, in the spirit of the original request in #17688.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18481)
=> [visualization] Enable alpha sliders in ModelVisualizer

geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/test/cspace_free_polytope_test.cc
Based on Calder's suggestion to continue the while loop when one of the thread fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18482)
=> [C-IRIS] fix tsan problem with multiple threads.

multibody/inverse_kinematics/minimum_distance_constraint.cc, multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc, multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.h, multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc
The original code is correct, but the check on `signed_distance_pair.distance < influence_distance` is redundant because `signed_distance_pairs` is computed with `max_distance = influence_distance`. https://github.com/RobotLocomotion/drake/blob/4443764321ac2dcad19fc796b5ce685916b045c1/multibody/inverse_kinematics/minimum_distance_constraint.cc#L33-L35
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18459)
This was motivated by the stack overflow question https://stackoverflow.com/questions/74793241/multiple-minimumdistanceconstraint-constraints
=> Remove a redundant check on the signed_distance < influence_distance in MinimumDistanceConstraint.

bindings/pydrake/common/test/numpy_compare_test.py, bindings/pydrake/forwarddiff.py, bindings/pydrake/test/autodiffutils_test.py, common/proto/call_python_client.py, tools/workspace/drake_visualizer/_drake_visualizer_builtin_scripts/show_hydroelastic_contact.py
In NumPy 1.24.0, deprecated aliases `np.object`, `np.bool`, `np.float` and `np.int` are no longer supported. Replace aliases with the equivalent builtin types.
When Homebrew updated to NumPy 1.24.0, Mac unprovisioned jobs to failed due to this change, e.g.
- [mac-x86-monterey-unprovisioned-clang-bazel-nightly-release](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-x86-monterey-unprovisioned-clang-bazel-nightly-release/39/) 
- [mac-arm-monterey-unprovisioned-clang-bazel-nightly-release](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-arm-monterey-unprovisioned-clang-bazel-nightly-release/)
NumPy 1.24.0 release notes: https://numpy.org/devdocs/release/1.24.0-notes.html
Deprecation: https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-alia …
=> Replace unsupported NumPy aliases

bindings/pydrake/visualization/_model_visualizer.py, bindings/pydrake/visualization/model_visualizer.py
Adds a Reload Model File button to the ModelVisualizer control panel to allow live model editing and re-visualization. Also improves error feedback when the number of position arguments does not match that in the model, and normalizes some docstring style.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18488)
=> Enable manual model reloading in ModelVisualizer

geometry/optimization/dev/collision_geometry.cc, geometry/optimization/dev/collision_geometry.h, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/test/collision_geometry_test.cc, geometry/optimization/dev/test/cspace_free_polytope_test.cc
1. When the geometry on the other side of the plane is not a polytope, then we can't use a'*x+b>=1 formulation for the polytope geometry, instead we should use the one with the Chebyshev center.
2. Add a'*p_AC+b >= 0.5r where C is the chebyshev center to the formulation to prevent trivial solution a = 0, b=0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18494)
=> [C-IRIS] Fix a problem when generating rationals for polytope on one side of plane

geometry/optimization/dev/collision_geometry.cc, geometry/optimization/dev/collision_geometry.h, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/test/collision_geometry_test.cc, geometry/optimization/dev/test/cspace_free_polytope_test.cc
If I were to use the formulation that doesn't introduce Chebyshev, namely a'*x + b >= 1, then this causes problem in the bilinear iteration. Since when we search for the separating margin, we use the formulation a'*x + b - margin - lambda(s) * (d - C*s) is sos. Then in the next iteration when we search for C and d, we don't need the margin and use the formulation a'*x + b - 1 - lambda(s) * (d-C*s) is sos. This causes the problem that the solution a, b, lambda in the first iteration with margin is NOT a feasible solution for the next iteration when we search for C and d but fix lambda(s) (as very likely the margin is < 1).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/d …
=> [C-IRIS] Consolidate to the formulation using Chebyshev center for polytope

geometry/optimization/dev/collision_geometry.h, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/cspace_free_polytope_test.cc
1. When we search for the polytope C*s<=d, oftencases the bounds s_lower <= s <= s_upper is redundant, and searching for its Lagrangian multiplier doesn't affect the C-space polytope. But searching for its Lagrangian multiplier greatly increases the size of the SOS problem since for each rational function we will introduce 2 * s_size sos polynomials for Lagrangian multiplier. Hence we add the option to fix the Lagrangian multipliers for s_lower <= s <= s_upper.
2. Add the option to search the Lagrangian multiplier for the redundant rows in C. I found that in the bilinear alternation, if I always ignore the Lagrangian multiplier for a row in C*s<=d, then that row often ends up as 0 * s <= some_positive_number, which is always redundant in the future iterations. So I add the option to still …
=> [C-IRIS] fix Lagrangian for s_lower <= s <= s_upper.

solvers/test/ipopt_solver_test.cc, solvers/test/nonlinear_program_test.cc
IPOPT already handles variable duplication through its sparse matrix format. So I only need to add test to confirm it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18503)
=> [solvers] Add test with ipopt for problem costs/constraints containing duplicated variables.

multibody/plant/multibody_plant.h, multibody/tree/multibody_tree.h
Removes deprecation documentation and implements the promised behavior of throwing pre-Finalize() for MultibodyPlant::
- num_positions()
- num_velocities()
- num_multibody_states()
Resolves #18511
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18515)
=> [multibody] Require finalize before state counts are available

planning/body_shape_description.h, planning/test/body_shape_description_test.cc
BodyShapeDescription is a serialization helper, not an inner-loop class. When the user attempts to fetch a name from a moved-from object, we should fail immediately rather than allow them to bash on with an empty string.
See `anzu/pull/9094#pullrequestreview-31230` for rationale.
Amends #18424 and #18472.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18521)
=> [planning] BodyShapeDescription fails fast upon mis-use

multibody/tree/BUILD.bazel, multibody/tree/joint.h, multibody/tree/multibody_element.cc, multibody/tree/multibody_element.h
The `MultibodyElement` header depends on `MultibodyTree`, so should be part of the main library, instead of pretending to be usable in isolation. This will allow for it to have a `*.cc` file down the road.
The `JointImplementBuilder` is a Tree--Joint interface so should not pollute `MultibodyElement`.
I noticed this while reading #18460.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18522)
=> [multibody] Repair some physical dependency defects in MbT

tools/install/bazel/test/drake_bazel_installed_test.py, tools/workspace/rules_python/repository.bzl
Not expected to pass tests (causes `//:py/install_test` to fail). Needs investigation (@jwnimmer-tri ?). Should be locally reproducible; unfortunately, all CI reports for that test is to see a more detailed log.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18524)
=> [workspace] Upgrade rules_python to latest release 0.16.1

systems/framework/test/input_port_test.cc
Adds a missing unit test to verify that repeated calls to FixValue() on an input port properly invalidate cache entries that are dependent just on that port.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18501)
=> Add unit test for input_port.FixValue() cache invalidation

tools/workspace/README.md
Modify the semi-automated monthly upgrades to request that failed upgrades create a WIP PR showing the failure, rather than an issue.
+@jwnimmer-tri for feature review, please. (Although this is just your suggestion, verbatim; I'll claim that between the two of us, feature review is covered.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18517)
=> Request WIP PRs on failed external upgrades

tools/workspace/mypy_internal/patches/timeout.patch, tools/workspace/mypy_internal/repository.bzl
For now, we'll just bump the timeout and see if that is enough for CI be happy.  If not, possibly the process is stuck forever instead of just slow.
See also https://github.com/RobotLocomotion/drake/pull/17552 and https://github.com/python/mypy/pull/13109 for prior failed attempt (increasing from 5s to 30s).
Closes #18119.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18527)
=> Increase mypy timeout for glacial CI machines

tools/workspace/doxygen/repository.bzl
The Doxygen binary runs on Ubuntu 22 without errors.
Towards #18507.
(Prior to switching CI to use Ubuntu 22, we still need to check that it's output has no regressions on the new platform.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18528)
=> [doc] Enable Doxygen builds on Ubuntu 22.04

tools/workspace/gym_py/README.md, tools/workspace/new_release.py
* See tools/workspace/gym_py/README.md for details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18534)
=> Mark `gym_py` as not to be upgraded.

geometry/BUILD.bazel, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/internal_geometry.h, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/geometry_state_test.cc, geometry/test/internal_geometry_test.cc, geometry/test/scene_graph_test.cc
In addition to changing things like collision filters or geometry properties after registration, now the `Shape` associated with a geometry instance can also be changed.
This is *especially* useful if a user wants to change a body in an existing plant. They can change the mass properties via MbP's mass "parameters" and change the geometric representation in `SceneGraph` to match.
The new shape is associated with the original `GeometryId`, making it friendly to MbP's internals.
This required some refactoring of the `GeometryState` code that controls the registration/removal of geometry with respect to the proximity and render engines.
- - - …
=> SceneGraph allows changing geometry shape

multibody/tree/body.h, multibody/tree/body_node.h, multibody/tree/force_element.h, multibody/tree/frame_base.h, multibody/tree/joint.h, multibody/tree/joint_actuator.cc, multibody/tree/joint_actuator.h, multibody/tree/mobilizer.h, multibody/tree/model_instance.h, multibody/tree/multibody_element.cc, multibody/tree/multibody_element.h, multibody/tree/multibody_tree_system.h, multibody/tree/test/multibody_tree_creation_test.cc
This allows us to to move a bunch of function definitions into the cc file, which is Drake style.
I noticed this while reading #18460. (Since we already did one breaking change to the template list in that PR, I think it makes sense to try to get this change into the next release as well, so there's effectively only one break.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18526)
=> [multibody] Remove MultibodyElement's second template argument

tools/workspace/conex/patches/debug_macros.patch, tools/workspace/conex/repository.bzl
At the bottom of [conex/debug_macros.h](https://github.com/ToyotaResearchInstitute/conex/blob/main/conex/debug_macros.h), we see a use of `std::array` without a matching `#include` atop the file.
See also https://github.com/ToyotaResearchInstitute/conex/pull/3.
My repro on Jammy was `bazel test --config=clang --compilation_mode=dbg --config=tsan //geometry/optimization:iris_test` but I think most Jammy Clang Debug builds will hit this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18537)
=> [workspace] Fix conex build with modern compilers

CMakeLists.txt
Tweak the CMake front-end to accept an unsupported compiler with a warning, to be consistent with the behavior when using Bazel directly, rather than making this a hard error.
Fixes #17986.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18498)
=> Allow unsupported compilers with warning (CMake)

bindings/pydrake/geometry_py_render.cc, bindings/pydrake/math_py.cc, bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/test/geometry_render_test.py, bindings/pydrake/test/math_test.py
Closes #13987.
`RenderLabel` gets a round-trip `repr()`.
`NumericalGradientOption` lacks a getter function for one of its constructor arguments, so can only provide an incomplete `repr()`.
`SolverOptions` only provides a no-argument constructor, so cannot offer round-trip.  For the purpose of cleaning up our generated documentation, it's sufficient to just hard-code a return value in order to omit the hex address that would otherwise show up in our docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18529)
=> [pydrake] Add __repr__ to several classes

multibody/topology/multibody_graph.cc, multibody/topology/multibody_graph.h
In the member functions of a non-templated class, we must see definitions for all the classes used as member fields prior to defining the member functions that interact with them.
To break the cyclic dependency, move several function definitions to the cc file.
My repro on Jammy was `bazel test --config=clang --compilation_mode=dbg --config=tsan //geometry/optimization:iris_test` but I think most Jammy Clang Debug builds will hit this.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18538)
=> [multibody] Fix misuse of forward-declared classes

setup/ubuntu/binary_distribution/packages-jammy.txt, setup/ubuntu/source_distribution/packages-jammy.txt
Drake by default should stick with the Ubuntu default BLAS (Netlib). Users are invited to install a custom BLAS, but we shouldn't force it.
Through a chain of calamities in upstream Ubuntu 22.04 packaging, Drake's `binary_distribution` dependency on `python3-matplotlib` leads to the dependency chain of:
```
python3-matplotlib =>
python3-fonttools =>
python3-scipy | python3-munkres
```
with
```
python3-scipy =>
python3-pythran =>
libopenblas-dev | ... | libblas.so
```
This ends up installing the OpenBLAS dev package, trumping our `source_distribution` dependency preference for `libblas-dev` that comes along in the second install command.
Work around this problem by elevating Drake's BLAS dev package dependency from a source dep to a binary dep, which is able to guide `python3-pythran`'s …
=> [setup] Avoid accidentally installing OpenBLAS

bindings/pydrake/geometry_py_common.cc, bindings/pydrake/test/geometry_common_test.py, geometry/shape_specification.cc, geometry/shape_specification.h, geometry/test/shape_specification_test.cc, geometry/test/shape_to_string_test.cc, multibody/parsing/test/detail_sdf_geometry_test.cc, multibody/tree/test/geometry_spatial_inertia_test.cc
* Release engineer:  This changes an incorrect parameter name, deprecating the old kwarg in pydrake.
* The absolute path requirement was documented but never checked.
* Much code used relative paths, to unspecified effect.
* Remove the absolute path requirement; if path is relative, resolve it immediately wrt the cwd.
* Deprecate the old parameter name in the bindings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18536)
=> Remove unenforced "absolute path" requirement; resolve relpaths

tools/dynamic_analysis/valgrind.supp
The test `solvers/mosek_solver_internal_test` is currently failing under Valgrind on Jammy.  To speed our migration to Jammy, Valgrind has been disabled for this test.
This change fixes one of the issues listed in https://github.com/RobotLocomotion/drake/issues/18091.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18539)
=> Suppress Valgrind false positive in mosek_solver_internal_test

bindings/pydrake/solvers/solvers_py_nlopt.cc, bindings/pydrake/solvers/test/nlopt_solver_test.py, solvers/nlopt_solver.cc, solvers/nlopt_solver.h, solvers/nlopt_solver_common.cc, solvers/solver_options.h, solvers/test/nlopt_solver_test.cc
Call SolverOptions::SetOption(NloptSolver::id(), algorithm, ALGORITHM_NAME_STRING) to set the algorithm.
Requested by the stackoverflow question https://stackoverflow.com/questions/74972952/pydrake-nlopt-method-selection
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18535)
=> NloptSolver supports setting algorithm

bindings/pydrake/test/all_test.py
Test that specific disallowed modules are not imported by `pydrake.all`, i.e. that they're specifically imported by the functions that require them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18544)
=> Add test for disallowed top-level imports

tools/workspace/default.bzl, tools/workspace/googlebenchmark/repository.bzl, tools/workspace/libpfm/BUILD.bazel, tools/workspace/libpfm/package.BUILD.bazel, tools/workspace/libpfm/repository.bzl
Closes #18435.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18457)
=> [workspace] Upgrade googlebenchmark to v1.7.1

common/BUILD.bazel, perception/BUILD.bazel, tools/skylark/README.md, tools/skylark/drake_cc.bzl, tools/skylark/drake_py.bzl, tools/skylark/kwargs.bzl
Tests that do not opt-in to concurrency will be limited to 1 thread.
---
Reviewable r1 contains code copied from Anzu; r2 and onward contain Drake's integration changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18546)
=> [skylark] Set num_threads for test concurrency control

doc/pydrake/_static/css/custom.css
We need to override more of the main style sheet to keep things red.
Towards #18552.
+@SeanCurtis-TRI for both reviews per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18557)
=> [doc] Fix pydrake custom stylesheet for Sphinx on Jammy

CMakeLists.txt, cmake/modules/FindGurobi.cmake, doc/_pages/bazel.md, doc/_pages/python_bindings.md, tools/workspace/gurobi/package-macos.BUILD.bazel.in, tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in, tools/workspace/gurobi/repository.bzl
Remove logic that limits Gurobi to 9.5.1, in order to support 9.5.x at any patch version. Update documentation accordingly.
Towards #14157.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18464)
=> Support Gurobi 9.5.x

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/test/yaml_test.py, bindings/pydrake/common/test/yaml_typed_test.py, bindings/pydrake/common/yaml.py, common/yaml/test/example_structs.h, common/yaml/test/yaml_read_archive_test.cc
Towards #18566 (and therefore #17112).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18564)
=> [pydrake] Begin adding typed (i.e., schema-based) YAML loading

tools/workspace/gurobi/repository.bzl
Remove unnecessary `realpath` in Gurobi's _find_latest helper. Apparently, the only way to get a string from a Bazel `path` object is... to use `str()` on it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18576)
=> Simplify Gurobi _find_latest

multibody/parsing/detail_mujoco_parser.h, multibody/parsing/detail_parsing_workspace.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_sdf_parser.h, multibody/parsing/detail_urdf_parser.h, multibody/parsing/test/detail_sdf_parser_test.cc
This is part of a long campaign to modernize Parser APIs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18550)
=> [parsing] Implement parent model name for Sdformat

tools/workspace/pybind11/pybind_coverage_xml_parser.py
~Partially resolves~ Towards https://github.com/RobotLocomotion/drake/issues/17933.
This PR fixes the Pandas-related console spam which is currently appearing on macOS.  This PR only fixes the source of the existing spam and makes no attempt to suppress similar spam.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18573)
=> Reduce macOS console spam

doc/_pages/documentation_instructions.md, doc/_pages/release_playbook.md
This PR updates the relevant pages in the documentation to properly indicate that only Ubuntu 22.04 Jammy is officially supported when generating the documentation site.
Partially resolves https://github.com/RobotLocomotion/drake/issues/18552.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18574)
=> Update documentation to reflect switch to Jammy for documentation site

doc/_pages/pip.md
Remove text about Ubuntu prerequisites, per the TODO.
Remove macOS arm64 disclaimers.
Unify the pip command line examples (the 2nd was missing "activate").
Follow-up from #18443.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18565)
=> [doc] Tidy up pip-related instructions

planning/BUILD.bazel, planning/collision_checker.cc, planning/collision_checker.h, planning/edge_measure.h, planning/test/collision_checker_test.cc, planning/test/unimplemented_collision_checker_test.cc, planning/unimplemented_collision_checker.cc, planning/unimplemented_collision_checker.h
|  Topic  | Total lines | Reviewer | Code sections |
| -------| -----------| ------------| ------------- |
| Contexts | 498 | @jwnimmer-tri | `collision_checker.h`:25-148, 1029-1053, 1137-1148, 1202-1317 <br> `collision_checker.cc`: 177-201, 814-848, 858-862, 1074-1111 <br> `collision_checker_test.cc`: 469-480, 567-594, 787-812 |
| Base Class | 395 | @sammy-tri | `collision_checker.h`: 149-223, 1014-1028, 1128-1131 <br> `collision_checker.cc`: 155-176, 769-813, 849-853 <br> `collision_checker_test.cc`: 77-124, 352-468, 778-786 <br> `BUILD.bazel`: all lines |
| Shapes | 229 | @sherm1 | `collision_checker.h`: 276-385 <br> `collision_checker.cc`: 202-290 <br> `collision_checker_test.cc`: 748-777 |
| Collision filters | 720 | @EricCousineau-TRI  | `collision_checker.h`: …
=> [planning] Add CollisionChecker

bindings/pydrake/_math_extra.py, bindings/pydrake/test/math_test.py
(Noticed during #18587.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18588)
=> [pydrake] Fix RollPitchYaw repr for missing template annotation

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py
Add an underscore to `FormulaKind.True_` and `FormulaKind.False_`. The plain `True` and `False` (without the underscore) are reserved words; for users to be able to use these constants, they must have valid names.
Remove Python 2 bindings of `symbolic.Formula.True()` and `symbolic.Formula.False()`. The corresponding test code was already removed in 040b2b0f, and the `True_()` and `False_()` functions already exist.
Also purge some straggler six.PY2 TODOs.
---
Towards #18580:  Mypy chokes on our code when we use reserved keywords as names.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18589)
=> [pydrake] Rename symbolic.FormulaKind.True and False

manipulation/kuka_iiwa/iiwa_driver.h
The prior docstring leads to a malformed property, which shows up wrong on the website and breaks Mypy.
Towards https://github.com/RobotLocomotion/drake/issues/18580.
Required for the Mypy regression test in #18587 to pass.
---
Current website:
Updated website:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18592)
=> [pydrake] Fix docstring formatting for IiwaDriver.control_mode

multibody/tree/geometry_spatial_inertia.h
In the `shape` overload of `CalcSpatialInertia`, the hyperlink to the other overload just below on the page ends up unparseable in Python. Reword to use slightly less precise (but simpler) phrasing.
(Ideally, our API documentation parsing tools would be able to handle cross-references like this, but there are so many layers of parsing, transformation, reparsing, retransformation, etc. that sometimes discretion is the better part of valor.)
Towards https://github.com/RobotLocomotion/drake/issues/18580.
Required for the Mypy regression test in #18587 to pass.
---
FYI here are the current Python docs on master, showing the unparsed cross-reference:
- - - …
=> [multibody] Remove markup that destroys Python

bindings/pydrake/geometry_py_common.cc, bindings/pydrake/test/geometry_common_test.py
A non-default argument is not allowed after defaulted arguments.
Towards #18580.
Required for the Mypy regression test in #18587 to pass.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18591)
=> [pydrake] Fix AddContactMaterial parameter ordering

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/test/schema_serialization_test.py, bindings/pydrake/common/test/serialize_test_util_py.cc, bindings/pydrake/common/test/yaml_typed_test.py, bindings/pydrake/common/yaml.py
As additional regression testing, add yaml deserialization acceptance tests for the stochastic vector and rotation classes.
Towards #18566 and thus #17112.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18604)
=> [pydrake] Add YAML parsing for variant/union

geometry/optimization/dev/BUILD.bazel, geometry/optimization/dev/collision_geometry.cc, geometry/optimization/dev/collision_geometry.h, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/c_iris_test_utilities.cc, geometry/optimization/dev/test/c_iris_test_utilities.h, geometry/optimization/dev/test/collision_geometry_test.cc, geometry/optimization/dev/test/cspace_free_polytope_test.cc
Instead of using the constraint |a| <= 1, we switch to a matrix-sos constraint derived from a.dot(x) + b >= r |a|. This new formulation allows certifying much larger C-space region with a low-degree polynomial a(s), b(s).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18583)
=> [C-IRIS] Re-implement non-polytopic collision geometry.

solvers/benchmarking/BUILD.bazel, solvers/benchmarking/benchmark_ipopt_solver.cc, solvers/ipopt_solver.cc
* Addresses the following IPOPT issue mentioned in [#18292](https://github.com/RobotLocomotion/drake/issues/18292#issuecomment-1314121771) by avoiding auto-diff for linear constraints:
> We treat the linear constraints as if they are nonlinear. When we compute the gradient of the linear constraints lb <= A * x <= ub, instead of fetching the A matrix directly, we form an AutoDiffVecXd, evaluate this constraint with AutoDiffVecXd, and then take the gradient. This is very inefficient. We should directly fetch A matrix as the gradient without evaluating AutoDiff. This is a problem specific in IpoptSolver, but not in SnoptSolver.
* Adds a benchmark to evaluate the IPOPT performance for a nonlinear program in the following form:
`min x^T*x s.t. x^T*x <= 1, Identity*x  = 0, 0 <= A*x <= 1e20, -1 …
=> Avoid auto-diff for linear IPOPT constraints

geometry/BUILD.bazel, geometry/meshcat.cc, tools/workspace/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/stduuid/package.BUILD.bazel, tools/workspace/stduuid_internal/BUILD.bazel, tools/workspace/stduuid_internal/package.BUILD.bazel, tools/workspace/stduuid_internal/patches/vendor.patch, tools/workspace/stduuid_internal/repository.bzl
Fork it to `@stduuid_internal` instead.
Fix the new copy to actually install its license file.
Adjust the new copy to use a numbered version now that upstream uses tags.
Adjust the new copy to be vendored and linker-hidden.
Rework `gsl` build rule and note that `gsl` is soon-to-be unused.
Note that Focal users will still be at ODR-risk for `gsl::span`, since we don't vendor that here.  It doesn't seem worth the effort since Focal support will eventually evaporate.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18610)
=> [workspace] Deprecate the stduuid external

bindings/pydrake/common/schema_py.cc, bindings/pydrake/common/test/schema_serialization_test.py, bindings/pydrake/common/test/schema_test.py, bindings/pydrake/common/yaml.py
Add some asserts that trip when getattr/setattr are broken.
---
We need to special-case Transform and Rotation due to this oddball line:
https://github.com/RobotLocomotion/drake/blob/8b40ab2fa2fc59ad59e506842211f60eeae4e36a/common/schema/transform.h#L195
Towards https://github.com/RobotLocomotion/drake/pull/18566 and thus https://github.com/RobotLocomotion/drake/issues/17112.  This is the final preparatory commit before the end-user feature can actually land!
Fixes #13494.
+@sammy-tri for platform review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18606)
=> [pydrake] Add YAML parsing for schema.Transform

bindings/pydrake/solvers/test/scs_solver_test.py, multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc, solvers/scs_solver.cc
Instead of converting it to rotated Lorentz cone constraints with linear costs.
resolves #18365
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18605)
=> ScsSolver adds quadratic cost directly.

geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h
If a pair of geometry is certified to be separated for a larger C-space region in the previous iteration of binary search, we can skip it in the current iteration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18623)
=> [C-IRIS] Speed up binary search.

geometry/optimization/dev/collision_geometry.cc, geometry/optimization/dev/collision_geometry.h, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/collision_geometry_test.cc, geometry/optimization/dev/test/cspace_free_polytope_test.cc
Also if a Lagrangian multiplier should be zero, we set it to zero polynomial directly, instead of adding its Gram matrix with bounding-box constraints gram_var = 0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18627)
=> [C-IRIS] combine rational_for_point and rational_for_matrix_sos.

tools/performance/benchmark_tool.py
Bump the supported Ubuntu version within benchmark_tool to Jammy 22.04.
Also, make the routine for checking installed package versions a bit more robust. If the package of interest is in a broken state, the dpkg-query output may not contain a version number at all. The revised code avoids raising an exception in that case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18631)
=> [tools] Upgrade benchmark_tool to Jammy

tools/workspace/gtest/repository.bzl, tools/workspace/new_release.py
See https://github.com/google/googletest/releases/tag/v1.13.0.
Switch `new_release` tooling to claim support for Jammy. (I used it on Jammy to perform this update.)  Closes #18507.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18633)
=> [workspace] Upgrade gtest to latest release v1.13.0

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py
Wanted `.already_built()` for debugging Anzu work, but saw it wasn't bound.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18636)
=> [py systems] Bind `DiagramBuilder.{already_built,IsConnectedOrExported}`

bindings/pydrake/visualization/_meldis.py, bindings/pydrake/visualization/test/meldis_test.py
This improves responsiveness when repeatedly viewing the same simulation over and over again.
Credit to EricCousineau-TRI for coming up with this idea.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18626)
=> [meldis] Avoid reloading when the scene hasn't changed

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/test/parser_test.cc, multibody/rational/test/rational_forward_kinematics_test_utilities.cc, multibody/test_utilities/add_fixed_objects_to_plant.h, tutorials/rendering_multibody_plant.ipynb
This patch introduces a new means to disambiguate parsed copies of the same model: Parser constructors that take model_name_prefix. The new mechanism will supplant the old scheme of renaming a single model during parsing.
This patch only introduces the new API elements; later patches will port call sites and deprecate the APIs that implemented parse-time renaming.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18625)
=> [parsing] Add model name prefix constructors to Parser

tools/workspace/mypy_internal/patches/timeout.patch
Followup to #18527.  Closes #18119.  Linux debug jobs have been timing out again, increasing from "90 seconds" to "180 seconds" to try and give it enough time to poll the results.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18644)
=> Increase mypy timeout for glacial CI machines again

multibody/plant/BUILD.bazel, multibody/plant/constraint_specs.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/sap_driver.h, multibody/plant/test/sap_driver_ball_constraints_test.cc
Implements support for ball constraints when using the SAP solver.
With this PR the user can set a ball constraint with the call to `MultibodyPlant::AddBallConstraint()`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18470)
=> [multibody] Add 3-dof ball constraints to SAP

bindings/pydrake/geometry_py_scene_graph.cc, bindings/pydrake/test/geometry_scene_graph_test.py, geometry/scene_graph.h
In particular, it's important for users to be able to modify roles in a `Context`, not just the model.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18645)
=> [pydrake] Bind all SceneGraph.RemoveRole overloads

solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc, solvers/test/mosek_solver_test.cc
When calling NewSosPolynomial, if the gram matrix has size 1x1, add a bounding box constraint. if the gram matrix has size 2x2, add a rotated lorentz cone constraint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18562)
=> Add bounding box or rotated lorentz cone constraint for small psd matrices

tools/workspace/stduuid_internal/repository.bzl
The code isn't actually changed at all, but there is finally a release tag for the version we want (https://github.com/mariusbancila/stduuid/issues/73).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18652)
=> [workspace] Upgrade stduuid_internal to latest release v1.2.3

planning/test_utilities/collision_checker_abstract_test_suite.cc, planning/test_utilities/collision_checker_abstract_test_suite.h
Gtest's default efforts to print CollisionCheckerTestParams was apparently choking our sanitiziers on focal. Providing our own "to string" functionality circumvents the problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18658)
=> [planning] Fix CollisionChecker test vs memcheck

geometry/optimization/dev/BUILD.bazel
The test IrisToyRobotTest.FindPolytopeGivenLagrangian failed in a couple of mac tests. Simply marking the dev test as being manual for later resolution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18657)
=> Setting optimization/dev test manual

planning/edge_measure.h
Adds `DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN` to `EdgeMeasure`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18661)
=> [planning] Make EdgeMeasure DEFAULT_COPY

examples/multibody/inclined_plane_with_body/inclined_plane_with_body.cc, multibody/plant/compliant_contact_manager.cc, multibody/plant/contact_jacobians.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/tamsi_driver.cc, multibody/plant/tamsi_driver.h, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/plant/test_utilities/rigid_body_on_compliant_ground.h
Towards #16955. The result of work that started long ago, #17741, #18121, #18170, #18265, #18402.
This PR moves the responsibility of computing contact results from MultibodyPlant into the DiscreteUpdateManager. This allows for the consistent computation of contact results according to the underlying contact model (regularization with TAMSI, convex relaxation with SAP).
This is done in two parts (two commits):
1. TamsiDriver computes a consistent contact Jacobian from the pair kinematics computed by the manager. Therefore now both SAP and TAMSI always use consistent sign conventions hardwired in the Jacobian.
2. Removal of unused Jacobian computation code in the MultibodyPlant.
Unit tests already in master verify that this refactoring of the code does not break existing functionality. …
=> Consolidate contact results

tools/workspace/README.md
Recommend using --lint when running the new_release script. (This change was inadvertently missed when the script was previously updated.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18662)
=> Update new_release README

multibody/plant/multibody_plant.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18668)
=> fix small typo in multibody plant documentation

tools/workspace/fcl_internal/patches/cassert.patch, tools/workspace/fcl_internal/repository.bzl
Pre-release versions of Eigen have stopped including `<cassert>`, which exposes some places in FCL where its now missing.
Towards #17850.
I'm not submitting this patch to FCL upstream, since it's dead.
Example:
```console
external/fcl_internal/include/fcl/geometry/shape/convex-inl.h:68:3: error: there are no arguments to 'assert' that depend on a template parameter, so a declaration of 'assert' must be available [-fpermissive]
68 |   assert(faces != nullptr);
```
+@ggould-tri for both reviews per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18694)
=> [workspace] Patch FCL for missing include statement

tools/workspace/conex/patches/debug_macros.patch
Pre-release versions of Eigen have stopped including `<cassert>`, which exposes some places in Conex where its now missing.
See https://github.com/ToyotaResearchInstitute/conex/pull/4.
Towards https://github.com/RobotLocomotion/drake/pull/17850.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18695)
=> [workspace] Patch Conex for missing include statement

bindings/pydrake/test/stubgen_test.py, common/symbolic/expression/formula.h, multibody/tree/geometry_spatial_inertia.h, tools/workspace/mypy_internal/patches/reject_double_colon.patch, tools/workspace/mypy_internal/repository.bzl
When parsing the docstrings of a function to find its set of overloads, C++ code samples that mention the function name were at risk of matching the C++ scoping operator `::` as a type annotation, leading to malformed output. For example `MyFunc(foo : int) -> bool` is a valid signature, but the sample code `MyFunc(Eigen::Lower)` was being mis-parsed. Fix this by patching stubgen to reset in case it sees a double colon.
Enable the stubgen regression for all of pydrake; no more caveats.
Revert da58ae08 and 2cf04fdc header file changes, which were work-arounds for this parsing bug and are no longer needed.
Closes #18580.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake …
=> [pydrake] Fix incompatibility with Mypy

examples/kinova_jaco_arm/BUILD.bazel, examples/kinova_jaco_arm/jaco_controller.cc, examples/kuka_iiwa_arm/BUILD.bazel, examples/kuka_iiwa_arm/iiwa_controller.cc, examples/kuka_iiwa_arm/lcm_plan_interpolator.cc, examples/kuka_iiwa_arm/lcm_plan_interpolator.h, manipulation/planner/BUILD.bazel, manipulation/planner/stub/constraint_relaxing_ik.h, manipulation/planner/stub/robot_plan_interpolator.h, manipulation/planner/test/deprecation_test.cc, manipulation/util/BUILD.bazel, manipulation/util/move_ik_demo_base.cc, manipulation/util/move_ik_demo_base.h, manipulation/util/robot_plan_interpolator.cc, manipulation/util/robot_plan_interpolator.h, manipulation/util/test/robot_plan_interpolator_test.cc, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/constraint_relaxing_ik.cc, multibody/inverse_kinematics/constraint_relaxing_ik.h, multibody/inverse_kinematics/test/constraint_relaxing_ik_test.cc
Moves the *unbound* artifacts into `planning` with deprecated breadcrumbs.
- manipulation/planner to multibody/inverse_kinematics
- constraint_relaxing_ik
- manipulation/planner to manipulation/util
- robot_plan_interpolator
Moving includes updating all references and namespaces.
relates #18640
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18664)
=> [planning] Reorganize planning artifacts in planning (1 of 3)

bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/analysis_test.py
Similar to / derived from #17859
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18696)
=> [py systems] Allow simulator monitor to return None

manipulation/planner/BUILD.bazel
During `bazel build //...`, the deprecated targets were being globbed and therefore creating warnings.
Hotfix for #18664.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18698)
=> [manipulation] Remove spurious deprecation warning output

tools/wheel/image/setup.py
We need to teach `setuptools` to install the `_geometry_extra.py`.
Hotfix for #18684.
Closes #18702.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18706)
=> [pydrake] Hotfix for moving geometry files into subdir

tutorials/_developers.md
Encountered while wanting to look at tutorials
(I always get tripped on when to fork w/ DeepNote)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18708)
=> [tutorials] Fix markup typo for link

CTestCustom.cmake.in
Example of failing CI job:
https://drake-jenkins.csail.mit.edu/view/Production/job/mac-x86-monterey-clang-cmake-nightly-release/
CDash lists the deprecation warnings as errors: https://drake-cdash.csail.mit.edu/viewBuildError.php?buildid=1667379
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18707)
=> CMake builds: Treat DrakeDeprecationWarning as a warning not an error

common/eigen_types.h, common/symbolic/expression/formula.h, common/symbolic/expression/test/expression_test.cc
We no longer support Bionic.
FYI
- https://packages.ubuntu.com/bionic/libeigen3-dev is 3.3.4
- https://packages.ubuntu.com/focal/libeigen3-dev is 3.3.7
- https://packages.ubuntu.com/jammy/libeigen3-dev is 3.4.0
- 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18699)
=> [common] Remove vestigial Eigen version guards

bindings/pydrake/examples/acrobot.py, bindings/pydrake/examples/compass_gait.py, bindings/pydrake/examples/manipulation_station.py, bindings/pydrake/examples/multibody/run_planar_scenegraph_visualizer.py, bindings/pydrake/examples/pendulum.py, bindings/pydrake/examples/quadrotor.py, bindings/pydrake/examples/rimless_wheel.py, bindings/pydrake/examples/test/acrobot_test.py, bindings/pydrake/examples/test/compass_gait_test.py, bindings/pydrake/examples/test/manipulation_station_test.py, bindings/pydrake/examples/test/pendulum_test.py, bindings/pydrake/examples/test/quadrotor_test.py, bindings/pydrake/examples/test/rimless_wheel_test.py, bindings/pydrake/examples/test/van_der_pol_test.py, bindings/pydrake/examples/van_der_pol.py
All of the classes have been available from the `pydrake.examples` module directly for a while now. It's time to clean out the cruft.
Follow-up from #17454.
\CC @RussTedrake FYI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18685)
=> [pydrake] Deprecate the pydrake.examples.* submodules

planning/collision_checker.cc, tools/workspace/common_robotics_utilities/repository.bzl, tools/workspace/voxelized_geometry_tools/repository.bzl
Adds logging to `CollisionChecker::AllocateContexts` of whether or not OpenMP is enabled in the build.
Bumps CRU and VGT externals to add the necessary `IsOmpEnabledInBuild` function from CRU.
cc @sadraddini
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18709)
=> [planning] Add logging of OpenMP enablement in CollisionChecker

doc/_release-notes/2015.md, doc/_release-notes/2016.md, doc/_release-notes/end_of_support.md, doc/_release-notes/release_notes.md
Move end-of-support information to a new, consolidated document. Add a separate section to the release notes content page for "supplemental" pages (i.e. things that make sense here but aren't releases, such as the aforementioned end-of-support information). Replace old documents with a redirect and hide from the contents.
Fixes #18303. ~I'm guessing we will still need to add the EOS information for Bionic.~ Right, information for Bionic *is* added here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18713)
=> Consolidate out-of-support documentation

common/symbolic/expression/formula.h, common/symbolic/polynomial.cc, common/symbolic/polynomial.h, common/symbolic/rational_function.cc, common/symbolic/rational_function.h
Our existing `equal_strict` specializations must be extended to cover even more symbolic types, and a new operator struct `minmax_compare` must also be specialized now.
Closes #17850.
In #18700, I ran a bunch of CI testing to prove that this passes when mixed with a recent version of Eigen `master`, modulo two exceptions:
(1) `@libcmaes` does not build with the latest Eigen, so I disabled it.  It's `dev`-only code.
(2) `drake/math/test/linear_solve_test.cc` doesn't build, due to some template changes in upstream Eigen solvers.  That problem will still remain even after this PR lands, but it's a much more isolated piece of code, so will have less impact on users.
- - - …
=> [common] Adjust Expression for Eigen pre-3.5 compatibility

examples/manipulation_station/manipulation_station.cc, examples/manipulation_station/manipulation_station.h, examples/manipulation_station/test/manipulation_station_test.cc
This PR makes `ManipulationStation` more versatile.
I needed this change to create `ExternallyAppliedSpatialForce`-s, acting on objects of the ManipulationStation scene via python bindings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18268)
=> [examples] manipulation_station exports `applied_spatial_force` port

bindings/pydrake/planning/planning_py_robot_diagram.cc, bindings/pydrake/planning/test/collision_checker_test.py, bindings/pydrake/planning/test/robot_diagram_test.py
In Python, only the mutable getters make any sense when using the builder pattern.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18714)
=> [py planning] Remove RobotBuilder const vs non-const distinction

geometry/BUILD.bazel, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/geometry_state_test.cc, geometry/test/scene_graph_test.cc, planning/robot_diagram.cc, planning/test/robot_diagram_test.cc, systems/framework/diagram.h, systems/framework/system_scalar_conversion_doxygen.h, systems/framework/test/diagram_test.cc
In support, amend `SceneGraph` to support `AutoDiff`-to-`double` and `Expression`-to-`double` scalar conversions.
In support, enhance `Diagram` scalar conversion to allow preserving subtypes even across multiple chained conversions (which is how we implement cloning for systems).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18717)
=> Add Clone support to SceneGraph and RobotDiagram

doc/_pages/apt.md
The [documentation](https://drake.mit.edu/apt.html) currently indicates that no stable APT packages are published for Ubuntu 22.04 Jammy.
The warning has been removed since stable packages are now published.
Closes https://github.com/RobotLocomotion/drake/issues/18649.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18654)
=> Remove Jammy APT packages warning from documentation

multibody/tree/test/planar_mobilizer_test.cc, multibody/tree/test/prismatic_mobilizer_test.cc, multibody/tree/test/quaternion_floating_mobilizer_test.cc, multibody/tree/test/revolute_mobilizer_test.cc, multibody/tree/test/screw_mobilizer_test.cc, multibody/tree/test/space_xyz_floating_mobilizer_test.cc, multibody/tree/test/space_xyz_mobilizer_test.cc, multibody/tree/test/universal_mobilizer_test.cc, multibody/tree/test/weld_mobilizer_test.cc
Pull request adding unit tests to ensure mobilizer implementations are consistent with the N matrix. 
https://stackoverflow.com/questions/75211342/why-isnt-the-use-of-the-kinematic-coupling-matrix-in-unit-tests-for-mobilizers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18642)
=> Ensure that the N matrix is consistent with MapVelocityToQdot() and MapQdotToVelocity().

multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/spatial_inertia_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18725)
=> SpatialInertia tetrahedron calculations always returns a valid spatial inertia.

multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf
Support the correct, standard 'joint' spelling of planar joints. Since Drake only supported the incorrect 'drake:joint' spelling for several years, continue to accept that as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18735)
=> [parsing] Fix URDF planar joint support

multibody/parsing/detail_urdf_parser.cc, multibody/parsing/parsing_doxygen.h, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf
Implements parsing support for the `<mimic>` element in URDF. Towards #17663.
Users could have been using existing URDF models in Drake with mimic tags that were ignored. Now those models will be simulated differently if they are being simulated with DiscreteContactSolver::kSap.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18728)
=> [parsing] Add support for URDF mimic element.

geometry/meshcat.html
Meshcat was sometimes throwing an error in Firefox:  `Uncaught TypeError: navigator.getGamepads is not a function`
This interrupted the animation loop and it would not draw any geometry from Drake.
I think root cause is the gamepad API is moving to ["secure context only"](https://caniuse.com/?search=navigator.getgamepads). This workaround will allow the visualizer to keep working in these circumstances.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18720)
=> Check browser supports gamepads in meshcat

systems/framework/diagram_builder.cc, systems/framework/test/diagram_builder_test.cc
When a system is not registered, it will now list the registered system, and offer the export input/output option that people often are missing.
I saw countless student notebooks that were trying to connect to a subsystem port directly, etc.  I think this will help a lot!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18446)
=> [systems/framework] More verbose error message in DiagramBuilder

geometry/proximity/BUILD.bazel, geometry/proximity/collisions_exist_callback.h, geometry/proximity/distance_to_point_callback.h, geometry/proximity/distance_to_shape_callback.h, geometry/proximity/find_collision_candidates_callback.h, geometry/proximity/hydroelastic_callback.h, geometry/proximity/penetration_as_point_pair_callback.h, geometry/proximity/proximity_utilities.h, geometry/proximity/test/characterization_utilities.h, geometry/proximity/test/collisions_exist_callback_test.cc, geometry/proximity/test/distance_sphere_to_shape_test.cc, geometry/proximity/test/distance_to_point_callback_test.cc, geometry/proximity/test/find_collision_candidates_callback_test.cc, geometry/proximity/test/hydroelastic_callback_test.cc, geometry/proximity/test/proximity_utilities_test.cc, geometry/proximity_engine.cc, geometry/test/proximity_engine_test.cc, tools/workspace/BUILD.bazel, tools/workspace/ccd/package.BUILD.bazel, tools/workspace/ccd_internal/package.BUILD.bazel, tools/workspace/default.bzl, tools/workspace/fcl_internal/package.BUILD.bazel, tools/workspace/fcl_internal/version-from-xml.sed
Fix `ccd` BUILD file to disallow things like `#include "polytope.h"` which previously resolved to its `src` directory.
Remove unnecessary fcl version rules; use strict genrule checking.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18678)
=> [workspace] Better hide ccd and fcl externals

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_config.h, multibody/plant/multibody_plant_config_functions.cc, multibody/plant/test/multibody_plant_config_functions_test.cc, multibody/plant/test/multibody_plant_test.cc
This long-standing automatic filtering was correct and convenient in many cases, but is not always correct or desirable. This patch gives a config entry and APIs to turn them off when needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18736)
=> [multibody] Allow opt out of adjacent body collision filters

math/hopf_coordinate.h, math/test/hopf_coordinate_test.cc, math/test/random_rotation_test.cc
The psi angle was computed incorrectly before.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18747)
=> Fix a bug in QuaternionToHopfCoordinate.

CMakeLists.txt, tools/workspace/os.bzl
Distributions like Tuxedo produce slightly different output from `lsb_release` but actually still work fine.
Closes #18530.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18680)
=> [tools] Improve compatibility with Ubuntu derivatives

doc/_includes/header.html, doc/doxygen_cxx/doxygen_extra.css, doc/doxygen_cxx/header.html.patch, doc/pydrake/searchbox.html
Adds underactuated.csail.mit.edu and manipulation.csail.mit.edu to the search provided by duckduckgo. According to online discussions (like https://www.reddit.com/r/duckduckgo/comments/gcabk5/multiple_site_search_not_working/) and my testing, I believe using the OR is the recommended syntax.
+@jwnimmer-tri for feature review, please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18737)
=> Include underactuated and manipulation in "Search all of Drake"

tools/skylark/test_tags.bzl, tools/workspace/gurobi/repository.bzl
Half of changes for https://github.com/RobotLocomotion/drake/issues/8610.
Closes https://github.com/RobotLocomotion/drake/issues/8610 in combination with https://github.com/RobotLocomotion/drake-ci/pull/194.
I have kicked off a [CI job](https://drake-jenkins.csail.mit.edu/view/Gurobi/job/linux-focal-clang-bazel-experimental-gurobi-release/13/console) to test these changes.  I also tested this locally and verified that with `DRAKE_GUROBI_LICENSE_UNLIMITED=1`, more than one Gurobi test runs at one time, while `DRAKE_GUROBI_LICENSE_UNLIMITED=0` runs tests synchronously.  
Thanks to @jwnimmer-tri for providing starter code for this patch!
- - - …
=> Allow Gurobi tests to run in parallel in CI

tools/workspace/usockets/repository.bzl, tools/workspace/uwebsockets/repository.bzl
The upgrade in #18516 broke meshcat on Deepnote again.  See #18289.
Marking "emergency", because I'm trying to release pset 1 tonight, and it is MUCH more complicated if I can't use the recent Drake nightlies. (we've had a lot of deprecations / changes since the last functional nightly).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18755)
=> Downgrade usockets/uwebsockets

bindings/pydrake/BUILD.bazel, bindings/pydrake/manipulation/BUILD.bazel, bindings/pydrake/manipulation/all.py, bindings/pydrake/manipulation/planner.py, bindings/pydrake/manipulation/test/planner_deprecated_test.py, bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/inverse_kinematics_py.h, bindings/pydrake/multibody/inverse_kinematics_py_differential.cc, bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py, examples/manipulation_station/end_effector_teleop_dualshock4.py, examples/manipulation_station/end_effector_teleop_mouse.py, examples/manipulation_station/end_effector_teleop_sliders.py, manipulation/planner/BUILD.bazel, manipulation/planner/stub/constraint_relaxing_ik.h, manipulation/planner/stub/differential_inverse_kinematics.h, manipulation/planner/stub/differential_inverse_kinematics_integrator.h, manipulation/planner/stub/robot_plan_interpolator.h, manipulation/planner/test/deprecation_test.cc, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/differential_inverse_kinematics.cc, multibody/inverse_kinematics/differential_inverse_kinematics.h, multibody/inverse_kinematics/differential_inverse_kinematics_integrator.cc, multibody/inverse_kinematics/differential_inverse_kinematics_integrator.h, multibody/inverse_kinematics/test/differential_inverse_kinematics_integrator_test.cc, multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc, tools/install/libdrake/build_components.bzl
- manipulation/planner/differential_inverse_dynamics* goes to multibody/inverse_dynamics.
Moving includes updating all references, namespaces, and bindings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18715)
=> [planning] Reorganize planning artifacts in planning (3 of 3)

tools/workspace/new_release.py
Towards #17910.
https://github.com/RobotLocomotion/drake/blob/e51565608b03a54286620057c59f66fa83d059d3/tools/workspace/usockets/repository.bzl#L11-L13
https://github.com/RobotLocomotion/drake/blob/e51565608b03a54286620057c59f66fa83d059d3/tools/workspace/uwebsockets/repository.bzl#L11-L13
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18761)
=> [workspace] Disable auto-upgrade for usockets,uwebsockets

tools/workspace/buildifier/repository.bzl
Fixes #18754. Towards #18724.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18763)
=> [workspace] Upgrade buildifier to latest release 6.0.1

bindings/pydrake/multibody/optimization_py.cc, bindings/pydrake/multibody/test/optimization_test.py, multibody/optimization/BUILD.bazel, multibody/optimization/test/toppra_test.cc, multibody/optimization/toppra.cc, multibody/optimization/toppra.h
This allows setting the cartesian frame speed and acceleration limits with trajectories.
Resolves #17131 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18738)
=> [multibody] Adding time-varying constraints to two Toppra APIs

common/sorted_pair.h, common/test/sorted_pair_test.cc
Mutation allows the user to violate the sorting invariant.
See https://github.com/RobotLocomotion/drake/pull/15551#issuecomment-1426961027.
---
I noticed this while deprecating `operator<<` functions. With a `#include <fmt/ranges.h>`, there is no need for any `operator<<` customization; formatting works exactly the same, right out of the box, because SortedPair presents the tuple concept.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18767)
=> [common] Remove SortedPair mutable structured bindings

bindings/pydrake/planning/planning_py_robot_diagram.cc, bindings/pydrake/planning/test/robot_diagram_test.py, planning/robot_diagram_builder.cc, planning/robot_diagram_builder.h, planning/test/body_shape_description_test.cc, planning/test/collision_avoidance_test.cc, planning/test/collision_checker_test.cc, planning/test/planning_test_helpers.cc, planning/test/robot_diagram_test.cc, planning/test/scene_graph_collision_checker_test.cc
The typical use case of a builder is that the object is mutable and users are mutating it. In that case, the clarity benefit of using "mutable_" prefix on is small compared to the cost. (In contrast with, e.g., a Context where mutation access causes cache entry invalidation so using special names make sense.)  This brings C++ up to par with what we did in Python.
Also deprecate the IsPlantFinalized and FinalizePlant sugar. The sugar isn't encapsulating or abbreviating anything versus calling the MbP functions directly on the plant() accessor, where the MbP functions have full documentation directly under your auto-complete IDE fingertips.
---
Follow-up from #18770.
\CC @RussTedrake @calderpg-tri FYI
Confirmed `Anzu-master-Drake-PR/181` passes vs these deprecations.
Confirmed …
=> [planning] Simplify RobotDiagramBuilder function names

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/detail_tinyxml.cc, multibody/parsing/detail_tinyxml.h, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Adds support for parsing the `<contact>` elements.
Adds an accessor method to MultibodyPlant to get the registered SceneGraph.  I don't know why we've never offered it before; I don't see a problem with it.  And I can't get access to the collision filter logic directly without it.  The CollisionFilterResolver hoopla from the other parsers isn't immediately suited to this MuJoCo case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18351)
=> [parsing] Initial collision filter support in mujoco parser

geometry/optimization/dev/BUILD.bazel, geometry/optimization/dev/c_iris_collision_geometry.cc, geometry/optimization/dev/c_iris_collision_geometry.h, geometry/optimization/dev/c_iris_separating_plane.cc, geometry/optimization/dev/c_iris_separating_plane.h, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/separating_plane.cc, geometry/optimization/dev/test/c_iris_collision_geometry_test.cc, geometry/optimization/dev/test/c_iris_separating_plane_test.cc, geometry/optimization/dev/test/cspace_free_polytope_test.cc, geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
CollisionGeometry and SeparatingPlane are too general names, these names can be used in many other applications. To avoid name collision, I rename them as CIrisCollisionGeometry and CIrisSeparatingPlane.
Also rename the file to add c_iris.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18781)
=> [C-IRIS] add CIris to CollisionGeometry and SeparatingPlane.

multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/test/discrete_update_manager_test.cc, multibody/plant/test/multibody_plant_scalar_conversion_test.cc
Towards #16955.
A follow up cleanup to #18647 (consolidate contact results).
This PR moves EvalContactSolverResults() into DiscreteUpdateManager().
Before this PR this methods was implemented in the plant, but with a forwarding in the manager to pretend it was its job. Now it is.
Simply a cleanup, no new functionality, no new unit tests needed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18746)
=> Cleanup of the EvalContactResults() workflow

bindings/pydrake/common/test/deprecation_autocomplete_test.py, tools/workspace/styleguide/BUILD.bazel
Follow-up to #18262.
- deprecation_autocomplete_test: add __getstate__(, refs: https://docs.python.org/3/library/pickle.html#object.__getstate__
Changed in version 3.11: Added the default implementation of the __getstate__() method in the object class.
- styleguide: temporarily mark the failing test as manual to unblock CI, proper fix to adjust import paths TBD.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18786)
=> [macOS] Fix python 3.11 testing issues

common/BUILD.bazel, common/copyable_unique_ptr.h, common/fmt.h, common/test/copyable_unique_ptr_test.cc, common/test/fmt_test.cc, common/test_utilities/BUILD.bazel, common/test_utilities/fmt_format_printer.h, common/text_logging.h, tools/workspace/gtest/package.BUILD.bazel, tools/workspace/gtest/patches/add_printers.patch, tools/workspace/gtest/repository.bzl
Move `drake::fmt_runtime` shim from `common/text_logging.h` to new file `common/fmt.h`.
Add `DRAKE_FORMATTER_AS` macro to trampoline formatter to another related object. This is useful for formatting wrapper types (copyable_unique_ptr, identifier, sorted_pair, type_safe_index, etc).
Patch googletest to use fmt for formatting, when available.
Port `copyable_unique_ptr` to the new code and deprecate its `operator<<`.
---
Towards #17742.  See also the WIP branch: https://github.com/jwnimmer-tri/drake/commits/fmt-v9.
The goal of this first step is to land the googletest integration, so that as we continue to deprecate the `operator<<` overloads, we won't run into unit testing headaches.
- - - …
=> [common] Add infrastructure for fmt without ostreams

geometry/proximity/BUILD.bazel, geometry/proximity/obj_to_surface_mesh.cc, geometry/proximity/obj_to_surface_mesh.h, geometry/proximity/test/obj_to_surface_mesh_test.cc, geometry/render/test/meshes/box.obj, multibody/parsing/BUILD.bazel, multibody/parsing/detail_mesh_parser.cc, multibody/parsing/detail_mesh_parser.h, multibody/parsing/detail_select_parser.cc, multibody/parsing/parser.h, multibody/parsing/test/detail_mesh_parser_test.cc, multibody/parsing/test/parser_test.cc
The parser now accepts files with the .obj extension. The result of parsing is a new model instance with a single body whose mass properties are derived from the mesh.
To support this, it required some infrastructure support:
- geometry parsing of OBJ --> `TriangleSurfaceMesh` exposed for the parser to use.
- Tweak the error messages to allude to *data* instead of file as it allows for parsing from in-memory OBJ data.
- Update box.obj to include an object name.
- New patch to address defect in tiny obj loader.
Resolves #17267
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18776)
=> [parsing] Allow models to be parsed into plant from obj files

bindings/pydrake/symbolic_py.cc, bindings/pydrake/symbolic_py_unapply.cc, common/find_runfiles.cc, examples/pendulum/pendulum_parameters_derivatives.cc, examples/simple_gripper/simple_gripper.cc, geometry/benchmarking/mesh_intersection_benchmark.cc, geometry/benchmarking/render_benchmark.cc, geometry/geometry_properties.h, multibody/contact_solvers/sap/partial_permutation.cc, multibody/parsing/test/detail_sdf_geometry_test.cc, solvers/solver_options.cc, systems/lcm/lcm_interface_system.cc, systems/sensors/image_writer.cc
Towards #17742.  Having everything use `<>` makes it a lot easier to grep for places that need adjustments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18805)
=> Canonicalize fmt include spellings

common/BUILD.bazel, common/fmt.h, common/fmt_ostream.h, common/test/fmt_ostream_test.cc, math/rigid_transform.h, math/roll_pitch_yaw.cc, math/roll_pitch_yaw.h, multibody/parsing/test/detail_sdf_geometry_test.cc
Towards #17742.
The "feature" here is the `fmt::streamed` and `fmt::ostream_formatter` polyfills.
---
This is a microcosm of the coming porting.  As one of the next steps in porting, we'll add snippets like this ...
```c++
// Format RollPitchYaw using its operator<<.
// TODO(jwnimmer-tri) Add a real formatter and deprecate the operator<<.
namespace fmt {
template <typename T>
struct formatter<drake::math::RollPitchYaw<T>>
: drake::ostream_formatter {};
}  // namespace fmt
```
... to any Drake class that provides an `operator<<`.  I've decided not to sugar that up with a macro, because they will all soon thereafter be replaced with proper formatters, and the sugar isn't a huge win anyway.
- - - …
=> [common] Add infrastructure to opt-in to fmt via ostream

manipulation/models/jaco_description/urdf/j2s7s300_arm_sphere_collision.urdf
This doesn't actually affect the collision geometry of the arm -- moving a sphere across a revolute joint has no effect.  What it does do is make the adjacent link collision filtering work more effectively so that attaching a gripper to this model doesn't create a self collision.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18799)
=> Move the distal geometry for the Jaco arm to link 7

multibody/parsing/BUILD.bazel, multibody/parsing/detail_dmd_parser.cc, multibody/parsing/test/process_model_directives_test.cc
The SDF  and URDF parsers already do this, it  was missing from the model directives parser.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18798)
=> Ignore collision filter groups from model directives if there's no scene graph

multibody/inverse_kinematics/BUILD.bazel, solvers/BUILD.bazel, solvers/gurobi_solver.cc, tools/skylark/kwargs.bzl
Towards #18775.
When `GUROBI_NUM_THREADS` is set to an integer, it provides a default for the `"Threads"` solver-specific solver option.
Wire this up into the Bazel test runner so that the BUILD rule `num_threads = ...` specification covers this new variable as well.
This should allow us to run Gurobi tests in parallel in CI again with caching, by reverting https://github.com/RobotLocomotion/drake-ci/pull/199.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18819)
=> [solvers] Add GUROBI_NUM_THREADS environment variable

tools/workspace/gz_math_internal/repository.bzl, tools/workspace/gz_utils_internal/repository.bzl, tools/workspace/mypy_extensions_internal/repository.bzl, tools/workspace/mypy_internal/repository.bzl, tools/workspace/new_release.py, tools/workspace/sdformat_internal/repository.bzl, tools/workspace/usockets/repository.bzl, tools/workspace/uwebsockets/repository.bzl
A `_COHORTS` constant has been added to the top of the `new_release` script, and checks have been added to enforce upgrades as a "cohort" for the groups of dependencies listed.  Additionally, a message was added to the relevant `repository.bzl` scripts to point to the `new_release` script.
Closes https://github.com/RobotLocomotion/drake/issues/18638.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18673)
=> Enforce external upgrades in "cohorts"

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/detail_mujoco_parser.h, multibody/parsing/test/detail_mujoco_parser_test.cc
This patch clears the way for making the Mujoco parser work more like the other parsers in the suite. It will be necessary for integrating control of diagnostic output, and for other forthcoming changes that affect all parsers.
The bulk of the changes are in the unit test, but that should all be functionality-neutral.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18812)
=> [parsing] Integrate ParsingWorkspace into Mujoco parser

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/scalar_conversion.py, bindings/pydrake/systems/test/scalar_conversion_test.py
Helpful for debugging some MultibodyPlant stuff in pydrake
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18813)
=> [py systems] Allow scalar conversion for subclassed diagrams

multibody/tree/rotational_inertia.h
Was reading docs, found non-printing character in Sublime; seems like it was introduced in #5524
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18810)
=> [multibody] Replace non-space character `<0x2009>` with space

bindings/pydrake/common/containers.py, bindings/pydrake/common/cpp_template.py, bindings/pydrake/common/deprecation.py, bindings/pydrake/systems/scalar_conversion.py
We have several pure python methods with example code in their doc strings. In some cases, they don't render as doc strings at all. In other cases, they render inconsistently (i.e., as a list).
This picks an arbitrary style for the examples and confirms that the instances all render the same.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18825)
=> [pydrake] Correct and unify examples in pydrake docstrings

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/primitives/affine_system.cc, systems/primitives/affine_system.h, systems/primitives/linear_system.cc, systems/primitives/linear_system.h, systems/primitives/test/affine_system_test.cc
It's always been a pain to produce simple linear/affine systems, because we needed to pass in empty matrices of the correct size (e.g. even if we have no states, the B matrix must have zero rows and number of input columns).  This PR makes the constructor for AffineSystem more robust, setting any empty matrix to an appropriate size. This makes it reasonable to have default values.
This motivation for this was that I was writing a tutorial where the simplest way to produce a system that simple adds an offset to a signal (e.g. to change coordinates), took many lines and lots of explaining. Now we can just have e.g.
```
system = AffineSystem(D=np.eye(2), y0=[1, 2])
```
- - - …
=> Improve defaults for AffineSystem and LinearSystem

tools/bazel.rc, tools/dynamic_analysis/bazel.rc, tools/lint/bazel.rc
As it turns out, varying 'test' vs 'build' for options in a bazelrc causes the analysis phase to be re-run as the user alternates between 'bazel build' and 'bazel test'.  Since all test options are valid for build as well, we should just list everything in build.
This removes "Options have changed, discarding analysis cache" output from bazel in the typical case.
(See also `anzu#4460` for the ditto change.)
Towards #18828.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18838)
=> [tools] Keep bazel analysis phase intact

tools/bazel.rc
Towards #18828.
My intention here is that we switch the CI job definition for packaging builds to **not** specify mosek and/or snopt specifically, but rather to just say `--config=packaging`, so that `drake.git` owns its configuration entropy.
I think it's harmless to add this option here first, and then later refactor the Drake CI job names.  I don't think we need tandem.
@svenevs or @BetsyMcPhail whoever is around, please grab a feature-review here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18840)
=> [tools] Offer --config=packaging option to build a nightly release

multibody/inverse_kinematics/inverse_kinematics.h
The `get_mutable_prog()` was mistakenly tagged as const.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18793)
=> [multibody] const InverseKinematics no longer gives mutable access to members

BUILD.bazel, bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/visualization/BUILD.bazel, examples/hardware_sim/BUILD.bazel, examples/hydroelastic/ball_plate/BUILD.bazel, examples/hydroelastic/python_ball_paddle/BUILD.bazel, examples/hydroelastic/python_nonconvex_mesh/BUILD.bazel, examples/multibody/four_bar/BUILD.bazel
Closes #18827.
Note that this is only relevant for source builds.  Install users of model_visualizer still only have access to the same set of installed models as before.
\CC @trowell-tri FYI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18843)
=> [tools] Add all models to model_visualizer's runfiles

lcm/BUILD.bazel, lcm/drake_lcm_base.cc, lcm/drake_lcm_base.h, lcm/drake_lcm_interface.h, lcm/test/drake_lcm_base_test.cc
This might smooth out downstream transitions for subclasses of `DrakeLcmInterface` for changes such as #18826.
+@EricCousineau-TRI for both reviews per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18847)
=> [lcm] Add DrakeLcmBase

examples/zmp/zmp_example.cc, systems/controllers/test/zmp_planner_test.cc, systems/controllers/test/zmp_test_util.cc, systems/controllers/test/zmp_test_util.h, systems/controllers/zmp_planner.cc, systems/controllers/zmp_planner.h
Originally inspired by observed errors in doxygen formatting (erroneous comments in `@param foo, bar` led to incorrect documentation). However, the clean up expanded to the following:
1. Correct the doxygen formatting error.
2. Update doxygen to use the current practice of /** */ comments without leading * on each line.
3. References to other methods include terminal ().
4. Add `@pre` to functions that require `Plan()` to have been called.
5. Rename the class to conform with current standards.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18845)
=> [planning] Clean up ZMPPlanner

geometry/proximity/contact_surface_utility.cc
Somehow these call sites evaded recent modernization sweeps.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18855)
=> [geometry] Fix some fmt_eigen() stragglers

common/BUILD.bazel, common/type_safe_index.cc, common/type_safe_index.h
Noticed during #17742.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18856)
=> [common] Move non-inlined TypeSafeIndex functions to the cc file

doc/doxygen_cxx/doxygen.h, multibody/inverse_kinematics/constraint_relaxing_ik.h, multibody/inverse_kinematics/differential_inverse_kinematics.h, multibody/inverse_kinematics/global_inverse_kinematics.h, multibody/inverse_kinematics/inverse_kinematics.h, multibody/optimization/static_equilibrium_problem.h, multibody/optimization/toppra.h, planning/body_shape_description.h, planning/collision_avoidance.h, planning/collision_checker.h, planning/collision_checker_context.h, planning/collision_checker_params.h, planning/edge_measure.h, planning/planning_doxygen.h, planning/robot_clearance.h, planning/robot_collision_type.h, planning/robot_diagram.h, planning/robot_diagram_builder.h, planning/scene_graph_collision_checker.h, planning/trajectory_optimization/direct_collocation.h, planning/trajectory_optimization/direct_transcription.h, planning/trajectory_optimization/integration_constraint.h, planning/trajectory_optimization/kinematic_trajectory_optimization.h, planning/trajectory_optimization/multiple_shooting.h, systems/controllers/zmp_planner.h
1. Adds the new classes in drake/planning to the module.
2. Adds subgroups to the module to provide broad guidance on the classes.
3. Moves the planning module documentation into its own header.
resolves #18640
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18854)
=> [planning] Update algorithms/planning module documentation

bindings/pydrake/common/test/eigen_geometry_test_util_py.cc, common/constants.h, common/eigen_types.h, common/symbolic/expression/formula.h, math/cross_product.h, math/rotation_conversion_gradient.h, multibody/fem/test/constitutive_model_test_utilities.cc, solvers/mathematical_program.h
Many of the deprecations are just for dead constants. 
The more interesting ones are using-statements for some Eigen types ...
In cases like `Eigen::Matrix...`, it's sensible to alias them as `drake::Matrix...` because (1) they are extremely heavily used, and (2) we are effectively _adopting_ them as our own type, with a promise to keep the type intact and inter-operable forevermore.
In contrast, for `std::vector` we have not aliased nor adoped it.  In headers we say `std::` and in some cc files we choose `using std::vector`.
My thesis here is that things like `Eigen::AngleAxis` are more like `std::vector` than `Eigen::Matrix` -- we should not adopt them, but rather treat them as third-party library types, with a fully-qualified (and therefore much more clear) typename in headers, and (if …
=> [common] Deprecate unused constants and typedefs in :essential

common/benchmarking/BUILD.bazel, common/benchmarking/benchmark_polynomial.cc
This is extremely slow for A and X being of size 200 * 200, takes 77 seconds on my Puget.
As reported from the slack discussion https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1677172164932209
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18861)
=> Add a benchmark on trace(A*X) where X contains symbolic variables.

common/benchmarking/BUILD.bazel, common/benchmarking/benchmark_polynomial.cc
Here is the result on my machine
```
Benchmark                                   Time             CPU   Iterations
-----------------------------------------------------------------------------
BenchmarkPolynomialEvaluatePartial       2394 us         2389 us          304
BenchmarkMatrixInnerProduct/10/0        0.001 s         0.001 s          1024
BenchmarkMatrixInnerProduct/50/0        0.239 s         0.238 s             3
BenchmarkMatrixInnerProduct/100/0        3.54 s          3.54 s             1
BenchmarkMatrixInnerProduct/200/0        55.7 s          55.6 s             1
BenchmarkMatrixInnerProduct/10/1        0.000 s         0.000 s          8238
BenchmarkMatrixInnerProduct/50/1        0.006 s         0.006 s           122
BenchmarkMatrixInnerProduct/100/1       0.041 s …
```
=> Add a benchmark on Q * X while Q is sparse.

solvers/BUILD.bazel, solvers/clp_solver_common.cc, solvers/csdp_solver_common.cc, solvers/equality_constrained_qp_solver.cc, solvers/gurobi_solver_common.cc, solvers/ipopt_solver_common.cc, solvers/linear_system_solver.cc, solvers/moby_lcp_solver.cc, solvers/mosek_solver_common.cc, solvers/nlopt_solver_common.cc, solvers/osqp_solver_common.cc, solvers/scs_solver_common.cc, solvers/snopt_solver_common.cc, solvers/solver_base.cc, solvers/solver_base.h, solvers/solver_id.cc, solvers/solver_id.h, solvers/test/equality_constrained_qp_solver_test.cc, solvers/test/snopt_solver_test.cc, solvers/test/solver_base_test.cc, solvers/test/solver_id_test.cc, solvers/unrevised_lemke_solver.cc
The constructor with a `SolverId`-returning functor is now deprecated.
Fetching the `solver_id()` should be a zero-cost abstraction, which means the function must be final and inline, rather than a virtual function that makes another indirect call.
Add an API comment and runtime warning about `SolverId` pessimizations. The `SolverId` is supposed to be a integer-like flyweight that's cheap to pass by value, but when its name exceeds 15 characters (i.e., more than SSO can handle) then we were using heap when copying it (e.g., into the `SolverOptions` maps).
While we're updating comments anyway, upgrade them all to the preferred lightweight Doxygen style.
- - - …
=> [solvers] Change SolverBase constructor to prefer SolverId directly

multibody/inverse_kinematics/constraint_relaxing_ik.h, multibody/inverse_kinematics/differential_inverse_kinematics.h, multibody/inverse_kinematics/global_inverse_kinematics.h, multibody/inverse_kinematics/inverse_kinematics.h, multibody/optimization/static_equilibrium_problem.h, planning/planning_doxygen.h
1. Rename configuration -> Inverse kinematics
2. Put the static equilibrium problem directly into planning (as it doesn't fit well with the other topics).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18883)
=> [planning] Clean up of planning module documentation

solvers/ipopt_solver.cc
Note the contract of `SolverBase::DoSolve`:
>  The options and initial guess are already merged, i.e., the DoSolve
>  implementation should ignore prog's solver options and guess.
This was overlooked in #10672.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18874)
=> [solvers] Remove redundant options copying in IpoptSolver

bindings/pydrake/visualization/_meldis.py, bindings/pydrake/visualization/test/meldis_test.py
Reverts RobotLocomotion/drake#18774
Dear @zachfang ,
The on-call build cop, @svenevs, believes that your PR #18774 may have
- https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-clang-bazel-continuous-release/363/
```
[1:36:50 PM]  FAIL: //bindings/pydrake/visualization:py/meldis_test (see /Users/admin/workspace/mac-arm-monterey-clang-bazel-continuous-release/_bazel_admin/d8209b58b645930155068a99d03380e4/execroot/drake/bazel-out/darwin_arm64-opt/testlogs/bindings/pydrake/visualization/py/meldis_test/test.log)
[1:36:50 PM] …
```
=> Revert "[visualization] Meldis displays point cloud data"

multibody/tree/multibody_tree.cc, multibody/tree/test/multibody_tree_test.cc
Now when the model instance is not found, it helpfully reports the model instances that could have been found.
+@ggould-tri for both reviews, please.  (I think you'll approve of the change!)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18879)
=> Improve error message for MbP::GetModelInstanceByName()

common/symbolic/expression/expression.cc, common/symbolic/expression/expression_cell.cc, common/symbolic/expression/expression_cell.h, common/symbolic/expression/variable.cc, common/symbolic/expression/variable.h
Note that `expression_cell.h` is internal use only, so this API change will not disturb any users.
This is roughly a 50% reduction in BenchmarkMatrixInnerProduct/200, and a 10% reduction in all three BenchmarkSosProgram.
Also move two tiny Variable getters to the header file. It's a little difficult to show this in a profile, but I think we'd all agree that this change is blindingly obvious and should have been like this from the beginning.
Relates to #18861.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18869)
=> [symbolic] Speed up Add and Mul cell ctors

common/fmt_eigen.h, common/fmt_ostream.h, common/yaml/yaml_node.h, geometry/geometry_ids.h, geometry/proximity_properties.h
Also work around a Doxygen bug parsing the GeometryId formatter.
---
Towards https://github.com/RobotLocomotion/drake/issues/17742.
Examples of what's fixed in this PR:
- https://drake.mit.edu/doxygen_cxx/classformatter.html
- https://drake.mit.edu/doxygen_cxx/namespacefmt.html
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18894)
=> Remove fmt::formatter of internal types from Doxygen

common/sorted_pair.h, common/test/sorted_pair_test.cc
Towards #17742.
FYI https://fmt.dev/latest/api.html#ranges-api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18892)
=> [common] Deprecate SortedPair::operator<<

solvers/gurobi_solver.cc, solvers/test/csdp_solver_test.cc, solvers/test/gurobi_solver_test.cc, solvers/test/mosek_solver_test.cc, solvers/test/scs_solver_test.cc, solvers/test/second_order_cone_program_examples.cc, solvers/test/second_order_cone_program_examples.h
Resolves #18882
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18890)
=> [solvers] Fix a bug in GurobiSolver with duplicated variables in second-order cone constraints.

geometry/BUILD.bazel, geometry/geometry_properties.h, geometry/test/geometry_properties_test.cc
The private method GetValueOrThrow would take the name of the calling function in the event of failure so it could be included in the error message. However, that method name was being captured as a const std::string&. Going from string literal to string requires a copy of the string (and a concomitant heap allocation).
By replacing string with string_view, we eliminate the copy.
Closes #18897
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18899)
=> [geometry] Eliminate unnecessary heap allocation in Geometry_properties

common/symbolic/expression/variable.cc, common/symbolic/expression/variable.h
Pack the `Variable::Type` into the ID. This reduces `sizeof(Variable)` from 32 to 24 bytes.
This is about a 2-3% speedup on `BenchmarkPolynomialEvaluatePartial`, but the main benefit is a step towards a size of 16 bytes with SSO in a future commit.
This changes the order of variables in ordered collections. Previously, they were sorted by creation time. Now they're effectively sorted by the pair of (variable type, creation time).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18901)
=> [symbolic] Speed up symbolic::Variable a little bit

solvers/mosek_solver.cc, solvers/test/mosek_solver_test.cc
Previously MosekSolver will still query the basis solution, which is not available from Mosek, causing errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18895)
=> [solvers] retrieve Mosek IPM solution if basis selection is disabled for LP

examples/quadrotor/README.md, examples/quadrotor/run_quadrotor_lqr.cc, tools/workspace/models_internal/files.bzl, tools/workspace/models_internal/repository.bzl
Pull in the fixes from
https://github.com/RobotLocomotion/models/pull/21
To test, run `meldis` and `//examples/quadrotor/run_quadrotor_lqr`.  Before this change, you will see that the propellers are black from above and invisible from below.  Now they should be grey from both sides.
Also removes stale comment in quadrotor/README.md.  Issue #6243 is closed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18867)
=> Fixes skydio model prop colors and normals

geometry/geometry_state.cc, geometry/geometry_state.h, geometry/scene_graph_inspector.cc, geometry/scene_graph_inspector.h, geometry/test/geometry_state_test.cc, geometry/test/scene_graph_inspector_test.cc
SceneGraphInspector has four methods that return collections of ids (frame and geometry). Previously, only one of those guaranteed ordering on the ids. This brings the other three in line.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18903)
=> [geometry] SceneGraphInspector provides ordering guarantees on reported ids

bindings/pydrake/visualization/_meldis.py, bindings/pydrake/visualization/test/meldis_test.py
This PR is a re-apply of a previous commit, #18774, with a fix for a unit test.
Investigation:
EDIT: The root cause is the indeterministic order of `FrameId` when constructing `lcmt_viewer_load_robot` messages. The test depends on two LCM messages to be encoded exactly the same to pass its test objectives.
~~I haven't fully grasped what the root cause is, but one of the LCM message comparisons behaves differently due to the order of a field, i.e., `lcmt_viewer_load_robot.link`.~~ This is an example from: https://github.com/RobotLocomotion/drake/blob/master/bindings/pydrake/visualization/_meldis.py#L102
```
(message.encode() == self._load_message.encode()) yields `false` when it should be `true`.
b'\x89\x87 \x9b\x10\xaa-9\x00\x00\x00\x02\x00\x00\x00\x16plant::acrobot::Link1\x00\x00\x00\x00\ …
```
=> [visualization] Meldis displays point cloud data

multibody/parsing/package_map.cc, multibody/parsing/package_map.h
In preparation for larger pending changes:
- Move and regroup functions within Doxygen for clarity.
- Adopt modern comment flow style and markup.
- In default ctor doxygen, add a see-also to MakeEmpty.
- Switch error messages to use fmt.
- Hit it with clang-format.
- Tweak some weird optional assignments that clang-format hated.
Towards #15774.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18918)
=> [parsing] Tidy up PackageMap code style

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/table_in_world.sdf
The SDFormat API has evolved since the original check was written. Work harder to tolerate single-model loading within the richer API.
Long term, we aim to drop single-model enforcing APIs altogether.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18888)
=> [parsing] Relax single model test in SDFormat singular API
