multibody/plant/BUILD.bazel, multibody/plant/constraint_specs.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/constraint_specs_test.cc, multibody/plant/test/multibody_plant_scalar_conversion_test.cc
In addition, remove an unused data memeber in MbP.
Closes #15168.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17708)
=> [multibody] Bookkeeping for MbP's scalar converting constructor

systems/primitives/test/linear_transform_density_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17777)
=> Perturb test order to avoid kcov issue #339

solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17754)
=> NewSosPolynomial detects uninitialized enum values

geometry/BUILD.bazel, geometry/proximity/BUILD.bazel, geometry/proximity/test/vtk_to_volume_mesh_test.cc, geometry/proximity/vtk_to_volume_mesh.cc, geometry/proximity/vtk_to_volume_mesh.h, geometry/test/one_tetrahedron.vtk, geometry/test/two_tetrahedra_with_field_variable.vtk, tools/dynamic_analysis/lsan.supp, tools/workspace/vtk/repository.bzl
Read VTK files of tetrahedral meshes using VTK library.
Also fixes #17767.
CC: @xuchenhan-tri
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17725)
=> [geometry] ReadVtkToVolumeMesh

manipulation/models/wsg_50_description/sdf/schunk_wsg_50_with_tip.sdf
I found it very difficult to read the collision geometry without this
touch up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17785)
=> Fix whitespace in schunk_wsg_with_tip.sdf

bindings/pydrake/geometry_py_hydro.cc, bindings/pydrake/geometry_py_scene_graph.cc
Towards #17625.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17799)
=> [pydrake] No constructor binding of *SurfaceMeshFieldLinear and ContactSurface

systems/controllers/finite_horizon_linear_quadratic_regulator.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17801)
=> Fix misspelling of "Riccati"

multibody/parsing/model_directives.h, multibody/parsing/process_model_directives.cc, multibody/parsing/test/model_directives_test.cc, multibody/parsing/test/process_model_directives_test.cc, multibody/parsing/test/process_model_directives_test/inject_frames.dmd.yaml
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17811)
=> [multibody/parsing] Add optional X_PC to model directives AddWeld

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_com_test.cc, multibody/plant/test/multibody_plant_momentum_energy_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17770)
=> New function MultibodyPlant::CalcSpatialInertia()

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/process_model_directives.cc, multibody/parsing/process_model_directives.h, multibody/parsing/test/process_model_directives_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17810)
=> [multibody/parsing] LoadModelDirectivesFromString

geometry/render/BUILD.bazel
Hotfix for #17812.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17841)
=> Fix bazel visibility on //geometry/render

doc/_pages/from_source.md, doc/_pages/installation.md, doc/_pages/pip.md, tools/workspace/python/repository.bzl
Closes #17000.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17805)
=> [doc] Update supported Xcode / python versions to match CI

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py, math/rigid_transform.cc, math/rigid_transform.h, math/test/rigid_transform_test.cc
@rpoyner-tri as relates to collision checker cleanup in anzu.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17790)
=> Add RigidTransform multiply by Vector4d

doc/_pages/from_source.md, doc/_pages/troubleshooting.md
Inspired by a [question on drakedevelopers#build slack](https://app.slack.com/client/T0JNB2DS4/C0KDGF4V9/thread/C0KDGF4V9-1662477077.273739).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17842)
=> [doc] Add build OOM troubleshooting

systems/sensors/camera_config.cc, systems/sensors/camera_config.h, systems/sensors/test/camera_config_test.cc
Towards #17852.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17854)
=> [sensors] Validate CameraConfig substructs only as part of the whole

examples/hardware_sim/example_iiwa_wsg.dmd.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17856)
=> [examples] Set an initial position for the hardware_sim demo

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/multibody_tree_topology.h, multibody/tree/test/multibody_tree_creation_test.cc
Closes #15496.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17800)
=> [multibody] Compute bodies affected by joints

bindings/pydrake/perception_py.cc, bindings/pydrake/test/perception_test.py, perception/point_cloud.cc, perception/point_cloud.h, perception/test/point_cloud_test.cc
Towards https://github.com/RussTedrake/manipulation/issues/130.
+@EricCousineau-TRI for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17829)
=> [perception] Add PointCloud::Crop and Concatenate(vector<PointCloud>)

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/sensors_py.cc, bindings/pydrake/systems/test/sensors_test.py
This also includes bindings of `CameraConfig`s substructs: `FovDegress` and `FocalLength`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17852)
=> [config] Provide bindings for CameraConfig and ApplyCameraConfig

bindings/pydrake/visualization/meldis.py, bindings/pydrake/visualization/test/meldis_test.py
- Subscribe to DRAKE_VIEWER_DEFORMABLE lcm channel
- Convert lcmt_viewer_link_data and lcmt_viewer_geometry_data to meshcat's triangle meshes.
Towards #16875
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17848)
=> [meldis] Support deformable geometries

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/BUILD.bazel, common/trajectories/path_parameterized_trajectory.cc, common/trajectories/path_parameterized_trajectory.h, common/trajectories/test/path_parameterized_trajectory_test.cc
Adds a trajectory class that consists of a path and parameterization of the progress along that path.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17816)
=> Add PathParameterizedTrajectory

tools/install/install_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17871)
=> [install] Add better help for running just one test

tools/skylark/drake_py.bzl
This improves clarity in several senses:
1. Cleans up comments to developers.
2. Changes names to be more suggestive of what the rule is (i.e., "disable_test" actually redirects users, so it is a "redirect_test".
3. Reformats the redirection error message so that the bazel labels are easier to see and select.
Without the format change, the message could look like (depending on window width):
```
ERROR: Please use '//bindings/pydrake/systems:py/planar_scenegraph_visualiz
er_test'; the label '//bindings/pydrake/systems:planar_scenegraph_visualize
r_test' has been removed.
```
With the change it looks like this:
```
ERROR: Please use
//bindings/pydrake/systems:py/planar_scenegraph_visualizer_test
The label
//bindings/pydrake/systems:planar_scenegraph_visualizer_test
has been removed.
```
- - …
=> [bazel] Tweak drake_py.bzl for clarity

manipulation/util/BUILD.bazel, manipulation/util/make_arm_controller_model.cc, manipulation/util/make_arm_controller_model.h, manipulation/util/test/iiwa7_wsg.dmd.yaml, manipulation/util/test/make_arm_controller_model_test.cc
Toward #17112 
Another PR for porting the Iiwa simulated driver will follow after this one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17865)
=> Port make_arm_controller_model() to Drake

geometry/BUILD.bazel, geometry/proximity/BUILD.bazel, geometry/proximity/make_mesh_from_vtk.cc, geometry/proximity/make_mesh_from_vtk.h, geometry/proximity/test/make_mesh_from_vtk_test.cc, geometry/proximity/volume_mesh.h, geometry/test/non_convex_mesh.vtk, geometry/test/one_negative_tetrahedron.vtk
Support #17780
Predecessor: #17817
Successor: #17828
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17820)
=> [geometry] Make VolumeMesh from VTK specified in geometry::Mesh

bindings/pydrake/visualization/test/meldis_test.py, common/test_utilities/drake_py_unittest_main.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17878)
=> [meldis] Help message in meldis_test

math/rigid_transform.h, math/test/rigid_transform_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17849)
=> Improve RigidTransform unit test

bindings/pydrake/test/all_test.py, bindings/pydrake/visualization/all.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17894)
=> [pydrake] Add missing items to pydrake.visualization.all

tools/wheel/image/build-dependencies.sh, tools/wheel/image/build-wheel.sh, tools/wheel/macos/build-wheel.sh, tools/wheel/macos/test-wheel.sh, tools/wheel/test/test-wheel.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17884)
=> Use [[ instead of [ in wheel scripts

geometry/BUILD.bazel, geometry/make_mesh_for_deformable.cc, geometry/make_mesh_for_deformable.h, geometry/test/make_mesh_for_deformable_test.cc
Towards #16875.
Still a draft since it's waiting for #17820.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17880)
=> [geometry] Make deformable mesh from VTK in mesh specification.

bindings/pydrake/multibody/tree_py.cc, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/multibody_tree_topology.h, multibody/tree/test/multibody_tree_creation_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17557)
=> Throw exception if distal body translates and has zero/NaN mass or rotates and has zero/NaN rotational inertia (towards issue #17081).

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/angle_between_vectors_cost.cc, multibody/inverse_kinematics/angle_between_vectors_cost.h, multibody/inverse_kinematics/inverse_kinematics.cc, multibody/inverse_kinematics/inverse_kinematics.h, multibody/inverse_kinematics/test/angle_between_vectors_cost_test.cc, multibody/inverse_kinematics/test/inverse_kinematics_test.cc
As requested on https://stackoverflow.com/questions/73571388/request-for-addanglebetweenvectorscost
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17821)
=> Add AngleBetweenVectorsCost

doc/_pages/gallery.md, doc/_pages/python_bindings.md, doc/index.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17903)
=> [doc] Add articles section to landing page

tools/workspace/BUILD.bazel, tools/workspace/snopt/BUILD.bazel, tools/workspace/snopt/LICENSE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17904)
=> [workspace] Install license snippet for SNOPT

geometry/optimization/test/graph_of_convex_sets_test.cc
Closes #17912.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17917)
=> [geometry/optimization] Fix GraphOfConvexSet test failure under Mosek

tools/workspace/usockets/repository.bzl, tools/workspace/uwebsockets/repository.bzl
Closes #17910.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17926)
=> [workspace] Upgrade uwebsockets to latest release v20.16.0

manipulation/kuka_iiwa/test/build_iiwa_control_test.cc
Hotfix for #17886.
Closes #17928.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17929)
=> Fix `build_iiwa_control_test` address sanitizer

multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_jacobians_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17920)
=> Add CalcJacobianPositionVector

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17931)
=> [pydrake] Add binding for CalcJacobianPositionVector

common/proto/call_python_client.py
Per https://github.com/matplotlib/matplotlib/issues/20770#issuecomment-890494483
Resolves #17936
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17938)
=> call_python_client: Use newer matplotlib API for 3d plotting

tools/workspace/usockets/repository.bzl, tools/workspace/uwebsockets/repository.bzl
Dear @mwoehlke-kitware ,
The on-call build cop, @BetsyMcPhail, believes that your PR #17926 may have
[linux-focal-clang-bazel-nightly-undefined-behavior-sanitizer](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-focal-clang-bazel-nightly-undefined-behavior-sanitizer/218/)
[linux-focal-clang-bazel-nightly-everything-undefined-behavior-sanitizer](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-focal-clang-bazel-nightly-everything-undefined-behavior-sanitizer/220/)
Therefore, the build cop …
=> Revert "[workspace] Upgrade uwebsockets to latest release v20.16.0"

tools/workspace/petsc/patches/petscimpl.patch, tools/workspace/petsc/repository.bzl
Closes #17908.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17953)
=> [workspace] Upgrade petsc to latest release v3.17.4

bindings/pydrake/manipulation/BUILD.bazel, bindings/pydrake/manipulation/all.py, bindings/pydrake/manipulation/kuka_iiwa_py.cc, bindings/pydrake/manipulation/schunk_wsg_py.cc, bindings/pydrake/manipulation/test/kuka_iiwa_test.py, bindings/pydrake/manipulation/test/schunk_wsg_test.py, bindings/pydrake/manipulation/test/util_test.py, bindings/pydrake/manipulation/util_py.cc
Adds bindings for the ZeroForce, Iiwa & Schunk drivers.
Towards #17112
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17940)
=> [bindings/manipulation] Bind manipulation drivers

tools/workspace/dreal/patches/pull283.patch, tools/workspace/dreal/repository.bzl
See also https://github.com/dreal/dreal4/pull/283.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17970)
=> [workspace] Patch dReal to fix fmt strings

multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/deformable_model.cc, multibody/plant/deformable_model.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/physical_model.h, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/deformable_driver_test.cc, multibody/plant/test/deformable_model_test.cc, multibody/plant/test/dummy_model.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17792)
=> [multibody] Add DeformableDriver

multibody/plant/deformable_model.cc, multibody/plant/deformable_model.h, multibody/plant/test/deformable_model_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17972)
=> [multibody] Add output port for deformable configurations

visualization/visualization_config_functions.cc
To clarify #17814.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17930)
=> [visualization] Add comment on design rationale

multibody/plant/BUILD.bazel, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/test/deformable_driver_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17955)
=> [multibody] Support deformable free motion calculation

bindings/pydrake/manipulation/kuka_iiwa_py.cc, manipulation/kuka_iiwa/build_iiwa_control.h, manipulation/util/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17984)
=> Make make_arm_controller_model externally accessible

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/optimization_py.cc, bindings/pydrake/multibody/test/optimization_test.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17988)
=> [pydrake] Add binding for ContactWrenchFromForceInWorldFrameEvaluator

multibody/plant/test/deformable_driver_contact_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18002)
=> [hotfix] Reconcile difference between #17741 and #17969

doc/_pages/release_playbook.md
Switch to Jammy. Preload nginx for convenience.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18000)
=> [doc] Updates to release playbook for tutorials

solvers/test/rotation_constraint_test.cc
Fixes #17915.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17998)
=> Add tolerance to rotation_constraint_test TestRpyLimits

tools/wheel/image/dependencies/projects.cmake
Hotfix for #17943.
Closes #18010.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18011)
=> [wheel] Use Eigen 3.4 on macOS

bindings/pydrake/geometry_py_scene_graph.cc, bindings/pydrake/lcm_py.cc, bindings/pydrake/test/geometry_scene_graph_test.py, bindings/pydrake/test/lcm_test.py, geometry/BUILD.bazel, geometry/frame_kinematics_vector.h, geometry/kinematics_vector.cc, geometry/kinematics_vector.h, geometry/test/kinematics_vector_test.cc, lcm/drake_lcm.cc, lcm/drake_lcm.h, lcm/test/drake_lcm_test.cc, multibody/inverse_kinematics/global_inverse_kinematics.cc, multibody/inverse_kinematics/global_inverse_kinematics.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18014)
=> [misc] Remove deprecated code 2022-10

tools/install/bazel/drake.BUILD.bazel, tools/install/bazel/repo_template.bzl
Towards https://github.com/RobotLocomotion/drake-external-examples/pull/237.
Follow-up from #17968.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18008)
=> [install] Add lcm and autodiff support to drake_bazel_installed

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/benchmarks_py.cc, bindings/pydrake/multibody/test/benchmarks_test.py
+@jwnimmer-tri for both(?) reviews, please/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18037)
=> [pydrake/multibody] Add bindings for MassDamperSpringAnalyticalSolution

solvers/cost.h, solvers/test/cost_test.cc
Resolves #17989
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18030)
=> Construct EvaluatorCost as a linear transformation of another evaluator

multibody/plant/BUILD.bazel, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/test/deformable_driver_contact_test.cc
Calculate linear dynamics matrices and participating free motion velocities for deformable bodies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17993)
=> DeformableDriver computes dynamic data for contact solver

doc/_pages/release_playbook.md, tools/release_engineering/download_release_candidate.py
Launch the wheel jobs prior to finalizing the tagging
Teach download_release_candidate to download and check the wheels.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18050)
=> [tools] Improve release tooling for wheels

tools/install/bazel/test/drake_bazel_installed_test.py, tools/workspace/abseil_cpp_internal/repository.bzl, tools/workspace/common_robotics_utilities/repository.bzl, tools/workspace/dm_control_internal/repository.bzl, tools/workspace/lcm/repository.bzl, tools/workspace/mypy_internal/repository.bzl, tools/workspace/rules_pkg/repository.bzl, tools/workspace/rules_python/repository.bzl, tools/workspace/sdformat_internal/repository.bzl
Towards #18023.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18028)
=> October 2022 updates

multibody/benchmarking/homecart_global_ik.cc, multibody/parsing/BUILD.bazel, multibody/parsing/detail_dmd_parser.cc, multibody/parsing/detail_dmd_parser.h, multibody/parsing/detail_select_parser.cc, multibody/parsing/parser.h, multibody/parsing/parsing_doxygen.h, multibody/parsing/process_model_directives.cc, multibody/parsing/test/parser_test.cc, multibody/parsing/test/process_model_directives_test/acrobot.dmd.yaml
Relevant to #17390. Usual prototype caveats apply.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17623)
=> [parsing] Add model directives support to Parser

solvers/BUILD.bazel, solvers/defs.bzl, solvers/mosek_solver.cc, solvers/mosek_solver_internal.cc, solvers/mosek_solver_internal.h
Move the internal functions in mosek_solver.cc to mosek_solver_internal.h/cc file, so that we can add unit test in the future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18046)
=> Refactor mosek_solver.cc

bindings/pydrake/manipulation/__init__.py, bindings/pydrake/manipulation/test/util_test.py, bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, examples/hardware_sim/BUILD.bazel, examples/hardware_sim/README.md, examples/hardware_sim/hardware_sim.cc, examples/hardware_sim/hardware_sim.py, examples/hardware_sim/scenario.h, examples/hardware_sim/test/hardware_sim_py_test.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18066)
=> [hardware_sim] Add python flavor of the example

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py, common/pointer_cast.h, common/test/pointer_cast_test.cc, systems/framework/BUILD.bazel, systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/diagram_builder.cc, systems/framework/diagram_builder.h, systems/framework/test/diagram_builder_test.cc, systems/framework/test/diagram_test.cc, visualization/test/visualization_config_functions_test.cc, visualization/visualization_config_functions.cc
Towards #18069.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18078)
=> [framework] Add more by-name sugar to Diagram and DiagramBuilder

multibody/multibody_doxygen.h
Per Slack discussion [here](https://tri-internal.slack.com/archives/C2BMF3K28/p1665534454588219?thread_ts=1665141316.894749&cid=C2BMF3K28).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18092)
=> Minor clarifications to the Notation Basics page

geometry/render_gltf_client/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18104)
=> Fix CI failure by disabling a test

solvers/BUILD.bazel, solvers/defs.bzl, solvers/mosek_solver_internal.cc, solvers/mosek_solver_internal.h, solvers/test/mosek_solver_internal_test.cc
This factored function `ParseLinearExpression` will be used in imposing affine cone constraint in my next PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18085)
=> parse affine expressions in Mosek

bindings/pydrake/multibody/meshcat_py.cc, bindings/pydrake/multibody/test/meshcat_test.py, multibody/meshcat/joint_sliders.cc, multibody/meshcat/joint_sliders.h, multibody/meshcat/test/joint_sliders_test.cc
+@trowell-tri for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18087)
=> [meshcat] Support keycodes in JointSliders

tools/release_engineering/dev/push_release
Relates: #17736.
- This is the current version (ready for focal + jammy) on s3.
- Only change: user must manually set `gpg_key` variable for now, comments added to explain.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18075)
=> [tools] Add push_release script to drake

multibody/plant/multibody_plant.cc
Came across while working on some haptic sim stuff, saw this:
```
...
2. decrease the high gains in your controller whenever possible,
3. switch to a continuous model (discrete update period is zero),      though this might affect the simulation run time.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18111)
=> [multibody] Fix missing newline in discrete solver error message

tools/workspace/meshcat/README.md, tools/workspace/meshcat/repository.bzl
For https://github.com/rdeits/meshcat/pull/116 towards #17319.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18132)
=> [workspace] Upgrade meshcat to latest commit

doc/_pages/apt.md, doc/_pages/bazel.md, doc/_pages/code_review_checklist.md, doc/_pages/code_style_tools.md, doc/_pages/developers.md, doc/_pages/directory_structure.md, doc/_pages/docker.md, doc/_pages/doxygen_instructions.md, doc/_pages/from_binary.md, doc/_pages/from_source.md, doc/_pages/getting_help.md, doc/_pages/installation.md, doc/_pages/pip.md, doc/_pages/reviewable.md, doc/_pages/sphinx_instructions.md, doc/_pages/stable.md, doc/_pages/sublime_text.md
- Fix some link names to better match the linked page.
- Fix some links to refer to the proper destination anchor.
- Fix some broken links.
- A few minor prose edits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18125)
=> [doc] Correct link names and minor edits

bindings/pydrake/geometry_py_visualizers.cc, bindings/pydrake/test/geometry_visualizers_test.py, geometry/meshcat.h, geometry/test/meshcat_manual_test.cc
Resolves #18096.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18100)
=> [meshcat] Add a binding/doc/test for SetTriangleColorMesh

doc/_pages/release_playbook.md
Update Release Playbook to use the new link. 
Towards #17869
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18142)
=> [doc] Jenkins jobs have been renamed from M1 to ARM

multibody/plant/test/multibody_plant_symbolic_test.cc
To assist with #17996.  (High priority because it's blocking another PR.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18146)
=> [plant] Reduce symbolic test sensitivity to implementation details

manipulation/util/BUILD.bazel, manipulation/util/show_model.py, manipulation/util/test/show_model_test.py
Refactor the existing show_model code into a new ModelVisualizer class to simplify the use of this code and prepare the way for migrating this to pydrake.
Towards #17689.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18137)
=> Refactor show_model into a future library class

solvers/mosek_solver.cc, solvers/mosek_solver_internal.cc, solvers/mosek_solver_internal.h, solvers/test/mosek_solver_internal_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18114)
=> Add affine cone constraint in Mosek.

multibody/plant/BUILD.bazel, multibody/plant/deformable_driver.h, multibody/plant/test/deformable_integration_test.cc
The test exercises the entire discrete update for deformable simulation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18105)
=> [multibody] Add deformable integration test

multibody/parsing/test/parser_test.cc
And repair some changes missed as a result.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18155)
=> [parsing] Fix a deprecation typo

setup/ubuntu/source_distribution/packages-focal-test-only.txt, setup/ubuntu/source_distribution/packages-jammy-test-only.txt
Towards #17597.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18166)
=> [setup] Add ubuntu testonly dependency on python3-opencv

common/symbolic/trigonometric_polynomial.cc, common/symbolic/trigonometric_polynomial.h, multibody/rational/BUILD.bazel, multibody/rational/rational_forward_kinematics.cc, multibody/rational/rational_forward_kinematics.h, multibody/rational/test/rational_forward_kinematics_test.cc
This class computes the link poses as rational function of the stereographic projection variables.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/17572)
=> Add RationalForwardKinematics class.

multibody/multibody_doxygen.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18174)
=> Improve documentation for spatial forces.

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py, math/rigid_transform.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18173)
=> Python bind RigidTransform::GetMaximumAbsoluteTranslationalDifference, etc.

math/rotation_matrix.h, math/test/rotation_matrix_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18172)
=> [math] Add RotationMatrix::ToRollPitchYaw()

bindings/pydrake/visualization/meldis.py, geometry/meshcat_point_cloud_visualizer.h, geometry/meshcat_visualizer.h, geometry/meshcat_visualizer_params.h, multibody/meshcat/contact_visualizer_params.h, multibody/meshcat/joint_sliders.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18181)
=> Correct comment typos

solvers/cost.cc, solvers/ipopt_solver_common.cc, solvers/mathematical_program.h, solvers/snopt_solver.cc, solvers/snopt_solver_common.cc, solvers/test/ipopt_solver_test.cc, solvers/test/optimization_examples.cc, solvers/test/optimization_examples.h, solvers/test/snopt_solver_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18184)
=> [solvers] Support L2NormCost in SnoptSolver and IpoptSolver.

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18187)
=> [math] Python binding for RotationMatrix::ToRollPitchYaw().

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/iris.cc, geometry/optimization/iris.h, geometry/optimization/test/iris_in_configuration_space_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18136)
=> [geometry/optimization] Allow IrisInConfigurationSpace to optionally consider configuration space obstacles

multibody/rational/BUILD.bazel, multibody/rational/test/rational_forward_kinematics_test.cc
As discussed in https://drakedevelopers.slack.com/archives/C270MN28G/p1666874969442129
closes #18193
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18197)
=> Split rational_forward_kinematics_test.cc

bindings/pydrake/visualization/test/model_visualizer_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18199)
=> [visualization] Avoid using webbrowser in unit test

multibody/plant/contact_properties.cc, multibody/plant/contact_properties.h, multibody/plant/test/contact_properties_test.cc
Additional helper methods as needed in #18170.
Towards #16955 and #13888.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18188)
=> Implements additional helper methods to retrieve contact properties

bindings/pydrake/common/serialize_pybind.h, bindings/pydrake/common/test/serialize_pybind_test.py
Minor bug when scanning code when doing #18204
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18207)
=> py serialize: Add mising .Finished() for no-doc case

tools/workspace/os.bzl
This opens the door for macOS Ventura (13) support.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18210)
=> [workspace] Don't abort for unsupported macOS versions

multibody/inverse_kinematics/global_inverse_kinematics.cc
Same as we did in #17572
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18211)
=> Do not use dynamic_cast to control flow in global IK

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18214)
=> [pydrake] Add bindings for MultibodyPlant::set_discrete_contact_solver

solvers/BUILD.bazel, solvers/mosek_solver_internal.cc, solvers/mosek_solver_internal.h, solvers/test/mosek_solver_internal_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18185)
=> Replace quadratic cost with affine cone constraint and linear cost.

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, bindings/pydrake/visualization/_model_visualizer.py, multibody/benchmarking/homecart_global_ik.cc, multibody/parsing/detail_dmd_parser.cc, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/test/parser_manual_test.cc, multibody/parsing/test/parser_test.cc, multibody/plant/multibody_plant.h, planning/test/robot_diagram_test.cc
No deprecations yet; just add the new modernized method.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18208)
=> [parsing] Modernize parser.AddAllModelsFromFile

bindings/pydrake/systems/test/trajectory_optimization_test.py, bindings/pydrake/systems/trajectory_optimization_py.cc, systems/trajectory_optimization/BUILD.bazel, systems/trajectory_optimization/kinematic_trajectory_optimization.cc, systems/trajectory_optimization/kinematic_trajectory_optimization.h, systems/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Implements kinematic trajectory optimization using
B-spline trajectories.
This is my re-implementation of code written by Andrés Valenzuela
<andres.valenzuela@tri.global>; with a new interface and
implementation, but the same basic formulation.
Resolves #10188.
+@aykut-tri for feature review, please
+@tobiamarcucci for additional math review, please
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18190)
=> [planning] Adds KinematicTrajectoryOptimization

bindings/pydrake/systems/test/sensors_test.py
A step towards #18237 and #16502.
The overall goal is to have Python test coverage of libjpeg image decoding (which we perform in Drake via VTK) so that we can be confident in our VTK build system updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18245)
=> [pydrake] Improve unit test demo/coverage for lcmt_image_array

tools/workspace/abseil_cpp_internal/repository.bzl, tools/workspace/dm_control_internal/repository.bzl, tools/workspace/petsc/repository.bzl, tools/workspace/ros_xacro_internal/repository.bzl, tools/workspace/styleguide/repository.bzl, tools/workspace/tinyobjloader/repository.bzl, tools/workspace/typing_extensions_internal/repository.bzl
Towards #18232
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18244)
=> November 2022 updates

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/tree/body.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18242)
=> Complete deprecation of get_default_mass()

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic/BUILD.bazel, common/symbolic/monomial_util.cc, common/symbolic/monomial_util.h, common/symbolic/test/monomial_util_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18222)
=> Compute monomial basis with the degree for each variable <= 1

bindings/pydrake/manipulation/kuka_iiwa_py.cc, bindings/pydrake/manipulation/test/kuka_iiwa_test.py, manipulation/kinova_jaco/jaco_command_receiver.cc, manipulation/kinova_jaco/jaco_command_receiver.h, manipulation/kinova_jaco/jaco_command_sender.cc, manipulation/kinova_jaco/jaco_command_sender.h, manipulation/kinova_jaco/jaco_status_receiver.cc, manipulation/kinova_jaco/jaco_status_receiver.h, manipulation/kinova_jaco/jaco_status_sender.cc, manipulation/kinova_jaco/jaco_status_sender.h, manipulation/kinova_jaco/test/jaco_command_receiver_test.cc, manipulation/kinova_jaco/test/jaco_command_sender_test.cc, manipulation/kinova_jaco/test/jaco_status_receiver_test.cc, manipulation/kinova_jaco/test/jaco_status_sender_test.cc, manipulation/kuka_iiwa/iiwa_command_receiver.cc, manipulation/kuka_iiwa/iiwa_command_receiver.h, manipulation/kuka_iiwa/iiwa_command_sender.cc, manipulation/kuka_iiwa/iiwa_command_sender.h, manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc, manipulation/kuka_iiwa/test/iiwa_command_sender_test.cc
Also updates the names on some iiwa ports.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18220)
=> Add jaco lcm time input/output ports

tools/workspace/pkg_config.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18256)
=> [typo] reserve => reverse

geometry/test/meshcat_manual_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18273)
=> [meshcat] Remove stale reference to #15965 in meshcat_manual_test

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py
Would like to use this to copy state to a non-root context
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18267)
=> py systems: Bind SetStateAndParametersFrom

tools/workspace/usockets/repository.bzl, tools/workspace/uwebsockets/repository.bzl
Closes #17910.
See also https://github.com/uNetworking/uWebSockets/issues/1512.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18259)
=> [workspace] Upgrade usockets and uwebsockets

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/plant/test/multibody_plant_test.cc, multibody/tree/fixed_offset_frame.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18198)
=> Deprecate FixedOffsetFrame::SetPoseInBodyFrame() for SetPoseInParentFrame()

bindings/pydrake/perception_py.cc, bindings/pydrake/test/perception_test.py, perception/BUILD.bazel, perception/point_cloud.cc, perception/point_cloud.h, perception/test/point_cloud_test.cc
@RussTedrake do you have examples of pointcloud voxel filter and normal estimation that would be good for benchmarking?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18216)
=> Parallelize pointcloud operations with OpenMP and use CRU DSHVG for voxel filter

multibody/tree/rigid_body.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18251)
=> Improve documentation for RigidBody::SetCenterOfMassInBodyFrame()

multibody/plant/BUILD.bazel, multibody/plant/test/multibody_plant_forward_dynamics_test.cc, multibody/tree/BUILD.bazel, multibody/tree/articulated_body_inertia_cache.h, multibody/tree/body_node.cc, multibody/tree/body_node.h, multibody/tree/test/body_node_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18153)
=> MultibodyPlant sometimes throws an exception for invalid mass/inertia properties

doc/_pages/release_playbook.md, tools/release_engineering/download_release_candidate.py, tools/wheel/wheel_builder/linux.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18148)
=> [release] Update release playbook for new staging jobs

bindings/pydrake/multibody/parsing_py.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18283)
=> [pydrake] Add PopulateFromRosPackagePath docstring

bindings/pydrake/visualization/_model_visualizer.py, bindings/pydrake/visualization/test/model_visualizer_test.py
These fixes are necessary in order to replace the model_inspector function in authoring_multibody_simulation with the ModelVisualizer class.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18284)
=> Add a Stop Running button and Meshcat reuse to ModelVisualizer

doc/_pages/buildcop.md
* Modified TRI hours
* Use issues, not googledoc, to track recurring failures
* Note d-e-e and documentation builds
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18282)
=> Update buildcop instructions to match recent practice

bindings/pydrake/visualization/meldis.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18293)
=> [visualization] Do not show stack trace for meldis on sigint

solvers/gurobi_solver.cc, solvers/test/gurobi_solver_test.cc, solvers/test/mosek_solver_test.cc, solvers/test/second_order_cone_program_examples.cc, solvers/test/second_order_cone_program_examples.h
As mentioned in #18275
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18291)
=> Gurobi handles duplicated variables in its linear constraints.

geometry/render_gltf_client/test/integration_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18298)
=> Disable glTF integration test on macOS

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/BUILD.bazel, common/trajectories/stacked_trajectory.cc, common/trajectories/stacked_trajectory.h, common/trajectories/test/stacked_trajectory_test.cc
Closes #17990.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18192)
=> [trajectories] Add StackedTrajectory

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/all.py, bindings/pydrake/multibody/fem_py.cc, bindings/pydrake/multibody/test/fem_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18308)
=> [bindings] Add bindings for DeformableBodyConfig

geometry/render_gltf_client/test/integration_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18332)
=> [geometry/render_gltf_client] disable integration test on macOS

multibody/tree/BUILD.bazel, multibody/tree/rigid_body.h, multibody/tree/test/rigid_body_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18304)
=> Add tests for RigidFrame::SetCenterOfMassInBodyFrame

bindings/pydrake/BUILD.bazel, bindings/pydrake/all.py, bindings/pydrake/test/all_test.py, bindings/pydrake/test/print_symbol_collisions.py
Resolves #18353
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18357)
=> [py all] Add Preferred Ordering mechanism and tests

tools/workspace/optitrack_driver/repository.bzl
This is a breaking change to the optitrack LCM types.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18330)
=> workspace: Update optitrack_driver for skeleton support

solvers/gurobi_solver.cc, solvers/test/gurobi_solver_test.cc
This best effort solution is reported by Gurobi, including both the primal and dual solution. The solution is reported for every *non-error* status of the solver, whether it is infeasible/unbounded/hitting iteration limit, etc.
Resolves #18366
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18367)
=> GurobiSolver always returns the best effort solution.

bindings/pydrake/multibody/optimization_py.cc, bindings/pydrake/multibody/test/optimization_test.py, multibody/optimization/BUILD.bazel, multibody/optimization/spatial_velocity_constraint.cc, multibody/optimization/spatial_velocity_constraint.h, multibody/optimization/test/spatial_velocity_constraint_test.cc
Implements a constraint on the spatial velocity of a point (in a relative frame).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18364)
=> [multibody/optimization] Add SpatialVelocityConstraint

examples/hydroelastic/python_nonconvex_mesh/drop_pepper.py
This is another file that was missed in prior passes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18372)
=> [parsing] Port to parser.AddModels, part 4

geometry/optimization/dev/collision_geometry.cc, geometry/optimization/dev/collision_geometry.h, geometry/optimization/dev/test/collision_geometry_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18375)
=> Support sphere and capsule in C-IRIS collision geometry.

solvers/gurobi_solver.cc
Replaces #18377
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18378)
=> Fix a memory bug when setting gurobi dual solution.

solvers/scs_solver.cc, solvers/test/scs_solver_test.cc
Include dual solution for bounding-box, linear, second order cone constraints.
I will add the dual solution for linear equality constraints in the next PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18360)
=> ScsSolver result reports dual solution.

multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18382)
=> Change sprintf() to snprintf() to avoid security warnings/errors.

doc/_pages/gallery.md
Point to an example of hydroelastic contact between non-convex meshes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18386)
=> [doc] Add hydroelastic example to the drake gallery.

multibody/math/spatial_acceleration.h, multibody/math/spatial_velocity.h, multibody/math/test/spatial_algebra_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18373)
=> Improve documentation and tests for ComposeWithMovingFrameVelocity().

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/world_joint_test.sdf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18322)
=> [parsing] Add SDFormat support for //world/joint

geometry/optimization/dev/BUILD.bazel, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/separating_plane.cc, geometry/optimization/dev/separating_plane.h, geometry/optimization/dev/test/cspace_free_polytope_test.cc, multibody/rational/rational_forward_kinematics.h, multibody/rational/test/rational_forward_kinematics_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18384)
=> add CspaceFreeRegion class constructor.

solvers/snopt_solver.cc, solvers/test/nonlinear_program_test.cc, solvers/test/optimization_examples.cc, solvers/test/optimization_examples.h, solvers/test/snopt_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18401)
=> Snopt handles duplicated variables.

multibody/plant/deformable_driver.cc, multibody/plant/test/deformable_driver_contact_kinematics_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18371)
=> [deformable] Zero out jacobian columns for dofs under bc

geometry/test/meshcat_manual_test.cc
* Fix sphere disappearance
* Fix blue box disappearance
* Cleanup: remove some redundant Eigen:: qualifiers
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18392)
=> [geometry] Fix meshcat_manual_test bugs

solvers/scs_solver.cc, solvers/test/gurobi_solver_test.cc, solvers/test/linear_program_examples.cc, solvers/test/linear_program_examples.h, solvers/test/mosek_solver_test.cc, solvers/test/scs_solver_test.cc
A step towards #13285
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18388)
=> ScsSolver returns the dual solution for linear equality constraints.

multibody/plant/test/contact_properties_test.cc
Alternative to current code in #18399.
This now tests the behavior of interaction w/ scalar conversion, and confirms behavior fix in #18397.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18403)
=> [multibody] Add testing for scalar promotion from double to AutoDiffXd

planning/BUILD.bazel, planning/robot_collision_type.h, planning/test/robot_collision_type_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18405)
=> [planning] Add RobotCollisionType

tools/workspace/abseil_cpp_internal/repository.bzl, tools/workspace/dm_control_internal/repository.bzl, tools/workspace/gz_math_internal/repository.bzl, tools/workspace/lcm/repository.bzl, tools/workspace/mypy_internal/repository.bzl, tools/workspace/petsc/repository.bzl, tools/workspace/pycodestyle/repository.bzl, tools/workspace/rules_pkg/repository.bzl, tools/workspace/rules_python/repository.bzl
Towards #18379
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18394)
=> Upgrade Externals December 2022

geometry/optimization/dev/collision_geometry.cc, geometry/optimization/dev/collision_geometry.h, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/separating_plane.h, geometry/optimization/dev/test/c_iris_test_utilities.cc, geometry/optimization/dev/test/c_iris_test_utilities.h, geometry/optimization/dev/test/collision_geometry_test.cc, geometry/optimization/dev/test/cspace_free_polytope_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18400)
=> Add CspaceFreePolytope::GenerateRationals.

multibody/plant/test/multibody_plant_forward_dynamics_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18329)
=> Improve tests for non-positive definite articulated hinge inertia matrices.

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
.. to prepare for adding yet another Joint class binding.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18419)
=> [bindings] Alphabetize joint code

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18420)
=> [bindings] Add bindings for QuaternionFloatingJoint

planning/BUILD.bazel, planning/robot_clearance.cc, planning/robot_clearance.h, planning/test/robot_clearance_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18418)
=> [planning] Add RobotClearance

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/general_test.py
Towards #13581
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18430)
=> [py systems] Bind System.{AllocateInputVector,AllocateInputAbstract}

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic/monomial_util.h, common/symbolic/polynomial.h, common/symbolic/test/polynomial_test.cc
This is useful in Sum-of-Squares optimization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18429)
=> Compute a polynomial from monomial basis and the lower triangular of the Gram.

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py, systems/framework/BUILD.bazel, systems/framework/input_port.cc, systems/framework/input_port.h, systems/framework/test/input_port_test.cc
Resolves #13581
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18431)
=> [input_port] Add Allocate() method

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/test/hpolyhedron_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18432)
=> Add HPolyhedron::FindRedundant

geometry/optimization/dev/BUILD.bazel, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/c_iris_test_utilities.cc, geometry/optimization/dev/test/cspace_free_polytope_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18444)
=> [C-IRIS] Construct the program to search for the separating plane

multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/tree/geometry_spatial_inertia.cc, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/articulated_body_inertia_test.cc, multibody/tree/test/spatial_inertia_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18407)
=> New SpatialInertia factory method for SolidBox.

setup/ubuntu/source_distribution/packages-focal.txt, setup/ubuntu/source_distribution/packages-jammy.txt, tools/workspace/default.bzl, tools/workspace/googlebenchmark/repository.bzl, tools/workspace/libpfm4/BUILD.bazel, tools/workspace/libpfm4/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18447)
=> Google Benchmark 2-step update

planning/BUILD.bazel, planning/collision_checker_context.cc, planning/collision_checker_context.h, planning/test/collision_checker_context_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18428)
=> [planning] Add CollisionCheckerContext

planning/BUILD.bazel, planning/body_shape_description.cc, planning/body_shape_description.h, planning/test/body_shape_description_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18424)
=> [planning] Add BodyShapeDescription

geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/cspace_free_polytope_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18461)
=> [C-IRIS] Add unit length vector constraint when searching for separating plane

geometry/optimization/dev/BUILD.bazel, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/cspace_free_polytope_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18474)
=> [C-IRIS] search many separating planes in parallel.

geometry/optimization/dev/collision_geometry.cc, geometry/optimization/dev/collision_geometry.h, geometry/optimization/dev/test/collision_geometry_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18475)
=> [C-IRIS] compute the distance from a halfspace to a collision geometry.

geometry/optimization/dev/test/cspace_free_polytope_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18478)
=> buildcop: Disable a test failing TSAN

planning/BUILD.bazel, planning/collision_checker_params.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18473)
=> [planning] Add CollisionCheckerParams

geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/cspace_free_polytope_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18485)
=> Create the CspaceFreePolytope rationals at object construction

doc/_pages/buildcop.md
Closes #17806.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18455)
=> [doc] Add direct links for buildcop cache server checks

geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/cspace_free_polytope_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18484)
=> [C-IRIS] Add a public function to search for separation certificate for a given polytope.

doc/_pages/gallery.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18489)
=> [doc] add carrot scooping video to the drake gallery

bindings/pydrake/geometry_py_optimization.cc, bindings/pydrake/test/geometry_optimization_test.py, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/test/hpolyhedron_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18493)
=> [geometry] Construct an HPoyhedron from a VPolytope.

geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/cspace_free_polytope_test.cc
Given the Lagrangian, find the C-space polytope {s | C*s<=d}.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18497)
=> [C-IRIS] construct polytope search program.

geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/cspace_free_polytope_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18499)
=> [C-IRIS] Add bilinear alternation to CspaceFreePolytope.

geometry/optimization/dev/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18504)
=> [C-IRIS] increase timeout for cspace_free_polytope_test

geometry/optimization/dev/collision_geometry.cc, geometry/optimization/dev/collision_geometry.h, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/collision_geometry_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18500)
=> [C-IRIS] allow the user to set the constant multiplier for poytope Chebyshev center.

geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/hpolyhedron.cc
We have fixed the duplicated variable issue in the solvers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18502)
=> Add LorentzCone constraint using non-symbolic form in HPolyhedron.

planning/BUILD.bazel
Amends #18424.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18519)
=> [planning] Fix typo in BUILD file

doc/_pages/release_playbook.md, doc/_pages/reviewable.md, doc/_release-notes/template.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18523)
=> [doc] Remove "newly bound" itemization

bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/analysis_test.py, multibody/inverse_kinematics/BUILD.bazel, systems/analysis/simulator_config_functions.cc, systems/analysis/simulator_config_functions.h, systems/analysis/test/simulator_config_functions_test.cc
Follow-up from #17654 and #17585.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18533)
=> Remove deprecated code 2022-11

bindings/pydrake/systems/framework_py_semantics.cc, systems/framework/BUILD.bazel, systems/framework/input_port.cc, systems/framework/input_port.h, systems/framework/input_port_base.cc, systems/framework/input_port_base.h, systems/framework/system.cc, systems/framework/test/input_port_test.cc
Amends #18431.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18525)
=> [framework] Fix physical dependencies for InputPort::Allocate

multibody/plant/tamsi_solver.cc
Towards #14590.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18543)
=> [multibody] Change a user-facing error to throw, not abort

geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/cspace_free_polytope_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18505)
=> [C-IRIS] Find C-space polytope through binary search.

tools/skylark/README.md
Follow-up from #18546.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18560)
=> [tools] Improve documentation of num_threads

systems/lcm/BUILD.bazel
Closes #18346
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18561)
=> Mark lcm_interface_system_test as Flaky

tools/workspace/gurobi/repository.bzl
Amends 2fbd72faeaa1a76641116c78f8b9be8f9e475d5b.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18563)
=> [workspace] Hotfix for Gurobi path searching

setup/ubuntu/source_distribution/packages-focal-maintainer-only.txt, setup/ubuntu/source_distribution/packages-jammy-maintainer-only.txt, tools/workspace/README.md, tools/workspace/new_release.py
Modify `new_release` to accept more than one external at a time, and to directly commit the changes, rather than prompting the user to do so. Update documentation to reflect the new usage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18548)
=> Improve new_release script

manipulation/util/make_arm_controller_model.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18575)
=> Port to parser.AddModels, part 5

manipulation/util/test/make_arm_controller_model_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18577)
=> Port to parser.AddModels, part 6

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/test/yaml_typed_test.py, bindings/pydrake/common/yaml.py
Towards https://github.com/RobotLocomotion/drake/pull/18566 (and therefore https://github.com/RobotLocomotion/drake/issues/17112).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18572)
=> [pydrake] Add pybind11 support to yaml_load_typed

geometry/render_gltf_client/BUILD.bazel, tools/install/libdrake/build_components.bzl, tools/workspace/curl_internal/package.BUILD.bazel, tools/workspace/vtk/repository.bzl
Closes #18423.
Reverts #17697.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18480)
=> [geometry] Promote RenderEngineGltfClient to public

tools/release_engineering/dev/README.md, tools/release_engineering/dev/push_release
* Remove commented out Colab support, this option is no longer needed.
* Add examples of commands needed to add a package or repository.
* Add a README describing the current process for docker and apt releases
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18487)
=> [tools] Update push_release script

bindings/pydrake/BUILD.bazel, bindings/pydrake/geometry_py_common.cc, bindings/pydrake/test/geometry_common_test.py, common/yaml/test/example_structs.h, common/yaml/test/yaml_read_archive_test.cc, common/yaml/yaml_read_archive.h, geometry/rgba.cc, geometry/rgba.h, geometry/test/rgba_test.cc
Rewrite serialization to add python bindings.
Towards https://github.com/RobotLocomotion/drake/pull/18566 (and therefore https://github.com/RobotLocomotion/drake/issues/17112).
Requires #18572 first.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18571)
=> [geometry] Add array-based getters and setters to Rgba

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/schema_py.cc, bindings/pydrake/common/test/schema_test.py, common/schema/stochastic.cc, common/schema/stochastic.h
Towards https://github.com/RobotLocomotion/drake/pull/18581 for https://github.com/RobotLocomotion/drake/pull/18566 (and therefore https://github.com/RobotLocomotion/drake/issues/17112).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18567)
=> [pydrake] Bind fixed-size DistributionVector classes

bindings/pydrake/geometry_py_render.cc, bindings/pydrake/test/geometry_render_test.py, geometry/render_gltf_client/BUILD.bazel, geometry/render_gltf_client/render_engine_gltf_client_params.h
Add python binding for RenderEngineGltfClient. 
Added tests. 
+@zachfang
Close #18347 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18387)
=> Add python binding for RenderEngineGltfClient

multibody/parsing/test/parser_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18585)
=> [parsing] Simplify tests of deprecated AddModelFromString

bindings/pydrake/multibody/test/plant_test.py, multibody/tree/body.h
Cleans up outdated/incorrect/messy comments in multibody::Body.
Resolves #18570
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18578)
=> [multibody] Clean up some Body comments

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/tree/BUILD.bazel, multibody/tree/geometry_spatial_inertia.cc, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/geometry_spatial_inertia_test.cc, multibody/tree/test/spatial_inertia_test.cc, multibody/tree/test/unit_inertia_test.cc, multibody/tree/unit_inertia.cc, multibody/tree/unit_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18483)
=> Add more shapes to SpatialInertia factories

planning/BUILD.bazel, planning/collision_avoidance.cc, planning/collision_avoidance.h, planning/test/collision_avoidance_test.cc
+@sherm1 for platform review per schedule, please.  This code has already been feature-reviewed in Anzu.
\CC @calderpg-tri @rpoyner-tri @SeanCurtis-TRI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18608)
=> [planning] Add ComputeCollisionAvoidanceDisplacement

examples/hardware_sim/BUILD.bazel, examples/hardware_sim/README.md, examples/hardware_sim/hardware_sim.py, examples/hardware_sim/test/hardware_sim_cc_test.py, examples/hardware_sim/test/hardware_sim_test_common.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18566)
=> [examples] Add main and yaml parsing to python hardware_sim

geometry/optimization/dev/collision_geometry.cc, geometry/optimization/dev/test/c_iris_test_utilities.cc, geometry/optimization/dev/test/c_iris_test_utilities.h, geometry/optimization/dev/test/collision_geometry_test.cc, geometry/optimization/dev/test/cspace_free_polytope_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18613)
=> [C-IRIS] support cylinder geometry.

planning/test/collision_avoidance_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18624)
=> [planning] Hotfix unit test for ARM machine precision

geometry/optimization/dev/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18621)
=> Disable cspace_free_polytope_test to appease CI

planning/body_shape_description.cc, planning/collision_checker_context.cc, planning/test/body_shape_description_test.cc, planning/test/collision_avoidance_test.cc, planning/test/collision_checker_test.cc, planning/test/robot_collision_type_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18628)
=> [planning] Fix malformed include statements

CMakeLists.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18637)
=> [cmake] Set same bazel minimum version as WORKSPACE

doc/_pages/credits.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18643)
=> add Alexandre Amice to contributors

common/symbolic/polynomial.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18641)
=> fix small typo in polynomial.h

math/discrete_lyapunov_equation.cc, math/test/discrete_lyapunov_equation_test.cc
Fixes #17634
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18600)
=> Fix a bug in DiscreteLyapunovEquation

solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc, solvers/test/mosek_solver_test.cc
Reverts RobotLocomotion/drake#18562
Dear @hongkai-dai ,
The on-call build cop, @SeanCurtis-TRI , believes that your PR #18562 may have
- https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-arm-monterey-clang-bazel-nightly-address-sanitizer/79/
- https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-arm-monterey-clang-bazel-nightly-debug/78/
- https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-x86-monterey-clang-bazel-nightly-address-sanitizer/78/
- …
=> Revert "Add bounding box or rotated lorentz cone constraint for small psd matrices"

planning/BUILD.bazel, planning/scene_graph_collision_checker.cc, planning/scene_graph_collision_checker.h, planning/test/collision_checker_test.cc, planning/test/planning_test_helpers.cc, planning/test/planning_test_helpers.h, planning/test/scene_graph_collision_checker_test.cc, planning/test_utilities/BUILD.bazel, planning/test_utilities/collision_checker_abstract_test_suite.cc, planning/test_utilities/collision_checker_abstract_test_suite.h, planning/test_utilities/collision_ground_plane.sdf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18629)
=> [planning] Add SceneGraphCollisionChecker

bindings/pydrake/visualization/test/meldis_test.py, geometry/test/meshcat_visualizer_test.cc, multibody/meshcat/test/contact_visualizer_test.cc, multibody/meshcat/test/joint_sliders_test.cc, multibody/plant/test/applied_generalized_force_test.cc, multibody/plant/test/internal_geometry_names_test.cc, multibody/plant/test/multibody_plant_introspection_test.cc, multibody/plant/test/multibody_plant_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18646)
=> Port to parser.AddModels, part 7

geometry/optimization/dev/BUILD.bazel, geometry/optimization/dev/separating_plane.h, geometry/optimization/dev/test/c_iris_test_utilities.cc, geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc, geometry/optimization/dev/test/separating_plane_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18651)
=> [C-IRIS] fix a bug in the separating plane.

setup/mac/install_prereqs.sh, setup/mac/source_distribution/Brewfile-maintainer-only, setup/mac/source_distribution/install_prereqs.sh, setup/mac/source_distribution/requirements-maintainer-only.txt
Closes https://github.com/RobotLocomotion/drake/issues/14754
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18665)
=> Deprecate `--with-maintainer-only` install flag on macOS

bindings/pydrake/common/cpp_param_pybind.cc, bindings/pydrake/common/cpp_param_pybind.h, bindings/pydrake/common/test/value_test.py, bindings/pydrake/common/value_py.cc, bindings/pydrake/systems/test/custom_test.py
Resovles #18653
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18655)
=> [py value] Ensure Value[object].SetFrom() deep copies the value

geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18667)
=> [C-IRIS] include HPolyhedron {s | C*s<=d, s_lower <= s <= s_upper} in the result.

setup/ubuntu/source_distribution/install_prereqs.sh, tools/workspace/pybind11/mkdoc.py
Closes #18370.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18669)
=> [setup] Automatically fix GCC 12 installation mistakes on Jammy

bindings/pydrake/visualization/_meldis.py, bindings/pydrake/visualization/test/meldis_test.py
Closes #18620.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18671)
=> [meldis] Fix deprecation warning spam

doc/_pages/code_style_tools.md, doc/_pages/developers.md, doc/_pages/emacs.md, doc/_pages/vscode.md
Towards #18175.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18681)
=> [doc] Add VS Code and Emacs integration tips

common/symbolic/test/codegen_test.cc, common/symbolic/test/latex_test.cc, common/symbolic/test/trigonometric_polynomial_test.cc, common/test/eigen_types_test.cc, common/trajectories/test/piecewise_polynomial_generation_test.cc, examples/fibonacci/fibonacci_difference_equation.h, examples/fibonacci/run_fibonacci.cc, examples/pendulum/pendulum_parameters_derivatives.cc, geometry/benchmarking/render_benchmark.cc, geometry/proximity/mesh_to_vtk.cc, manipulation/models/wsg_50_description/sdf/test/wsg_50_sdf_test.cc, math/test/rotation_conversion_test.cc, multibody/tree/body_node.cc, perception/test/point_cloud_flags_test.cc, tools/lint/drakelint.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18693)
=> [tools] Add linter for unnecessary iostream includes

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/scalar_conversion_test.py, systems/framework/BUILD.bazel, systems/framework/system.cc, systems/framework/system.h, systems/framework/system_base.cc, systems/framework/system_base.h, systems/framework/test/leaf_system_test.cc
Closes #18212.
\CC @adeeb10abbas @EricCousineau-TRI FYI
+@sherm1 for platform review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18687)
=> [framework] Add System::Clone

bindings/pydrake/planning/BUILD.bazel, bindings/pydrake/planning/planning_py.cc, bindings/pydrake/planning/planning_py.h, bindings/pydrake/planning/planning_py_collision_checker.cc, bindings/pydrake/planning/planning_py_collision_checker_interface_types.cc, bindings/pydrake/planning/test/collision_checker_test.py, planning/collision_checker.h, planning/unimplemented_collision_checker.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18670)
=> [pydrake] Bind planning.CollisionChecker and related

multibody/tree/rigid_body.cc, multibody/tree/rigid_body.h, multibody/tree/test/rigid_body_test.cc, multibody/tree/unit_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18582)
=> Function that shifts a body's center of mass location and preserves its central unit inertia.

multibody/tree/rotational_inertia.h, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/rigid_body_test.cc, multibody/tree/test/spatial_inertia_test.cc, multibody/tree/test/unit_inertia_test.cc, multibody/tree/unit_inertia.cc, multibody/tree/unit_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18618)
=> Add tetrahedron to SpatialInertia and UnitInertia.

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic/trigonometric_polynomial.h, systems/framework/system.h
Closes #18688.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18716)
=> Remove deprecated code 2023-02

bindings/pydrake/systems/trajectory_optimization_py.cc
This makes use of the binding style of declaring a block for each unique class and defining the Class (and associated) alias.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18721)
=> [pydrake] Clean up binding code for trajectory_optimization_py.cc

planning/collision_checker.cc
Currently, `CollisionChecker::GenerateFilteredCollisionMatrix` calls `MbP::GetBodiesWeldedTo(body)` `num_bodies^2` times to check if pairs of bodies are welded together. Replaces this by calling `MbP::GetBodiesWeldedTo(body)` once per body and saving the results in an `unordered_set` for checking later.
cc @sadraddini
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18718)
=> [planning] Improve welded body check in CollisionChecker

doc/_pages/troubleshooting.md
Fixes #17924.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18722)
=> Add pip troubleshooting documentation

multibody/plant/multibody_plant.h
Delete a stale done TODO.
Point a TODO to a newly filed issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18733)
=> [multibody] Update some TODOs in multibody_plant.h

geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18739)
=> [C-IRIS] bring InitializePolytopeSearchProgram to public.

geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
Certifies if a single pair of geometry is separable or not.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18742)
=> [C-IRIS] add IsGeometrySeparable function.

geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
Closes #18759.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18760)
=> fix c_iris tests

bindings/pydrake/planning/BUILD.bazel, bindings/pydrake/planning/planning_py_robot_diagram.cc, bindings/pydrake/planning/test/collision_checker_test.py, bindings/pydrake/planning/test/robot_diagram_test.py, planning/robot_diagram_builder.cc, planning/robot_diagram_builder.h, planning/test/body_shape_description_test.cc, planning/test/collision_avoidance_test.cc, planning/test/collision_checker_context_test.cc, planning/test/collision_checker_test.cc, planning/test/planning_test_helpers.cc, planning/test/robot_diagram_test.cc, planning/test/scene_graph_collision_checker_test.cc, planning/test/unimplemented_collision_checker_test.cc
This is less verbose and more consistent with `DiagramBuilder()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18770)
=> Rename RobotDiagram::BuildDiagram() => Build()

multibody/optimization/test/toppra_test.cc
Closes #18778.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18779)
=> [toppra] Use larger unit test tolerance (for macOS arm64)

geometry/optimization/dev/BUILD.bazel, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18777)
=> [C-IRIS] bring back cspace_free_polytope_with_mosek_test.

tools/workspace/tinyobjloader/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18785)
=> [workspace] Upgrade tinyobjloader to latest commit

bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/meldis.py, bindings/pydrake/visualization/model_visualizer.py, bindings/pydrake/visualization/run_installed_meldis.py.in, bindings/pydrake/visualization/run_installed_model_visualizer.py.in, bindings/pydrake/visualization/test/visualization_install_tests.py, tools/workspace/drake_visualizer/drake_visualizer_disabled.py
Closes #18751.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18764)
=> [install] Add shortcuts for meldis and model_visualizer

.clang-format, bindings/pydrake/.clang-format, lcm/drake_lcm.cc, planning/BUILD.bazel, planning/body_shape_description.cc, planning/collision_checker.cc, planning/collision_checker_params.h, planning/robot_diagram.cc, planning/robot_diagram.h, planning/robot_diagram_builder.h, planning/scene_graph_collision_checker.cc, planning/test/collision_avoidance_test.cc, planning/test/collision_checker_test.cc, planning/test/planning_test_helpers.cc, planning/test/planning_test_helpers.h, planning/test/robot_diagram_test.cc, planning/test/scene_graph_collision_checker_test.cc, planning/test/unimplemented_collision_checker_test.cc, planning/test_utilities/BUILD.bazel, planning/test_utilities/collision_checker_abstract_test_suite.cc, planning/test_utilities/collision_checker_abstract_test_suite.h, planning/unimplemented_collision_checker.cc
See #18175 for prior art.  That PR has a long explanation for the motivation here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18701)
=> [planning] Opt-in to clang-format lint

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, planning/collision_checker.cc
Alternative approach to #18718
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18723)
=> [planning] Further improve welded body check

examples/manipulation_station/manipulation_station.cc, examples/manipulation_station/manipulation_station.h, multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18795)
=> [parsing] Port to parser.AddModels, part 8

bindings/pydrake/common/text_logging_pybind.cc
Sometimes, users might still want to add more C++ specific sinks (e.g., logging over the network) even when running via pydrake.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18750)
=> [pydrake] Leave C++ logging sink intact (but no-op)

planning/test/collision_checker_test.cc
Resolves #18797 (properly speaking, mitigates, does not resolve completely)
+@rpoyner-tri for review, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18800)
=> Increase sleep time in collision_checker_test

tools/workspace/styleguide/BUILD.bazel, tools/workspace/styleguide/patches/sre_deprecation.patch, tools/workspace/styleguide/patches/test_paths.patch, tools/workspace/styleguide/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18788)
=> [workspace] Fix cpplint vs Python 3.11

bindings/pydrake/symbolic_types_pybind.h, bindings/pydrake/test/symbolic_test.py, common/symbolic/expression/test/expression_matrix_test.cc
Relates investigations in #18816
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18823)
=> [py symbolic] Enable matrix inversions

bindings/pydrake/lcm_py.cc, bindings/pydrake/test/lcm_test.py, lcm/BUILD.bazel, lcm/drake_lcm.cc, lcm/drake_lcm.h, lcm/drake_lcm_interface.h, lcm/drake_lcm_log.cc, lcm/drake_lcm_log.h, lcm/drake_lcm_params.h, lcm/test/drake_lcm_test.cc, systems/lcm/lcm_interface_system.cc, systems/lcm/lcm_interface_system.h
Towards #18774.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18826)
=> [lcm] Add SubscribeMultichannel

bindings/pydrake/common/containers.py, bindings/pydrake/common/test/containers_test.py
Relating #18809
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18831)
=> [py containers] Add nuance on `np.asarray()` for namedview

lcm/test/drake_lcm_base_test.cc
Hotfix for #18847.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18848)
=> [lcm] Add missing include in test

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/inverse_kinematics.cc, multibody/inverse_kinematics/inverse_kinematics.h, multibody/inverse_kinematics/point_to_line_distance_constraint.cc, multibody/inverse_kinematics/point_to_line_distance_constraint.h, multibody/inverse_kinematics/point_to_point_distance_constraint.cc, multibody/inverse_kinematics/test/inverse_kinematics_test.cc, multibody/inverse_kinematics/test/point_to_line_distance_constraint_test.cc
Constrain the distance between a point and a line to be within certain range.
Resolves #18790
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18817)
=> [Inverse Kinematics] Add PointToLineDistanceConstraint.

geometry/optimization/BUILD.bazel, geometry/optimization/c_iris_collision_geometry.h, geometry/optimization/c_iris_separating_plane.cc, geometry/optimization/c_iris_separating_plane.h, geometry/optimization/dev/BUILD.bazel, geometry/optimization/dev/c_iris_separating_plane.cc, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.h, geometry/optimization/test/c_iris_separating_plane_test.cc
We define how to compute the separating plane as polynomial of configuration variable s.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18852)
=> [C-IRIS] move c_iris_separating_plane out of dev.

multibody/constraint/constraint_solver.h, solvers/unrevised_lemke_solver.cc, systems/analysis/implicit_euler_integrator.cc, systems/analysis/implicit_integrator.cc, systems/analysis/radau_integrator.cc, systems/analysis/velocity_implicit_euler_integrator.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18858)
=> [hotfix] Patch missing fmt_eigen usage in debug logging

doc/_pages/from_source.md, doc/_pages/installation.md
Closes #18802.
+@BetsyMcPhail for feature review, please.
+@SeanCurtis-TRI for feature & platform review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18853)
=> [doc] Clarify what "support" means a bit

doc/_pages/release_playbook.md
Resolves #18842, blocked by https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/66
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18851)
=> [doc] Update packaging job names in the Release Playbook

geometry/optimization/BUILD.bazel, geometry/optimization/cspace_free_polytope.h, geometry/optimization/dev/BUILD.bazel, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/test/c_iris_test_utilities.h, geometry/optimization/dev/test/cspace_free_polytope_test.cc, geometry/optimization/dev/test/cspace_free_polytope_with_mosek_test.cc
I will move the cc file out of dev folder in my next PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18860)
=> [C-IRIS] move cspace_free_polytope.h out of dev folder.

common/trajectories/piecewise_polynomial.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18872)
=> [piecewise_polynomial] Replace broken link w/ wayback URL

tools/wheel/wheel_builder/common.py, tools/wheel/wheel_builder/main.py
+@svenevs for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18784)
=> [wheel builder] Add option to validate version against PEP 440

multibody/benchmarks/pendulum/make_pendulum_plant.cc, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/spatial_inertia_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18864)
=> Add SpatialInertia::PointMass()

geometry/optimization/BUILD.bazel, geometry/optimization/cspace_free_polytope.cc, geometry/optimization/dev/cspace_free_polytope.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18863)
=> [C-IRIS] move CspaceFreePolytope constructor out of dev folder.

multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/spatial_inertia_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18865)
=> Add SpatialInertial::HollowSphereWithDensity()

geometry/optimization/c_iris_separating_plane.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18893)
=> Add @file tag to c_iris_seaparating_plane.h doc.

planning/robot_diagram.h, tutorials/BUILD.bazel, tutorials/authoring_leaf_systems.ipynb, tutorials/dynamical_systems.ipynb, tutorials/index.ipynb, tutorials/working_with_diagrams.ipynb
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18873)
=> adds Diagram tutorial

multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/spatial_inertia_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18866)
=> Add SpatialInertia::SolidCubeWithDensity()

solvers/test/csdp_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18906)
=> Fix csdp_solver_test on mac.

multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/spatial_inertia_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18889)
=> Add SpatialInertia::SolidCylinderAboutEnd()

common/symbolic/expression/BUILD.bazel, common/symbolic/expression/boxed_cell.h, common/symbolic/expression/expression.cc, common/symbolic/expression/expression.h, common/symbolic/expression/expression_cell.cc, common/symbolic/expression/expression_kind.h, common/symbolic/expression/formula.cc, common/symbolic/expression/formula.h, common/symbolic/expression/formula_cell.cc, common/symbolic/expression/ldlt.cc, common/symbolic/expression/ldlt.h, common/symbolic/expression/test/boxed_cell_test.cc, common/symbolic/expression/test/expression_array_test.cc, common/symbolic/expression/test/expression_cell_test.cc, common/symbolic/expression/test/expression_differentiation_test.cc, common/symbolic/expression/test/expression_expansion_test.cc, common/symbolic/expression/test/expression_matrix_test.cc, common/symbolic/expression/test/expression_test.cc, common/symbolic/expression/test/formula_test.cc, common/symbolic/expression/test/ldlt_test.cc, common/symbolic/expression/test/mixing_scalar_types_test.cc, common/symbolic/expression/test/sparse_test.cc, common/symbolic/expression/test/substitution_test.cc, common/symbolic/expression/variable.cc, common/symbolic/expression/variable.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18904)
=> [common] Opt-in to clang-format for the expression package

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic/polynomial.cc, common/symbolic/polynomial.h, common/symbolic/test/polynomial_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18887)
=> add binding for SubstituteAndExpand

geometry/optimization/BUILD.bazel, geometry/optimization/dev/BUILD.bazel, geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18909)
=> [C-IRIS] move cspace_free_polytope_with_mosek_test.cc out of dev.

setup/ubuntu/source_distribution/install_prereqs.sh
Thanks, NVidia.
Closes #18787.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18925)
=> [setup] Automatically fix more GCC 12 installation mistakes

setup/ubuntu/binary_distribution/packages-focal.txt, setup/ubuntu/binary_distribution/packages-jammy.txt, tools/ubuntu-focal.bazelrc, tools/ubuntu-jammy.bazelrc, tools/wheel/image/build-dependencies.sh, tools/wheel/image/build-drake.sh, tools/wheel/macos/build-wheel.sh
Closes #18828.
Requires
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18849)
=> [tools] Enable OpenMP in Ubuntu binaries

multibody/benchmarking/position_constraint.cc, multibody/inverse_kinematics/test/com_in_polyhedron_constraint_test.cc, multibody/inverse_kinematics/test/com_position_constraint_test.cc, multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc, multibody/optimization/test/centroidal_momentum_constraint_test.cc, multibody/plant/test/sap_driver_joint_limits_test.cc
Update call sites and use newly added auto-renaming feature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18935)
=> [parsing] Port to parser.AddModels, part 9

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/_model_visualizer.py, bindings/pydrake/visualization/model_visualizer.py, bindings/pydrake/visualization/test/model_visualizer_test.py, geometry/BUILD.bazel
Previously, after pushing the reload button it would vanish along with the stop button. The new control flow logic is less brittle and will be easier to maintain over time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18933)
=> [visualization] Fix model_visualizer reloading

tools/workspace/curl_internal/package.BUILD.bazel, tools/workspace/curl_internal/repository.bzl
Towards #18914.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18929)
=> [workspace] Upgrade curl_internal to latest release 7.88.1

tools/workspace/sdformat_internal/package.BUILD.bazel, tools/workspace/sdformat_internal/patches/console.patch, tools/workspace/sdformat_internal/repository.bzl
Towards #18914. Does not build.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18931)
=> [workspace] Upgrade sdformat_internal to latest release 13.3.0

common/yaml/BUILD.bazel, common/yaml/test/example_structs.h, common/yaml/test/yaml_io_test.cc, common/yaml/test/yaml_node_test.cc, common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_defaults_test.cc, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_io.cc, common/yaml/yaml_io.h, common/yaml/yaml_io_options.cc, common/yaml/yaml_io_options.h, common/yaml/yaml_node.cc, common/yaml/yaml_node.h, common/yaml/yaml_read_archive.cc, common/yaml/yaml_read_archive.h, common/yaml/yaml_write_archive.cc, common/yaml/yaml_write_archive.h
Towards #15774.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18941)
=> [yaml] Opt-in to clang-format linting

tools/install/bazel/test/drake_bazel_installed_test.py, tools/workspace/abseil_cpp_internal/repository.bzl, tools/workspace/bazel_skylib/repository.bzl, tools/workspace/lcm/repository.bzl, tools/workspace/mypy_internal/repository.bzl, tools/workspace/petsc/repository.bzl, tools/workspace/ros_xacro_internal/repository.bzl, tools/workspace/rules_pkg/repository.bzl, tools/workspace/rules_python/repository.bzl, tools/workspace/tinyobjloader/repository.bzl, tools/workspace/typing_extensions_internal/repository.bzl
Towards #18914.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18926)
=> Upgrade Externals March 2023

solvers/aggregate_costs_constraints.h, solvers/binding.h, solvers/branch_and_bound.cc, solvers/choose_best_solver.cc, solvers/clp_solver.cc, solvers/clp_solver_common.cc, solvers/constraint.h, solvers/create_constraint.cc, solvers/create_cost.cc, solvers/create_cost.h, solvers/csdp_solver.cc, solvers/csdp_solver_common.cc, solvers/decision_variable.cc, solvers/equality_constrained_qp_solver.cc, solvers/evaluator_base.cc, solvers/evaluator_base.h, solvers/get_program_type.cc, solvers/gurobi_solver.cc, solvers/gurobi_solver.h, solvers/gurobi_solver_common.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18944)
=> clang-format solvers folder with files start with a to g

doc/_pages/release_playbook.md
Resolves [#18842](https://github.com/RobotLocomotion/drake/issues/18842)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18953)
=> [doc] Update path to Jenkins Wheel Staging job in the Release Playbook

multibody/parsing/BUILD.bazel, multibody/parsing/package_downloader.py, multibody/parsing/test/package_downloader_test.py
For now this is only unit tested; not installed nor used in earnest.
Towards #15774 and #9498.  You can see it used in action in #18955.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18948)
=> [parsing] Add package_downloader tool

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
Amends #17482.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18958)
=> [py multibody] Add bindings for ScopedName

multibody/parsing/package_map.cc
- Add never_destroyed to globals (https://github.com/RobotLocomotion/drake/pull/15896#issuecomment-1460865018).
- Remove std-using stuff (it was applied inconsistently).
- Prefer structured bindings for map iteration.
Towards #15774 and #9498.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18960)
=> [parsing] Tidy up PackageMap implementation a bit more

multibody/plant/test/multibody_plant_reaction_forces_test.cc, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/spatial_inertia_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18950)
=> Add SpatialInertia::ThinRodWithMassAboutEnd()

solvers/integer_inequality_solver.cc, solvers/integer_inequality_solver.h, solvers/integer_optimization_util.cc, solvers/ipopt_solver.cc, solvers/ipopt_solver_common.cc, solvers/linear_system_solver.cc, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/mathematical_program_result.h, solvers/mixed_integer_optimization_util.h, solvers/moby_lcp_solver.cc, solvers/moby_lcp_solver.h, solvers/mosek_solver.cc, solvers/mosek_solver_internal.cc, solvers/nlopt_solver.cc, solvers/nlopt_solver_common.cc, solvers/no_clp.cc, solvers/no_csdp.cc, solvers/no_gurobi.cc, solvers/no_ipopt.cc, solvers/no_mosek.cc, solvers/no_nlopt.cc, solvers/no_osqp.cc, solvers/no_scs.cc, solvers/no_snopt.cc, solvers/non_convex_optimization_util.cc
For files starting with h to n
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18974)
=> Apply clang-format to solvers folder

solvers/mathematical_program.h
To comply with the google style guide https://google.github.io/styleguide/cppguide.html#Declaration_Order
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18978)
=> Move MathematicalProgram data members to the end of private section.

bindings/pydrake/math_operators_pybind.h
Amends #18979.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18985)
=> [pydrake] Hotfix for the C++ list of math operators

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/constraint.cc, solvers/constraint.h, solvers/test/constraint_test.cc
Indicate whether the Hessian is positive/negative semidefinite or indefinite. This will be useful for checking the convexity of the constraint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18965)
=> [solvers]: QuadraticConstraint stores the Hessian type.

tools/wheel/image/pip-drake.patch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18994)
=> [wheel] Hotfix for patch file offsets

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_introspection_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/tree/model_instance.cc, multibody/tree/model_instance.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h
closes #18956
cc'ing @yu-fz 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18959)
=> MultibodyPlant methods to retrieve actuated joints

tools/wheel/image/setup.py
Amends #18973.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18998)
=> [wheel] Hotfix for consolidated manipulation module

tools/workspace/fcl_internal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19006)
=> [workspace] Upgrade fcl_internal to latest commit

common/yaml/test/yaml_io_test.cc, common/yaml/test/yaml_node_test.cc, common/yaml/test/yaml_read_archive_test.cc, common/yaml/yaml_node.cc, common/yaml/yaml_node.h, common/yaml/yaml_read_archive.cc
Closes #18930.
+@dmcconachie-tri you get right of first refusal for feature review.  Let me know if you'd like to defer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18952)
=> [yaml] Add filename, line, and column to error messages

doc/_pages/release_playbook.md
This is from my experience with v1.14.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19008)
=> Update release playbook

.bazeliskrc, doc/_pages/from_source.md, setup/ubuntu/source_distribution/install_prereqs.sh, tools/wheel/image/provision-base.sh, tools/workspace/drake_visualizer/image/provision.sh
Resolves #18946  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19012)
=> Upgrade to Bazel 6.1.1

doc/build.py, setup/mac/binary_distribution/requirements.txt, setup/ubuntu/binary_distribution/packages-focal.txt, setup/ubuntu/binary_distribution/packages-jammy.txt, setup/ubuntu/source_distribution/packages-focal-test-only.txt, tools/wheel/image/provision-python.sh, tools/workspace/pybind11/pybind_coverage_xml_parser.py, tools/workspace/sdformat_internal/embed_sdf.py
Towards #19023 and #18719.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19027)
=> [tools] Remove compile-time dependencies on lxml

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19031)
=> Add a few missing bindings in InverseDynamics and MultibodyPlant

setup/ubuntu/source_distribution/install_prereqs_user_environment.sh, tools/bazel.rc, tools/cc_toolchain/bazel.rc, tools/macos.bazelrc, tools/ubuntu-focal.bazelrc, tools/ubuntu-jammy.bazelrc, tools/ubuntu.bazelrc
Towards #19023.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19025)
=> [tools] Refactor rcfiles for reuse

solvers/test/constraint_test.cc
Towards #19030.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19037)
=> [solvers] Fix typos in unit test

multibody/parsing/BUILD.bazel, multibody/parsing/package_downloader.py, multibody/parsing/test/package_downloader_stress_test.py
Amends #18948.
Towards #15774 and #9498.
(This program wasn't used yet (outside of a little unit testing), so it's non-notable.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19010)
=> [parsing] Fix race conditions in the downloader

multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/detail_urdf_geometry.h, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_urdf_geometry_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc
Closes #19028
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19029)
=> [parsing] Allow duplicate geometry names in URDF input

tools/workspace/common_robotics_utilities/repository.bzl
Towards #19030.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19036)
=> [workspace] Upgrade common_robotics_utilities to latest commit

solvers/test/mathematical_program_test.cc
Towards #19030.
+@ggould-tri for platform review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19038)
=> [solvers] Adjust epsilon in unit test

doc/doxygen_cxx/system_doxygen.py
Closes #18980.
\CC @amcastro-tri FYI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19041)
=> [doc] Reduce the fallout from system_html crashes

tools/wheel/README.rst, tools/wheel/image/setup.py, tools/wheel/test/tests/pyi-install-test.py, tools/wheel/test/tests/sanity-test.py, tools/wheel/test/tests/size-test.py, tools/wheel/wheel_builder/common.py, tools/wheel/wheel_builder/linux.py, tools/wheel/wheel_builder/main.py
Closes #18934.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18999)
=> [wheel] Improve usability for local development

multibody/contact_solvers/sap/sap_holonomic_constraint.cc, multibody/contact_solvers/sap/sap_holonomic_constraint.h, multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc
Towards landing implicit PD control in #17674.
cc'ing @RussTedrake
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18996)
=> SAP holonomic constraints with non-zero bias

setup/ubuntu/source_distribution/packages-jammy-clang.txt, tools/ubuntu-jammy.bazelrc
Closes #19024.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19030)
=> [setup] Upgrade from clang-12 to clang-14 on Ubuntu

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, math/autodiff_gradient.cc, math/autodiff_gradient.h, math/test/autodiff_test.cc, multibody/inverse_kinematics/kinematic_evaluator_utilities.cc, multibody/inverse_kinematics/kinematic_evaluator_utilities.h, multibody/optimization/sliding_friction_complementarity_constraint.cc, multibody/optimization/static_equilibrium_constraint.cc, multibody/optimization/static_friction_cone_complementarity_constraint.cc, multibody/optimization/static_friction_cone_constraint.cc, planning/trajectory_optimization/direct_collocation.cc, planning/trajectory_optimization/direct_collocation.h, planning/trajectory_optimization/test/direct_collocation_test.cc
Resolves #18937.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19019)
=> Implements caching in DirectCollocation.

planning/trajectory_optimization/test/direct_collocation_test.cc
+@BetsyMcPhail for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19056)
=> hotfix for direct_collocation_constraint_test memcheck failure

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py, bindings/pydrake/systems/test/general_test.py, systems/framework/system.h
This does two things:
1. Reorder the bindings of drake::System to match the declaration in the header.
2. Add missing keyword arguments.
#relates #19005
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19053)
=> Update drake::Systems bindings

math/rotation_matrix.cc, math/rotation_matrix.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19040)
=> [math] Move code from rotation_matrix.h to cc

common/trajectories/BUILD.bazel, common/trajectories/bezier_curve.cc, common/trajectories/bspline_trajectory.cc, common/trajectories/bspline_trajectory.h, common/trajectories/exponential_plus_piecewise_polynomial.cc, common/trajectories/exponential_plus_piecewise_polynomial.h, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/piecewise_pose.cc, common/trajectories/piecewise_quaternion.cc, common/trajectories/piecewise_quaternion.h, common/trajectories/piecewise_trajectory.h, common/trajectories/stacked_trajectory.cc, common/trajectories/test/bezier_curve_test.cc, common/trajectories/test/bspline_trajectory_test.cc, common/trajectories/test/discrete_time_trajectory_test.cc, common/trajectories/test/exponential_plus_piecewise_polynomial_test.cc, common/trajectories/test/piecewise_polynomial_generation_test.cc, common/trajectories/test/piecewise_polynomial_test.cc, common/trajectories/test/piecewise_quaternion_test.cc, common/trajectories/test/piecewise_trajectory_test.cc, common/trajectories/test/random_piecewise_polynomial.h, common/trajectories/test/stacked_trajectory_test.cc, common/trajectories/test/trajectory_test.cc, common/trajectories/trajectory.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19060)
=> [trajectories] Opt-in to clang-format lint

setup/ubuntu/source_distribution/packages-jammy-clang.txt, setup/ubuntu/source_distribution/packages-jammy-test-only.txt, tools/dynamic_analysis/asan.sh, tools/dynamic_analysis/drd.sh, tools/dynamic_analysis/helgrind.sh, tools/dynamic_analysis/lsan.sh, tools/dynamic_analysis/tsan.sh, tools/dynamic_analysis/ubsan.sh, tools/dynamic_analysis/valgrind.sh
Amends #19030.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19064)
=> [setup] Upgrade sanitizer builds to clang-14 on Ubuntu

bindings/pydrake/polynomial_py.cc, bindings/pydrake/test/polynomial_test.py, common/polynomial.cc, common/polynomial.h, common/test/polynomial_test.cc
Noticed while working on #19062.
+@xuchenhan-tri for both reviews please, if you're available?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19063)
=> [common] Add missing Python kwarg for Polynomial constructor

multibody/parsing/BUILD.bazel
Amends #19046. Towards #15774.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19072)
=> [parsing] Mark drake_models.json bazel-public

bindings/pydrake/BUILD.bazel, bindings/pydrake/common/test/yaml_typed_test.py, bindings/pydrake/common/yaml.py, bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/BUILD.bazel, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/test/piecewise_polynomial_test.cc
Closes #18947.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19062)
=> [trajectories] PiecewisePolynomial supports serialization

multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/parsing_doxygen.h, multibody/parsing/test/detail_urdf_geometry_test.cc
Toward #18844 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19066)
=> [parsing] Error out if <drake:diffuse_map> is specified in a URDF

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19074)
=> Add Python bindings to CalcRpyDtFromAngularVelocityInChild().

multibody/contact_solvers/test/block_3x3_sparse_matrix_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19086)
=> [hotfix] Fix block_3x3_sparse_matrix_test

math/rigid_transform.cc, math/rigid_transform.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19084)
=> Move RigidTransform code from .h file to .cc file.

geometry/render_gl/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19101)
=> [geometry] fix render_gl deprecation test

geometry/optimization/dev/BUILD.bazel, geometry/optimization/dev/cspace_free_path.cc, geometry/optimization/dev/cspace_free_path.h, geometry/optimization/dev/polynomial_positive_on_path.cc, geometry/optimization/dev/polynomial_positive_on_path.h, geometry/optimization/dev/test/polynomial_positive_on_path_test.cc, geometry/optimization/test/c_iris_test_utilities.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18995)
=> Cspace free path parametrized polynomial

tools/workspace/models_internal/package.BUILD.bazel, tools/workspace/models_internal/repository.bzl
Towards #15774.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19102)
=> [workspace] Upgrade models_internal to latest commit

CMakeLists.txt, cmake/bazel.rc.in, cmake/external/workspace/eigen/BUILD.bazel.in, cmake/external/workspace/fmt/BUILD.bazel.in, cmake/external/workspace/spdlog/BUILD.bazel.in
Amends #19023.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19110)
=> [cmake] Fix several errors and imprecisions

multibody/parsing/package_map.cc, multibody/parsing/test/package_map_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19111)
=> [parsing] Don't warn on equivalent package.xml files

tutorials/authoring_leaf_systems.ipynb, tutorials/working_with_diagrams.ipynb
+@xuchenhan-tri for both reviews per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19122)
=> [tutorials] Fix line wrapping

solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19087)
=> [solvers] MathematicalProgram AddDecisionVariables and AddIndeterminates allow duplicated variables.

multibody/parsing/detail_dmd_parser.cc, multibody/parsing/model_directives.h, multibody/parsing/test/parser_test.cc
FYI @trowell-tri per #19014.
Relates #7827.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19125)
=> [parsing] Don't abort on invalid input

systems/controllers/inverse_dynamics_controller.cc
Related to https://stackoverflow.com/q/75917723/9510020 .
+@rcory for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19121)
=> Adds a more helpful error message to InverseDynamicsControl.

doc/_pages/from_binary.md
Amends #18954.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19132)
=> [doc] Fix broken links to v1.14.0 tgz downloads

geometry/optimization/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19133)
=> Use shard_count for cspace_free_polytope_with_mosek_test

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/tree/spatial_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19134)
=> Python bindings for SpatialInertia geometries.

multibody/parsing/BUILD.bazel, multibody/parsing/package_map.cc, multibody/parsing/test/package_map_remote_test.cc
Closes #19127.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19139)
=> [parsing] Ensure strip_prefix affects cache validation

bindings/pydrake/visualization/_model_visualizer.py, bindings/pydrake/visualization/model_visualizer.py, bindings/pydrake/visualization/test/model_visualizer_test.py
Closes #18977.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19131)
=> [visualization] Enhance model_visualizer command line

bindings/pydrake/multibody/test/mesh_to_model_test.py, multibody/benchmarks/inclined_plane/inclined_plane_plant.cc, multibody/plant/test/joint_limits_test.cc, multibody/plant/test/multibody_plant_forward_dynamics_test.cc, multibody/plant/test/multibody_plant_jacobians_test.cc, multibody/plant/test/multibody_plant_reaction_forces_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/articulated_body_algorithm_test.cc, multibody/tree/test/spatial_inertia_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19141)
=> New SpatialInertia factory method SolidBoxWithMass().

multibody/parsing/scoped_names.cc, multibody/parsing/test/scoped_names_test.cc, systems/sensors/test/camera_config_functions_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19154)
=> [parsing] Provide name suggestions when dmd frames have typos

doc/_pages/stable.md
See https://github.com/RobotLocomotion/drake/pull/19105 and https://github.com/RobotLocomotion/drake/pull/19144.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19145)
=> [doc] Clarify stability policy for struct aggregate initialization

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19172)
=> Python bind SpatialInertia::SolidBoxWithMass().

multibody/inverse_kinematics/differential_inverse_kinematics_integrator.h
Inspired by this [stackoverflow question](https://stackoverflow.com/questions/75981586/differentialinversekinematicsintegrator-causes-multibodyplant-to-snap-to-the-sam)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19173)
=> Improve DifferentialInverseKinematicsIntegrator docstring

bindings/pydrake/systems/sensors_py.cc, bindings/pydrake/systems/test/sensors_test.py
Amends #17852.
I stumbled on this while prototyping some things.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19184)
=> [pydrake] Bind CameraConfig.MakeCameras

multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/plant/test/joint_limits_test.cc, multibody/plant/test/multibody_plant_forward_dynamics_test.cc, multibody/plant/test/multibody_plant_reaction_forces_test.cc, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/spatial_inertia_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19171)
=> Add SpatialInertia::SolidCubeWithMass().

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Resolves #10736.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19174)
=> Adds GetVelocityNames, GetStateNames, and GetActuatorNames to MultibodyPlant

doc/BUILD.bazel, tools/workspace/buildifier/repository.bzl
Towards #19137.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19189)
=> [workspace] Upgrade buildifier to latest release 6.1.0

tools/workspace/abseil_cpp_internal/repository.bzl, tools/workspace/curl_internal/package.BUILD.bazel, tools/workspace/curl_internal/repository.bzl, tools/workspace/dm_control_internal/repository.bzl, tools/workspace/fcl_internal/repository.bzl, tools/workspace/lcm/repository.bzl, tools/workspace/msgpack_internal/repository.bzl, tools/workspace/mypy_internal/repository.bzl, tools/workspace/new_release.py, tools/workspace/rules_python/repository.bzl, tools/workspace/scs_internal/repository.bzl, tools/workspace/sdformat_internal/repository.bzl, tools/workspace/statsjs/repository.bzl, tools/workspace/tinyobjloader/repository.bzl
Towards #19137.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19185)
=> Upgrade Externals April 2023

doc/_release-notes/v1.14.0.md
- https://github.com/RobotLocomotion/drake-ci/pull/214 will bump cache key version and nightlies will begin.
- Then this PR should merge, triggering continuous.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19200)
=> [doc] Minor grammar fix

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/linear_operator.h, multibody/contact_solvers/matrix_block.cc, multibody/contact_solvers/matrix_block.h, multibody/contact_solvers/newton_with_bisection.h, multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/contact_problem_graph.cc, multibody/contact_solvers/sap/contact_problem_graph.h, multibody/contact_solvers/sap/sap_constraint.h, multibody/contact_solvers/sap/sap_contact_problem.h, multibody/contact_solvers/sap/sap_limit_constraint.cc, multibody/contact_solvers/sap/sap_limit_constraint.h, multibody/contact_solvers/sap/sap_model.h, multibody/contact_solvers/sap/sap_solver.cc, multibody/contact_solvers/sap/test/sap_model_test.cc, multibody/contact_solvers/sap/test/sap_solver_test.cc, multibody/contact_solvers/sparse_linear_operator.h, multibody/contact_solvers/test/matrix_block_test.cc, multibody/contact_solvers/test/newton_with_bisection_test.cc
Towards the ongoing effort to clang-format everything as discussed in platform reviewer meeting.
See https://github.com/RobotLocomotion/drake/pull/18175 for prior art. That PR has a long explanation for the motivation here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19180)
=> [contact_solvers] Opt-in to clang-format linting

multibody/fem/petsc_symmetric_block_sparse_matrix.cc, tools/workspace/petsc/package.BUILD.bazel, tools/workspace/petsc/patches/petsc_creationidx_keyval.patch, tools/workspace/petsc/patches/petscimpl.patch, tools/workspace/petsc/patches/remove_packages.patch, tools/workspace/petsc/repository.bzl, tools/workspace/petsc/stubs/petscconf.h
Towards #19137.
Our patches no longer apply and need to be updated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19186)
=> [workspace] Upgrade petsc to latest release v3.19.0

multibody/plant/BUILD.bazel, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19212)
=> [multibody] Remove unused MbP includes

solvers/clp_solver.cc, solvers/clp_solver.h, solvers/test/clp_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19213)
=> [solvers] Provide clp_version in ClpSolverDetails

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py, math/quaternion.h
Includes some fix-ups to support all scalar types.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19208)
=> Add bindings for math/quaternion.h

geometry/optimization/BUILD.bazel, geometry/optimization/convex_set.h, geometry/optimization/test/convex_set_test.cc, geometry/optimization/vpolytope.cc
This is a simple method to help initialize lists of ConvexSets.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19207)
=> Add geometry::optimization::MakeConvexSets

multibody/tree/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19216)
=> [multibody] Remove deprecated bazel label 2023-04

multibody/multibody_doxygen.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19190)
=> Enhance documentation for monogram notation.

bindings/pydrake/geometry/geometry_py_common.cc, bindings/pydrake/geometry/test/common_test.py, bindings/pydrake/visualization/_meldis.py, geometry/drake_visualizer.cc, geometry/geometry_properties.h, geometry/meshcat_visualizer.cc, geometry/render_gl/internal_render_engine_gl.cc, geometry/rgba.h, geometry/test/rgba_test.cc
Modernize several Rgba-related call sites to avoid syntax vomit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19237)
=> [geometry] Add Rgba::update to selectively change values

bindings/pydrake/multibody/fem_py.cc, bindings/pydrake/multibody/test/fem_test.py, examples/multibody/deformable_torus/deformable_torus.cc, multibody/fem/BUILD.bazel, multibody/fem/deformable_body_config.h, multibody/fem/deformation_gradient_data.h, multibody/fem/discrete_time_integrator.cc, multibody/fem/fem_state.cc, multibody/fem/fem_state.h, multibody/fem/fem_state_system.cc, multibody/fem/fem_state_system.h, multibody/fem/linear_constitutive_model.h, multibody/fem/linear_corotated_model.cc, multibody/fem/linear_corotated_model.h, multibody/fem/linear_corotated_model_data.cc, multibody/fem/linear_corotated_model_data.h, multibody/fem/test/calc_lame_parameters_test.cc, multibody/fem/test/constitutive_model_test_utilities.cc, multibody/fem/test/corotated_model_data_test.cc, multibody/fem/test/deformable_body_config_test.cc, multibody/fem/test/deformation_gradient_data_test.cc, multibody/fem/test/linear_constitutive_model_data_test.cc, multibody/fem/test/linear_corotated_model_data_test.cc, multibody/fem/test/linear_corotated_model_test.cc, multibody/fem/test/volumetric_element_test.cc, multibody/fem/volumetric_element.h, multibody/plant/deformable_model.cc, multibody/plant/test/deformable_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19170)
=> [fem] Add linear corotated model

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/BUILD.bazel, common/trajectories/bezier_curve.cc, common/trajectories/bezier_curve.h, common/trajectories/test/bezier_curve_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19205)
=> Add BezierCurve::GetExpression()

doc/_pages/credits.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19253)
=> [doc] add David von Wrangel to contributors

examples/quadrotor/quadrotor_plant.cc, examples/quadrotor/quadrotor_plant.h, examples/quadrotor/test/quadrotor_plant_test.cc, math/roll_pitch_yaw.cc
+@ggould-tri for both reviews(?), please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19256)
=> Adds support for T=Expression to QuadrotorPlant example.

bindings/pydrake/geometry/test/visualizers_test.py, bindings/pydrake/systems/test/perception_test.py
Close #12086
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19255)
=> [bindings] Use PointCloud object directly for GetInputPort.FixValue

common/hash.h, common/test/hash_test.cc, systems/framework/diagram_builder.h
Towards #19243.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19248)
=> [common] Add hash_append support for bare pointers

geometry/optimization/BUILD.bazel, geometry/optimization/test/convex_set_solving_test.cc, geometry/optimization/test/convex_set_test.cc
Closes #19258.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19260)
=> [optimization] Split convex_set_test into solver vs non-solver

bindings/pydrake/trajectories_py.cc
I stumbled upon this while grepping for `unique_ptr`.  A `copyable_unique_ptr` doesn't make any sense in Python.  We could probably automate this conversion in the type_caster logic, but for now writing it out by hand isn't too bad.
Amends #19163.  No deprecation required because #19163 was so recent.
+@RussTedrake for feature review, please.
+@rpoyner-tri for platform review, please.
\CC @sammy-tri FYI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19252)
=> [pydrake] Fix CompositeTrajectory constructor argument type

multibody/tree/spatial_inertia.cc
Also, use anonymous namespace instead of static.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19240)
=> Change is_positive_and_finite() to is_positive_finite().  

planning/trajectory_optimization/BUILD.bazel, planning/trajectory_optimization/direct_collocation.cc, planning/trajectory_optimization/direct_transcription.cc, planning/trajectory_optimization/kinematic_trajectory_optimization.cc, planning/trajectory_optimization/kinematic_trajectory_optimization.h, planning/trajectory_optimization/multiple_shooting.cc, planning/trajectory_optimization/multiple_shooting.h, planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc, planning/trajectory_optimization/test/multiple_shooting_test.cc
To help double-check #19239 as it develops.  (It's already pretty good already.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19273)
=> [trajectory_optimization] Opt-in to clang-format-lint

common/symbolic/expression/environment.cc, common/symbolic/expression/expression_cell.cc, common/test/polynomial_test.cc, common/test/scoped_singleton_test.cc, common/test/text_logging_ostream_test.cc, common/test/text_logging_test.cc, common/trajectories/piecewise_polynomial.cc, math/hopf_coordinate.h, multibody/optimization/static_friction_cone_complementarity_constraint.h, multibody/tree/spatial_inertia.cc, perception/point_cloud_to_lcm.cc, planning/trajectory_optimization/direct_transcription.cc, planning/trajectory_optimization/test/direct_collocation_test.cc, planning/trajectory_optimization/test/direct_transcription_test.cc, planning/trajectory_optimization/test/multiple_shooting_test.cc, solvers/create_cost.cc, solvers/decision_variable.h, solvers/gurobi_solver.cc, solvers/gurobi_solver.h, solvers/indeterminate.h, solvers/moby_lcp_solver.cc, solvers/moby_lcp_solver.h, solvers/nlopt_solver.cc, solvers/no_gurobi.cc, solvers/test/cost_test.cc, solvers/test/evaluator_base_test.cc, solvers/unrevised_lemke_solver.cc, solvers/unrevised_lemke_solver.h, systems/analysis/lyapunov.cc, systems/sensors/image_to_lcm_image_array_t.cc
These will be flagged by cpplint once we upgrade it to https://github.com/RobotLocomotion/styleguide/pull/52.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19270)
=> [lint] Uniform closing-namespace comments throughout

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, examples/hydroelastic/ball_plate/make_ball_plate_plant.cc, examples/multibody/rolling_sphere/populate_ball_plant.cc, multibody/benchmarks/inclined_plane/inclined_plane_plant.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/plant/test/multibody_plant_hydroelastic_test.cc, multibody/plant/test/sap_driver_ball_constraints_test.cc, multibody/plant/test/sap_driver_distance_constraints_test.cc, multibody/plant/test/spheres_stack.h, multibody/plant/test_utilities/rigid_body_on_compliant_ground.h, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/linear_bushing_roll_pitch_yaw_test.cc, multibody/tree/test/spatial_inertia_test.cc, systems/analysis/test/semi_explicit_euler_integrator_test.cc, systems/analysis/test_utilities/generic_integrator_test.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19268)
=> Create SpatialInertia::SolidSphereWithMass() and HollowSphereWithMass().

bindings/pydrake/geometry/geometry_py_scene_graph.cc, bindings/pydrake/geometry/test/scene_graph_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19278)
=> Add bindings for SceneGraph::ChangeShape()

geometry/optimization/cartesian_product.cc, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/cspace_free_polytope.cc, geometry/optimization/cspace_free_polytope.h, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/dev/test/c_iris_path_test_utilities.h, geometry/optimization/dev/test/cspace_free_path_test.cc, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/hpolyhedron.cc, geometry/optimization/hyperellipsoid.cc, geometry/optimization/iris.cc, geometry/optimization/test/convex_set_test.cc, geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc, geometry/optimization/test/graph_of_convex_sets_test.cc, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/hyperellipsoid_test.cc, geometry/optimization/test/iris_in_configuration_space_test.cc, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19246)
=> clang-format geometry/optimization folder.

common/polynomial.cc, common/polynomial.h, common/test/polynomial_test.cc, geometry/optimization/cspace_free_polytope.cc, geometry/optimization/cspace_free_polytope.h, geometry/optimization/dev/BUILD.bazel, geometry/optimization/dev/cspace_free_path.cc, geometry/optimization/dev/cspace_free_path.h, geometry/optimization/dev/polynomial_positive_on_path.cc, geometry/optimization/dev/polynomial_positive_on_path.h, geometry/optimization/dev/test/c_iris_path_test_utilities.h, geometry/optimization/dev/test/cspace_free_path_test.cc, geometry/optimization/dev/test/cspace_free_path_with_mosek_test.cc, geometry/optimization/dev/test/polynomial_positive_on_path_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19201)
=> Cspace free path setup program

math/test/continuous_algebraic_riccati_equation_test.cc
In lieu of #19274
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19276)
=> Fix the test in continuous algebraic Riccati equation

bindings/pydrake/multibody/optimization_py.cc, bindings/pydrake/multibody/test/optimization_test.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19288)
=> Add bindings for functions on QuaternionEulerIntegrationConstraint

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/primitives/linear_system.cc, systems/primitives/linear_system.h, systems/primitives/test/linear_system_test.cc
Including controllability, observability, stabilizability and detectability
Resolves #19227 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19289)
=> Determine certain properties of linear dynamical systems

systems/stochastic_systems.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19291)
=> Improve readability of stochastic systems doc w/ unicode

doc/_pages/jenkins.md
Amends #18953.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19297)
=> [doc] Fix names of Packaging jobs vs recent renames

setup/mac/install_prereqs.sh
Hotfix for #19307.  Bump removal date to 2023-06.
Follow-up is in #19318.
+@SeanCurtis-TRI for both reviews per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19317)
=> [setup] Revert removal of macOS maintainer only flag

geometry/optimization/cartesian_product.cc, geometry/optimization/cartesian_product.h, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/intersection.cc, geometry/optimization/intersection.h, geometry/optimization/minkowski_sum.cc, geometry/optimization/minkowski_sum.h, geometry/optimization/point.cc, geometry/optimization/point.h, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
Towards #19311.
+@SeanCurtis-TRI for platform review per schedule, please.  No feature review required; this is just cleaning up prior platform reviewer leaks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19313)
=> Tidy up ConvexSet implementation conventions

solvers/mathematical_program.h
The public documentation wasn't quite clear on the relationship between bounding box, linear constraints, and linear equality constraints. This PR makes it slightly better.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19315)
=> Touch up MathematicalProgram docs for linear constraints.

doc/_config.yml, doc/_pages/python_bindings.md, doc/doxygen_cxx/header.html.patch, doc/index.md, doc/pydrake/layout.html
Towards #19325.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19326)
=> [doc] Switch some links to use relative (host-agnostic) paths

common/trajectories/BUILD.bazel, common/trajectories/test/bezier_curve_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19302)
=> Add CheckConvexHullProperty to bezier curve

doc/_pages/reviewable.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19329)
=> Add guidance for release notes when bumping externals

geometry/optimization/test/spectrahedron_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19339)
=> [hotfix] Fix lint in geometry/optimization

tools/workspace/os.bzl
Support for Ventura is inbound.  Relates: #18327.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19350)
=> [workspace] Do not warn against macOS Ventura

geometry/proximity/mesh_plane_intersection.cc, multibody/inverse_kinematics/constraint_relaxing_ik.cc, multibody/plant/multibody_plant.cc
This code is flagged by the latest Clang.
Towards #18327.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19358)
=> Remove dead code

common/schema/test/transform_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19374)
=> [common] Add tolerance for schema/transform_test

solvers/test/clp_solver_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19378)
=> [solvers] Add tolerance for clp_solver_test

math/test/linear_solve_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19373)
=> [math] Add tolerance to linear_solve_test Eigen compare

solvers/test/constraint_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19377)
=> [solvers] Increase tolerance for constraint_test

systems/primitives/test/symbolic_vector_system_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19375)
=> [systems] Add tolerance to primitives/symbolic_vector_system_test

tools/workspace/README.md
Add additional details for how monthly updates should be pushed and reviewed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19382)
=> Improve monthly updates documentation

geometry/proximity/test/obb_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19371)
=> [geometry] Increase tolerance for proximity/obb_test

bindings/pydrake/systems/_lcm_extra.py, bindings/pydrake/systems/test/lcm_test.py, systems/lcm/lcm_publisher_system.cc, systems/lcm/lcm_publisher_system.h, systems/lcm/lcm_subscriber_system.cc, systems/lcm/lcm_subscriber_system.h
Towards #19369.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19390)
=> [systems/lcm] Improve error messages

bindings/pydrake/visualization/test/video_test.py, manipulation/models/iiwa_description/README.md, manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf, manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc, manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14.xacro, manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf, manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf, multibody/plant/test/joint_limits_test.cc, multibody/plant/test/multibody_plant_reflected_inertia_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19344)
=> Added updated models of the IIWA 14 with estimated rotor inertia and gear ratio

geometry/optimization/BUILD.bazel, geometry/optimization/c_iris_separating_plane.h, geometry/optimization/cspace_free_internal.cc, geometry/optimization/cspace_free_internal.h, geometry/optimization/cspace_free_polytope.cc, geometry/optimization/cspace_free_polytope.h, geometry/optimization/cspace_free_structs.h, geometry/optimization/cspace_separating_plane.cc, geometry/optimization/cspace_separating_plane.h, geometry/optimization/dev/cspace_free_polytope.cc, geometry/optimization/test/cspace_free_internal_test.cc, geometry/optimization/test/cspace_free_polytope_test.cc
Refactors CspaceFreePolytope internals to make it easier to develop the path certifier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19368)
=> Refactor CspaceFreePolytope

bindings/pydrake/solvers/solvers_py_branch_and_bound.cc, bindings/pydrake/solvers/test/branch_and_bound_test.py, solvers/branch_and_bound.cc, solvers/branch_and_bound.h, solvers/test/branch_and_bound_test.cc
Early terminate the branch and bound process if the nodes in the tree exceeds this number.
Resolves #19284
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19366)
=> [solvers] Add max_nodes_in_tree for branch_and_bound.

systems/optimization/test/system_constraint_adapter_test.cc
Closes #19409.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19410)
=> [optimization] Defend test against kcov bug

geometry/benchmarking/BUILD.bazel, geometry/benchmarking/README.md, geometry/benchmarking/render_benchmark_doxygen.h, tools/performance/README.md
Towards #19323.
+@rpoyner-tri for platform review, please.
\CC @DamrongGuoy FYI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19418)
=> [geometry] Add benchmark experiment wrappers for reproducible reports

bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/_model_visualizer.py, bindings/pydrake/visualization/_rgbd_camera_sliders.dmd.yaml, bindings/pydrake/visualization/_rgbd_camera_sliders.sdf, bindings/pydrake/visualization/model_visualizer.py, bindings/pydrake/visualization/test/model_visualizer_test.py, tools/install/bazel/drake.BUILD.bazel, tools/install/bazel/drake__bindings__pydrake.BUILD.bazel
Caveat: This won't work in Deepnote until #18862 and related are finished.  It uses a GL native window as the preview for now.
[Screencast from 04-07-2023 12:48:36 PM.webm](https://user-images.githubusercontent.com/17596505/230668625-da9f88df-2c4b-4b2b-9e62-025b3c5b9897.webm)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19158)
=> [visualization] Add render camera preview

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/test/parser_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19413)
=> [multibody] Remove the deprecated Parser::AddModelFromString

setup/ubuntu/binary_distribution/packages-focal.txt, setup/ubuntu/binary_distribution/packages-jammy.txt, setup/ubuntu/source_distribution/packages-focal.txt, setup/ubuntu/source_distribution/packages-jammy.txt
This has been unused for a while (#18532).
Towards #17161.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19427)
=> [setup] Remove NLopt dependency from Ubuntu

geometry/render_vtk/BUILD.bazel
Towards #18327. See #19424 for the tracking issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19425)
=> [render_vtk] Nerf a few test cases on macOS

doc/_release-notes/v1.16.0.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19431)
=> [doc] Improve 1.16 release notes

doc/_pages/release_playbook.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19432)
=> [doc] Refresh tutorials release playbook from experience with v1.16.0

solvers/test/create_constraint_test.cc
Necessary for macOS Ventura on arm64.
Towards #18327.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19423)
=> [solvers] Increase tolerance for create_constraint_test

geometry/geometry_state.cc, geometry/test/geometry_state_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19448)
=> Improve error message for GetGeometryIdByName.

math/BUILD.bazel, math/continuous_algebraic_riccati_equation.cc, math/test/continuous_algebraic_riccati_equation_test.cc, systems/controllers/zmp_planner.h
As discussed in #19191
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19300)
=> Check IsStabilizable and IsDetectable in ContinuousAlgebraicRiccatiEquation

geometry/proximity/test/characterization_utilities.h, geometry/render_gltf_client/internal_http_service_curl.cc
Towards #19446.
This only fixes the build errors.  I'm going to work on the test failures separately.
+@ggould-tri for both reviews per schedule, please.
\CC @SeanCurtis-TRI FYI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19451)
=> Fix build errors vs fmt 10

geometry/render_gl/BUILD.bazel, geometry/render_gl/internal_opengl_context.cc, geometry/render_gl/test/thread_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19323)
=> [render_gl] Support multithreaded operation (sometimes)

tutorials/index.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19439)
=> [tutorials] Taking derivatives of MultibodyPlant with respect to mass

systems/sensors/image.h, systems/sensors/test/image_test.cc
Inspired by being annoyed by this during #19436.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19443)
=> [sensors] Simplify the creation of empty images

bindings/pydrake/systems/sensors_py.cc, bindings/pydrake/systems/test/sensors_test.py, geometry/render_gltf_client/internal_render_client.cc, systems/sensors/image.cc, systems/sensors/image.h, systems/sensors/image_writer.h, systems/sensors/rgbd_sensor.cc, systems/sensors/rgbd_sensor.h, systems/sensors/test/image_test.cc, systems/sensors/test/rgbd_sensor_test.cc
Towards #19437.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19436)
=> [sensors] Add depth image conversion helpers

doc/_pages/from_source.md, doc/_pages/installation.md
Towards #18327
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19458)
=> [doc] Offically support macOS Ventura

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/solvers_py.cc, bindings/pydrake/solvers/solvers_py.h, bindings/pydrake/solvers/solvers_py_mobylcp.cc, bindings/pydrake/solvers/test/mobylcp_solver_test.py
Resolves #19259
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19460)
=> [pydrake] Bind MobyLCP solver.

geometry/optimization/dev/BUILD.bazel, geometry/optimization/dev/cspace_free_path.cc, geometry/optimization/dev/cspace_free_path.h, geometry/optimization/dev/cspace_free_path_separating_plane.cc, geometry/optimization/dev/cspace_free_path_separating_plane.h, geometry/optimization/dev/test/c_iris_path_test_utilities.h, geometry/optimization/dev/test/cspace_free_path_separating_plane_test.cc, geometry/optimization/dev/test/cspace_free_path_test.cc, geometry/optimization/dev/test/cspace_free_path_with_mosek_test.cc
Refactor cspace_free_path to use the cspace_free_structs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19395)
=> Restructure cspace_free_path

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/primitives/discrete_time_delay.cc, systems/primitives/discrete_time_delay.h, systems/primitives/test/discrete_derivative_test.cc, systems/primitives/test/discrete_time_delay_test.cc
Towards #9661.
This follows up on #19470.  Might as well finish the job, so people don't need to get irritated by the change multiple times.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19475)
=> Rename timestep => time_step in systems/primitives

bindings/pydrake/systems/test/controllers_test.py, systems/controllers/dynamic_programming.cc, systems/controllers/dynamic_programming.h, systems/controllers/test/dynamic_programming_test.cc
Towards #9661.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19476)
=> Rename timestep => time_step in systems/controllers

bindings/pydrake/systems/_resample_interp1d.py, bindings/pydrake/systems/pyplot_visualizer.py, bindings/pydrake/systems/test/_resample_log_interp1d_test.py
Towards #9661.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19477)
=> Rename timestep => time_step in pyplot_visualizer

bindings/pydrake/multibody/test/plant_test.py, examples/hardware_sim/hardware_sim.py, examples/hardware_sim/scenario.h, examples/manipulation_station/manipulation_station.cc, examples/manipulation_station/test/manipulation_station_test.cc, examples/mass_spring_cloth/README.md, examples/mass_spring_cloth/cloth_spring_model.h, geometry/drake_visualizer_params.h, geometry/meshcat_visualizer_params.h, manipulation/util/robot_plan_utils.cc, multibody/constraint/test/constraint_solver_test.cc, multibody/fem/discrete_time_integrator.cc, multibody/fem/newmark_scheme.h, multibody/inverse_kinematics/differential_inverse_kinematics_integrator.h, multibody/meshcat/contact_visualizer_params.h, multibody/plant/contact_results_to_lcm.cc, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/joint_locking_test.cc, multibody/plant/test/propeller_test.cc, multibody/plant/test_utilities/rigid_body_on_compliant_ground.h, systems/analysis/test/simulator_test.cc, systems/analysis/velocity_implicit_euler_integrator.h, tutorials/dynamical_systems.ipynb, visualization/visualization_config.h
Resolves #9661.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19478)
=> Rename timestep => time_step in remaining uses/comments throughout

examples/kuka_iiwa_arm/models/objects/simple_cuboid.urdf, examples/quadrotor/office.urdf, multibody/parsing/test/sdf_parser_test/table_in_world.sdf, multibody/parsing/test/urdf_parser_test/collision_filter_group_parsing_test.urdf, multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf
... found while developing an XML inertia fixer tool.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19487)
=> Fix some xml file typos

doc/_pages/from_source.md, doc/_pages/mac.md, doc/_pages/ubuntu.md
Prefer https shallow cloning for upstream.
Reduce prereqs page splatter.
Add a reminder about CMake behavior.
Closes #19009.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19486)
=> [doc] Improve source install instructions

geometry/query_object.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19411)
=> Fix document of ComputeContactSurfaces() that compliant Mesh is supported

multibody/contact_solvers/sap/sap_friction_cone_constraint.cc
Update to use `SapConstraint::MoveAndMakeAbstractValue()` introduced in #19402.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19495)
=> SapFrictionConeConstraint: Move constraint data into abstract value

multibody/optimization/static_friction_cone_constraint.cc
I stumbled on this obvious inefficiency, so decided to clean it up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19497)
=> Use preferred signed-distance query in StaticFrictionConeConstraint

.bazeliskrc, doc/_pages/from_source.md, setup/ubuntu/source_distribution/install_prereqs.sh, tools/wheel/image/provision-base.sh, tools/workspace/drake_visualizer/image/provision.sh
Resolves #19389
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19502)
=> Upgrade to Bazel 6.2.0

tools/release_engineering/dev/push_release
Towards #18659.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19496)
=> [releng] Don't sign individual files

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19509)
=> JointActuator Python bindings for rotor inertias

tutorials/_developers.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19506)
=> [doc] Guidance to review tutorials

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc, multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h, multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
Introduce data structure used for bespoke block sparse cholesky solver for SapSolver as well as linear solves in FEM.
Towards #19466.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19465)
=> Add BlockSparseLowerTriangularOrSymmetricMatrix

setup/mac/install_prereqs.sh
This re-applies #19307, undoing the revert in #19317.
See also #19516.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19518)
=> [setup] Remove deprecated code 2023-06

geometry/render_vtk/BUILD.bazel
Resolves #18745
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19530)
=> Disable RenderEngineVtkTest.NonUcharChannelTextures test on Mac Arm

tools/workspace/bazel_skylib/repository.bzl
Toward #19511.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19539)
=> [workspace] Upgrade bazel_skylib to latest release 1.4.2

doc/_pages/installation.md, doc/_pages/pip.md, doc/_pages/python_bindings.md, setup/mac/binary_distribution/install_prereqs.sh, setup/ubuntu/binary_distribution/install_prereqs.sh
Remove pip known issues (all fixed).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19515)
=> [doc] Soften the warnings around Anaconda

multibody/parsing/detail_common.cc
+@rpoyner-tri for feature review (or both?), please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19543)
=> [parsing] Improve inertia warning text to be more specific

geometry/optimization/BUILD.bazel, geometry/optimization/iris.h, geometry/optimization/test/iris_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19512)
=> Serializes IrisOptions

multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc, multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h, multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19542)
=> Zero out rows and columns in block sparse matrix

multibody/benchmarking/position_constraint.cc, tools/performance/fixture_memory_yes.cc, tools/workspace/googlebenchmark/repository.bzl
Toward #19511.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19537)
=> [workspace] Upgrade googlebenchmark to latest release v1.8.0

multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc, multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19556)
=> Fix an aliasing bug in block sparse matrix

bindings/pydrake/common/eigen_geometry_py.cc, bindings/pydrake/visualization/visualization_py.cc
Amends #19513.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19565)
=> Hotfix ODR violation in MeshcatPoseSliders bindings

manipulation/models/allegro_hand_description/BUILD.bazel, manipulation/models/allegro_hand_description/test/parse_test.cc, manipulation/models/franka_description/BUILD.bazel, manipulation/models/franka_description/urdf/test/franka_arm_test.cc, manipulation/models/iiwa_description/BUILD.bazel, manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc, manipulation/models/jaco_description/BUILD.bazel, manipulation/models/jaco_description/urdf/test/jaco_arm_test.cc, manipulation/models/realsense2_description/BUILD.bazel, manipulation/models/realsense2_description/test/realsense_parse_test.cc, manipulation/models/wsg_50_description/BUILD.bazel, manipulation/models/wsg_50_description/sdf/test/wsg_50_sdf_test.cc, manipulation/models/ycb/BUILD.bazel, manipulation/models/ycb/test/parse_test.cc, manipulation/util/BUILD.bazel, manipulation/util/apply_driver_configs.h, manipulation/util/make_arm_controller_model.cc, manipulation/util/move_ik_demo_base.cc, manipulation/util/move_ik_demo_base.h, manipulation/util/moving_average_filter.cc, manipulation/util/robot_plan_interpolator.cc, manipulation/util/robot_plan_interpolator.h, manipulation/util/robot_plan_utils.cc, manipulation/util/robot_plan_utils.h, manipulation/util/stl2obj.cc, manipulation/util/test/move_ik_demo_base_test.cc, manipulation/util/test/robot_plan_interpolator_test.cc, manipulation/util/test/robot_plan_utils_test.cc, manipulation/util/zero_force_driver_functions.cc
Towards https://github.com/RobotLocomotion/drake/issues/4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19561)
=> [manipulation] Opt-in to clang-format lint for models and util

bindings/pydrake/visualization/BUILD.bazel
This test was occasionally timing out in CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19567)
=> Increase model_visualizer_test timeout

geometry/optimization/BUILD.bazel, geometry/optimization/iris.cc, geometry/optimization/iris_internal.cc, geometry/optimization/iris_internal.h
Move some functions from iris.cc to iris_internal.h/cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19573)
=> Add iris_internal.h/cc.

tutorials/hydroelastic_basics.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19562)
=> [tutorials] Fix typos for hydroelastic_basics.ipynb

geometry/optimization/BUILD.bazel, geometry/optimization/cspace_free_box.cc, geometry/optimization/cspace_free_box.h, geometry/optimization/cspace_free_internal.cc, geometry/optimization/cspace_free_internal.h, geometry/optimization/cspace_free_polytope.cc, geometry/optimization/cspace_free_polytope.h, geometry/optimization/cspace_free_polytope_base.cc, geometry/optimization/cspace_free_polytope_base.h, geometry/optimization/test/c_iris_test_utilities.h, geometry/optimization/test/cspace_free_box_test.cc, geometry/optimization/test/cspace_free_polytope_base_test.cc, geometry/optimization/test/cspace_free_polytope_test.cc
Factor out CspaceFreePolytopeBase for the common code in both CspaceFreePolytope and CspaceFreeBox.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19552)
=> Create CspaceFreeBox class constructor.

doc/_pages/code_review_checklist.md, doc/_pages/developers.md
Per https://github.com/RobotLocomotion/drake/pull/19491#issuecomment-1563118377.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19576)
=> [doc] Consolidate advice about PR size limits

geometry/scene_graph.cc, geometry/test/scene_graph_test.cc
Closes: https://github.com/RobotLocomotion/drake/issues/19586
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19587)
=> [geometry] Add context validation to SceneGraph

visualization/test/visualization_config_functions_test.cc
Amends #19590.
+@DamrongGuoy for feature review, please.
+@EricCousineau-TRI for platform review per schedule, please.
@trowell-tri FYI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19606)
=> [visualization] Add missing unit test for publish period config

multibody/fem/BUILD.bazel, multibody/fem/dirichlet_boundary_condition.cc, multibody/fem/dirichlet_boundary_condition.h, multibody/fem/fem_model.cc, multibody/fem/fem_model.h, multibody/fem/fem_model_impl.h, multibody/fem/test/dirichlet_boundary_condition_test.cc, multibody/fem/test/fem_model_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19559)
=> Store FEM tangent matrix in block sparse matrix

bindings/pydrake/systems/sensors_py.cc, bindings/pydrake/systems/test/sensors_test.py, systems/sensors/BUILD.bazel, systems/sensors/rgbd_sensor.h, systems/sensors/rgbd_sensor_async.cc, systems/sensors/rgbd_sensor_async.h, systems/sensors/test/rgbd_sensor_async_gl_test.cc, systems/sensors/test/rgbd_sensor_async_gl_test.dmd.yaml, systems/sensors/test/rgbd_sensor_async_test.cc
Towards #19437.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19553)
=> [sensors] Add RgbdSensorAsync

tools/wheel/wheel_builder/linux.py
The tar pipe seems to spuriously fail (https://drake-jenkins.csail.mit.edu/view/Production/job/linux-focal-unprovisioned-gcc-wheel-nightly-release/105/) for unknown reasons.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19618)
=> [wheel] Use 'docker cp' (not tar) to extract wheels

common/ad/BUILD.bazel, common/ad/auto_diff.h, common/ad/internal/eigen_specializations.h, common/ad/test/auto_diff_basic_test.cc, common/ad/test/matrix_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19622)
=> [ad] Add Eigen trait specializations

common/ad/BUILD.bazel, common/ad/auto_diff.h, common/ad/internal/partials.cc, common/ad/internal/partials.h, common/ad/internal/standard_operations.cc, common/ad/test/partials_test.cc, common/ad/test/standard_operations_add_test.cc, common/ad/test/standard_operations_atan_test.cc, common/ad/test/standard_operations_cmp_test.cc, common/ad/test/standard_operations_pow_special_test.cc, common/ad/test/standard_operations_sub_test.cc, common/ad/test/standard_operations_test.h
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19621)
=> [ad] Opt-in to clang-format lint

doc/_pages/release_playbook.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19640)
=> [doc] Fix some release playbook typos

multibody/plant/test/multibody_plant_forward_dynamics_test.cc, multibody/tree/rotational_inertia.h, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/unit_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19610)
=> Improve spatial inertia shift efficiency.

tutorials/hydroelastic_contact_basics.ipynb
Towards #19641.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19643)
=> [tutorials] Remove hard linebreaks in Hydroelastic Contact

bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/cartesian_product.cc, geometry/optimization/cartesian_product.h, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/intersection.cc, geometry/optimization/intersection.h, geometry/optimization/minkowski_sum.cc, geometry/optimization/minkowski_sum.h, geometry/optimization/point.cc, geometry/optimization/point.h, geometry/optimization/spectrahedron.cc, geometry/optimization/spectrahedron.h, geometry/optimization/test/cartesian_product_test.cc, geometry/optimization/test/intersection_test.cc, geometry/optimization/test/minkowski_sum_test.cc, geometry/optimization/test/spectrahedron_test.cc, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/test_utilities.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
Resolves #19585
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19634)
=> [planning] ConvexSet::AddPointInSetConstraints returns the new variables

common/trajectories/bezier_curve.cc, common/trajectories/bezier_curve.h, common/trajectories/test/bezier_curve_test.cc
Noticed during #19620.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19648)
=> [trajectories] Fix BezierCurve move operators

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/custom_test.py, bindings/pydrake/systems/test/general_test.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19669)
=> Adds more bindings for CacheEntry

geometry/optimization/BUILD.bazel, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/test/hyperellipsoid_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19670)
=> Adds Serialize to Hyperellipsoid

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/BUILD.bazel, multibody/plant/contact_results.cc, multibody/plant/contact_results.h, multibody/plant/test/contact_results_test.cc
Fix #19592
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19663)
=> [multibody] Select a subset of hydroelastic ContactResults

multibody/contact_solvers/sap/sap_limit_constraint.cc, multibody/contact_solvers/sap/sap_limit_constraint.h, multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc
Towards  #19435.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19688)
=> SapLimitConstraint reports forces

multibody/contact_solvers/sap/sap_contact_problem.cc, multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
Fixes a small off by one introduced in #19557 and adds a unit test to catch the error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19681)
=> [multibody] Fix bug in SapContactProblem::velocities_start()

tutorials/quadratic_program.ipynb
As pointed out by Tao Chen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19682)
=> [tutorials] Fix broken link to differential inverse kinematics

bindings/pydrake/multibody/inverse_kinematics_py_differential.cc, bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/differential_inverse_kinematics.cc, multibody/inverse_kinematics/differential_inverse_kinematics.h, multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc, multibody/plant/multibody_plant.h
Resolves a question from StackOverflow:
https://stackoverflow.com/questions/76391333/differential-inverse-kinematics-integrator-does-not-work-with-a-floating-plant
+@sherm1 for feature review, please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19522)
=> Add support for num_positions != num_velocities in DifferentialIK

tools/release_engineering/dev/push_release.py
Fix a minor bug in the new push_release script where the source tarball was being mirrored to the wrong location in S3. Add additional reporting so users get an indication that the script is doing things and not just out to lunch.
+@BetsyMcPhail for review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19690)
=> push_release: fix bug, add more logging

tools/workspace/drake_visualizer/repository.bzl, tools/workspace/drake_visualizer/warn_gltf.patch
See #19624 for manual testing instructions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19692)
=> [drake_visualizer] Warn on glTF meshes instead of crashing

solvers/aggregate_costs_constraints.cc, solvers/aggregate_costs_constraints.h, solvers/osqp_solver_common.cc, solvers/test/aggregate_costs_constraints_test.cc
Returns the first non-convex quadratic constraint among a list of quadratic constraints.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19668)
=> [solvers] Add FindNonconvexQuadraticConstraint.

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/test/text_logging_example.py, bindings/pydrake/common/test/text_logging_gil_test.py, bindings/pydrake/common/test/text_logging_test.py, bindings/pydrake/common/test/text_logging_test_helpers_py.cc, bindings/pydrake/common/text_logging_pybind.cc, bindings/pydrake/pydrake_doxygen.h, doc/doxygen_cxx/doxygen.h
Resolves #19680
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19685)
=> [bindings] Add env var DRAKE_PYTHON_LOGGING to disable redirect

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19706)
=> Adds bindings for ExpressionCost and ExpressionConstraint

systems/primitives/BUILD.bazel, systems/primitives/test/affine_system_test.cc, systems/primitives/test/barycentric_system_test.cc, systems/primitives/test/constant_value_source_test.cc, systems/primitives/test/constant_vector_source_test.cc, systems/primitives/test/discrete_derivative_test.cc, systems/primitives/test/discrete_time_delay_test.cc, systems/primitives/test/first_order_low_pass_filter_test.cc, systems/primitives/test/integrator_test.cc, systems/primitives/test/linear_system_test.cc, systems/primitives/test/linear_transform_density_test.cc, systems/primitives/test/pass_through_test.cc, systems/primitives/test/random_source_test.cc, systems/primitives/test/saturation_test.cc, systems/primitives/test/shared_pointer_system_test.cc, systems/primitives/test/sine_test.cc, systems/primitives/test/symbolic_vector_system_test.cc, systems/primitives/test/trajectory_affine_system_test.cc, systems/primitives/test/trajectory_linear_affine_test.h, systems/primitives/test/trajectory_linear_system_test.cc, systems/primitives/test/trajectory_source_test.cc, systems/primitives/test/vector_log_sink_test.cc, systems/primitives/test/wrap_to_system_test.cc, systems/primitives/test/zero_order_hold_test.cc
Towards #19707 and #4843. Follow-up from #19708.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19710)
=> [primitives] Opt-in to clang-format-lint

multibody/inverse_kinematics/minimum_distance_constraint.h, solvers/minimum_value_constraint.cc, solvers/minimum_value_constraint.h, solvers/test/minimum_value_constraint_test.cc
Now we support lower <= min(f(x)) <= upper.
Towards #18830
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19665)
=> [solvers] Support upper bound in MinimumValueConstraint.

solvers/mathematical_program_doxygen.h
cc @hongkai-dai
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19721)
=> Add link from solvers doxygen to build info for priopriety solvers.

common/yaml/test/yaml_read_archive_test.cc, common/yaml/yaml_read_archive.cc, common/yaml/yaml_read_archive.h
Closes #19725.
I didn't actually check if this solves the repro from the original issue, but I assume it will.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19730)
=> [yaml] Improve error message for parsing a non-Mapping root node

geometry/optimization/BUILD.bazel, geometry/optimization/cspace_free_box.cc, geometry/optimization/cspace_free_box.h, geometry/optimization/cspace_free_polytope.cc, geometry/optimization/cspace_free_polytope.h, geometry/optimization/cspace_free_polytope_base.cc, geometry/optimization/cspace_free_polytope_base.h, geometry/optimization/cspace_free_structs.h, geometry/optimization/test/c_iris_test_utilities.cc, geometry/optimization/test/c_iris_test_utilities.h, geometry/optimization/test/cspace_free_box_test.cc, geometry/optimization/test/cspace_free_box_with_mosek_test.cc, geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19658)
=> Add ConstructPlaneSearchProgram to CspaceFreeBox.

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/primitives/affine_system.cc, systems/primitives/affine_system.h, systems/primitives/test/affine_system_test.cc
This PR adds a function to `AffineSystem` that allows updating A , B, C, D, f0 and y0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19707)
=> Update coefficients in AffineSystem

geometry/render_gl/internal_opengl_includes.h, geometry/render_gl/internal_render_engine_gl.h, geometry/render_vtk/internal_render_engine_vtk.h, geometry/render_vtk/internal_vtk_util.h, tools/skylark/drake_cc.bzl, visualization/visualization_config.h
Close #19089
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19750)
=> Fix outdated doxygen comments and some typos

systems/benchmarking/BUILD.bazel, systems/benchmarking/framework_benchmarks.cc, systems/benchmarking/multilayer_perceptron_benchmark.cc, tools/performance/defs.bzl
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19745)
=> [systems] Enable clang-format lint for benchmarking

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/block_sparse_cholesky_solver.cc, multibody/contact_solvers/block_sparse_cholesky_solver.h, multibody/contact_solvers/test/block_sparse_cholesky_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19741)
=> Add BlockSparseCholeskySolver

bindings/pydrake/visualization/test/meldis_test.py, visualization/inertia_visualizer.h, visualization/test/inertia_visualizer_test.cc, visualization/test/visualization_config_functions_test.cc, visualization/visualization_config.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19743)
=> [visualization] Enable inertia visualization by default

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/sorted_pair_pybind.h, bindings/pydrake/common/test/sorted_pair_pybind_test.cc
For #19574
FYI @AlexandreAmice
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19753)
=> [bindings] Fix bugs for sorted_pair_pybind; add test

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, examples/multibody/cylinder_with_multicontact/populate_cylinder_plant.cc, multibody/plant/test/multibody_plant_forward_dynamics_test.cc, multibody/plant/test/multibody_plant_jacobians_test.cc, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/articulated_body_algorithm_test.cc, multibody/tree/test/spatial_inertia_test.cc, multibody/tree/unit_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19737)
=> Add more SpatialInertia::ObjectWithMass() functions

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/block_sparse_matrix.h, multibody/contact_solvers/block_sparse_supernodal_solver.cc, multibody/contact_solvers/block_sparse_supernodal_solver.h, multibody/contact_solvers/conex_supernodal_solver.cc, multibody/contact_solvers/conex_supernodal_solver.h, multibody/contact_solvers/supernodal_solver.cc, multibody/contact_solvers/supernodal_solver.h, multibody/contact_solvers/test/block_sparse_matrix_test.cc, multibody/contact_solvers/test/supernodal_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19754)
=> Implement SuperNodalSolver with BlockSparseCholeskySolver

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_solver.cc, multibody/contact_solvers/sap/sap_solver.h, multibody/contact_solvers/sap/test/sap_solver_test.cc
The BlockSparseSuperNodalSolver better exploits sparsity and provides significant speed-up in solving larger contact problems.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19757)
=> SAP uses BlockSparseSuperNodalSolver

geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/internal_render_engine_gl.h, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/internal_render_engine_vtk.h
Amends #19747.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19769)
=> Use temporary DiagnosticPolicy object

tools/workspace/dm_control_internal/repository.bzl, tools/workspace/googlebenchmark/repository.bzl, tools/workspace/libcmaes/repository.bzl, tools/workspace/msgpack_internal/repository.bzl, tools/workspace/mypy_internal/repository.bzl, tools/workspace/petsc/repository.bzl, tools/workspace/qdldl_internal/repository.bzl, tools/workspace/rules_python/repository.bzl, tools/workspace/suitesparse_internal/repository.bzl, tools/workspace/tinyobjloader/repository.bzl, tools/workspace/typing_extensions_internal/repository.bzl
Towards #19715
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19773)
=> Upgrade Externals July 2023

multibody/tree/unit_inertia.cc, multibody/tree/unit_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19761)
=> Move code from unit_inertia.h to unit_inertia.cc. TODO() for later possible breaking change.

tools/workspace/gz_math_internal/package.BUILD.bazel, tools/workspace/gz_math_internal/repository.bzl
Towards #19715
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19776)
=> [workspace] Upgrade gz_math_internal to latest release gz-math7_7.2.0

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
+@TobiaMarcucci for feature review, please
cc @wrangelvid
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19785)
=> Add GraphOfConvexSets::SolveConvexRestriction()

perception/point_cloud.cc, tools/workspace/nanoflann_internal/repository.bzl
Towards #19715
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19775)
=> [workspace] Upgrade nanoflann_internal to latest release v1.5.0

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19789)
=> [pybind] Add python binding for soft min/max.

tools/workspace/mosek/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19798)
=> Upgrade Mosek patch from 10.0.18 to 10.0.46

geometry/optimization/test/graph_of_convex_sets_test.cc
+@BetsyMcPhail for review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19801)
=> Adjust test tolerance for GraphOfConvexSetsTest

geometry/optimization/graph_of_convex_sets.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19821)
=> Fix UB in GraphOfConvexSets::GetSolutionPath error handling

geometry/render/render_mesh.cc, geometry/render/test/render_mesh_test.cc
Closes #19809.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19815)
=> [geometry] Demote warning message for too many materials

geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer.h, geometry/test/meshcat_visualizer_test.cc
Amends #19287.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19813)
=> [geometry] Fix MeshcatVisualizer initialization of alpha slider

systems/framework/diagram.cc, systems/framework/diagram.h
Closes #19711.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19746)
=> [framework] Improve DiagramBuilder::Build performance

manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf, manipulation/models/iiwa_description/sdf/iiwa14_polytope_collision.sdf, manipulation/models/iiwa_description/test/iiwa14_variants_parsing_test.cc, manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14.xacro, manipulation/models/iiwa_description/urdf/iiwa14_no_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf, manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19830)
=> Updated inertias for link 2 and link 4 for the kuka iiwa

geometry/optimization/test/iris_in_configuration_space_test.cc
+@cohnt for feature review, please?
To see these, use
```
bazel build //geometry/optimization:iris_in_configuration_space_test && bazel-bin/geometry/optimization/iris_in_configuration_space_test
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19834)
=> Adds more meshcat visualizations for IrishInConfigurationSpace tests.

geometry/optimization/BUILD.bazel, geometry/optimization/cspace_free_box.cc, geometry/optimization/cspace_free_box.h, geometry/optimization/cspace_free_polytope.cc, geometry/optimization/cspace_free_polytope_base.cc, geometry/optimization/cspace_free_polytope_base.h, geometry/optimization/test/c_iris_test_utilities.h, geometry/optimization/test/cspace_free_box_with_mosek_test.cc
Refactor the code in CspaceFreePolytope::FindSeparationCertificateGivenPolytope and CspaceFreeBox::FindSeparationCertificateGivenBox. Factor out the common part to CspaceFreePolytopeBase.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19742)
=> CspaceFreeBox find separation certificates for a given box.

geometry/optimization/test/iris_in_configuration_space_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19844)
=> Adjust termination conditions for IRIS-NP on focal

geometry/optimization/BUILD.bazel, geometry/optimization/iris.cc, geometry/optimization/iris.h, geometry/optimization/test/iris_in_configuration_space_test.cc
Also adds a more detailed explaination for the adversarial test case in ConvexConfigurationSpace. It's truly devious!
+@rhjiang for feature review (and a serious look).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19847)
=> Add optional visualization debugging to IrisInConfigurationSpace

solvers/mathematical_program.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19849)
=> Clarify the documentation of AddMaximizeLogDeterminantCost.

bindings/pydrake/solvers/solvers_py_evaluators.cc, bindings/pydrake/solvers/test/evaluators_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19839)
=> add pybind for MinimumValueConstraint

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/plant/test/joint_limits_test.cc, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/spatial_inertia_test.cc, multibody/tree/test/unit_inertia_test.cc, multibody/tree/unit_inertia.cc, multibody/tree/unit_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19803)
=> Add SpatialInertia::SolidCylinderWithMassAboutEnd()

math/quaternion.h, math/roll_pitch_yaw.cc, math/rotation_matrix.cc, math/rotation_matrix.h, multibody/tree/linear_bushing_roll_pitch_yaw.cc, multibody/tree/rotational_inertia.h, multibody/tree/unit_inertia.cc, multibody/tree/unit_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19853)
=> Change template type T(doubleNumber) to just doubleNumber in part of code.

solvers/mathematical_program.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19856)
=> Clarify the documentation for AddMaximizeGeometricMeanCost

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/test/hyperellipsoid_test.cc
Also known as the "outer Loewner-John" ellipsoid.
+@AlexandreAmice for feature review, please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19857)
=> Implements Hyperellipsoid::MinimumVolumeCircumscribedEllipsoid

multibody/contact_solvers/block_sparse_cholesky_solver.cc, multibody/contact_solvers/block_sparse_cholesky_solver.h, multibody/contact_solvers/test/block_sparse_cholesky_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19807)
=> BlockSparseCholeskySolver computes Schur complement

systems/framework/system.cc, systems/framework/system_base.cc, systems/framework/system_base.h
Closes #19758. Amends #18687.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19875)
=> [framework] Fix wrong SystemId on the ports of a cloned system

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/__init__.py, bindings/pydrake/common/module_py.cc, bindings/pydrake/common/test/text_logging_example.py, bindings/pydrake/common/test/text_logging_test.py, bindings/pydrake/common/test/text_logging_test_helpers_py.cc, bindings/pydrake/common/test/text_logging_threading_direct_to_stderr_test.py, bindings/pydrake/common/test/text_logging_threading_with_gil_release_test.py, bindings/pydrake/common/text_logging_pybind.cc, bindings/pydrake/common/text_logging_pybind.h, bindings/pydrake/pydrake_doxygen.h, doc/doxygen_cxx/doxygen.h
Closes #19695.  Closes #19680. Relates #19685.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19703)
=> [py common] Add use_native_cpp_logging feature

bindings/pydrake/visualization/_meldis.py, bindings/pydrake/visualization/test/meldis_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19848)
=> Added visualization triads in meldis

bindings/pydrake/BUILD.bazel, bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/bezier_curve.cc, common/trajectories/bezier_curve.h, common/trajectories/test/bezier_curve_test.cc
This will enable us to write many optimizations over Bezier curves without resorting to symbolic Expression parsing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19867)
=> Implements BezierCurve::AsLinearInControlPoints()

geometry/BUILD.bazel, geometry/proximity/BUILD.bazel, geometry/render/BUILD.bazel, geometry/render_gl/BUILD.bazel, multibody/parsing/BUILD.bazel, tools/workspace/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/tinyobjloader/patches/double_precision.patch, tools/workspace/tinyobjloader_internal/BUILD.bazel, tools/workspace/tinyobjloader_internal/package.BUILD.bazel, tools/workspace/tinyobjloader_internal/patches/default_texture_color.patch, tools/workspace/tinyobjloader_internal/patches/faster_float_parsing.patch, tools/workspace/tinyobjloader_internal/repository.bzl
We are applying custom patches to our copy of tinyobyloader. As such, it needs to be badged as "internal".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19880)
=> [workspace] Deprecate the tinyobjloader external

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/test/graph_of_convex_sets_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19874)
=> [GCS] Use SparseMatrix for linear perspective constraints

lcmtypes/BUILD.bazel, tools/install/install.bzl, tools/workspace/lcm/package.BUILD.bazel
The build system should never just give up and print to the console.
Follow-up to prevent #19836 from slipping through next time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19861)
=> [install] Promote unknown-path warnings to errors

bindings/pydrake/common/test_utilities/numpy_compare.py, bindings/pydrake/geometry/test/render_engine_gl_test.py
+@SeanCurtis-TRI for both reviews, please?
Amends #12861.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19913)
=> [py geometry] Actually test the RenderEngineGl bindings at all ever

geometry/BUILD.bazel, tools/workspace/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/new_release.py, tools/workspace/usockets/repository.bzl, tools/workspace/usockets_internal/BUILD.bazel, tools/workspace/usockets_internal/package.BUILD.bazel, tools/workspace/usockets_internal/repository.bzl, tools/workspace/uwebsockets/repository.bzl, tools/workspace/uwebsockets_internal/BUILD.bazel, tools/workspace/uwebsockets_internal/package.BUILD.bazel, tools/workspace/uwebsockets_internal/repository.bzl
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19889)
=> [workspace] Deprecate the usockets and uwebsockets externals

.bazeliskrc, doc/_pages/from_source.md, setup/ubuntu/source_distribution/install_prereqs.sh, tools/wheel/image/provision-base.sh, tools/workspace/drake_visualizer/image/provision.sh
Resolves #19858
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19891)
=> Upgrade to Bazel 6.3.1

systems/sensors/BUILD.bazel, systems/sensors/camera_config.cc, systems/sensors/camera_config.h, systems/sensors/camera_config_functions.cc, systems/sensors/camera_config_functions.h, systems/sensors/sim_rgbd_sensor.cc, systems/sensors/sim_rgbd_sensor.h, systems/sensors/test/camera_config_functions_test.cc
\CC @SeanCurtis-TRI FYI
Towards #19437.  Requires #19899 (will rebase).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19898)
=> [sensors] Add output_delay and capture_offset to CameraConfig

systems/framework/diagram_builder.h, systems/framework/test/diagram_builder_test.cc
`Diagram` already supports this. This gives `DiagramBuilder` the analogous functionality.
In contrast with `Diagram`, this uses the hypothesis that the extra C++ plumbing doesn't need to be documented in doxygen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19925)
=> Allow GetDowncastSubsystemByName to work with non-templatized system

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19921)
=> Add python binding for MinimumDistanceConstraint with CollisionChecker.

tools/workspace/abseil_cpp_internal/repository.bzl, tools/workspace/dm_control_internal/repository.bzl, tools/workspace/new_release.py, tools/workspace/optitrack_driver/repository.bzl, tools/workspace/platforms/repository.bzl, tools/workspace/voxelized_geometry_tools/repository.bzl
Towards #19865
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19929)
=> Upgrade Externals August 2023

bindings/pydrake/common/yaml.py, examples/acrobot/test/spong_sim_main_test.py, geometry/test/meshcat_websocket_client.py, tools/workspace/pycodestyle/repository.bzl
Towards #19865.
Some *pycodestyle tests are failing after the update.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19933)
=> [workspace] Upgrade pycodestyle to latest release 2.11.0

bindings/pydrake/planning/planning_py.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py
Fix #19937
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19938)
=> [pybind] import pydrake.trajectories in traj_opt

common/symbolic/latex.cc, common/symbolic/test/latex_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19941)
=> Improve ToLatex support for inf, nan, π, and e.

systems/sensors/test/camera_config_functions_test.cc
This had rolled its own GetSystem() method to extract a down cast system from the builder. This was necessary, because the systems being extracted weren't templated.
DiagramBuilder now supports down casting for untemplated systems and so we shift to using that API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19953)
=> Update CameraConfig functions test to use DiagramBuilder API

bindings/pydrake/visualization/_meldis.py, bindings/pydrake/visualization/test/meldis_test.py
Closes #19763.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19878)
=> [py visualization] Fix Meldis to recognize mesh file content changes

tools/workspace/cmake_configure_file.bzl, tools/workspace/cmake_configure_file.py, tools/workspace/coinutils_internal/BUILD.bazel, tools/workspace/coinutils_internal/defs.bzl, tools/workspace/ipopt_internal_fromsource/package.BUILD.bazel
Towards #19928 and #17231.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19930)
=> [workspace] Simplify Ipopt build rules with some abstractions

bindings/pydrake/multibody/rational_py.cc, bindings/pydrake/multibody/test/rational_test.py, geometry/optimization/cspace_free_box.cc, geometry/optimization/cspace_free_internal.cc, geometry/optimization/cspace_free_internal.h, geometry/optimization/cspace_free_polytope.cc, geometry/optimization/cspace_free_polytope.h, geometry/optimization/cspace_free_polytope_base.cc, geometry/optimization/cspace_free_polytope_base.h, geometry/optimization/cspace_separating_plane.h, geometry/optimization/test/cspace_free_polytope_base_test.cc, multibody/rational/rational_forward_kinematics.cc, multibody/rational/rational_forward_kinematics.h, multibody/rational/test/rational_forward_kinematics_test.cc
Move some functions to CspaceFreePolytopeBase.
#19895 is too large, so I split that PR into two. This is the first PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19900)
=> Clean up CspaceFreePolytope.

bindings/pydrake/solvers/solvers_py_evaluators.cc, bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/evaluators_test.py, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/BUILD.bazel, solvers/binding.h, solvers/constraint.cc, solvers/constraint.h, solvers/cost.cc, solvers/cost.h, solvers/evaluator_base.cc, solvers/evaluator_base.h, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/binding_test.cc, solvers/test/constraint_test.cc, solvers/test/cost_test.cc, solvers/test/mathematical_program_test.cc, tutorials/debug_mathematical_program.ipynb, tutorials/mathematical_program.ipynb
This has been on my list of a long time... and it really makes `MathematicalProgram` beautiful!
Here is the example from the `debug_mathematical_program.ipynb` tutorial:
```
prog = MathematicalProgram()
x = prog.NewContinuousVariables(3, "x")
prog.AddQuadraticCost(x[0] * x[0] + 2 * x[0] + 3)
prog.Add2NormSquaredCost(A = [[1, 3], [2, 4]], b=[1, 4], vars=[x[1], x[2]])
prog.AddLinearEqualityConstraint(x[0] + 2*x[1] == 5)
prog.AddLinearConstraint(x[0] + 4 *x[1] <= 10)
prog.AddBoundingBoxConstraint(-1, 10, x)
display(Markdown(prog.ToLatex()))
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19942)
=> Implements MathematicalProgram::ToLatex()

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19962)
=> Adds binding for MathematicalProgram::AddLinearConstraint(a,lb,ub,vars)

common/test_utilities/BUILD.bazel, common/test_utilities/maybe_pause_for_user.cc, common/test_utilities/maybe_pause_for_user.h, geometry/BUILD.bazel, geometry/optimization/BUILD.bazel, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/iris_in_configuration_space_test.cc, geometry/test/meshcat_manual_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19971)
=> [geometry] Factor MaybePauseForUser to test_utilities/

bindings/pydrake/geometry/geometry_py_scene_graph.cc, bindings/pydrake/geometry/test/scene_graph_test.py, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, examples/manipulation_station/manipulation_station.cc, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/internal_frame.h, geometry/internal_geometry.h, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/geometry_state_test.cc, geometry/test/internal_geometry_test.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc, multibody/tree/BUILD.bazel, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree.h, multibody/tree/test/model_instance_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19939)
=> [multibody] Introduce plant.RenameModelInstance()

geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_test.cc
Closes #19362.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19960)
=> [geometry] Increase range of Meshcat's search for an open port

bindings/pydrake/examples/gym/envs/cart_pole.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19976)
=> Port to parser.AddModels, part 10

lcm/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19977)
=> Remove useless, out-of-date README.md

geometry/collision_filter_declaration.h, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/proximity/BUILD.bazel, geometry/proximity/collision_filter.cc, geometry/proximity/collision_filter.h, geometry/proximity/deformable_contact_internal.cc, geometry/proximity/deformable_contact_internal.h, geometry/proximity/test/collision_filter_test.cc, geometry/proximity/test/collisions_exist_callback_test.cc, geometry/proximity/test/deformable_contact_internal_test.cc, geometry/proximity/test/distance_sphere_to_shape_test.cc, geometry/proximity/test/find_collision_candidates_callback_test.cc, geometry/proximity/test/hydroelastic_callback_test.cc, geometry/proximity/test/penetration_as_point_pair_callback_test.cc, geometry/proximity_engine.cc, geometry/scene_graph.h, geometry/test/geometry_state_test.cc, geometry/test/proximity_engine_test.cc, multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/deformable_collision_filter_test.cc
Closes #19854
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19897)
=> Support collision filtering for deformable geometries

bindings/pydrake/multibody/all.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19991)
=> [fix_inertia] Make sure fix_inertia gets into pydrake documentation

bindings/pydrake/planning/test/trajectory_optimization_test.py
Towards #19987.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19994)
=> [py planning] Add non-MOSEK unit test of GCS bindings

bindings/pydrake/planning/planning_py.cc, bindings/pydrake/planning/planning_py_trajectory_optimization.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19995)
=> [py planning] Clean up an import order TODO

doc/_pages/release_playbook.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19999)
=> [release] Remind drake-ros to update DRAKE_SUGGESTED_VERSION

tools/workspace/meshcat/README.md, tools/workspace/meshcat/repository.bzl
Also makes a minor update to the meshcat workspace documenation.
Closes #19973.
Closes #18542.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20000)
=> Update meshcat to include resizable control panel

bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/_lcm_image_array_viewer.py, bindings/pydrake/visualization/test/lcm_image_array_viewer_test.py
Toward #18862 
TODO:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19963)
=> Add lcm_image_array_viewer for image visualization

doc/_pages/release_playbook.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20004)
=> [doc] Caveats and corrections for release playbook

visualization/visualization_config_functions.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20005)
=> Fix a typo in the documentation of ApplyVisualizationConfig

tools/workspace/meshcat/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20016)
=> Update instructions for bumping meshcat commit

bindings/pydrake/planning/BUILD.bazel, bindings/pydrake/planning/planning_py.cc, bindings/pydrake/planning/planning_py.h, bindings/pydrake/planning/planning_py_collision_checker.cc, bindings/pydrake/planning/planning_py_visibility_graph.cc, bindings/pydrake/planning/test/collision_checker_test.py, geometry/optimization/test/iris_in_configuration_space_test.cc, planning/BUILD.bazel, planning/collision_checker.cc, planning/collision_checker.h, planning/test/collision_checker_test.cc, planning/test/visibility_graph_test.cc, planning/visibility_graph.cc, planning/visibility_graph.h
This constructs a visibility graph by running
CollisionChecker::CheckEdgeCollsionFree to create the adjacency matrix, with support for cpu parallelization.
+@calderpg-tri for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19914)
=> Implements planning::VisibilityGraph()

tools/release_engineering/dev/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20018)
=> [doc] Updates to Docker/Apt/S3 release documentation

common/test_utilities/BUILD.bazel, common/test_utilities/maybe_pause_for_user.cc, common/test_utilities/maybe_pause_for_user.h, common/test_utilities/test/maybe_pause_for_user_manual_test.cc, common/test_utilities/test/maybe_pause_for_user_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20031)
=> [common] Fix hangs with MaybePauseForUser

bindings/pydrake/geometry/geometry_py_optimization.cc
Resolves #20047
Not really sure if/how I should improve the test to have caught this?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20050)
=> Add missing py_reference_internal

CMakeLists.txt, cmake/modules/FindGurobi.cmake, doc/_pages/bazel.md, doc/_pages/python_bindings.md, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/test/global_inverse_kinematics_reachable_test.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_test.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.cc, multibody/inverse_kinematics/test/global_inverse_kinematics_test_util.h, solvers/gurobi_solver.cc, solvers/gurobi_solver.h, solvers/mathematical_program_result.h, solvers/solver_options.h, solvers/test/gurobi_solver_test.cc, tools/bazel.rc, tools/dynamic_analysis/tsan.supp, tools/workspace/gurobi/package-macos.BUILD.bazel.in, tools/workspace/gurobi/package-ubuntu.BUILD.bazel.in, tools/workspace/gurobi/repository.bzl
Resolves #18352
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19766)
=> Upgrade to Gurobi 10.0.2

multibody/inverse_kinematics/test/global_inverse_kinematics_reachable_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20062)
=> Relax the tolerance for global IK reachable test.

common/symbolic/BUILD.bazel, common/symbolic/decompose.cc, common/symbolic/test/decompose_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20060)
=> Fix some awkward grammar in an error message

tools/dynamic_analysis/valgrind.supp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20067)
=> Suppress a memory check issue since gurobi upgrade to 10.0.2

systems/sensors/vtk_image_reader_writer.cc
Amends #20026.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20070)
=> [sensors] Fix VTK memory writer

systems/controllers/inverse_dynamics_controller.cc
This substantially improves the Graphviz debug output:
+@RussTedrake for both(?) reviews, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20078)
=> [controllers] Set subsystem names within InverseDynamicsController

geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat.html, multibody/hydroelastics/hydroelastic_user_guide_doxygen.h, systems/systems.h
Closes #20043.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20063)
=> [doc] Update links to new Meshcat org homepage

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py, systems/framework/system_base.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20073)
=> Add binding for Systems::ValidateContext

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py, examples/planar_gripper/planar_gripper_simulation.cc, manipulation/kuka_iiwa/build_iiwa_control.cc, systems/controllers/inverse_dynamics.cc, systems/controllers/inverse_dynamics.h, systems/controllers/inverse_dynamics_controller.cc, systems/controllers/inverse_dynamics_controller.h, systems/controllers/test/inverse_dynamics_controller_test.cc, systems/controllers/test/inverse_dynamics_test.cc
See also #20080 and #20082.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20079)
=> [controllers] Use descriptive InverseDynamics port names

examples/hardware_sim/BUILD.bazel, examples/hardware_sim/hardware_sim.py
Closes #20054.
Amends #19869.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20077)
=> [hardware_sim] Fix deprecation warnings

multibody/fem/BUILD.bazel, multibody/fem/constitutive_model.h, multibody/fem/corotated_model.h, multibody/fem/fem_element.h, multibody/fem/fem_model.h, multibody/fem/fem_model_impl.h, multibody/fem/fem_solver.cc, multibody/fem/fem_solver.h, multibody/fem/linear_constitutive_model.h, multibody/fem/linear_corotated_model.h, multibody/fem/test/corotated_model_test.cc, multibody/fem/test/dummy_element.h, multibody/fem/test/dummy_model.cc, multibody/fem/test/dummy_model.h, multibody/fem/test/fem_element_test.cc, multibody/fem/test/fem_model_test.cc, multibody/fem/test/fem_solver_test.cc, multibody/fem/test/linear_constitutive_model_test.cc, multibody/fem/test/linear_corotated_model_test.cc, multibody/fem/test/volumetric_element_test.cc, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19972)
=> FemSolver uses SchurComplement for linear models

multibody/fem/test/fem_model_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20088)
=> [hotfix] Increase tolerance for FEM model test

common/symbolic/decompose.cc
Motivated by slack discussion https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1692903961875319
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20065)
=> Improve error message for DecomposeLinearExpression and DecomposeAffineExpression.

systems/controllers/linear_model_predictive_controller.cc, systems/estimators/luenberger_observer.cc, systems/framework/diagram_builder.cc, systems/framework/diagram_builder.h, systems/framework/system.cc, systems/framework/system.h, systems/framework/test/diagram_builder_test.cc, systems/framework/test/system_test.cc
Closes #20082.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20090)
=> [framework] Adjust "sole port" getters to work around deprecation

BUILD.bazel, manipulation/util/BUILD.bazel, tools/BUILD.bazel, tools/model_visualizer_private.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20091)
=> [tools] Provide model_visualizer access to some test models

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Resolves #19203 (at least one way)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19204)
=> [plant] Add MultibodyPlant::GetDefaultPositions()

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/module_py.cc, bindings/pydrake/common/test/module_test.py, common/BUILD.bazel, common/parallelism.cc, common/parallelism.h, common/test/parallelism_test.cc, doc/doxygen_cxx/doxygen.h, perception/BUILD.bazel, perception/point_cloud.cc, perception/point_cloud.h, tools/skylark/README.md, tools/skylark/kwargs.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20093)
=> Copy Parallelism code from TRI and adapt for Drake

common/test/parallelism_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20101)
=> [common] Hotfix for parallelism_test

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/tree/multibody_forces.h
and a comment to help find it. This came up in
https://stackoverflow.com/questions/77003297/how-to-initialize-a-multibody-force-object-for-calcforceelementscontribution
+@amcastro-tri for feature review, please. (to make sure you agree with the comment I added)
+@jwnimmer-tri for platform/binding review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20102)
=> Add bindings for MultibodyPlant::CalcGeneralizedForce()

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py
Towards #20117.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20119)
=> [py symbolic] Bind Formula(bool) constructor

doc/_pages/installation.md, doc/_pages/stable.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20121)
=> [doc] More clearly explain our version support timelines

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_pd_controller_constraint.cc, multibody/contact_solvers/sap/sap_pd_controller_constraint.h, multibody/contact_solvers/sap/test/sap_pd_controller_constraint_test.cc
Towards #19067.
cc'ing @joemasterjohn, since I'll ask you to review the next PR that wires this up in the plant.
cc'ing @JoseBarreiros-TRI, since you need this feature for your project.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20110)
=> Implements SAP constraint to model PD controllers

geometry/proximity/BUILD.bazel, geometry/proximity/detect_zero_simplex.cc, geometry/proximity/detect_zero_simplex.h, geometry/proximity/test/detect_zero_simplex_test.cc
This PR is a prequel to #19550. We work on detect_zero_simplex in this PR, and 19550 will use detect_zero_simplex in volume_mesh_refiner.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19699)
=> [geometry] Detect problems in hydroelastic tetrahedral meshes

tools/workspace/stable_baselines3_internal/patches/version.patch, tools/workspace/stable_baselines3_internal/repository.bzl
Towards #20108
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20147)
=> [workspace] Upgrade stable_baselines3_internal to latest release v2.1.0

tools/install/bazel/test/drake_bazel_installed_test.py, tools/workspace/buildifier/repository.bzl, tools/workspace/googlebenchmark/repository.bzl, tools/workspace/gymnasium_py/repository.bzl, tools/workspace/mypy_internal/repository.bzl, tools/workspace/rules_python/repository.bzl, tools/workspace/tinyobjloader_internal/repository.bzl
Towards #20108
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20148)
=> Upgrade Externals September 2023

bindings/pydrake/math_py.cc, bindings/pydrake/test/math_overloads_matrix_test.py, common/symbolic/expression/expression.cc, common/symbolic/expression/expression.h, common/symbolic/expression/test/expression_matrix_test.cc, common/symbolic/polynomial.cc, common/symbolic/polynomial.h, common/symbolic/test/monomial_test.cc, common/symbolic/test/polynomial_matrix_test.cc, common/symbolic/test/polynomial_test.cc, systems/primitives/test/linear_system_test.cc
This is a subset of the the code in #20057, plus a few fixes and more tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20099)
=> [common] Add polynomial matrix multiplication overloads

common/symbolic/BUILD.bazel, common/symbolic/decompose.cc, common/symbolic/generic_polynomial.h, common/symbolic/latex.cc, common/symbolic/monomial.cc, common/symbolic/monomial.h, common/symbolic/monomial_basis_element.h, common/symbolic/polynomial.cc, common/symbolic/polynomial.h, common/symbolic/rational_function.cc, common/symbolic/rational_function.h, common/symbolic/test/codegen_test.cc, common/symbolic/test/decompose_test.cc, common/symbolic/test/polynomial_basis_element_test.cc, common/symbolic/test/rational_function_test.cc, common/symbolic/test/simplification_test.cc, common/symbolic/trigonometric_polynomial.cc, common/symbolic/trigonometric_polynomial.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20158)
=> [symbolic] Opt-in to clang-format-lint

examples/bouncing_ball/BUILD.bazel, multibody/benchmarks/free_body/BUILD.bazel, multibody/plant/BUILD.bazel, multibody/tree/BUILD.bazel, systems/analysis/BUILD.bazel
Noticed during #20130.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20166)
=> [systems] Remove spurious deps

manipulation/kuka_iiwa/BUILD.bazel, manipulation/kuka_iiwa/build_iiwa_control.cc, manipulation/kuka_iiwa/iiwa_command_receiver.cc, manipulation/kuka_iiwa/iiwa_command_receiver.h, manipulation/kuka_iiwa/iiwa_command_sender.cc, manipulation/kuka_iiwa/iiwa_constants.cc, manipulation/kuka_iiwa/iiwa_constants.h, manipulation/kuka_iiwa/iiwa_driver_functions.cc, manipulation/kuka_iiwa/iiwa_status_receiver.cc, manipulation/kuka_iiwa/iiwa_status_sender.cc, manipulation/kuka_iiwa/test/iiwa_command_receiver_test.cc, manipulation/kuka_iiwa/test/iiwa_command_sender_test.cc, manipulation/kuka_iiwa/test/iiwa_constants_test.cc
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20168)
=> [kuka_iiwa] Opt-in to clang-format lint

bindings/pydrake/visualization/test/model_visualizer_test.py
Amends #20129 for a missing import.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20170)
=> [py visualization] Hotfix TestModelVisualizer.test_reload

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_constraint.h, multibody/contact_solvers/sap/sap_fixed_constraint.cc, multibody/contact_solvers/sap/sap_fixed_constraint.h, multibody/contact_solvers/sap/test/sap_fixed_constraint_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20098)
=> [multibody] Add SapFixedConstraint

tutorials/nonlinear_program.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20192)
=> [tutorial] Fix LaTeX display in nonlinear program

systems/lcm/BUILD.bazel, systems/lcm/lcm_buses.cc, systems/lcm/lcm_buses.h, systems/lcm/lcm_config_functions.cc, systems/lcm/lcm_config_functions.h, systems/lcm/lcm_interface_system.cc, systems/lcm/lcm_interface_system.h, systems/lcm/lcm_log_playback_system.cc, systems/lcm/lcm_publisher_system.cc, systems/lcm/lcm_publisher_system.h, systems/lcm/lcm_scope_system.cc, systems/lcm/lcm_scope_system.h, systems/lcm/lcm_subscriber_system.cc, systems/lcm/serializer.h, systems/lcm/test/lcm_config_functions_test.cc, systems/lcm/test/lcm_interface_system_test.cc, systems/lcm/test/lcm_log_playback_test.cc, systems/lcm/test/lcm_publisher_system_test.cc, systems/lcm/test/lcm_scope_system_test.cc, systems/lcm/test/lcm_subscriber_system_test.cc, systems/lcm/test/serializer_test.cc
Towards #4843.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20197)
=> [systems/lcm] Opt-in to clang-format-lint

multibody/parsing/test/parser_test.cc, tools/workspace/sdformat_internal/patches/deprecation_unit_testing.patch, tools/workspace/sdformat_internal/patches/no_urdf.patch, tools/workspace/sdformat_internal/repository.bzl
Mainly fixes an issue with deeply nested merge-includes for custom parsed files needed by #16727 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20195)
=> [workspace] Upgrade sdformat_internal to latest release sdformat13_13.6.0

multibody/plant/BUILD.bazel, multibody/plant/deformable_ids.h, multibody/plant/deformable_model.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20216)
=> Move DeformableBodyId/Index out of deformable_model.h

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_weld_constraint.cc, multibody/contact_solvers/sap/sap_weld_constraint.h, multibody/contact_solvers/sap/test/sap_weld_constraint_test.cc, multibody/plant/BUILD.bazel, multibody/plant/constraint_specs.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/sap_driver.h, multibody/plant/test/sap_driver_distance_constraints_test.cc, multibody/plant/test/sap_driver_weld_constraints_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19608)
=> [multibody] Add SapWeldConstraint

.github/ISSUE_TEMPLATE/BUG.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20218)
=> [github] Add macOS 13 to issue template drop-down

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py, bindings/pydrake/systems/test/general_test.py, examples/hardware_sim/hardware_sim.cc, systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/system.cc, systems/framework/system.h, systems/framework/system_base.cc, systems/framework/system_base.h, systems/framework/test/diagram_test.cc, systems/framework/test/leaf_system_test.cc
Towards #20203.
---
Using the command line from #20198, we can see the change in output.
Before this PR:
After this PR:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20204)
=> [framework] Improve system graphviz output

common/symbolic/monomial.h, common/symbolic/polynomial.h
Towards #20202.
During reviews of prior changes to these files, we failed to detect the diverging comment formatting styles, so the classes were mixes of all different styles.  Repave both files entirely, using our modern comment formatting style.  This will make future changes go more smoothly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20213)
=> [symbolic] Unify comment formatting in Polynomial and Monomial

bindings/pydrake/solvers/_extra.py, bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
Closes #20150.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20178)
=> [py solvers] Improve error message for evaluator return type mistakes

examples/hardware_sim/hardware_sim.cc, examples/hardware_sim/hardware_sim.py, examples/hardware_sim/test/hardware_sim_test_common.py
Amends #20204.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20227)
=> [hardware_sim] Fix graphviz output

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py, systems/framework/diagram_builder.cc, systems/framework/diagram_builder.h, systems/framework/test/diagram_builder_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20239)
=> [framework] Add DiagramBuilder num_{input/output}_ports accessors

solvers/test/clp_solver_test.cc, solvers/test/gurobi_solver_test.cc, solvers/test/ipopt_solver_test.cc, solvers/test/linear_program_examples.cc, solvers/test/linear_program_examples.h, solvers/test/mosek_solver_test.cc, solvers/test/scs_solver_test.cc, solvers/test/snopt_solver_test.cc
When the BoundingBoxConstraint is an equality constraint on the variable, the dual solution could be tricky. We add more tests to make sure the dual solution is correct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20160)
=> Add more tests on the BoundingBoxConstraint dual solution.

geometry/query_results/deformable_contact.cc, geometry/query_results/deformable_contact.h, geometry/query_results/test/deformable_contact_test.cc, multibody/contact_solvers/sap/sap_fixed_constraint.cc, multibody/contact_solvers/sap/sap_fixed_constraint.h, multibody/contact_solvers/sap/test/sap_fixed_constraint_test.cc, multibody/plant/BUILD.bazel, multibody/plant/constraint_specs.h, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/deformable_model.cc, multibody/plant/deformable_model.h, multibody/plant/test/deformable_driver_contact_kinematics_test.cc, multibody/plant/test/deformable_model_test.cc
Specify fixed constraints between a rigid body and and a deformable body This commit does not implement or enforce the constraints yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20041)
=> Specify fixed constraints

planning/BUILD.bazel, planning/robot_diagram_builder.cc, planning/robot_diagram_builder.h, planning/test/robot_diagram_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20241)
=> [planning] RobotDiagramBuilder fails fast on a missing MbP or SG

geometry/render/render_doxygen.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20248)
=> Add RenderEngineGltfClient to the rendering documentation

multibody/plant/sap_driver.cc, multibody/plant/test/sap_driver_test.cc
Closes #20103
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20177)
=> Fix segfault in SAP when caching is disabled

solvers/mosek_solver.cc
Note: there is no modification to the unit tests, because we don't test license acquisition failure. This will rely on review to confirm that this is sane.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20262)
=> Mosek license acquisition failure prints more info

multibody/plant/BUILD.bazel, multibody/plant/sap_driver.cc, multibody/plant/sap_driver.h, multibody/plant/test/deformable_fixed_constraint_test.cc
Also add an integration test for fixed constraints between deformable bodies and rigid bodies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20249)
=> SapDriver supports fixed constraints

solvers/mosek_solver.cc
Hot fix for #20262
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20269)
=> [hotfix] Mac fmt::format chokes on enum

tools/workspace/clang_cindex_python3_internal/changelog.txt, tools/workspace/clang_cindex_python3_internal/patches/clang-15.patch, tools/workspace/clang_cindex_python3_internal/repository.bzl, tools/workspace/pybind11/mkdoc.py
Works around #20258.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20261)
=> [workspace] Patch clang.cindex vs Clang 15

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/gravity_test.cc, multibody/tree/uniform_gravity_field_element.cc, multibody/tree/uniform_gravity_field_element.h, systems/controllers/inverse_dynamics.h, systems/controllers/inverse_dynamics_controller.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20264)
=> Implement APIs to enable/disable gravity

tools/workspace/glew/repository.bzl, tools/workspace/liblzma/repository.bzl, tools/workspace/pkg_config.bzl
+@sammy-tri for both reviews per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20275)
=> [workspace] Fix deprecation notations in pkg-config

geometry/BUILD.bazel, geometry/proximity/test/vtk_to_volume_mesh_test.cc, geometry/proximity/vtk_to_volume_mesh.cc, geometry/test/bad_tet.vtk, geometry/test/cube_as_6_squares.vtk, geometry/test/some_volume.vtk, geometry/test/unstructured.vtk
Add some slightly more adversarial VTK files to the test suite, and improve error reporting for VTK parse failures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20240)
=> [geometry] Strengthen VTK to volume mesh error cases

tools/install/libdrake/test/snopt_visibility_install_test.py
See https://docs.python.org/3/whatsnew/3.3.html#porting-python-code, second bullet point.
+@sammy-tri for both reviews per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20277)
=> [tools] Fix mis-detection of linux platform

bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/_lcm_image_array_viewer.py, bindings/pydrake/visualization/_video.py, bindings/pydrake/visualization/test/video_test.py
Relates #20221
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20254)
=> [visualization] ColorizeDepthImage takes 32F and 16U depth as input

multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.cc, multibody/benchmarks/chaotic_babyboot/MG/MG_chaotic_babyboot_auto_generated.h
Addresses #20258
@jwnimmer-tri for review, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20287)
=> Refactor MGChaoticBabyboot methods to use explicit array sizes.

tools/workspace/vtk_internal/patches/io_legacy_data_reader_uninit.patch, tools/workspace/vtk_internal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20286)
=> [vtk_internal] Patch to work around memcheck false positives

geometry/optimization/cspace_separating_plane.h
+@SeanCurtis-TRI for both reviews per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20291)
=> [optimization] Remove deprecated code 2023-10

doc/_pages/jenkins.md
Resolves #19860
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20293)
=> [doc] Add links to experimental Jenkins bot commands

tools/workspace/build_bazel_apple_support/repository.bzl, tools/workspace/dm_control_internal/repository.bzl, tools/workspace/rules_rust/repository.bzl, tools/workspace/suitesparse_internal/repository.bzl, tools/workspace/typing_extensions_internal/repository.bzl, tools/workspace/yaml_cpp_internal/repository.bzl
Towards #20290.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20304)
=> Upgrade Externals October 2023

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/solvers_py_evaluators.cc, bindings/pydrake/solvers/test/evaluators_test.py, multibody/inverse_kinematics/inverse_kinematics.cc, multibody/inverse_kinematics/inverse_kinematics.h, multibody/inverse_kinematics/minimum_distance_constraint.cc, multibody/inverse_kinematics/minimum_distance_constraint.h, multibody/inverse_kinematics/minimum_distance_lower_bound_constraint.cc, multibody/inverse_kinematics/minimum_distance_lower_bound_constraint.h, multibody/inverse_kinematics/minimum_distance_upper_bound_constraint.cc, multibody/inverse_kinematics/minimum_distance_upper_bound_constraint.h, multibody/inverse_kinematics/test/inverse_kinematics_test.cc, multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc, solvers/minimum_value_constraint.h, solvers/test/minimum_value_constraint_test.cc
Replace it with MinimumDistanceLowerBoundConstraint and MinimumDistanceUpperBoundConstraint. Also add the python binding for these two new constraints.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20282)
=> Deprecate MinimumDistanceConstraint.
