RobotLocomotion/drake

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/BUILD.bazel, multibody/parsing/detail_composite_parse.cc, multibody/parsing/detail_composite_parse.h, multibody/parsing/detail_dmd_parser.cc, multibody/parsing/detail_make_model_name.cc, multibody/parsing/detail_make_model_name.h, multibody/parsing/detail_mesh_parser.cc, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/detail_parsing_workspace.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/parser.h, multibody/parsing/test/detail_make_model_name_test.cc, multibody/parsing/test/detail_mesh_parser_test.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_select_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/parser_test.cc
Add a parser option {Set,Get}AutoRenaming(bool). When enabled, the parser will resolve model naming conflicts by adding a numeric subscript to names.
This is another step in the long march toward retiring Parser APIs that assume and/or enforce single-model-per-input-text conditions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18921)
=> [parsing] Support auto-renaming of models

common/BUILD.bazel, common/find_cache.cc, common/find_cache.h, common/test/find_cache_test.cc
Towards #15774 and #9498.
When we download models from the internet, we need a place to put them.  We could put them in `/tmp`, but that would be a lot of extra downloading.  Instead, we should endeavor to put them into a semi-permanent cache.
For an example use in-situ, see the WIP parser branch [here](https://github.com/jwnimmer-tri/drake/blob/package-map-uberweltenfresser/multibody/parsing/package_map.cc).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18939)
=> [common] Add FindOrCreateCache

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
See C++ code:
https://github.com/RobotLocomotion/drake/blob/520e11aef6fb102eb2752192b4bc76d287db23fe/multibody/plant/multibody_plant.h#L3494-L3500
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18876)
=> [py plant] Deprecate CalcJacobianSpatialVelocity(*, p_BP)

tools/workspace/README.md, tools/workspace/common_robotics_utilities/repository.bzl, tools/workspace/curl_internal/repository.bzl, tools/workspace/github.bzl, tools/workspace/lcm/repository.bzl, tools/workspace/libcmaes/repository.bzl, tools/workspace/meshcat/repository.bzl, tools/workspace/new_release.py, tools/workspace/osqp_internal/repository.bzl, tools/workspace/qdldl_internal/repository.bzl, tools/workspace/rules_python/repository.bzl, tools/workspace/scs_internal/repository.bzl, tools/workspace/usockets/repository.bzl, tools/workspace/uwebsockets/repository.bzl, tools/workspace/voxelized_geometry_tools/repository.bzl
Fix new_release so it can be run via `bazel run`. Teach it to recognize notices that should be displayed during an upgrade. Add markers to externals that have such information. Update documentation.
This should avoid the need for the user running the script to manually inspect each `repository.bzl` to determine if additional actions need to be performed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18928)
=> [tools] Improve new_release script

multibody/parsing/BUILD.bazel, multibody/parsing/detail_sdf_diagnostic.cc, multibody/parsing/detail_sdf_diagnostic.h, multibody/parsing/detail_sdf_geometry.cc, multibody/parsing/detail_sdf_geometry.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_diagnostic_test.cc, multibody/parsing/test/detail_sdf_geometry_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/diagnostic_policy_test_base.h, multibody/parsing/test/parser_test.cc
Work towards https://github.com/RobotLocomotion/drake/issues/17053.
This PR adds filename/lineno to errors and warnings thrown from `detail_sdf_parser.cc`.
Some questions about it:
- Do we see value in creating a similar structure as [detail_tinixml2_diagnostic](https://github.com/RobotLocomotion/drake/blob/master/multibody/parsing/detail_tinyxml2_diagnostic.cc) for sdf? if so, should we add it in a following PR?
- Anything we should do about the exceptions being thrown?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/robotlocomotion/drake/18462)
=> ensure sdf diagnostic includes filename/lineno

bindings/pydrake/geometry/geometry_py_visualizers.cc, bindings/pydrake/geometry/test/visualizers_test.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat_types.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc
This is a handy plotting helper, providing an interface like matplotlib's plot_surface. I've been using a python version of it for years in my course notes, but now I find myself wanting it in C++.
+@xuchenhan-tri for feature review, please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18924)
=> [meshcat] Implement Meshcat::PlotSurface()

multibody/parsing/package_map.cc, multibody/parsing/package_map.h, multibody/parsing/test/package_map_test.cc
Towards https://github.com/RobotLocomotion/drake/pull/18955 and https://github.com/RobotLocomotion/drake/issues/15774 and https://github.com/RobotLocomotion/drake/issues/9498.
Fetching remote packages will involve some locking and atomics, which ends up being too difficult with a header file representation of our member fields.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18961)
=> [parsing] Switch PackageMap to pimpl

tools/performance/benchmark_tool.py
This patch adds support for the Linux kernel's architecture agnostic control of CPU frequency boosting. In practice, this means that drake benchmarking experiments should work on not only Intel machines, but AMD machines (with new enough kernels) as well.
Closes: https://github.com/RobotLocomotion/drake/issues/18942.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18964)
=> [tools] Support benchmarking on more architectures

bindings/pydrake/geometry/geometry_py_visualizers.cc, bindings/pydrake/geometry/test/visualizers_test.py, bindings/pydrake/visualization/_model_visualizer.py, bindings/pydrake/visualization/model_visualizer.py, bindings/pydrake/visualization/test/model_visualizer_test.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_test.cc
Makes the reload feature of ModelVisualizer more robust by setting joint positions in the reloaded model to the prior values of joints with the same names, rather than requiring an exact match of the number of joints before and after.
Also fixes docstrings relating to accessing the visualizer's parser.
Closes #18910.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18949)
=> ModelVisualizer: re-pose joints by name

bindings/pydrake/BUILD.bazel, bindings/pydrake/autodiff_types_pybind.h, bindings/pydrake/autodiffutils_py.cc, bindings/pydrake/math_operators_pybind.h, bindings/pydrake/math_py.cc, bindings/pydrake/symbolic_py.cc, bindings/pydrake/symbolic_py_unapply.h, bindings/pydrake/symbolic_types_pybind.h
Repeating the list of functions in three different places is too difficult to maintain; refactor into a single place.
Remove `inv` methods on symbolic types; the type of `self` would never be able to match so they would always throw (I think?).
Add proper `atan2` kwargs and documentation for all scalars.  Calling `y.atan2(x)` is ... a thing.
Towards https://github.com/RobotLocomotion/drake/issues/11802.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18979)
=> [pydrake] Consolidate the C++ list of math operators

perception/point_cloud.cc, perception/point_cloud.h
Keeping two copies of the cloud's metadata in sync is more work than its worth -- especially as we further customize the flags reconfiguration in #18987.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18989)
=> [perception] Remove duplicated member fields

bindings/pydrake/_math_extra.py, bindings/pydrake/common/__init__.py, bindings/pydrake/common/cpp_template.py, bindings/pydrake/common/cpp_template_pybind.h, bindings/pydrake/common/test/eigen_geometry_test.py, bindings/pydrake/multibody/_math_extra.py, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/systems/scalar_conversion.py, bindings/pydrake/systems/test/value_test.py, doc/pydrake/pydrake_sphinx_extension.py
When a template class has a default type parameter, name the default instantiation directly using the default name, instead of via an alias. This makes IDE auto-complete and type annotations more natural.
---
This improves upon #18587 by avoiding exposing the user to name-mangling in debug output unless they are using non-default template arguments.
Note that this also affects the pydrake website organization.
Previously, the pages ended up [like this](https://drake.mit.edu/pydrake/pydrake.math.html#pydrake.math.BsplineBasis):
- Class Foo
- Alias for Foo_[float]
- Template Class Foo_
- Instantiations: Foo_[float], Foo_[AutoDiffXd], Foo_[Expression]
- Class Foo_[float]
- details
- Class Foo_[AutoDiffXd]
- details
- Class Foo_[Expression]
- details
Now it ends up like this:
- Class Foo
- …
=> [pydrake] Use nice names for default template classes

examples/manipulation_station/manipulation_station.h
Remove in the attempt to fix #18980. It does not solve it, but definitely an unnecessary change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19004)
=> Removes unnecessary forward declaration from ManipulationStation

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/create_constraint.cc, solvers/create_constraint.h, solvers/get_program_type.cc, solvers/ipopt_solver.cc, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/nlopt_solver.cc, solvers/snopt_solver.cc, solvers/test/create_constraint_test.cc, solvers/test/ipopt_solver_test.cc, solvers/test/mathematical_program_test.cc, solvers/test/nlopt_solver_test.cc, solvers/test/optimization_examples.cc, solvers/test/optimization_examples.h, solvers/test/snopt_solver_test.cc
Currently except for IPOPT/NLOP/SNOPT (which support generic nonlinear constraints), none of the other solvers will support quadratic constraints.
In the future PRs, I will modify each solver wrapper to support convex quadratic constraint.
Towards #6341
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19016)
=> [solvers] MathematicalProgram adds and stores QuadraticConstraint.

BUILD.bazel, multibody/parsing/BUILD.bazel, tools/install/bazel/BUILD.bazel, tools/install/bazel/drake.BUILD.bazel, tools/install/bazel/drake__multibody.BUILD.bazel
Towards https://github.com/RobotLocomotion/drake/pull/18955 and https://github.com/RobotLocomotion/drake/issues/15774 and https://github.com/RobotLocomotion/drake/issues/9498.
I tested this manually by running the install, and confirming that the script made it into the install destination.
(It's a little bit unusual to commit this change on its own without actually calling the downloader anywhere yet, but the #18955 is so huge that I'd rather try to prune off as much as I can there.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19017)
=> [parsing] Install package_downloader

bindings/pydrake/perception_py.cc, bindings/pydrake/test/perception_test.py, bindings/pydrake/visualization/test/meldis_test.py, perception/point_cloud.cc, perception/point_cloud.h, perception/test/point_cloud_test.cc
As discussed in https://github.com/RobotLocomotion/drake/pull/18774#issuecomment-1437232982, this PR modified the code and relevant documentation to allow morphing fields after the construction of a PointCloud.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18987)
=> [perception] PointCloud can morph its fields after construction

multibody/parsing/BUILD.bazel, multibody/parsing/package_map.cc, multibody/parsing/package_map.h, multibody/parsing/test/package_map_test.cc
Towards https://github.com/RobotLocomotion/drake/issues/15774 and https://github.com/RobotLocomotion/drake/issues/9498.
See for the https://github.com/RobotLocomotion/drake/pull/18955 next PR that takes advantage of the encapsulation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19020)
=> [parsing] PackageMap better encapsulates PackageData

geometry/render_gltf_client/internal_http_service.cc, geometry/render_gltf_client/internal_http_service_curl.cc, geometry/render_gltf_client/internal_render_client.cc, geometry/render_gltf_client/test/internal_http_service_curl_test.cc, geometry/render_gltf_client/test/internal_render_client_test.cc
- Prefix error messages with "RenderClient".
- Remote extra indentation that ends up being printed.
+@zachfang for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19022)
=> [render] Improve error messages

multibody/meshcat/joint_sliders.cc, multibody/meshcat/joint_sliders.h
Update the documentation vis a vis floating bodies -- they are now driven by joints. Also clarify implementation details related to this - renaming "initial" values with "nominal" values as they are no longer strictly "initial" but *do* represent the values that state will be held at when sliders can't be provided.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19043)
=> Update JointSlider documentation

multibody/tree/multibody_tree.h
This PR updates the documentation for DRAKE_MBT_THROW_IF_FINALIZED and DRAKE_MBT_THROW_IF_NOT_FINALIZED to clearly state they are constant-time.
Per [review discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS2K06B7e2iJXCUlli) it is ok to call these method from within snake_case methods. 
This PR simply documents this fact for future developers going through this code.
Refer to this [review discussion](https://reviewable.io/reviews/RobotLocomotion/drake/18959#-NQS2K06B7e2iJXCUlli) for further details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18997)
=> Update documentation for MultibodyTree macros

bindings/pydrake/geometry/geometry_py_visualizers.cc, bindings/pydrake/geometry/test/visualizers_test.py, bindings/pydrake/multibody/meshcat_py.cc, bindings/pydrake/visualization/_meldis.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer.h, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc, geometry/test/meshcat_visualizer_test.cc, multibody/meshcat/contact_visualizer.cc, multibody/meshcat/hydroelastic_contact_visualizer.cc, multibody/meshcat/hydroelastic_contact_visualizer.h, multibody/meshcat/point_contact_visualizer.cc, multibody/meshcat/point_contact_visualizer.h, multibody/meshcat/test/hydroelastic_contact_visualizer_test.cc
Towards #17832 -- with this PR we now support recording contact
visualization in meshcat animations (only not the hydroelastic
surface visualization yet).
Previously the recording logic lived in the System
(MeshcatVisualizer), because it was the system that knows about
time. But this became unwieldy... as more systems wanted to contribute
to the animation (for instance the contact visualizer, the point cloud
visualizer, my manipulation class meshcat writer, ...), I had to start
writing a significant amount of custom recording-specific logic in
each subsystem. (I do have a working experimental branch in which I
made this possible through a recording output port on the
MeshcatVisualizer... but the burden on every downstream visualizer was
too great).
In this PR I've hoisted the recording …
=> [meshcat] Hoist recording logic from MeshcatVisualizer to Meshcat

bindings/pydrake/multibody/test/plant_test.py
Amends #17639.
+@EricCousineau-TRI for both reviews per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19054)
=> [pydrake] Remove clutter from unit test

bindings/pydrake/geometry/BUILD.bazel, common/BUILD.bazel, common/network_policy.cc, common/network_policy.h, common/test/network_policy_test.cc, doc/doxygen_cxx/doxygen.h, examples/allegro_hand/joint_control/BUILD.bazel, geometry/BUILD.bazel, geometry/meshcat.cc, geometry/meshcat.h, geometry/render_gltf_client/BUILD.bazel, geometry/render_gltf_client/factory.cc, geometry/render_gltf_client/factory.h, geometry/render_gltf_client/test/factory_denied_test.cc, geometry/test/meshcat_denied_test.cc, lcm/BUILD.bazel, lcm/drake_lcm.cc, lcm/drake_lcm.h, lcm/test/drake_lcm_denied_test.cc, multibody/parsing/BUILD.bazel, multibody/parsing/package_map.cc, multibody/parsing/package_map.h, multibody/parsing/test/package_map_remote_test.cc, multibody/parsing/test/package_map_test.cc, tools/skylark/README.md, tools/skylark/drake_cc.bzl, tools/skylark/drake_py.bzl, tools/skylark/kwargs.bzl
Towards #15774 and #19046.  I think it's important to have our test-fixtures fail fast when PackageMap is going to hit the internet, before we can land #19046.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19050)
=> Add DRAKE_ALLOW_NETWORK governor

bindings/pydrake/geometry/test/visualizers_test.py, bindings/pydrake/visualization/_model_visualizer.py, geometry/BUILD.bazel, geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer_params.h, geometry/test/meshcat_visualizer_test.cc, visualization/test/visualization_config_functions_test.cc, visualization/visualization_config_functions.cc
Amends #18409.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19058)
=> [visualization] By default, Meshcat proximity geometry is hidden

BUILD.bazel, common/find_cache.cc, multibody/parsing/BUILD.bazel, multibody/parsing/package_map.cc, tools/install/bazel/drake.BUILD.bazel, tools/install/bazel/generate_installed_files_manifest.bzl, tools/install/bazel/repo_template.bzl, tools/install/bazel/test/drake_bazel_installed_test.py, tools/install/dockerhub/focal/Dockerfile, tools/install/dockerhub/jammy/Dockerfile, tools/install/install_test.py, tools/wheel/image/build-wheel.sh, tools/workspace/BUILD.bazel, tools/workspace/github.bzl, tools/workspace/models_internal/package.BUILD.bazel
Closes #15774.
---
Local testing of a CMake install:
```console
$ bazel run //:install -- /home/jwnimmer/tmp/install
$ cd ~/tmp
$ env PYTHONPATH=install/lib/python3.10/site-packages python3
>>> from pydrake.all import PackageMap
>>> PackageMap().GetPath("drake_models")
INFO:drake:PackageMap: Downloading https://github.com/RobotLocomotion/models/archive/6751ba850fd46fee789a095edba7ad9fc99cd188.tar.gz
'/home/jwnimmer/.cache/drake/package_map/dc38658f7acb4d07442e6dae4d18818d31ac6cc6d66bf16913ef1b208692627c'
```
---
Local testing of an Ubuntu Wheel install:
```console
$ cd tmp
$ python3 -m venv env && env/bin/pip install 'https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.2023.3.24.16.25.24%2Bgit0cd06a59-cp310-cp310-manylinux_2_31_x86_64.whl'
$ env/bin/python3
>>> from …
```
=> [parsing] Switch drake_models to a remote package

multibody/fem/BUILD.bazel, multibody/fem/test/petsc_symmetric_block_sparse_matrix_test.cc
The upgrade from Clang-12 to Clang-14 reveals that more atomic patching is needed for PETSc for thread safety. This has become tedious as PETSc is not designed to be thread safe to begin with.
As we have plans to remove the PETSc dependency in the near future, we remove the failing multi-thread test for now instead trying to apply more band-aid to stop the hemorrhage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19073)
=> [fem] Remove multi-thread test for PETSc

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/block_3x3_sparse_matrix.cc, multibody/contact_solvers/block_3x3_sparse_matrix.h, multibody/contact_solvers/test/block_3x3_sparse_matrix_test.cc
Block3x3SparseMatrix is a highly-specialized sparse matrix data structure that stores data as 3x3 dense blocks. It provides a minimal set of APIs to support the matrix operations required for constraint Jacobians in SAP. It is particularly useful for constraints involving deformable bodies where the non-zero entries usually assume a 3x3 block structure (i.e. each constraint has 3 constraint equations and dofs involved in the constraint also come in groups of 3 as the x,y,z coordinates of the deformable mesh vertex involved in the constraint).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19000)
=> [multibody] Add Block3x3SparseMatrix

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/general_test.py, geometry/drake_visualizer.cc, geometry/drake_visualizer.h, geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer.h, geometry/test/drake_visualizer_test.cc, geometry/test/meshcat_visualizer_test.cc, multibody/meshcat/contact_visualizer.cc, multibody/meshcat/contact_visualizer.h, multibody/meshcat/test/contact_visualizer_test.cc, systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/diagram_builder.cc, systems/framework/diagram_builder.h, systems/framework/test/diagram_builder_test.cc, systems/framework/test/diagram_test.cc, visualization/test/visualization_config_functions_test.cc
This was of interest to Russ so he could customize the systems _after_ they were added to the diagram.  Our config-application functions don't return pointers to the (many!) subsystems that they add, so the user needs to find them by name.  When they were memory-object names, that was not very easy.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19075)
=> Add names to visualization systems (when possible)

multibody/contact_solvers/sap/sap_model.cc, multibody/contact_solvers/sap/test/sap_model_test.cc
Both `SapConstraintBundle`'s constructor and `SapModel::CalcDelassusDiagonalApproximation()` document that the Delassus operator diagonal approximation is stored in the order constraints are enumerated in `SapProblem`.
`SapConstraintBundle` expects this order. However, `SapModel::CalcDelassusDiagonalApproximation()` was inconsistently ordering them by cluster. This can lead to very bad scaling of the constraints, specially so in problems with large mass ratios.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19082)
=> Fix the ordering of the Delassus operator approximation

geometry/BUILD.bazel, geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer_params.h, geometry/test/meshcat_visualizer_test.cc, visualization/test/visualization_config_functions_test.cc, visualization/visualization_config_functions.cc
Towards #15738.
---
Note that this will increase the message bandwidth used for primitive collision shapes.  Now we'll send their tessellation surface, instead of just the primitive shape parameters.
---
Tested using:
`bazel run //examples/hydroelastic/ball_plate:ball_plate_run_dynamics -- -simulator_target_realtime_rate 0.001 --resolution_hint_factor=1`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19085)
=> [visualization] Show hydro tesselation for proximity shapes

doc/_pages/buildcop.md
Caching is enabled for Mac ARM64 but not x86.
Towards #19097
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19107)
=> [doc] Update Mac link for buildcop cache server check

multibody/parsing/package_downloader.py, multibody/parsing/package_map.cc, multibody/parsing/test/package_downloader_stress_test.py, multibody/parsing/test/package_downloader_test.py, multibody/parsing/test/package_map_remote_test.cc
Closes #19047.  Towards #9498.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19081)
=> [parsing] Plumb downloader errors through to the exception text

geometry/meshcat.h
The docstring for PlotSurface was malformed, and caused all methods lower in meshcat.h to not appear in the doxygen output.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19108)
=> Fix Meshcat doxygen

bindings/pydrake/polynomial_py.cc, bindings/pydrake/test/polynomial_test.py
This came up in my response to a [StackOverflow question](https://stackoverflow.com/questions/75894087/pydrake-evaluate-piecewisepolynomial-with-symbolic-expression).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19118)
=> Adds python binding for Polynomial<T>::EvaluateUnivariate()

setup/mac/binary_distribution/requirements.txt, setup/mac/source_distribution/requirements-test-only.txt, setup/ubuntu/binary_distribution/packages-focal.txt, setup/ubuntu/binary_distribution/packages-jammy.txt, setup/ubuntu/source_distribution/packages-focal-test-only.txt, setup/ubuntu/source_distribution/packages-jammy-test-only.txt, tools/wheel/image/setup.py
Closes #19039.
Note that we cannot drop `libmsgpack-dev` from the setup scripts until the deprecation window for #18559 closes.
We keep `u-msgpack` as testonly because the `geometry/test/meshcat_websocket_client.py` still uses it.
---
Ubuntu Wheel testing:
```console
jwnimmer@call-cps:~/tmp$ python3 -m venv env
jwnimmer@call-cps:~/tmp$ env/bin/pip install https://drake-packages.csail.mit.edu/drake/experimental/drake-0.0.2023.3.28.19.34.49%2Bgita4109729-cp310-cp310-manylinux_2_31_x86_64.whl
Collecting drake==0.0.2023.3.28.19.34.49+gita4109729
...
jwnimmer@call-cps:~/tmp$ env/bin/python3 -c 'import pydrake.all'
jwnimmer@call-cps:~/tmp$ echo $?
0
```
---
macOS Wheel testing:
```console
% python3 --version
Python 3.11.2
% python3 -m venv env
% env/bin/pip install …
```
=> [setup] Drop vestigial meshcat dependencies

common/symbolic/polynomial.cc, geometry/optimization/cspace_free_polytope.cc, multibody/optimization/toppra.cc
The `drake::log()` functions already call format on the arguments, no need for `fmt::format` inside of a `log()->warn(...)`.
+@xuchenhan-tri for both reviews per schedule, please.
\CC @hongkai-dai @AlexandreAmice FYI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19115)
=> Remove extraneous calls to fmt

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
I tried running https://github.com/kevinzakka/obj2mjcf/ and then ran into this parser bug.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19124)
=> [parsing] Fix mujoco default mesh name heuristic

bindings/pydrake/visualization/_model_visualizer.py, bindings/pydrake/visualization/model_visualizer.py, bindings/pydrake/visualization/test/model_visualizer_test.py
As I was editing my model files and reloading, I got frustrated when the visualizer would crash any time I made a typo.
This is my attempt at the simplest possible change to mitigate that inconvenience:
- Use logging (not print) for terminal output.  This should work better for Jupyter, too.
- Use a hint of color in the terminal output to indicate the message severity.
- When the parser crashes, log the error and then replace the scene with a traffic cone.
- Allow "Reload" to reload the original files, after the user fixes their mistake.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19014)
=> [model_visualizer] Don't crash on a failed reload

doc/BUILD.bazel, doc/_release-notes/index.html
The longer URL looks silly when pasted into a slide deck.
Tested with `bazel run //doc:pages -- --serve` then open `http://127.0.0.1:8000/release_notes/` in a browser.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19126)
=> [doc] Support shorter URL for release notes index

geometry/meshcat.cc, geometry/render/test/meshes/box.obj.mtl
For some reason, a lot of the `*.mtl` files in the YCB dataset contain this trailing whitespace.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19129)
=> [geometry] Ignore trailing whitespace in mtl files

tools/workspace/pybind11/BUILD.bazel, tools/workspace/pybind11/pybind_coverage_xml_parser.py
This was failing on macOS unprovisioned builds that used pandas 2.0.
Because the affected files are used in both build (genrule) and test steps, do a minimal patch to avoid build-phase failures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19140)
=> [pybind11] Hotfix: nerf pybind coverage

multibody/meshcat/BUILD.bazel, multibody/meshcat/hydroelastic_contact_visualizer.cc, multibody/meshcat/test/hydroelastic_contact_visualizer_test.cc
Before this fix, MeshCat used the arrows from the last sizable force or moment in the previous time step.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19112)
=> [visualization] Hide near-zero hydroelastic force or moment.

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/matrix_block.cc, multibody/contact_solvers/matrix_block.h, multibody/contact_solvers/test/matrix_block_test.cc
MatrixBlock wraps around std::variant<MatrixX<T>, Block3x3SparseMatrix<T>> and provides a common set of API for a set of matrix operations that leverages sparsity when possible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19083)
=> [multibody] Add MatrixBlock class

bindings/pydrake/common/containers.py, bindings/pydrake/common/test/containers_test.py
Previously, setting a bad attribute just said "Cannot add attributes!"
Now it says, e.g.  "Cannot add attributes! The fields in this named view are ('a', 'b'), but you tried to set 'c'."
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19148)
=> Improve error message for namedview

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/direct_collocation.cc, planning/trajectory_optimization/direct_collocation.h, planning/trajectory_optimization/multiple_shooting.cc, planning/trajectory_optimization/multiple_shooting.h, planning/trajectory_optimization/test/direct_collocation_test.cc, planning/trajectory_optimization/test/multiple_shooting_test.cc
This enables adding multiple direct collocation programs into the same MathematicalProgram, which is important for enabling e.g. hybrid trajectory optimization. This has been a TODO, and was a major reason that we switched MultipleShooting to has-a prog (from is-a prog).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19156)
=> Support passing a MathematicalProgram to the DirectCollocation constructor

bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/_model_visualizer.py, bindings/pydrake/visualization/_triad.py, bindings/pydrake/visualization/_visualization_extra.py, bindings/pydrake/visualization/test/model_visualizer_test.py, bindings/pydrake/visualization/test/triad_test.py
Closes #17170.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19152)
=> [visualization] Add frame (aka triad) visualization function

tools/workspace/mypy_internal/patches/timeout.patch
Relates #18119. Linux CI jobs have been timing out again, increasing from "180 seconds" to "360 seconds" to try and give it enough time to poll the results.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19169)
=> Increase mypy timeout for CI machines to 360 secs

multibody/parsing/BUILD.bazel, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/detail_mujoco_parser.h, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/parsing/test/parser_test.cc
This patch updates most of the mujoco parser diagnostics to include file and line number, and to obey policy configuration from the top-level Parser.
In addition, it fixes a bug found trying to use std::optional<bool> for a tri-state variable -- one dropped '*' in the wrong place led to an unreachable branch, and probably other problems.
Finally, it moves the affected files closer to clang-format compliance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19157)
=> [parsing] Port mujoco parser to diagnostic policy

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
We got yet another question on stackoverflow last night about the case when joint.num_velocities() != 1.  Time for a better message!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19181)
=> Improve error message for AddJointActuator

bindings/pydrake/common/containers.py, bindings/pydrake/common/test/containers_test.py
Related to #19164 -- MbP uses names which are not immediately useable as `namedview` fields.
After this PR (and now that #19174 has landed), we can do e.g.
```
PositionView = namedview("PositionView", plant.GetPositionNames())
StateView = namedview("StateView", plant.GetStateNames())
```
+@EricCousineau-TRI for feature review, please?  WDYT?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19196)
=> Provide automatic sanitization of field names in `namedview`

common/BUILD.bazel, common/bit_cast.h, common/ssize.h, common/test/ssize_test.cc, multibody/constraint/test/constraint_solver_test.cc, multibody/contact_solvers/sap/contact_problem_graph.h, multibody/plant/multibody_plant.cc, multibody/tree/multibody_tree_topology.h, systems/framework/context_base.h, systems/framework/system_base.h
Tired of writing `static_cast<int>(thing.size())` over and over to avoid warnings? C++20 adds the very handy std::ssize() ("signed size") template function allowing `ssize(thing)` instead for any `thing` that has a size() method.
Unfortunately we still have to support C++17 for a while longer. This PR provides a polyfill implementation of `drake::ssize()` that allows writing `ssize(thing)` whenever you are in the drake:: namespace. (You have to include `drake/common/ssize.h`.) This uses the library implementation when available otherwise fakes it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19199)
=> Add polyfill for std::ssize

geometry/proximity/distance_to_shape_callback.cc, geometry/proximity/distance_to_shape_callback.h, geometry/proximity/test/distance_sphere_to_shape_test.cc, geometry/proximity_engine.cc, geometry/query_object.h, geometry/test/proximity_engine_test.cc
Historically, requesting signed distance between two geometries that had been filtered would throw. While it might make sense to have the geometries filtered for contact, it might still be convenient to know how far they are. This changes the API to allow the caller to demand that collision filters be ignored.
closes #19135
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19176)
=> QueryObject allows signed distance between a filtered geometry pair

bindings/pydrake/geometry/geometry_py_scene_graph.cc, bindings/pydrake/geometry/test/scene_graph_test.py, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/internal_geometry.cc, geometry/internal_geometry.h, geometry/query_object.h, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/scene_graph_inspector.cc, geometry/scene_graph_inspector.h, geometry/test/geometry_state_test.cc, geometry/test/internal_geometry_test.cc, geometry/test/scene_graph_inspector_test.cc, geometry/test/scene_graph_test.cc
This does all the work of removing the public and internal APIs in support of registering a geometry relative to another geometry. In addition to removing the deprecated public APIs, it also removes some of the supporting artifacts that are no longer necessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19177)
=> Remove deprecated "register geometry to geometry" from SceneGraph

geometry/test/scene_graph_inspector_test.cc
The functionality for cloning geometry instances was not properly covered in the unit tests. This function is exceptional because SGInspector actually defines logic to do the work rather than simply forwarding to GeometryState.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19209)
=> Improve SceneGraphInspector test coverage

bindings/pydrake/visualization/visualization_py_config.cc, visualization/test/visualization_config_functions_test.cc, visualization/visualization_config_functions.cc, visualization/visualization_config_functions.h
Towards #19210.
This commit takes the hacky version of a prototype patch I'd previously donated to that PR and turns it into a more carefully-spelled change.
Given the forthcoming release date, this probably won't make it in, so I've elected to push the deprecation removal a little further into the future since it's low-cost to extend it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19217)
=> [visualization] Use a mutable scene_graph for setup

multibody/plant/tamsi_solver.h
I recently read the document about TAMSI-Solver and find a formula error in tamsi_solver.h. The brackets might be in error order. I fix that and create a pull request. I will be grateful if somebody can check it out.
https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_tamsi_solver.html equation (15)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19166)
=> fix tamsi_solver.h document brackets error

common/find_resource.cc, common/test/resource_tool_installed_test.py
When a user installs Drake via pip or apt, but still uses Bazel as their build & test system, then previously we'd get confused and try to use Bazel runfiles to find Drake resources. Instead, we should fall back to the other mechanism (library-relative paths) in this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19206)
=> [common] Fix FindResource vs non-source Bazel builds

common/find_resource.cc
Adjust an error message inaccuracy from the prior commit (#19206).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19228)
=> [common] Tweak FindResource error message

multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/spatial_inertia_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19192)
=> Throw exceptions for spatial inertia primitives with negative mass or density.

geometry/BUILD.bazel, geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer_params.h, geometry/test/meshcat_visualizer_test.cc
Towards https://github.com/RobotLocomotion/drake/pull/19210.
This commit takes the hacky version of a prototype patch I'd previously donated to that PR and turns it into a more carefully-spelled change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19220)
=> [geometry] MeshcatVisualizer can filter geometry via property

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/contact_solvers/sap/sap_friction_cone_constraint.cc, multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc, multibody/plant/compliant_contact_manager.cc, multibody/plant/deformable_driver.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_config.h, multibody/plant/multibody_plant_config_functions.cc, multibody/plant/sap_driver.cc, multibody/plant/sap_driver.h, multibody/plant/test/deformable_driver_contact_test.cc, multibody/plant/test/multibody_plant_config_functions_test.cc, multibody/plant/test/sap_driver_test.cc
This PR exposes the parameter that controls the "near rigid" approximation used by SAP.
This parameter is used to avoid ill-conditioning for very stiff contact models. It turns out that our default value is too conservative and often leads to softened contact constraints. This is specially true in models with large mass ratios, typically gripper fingers on a much massive robot. 
While we should probably set this parameter to zero by default (meaning no near rigid conditioning), this PR simply exposes this parameters so that they can set it to zero themselves in cases for which softening is observed.
Marking high priority since several users run into this kind of problems.
- - - …
=> Exposes SAP near rigid threshold

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, multibody/inverse_kinematics/differential_inverse_kinematics_integrator.h, systems/primitives/discrete_derivative.h, systems/primitives/test/discrete_derivative_test.cc
Also adds missing documentation and fixes up the doxygen for the related DifferentialInverseKinematicIntegrator.
I think this is a worthwhile change. Almost everyone wants the suppression; anyone who calls `set_input_history` manually has this default effectively overwritten.  The cost of not using the suppression is high (huge initial transients), and the cost of having extra suppression is low.
Inspired by https://stackoverflow.com/q/75981586/9510020.
Does this need to be labeled a breaking change?  I could find our policy on this in the developer docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19247)
=> DiscreteDerivative sets suppress_initial_transient=true by default

planning/trajectory_optimization/direct_transcription.h
Adds a note to remember why we have the atypical (and not very user friendly) TimeStep struct in direct_transcription.h.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19249)
=> Document direct_transcription::TimeStep

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/general_test.py, systems/framework/diagram.h, systems/framework/diagram_builder.cc, systems/framework/diagram_builder.h, systems/framework/test/diagram_builder_test.cc
Towards #19158.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19243)
=> [systems] Add DiagramBuilder::RemoveSystem

bindings/pydrake/geometry/geometry_py_common.cc, bindings/pydrake/geometry/test/common_test.py, geometry/geometry_instance.cc, geometry/geometry_instance.h, geometry/scene_graph_inspector.cc, geometry/test/geometry_instance_test.cc, geometry/test/scene_graph_inspector_test.cc, multibody/plant/test/contact_properties_test.cc
Towards #19250.
Broadly, a C++ function that takes a `unique_ptr<T>` as input without also offering a `const T&` overload is defective in that it forces users (even C++ users) to worry about lifetimes and leaves our implementations vulnerable to unwanted aliasing, when in most cases they don't care about actually care about ownership transfer. See, e.g., #14453 for prior art.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19251)
=> [geometry] Add GeometryInstance overload without unique_ptr

math/BUILD.bazel, math/continuous_algebraic_riccati_equation.cc, math/continuous_algebraic_riccati_equation.h, math/test/continuous_algebraic_riccati_equation_test.cc, systems/controllers/linear_quadratic_regulator.h
Riccati equation might not have a finite solution if the system is not stabilizable, or Q and R matrices are not positive definite.
Resolves #19191 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19222)
=> Throw an error when Riccati equation is not solved for continuous time system.

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
In practice, it is sufficient to solve the relaxed `GraphOfConvexSets` problem with lower tolerances and with higher tolerances for the simpler rounded problems where the flows are set. This dramatically reduces the overall solve time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18875)
=> added optional rounding solver options

multibody/tree/spatial_inertia.h
I was working on SDFormat files and browsed documentation of [SpatialInertia](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_spatial_inertia.html) and saw useful functions to help me set `<inertial>` blocks for HollowSphere, SolidBox, SolidCapsule, etc.  However, I didn't find the function for meshes.
I propose to make a doxygen link from SpatialInertia to CalcSpatialInertia(mesh).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19226)
=> [doc] Link from SpatialInertia to CalcSpatialInertia of meshes

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/iris.cc, geometry/optimization/iris.h, geometry/optimization/test/iris_in_configuration_space_test.cc, geometry/optimization/test/iris_test.cc
Enables specifying a starting ellipse to use for either `Iris` or `IrisInConfigurationSpace`. Useful for region refinement or taking additional growth steps if iteration limit terminated too soon.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19257)
=> [geometry/optimization] Support IRIS initial ellipse

tools/workspace/styleguide/repository.bzl
Per https://github.com/RobotLocomotion/styleguide/pull/52.
See also #19270.
I've confirmed that Anzu has no new lint with this upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19277)
=> [workspace] Upgrade styleguide to latest commit

multibody/hydroelastics/hydroelastic_user_guide_doxygen.h
Thanks to Andreas Hofmann who noticed that the content in Appendix B of Hydroelastic User Guide needed an update.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19267)
=> [doc] Update Appendix B State of Implementation of Hydroelastic User Guide

bindings/pydrake/geometry/geometry_py_optimization.cc
Shuffle the order of some bindings to meet best practices.  None of the bindings code was changed; only re-ordered.
A class that's used as a function argument or return type must be bound prior to use. Previously these (e.g., GOCS::Vertex) were used in the GOCS bindings prior to being bound.
Before:
After:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19283)
=> [pydrake] Fix docs & mypy stubs for GraphOfConvexSets

geometry/proximity/distance_to_shape_callback.cc, geometry/proximity/distance_to_shape_callback.h, geometry/proximity/penetration_as_point_pair_callback.cc, geometry/proximity/test/distance_sphere_to_shape_test.cc, geometry/query_object.h, geometry/test/proximity_engine_test.cc
Now it points users to the supported geometry tables. Also fixes up a few errant footnotes in those geometry tables.
+@damrongguoy for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19275)
=> Improve error message for unsupported geometries in proximity engine.

geometry/optimization/test/iris_in_configuration_space_test.cc
Closes #19282. @liangfok for all reviews.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19285)
=> [geometry/optimization] Hotfix to IrisInConfigurationSpaceTest.StartingEllipse tolerance

tutorials/authoring_multibody_simulation.ipynb, tutorials/rendering_multibody_plant.ipynb
Switch rendering_multibody_plant to use AddDefaultVisualization.
Also correct a comment about collision geometry color.
Closes #17690.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19280)
=> [tutorials] Use AddDefaultVisualization in a tutorial

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/BUILD.bazel, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
This adds a basic version of the motion planner introduced in the paper "Motion Planning around Obstacles with Convex
Optimization." by Tobia Marcucci,
Mark Petersen, David von Wrangel, Russ Tedrake. https://arxiv.org/abs/2205.04422
Instead of using the full time scaling curve, this `GCSTrajectoryOptimization` uses a single time
scaling variable for each region.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19239)
=> Adds basic GCS planner

bindings/pydrake/__init__.py
The fields of an ImportError might be None; don't crash with an even more obscure error in that case.
Noticed during https://github.com/RobotLocomotion/drake/pull/19103.
My cost / benefit on adding a regression test for this was in favor for punting.  We regression test the non-None case already; injecting the None seemed difficult.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19296)
=> [pydrake] Handle nulls in ImportError reporting

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
Adds the `SetWallBoundaryCondition` pybinding for `DeformableModel`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19299)
=> [bindings] Add SetWallBoundaryCondition Deformable Model Binding

geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer_params.h, geometry/test/meshcat_visualizer_test.cc
If geometry is invisible, the meshcat alpha sliders will never make it visible because MeshcatVisualizer simply multiplies geometry alpha by the slider value. To improve this somewhat, check if all geometry in a visualizer is invisible and if so use the absolute alpha slider value as the new alpha instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19287)
=> [meshcat] Enable alpha adjustment of invisible geometry

geometry/render_gltf_client/test/integration_test.py
Relates to #19305.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19306)
=> Skip render_gltf_client integration tests that fail on macOS

multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_urdf_parser_test.cc
This patch brings inertia invalidity reporting under diagnostic policy, and relaxes inertia problems from hard throws to warnings.
The move to diagnostic policy means that inertia warnings give file names and line numbers, which make it easier to fix problems.
The move from hard throws to warnings means that models with non-physical inertias can still be used with non-simulation workflows, such as visualization, kinematics, and analysis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19238)
=> [parsing] Improve URDF inertia invalidity handling

common/benchmarking/BUILD.bazel, common/benchmarking/benchmark_polynomial.cc
Towards #19202 and #10900.
---
Sample output:
```console
$ bazel-bin/common/benchmarking/benchmark_polynomial --benchmark_filter=Gemm
-----------------------------------------------------
Benchmark           Time             CPU   Iterations
-----------------------------------------------------
GemmDV/10       0.663 ms        0.663 ms          935
GemmDV/50         199 ms          199 ms            4
GemmDV/100       2809 ms         2809 ms            1
GemmDV/200      41299 ms        41295 ms            1
GemmDE/10       0.263 ms        0.263 ms         2675
GemmDE/50        70.7 ms         70.7 ms           10
GemmDE/100        971 ms          971 ms            1
GemmDE/200      13949 ms        13947 ms            1
GemmEE/10       0.442 ms        0.442 ms         1585
GemmEE/50 …
```
=> [common] Add benchmark for Gemm on Expression

bindings/pydrake/BUILD.bazel, bindings/pydrake/math_py.cc, bindings/pydrake/test/math_overloads_matrix_test.py, common/eigen_types.h
This is important for performance until numpy allows us to define dtype-specific implementations. Doing a matmul elementwise with a C++ <=> Python call for every flop is extraordinarily slow.
Towards #19202.  This provides the plumbing (which should already be a nice >20% speed win).  Follow-up work will optimize the actual computation (see #19304).
---
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19298)
=> [pydrake] Add math.matmul

tools/workspace/optitrack_driver/repository.bzl
This has no direct effect on any drake usage of optitrack_driver, but does add new command line arguments to the installed optitrack_client which are useful when connecting to newer versions of the optitrack software in unicast mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19324)
=> Update optitrack driver version

examples/manipulation_station/test/manipulation_station_test.cc, multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/tamsi_driver.cc, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/compliant_contact_manager_tester.h, multibody/plant/test/discrete_update_manager_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/plant/test/sap_driver_joint_limits_test.cc
Closes #18682.
Systematically adopt the strategy of mimicking discrete input force ports for a discrete MultibodyPlant.
1. Ensure that all the discrete sampling happen at a single place.
2. Ensure the cache entry is manually updated at the beginning of a time step.
3. Move all CalcNonContactForce() logic for all MbP discrete updates (that depends on the discretely sampled force input ports) to a single place in DiscreteUpdateManager.
4. Consequently, the ThrowIfNonContactForceInProgress guard against algebraic loops can be centralized in DiscreteUpdateManager.
5. Throw an exception if caching is disabled for discrete updates as the discrete sampling depends on caching.
- - - …
=> [multibody] Refresh cache entry hack upon update

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
This adds a minimum time objective. Rather than finding the shortest path, this allows users to find the fastest path. It becomes particularly useful once velocity bounds will be introduced.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19301)
=> [planning] Adds a time cost to GcsTrajectoryOptimization

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/spectrahedron.cc, geometry/optimization/spectrahedron.h, geometry/optimization/test/spectrahedron_test.cc
This adds the minimal functionality to be useful. I will follow-up with more PRs to fill in the "not implemented yet" blocks as needed.
+@TobiaMarcucci for feature review, please.
fyi @jwnimmer-tri.  I expect this will land on your platform day tomorrow.  You have a lot of cleanups in the ConvexSet hierarchy; I tried to be consistent with most of them (but still have the copyable_unique_ptr in my bindings so far).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19316)
=> Adds Spectrahedron isa ConvexSet

geometry/optimization/BUILD.bazel, geometry/optimization/cspace_free_polytope.h, geometry/optimization/test/convex_set_solving_test.cc, geometry/optimization/vpolytope.cc
This asks local tests (and CI tests) to enforce that `clang-format` has been run on all files in this directory.  This should help all contributors overcome most formatting hurdles prior to code review.
Towards #4843.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19331)
=> [geometry/optimization] Opt-in to clang-format lint

geometry/optimization/cartesian_product.cc, geometry/optimization/cartesian_product.h, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/intersection.cc, geometry/optimization/intersection.h, geometry/optimization/minkowski_sum.cc, geometry/optimization/minkowski_sum.h, geometry/optimization/point.cc, geometry/optimization/point.h, geometry/optimization/spectrahedron.cc, geometry/optimization/spectrahedron.h, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
Towards #19311.  Amends #15266.
This class is `@experimental`, so no deprecation is required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19336)
=> Move ConvexSet cloning to vtable instead of std::function

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
This adds velocity bounds to the subgraphs, which enables useful minimum time planning.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19334)
=> [planning] Add velocity bounds to subgraphs

common/symbolic/expression/expression.cc, common/symbolic/expression/expression.h, common/symbolic/expression/test/expression_matrix_test.cc
Towards https://github.com/RobotLocomotion/drake/issues/19202 and https://github.com/RobotLocomotion/drake/issues/10900.
The crux of the improvement here is `GenericGevv` computing the inner product directly using `AddFactory`, without creating intermediate Expression nodes.
The calculation of `MatrixX<double> * MatrixX<Variable>` can still be _much_ better optimized.  That will come in a future commit (#19345).
---
For multiplying two matrices each with shape=(50, 50), this yields ~4x throughput compared to master (data shown below).  For shape=(200, 200), the throughput yield is more like ~11x.
On master:
```
------------------------------------------------------------
Benchmark                  Time             CPU   Iterations …
```
=> [symbolic] Speed up matmul

bindings/pydrake/geometry/BUILD.bazel, bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/optimization_pybind.h, bindings/pydrake/geometry/test/optimization_test.py, bindings/pydrake/planning/BUILD.bazel, bindings/pydrake/planning/planning_py_trajectory_optimization.cc
In Python bindings, lifetime annotations should not be part of the Python runtime type, rather it should be handled while crossing the C++ / Python layer.
---
Before:
After:
---
The constructor docs for `CartesianProduct`, `Intersection`, `MinkowskiSum` etc all look better also.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19343)
=> [pydrake] Remove CopyableUniquePtrConvexSet binding

common/symbolic/generic_polynomial.cc, common/symbolic/polynomial.cc, geometry/proximity/test/contact_surface_test.cc, geometry/proximity/test/contact_surface_utility_test.cc, geometry/proximity/test/mesh_field_linear_test.cc, geometry/proximity/test/mesh_half_space_intersection_test.cc, geometry/proximity/test/mesh_intersection_test.cc, geometry/proximity/test/mesh_plane_intersection_test.cc, geometry/proximity/test/polygon_surface_mesh_test.cc, geometry/proximity/test/triangle_surface_mesh_test.cc, geometry/query_results/contact_surface.h, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/test/scene_graph_test.cc, multibody/plant/test/contact_properties_test.cc, multibody/plant/test/contact_results_to_lcm_test.cc, multibody/plant/test/deformable_boundary_condition_test.cc, multibody/plant/test/deformable_driver_contact_kinematics_test.cc, multibody/plant/test/deformable_integration_test.cc, multibody/plant/test/deformable_model_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/tree/test/body_node_test.cc, systems/rendering/multibody_position_to_geometry_pose.cc, systems/rendering/test/multibody_position_to_geometry_pose_test.cc, systems/sensors/test/rgbd_sensor_test.cc
Amends #19354.  In that PR, I only searched for the `using std::move;` statements.  Turns out, for things like move on a `std::unique_ptr`, we were getting away with ADL sometimes, too -- even in headers!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19356)
=> Avoid ADL std::move

geometry/render/BUILD.bazel, geometry/render/render_material.cc, geometry/render/render_material.h, geometry/render/test/render_material_test.cc
Introduce the RenderMaterial type and utility functions:
- Convert from GeometryProperties to RenderMaterial
- Define fallback logic for when a mesh doesn't specify its own materials.
- Provide a utility for mesh parsing to report when the mesh specifies its own materials as well as material properties.
Relates #18844
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19352)
=> Add RenderMaterial to geometry/render

geometry/render/render_material.cc
Amends #19352.
This is required for macOS.  By default on that platform, `std::filesystem::path` is not formattable unless we include a special header file.
Example failuire: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/mac-arm-monterey-clang-bazel-continuous-release/672/consoleFull
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19359)
=> Fix fmt for fs::path

geometry/render/BUILD.bazel, geometry/render/render_mesh.cc, geometry/render/render_mesh.h, geometry/render/test/render_mesh_test.cc, geometry/render_gl/BUILD.bazel, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/internal_render_engine_gl.h, geometry/render_gl/internal_shape_meshes.cc, geometry/render_gl/internal_shape_meshes.h, geometry/render_gl/test/internal_shape_meshes_test.cc
We're pulling `MeshData` out of the `render_gl` infrastructure. It will serve as the interface for extracting mesh data (OBJ for now) for multiple render engine implementations. To do this:
1. Extract the struct and functions from `render_gl/internal_shape_meshes.*` into its own `render/render_mesh.*` shared locale.
2. Names have been changed. `MeshData` --> `RenderMesh` (it will eventually also carry material information). The `LoadMeshFromObj` name has been elaborated to differentiate other OBJ parsing targets.
3. The `RenderMesh` is no longer OpenGl specific; so we've removed the strong numerical types for `GLfloat` and the like.
- This requires the consumers of the erstwhile `MeshData` to change how it handles the types.
Relates #18844
- - - …
=> Generalize render_gl/MeshData into render/RenderMesh

common/symbolic/expression/test/substitution_test.cc
The newest macOS Xcode complains about this (see https://drake-jenkins.csail.mit.edu/view/Mac%20Ventura/job/mac-arm-ventura-clang-bazel-continuous-non-production-release/10/).
Towards #18327.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19360)
=> Remove dead code

common/symbolic/expression/BUILD.bazel, common/symbolic/expression/expression.cc, common/symbolic/expression/test/mixing_scalar_types_test.cc
Avoid using flat_hash_set until TSan understands how to link it.
Hotfix for #19345 vs https://drake-jenkins.csail.mit.edu/view/Production/job/linux-focal-clang-bazel-nightly-thread-sanitizer/451/.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19361)
=> [symbolic] Work around TSan bug

common/symbolic/expression/BUILD.bazel, common/symbolic/expression/expression.cc, common/symbolic/expression/test/mixing_scalar_types_test.cc, tools/workspace/abseil_cpp_internal/patches/hidden_visibility.patch
This also reverts #19361, amending #19345.
When the linker resolves abseil's call to `__tsan_read1`, we want it to search the public symbols of our library dependencies (i.e., `libtsan`, which provides this symbol), not the hidden symbols within `libdrake` (which does not provide this symbol).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19363)
=> [abseil] Fix TSan linking errors

geometry/render/BUILD.bazel, geometry/render/render_material.cc, geometry/render/render_material.h, geometry/render/render_mesh.cc, geometry/render/render_mesh.h, geometry/render/test/render_mesh_test.cc, geometry/render_gl/internal_render_engine_gl.cc, tools/workspace/tinyobjloader/default_texture_color.patch, tools/workspace/tinyobjloader/repository.bzl
- `RenderMesh` can now come back with material data in addition to the geometric data.
- `LoadRenderMeshFromObj()` signature has changed to provide sufficient data for material definition.
- `RenderEngineGl` call has changed to patch around the change. `RenderEngineGl` still doesn't take advantage of this information. That will require further modifications.
- Implementation in `LoadRenderMeshFromObj()` has been updated to use the object-oriented version of `tinyobj`.
- Some error messages have been made more agnostic -- no longer tied to a specific render engine implementation.
- Parsing is now wholly reliant on `tinyobj`; the unused/incompatible streaming version of the parser has simply been removed.
- Patch `tinyobj` to conform to Drake behavior: if `map_Kd` is supplied but `Kd` is …
=> Add RenderMaterial to RenderMesh

geometry/optimization/BUILD.bazel, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
Previously, the solver passed in was not respected by the preprocessor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19312)
=> Make GCS Preprocessing respect solver options

multibody/plant/compliant_contact_manager.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/tamsi_driver.cc, multibody/plant/test/joint_locking_test.cc
This change serves as a prerequisite to joint locking in SAP #18983.
Because SAP uses sparse constraint Jacobians the possibility exists for a contact constraint Jacobian to become degenerate (0-dimensional) when all DOFs of participating trees within the tree topology are locked from joint locking. This occurs becuase joint locking uses the strategy of projecting the contact problem to a reduced DOF problem to lock DOFs.
To alleviate the problem, this PR filters out `DiscreteContactPairs` corresponding to geometries that are part of completely locked trees. This has the effect of removing the corresponding `ContactResults` for these pairs. Geometry computed contact data for these types of pairs (`PenetrationAsPointPair` and `ContactSurface`) are not affected and still exist.
- - -
This …
=> Filter contact results for completely locked trees

bindings/pydrake/systems/_lcm_extra.py, bindings/pydrake/systems/lcm_py.cc, bindings/pydrake/systems/lcm_pybind.h, bindings/pydrake/systems/test/lcm_test.py, systems/lcm/BUILD.bazel, systems/lcm/lcm_publisher_system.cc, systems/lcm/lcm_publisher_system.h, systems/lcm/lcm_subscriber_system.cc, systems/lcm/lcm_subscriber_system.h, systems/lcm/serializer.h, systems/lcm/test/serializer_deprecated_test.cc, systems/lcm/test/serializer_test.cc
Towards #19250.  Undoes #15394.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19369)
=> [systems/lcm] Use shared_ptr for LCM serializers

math/autodiff_gradient.cc, math/test/autodiff_test.cc
Previously, it was possible that ExtractGradient (and therefore AreAutoDiffVecXdEqual) would throw, when this method should simply return false. Now we handle the case where the elements of the vector could have a different number of derivative values.
This version should also be slightly faster.
N.B. This came up for me because I had two different constraints setting values in a shared Context, but one was calling SetPositions(), and the other was calling SetPositionsAndVelocities().
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19393)
=> Improve math::AreAutoDiffVecXdEqual

multibody/parsing/BUILD.bazel, multibody/parsing/detail_common.cc, multibody/parsing/detail_common.h, multibody/parsing/detail_sdf_diagnostic.cc, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_common_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/tree/rotational_inertia.h, multibody/tree/spatial_inertia.h, multibody/tree/unit_inertia.h
This patch brings inertia invalidity reporting under diagnostic policy, and relaxes inertia problems from hard throws to warnings.
The move to diagnostic policy means that inertia warnings give file names and line numbers, which make it easier to fix problems. In the case of SDFormat, this patch demotes the useless error message from the underlying sdformat library to a warning, and emits more detailed warnings in the later translation-to-Drake phase.
The move from hard throws to warnings means that models with non-physical inertias can still be used with non-simulation workflows, such as visualization, kinematics, and analysis.
- - - …
=> [parsing] Improve SDFormat inertia handling

geometry/proximity/test/mesh_plane_intersection_test.cc
On Mac Ventura Arm, this comparison was [slightly beyond tolerance](https://drake-cdash.csail.mit.edu/test/1051759841).  Towards #18327.
+@SeanCurtis-TRI for both reviews (as original author), please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19399)
=> [geometry] Bump tolerance for mesh_plane_intersection_test

geometry/geometry_state.cc, geometry/geometry_state.h, geometry/render_gl/internal_render_engine_gl.cc, geometry/test/geometry_state_test.cc
GeometryState didn't test its Render*Image responsibilities. As it turns out, they were defective. Specifically, the camera pose should be a concatenation of *three* transforms.
Given frames for the camera's parent (P), body (B), and sensor (S). The pose of the camera in the world should be X_WP * X_PB * X_BS. It was omitting the last transform. Generally, the sensor offset from the body has been identity so we've been "getting away with it".
- Incidentally enables back face culling in RenderEngineGl.
- If the camera was inside a mesh (because, for example, the pose was not what one was expected), the view would be full of black because one would see the un-illuminated back of the mesh.
- Enabling this is good; it'll help eliminate z-fighting for "skinny" geometry and no one should have …
=> RenderEngine no longer ignores sensor pose in camera body

multibody/parsing/detail_dmd_parser.cc, multibody/parsing/test/process_model_directives_test.cc, multibody/parsing/test/process_model_directives_test/deep_child_frame_weld.dmd.yaml, multibody/parsing/test/process_model_directives_test/deep_child_weld.dmd.yaml, multibody/parsing/test/process_model_directives_test/model_with_directly_nested_models.sdf
As suggested by VC regarding the changes in https://github.com/RobotLocomotion/drake/pull/17223.
This PR adds a test that serves as an example that Model Directives currently fails to load welds with a deep nested child and welds to a frame with a deep nested base frame.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19090)
=> Model directives fail to load deep nested weld tests

solvers/test/nonlinear_program_test.cc
This is almost certainly incorrect, probably there is something wrong with the solver on macOS arm64 Ventura.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19376)
=> [solvers] Start nonlinear_program_test closer to solution

bindings/pydrake/solvers/test/branch_and_bound_test.py
On Mac Ventura Arm, this was [spuriously failing](https://drake-cdash.csail.mit.edu/test/1051758745).  Towards #18327.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19403)
=> [py solvers] Fix branch and bound test vs solution ordering

multibody/plant/test/compliant_contact_manager_test.cc
On Mac Ventura Arm, this comparison was [slightly beyond tolerance](https://drake-cdash.csail.mit.edu/test/1051757934).  Towards #18327.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19401)
=> [multibody] Bump tolerance for compliant_contact_manager_test

multibody/benchmarks/free_body/test/multibody_plant_free_body_test.cc
On Mac Ventura Arm, this comparison was [slightly beyond tolerance](https://drake-cdash.csail.mit.edu/test/1051762247).  Towards #18327.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19400)
=> [multibody] Bump tolerance for free_body_test

bindings/pydrake/planning/planning_py_collision_checker.cc, bindings/pydrake/planning/test/collision_checker_test.py, planning/collision_checker.cc, planning/collision_checker.h, planning/scene_graph_collision_checker.cc, planning/scene_graph_collision_checker.h, planning/test/collision_checker_test.cc, planning/test/scene_graph_collision_checker_test.cc, planning/unimplemented_collision_checker.cc, planning/unimplemented_collision_checker.h
Resolves #19386 by providing a new affordance for `CollisionChecker` implementations to perform additional collision filter updates when changes are made to the filtered collisions. This primarily exists so that `SceneGraphCollisionChecker` can convert allowed/excluded collisions into `SceneGraph`-native filter declarations.
+@SeanCurtis-TRI for feature review, as you're most familiar with `SceneGraph` filtering.
cc @jwnimmer-tri @sadraddini
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19387)
=> [planning] Improve performance of SceneGraphCollisionChecker through better collision filtering

multibody/tree/BUILD.bazel, multibody/tree/space_xyz_floating_mobilizer.cc, multibody/tree/space_xyz_mobilizer.cc, multibody/tree/test/space_xyz_floating_mobilizer_test.cc, multibody/tree/test/space_xyz_mobilizer_test.cc
Previously, users saw `DRAKE_DEMAND(abs(cp) > 1.0e-3)` and had no idea where it was coming from. Now they should get a more helpful error message.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19406)
=> Improve error message for xyz mobilizers in singularity.

multibody/plant/tamsi_solver.cc, multibody/plant/tamsi_solver.h, multibody/plant/test/tamsi_solver_test.cc
Closes #14590.
Closes #19416.
I suspect someone is feeding a NaN into this arithmetic and it just happens to get all the way to the `sqrt` before we notice.  It's likely that diagnosing the NaN earlier would be better, but anyway this at least somewhat improves the message in this case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19407)
=> [multibody] Improve error message for !(Delta > 0)

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, solvers/BUILD.bazel, solvers/cost.cc, solvers/cost.h, solvers/create_cost.cc, solvers/mathematical_program.h, solvers/test/cost_test.cc, solvers/test/mathematical_program_test.cc
Most importantly, now AddCost(Expression) will succeed, even if it is passed in an Expression that is non-Polynomial.
Resolves #17897.
+@jwnimmer-tri for feature review, please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19405)
=> Implements ExpressionCost

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_constraint.cc, multibody/contact_solvers/sap/sap_constraint.h, multibody/contact_solvers/sap/sap_constraint_bundle.cc, multibody/contact_solvers/sap/sap_constraint_bundle.h, multibody/contact_solvers/sap/sap_friction_cone_constraint.h, multibody/contact_solvers/sap/sap_holonomic_constraint.cc, multibody/contact_solvers/sap/sap_holonomic_constraint.h, multibody/contact_solvers/sap/sap_limit_constraint.cc, multibody/contact_solvers/sap/sap_limit_constraint.h, multibody/contact_solvers/sap/sap_model.cc, multibody/contact_solvers/sap/sap_model.h, multibody/contact_solvers/sap/sap_solver.cc, multibody/contact_solvers/sap/test/sap_constraint_bundle_test.cc, multibody/contact_solvers/sap/test/sap_constraint_test.cc, multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, multibody/contact_solvers/sap/test/sap_model_test.cc, multibody/contact_solvers/sap/test/sap_solver_test.cc
Towards landing the full PR #19392.
This PR introduces the new set of `SapConstraint` APIs but implements them in terms of the old APIs so that we can make the migration towards #19392 progressively. Therefore specific constraints are not touched in this PR.
The PR also teaches `SapConstraintBundle`, `SapModel` and `SapSolver` how to use the new APIs. With these new APIs the cost assigned to each constraint no longer needs to have the form of a quadratic regularizer. This will allow us to introduce more complex models of contact.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19402)
=> Introduce new SapConstraint APIs implemented in terms of older APIs.

multibody/plant/test/multibody_plant_forward_dynamics_test.cc, multibody/tree/body.h, multibody/tree/body_node.h, multibody/tree/joint.h, multibody/tree/mobilizer.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree_system.cc
Towards #18983.
Considers joint locking parameters for mobilizers in plant forward dynamics computations. This has a twofold effect:
1. Enables joint locking in continous mode.
2. Enables the acurate calculation of free-motion velocities (v*) in SAP such that we can make the assumption that `Δv = v−v* = 0` for locked dofs in the SapProblem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19420)
=> [multibody] Including joint locking in forward dynamics computations

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
This adds velocity bounds on `EdgesBetweenSubgraphs`, which can be used to enable zero initial/final velocities, but also the proper use of delays in the graph.
It also fixes a bug when extracting the solution to ensure continuity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19357)
=> [planning] Add velocity bounds to edges between subgraphs

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
Resolves #19290
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19445)
=> [pydrake] Add binding for LinearComplementarityConstraint M and q.

bindings/pydrake/trajectories_py.cc, common/trajectories/test/piecewise_polynomial_test.cc, common/trajectories/trajectory.cc, common/trajectories/trajectory.h
This makes it easier (in c++) to, for instance, using Eigen::LinSpaced to sample at regular intervals from a trajectory.
+@xuchenhan-tri for both reviews, please (if it's not too late).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19422)
=> Overload Trajectory::vector_values to accept Eigen::VectorXd

bindings/pydrake/multibody/plant_py.cc
The python bindings for MultibodyPlant::GetStateNames() as well as GetPositionNames, GetVelocityNames, and GetActuatorNames had slightly different default values than in c++.  This update makes them consistent.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19455)
=> Fix default arguments for GetStateNames() and friends to match C++.

common/fmt.h, common/test/fmt_test.cc, common/test/text_logging_test.cc, common/yaml/yaml_write_archive.h, solvers/sdpa_free_format.cc
Towards #19446.
See also https://github.com/fmtlib/fmt/issues/3456.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19454)
=> [common] Provide fmt helper for consistent floating point output

geometry/optimization/convex_set.h, geometry/optimization/hpolyhedron.h
Resolves #19309.
I think we should just rip this bandaid off, as I don't think we actually have users of the `HPolyhedron::Serialize()` yet (but we're about to).
If need be, it would be easy to manually update the names in the yaml files to remove the trailing _ from the fields, and make them compatible again.
fyi @rcory , @mpetersen94 , @wrangelvid , @AlexandreAmice
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19469)
=> Rename fields in HPolyhedron::Serialize to match convention

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf
Closes https://github.com/RobotLocomotion/drake/issues/18951.
Ball joints should have no axis and if there is one the sdf parser will ignore it.
This PR corrects the warning the user gets when the sdf parser finds an axis in a ball joint. It also adds fixes to the relevant tests and removes irrelevant code related to parameters of a ball joint axis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18966)
=> Fix warning when ball joint has an axis

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_constraint.h, multibody/contact_solvers/sap/sap_limit_constraint.cc, multibody/contact_solvers/sap/sap_limit_constraint.h, multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc
Follow up to https://github.com/RobotLocomotion/drake/pull/19402, this PR implements the SAP limit constraints in terms of the newly introduced APIs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19452)
=> Implement SapLimitConstraint in terms of new APIs introduced in #19402

systems/analysis/integrator_base.h
I've found that even a little nudge to say "your system is probably unstable" and "no, the discrete-time multibodyplant is not (directly) to blame, look at the continuous-state parts of your system" can help them understand/resolve.
Related to #18452.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19481)
=> Improve error message for integrator smaller step size

planning/trajectory_optimization/direct_collocation.cc, planning/trajectory_optimization/direct_collocation.h, planning/trajectory_optimization/test/direct_collocation_test.cc
My previous attempt at caching failed to address the fact that the autodiff gradients would be different when the status/inputs were passed in different places inside the variable list for the constraint. Now we implement the chain rule locally so that the cache is kept warm with gradients only with respect to the current variables.
Resolves #19396.
+@sammy-tri for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19468)
=> Fix caching for autodiff in direct collocation

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_constraint.cc, multibody/contact_solvers/sap/sap_constraint.h, multibody/contact_solvers/sap/sap_constraint_jacobian.cc, multibody/contact_solvers/sap/sap_constraint_jacobian.h, multibody/contact_solvers/sap/sap_friction_cone_constraint.cc, multibody/contact_solvers/sap/sap_friction_cone_constraint.h, multibody/contact_solvers/sap/sap_holonomic_constraint.cc, multibody/contact_solvers/sap/sap_holonomic_constraint.h, multibody/contact_solvers/sap/sap_limit_constraint.cc, multibody/contact_solvers/sap/sap_limit_constraint.h, multibody/contact_solvers/sap/test/sap_constraint_bundle_test.cc, multibody/contact_solvers/sap/test/sap_constraint_test.cc, multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc, multibody/contact_solvers/sap/test/sap_holonomic_constraint_test.cc, multibody/contact_solvers/sap/test/sap_limit_constraint_test.cc, multibody/contact_solvers/sap/test/sap_model_test.cc, multibody/contact_solvers/sap/test/sap_solver_autodiff_test.cc, multibody/contact_solvers/sap/test/sap_solver_test.cc, multibody/plant/sap_driver.cc, multibody/plant/test/sap_driver_test.cc
Towards #19434.
In this PR:
1. Docs of `SapConstraint` are updated according to #19434.
2. `SapConstraint::constraint_function()` is removed, since no longer fits this abstraction. 
3. `SapConstraintJacobian` is introduced to defined the contraint velocity `vc` in a compact manner.
4. Refactoring of call sites to use new APIs in terms of `SapConstraintJacobian` (most of the bulk).
The compact set of arguments in a constraint is important for #19435, which introduces additional semantics for constraints to understand forces (i.e. more arguments).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19462)
=> Introduce SapConstraintJacobian

planning/trajectory_optimization/BUILD.bazel, planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc, solvers/osqp_solver.cc, solvers/test/osqp_solver_test.cc
Partial solution to #10048
Extracting primal-only warm starting from #19498
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19499)
=> [osqp_solver] Allow for primal-only warm-start

geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc
Fix #19504
- #19504 
Related to:
- #19494 
Test it by:
```
bazel run //tools:meldis -- -w &
bazel run //geometry/profiling:contact_surface_rigid_bowl_soft_ball
```
You should see contact surfaces like this:
Diagnosis of #19504:
1. contact_surface_rigid_bowl_soft_ball uses SceneGraph without MultibodyPlant.
2. It didn't calculate force and moment, so it sent the default zero force and moment to LCM  via lcmt_hydroelastic_contact_surface_for_viz message.
3. Meldis passes zero force and moment from LCM to Meshcat
4. Meshcat passes zero force and moment to HydroelasticContactVisualizer
5. [This code in HydroelasticContactVisualizer](https://github.com/RobotLocomotion/drake/blob/7417c146d434934fdced26449449b003040ec0f2/multibody/meshcat/hydroelastic_contact_visualizer.cc#L56-L63) skips any …
=> Fix visualization of contact_surface_rigid_bowl_soft_ball

geometry/render_gl/internal_opengl_geometry.h, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/internal_render_engine_gl.h, geometry/render_gl/test/internal_opengl_geometry_test.cc, geometry/render_gl/test/internal_render_engine_gl_test.cc
Previously, each `OpenGlInstance` contained a *copy* of the `OpenGlGeometry` that it instantiated. While the cost of a few ints isn't overly burdensome, this will be an obstacle in future efforts to clone the OpenGl context.
`RenderEngineGl` now maintains a vector of `OpenGlGeometry` and each instance merely gets an index into that vector. These indices are amenable to copying without requiring changing the references.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19508)
=> OpenGlInstance now references OpenGlGeometry in preparation for cloning

multibody/benchmarking/cassie.cc, tools/BUILD.bazel, tools/dynamic_analysis/bazel.rc, tools/performance/BUILD.bazel, tools/performance/fixture_memory.h, tools/performance/fixture_memory_no.cc, tools/performance/fixture_memory_yes.cc, tools/performance/gflags_main.cc, tools/workspace/googlebenchmark/patches/console_allocs.patch, tools/workspace/googlebenchmark/patches/string_precision.patch, tools/workspace/googlebenchmark/repository.bzl
Follow-up from #17487 to restore heap reporting.
Looking carefully at the `compare.py` report for the `CassieAutoDiff/MassMatrix/1` data with repetitions=100, it definitively shows that this new instrumentation costs exactly 3 extra CPU cycles per allocation.  On my 3 GHz machine, that's +1 ns per allocation, scaled up by 31,400 allocations is a difference of +31us on benchmark (~2%).
This probably the most extreme case; of all the benchmarks, MassMatrix has one of the highest fraction of allocations per instruction.
We could imagine automatically offering benchmark binaries that do not link in the malloc hooks, but for me the 3 cycle penalty is a reasonable enough one to leave unconditionally enabled.  Any relative before/after measurements for performance improvements should still hold …
=> [performance] Add allocation reporting

multibody/plant/multibody_plant.cc
Geometry with perception roles, if they have no definition of color, should defer to the `RenderEngine`'s logic and default values to pick up a color. MultibodyPlant shouldn't be playing a role in that regard.
In this case, MultibodyPlant is assuming that if the illustration properties have a color defined, the perception role should pick up the same. This is correct so far as our parsing cannot yet distinguish between illustration and perception roles (they're all just "visual").
This *can* affect an end user who never specified a color -- i.e., the default may change from MultibodyPlant's default color to their render engine or visualizer's default color.
- - - …
=> MultibodyPlant no longer assigned perception color

geometry/render_gl/BUILD.bazel, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/internal_render_engine_gl.h, geometry/render_gl/internal_shader_program.h, geometry/render_gl/internal_texture_library.cc, geometry/render_gl/internal_texture_library.h, geometry/render_gl/test/internal_texture_library_test.cc, geometry/render_gl/test/multithread_safety_test.cc
1. `TextureLibrary` no longer stores a pointer to `OpenGlContext`. It simply declares that the `OpenGlContext` must be bound. This will aid in cloning contexts across render engine families.
2. It handles look up of texture id in a thread-safe way. This was missing before and has now been corrected.
3. Tests have been added.
4. The texture library now handles symlink files so that a single file, aliased in different ways, doesn't lead to multiple textures on the GPU.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19507)
=> [rendering] TextureLibrary upgraded to prepare for cloning

bindings/pydrake/geometry/geometry_py_scene_graph.cc, bindings/pydrake/geometry/test/scene_graph_test.py, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/scene_graph.h, geometry/scene_graph_inspector.cc, geometry/scene_graph_inspector.h, geometry/test/geometry_state_test.cc, geometry/test/scene_graph_inspector_test.cc
This enables downstream code to know which input ports and frame kinematics to provide to (or expect from) a SceneGraph.
Towards #19437.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19525)
=> [geometry] Add SceneGraphInspector::GetAllSourceIds

math/BUILD.bazel, math/continuous_algebraic_riccati_equation.cc, systems/primitives/BUILD.bazel, systems/primitives/linear_system.cc, systems/primitives/linear_system_internal.cc, systems/primitives/linear_system_internal.h
The only edits to the moved code are the function arguments (now passed directly as matrices, instead of a `LinearSystem`), more `DRAKE_DEMAND` cross-checks, namespaces, clang formatting, and https://drake.mit.edu/styleguide/cppguide.html#Preincrement_and_Predecrement.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19529)
=> [math] Narrow the circular dependency on systems/primitives

bindings/pydrake/BUILD.bazel, bindings/pydrake/systems/BUILD.bazel
Fix error in earlier commit where the wrong test was marked as flaky.
Resolves #19394
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19541)
=> [pydrake] Mark systems lcm_test as flaky

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/cartesian_product.cc, geometry/optimization/cartesian_product.h, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/hpolyhedron.cc, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/intersection.cc, geometry/optimization/intersection.h, geometry/optimization/minkowski_sum.cc, geometry/optimization/minkowski_sum.h, geometry/optimization/point.cc, geometry/optimization/point.h, geometry/optimization/test/cartesian_product_test.cc, geometry/optimization/test/graph_of_convex_sets_test.cc, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/hyperellipsoid_test.cc, geometry/optimization/test/intersection_test.cc, geometry/optimization/test/minkowski_sum_test.cc, geometry/optimization/test/point_test.cc, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h, planning/trajectory_optimization/gcs_trajectory_optimization.cc
The user can already create such a set by moving-from an existing object. Making it directly constructible instead makes it easier to operate on and unit test these objects.
Add some missing nullptr checks.
---
Towards #19311.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19321)
=> Add a default constructor to all ConvexSet subclasses

geometry/optimization/convex_set.h, geometry/optimization/spectrahedron.cc, geometry/optimization/test/spectrahedron_test.cc
This will enable, e.g., using Spectrahedron in the GraphOfConvexSets using the two-cycle elimination constraint.
+@bernhardpg for feature review, please.
+@TobiaMarcucci for additional feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19527)
=> Implement the more general perspective function for Spectrahedron

planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Many constraints, like the path continuity constraints or velocity bounds are enforced on just one control point. Thus it's the constraint matrices end up sparse, which can be mitigated by dropping the unnecssary columns and variables in those constraints.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19444)
=> [planning] Removed unnecessary variables in constraints

geometry/optimization/convex_set.h, geometry/optimization/test/cartesian_product_test.cc, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/hyperellipsoid_test.cc, geometry/optimization/test/intersection_test.cc, geometry/optimization/test/minkowski_sum_test.cc, geometry/optimization/test/point_test.cc, geometry/optimization/test/spectrahedron_test.cc, geometry/optimization/test/vpolytope_test.cc
Requires #19321.  Closes #19310.  Towards #19279.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19311)
=> Fix ConvexSet move operations

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_constraint.cc, multibody/contact_solvers/sap/sap_constraint.h, multibody/contact_solvers/sap/sap_contact_problem.cc, multibody/contact_solvers/sap/sap_contact_problem.h, multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, multibody/plant/BUILD.bazel, multibody/plant/slicing_and_indexing.cc, multibody/plant/slicing_and_indexing.h, multibody/plant/test/slicing_and_indexing_test.cc
Towards #18983.
Adds functionality to reduce a `SapContactProblem` via `SapContactProblem::Reduce()` by providing a list of "locked" or non-participating dofs. This results in a permutation of the original cliques and constraints of the problem as well as the associated linear dynamics matrices, v_star, and constraint jacobians. The returned data structure `ReducedMapping` contains the information to map a `SapSolverResults` associated with the reduced dof problem to a corresponding `SapSolverResults` for the original problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19488)
=> [multibody] Reduce SapContactProblem to selected/excluded dofs.

multibody/fem/dirichlet_boundary_condition.cc, multibody/fem/dirichlet_boundary_condition.h, multibody/fem/fem_state.h, multibody/fem/test/dirichlet_boundary_condition_test.cc, multibody/fem/test/fem_model_test.cc, multibody/fem/test/fem_state_test.cc, multibody/plant/deformable_driver.cc, multibody/plant/deformable_model.cc
Instead, we require the full state (3 DoFs) of a vertex is specified when a vertex is put under a Dirichlet boundary condition.
The flexibility of putting individual DoFs of a vertex under BC turns out to be rather useless in practice as our public APIs only allow users to describes BCs at the level of vertices.
This also paves the way for transitioning to the new data structure of storing FEM tangent matrix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19545)
=> Disallow partial Dirichlet BC for an FEM node

visualization/BUILD.bazel, visualization/inertia_visualizer.cc, visualization/inertia_visualizer.h, visualization/test/inertia_visualizer_test.cc, visualization/test/visualization_config_functions_test.cc, visualization/visualization_config.h, visualization/visualization_config_functions.cc
Add the InertiaVisualizer and update ApplyVisualizationConfig() to add it by default. Inertia geometry is fully transparent for non-Meshcat visualizers (which do not offer alpha sliders).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19210)
=> [visualization] Add basic inertia visualizer

geometry/render_gl/BUILD.bazel, geometry/render_gl/factory.h, geometry/render_gl/internal_opengl_context.cc, geometry/render_gl/internal_opengl_context.h, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/internal_render_engine_gl.h, geometry/render_gl/internal_shader_program.cc, geometry/render_gl/internal_shader_program.h, geometry/render_gl/internal_texture_library.cc, geometry/render_gl/internal_texture_library.h, geometry/render_gl/test/internal_opengl_context_test.cc, geometry/render_gl/test/internal_shader_program_test.cc, geometry/render_gl/test/multithread_safety_test.cc
This allows a single RenderEngineGL to be cloned so that each clone can safely be used in different threads.
1. The OpenGlContext for each RenderEngineGl is thread-independent; binding one in one thread, doesn't preclude binding another in another thread.
2. OpenGlContexts that get cloned from each other share the same OpenGl artifacts (display lists, etc.) on the GPU.
Introduces a unit test that failed under the old non-threadsafe regime.
TODO:
- Delete thread_test_2.cc
- Change OpenGlContext so the test passes.
- Chnage the test to make sure OpenGlContext can be tested directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19426)
=> Make RenderEngineGl intelligently threadsafe

tools/release_engineering/dev/BUILD.bazel, tools/release_engineering/dev/README.md, tools/release_engineering/dev/push_release, tools/release_engineering/dev/push_release.py
Create a new push_release script written in Python. This takes over mirroring the .tar and .deb artifacts (and their respective hashes) to S3; the latter in particular replaces what was formerly a manual process due to the names being different. This also removes local specification of the artifact set and local recalculation of the hashes; both now use whatever is associated with the GitHub release.
Also, remove the actions handled by the new script from the old script. Eventually we expect to move the docker and apt steps to this script as well.
_Edit: Towards #18659_.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19510)
=> Start refactoring push_release script

systems/controllers/joint_stiffness_controller.h
Amends #19563 by reverting the problematic comment reflow.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19568)
=> [doc] Hotfix for system ports figure typo

bindings/pydrake/autodiff_types_pybind.h, bindings/pydrake/polynomial_types_pybind.h, bindings/pydrake/pydrake_pybind.h, bindings/pydrake/symbolic_types_pybind.h
This provides a single point of control for our custom dtypes, in preparation for dropping our forked version of pybind11.
Towards #19250.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19572)
=> [pydrake] Factor out DRAKE_PYBIND11_NUMPY_OBJECT_DTYPE helper

tools/workspace/pybind11/package.BUILD.bazel
Towards #19250.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19570)
=> [workspace] Use hdrs consistency checking for pybind11

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/cartesian_product.cc, geometry/optimization/cartesian_product.h, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.h, geometry/optimization/intersection.cc, geometry/optimization/intersection.h, geometry/optimization/minkowski_sum.cc, geometry/optimization/minkowski_sum.h, geometry/optimization/point.cc, geometry/optimization/point.h, geometry/optimization/spectrahedron.h, geometry/optimization/test/cartesian_product_test.cc, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/hyperellipsoid_test.cc, geometry/optimization/test/intersection_test.cc, geometry/optimization/test/minkowski_sum_test.cc, geometry/optimization/test/point_test.cc, geometry/optimization/test/spectrahedron_test.cc, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h, planning/trajectory_optimization/gcs_trajectory_optimization.cc
This allows algorithms (#19239) to customize themselves for degenerate sets, for performance.
+@wrangelvid +@RussTedrake what do you think of this proposal?  I think we could use this in `EdgesBetweenSubgraphs::RegionsConnectThroughSubspace` instead of the `dynamic_cast<Point*>`.
I only ported a few sets to the new function.  I suspect that some of the other types of sets (like a cartesian product of points) can also be degenerate.  We could iron out those details if the proposal seems useful.
Requires #19311.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19279)
=> ConvexSet can report when its just a point

geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer.h, geometry/test/meshcat_visualizer_test.cc
Previously, the visibility parameter was not respected (a) before the initialization event or (b) if delete_on_initialization_event was false.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19578)
=> MeshcatVisualizer sets visibility directly without events

visualization/visualization_config_functions.cc
It was hard coded to 1/64 seconds before this fix.
Relevant to #19494.
Thanks to @rcory for using LCM Spy and reporting this problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19590)
=> [visualization] Make LCM CONTACT_RESULTS from ApplyVisualizationConfig() respect publish_period

multibody/tree/rotational_inertia.h, multibody/tree/spatial_inertia.cc, multibody/tree/test/spatial_inertia_test.cc, multibody/tree/unit_inertia.h, visualization/test/inertia_visualizer_test.cc
Closes #19544
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19581)
=> SpatialInertia::MakeFromCentralInertia() immediately checks physical validity

systems/sensors/BUILD.bazel
Similar to #7520, the GL vendor's libraries are not sufficiently instrumented for compatibility with TSan.
Possibly this should be part of `vtk_test_tags()` in the first place, but for now I'll be conservative and just change one spot.
Here's an example of the errors we'll be ignoring now:
```
==================
WARNING: ThreadSanitizer: data race (pid=596042)
Write of size 8 at 0x7b5400018d80 by thread T1 (mutexes: write M0):
#0 free <null> (rgbd_sensor_async_gl_test+0x273914) (BuildId: d89053b7261f5ad5c666c45513ee3f4d23641657)
#1 <null> <null> (libnvidia-glcore.so.525.105.17+0x146eaf5) (BuildId: 5bdffe680592c7195d8beb3e9a87fcb951d4c64f)
#2 drake::geometry::render_gl::internal::OpenGlContext::MakeCurrent() const geometry/render_gl/internal_opengl_context.cc:324:50 …
```
=> [sensors] Hotfix for async test vs TSan

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/iris.h
In order to serialize a dictionary of Iris regions in both C++ and Python, this PR defines the type and adds the bespoke serialization wrapper for pydrake.
Towards #19514.
Related to #19597.  If that lands, we can deprecate this shim.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19612)
=> Adds SaveIrisRegionsYamlFile and LoadIrisRegionsYamlFile to pydrake

bindings/pydrake/test/symbolic_test.py
For an example failure, see here:
https://drake-jenkins.csail.mit.edu/view/Production/job/mac-arm-monterey-unprovisioned-clang-bazel-nightly-release/260/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19626)
=> [pydrake] Adjust deprecation test for pydrake >= 1.25

geometry/profiling/BUILD.bazel, manipulation/models/realsense2_description/BUILD.bazel, multibody/parsing/BUILD.bazel, tools/workspace/forward_files.bzl
This helps mitigate spurious build errors when downstream developers use different versions of model files externals. For example, if they are skipping `detail_mujoco_parser_test` then we shouldn't try to copy the `dm_control` model files when building `//...`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19614)
=> [tools] Always set forward_files to manual

examples/kuka_iiwa_arm/BUILD.bazel, examples/kuka_iiwa_arm/test/optitrack_test.cc
This test is vestigial.
It as created as a bootstrapping tool while we were working on adding new dependencies to the build system.  Since then, we've grown our optitrack support, and we now have several tests that supersede it, e.g., the sender and receiver tests here:
https://github.com/RobotLocomotion/drake/blob/v1.17.0/systems/sensors/test/optitrack_sender_test.cc#L3
https://github.com/RobotLocomotion/drake/blob/v1.17.0/systems/sensors/test/optitrack_receiver_test.cc#L3
To prune some deadwood, we should remove the now-redundant test.
Towards #19600.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19616)
=> [examples] Remove optitrack_test

geometry/render_gltf_client/BUILD.bazel, geometry/render_gltf_client/test/merge_gltf_test.cc, tools/workspace/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/nlohmann_internal/BUILD.bazel, tools/workspace/nlohmann_internal/package.BUILD.bazel, tools/workspace/nlohmann_internal/patches/vendor.patch, tools/workspace/nlohmann_internal/repository.bzl
This adds the library as header only. It might be better to build it as a static library, but the header-only version was quick and dirty.
relates #19532
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19625)
=> Add nlohmann as internal vendored library

solvers/constraint.h, solvers/create_constraint.cc, solvers/mathematical_program.h, solvers/test/create_constraint_test.cc
Previously, a quadratic constraint passes to AddConstraint would default to an ExpressionConstraint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19633)
=> MathematicalProgram::AddConstraint parses QuadraticConstraint

bindings/pydrake/BUILD.bazel, bindings/pydrake/forwarddiff.py, bindings/pydrake/test/forward_diff_test.py
Resolves #19584
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19638)
=> [py autodiff] Handle empty derivatives in pydrake.forwarddiff.jacobian.

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/solvers_py_branch_and_bound.cc, bindings/pydrake/solvers/test/branch_and_bound_test.py, solvers/BUILD.bazel, solvers/branch_and_bound.h
In particular, we need `repr()` to remove hex spam from our API reference:
https://drake.mit.edu/pydrake/pydrake.solvers.html#pydrake.solvers.MixedIntegerBranchAndBound
Before: 
After:
Amends #19366.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19639)
=> [py solvers] Add more MixedIntegerBranchAndBound::Options bindings

tools/release_engineering/dev/push_release
Modify the logic in push_release that expected the GPG key fingerprint to be manually entered. While preserving the security of the private key is good, the identifying fingerprint is part of the public key, and therefore there is no reason to not simply fetch the public key in order to obtain the fingerprint, thus removing a manual step.
+@BetsyMcPhail for review (both), please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19630)
=> push_release: get GPG fingerprint from public key

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/contact_configuration.cc, multibody/contact_solvers/contact_configuration.h, multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_friction_cone_constraint.cc, multibody/contact_solvers/sap/sap_friction_cone_constraint.h, multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc, multibody/contact_solvers/sap/test/sap_solver_autodiff_test.cc, multibody/contact_solvers/sap/test/sap_solver_test.cc, multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/contact_pair_kinematics.h, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/sap_driver.cc, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/deformable_driver_contact_kinematics_test.cc, multibody/plant/test/sap_driver_test.cc
Towards #19435. Follow up to #19557.
This PR implements `SapFrictionConeConstraint::DoAccumulateSpatialImpulses()` so that the constraint can report forces.
Notice however this new functionality is not yet used.
Updates in manager and drivers are only due to an updated constructor signature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19596)
=> SAP contact constraint reports multibody forces

examples/manipulation_station/manipulation_station.cc, examples/manipulation_station/test/manipulation_station_test.cc
#18268 introduced the `applied_spatial_force` input port in `ManipulationStation`; however, the input applied spatial force value is not used by MbP at all but instead only flows through the force computer.
Some context: #18268 has a unit test that's supposed to reveal this issue but it was short circuited by #12786. Partially resolving #12786, #19225 allows the unit test to reveal the problem again.
I believe the fix is as simple as porting `applied_spatial_force` into MbP, but I'm not overly familiar with manipulation station so reviewers be aware.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19548)
=> [manipulation_station] Use applied spatial force in MbP

geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc
Use a variable to more easily space out the x-axis offsets.
Obey GSG's formatting rule for floating point literals.
Inspired by #19635.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19645)
=> [geometry] Clean up meshcat tests for maintainability

bindings/pydrake/systems/sensors_py.cc, systems/sensors/BUILD.bazel, systems/sensors/rgbd_sensor.cc, systems/sensors/rgbd_sensor.h, systems/sensors/rgbd_sensor_discrete.cc, systems/sensors/rgbd_sensor_discrete.h, systems/sensors/test/rgbd_sensor_async_gl_test.cc, systems/sensors/test/rgbd_sensor_discrete_test.cc, systems/sensors/test/rgbd_sensor_test.cc
Unless classes need to bleed private implementation details between each other, generally we should place once class per h/cc file pair to de-clutter development and improve build speeds.
Towards #19604 and #19437.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19649)
=> [sensors] Split RgbdSensorDiscrete into its own file

multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc, multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
Fix a bug that incorrectly rejects putting zero matrix on the diagonal block of a block sparse symmetric matrix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19647)
=> Allow zero matrix on the diagonal for block sparse matrix

math/BUILD.bazel, math/soft_min_max.cc, math/soft_min_max.h, math/test/soft_min_max_test.cc, solvers/BUILD.bazel, solvers/minimum_value_constraint.cc
Support soft min or max being either the under or over approximation of min/max.
This will be used later when I impose the minimum distance constraint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19591)
=> [math] Add soft min and max function

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/bezier_curve.cc, common/trajectories/bezier_curve.h, common/trajectories/test/bezier_curve_test.cc
A Bezier curve of degree n can be converted into a Bézier curve of degree n + 1 with the same shape. This method implements the degree/order elevation.
+@AlexandreAmice for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19620)
=> Implements BezierCurve::ElevateOrder()

geometry/optimization/cspace_free_box.cc, geometry/optimization/cspace_free_polytope.cc, geometry/optimization/cspace_free_polytope_base.cc, geometry/optimization/cspace_free_polytope_base.h, geometry/optimization/test/cspace_free_polytope_base_test.cc
For CspaceFreeBox, for the separating plane between a pair of geometries, the a(s) and b(s) of that plane only need to depend on the subset of s on the kinematics chain between the pair of geometries.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19609)
=> [C-IRIS] Compute s on the kinematics chain between each body.

multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc, multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h, multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
This is useful for getting the Schur complement as a by-product of a right-looking Cholesky factorization as the bottom right corner of the matrix stores the Schur complement of the already-factored top-left corner of the matrix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19644)
=> Add MakeDenseBottomRightCorner to block sparse matrix

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_contact_problem.cc, multibody/contact_solvers/sap/sap_contact_problem.h, multibody/contact_solvers/sap/test/sap_contact_problem_test.cc
This is the final companion PR to #18983.
We introduce one new API `SapContactProblem::ExpandContactSolverResults()` that takes as input the results of a reduced version of the contact problem as well as the mapping between original problem and reduced, and fills a `SapSolverResults` with the dimensionality of the original problem. Values of the results for non-participating DoFs and constraints are set to zero.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19607)
=> [multibody] Expand SapSolver results from reduced problem.

bindings/pydrake/autodiffutils_py.cc, bindings/pydrake/forwarddiff.py, bindings/pydrake/test/autodiffutils_test.py
Add docs and kwarg names for all overloads, matching the naming choices of the forthcoming `drake::ad::AutoDiff`.
Port a few existing call sites to use the more efficient constructor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19623)
=> [py autodiff] Bind constructor overload for unit derivatives vector

bindings/pydrake/common/eigen_pybind.h, bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/pydrake_pybind.h, bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/sensors_py.cc, bindings/pydrake/test/_pydrake_pybind_test_extra.py, bindings/pydrake/test/pydrake_pybind_test.cc
Resolves #19617, at least as far as the acute error goes. Using Rico's solution outright.
~Resolves~ Relates #11046 (core issue) - This narrows the use of `py::detail::keep_alive_impl()`
Closes #19615 (superseded)
Relates #19636 (attempt to make a `type_caster<>` for `copyable_unique_ptr<>`)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19655)
=> [bindings] Use vanilla py::cast() for keep alive behavior

multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc, multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h, multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
The information about the number of nonzeros in a sparsity pattern helps evaluate the quality of the elimination ordering for a sparse system.
Towards #19466.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19678)
=> Compute number of nonzeros in a sparsity pattern

geometry/render_gltf_client/test/internal_merge_gltf_test.cc
Adding the `operator<<` in `MergeCase` resolves the memcheck failure.
```
$ bazel test --config=memcheck //geometry/render_gltf_client:internal_merge_gltf_test
INFO: Invocation ID: a0286ef3-256f-49ec-bb9a-ac4972b31824
INFO: Analyzed target //geometry/render_gltf_client:internal_merge_gltf_test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //geometry/render_gltf_client:internal_merge_gltf_test up-to-date:
bazel-bin/geometry/render_gltf_client/internal_merge_gltf_test
INFO: Elapsed time: 10.844s, Critical Path: 10.62s
INFO: 4 processes: 1 internal, 3 linux-sandbox.
INFO: Build completed successfully, 4 total actions
Executed 1 out of 1 test: 1 test passes.
```
- - - …
=> Fix memcheck failure in internal_merge_gltf_test.cc

geometry/optimization/iris.cc
For long-running calls to IRIS, this gives some much needed feedback. It also can give some insights on if/where IRIS is getting bogged down.
This PR also clarifies the usage of the term "seed" vs "samples" vs "searches", which got even more confusing when we start reporting excessive numbers of searches.
The code does not change the computation (and therefore does not change the tests).
+@cohnt for feature review, please?
cc @rhjiang
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19673)
=> Adds some text logging to IrisInConfigurationSpace

geometry/optimization/iris.cc, geometry/optimization/test/iris_in_configuration_space_test.cc, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
Previously they supported Convex geometry; now we extend that support to Mesh.
For VPolytope: The semantics of this class are already clear that the set is defined by the convex hull of the points. We even had a test case of passing a non-convex mesh as Convex to prove it. This PR simply adds the natural support.
For IrisInConfigurationSpace: Since IRIS is attempting to certify non-collision, taking the convex hull of the mesh is on the correct side of conservatism. Having this support will improve usability for folks bringing their own geometry to IRIS.
Related to #19514.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/196 …
=> VPolytope and IrisInConfigurationSpace support Mesh geometry.

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py, multibody/meshcat/BUILD.bazel, multibody/meshcat/joint_sliders.cc, multibody/meshcat/joint_sliders.h, multibody/meshcat/test/joint_sliders_test.cc, systems/framework/BUILD.bazel, systems/framework/system.cc, systems/framework/system.h, systems/framework/test/diagram_test.cc, systems/framework/test/leaf_system_test.cc, systems/framework/test_utilities/BUILD.bazel, systems/framework/test_utilities/initialization_test_system.h, visualization/BUILD.bazel, visualization/meshcat_pose_sliders.cc, visualization/test/meshcat_pose_sliders_test.cc
and uses it in MeshcatPoseSliders and JointSliders.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19577)
=> Implements System<T>::ExecuteInitializationEvents()

tools/release_engineering/dev/README.md, tools/release_engineering/dev/push_release, tools/release_engineering/dev/push_release.py
Rewrite logic to push the release docker tags in Python, and to rely on the staging tags we are newly creating. This hopefully makes the logic easier to follow, and allows for a dry-run. More importantly, it eliminates the need to associate a release with a nightly build, which we really shouldn't have been doing in the first place, and simplifies things for the release manager.
Also remove an outdated instruction from the README, and change the aptly snapshot to use the source version rather than the corresponding nightly date for the release's snapshot name.
Fixes #19564.
See also RobotLocomotion/drake-ci#227 which added the staging tags. (Also RobotLocomotion/drake-ci#228, RobotLocomotion/drake-ci#229 and RobotLocomotion/drake-ci#230 which fixed the ensuing fallout.)
+@BetsyMcPhail for …
=> Rewrite push_release logic for docker

doc/_release-notes/v1.18.0.md
Amends #19534. Relates #19659.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19661)
=> [doc] Add 1.18 release notes caveat for DockerHub

bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/test/model_visualizer_camera_test.py, bindings/pydrake/visualization/test/model_visualizer_test.py
Closes #19415.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19687)
=> [py visualization] Split flaky camera_test into its own file

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, geometry/geometry_state.h, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h
This was needed immediately for #19522, but is useful particularly for optimization algorithms which need to know the linear form (given q) of the map from velocity to qdot (and back).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19675)
=> Implements MultibodyPlant::MakeVelocityToQDotMap and MakeQDotToVelocityMap

systems/analysis/simulator.h
Minor doc improvement due to users missing this feature
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19694)
=> Add set_monitor() reference to Simulator::AdvanceTo() docs

multibody/contact_solvers/sap/sap_constraint.cc, multibody/contact_solvers/sap/sap_constraint.h, multibody/contact_solvers/sap/sap_contact_problem.cc, multibody/contact_solvers/sap/sap_contact_problem.h, multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/sap_driver.h, multibody/plant/slicing_and_indexing.cc, multibody/plant/slicing_and_indexing.h, multibody/plant/tamsi_driver.cc, multibody/plant/test/deformable_driver_test.cc, multibody/plant/test/joint_locking_test.cc, multibody/plant/test/slicing_and_indexing_test.cc
Implements functionality for joint locking when SAP is the underlying discrete solver. Prior to this PR, the locked/unlocked status of a joint was ignored when using SAP.
Now joint locking with function as intended: whatever configuration the joint was in when `joint.Lock(&context)` is called will remain constant in every subsequent timestep until `joint.Unlock(&context)` is called. Further, joint velocities for the locked joint will remain exactly 0 for every timestep while the joint is locked.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/18983)
=> [multibody] Add joint locking feature to SAP

geometry/meshcat_visualizer.h, geometry/test/meshcat_test.cc, geometry/test/meshcat_visualizer_test.cc, systems/analysis/instantaneous_realtime_rate_calculator.h, systems/analysis/test/instantaneous_realtime_rate_calculator_test.cc
Previously when resuming simulator from a paused state, the realtime rate (RTR) calculator will use a wrong prev_sim_time_, resulting in a sudden drop of RTR in meshcat. This adds a new API ResetRealtimeRateCalculator() to meshcat visualizer which should be called upon simulation resuming to fix the issue.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19667)
=> Add Reset functions for realtime rate calculation

bindings/pydrake/systems/sensors_py.cc, bindings/pydrake/systems/test/sensors_test.py, systems/sensors/rgbd_sensor.cc, systems/sensors/rgbd_sensor.h, systems/sensors/rgbd_sensor_async.cc, systems/sensors/rgbd_sensor_async.h, systems/sensors/rgbd_sensor_discrete.cc, systems/sensors/rgbd_sensor_discrete.h, systems/sensors/test/rgbd_sensor_async_test.cc, systems/sensors/test/rgbd_sensor_discrete_test.cc, systems/sensors/test/rgbd_sensor_test.cc
Towards #19604 and #19437.
Closes #19198.
Feature:
- Add an image_time output port to all three RGBD sensors.
Fixes:
- Fix the missing ZOH on the discrete sensor's body pose output port.
- Async sensor: the systems framework does not allow negative event trigger times, so we need to forbid that.
- Async sensor: Change the port getters to throw instead of nullptr. This is better for return-type consistency with the other sensors.
Tweak some style guide typos and related inconsistencies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19696)
=> [sensors] Improve RgbdSensorDiscrete and RgbdSensorAsync

manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14.xacro, manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf, manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf
Adds a collision filter group to all iiwa models to avoid self collisions between links 5 through 7.
To see the change, one can run
```
from pydrake.visualization import ModelVisualizer
v = ModelVisualizer()
v.AddModels(url="package://drake/manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf")
plant = v.parser().plant()
plant.WeldFrames(plant.world_frame(), plant.GetFrameByName("base"))
v.Finalize()
v.Run(position=[0, 0.3, 0, -1.8, 0, 1, 1.57])
```
Before the change, the visualizer will show the self collision. After the change there is no collision.
This PR also adds a missing declare_convex tag to the polytopic geometry.
+@rcory for feature review, please.
Towards #19514.
- - - …
=> Avoid false self collisions in iiwa_primitive_collision.urdf

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/plant/BUILD.bazel, multibody/plant/constraint_specs.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/test/multibody_plant_scalar_conversion_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/plant/test/sap_driver_ball_constraints_test.cc, multibody/plant/test/sap_driver_distance_constraints_test.cc, multibody/plant/test/sap_driver_joint_limits_test.cc, multibody/tree/BUILD.bazel, multibody/tree/multibody_tree_indexes.h
Changes the internal indexing of SAP constraints from a TypeSafeIndex into an Identifier. This will more easily enable the workflow of adding/removing or enabling/disabling constraints.
Currently `ConstraintIndex` is only exposed through the return value of:
- `AddCouplerConstraint()`
- `AddDistanceConstraint()`
- `AddBallConstraint()`
It is not used in any public API for access or introspection to constraints in the plant.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19698)
=> [multibody] Change ConstraintIndex into ConstraintId

bindings/pydrake/geometry/geometry_py_visualizers.cc, bindings/pydrake/geometry/test/visualizers_test.py, bindings/pydrake/visualization/_meldis.py, bindings/pydrake/visualization/test/meldis_test.py
Towards #17662.
For local testing, use this patch to enable inertia visualization:
```patch
--- a/bindings/pydrake/visualization/_model_visualizer.py
+++ b/bindings/pydrake/visualization/_model_visualizer.py
@@ -317,6 +317,7 @@ class ModelVisualizer:
ApplyVisualizationConfig(
config=VisualizationConfig(
publish_contacts=self._publish_contacts,
+                publish_inertia=True,
enable_alpha_sliders=True),
plant=self._builder.plant(),
scene_graph=self._builder.scene_graph(),
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19677)
=> [py visualization] Meldis supports inertia visualization

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/test/graph_of_convex_sets_test.cc
This fixes some small bugs in our handling of the case where no path exists.
+@TobiaMarcucci for feature review, please.
(I found this when toying with the default parameter changes, which I will PR once this lands).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19719)
=> GraphOfConvexSets returns kInfeasibleConstraints when no path exists.

bindings/pydrake/multibody/inverse_kinematics_py.cc, multibody/inverse_kinematics/minimum_distance_constraint.cc, multibody/inverse_kinematics/minimum_distance_constraint.h, multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc, solvers/minimum_value_constraint.cc, solvers/minimum_value_constraint.h
We can enforce the constraint that the minimum distance is below a certain threshold.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19718)
=> [InverseKinematics] Add upper bound on the minimum distance.

solvers/BUILD.bazel, solvers/gurobi_solver.cc, solvers/gurobi_solver.h, solvers/test/gurobi_solver_license_retention_test.py, solvers/test/gurobi_solver_license_retention_test_helper.cc
Iff the contents of the file identified in GRB_LICENSE_FILE contain the magic keywork HOSTID, then any license that is obtained will never be destroyed.
Resolves #19657.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19713)
=> GurobiSolver acquires a local license at most once per process

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/solvers_py.cc, bindings/pydrake/solvers/solvers_py.h, bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/solvers_py_semidefinite_relaxation.cc, bindings/pydrake/solvers/test/semidefinite_relaxation_test.py, geometry/optimization/spectrahedron.cc, solvers/BUILD.bazel, solvers/semidefinite_relaxation.cc, solvers/semidefinite_relaxation.h, solvers/test/semidefinite_relaxation_test.cc
Given a (typically nonconvex) MathematicalProgram, this method constructs a new MathematicalProgram which implements the SDP relaxation of the original program.
This initial implementation supports the case of quadratic objectives and constraints; it's an extremely important (and quite general) case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19632)
=> Implements MakeSemidefiniteRelaxation

geometry/optimization/BUILD.bazel, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/test/hyperellipsoid_test.cc
Previously, if the set `other` had no interior, the solver would fail the method would throw a confusing error message. Now it handles this case explicitly.
This PR also resolves a TODO to return to ChooseBestSolver in the MinimumUniformScalingToTouch now that #15320 is resolved.
+@cohnt for feature review, please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19671)
=> Hyperellipsoid::MinimumUniformScalingToTouch handles the empty case.

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/cartesian_product.cc, geometry/optimization/cartesian_product.h, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/minkowski_sum.cc, geometry/optimization/minkowski_sum.h, geometry/optimization/point.cc, geometry/optimization/point.h, geometry/optimization/test/cartesian_product_test.cc, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/hyperellipsoid_test.cc, geometry/optimization/test/intersection_test.cc, geometry/optimization/test/minkowski_sum_test.cc, geometry/optimization/test/point_test.cc, geometry/optimization/test/spectrahedron_test.cc, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
This function already existed for HPolyedron, but this adds it to the base ConvexSet class, and implements it for all derived classes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19716)
=> Implement IsEmpty for ConvexSet and derived classes

bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc, planning/trajectory_optimization/BUILD.bazel, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, solvers/choose_best_solver.cc
NOTE: Also changes GraphOfConvexSets to use `convex_relaxation = false` by default.
GcsTrajectoryOptimization (and perhaps other future downstream consumers of GCS) should use different default GCS options than the main GCS class. To support this, we make the relevant options std::optional, so that each method can distinguish between whether they have been set by the user or can be set to new appropriate default values before passing those options to the main GCS class.
For legibility, also adds an info-level log message telling user which of those most important options they've ended up with.
+@tobiamarcucci for feature review.
+@wrangelvid for additional feature review.
- - - …
=> Optional default options for GraphOfConvexSets.

multibody/plant/multibody_plant.h, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/test/model_instance_test.cc, multibody/tree/test/multibody_tree_test.cc
Unwind some code duplication between the plant and the tree, so that we only need to fix the logic one place. (Amends #11344 to remove its copy-pasta.)
To avoid name conflicts for a joint's parent body's offset frame, register the offset frame using the child body's model instance instead of the parent's model instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19724)
=> [multibody] Reject duplicated frame names

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/minimum_degree_ordering.cc, multibody/contact_solvers/minimum_degree_ordering.h, multibody/contact_solvers/test/minimum_degree_ordering_test.cc
Introduce a minimum degree ordering that is a slightly modified version of Algorithm 1 in [Amestoy 1996].
This ordering is intended to be used for the block sparse Cholesky solver that will serve as an alternative implementation to the Conex solver in the `contact_solvers::internal::SupernodalSolver`.
Towards #19466.
[Amestoy 1996] Amestoy, Patrick R., Timothy A. Davis, and  Iain S. Duff. "An approximate minimum degree ordering algorithm." SIAM Journal on Matrix Analysis and Applications 17.4 (1996): 886-905.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19535)
=> Add Minimum Degree ordering

solvers/BUILD.bazel, solvers/mathematical_program.h, solvers/mosek_solver.cc, solvers/mosek_solver_common.cc, solvers/mosek_solver_internal.cc, solvers/mosek_solver_internal.h, solvers/test/mosek_solver_internal_test.cc, solvers/test/mosek_solver_test.cc, solvers/test/quadratic_constrained_program_examples.cc, solvers/test/quadratic_constrained_program_examples.h
MosekSolver now takes in convex QuadraticConstraint. We still recommended the users to formulate the convex QuadraticConstraint
as Lorentz cone constraint to get best solver performance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19705)
=> MosekSolver supports QuadraticConstraint

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/test/hpolyhedron_test.cc
This method returns a scaled version of the HPolyhedron (about some center point). It is useful in our IRIS workflows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19733)
=> Adds HPolyhedron::Scale()

geometry/optimization/iris.cc, geometry/optimization/test/iris_in_configuration_space_test.cc
When using configuration obstacles, it was possible to add a face to the polyhedron and move the guess outside of the region. This caused the hit and run sampler to fail.  Adds a test to cover it.
This PR also touches up the guess logic in all three loops (configuration obstacles, task obstacles, and additional constraints) to be consistent.
+@sadraddini for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19728)
=> Fix IrisInConfigurationSpace hit and run.

tools/performance/defs.bzl
Otherwise, all benchmark programs warn about units every time we test them.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19744)
=> [tools] Fix a typo in googlebench command line

multibody/tree/rotational_inertia.cc, multibody/tree/rotational_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19726)
=> Notation clean-up (replace frame P with frame A).  Isolate calculation of canonical principal directions.

bindings/pydrake/common/test/wrap_pybind_test.py, bindings/pydrake/common/test/wrap_test_util_py.cc, bindings/pydrake/common/wrap_function.h
Ran into this in some Anzu code (PR 10614) using `WrapCalbacks()`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19697)
=> [wrap_function] Allow for empty std::function objects

geometry/optimization/test/iris_in_configuration_space_test.cc
After #19728, mac w/ SNOPT was failing with the default random seed. This PR increases the number of samples to verify the region.
Closes #19749.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19751)
=> Follow-up fix for IrisInConfigurationSpace mac test

planning/collision_checker.cc, planning/collision_checker.h, planning/collision_checker_params.h, planning/test/collision_checker_test.cc
Previously, when setting a distance (or interpolation) function, `CollisionChecker` would validate it by testing the distance between the zero configuration and itself (or by interpolating between the zero configuration and itself). It is perfectly reasonable that a distance or interpolation function (e.g., one with quaternions) would reject such an invalid configuration as being incalculable. By using the default configuration, we assume we're starting with a valid configuration and the distance/interpolation functions can use their most natural semantics.
The valid test now validates using the plant's default configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomoti …
=> CollisionChecker validates distance/interpolation funcs with default config

geometry/meshcat_visualizer.h
In PR #18433, we moved MeshcatAnimation into Meshcat (instead of the Context). The comments about multithreading are moot -- our current stance is that one should not try to publish to visualizers from multiple threads.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19767)
=> Remove outdated TODO from MeshcatVisualizer

systems/controllers/finite_horizon_linear_quadratic_regulator.h
+@EricCousineau for both reviews, please.
The doxygen build server had failed with
```
[1:24:49 PM]  RuntimeError: Problems found by Doxygen:
[1:24:49 PM]  drake/systems/controllers/finite_horizon_linear_quadratic_regulator.h:81: error: unable to resolve reference to `Integrators' for \ref command
````
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19772)
=> Fixup for #19765. Remove problematic doxygen ref.

tools/install/bazel/test/drake_bazel_installed_test.py
Follow-up to #19715, this change should have been committed along with the upgrade to `drake/tools/workspace/rules_python/repository.bzl`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19784)
=> [install] Upgrade rules_python to latest release to match workspace

tools/workspace/lcm/package.BUILD.bazel
This removes unnecessary build steps during message codegen.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19788)
=> [workspace] Remove spurious lcm-gen dependency

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program_result.cc, solvers/mathematical_program_result.h, solvers/test/mathematical_program_result_test.cc
This only supports the narrow case where the decision variable indices do not change. But it is very helpful for, e.g., writing test cases for methods that must extract context from a
MathematicalProgramResult. Previously, the only alternative was to set the entire vector each time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19790)
=> Adds MathematicalProgramResult::SetSolution()

geometry/optimization/test/graph_of_convex_sets_test.cc
Replaces #19793.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-everything-valgrind-memcheck please
@drake-jenkins-bot linux-focal-clang-bazel-nightly-gurobi-release please
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19794)
=> Fix GraphOfConvexSets test tolerances

geometry/benchmarking/render_benchmark.cc, multibody/benchmarking/acrobot.cc, multibody/benchmarking/cassie.cc, multibody/benchmarking/position_constraint.cc, systems/benchmarking/framework_benchmarks.cc, systems/benchmarking/multilayer_perceptron_benchmark.cc, tools/workspace/googlebenchmark/patches/remove_overloaded_fixture_set_up.patch, tools/workspace/googlebenchmark/repository.bzl
This allows us to remove copy-pasta in every benchmark we write.
\CC @RussTedrake whichever #19771 or this merges first, the other one should rebase to delete the pasta in the new benchmark, too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19796)
=> [workspace] Patch googlebenchmark to avoid shadow warnings

geometry/render_vtk/internal_render_engine_vtk.h
Extracted from #17962.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19799)
=> [render_vtk] Hide VTK derived class symbols

multibody/parsing/detail_common.cc, multibody/parsing/detail_common.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/parsing_doxygen.h, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/plant/constraint_specs.h, multibody/plant/multibody_plant.h, multibody/plant/test/sap_driver_ball_constraints_test.cc, multibody/plant/test/sap_driver_distance_constraints_test.cc
Adds parsing for SAP ball constraints in SDF and URDF. In addition a few small APIs for constraint introspection are introduced. They give const access to all constraint specs in the plant. These are necessary to give access to constraints when an associated `MultibodyConstraintId` is not present (e.g. silently thrown away by the Parser).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19780)
=> [parsing] Parse custom ball constraint elements.

solvers/semidefinite_relaxation.cc, solvers/semidefinite_relaxation.h, solvers/test/semidefinite_relaxation_test.cc
Fixes the issue described in #19783.
On [this](https://github.com/bernhardpg/drake/blob/sdp_relaxation_bounding_box_constraints/solvers/semidefinite_relaxation.cc#L164) (and [this](https://github.com/bernhardpg/drake/blob/sdp_relaxation_bounding_box_constraints/solvers/semidefinite_relaxation.cc#L174)) line, we know that the value should be `-1.0` (and `1.0`). Do we prefer to keep it the way it is, which may be more readable, or should we rather use the constant values?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19795)
=> Handle bounding box constraints in MakeSemidefiniteRelaxation

multibody/contact_solvers/minimum_degree_ordering.cc, multibody/contact_solvers/minimum_degree_ordering.h, multibody/contact_solvers/test/minimum_degree_ordering_test.cc
Compute the minimum degree ordering of a sparsity pattern under the constraint that certain nodes are eliminated before others. This is useful for computing Schur complement as a side effect of a right-looking Cholesky factorization as the variables w.r.t which the Schur complement is computed must be eliminated first.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19762)
=> Compute MD ordering with priority nodes

multibody/rational/rational_forward_kinematics.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19797)
=> fix names shown off-by-one in RationalForwardKinematics var names

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/minimum_degree_ordering.cc, multibody/contact_solvers/minimum_degree_ordering.h, multibody/contact_solvers/test/minimum_degree_ordering_test.cc
Given a block sparsity pattern G on vertices v = {0, 1, ..., n-1} and a partition on v = v₁ ∪ v₂ (such that v₁ ∩ v₂ = ∅), computes an elimination for v₁ and v₂ respectively using their induced graphs and concatenates them.
This is useful for computing Schur complement as a side effect of a right-looking Cholesky factorization as the variables w.r.t which the Schur complement is computed must be eliminated first.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19764)
=> Compute in-group Minimum Degree ordering

tutorials/authoring_multibody_simulation.ipynb
Add text telling users how to unfold and see the inertia geometry.
Update the simple simulation to use default visualization and record the proximity geometry and contact forces as well.
(Note that meshcat-recorded animations won't show the inertia ellipsoids until #19813 lands.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19812)
=> [tutorials] Highlight inertia visualization in multibody tutorial

solvers/mathematical_program_result.h, solvers/test/mathematical_program_result_test.cc
This enables, for instance, callers that want to add new variables to an existing `MathematicalProgramResult` (who can get the current index, add to it, and then `set_decision_variable_index()`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19814)
=> Add MathematicalProgramResult::get_decision_variable_index()

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc, planning/trajectory_optimization/gcs_trajectory_optimization.cc
... and use it in GcsTrajectoryOptimization.
Also adds introspection methods that curate the incoming and outgoing edges from a vertex.
cc @TobiaMarcucci 
(note that one test will fail until #19790 lands, but I'd like to start the review process here)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19792)
=> Adds GraphOfConvexSets::GetSolutionPath() and supporting introspection methods.

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/cartesian_product.cc, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/test/cartesian_product_test.cc, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/hyperellipsoid_test.cc, geometry/optimization/test/intersection_test.cc, geometry/optimization/test/minkowski_sum_test.cc, geometry/optimization/test/point_test.cc, geometry/optimization/test/spectrahedron_test.cc, geometry/optimization/test/vpolytope_test.cc
Towards #19717.
This method simply computes and returns a point within a convex set. If the set is empty or has ambient dimension zero, it instead returns nullopt. In this PR, I provide a base class implementation, that tries MaybeGetPoint, and otherwise just solves a simple optimization problem. I also added test cases for all derived classes. Once this PR lands, I'll go through and start adding more efficient implementations for certain subclasses.
+@hongkai-dai for feature review
EDIT: Sorry about the repeated updates. I had to mess with the tolerances a bit to get it to work on the default solvers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19804)
=> Implement MaybeGetFeasiblePoint for ConvexSet

tools/workspace/meshcat/repository.bzl
Meshcat has had a bugfix that allows glTF files to cast/receive shadows.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19817)
=> [workspace] Upgrade meshcat to latest commit

geometry/optimization/test/graph_of_convex_sets_test.cc
@Xining-Du reported that building drake with slightly different dependencies caused this test to fail -- 1e-6 was being rounded down to 0. 1e-5 is just as good for this test, but resolves that issue.
+@Xining-Du for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19818)
=> Adjust value in GraphOfConvexSets::GetGraphvizString test

bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc, solvers/cost.h
Also fixes SolveConvexRestriction to properly rewrite the convex costs into constriants (with slack variables) to be supported by the convex solvers. Previously it could call SNOPT instead of, e.g., Mosek.
+@tobiamarcucci for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19816)
=> Use GraphOfConvexSets::SolveConvexRestriction in rounding.

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h
BREAKING CHANGE.
The class is marked experimental, so some changes are made without deprecation.
- Deprecated the VertexId and EdgeId overloads. In particular, python users should get a useful message telling them to use the other overload.
- AddEdge, RemoveVertex, and RemoveEdge have changed (without deprecation) from taking `const Vertex&` to `Vertex*`. The previous constness was a lie. This change will not impact python users.
+@wrangelvid for feature review, and confirmation that we like the changes.
+@jwnimmer-tri for super platform review, and approval of my decisions and half-deprecation strategy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19825)
=> Removes VertexId and EdgeId overloads from GraphOfConvexSets API

examples/manipulation_station/BUILD.bazel, examples/manipulation_station/models/bin2.sdf, examples/manipulation_station/models/shelves.sdf, examples/manipulation_station/models/table_wide.sdf, geometry/benchmarking/BUILD.bazel, geometry/benchmarking/README.md, geometry/benchmarking/iris_in_configuration_space_benchmarks.cc, tools/workspace/drake_models/repository.bzl
This benchmark plants a flag before we start optimizing the IrisInConfigurationSpace runtimes.
+@wrangelvid for feature review (especially confirmation of the iris workflow).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19771)
=> Adds a benchmark for IrisInConfigurationSpace

geometry/optimization/cartesian_product.cc, geometry/optimization/cartesian_product.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/minkowski_sum.cc, geometry/optimization/minkowski_sum.h, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
As discussed in #19804, this provides more efficient subclass-specific implementations of DoMaybeGetFeasiblePoint. Towards #19717.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19824)
=> Subclass-Specific Implementations of DoMaybeGetFeasiblePoint

examples/manipulation_station/BUILD.bazel
Follow-up to #19771. Related to #19822.
The workflow for drake_models has changed. I should not have installed them.
Thanks @adeeb10abbas for the help!
Relevant slack thread: https://drakedevelopers.slack.com/archives/C2PMBJVAN/p1690124580155169
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19836)
=> Don't install drake_models from manipulation_station

multibody/tree/BUILD.bazel, multibody/tree/test/articulated_body_algorithm_test.cc
(This is a yak shave for #18442.)
In the near future Mobilizers won't be independently definable like Joints, they will instead be created already in depth-first order from the computed SpanningForestModel. MultibodyTree's articulated body algorithm test is the only one that defined its own Mobilizer and then used it like a Joint, so can't be easily converted to the new paradigm. 
This PR removes the bespoke Mobilizer, adds a massless body to provide the desired mobility, and models the system using only Joints (corresponding Mobilizers get created under the covers). Recalculated the ABIs, added some comments and a little cleanup.
+@amcastro-tri for feature review, please
- - - …
=> Modernize articulated body algorithm test

geometry/optimization/cspace_free_box.cc, geometry/optimization/cspace_free_polytope.cc, geometry/optimization/cspace_free_polytope_base.cc, geometry/optimization/cspace_free_polytope_base.h
When finding the separating planes in parallel, the lambda function that actually solves the sos should return plane_count.
Resolves #19843
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19845)
=> Fix an asan bug in CspaceFreePolytope.

geometry/optimization/spectrahedron.cc, geometry/optimization/test/spectrahedron_test.cc
This PR fixes a bug in the `DoAddPointInNonnegativeScalingConstraints ` function of the `Spectrahedron` class.
The bug is triggered when a binding has multiple constraints, i.e. `num_constraints` is higher than 1. In [line 131](https://github.com/RobotLocomotion/drake/blob/3fdd74cae58f672fe16b1f305e5a606f7f85c2e3/geometry/optimization/spectrahedron.cc#L131) (and [line 149](https://github.com/RobotLocomotion/drake/blob/3fdd74cae58f672fe16b1f305e5a606f7f85c2e3/geometry/optimization/spectrahedron.cc#L149), the row vector version of `AddLinearEqualityConstraint` (and `AddLinearConstraint`) is called due to a `double` passed as the argument to `b`. When there are multiple constraints in the binding, a matrix is wrongly passed as the row vector, resulting in an error.
See the added unit tests …
=> Fix bug in DoAddPointInNonnegativeScalingConstraints for Spectrahedron class

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py
Bind the overloaded constructor with minimum_distance_upper input argument.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19855)
=> Add python binding for MinimumDistanceConstraint.

tools/workspace/meshcat/package.BUILD.bazel
I believe these were used by `meshcat-python`, but are now unused.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19877)
=> [workspace] Remove vestigial meshcat files from the install

bindings/pydrake/manipulation/BUILD.bazel, bindings/pydrake/manipulation/kuka_iiwa.py, bindings/pydrake/manipulation/schunk_wsg.py, bindings/pydrake/manipulation/test/kuka_iiwa_test.py, bindings/pydrake/manipulation/test/schunk_wsg_test.py, bindings/pydrake/manipulation/test/util_test.py, bindings/pydrake/manipulation/util.py
Follow-up from #18973.
Manually tested:
```console
>>> from pydrake.all import *
>>> import pydrake.manipulation
>>> import pydrake.manipulation.kuka_iiwa
<stdin>:1: DrakeDeprecationWarning: Please import from the pydrake.manipulation module directly, instead of the deprecated pydrake.manipulation.kuka_iiwa submodule. The deprecated code will be removed from Drake on or after 2023-11-01.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19869)
=> [py manipulation] Deprecate three vestigial sub-modules

examples/multibody/strandbeest/BUILD.bazel, examples/multibody/strandbeest/model/LegAssembly.xacro, examples/multibody/strandbeest/model/LegPair.xacro, examples/multibody/strandbeest/model/Macros.xacro, examples/multibody/strandbeest/model/Strandbeest.xacro, examples/multibody/strandbeest/model/StrandbeestBushings.urdf.xacro, examples/multibody/strandbeest/model/StrandbeestConstraints.urdf.xacro, examples/multibody/strandbeest/run_with_motor.cc
Modifies the Strandbeest example to have an option to close loops with ball constraints rather than with bushing force elements. Currently runs only with SAP when using ball constraints.
This PR depends on #19780 and cannot be merged until it has been merged. The PR is split into two commits, the first containing all of the ball constraint parsing code from #19780 which can be ignored in this review. The second contains all of the relevant code for this review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19782)
=> [examples] Strandbeest with constraints

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/affine_subspace.cc, geometry/optimization/affine_subspace.h, geometry/optimization/test/affine_subspace_test.cc
These methods allow the comparison of two AffineSubspaces, to check if one is contained in the other, and to check if they're equivalent.
Once #19828 lands, I'll rebase and look for a reviewer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19850)
=> Implement AffineSubspace Methods to Check Containment and Equivalence

tools/workspace/default.bzl, tools/workspace/metadata.py, tools/workspace/rules_pkg/repository.bzl
This has been unused within Drake for a while now.
Note that in this case it's impractical to add build-system warnings to announce the deprecation.  The only place the deprecation will be announced is in the new source file comments and the release notes.
Closes #19781.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19872)
=> [workspace] Deprecate the rules_pkg external

multibody/fem/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/petsc/package.BUILD.bazel, tools/workspace/petsc/repository.bzl
We anticipate no longer using this soon, so it's time to start the clock for its removal.
Towards #17231 and #19882.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19890)
=> [workspace] Deprecate the petsc external

multibody/contact_solvers/BUILD.bazel, tools/workspace/BUILD.bazel, tools/workspace/conex/BUILD.bazel, tools/workspace/conex/patches/deprecation.patch, tools/workspace/conex_internal/BUILD.bazel, tools/workspace/conex_internal/package.BUILD.bazel, tools/workspace/conex_internal/patches/debug_macros.patch, tools/workspace/conex_internal/patches/no_eigen_io.patch, tools/workspace/conex_internal/repository.bzl, tools/workspace/default.bzl
We are already applying custom patches to our copy of conex, and will be applying more in the future (for C++ ODR).  As such, it needs to be badged as "internal".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19883)
=> [workspace] Deprecate the conex external

systems/sensors/BUILD.bazel, systems/sensors/optitrack_receiver.h, systems/sensors/optitrack_sender.h, tools/install/libdrake/drake-config.cmake.in, tools/install/libdrake/header_lint.bzl, tools/install/libdrake/test/header_dependency_test.py, tools/workspace/default.bzl, tools/workspace/optitrack_driver/optitrack_client, tools/workspace/optitrack_driver/repository.bzl
The following code will be removed in ~3 months:
- `drake::systems::sensors::OptitrackLcmFrameSender`
- `drake::systems::sensors::OptitrackReceiver`
- The `@optitrack_driver` external
- The installed `optitrack_client` program
Note that this does not add Bazel deprecation markers anywhere (doing so ends up being extra trouble for downstreams).
Closes #19600.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19866)
=> Deprecate all optitrack-related code for removal

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_constraint_jacobian.cc, multibody/contact_solvers/sap/sap_constraint_jacobian.h, multibody/contact_solvers/sap/sap_distance_constraint.cc, multibody/contact_solvers/sap/sap_distance_constraint.h, multibody/contact_solvers/sap/sap_holonomic_constraint.cc, multibody/contact_solvers/sap/sap_holonomic_constraint.h, multibody/contact_solvers/sap/test/sap_distance_constraint_test.cc, multibody/plant/sap_driver.cc
This PR makes `SapDistanceConstraint` a first class citizen of the constraints family and it also implements the reporting of forces.
The `SapDriver` is refactored to use this constraint. Notice that `sap_drive_test.cc` already provides test coverage for distance constraints.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19846)
=> Implements SapDistanceConstraint

tools/workspace/conex/repository.bzl, tools/workspace/tinyobjloader/repository.bzl
Downstream projects using Bazel to build Drake need to resolve the paths against Drake, not their own WORKSPACE.
Amends #19880 and #19883.
+@rpoyner-tri for both review please (high priority).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19904)
=> [workspace] Fully qualify absolute paths to patch files

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/affine_subspace.cc, geometry/optimization/affine_subspace.h, geometry/optimization/test/affine_subspace_test.cc
This PR implements new functionality for the AffineSubspace class:
- `AffineDimension()`, which returns the affine dimension of this AffineSubspace. For this class of sets, it's simply the number of columns in the basis.
- `Project(x)`, which computes the orthogonal projection of x onto the AffineSubspace
- `ToLocalCoordinates(x)`, which yields local coordinates of the projection onto AffineSubspace, with respect to its own basis (and zero point)
- `ToGlobalCoordinates(x)`, which lifts a point from local coordinate along AffineSubspace into the ambient space
Once #19828 lands, I'll rebase and look for a reviewer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/1985 …
=> Implement Change of Coordinates Functionality for AffineSubspace.

solvers/create_constraint.cc, solvers/test/create_constraint_test.cc
Previously, cases like
```
b = [0.12, inf]
ParseConstraint(x <= b)
```
would fail with
```
abort: Failure at solvers/create_constraint.cc:88 in ParseConstraint(): condition '!std::isnan(new_lb(i))' failed.
```
due to an `inf - inf` situation. Now we handle those cases properly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19903)
=> Fix ParseConstraint for cases with infs in rhs or lhs.

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/affine_subspace.cc, geometry/optimization/affine_subspace.h, geometry/optimization/test/affine_subspace_test.cc
Towards #19717 
(We're getting pretty close now!)
The procedure to compute the convex hull itself is implemented in `affine_subspace.cc`. It works by incrementally building a list of feasible line segments within the convex set that are mutually orthogonal, until no more can be found. This gives us the basis we need for the AffineSubspace, and any feasible point can serve as the translation.
Most of the additions in this PR are a comprehensive set of test cases, as we check that it can correctly produce the affine hull of all subclasses of ConvexSet, with a variety of special cases. Note that the tolerances for the default solvers are somewhat poor (especially for the intersection cases). When using commercial solvers (e.g. Gurobi), the performance is much better.
If you're up to it, …
=> Implement a ConvexSet Constructor to Compute the Affine Hull of another ConvexSet

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
- Simplifies AddPathLengthCost.
- Uses the new BezierCurve method to avoid Expression parsing in
AddVelocityBounds (and uses SparseMatrix).
- Avoids extraneous placeholder variable manipulation.
- Fixes some missing default names.
Note: this has #19867 as a first commit.  You can ignore those files in this review; I will merge that PR first.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19873)
=> Cleanup GcsTrajectoryOptimization Subgraph costs and constraints

doc/_pages/model_version_control.md, multibody/parsing/package_map.cc, multibody/parsing/package_map.h, multibody/parsing/test/package_map_remote_test.cc, tools/workspace/drake_models/package.BUILD.bazel
Closes #19822.
+@RussTedrake for platform review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19876)
=> [doc] Fix model_version_control instructions

multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/minimum_distance_constraint.cc, multibody/inverse_kinematics/minimum_distance_constraint.h, multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc, multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.h, multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc
We can now compute the distance through CollisionChecker, and then impose bounds on the minimum distance.
This is a step towards #18830 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19760)
=> Construct MinimumDistanceConstraint with a CollisionChecker.

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/conex_supernodal_solver.cc, multibody/contact_solvers/conex_supernodal_solver.h, tools/workspace/BUILD.bazel, tools/workspace/conex_internal/patches/eigen_namespace_pollution.patch, tools/workspace/conex_internal/patches/vendor.patch, tools/workspace/conex_internal/repository.bzl, tools/workspace/conex_internal/vendor.bzl
See also https://github.com/ToyotaResearchInstitute/conex/pull/6.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19892)
=> [workspace] Switch conex to use hidden namespace

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/test/multibody_plant_test.cc, multibody/plant/test/sap_driver_test.cc
Adds a parameter to `MultibodyPlant` that stores an "active" status for each constraint added to the plant. The active status is forwarded to `SapDriver` which in turn only adds "active" constraints to the `SapContactProblem` computed by `EvalContactProblemCache`. This allows a user to dynamically turn off/on constraints in a context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19884)
=> [multibody] Adds active/inactive parameter for SAP constraints.

tools/workspace/mypy_internal/patches/timeout.patch
Relates: https://github.com/RobotLocomotion/drake/issues/18119
[Slack discussion](https://drakedevelopers.slack.com/archives/C270MN28G/p1690974686728459).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19916)
=> Increase mypy timeout for CI machines to 720 secs

bindings/pydrake/geometry/geometry_py_render.cc, bindings/pydrake/geometry/test/render_test.py, geometry/render_gl/BUILD.bazel, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/render_engine_gl_params.h, geometry/render_gl/test/internal_render_engine_gl_test.cc, geometry/render_gl/test/render_engine_gl_params_test.cc
See #19906 for discussion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19912)
=> [geometry] Deprecate RenderEngineGl's default_label option

geometry/render_gltf_client/BUILD.bazel, multibody/parsing/BUILD.bazel, tools/workspace/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/picosha2_internal/BUILD.bazel, tools/workspace/picosha2_internal/package.BUILD.bazel, tools/workspace/picosha2_internal/patches/vendor.patch, tools/workspace/picosha2_internal/repository.bzl
Use vendored `picosha2_internal` instead (with an ODR-safe namespace).
Install the LICENSE file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19879)
=> [workspace] Deprecate the picosha2 external

bindings/pydrake/geometry/geometry_py_render.cc, bindings/pydrake/geometry/test/render_test.py, geometry/render_gltf_client/BUILD.bazel, geometry/render_gltf_client/internal_render_client.h, geometry/render_gltf_client/internal_render_engine_gltf_client.cc, geometry/render_gltf_client/render_engine_gltf_client_params.h, geometry/render_gltf_client/test/internal_render_client_test.cc, geometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc, geometry/render_gltf_client/test/render_engine_gltf_client_params_test.cc
Towards #19863.
For the glTF engine, I think the best path forward is to remove the problematic option, and therefore avoid serializing it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19906)
=> [geometry] Deprecate RenderEngineGltfClient's default_label option

tools/dynamic_analysis/bazel.rc
This resolves the kcov build errors after #19892.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19919)
=> [tools] For kcov, only skip sandboxing for test actions

geometry/optimization/test/affine_subspace_test.cc, geometry/optimization/test/vpolytope_test.cc
Testing out tolerances and diagnosing the problem discussed in #19917. If it's not a quick fix, then I'll ask buildcop to revert #19864.
@drake-jenkins-bot linux-focal-clang-bazel-experimental-mosek-release
Doing this all in a PR because I'm on 22.04 locally, and the existing tolerances work on my 22.04 machine with and without Mosek.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19918)
=> Fix AffineSubspace tolerance for focal/mosek.

bindings/pydrake/geometry/geometry_py_render.cc, bindings/pydrake/geometry/test/render_test.py, geometry/render_gltf_client/internal_render_engine_gltf_client.cc, geometry/render_vtk/BUILD.bazel, geometry/render_vtk/factory.h, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/render_engine_vtk_params.h, geometry/render_vtk/test/internal_render_engine_vtk_test.cc, geometry/render_vtk/test/render_engine_vtk_params_test.cc
See #19906 for discussion.
To avoid some merge conflict awkwardness, I plan to wait for that PR to merge first before we start reviewing this one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19911)
=> [geometry] Deprecate RenderEngineVtk's default_label option

bindings/pydrake/test/trajectories_test.py, common/trajectories/BUILD.bazel, common/trajectories/bezier_curve.cc, common/trajectories/bezier_curve.h, common/trajectories/test/bezier_curve_test.cc, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
To use less placeholder variables, and make use of the new BezierCurve::AsLinearInControlPoints() to avoid symbolic expressions.
+wrangelvid for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19907)
=> Cleanup GcsTrajectoryOptimization::EdgesBetweenSubgraphs

geometry/render_gltf_client/internal_render_engine_gltf_client.cc, geometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc, geometry/render_gltf_client/test/tri_tree.gltf
In the previous version, we'd omitted nodes that weren't mesh nodes with the intent of excluding camera nodes. However, this also omitted all "empty" root nodes (neither mesh nor camera). However, glTF defines hierarchies of nodes and it is perfectly reasonable to have an empty node at the root of a hierarchy of meshes. By omitting empty nodes from the set of root nodes, such hierarchies weren't getting properly posed.
This now considers all root nodes agnostically, regardless of type, just to be safe.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19896)
=> Fix to merging gltf in RenderEngineGltfClient

doc/_pages/release_playbook.md, tools/release_engineering/dev/README.md
The updated `push_release` scripts only require the release tag, we no longer need the date or SHA.
Also, move the verification step to after running the script to push docker images and S3 artifacts. That is the step that we are verifying.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19787)
=> [doc] Minor updates to Docker/Apt/S3 release documentation

tools/workspace/README.md
Now that there is a macOS pre-merge job, that should be good enough.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19931)
=> [doc] Monthly update PRs no longer require an extra macOS build

math/roll_pitch_yaw.h, multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc, multibody/tree/BUILD.bazel, multibody/tree/body.h, multibody/tree/joint.h, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/test/frames_test.cc, multibody/tree/test/free_rotating_body_plant.cc, multibody/tree/test/free_rotating_body_plant.h, multibody/tree/test/linear_bushing_roll_pitch_yaw_test.cc, multibody/tree/test/mobilizer_tester.h, multibody/tree/test/multibody_tree_creation_test.cc, multibody/tree/test/multibody_tree_test.cc, multibody/tree/test/planar_mobilizer_test.cc, multibody/tree/test/prismatic_mobilizer_test.cc, multibody/tree/test/quaternion_floating_mobilizer_test.cc, multibody/tree/test/revolute_mobilizer_test.cc, multibody/tree/test/screw_mobilizer_test.cc, multibody/tree/test/space_xyz_mobilizer_test.cc, multibody/tree/test/tree_from_mobilizers_test.cc, multibody/tree/test/universal_mobilizer_test.cc, multibody/tree/test/weld_mobilizer_test.cc
(This is another #18442 yak shave)
This PR modifies all the direct MultibodyTree tests to use AddJoint() rather than a raw AddMobilizer(). This will allow these tests to keep working after changes to graphing, where Mobilizers are created under the covers already in depth-first order so can't be treated like Joints.
The existing MultibodyGraph is moved from MultibodyPlant to MultibodyTree (to be called "MultibodyPlantImpl" later) but the functionality is unchanged.
+@amcastro-tri for feature review, please (no rush)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19841)
=> Modify MultibodyTree tests to use AddJoint() rather than AddMobilizer()

geometry/render_gl/BUILD.bazel, systems/sensors/BUILD.bazel, systems/sensors/camera_config.cc, systems/sensors/camera_config.h, systems/sensors/camera_config_functions.cc, systems/sensors/test/camera_config_functions_test.cc, systems/sensors/test/camera_config_test.cc
Previously, the nature of the render engine was given by a single string: naming the render engine class to use. It makes the `RenderEngine` impossible to configure.
This extends the `renderer_class` field to also take instances of the various `RenderEngine*Params` structs. Now the engines can be fully specified in yaml.
This also extends the set of renderer classes to include GltfCLient.
Updated the documentation on `CameraConfig::background` to clarify its scope in the new world.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19863)
=> CameraConfig can use RenderEngineParams

tools/workspace/gtest/patches/add_printers.patch, tools/workspace/gtest/repository.bzl
Towards #19865
The auto-update failed:
```
Error in fail: Error applying patch @//tools/workspace/gtest:patches/add_printers.patch:
patching file googletest/include/gtest/gtest-printers.h
Hunk #1 succeeded at 122 (offset 7 lines).
Hunk #2 FAILED at 309.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19932)
=> [workspace] Upgrade gtest to latest release v1.14.0

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_coupler_constraint.cc, multibody/contact_solvers/sap/sap_coupler_constraint.h, multibody/contact_solvers/sap/test/sap_coupler_constraint_test.cc, multibody/plant/sap_driver.cc, multibody/plant/test/sap_driver_joint_limits_test.cc
Makes `SapCouplerConstraint` a first class citizen of the sap constraints family. Refactors `SapDriver` to use the new constraint. Implements reporting forces for coupler constraints. 
Note: Coupler constraints are already tested in `compliant_contact_manager_test`, but these test should probably moved and refactored to match the testing strategy already adopted by `sap_driver_ball_constraints_test`, `sap_driver_distance_constraints_test`, etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19902)
=> [multibody] Implements SapCouplerConstraint

tools/workspace/drake_visualizer/package.BUILD.bazel
Avoid direct mention of `@vtk`; that name will soon be deprecated.
Towards https://github.com/RobotLocomotion/drake/pull/17962.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19944)
=> [workspace] Tidy up drake-visualizer comment

common/symbolic/latex.cc, common/symbolic/test/latex_test.cc
Also some nearby cleanups:
- Prefer "optional" over "bool success + output argument".
- Remove unused precision; ints never have decimals anyway.
- Prefer "isinf" over "== numeric_limits::infinity".
Amends #19941.
+@RussTedrake for feature review, please.
+@sherm1 for platform review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19951)
=> [symbolic] Fix integer overflow in ToLatex

examples/pr2/BUILD.bazel, manipulation/models/realsense2_description/BUILD.bazel
This will matter a lot more when the VTK build footprint grows.
Towards #19945.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19946)
=> [models] Run stl2obj using target config, not exec config

common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_read_archive.h, systems/sensors/test/camera_config_test.cc
This is required for the default `renderer_class` value in #19863 (the empty string) to round-trip correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19954)
=> [yaml] Fix round-trip bugs with variant<string,...>

geometry/optimization/affine_subspace.cc, geometry/optimization/affine_subspace.h, geometry/optimization/cartesian_product.cc, geometry/optimization/cartesian_product.h, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/intersection.cc, geometry/optimization/intersection.h, geometry/optimization/minkowski_sum.cc, geometry/optimization/minkowski_sum.h, geometry/optimization/point.cc, geometry/optimization/point.h, geometry/optimization/spectrahedron.cc, geometry/optimization/spectrahedron.h, geometry/optimization/test/intersection_test.cc, geometry/optimization/test/spectrahedron_test.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
This implements `DoIsBoundedShortcut()` for `ConvexSet`, and also modifies the implementations for `Intersection` and `Spectahedron` to use the generic base class method (after checking some edge cases).
Fixes #16663 (although potentially not in the most efficient way). +@russtedrake for feature review.
The implementation is slightly different than what I suggested in [this comment](https://github.com/RobotLocomotion/drake/issues/16663#issuecomment-1619017030) -- instead of maximizing and minimizing each dimension, I maximize the displacement between two feasible points along each dimension. This doubles the number of decision variables, but halves the number of optimization problems solved.
- - - …
=> Enable Boundedness Checks for Spectrahedra and Intersections with Unbounded Components

tools/workspace/cmake_configure_file.bzl, tools/workspace/cmake_configure_file.py
Towards #19945.
+@xuchenhan-tri for both reviews (off-schedule), please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19952)
=> [tools] Add cmake_configure_files (plural) macro

systems/sensors/camera_config.h, systems/sensors/test/camera_config_test.cc
Recently, the yaml parsing was fixed so that a variant with a string could be passed the empty string. This resolved a TODO in the CameraConfig documentation (allowing the set of documented examples to be expanded and the corresponding tests to cover it).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19957)
=> Update camera_config doc/test based on yaml fix

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/_inertia_fixer.py, bindings/pydrake/multibody/fix_inertia.py, bindings/pydrake/multibody/run_installed_fix_inertia.py.in, bindings/pydrake/multibody/test/Acrobot_unicode.urdf, bindings/pydrake/multibody/test/fix_inertia_test.py, examples/multibody/four_bar/BUILD.bazel, tools/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19731)
=> [pydrake/multibody] Add fix_inertia tool

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
Visual geometries do not have proximity roles. Filtering them for collision is a no-op as they are not considered in the proximity engine in the first place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19966)
=> Remove MbP::ExcludeCollisionsWithVisualGeometry

multibody/contact_solvers/BUILD.bazel, multibody/contact_solvers/schur_complement.cc, multibody/contact_solvers/schur_complement.h, multibody/contact_solvers/test/schur_complement_test.cc
The SchurComplement class computes the Schur complement of a given 3x3 block sparse symmetric matrix `A` based on the block indices to be eliminated. It also supports solving the linear system Az = b by leveraging the Cholesky factorization obtained in the process of computing the Schur complement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19924)
=> Add SchurComplement

geometry/optimization/affine_subspace.cc, geometry/optimization/affine_subspace.h, geometry/optimization/test/affine_subspace_test.cc
Towards #19717. This returns a basis of the orthogonal complement of the vector subspace describing an affine subspace. That is, all vectors in the span of this basis are orthogonal to all vectors in the affine subspace (if it is translated so as to pass through the origin).
+@hongkai-dai for feature review, please
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19975)
=> Implement a method to get the perpendicular basis for an AffineSubspace.

bindings/pydrake/examples/examples_py.cc
Enables downstream use of drake::sensors.
cc: @jwnimmer-tri for review, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19985)
=> [pydrake] Adds `pydrake.systems.sensors` import to the examples 

bindings/pydrake/common/value_py.cc
A better message for problems like #19985.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19984)
=> [py common] Improve error message for un-imported Value<> binding

examples/pr2/BUILD.bazel, manipulation/models/realsense2_description/BUILD.bazel
Genrules don't obey --run_under, so miss out on the suppression file.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19990)
=> Disable TSan on stl2obj

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_ball_constraint.cc, multibody/contact_solvers/sap/sap_ball_constraint.h, multibody/contact_solvers/sap/test/sap_ball_constraint_test.cc, multibody/plant/sap_driver.cc, multibody/plant/test/sap_driver_ball_constraints_test.cc
Makes SapBallConstraint a first class citizen of the sap constraints family. Refactors SapDriver to use the new constraint. Implements reporting forces for ball constraints.
Note: Ball constraints are already tested in `sap_driver_ball_constraints_test`, the new tests just verify that data flows through the new class correctly and expected spatial impulses are accumulated correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19940)
=> [multibody] Add SapBallConstraint

tools/workspace/drake_models/BUILD.bazel, tools/workspace/drake_models/test/parse_test.py
Required for #13942.  Related to #17061.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19986)
=> [workspace] Add drake_models regression test

bindings/pydrake/systems/framework_py_semantics.cc, manipulation/kinova_jaco/jaco_command_receiver.cc, manipulation/kuka_iiwa/iiwa_command_receiver.cc, systems/analysis/test/simulator_test.cc, systems/framework/BUILD.bazel, systems/framework/event.h, systems/framework/leaf_system.h, systems/framework/test/event_deprecated_test.cc, systems/framework/test/leaf_system_test.cc, systems/framework/test_utilities/initialization_test_system.h, systems/lcm/lcm_log_playback_system.cc, systems/lcm/lcm_publisher_system.cc, systems/lcm/lcm_publisher_system.h, systems/lcm/lcm_subscriber_system.cc, systems/primitives/vector_log_sink.cc, systems/sensors/image_writer.cc
Towards #19980.  This only updates the Event classes.  It does not yet propagate through Diagram, Simulator, etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19989)
=> [framework] Propagate EventStatus through Event handlers

geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/test/hpolyhedron_test.cc
One of the last two major steps to complete #19717. This allows the conversion of a VPolytope to an HPolyhedron even if the VPolytope is not full dimensional, or has insufficient points for QHull. (QHull always needs n+1 points in R^n.)
+@hongkai-dai for feature review, please
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19979)
=> Handle converting VPolytope to HPolyhedron if it is not full dimensional.

geometry/render_gltf_client/render_gltf_client_doxygen.h
I browsed through the documentation, and I think this is the only place mentioning `beta-testing` or `experimental`. I also built the Doxygen locally.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19997)
=> Remove beta testing tag from RenderEngineGltf doxygen

multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/sap_driver.cc, multibody/plant/sap_driver.h, multibody/plant/tamsi_driver.cc, multibody/plant/tamsi_driver.h, multibody/plant/test/discrete_update_manager_test.cc, multibody/plant/test/multibody_plant_reaction_forces_test.cc, multibody/plant/test/multibody_plant_scalar_conversion_test.cc, multibody/plant/test/multibody_plant_test.cc
This PR closes #19435 and #19068
It makes use of the infrastructure at the SAP solver level to report constraint forces within SapDriver so that we can compute the aggregate multibody forces due to constraints. With this information, we can reliably compute reaction forces including all terms in the discrete update.
With this PR we include discrete hydro forces along with every other solver constraint in the computation of reaction forces, effectively resolving #19068.
In summary
- Closes #18749
- Closes #19068
- Closes #19435
- Closes #13888
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19920)
=> Pipes constraints forces through and fixes reaction forces computation

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, common/text_logging.h, examples/multibody/cylinder_with_multicontact/test/populate_cylinder_plant_test.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/tree/spatial_inertia.cc, multibody/tree/test/spatial_inertia_test.cc, multibody/tree/test/unit_inertia_test.cc, multibody/tree/unit_inertia.cc, multibody/tree/unit_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19926)
=> Require unit vectors for UnitInertia functions.

geometry/benchmarking/render_benchmark.cc, geometry/render_vtk/BUILD.bazel, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/internal_render_engine_vtk.h, geometry/render_vtk/render_engine_vtk_params.h, geometry/render_vtk/test/internal_render_engine_vtk_test.cc, geometry/render_vtk/test/render_engine_vtk_params_test.cc
This allows lights to be configured in `RenderEngineVtk` like they are in `RenderEngineGl`.
Calling the `SetDefaultLightPosition()` now spews a warning and does little else. `render_benchmark.cc` was the only code in Drake that exercised this API. It is not part of `RenderEngine`'s public API, just part of its protected API. This is a precursor to removing it.
The light tests are basically copied from `RenderEngineGl`'s tests (with small tweaks to make them applicable to VTK).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19948)
=> Add lights to RenderEngineVtkParams

bindings/pydrake/systems/sensors_py.cc, systems/sensors/BUILD.bazel, systems/sensors/pixel_types.cc, systems/sensors/pixel_types.h, systems/sensors/test/pixel_types_test.cc
The `PixelScalar` is useful to denote image scalar types as values, in contrast with the `ChannelType` typedef which is only usable for template programming.
Both of these features will be used soon as part of a new [consolidated image I/O feature](https://github.com/jwnimmer-tri/drake/commits/image-io).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20015)
=> [sensors] Add to_string and PixelScalar

geometry/render_gltf_client/BUILD.bazel, geometry/render_gltf_client/test/internal_render_client_test.cc, geometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc, systems/sensors/BUILD.bazel, systems/sensors/test/image_writer_free_functions_test.cc, systems/sensors/test/image_writer_test.cc, systems/sensors/test_utilities/BUILD.bazel, systems/sensors/test_utilities/image_compare.cc, systems/sensors/test_utilities/image_compare.h
Split `image_writer_test` into separate files for the free functions versus the system logic. (We'll soon be deprecating the free functions, in lieu of a [more full-featured replacement class](https://github.com/jwnimmer-tri/drake/commits/image-io).)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20017)
=> [sensors] Add image_compare test utility

geometry/proximity/BUILD.bazel, geometry/proximity/vtk_to_volume_mesh.cc, geometry/render_gl/BUILD.bazel, geometry/render_gl/internal_texture_library.cc, geometry/render_gl/test/internal_render_engine_gl_test.cc, geometry/render_gltf_client/BUILD.bazel, geometry/render_gltf_client/internal_render_client.cc, geometry/render_gltf_client/internal_render_engine_gltf_client.cc, geometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc, geometry/render_gltf_client/test/server_vtk_backend.cc, geometry/render_vtk/BUILD.bazel, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/internal_render_engine_vtk.h, geometry/render_vtk/internal_render_engine_vtk_base.cc, geometry/render_vtk/internal_render_engine_vtk_base.h, geometry/render_vtk/internal_vtk_util.cc, geometry/render_vtk/internal_vtk_util.h, geometry/render_vtk/test/internal_render_engine_vtk_test.cc, geometry/render_vtk/test/internal_vtk_util_test.cc, manipulation/util/BUILD.bazel, manipulation/util/stl2obj.cc, systems/sensors/BUILD.bazel, systems/sensors/image_writer.cc, systems/sensors/lcm_image_array_to_images.cc, systems/sensors/test_utilities/BUILD.bazel, systems/sensors/test_utilities/image_compare.cc, tools/workspace/vtk/repository.bzl
Towards #19945 and #16502.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20024)
=> [vtk] Unify include spelling, add comments, fix deps

multibody/plant/sap_driver.cc, multibody/plant/tamsi_driver.cc
We should use the EvalContactKinematics in SapDriver::AddContactConstraint as the value may have been pre-computed elsewhere.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19970)
=> Prefer Eval over Calc in SapDriver

setup/mac/source_distribution/Brewfile, setup/mac/source_distribution/Brewfile-test-only, setup/mac/source_distribution/install_prereqs.sh, setup/ubuntu/source_distribution/packages-focal-test-only.txt, setup/ubuntu/source_distribution/packages-focal.txt, setup/ubuntu/source_distribution/packages-jammy-test-only.txt, setup/ubuntu/source_distribution/packages-jammy.txt, tools/lint/BUILD.bazel, tools/vector_gen/BUILD.bazel, tools/vector_gen/lcm_vector_gen.py, tools/vector_gen/test/goal/lcmt_sample_t.lcm, tools/vector_gen/test/goal/sample.cc, tools/vector_gen/test/goal/sample.h, tools/vector_gen/test/sample_named_vector.yaml, tools/vector_gen/vector_gen.bzl, tools/wheel/image/packages-focal
This should allow users to rebuild from source with fewer headaches.
On macOS, it removes 1 of 2 remaining build-time dependencies on the custom RobotLocomotion homebrew tap. We anticipate dropping the other item (VTK) from the custom tap soon, as well.
On Ubuntu, it avoids a hard-coded clang-format version. This should be more portable for users who build on a non-Ubuntu distribution.
Developers who want to run Drake's full test suite will still need this dependency; this is only a change for *users* who build from source.
With this change, the build-time vector_gen can no longer autoformat its generated code. With a few minor edits to the tool, the output still looks passable without the autoformat.
- - - …
=> [setup] Change clang-format to a testonly dependency

bindings/pydrake/geometry/BUILD.bazel, bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/cspace_free_polytope.h, geometry/optimization/cspace_free_structs.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19574)
=> Cspace free polytope bindings non dev

systems/sensors/image.h, systems/sensors/image_to_lcm_image_array_t.cc, systems/sensors/image_writer.cc, systems/sensors/pixel_types.cc, systems/sensors/pixel_types.h
Reverts #8055.
Their only effect is to clutter up our switch-case statements with an extra condition that always throws an exception.
Eigen should be a sufficient alternative for users who actually need a two-dimensional array of expressions. The only advantages of `Image<>` over `Array<>` are semantic labeling of the pixels (color, depth, label) and multi-channel pixels (rgb) -- neither of which apply here anyway.  (The `u,v` vs `x,y` indexing is another difference, but not too difficult to manage.)
This came up during #19945 when trying to improved our image reading and writing infrastructure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20023)
=> [sensors] Deprecate symbolic expression images

geometry/optimization/hpolyhedron.cc, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
The last steps to complete #19717. This allows the conversion of a HPolyhedron to a VPolytope even if the HPolyhedron is not full dimensional.
+@hongkai-dai for feature review, please
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20001)
=>  Handle converting HPolyhedron to VPolytope if it is not full dimensional.

geometry/benchmarking/render_benchmark_doxygen.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20039)
=> [geometry] Fix a benchmarking doc typo

multibody/plant/multibody_plant.cc, multibody/plant/test/multibody_plant_hydroelastic_test.cc
This was most certainly a bug. I am still scratching my head figuring out how to write a test to demonstrate the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20022)
=> [multibody] Fix typo in CalcHydroelasticContactForces

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/parser.h, multibody/parsing/test/parser_test.cc
This patch deprecates the legacy spelling AddAllModelsFromFile() and the singular method AddModelFromFile(), and reorganizes tests around those deprecations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19978)
=> [parsing] Deprecate some parser methods

geometry/render_gltf_client/BUILD.bazel, geometry/render_gltf_client/internal_render_client.cc, systems/sensors/BUILD.bazel, systems/sensors/image_file_format.cc, systems/sensors/image_file_format.h, systems/sensors/image_writer.cc, systems/sensors/lcm_image_array_to_images.cc, systems/sensors/test/image_file_format_test.cc, systems/sensors/test/vtk_image_reader_writer_test.cc, systems/sensors/vtk_image_reader_writer.cc, systems/sensors/vtk_image_reader_writer.h
Towards https://github.com/RobotLocomotion/drake/pull/19945 and https://github.com/RobotLocomotion/drake/issues/16502.  In particular, the new unit test here will serve as a backstop against regressions in the reader/writer code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20026)
=> [sensors] Encapsulate VTK image readers and writers

bindings/pydrake/systems/lcm_py.cc, bindings/pydrake/systems/test/lcm_test.py
+@jwnimmer-tri for both reviews, please.  This is the double-inheritance goo that you wanted to check carefully.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20074)
=> Add bindings for LcmInterfaceSystem methods

bindings/pydrake/systems/_lcm_extra.py, bindings/pydrake/systems/lcm_py.cc, bindings/pydrake/systems/test/lcm_test.py, systems/lcm/BUILD.bazel, systems/lcm/lcm_subscriber_system.cc, systems/lcm/lcm_subscriber_system.h, systems/lcm/test/lcm_subscriber_system_test.cc
Also supports a new opt-in ability to wait for at least one message to be received during initialization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20072)
=> Adds an initialization event to LcmSubscriberSystem

geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
GraphOfConvexSets::Edge::xu() returns the placeholder variables for the vertices. This can be potentially confusing when one is inspecting the MathematicalProgramResult for a solution where the convex relaxation is loose. I've captured the confusion in an example, and tried to improve the most relevant docstring.
+@iamsavva for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20042)
=> Adds a test and an improved docstring for getting GCS Edge solutions.

.bazeliskrc, CMakeLists.txt, cmake/modules/FindBazel.cmake, setup/mac/source_distribution/install_prereqs_user_environment.sh, setup/ubuntu/source_distribution/install_prereqs_user_environment.sh, third_party/BUILD.bazel, third_party/com_github_bazelbuild_bazelisk/LICENSE, third_party/com_github_bazelbuild_bazelisk/bazelisk.py, tools/wheel/image/build-drake.sh, tools/wheel/image/provision-base.sh, tools/workspace/bazelisk/BUILD.bazel, tools/workspace/bazelisk/package.BUILD.bazel, tools/workspace/bazelisk/patches/pull494.patch, tools/workspace/bazelisk/repository.bzl, tools/workspace/bazelisk/test/lint_test.py, tools/workspace/default.bzl
Closes #19923.
See also https://github.com/bazelbuild/bazelisk/pull/494.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20064)
=> [cmake] Use Bazelisk to download Bazel

systems/sensors/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/vtk_internal/BUILD.bazel, tools/workspace/vtk_internal/package.BUILD.bazel, tools/workspace/vtk_internal/patches/common_core_version.patch, tools/workspace/vtk_internal/patches/common_core_vs_data_model_cycle.patch, tools/workspace/vtk_internal/patches/common_core_warnings.patch, tools/workspace/vtk_internal/patches/common_data_model_warnings.patch, tools/workspace/vtk_internal/patches/io_image_formats.patch, tools/workspace/vtk_internal/repository.bzl, tools/workspace/vtk_internal/rules.bzl, tools/workspace/vtk_internal/settings.bzl
Towards #19945 and #16502.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20068)
=> [workspace] Add vtk_internal build from source

manipulation/util/BUILD.bazel, tools/workspace/vtk_internal/settings.bzl
Towards #19945 and #16502.
Requires #20068.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20084)
=> [tools] Switch stl2obj to use VTK built from source

systems/sensors/camera_config_functions.cc, systems/sensors/test/camera_config_functions_test.cc
When the renderer_class is empty, no engine type cross-checks should be performed.
Amends #19863.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20087)
=> [sensors] Fix exception from empty renderer_class config

tools/install/install.bzl, tools/skylark/drake_py.bzl
Fix drake_py_unittest to actually obey num_threads.
Fix drake_py_test to actually obey allow_network.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20092)
=> [tools] Fix drake_py_unittest and drake_py_test option handling.

tools/workspace/vtk_internal/patches/vtksys_hidden.patch, tools/workspace/vtk_internal/repository.bzl, tools/workspace/vtk_internal/settings.bzl
Towards #19945.
Amends #20068.
See also #19965.
FYI In local testing (of the full PR 19945), this is the command I used to look for problems:
```console
nm -a bazel-bin/tools/install/libdrake/libdrake.so |
grep vtksys |
sed -e 's#^................ ##' |
grep -E '[A-Z] ' |
sort -u |
less
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20097)
=> [workspace] Use hidden symbols for our build of vtksys

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py
When the user accidentally forgets the `return` statement, the error message was very poor.
Closes #20032.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20106)
=> [py systems] Improve error message for missing witness functions

lcm/drake_lcm.cc
See also #20115.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20116)
=> [lcm] Eschew LCM C++ API (use C instead)

lcm/drake_lcm.cc, lcm/drake_lcm.h, lcm/test/drake_lcm_test.cc, lcm/test/drake_lcm_thread_test.cc
It's not sufficiently ABI-stable to offer as Drake ABI, and because its LGPL we are required to expose its ABI if we use it.
This function is used nowhere in Drake or Anzu currently.  (It was last used in Anzu in May, 2022.)
See also #20116.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20115)
=> [lcm] Deprecate direct access to the native LCM library

doc/_pages/documentation_instructions.md, doc/doxygen_cxx/Doxyfile_CXX.in, doc/doxygen_cxx/build.py, geometry/scene_graph.h, tools/workspace/pybind11/mkdoc_comment.py, tools/workspace/pybind11/test/mkdoc_comment_test.py
For my sense of style, this presentation layout is still a bit rough, but it seems like enough of an improvement to land now, and let others improve upon over time.  At least this solves the tricky build system parts; the rest is just html & css fu.
---
C++ sample:
---
Python sample:
---
Towards #12591.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20083)
=> [doc] Improve code block formatting in API docs

math/BUILD.bazel, math/discrete_algebraic_riccati_equation.cc, math/discrete_algebraic_riccati_equation.h, math/test/discrete_algebraic_riccati_equation_test.cc, systems/primitives/linear_system_internal.cc
Implements the SDA algorithm on page 5 of the following paper:
E. K.-W. Chu, H.-Y. Fan, W.-W. Lin & C.-S. Wang "Structure-Preserving
Algorithms for Periodic Discrete-Time Algebraic Riccati Equations",
International Journal of Control, 77:8, 767-788, 2004.
DOI: 10.1080/00207170410001714988
Here's Google Benchmark results for the old DARE solver using https://github.com/calcmogul/DAREBench/:
```
Running ./build/DAREBench
Run on (8 X 3595.49 MHz CPU s)
CPU Caches:
L1 Data 32 KiB (x4)
L1 Instruction 32 KiB (x4)
L2 Unified 256 KiB (x4)
L3 Unified 6144 KiB (x1)
Load Average: 1.59, 4.28, 3.08
-------------------------------------------------------------------------------
Benchmark                                     Time             CPU   Iterations …
```
=> [math] Rewrite the DARE solver to use a faster algorithm

multibody/fem/fem_model.cc, multibody/fem/fem_model.h, multibody/fem/fem_solver.cc, multibody/fem/fem_solver.h, multibody/fem/test/fem_solver_test.cc, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/test/deformable_driver_contact_test.cc
FemSolver stores the scratch data and the solution as data members to ensure compatibility of with the FEM model being solved for.
As a result, `FemSolver::AdvanceOneTimeStep()` only takes the previous FEM state and the set of non-participating vertices as input and FemSolver offers a `next_state_and_schur_complement()` function to inspect the solution.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20086)
=> DeformableDriver uses the new FemSolver

lcm/drake_lcm.cc, lcm/test/drake_lcm_test.cc
Previously, when multicast was disabled all operations printed a warning to the console and then did nothing.  The prior commit changed that to throw an error instead, which was breaking.
Instead, let LCM still print the console warning but then instead of throwing provide an inert DrakeLcm instead.
Closes #20136.
Amends #20116.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20137)
=> [lcm] Hotfix for "Eschew LCM C++ API"

bindings/pydrake/visualization/test/model_visualizer_test.py
Closes #19998.
I cannot reproduce the problem locally.  Hopefully it's the kind of thing that will be solved by a bit more sleeping.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20129)
=> [py visualization] De-flake TestModelVisualizer.test_reload

examples/rod2d/rod2d.cc, examples/rod2d/rod2d.h, manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc, manipulation/schunk_wsg/schunk_wsg_trajectory_generator.h, planning/trajectory_optimization/test/direct_transcription_test.cc, systems/controllers/linear_model_predictive_controller.cc, systems/controllers/linear_model_predictive_controller.h, systems/controllers/test/linear_model_predictive_controller_test.cc, systems/framework/test/diagram_test.cc, systems/framework/test/system_symbolic_inspector_test.cc, systems/framework/test_utilities/initialization_test_system.h, systems/primitives/discrete_derivative.cc, systems/primitives/discrete_derivative.h, systems/primitives/symbolic_vector_system.cc, systems/primitives/symbolic_vector_system.h, systems/primitives/test/linear_system_test.cc
Overriding the event dispatching will soon be deprecated.
Towards #13799.
For testonly systems, I've only made the minimal adjustments.  For systems available to users, I tried to ensure the behavior remains the same by declaring both periodic and forced triggers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20114)
=> Update primitives and examples to use modern event API

bindings/pydrake/planning/BUILD.bazel, bindings/pydrake/planning/planning_py_collision_checker.cc, bindings/pydrake/planning/planning_py_collision_checker_interface_types.cc, bindings/pydrake/planning/test/collision_checker_test.py, planning/BUILD.bazel, planning/collision_avoidance.cc, planning/collision_avoidance.h, planning/collision_checker.cc, planning/collision_checker.h, planning/collision_checker_params.h, planning/test/collision_avoidance_test.cc, planning/test/collision_checker_test.cc, planning/test_utilities/collision_checker_abstract_test_suite.cc, planning/test_utilities/collision_checker_abstract_test_suite.h, planning/visibility_graph.cc
Changes:
- Removes uses of CRU parallelization macros to decrease Drake+anzu+CRU coupling
- Provides `Parallelism` control to all parallel/optionally-parallelized `CollisionChecker` methods (many of which previously took just a `bool parallelize`)
- Provides an `implicit_context_parallelism` member of `CollisionCheckerParams` to optionally specify a different number of implicit contexts (e.g. to effectively disable implicit context parallelism if unnecessary), resolves #18982 
- Provides optional `context_number` parameters to all `CollisionChecker` implicit context methods to support (among other uses) non-OpenMP parallel for loop implementations
+@jwnimmer-tri for feature review, thanks!
fyi @rpoyner-tri @sadraddini
- - - …
=> [planning] CollisionChecker parallelism updates

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/test/graph_of_convex_sets_test.cc
Resolves #20113.
The ultimate solution will be to write the costs into the MathematicalProgramResult when solving the convex restriction. This is already listed with a TODO in SolveConvexRestriction; but will require some effort. For now, we shouldn't throw errors; we simply don't offer the cost display for that case.
+@richardrl for feature review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20118)
=> GraphOfConvexSets: don't try to display costs for convex restriction solutions

tools/wheel/image/dependencies/projects.cmake
The original archive link has a different md5sum now.  We have mirrored the original.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20142)
=> [wheel] Update xz url to newly mirrored 5.2.5

geometry/render_gl/test/internal_render_engine_gl_test.cc, geometry/render_vtk/BUILD.bazel, geometry/render_vtk/test/internal_render_engine_vtk_test.cc
It's nice to be able to debug `show_window` without rebuilding.  This came up during #19945.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20143)
=> [render_vtk] Add gflag for show_window

tools/workspace/voxelized_geometry_tools/repository.bzl
Changes in VGT:
- Workaround for what appears to be a broken `clEnqueueFillBuffer` on macOS (resolves #20133)
- Fixes for OpenCL kernel double->float conversions, which are now warnings using the latest Intel OpenCL (specifically necessary to support ADL-N and ARC GPUs)
- Updates to buffer memory flags and kernel build flags
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20163)
=> Bump VGT with workaround for macOS OpenCL and fixes for Intel OpenCL

bindings/pydrake/symbolic_py.cc, bindings/pydrake/test/symbolic_test.py, common/symbolic/BUILD.bazel, common/symbolic/polynomial.cc, common/symbolic/polynomial.h, common/symbolic/test/polynomial_test.cc
For finding the roots of univariate polynomials.
Towards #20159.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20161)
=> Implements symbolic::Polynomial::Roots()

tools/dynamic_analysis/bazel.rc
Switch ASan back to using ld.gold and fission because the non-fission builds are way too big.
This means that the buggy [console spam from ld.gold](https://github.com/RobotLocomotion/drake/pull/13650#issuecomment-656316040) comes back (see [binutils bug tracker](https://sourceware.org/bugzilla/show_bug.cgi?id=25975)), which means we need to globally disable all console warnings in ASan builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20156)
=> [tools] Switch ASan back to using ld.gold and fission

systems/controllers/inverse_dynamics_controller.cc, systems/controllers/test/inverse_dynamics_controller_test.cc
Amends #20079 so that `get_output_port()` still works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20167)
=> [controllers] Add InverseDynamicsController deprecation annotation

math/rotation_matrix.h, math/test/rotation_matrix_test.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_urdf_parser_test.cc
Closes #20095 
Add RotationMatrix::MakeClosestRotationToIdentityFromUnitZ
In addition, use this new function when parsing planar joint in URDF. Even though URDF does not put requirement on x and y axes for planar joint, we should choose a canonical frame that's not surprising. In particular if Mz is chosen to be Bz, then we should choose M to be equal to B.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20107)
=> [parsing] URDF planar joint uses canonical frame

bindings/pydrake/visualization/_meldis.py, bindings/pydrake/visualization/test/meldis_test.py, geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer.h, geometry/test/meshcat_visualizer_test.cc, tools/workspace/meshcat/repository.bzl, visualization/inertia_visualizer.cc
Previously, meshcat visualizer was trying to modulate the opacity of geometries by storing the underlying color/opacity and subsequently setting it by setting the "color" property. This works for primtive shapes but breaks down for complex geometries (e.g., obj with mtl files and glTF files).
Instead, MeshcatVisualizer makes use of the new affordances in meshcat. With meshcat, one can set the "opacity" or "modulated_opacity" property. As with setting the "color" property, meshcat will update all of the materials in a tree. Meshcat and meldis now exploit this to reduce the number of meshcat calls (making a single API invocation for the entire path tree that the instance owns).
Resolves #19820
- - - …
=> [vis] MeshcatVisualizer and Meldis rely on meshcat APIs to handle alpha sliders

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/analysis_test.py, systems/analysis/BUILD.bazel, systems/analysis/simulator.cc, systems/analysis/simulator.h, systems/analysis/simulator_python_internal.h, systems/analysis/test/simulator_python_internal_test.cc, tools/skylark/pybind.bzl
Closes #20053.
(Aside: This will probably make a bunch of Anzu simulations happier in CI.  As it stands, IIRC out CI has trouble killing simulator jobs and tends to time them out rather then interrupt them.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20130)
=> [py systems] Simulator.AdvanceTo is interruptible by default

geometry/render_gltf_client/internal_render_engine_gltf_client.h, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/internal_render_engine_vtk.h, geometry/render_vtk/internal_vtk_util.cc, geometry/render_vtk/internal_vtk_util.h, geometry/render_vtk/test/internal_render_engine_vtk_test.cc, geometry/render_vtk/test/internal_vtk_util_test.cc
vtkAssembly is a poorly supported class in VTK. It has already been shown to be ignored when exporting to glTF. It has also been shown to cause textures from glTF files to render upside down. Therefore, it causes more troubles than it solves.
RenderEngineVtk now provides its own assembly-like struct: a "prop", comprised of one or more "parts".
The glTF import, pose update, and cloning has been updated to reflect the change from assembly to "prop" and all references to the old assemblies have been removed (except for "here-be-dragons" warnings).
Furthermore, we evolve the internal VTK utilities to produce a VTK-compatible *general* transform instead of just a rigid transform.
The existing tests should serve as sufficient proof against regression.
(Incidental clean up in …
=> Remove vtkAssembly from RenderEngineVtk

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/plant/BUILD.bazel, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/sap_driver.h, multibody/plant/test/actuated_models_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/plant/test/sap_driver_pd_controller_constraints_test.cc, multibody/tree/joint_actuator.cc, multibody/tree/joint_actuator.h, multibody/tree/test/joint_actuator_test.cc
New feature to define PD controlled actuators (with effort limits).
The model is integrated in SAP for stable simulation even with high gains.
Closes #19067
Below is a screenshot of the new MbP docs in this PR on PD controlled actuators:
cc'ing @joemasterjohn and @JoseBarreiros-TRI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20111)
=> Actuators with PD control implicitly integrated with SAP

common/symbolic/expression/BUILD.bazel, common/symbolic/expression/environment.cc, common/symbolic/expression/environment.h, common/symbolic/expression/expression.h, common/symbolic/expression/expression_cell.cc, common/symbolic/expression/expression_cell.h, common/symbolic/expression/formula.h, common/symbolic/expression/formula_cell.cc, common/symbolic/expression/formula_cell.h, common/symbolic/expression/test/environment_test.cc, common/symbolic/expression/test/variable_test.cc, common/symbolic/expression/variable.cc, common/symbolic/expression/variable.h, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
Remove various restriction on using the default Variable in an Expression, Environment, Formula, etc.
This will be useful for univariate monomials and polynomials, where the variable name doesn't matter but shouldn't be empty.
This is also probably a tiny speed-up to not hit the heap during the default constructor (to allocate an empty reference-counted string).
Towards #7576 and #20159.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20164)
=> [symbolic] Give the default Variable a name

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/cspace_free_polytope_base.h
The lack of a `repr()` leads to [hex spam](https://drake.mit.edu/pydrake/pydrake.geometry.optimization.html#pydrake.geometry.optimization.CspaceFreePolytope) in the website API reference.
Amends #19574.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20181)
=> [py optimization] Add missing repr and docs for polytope options

tutorials/dynamical_systems.ipynb
As of matplotlib 3.8.0, `stem(..., use_line_collection=False)` is no longer supported ([reference here](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#stem-use-line-collection-false)).
On 9/15, Mac Unprovisioned Nightlies upgraded to Matplotlib 3.8.0 and the `//tutorials:py/dynamical_systems_test` began to fail as it is using the now unsupported argument:
- [mac-arm-monterey-unprovisioned-clang-bazel-nightly-release](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-arm-monterey-unprovisioned-clang-bazel-nightly-release/352/)
- [mac-arm-ventura-unprovisioned-clang-bazel-nightly-release](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-arm-ventura-unprovisioned-clang-bazel-nightly-release/124/)
- …
=>  [tutorials] Remove unsupported matplotlib argument

doc/_pages/pip.md
Relates: #18792
To review, please run the following checks:
- Checkout this PR locally and confirm that running `bazel run //doc:pages -- --serve` and viewing `http://127.0.0.1:8000/pip.html#nightly-releases` in your browser reads as desired.
- Confirm that (for whatever your os is) the `pip install --extra-index-url` commands give you (a) a specific date in the past and (b) the latest nightly using `<0.1`.
CC @RussTedrake
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20189)
=> [doc] Advertise PEP 503 nightly pip wheel Index

systems/controllers/pid_controller.cc, systems/controllers/pid_controller.h, systems/controllers/test/pid_controller_test.cc
The custom code was useful when PidController used to be a Diagram, but when it was refactored to be a LeafSystem in #6326 we forgot to undo it. As we improve our default Graphviz output for systems, the custom code becomes actively harmful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20196)
=> [controllers] Remove PidController's special Graphviz

solvers/mosek_solver.h
The numbered list is ignored in pydrake doxygen.
Now the rendering looks like this in pydrake doc
and in C++ doxygen
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20199)
=> Use bullet point rather than number list in MosekSolver doxygen.

geometry/optimization/test/hpolyhedron_test.cc
Relax the tolerance for finding redundant faces.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20201)
=> Fix HPolyhedronTest.

systems/framework/system.cc, systems/framework/system.h, systems/framework/system_base.cc, systems/framework/system_base.h, systems/framework/test/system_base_test.cc, systems/framework/test/system_test.cc
Nothing about this function needs scalar-type templating.
While we're here, fix it to use `fmt` (instead of `<iomanip>` :scream_cat:) and `uintptr_t`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20200)
=> [framework] Move GetMemoryObjectName to SystemBase

examples/hardware_sim/BUILD.bazel, examples/hardware_sim/hardware_sim.cc, examples/hardware_sim/hardware_sim.py, examples/hardware_sim/test/hardware_sim_test_common.py
In support of #20182, and also other future work to improve our Graphviz output.
For example:
```
bazel run //examples/hardware_sim:demo_cc -- \
--scenario_text='{simulation_duration: 0}' \
--graphviz=$(pwd)/example.dot &&
dot -Tpng example.dot > example.png
```
I looked into adding some text to the `README.md` to demonstrate this option, but it seemed like it might be more confusing than helpful.  If anything, I want to make our graphviz output better before we advertise this too much.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20198)
=> [hardware_sim] Add option to output Graphviz

geometry/render_vtk/BUILD.bazel
Towards #19424.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20205)
=> [render_vtk] Nerf the macOS arm64 tests even harder

bindings/pydrake/systems/framework_py_systems.cc
Something apparently to do with the templated call to operator() causes clang-format to no longer format the SystemBase code, but still to declare success even though the indentation is all wrong.
Work around this by segregating the problamtic code into its own little stanza.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20208)
=> [py systems] Fix clang-format to avoid "mission accomplished"

multibody/plant/multibody_plant.cc, multibody/plant/test/actuated_models_test.cc
This was already identified in this [Slack conversation](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1695068480697379) by @jwnimmer-tri. 
It turns out the problem shows quickly as users start excercising the implicit PD controllers recently merged, when their models do not connect feed-forward terms (expecing these ports to evaluate to zero by default).
cc'ing @JoseBarreiros-TRI 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20215)
=> Disconnected actuation input ports evaluate to zero actuation

doc/_release-notes/v1.21.0.md, tools/workspace/vtk_internal/package.BUILD.bazel, tools/workspace/vtk_internal/rules.bzl
Here's the improved error message:
```console
jeremynimmer@macsim-m1-1 drake % bazel build --force_pic @vtk_internal//:all
ERROR: /.../external/vtk_internal/BUILD.bazel:21:11: in cc_library rule @vtk_internal//:_on_macos_you_must_not_have_forcepic_in_your_bazelrc_file_see_drake_issue_20217: 
Traceback (most recent call last):
File "/virtual_builtins_bzl/common/cc/cc_library.bzl", line 32, column 57, in _cc_library_impl
Error in configure_features: PIC compilation is requested but the toolchain does not support it (feature named 'supports_pic' is not enabled)
ERROR: /.../external/vtk_internal/BUILD.bazel:21:11: Analysis of target '@vtk_internal//:_on_macos_you_must_not_have_forcepic_in_your_bazelrc_file_see_drake_issue_20217' failed
WARNING: errors encountered while analyzing target …
```
=> [workspace] Fail-fast in miscofigured VTK build on macOS

bindings/pydrake/manipulation/test/kuka_iiwa_test.py, manipulation/kuka_iiwa/BUILD.bazel, manipulation/kuka_iiwa/build_iiwa_control.cc, manipulation/kuka_iiwa/build_iiwa_control.h, manipulation/kuka_iiwa/sim_iiwa_driver.cc, manipulation/kuka_iiwa/sim_iiwa_driver.h, manipulation/kuka_iiwa/test/build_iiwa_control_test.cc, manipulation/kuka_iiwa/test/sim_iiwa_driver_test.cc
Towards #20055.  See the discussion here: https://github.com/RobotLocomotion/drake/issues/20055#issuecomment-1716196721.
For a visual representation of the change, we can use the new option #20198 to output Graphviz from the `hardware_sim` example:
Before:
After (r2):
After (r3):
(FYI These images also contain some styling improvements that are not yet on `master`.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20182)
=> [kuka_iiwa] Factor non-LCM iiwa driver into a separate Diagram

bindings/pydrake/geometry/test/visualizers_test.py, geometry/meshcat.cc, geometry/test/meshcat_test.cc
It's not clear to me why or whether this matters, but we have [anecdotal reports](https://stackoverflow.com/questions/77137333/meshcat-port-forwarding-with-vs-code) that it might.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20237)
=> [meshcat] Set Content-Type for HTML pages

systems/primitives/shared_pointer_system.cc, systems/primitives/shared_pointer_system.h, systems/primitives/test/shared_pointer_system_test.cc
Towards #20203.
It never has any ports or connections.  The only thing it could add as a clue to the output is something like it's name?
My premise, however, it that users looking at graphviz are seeking information about control and/or information flow, not details about heap reference counting.
To compare the before/after output, you can use the command line given in #20198.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20228)
=> [systems] Don't render SharedPointerSystem in Graphviz

geometry/render/render_material.cc, geometry/render/render_material.h, geometry/render/render_mesh.cc, geometry/render/render_mesh.h, geometry/render/test/render_material_test.cc, geometry/render/test/render_mesh_test.cc, geometry/render_gl/BUILD.bazel, geometry/render_gl/internal_opengl_geometry.h, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/test/internal_opengl_geometry_test.cc, geometry/render_vtk/internal_render_engine_vtk.cc
The fallback materials would use the ('phong', 'diffuse_map') or matching foo.png images as diffuse texture map, even if the underlying mesh could not support it. This is because they were given no information about whether a texture could be applied or not.
Now, it is provided information as to the support of texture coordinates and will *also* omit a texture if the underlying geometry lacks sufficient texture coordinate support.
Note: This leads to a very subtle, but non-destructive behavior change. If a diffuse map was specified for a capsule in RenderEngineVtk, the image will not appear (as it did before), but now there's a warning emitted.
This is the first PR in a train relating to #17266. The full PR train can be seen in #20235. This PR corresponds to the first commit  in that PR. …
=> [render] RenderMaterial offers more nuanced and complete warnings

geometry/render_gltf_client/BUILD.bazel, geometry/render_gltf_client/internal_merge_gltf.cc, geometry/render_gltf_client/internal_merge_gltf.h, geometry/render_gltf_client/internal_render_engine_gltf_client.cc, geometry/render_gltf_client/internal_render_engine_gltf_client.h, geometry/render_gltf_client/test/internal_merge_gltf_test.cc
There are two significant behavioral changes -- that *could* affect a user. However, given the newness of the underlying code and the fact that this touches distant corners of glTF-dom, the odds that anyone *actually* gets affected is small.
Scene merging.
- Previously, all input scenes were included and scenes with the same name were merged. Now only default scenes are merged, regardless of names.
Extras and extensions are properly handled.
- We now include two root arrays that were previously skipped: "extensionsUsed" and "extensionsRequired". These are now merged (without duplicates). The previous omission of "extensionsUsed" and "extensionsRequired" wasn't *obviously* a defect before because some glTF parsers are more forgiving than others in terms of *applying* extensions without …
=> RenderEngineGltfClient changes how input glTFs are handled

solvers/minimum_value_constraint.cc, solvers/minimum_value_constraint.h, solvers/test/minimum_value_constraint_test.cc
We should impose the minimum value lower and upper bound separately, as they will use different influence_value_offset.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20229)
=> Add MinimumValueLower/UpperBoundConstraint

tools/bazel.rc
See https://github.com/bazelbuild/bazel/issues/9006.  This flag doesn't do anything.
https://github.com/RobotLocomotion/drake-external-examples/pull/270 tracks its removal from `drake-external-examples` as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20242)
=> [bazel] Remove irrelevant rcfile flag

math/BUILD.bazel, math/rigid_transform.h, math/roll_pitch_yaw.h, math/rotation_matrix.h, math/test/rigid_transform_test.cc, math/test/roll_pitch_yaw_test.cc, math/test/rotation_matrix_test.cc
This can be useful for a part of an architecture for checking whether a pre-computed planning model for a robot or scene might have changed.
Closes #20207.
+@sadraddini for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20252)
=> [math] Add hash_append to RollPitchYaw/RotationMatrix/RigidTransform

planning/robot_diagram.cc, planning/robot_diagram.h, planning/robot_diagram_builder.cc, planning/robot_diagram_builder.h, planning/test/robot_diagram_test.cc
As of r1:
As of r2:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20238)
=> [planning] Export ports from RobotDiagram by default

multibody/plant/compliant_contact_manager.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/tamsi_driver.cc, multibody/plant/test/actuated_models_test.cc, multibody/plant/test/compliant_contact_manager_tester.h
Bug reported via the [SO](https://stackoverflow.com/questions/77169145/drifting-observed-when-controlling-a-robot-arm-with-implicit-pd-control-gravit).
Fix to bug introduced in #20111.
There are two types of force contributions: continuous forces (such as Coriolis, damping and force elements) and constraints. SAP incorporates continuous forces in the "free motion velocities" computation. 
Implicit PD controllers implemented in #20111 move actuation from a continuous contribution to a constraint contribution. However, #20111 failed to remove the contribution from the free motion velocities computation, and therefore this contribution is erroneously accounted for twice.
This PR removes actuation from the free motion velocities computation.
- - - …
=> Removes duplicated contribution of actuation when using PD controllers

geometry/render/render_mesh.cc, geometry/render/render_mesh.h, geometry/render/test/render_mesh_test.cc
Obj files have several mechanisms that would conceptually lead to creating disjoint "meshes" (i.e., putting them in different groups, different objects, or assigning different materials). For the purpose of rendering, the only important distinction is material. Because we render the whole mesh as a rigid object, we just need to partition based on the material assigned to a triangle. LoadRenderMeshesFromObj can now return multiple RenderMeshes.
We've introduced a shim for the old API (LoadRenderMeshFromObj()). This allows us to update RenderEngineVtk and RenderEngineGl in a follow up PR. The shim is *mostly* the same as the old. It has two differences which are acceptable for a short horizon.
- The debug message no longer prints out the material names.
- The resultant RenderMesh can easily …
=> Parsing an .obj file can produce multiple RenderMesh instances

bindings/pydrake/visualization/meldis.py, bindings/pydrake/visualization/test/meldis_test.py
This is ever so slightly easier to use (and discover) than the $BROWSER env var.
Towards #20221.  When viewing images, I think we'll be recommending `chromium` instead of `firefox`.
Here's an example of using the new flag:
```
bazel run //tools:meldis -- --browser=chromium
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20257)
=> [meldis] Offer --browser selection on the command line

multibody/plant/BUILD.bazel, multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/discrete_contact_data.h, multibody/plant/sap_driver.cc, multibody/plant/tamsi_driver.cc, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/compliant_contact_manager_tester.h, multibody/plant/test/deformable_contact_results_test.cc, multibody/plant/test/deformable_driver_contact_kinematics_test.cc, multibody/plant/test/deformable_driver_contact_test.cc, multibody/plant/test/discrete_contact_data_test.cc, multibody/plant/test/sap_driver_joint_limits_test.cc, multibody/plant/test/sap_driver_test.cc
Closes #20187 
We have three types of contact: point, hydroelastic, and deformable that share similar contact data like  DiscreteContactPair and ContactPairKinematics. Currently, we store them all in a std::vector with an ordering convention that is inconsistent across various classes that produce and consume these data.
We introduce DiscreteContactData to help enforce ordering conventions across the board and ensure the correct contact data is retrieved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20209)
=> Add DiscreteContactData

geometry/render/render_mesh.cc, geometry/render/render_mesh.h, geometry/render/test/render_mesh_test.cc
Reverts RobotLocomotion/drake#20250
This is causing problems in Anzu.
Try running 
bazel run tools:model_visualizer -- package://drake/manipulation/models/franka_description/urdf/panda_arm.urdf --show_rgbd_sensor
and it will crash.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20281)
=> Revert "Parsing an .obj file can produce multiple RenderMesh instances"

CMakeLists.txt, WORKSPACE, doc/_release-notes/v1.21.0.md
This was already true in practice; our docs just missed it.  The `@vtk_internal` rules use https://github.com/bazelbuild/bazel/pull/14835.
Amends #19945.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20263)
=> [doc] Bump Bazel minimum version to 5.1

geometry/render/render_mesh.cc, geometry/render/render_mesh.h, geometry/render/test/render_mesh_test.cc
Obj files have several mechanisms that would conceptually lead to creating disjoint "meshes" (i.e., putting them in different groups, different objects, or assigning different materials). For the purpose of rendering, the only important distinction is material. Because we render the whole mesh as a rigid object, we just need to partition based on the material assigned to a triangle. LoadRenderMeshesFromObj can now return multiple RenderMeshes.
We've introduced a shim for the old API (LoadRenderMeshFromObj()). This allows us to update RenderEngineVtk and RenderEngineGl in a follow up PR. The shim is mostly the same as the old. It has two differences which are acceptable for a short horizon.
- The debug message no longer prints out the material names.
- The resultant RenderMesh can easily …
=> [render] Parsing an .obj file can produce multiple RenderMesh instances

tools/workspace/new_release.py
Sample output as of this morning:
```
Checking for new releases...
abseil_cpp_internal needs upgrade from 1981cf8c0206657a16f73f48d43a313c65485d5e to 302d851a06072a581961970c1e120c2af7b70482
build_bazel_apple_support needs upgrade from 1.8.1 to 1.10.1
Ignoring crate__amd-0.2.2 from rules_rust
Ignoring crate__autocfg-1.1.0 from rules_rust
Ignoring crate__cfg-if-1.0.0 from rules_rust
Ignoring crate__clarabel-0.6.0 from rules_rust
Ignoring crate__darling-0.14.4 from rules_rust
Ignoring crate__darling_core-0.14.4 from rules_rust
Ignoring crate__darling_macro-0.14.4 from rules_rust
Ignoring crate__derive_builder-0.11.2 from rules_rust
Ignoring crate__derive_builder_core-0.11.2 from rules_rust
Ignoring crate__derive_builder_macro-0.11.2 from rules_rust
Ignoring crate__either-1.9.0 from …
```
=> [workspace] Nerf new_release for rust crates

geometry/BUILD.bazel, geometry/meshcat_graphviz.cc, geometry/meshcat_graphviz.h, geometry/meshcat_point_cloud_visualizer.cc, geometry/meshcat_point_cloud_visualizer.h, geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer.h, geometry/test/meshcat_graphviz_test.cc, geometry/test/meshcat_point_cloud_visualizer_test.cc, geometry/test/meshcat_visualizer_test.cc, multibody/meshcat/BUILD.bazel, multibody/meshcat/contact_visualizer.cc, multibody/meshcat/contact_visualizer.h, multibody/meshcat/joint_sliders.cc, multibody/meshcat/joint_sliders.h, multibody/meshcat/test/contact_visualizer_test.cc, multibody/meshcat/test/joint_sliders_test.cc, systems/framework/system_base.h, visualization/BUILD.bazel, visualization/meshcat_pose_sliders.cc, visualization/meshcat_pose_sliders.h, visualization/test/meshcat_pose_sliders_test.cc
Towards #20203.
As an example, here's what `//tools:model_visualizer` looks like in r1:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20270)
=> [geometry] Indicate Meshcat connections in System graphviz output

bindings/pydrake/systems/test/test_util_py.cc, geometry/test/meshcat_visualizer_test.cc, systems/analysis/simulator.cc, systems/analysis/simulator.h, systems/analysis/test/simulator_test.cc, systems/framework/BUILD.bazel, systems/framework/context_base.h, systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/event_status.cc, systems/framework/event_status.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/system.cc, systems/framework/system.h, systems/framework/test/diagram_test.cc, systems/framework/test/event_deprecated_test.cc, systems/framework/test/event_status_test.cc, systems/framework/test/leaf_context_test.cc, systems/framework/test/leaf_system_test.cc, systems/framework/test/system_test.cc, systems/lcm/test/lcm_publisher_system_test.cc, systems/lcm/test/lcm_subscriber_system_test.cc, systems/sensors/test/image_writer_test.cc, systems/sensors/test/rgbd_sensor_async_test.cc
Replaces Draft PR #19980
PR #19989 added `EventStatus` returns to the callbacks stored with Event objects. This PR propagates those upwards through the Drake API and deals with Event status returns in the Simulator. Caveat: code that overrides the default dispatchers (DoPublish(), DoCalcDiscreteVariableUpdates(), DoCalcUnrestrictedUpdate()) will still be assumed to return success since those virtuals have no way to return a status.
This is potentially (but not likely) a breaking change for these reasons:
- The default dispatchers listed above now execute handlers _after_ the overridable dispatchers return, _if_ the override invoked the default implementation. Previously, default dispatch would occur immediately when invoked.
- We now officially disallow user extension of class `System`; …
=> [framework] Propagate EventStatus through the API

systems/sensors/rgbd_sensor.cc, systems/sensors/test/rgbd_sensor_test.cc
`QueryObject` documents that it expected the pose of the camera *body* relative to a parent frame. `RgbdSensor` was passing the pose of the camera *sensor* relative to the parent frame. There can be a non-identity transform between the camera body and the camera sensor. The tests used the identity transform so this mistake slipped through the cracks.
resolves #20295
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20305)
=> [sensors] RgbdSensor now passes the correct camera pose

doc/_pages/installation.md, doc/_pages/release_playbook.md, tools/release_engineering/download_release_candidate.py, tools/wheel/wheel_builder/linux.py, tools/workspace/python/repository.bzl
(This helps show that #20294 doesn't appear to need any `pybind11` adjustments due to Python 3.12.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20299)
=> [wheel] Add Python 3.12 manylinux support

multibody/plant/deformable_driver.cc, multibody/plant/deformable_model.cc, multibody/plant/deformable_model.h, multibody/plant/test/deformable_fixed_constraint_test.cc, multibody/plant/test/deformable_model_test.cc
1. The Jacobian of the rigid dofs when computing the kinematics for fixed constraints now have the correct number of rows.
2. Fail fast when no constraints are added in DeformableModel::AddFixedConstraint().
3. Use dense algebra for computing `G*J` for the Jacobians of the deformable dofs for fixed constraints because `G*J` for non-3x3 G and block sparse J is not yet supported.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20297)
=> Bug fix for deformable fixed constraints

math/fast_pose_composition_functions_avx2_fma.cc
Recently I came back to re-read these functions, and I found them a bit difficult to follow.  This is my attempt to make them more clear (and polish a few rough edges with GCC in the process), especially for developers who are rusty with either their linear algebra or their familiarity with SIMD conventions.
None of the prior PRs #15013 #15073 #15119 appear to have any public benchmark tools, so this PR relies on llvm-mca to assess the impact of these changes.  Here's one example [on godbolt](https://godbolt.org/z/WM4vajdWz).
Refer to the commit message for further details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20289)
=> [math] Clarify implementation of fast pose composition functions

tools/install/libdrake/BUILD.bazel, tools/install/libdrake/test/exported_symbols_test.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20279)
=> [tools] Add test to flag hazardous exported symbols

multibody/plant/test/sap_driver_multidof_joints_test.cc, multibody/tree/ball_rpy_joint.cc, multibody/tree/ball_rpy_joint.h, multibody/tree/joint.cc, multibody/tree/joint.h, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree.cc, multibody/tree/planar_joint.cc, multibody/tree/planar_joint.h, multibody/tree/prismatic_joint.h, multibody/tree/quaternion_floating_joint.cc, multibody/tree/quaternion_floating_joint.h, multibody/tree/revolute_joint.cc, multibody/tree/revolute_joint.h, multibody/tree/screw_joint.cc, multibody/tree/screw_joint.h, multibody/tree/universal_joint.cc, multibody/tree/universal_joint.h, multibody/tree/weld_joint.cc, multibody/tree/weld_joint.h
For reasons lost to history (and likely my fault) MultibodyTree joint implementations allowed for the possibility that a joint would get modeled with more than one Mobilizer. With no loss of functionality, that is never going to happen! This PR removes that provision and its associated mess.
Changes are internal and not user visible.
(This is a small yak shave for multibody topology changes in #20225).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20309)
=> [multibody] Remove the unused provision for a Joint to be modeled with multiple Mobilizers

multibody/contact_solvers/matrix_block.cc, multibody/contact_solvers/matrix_block.h, multibody/contact_solvers/test/matrix_block_test.cc, multibody/plant/deformable_driver.cc
When the MatrixBlock is Block3x3SparseMatrix, we now allow the blocks in the block diagonal to be of size 3n-by-3n instead of restricted to be 3x3.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20312)
=> Extend MatrixBlock::LeftMultiplyByBlockDiagonal()

tools/wheel/Dockerfile, tools/wheel/wheel_builder/linux.py
It wastes about 15 seconds to compress the source tree every time, but the compression cannot be reused from one run to the next. Iterative local testing is much more pleasant without compressing, and there's no downside even for Jenkins builds.
+@mwoehlke-kitware for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20315)
=> [wheel] Save time by not compressing drake-src

multibody/plant/test/multibody_plant_reflected_inertia_test.cc, multibody/tree/body.h, multibody/tree/fixed_offset_frame.h, multibody/tree/force_element.h, multibody/tree/frame.h, multibody/tree/joint_actuator.h, multibody/tree/linear_bushing_roll_pitch_yaw.h, multibody/tree/mobilizer.h, multibody/tree/multibody_element.cc, multibody/tree/multibody_element.h, multibody/tree/multibody_tree_system.cc, multibody/tree/multibody_tree_system.h, multibody/tree/rigid_body.h
Sets up a framework within MultibodyTree/MultibodyPlant to have all MultibodyElements fill in their default model parameter values upon default context creation. This change means that model default values can now change post-Finalize, and those changes will be reflected in new default contexts.
Note: The member fields of all MultibodyElements will be the source of truth for default model parameter values. Model values for system parameters are set to dummy values to reflect that they are not used. When a default context is created (i.e. `MultibodyPlantSystem::SetDefaultContext()` is called) each `MultibodyElement` instance in the plant has the chance to write default values for its system level parameters through the NVI `MultibodyElement::SetDefaultParameters()`.
The current list of …
=> [multibody] Implements MultibodyTreeSystem::SetDefaultParameters

tools/install/libdrake/BUILD.bazel, tools/workspace/clarabel_cpp_internal/package.BUILD.bazel
\CC @hongkai-dai per https://github.com/RobotLocomotion/drake/pull/20314#pullrequestreview-1660255664.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20318)
=> [tools] Nerf the symbol visibility test when Clarabel is enabled

geometry/BUILD.bazel, geometry/drake_visualizer.cc, geometry/drake_visualizer.h, geometry/meshcat_graphviz.h, geometry/test/drake_visualizer_test.cc, manipulation/kuka_iiwa/test/iiwa_driver_functions_test.cc, systems/lcm/BUILD.bazel, systems/lcm/lcm_config_functions.cc, systems/lcm/lcm_interface_system.cc, systems/lcm/lcm_interface_system.h, systems/lcm/lcm_publisher_system.cc, systems/lcm/lcm_publisher_system.h, systems/lcm/lcm_subscriber_system.cc, systems/lcm/lcm_subscriber_system.h, systems/lcm/lcm_system_graphviz.cc, systems/lcm/lcm_system_graphviz.h, systems/lcm/test/lcm_config_functions_test.cc, systems/lcm/test/lcm_interface_system_test.cc, systems/lcm/test/lcm_publisher_system_test.cc, systems/lcm/test/lcm_subscriber_system_test.cc, systems/lcm/test/lcm_system_graphviz_test.cc
Closes #20203.  Here's a demo using the command line given in #20198.  See also #20270 for related Meshcat change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20310)
=> [systems/lcm] Indicate LCM connections in System graphviz output

geometry/render/render_mesh.cc
`error: loop variable '[full_index, part_index]' creates a copy from type 'std::pair<const int, unsigned int> const' [-Werror,-Wrange-loop-construct]`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20332)
=> [geometry] Fix clang warning in render_mesh

geometry/proximity/BUILD.bazel, geometry/proximity/test/zero_simplex_manual_test.cc
This is a developer convenience for quick evaluation of volume meshes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20323)
=> [geometry] Add zero_simplex_manual_test

multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/deformable_model.cc, multibody/plant/deformable_model.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/sap_driver.cc, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/compliant_contact_manager_tester.h, multibody/plant/test/deformable_boundary_condition_test.cc, multibody/plant/test/deformable_driver_contact_kinematics_test.cc, multibody/plant/test/deformable_driver_contact_test.cc, multibody/plant/test/deformable_driver_test.cc, multibody/plant/test/deformable_integration_test.cc, multibody/plant/test/deformable_model_test.cc, multibody/plant/test/discrete_update_manager_test.cc, multibody/plant/test/multibody_plant_scalar_conversion_test.cc
Towards #20274 
The computation of DiscreteContactPair data and ContactKinematics data is moved from CompliantContactManager to the base class DiscreteUpdateManager. This is in line with computation of ContactResults and ContactSolverResults. This allows objects with only pointer to the base class to access these information.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20273)
=> DiscreteUpdateManager computes contact kinematics

bindings/pydrake/geometry/geometry_py_scene_graph.cc, bindings/pydrake/geometry/test/scene_graph_test.py, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/scene_graph_test.cc
Previously we only provide API to modify/query the renderer in the SceneGraph
model. Now we provide API to modify/query the renderer in the context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20355)
=> SceneGraph modifies/access renderer in the context.

tools/install/libdrake/test/exported_symbols_test.py, tools/workspace/BUILD.bazel, tools/workspace/tinyobjloader_internal/package.BUILD.bazel
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20357)
=> [workspace] Use hidden symbols for tinyobjloader

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py
I added this method in #19975, but realized today I hadn't made a python binding for it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20341)
=> Add python binding for AffineSubspace::OrthogonalComplementBasis.

geometry/optimization/affine_subspace.cc, geometry/optimization/test/affine_subspace_test.cc
Functionality to compute the volume of convex sets was added in #19982, but AffineSubspace slipped through without having any test cases. This adds tests for CalcVolume and has_exact_volume.
This also updates the comment for DoCalcVolume, since it previously contradicted the base class documentation -- we throw an error if affine_dimension is zero.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20342)
=> Tests for AffineSubspace::CalcVolume.

tools/install/libdrake/test/exported_symbols_test.py, tools/workspace/clp_internal/package.BUILD.bazel
Towards #17231.  (More broadly Clp still leaks a bajillion global symbols that we don't want, but that remains as future work.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20358)
=> [workspace] Cull some unwanted ClpSolver code

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/affine_ball.cc, geometry/optimization/affine_ball.h, geometry/optimization/hyperellipsoid.h, geometry/optimization/test/affine_ball_test.cc
Towards #20037. This set can be used to represent ellipsoidal convex sets. The set must be bounded, but can be lower-dimensional.
Contrast with `Hyperellipsoid`, which can be unbounded, but must be full-dimensional.
+@russtedrake for feature review, please
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20038)
=> Implement AffineBall subclass of ConvexSet

bindings/pydrake/common/deprecation.py, common/BUILD.bazel, common/drake_deprecated.cc, common/drake_deprecated.h, common/test/drake_deprecated_test.cc, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gltf_client/internal_render_engine_gltf_client.cc, geometry/render_vtk/internal_render_engine_vtk.cc, multibody/tree/unit_inertia.cc, systems/framework/leaf_system.cc, systems/framework/system.cc
Example output:
```
[ RUN      ] DrakeDeprecatedTest.WarnOnceTest
[2023-10-13 06:56:48.867] [console] [warning] DRAKE DEPRECATED: The method OldCalc() has been renamed to NewCalc(). The deprecated code will be removed from Drake on or after 2038-01-19.
[       OK ] DrakeDeprecatedTest.WarnOnceTest (0 ms)
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20365)
=> [common] Add WarnDeprecated sugar for console deprecation logs

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/actuated_models_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/tree/joint_actuator.cc, multibody/tree/joint_actuator.h, multibody/tree/model_instance.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree_topology.h
Per [conversation in Slack](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1695068480697379).
This PR ensure that we properly documented and verify the indexing of input ports according to:
1. Actuation input ordered by JointActuatorIndex for the full actuation port.
2. For per-instance ports, inputs are ordered by JointActuatorIndex within that model instance.
And a bug fix for when joint actuators are not added in the same order model instances are. This seldom happens as we usually load models with our parsers, which add all actuators one model instance at a time. But users could choose to add actuators programatically in arbitrary oder of model instance. 
- - - …
=> Bug fix in actuation inputs ordering

bindings/pydrake/solvers/solvers_py_evaluators.cc, bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/evaluators_test.py, bindings/pydrake/solvers/test/mathematicalprogram_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/iris.cc, solvers/constraint.cc, solvers/constraint.h, solvers/ipopt_solver.cc, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/sdpa_free_format.cc, solvers/semidefinite_relaxation.cc, solvers/sparse_and_dense_matrix.cc, solvers/sparse_and_dense_matrix.h, solvers/test/constraint_test.cc, solvers/test/mathematical_program_test.cc, solvers/test/mathematical_program_test_util.h, solvers/test/sparse_and_dense_matrix_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20361)
=> Sparse add linear constraint

bindings/pydrake/BUILD.bazel, bindings/pydrake/common/BUILD.bazel, bindings/pydrake/multibody/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20382)
=> [pydrake] Remove misleadingly long spellings in BUILD files

tools/workspace/voxelized_geometry_tools/package.BUILD.bazel, tools/workspace/voxelized_geometry_tools/patches/vendor.patch, tools/workspace/voxelized_geometry_tools/repository.bzl
Equivalent to #19893 for VGT, towards #17231
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20387)
=> [workspace] Bump VGT to support hidden visibility

multibody/plant/discrete_update_manager.cc, multibody/plant/sap_driver.cc, multibody/plant/test/sap_driver_ball_constraints_test.cc, multibody/plant/test/sap_driver_distance_constraints_test.cc, multibody/plant/test/sap_driver_weld_constraints_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/multibody_tree_topology.h, multibody/tree/test/multibody_tree_creation_test.cc
This internal-only change brings the definition of a "tree" in line with the upcoming SpanningForest, and with standard graph terminology. Previously zero-dof trees didn't count, now they do. This required some minor changes to a few unit tests and to how constraints decide whether they have 1 clique or 2. (Consequences cleared f2f w/Alejandro)
Also renamed `MultibodyTreeTopology::tree_height()` to `::forest_height()` to avoid missing the forest for the trees.
This is a yak shave for the new MbP topology in #20225.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20386)
=> [multibody] Allow zero-dof trees in the multibody forest

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc
CompositeTrajectory's binding should have derived from PiecewiseTrajectory, not Trajectory. Now we have access to methods like `get_number_of_segments()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20407)
=> CompositeTrajectory binding isa PiecewiseTrajectory

math/rotation_matrix.cc, math/test/rotation_matrix_test.cc
Helps address issue #20405.
To fully close this issue, this piece of code needs to move to unit_vector.cc and there needs more complete test coverage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20406)
=> Fix divide by norm bug in RotationMatrix::NormalizeOrThrow().

multibody/plant/multibody_plant.h, multibody/tree/multibody_tree.h
Closes #20244
Steer away from using `tau_app` because it sometimes is used to denote externally applied forces excluding gravity.
Also update the stale documentation of the related MbT function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20426)
=> Clarify MultibodyPlant::CalcGeneralizedForces()

bindings/pydrake/examples/gym/play_cart_pole.py
CI got repeatable timeout (60 seconds) for //bindings/pydrake/examples/gym:py/play_cart_pole_test in 
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-jammy-gcc-bazel-continuous-release/2048/
https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-jammy-gcc-bazel-continuous-release/2049/
Increase test size to medium.  Previously it was using default (small).
Edit: Actually I can shorten the running time of the test to keep it small.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20422)
=> [examples/gym] Shorten running time of play_cart_pole_test

multibody/tree/multibody_tree_topology.h, multibody/tree/test/multibody_tree_creation_test.cc
Removes some special cases for Weld coordinate numbering by making it consistent with other mobilizer types.
The consistent approach is to assign q_start and v_start for Welds to be where they _would_ put coordinates if they had any. Then because nq==nv==0 for Welds, the next mobilizer starts at the same place. This consistent numbering scheme was already being used for trees with 0 dofs; it is definitely the nicer approach!
This is an internal-only change with no visible consequences. (This PR is a yak shave for the new MbP topology code which uses consistent numbering for all mobilized body types.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20428)
=> [multibody] Make coordinate numbering for Weld mobilizers consistent with others

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/exponential_cone_program_examples.cc, solvers/test/exponential_cone_program_examples.h, solvers/test/mathematical_program_test.cc, solvers/test/mosek_solver_test.cc, solvers/test/scs_solver_test.cc
MathematicalProgram.AddLogDeterminantLowerConstraint imposes log(det(X)) >= lower as convex constraints.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20411)
=> Add log(det(X)) >= lower to MathematicalProgram.

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/multibody_doxygen.h, multibody/plant/sap_driver.cc, multibody/tree/body.h, multibody/tree/body_node.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree_topology.h, multibody/tree/rigid_body.h, multibody/tree/test/body_node_test.cc, multibody/tree/test/multibody_tree_creation_test.cc
At one time we thought we'd support flexible bodies in MultibodyTree. Now we support deformable bodies via a different mechanism. This PR removes anachronistic mention of flexible bodies and internal body states.
Two methods are removed from Body (`get_num_flexible_positions/velocities()`). Since these were documented as "not implemented" I'm proposing to remove them without further deprecation.
Since I had to wade through lots of comments to find everything, there are a few opportunistic comment fixes and removal of expired TODOs also.
In addition to general tech debt cleanup, this is a yak shave for the new MbP topology code which does not deal in body-internal coordinates.
- - - …
=> [multibody] Eliminate mention of flexible body support from MultibodyTree

multibody/plant/deformable_driver.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/multibody_plant.cc, multibody/plant/sap_driver.cc, multibody/plant/tamsi_driver.cc, multibody/plant/test/compliant_contact_manager_tester.h, multibody/plant/test/sap_driver_joint_limits_test.cc, multibody/plant/test/sap_driver_test.cc, multibody/tree/body.h, multibody/tree/body_node.h, multibody/tree/joint.h, multibody/tree/mobilizer_impl.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree_topology.h, multibody/tree/test/multibody_tree_creation_test.cc
The terms "velocity_start" and "velocities_start" are used in MbP and MbT ambiguously. Either "start within v" or "start within state qv".
This internal-only PR renames variables to disambiguate using "_in_state" or "_in_v" to clarify. No changes are made to the public API which uses "velocity_start()" to mean "in v" but "floating_velocities_start()" to mean "in state". 
Ideally I'd like to have position_start() mean "in q" and velocity_start() mean "in v" always, and do away entirely with the odd concept of velocity indexes "in state" which assumes that q and v are contiguous (something we hope to change). However for now I'll just settle for disambiguating the internals.
This is both a tech debt cleanup and yak shave for substituting the new graph's coordinate assignments for the old …
=> [multibody] Disambiguate use of "velocity_start" in MultibodyTree

bindings/pydrake/pydrake_doxygen.h
Even modules that start small end up growing too big, so from day one we should always define modules in pieces.
The dependency tree is not always simple. By defining the pieces of a module one by one, it allows us to stagger imports vs definitions and/or more carefully bind things in the right order.
+@EricCousineau-TRI for SME feature review, please.
+@SeanCurtis-TRI for additional feature review, please.
+@sammy-tri for platform review per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20432)
=> [py doc] Set a policy that modules must always be factored

geometry/render_vtk/BUILD.bazel
Although the tests are excluded from mac arm, this test now times out on mac x86 monterey.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20434)
=> Increase timeout for internal_render_engine_vtk_test

geometry/meshcat.html, tools/workspace/meshcat/repository.bzl
Note: This qualitatively changes the output renderings. Meshcat's rendered result has moved from linear-srgb to srgb. Things are generally less saturated now as part of three.js's move towards more realistic lighting.
We've amended meshcat.html to accommodate some of the fundamental changes:
- Silence a console warning.
- Beef up the lighting so that it's more aesthetically pleasing.
TODO: After the meshcat PR has merged, update repository.bzl to refer to
the correct upstream source.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20442)
=> Upgrade meshcat to latest commit

tools/workspace/conex_internal/vendor.bzl, tools/workspace/vendor_cxx.bzl, tools/workspace/vendor_cxx.py, tools/workspace/vendor_cxx_test.py
We stopped using this feature a while ago (#19936). I left it available as unit-tested-dead-code in case we ever wanted to start using it again, but it seems like probably not, and it's getting in the way of forthcoming revisions to this file (for #17231).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20452)
=> [tools] Remove --edit-include feature for vendoring

tools/workspace/vtk_internal/patches/io_image_png_messages.patch, tools/workspace/vtk_internal/repository.bzl
We don't yet have enough plumbing hooked up to add regression testing for this, but I hope that the patch is obviously correct on its own.  At least, it doesn't cause any _new_ test failures.
+@svenevs for feature review or delegation, please.
Towards #20447.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20445)
=> [vtk] Dispatch vtkPNGReader errors correctly

geometry/meshcat.h, geometry/meshcat.html, geometry/test/meshcat_manual_test.cc
Refer to the comments in `meshcat.html` for more information on usage.
How it works:
- Access `https://localhost:7000?webxr=ar` to enable AR.
- Access `https://localhost:7000?webxr=vr` to enable VR.
- Append `&controller=on` to the URL to visualize the headset controllers in immersive mode.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20430)
=> Enable webxr with html argument

tools/workspace/common_robotics_utilities/repository.bzl
Fixes a nuisance `warning: 'common_robotics_utilities::parallelism_test::ParallelismTestSuite' declared with greater visibility than its base` in a CRU test.
+@rpoyner-tri for review, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20459)
=> [workspace] Bump CRU to fix visibility warning in test

bindings/pydrake/examples/gym/named_view_helpers.py, bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, examples/atlas/atlas_run_dynamics.cc, multibody/plant/multibody_plant.h, multibody/plant/test/calc_distance_and_time_derivative_test.cc, multibody/plant/test/joint_locking_test.cc, multibody/plant/test/multibody_plant_introspection_test.cc, multibody/tree/body.h, multibody/tree/multibody_tree_topology.h, tutorials/multibody_plant_autodiff_mass.ipynb
In MbP Joint and in MbP/MbT internals, `velocity_start()` means "start index in v" while in MbP Body, `floating_velocities_start()` means "start index in state qv" so adds num_positions() to skip over q. This has been an endless source of confusion, as first noted by @amcastro-tri in #12757. The "within state" indexing also bakes in an assumption that we store q and v concatenated, something we may want to change for performance reasons later.
This PR deprecates  `Body::floating_velocities_start()` and replaces it with `floating_velocities_start_in_v()`, with deprecation instructions noting that it has to be offset by num_positions() to be equivalent. This brings the floating API (marked as "Advanced") in line with the Joint API.
Resolves #12757
cc @drewhamiltonasdf
- - -
This change …
=> [multibody] Deprecate confusing Body::floating_velocities_start() method

geometry/render_vtk/BUILD.bazel, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/internal_render_engine_vtk.h, geometry/render_vtk/test/internal_render_engine_vtk_no_display_test.cc, systems/sensors/BUILD.bazel
Previously, it would print to stderr and then abort, which was less-than-helpful for Jupyter sessions.
Closes #18445.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20461)
=> [render] RenderEngineVtk throws on errors

bindings/pydrake/BUILD.bazel, bindings/pydrake/stubgen.py
Amends #20403.
Without this fix, VSCode users are missing tab-completion for things like `pydrake.common.Parallelism`.
+(release notes: none) because 20403 has not yet been released.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20466)
=> [py tools] Add back some missing pydrake.common stubgen output

doc/_release-notes/end_of_support.md
Towards #20339.
+@svenevs or +@BetsyMcPhail for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20458)
=> [doc] Document macOS EOL release tags

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/contact_solvers/sap/sap_contact_problem.cc, multibody/contact_solvers/sap/sap_contact_problem.h, multibody/contact_solvers/sap/test/sap_contact_problem_test.cc, multibody/plant/compliant_contact_manager.cc, multibody/plant/compliant_contact_manager.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/sap_driver.cc, multibody/plant/sap_driver.h, multibody/plant/test/actuated_models_test.cc, multibody/plant/test/discrete_update_manager_test.cc, multibody/plant/test/multibody_plant_scalar_conversion_test.cc, multibody/plant/test/multibody_plant_test.cc
Adds output port to MultibodyPlant to report the total actuation applied by the actuators in the model, including PD controllers added to the plant.
cc'ing @JoseBarreiros-TRI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20421)
=> Implements actuation output port for MultibodyPlant

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/iris.cc, geometry/optimization/iris.h, geometry/optimization/test/iris_in_configuration_space_test.cc, geometry/optimization/test/iris_test.cc
This PR addresses https://github.com/RobotLocomotion/drake/issues/20268 by adding a ~`starting_polytope`~ _`bounding_region`_ member to the `IrisOptions` struct. 
@RussTedrake when you have a chance could I bother you for a feature review on this one?
P.S this is be my first PR into drake. I've been through the contributing guidelines but let me know if I missed anything!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20417)
=> Add bounding_region to IrisOptions

geometry/optimization/BUILD.bazel, geometry/optimization/test/affine_ball_test.cc
This fixes the test failure [shown here](https://drake-jenkins.csail.mit.edu/view/Production/job/linux-focal-clang-bazel-nightly-gurobi-release/418/).  (FYI it fails the same way on Jammy, not just Focal.)
Amends #20399.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20498)
=> Adjust MinimumVolumeCircumscribedEllipsoid test tolerance for Gurobi

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/parsing_doxygen.h, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc
Adds SDFormat and URDF parsing for JointActuator's PD controller gains as well as parsing documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20497)
=> [multibody] Add parsing of JointActuator PD controller gains.

doc/_pages/buildcop.md, doc/_pages/from_source.md, doc/_pages/getting_help.md, doc/_pages/installation.md, doc/_pages/jenkins.md, doc/_pages/release_playbook.md
Drake v1.22.0 was the last release with macOS Monterey arm64 support.
Relates: #20339.  CC @BetsyMcPhail
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20511)
=> [doc] Remove macOS Monterey arm64 support

geometry/optimization/test/iris_test.cc
Fix iris_test failure
Use a point more deeply embedded in the obstacle when checking that obstacles are removed from iris regions
Closes #20507.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20512)
=> Fix build failure for `iris_test`

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/parsing_doxygen.h, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf
Adds a custom `drake:mimic` tag for SDFormat with semantics analogous to the already supported `<mimic>` tag in URDF.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20503)
=> [parsing] Add parsing of custom drake:mimic tag for SDFormat

multibody/parsing/README_model_directives.md, multibody/parsing/process_model_directives.cc, multibody/parsing/process_model_directives.h, multibody/parsing/test/process_model_directives_test.cc, multibody/parsing/test/process_model_directives_test/add_scoped_top.dmd.yaml
FlattenModelDirectives did not handle scoped names, which made it difficult to use in scenarios with multiple instances of the same model.
It was also undocumented and untested.
This change adds correct namespace handling; it also adds documentation and a minimal test (minimal because any naming-related errors are caught during the assembly of the MultibodyTree, and because the scoped test fixtures were designed to exercise naming).
* Fixes #20425.
* Removes misleading comments (including a mention of RigidBodyTree!).
* Documents FlattenModelDirectives.
* Documents the special-case naming semantics in add_frame directives.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/ …
=> Correct, test, and document `FlattenModelDirectives`

tools/release_engineering/download_release_candidate.py
Relates: #20339
This is an implication of switching the wheel build as far as I know.  We have not had [nightly CI finish yet](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-arm-ventura-unprovisioned-clang-wheel-nightly-release/2/console) which will be the first CI job capable of producing an artifact similar to the staging urls being considered.
CC @BetsyMcPhail @jwnimmer-tri
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20520)
=> [wheel] macOS arm64 staging builds use Ventura now

tools/workspace/pybind11/repository.bzl
Closes https://github.com/RobotLocomotion/drake/issues/20516.
See https://github.com/RobotLocomotion/pybind11/pull/69.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20524)
=> [workspace] Upgrade pybind11 to latest commit

planning/trajectory_optimization/BUILD.bazel, planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Resolves a CI failure at
https://drake-jenkins.csail.mit.edu/job/mac-arm-monterey-unprovisioned-clang-bazel-nightly-release/409/consoleFull
Homebrew upgraded from ipopt 3.14.14 (which passed) to ipopt 3.14.13 (which failed).  This is a new failure due to the homebrew upgrade.
The solver was actually finding a solution which passed the test, but reporting failure because it could not achieve the desired tolerance. Additionally, IPOPT was complaining about unbounded variables. This PR adds bounds to the unbounded variables and adjusts the solver convergence tolerance.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20526)
=> Adjust tolerance for KinTrajOpt w/ new ipopt on mac arm

multibody/tree/geometry_spatial_inertia.cc
CalcMassProperties is not a method that exists in current code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20533)
=> [multibody] Fix an error message typo

bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/sap_driver.cc, multibody/plant/test/multibody_plant_test.cc, multibody/plant/test/sap_driver_test.cc, multibody/plant/test/sap_driver_weld_constraints_test.cc
Fixes #20527.
The weld constraint was not wired up to use the constraint active status mechanism, this PR adds the missing feature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20530)
=> [multibody] Make weld constraint use active status.

doc/_pages/from_binary.md, doc/_pages/release_playbook.md, doc/_release-notes/template.txt, tools/release_engineering/dev/push_release.py, tools/release_engineering/download_release_candidate.py
Staging jobs now produce packages with version numbers rather than timestamps in the file names. Update release instructions and related scripts accordingly.
Fixes #18300.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20532)
=> Update release scripts for staging changes

geometry/optimization/BUILD.bazel
See [example failure](https://drake-jenkins.csail.mit.edu/view/Production/job/linux-jammy-clang-bazel-nightly-everything-leak-sanitizer/7/).
This also adds a `no_memcheck` comment missed in #18621.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20546)
=> [optimization] Disable LSan on cspace_free_polytope_with_mosek_test

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/actuated_models_test.cc, multibody/plant/test/multibody_plant_test.cc
Per @jwnimmer-tri's request during the review of #20421.
While in #20421 we only provide a port of the net actuation for the entire model, this PR adds the per model instance output ports.
cc'ing @JoseBarreiros-TRI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20549)
=> Implement per model instance net actuation output port

common/test_utilities/diagnostic_policy_test_base.h, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_urdf_parser_test.cc
Fixes #20538.
This bug was introduced #20503. I forgot to use the model instance specific joint getter APIs on a few calls.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20551)
=> [parsing] Fix urdf mimic parsing multiple model instances.

doc/_pages/release_playbook.md, doc/_release-notes/template.txt, tools/release_engineering/relnotes.py
We can fill in the version number ahead of time, in the template.
We only have YYYY-MM-DD now in the notes, not YYYYMMDD.
+@EricCousineau-TRI for both reviews, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20553)
=> [doc] Tidy up release playbook version docs and tools

tools/workspace/pybind11/mkdoc.py
Towards #20339.
This resolves a newly-seen error XCode 15 seen [here](https://drake-cdash.csail.mit.edu/test/1289370145).
I'll use "none" for release notes because we'll wait to announce XCode 15 support concurrently with Sonoma support, once all of the other steps are finished.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20561)
=> [mkdoc] Fix handling of anoymous enums vs Apple Clang 15

cmake/bazel.rc.in, tools/wheel/image/build-drake.sh
Change the CMake-generated bazelrc file to also look for an (optional) per-build bazelrc. This gives users a way to create a bazelrc that only applies to a specific CMake build tree, in addition to the user.bazelrc that applies to the Drake checkout.
Also, change the Linux wheel build to use this rather than the system bazelrc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20566)
=> Add per-build bazelrc

CMakeLists.txt, tools/wheel/macos/build-wheel.sh, tools/wheel/wheel_builder/common.py, tools/wheel/wheel_builder/macos.py
Change the macOS wheel builder to use the CMake front-end to build Drake.
Also, clean up the wheel builder script a bit, removing a deprecated and unneeded option, and adding an option to skip provisioning on macOS. (The latter is needed to build as a user that doesn't own the homebrew installation.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20570)
=> Use CMake to build macOS wheels

doc/_pages/jenkins.md
The instructions for dispatching wheel builds was missing the please. This makes the instructions copy-and-pastable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20601)
=> Jenkins document missing "please"

geometry/proximity/field_intersection.cc, geometry/proximity/field_intersection.h, geometry/proximity/test/field_intersection_test.cc
- Remove template parameter BvType because it's always Obb for hydroelastics.
Related to #19704
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20555)
=> [geometry] Simplify HydroelasticVolumeIntersector template

bindings/pydrake/examples/gym/envs/cart_pole.py
Use the much more direct way to get the SceneGraph world frame id, since many people might copy from this example.
+@JoseBarreiros-TRI for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20580)
=> Minor style fixup in cartpole DrakeGymEnv example.

examples/kuka_iiwa_arm/models/objects/block_for_pick_and_place_mid_size.urdf, manipulation/models/allegro_hand_description/urdf/allegro_hand_description_left.urdf, manipulation/models/allegro_hand_description/urdf/allegro_hand_description_right.urdf
The removed bits are ignored, but not complained about, by the current parser. Schema checking (still in development) noticed the problems.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20612)
=> [urdf] Remove some oddities noticed by schema checking

geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/test/internal_render_engine_vtk_test.cc
The generic phong model uses vtkActor::Texture to define the diffuse texture.
The Pbr illumination model uses a texture assigned to the actor's properties (the "albedo texture"). Furthermore, that texture must be marked as sRGB.
This correct both the assignment (when PBR is active) as well as the upgrade when it is activated after geometries have aleady been assigned.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20607)
=> Correct phong-to-pbr promotion in presence of diffuse texture

tools/wheel/macos/build-dependencies.sh, tools/wheel/macos/build-wheel.sh, tools/wheel/wheel_builder/macos.py
Rework macOS wheel build script to completely separate provisioning, dependency building, and building of the actual wheel. This more closely aligns with how the builder allows these stages to be skipped, and will also make it easier to build multiple wheels (which can share a dependency build).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20595)
=> Refactor macOS wheel build

visualization/concatenate_images.cc, visualization/concatenate_images.h, visualization/test/concatenate_images_test.cc
Towards #18862.  When displaying image array messages received over LCM, we have no way enforce that the sizes will be uniform, so instead we'll need to pad them out to tile correctly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20599)
=> [visualization] ConcatenateImages allows for variable size inputs

multibody/parsing/test/scoped_names_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/test/multibody_tree_test.cc
I've seen a number of students confused by the following sequence of events:
1) they add a new manipuland, let's call it "mug", into the simulation (typically via mesh_to_model, and then loading the sdf into the HardwareStation via model directives.
2) they call `GetBodyByName("mug")`. Not only does it fail, but it prints out a list of bodies, none of which resemble the name mug.
The problem, of course, is that "mug" is the model instance name, but not the body name. The body name is an obfuscated "body", which was autogenerated by mesh_to_model; at no time were they aware of that string and don't immediately associate it with the mug. Instead, they suspect that something was wrong with the dmd string and they failed to parse the mug. Moreover, the entire concept of MultibodyPlant …
=> Increase verbosity of GetElementByName error message.

geometry/optimization/iris.cc, geometry/optimization/test/iris_in_configuration_space_test.cc
I noticed a small bug in `IrisInConfigurationSpace` when handling additional constraints. The algorithm first falsifies lower bound, and then must falsify upper bound. 
However, when both bounds are present, then all `consecutive_failures` are consumed by the lower bound, and the falsification of the upper bound is wrongly skipped, leading to invalid IRIS regions. 
Augmented an existing unit test to ensure this is working. Without the fix in this PR, the extra part of the unit test fails. 
cc @RussTedrake
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20627)
=> Reset IRIS consecutive_failures after falsifying lower bound

solvers/mathematical_program.h, solvers/mathematical_program_result.h, solvers/mosek_solver.cc, solvers/mosek_solver.h, solvers/mosek_solver_internal.cc, solvers/mosek_solver_internal.h, solvers/test/linear_program_examples.h, solvers/test/mosek_solver_test.cc, solvers/test/semidefinite_program_examples.h, tools/workspace/mosek/repository.bzl
Closes #20628.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20634)
=> [workspace] Upgrade MOSEK to latest release 10.1.21

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20586)
=> Adds methods for enforcing that a principal submatrix of a symmetric matrix be positive semidefinite

bindings/pydrake/multibody/test/optimization_test.py, doc/doxygen_cxx/doxygen.h, examples/acrobot/test/run_swing_up_traj_optimization.cc, multibody/optimization/test/static_equilibrium_problem_test.cc, planning/trajectory_optimization/test/direct_transcription_test.cc, solvers/snopt_solver.h, solvers/snopt_solver_common.cc, solvers/test/complementary_problem_test.cc, solvers/test/gurobi_solver_grb_license_file_test.cc, solvers/test/mathematical_program_result_test.cc, solvers/test/mathematical_program_test.cc, solvers/test/mosek_solver_moseklm_license_file_test.cc, solvers/test/nonlinear_program_test.cc, solvers/test/snopt_solver_test.cc
In a forthcoming refactoring of our build & test tactics w.r.t. commercial solvers, we need the ability to toggle them on/off using environment variables.  The MosekSolver and GurobiSolver already offer that with their `enabled()` logic.  Extend that to SNOPT as well, with a new environment variable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20636)
=> [solvers] Add an environment variable to disable SnoptSolver

geometry/optimization/test/graph_of_convex_sets_test.cc
Previously this test was checking the convex restriction result with the full MIP result at all vertices. It should have only been checking along the shortest path.
This should avoid the revert in #20651.  
(Closes: #20651)
cc @TobiaMarcucci 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20657)
=> Fix GCS test when running w/ Mosek's MI solver.

multibody/contact_solvers/sap/sap_solver.cc, multibody/contact_solvers/sap/test/sap_solver_test.cc
With the updated SAP formulation (#19434) costs can no longer be assumed to be always positive.
In particular, the Hunt & Crossley constraint in #20635 can produce negative values.
This PR removes the "postive costs" assumptions from the SAP solver, which really only shows in scaling and convergence tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20650)
=> SAP: Remove the assumption that costs are always positive.

third_party/com_github_bazelbuild_rules_cc/whole_archive.bzl, tools/bazel.rc, tools/lint/library_lint_reporter.py, tools/workspace/tinyxml2_internal/package.BUILD.bazel
Note that Bazel 7 isn't tested in Jenkins yet.
To test locally, `cd drake` and then edit your `.bazeliskrc` file (inside Drake) to set this line:
```
USE_BAZEL_VERSION=7.0.0
```
Then you can run bazelisk to download the new Bazel on the fly:
```
third_party/com_github_bazelbuild_bazelisk/bazelisk.py build //:install
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20658)
=> [tools] Fix some errors with Bazel 7

examples/multibody/deformable_torus/BUILD.bazel, examples/multibody/deformable_torus/README.md, examples/multibody/deformable_torus/deformable_torus.cc, examples/multibody/deformable_torus/parallel_gripper_controller.cc, examples/multibody/deformable_torus/parallel_gripper_controller.h, examples/multibody/deformable_torus/point_source_force_field.cc, examples/multibody/deformable_torus/point_source_force_field.h, examples/multibody/deformable_torus/simple_gripper.sdf, examples/multibody/deformable_torus/suction_cup_controller.cc, examples/multibody/deformable_torus/suction_cup_controller.h, examples/multibody/deformable_torus/test/point_source_force_field_test.cc
- Add PointSourceForceField as an example of a concrete ForceDensityField.
- Add a `gripper` flag so that one can toggle between a parallel gripper and a suction gripper to pick up the deformable torus.
- Refactor the controller into separate files to reduce the lines of code in the example .cc file.
- Change the parallel fingers to capsule shape to avoid sticking resulting from the sharp change in contact normal from boxes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20629)
=> Rework deformable torus example to demo external force

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/BUILD.bazel, multibody/plant/discrete_update_manager.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_config.h, multibody/plant/multibody_plant_config_functions.cc, multibody/plant/multibody_plant_config_functions.h, multibody/plant/sap_driver.cc, multibody/plant/test/multibody_plant_config_functions_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/plant/test/sap_driver_contact_constraints_test.cc
Closes #19320.
Towards #19322
In a nutshell, with this PR the `SapDriver` now makes uses of the `SapHuntCrossleyConstraint` (#20635).
To choose among contact model approximations, the users can call:
- `MultibodyPlant::set_discrete_contact_approximation()` or,
- Use the `MultibodyPlantConfig::discrete_contact_approximation`
Notice that:
1. for backwards compatibility, the default approximaiton is `DiscreteContactApproximation::kTamsi`.
2. The new API to set model approximations is consistent with the API to set discrete solvers.
3. There are no deprecations in this PR, though depreaction of `MbP::set_discrete_contact_solver()` in the future is a posibility.
- - - …
=> MultibodyPlant uses the new Hunt&Crossley model from SAP

bindings/pydrake/BUILD.bazel, common/BUILD.bazel, common/overloaded.h, common/schema/BUILD.bazel, common/schema/rotation.cc, common/schema/stochastic.cc, common/test/overloaded_test.cc, geometry/render_gl/BUILD.bazel, geometry/render_gl/test/multithread_safety_test.cc, multibody/meshcat/BUILD.bazel, multibody/meshcat/joint_sliders.cc, tools/lint/drakelint.py
* The C++ `std::visit` (typeswitch dispatch) is very useful for `std::variant` but doesn't support it natively.
* There is a two-line mystic sigil that is copied literally in a few Drake files (and many files downstream expected to move to drake).
* It is rule-of-three and should be factored.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20644)
=> Move common "overloaded" helper idiom to common

doc/_pages/jenkins.md
Update the instructions for how to find the URL of a wheel built as part of a pull request experimental build (the links are now easier to find). Add instructions for how to locally install the wheel.
Fixes #18968.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20661)
=> Improve wheel testing instructions

geometry/optimization/BUILD.bazel, geometry/optimization/hyperellipsoid.cc
Following up on https://github.com/RobotLocomotion/drake/pull/20663
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20677)
=> Add Clarabel to preferred_solvers in MinimumUniformScalingToTouch

geometry/optimization/hyperrectangle.cc, geometry/optimization/test/hyperrectangle_test.cc
Closes https://github.com/RobotLocomotion/drake/issues/20667 by calling `ConvexSet::IsBounded` instead of solely relying on mathematical optimization, for which some solvers behave badly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20680)
=> Check ConvexSet::IsBounded first in MaybeCalcAxisAlignedBoundingBox

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/BUILD.bazel, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Towards #20449.
Performs introspection on a MulitbodyPlant, returning the indices in the internal configuration vector which are associated to continuous revolute joints and mobile bases (stored as `PlanarJoint` which are implicitly just two prismatic joints and a revolute joint). This list of indices can then be passed directly into the GcsTrajectoryOptimization constructor, and the joint indices will align with IRIS regions created from the same multibody plant.
+@sadraddini for feature review, please
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20652)
=> GcsTrajectoryOptimization helper function to get indices associated to continuous revolute joints.

multibody/hydroelastics/hydroelastic_user_guide_doxygen.h, multibody/parsing/parsing_doxygen.h, multibody/plant/contact_model_doxygen.h, multibody/plant/multibody_plant.h
This PR updates stale contact documentation in `@anchor mbp_contact_modeling` in MultibodyPlant. 
With the new hydroelatic guide and contact solver these docs lagged behind.
We should definitely still do a more hollistic pass to update this section, the hydro guide and "Contact Modeling in Drake" Doxygen module. Some information is either repeated across these three or even slightly contradictory.
This is NOT the purpose of this PR.
This PR simply focuses on making  sure `@anchor mbp_contact_modeling`  is no longer a lie, providing a quick read for those setting contact parameters, with links to the more detailed discussions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomoti …
=> Update stale MultibodyPlant contact docs

tools/skylark/drake_cc.bzl
It appears that if we have a .cc file that declares unit tests (e.g., using TEST_F), if we build it into a library against @gtest//:without_main, the actual tests get omitted.
This tweaks the set up slightly so that if we're on linux, the test declaration uses the .cc file directly and links with drake's default gtest main function.
(Incidentally fixes a typo.)
relates to #20576
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20689)
=> Change how linux-only tests get built

geometry/render_gl/internal_opengl_context.cc
If a RenderEngineGl is asked to render and display an image that didn't match the default window size in the OpenGlContext, it would hang.
This is because the resizing would wait for xwindows to provide an expose event. However, if the window isn't visible yet (i.e., it's being resized before being made visible), there won't be such an event. This leads to the process hanging, waiting for an event that will never come.
We've changed the context's default window size. The test on the OpenGlContext is sufficient to test the expected outcome.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20695)
=> Correct window sizing in RenderEngineGl

systems/sensors/camera_config_functions.cc, systems/sensors/test/camera_config_functions_test.cc, visualization/test/visualization_config_functions_test.cc, visualization/visualization_config.h, visualization/visualization_config_functions.cc
Closes #20668.
---
Using this patch to the example demo:
```
--- a/examples/hardware_sim/example_scenarios.yaml
+++ b/examples/hardware_sim/example_scenarios.yaml
@@ -3,6 +3,7 @@
Demo:
+  simulation_duration: 0
directives:
- add_model:
name: amazon_table
@@ -46,9 +47,8 @@ Demo:
parent: wsg_on_iiwa
child: wsg::body
lcm_buses:
-    driver_traffic:
-      # Use a non-default LCM url to communicate with the robot.
-      lcm_url: udpm://239.241.129.92:20185?ttl=0
+    default:
+      lcm_url: memq://null
cameras:
oracular_view:
name: camera_0
@@ -56,8 +56,5 @@ Demo:
translation: [1.5, 0.8, 1.25]
rotation: !Rpy { deg: [-120, 5, 125] }
model_drivers:
-    iiwa: !IiwaDriver
-      hand_model_name: wsg
-      lcm_bus: driver_traffic
-    wsg: !SchunkWsgDriver
-      lcm_bus: driver_traffic
+ …
```
=> Avoid Diagram pollution when opted-out of LCM

lcm/drake_lcm.cc, lcm/drake_lcm.h, lcm/drake_lcm_log.cc, lcm/test/drake_lcm_test.cc, tools/install/libdrake/test/exported_symbols_test.py
Remove deprecated access to underlying native LCM C++ object.
Adjust DrakeLcmLog implementation to avoid calling LCM's C++ code. The C++ code is not ABI-stable. (This was missed in #20116.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20716)
=> [lcm] Remove deprecated code 2024-01

common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_write_archive.cc, common/yaml/yaml_write_archive.h
Per the [YAML specification](https://yaml.org/spec/1.2.2/#10214-floating-point), the negative sign should precede the dot.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20719)
=> [yaml] Fix output spelling of negative infinity

multibody/parsing/parsing_doxygen.h
The previous documentation told me that mu_static would be ignored, but didn't give me a breadcrumb to figure out what parameter I _should_ set. In the code, I found comments of this form repeated often, and they were much more helpful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20721)
=> Touchup parsing documentation for mu_static

multibody/parsing/BUILD.bazel, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/parsing/test/sdf_parser_test/interface_api_test/arm.xml, tools/workspace/dm_control_internal/files.bzl
Towards #20232.  Related to #20444.
In #20232 we realized that the default eulerseq in MJCF is "xyz", which is NOT the standard eulerseq in urdf/sdf. This PR fixes a bug in which we assumed the wrong eulerseq by default, leading to incorrect kinematics in some parsed models. It also adds support for non-default eulerseq.
It also adds a test so that we can readily visualize the parsed kinematics from the dm_control suite which are being used to test the parser.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20620)
=> MJCF parser supports eulerseq (and fixes the default)

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
Mesh defaults can be used to set the scale of the assets globally. "assetdir" is another way to set the "meshdir".
Towards #20444.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20621)
=> MJCF parser supports mesh defaults and assetdir

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py
Currently, there is no python binding for InverseKinematics::AddMinimumDistanceUpperBoundConstraint
Added such a binding in [bindings/pydrake/multibody/inverse_kinematics_py.cc]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20736)
=> Adding Python Binding for InverseKinematics.AddMinimumDistanceUpperBoundConstraint

multibody/tree/multibody_tree-inl.h, multibody/tree/test/joint_actuator_test.cc
Extracted out of #20711, with improved unit test clarity.
\CC @RussTedrake FYI
---
This was previously observed here:
> Note: It's a little strange that the actuators which throw an exception in the existing tests are still added to the topology.
-- https://github.com/RobotLocomotion/drake/pull/16835#pullrequestreview-918689989
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20751)
=> [plant] Fix exception safety bug in AddJointActuator

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
Towards #20444.
As discussed in
https://drakedevelopers.slack.com/archives/C43KX47A9/p1697895553790089 , this PR:
- avoids registering collision geometry for geom with contype==conaffinity==0
- avoids registering visual geometry for group > 2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20622)
=> Mujoco parser support for visual-only and/or collision-only geometry

multibody/inverse_kinematics/inverse_kinematics.cc, multibody/inverse_kinematics/test/inverse_kinematics_test.cc, multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc, multibody/inverse_kinematics/unit_quaternion_constraint.cc, multibody/inverse_kinematics/unit_quaternion_constraint.h
Resolves #17726.
cc @cohnt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20624)
=> InverseKinematics: set non-zero initial guess for quaternion joints.

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Adds a pre-finalize method to remove MbP constraints.
An example use case for this is when I've parsed a gripper into my plant with the parser, but then want to go through and replace all of the joints with weld joints. In that workflow, I'll also have to remove any constraints that were added by the parser, but will now become invalid.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20720)
=> Implements MultibodyPlant::RemoveConstraint

multibody/plant/compliant_contact_manager.cc, multibody/plant/multibody_plant.cc, multibody/rational/rational_forward_kinematics.cc, multibody/rational/rational_forward_kinematics_internal.cc, multibody/rational/test/rational_forward_kinematics_test_utilities.cc, multibody/tree/body_node.h, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree_topology.h, multibody/tree/rigid_body.h, multibody/tree/test/multibody_tree_creation_test.cc, multibody/tree/test/tree_from_mobilizers_test.cc
This extracts some internal cleanup changes from #20225:
- removes unused ForceElementTopology (from multibody_tree_topology.h)
- updates some comments
- adds some missing "body" -> "rigid body" terminology changes (see #20676)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20734)
=> [multibody] Remove dead code; minor internals cleanup.

geometry/proximity/BUILD.bazel, geometry/proximity/test/volume_mesh_refiner_test.cc, geometry/proximity/volume_mesh_refiner.cc, geometry/proximity/volume_mesh_refiner.h
Spin off a part of #19232 for easy review.
This PR #19550 is a prerequisite of PR #20324 as a tool for advanced users to enrich tetrahedral meshes for hydroelastics and deformables.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19550)
=> [geometry] Tetrahedral mesh refinement

tools/workspace/vtk_internal/patches/common_data_model_warnings.patch
VTK update re-writes this module and this patch is not longer needed nor applies.
@svenevs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20746)
=> [vtk_internal] DataModel warnings patch is no longer needed

multibody/multibody_doxygen.h
As mentioned in https://github.com/RobotLocomotion/drake/pull/14397#issuecomment-1879309659
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20749)
=> [multibody_doxygen] Remove incorrect statement about model frames

common/schema/test/transform_test.cc, common/schema/transform.cc, common/schema/transform.h
* Resolves #20754:  Sample() was silently discarding base_frame.
* Throws when called in the dangerous case.
* Adds new SampleAsTransform() method that samples into the same type, preseving the frame.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20756)
=> Throw when Transform::Sample is called with a base frame.

bindings/pydrake/test/stubgen_test.py, tools/workspace/mypy_internal/repository.bzl
Toward #20723.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20745)
=> [workspace] Upgrade mypy_internal to latest release v1.8.0

multibody/parsing/model_directives.h, multibody/parsing/test/process_model_directives_test.cc
Throws an error earlier in the parsing if the specified frame is not deterministic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20773)
=> [multibody/parsing] Improve error handling of AddFrame

bindings/pydrake/perception_py.cc, bindings/pydrake/planning/BUILD.bazel, bindings/pydrake/planning/planning_py_collision_checker.cc, bindings/pydrake/planning/planning_py_visibility_graph.cc, bindings/pydrake/planning/test/collision_checker_test.py, bindings/pydrake/planning/test/collision_checker_trace_test.py
New bindings rule: when a function accepts `Parallelism` as an argument, its binding should release the GIL.
See #20755 for some discussion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20759)
=> [py planning] Fix deadlocks when using parallelize=True

common/schema/BUILD.bazel, common/schema/test/transform_test.cc, common/schema/transform.cc, common/schema/transform.h
There is correct code downstream that was manually handling the base_frame propagation. We should allow users who did a good job to cross this API transition without a flag day.
Amends #20756.
+(priority: high) because this needs to land before the next release.
Ping to either +@calderpg-tri or +@ggould-tri for feature review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20775)
=> [schema] Nerf Transform::Sample back to a deprecation, not error

geometry/BUILD.bazel, geometry/test/meshcat_manual_test.cc
This can be useful to read DEBUG-level messages when using the program for local manual debugging.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20778)
=> [geometry] Enable log level control in meshcat_manual_test

bindings/pydrake/multibody/inverse_kinematics_py_differential.cc, bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py, multibody/inverse_kinematics/differential_inverse_kinematics.cc, multibody/inverse_kinematics/differential_inverse_kinematics.h, multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc
Add support for non-world reference frames to differential inverse kinematics.
Adds two new overloads to DoDifferentialInverseKinematics().
Towards #19580
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20735)
=> non-world reference frames for DiffIK

geometry/meshcat.cc, geometry/meshcat_types_internal.h
The upstream name is `_meshfile_object` not `_mesh_file_object`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20788)
=> [geometry] Fix typo in Meshcat helper struct name

common/BUILD.bazel, common/sha256.cc, common/sha256.h, common/test/sha256_test.cc, geometry/render_gltf_client/BUILD.bazel, geometry/render_gltf_client/internal_render_client.cc, multibody/parsing/BUILD.bazel, multibody/parsing/package_map.cc, multibody/parsing/test/package_map_remote_test.cc
I anticipate this being useful for #19598, but in any case factoring out a wrapper around picosha for rule-of-two seems plausible on its own.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20779)
=> [common] Add Sha256 utility class

bindings/pydrake/systems/analysis_py.cc, systems/analysis/BUILD.bazel, systems/analysis/monte_carlo.cc, systems/analysis/monte_carlo.h, systems/analysis/test/monte_carlo_test.cc
+@calderpg-tri for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20785)
=> [analysis] Update MonteCarlo to use Parallelism API

tools/workspace/common_robotics_utilities/repository.bzl
Latest CRU adds catch + rethrow for exceptions thrown in worker threads of CRU `{Static,Dynamic}ParallelFor{Index,Range}Loop` functions so that consuming code can rely on RAII cleanup (raw OpenMP does not handle this cleanly).
+@EricCousineau-TRI for review, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20786)
=> [workspace] Bump CRU with fixes for parallel-for exception handling

bindings/pydrake/geometry/test/visualizers_test.py, common/BUILD.bazel, common/find_resource.cc, common/find_resource.h, common/test/find_resource_test.cc, common/yaml/test/yaml_doxygen_test.cc, common/yaml/test/yaml_io_test.cc, geometry/BUILD.bazel, geometry/meshcat.cc, geometry/meshcat_internal.cc, geometry/meshcat_internal.h, geometry/render_gl/internal_shader_program.cc, geometry/render_gltf_client/internal_render_client.cc, geometry/test/meshcat_internal_test.cc, multibody/parsing/package_map.cc, multibody/parsing/test/package_map_remote_test.cc, multibody/parsing/test/parser_test.cc, multibody/parsing/test/process_model_directives_test.cc, solvers/BUILD.bazel, solvers/gurobi_solver.cc, solvers/test/snopt_solver_test.cc
Towards #19598.
Returning cacheable 200 responses with empty bodies is seriously misleading to the browser-side code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20790)
=> [geometry] Meshcat's server returns 404 (not 200) on failures

geometry/render/BUILD.bazel, geometry/render/render_engine.cc, geometry/render/render_engine.h, geometry/render/test/render_engine_test.cc, geometry/test_utilities/dummy_render_engine.h
Towards #18922.
See the full wip branch at #20780 for bigger picture.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20781)
=> RenderEngine accepts and updates deformable geometries

doc/_pages/release_playbook.md, tools/release_engineering/download_release_candidate.py, tools/wheel/BUILD.bazel, tools/wheel/README.rst, tools/wheel/macos/build-wheel.sh, tools/wheel/macos/provision-test-python.sh, tools/wheel/wheel_builder/common.py, tools/wheel/wheel_builder/macos.py, tools/wheel/wheel_builder/macos_types.py
Rework macOS wheel build scripts to use Python-version-specific permanent locations for all operations, with temporary symlinks used for operations shared with the Linux wheel builds that expect non-versioned locations. Also rework builder to support a set of Python targets and to be able to build multiple wheels in a manner similar to how things work for Linux.
This changes the macOS wheel build to produce wheels for (as of writing) both Python 3.11 and 3.12.
Fixes #18791.
Fixes #19098.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20616)
=> Build macOS wheels for multiple Python versions

geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat.html, geometry/test/meshcat_manual_test.cc
Prior to this, `Uncaught ReferenceError: urlParams is not defined` was printed from any static HTML page.
Amends #20430.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20791)
=> [geometry] Fix Meshcat browser console error messages

tools/install/libdrake/BUILD.bazel
Avoids a crash that was breaking coverage uploads in CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20800)
=> [tools] Disable kcov for exported_symbols_test

multibody/topology/BUILD.bazel, multibody/topology/multibody_graph.cc
Sets `enable_clang_format_lint` to `True`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20801)
=> Enable clang_format for multibody/topology directory

examples/pendulum/BUILD.bazel, examples/pendulum/trajectory_optimization_simulation.cc, geometry/optimization/BUILD.bazel
Towards #20799.
Since we have no `WORKSPACE` control over the BLAS version that Homebrew ships, we need to disable tests to get CI back to green.  Then in due time we can work to overcome the problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20803)
=> Disable two tests on macOS that fail with upgraded OpenBLAS

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py
Very small PR to create a python binding for the static method `Hyperrectangle::MaybeCalcAxisAlignedBoundingBox`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20804)
=> Bind Hyperrectangle::MaybeCalcAxisAlignedBoundingBox

geometry/proximity/BUILD.bazel, geometry/proximity/deformable_contact_internal.cc, geometry/proximity/deformable_contact_internal.h, geometry/proximity/test/deformable_contact_internal_test.cc, geometry/test/proximity_engine_test.cc
When no deformable shapes appear in proximity engine, don't bother computing the deformables-specific surface meshes for rigid shapes since it will never be used and can be very expensive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20822)
=> [geometry] Defer surface meshing for deformables when inactive

bindings/pydrake/common/value_py.cc, bindings/pydrake/multibody/meshcat_py.cc, bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/lcm_py.cc, bindings/pydrake/systems/test/lcm_test.py, bindings/pydrake/visualization/visualization_py_sliders.cc
Functions that run indefinitely (or sleep) in C++ should release the GIL so that other Python-based work can be scheduled on some other thread.
Fixing the Run functions releasing pointed out a few places we were missing some `scoped_acquire` annotations (in non-trivial `PYBIND11_OVERRIDE` bodies).  The `pybind11` library has built-in checks that flag those oversights in Debug builds, so CI caught and reminded us.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20811)
=> [pydrake] Release the GIL during "Run" functions

tools/workspace/README.md, tools/workspace/clarabel_cpp_internal/repository.bzl
Add a paragraph to the monthly upgrades documentation that describes how to perform the crate_universe upgrade. Note that this should be done as a 'cohort' with clarabel_cpp if/when that is upgraded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20815)
=> Add instructions to upgrade crate_universe monthly

manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc, manipulation/schunk_wsg/test/schunk_wsg_trajectory_generator_test.cc
There was a particular set of initial conditions which could cause the trajectory generator to fail, because it passed times=[0, 0, 0] to the PiecewisePolynomial.FirstOrderHold, which then complained about non-increasing times.
This PR adds a test which captures the failure, and the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20828)
=> Fix for SchunkWsgTrajectoryGenerator failing on delta=0

geometry/render_vtk/BUILD.bazel, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/test/internal_vtk_gltf_parser_patch_test.cc, tools/workspace/vtk_internal/patches/gltf_parser.patch, tools/workspace/vtk_internal/repository.bzl
Patches some bugs in VTK's glTF parsing.
- A material with only non-color textures would ignore its textures.
- A material with only non-color textures would erroneously report multiple UV texture coordinate sets.
- Warnings in the glTF parser were coded to go straight to the console (no event observer could intervene).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20818)
=> Patch VTK's glTF parser logic

geometry/optimization/cartesian_product.h, geometry/optimization/convex_set.h, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.h, geometry/optimization/minkowski_sum.h, geometry/optimization/point.h, geometry/optimization/vpolytope.h
Offering these functions up to users is at best misleading, and at worst a segfault (writing through an invalid `static_cast`).
Amends #15194 (see discussion labeled `geometry/optimization/convex_set.cc, line 42 at r3`): _"I'll leave this for now. It's easy enough to change (without changing any of the intended public API) later if we prefer."_.
Closes #20830.  (This is an alternative approach to the same goal.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20832)
=> [optimization] Remove ShapeReifier as a public base of ConvexSet

bindings/pydrake/geometry/geometry_py.h, common/autodiff.h, common/overloaded.h, examples/acrobot/acrobot_lcm.h, examples/allegro_hand/allegro_lcm.h, examples/planar_gripper/gripper_brick_planning_constraint_helper.h, geometry/proximity/detect_zero_simplex.h, geometry/proximity/distance_to_shape_callback.h, geometry/proximity/distance_to_shape_touching.h, geometry/proximity/test/characterization_utilities.h, manipulation/schunk_wsg/schunk_wsg_lcm.h, manipulation/util/robot_plan_utils.h, solvers/rotation_constraint.h, systems/sensors/image_writer.h, tools/lint/drakelint.py
A common mistake is to say `@file` followed by a topic sentence, but this is wrong. The text after `@file` is filename. We always need a line break before starting the topic sentence.
https://www.doxygen.nl/manual/commands.html#cmdfile
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20836)
=> [doc] Fix Doxygen file-overview syntax typo

common/overloaded.h, common/schema/rotation.cc, common/schema/stochastic.cc, common/test/overloaded_test.cc, common/yaml/BUILD.bazel, common/yaml/yaml_node.cc, common/yaml/yaml_write_archive.cc, geometry/meshcat.cc, geometry/meshcat_visualizer.cc, geometry/render_gl/test/multithread_safety_test.cc, multibody/meshcat/joint_sliders.cc, systems/sensors/BUILD.bazel, systems/sensors/camera_config_functions.cc
This helps avoid boilerplate and improve clarity.
Unfortunately, the `std::visit` feature we need is C++ 20 only, so we need to temporarily lobotomize this for C++17 until we drop Focal.
In Reviewable, r⊥..r1 shows what the code will look like long-term.  The r1..head is the Focal band-aid that will be reverted in a couple months when we drop Focal.
---
Examples:
```c++
// Visiting a generic lambda with a uniform return type.
// No need to pass a template argument to std::visit.
// For code in this form, this PR doesn't change anything.
const int size = std::visit(
[](auto&& arg) {
return arg.size();
},
some_variant);
// Visiting an overloaded group of lambdas.
// Pass a template argument to std::visit to unify the return types.
// This template argument is new in this PR; previously, we …
```
=> When using visit with overloaded, prescribe the return type

geometry/optimization/BUILD.bazel, solvers/clarabel_solver.cc
When the program contains both PSD and Exponential cones, we must loosen the default tolerance to reduce the possibility of crashing the entire process.
This is not guaranteed to avoid the crashes, but in practice it seems to make it a lot less likely.
Relates to https://github.com/RobotLocomotion/drake/issues/20799 and https://github.com/oxfordcontrol/Clarabel.rs/issues/66.
---
```
bazel test //solvers:clarabel_solver_test \
--nocache_test_results \
--test_output=streamed \
--test_arg=--spdlog_level=debug \
--test_arg=--gtest_filter=TestExponentialConeProgram.MinimalEllipsoidConveringPoints
...
[----------] 1 test from TestExponentialConeProgram
[ RUN      ] TestExponentialConeProgram.MinimalEllipsoidConveringPoints
[2024-01-30 14:56:54.591] [console] [debug] ClarabelSolver is using …
```
=> [solvers] Adjust ClarabelSolver default tolerances

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/test/hpolyhedron_test.cc
More than a single step of hit and run between samples is required to get a distribuiton that converges to a uniform distribution for general HPolyhedra. This PR adds an optional argument 'mixing_steps' that sets the number of hit and run iterations between samples.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20817)
=> Implements mixing for uniform sampling in HPolyhedra

geometry/optimization/test/geodesic_convexity_test.cc, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Towards #20449. Now supports the wraparound edges in the [AddEdges](https://drake.mit.edu/doxygen_cxx/classdrake_1_1planning_1_1trajectory__optimization_1_1_gcs_trajectory_optimization.html#a8bebbda88b8d0ae4fadc88777404491e) method of GcsTrajectoryOptimization.
Will look for a feature reviewer once #20655 lands, since this builds off some of those changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20700)
=> Support Wraparound Edges when Adding Edges Between Subgraphs

CMakeLists.txt, tools/workspace/execute.bzl, tools/workspace/os.bzl, tools/workspace/python/repository.bzl
(Refer to the commit message for details.)
Towards #20556 and #14967.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20562)
=> [workspace] Avoid crashes in python repository rule

bindings/pydrake/geometry/geometry_py_scene_graph.cc, bindings/pydrake/geometry/test/scene_graph_test.py, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/optimization/iris.cc, geometry/scene_graph_inspector.cc, geometry/scene_graph_inspector.h, geometry/test/geometry_state_test.cc
Use this in IRIS so obstacles are created in a deterministic order.  Looping over an `unordered_set` is bad juju.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20834)
=> [geometry] Add optional role parameter to GetAllGeometryIds

geometry/proximity/BUILD.bazel, geometry/proximity/calc_distance_to_surface_mesh.cc, geometry/proximity/calc_distance_to_surface_mesh.h, geometry/proximity/deformable_contact_geometries.cc, geometry/proximity/make_mesh_field.cc, geometry/proximity/test/calc_distance_to_surface_mesh_test.cc, geometry/proximity/volume_to_surface_mesh.cc, geometry/proximity/volume_to_surface_mesh.h
Speed up loading a tetrahedral-mesh VTK file. Improve pressure-field computation from O(mn) to O(n log n + m log n) using BVH, about 10X speed up in practice for moderate meshes.
Use BVH in CalcDistanceToSurfaceMesh.
Prequel of #20774.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20798)
=> [geometry]  Accelerate initialization of compliant-hydroelastic nonconvex meshes

planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Avoid calling indices that may not exist that led to default zeros (and absence of proper wrapping) when `continuous_revolute_joints` did not start with 0 (or had gaps between the smallest and largest index).  
Added a unit test that would not pass otherwise.
@cohnt for feature review
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20857)
=> Fix index query bug in PairwiseIntersectionsContinuousJoints

tools/workspace/vtk_internal/patches/filters_sources_cylinder.patch
The patch can be dropped during the next VTK upgrade.
VTK MR: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10860
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20864)
=> [vtk] Denote vtkCylinderSource patch already upstreamed

bindings/pydrake/geometry/geometry_py_render.cc, geometry/render/BUILD.bazel, geometry/render/color_deprecated.h, geometry/render/render_engine.h, geometry/render/test/render_engine_test.cc, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/test/internal_render_engine_gl_test.cc, geometry/render_gltf_client/internal_render_engine_gltf_client.cc, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/internal_render_engine_vtk.h, geometry/render_vtk/test/internal_render_engine_vtk_test.cc, geometry/test_utilities/dummy_render_engine.h, systems/sensors/BUILD.bazel, systems/sensors/color_palette.h
Closes #9628.
Rationale:
- `ColorPalette` is dead code with no tests.
- `Color<T>`  is not used generically, only as an implementation trick for `ColorI` and `ColorD`.
- `ColorI` is only used by dead code.
- `ColorD` was still lightly used, but is confusingly duplicative of `geometry::Rgba`, but with less sugar and fine-tuning.  Better to just use the canonical type everywhere.  The extra alpha-channel is no harm done.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20860)
=> [sensors] Deprecate Color, ColorI, ColorD, ColorPalette

tools/workspace/metadata.py
Affirm to the S3 mirroring script that `crate_universe` itself doesn't have any downloads to be archived.
Amends #20855.
https://drake-jenkins.csail.mit.edu/view/Production/job/linux-jammy-unprovisioned-gcc-bazel-continuous-mirror-to-s3/
+(priority: emergency)
+@mwoehlke-kitware for review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20869)
=> Fix "Teach new_release to use upgrade scripts" vs S3

geometry/optimization/test/spectrahedron_test.cc
Constrainted => constrained.
Really this PR is getting opened to confirm results of #20865 and triggers are working.
While this was introduced in #19888, I'm going to post on #code_review for an internal developer to stamp it given the perceived role of the original author there.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20871)
=> [geometry] Fix minor typo in implementation comment

bindings/pydrake/geometry/geometry_py_common.cc, bindings/pydrake/geometry/test/common_test.py, geometry/BUILD.bazel, geometry/proximity/deformable_contact_geometries.h, geometry/proximity/hydroelastic_internal.h, geometry/proximity/test/distance_to_point_characterize_test.cc, geometry/proximity/test/hydroelastic_internal_test.cc, geometry/shape_specification.cc, geometry/shape_specification.h, geometry/shape_to_string.cc, geometry/shape_to_string.h, geometry/test/geometry_state_test.cc, geometry/test/internal_geometry_test.cc, geometry/test/scene_graph_test.cc, geometry/test/shape_specification_test.cc, geometry/test/shape_to_string_test.cc, multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/all_geometries_as_collision.sdf, multibody/parsing/test/sdf_parser_test/all_geometries_as_visual.sdf, multibody/parsing/test/urdf_parser_test/all_geometries_as_collision.urdf, multibody/parsing/test/urdf_parser_test/all_geometries_as_visual.urdf
Deprecate the (awkward) ShapeName and (unused) ShapeToString reifiers, which were the prior mechanisms to obtain the Shape::type_name and Shape::to_string values.
Refactor Shape to use a vtable instead of copying reference-counted std::function objects everywhere. Implementing vtables by hand is confusing and wasteful.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20870)
=> [geometry] Add Shape::type_name, Shape::to_string, and fmt formatter

geometry/scene_graph_inspector.h
This (untested) sugar is not used anywhere.  It probably made more sense before we had the `GetGeometry(id)` inspection function.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20872)
=> [geometry] Deprecate SceneGraphInspector::Reify

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/test/graph_of_convex_sets_test.cc
When we remove a vertex, we also remove the edges connected to it. But those should also be removed from the outgoing/incoming edge lists of the corresponding vertices.
Also modified the unit test which would fail otherwise.
I came across this problem on a custom code when extracting the solution path from `GcsTrajectoryOptimization` with multiple sets as source/target ran into non-existing edges, because the edges from/to the `dummy_source` and `dummy_target` [in here](https://github.com/RobotLocomotion/drake/blob/10c26ec8b5037d477a40423e93f3c012f00e069f/planning/trajectory_optimization/gcs_trajectory_optimization.cc#L1027) don't get properly cleaned.
- - - …
=> gcs: remove incoming/outgoing edges of a vertex when they don't exist

multibody/parsing/BUILD.bazel, multibody/parsing/detail_dmd_parser.cc, multibody/parsing/detail_dmd_parser.h, multibody/parsing/model_directives.h, multibody/parsing/process_model_directives.cc, multibody/parsing/test/detail_collision_filter_group_resolver_test.cc, multibody/parsing/test/process_model_directives_test.cc, multibody/parsing/test/process_model_directives_test/add_scoped_sub.dmd.yaml, multibody/parsing/test/process_model_directives_test/fake_camera.sdf, multibody/parsing/test/process_model_directives_test/flattened.dmd.yaml, multibody/parsing/test/process_model_directives_test/unflattened_arm.dmd.yaml, multibody/parsing/test/process_model_directives_test/unflattened_top.dmd.yaml
* add_collision_filter_group does not permit a scoped name
* add_directives has a model_namespace to apply to the included directives
* As a result, add_directives would cause a throw when flattening a dmd file containing add_collision_filter_group, even though that dmd file was valid.
* The more correct outcome is to use the add_directives model_namespace when processing filter groups.
This implicitly breaks the semantics of CollisionFilterGroupResolver, which forbids scoped names.  But afaict that is only because it can take a model instance as parsing context, which could conflict with the namespace. In fact the namespace and model instance context cases seem to be non- overlapping.
- - - …
=> Allow add_directives of directives including collision filters

geometry/render/render_engine.h, geometry/render_gl/internal_render_engine_gl.h, geometry/render_vtk/internal_render_engine_vtk.h, geometry/test_utilities/dummy_render_engine.h
It doesn't make sense to let _users_ of a RenderEngine reify shapes into it.  The `void* user_data` would almost certainly be wrong, and segfault.
This might be a breaking change for code that implemented its own custom RenderEngine and was using `this` as the `ShapeReifier` receiver.  To fix the break, inherit from `ShapeReifier` directly yourself.
(There is not really any great way to deprecate this in a way that gives helpful compiler diagnostics.)
If you need your code to be compatible with versions of Drake both before and after this change, you can use a shim:
```c++
#include <type_traits>
...
namespace deprecation_shim {
struct Empty {};
using ShapeReifierOneWayOrAnother =
std::conditional_t<std::is_base_of_v<drake::geometry::ShapeReifier,
drake::geometry::render::RenderEngine>, …
```
=> [geometry] RenderEngine no longer inherits ShapeReifier

geometry/test/meshcat_test.cc
Before launching an external process that talks to the websocket thread and expects a specific reply, we need to ensure that all of our Defer() calls that modify the scene tree (or etc.) have actually been processed by the websocket thread.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20899)
=> [geometry] Fix race condition in meshcat unit test

lcmtypes/BUILD.bazel, tools/wheel/image/build-drake.sh, tools/wheel/macos/build-wheel.sh, tools/workspace/com_jidesoft_jide_oss/repository.bzl, tools/workspace/commons_io/repository.bzl, tools/workspace/java.bzl, tools/workspace/lcm/package.BUILD.bazel, tools/workspace/net_sf_jchart2d/repository.bzl, tools/workspace/org_apache_xmlgraphics_commons/repository.bzl
Instead of using the "detected OS" ("manylinux" or "macos_wheel") to implicitly opt-out (by virtue of it not being "ubuntu"), we now have an (internal use only) opt-out flag that wheel builds toggle acutuely.
This still isn't terribly elegant, but it's at least slightly more readable and documented. The important upside is removing another use of the `determine_os()` function, which is scheduled for removal.
Towards #14967.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20850)
=> [tools] Change how wheel builds opt-out of LCM java

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20843)
=> Add bindings for ConvexSet::CalcVolumeViaSampling

tools/workspace/metadata.py, tools/workspace/new_release.py, tools/workspace/rules_rust/repository.bzl, tools/workspace/rust_toolchain/lock/archives.bzl
- Upgrade rules_rust to latest release 0.38.0
- Upgrade rust_toolchain to latest
Additionally, add repository metadata for rust_toolchain, make rules_rust and rust_toolchain cohorts, and remove no-longer-needed upgrade advice from rules_rust.
Towards #20868.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20901)
=> [workspace] Upgrade rules_rust, rust_toolchain to latest

geometry/optimization/hpolyhedron.cc, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc
Previously, this would call QHull, which would lead to errors such as `QH6050 qhull error: dimension 1 must be > 1`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20893)
=> Transform between HPolyhedron and VPolytope with ambient dimension 1.

geometry/BUILD.bazel, geometry/meshcat.h, geometry/meshcat_params.h, geometry/test/meshcat_params_test.cc
Generally we aim for one class per file for clarity, but for config structs in particular we strongly prefer it so that config can use the schema without pulling in the full class.
Towards #20920.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20918)
=> [geometry] Split MeshcatParams into its own file

bindings/pydrake/common/test/yaml_typed_test.py, bindings/pydrake/common/yaml.py
Towards #20920.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20922)
=> [py yaml] yaml_load_typed uses schema=type(defaults) by default

geometry/optimization/hpolyhedron.cc, geometry/optimization/test/hpolyhedron_test.cc
This is occasionally necessary to prevent certain numerical issues, such as those described in #20839. An example of an HPolyhedron that experiences these numerical issues is available [here](https://gist.github.com/cohnt/56e887560451751d88149b1ff42981d4).
Runtime should be insignificant relative to solving the SDP, so it's probably easiest just to do it in every instance. An alternative is only calling this version if the first solve fails.
+@AlexandreAmice for feature review
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20849)
=> Normalize constraints in HPolyhedron::MaximumVolumeInscribedEllipsoid

systems/framework/system_base.cc, systems/framework/test/leaf_system_test.cc
The Graphviz was broken when a system used an HTML special character as part of its class name, system name, or port name.
Amends #20204.
Closes #20914.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20915)
=> [framework] Fix broken Graphviz on systems with <,>,& characters

common/eigen_types.h, common/test/eigen_types_test.cc, examples/scene_graph/simple_contact_surface_vis.cc, geometry/drake_visualizer.cc, geometry/profiling/contact_surface_rigid_bowl_soft_ball.cc, geometry/test_utilities/dummy_render_engine.h, multibody/meshcat/contact_visualizer.cc, multibody/plant/contact_results_to_lcm.cc, multibody/plant/test/contact_results_to_lcm_test.cc, multibody/rational/rational_forward_kinematics.cc, multibody/rational/rational_forward_kinematics.h
I've replaced a bunch of uses of longhand container-map conversion with this new sugar, but certainly haven't tried to hunt down all of them.
This arose in the context of switching to a new `lcm-gen` (#20761).  The upstream version of `lcm-gen` outputs C arrays as member fields in some cases, and we were relying on implicit decay of these to bare pointers to feed the `Eigen::Map` mumbo jumbo.  In my new `lcm_gen`, those member fields are generated as `std::array<>` types now instead of C arrays, so the decay doesn't work.  This is a feature!  Array decay is awful!  (It loses all ability to do size checking.)   I'm not 100% sure yet that I'll decide to make the breaking change to LCM message field types, but in any case (1) this helps us get ready and (2) OMG stop using array decay and all …
=> Add EigenMapView to aid inerop with C++ containers

bindings/pydrake/geometry/geometry_py_visualizers.cc, geometry/meshcat.h, geometry/test/meshcat_visualizer_test.cc
The default framerate for StartRecording should match the default publish period of MeshcatVisualizer. Mismatches can lead to unexpected behavior:
https://stackoverflow.com/questions/77916511/meshcat-not-visualizing-initial-conditions-correctly-drake/77979312#77979312
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20926)
=> [Meshcat] Change the default recording framerate to 64 fps.

manipulation/models/iiwa_description/README.md, manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf, manipulation/models/iiwa_description/iiwa7/iiwa7_with_box_collision.sdf, multibody/plant/test/actuated_models_test.cc
I copied the effort and velocity limits from [this](https://www.reeco.co.uk/wp-content/uploads/2020/05/KUKA-LBR-iiwa-technical-data.pdf) brochure. I kept 10 significant figures when converting degrees per second to radians per second.
This PR is towards https://github.com/RobotLocomotion/drake/issues/20907
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20917)
=> Improve iiwa 7 effort and velocity limits

bindings/pydrake/geometry/geometry_py_visualizers.cc, bindings/pydrake/geometry/test/visualizers_test.py, geometry/meshcat.cc, geometry/meshcat_params.h, geometry/test/meshcat_test.cc
Towards #20927.
This works with Python YAML loading, but not yet C++ YAML loading.  C++ loading support will appear in a follow-up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20920)
=> [geometry] Add MeshcatParams option for initial_properties

tools/workspace/vtk_internal/patches/common_core_version.patch, tools/workspace/vtk_internal/settings.bzl
We don't need to patch out quite as much. I'd forgotten that our cmake_configure_file accepts recursive definitions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20924)
=> [vtk] Simplify VTK_VERSION patching

tools/workspace/metadata.py
789298cc55bf (#20910) added some documentation, but left behind some where it appears the intention was to replace the prior wording. Clean up the leftover bit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20939)
=> Fix comment in metadata.py

tools/install/dockerhub/noble/.dockerignore, tools/install/dockerhub/noble/Dockerfile, tools/install/dockerhub/noble/README.md, tools/ubuntu-noble.bazelrc
This is the tools-side brother of #20929.
This is the second step toward supporting Ubuntu 24.04 ("Noble").
This PR doesn't actually do much yet, other than copy the files while preserving git history. The git hijinks are intricate enough that it makes sense to land this on its own, before changing any setup scripts to actually use it.
The one meaningful change is the final commit, which adjust some spellings in the Dockerfile.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20955)
=> [tools] Add Noble scripts, copied from Jammy

CMakeLists.txt
Rip out use of ExternalProject to drive the build, as we aren't doing anything that really benefits from it. Move the install logic to `install(CODE)` so that it happens via `make install` (or the equivalent), rather than as part of the build (e.g. `make`). Similarly, move the call that announces build information to the configure stage.
Fixes #20908.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20916)
=> Don't install as build step

geometry/test/geometry_state_test.cc, multibody/parsing/BUILD.bazel, multibody/parsing/detail_collision_filter_group_resolver.cc, multibody/parsing/detail_collision_filter_group_resolver.h, multibody/parsing/detail_common.cc, multibody/parsing/detail_dmd_parser.cc, multibody/parsing/detail_strongly_connected_components.h, multibody/parsing/model_directives.h, multibody/parsing/parsing_doxygen.h, multibody/parsing/test/detail_collision_filter_group_resolver_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_strongly_connected_components_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/process_model_directives_test.cc, multibody/parsing/test/process_model_directives_test/collision_filter_group.dmd.yaml, multibody/parsing/test/sdf_parser_test/collision_filter_group_parsing_test/test.sdf, multibody/parsing/test/urdf_parser_test/collision_filter_group_parsing_test.urdf
This patch allows collision filter groups to add the members of other groups by naming the group, instead of (previously) re-iterating all of the member links.
Since groups naming other groups induces an arbitrary graph at resolution time, do the proper graph for reasonably efficient resolution. Graph cycles are permitted.
Implement and test parsing support in URDF, SDFormat, and Drake Model Directives.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20925)
=> [parsing] Add collision filter member groups

systems/primitives/discrete_derivative.cc, systems/primitives/discrete_derivative.h, systems/primitives/discrete_time_delay.h, systems/primitives/first_order_low_pass_filter.cc, systems/primitives/integrator.cc, systems/primitives/multilayer_perceptron.cc, systems/primitives/random_source.cc, systems/primitives/zero_order_hold.h
Certain public methods of various primitive systems use a context without checking its validity. This can lead to downstream errors, such as the one encountered in #20945. I've gone through all the primitive systems and added context validation to the cases where it's not being checked, but values from the context are being used.
Closes: #20945.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20958)
=> Primitives context checks

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
This is an attempt to provide an API where users can plan through a sequence of vertices in GCS trajectory optimization.
While GraphOfConvexSets::SolveConvexRestriction takes in a list of edges, it turns out using the edges in the Subgraph class are not as straightforward as the vertices since the edges are often automatically connected.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20895)
=> Added solving a path via convex restriction

bindings/pydrake/all.py, bindings/pydrake/visualization/visualization_py.cc
When downstream code invokes meldis (or similar) using runpy, they would see this warning: `RuntimeWarning: 'pydrake.visualization.meldis' found in sys.modules after import of package 'pydrake.visualization', but prior to execution of 'pydrake.visualization.meldis'; this may result in unpredictable behaviour`.
We can avoid that by importing the command-line modules during all.py instead of during their parent module's import.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20968)
=> [py visualization] Avoid runpy warning due to import order

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/plant/multibody_plant.h, multibody/plant/test/floating_body_test.cc, multibody/tree/BUILD.bazel, multibody/tree/ball_rpy_joint.h, multibody/tree/joint.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/quaternion_floating_joint.h, multibody/tree/quaternion_floating_mobilizer.cc, multibody/tree/quaternion_floating_mobilizer.h, multibody/tree/rpy_floating_joint.cc, multibody/tree/rpy_floating_joint.h, multibody/tree/rpy_floating_mobilizer.cc, multibody/tree/rpy_floating_mobilizer.h, multibody/tree/test/quaternion_floating_mobilizer_test.cc, multibody/tree/test/rpy_floating_joint_test.cc, multibody/tree/test/rpy_floating_mobilizer_test.cc
Adds RpyFloatingJoint for use in MultibodyPlant. This joint blends the features of BallRpyJoint and QuaternionFloatingJoint. The new joint is implemented using the existing RpyFloatingMobilizer.
This PR also generalizes the notion of a floating joint since there are now two kinds. Previously MbP assumed that if a body was floating it must be on a QuaternionFloatingJoint; that's no longer true. I added SetDefaultPose() and GetDefaultPose() to the Joint base class so that we don't need to know what kind of floating joint we've got.
This PR deals only in adding the new joint as an MbP API as needed for #20225 (new topology code). It does not attempt to make it accessible through the various file formats. See issue #19165.
There are also some minor cleanups in QuaternionFloatingJoint docs for …
=> [multibody] Add rpy_floating_joint as an alternate to quaternion_floating_joint

bindings/pydrake/common/test/yaml_typed_test.py, bindings/pydrake/common/yaml.py, common/yaml/test/example_structs.h, common/yaml/test/json_test.cc, common/yaml/test/yaml_node_test.cc, common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_node.cc, common/yaml/yaml_node.h, common/yaml/yaml_read_archive.h, common/yaml/yaml_write_archive.cc, common/yaml/yaml_write_archive.h, geometry/test/meshcat_params_test.cc, tools/workspace/yaml_cpp_internal/patches/emit-local-tag.patch
This is necessary for C++ code to be able to parse the YAML syntax used in #20920.
The general idea is that when a `std::variant<>` (or `typing.Union`) meets YAML, we want use the YAML tag to disambiguate which type is being used in the document.  For user-defined types, we can just say `!MySubStruct` can call it a day.  For primitive types, there is already a tag convention that we need to follow: the "JSON schema" tags.  Using those tags requires special code paths, so I waited to implement it until we needed it.  Now we need it.
YAML processing rules also have a bunch of language about how to _infer_ a tag when none is provided.  So far, we're not going to support that usage; instead we'll always require the YAML document to write down a specific type.
- - - …
=> [yaml] Improve variant support for primitive types

tools/wheel/image/setup.py, tools/wheel/wheel_builder/common.py, tools/wheel/wheel_builder/linux.py, tools/wheel/wheel_builder/macos.py
Add logic to the wheel builder to set the current locale to a UTF-8 locale. This should ensure that any IPC happens in UTF-8 as opposed to just hoping that the system locale is UTF-8. Also, modify some file I/O to always specify the intended encoding.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20640)
=> Enforce UTF-8 during wheel builds

multibody/topology/BUILD.bazel, multibody/topology/forest.h, multibody/topology/graph.h, multibody/topology/link_joint_graph.cc, multibody/topology/link_joint_graph.h, multibody/topology/link_joint_graph_defs.h, multibody/topology/link_joint_graph_inlines.h, multibody/topology/link_joint_graph_joint.h, multibody/topology/link_joint_graph_link.h, multibody/topology/spanning_forest.cc, multibody/topology/spanning_forest.h, multibody/topology/test/link_joint_graph_test.cc
First PR in a chain to get #20225 merged in digestible pieces.
This contains a skeleton of the LinkJointGraph, with the full structure and documentation in place but minimal functionality and most of the APIs left out. There is also a stripped-down SpanningForest here which can be "built" and "cleared" but doesn't do anything.
Before reviewing this PR, please read the PR comments in #20225 to get the big picture. The main things requiring review in this smaller PR are:
- the overall design
- the administrative functionality: copy and move, modeling and unmodeling, basic setters and getters, etc.
- comments
- adequacy of unit tests
- whether this is a reasonable way to gradually introduce a big chunk of code into Drake
Please refer freely to #20225 to see where this is headed.
- - -
This …
=> [multibody] Adds LinkJointGraph skeleton

tools/workspace/openusd_internal/BUILD.bazel
Amends https://github.com/RobotLocomotion/drake/pull/20923.
[linux-jammy-unprovisioned-gcc-bazel-nightly-everything-release](https://drake-jenkins.csail.mit.edu/view/Production/job/linux-jammy-unprovisioned-gcc-bazel-nightly-everything-release/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20994)
=> [workspace] Temporarily disable OpenUSD testing

bindings/pydrake/multibody/inverse_kinematics_py_differential.cc, bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py, multibody/inverse_kinematics/differential_inverse_kinematics_integrator.cc, multibody/inverse_kinematics/differential_inverse_kinematics_integrator.h, multibody/inverse_kinematics/test/differential_inverse_kinematics_integrator_test.cc
Adds support for passing a relative frame A into the constructor. Deprecates the X_WE_desired input port in favor of the more general X_AE_desired input port.
Resolves #19580.
+@iantheengineer for feature review, please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20973)
=> Support relative frames in DifferentialInverseKinematicsIntegrator

bindings/pydrake/common/cpp_param.py, bindings/pydrake/common/test/cpp_template_test.py, bindings/pydrake/common/test/serialize_pybind_test.py, bindings/pydrake/common/test/yaml_typed_test.py, bindings/pydrake/common/yaml.py, bindings/pydrake/gym/_drake_gym_env.py, bindings/pydrake/systems/test/custom_test.py, bindings/pydrake/visualization/test/meldis_test.py, common/overloaded.h, common/schema/rotation.cc, common/schema/stochastic.cc, common/test/overloaded_test.cc, common/value.h, common/yaml/yaml_node.cc, geometry/meshcat.cc, geometry/meshcat_visualizer.cc, geometry/render_gl/test/multithread_safety_test.cc, geometry/test/meshcat_websocket_client.py, multibody/meshcat/joint_sliders.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc, multibody/tree/element_collection.cc, multibody/tree/scoped_name.cc, systems/analysis/radau_integrator.cc, systems/sensors/camera_config_functions.cc, tools/performance/fixture_memory_yes.cc, tools/workspace/pybind11/mkdoc.py
This reverts commit 6b32a81c.
No release notes.  We'll use #20952 to announce this change, overall.
See also #20970 for one more C++20-related cleanup.
Requires:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20965)
=> Remove compatibility shims for Focal

tools/ubuntu-focal.bazelrc
This file was removed in #20964 but is still needed to run wheel builds on Focal.  This can be removed when #21007 is resolved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21020)
=> [tools] Add empty file to allow CI wheel builds on Focal

geometry/optimization/BUILD.bazel, geometry/optimization/geodesic_convexity.cc, geometry/optimization/geodesic_convexity.h, geometry/optimization/test/geodesic_convexity_test.cc, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Allows the construction of edges between subgraphs while restricting the edges to be contained in a subspace. Completes #20449.
Still need to add test cases. Will request a reviewer once that is done.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20886)
=> Implement wraparound edges together with the subspace machinery.

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Often we build very large and complicated graphs. Rather than having to rebuild it each to for a new start and goal configuration, we could make use of the existing graph by removing and creating a new subgraph and connecting it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21006)
=> Enable removal of subgraphs

multibody/parsing/detail_mujoco_parser.cc
The bazel command was not quite runnable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21044)
=> Fix stl2obj recommendation text in mujoco parser

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/BUILD.bazel, multibody/parsing/package_map.cc, multibody/parsing/package_map.h, multibody/parsing/test/detail_path_utils_test.cc, multibody/parsing/test/package_map_test.cc
Adds a new PackageMap sugar function that takes a string url as input and returns the resolved path.
Resolves #20255.
+@jwnimmer-tri for feature review, please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21042)
=> Implements PackageMap::ResolveUrl()

tools/workspace/boost_internal/BUILD.bazel, tools/workspace/boost_internal/repository.bzl, tools/workspace/com_github_nelhage_rules_boost_internal/BUILD.bazel, tools/workspace/com_github_nelhage_rules_boost_internal/patches/iostreams.patch, tools/workspace/com_github_nelhage_rules_boost_internal/repository.bzl, tools/workspace/default.bzl, tools/workspace/github.bzl, tools/workspace/metadata.py, tools/workspace/openusd_internal/BUILD.bazel, tools/workspace/openusd_internal/defs.bzl
Also add `com_github_nelhage_rules_boost_internal` for its BUILD file.
These two repositories are not enabled by default. They are only used when `--WITH_USD=ON` is enabled.
Towards #20898. Amends #20923.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21037)
=> [workspace] Add boost_internal

tools/workspace/drake_models/repository.bzl, tutorials/BUILD.bazel, tutorials/hydroelastic_contact_nonconvex_mesh.ipynb, tutorials/index.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20774)
=> [tutorials] Hydroelastic Contact: Nonconvex Mesh

multibody/parsing/BUILD.bazel, multibody/parsing/detail_usd_parser.cc, multibody/parsing/detail_usd_parser.h, multibody/parsing/detail_usd_parser_off.cc, multibody/parsing/test/detail_usd_parser_test.cc, tools/workspace/openusd_internal/BUILD.bazel, tools/workspace/openusd_internal/defs.bzl, tools/workspace/openusd_internal/package.BUILD.bazel, tools/workspace/openusd_internal/patches/no_gnu_ext.patch, tools/workspace/openusd_internal/repository.bzl
This turns up a slew of previously-unseen errors in our OpenUSD build system, which we also fix here.
Towards #20898.  Amends #20923.
Requires:
Sample command for local testing:
```
bazel test --define=WITH_USD=ON //multibody/parsing:detail_usd_parser_test 
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21028)
=> [parsing] Add UsdParser smoke test stub

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
Previously, we failed when parsing https://github.com/google-deepmind/mujoco_menagerie/blob/d1e7d678c986788c8597e88111b4d94f000cf31e/aloha/scene.xml with a message of the form "already has a geometry named geom0".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21045)
=> mujoco parser assigns unique names to default geometries

bindings/pydrake/visualization/_meldis.py, geometry/meshcat_visualizer.cc, geometry/meshcat_visualizer_params.h, geometry/test/meshcat_visualizer_test.cc, visualization/test/visualization_config_functions_test.cc, visualization/visualization_config.h, visualization/visualization_config_functions.cc
When using `VisualizationConfig`, the default color for proximity geometries was 100% red with 50% alpha.
In rendering, it's generally a bad idea to define albedo (aka diffuse) color at 100%, and bad for red particularly. This has been backed off to 80% red.
By defining the *color* to be 50% transparent, the alpha slider for proximity can no longer make it opaque.
This changes the default configuration to have the same effect (red proximity geometries with 50% transparency), but defaults the *color* to be opaque and configures the slider to be at 50% so full opacity is now available.
The old behavior can be achieved by changing the default_proximity_color back to [1, 0, 0, 0.5] and the initial_proximity_alpha to 1.
Resolves #20984
- - - …
=> [meshcat] Change mechanism for proximity geometry transparency

geometry/meshcat.cc, geometry/meshcat_types_internal.h, geometry/test/meshcat_visualizer_test.cc
When `Meshcat` sends a Drake-generated mesh (as indicated by a call to a `SetTriangleMesh()` variant), that mesh's material is configured to render the mesh faceted.
The default behavior of smoothing them is unhelpful. Meshes of strongly angular objects (e.g., boxes) have their creases smoothed over. It can be difficult to fully understand the topology of the generated mesh with smoothing.
The types of meshes that will be affected:
- meshes representing hydroelastic proximity geometries.
- The hydroelastic contact surfaces
- Convex hulls (see issue #20618)
Resolves #20983
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21021)
=> [meshcat] Drake-generated meshes render faceted in meshcat

geometry/optimization/vpolytope.cc
This is a temporary fix for the bug in #21055, so that exceptions can be caught instead of the program segfaulting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21060)
=> Prevent segfaults in `VPolytope` by checking square matrix

common/find_resource.cc, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/detail_sdf_parser.cc
Remove/replace some home-made implementations in favor new library methods.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21062)
=> Use string::{starts,ends}_with() from C++20

tools/install/bazel/repo_template.bzl, tools/workspace/drake_models/repository.bzl
Companion PR: https://github.com/RobotLocomotion/models/pull/33.
To check that this is satisfactory, we can run the following command:
```
bazel run //tools:model_visualizer -- package://drake_models/tri_homecart/homecart.dmd.yaml
````
The display should be the same on master versus this PR, except that the lighting comes out more nicely.  All of the shapes should still be facing the same way, and all of the textures (metal vs wood) should be the same.
Towards #20932.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21039)
=> [workspace] Upgrade drake_models to latest commit

doc/_pages/buildcop.md, doc/_pages/jenkins.md, doc/_pages/release_playbook.md, tools/ubuntu-focal.bazelrc
Reverts RobotLocomotion/drake#21020
Closes #21007
Wheels are building on Jammy, the Focal workaround can be removed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21069)
=> Revert "[tools] Add empty file to allow CI wheel builds on Focal"

geometry/proximity_properties.cc, geometry/proximity_properties.h, geometry/test/proximity_properties_test.cc
kSoft was probably uncontroversial when it was chosen, but no longer aligns with our public API and documentation language. Introduce an alias kCompliant, and add enum<=>string conversions that use the "compliant" language.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21065)
=> [geometry] Give HydroelasticType a kCompliant alias

tools/workspace/new_release.py, tools/workspace/xmlrunner_py/repository.bzl
Flag it as using tags only, not GitHub release announcements.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21071)
=> [workspace] Upgrade xmlrunner_py to latest release 3.2.0

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/test/hpolyhedron_test.cc
This PR implements a new constructor for `HPolyhedron`, that takes in a `MathematicalProgram`, asserts that it indeed represents an LP, and sets up a single HPolyhedron representation of the entire feasible set.
cc @shrutigarg914 
+@hongkai-dai for feature review, please!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21027)
=> Construct HPolyhedron from Feasible Set of Linear Program

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/test/graph_of_convex_sets_test.cc
Implements support for `RotatedLorentzConeConstriants` in GCS edges and vertices.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21001)
=> Add support for LorentzConeConstraint and RotatedLorentzConeConstraint in GraphOfConvexSets edges and vertices

geometry/BUILD.bazel, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/internal_geometry.h, geometry/meshcat_visualizer.cc, geometry/proximity/BUILD.bazel, geometry/proximity/polygon_to_triangle_mesh.cc, geometry/proximity/polygon_to_triangle_mesh.h, geometry/proximity/test/polygon_to_triangle_mesh_test.cc, geometry/proximity_engine.cc, geometry/proximity_engine.h, geometry/render/test/box.sdf, geometry/scene_graph_inspector.cc, geometry/scene_graph_inspector.h, geometry/test/geometry_state_test.cc, geometry/test/internal_geometry_test.cc, geometry/test/meshcat_visualizer_test.cc, geometry/test/proximity_engine_test.cc, geometry/test/scene_graph_inspector_test.cc
- GeometryState computes the convex hull (and reports it).
- InternalGeometry stores the convex hull.
- MeshcatVisualizer uses the convex hull when appropriate.
- ProximityEngine reports if it would use a convex hull.
- SceneGraphInspector reports possible convex hull.
- New code converts from polygonal surface mesh to triangle surface mesh.
- update box.sdf to include collision geometry.
resolves #20618
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21061)
=> SceneGraph provides the convex hull for visualization

CTestCustom.cmake.in
Fixes failing CI jobs:
- https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-arm-sonoma-clang-cmake-nightly-everything-release/85/
- https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-arm-sonoma-clang-cmake-nightly-release/86/
- https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-arm-ventura-clang-cmake-nightly-everything-release/292/
- https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/mac-arm-ventura-clang-cmake-nightly-release/294/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21102)
=> CMake builds: Treat SyntaxWarning as a warning not an error

tools/workspace/rules_rust/patches/import_cycle.patch, tools/workspace/rules_rust/repository.bzl
The full extent of https://github.com/bazelbuild/rules_rust/issues/2383 is not actually fixed, so we need to work around it here.
Towards #21103 and #21054.
The manual testing recipe here is `bazel test //... --config=lint` on Ubuntu when using Bazel 7.0.  On master, it barfs an error about a BUILD file cycle[1]; with this PR, it passes.
One good way to try that is to use `bazelisk.py test //... --config=lint` via [bazelisk.py](https://github.com/bazelbuild/bazelisk/blob/master/bazelisk.py) to use a temporary bazel version, by changing the `.bazeliskrc` to point to 7.0.2 like we have in #21003.
The intent behind landing this patch now (ahead of Drake's full Bazel 7 transition), is to make it easier to test out Bazel 7 in downstream CI, and to make any commit-revert war over #21103 as …
=> [workspace] Patch rules_rust for Bazel 7 compatibility

tools/workspace/gflags/patches/bazel7.patch, tools/workspace/gflags/repository.bzl
Towards #21054.
FYI https://bazel.build/reference/be/c-cpp#cc_library.include_prefix
It is not entirely clear to me why `include_prefix` is causing trouble here.  With Bazel 7 and some mix of bzlmod and workspaces, sometimes it seems like "which package am I?" just gets bent out of shape.  In any case, a very straightfoward spelling of "generate files using the names you want to be known by" seems to make everything happy again.
I'll also xref https://github.com/gflags/gflags/issues/339 here -- when we upstream this, I think it would resolve that issue, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21106)
=> [workspace] Patch gflags for Bazel 7 compatibility

CMakeLists.txt, WORKSPACE, doc/_pages/from_source.md, tools/ubuntu-jammy.bazelrc, tools/ubuntu-noble.bazelrc, tools/workspace/cc/repository.bzl
GCC >= 11 (now that Focal is gone).
Clang >= 14 (now that Focal is gone).
Bazel >= 6.0 (amends cdeb0c61, which broke bazel < 6).
Remove some legacy cc_toolchain code for earlier bazel versions, that no longer works on Bazel >= 7 on macOS.
Towards #21103 and #21054.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21107)
=> [tools] Bump minimum supported versions

WORKSPACE, cmake/WORKSPACE.in, tools/cc_toolchain/BUILD.bazel
For macOS users building from source, Bazel 7 now requires a snippet to be added directly to `WORKSPACE` (not our `default.bzl`), or to the `MODULE.bazel`. Downstream projects using `drake_bazel_external` on macOS will need to mimic this same change (or similar), per instructions at https://github.com/bazelbuild/apple_support#toolchain-setup.
This is required in order to compile our Objective-C dependencies.
Towards #21103 and #21054.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21110)
=> [workspace] Adjust apple_support for Bazel 7 compatibility

tools/workspace/github.bzl
Unlike most other functions in Bazel, we can't pass `None` to `stripPrefix` to select the default behavior (of no stripping). We actually need to omit the kwarg name entirely. Adjust `github_release_attachments()` logic to hide this irregularity, to allow for extracting attachments that don't need any prefix stripped away.
Towards #20935.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21111)
=> [tools] Fix github.bzl for extracting attachments without a prefix

WORKSPACE, cmake/WORKSPACE.in, tools/cc_toolchain/BUILD.bazel
Dear @jwnimmer-tri,
The on-call build cop, @BetsyMcPhail, believes that your PR #21110 may have
https://drake-jenkins.csail.mit.edu/job/linux-jammy-unprovisioned-gcc-bazel-continuous-mirror-to-s3/457/
now. You can then fix the problem at your leisure, and send a new PR to
reinstate your change.
If you believe …
=> Revert "[workspace] Adjust apple_support for Bazel 7 compatibility"

tools/BUILD.bazel, tools/bazel.rc, tools/ubuntu-jammy.bazelrc, tools/ubuntu-noble.bazelrc
Reverts 35ca15439c6d63a3c60310df391ea2f34d00145f.
Something here is incompatible with Bazel 7.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21118)
=> Revert "[workspace] Build OpenUSD in macOS CI"

planning/iris/BUILD.bazel, planning/iris/test/iris_from_clique_cover_test.cc
see title
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21128)
=> Bumped test numbers for iris_from_clique_cover_test to prevent timeout on nightly build 

tools/lint/BUILD.bazel, tools/lint/__init__.py, tools/lint/install_lint.bzl, tools/lint/library_lint.bzl, tools/lint/python_lint.bzl, tools/skylark/drake_py.bzl
Update linters' BUILD rules to match.
This fixes some backcompat problems with Bazel 7.1.0.
---
Towards #21123.  (Follow-up to #21054, in a way.)
FYI Anzu CI has succeeded on this PR already.
We've had in mind to opt-out of `legacy_create_init` for a while.  I don't know exactly why Bazel 7.1 is being picky about it now, but that's fine -- we should just turn it off in the first place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21126)
=> [tools] Disable legacy_create_init by default

systems/framework/cache_doxygen.h, systems/framework/context.cc, systems/framework/context.h, systems/framework/dependency_tracker.cc, systems/framework/dependency_tracker.h, systems/framework/discrete_values.h, systems/framework/state.h, systems/framework/test/dependency_tracker_test.cc, systems/framework/test/diagram_context_test.cc
This PR prevents "out of date" notifications for state variable changes from being propagated in systems that don't have the requisite state variables.
There are just two changes:
- We add a "suppress_notifications" flag to DependencyTracker that prevents further propagation of notifications to subscribers
- At Context allocation, we suppress notifications from dependency trackers for non-existent state variables.
This prevents, for example, a "continuous state variables changed" notification from affecting configuration_ticket in a system that has only discrete state variables (as is commonly the case for MultibodyPlant).
The diagram_context_test & dependency_tracker_test are updated to reflect the new expectations for notification propagation.
The cache implementation document is …
=> Disable unused dependency trackers for better performance

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc
This adds a binding for [SpatialInertia::CalcPrincipalSemiDiametersAndPoseForSolidEllipsoid](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_spatial_inertia.html#aba6d2ff81ae140bb2c4249933a51597c).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21149)
=> Bind CalcPrincipalSemiDiametersAndPoseForSolidEllipsoid

planning/trajectory_optimization/BUILD.bazel, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
GCS trajectories that are calculated from `GcsTrajectoryOptimization` with fully revolute joints are not continous in Euclidean space - they may have integer multiples of 2π jumps across the segments. We want continous trajectories in Euclidean space so we can, for example, send them to a robot driver.
This PR features a new static method `GcsTrajectoryOptimization::UnWrapToContinousTrajectory` with unit tests.
Example:
+@cohnt for feature review
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21137)
=> Unwrap gcs trajs with continous revolute joints to continous Euclidean space

multibody/parsing/test/detail_collision_filter_group_resolver_test.cc
This clause was missed in #17241.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21148)
=> [parsing] Add a missed test for CollsionFilterGroupResolver

bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/BUILD.bazel, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
The GcsTrajectoryOptimization tests run with Clarabel. Since the solver is included by default, we no longer need to check for the availability of Gurobi and Mosek.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21164)
=> Remove Gurobi and Mosek solver dependencies

doc/_pages/code_review_checklist.md, doc/_pages/from_binary.md, doc/_pages/from_source.md, doc/_pages/installation.md, doc/_pages/jenkins.md, doc/_pages/release_playbook.md, tools/release_engineering/download_release_candidate.py
Phase 2 of https://github.com/RobotLocomotion/drake/issues/21140.
- All mac-x86 packaging jobs have been removed, only wheel remains.
- Release playbook: fix up the release artifiact count, the focal drop missed updating some of these.  Current `master` on v1.27.0 had 33 artifacts, with the changes here 30 will be downloaded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21160)
=> [tools,doc] Remove most mac-x86

planning/trajectory_optimization/BUILD.bazel
Clarabel is slower than Mosek, which results in the more extensive memory check test to time out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21172)
=> Set shard_count for slow test

multibody/topology/BUILD.bazel, multibody/topology/graph.h, multibody/topology/link_joint_graph.cc, multibody/topology/link_joint_graph.h, multibody/topology/link_joint_graph_defs.h, multibody/topology/link_joint_graph_inlines.h, multibody/topology/link_joint_graph_joint.h, multibody/topology/link_joint_graph_link.h, multibody/topology/link_joint_graph_loop_constraint.h, multibody/topology/spanning_forest.cc, multibody/topology/spanning_forest.h, multibody/topology/test/link_joint_graph_test.cc, multibody/topology/test/spanning_forest_test.cc
This is the second installment towards #20225, following PR #20806.
Introduces more of the LinkJointGraph functionality and adds tests. MultibodyPlant continues to use its old topology code unchanged. There are no user-visible changes yet.
Additions here:
- AddJoint() and related functions
- Defines the LoopConstraint subclass and minimal related infrastructure.
- Introduces Link Composite API
- Adds a _tiny_ bit more BuildForest() functionality: make the World composite
- Splits tests into ones that need only LinkJointGraph definitions and those that also need SpanningForest
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21142)
=> [multibody] Fill in more LinkJointGraph functionality

geometry/proximity/deformable_contact_internal.cc, geometry/proximity/deformable_field_intersection.cc, geometry/proximity/deformable_field_intersection.h, geometry/proximity/test/deformable_contact_internal_test.cc, geometry/proximity/test/deformable_field_intersection_test.cc, geometry/query_results/deformable_contact.cc, geometry/query_results/deformable_contact.h
Maintain the convention that the deformable geometry with the smaller GeometryId is regarded as "geometry A" and the deformable geometry with the larger GeometryId is regarded as "geometry B" in DeformableContactSurface.
Fix #20613 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21165)
=> [geometry] Enforece deformable on deformable convention

planning/trajectory_optimization/BUILD.bazel, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Even with a shard_count, the memory checking CI takes 15-30 minutes on certain test cases. Requiring both MOSEK and Gurobi to be enabled brings the total test down to about a minute. See the results below with the bazel configurations:
Without the guard in this PR:
| Enabled Bazel Configurations  | Runtime    |
| ----------------------------- | ---------- |
| Memcheck and MOSEK and Gurobi | 2 minutes  |
| Memcheck and Gurobi           | 5 minutes  |
| Memcheck and MOSEK            | 8 minutes  |
| Memcheck                      | 15 minutes |
With the guard on:
| Enabled Bazel Configurations  | Runtime   |
| ----------------------------- | --------- |
| Memcheck and MOSEK and Gurobi | 2 minutes |
| Memcheck and Gurobi           | 36 s      |
| Memcheck and MOSEK            | 226 s     |
| …
=> Require MOSEK and Gurobi during memory check

bindings/pydrake/solvers/solvers_py_evaluators.cc, bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, solvers/constraint.cc, solvers/constraint.h, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/constraint_test.cc, solvers/test/csdp_test_examples.cc, solvers/test/mathematical_program_test.cc
Use std::vector<Eigen::MatrixXd> instead of std::vector<Eigen::Ref<const Eigen::MatrixXd>> as the latter can produce memory garbage.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21152)
=> Change the type of F in LinearMatrixInequalityConstraint.

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
Adds a binding for [MultibodyPlant::EvalBodySpatialAccelerationInWorld](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html#a725008fd74cc0c6c30e938eeaaf902e2).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21161)
=> Bind EvalBodySpatialAccelerationInWorld

geometry/BUILD.bazel, geometry/scene_graph_config.cc, geometry/scene_graph_config.h, geometry/test/scene_graph_config_test.cc
Introduce some public API vocabulary toward implementing easier configuration of hydroelastic contact.
This (so far) is just an island and not yet integrated; future patches will connect it to SceneGraph and implement new functionality.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21129)
=> [geometry] Introduce SceneGraphConfig

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Constraining the velocity, acceleration, jerk, etc. to zero between the edges of subgraphs can be formulated as a convex equality constraint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21180)
=> [GCSTrajOpt] Add zero derivative constraints

geometry/BUILD.bazel, geometry/shape_specification.cc, geometry/shape_specification.h, geometry/test/shape_specification_test.cc, multibody/tree/BUILD.bazel, multibody/tree/geometry_spatial_inertia.cc
Code that needs to operate on concrete Shape subclasses can now do so without needing to implement an entire Reifier.
Two samples are included in this PR.  For more examples of how this would be used, refer to the WIP commits at https://github.com/jwnimmer-tri/drake/commits/shape-visit/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21181)
=> [geometry] Add Shape::Visit

bindings/pydrake/common/serialize_pybind.h, bindings/pydrake/geometry/BUILD.bazel, bindings/pydrake/geometry/geometry_py_render.cc, bindings/pydrake/geometry/test/render_test.py, geometry/render_vtk/BUILD.bazel, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/internal_render_engine_vtk.h, geometry/render_vtk/render_engine_vtk_params.h, geometry/render_vtk/test/render_engine_vtk_params_test.cc
Add RenderVtkParams configuration for what to silence.
Fix serialize_pybind to admit the full vector and map template signatures.
Towards #20935.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21183)
=> [render_vtk] Silence gltf basisu extension warnings by default

geometry/geometry_file_formats_doxygen.h
We also refresh some glTF-related details (e.g., VTK support).
Towards #20935.
+@SeanCurtis-TRI for both(?) reviews, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21193)
=> [doc] Geometry "supported file formats" explains ktx2 textures

geometry/scene_graph_config.h, geometry/test/scene_graph_config_test.cc
This hackery was obviated by #21147.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21196)
=> [geometry] Remove now-unneeded fallback flag

geometry/optimization/BUILD.bazel, geometry/optimization/cartesian_product.cc, geometry/optimization/cartesian_product.h, geometry/optimization/minkowski_sum.cc, geometry/optimization/minkowski_sum.h, geometry/optimization/point.cc, geometry/optimization/point.h, geometry/optimization/test/cartesian_product_test.cc, geometry/optimization/test/hpolyhedron_test.cc, geometry/optimization/test/hyperellipsoid_test.cc, geometry/optimization/test/minkowski_sum_test.cc, geometry/optimization/test/point_test.cc, geometry/optimization/test/vpolytope_test.cc, geometry/optimization/test_utilities.cc, geometry/optimization/test_utilities.h
When given an unsupported shape, provide an error message with the full details of the wrong-shape (e.g., dimensions) and what we expected. Remove gratuitous reifier inheritance for one kind of shape.
Refactor test utility for less boilerplate, and fix erroneous public visibility.
(This is part of a slow-moving PR train to rid ourselves of unnecessary reifier-related complexity.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21197)
=> [optimization] Tidy up ConvexSet constructors for a single shape

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/tree_py.cc, bindings/pydrake/multibody/tree_py.h, bindings/pydrake/multibody/tree_py_inertia.cc
This will help build speed (toward #20491), and is necessary to solve ordering problems with which classes are loaded in what order (toward #21198).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21200)
=> [pydrake] Split MbT inertia bindings into their own file

planning/iris/BUILD.bazel, planning/iris/iris_from_clique_cover.cc, planning/iris/test/iris_from_clique_cover_test.cc
Previously the error was an unhelpful throw from HPolyhedron saying some set was unbounded (which is confusing for a method whose goal is to use complex logic to assemble new hpolyhedron). We can fail-fast on this one and give a much more clear/specific error message.
cc @AlexandreAmice @wernerpe
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21207)
=> Improve error message when calling iris clique cover without joint limits

tools/workspace/mosek/package.BUILD.bazel
The [build log](https://drake-jenkins.csail.mit.edu/job/linux-arm-jammy-unprovisioned-gcc-bazel-experimental-release/18/) of this PR on arm64 shows no more MOSEK errors.  Compare with [build log of existing conditions](https://drake-jenkins.csail.mit.edu/job/linux-arm-jammy-unprovisioned-gcc-bazel-experimental-release/17/) to see what this is fixing.
Towards #13514.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21206)
=> [workspace] Fix MOSEK TBB glob on linuxaarch64

geometry/BUILD.bazel, geometry/internal_geometry.cc, geometry/make_mesh_for_deformable.cc, geometry/make_mesh_for_deformable.h, geometry/test/make_mesh_for_deformable_test.cc, geometry/test/scene_graph_test.cc
This is more straightforward.
(This is part of a slow-moving PR train to rid ourselves of unnecessary reifier-related complexity.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21209)
=> [geometry] Port MakeMeshForDeformable to Shape::Visit

multibody/plant/test/atlas_with_fixed_joints.urdf
In https://github.com/RobotLocomotion/models/issues/44 we will be changing around some of our mesh models.  Since this test case doesn't care about visualization, it's easier to prune them away than try to keep this forked file in sync during porting.
Related to #13954.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21212)
=> [multibody] Remove unused brittle mesh paths from unit test

bindings/pydrake/solvers/solvers_py_semidefinite_relaxation.cc, bindings/pydrake/solvers/test/semidefinite_relaxation_test.py, math/matrix_util.h, solvers/semidefinite_relaxation.cc, solvers/semidefinite_relaxation.h, solvers/test/semidefinite_relaxation_test.cc
Add the ability to specify which groups of variables are jointly relaxed in MakeSemidefiniteRelaxation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21043)
=> Add Optional Sparsity Groups to MakeSemidefiniteRelaxation

geometry/query_results/deformable_contact.cc, geometry/query_results/deformable_contact.h, geometry/query_results/test/deformable_contact_test.cc, multibody/plant/BUILD.bazel, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/test/deformable_driver_contact_kinematics_test.cc
Refactor ContactData computation to facilitate using code from deformable vs. rigid contact.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21187)
=> Support deformable vs. deformable contact
