RobotLocomotion/drake

- examples/hardware_sim/BUILD.bazel
- examples/hardware_sim/README.md
- examples/hardware_sim/example_scenarios.yaml
- examples/hardware_sim/robot_commander.py
- examples/hardware_sim/test/robot_commander_test.py
Toward #20221 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20283)
> Actuate the iiwa in the hardware_sim example

- examples/multibody/acrobot/BUILD.bazel
- examples/multibody/cylinder_with_multicontact/BUILD.bazel
- examples/multibody/inclined_plane_with_body/BUILD.bazel
- examples/multibody/pendulum/BUILD.bazel
- examples/multibody/rolling_sphere/BUILD.bazel
- examples/scene_graph/BUILD.bazel
- geometry/BUILD.bazel
- geometry/profiling/BUILD.bazel
- geometry/render_gltf_client/BUILD.bazel
- manipulation/kuka_iiwa/BUILD.bazel
- manipulation/schunk_wsg/BUILD.bazel
- multibody/plant/BUILD.bazel
- systems/lcm/BUILD.bazel
Towards #20203.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20308)
> [lcm] Remove spurious deps from library code

- bindings/pydrake/systems/lcm_py.cc
- bindings/pydrake/systems/test/lcm_test.py
- manipulation/kuka_iiwa/build_iiwa_control.cc
- manipulation/kuka_iiwa/build_iiwa_control.h
- manipulation/kuka_iiwa/iiwa_driver_functions.cc
- manipulation/kuka_iiwa/test/build_iiwa_control_test.cc
- manipulation/kuka_iiwa/test/iiwa_driver_functions_test.cc
- systems/lcm/BUILD.bazel
- systems/lcm/lcm_buses.h
- systems/lcm/lcm_config_functions.cc
- systems/lcm/lcm_config_functions.h
- systems/lcm/test/lcm_config_functions_test.cc
Towards #20055.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20247)
> [systems/lcm] Add protocol for opting out of LCM messaging

- bindings/pydrake/geometry/geometry_py_scene_graph.cc
- bindings/pydrake/geometry/test/scene_graph_test.py
- geometry/geometry_state.cc
- geometry/geometry_state.h
- geometry/scene_graph.cc
- geometry/scene_graph.h
- geometry/test/scene_graph_test.cc
Remove a renderer from SceneGraph.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20319)
> Add SceneGraph::RemoveRenderer().

- tools/workspace/vtk_internal/patches/rendering_opengl2_nobacktrace.patch
- tools/workspace/vtk_internal/repository.bzl
- tools/workspace/vtk_internal/settings.bzl
Cull a dozen more files from `vtksys`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20335)
> [vtk] Remove dead code

- tools/install/libdrake/test/exported_symbols_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20334)
> [tools] Handle unusual `readelf` output in exported_symbols_test

- bindings/pydrake/visualization/BUILD.bazel
- bindings/pydrake/visualization/test/model_visualizer_reload_test.py
- bindings/pydrake/visualization/test/model_visualizer_test.py
Closes #19998.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20337)
> [py visualization] Split out flaky visualizer reload test

- bindings/pydrake/systems/pyplot_visualizer.py
- examples/bouncing_ball/bouncing_ball.h
Amends #20114.  Towards #20094.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20338)
> Port more event-handling code to modern API

- multibody/plant/BUILD.bazel
- multibody/plant/contact_results.cc
- multibody/plant/contact_results.h
- multibody/plant/deformable_contact_info.cc
- multibody/plant/deformable_contact_info.h
- multibody/plant/hydroelastic_quadrature_point_data.h
- multibody/plant/test/contact_results_test.cc
- multibody/plant/test/deformable_contact_info_test.cc
Towards #20274
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20301)
> Add DeformableContactInfo to ContactResults

- setup/mac/source_distribution/Brewfile
- setup/ubuntu/source_distribution/packages-focal.txt
- setup/ubuntu/source_distribution/packages-jammy.txt
- tools/wheel/image/packages-focal
- tools/wheel/image/packages-macos
This will be required to build `libjpeg-turbo` from source (#20343).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20353)
> [setup] Add nasm to source prereqs

- bindings/pydrake/systems/framework_py_systems.cc
- bindings/pydrake/systems/test/custom_test.py
- systems/analysis/test/simulator_test.cc
- systems/framework/leaf_system.cc
- systems/framework/leaf_system.h
- systems/framework/test/diagram_test.cc
- systems/framework/test/leaf_system_test.cc
- systems/framework/test/vector_system_test.cc
- systems/framework/vector_system.cc
- systems/framework/vector_system.h
Requires #20114.
See also #20035.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20094)
> [framework] Deprecate LeafSystem update dispatcher overrides

- tools/install/libdrake/test/exported_symbols_test.py
- tools/workspace/vtk_internal/patches/common_core_noutf8.patch
- tools/workspace/vtk_internal/patches/vtkdoubleconversion_hidden.patch
- tools/workspace/vtk_internal/patches/vtkglew_hidden.patch
- tools/workspace/vtk_internal/patches/vtkpugixml_hidden.patch
- tools/workspace/vtk_internal/repository.bzl
- tools/workspace/vtk_internal/settings.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20346)
> [workspace] Build VTK-vendored third-party code with hidden symbols

- setup/ubuntu/binary_distribution/packages-focal.txt
- setup/ubuntu/binary_distribution/packages-jammy.txt
- setup/ubuntu/source_distribution/packages-focal.txt
- setup/ubuntu/source_distribution/packages-jammy.txt
- tools/workspace/default.bzl
- tools/workspace/expat/repository.bzl
As of #19945, Drake no longer needs this at all.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20351)
> [workspace] Deprecate the expat external

- geometry/proximity/deformable_contact_internal.cc
- geometry/proximity/deformable_mesh_intersection.cc
- geometry/proximity/deformable_mesh_intersection.h
- geometry/proximity/test/deformable_contact_internal_test.cc
- geometry/proximity/test/deformable_mesh_intersection_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20347)
> Avoid unnecessary re-computation of deformable sdf

- tools/install/libdrake/test/exported_symbols_test.py
- tools/workspace/abseil_cpp_internal/patches/inline_namespace.patch
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20359)
> [workspace] Fix leaky symbol in abseil_cpp

- manipulation/schunk_wsg/BUILD.bazel
- manipulation/schunk_wsg/build_schunk_wsg_control.cc
- manipulation/schunk_wsg/build_schunk_wsg_control.h
- manipulation/schunk_wsg/schunk_wsg_constants.h
- manipulation/schunk_wsg/schunk_wsg_driver_functions.cc
- manipulation/schunk_wsg/schunk_wsg_lcm.cc
- manipulation/schunk_wsg/schunk_wsg_lcm.h
- manipulation/schunk_wsg/schunk_wsg_plain_controller.h
- manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc
- manipulation/schunk_wsg/schunk_wsg_trajectory_generator.h
- manipulation/schunk_wsg/test/schunk_wsg_controller_test.cc
- manipulation/schunk_wsg/test/schunk_wsg_lcm_test.cc
- manipulation/schunk_wsg/test/schunk_wsg_position_controller_test.cc
- manipulation/schunk_wsg/test/schunk_wsg_trajectory_generator_test.cc
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20329)
> [schunk_wsg] Opt-in to clang-format lint

- solvers/test/diagonally_dominant_dual_cone_matrix_test.cc
- solvers/test/scaled_diagonally_dominant_dual_cone_matrix_test.cc
Amends #20317.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20369)
> add numeric tolerances to test

- multibody/parsing/detail_sdf_parser.cc
- multibody/parsing/test/detail_sdf_parser_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20381)
> [parsing] Support drake:joint involving links in nested models

- tools/workspace/common_robotics_utilities/package.BUILD.bazel
- tools/workspace/voxelized_geometry_tools/package.BUILD.bazel
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20390)
> [workspace] Disable kcov on CRU and VGT tests

- math/autodiff.h
- math/autodiff_gradient.h
- math/bspline_basis.cc
- math/bspline_basis.h
- math/continuous_lyapunov_equation.cc
- math/discrete_lyapunov_equation.cc
- math/eigen_sparse_triplet.h
- math/fast_pose_composition_functions.cc
- math/fast_pose_composition_functions_avx2_fma.cc
- math/fast_pose_composition_functions_avx2_fma.h
- math/gradient.h
- math/gradient_util.h
- math/gray_code.h
- math/jacobian.h
- math/matrix_util.h
- math/quadratic_form.cc
- math/quadratic_form.h
- math/quaternion.h
- math/rigid_transform.cc
- math/rigid_transform.h
- math/roll_pitch_yaw.cc
- math/roll_pitch_yaw.h
- math/rotation_conversion_gradient.h
- math/rotation_matrix.cc
- math/rotation_matrix.h
- math/wrap_to.h
Towards #4843.
(Once enough PRs have landed, the plan is to enable `clang-format-lint` for this directory.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20389)
> [math] Clang-format the non-test files

- common/symbolic/expression/test/substitution_test.cc
- geometry/optimization/test/affine_subspace_test.cc
- geometry/optimization/test/hpolyhedron_test.cc
- geometry/optimization/test/intersection_test.cc
- solvers/test/complementary_problem_test.cc
- solvers/test/mathematical_program_test.cc
- systems/controllers/test/linear_quadratic_regulator_test.cc
- tools/lint/drakelint.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20396)
> [lint] Identify mismatched clang-format-{on,off} comments

- solvers/mathematical_program.cc
- solvers/test/diagonally_dominant_dual_cone_matrix_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20379)
> Update dd and sdd dual cone constraints  to use sparse matrices

- bindings/pydrake/common/test/yaml_typed_test.py
- bindings/pydrake/common/yaml.py
- common/yaml/test/yaml_read_archive_test.cc
- common/yaml/yaml_read_archive.h
Closes #20377.
+@dmcconachie-tri for feature review, please -- or at least to check that the test expectations are as-desired.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20391)
> [yaml] Retain default values when parsing a variant

- math/BUILD.bazel
- math/test/autodiff_test.cc
- math/test/barycentric_test.cc
- math/test/compute_numerical_gradient_test.cc
- math/test/continuous_algebraic_riccati_equation_test.cc
- math/test/convert_time_derivative_test.cc
- math/test/differentiable_norm_test.cc
- math/test/fast_pose_composition_functions_test.cc
- math/test/gradient_util_test.cc
- math/test/gray_code_test.cc
- math/test/jacobian_test.cc
- math/test/linear_solve_test.cc
- math/test/normalize_vector_test.cc
- math/test/quadratic_form_test.cc
- math/test/quaternion_test.cc
- math/test/rigid_transform_test.cc
- math/test/roll_pitch_yaw_test.cc
- math/test/rotation_conversion_test.cc
- math/test/rotation_matrix_test.cc
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20392)
> [math] Clang-format the tests

- bindings/pydrake/symbolic/BUILD.bazel
- bindings/pydrake/symbolic/_symbolic_extra.py
- bindings/pydrake/symbolic/_symbolic_sympy.py
- bindings/pydrake/symbolic/test/sympy_test.py
- tools/workspace/default.bzl
- tools/workspace/mpmath_py_internal/BUILD.bazel
- tools/workspace/mpmath_py_internal/package.BUILD.bazel
- tools/workspace/mpmath_py_internal/repository.bzl
- tools/workspace/sympy_py_internal/BUILD.bazel
- tools/workspace/sympy_py_internal/package.BUILD.bazel
- tools/workspace/sympy_py_internal/repository.bzl
Closes #20076.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20117)
> [pydrake] Add conversion to/from SymPy

- tools/wheel/image/setup.py
Amends #20384.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20400)
> [py autodiff,math,symbolic] Hotfix wheel build for subdirs

- solvers/BUILD.bazel
- solvers/clarabel_solver.cc
- solvers/clarabel_solver.h
- solvers/clarabel_solver_common.cc
- solvers/mathematical_program_doxygen.h
- solvers/no_clarabel.cc
- solvers/test/clarabel_solver_test.cc
- solvers/test/optimization_examples.cc
Towards #19449.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20375)
> Add ClarabelSolver.

- bindings/pydrake/BUILD.bazel
- bindings/pydrake/_all_everything.py
- bindings/pydrake/all.py
- bindings/pydrake/stubgen.bzl
- bindings/pydrake/stubgen.py
- bindings/pydrake/test/all_install_test.py
- doc/pydrake/build.py
- tools/workspace/mypy_internal/patches/no_retry.patch
- tools/workspace/mypy_internal/repository.bzl
Closes #18119 -- at least we hope so.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20403)
> [py tools] Vastly improve stubgen wrapper

- tools/wheel/test/tests/pyi-install-test.py
Amends #20403.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20409)
> [py tools] Update test for new stubgen wrapper

- tools/workspace/common_robotics_utilities/package.BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20418)
> Disable memcheck for parallelism tests

- bindings/pydrake/gym/README.md
- bindings/pydrake/gym/test/drake_gym_test.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20416)
> minor: fix a few typos in DrakeGym docs

- manipulation/kuka_iiwa/test/build_iiwa_control_test.cc
- manipulation/models/iiwa_description/BUILD.bazel
- manipulation/models/iiwa_description/README.md
- manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf
- manipulation/models/iiwa_description/iiwa7/iiwa7_with_box_collision.sdf
- manipulation/models/iiwa_description/test/iiwa_variants_parsing_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20420)
> Updated inertias for the iiwa 7

- multibody/parsing/detail_mujoco_parser.cc
- multibody/parsing/test/detail_mujoco_parser_test.cc
Resolves #20367. (a bug fix)
Also adds support for joint defaults. (a new feature)
Together these support new tests confirming that the acrobot and cartpole models from dm_control have the expected kinematics.
The MuJoCo XML documentation specifies the position of a joint as being "specified in the frame of the parent body". But this apparently needs to be interpretted as the current body, not the parent of the current body.
+@drewhamiltonasdf for initial review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20414)
> Fix mujoco parser joint kinematics.

- math/BUILD.bazel
- math/rotation_matrix.cc
- math/rotation_matrix.h
- math/test/rotation_matrix_test.cc
- math/unit_vector.cc
- math/unit_vector.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20423)
> Move internal static RotationMatrix::NormalizeOrThrow() to unit_vector.

- bindings/pydrake/visualization/BUILD.bazel
- bindings/pydrake/visualization/visualization_py.cc
- bindings/pydrake/visualization/visualization_py.h
- bindings/pydrake/visualization/visualization_py_sliders.cc
Bindings should always be added in class-specific helper files, which are then referred to by the overall module.  (See #20432.)
Amends #19513.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20431)
> [py visualization] Follow code layout conventions

- .bazeliskrc
- doc/_pages/from_source.md
- setup/ubuntu/source_distribution/install_bazel.sh
- tools/workspace/drake_visualizer/image/provision.sh
Resolves #20402.
Previous upgrade PR #19891 (see comments as they go down for the full array of jobs we need to pass here first).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20410)
> Upgrade to bazel 6.4.0

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
- bindings/pydrake/systems/test/controllers_test.py
- multibody/inverse_kinematics/test/angle_between_vectors_constraint_test.cc
- multibody/inverse_kinematics/test/com_in_polyhedron_constraint_test.cc
- multibody/inverse_kinematics/test/com_position_constraint_test.cc
- multibody/inverse_kinematics/test/gaze_target_constraint_test.cc
- multibody/inverse_kinematics/test/orientation_constraint_test.cc
- multibody/inverse_kinematics/test/polyhedron_constraint_test.cc
- multibody/inverse_kinematics/test/position_constraint_test.cc
- multibody/plant/multibody_plant.h
- multibody/plant/test/multibody_plant_jacobians_test.cc
- multibody/plant/test/multibody_plant_test.cc
- multibody/test_utilities/spatial_derivative.h
- planning/test/collision_checker_test.cc
- systems/rendering/multibody_position_to_geometry_pose.cc
Closes #10636
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20424)
> Deprecate get mutable state functions in MultibodyPlant

- bindings/pydrake/symbolic/_symbolic_extra.py
- bindings/pydrake/symbolic/_symbolic_sympy.py
- bindings/pydrake/symbolic/test/sympy_test.py
A few small updates. Support for converting ndarrays of any size back and forth from Drake to Sympy. A few tweaks to get integers to display properly including an option to round floats that are integers to 16 decimal places into proper integer types for readability and simplification.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20415)
> Small updates to sympy routines.

- tools/workspace/abseil_cpp_internal/repository.bzl
- tools/workspace/build_bazel_apple_support/repository.bzl
- tools/workspace/clp_internal/repository.bzl
- tools/workspace/coinutils_internal/repository.bzl
- tools/workspace/dm_control_internal/repository.bzl
- tools/workspace/mypy_internal/repository.bzl
- tools/workspace/new_release.py
- tools/workspace/platforms/repository.bzl
- tools/workspace/pycodestyle/repository.bzl
- tools/workspace/suitesparse_internal/repository.bzl
Towards #20462
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20469)
> Upgrade Externals November 2023

- bindings/pydrake/visualization/BUILD.bazel
- bindings/pydrake/visualization/test/multicam_scenario.yaml
- bindings/pydrake/visualization/test/multicam_scenario_test.py
Per the comment in #20221, moved the file and added comments to a new location.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20456)
> Add multi-cam scenario for testing

- tools/wheel/image/setup.py
Amends f4bed908ae74937a49e55b7a32305743fc0b9e5b.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20478)
> [py common] Hotfix wheel build for subdirs

- third_party/BUILD.bazel
- third_party/com_github_bazelbuild_rules_python/LICENSE
- third_party/com_github_bazelbuild_rules_python/internal_config_repo.bzl
- tools/workspace/rules_python/BUILD.bazel
- tools/workspace/rules_python/patches/internal_config_repo.patch
- tools/workspace/rules_python/repository.bzl
- tools/workspace/rules_python/test/rules_python_internal_test.py
Towards #20462.
We'll plan to squash-and-merge using the PR title as the subject, and no commit body other than Co-authored-by.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20473)
> [workspace] Upgrade python_rules to latest release 0.26.0

- tools/workspace/drake_models/repository.bzl
Relevant to //examples/hydroelastic/python_nonconvex_mesh:drop_pepper_py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20485)
> Use the updated yellow bell pepper from RobotLocomotion/models/pull/27

- math/BUILD.bazel
- math/test/unit_vector_test.cc
- math/unit_vector.cc
- math/unit_vector.h
- multibody/tree/unit_inertia.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20467)
> Fix AutoDiff bug in unit vector code

- doc/_pages/from_binary.md
Closes #19130.
(I was skimming my issues list and realized this one can be easily closed now.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20499)
> [doc] Don't hyperlink to Gatekeeper-tainted downloads on macOS

- bindings/pydrake/systems/sensors_py.h
- bindings/pydrake/systems/sensors_py_image.cc
- bindings/pydrake/systems/test/sensors_test.py
Towards #20447.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20502)
> [py sensors] Bind all image types

- solvers/test/diagonally_dominant_matrix_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20493)
> fix dd test

- bindings/pydrake/systems/sensors_py_image.cc
- bindings/pydrake/systems/sensors_py_image_io.cc
- bindings/pydrake/systems/test/sensors_test.py
Towards #20447.
+@sammy-tri for both reviews per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20508)
> [py sensors] Bind ImageFileFormat and PixelScalar

- bindings/pydrake/planning/planning_py_trajectory_optimization.cc
- bindings/pydrake/planning/test/trajectory_optimization_test.py
- planning/trajectory_optimization/gcs_trajectory_optimization.cc
- planning/trajectory_optimization/gcs_trajectory_optimization.h
- planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
This adds continuity constraints on r(t), which enables a better distribution of grid points for smoother trajectories where Toppra can enforce acceleration constraints.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20441)
> Added continuity constraints

- geometry/render_gl/internal_render_engine_gl.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20510)
> Remove confusing unused code in RenderEngineGl

- tools/wheel/image/dependencies/projects.cmake
- tools/workspace/ipopt_internal_fromsource/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20525)
> [workspace] Upgrade ipopt to latest release 3.14.13

- bindings/pydrake/gym/_drake_gym_env.py
cc @JoseBarreiros-TRI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20529)
> fixup: DrakeGym documentation had the wrong arguments for the reward callback

- solvers/aggregate_costs_constraints.cc
- solvers/aggregate_costs_constraints.h
- solvers/scs_solver.cc
- solvers/test/aggregate_costs_constraints_test.cc
Move it to aggregate_costs_constraints.h/cc, and the test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20517)
> Move ParsePositiveSemidefiniteConstraints.

- bindings/pydrake/symbolic/symbolic_py_monolith.cc
- bindings/pydrake/symbolic/test/symbolic_test.py
- common/symbolic/BUILD.bazel
- common/symbolic/monomial_util.cc
- common/symbolic/monomial_util.h
- common/symbolic/test/monomial_util_test.cc
Generate the monomial basis, such that the total degree for each Variables set is less than a specific degree.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20523)
> Add MonomialBasis for a map from Variables to its degree.

- solvers/BUILD.bazel
- solvers/aggregate_costs_constraints.cc
- solvers/aggregate_costs_constraints.h
- solvers/clarabel_solver.cc
- solvers/clarabel_solver_common.cc
- solvers/mathematical_program_doxygen.h
- solvers/scs_solver.cc
- solvers/test/aggregate_costs_constraints_test.cc
- solvers/test/clarabel_solver_test.cc
Also modify ParseSemidefiniteConstraints to handle using upper or lower triangular matrix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20536)
> ClarabelSolver supports SDP.

- bindings/pydrake/common/test_utilities/BUILD.bazel
- bindings/pydrake/common/test_utilities/scipy_stub/scipy/sparse/__init__.py
- bindings/pydrake/common/test_utilities/test/scipy_stub_test.py
From #20519
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20541)
> [scipy_stub] Add test and bugfix

- multibody/tree/BUILD.bazel
- multibody/tree/geometry_spatial_inertia.cc
- multibody/tree/test/geometry_spatial_inertia_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20539)
> [multibody] Support .vtk meshes in CalcSpatialInertia()

- bindings/pydrake/geometry/geometry_py_visualizers.cc
- bindings/pydrake/geometry/test/visualizers_test.py
- geometry/meshcat.cc
- geometry/meshcat.h
- geometry/test/meshcat_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20548)
> [geometry] Add Meshcat API for directly testing message handling

- planning/BUILD.bazel
- planning/collision_checker.cc
- planning/collision_checker.h
- planning/visibility_graph.cc
- planning/visibility_graph.h
- tools/workspace/common_robotics_utilities/repository.bzl
- tools/workspace/voxelized_geometry_tools/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20528)
> [planning] Switch CollisionChecker and VisibilityGraph to use CRU parfor API

- geometry/proximity/BUILD.bazel
- geometry/proximity/deformable_field_intersection.cc
- geometry/proximity/deformable_field_intersection.h
- geometry/proximity/field_intersection.cc
- geometry/proximity/field_intersection.h
- geometry/proximity/test/deformable_field_intersection_test.cc
- geometry/proximity/test/field_intersection_test.cc
- geometry/query_results/deformable_contact.cc
- geometry/query_results/deformable_contact.h
- geometry/query_results/test/deformable_contact_test.cc
- Introduce query_result's AddDeformableDeformableContactSurface().
- Introduce proximity's AddDeformableDeformableContactSurface().
- Refactor field_intersection to support both hydroelastics and deformables.
Relates #19704
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20514)
> [geometry] Introduce AddDeformableDeformableContactSurface()

- multibody/fem/BUILD.bazel
- multibody/fem/fem_element.h
- multibody/fem/fem_model.cc
- multibody/fem/fem_model.h
- multibody/fem/fem_model_impl.h
- multibody/fem/fem_plant_data.cc
- multibody/fem/fem_plant_data.h
- multibody/fem/fem_solver.cc
- multibody/fem/fem_solver.h
- multibody/fem/test/dummy_element.h
- multibody/fem/test/fem_element_test.cc
- multibody/fem/test/fem_model_test.cc
- multibody/fem/test/fem_solver_test.cc
- multibody/fem/test/volumetric_element_test.cc
- multibody/fem/test/volumetric_model_test.cc
- multibody/fem/volumetric_element.h
- multibody/plant/BUILD.bazel
- multibody/plant/deformable_driver.cc
- multibody/plant/deformable_model.cc
- multibody/plant/deformable_model.h
- multibody/plant/force_density_field.cc
- multibody/plant/force_density_field.h
- multibody/plant/test/deformable_model_test.cc
- multibody/tree/multibody_tree_system.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20404)
> External force field for deformable

- systems/sensors/BUILD.bazel
- systems/sensors/test/image_io_test_params.cc
- systems/sensors/test/image_io_test_params.h
- systems/sensors/test/vtk_image_reader_writer_test.cc
Towards #20447.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20557)
> [sensors] Factor out and improve image load/save test infrastructure

- bindings/pydrake/solvers/BUILD.bazel
- bindings/pydrake/solvers/solvers_py.cc
- bindings/pydrake/solvers/solvers_py.h
- bindings/pydrake/solvers/solvers_py_clarabel.cc
- bindings/pydrake/solvers/test/clarabel_solver_test.py
Towards #19449.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20569)
> [py solvers] Bind ClarabelSolver

- bindings/pydrake/examples/gym/BUILD.bazel
- bindings/pydrake/gym/BUILD.bazel
- tools/workspace/stable_baselines3_internal/BUILD.bazel
Towards #14967.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20574)
> [py gym] Use PYTHON_VERSION (not UBUNTU_RELEASE) to toggle on/off

- solvers/BUILD.bazel
- solvers/choose_best_solver.cc
- solvers/mathematical_program_doxygen.h
- solvers/test/choose_best_solver_test.cc
As mentioned in https://github.com/RobotLocomotion/drake/issues/19449#issuecomment-1820213010
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20587)
> Add ClarabelSolver to ChooseBestSolver.

- bindings/pydrake/visualization/test/multicam_scenario.yaml
- systems/sensors/camera_config.cc
- systems/sensors/camera_config.h
- systems/sensors/camera_config_functions.cc
- systems/sensors/camera_config_functions.h
- systems/sensors/sim_rgbd_sensor.cc
- systems/sensors/sim_rgbd_sensor.h
- systems/sensors/test/camera_config_functions_test.cc
- systems/sensors/test/camera_config_test.cc
- systems/sensors/test/sim_rgbd_sensor_test.cc
Close #20483
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20554)
> Configure label image publishing in CameraConfig

- tools/workspace/default.bzl
- tools/workspace/os.bzl
Follow-up from #20574 and #20576.
Towards #14967.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20600)
> [workspace] Deprecate drake_detected_os external

- examples/hydroelastic/spatula_slip_control/README.md
Fix #20559
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20596)
> [examples] Update spatula_slip_control README about visualization

- bindings/pydrake/multibody/parsing_py.cc
- bindings/pydrake/multibody/test/parsing_test.py
- systems/controllers/inverse_dynamics_controller.h
(also fixes one spurios minor typo)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20608)
> Add python bindings for FlattenModelDirectives

- multibody/fem/test/volumetric_element_test.cc
- multibody/fem/volumetric_element.h
- multibody/plant/force_density_field.h
- multibody/plant/test/deformable_model_test.cc
Amends #20404
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20573)
> ForceDensityField defaults to per current volume density

- bindings/pydrake/geometry/geometry_py_render.cc
- bindings/pydrake/geometry/test/render_test.py
- geometry/render_gl/internal_render_engine_gl.cc
- geometry/render_gl/render_engine_gl_params.h
- geometry/render_gl/test/internal_render_engine_gl_test.cc
- geometry/render_gltf_client/internal_render_engine_gltf_client.cc
- geometry/render_gltf_client/render_engine_gltf_client_params.h
- geometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc
- geometry/render_vtk/internal_render_engine_vtk.cc
- geometry/render_vtk/render_engine_vtk_params.h
- geometry/render_vtk/test/internal_render_engine_vtk_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20589)
> [geometry] Remove deprecated code 2023-12

- bindings/pydrake/multibody/test/plant_test.py
- bindings/pydrake/multibody/tree_py.cc
- math/test/unit_vector_test.cc
- math/unit_vector.cc
- math/unit_vector.h
- multibody/tree/test/unit_inertia_test.cc
- multibody/tree/unit_inertia.cc
- multibody/tree/unit_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20593)
> [tree] Remove deprecated code 2023-12

- systems/sensors/image.h
- systems/sensors/image_io_internal.h
- systems/sensors/image_to_lcm_image_array_t.cc
- systems/sensors/image_writer.cc
- systems/sensors/pixel_types.cc
- systems/sensors/pixel_types.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20590)
> [sensors] Remove deprecated code 2023-12

- bindings/pydrake/systems/sensors_py_image_io.cc
- systems/sensors/image_io.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20611)
> [py sensors] Hotfix ImageIo for XCode 15

- tools/workspace/stable_baselines3_internal/patches/no_torch.patch
- tools/workspace/stable_baselines3_internal/repository.bzl
Toward #20594.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20632)
> [workspace] Upgrade stable_baselines3_internal to latest release v2.2.1

- tools/install/bazel/test/drake_bazel_installed_test.py
- tools/workspace/abseil_cpp_internal/repository.bzl
- tools/workspace/bazel_skylib/repository.bzl
- tools/workspace/fcl_internal/repository.bzl
- tools/workspace/mypy_internal/repository.bzl
- tools/workspace/nanoflann_internal/repository.bzl
- tools/workspace/nlohmann_internal/repository.bzl
- tools/workspace/rules_python/repository.bzl
- tools/workspace/rules_rust/repository.bzl
- tools/workspace/rust_toolchain/lock/archives.bzl
- tools/workspace/suitesparse_internal/repository.bzl
Toward #20594.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20630)
> Upgrade Externals December 2023

- solvers/BUILD.bazel
- solvers/clarabel_solver.cc
- solvers/scs_clarabel_common.cc
- solvers/scs_clarabel_common.h
- solvers/scs_solver.cc
- solvers/test/clarabel_solver_test.cc
Also move SetDualSolution from scs_solver.cc to scs_clarabel_common.h/cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20597)
> Get dual solution from Clarabel.

- bindings/pydrake/solvers/BUILD.bazel
- bindings/pydrake/solvers/test/clarabel_solver_test.py
- bindings/pydrake/solvers/test/mathematicalprogram_test.py
- bindings/pydrake/systems/BUILD.bazel
- bindings/pydrake/systems/analysis_py.cc
- bindings/pydrake/systems/test/analysis_test.py
- geometry/optimization/BUILD.bazel
- geometry/optimization/test/graph_of_convex_sets_test.cc
- solvers/BUILD.bazel
- solvers/mathematical_program_doxygen.h
- systems/analysis/BUILD.bazel
- systems/analysis/region_of_attraction.cc
- systems/analysis/region_of_attraction.h
- systems/analysis/test/region_of_attraction_test.cc
- tools/BUILD.bazel
- tools/bazel.rc
- tools/ubuntu-focal.bazelrc
- tools/workspace/BUILD.bazel
Closes #19449.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20604)
> Enable Clarabel by default.

- tools/dynamic_analysis/tsan.supp
Resolves multiple [test failures](https://drake-cdash.csail.mit.edu/viewTest.php?onlyfailed&buildid=1749687) in [linux-jammy-clang-bazel-nightly-everything-thread-sanitizer](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-jammy-clang-bazel-nightly-everything-thread-sanitizer/29/).
Follow up to #20634
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20647)
> Update tsan suppressions for Mosek 10.1

- tools/workspace/gz_utils_internal/package.BUILD.bazel
- tools/workspace/sdformat_internal/patches/console.patch
- tools/workspace/sdformat_internal/patches/environment.patch
- tools/workspace/sdformat_internal/repository.bzl
Towards #20637.
+@SeanCurtis-TRI for platform review per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20642)
> [workspace] Cull sdformat use of environment and subprocess

- multibody/contact_solvers/contact_configuration.h
- multibody/contact_solvers/sap/BUILD.bazel
- multibody/contact_solvers/sap/sap_hunt_crossley_constraint.cc
- multibody/contact_solvers/sap/sap_hunt_crossley_constraint.h
- multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc
- multibody/contact_solvers/sap/test/sap_hunt_crossley_constraint_test.cc
Towards #19320. 
For now, this PR only implements the new constraint.
A second PR will use this constraint from the SapDriver, and will provide APIs to select either contact model.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20635)
> Implements SAP H&C constraint

- bindings/pydrake/math/math_py_monolith.cc
- bindings/pydrake/math/test/math_test.py
- math/matrix_util.h
- math/test/matrix_util_test.cc
- solvers/mathematical_program.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20646)
> ExtractPrincipalSubmatrix and ToLowerTriangularColumnsFromMatrix

- common/test_utilities/drake_py_unittest_main.py
The lack of affirmation will become a console warning in Bazel 7.
See https://bazel.build/reference/test-encyclopedia#test-sharding for details.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20660)
> [test_utilities] Obey test sharding protocol during Python tests

- geometry/proximity/BUILD.bazel
- geometry/proximity/deformable_contact_internal.cc
- geometry/proximity/deformable_contact_internal.h
- geometry/proximity/test/deformable_contact_internal_test.cc
- geometry/query_object.h
- multibody/plant/test/deformable_driver_contact_test.cc
Resolve #19704
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20614)
> [geometry] Provide deformable-deformable contact data

- solvers/BUILD.bazel
- solvers/semidefinite_relaxation.cc
- solvers/semidefinite_relaxation.h
- solvers/test/semidefinite_relaxation_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20639)
> Semidefinite relaxation lower triangular linear only

- third_party/com_github_bazelbuild_bazelisk/bazelisk.py
- tools/workspace/bazelisk/repository.bzl
- tools/workspace/bazelisk/test/lint_test.py
- tools/workspace/github.bzl
Toward #20594.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20631)
> [workspace] Upgrade bazelisk to latest release v1.19.0

- math/matrix_util.h
- math/test/matrix_util_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20670)
> fix an off by one error in ExtractPrincipalMinor and add tests

- .github/ISSUE_TEMPLATE/BUG.yml
- doc/_pages/from_source.md
- doc/_pages/installation.md
- tools/workspace/os.bzl
Resolves #20339
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20678)
> [doc] Offically support macOS Sonoma

- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/test/optimization_test.py
- geometry/optimization/hyperrectangle.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20690)
> Adds bindings for Hyperrectangle.

- multibody/parsing/parsing_doxygen.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20675)
> [parsing] Fix typos in drake:ball_constraint documentation

- bindings/pydrake/multibody/_inertia_fixer.py
- bindings/pydrake/multibody/fix_inertia.py
- bindings/pydrake/multibody/test/fix_inertia_test.py
Resolves #20691
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20693)
> [fix_inertia] Add --geom_inertia_role_order flag

- tools/workspace/tinyobjloader_internal/package.BUILD.bazel
Closes #20708.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20717)
> [tinyobjloader] Adjust paths for unsandboxed builds.

- bindings/pydrake/multibody/parsing_py.cc
- bindings/pydrake/multibody/test/parsing_test.py
- multibody/parsing/parser.cc
- multibody/parsing/parser.h
- multibody/parsing/test/parser_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20724)
> [parsing] Remove deprecated code 2023-12

- tools/workspace/vtk_internal/patches/common_core_noutf8.patch
- tools/workspace/vtk_internal/patches/common_core_warnings.patch
- tools/workspace/vtk_internal/patches/io_image_png_messages.patch
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20710)
> Note VTK patches that have been upstreamed.

- bindings/pydrake/systems/sensors_py_lcm.cc
- bindings/pydrake/systems/test/sensors_test.py
- systems/sensors/lcm_image_array_to_images.cc
- systems/sensors/lcm_image_array_to_images.h
- systems/sensors/test/lcm_image_array_to_images_test.cc
Follow-up from #20554.
Towards #18862.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20598)
> [sensors] Add lcmt_image_array_to_images output for label images

- bindings/pydrake/common/test/yaml_typed_test.py
- bindings/pydrake/common/yaml.py
- common/yaml/test/yaml_write_archive_defaults_test.cc
- common/yaml/test/yaml_write_archive_test.cc
Closes #19597.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20722)
> [py yaml] Add yaml_dump_typed to complement yaml_load_typed

- CMakeLists.txt
- cmake/bazel.rc.in
Fixes #19091.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20703)
> Add CMake option to enable OpenMP

- bindings/pydrake/common/test/yaml_test.py
- bindings/pydrake/common/yaml.py
Closes #18634.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20728)
> [py yaml] Improve error messages

- setup/ubuntu/source_distribution/packages-jammy.txt
- tools/workspace/pybind11/libclang_setup.py
Relates to https://github.com/RobotLocomotion/ros-drake-vendor/issues/2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20732)
> [setup] Switch to libclang-14 on Jammy

- tools/workspace/suitesparse_internal/package.BUILD.bazel
- tools/workspace/suitesparse_internal/repository.bzl
Toward https://github.com/RobotLocomotion/drake/issues/20723.
----
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20744)
> [workspace] Upgrade suitesparse_internal to latest release v7.4.0

- tools/workspace/crate_universe/README.md
This was fixed in #20477 already.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20743)
> [workspace] Remove stale crate_universe TODO

- geometry/meshcat_visualizer.h
Amends #18433.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20726)
> [geometry] De-duplicate the API docs for meshcat recordings

- geometry/render_gltf_client/BUILD.bazel
- geometry/render_gltf_client/internal_render_client.cc
- geometry/render_gltf_client/test/internal_render_client_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20729)
> [render_gltf_client] Port to ImageIo

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20753)
> Bind MultibodyPlant::HasFrameNamed

- manipulation/util/BUILD.bazel
- manipulation/util/make_arm_controller_model.cc
- manipulation/util/make_arm_controller_model.h
- manipulation/util/test/fake_camera.sdf
- manipulation/util/test/iiwa7_wsg_cameras.dmd.yaml
- manipulation/util/test/make_arm_controller_model_test.cc
Follow-up to #20513 
Towards Anzu PR 11156
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20733)
> [make_arm_controller_model] Account for attached mass

- geometry/query_object.h
Related to issue:
- #14789
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20679)
> [geometry] Update document of QueryObject about gradients of signed distances

- systems/framework/diagram_builder.cc
- systems/framework/test/diagram_builder_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20758)
> DiagramBuilder: Improve error message when input is already wired.

- tutorials/hydroelastic_contact_basics.ipynb
- discrete_contact_approximation="similar" for high impact
- Remove simulator.Initialize()
- Save simulation result into html file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20665)
> Clean up hydroelastic-contact tutorial

- lcm/lcm_messages.cc
- lcm/lcm_messages.h
- lcm/test/lcm_messages_test.cc
This is a bit more relevant with #20761 on the horizon.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20760)
> [lcm] Notice errors during message encoding

- multibody/tree/BUILD.bazel
- multibody/tree/element_collection.cc
- multibody/tree/element_collection.h
- multibody/tree/model_instance.cc
- multibody/tree/model_instance.h
- multibody/tree/multibody_element.cc
- multibody/tree/multibody_element.h
- multibody/tree/multibody_tree-inl.h
- multibody/tree/multibody_tree.cc
- multibody/tree/multibody_tree.h
- multibody/tree/test/element_collection_test.cc
- multibody/tree/test/model_instance_test.cc
- planning/test/linear_distance_and_interpolation_provider_test.cc
This is prep work for #20711.
There are no user-visible changes here, other than perhaps some slight rewording of error messages.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20752)
> [tree] Factor out internal ElementCollection helper class

- geometry/meshcat.cc
Compiling the mesh loading code twice offends my sensibilities.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20771)
> [geometry] De-template Meshcat's mesh loading code

- tools/lcm_gen/BUILD.bazel
- tools/lcm_gen/__init__.py
- tools/lcm_gen/test/lcm_gen_test.py
- tools/lcm_gen/test/lima.lcm
- tools/lcm_gen/test/mike.lcm
For now, this is just the `*.lcm` file parser. The codegen is deferred to a future commit (#20761).
The book https://craftinginterpreters.com/ is a spectacularly good guide about how a recursive descent parser works.  Highly recommended.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20762)
> [tools] Start a from-scratch Python reimplementation of lcm_gen

- doc/_pages/release_playbook.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20783)
> [doc] Fix up some Deepnote links in release playbook

- bindings/pydrake/BUILD.bazel
- bindings/pydrake/common/test/eigen_geometry_test.py
- bindings/pydrake/examples/test/manipulation_station_test.py
- bindings/pydrake/geometry/test/render_test.py
- bindings/pydrake/math/test/math_test.py
- bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py
- bindings/pydrake/multibody/test/parsing_test.py
- bindings/pydrake/systems/BUILD.bazel
- bindings/pydrake/systems/test/controllers_test.py
- bindings/pydrake/systems/test/general_test.py
- bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py
- bindings/pydrake/systems/test/rendering_test.py
- bindings/pydrake/systems/test/sensors_test.py
- bindings/pydrake/test/all_test.py
- bindings/pydrake/test/lcm_test.py
(Noticed during my work on #20776.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20784)
> [pydrake] Clean up some deprecation cruft

- doc/_pages/installation.md
Amends #20678.
+@BetsyMcPhail or +@svenevs for both reviews, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20787)
> [doc] Fix support matrix typo

- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/test/optimization_test.py
- geometry/optimization/BUILD.bazel
- geometry/optimization/cspace_free_box.cc
- geometry/optimization/cspace_free_polytope.cc
- geometry/optimization/cspace_free_polytope.h
- geometry/optimization/cspace_free_polytope_base.cc
- geometry/optimization/cspace_free_polytope_base.h
- geometry/optimization/cspace_free_structs.h
- geometry/optimization/test/cspace_free_box_with_mosek_test.cc
- geometry/optimization/test/cspace_free_polytope_with_mosek_test.cc
Inspired by #20759.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20776)
> [optimization] Adjust "cspace free" to use the Parallelism helper

- geometry/proximity/BUILD.bazel
- geometry/proximity/refine_mesh.cc
- geometry/proximity/test/refine_mesh_test.py
This is dependent (and completely contingent) on #19550, and contains a copy of it. It should not land until that PR is resolved.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20324)
>  Introduce refine_mesh tool

- geometry/meshcat.cc
- geometry/meshcat_internal.cc
- geometry/meshcat_internal.h
- geometry/test/meshcat_internal_test.cc
Towards #19598.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20796)
> [geometry] Factor out Meshcat UUID generator

- geometry/render/BUILD.bazel
- geometry/render/render_mesh.cc
- geometry/render/render_mesh.h
- geometry/render/test/render_mesh_test.cc
Towards #18922
See the full WIP branch at #20780 for bigger picture.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20789)
> [render] Make RenderMesh from TriangleSurfaceMesh

- geometry/render_gl/internal_render_engine_gl.cc
- geometry/render_gl/internal_render_engine_gl.h
- geometry/render_gl/test/internal_render_engine_gl_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20794)
> RenderEngineGl supports deformable geometries

- tools/wheel/image/build-drake.sh
- tools/wheel/image/dependencies/projects.cmake
- tools/wheel/test/tests/sanity-test.py
- tools/workspace/clarabel_cpp_internal/patches/unicode.patch
- tools/workspace/clarabel_cpp_internal/repository.bzl
See also https://github.com/oxfordcontrol/Clarabel.cpp/pull/29.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20802)
> [wheel] Enable ClarabelSolver on Linux

- multibody/inverse_kinematics/minimum_distance_lower_bound_constraint.h
- multibody/inverse_kinematics/minimum_distance_upper_bound_constraint.h
@wrangelvid ran into this issue that the documentation for plant_context is missing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20816)
> Add the documentation on plant_context to minimum distance constraints.

- bindings/pydrake/geometry/geometry_py_visualizers.cc
When threads are involved, bindings need to be careful.  Functions that block on worker threads should release the GIL (to avoid potential deadlocks).
Functions that internally sleep should release the GIL (to be a good citizen).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20810)
> [py geometry] Release the GIL during blocking Meshcat operations

- geometry/BUILD.bazel
- geometry/meshcat.cc
- geometry/meshcat_file_storage_internal.cc
- geometry/meshcat_file_storage_internal.h
- geometry/test/meshcat_file_storage_internal_test.cc
- geometry/test/meshcat_manual_test.cc
- geometry/test/meshcat_test.cc
Towards #19598.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20793)
> [geometry] Serve the environment map over http

- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/optimization_pybind.h
- geometry/optimization/iris.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20845)
> Remove explicit constructor on struct IrisOptions

- tools/workspace/buildifier/package.BUILD.bazel
- tools/workspace/buildifier/repository.bzl
- tools/workspace/github.bzl
- tools/workspace/mirrors.bzl
- tools/workspace/new_release.py
(To be squashed.)
Towards #14967.
Closes #20638.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20579)
> [workspace] Rewrite buildifier rule to use a github-centric flow

- tools/workspace/vtk_internal/patches/filters_sources_cylinder.patch
- tools/workspace/vtk_internal/repository.bzl
Amends #20765 and #20492.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20853)
> [vtk] Add missing member field initialization

- tools/workspace/new_release.py
Actually use logging in new_release script rather than using bare print statements everywhere. Also, use f-strings in more (most) places.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20740)
> Use logging in new_release

- bindings/pydrake/multibody/parsing_py.cc
- bindings/pydrake/multibody/test/parsing_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20905)
> Add binding for GetScopedFrameByNameMaybe

- lcmtypes/BUILD.bazel
- lcmtypes/test/test_message_test.cc
- tools/lcm_gen/BUILD.bazel
- tools/lcm_gen/__init__.py
- tools/lcm_gen/test/functional_test.cc
- tools/lcm_gen/test/goal/lima.hpp
- tools/lcm_gen/test/goal/mike.hpp
- tools/lcm_gen/test/goal/november.hpp
- tools/lcm_gen/test/lcm_gen_test.py
- tools/skylark/drake_lcm.bzl
- tools/workspace/lcm/lcm.bzl
This offers a build-system toggle on a per-rule basis for which C++ message code generator to use.
Towards #20761.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20903)
> [tools] Add drake_lcm_cc_library opt-in for new lcm_gen

- bindings/pydrake/common/test/yaml_typed_test.py
- bindings/pydrake/common/yaml.py
Towards #20920.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20919)
> [py yaml] Add support for Union[List[T], ...]

- geometry/optimization/cspace_free_polytope.h
- geometry/optimization/iris.h
We know that people have had trouble finding the implementation. 
+@alexandreamice for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20909)
> Add mention of C-IRIS and fix typos

- tools/workspace/common_robotics_utilities/package.BUILD.bazel
+@svenevs for review, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20928)
> [workspace] Add sharding to CRU parallelism_test

- manipulation/models/iiwa_description/README.md
- manipulation/models/iiwa_description/iiwa7/iiwa7_no_collision.sdf
- manipulation/models/iiwa_description/iiwa7/iiwa7_with_box_collision.sdf
Towards https://github.com/RobotLocomotion/drake/issues/20907
The methodology for computing these limits is described in the `README`.
For reference, I used the following code to compute them:
```python
from manipulation import ConfigureParser
from pydrake.all import MultibodyPlant, Parser, inv
def create_arm(file: str):
plant = MultibodyPlant(0.0)
parser = Parser(plant)
ConfigureParser(parser)
arm = parser.AddModelsFromString(file, "dmd.yaml")[0]
plant.Finalize()
return plant, arm
iiwa14_scenario = """
directives:
- add_model:
name: iiwa
file: package://drake/manipulation/models/iiwa_description/sdf/iiwa14_no_collision.sdf
- add_weld:
parent: world
child: iiwa::iiwa_link_0
"""
iiwa7_scenario = """
directives:
- add_model:
name: iiwa
file: …
```
> Add iiwa 7 acceleration limits

- third_party/com_github_bazelbuild_rules_python/internal_config_repo.bzl
- tools/install/bazel/test/drake_bazel_installed_test.py
- tools/workspace/rules_python/repository.bzl
- tools/workspace/rules_python/test/rules_python_internal_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20902)
> [workspace] Upgrade rules_python to latest release 0.29.0

- tools/release_engineering/download_release_candidate.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20950)
> Fix typos in download_release_candidate.py

- CMakeLists.txt
- setup/ubuntu/binary_distribution/install_prereqs.sh
- setup/ubuntu/binary_distribution/packages-noble.txt
- setup/ubuntu/source_distribution/packages-noble-test-only.txt
- tools/workspace/fmt/repository.bzl
- tools/workspace/os.bzl
This get us to the point of seeing the compilation errors.
There are still plenty of problems and failures building on Noble.  The objective here is just to get the point of seeing more of those errors.  To me, the review criteria should just be (1) does everything here seem like a strict improvement and (2) is the code sufficiently clear / documented.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20956)
> [setup] Add bootstrap support for Noble

- doc/_pages/apt.md
- doc/_pages/bazel.md
- doc/_pages/docker.md
- doc/_pages/from_binary.md
- doc/_pages/from_source.md
- doc/_pages/getting_help.md
- doc/_pages/installation.md
- doc/_pages/jenkins.md
- doc/_pages/pip.md
- doc/_pages/release_playbook.md
- doc/_pages/troubleshooting.md
- doc/_release-notes/end_of_support.md
- doc/_release-notes/template.txt
- doc/_release-notes/v1.26.0.md
- tools/release_engineering/README.md
- tools/wheel/content/INSTALLATION
- tools/workspace/README.md
This doesn't yet rip it out of the code or Jenkins, rather just the docs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20952)
> [doc] Drop Focal as a supported platform

- CMakeLists.txt
- doc/_pages/from_source.md
- doc/_pages/installation.md
- tools/workspace/python/repository.bzl
Amends #20916, #18262.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20977)
> [doc] Fix staleness in from_source instructions

- bindings/pydrake/multibody/_mesh_model_maker.py
Wavefront .obj files do not specify or store units for the vertex vectors, and different tools use different units.
It is impractical and imprecise to try to infer units from comments that might be in the input file (though some software tries): https://stackoverflow.com/questions/47995531/three-js-load-proper-model-scale-size
Instead, this patch checks the volume of the output against implausibly large and small volumes, and issues warnings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20966)
> [mesh_to_model] Warn about implausible scale

- tools/install/dockerhub/focal/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20991)
> [dockerhub] Remove Focal drake-visualizer shim

- solvers/clarabel_solver.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20981)
> add units to the clarabel solve time documentation

- geometry/BUILD.bazel
- geometry/mesh_deformation_interpolator.cc
- geometry/mesh_deformation_interpolator.h
- geometry/test/mesh_deformation_interpolator_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20851)
> Add MeshDeformationInterpolator

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
- multibody/plant/multibody_plant.cc
- multibody/plant/multibody_plant.h
- multibody/plant/test/multibody_plant_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20975)
> Adds MultibodyPlant::MakeActuationMatrixInverse

- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/test/optimization_test.py
- geometry/optimization/iris.cc
- geometry/optimization/iris.h
- geometry/optimization/test/iris_in_configuration_space_test.cc
Resolves #20036.
+@alexandreamice for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20974)
> Add mixing_steps to IrisOptions

- bindings/pydrake/systems/framework_py_systems.cc
- bindings/pydrake/systems/test/general_test.py
- systems/framework/system.cc
- systems/framework/system.h
- systems/framework/test/diagram_test.cc
- systems/framework/test/system_test.cc
- systems/primitives/test/linear_system_test.cc
(This will support some forthcoming PRs)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20976)
> Add System::IsDifferentialEquationSystem

- multibody/multibody_doxygen.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21005)
> [doc] Improve monogram notation examples for vectors

- geometry/render_vtk/test/internal_render_engine_vtk_test.cc
Towards #20932.
As it happens, the render engine already supported glTF with external resources.  This just locks it in with a regression test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21002)
> [render_vtk] Add regression test for glTFs with external assets

- bindings/pydrake/symbolic/_symbolic_sympy.py
- bindings/pydrake/symbolic/test/sympy_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20996)
> Convert Drake ExpressionKind.Constant to Sympy Integer and Float

- bindings/pydrake/visualization/test/visualization_install_tests.py
See #21023.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21024)
> [py visualization] Disable some macOS bin-install tests

- planning/trajectory_optimization/kinematic_trajectory_optimization.cc
- planning/trajectory_optimization/kinematic_trajectory_optimization.h
- planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Resolves #20894.
+@nepfaff for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21014)
> Return bindings from KinematicTrajectoryOptimization Add* methods.

- bindings/pydrake/test/trajectories_test.py
- bindings/pydrake/trajectories_py.cc
- common/trajectories/BUILD.bazel
- common/trajectories/derivative_trajectory.cc
- common/trajectories/derivative_trajectory.h
- common/trajectories/path_parameterized_trajectory.cc
- common/trajectories/path_parameterized_trajectory.h
- common/trajectories/test/derivative_trajectory_test.cc
- common/trajectories/test/path_parameterized_trajectory_test.cc
- common/trajectories/test/trajectory_test.cc
- common/trajectories/trajectory.cc
- common/trajectories/trajectory.h
Resolves #20982.
+@nepfaff for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21036)
> Implements DerivativeTrajectory.

- doc/_pages/credits.md
+@RussTedrake for feature review?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21034)
> [doc] Add Thomas Cohn as a contributor.

- systems/sensors/camera_config.h
Close #20957
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21018)
> Update show_rgb documentation

- geometry/geometry_file_formats_doxygen.h
- geometry/render/render_doxygen.h
- geometry/render_gltf_client/render_gltf_client_doxygen.h
Also fix a few small typos, etc.
Towards #20932.
+@zachfang for feature review, please.
+@SeanCurtis-TRI for extra feature and platform review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21052)
> [doc] Clarify information about glTF embedded assets

- solvers/constraint.cc
- solvers/constraint.h
- solvers/test/constraint_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21049)
> add finiteness check to linear constraints

- bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc
- bindings/pydrake/manipulation/test/kuka_iiwa_test.py
- manipulation/kuka_iiwa/build_iiwa_control.cc
- manipulation/kuka_iiwa/build_iiwa_control.h
- manipulation/kuka_iiwa/iiwa_driver_functions.cc
- manipulation/kuka_iiwa/sim_iiwa_driver.cc
- manipulation/kuka_iiwa/sim_iiwa_driver.h
- manipulation/kuka_iiwa/test/sim_iiwa_driver_test.cc
Moves `AddSimIiwaDriver` into `SimIiwaDriver` and binds `SimIiwaDriver`.
Adds a test case for `AddSimIiwaDriver`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21040)
> Promote SimIiwaDriver to public API

- tools/BUILD.bazel
- tools/bazel.rc
- tools/ubuntu-jammy.bazelrc
- tools/ubuntu-noble.bazelrc
Towards #20898.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20990)
> [workspace] Build OpenUSD in macOS CI

- bindings/pydrake/visualization/_triad.py
- bindings/pydrake/visualization/test/triad_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21064)
> [visualization] Allow adding triad to multibody Frame

- multibody/tree/rigid_body.h
- tools/workspace/default.bzl
- tools/workspace/os.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21075)
> Remove deprecated code 2024-03

- bindings/pydrake/geometry/test/optimization_test.py
- examples/multibody/strandbeest/model/LegAssembly.xacro
- examples/multibody/strandbeest/model/LegPair.xacro
- examples/multibody/strandbeest/model/Macros.xacro
- examples/multibody/strandbeest/model/Strandbeest.xacro
- examples/multibody/strandbeest/model/StrandbeestBushings.urdf.xacro
- examples/multibody/strandbeest/model/StrandbeestConstraints.urdf.xacro
- examples/pr2/models/pr2_description/urdf/pr2_simplified.urdf
- examples/quadrotor/office.urdf
- geometry/optimization/test/iris_in_configuration_space_test.cc
- manipulation/models/franka_description/urdf/panda_hand.urdf
- manipulation/models/iiwa_description/urdf/dual_iiwa14_polytope_collision.urdf
- manipulation/models/iiwa_description/urdf/iiwa14_polytope_collision.urdf
- manipulation/models/iiwa_description/urdf/iiwa14_primitive_collision.urdf
- manipulation/models/iiwa_description/urdf/iiwa14_spheres_collision.urdf
- manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_collision.urdf
- manipulation/models/iiwa_description/urdf/iiwa14_spheres_dense_elbow_collision.urdf
- manipulation/models/iiwa_description/urdf/planar_iiwa14_spheres_dense_elbow_collision.urdf
- manipulation/models/ur3e/ur3e.urdf.xacro
- multibody/plant/test/atlas_with_fixed_joints.urdf
* Add standardized namespace definition for drake:
* Delete a variety of no-op text
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21067)
> URDF text cleanups

- tools/workspace/styleguide/repository.bzl
Relates: #20294, #21013, https://github.com/RobotLocomotion/styleguide/pull/54
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21084)
> [workspace] Update styleguide for python 3.12 support

- common/find_resource.cc
- common/test/resource_tool_installed_test.py
In case the user had set up any symlinks to help load Drake's runtime libraries, the logic to find the neighboring `$prefix/share` would fail to find the neighbor. Here we add a second attempt to find the `share` tree after resolving all symlinks in the library path. This should only add new capability, not break anything that is already working properly.
This is required for https://github.com/RobotLocomotion/drake-external-examples/pull/286 to work.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21092)
> [common] Adjust FindResource on installed Drake to chase symlinks

- bindings/pydrake/systems/analysis_py.cc
- bindings/pydrake/systems/test/analysis_test.py
- systems/analysis/BUILD.bazel
- systems/analysis/batch_eval.cc
- systems/analysis/batch_eval.h
- systems/analysis/test/batch_eval_test.cc
- systems/framework/system.h
This enables, for instance, writing value iteration codes in python (and using pytorch).
+@jwnimmer-tri for feature review, please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/20979)
> Add batch (multithreaded) evaluation of system dynamics.

- multibody/benchmarks/acrobot/acrobot.xml
- multibody/parsing/detail_mujoco_parser.cc
- multibody/parsing/test/detail_mujoco_parser_test.cc
- multibody/parsing/test/mujoco_parser_test/nested.xml
- multibody/parsing/test/mujoco_parser_test/pendulum.xml
- multibody/parsing/test/mujoco_parser_test/pendulum_geom.xml
- multibody/parsing/test/mujoco_parser_test/scene.xml
- multibody/parsing/test/parser_test.cc
Resolves #20683.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21087)
> Adds support for <include> tags in the mujoco parser.

- bindings/pydrake/common/test/yaml_typed_test.py
- bindings/pydrake/common/yaml.py
As of Python 3.10, we can spell type hints like `foo : Foo | None = ...` now (preferred) instead of `foo: Optional[Foo] = ...` (dispreferred).  Here we adjust the typed yaml code to work with either spelling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21108)
> [py yaml] Handle UnionType hints

- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/test/optimization_test.py
- geometry/optimization/hyperrectangle.cc
- geometry/optimization/hyperrectangle.h
- geometry/optimization/test/hyperrectangle_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21076)
> Add support of intersection and unbounded hyperrectangles

- WORKSPACE
- cmake/WORKSPACE.in
This re-applies f2187b3f (by reverting the 5a35be04 revert).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21116)
> [workspace] Adjust apple_support for Bazel 7 compatibility

- .bazeliskrc
- doc/_pages/from_source.md
- setup/ubuntu/source_distribution/install_bazel.sh
Closes #21054.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21103)
> [setup] Upgrade Bazel to latest release 7.0.2

- planning/iris/BUILD.bazel
- planning/iris/iris_from_clique_cover.cc
- planning/iris/test/iris_from_clique_cover_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21136)
> Fixes race condition in IrisInConfigurationSpaceFromCliqueCover

- systems/benchmarking/BUILD.bazel
- systems/benchmarking/framework_benchmarks.cc
As (retroactive) motivation for #19746.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/19810)
> [framework] Add DiagramBuilder::Build benchmark

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
- bindings/pydrake/multibody/test/two_bodies.sdf
This adds a binding for [MultibodyPlant::GetVisualGeometriesForBody](https://drake.mit.edu/doxygen_cxx/classdrake_1_1multibody_1_1_multibody_plant.html#aaa44d7039f5dbc60525e53b20fdca226).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21153)
> Add binding for GetVisualGeometriesForBody

- geometry/BUILD.bazel
- geometry/geometry_state.cc
- geometry/geometry_state.h
- geometry/mesh_deformation_interpolator.h
- geometry/render/render_mesh.cc
- geometry/render/render_mesh.h
- geometry/render/test/render_mesh_test.cc
- geometry/scene_graph.cc
- geometry/test/geometry_state_test.cc
- geometry/test/utilities_test.cc
- geometry/utilities.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21094)
> GeometryState supports perception deformable geometries

- multibody/parsing/BUILD.bazel
- multibody/parsing/collision_filter_groups.cc
- multibody/parsing/collision_filter_groups.h
- multibody/parsing/detail_collision_filter_group_resolver.cc
- multibody/parsing/detail_collision_filter_group_resolver.h
- multibody/parsing/detail_composite_parse.cc
- multibody/parsing/detail_composite_parse.h
- multibody/parsing/parser.h
- multibody/parsing/test/collision_filter_groups_test.cc
- multibody/parsing/test/detail_collision_filter_group_resolver_test.cc
- multibody/parsing/test/detail_make_model_name_test.cc
- multibody/parsing/test/detail_mesh_parser_test.cc
- multibody/parsing/test/detail_mujoco_parser_test.cc
- multibody/parsing/test/detail_sdf_parser_test.cc
- multibody/parsing/test/detail_select_parser_test.cc
- multibody/parsing/test/detail_urdf_parser_test.cc
- multibody/parsing/test/detail_usd_parser_test.cc
- multibody/parsing/test/parser_manual_test.cc
- multibody/parsing/test/process_model_directives_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21138)
> [parsing] Report accumulated collision filter groups

- systems/framework/input_port.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21166)
> Document a gotcha in input_port.Eval's argument.

- solvers/program_attribute.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21163)
> fix a typo in program attributes documentation

- tools/install/libdrake/BUILD.bazel
- tools/skylark/cc.bzl
- tools/workspace/BUILD.bazel
- tools/workspace/default.bzl
- tools/workspace/mirrors.bzl
- tools/workspace/mosek/package.BUILD.bazel
- tools/workspace/mosek/repository.bzl
- tools/workspace/mosek/repository_impl.bzl
- tools/workspace/new_release.py
- tools/workspace/onetbb_internal/package.BUILD.bazel
Towards #20898.
Closes #20233 (incidentally).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21155)
> [workspace] Straighten out repo rules for MOSEK, TBB, OpenUSD

- tools/workspace/mosek/repository.bzl
Follow-up to #21155
Fixes CI build https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-jammy-unprovisioned-gcc-bazel-continuous-mirror-to-s3/496/console
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21175)
> [workspace] Fix typo in mosek checksum

- tools/workspace/drake_models/repository.bzl
- tools/workspace/drake_models/test/parse_test.py
Twin PR: https://github.com/RobotLocomotion/models/pull/41
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21217)
> [workspace] Upgrade drake_models to latest commit

- bindings/pydrake/multibody/test/plant_test.py
- bindings/pydrake/multibody/tree_py.cc
- multibody/tree/BUILD.bazel
- multibody/tree/body.h
- multibody/tree/rigid_body.h
Note that this is only pare of the 2024-04 removals.  #21225 tracks the other part.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21226)
> [multibody] Remove Body deprecations 2024-04

- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/test/optimization_test.py
- geometry/optimization/BUILD.bazel
- geometry/optimization/iris.cc
- geometry/optimization/iris.h
- geometry/optimization/iris_internal.cc
- geometry/optimization/iris_internal.h
- geometry/optimization/test/iris_in_configuration_space_test.cc
- geometry/optimization/test/iris_internal_test.cc
Resolve #21150
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21182)
> Add counterexample_solver_options to IrisOptions.

- bindings/pydrake/solvers/solvers_py_evaluators.cc
- bindings/pydrake/solvers/test/evaluators_test.py
- geometry/optimization/graph_of_convex_sets.cc
- solvers/BUILD.bazel
- solvers/cost.cc
- solvers/cost.h
- solvers/test/cost_test.cc
This is a preparation PR for #20552
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21199)
> Add A_sparse and A_dense to L2NormCost.

- solvers/BUILD.bazel
- solvers/gurobi_solver.cc
- solvers/gurobi_solver_internal.cc
- solvers/gurobi_solver_internal.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21223)
> Add gurobi_solver_internal.h/cc

- solvers/aggregate_costs_constraints.cc
- solvers/aggregate_costs_constraints.h
- solvers/test/aggregate_costs_constraints_test.cc
This will be used for Clarabel and SCS.
As a step towards resolving #20552
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21204)
> Add ParseL2NormCosts.

- solvers/BUILD.bazel
- solvers/gurobi_solver.cc
- solvers/gurobi_solver_common.cc
- solvers/gurobi_solver_internal.cc
- solvers/gurobi_solver_internal.h
- solvers/test/gurobi_solver_internal_test.cc
- solvers/test/gurobi_solver_test.cc
- solvers/test/l2norm_cost_examples.cc
- solvers/test/l2norm_cost_examples.h
Partially resolves #20552
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21256)
> GurobiSolver supports L2NormCost

- solvers/test/gurobi_solver_internal_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21270)
> Fix a memory leak in gurobi_solver_internal_test

- solvers/BUILD.bazel
- solvers/clarabel_solver.cc
- solvers/clarabel_solver_common.cc
- solvers/scs_solver.cc
- solvers/scs_solver_common.cc
- solvers/test/clarabel_solver_test.cc
- solvers/test/l2norm_cost_examples.cc
- solvers/test/l2norm_cost_examples.h
- solvers/test/scs_solver_test.cc
Towards #20552
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21271)
> Clarabel and SCS support L2NormCost.

- bindings/pydrake/systems/framework_py_semantics.cc
- bindings/pydrake/systems/test/general_test.py
Resolves #21221
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21236)
> [py systems] Ensure DiscreteValues accessors work for T != double

- tools/workspace/abseil_cpp_internal/repository.bzl
- tools/workspace/build_bazel_apple_support/repository.bzl
- tools/workspace/com_github_nelhage_rules_boost_internal/repository.bzl
- tools/workspace/common_robotics_utilities/repository.bzl
- tools/workspace/msgpack_internal/repository.bzl
- tools/workspace/nanoflann_internal/repository.bzl
- tools/workspace/platforms/repository.bzl
- tools/workspace/stable_baselines3_internal/repository.bzl
- tools/workspace/suitesparse_internal/repository.bzl
Towards #21211
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21260)
> Upgrade externals April 2024

- solvers/BUILD.bazel
- solvers/mosek_solver.cc
- solvers/mosek_solver_common.cc
- solvers/mosek_solver_internal.cc
- solvers/mosek_solver_internal.h
- solvers/test/mosek_solver_test.cc
Towards #20552
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21274)
> Mosek supports L2NormCost.

- tools/workspace/gz_math_internal/repository.bzl
- tools/workspace/sdformat_internal/package.BUILD.bazel
- tools/workspace/sdformat_internal/repository.bzl
Towards #21211
- Upgrade sdformat_internal to latest release sdformat14_14.1.1
- Upgrade gz_math_internal to latest release gz-math7_7.4.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21262)
> [workspace] Upgrade sdformat_internal, gz_math_internal to latest

- solvers/test/gurobi_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21282)
> Enable ShortestDistanceFromPlaneToTwoPoints test for gurobi.

- bindings/pydrake/visualization/_meldis.py
- bindings/pydrake/visualization/test/meldis_test.py
Relates #21194
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21297)
> Meldis reload considers glTF content

- bindings/pydrake/test/trajectories_test.py
- bindings/pydrake/trajectories_py.cc
- common/trajectories/exponential_plus_piecewise_polynomial.h
- common/trajectories/test/exponential_plus_piecewise_polynomial_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21304)
> Adds documentation and python bindings for ExponentialPlusPiecewisePolynomial

- doc/_pages/from_binary.md
- doc/_pages/release_playbook.md
- tools/release_engineering/download_release_candidate.py
While releasing v1.28.0, I encountered a couple of stale details in the documentation and automation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21302)
> Update release details

- solvers/mathematical_program.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21299)
> update AddL2NormCost docs

- solvers/sdpa_free_format.cc
- solvers/sdpa_free_format.h
- solvers/test/csdp_solver_test.cc
- solvers/test/sdpa_free_format_test.cc
Towards #21135.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21311)
> [solvers] Add more failure details to csdp_solver_test

- multibody/tree/quaternion_floating_mobilizer.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21312)
> [multibody] Fix whitespace

- .bazeliskrc
I used this in #21123 for the ~25 builds with zero flakes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21324)
> [setup] Switch preferred bazel mirror to github.com

- .bazeliskrc
- doc/_pages/from_source.md
FYI Prior upgrade #21103.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21123)
> [setup] Upgrade Bazel to latest release 7.1.1

- geometry/proximity/BUILD.bazel
- geometry/proximity/distance_to_shape_touching.cc
- geometry/proximity/distance_to_shape_touching.h
- geometry/proximity/test/distance_to_shape_touching_test.cc
Fix #21192
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21266)
>  [geometry] Fix gradient of signed distance between touching (zero distance) boxes

- tools/bazel.rc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21333)
> [tools] Disable implicit __init__.py creation

- tools/workspace/openusd_internal/lock/files.bzl
- tools/workspace/openusd_internal/repository.bzl
Towards #20898.
+@sherm1 for both reviews, please (load balancing).
\CC @hong-nvidia FYI
https://github.com/PixarAnimationStudios/OpenUSD/blob/release/CHANGELOG.md#2405---2024-04-19
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21340)
> [workspace] Upgrade openusd_internal to latest release v24.05

- geometry/optimization/test/graph_of_convex_sets_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21342)
> Fix forward gurobi failure on GCS test updates

- geometry/optimization/graph_of_convex_sets.cc
- geometry/optimization/test/graph_of_convex_sets_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21296)
> Add perspective of positive semidefinite constraint

- bindings/pydrake/systems/controllers_py.cc
- bindings/pydrake/systems/test/controllers_test.py
- systems/controllers/inverse_dynamics.cc
- systems/controllers/inverse_dynamics.h
- systems/controllers/inverse_dynamics_controller.cc
- systems/controllers/inverse_dynamics_controller.h
- systems/controllers/test/inverse_dynamics_controller_test.cc
- systems/controllers/test/inverse_dynamics_test.cc
Closes #21130
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21287)
> Add `plant_context` argument to `InverseDynamics` and `InverseDynamicsController`

- bindings/pydrake/planning/BUILD.bazel
- bindings/pydrake/planning/planning_py.cc
- bindings/pydrake/planning/planning_py.h
- bindings/pydrake/planning/planning_py_zmp_planner.cc
- bindings/pydrake/planning/test/zmp_planner_test.py
- examples/zmp/BUILD.bazel
- examples/zmp/zmp_example.cc
- planning/BUILD.bazel
- planning/locomotion/BUILD.bazel
- planning/locomotion/test/zmp_planner_test.cc
- planning/locomotion/test_utilities/BUILD.bazel
- planning/locomotion/test_utilities/zmp_test_util.cc
- planning/locomotion/test_utilities/zmp_test_util.h
- planning/locomotion/zmp_planner.cc
- planning/locomotion/zmp_planner.h
- systems/controllers/BUILD.bazel
- systems/controllers/stub/zmp_planner.h
- systems/controllers/test/deprecated_zmp_planner_test.cc
- tools/install/libdrake/build_components.bzl
+@jwnimmer-tri for feature review, please (due to the relocation).  Or both reviews if you are ok with it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21305)
> Moves ZmpPlanner to planning directory and adds python bindings.

- geometry/optimization/convex_set.cc
- geometry/optimization/test/convex_set_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21354)
> loosen a tolerance and fix a bad log message

- doc/_pages/jenkins.md
- doc/_pages/release_playbook.md
- tools/release_engineering/download_release_candidate.py
Resolves #21140
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21353)
> Remove mac x86 wheel jobs

- CMakeLists.txt
- bindings/pydrake/geometry/geometry_py_visualizers.cc
- common/symbolic/test/generic_polynomial_test.cc
- common/symbolic/test/polynomial_test.cc
- doc/_pages/clion.md
- doc/_pages/code_style_tools.md
- doc/_pages/emacs.md
- doc/_pages/from_source.md
- doc/_pages/vscode.md
- setup/mac/source_distribution/Brewfile-test-only
- setup/ubuntu/source_distribution/packages-jammy-clang.txt
- setup/ubuntu/source_distribution/packages-jammy-test-only.txt
- setup/ubuntu/source_distribution/packages-jammy.txt
- setup/ubuntu/source_distribution/packages-noble-clang.txt
- setup/ubuntu/source_distribution/packages-noble.txt
- tools/dynamic_analysis/drd.sh
- tools/dynamic_analysis/helgrind.sh
- tools/dynamic_analysis/valgrind.sh
- tools/lint/clang_format.py
- tools/ubuntu-jammy.bazelrc
- tools/ubuntu-noble.bazelrc
- tools/wheel/image/packages-jammy
- tools/workspace/cc/repository.bzl
- tools/workspace/pybind11/libclang_setup.py
Towards #21335.
Note that because this changes the setup scripts, all Provisioned jobs (pre-merge) will fail.  We need to deploy new images to get it passing.  During review, we'll use Unprovisioned jobs to test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21339)
> [setup] Upgrade supported Clang to version 15

- geometry/meshcat.cc
- geometry/meshcat.h
- geometry/test/meshcat_test.cc
Towards #21362.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21369)
> [geometry] Consolidate property checking boilerplate in meshcat_test

- solvers/BUILD.bazel
- solvers/semidefinite_relaxation_internal.cc
- solvers/semidefinite_relaxation_internal.h
- solvers/test/semidefinite_relaxation_internal_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21144)
> Products of Lorentz and Positive Orthant Constraints.

- tools/workspace/sdformat_internal/patches/console.patch
- tools/workspace/sdformat_internal/repository.bzl
Towards #21372
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21390)
> [workspace] Upgrade sdformat_internal to latest

- tools/workspace/boost_internal/repository.bzl
- tools/workspace/github.bzl
Closes #21388.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21396)
> [workspace] Pin the version of boost

- bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
- bindings/pydrake/solvers/test/mathematicalprogram_test.py
- solvers/mathematical_program.cc
- solvers/mathematical_program.h
- solvers/test/mathematical_program_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21399)
> Add MathematicalProgram::RemoveVisualizationCallback

- multibody/parsing/detail_usd_parser.cc
- tools/workspace/openusd_internal/patches/namespace.patch
- tools/workspace/openusd_internal/repository.bzl
Towards #20898.  I was going to save this fix for a larger PR later, but it seems troublesome enough now to merit a tiny PR now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21407)
> [workspace] Fix OpenUSD namespace

- multibody/fem/dirichlet_boundary_condition.cc
- multibody/fem/dirichlet_boundary_condition.h
- multibody/fem/fem_model.cc
- multibody/fem/fem_model.h
- multibody/fem/fem_model_impl.h
- multibody/fem/fem_state.cc
- multibody/fem/fem_state.h
- multibody/fem/fem_state_system.cc
- multibody/fem/fem_state_system.h
- multibody/fem/test/dummy_model.h
- multibody/fem/test/fem_model_test.cc
- multibody/fem/test/volumetric_model_test.cc
- multibody/fem/volumetric_model.h
In addition, widen the scalar support for some FEM classes.
See #21357 for the full picture. Towards #21355.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21400)
> Implement FemModel::Clone()

- geometry/BUILD.bazel
- geometry/meshcat.cc
- geometry/meshcat.h
- geometry/meshcat_recording_internal.cc
- geometry/meshcat_recording_internal.h
- geometry/test/meshcat_recording_internal_test.cc
- geometry/test/meshcat_test.cc
The user-facing API is unchanged.
Towards #21279.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21362)
> [geometry] Factor recording implementation out of Meshcat

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21426)
> [pybind] Add MultibodyPlant::CalcRelativeRotationMatrix.

- tools/performance/defs.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21432)
> [tools] Fix an import missed in porting to rules_python

- solvers/csdp_solver.h
I was seeing code 5 while debugging #21135 and couldn't figure out what it meant.
+@jwnimmer-tri platform review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21448)
> [solvers] Document more CSDP return codes

- solvers/csdp_solver.cc
- solvers/test/csdp_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21449)
> [solvers] CsdpSolver obeys SolverOptions

- doc/_pages/release_playbook.md
Update Release Playbook from my experience with v1.29.0.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21444)
> [doc] Minor update to Release Playbook

- tools/ubuntu-noble.bazelrc
Due to #21456.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21457)
> [tools] Disable OpenUSD on Noble

- tools/macos-arch-arm64.bazelrc
- tools/macos-arch-i386.bazelrc
- tools/workspace/execute.bzl
Some font hunting stuff inside matplotlib needs `/usr/sbin/system_profiler`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21465)
> [tools] On macOS add /usr/sbin and /sbin to $PATH

- bindings/pydrake/planning/planning_py_trajectory_optimization.cc
- bindings/pydrake/planning/test/trajectory_optimization_test.py
- planning/trajectory_optimization/gcs_trajectory_optimization.cc
- planning/trajectory_optimization/gcs_trajectory_optimization.h
- planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
This adds nonlinear continuity constraints on q(t). Before we only had path contiuity on r(s).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21480)
> Added nonlinear continuity constraints

- multibody/contact_solvers/sap/sap_solver.cc
- multibody/plant/sap_driver.cc
We replace DRAKE_DEMANDs with exceptions, with a more informative error messasge to users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21470)
> Exceptions with improved error messages in SapSolver

- planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Hotfix for #21480.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21494)
> [fix] Speedup continuity test

- solvers/ipopt_solver_internal.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21497)
> Fix the uninitialized status in IpoptSolver_NLP.

- solvers/BUILD.bazel
- solvers/ipopt_solver_internal.cc
- solvers/test/ipopt_solver_internal_test.cc
Resolves #21485
cc @jorgenin
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21492)
> IpoptSolver sets the sparsity parttern of the linear constraints.

- solvers/ipopt_solver_internal.cc
- solvers/test/ipopt_solver_internal_test.cc
Towards #18292
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21499)
> Set IPOPT nonlinear constraint sparsity.

- bindings/pydrake/systems/framework_py_systems.cc
- systems/framework/leaf_system.cc
- systems/framework/leaf_system.h
PR #21478 resolves issue #18768
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21478)
>  Fix Python binding for LeafSystems::DeclareAbstractOutputPort().

- planning/trajectory_optimization/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21490)
> [planning] Bump up gcs_trajectory_optimization_test shard count

- geometry/scene_graph_config.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21511)
> [geometry] Update default resolution hint

- multibody/tree/frame.cc
- multibody/tree/frame.h
- multibody/tree/rigid_body.cc
- multibody/tree/rigid_body.h
This PR helps speed subsequent PRs (e.g., for subsequent work on issue #14269).
For practical purposes, this PR is a copy-paste of code from frame.h to frame.cc and code from rigid_body.h to rigid_body.cc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21516)
> Move code in frame.h and rigid_body.h to frame.cc and rigid_body.cc

- tutorials/authoring_multibody_simulation.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21481)
> [tutorials] Add hydro quick-start to a tutorial

- tutorials/authoring_multibody_simulation.ipynb
(We will squash this for merge.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21509)
> [tutorials] Clarify that glTF is our preferred mesh format

- geometry/optimization/test/vpolytope_test.cc
- geometry/optimization/vpolytope.cc
Closes #21055.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21527)
> change hpolyhedron to vpolytope linear solver

- solvers/gurobi_solver_internal.cc
Gurobi throws warning if the coefficients is less than 1E-13. We check the coefficients of our problem data, and do not add the coefficient entry if it is smaller than 1E-13.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21540)
> Mute Gurobi's warning on small coefficients.

- tools/workspace/abseil_cpp_internal/repository.bzl
- tools/workspace/bazel_skylib/repository.bzl
- tools/workspace/bazelisk/repository.bzl
- tools/workspace/buildifier/repository.bzl
- tools/workspace/dm_control_internal/repository.bzl
- tools/workspace/googlebenchmark/repository.bzl
- tools/workspace/rules_python/repository.bzl
- tools/workspace/sympy_py_internal/repository.bzl
- tools/workspace/typing_extensions_internal/repository.bzl
Towards #21507
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21537)
> External upgrades - June 2024

- tools/workspace/vtk_internal/package.BUILD.bazel
- tools/workspace/vtk_internal/patches/nerf_pegtl.patch
- tools/workspace/vtk_internal/repository.bzl
- tools/workspace/vtk_internal/settings.bzl
Towards #21507
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21542)
> [workspace] Upgrade vtk_internal to latest commit

- tools/workspace/rules_python/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21564)
> [workspace] Upgrade rules_python to latest release 0.33.0

- multibody/parsing/parser.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21567)
> [parsing] Fix hazard in deprecated API

- tools/release_engineering/dev/push_release
Resolves #21573.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21586)
> Add noble to push_release script

- doc/_pages/credits.md
- tools/workspace/README.md
The bullet list styling used here is very bland.  We could imagine a better layout or adding icons for some of the software, but for now my plan is to get inventory of links collected, and later someone with a better sense of style could circle back and dress it up.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21575)
> [doc] Add most open source dependencies to website credits

- tools/workspace/pybind11/package.BUILD.bazel
- tools/workspace/pybind11/repository.bzl
Towards #21577
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21584)
> [workspace] Upgrade pybind11 to latest commit

- bindings/pydrake/planning/planning_py_trajectory_optimization.cc
- bindings/pydrake/planning/test/trajectory_optimization_test.py
- planning/trajectory_optimization/gcs_trajectory_optimization.cc
- planning/trajectory_optimization/gcs_trajectory_optimization.h
- planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21504)
> [GcsTrajOpt] Add Edges accessor to EdgesBetweenSubgraphs

- multibody/plant/multibody_plant.cc
- multibody/plant/multibody_plant.h
- multibody/plant/test/discrete_update_manager_test.cc
- multibody/plant/test/multibody_plant_reaction_forces_test.cc
- multibody/plant/test/sap_driver_test.cc
Towards #20545.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21595)
> [multibody] Remove some dead code during MbP time stepping

- multibody/plant/test/multibody_plant_kinematics_test.cc
Consolidate and enhance tests in multibody_plant_kinematics_test.cc to facilitate testing for subsequent PRs associated with issue #13662 and issue #14269.  To see how this PR fits into bigger plan, see PR #21519.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21570)
> Enhance multibody_plant_kinematics_test.cc for subsequent PRs.

- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/test/optimization_test.py
- geometry/optimization/graph_of_convex_sets.cc
- geometry/optimization/graph_of_convex_sets.h
- geometry/optimization/test/graph_of_convex_sets_test.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21506)
> [GCS] Support passing an initial_guess to SolveConvexRestriction

- bindings/pydrake/planning/planning_py_trajectory_optimization.cc
- bindings/pydrake/planning/test/trajectory_optimization_test.py
- planning/trajectory_optimization/kinematic_trajectory_optimization.cc
- planning/trajectory_optimization/kinematic_trajectory_optimization.h
- planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Implements a cost to minimize the energy of a trajectory. The global optimum of this cost is equivalent to the optimum for path length, in the limit of infinitely many control points, and it has the benefit of yielding a convex quadratic objective (which is much easier for optimizers to handle). See [here](https://en.wikipedia.org/wiki/Geodesic#Riemannian_geometry) for further discussion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21587)
> Adds Energy Cost to KinematicTrajectoryOptimization

- multibody/plant/multibody_plant.cc
- multibody/plant/multibody_plant.h
Someone already had the bright idea of a private struct CacheIndices to collate all of the cache entry lookups into a single member field.
We extend that same idea to also cover input and output ports, making the variable naming consistent throughout.
Towards #21597 and therefore #20545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21606)
> [multibody] Make MbP port bookeeping boring again

- math/BUILD.bazel
- math/fast_pose_composition_functions_avx2_fma.cc
- tools/workspace/BUILD.bazel
- tools/workspace/default.bzl
- tools/workspace/highway_internal/BUILD.bazel
- tools/workspace/highway_internal/patches/linkstatic.patch
- tools/workspace/highway_internal/repository.bzl
Another attempt at #21571.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21600)
> [math] Use highway instead of intrinsics

- geometry/benchmarking/BUILD.bazel
- geometry/benchmarking/boxes_overlap_benchmark.cc
- geometry/proximity/BUILD.bazel
- geometry/proximity/test/boxes_overlap_test.cc
- geometry/test_utilities/BUILD.bazel
- geometry/test_utilities/boxes_overlap_transforms.cc
- geometry/test_utilities/boxes_overlap_transforms.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21596)
> [geometry] Add benchmark for internal::BoxesOverlap

- solvers/test/gurobi_solver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21628)
> Fix the test failure on TestSocpDuplicatedVariable3

- multibody/plant/deformable_driver.cc
- multibody/plant/deformable_driver.h
- multibody/plant/discrete_update_manager.h
- multibody/plant/geometry_contact_data.h
- multibody/plant/multibody_plant.cc
- multibody/plant/multibody_plant.h
Towards #21623 and therefore also #20545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21619)
> [multibody] GeometryContactData takes over deformable caching

- multibody/plant/compliant_contact_manager.cc
- multibody/plant/deformable_driver.cc
- multibody/plant/discrete_update_manager.cc
- multibody/plant/discrete_update_manager.h
- multibody/plant/multibody_plant.cc
- multibody/plant/multibody_plant.h
- multibody/plant/sap_driver.cc
- multibody/plant/test/multibody_plant_hydroelastic_test.cc
- multibody/plant/test/multibody_plant_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21589)
> Improve accuracy of prereq tickets in MbP

- multibody/plant/test/multibody_plant_test.cc
- Write down a concise manifest of feedthrough expectations.
- Check that nothing is forgotten in the manifest.
- Use matchers so that gtest prints the differences on error.
Towards https://github.com/RobotLocomotion/drake/pull/21623 and therefore also https://github.com/RobotLocomotion/drake/issues/20545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21638)
> [multibody] Refactor MbP direct feedthrough test for usability

- geometry/optimization/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21637)
> [geometry] Exempt a long test from kcov

- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/test/optimization_test.py
- geometry/optimization/BUILD.bazel
- geometry/optimization/graph_of_convex_sets.cc
- geometry/optimization/graph_of_convex_sets.h
- geometry/optimization/test/graph_of_convex_sets_test.cc
+@hongkai-dai for feature review if you have the time.
Closes #21613.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21641)
> Specify Separate Solver and SolverOptions for GCS Preprocessing

- solvers/constraint.cc
- solvers/constraint.h
- solvers/cost.cc
- solvers/cost.h
As mentioned by Jeremy in his comment https://github.com/RobotLocomotion/drake/issues/21578#issuecomment-2174242791
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21654)
> Use DRAKE_THROW_UNLESS in cost/constraint

- multibody/inverse_kinematics/differential_inverse_kinematics_integrator.h
+@jwnimmer-tri for both reviews, please. (motivated by your anzu PR #13157).  I couldn't find the incantation for the tombstone that you've used in the past for deprecated ports.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21679)
> [DiffIkIntegrator] Update docstring port name X_WE => X_AE.

- bindings/pydrake/multibody/test/plant_test.py
- multibody/plant/discrete_update_manager.cc
- multibody/plant/discrete_update_manager.h
- multibody/plant/multibody_plant.cc
- multibody/plant/multibody_plant.h
Towards making #21623 local development less annoying, and therefore towards #20545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21680)
> [multibody] Avoid per-function template specialization

- multibody/plant/BUILD.bazel
- multibody/plant/test/hydroelastic_contact_info_test.cc
- multibody/plant/test/hydroelastic_traction_calculator_test.cc
Towards https://github.com/RobotLocomotion/drake/pull/21623, and therefore towards https://github.com/RobotLocomotion/drake/issues/20545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21689)
> [multibody] Adjust contact results targets for uniformity

- tools/workspace/abseil_cpp_internal/repository.bzl
- tools/workspace/mujoco_menagerie_internal/repository.bzl
- tools/workspace/mypy_internal/repository.bzl
- tools/workspace/pycodestyle/repository.bzl
- tools/workspace/ros_xacro_internal/repository.bzl
- tools/workspace/rules_python/repository.bzl
- tools/workspace/tinygltf_internal/repository.bzl
- tools/workspace/typing_extensions_internal/repository.bzl
- tools/workspace/vtk_internal/repository.bzl
Towards #21669
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21670)
> July external upgrades

- .bazeliskrc
- doc/_pages/from_source.md
Towards #21669
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21676)
> [setup] Upgrade Bazel to latest release 7.2.1

- geometry/proximity_engine.cc
- geometry/query_object.h
- geometry/test/proximity_engine_test.cc
resolves #21687 #21682
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21698)
> Sort the result of ComputeSignedDistancePairwiseClosestPoints.

- geometry/proximity/mesh_intersection.cc
This patch harvests a small performance win, as suggested by a TODO in the code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21691)
> [geometry] Speed up ClipPolygonbyHalfSpace

- tools/workspace/new_release.py
When reporting the list of external dependencies that can be upgraded, always print a reminder to check if a new version of Bazel is available.
Towards #20741
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21697)
> new_release now prompts to check if Bazel needs to be upgraded

- solvers/constraint.cc
Resolves #21552
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21553)
> Improve the warning message when the Hessian type is indefinite.

- geometry/proximity_engine.cc
- geometry/query_object.h
- geometry/test/proximity_engine_test.cc
Towards #13739
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21709)
> sort the result of ComputeSignedDistanceToPoint.

- geometry/optimization/test/hpolyhedron_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21717)
> Fix HPolyhedron::UniformSample Test Failure on Mac Builds.

- multibody/benchmarking/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21720)
> [benchmark] Increase test size for homecart benchmark

- tools/workspace/new_release.py
- tools/workspace/rust_toolchain/upgrade.py
Towards #21669
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21672)
> [workspace]  Improve new_release script to handle rust_toolchain

- common/BUILD.bazel
- math/BUILD.bazel
- tools/skylark/drake_cc.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21739)
> [math] Remove unnecessary textual_hdrs line

- multibody/plant/contact_results.h
Some deferred clean-up from #20545 for this discussion:
https://reviewable.io/reviews/RobotLocomotion/drake/21694#-O1TCKdN-2fpZe4beTf2:-O1TaNaB2xVul-2l3zKi:bb129ou
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21737)
> [multibody] Clarify some implementation docs

- multibody/plant/BUILD.bazel
- multibody/plant/deformable_contact_info.cc
- multibody/plant/deformable_contact_info.h
- multibody/plant/deformable_driver.cc
- multibody/plant/hydroelastic_contact_info.cc
- multibody/plant/hydroelastic_contact_info.h
- multibody/plant/hydroelastic_quadrature_point_data.h
- multibody/plant/test/contact_results_test.cc
- multibody/plant/test/deformable_contact_info_test.cc
Some deferred clean-up from #20545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21735)
> [multibody] Deprecate some private helper structs

- geometry/optimization/convex_set.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21636)
> Remove experimental caveat on convex set

- geometry/proximity/BUILD.bazel
- geometry/proximity/boxes_overlap.cc
- geometry/proximity/boxes_overlap.h
Resolves #21526.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21733)
> Reimplement OBB box overlap test using highway (simd)

- doc/_pages/buildcop.md
- doc/_pages/jenkins.md
Follow-up to #21617
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21752)
> [doc] Remove mentions of weekly CI jobs

- geometry/proximity/BUILD.bazel
- geometry/proximity/inflate_mesh.cc
- geometry/proximity/inflate_mesh.h
- geometry/proximity/test/inflate_mesh_test.cc
- geometry/proximity/test/make_mesh_field_test.cc
- geometry/proximity/test/make_mesh_from_vtk_test.cc
- geometry/test/non_convex_mesh.vtk
Towards #21514 and related wobbling in our sims.
The "2-days" work discussed in #21528.  
I believe the docs already explain well what this does.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21743)
> Implements mesh inflation for non-convex meshes

- tools/workspace/scs_internal/repository.bzl
Towards #21759
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21769)
> [workspace] Upgrade scs_internal to latest release 3.2.6

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
- multibody/plant/multibody_plant.h
- multibody/plant/test/multibody_plant_com_test.cc
- multibody/plant/test/multibody_plant_jacobians_test.cc
- multibody/tree/multibody_tree.cc
- multibody/tree/multibody_tree.h
Work towards issue #21711 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21740)
> Add model_instances to CalcBiasCenterOfMassTranslationalAcceleration() 

- bindings/pydrake/solvers/solvers_py_snopt.cc
- bindings/pydrake/solvers/test/snopt_solver_test.py
- solvers/snopt_solver.cc
- solvers/snopt_solver.h
- solvers/test/snopt_solver_test.cc
From slack discussion https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1722864395768569
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21781)
> SnoptSolverDetails report solving time.

- setup/mac/binary_distribution/Brewfile
Replaces the deprecated adoptOpenJDK with Temurin
Resolves RobotLocomotion/drake/issues/16779
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21776)
> Update openJDK installation to temurin

- tools/wheel/image/setup.py
To match https://drake.mit.edu/installation.html#supported-configurations.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21787)
> [wheel] Update metadata for 3.10 lower bound

- geometry/geometry_state.cc
- geometry/proximity/BUILD.bazel
- geometry/proximity/hydroelastic_calculator.cc
- geometry/proximity/hydroelastic_internal.cc
- geometry/proximity/hydroelastic_internal.h
- geometry/proximity_engine.cc
- geometry/proximity_properties.cc
- geometry/proximity_properties.h
- geometry/scene_graph_config.h
- geometry/test/geometry_state_test.cc
- geometry/test/proximity_engine_test.cc
- multibody/plant/BUILD.bazel
- multibody/plant/test/multibody_plant_hydroelastic_test.cc
Continuation of work in #21528.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21773)
> Incorporates margin in the compuation of hydroelastic fields.

- multibody/plant/multibody_plant.h
Simple copy/paste so that 
/// @name Bias acceleration functions
is not a sub-group of 
/// @name System matrix computations 
Also added a comment to end @name Bias acceleration functions
/// @} 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21794)
> Copy/paste documentation to avoid subgroup in @name System matrix computations 

- bindings/pydrake/systems/sensors_py_rgbd.cc
- bindings/pydrake/systems/test/sensors_test.py
- systems/sensors/rgbd_sensor.h
Fixes #21788
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21789)
> [RgbdSensor] Expose `X_PB_` via a const getter function

- geometry/optimization/graph_of_convex_sets.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21764)
> improve the error message when attempting to solve GCS problems with convex quadratic constraints

- tools/install/libdrake/drake-config.cmake.in
- tools/workspace/lcm/lcm-config.cmake
- tools/workspace/pybind11/pybind11-config.cmake
Updated deprecated CMake code find_dependency to find_package 
Updated CMake policy version
Issue: https://github.com/RobotLocomotion/drake/issues/21099
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21804)
> Update drake CMake config files for DEE

- geometry/optimization/hyperrectangle.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21814)
> Adds @ingroup geometry_optimization tag to Hyperrectangle

- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/test/optimization_test.py
Resolves #21816.  cc @cohnt 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21817)
> Fix GCS GetGraphvizString bindings to accept default `active_path`

- setup/mac/binary_distribution/requirements.txt
- tools/wheel/image/setup.py
Towards #21830
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21829)
> Pin mac binary numpy version to 2.0.1

- tutorials/updating_costs_and_constraints.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21815)
> Fix a typo found in tutorial update

- multibody/plant/BUILD.bazel
- multibody/topology/BUILD.bazel
- multibody/tree/BUILD.bazel
- tools/install/libdrake/build_components.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21841)
> [topology] Tidy up bazel library spelling

- tools/skylark/drake_cc.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21848)
> [tools] Clarify implementation deps vocabulary

- multibody/parsing/detail_dmd_parser.cc
- multibody/parsing/test/detail_dmd_parser_test.cc
Noticed while developing #21765.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21854)
> [multibody] Fix dmd default_free_body_pose vs offset frames

- tools/dynamic_analysis/kcov_tool
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21859)
> [tools] Fix kcov_tool to work with Bazel 7

- multibody/benchmarking/cassie.cc
Adds position & velocity kinematics benchmarks to the existing Cassie benchmark tests (mass matrix, inverse dynamics, forward dynamics). This is to support multibody kernel performance work because some of the tweaks affect only kinematics -- those effects get buried in the more elaborate computations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21873)
> Add kinematics benchmarks to CassieBench

- .bazeliskrc
- CMakeLists.txt
- WORKSPACE
- tools/bazel.rc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21878)
> [tools] Upgrade bazel to latest release 7.3.1

- setup/ubuntu/source_distribution/install_bazelisk.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21884)
> [setup] Upgrade bazelisk to latest release 1.21.0

- third_party/com_github_bazelbuild_bazelisk/bazelisk.py
- tools/workspace/bazelisk/repository.bzl
Towards #21870.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21888)
> [workspace] Upgrade bazelisk to latest release v1.21.0

- geometry/render_vtk/test/internal_render_engine_vtk_test.cc
Towards #19424.
This takes over from #20470.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21232)
> [render_vtk] Save test images to TEST_UNDECLARED_OUTPUTS_DIR

- geometry/optimization/iris.cc
- multibody/plant/test/multibody_plant_reflected_inertia_test.cc
- multibody/plant/test/sap_driver_joint_limits_test.cc
- planning/trajectory_optimization/gcs_trajectory_optimization.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21897)
> [multibody] Replace copy-pasted string literals with constants

- bindings/pydrake/common/BUILD.bazel
- bindings/pydrake/common/module_py.cc
- bindings/pydrake/common/test/module_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21895)
> Make MemoryFile and Sha256 pickleable

- bindings/pydrake/examples/gym/envs/cart_pole.py
- bindings/pydrake/multibody/test/plant_test.py
- bindings/pydrake/multibody/tree_py.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21896)
> [pydrake] Bind Joint.kTypeName constants

- doc/_release-notes/v1.33.0.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21905)
> [doc] Mention Ventura EOL in 1.33.0 release notes

- solvers/clarabel_solver.cc
- tools/workspace/clarabel_cpp_internal/gen_serialize.py
- tools/workspace/clarabel_cpp_internal/serialize.h
This simplifies the code necessary for the Visit operation.
Towards #21345.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21904)
> [solvers] Flag unsupported clarabel options in the header

- bindings/pydrake/geometry/geometry_py_optimization.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21913)
> [py optimization] Fix nested class declaration order

- geometry/optimization/affine_ball.cc
- geometry/optimization/test/affine_ball_test.cc
+@hongkai-dai for feature review, if you have the time
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21898)
> Implement AffineBall::DoAddPointInNonnegativeScalingConstraints.

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21933)
> Add two missing bindings for MbP

- multibody/plant/multibody_plant.cc
- multibody/plant/test/deformable_integration_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21931)
> Fix contact force port crash when deformables are present

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21930)
> Bind DeformableModel::AddFixedConstraint

- bindings/pydrake/common/test/yaml_test.py
- bindings/pydrake/common/yaml.py
Closes #16262.  I was in the neighborhood, so knocked this out quickly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21935)
> [py common] Improve a yaml_dump error message

- geometry/scene_graph_config.cc
- multibody/parsing/detail_common.cc
- multibody/parsing/detail_sdf_geometry.cc
- multibody/parsing/detail_sdf_geometry.h
- multibody/parsing/detail_urdf_geometry.h
- multibody/parsing/parsing_doxygen.h
- multibody/parsing/test/detail_common_test.cc
- multibody/parsing/test/detail_sdf_geometry_test.cc
- multibody/parsing/test/detail_urdf_geometry_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21831)
> Hydro margin parsing support

- tools/workspace/gurobi/repository.bzl
- tools/workspace/os.bzl
- tools/workspace/snopt/repository.bzl
This is not an issue in production, but came up for me during local back-and-forth experimentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21938)
> [workspace] Re-fetch when the is_wheel_build setting changes

- bindings/pydrake/systems/sensors_py_rgbd.cc
- bindings/pydrake/systems/test/sensors_test.py
- examples/manipulation_station/manipulation_station.cc
- systems/sensors/rgbd_sensor.cc
- systems/sensors/rgbd_sensor.h
- systems/sensors/rgbd_sensor_async.h
- systems/sensors/rgbd_sensor_discrete.cc
- systems/sensors/test/camera_config_functions_test.cc
- systems/sensors/test/rgbd_sensor_test.cc
- systems/sensors/test/sim_rgbd_sensor_test.cc
Also, deprecate a variety of old accessor methods.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21937)
> [sensors] Add parameters to RgbdSensor

- tools/wheel/wheel_builder/linux.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21969)
> [wheel] Test linux 3.12 wheel on Noble (not Mantic)

- bindings/pydrake/planning/planning_py_graph_algorithms.cc
- bindings/pydrake/planning/test/graph_algorithms_test.py
- planning/graph_algorithms/BUILD.bazel
- planning/graph_algorithms/max_clique_solver_base.h
- planning/graph_algorithms/max_clique_solver_via_greedy.cc
- planning/graph_algorithms/max_clique_solver_via_greedy.h
- planning/graph_algorithms/max_clique_solver_via_mip.cc
- planning/graph_algorithms/max_clique_solver_via_mip.h
- planning/graph_algorithms/min_clique_cover_solver_base.cc
- planning/graph_algorithms/min_clique_cover_solver_base.h
- planning/graph_algorithms/min_clique_cover_solver_via_greedy.cc
- planning/graph_algorithms/min_clique_cover_solver_via_greedy.h
- planning/graph_algorithms/test/common_graphs.h
- planning/graph_algorithms/test/max_clique_solver_via_greedy_test.cc
- planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc
- planning/graph_algorithms/test/min_clique_cover_solver_via_greedy_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21892)
> Introduce MinCliqueCoverSolver

- setup/ubuntu/source_distribution/install_bazelisk.sh
- third_party/com_github_bazelbuild_bazelisk/bazelisk.py
- tools/workspace/bazelisk/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21972)
> [workspace] Upgrade bazelisk to latest release v1.22.0

- bindings/pydrake/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21990)
> [pydrake] Hotfix debug timeout for memory_leak_test

- .bazeliskrc
- doc/_pages/from_source.md
Toward #21979.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21997)
> [setup] Upgrade Bazel to latest release 7.3.2

- geometry/optimization/hyperellipsoid.cc
- geometry/optimization/hyperellipsoid.h
- geometry/optimization/test/hyperellipsoid_test.cc
Closes #21976.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21985)
> Add Hyperellipsoid::Scale() functionality

- doc/_pages/issues.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22000)
> Add issue component for graphs of convex sets

- bindings/pydrake/manipulation/BUILD.bazel
- bindings/pydrake/manipulation/manipulation_py.cc
- bindings/pydrake/multibody/BUILD.bazel
- bindings/pydrake/multibody/math_py.cc
- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/tree_py.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22002)
> [py multibody] Fix signatures to use Python types (not C++)

- geometry/mesh_source.cc
- geometry/mesh_source.h
- geometry/render/render_material.h
- geometry/render_gl/BUILD.bazel
- geometry/render_gl/internal_render_engine_gl.cc
- geometry/render_gl/internal_render_engine_gl.h
- geometry/render_gl/internal_texture_library.cc
- geometry/render_gl/internal_texture_library.h
- geometry/render_gl/test/internal_render_engine_gl_test.cc
- geometry/test/mesh_source_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21953)
> RenderEngineGl supports in-memory meshes

- tools/workspace/python/package.BUILD.bazel
- tools/workspace/python/repository.bzl
Towards #21844.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21999)
> [workspace] Refactor python rule for maintainability

- geometry/render_gltf_client/BUILD.bazel
- geometry/render_gltf_client/test/acceptance_test.py
- geometry/render_gltf_client/test/client_demo.cc
In support of #21894.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22008)
> [render_gltf_client] Actually test something in the acceptance test

- geometry/render_gltf_client/test/acceptance_test.py
- tools/workspace/vtk_internal/patches/io_geometry_gltf_default_scene.patch
- tools/workspace/vtk_internal/repository.bzl
In support of #21894.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22011)
> [render_gltf_client] Fix defective glTF input in acceptance test

- solvers/mathematical_program.cc
- solvers/mathematical_program.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22023)
> Move AddPositiveSemidefiniteConstraint implementation to cc file.

- doc/_pages/platform_reviewer_checklist.md
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22034)
> Add new GCS tag to platform reviewer checklist

- geometry/optimization/test/graph_of_convex_sets_test.cc
#21641 allowed us to specify a separate solver and solver options for the preprocessing stage of GCS. This gives us a much more reliable way of verifying that options are being propagated into the preprocessing stage, so I've removed the old test for this functionality.
I've also modified the existing test to verify that these options are being propagated even when the user doesn't specify special options for the preprocessing solver, which I believe was a gap in test coverage.
cc @SeanCurtis-TRI since I'm removing/completing a TODO of yours.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22035)
> Remove an obsolete test from GCS.

- doc/_pages/release_playbook.md
The website UX has changed again, so the prior steps were not quite accurate anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22056)
> [doc] Adjust deepnote deployment instructions

- geometry/render_vtk/render_engine_vtk_params.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22058)
> Clarify VTK shadow documentation

- .bazeliskrc
- doc/_pages/from_source.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22066)
> [setup] Upgrade Bazel to latest release 7.4.0

- bindings/pydrake/test/trajectories_test.py
- bindings/pydrake/trajectories_py.cc
- common/trajectories/BUILD.bazel
- common/trajectories/function_handle_trajectory.cc
- common/trajectories/function_handle_trajectory.h
- common/trajectories/test/function_handle_trajectory_test.cc
Resolves #20699.
I still need to write more tests, but I hope this gets you unstuck @cohnt and @shrutigarg914 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21093)
> Implements FunctionHandleTrajectory

- solvers/mosek_solver_internal.cc
- solvers/nlopt_solver.cc
Hotfix for #22079.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22080)
> [solvers] Hotfix for fmt errors

- bindings/pydrake/geometry/geometry_py_visualizers.cc
- bindings/pydrake/geometry/test/visualizers_test.py
- bindings/pydrake/systems/framework_py_systems.cc
- bindings/pydrake/systems/test/custom_test.py
- geometry/meshcat_visualizer.h
- geometry/test/meshcat_visualizer_test.cc
- multibody/plant/BUILD.bazel
- multibody/plant/deformable_driver.cc
- multibody/plant/hydroelastic_contact_info.cc
- multibody/plant/hydroelastic_contact_info.h
- multibody/tree/geometry_spatial_inertia.h
- systems/framework/test/vector_system_test.cc
- systems/framework/vector_system.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22086)
> Remove deprecated code 2024-11 🎃

- solvers/gurobi_solver.cc
Closes #22107.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22108)
> [solvers] Fix Gurobi console logging obey our defaults again

- doc/_pages/bazel.md
- doc/_pages/profiling.md
- tools/cc_toolchain/BUILD.bazel
- tools/cc_toolchain/bazel.rc
- tools/skylark/drake_cc.bzl
Closes #21041.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22111)
> [tools] Remove unsupported apple_debug configuration

- tutorials/BUILD.bazel
Simply re-ordering the build targets so they're easy to read through.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22124)
> Alphabetize tutorials

- setup/ubuntu/source_distribution/install_bazelisk.sh
Follow-up to #22119
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22128)
> Hotfix for bazelisk checksum

- solvers/common_solver_option.h
- solvers/solver_options.h
Towards #22078.  In that PR, I am fixing / heavily editing a lot of this text, and I don't want to mix these formatting changes in with the actually-meaningful edits.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22101)
> [solvers] Reflow option classes' comments to my preferred style

- solvers/constraint.cc
- solvers/constraint.h
- solvers/test/constraint_test.cc
As mentioned in https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1730718062496299?thread_ts=1730511193.767279&cid=C3L92BM2Q
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22125)
> Set gradient sparsity pattern in LorentzConeConstraint and RotatedLorentzConeConstraint.

- common/schema/rotation.cc
- common/schema/rotation.h
- common/schema/test/rotation_test.cc
This brings it on par with `Transform::Sample`.
Closes #21416.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22113)
> [schema] Add Rotation::Sample

- tools/workspace/nanoflann_internal/repository.bzl
Upgrades nanoflann_internal to latest v1.6.2
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22130)
> [workspace] Upgrade nanoflann_internal to latest release v1.6.2

- bindings/pydrake/solvers/solvers_py_evaluators.cc
- bindings/pydrake/solvers/test/mathematicalprogram_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22151)
> Adds missing sparse UpdateCoefficient binding to LinearEqualityConstaint

- geometry/optimization/convex_set.cc
+@alexandreamice for feature review
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22167)
> Only update individual coefficients of the cost in ConvexSet::IsBounded.

- solvers/aggregate_costs_constraints.cc
- solvers/aggregate_costs_constraints.h
- solvers/clarabel_solver.cc
- solvers/scs_clarabel_common.cc
- solvers/scs_clarabel_common.h
- solvers/scs_solver.cc
- solvers/test/aggregate_costs_constraints_test.cc
- solvers/test/clarabel_solver_test.cc
- solvers/test/scs_solver_test.cc
Include dual for both PositiveSemidefiniteConstraint and LinearMatrixInequalityConstraint.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22147)
> Return dual solution for PSD constraint in SCS and Clarabel.

- doc/_pages/from_binary.md
- doc/_release-notes/v1.35.0.md
* Put back missing hyperlinks that somehow evaporated.
* Move the EGL note into a different section.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22181)
> [doc] Release notes 1.35.0 tweaks

- bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
- bindings/pydrake/solvers/solvers_py_options.cc
- bindings/pydrake/solvers/test/mathematicalprogram_test.py
Amends #21857.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22180)
> [py solvers] Add missing options bindings

- multibody/mpm/BUILD.bazel
- multibody/mpm/spgrid.h
- multibody/mpm/test/spgrid_test.cc
Dear @xuchenhan-tri ,
The on-call build cop, @BetsyMcPhail , believes that your PR #22163 may have
[linux-jammy-clang-bazel-nightly-valgrind-memcheck](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-jammy-clang-bazel-nightly-valgrind-memcheck/377/)
now. You can then fix the problem at your …
> Revert "Implement SpGrid for MPM"

- systems/framework/test_utilities/scalar_conversion.h
As of Xcode 16 or so, it is no longer safe to blithely dynamic_cast a system to a type that it has statically forbidden conversion support for. Instead, check (statically) for conversion support, and only then step through the dynamic conversion test steps. Give a nice error message if the conversion is forbidden statically.
While here, revert an obsolete compiler workaround, and fold the implementation code down from two copies to one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22188)
> [framework] Update scalar conversion test utility

- doc/_pages/installation.md
We closed https://github.com/RobotLocomotion/drake/issues/12782 as "won't fix".
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22202)
> [doc] Abandon hope for homebrew packages

- tools/workspace/rules_cc/patches/rm_protobuf.patch
- tools/workspace/rules_cc/repository.bzl
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22183)
> [workspace] Upgrade rules_cc to 0.0.16

- bindings/pydrake/common/deprecation_pybind.h
- bindings/pydrake/common/test/deprecation_example/cc_module_py.cc
- bindings/pydrake/common/test/deprecation_example/example_class.h
- bindings/pydrake/common/test/deprecation_utility_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22195)
> [py common] Fix GIL hazard in WrapDeprecated

- solvers/aggregate_costs_constraints.cc
- solvers/aggregate_costs_constraints.h
- solvers/clarabel_solver.cc
- solvers/scs_clarabel_common.cc
- solvers/scs_clarabel_common.h
- solvers/scs_solver.cc
- solvers/test/aggregate_costs_constraints_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22200)
> SCS and Clarabel parses scalar PSD constraint as linear constraint.

- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/test/optimization_test.py
- geometry/optimization/test/vpolytope_test.cc
- geometry/optimization/vpolytope.cc
- geometry/optimization/vpolytope.h
Closes #22218.
+@hongkai-dai for feature review if you're avaiable?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22220)
> Compute Minimal Representation of Degenerate VPolytopes

- bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
- bindings/pydrake/solvers/test/mathematicalprogram_test.py
- solvers/mathematical_program.cc
- solvers/mathematical_program.h
- solvers/test/mathematical_program_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22211)
> Add MathematicalProgram::AddLinearMatrixInequalityConstraint for a matrix of symbolic expressions.

- tools/dynamic_analysis/bazel.rc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22224)
> [tools] Boost kcov timeouts

- tools/workspace/cc/repository.bzl
In Bazel 8, the local_config_cc repository name is different, even when bzlmod is disabled.
Testing with this command:
```console
env USE_BAZEL_VERSION=8.0.0rc2 \
bazel build --enable_bzlmod=false //tools/cc_toolchain:capture_cc.env
cat bazel-bin/tools/cc_toolchain/capture_cc.env
```
On master, we see this:
```
Computing main repo mapping: 
ERROR: Error computing the main repository mapping:
at tools/workspace/default.bzl:8:6:
at tools/workspace/cc/repository.bzl:31:6:
cannot load '@@bazel_tools//tools/cpp:unix_cc_configure.bzl': no such file
```
On this branch, we see this:
```
...
INFO: Build completed successfully, 1 total action
BAZEL_CC="/usr/bin/gcc"
BAZEL_CC_FLAGS=""
```
Note that even _more_ changes will be required for `--enable_bzlmod=true` to succeed; this PR is …
> [tools] Accept bzlmod's spelling of local_config_cc

- planning/iris/iris_from_clique_cover.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22246)
> Fixes broadcasting bug in IrisInConfigurationSpaceFromCliqueCover

- solvers/aggregate_costs_constraints.cc
Previously we also add zero coefficient, which is still correct, but unnecessary.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22241)
> Only add non-zero coefficient to SCS/Clarabel LMI constraint.

- bindings/pydrake/geometry/BUILD.bazel
- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/test/optimization_test.py
- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
- geometry/optimization/geodesic_convexity.cc
- geometry/optimization/geodesic_convexity.h
- geometry/optimization/test/geodesic_convexity_test.cc
- multibody/plant/BUILD.bazel
- multibody/plant/hydroelastic_quadrature_point_data.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22248)
> Remove deprecated code 2024-12

- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/test/optimization_test.py
Resolves #22250.
+@cohnt for feature review, please.
cc @sadraddini 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22254)
> Add python binding for `AffineBall::MakeAffineBallFromLineSegment`

- math/matrix_util.cc
- math/matrix_util.h
- math/test/matrix_util_test.cc
- solvers/BUILD.bazel
- solvers/clarabel_solver.cc
- solvers/scs_solver.cc
- solvers/test/scs_solver_test.cc
We can specify solver options standalone_reproduction_file_name to write a python script, that will reproduce the optimization program in SCS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22223)
> Reproduce the SCS program with python code.

- tools/workspace/rules_cc/repository.bzl
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22263)
> [workspace] Upgrade rules_cc to latest release 0.0.17

- math/matrix_util.cc
- solvers/scs_solver.cc
fmt::join requires #include <fmt/ranges.h>.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22273)
> Hot fix on 22223

- setup/mac/source_distribution/requirements-build.txt
- setup/mac/source_distribution/requirements-test.txt
Towards #22240
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22267)
> [setup] Upgrade Python venv (mac) to latest

- setup/ubuntu/source_distribution/install_bazelisk.sh
- tools/workspace/abseil_cpp_internal/repository.bzl
- tools/workspace/bazelisk/repository.bzl
- tools/workspace/dm_control_internal/repository.bzl
- tools/workspace/googlebenchmark/repository.bzl
- tools/workspace/mujoco_menagerie_internal/repository.bzl
- tools/workspace/stable_baselines3_internal/repository.bzl
- tools/workspace/tinyobjloader_internal/repository.bzl
- tools/workspace/tomli_internal/repository.bzl
- tools/workspace/vtk_internal/repository.bzl
Towards #22240
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22249)
> December external upgrades

- geometry/BUILD.bazel
- geometry/poisson_disk.cc
- geometry/poisson_disk.h
- geometry/test/poisson_disk_test.cc
- tools/workspace/BUILD.bazel
- tools/workspace/default.bzl
- tools/workspace/poisson_disk_sampling_internal/BUILD.bazel
- tools/workspace/poisson_disk_sampling_internal/package.BUILD.bazel
- tools/workspace/poisson_disk_sampling_internal/patches/upstream/positive_capacity.patch
- tools/workspace/poisson_disk_sampling_internal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22243)
> Add poisson disk sampling

- multibody/parsing/detail_mujoco_parser.cc
- multibody/parsing/test/detail_mujoco_parser_test.cc
The InertialCalculator returns NaNs for HalfSpace, which would be fine, but then the SpatialInertial constructor threw an exception immediately after.
This PR avoids that particular failure (by not computing the inertia of a HalfSpace), and also improves the error message so that if we _do_ calculate an invalid inertia, we also print the geom name.
fyi @aykut-tri
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22290)
> [mujoco parser] Don't compute inertia of a HalfSpace

- .bazeliskrc
- doc/_pages/from_source.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22285)
> [setup] Upgrade Bazel to latest release 8.0.0

- common/find_runfiles.cc
Towards #22269.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22293)
> [common] Refactor FindRunfile error handling for clarity

- bindings/pydrake/solvers/solvers_py_evaluators.cc
- bindings/pydrake/solvers/test/evaluators_test.py
- solvers/cost.cc
- solvers/cost.h
- solvers/test/cost_test.cc
Including LInfNormCost, L1NormCost, PerspectiveQuadraticCost.
Resolves #22131
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22260)
> update individual entry in A/b of some costs.

- multibody/mpm/BUILD.bazel
- multibody/mpm/bspline_weights.cc
- multibody/mpm/bspline_weights.h
- multibody/mpm/test/bspline_weights_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22289)
> Add BsplineWeights for MPM

- bindings/pydrake/test/trajectories_test.py
- bindings/pydrake/trajectories_py.cc
- common/trajectories/BUILD.bazel
- common/trajectories/function_handle_trajectory.cc
- common/trajectories/function_handle_trajectory.h
- common/trajectories/test/function_handle_trajectory_test.cc
Resolves #22076.
+@cohnt for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22262)
> Support (opt-in) derivatives in FunctionHandleTrajectory.

- MODULE.bazel
- tools/workspace/rules_rust/repository.bzl
- tools/workspace/rust_toolchain/lock/archives.bzl
- tools/workspace/rust_toolchain/lock/details/BUILD.rust_darwin_aarch64__aarch64-apple-darwin__stable_tools.bazel
- tools/workspace/rust_toolchain/lock/details/BUILD.rust_darwin_x86_64__x86_64-apple-darwin__stable_tools.bazel
- tools/workspace/rust_toolchain/lock/details/BUILD.rust_linux_aarch64__aarch64-unknown-linux-gnu__stable_tools.bazel
- tools/workspace/rust_toolchain/lock/details/BUILD.rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools.bazel
- tools/workspace/rust_toolchain/upgrade/.bazeliskrc
Upgrade rules_rust to latest release 0.55.6.
Upgrade rust_toolchain to 1.83.0.
Towards #22269.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22302)
> [workspace] Upgrade rules_rust and rust_toolchain

- tools/workspace/drake_models/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22304)
> [drake_models] Increase parse_test timeout

- multibody/parsing/detail_instanced_name.cc
- multibody/parsing/detail_instanced_name.h
- multibody/parsing/test/detail_instanced_name_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22029)
> [parsing] Drop compatibility code for Ventura

- multibody/mpm/BUILD.bazel
- multibody/mpm/grid_data.h
- multibody/mpm/test/grid_data_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22295)
> Add GridNodeIndex and GridData for MPM

- examples/hardware_sim/test/hardware_sim_test_common.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22320)
> [examples] Disable test case on macOS Sequoia

- MODULE.bazel
- tools/bazel.rc
- tools/workspace/rules_rust/repository.bzl
- tools/workspace/rust_toolchain/lock/details/BUILD.rust_darwin_aarch64__aarch64-apple-darwin__stable_tools.bazel
- tools/workspace/rust_toolchain/lock/details/BUILD.rust_darwin_x86_64__x86_64-apple-darwin__stable_tools.bazel
- tools/workspace/rust_toolchain/lock/details/BUILD.rust_linux_aarch64__aarch64-unknown-linux-gnu__stable_tools.bazel
- tools/workspace/rust_toolchain/lock/details/BUILD.rust_linux_x86_64__x86_64-unknown-linux-gnu__stable_tools.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22319)
> [workspace] Upgrade rules_rust to latest release 0.56.0

- doc/_pages/from_source.md
- doc/_pages/installation.md
Resolves #21910
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22324)
> [doc] Offically support macOS Sequoia

- geometry/proximity/BUILD.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22332)
> [geometry] Shard a test to reduce CI timeouts in debug builds

- doc/defs.py
- doc/doxygen_cxx/build.py
- doc/pydrake/conf.py
Amends #22269.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22336)
> [build] Hotfix docs build for bzlmod

- bindings/pydrake/common/ref_cycle_pybind.h
- bindings/pydrake/geometry/BUILD.bazel
- bindings/pydrake/geometry/geometry_py_visualizers.cc
- bindings/pydrake/geometry/test/visualizers_test.py
- bindings/pydrake/manipulation/BUILD.bazel
- bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc
- bindings/pydrake/manipulation/test/kuka_iiwa_test.py
- bindings/pydrake/planning/BUILD.bazel
- bindings/pydrake/planning/planning_py_robot_diagram.cc
- bindings/pydrake/planning/test/robot_diagram_test.py
- bindings/pydrake/systems/BUILD.bazel
- bindings/pydrake/systems/builder_life_support_pybind.h
- bindings/pydrake/systems/framework_py_semantics.cc
- bindings/pydrake/systems/framework_py_systems.cc
- bindings/pydrake/systems/test/builder_life_support_test.py
- bindings/pydrake/systems/test/controllers_test.py
- bindings/pydrake/systems/test/lifetime_test.py
- bindings/pydrake/systems/test/test_util_py.cc
- bindings/pydrake/test/memory_leak_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22221)
> [pydrake] Fix diagram memory leaks

- doc/_pages/credits.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22339)
> Add name to credits.md

- bindings/pydrake/common/test_utilities/BUILD.bazel
- tools/workspace/drake_models/BUILD.bazel
- tools/workspace/drake_models/test/parse_test.py
This helps reduce the outlier test latency.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22344)
> [models] Add sharding to all-files parse_test

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22356)
> [multibody] Add binding for MultibodyPlant::GetActuationFromArray()

- systems/controllers/inverse_dynamics_controller.h
Inspired by #17409.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22366)
> Touchup doc string for InverseDynamicsController

- bindings/pydrake/geometry/geometry_py_scene_graph.cc
Towards #5842 and #21968.  We must stop passing `unique_ptr` as an argument from Python down to C++... passing `unique_ptr` in an argument of a call from Python into C++ is made possible by Drake-specific hacks to pybind11, and we need to get rid of the hacks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22352)
> [pydrake] Adjust RegisterGeometry bindings to avoid unique_ptr

- tools/skylark/py.bzl
- tools/workspace/python/package.BUILD.bazel
- tools/workspace/python/repository.bzl
- tools/workspace/python/venv_sync
Towards #22346 and #20731.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22354)
> [build] Adjust py_toolchain to directly depend on requirements

- tools/wheel/wheel_builder/common.py
When building locally, the "incubator" layer was being unnecessarily rebuilt every time due to gzip nondeterminism. With this fix, local wheel builds are incremental (fast) again.
To test it locally, try `bazel run //tools/wheel:builder -- --python=310 0.0.0` twice in a row.  With this PR, the second build should take around 10 seconds.  On master, it takes several minutes.
Amends #21647.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22391)
> [wheel] Speed up local rebuilds

- multibody/parsing/detail_mujoco_parser.cc
- multibody/parsing/test/detail_mujoco_parser_examples_test.cc
- multibody/parsing/test/detail_mujoco_parser_test.cc
Towards #20444.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22387)
> Fix "more than one orientation" error in mujoco parser

- tools/workspace/spral_internal/patches/upstream/pointer_math_undefined_behavior.patch
- tools/workspace/spral_internal/repository.bzl
Hotfix for #22385.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22400)
> [workspace] Fix undefined behavior in spral LDLT

- multibody/benchmarks/free_body/test/multibody_plant_free_body_test.cc
- multibody/plant/multibody_plant.h
- multibody/plant/test/floating_body_test.cc
- multibody/test_utilities/floating_body_plant.cc
- multibody/test_utilities/floating_body_plant.h
Closes #10310.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22397)
> [multibody] Deprecate subclassing of MultibodyPlant

- bindings/pydrake/common/test/yaml_typed_test.py
- bindings/pydrake/common/yaml.py
Towards #22078 (and thus #20967).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22394)
> [pydrake] Fix yaml_dump_typed for Union on str

- common/yaml/yaml_read_archive.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22406)
> [yaml] Hotfix for binary decoding error message

- bindings/pydrake/common/BUILD.bazel
- bindings/pydrake/common/test/yaml_typed_test.py
- bindings/pydrake/common/yaml.py
- common/yaml/test/example_structs.h
- common/yaml/test/yaml_read_archive_test.cc
Amends #22318.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22410)
> [py yaml] Deprecate certain implicit primitive conversions

- bindings/pydrake/solvers/test/clp_solver_test.py
- bindings/pydrake/solvers/test/ipopt_solver_test.py
- solvers/clp_solver_common.cc
- solvers/ipopt_solver_common.cc
- solvers/mosek_solver_common.cc
Upstream prefers the scream case (https://www.mosek.com/products/mosek/).
Towards #20967.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22407)
> [solvers] Change solver names to upstream's preferred case

- common/test_utilities/diagnostic_policy_test_base.h
* delete unused method FormatFirstWarning
* evict text logging code
* refactor error checking for Take() into Take() itself
FormatFirstError() should also go, but that is for another day...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22404)
> DiagnosticPolicyTestBase cleanups

- common/test_utilities/diagnostic_policy_test_base.h
- multibody/parsing/test/detail_sdf_geometry_test.cc
- multibody/parsing/test/detail_sdf_parser_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22418)
> [parsing] Delete FormatFirstError; fix call sites

- doc/styleguide/build.py
Amends #22338.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22429)
> [build] Hotfix doc builds for MODULE.bazel respelling

- tools/wheel/wheel_builder/common.py
Amends #22338.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22428)
> [build] Hotfix wheel builds for MODULE.bazel respelling

- CMakeLists.txt
Amends #22338.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22433)
> [build] Hotfix CMake builds for MODULE.bazel respelling

- tools/wheel/macos/build-wheel.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22439)
> [build] Hotfix macOS wheel builds for MODULE.bazel

- tools/workspace/drake_models/repository.bzl
Bringing in https://github.com/RobotLocomotion/models/pull/73.
+@seancurtis-tri for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22408)
> Update drake_models to get atlas w/ textures

- bindings/pydrake/geometry/geometry_py_common.cc
- bindings/pydrake/geometry/geometry_py_optimization.cc
- bindings/pydrake/geometry/test/common_test.py
- bindings/pydrake/geometry/test/optimization_test.py
For release engineers, this includes:
- Convex::Convex(points)
- VPolytope::ToShapeConvex()
Related to #22390
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22442)
> Add bindings for Convex construction from points

- tools/workspace/styleguide/repository.bzl
Context from TRI Slack: https://tri-internal.slack.com/archives/C16R6JA0M/p1733763131637889
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22409)
> Update styleguide commit and sha256

- tools/dynamic_analysis/tsan.sh
Like #22232 but also now for TSan.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22459)
> [tools] Disable ASLR during TSan

- multibody/tree/rotational_inertia.cc
- multibody/tree/rotational_inertia.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22466)
> Move RotationalInertia code from .h file to .cc file.

- bindings/pydrake/common/test/ref_cycle_test_util_py.cc
- bindings/pydrake/common/test/serialize_import_failure_test.py
- tools/skylark/pybind.bzl
- tools/workspace/pybind11/patches/check_signature_infection.patch
- tools/workspace/pybind11/repository.bzl
Closes #17520.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22450)
> [pydrake] Fail-fast when C++ types infect function signatures

- planning/dev/BUILD.bazel
+@BetsyMcPhail for review, thanks!
cc @jwnimmer-tri
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22486)
> Disable TSAN on voxel_self_filter_test

- multibody/meshcat/BUILD.bazel
- multibody/meshcat/contact_visualizer.h
- multibody/meshcat/hydroelastic_contact_visualizer.h
- multibody/meshcat/joint_sliders.cc
- multibody/meshcat/point_contact_visualizer.cc
- multibody/meshcat/test/contact_visualizer_test.cc
- multibody/meshcat/test/hydroelastic_contact_visualizer_test.cc
- multibody/meshcat/test/joint_sliders_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22501)
> [multibody/meshcat] Enable clang-format-lint

- tools/wheel/image/build-drake.sh
- tools/wheel/image/packages-jammy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22499)
> [wheel] Remove JDK from dependencies

- geometry/render_vtk/test/internal_render_engine_vtk_test.cc
Let's see if AppleClang is up to the job these days ...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22507)
> [render_vtk] Use source_location in test

- bindings/pydrake/visualization/_meldis.py
- bindings/pydrake/visualization/test/meldis_test.py
Closes #22512
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22513)
> [meldis] Fix bug in deformable channels

- geometry/render_gl/BUILD.bazel
- tools/wheel/image/build-drake.sh
- tools/wheel/macos/build-wheel.sh
- tools/wheel/test/tests/libs-test.py
Our lack of dylib wheel testing let two bugs go unnoticed in prior PRs, so here we add a regression test for next time.
Amends #22494.  
Amends #22421.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22518)
> [build] Don't link X11 on macOS

- systems/analysis/test/simulator_test.cc
* Remove excessive triple-slash
* Clean up floating point literals
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22522)
> [analysis] Cleanup simulator_test

- bindings/pydrake/systems/drawing.py
- tutorials/dynamical_systems.ipynb
- tutorials/working_with_diagrams.ipynb
Resolves #16313
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22526)
> plot_graphviz uses ipython display with svg in notebooks

- CMakeLists.txt
Used by RobotLocomotion/drake-ci#302.
Towards #22519.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22523)
> [build] CMake checks for DRAKE_CI_ENABLE_PACKAGING

- MODULE.bazel
- bindings/pydrake/common/test/ref_cycle_test_util_py.cc
- bindings/pydrake/common/wrap_pybind.h
- bindings/pydrake/math_operators_pybind.h
- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/systems/framework_py_semantics.cc
- common/symbolic/expression/test/expression_test.cc
- common/symbolic/test/generic_polynomial_test.cc
- geometry/optimization/convex_set.h
- geometry/optimization/graph_of_convex_sets.cc
- geometry/proximity/make_box_mesh.cc
- geometry/proximity/volume_to_surface_mesh.cc
- geometry/render_vtk/test/internal_render_engine_vtk_test.cc
- manipulation/kuka_iiwa/iiwa_status_receiver.cc
- math/autodiff.h
- math/compute_numerical_gradient.h
- multibody/contact_solvers/pgs_solver.cc
- multibody/contact_solvers/sap/sap_limit_constraint.h
- multibody/contact_solvers/sap/sap_model.h
- multibody/contact_solvers/sap/sap_solver.h
- multibody/plant/tamsi_solver.h
- multibody/tree/test/tree_from_mobilizers_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22554)
> [workspace] Upgrade clang-format to release 19.1.3

- bindings/pydrake/common/module_py.cc
- bindings/pydrake/common/test/module_test.py
- common/BUILD.bazel
- common/memory_file.cc
- common/memory_file.h
- common/test/file_source_test.cc
- common/test/memory_file_test.cc
- tools/workspace/pybind11/mkdoc_comment.py
Towards #22060.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22560)
> [common] Enable serialization for MemoryFile

- tools/workspace/gurobi/package-darwin.BUILD.bazel.in
- tools/workspace/gurobi/package-linux.BUILD.bazel.in
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22571)
> [workspace] Remove unused and bitrotted gurobi_cxx target

- bindings/pydrake/multibody/BUILD.bazel
- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/lifetime_test.py
- multibody/plant/multibody_plant.cc
- multibody/plant/multibody_plant.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22595)
> [pydrake] Avoid unique_ptr in "add plant" functions

- common/identifier.h
- common/type_safe_index.h
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22610)
> fix typos: indentifier => identifier

- multibody/parsing/BUILD.bazel
- multibody/parsing/detail_sdf_geometry.h
- multibody/parsing/detail_urdf_geometry.h
- multibody/parsing/test/acrobot_parser_test.cc
- multibody/parsing/test/collision_filter_groups_test.cc
- multibody/parsing/test/common_parser_test.cc
- multibody/parsing/test/detail_collision_filter_group_resolver_test.cc
- multibody/parsing/test/detail_common_test.cc
- multibody/parsing/test/detail_dmd_parser_test.cc
- multibody/parsing/test/detail_make_model_name_test.cc
- multibody/parsing/test/detail_mesh_parser_test.cc
- multibody/parsing/test/detail_mujoco_parser_examples_test.cc
- multibody/parsing/test/detail_mujoco_parser_test.cc
- multibody/parsing/test/detail_path_utils_test.cc
- multibody/parsing/test/detail_sdf_geometry_test.cc
- multibody/parsing/test/detail_select_parser_test.cc
- multibody/parsing/test/detail_tinyxml2_diagnostic_test.cc
- multibody/parsing/test/detail_tinyxml_test.cc
- multibody/parsing/test/detail_urdf_geometry_test.cc
- multibody/parsing/test/detail_usd_geometry_test.cc
- multibody/parsing/test/detail_usd_parser_test.cc
- multibody/parsing/test/drake_manifest_resolution_test.cc
- multibody/parsing/test/package_map_test.cc
- multibody/parsing/test/parser_manual_test.cc
- multibody/parsing/test/parser_test.cc
- multibody/parsing/test/process_model_directives_test.cc
- multibody/parsing/test/test_loaders.cc
- multibody/parsing/test/test_loaders.h
Towards #4843 and #22531.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22614)
> [multibody] Clang-format all remaining parsing code

- bindings/pydrake/planning/planning_py_trajectory_optimization.cc
- bindings/pydrake/planning/test/trajectory_optimization_test.py
- planning/trajectory_optimization/kinematic_trajectory_optimization.cc
- planning/trajectory_optimization/kinematic_trajectory_optimization.h
- planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Use the placeholder variable in the constraint binding. Adds a linear constraint on the decision variable when the user wants lb <= A * qdot(s * T) <= ub.
Also resolves #22532 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22599)
> KinematicTrajectoryOptimization adds velocity linear constraint.

- bindings/pydrake/planning/BUILD.bazel
- bindings/pydrake/planning/planning_py_collision_checker.cc
- bindings/pydrake/planning/planning_py_collision_checker_interface_types.cc
- bindings/pydrake/planning/test/collision_checker_test.py
- planning/collision_checker_params.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22619)
> [pydrake] avoid unique_ptr in CollisionChecker API

- bindings/pydrake/geometry/geometry_py_visualizers.cc
- bindings/pydrake/geometry/test/visualizers_test.py
Resolves #22617
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22650)
> Add missing bindings from MeshcatAnimation

- tools/release_engineering/dev/push_release
Follow-up to #19735. Fixes error found while completing #22645.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22656)
> push_release: Fix-up error in creating apt packages

- bindings/pydrake/systems/analysis_py.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22661)
> [pydrake] Fix annotation typo

- bindings/pydrake/systems/analysis_py.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22668)
> [pydrake] Rebind StopDenseIntegration for vanilla pybind11

- bindings/pydrake/geometry/geometry_py_render.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22685)
> [pybdrake] Rebind render factories for vanilla pybind11

- tools/workspace/abseil_cpp_internal/repository.bzl
- tools/workspace/buildifier/repository.bzl
- tools/workspace/drake_models/repository.bzl
- tools/workspace/gtest/repository.bzl
- tools/workspace/gymnasium_py/repository.bzl
- tools/workspace/libpng_internal/repository.bzl
- tools/workspace/mujoco_menagerie_internal/repository.bzl
- tools/workspace/mypy_internal/repository.bzl
- tools/workspace/nanoflann_internal/repository.bzl
- tools/workspace/openusd_internal/repository.bzl
- tools/workspace/suitesparse_internal/repository.bzl
Towards: #22666
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22670)
> March external upgrades

- bindings/pydrake/systems/sensors_py_camera_config.cc
- bindings/pydrake/systems/test/sensors_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22697)
> [pydrake] Add missing bindings for CameraConfig helper structs

- bindings/pydrake/test/trajectories_test.py
- bindings/pydrake/trajectories_py.cc
- common/trajectories/discrete_time_trajectory.cc
- common/trajectories/discrete_time_trajectory.h
Also resolves #22624.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22653)
> Python bindings for DiscreteTimeTrajectory class

- doc/_pages/credits.md
I forgot we're supposed to be adding these to our docs to give thanks, per the `tools/workspace/README`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22710)
> [doc] Add recently-added externals to credits

- geometry/proximity/volume_mesh_refiner.cc
- geometry/proximity/volume_mesh_refiner.h
Resolve #22675 Speed up refine_mesh.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22709)
> [geometry] Speed up VolumeMeshRefiner with local search

- tools/workspace/spral_internal/package.BUILD.bazel
- tools/workspace/spral_internal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22713)
> [workspace] Upgrade spral_internal to latest release v2025.03.06

- multibody/mpm/BUILD.bazel
- multibody/mpm/sparse_grid.cc
- multibody/mpm/sparse_grid.h
- multibody/mpm/spgrid.h
- multibody/mpm/test/particle_sorter_test.cc
- multibody/mpm/test/sparse_grid_test.cc
- multibody/mpm/test/spgrid_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22716)
> [mpm] Streamline valgrind fix for SpGrid

- bindings/pydrake/planning/planning_py_iris_zo.cc
- bindings/pydrake/planning/test/iris_zo_test.py
- planning/iris/BUILD.bazel
- planning/iris/iris_zo.cc
- planning/iris/iris_zo.h
- planning/iris/test/iris_zo_test.cc
Closes #22672.
Not ready for review yet. I'm creating the PR now so I can run the CI tests (especially memcheck). Also waiting for #22618 to merge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22706)
> Expression Parameterization for IRIS-ZO

- bindings/pydrake/pydrake_pybind.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22734)
> [pydrake] Rewrite DefClone() helper for vanilla pybind11

- common/timer.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22736)
> [common] Fix typo in include path

- doc/_pages/credits.md
I knew I was going to forget to mention this in #22739, and in fact I did.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22749)
> [doc] Remove Conex

- systems/analysis/semi_explicit_euler_integrator.cc
- systems/analysis/semi_explicit_euler_integrator.h
- systems/analysis/test/semi_explicit_euler_integrator_test.cc
Resolves #22744
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22751)
> Document SemiExplicitEulerIntegrator to support Expression scalar type

- systems/analysis/semi_explicit_euler_integrator.h
- systems/analysis/test/semi_explicit_euler_integrator_test.cc
Resolves #22742
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22743)
> Avoid accessing nullptr in SemiExplicitEulerIntegrator constructor

- bindings/pydrake/multibody/parsing_py.cc
- multibody/parsing/package_map.cc
- multibody/parsing/package_map.h
- multibody/parsing/test/package_map_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22731)
> [multibody] Add PackageMap overloads for filesystem and pathlib

- planning/dev/BUILD.bazel
- planning/dev/test/voxel_self_filter_test.cc
- tools/workspace/common_robotics_utilities_internal/repository.bzl
- tools/workspace/voxelized_geometry_tools_internal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22484)
> [workspace,planning/dev] Update CRU & VGT, re-enable TSAN on voxel self-filter

- examples/multibody/deformable/BUILD.bazel
- examples/multibody/deformable/bubble_gripper.cc
- geometry/render_vtk/internal_render_engine_vtk.cc
- geometry/render_vtk/internal_render_engine_vtk.h
- geometry/render_vtk/test/internal_render_engine_vtk_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22740)
> [deformable] Support RenderEngineVtk

- systems/analysis/bogacki_shampine3_integrator.cc
- systems/analysis/bogacki_shampine3_integrator.h
- systems/analysis/dense_output.cc
- systems/analysis/dense_output.h
- systems/analysis/explicit_euler_integrator.cc
- systems/analysis/explicit_euler_integrator.h
- systems/analysis/implicit_euler_integrator.cc
- systems/analysis/implicit_euler_integrator.h
- systems/analysis/implicit_integrator.cc
- systems/analysis/implicit_integrator.h
- systems/analysis/integrator_base.cc
- systems/analysis/integrator_base.h
- systems/analysis/radau_integrator.cc
- systems/analysis/radau_integrator.h
- systems/analysis/runge_kutta2_integrator.cc
- systems/analysis/runge_kutta2_integrator.h
- systems/analysis/runge_kutta3_integrator.cc
- systems/analysis/runge_kutta3_integrator.h
- systems/analysis/runge_kutta5_integrator.cc
- systems/analysis/runge_kutta5_integrator.h
- systems/analysis/scalar_dense_output.cc
- systems/analysis/scalar_dense_output.h
- systems/analysis/semi_explicit_euler_integrator.cc
- systems/analysis/semi_explicit_euler_integrator.h
- systems/analysis/stepwise_dense_output.cc
- systems/analysis/stepwise_dense_output.h
- systems/analysis/velocity_implicit_euler_integrator.cc
- systems/analysis/velocity_implicit_euler_integrator.h
Towards #22015
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22756)
> Remove inline destructor in /systems/analysis folder

- tools/workspace/poisson_disk_sampling_internal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22759)
> [workspace] Adjust to renamed upstream and checksum

- multibody/contact_solvers/sap/sap_pd_controller_constraint.cc
- multibody/plant/test/sap_driver_pd_controller_constraints_test.cc
See also [slack discussion](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1713885535352109).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22753)
> [sap] Remove bogus assertion on Kp > 0

- systems/controllers/BUILD.bazel
- systems/controllers/dynamic_programming.h
- systems/controllers/inverse_dynamics_controller.cc
- systems/controllers/inverse_dynamics_controller.h
- systems/controllers/joint_stiffness_controller.cc
- systems/controllers/joint_stiffness_controller.h
- systems/controllers/linear_quadratic_regulator.cc
- systems/controllers/pid_controlled_system.cc
- systems/controllers/pid_controlled_system.h
- systems/controllers/state_feedback_controller_interface.h
- systems/controllers/test/dynamic_programming_test.cc
- systems/controllers/test/linear_quadratic_regulator_test.cc
- systems/controllers/test/pid_controlled_system_test.cc
- systems/controllers/test/setpoint_test.cc
- systems/controllers/test_utilities/BUILD.bazel
- systems/controllers/test_utilities/compute_torque.h
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22768)
> [controllers] Enable clang-format-lint

- multibody/mpm/BUILD.bazel
- multibody/mpm/particle_sorter.h
- multibody/mpm/sparse_grid.h
- multibody/mpm/test/particle_sorter_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22719)
> [mpm] Add grid-particle iterate function

- planning/trajectory_optimization/BUILD.bazel
- planning/trajectory_optimization/kinematic_trajectory_optimization.cc
- planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
- solvers/test_utilities/BUILD.bazel
- solvers/test_utilities/check_gradient_sparsity_pattern.cc
- solvers/test_utilities/check_gradient_sparsity_pattern.h
As discussed in #22602
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22763)
> Set gradient sparsity pattern in KinTrajOpt AddVelocityConstraint

- doc/_pages/from_binary.md
The version number appears twice in the URLs, they were only updated once.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22784)
> [webpage] Binary links were incomplete

- multibody/mpm/BUILD.bazel
- multibody/mpm/grid_data.h
- multibody/mpm/mock_sparse_grid.cc
- multibody/mpm/mock_sparse_grid.h
- multibody/mpm/sparse_grid.h
- multibody/mpm/test/particle_sorter_test.cc
- multibody/mpm/test/sparse_grid_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22780)
> [mpm] Add MockSparseGrid

- multibody/mpm/test/sparse_grid_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22794)
> [hotfix] Fix test-time SpGrid out-of-bound issue

- systems/controllers/BUILD.bazel
- systems/controllers/finite_horizon_linear_quadratic_regulator.cc
- systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
Resolves #22761
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22762)
>  Avoid rejecting system with floating abstract input port in FiniteHorizonLinearQuadraticRegulator

- bindings/pydrake/systems/BUILD.bazel
- bindings/pydrake/systems/sensors_py.cc
- bindings/pydrake/systems/sensors_py_camera_config.cc
- bindings/pydrake/systems/test/sensors_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22811)
> [py sensors] ApplyCameraConfig overloaded on LcmInterfaceSystem

- bindings/pydrake/planning/planning_py_trajectory_optimization.cc
- bindings/pydrake/planning/test/trajectory_optimization_test.py
- bindings/pydrake/solvers/solvers_py_evaluators.cc
- bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
- bindings/pydrake/solvers/test/evaluators_test.py
- bindings/pydrake/solvers/test/mathematicalprogram_test.py
Closes #20131.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22795)
> [pydrake] Fix costs and constraints memory hazards

- LICENSE.TXT
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22837)
> [doc] Bump copyright year to 2025

- perception/BUILD.bazel
- perception/depth_image_to_point_cloud.cc
- perception/point_cloud.cc
- perception/point_cloud.h
- perception/point_cloud_flags.cc
- perception/point_cloud_flags.h
- perception/point_cloud_to_lcm.cc
- perception/test/depth_image_to_point_cloud_test.cc
- perception/test/point_cloud_test.cc
- perception/test/point_cloud_to_lcm_test.cc
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22829)
> [perception] Enable clang-format-lint

- tools/jupyter/jupyter_py.bzl
- tutorials/BUILD.bazel
Towards #22589.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22841)
> [tutorials] Disable hydroelastic_contact_basics test

- bindings/pydrake/pydrake_doxygen.h
* stop claiming to use the RL fork
* discuss ref_cycle
* fix some typos
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22833)
> [pydrake] Update the technical note

- multibody/parsing/detail_sdf_parser.cc
- multibody/parsing/detail_urdf_parser.cc
- multibody/parsing/test/detail_sdf_parser_test.cc
- multibody/parsing/test/detail_urdf_parser_test.cc
Closes: #22196.
Merge is blocked until #22839 is merged and this patch is rebased.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22840)
> [parsing] Fix parsing of erroneous curvilinear joint input

- planning/trajectory_optimization/kinematic_trajectory_optimization.cc
- planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Towards #22602
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22800)
> Add sparsity pattern when KinematicTrajectoryOptimization imposes bounds on acceleration and jerk.

- manipulation/util/named_positions_functions.cc
- manipulation/util/test/named_positions_functions_test.cc
- multibody/tree/BUILD.bazel
- multibody/tree/joint.cc
- multibody/tree/test/quaternion_floating_joint_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22850)
> [multibody] Improve set_default_positions() error message

- geometry/proximity/BUILD.bazel
- geometry/proximity/inflate_mesh.cc
- geometry/proximity/test/inflate_mesh_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22860)
> [geometry] Don't hard-code ClarabelSolver

- bindings/pydrake/systems/BUILD.bazel
- bindings/pydrake/systems/estimators_py.cc
- bindings/pydrake/systems/test/estimators_test.py
- systems/estimators/BUILD.bazel
- systems/estimators/luenberger_observer.cc
- systems/estimators/luenberger_observer.h
- systems/estimators/test/luenberger_observer_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22851)
> Support scalar conversion for LuenbergerObserver

- tools/workspace/drake_models/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22876)
> [workspace] Upgrade drake_models to latest version

- lcmtypes/lcmt_iiwa_status.lcm
- lcmtypes/lcmt_jaco_status.lcm
- lcmtypes/lcmt_panda_status.lcm
- manipulation/README.md
- manipulation/kuka_iiwa/build_iiwa_control.cc
- manipulation/kuka_iiwa/build_iiwa_control.h
Important when considering commanded, measured, and external torques / forces
Resolves #13374
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21077)
> [manipulation] Add coarse notes for torque conventions

- bindings/pydrake/common/text_logging_pybind.cc
- common/hwy_dynamic_impl.h
- common/overloaded.h
- examples/pendulum/pendulum_parameters_derivatives.cc
- tools/workspace/styleguide/repository.bzl
This incorporates changes to cpplint (https://github.com/RobotLocomotion/styleguide/pull/56). There are no docs (style guide) changes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22878)
> [workspace] Upgrade styleguide to latest commit

- geometry/proximity/test/deformable_field_intersection_test.cc
- geometry/query_results/deformable_contact.cc
- geometry/query_results/deformable_contact.h
- geometry/query_results/test/deformable_contact_test.cc
- multibody/contact_solvers/sap/partial_permutation.cc
- multibody/contact_solvers/sap/partial_permutation.h
- multibody/contact_solvers/sap/test/partial_permutation_test.cc
- multibody/plant/deformable_driver.cc
- multibody/plant/deformable_driver.h
- multibody/plant/test/deformable_driver_contact_kinematics_test.cc
- multibody/plant/test/deformable_driver_contact_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22872)
> Add VertexPartialPermutation

- bindings/pydrake/geometry/geometry_py_scene_graph.cc
- bindings/pydrake/geometry/test/scene_graph_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22879)
> [pydrake] Add some missing SceneGraph/Inspector bindings

- planning/iris/BUILD.bazel
- planning/iris/iris_zo.cc
- planning/iris/iris_zo.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22881)
> fix a bug where prefered solvers were not being used in IrizZo

- bindings/pydrake/systems/framework_py_semantics.cc
- bindings/pydrake/systems/test/general_test.py
- bindings/pydrake/systems/test/test_util_py.cc
Resolves #22880
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22884)
> [pydrake] Fix DiagramBuilder AddSystem return value policy

- MODULE.bazel
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22888)
> [workspace] Upgrade toolchains_llvm to latest release 1.4.0

- doc/_pages/release_playbook.md
- tools/release_engineering/download_release_candidate.py
- tools/release_engineering/relnotes.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22892)
> [tools] Update release tooling post-1.40.0

- doc/_pages/installation.md
- doc/_pages/release_playbook.md
- doc/_release-notes/end_of_support.md
- setup/mac/source_distribution/Brewfile-developer
- tools/release_engineering/download_release_candidate.py
- tools/wheel/wheel_builder/macos.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22893)
> [doc] Drop support for macOS for Python 3.11 wheels

- bindings/pydrake/manipulation/manipulation_py_schunk_wsg.cc
- bindings/pydrake/manipulation/test/schunk_wsg_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22900)
> Add pydrake binding for SchunkWsgTrajectoryGenerator

- CMakeLists.txt
Amends #22538.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22901)
> [build] Use our bazelversion pin in CMake builds also

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
- multibody/plant/deformable_model.cc
- multibody/plant/deformable_model.h
- multibody/plant/test/deformable_model_test.cc
Also remove some dead code in MultibodyPlant bindings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22911)
> Add position getter and setters for deformables

- geometry/BUILD.bazel
Attempt at #22869.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22909)
> Add retries for possibly flaky `MeshcatTest` on macOS

- planning/trajectory_optimization/kinematic_trajectory_optimization.cc
- planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Resolves #22602
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22912)
> Set sparsity pattern for KinematicTrajectoryOptimization effort bounds.

- math/rigid_transform.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22922)
> [hotfix] Fix doxygen

- geometry/render_vtk/BUILD.bazel
Closes #19424, if this works.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22924)
> [render_vtk] Re-enable tests on macOS

- tools/workspace/common_robotics_utilities_internal/repository.bzl
- tools/workspace/voxelized_geometry_tools_internal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22933)
> [workspace] Bump CRU and VGT with voxel access check fixes

- solvers/ipopt_solver.cc
- solvers/test/ipopt_solver_test.cc
Resolves #22926
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22927)
> [solvers] IpoptSolver accepts integers for floating-point options

- bindings/pydrake/multibody/parsing_py.cc
- bindings/pydrake/multibody/test/parsing_test.py
- multibody/parsing/process_model_directives.cc
- multibody/parsing/process_model_directives.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22936)
> [py parsing] Accept pathlib.Path for paths

- systems/estimators/test_utilities/BUILD.bazel
- systems/estimators/test_utilities/stochastic_linear_system.cc
- systems/estimators/test_utilities/stochastic_linear_system.h
- systems/estimators/test_utilities/sum_matrix_columns_system.cc
- systems/estimators/test_utilities/sum_matrix_columns_system.h
- systems/estimators/test_utilities/test/stochastic_linear_system_test.cc
- systems/estimators/test_utilities/test/sum_matrix_columns_system_test.cc
Towards #22907
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22908)
> [systems] Add testing utilities for estimators

- multibody/plant/test/multibody_plant_test.cc
PR #22949 (now allowing reversed weld, revolute, and prismatic mobilizers) fixed long-standing issue #17429. The even-older issue #9939 (bad error message, somewhat related) is also resolved (sometime earlier).
This PR adds unit tests to prove that those two issues are resolved, and closes them.
Closes #9939
Closes #17429
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22955)
> [multibody] Add tests to show issues 9939 & 17429 are closed

- multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.cc
- multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h
- multibody/fem/dirichlet_boundary_condition.cc
- multibody/fem/dirichlet_boundary_condition.h
- multibody/fem/fem_model.h
- multibody/fem/test/dirichlet_boundary_condition_test.cc
- multibody/plant/deformable_model.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22946)
> [fem] Support multiple BCs

- tools/workspace/ipopt_internal/patches/upstream/atomic.patch
- tools/workspace/ipopt_internal/repository.bzl
Hotfix for #22937.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22957)
> [solvers] Fix data races in IpoptSolver

- geometry/geometry_state.cc
- geometry/proximity/deformable_contact_geometries.cc
- geometry/proximity/deformable_contact_geometries.h
- geometry/proximity/deformable_contact_internal.cc
- geometry/proximity/deformable_contact_internal.h
- geometry/proximity/deformable_mesh_intersection.cc
- geometry/proximity/deformable_mesh_intersection.h
- geometry/proximity/test/deformable_contact_geometries_test.cc
- geometry/proximity/test/deformable_contact_internal_test.cc
- geometry/proximity/test/deformable_mesh_intersection_test.cc
- geometry/proximity/volume_to_surface_mesh.cc
- geometry/proximity/volume_to_surface_mesh.h
- geometry/proximity_engine.cc
- geometry/proximity_engine.h
- geometry/query_results/deformable_contact.cc
- geometry/query_results/deformable_contact.h
- geometry/query_results/test/deformable_contact_test.cc
- geometry/test/proximity_engine_test.cc
- multibody/plant/deformable_driver.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22952)
> Remove inverted elements from contact

- bindings/pydrake/manipulation/BUILD.bazel
- bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc
- bindings/pydrake/manipulation/test/kuka_iiwa_test.py
- manipulation/kuka_iiwa/BUILD.bazel
- manipulation/kuka_iiwa/build_iiwa_control.cc
- manipulation/kuka_iiwa/build_iiwa_control.h
- manipulation/kuka_iiwa/iiwa_constants.cc
- manipulation/kuka_iiwa/iiwa_constants.h
- manipulation/kuka_iiwa/iiwa_driver.h
- manipulation/kuka_iiwa/iiwa_driver_functions.cc
- manipulation/kuka_iiwa/sim_iiwa_driver.cc
- manipulation/kuka_iiwa/sim_iiwa_driver.h
- manipulation/kuka_iiwa/test/build_iiwa_control_test.cc
- manipulation/kuka_iiwa/test/iiwa7_wsg_renamed_weld_frames.dmd.yaml
- manipulation/kuka_iiwa/test/iiwa_driver_functions_test.cc
- manipulation/kuka_iiwa/test/sim_iiwa_driver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22916)
> [manipulation] Add more IiwaDriver config options

- bindings/pydrake/common/BUILD.bazel
- bindings/pydrake/common/test/yaml_typed_test.py
- bindings/pydrake/common/yaml.py
~(Marked "do not merge" until we reach 2025-05-01.)~
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22940)
> [py common] Remove deprecated yaml features 2025-05

- tools/workspace/common_robotics_utilities_internal/package.BUILD.bazel
- tools/workspace/common_robotics_utilities_internal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22971)
> [workspace] Bump CRU with continuous joint math fixes

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
- multibody/fem/BUILD.bazel
- multibody/fem/fem_model.cc
- multibody/fem/fem_model.h
- multibody/fem/fem_model_impl.h
- multibody/fem/test/fem_model_test.cc
- multibody/plant/BUILD.bazel
- multibody/plant/deformable_model.cc
- multibody/plant/deformable_model.h
- multibody/plant/test/deformable_model_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22962)
> [fem] Parallelize element computation

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
- examples/multibody/deformable/bubble_gripper.cc
- examples/multibody/deformable/deformable_torus.cc
- examples/multibody/deformable/models/bubbles.sdf
- examples/multibody/deformable/models/deformable_teddy.sdf
- examples/multibody/deformable/models/deformable_torus.sdf
- geometry/render/render_engine.cc
- geometry/render/render_engine.h
- geometry/render/test/render_engine_test.cc
- geometry/render_vtk/internal_render_engine_vtk.h
- geometry/test/proximity_engine_test.cc
- multibody/parsing/BUILD.bazel
- multibody/parsing/detail_sdf_geometry.cc
- multibody/parsing/detail_sdf_geometry.h
- multibody/parsing/detail_sdf_parser.cc
- multibody/parsing/parsing_doxygen.h
- multibody/parsing/test/detail_dmd_parser_test.cc
- multibody/parsing/test/detail_sdf_parser_test.cc
- multibody/parsing/test/single_tet.vtk
- multibody/plant/deformable_model.cc
- multibody/plant/deformable_model.h
- multibody/plant/test/deformable_model_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22914)
> Deformable parsing

- solvers/BUILD.bazel
- solvers/projected_gradient_descent_solver.cc
- solvers/projected_gradient_descent_solver.h
- solvers/test/csdp_solver_test.cc
- solvers/test/projected_gradient_descent_solver_test.cc
Closes #22070.
+@hongkai-dai for feature review. I doubt I got everything right on the first try, but hopefully this is a pretty good starting point.
cc @shrutigarg914 if you have any comments or suggestions as well.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22947)
> Implement a General Projected Gradient Descent Solver Interface

- tools/wheel/README.rst
- tools/wheel/image/provision-build.sh
- tools/wheel/macos/build-wheel.sh
- tools/wheel/macos/provision-test-python.sh
- tools/wheel/wheel_builder/common.py
- tools/wheel/wheel_builder/macos.py
Follows up on #22931.  Towards #22848.
+@Aiden2244 for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22979)
> Use unique directory for macOS wheel tests

- tools/dynamic_analysis/valgrind.supp
Reverts #14933.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22988)
> [tools] Remove ClpSolver memcheck suppressions

- manipulation/kuka_iiwa/BUILD.bazel
- manipulation/kuka_iiwa/sim_iiwa_driver.cc
- manipulation/kuka_iiwa/test/sim_iiwa_driver_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22976)
> [manipulation] Improve IiwaDriver wiring

- bindings/pydrake/solvers/BUILD.bazel
- bindings/pydrake/solvers/solvers_py.cc
- bindings/pydrake/solvers/solvers_py.h
- bindings/pydrake/solvers/solvers_py_projected_gradient_descent.cc
- bindings/pydrake/solvers/test/projected_gradient_descent_solver_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22986)
> Python bindings for ProjectedGradientDescentSolver.

- multibody/contact_solvers/BUILD.bazel
- multibody/contact_solvers/block_sparse_lower_triangular_or_symmetric_matrix.h
- multibody/contact_solvers/eigen_block_3x3_sparse_symmetric_matrix.cc
- multibody/contact_solvers/eigen_block_3x3_sparse_symmetric_matrix.h
- multibody/contact_solvers/test/block_sparse_lower_triangular_or_symmetric_matrix_test.cc
- multibody/contact_solvers/test/eigen_block_3x3_sparse_symmetric_matrix_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22989)
> Add EigenBlock3x3SparseSymmetricMatrix

- multibody/contact_solvers/minimum_degree_ordering.cc
- multibody/contact_solvers/minimum_degree_ordering.h
- multibody/contact_solvers/test/minimum_degree_ordering_test.cc
Also improve a few helpers used in computing the MD/AMD to be more memory conscious. When measure on the deformable torus example, these changes bring about 50% speed improvement on the elimination ordering routine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22992)
> Support Approximate Minimum Degree (AMD) ordering

- multibody/parsing/detail_sdf_parser.cc
- multibody/parsing/test/detail_sdf_parser_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23003)
> [deformable] Parse NeoHookean model

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23007)
> [pydrake] Add python binding for DeformableModel::GetBodyIds

- planning/BUILD.bazel
- planning/joint_limits.cc
- planning/joint_limits.h
- planning/test/joint_limits_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23000)
> Move joint limits

- bindings/pydrake/geometry/geometry_py_scene_graph.cc
- bindings/pydrake/geometry/test/scene_graph_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23002)
> [pydrake] Add binding for GeometryConfigurationVector.

- bindings/pydrake/planning/BUILD.bazel
- bindings/pydrake/planning/planning_py.cc
- bindings/pydrake/planning/planning_py.h
- bindings/pydrake/planning/planning_py_joint_limits.cc
- bindings/pydrake/planning/test/joint_limits_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23008)
> [pydrake] Add bindings for drake::planning::JointLimits

- doc/_release-notes/v1.41.0.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23021)
> [doc] Fix typos in release notes

- doc/_pages/release_playbook.md
The old "disable CI" commit no longer works. Propose a new one.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23022)
> [doc] Update the release playbook

- systems/analysis/simulator_config.h
- systems/analysis/simulator_config_functions.cc
- systems/analysis/simulator_config_functions.h
- systems/analysis/simulator_gflags.cc
- systems/analysis/test/simulator_config_functions_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23045)
> Add start_time to SimulatorConfig.

- bindings/pydrake/planning/planning_py.cc
- bindings/pydrake/planning/planning_py_joint_limits.cc
- bindings/pydrake/planning/test/joint_limits_test.py
- planning/BUILD.bazel
- planning/joint_limits.cc
- planning/joint_limits.h
- planning/test/joint_limits_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23047)
> [planning] Add JointLimits active DoF selecting constructor

- multibody/tree/joint.h
- multibody/tree/spatial_inertia.h
- systems/analysis/simulator.cc
- systems/analysis/simulator.h
- systems/analysis/test/simulator_test.cc
- systems/estimators/kalman_filter.cc
- systems/estimators/kalman_filter.h
- systems/estimators/test/kalman_filter_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23040)
> Remove deprecated code 2025-06

- tools/workspace/openusd_internal/defs.bzl
- tools/workspace/openusd_internal/lock/files.bzl
- tools/workspace/openusd_internal/package.BUILD.bazel
- tools/workspace/openusd_internal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23065)
> [workspace] Upgrade openusd_internal to latest release v25.05.01

- bindings/pydrake/planning/planning_py_dof_mask.cc
- bindings/pydrake/planning/test/dof_mask_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23069)
> [pydrake] add binding for DofMask operator[]

- geometry/geometry_state.cc
- geometry/geometry_state.h
- geometry/proximity_engine.cc
- geometry/proximity_engine.h
- geometry/query_object.cc
- geometry/query_object.h
- geometry/test/geometry_state_test.cc
- geometry/test/proximity_engine_test.cc
- geometry/test/query_object_test.cc
Closes #23046
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23048)
> Add point-to-specific-geometry distance query

- doc/_pages/from_binary.md
- doc/_release-notes/v1.42.0.md
- tools/skylark/cc.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23085)
> [doc] Add release notes v1.42.0

- tutorials/configuring_rendering_lighting.ipynb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23095)
> Fix a typo in the lighting tutorial

- doc/_pages/from_source.md
Follow-up to #22923
Towards #19734
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23099)
> [doc] Fix release source URL

- bindings/pydrake/planning/BUILD.bazel
- bindings/pydrake/planning/planning_py.cc
- bindings/pydrake/planning/planning_py.h
- bindings/pydrake/planning/planning_py_iris_np2.cc
- bindings/pydrake/planning/test/iris_test.py
Also requires moving some of the code in the python test cases around, to try and avoid too much code reuse. It's probably possible to reduce it even further, but all we're doing here is checking the bindings work.
+@wernerpe for feature review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23096)
> Implement Python Bindings for IrisNp2

- planning/iris/iris_zo.cc
This PR parallelizes calling the parameterization function if possible, and adds parallelization to checking for redundant particles.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23097)
> Further Use Parallelization within IrisZo.

- bindings/pydrake/multibody/plant_py.cc
- bindings/pydrake/multibody/test/plant_test.py
- bindings/pydrake/multibody/tree_py.cc
- multibody/plant/deformable_model.cc
- multibody/plant/deformable_model.h
- multibody/plant/test/deformable_model_test.cc
- multibody/tree/deformable_body.cc
- multibody/tree/deformable_body.h
- multibody/tree/test/deformable_body_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23136)
> Add setter and getter for deformable velocities

- bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
- bindings/pydrake/solvers/test/mathematicalprogram_test.py
- solvers/mathematical_program.cc
- solvers/mathematical_program.h
- solvers/test/mathematical_program_test.cc
Closes #23149.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23157)
> Overload of MathematicalProgram::AddLinearEqualityConstraint for vector of formulas.

- doc/_pages/issues.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23155)
> [doc] Update issue management: component leads

- MODULE.bazel
- tools/workspace/platforms/repository.bzl
- tools/workspace/rules_cc/repository.bzl
- tools/workspace/rules_java/repository.bzl
Upgrade bazel_features to version 1.30.0.
Upgrade platforms to version 0.0.11.
Upgrade rules_cc to version 0.1.1.
Upgrade rules_java to version 8.12.0.
Upgrade zlib to version 1.3.1.bcr.5.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23166)
> [workspace] Upgrade bazel externals in preparation for bazel 8.3.1

- doc/_pages/jenkins.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23167)
> [doc] Fix links to pull request jobs for external examples

- multibody/inverse_kinematics/BUILD.bazel
- multibody/inverse_kinematics/differential_inverse_kinematics_controller.cc
- multibody/inverse_kinematics/differential_inverse_kinematics_controller.h
- multibody/inverse_kinematics/differential_inverse_kinematics_system.cc
- multibody/inverse_kinematics/differential_inverse_kinematics_system.h
- multibody/inverse_kinematics/test/differential_inverse_kinematics_controller_test.cc
- multibody/inverse_kinematics/test/differential_inverse_kinematics_system_test.cc
This adds framework systems for a differential inverse kinematics system and controller, ported over from anzu.
Co-author: Aditya Bhat <aditya.bhat@tri.global>
Co-author: Jeremy  Nimmer <jeremy.nimmer@tri.global>
Co-author: Rick Poyner <rick.poyner@tri.global>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23175)
> Add DiffIk(System & Controller)

- bindings/pydrake/multibody/BUILD.bazel
- bindings/pydrake/multibody/inverse_kinematics_py_differential.cc
- bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23178)
> Add python bindings for DifferentialIK framework systems

- doc/_pages/installation.md
- tools/bazel.rc
- tools/lcm_gen/__init__.py
- tools/lcm_gen/test/goal/lima.hpp
- tools/lcm_gen/test/goal/mike.hpp
- tools/lcm_gen/test/goal/november.hpp
- tools/ubuntu-jammy.bazelrc
- tools/ubuntu-noble.bazelrc
- tools/workspace/vtk_internal/patches/upstream/common_datamodel_vtkdatasetattributes_iterator.patch
- tools/workspace/vtk_internal/patches/upstream/rendering_core_vtkcomposite_exception.patch
- tools/workspace/vtk_internal/repository.bzl
Closes #23168.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23177)
> [tools] Default to C++23 on macOS

- bindings/pydrake/planning/BUILD.bazel
- bindings/pydrake/planning/planning_py_robot_diagram.cc
- bindings/pydrake/planning/test/robot_diagram_test.py
- planning/robot_diagram.cc
- planning/robot_diagram.h
- planning/robot_diagram_builder.cc
- planning/robot_diagram_builder.h
Closes: #23161
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23171)
> [pydrake] Fix a RobotDiagramBuilder memory leak

- doc/_pages/buildcop.md
The old link wasn't valid. This new link goes to an existing page.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23208)
> Replace sample link with valid link

- .jenkins/Jenkinsfile-continuous
- .jenkins/Jenkinsfile-nightly
* Remove the sanity check for 'master', as `BRANCH_NAME` is only available for multibranch projects, and `GIT_BRANCH` is not available until after checkout.
* Remove `pollSCM` from continuous triggering, as this is handled via webhooks.
Towards #22826.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23215)
> [Jenkins] Fix errors from production deployment

- doc/_pages/jenkins.md
Jenkins 2.516.1 redesigned the header and navigation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23227)
> [doc] Update Jenkins sign in instructions

- bindings/pydrake/solvers/solvers_py_nlopt.cc
- bindings/pydrake/solvers/test/nlopt_solver_test.py
- solvers/nlopt_solver.cc
- solvers/nlopt_solver.h
- solvers/nlopt_solver_common.cc
- solvers/test/nlopt_solver_test.cc
cc @lunatic006
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23234)
> Can specify max time for NLopt.

- tools/release_engineering/dev/README.md
Fix broken link found while completing #23201.
Re-order validation steps to make the S3 checks consecutive.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23202)
> [tools] Minor updates to release documentation

- bindings/pydrake/test/trajectories_test.py
- bindings/pydrake/trajectories_py.cc
- common/trajectories/BUILD.bazel
- common/trajectories/bezier_curve.h
- common/trajectories/bspline_trajectory.h
- common/trajectories/composite_trajectory.h
- common/trajectories/discrete_time_trajectory.h
- common/trajectories/path_parameterized_trajectory.h
- common/trajectories/piecewise_constant_curvature_trajectory.h
- common/trajectories/piecewise_polynomial.h
- common/trajectories/test/piecewise_trajectory_test.cc
- common/trajectories/test/trajectory_test.cc
- common/trajectories/trajectory.cc
- common/trajectories/trajectory.h
See also #23224.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23223)
> [trajectories] Remove deprecated code 2025-08

- bindings/pydrake/systems/BUILD.bazel
- bindings/pydrake/systems/all.py
- bindings/pydrake/systems/primitives_py.cc
- bindings/pydrake/systems/test/primitives_test.py
- systems/analysis/discrete_time_approximation.cc
- systems/primitives/linear_system.cc
- systems/primitives/linear_system.h
- systems/primitives/test/linear_system_test.cc
See also #23223.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23224)
> [systems] Remove deprecated code 2025-08

- doc/_pages/python_bindings.md
- doc/_pages/troubleshooting.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23212)
> [pydrake] Document the need to customize garbage collection

- bindings/pydrake/systems/BUILD.bazel
- bindings/pydrake/systems/sensors_py_accelerometer.cc
- bindings/pydrake/systems/sensors_py_gyroscope.cc
- bindings/pydrake/systems/test/sensors_test.py
Closes #23263.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23264)
> [pydrake] Fix lint that snuck in while CI was down

- .jenkins/Jenkinsfile-production
- .jenkins/utils/utils.groovy
Towards #22826.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23270)
> [Jenkins] Fix pushes to nightly_release for production builds

- .jenkins/utils/utils.groovy
Towards #22826.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23271)
> [Jenkins] Use Docker credentials for production jobs only

- common/symbolic/expression/test/formula_test.cc
- common/test_utilities/drake_py_unittest_main.py
- examples/multibody/cylinder_with_multicontact/cylinder_run_dynamics.cc
- multibody/contact_solvers/sap/test/sap_friction_cone_constraint_test.cc
- multibody/contact_solvers/sap/test/sap_weld_constraint_test.cc
- multibody/parsing/test/detail_urdf_parser_test.cc
- multibody/plant/test/sap_driver_pd_controller_constraints_test.cc
- multibody/tree/test/multibody_forces_test.cc
- systems/optimization/test/system_constraint_adapter_test.cc
- systems/sensors/test/sim_rgbd_sensor_test.cc
- tools/dynamic_analysis/kcov.sh
- tools/dynamic_analysis/kcoverage.py
This patch is contingent on abandoning kcov support on Jammy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23211)
> [kcov] Abandon kcov hacks

- bindings/pydrake/systems/framework_py_systems.cc
- bindings/pydrake/systems/test/general_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23277)
> [pydrake] Add binding for Diagram.AreConnected

- setup/ubuntu/source_distribution/install_bazelisk.sh
- third_party/com_github_bazelbuild_bazelisk/bazelisk.py
- tools/workspace/bazelisk/repository.bzl
- tools/workspace/bazelisk/test/lint_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23281)
> [workspace] Upgrade bazelisk to latest release v1.27.0

- bindings/pydrake/planning/planning_py_iris_np2.cc
- bindings/pydrake/planning/test/iris_test.py
- planning/iris/BUILD.bazel
- planning/iris/iris_np2.cc
- planning/iris/iris_np2.h
- planning/iris/test/iris_np2_test.cc
- planning/iris/test/iris_zo_test.cc
Coauthored with @rhjiang. Holding off on review for a bit while we make sure we're happy with everything.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23247)
> Implement the ray sampling strategy for IrisNP2.

- tools/release_engineering/dev/push_release.py
The GitHub API endpoint that `github3` uses to fetch the source archive (downloaded and reuploaded with checksums to both GitHub and S3) ends up with `RobotLocomotion-drake-<commit hash>` as the root folder inside the tarball instead of `drake-<version>`. The latter mirrors the download link provided on the release, so it's what this script should use.
Use `urllib` to retrieve it because `github3` does not provide a way of accessing the endpoint needed.
Closes #23304.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23309)
> [tools] Retrieve GitHub source archive manually

- systems/estimators/BUILD.bazel
- systems/optimization/BUILD.bazel
- systems/optimization/test/system_constraint_adapter_test.cc
- systems/optimization/test/system_constraint_wrapper_test.cc
- systems/rendering/BUILD.bazel
- systems/rendering/test/multibody_position_to_geometry_pose_test.cc
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23314)
> [systems] Opt-in to clang-format-lint

- multibody/BUILD.bazel
- multibody/hydroelastics/BUILD.bazel
- multibody/hydroelastics/hydroelastic_engine.h
- multibody/plant/test_utilities/BUILD.bazel
- multibody/rational/BUILD.bazel
- multibody/rational/rational_forward_kinematics.cc
- multibody/test_utilities/BUILD.bazel
- multibody/test_utilities/add_fixed_objects_to_plant.h
- multibody/test_utilities/floating_body_plant.cc
- multibody/test_utilities/floating_body_plant.h
- multibody/test_utilities/spatial_derivative.h
- multibody/test_utilities/spatial_kinematics.h
- multibody/triangle_quadrature/BUILD.bazel
- multibody/triangle_quadrature/gaussian_triangle_quadrature_rule.h
- multibody/triangle_quadrature/test/triangle_quadrature_test.cc
- multibody/triangle_quadrature/triangle_quadrature.h
- multibody/triangle_quadrature/triangle_quadrature_rule.h
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23321)
> [multibody] Opt-in to clang-format-lint

- common/schema/BUILD.bazel
- common/schema/rotation.cc
- common/schema/stochastic.cc
- common/schema/stochastic.h
- common/schema/test/rotation_test.cc
- common/schema/test/stochastic_test.cc
- common/schema/test/transform_test.cc
- common/schema/transform.cc
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23315)
> [schema] Opt-in to clang-format-lint

- manipulation/kinova_jaco/BUILD.bazel
- manipulation/kinova_jaco/jaco_command_receiver.cc
- manipulation/kinova_jaco/jaco_command_receiver.h
- manipulation/kinova_jaco/jaco_command_sender.cc
- manipulation/kinova_jaco/jaco_status_receiver.cc
- manipulation/kinova_jaco/jaco_status_receiver.h
- manipulation/kinova_jaco/jaco_status_sender.cc
- manipulation/kinova_jaco/test/jaco_command_receiver_test.cc
- manipulation/kinova_jaco/test/jaco_command_sender_test.cc
- manipulation/kinova_jaco/test/jaco_status_receiver_test.cc
- manipulation/kinova_jaco/test/jaco_status_sender_test.cc
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23310)
> [kinova_jaco] Opt-in to clang-format-lint

- multibody/math/BUILD.bazel
- multibody/math/spatial_acceleration.h
- multibody/math/spatial_force.h
- multibody/math/spatial_momentum.h
- multibody/math/spatial_vector.h
- multibody/math/spatial_velocity.h
- multibody/math/test/spatial_algebra_test.cc
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23323)
> [multibody/math] Opt-in to clang-format-lint

- systems/framework/test_utilities/BUILD.bazel
- systems/framework/test_utilities/initialization_test_system.h
- systems/framework/test_utilities/my_vector.h
- systems/framework/test_utilities/scalar_conversion.h
- systems/framework/test_utilities/test/my_vector_test.cc
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23312)
> [framework/test_utilites] Opt-in to clang-format-lint

- multibody/benchmarking/BUILD.bazel
- multibody/benchmarking/acrobot.cc
- multibody/benchmarking/homecart_global_ik.cc
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23331)
> [multibody/benchmarking] Opt-in to clang-format-lint

- geometry/optimization/dev/BUILD.bazel
- geometry/optimization/dev/cspace_free_path.h
- geometry/optimization/dev/test/c_iris_path_test_utilities.h
- geometry/optimization/dev/test/cspace_free_path_with_mosek_test.cc
Towards #4843.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23311)
> [optimization/dev] Opt-in to clang-format-lint

- tools/workspace/ipopt_internal/package.BUILD.bazel
- tools/workspace/ipopt_internal/repository.bzl
Towards #23365 
Local upgrade succeeds but CI fails. Relevant error message includes the following:
```
[12:12:26 PM]  ERROR: /media/ephemeral0/ubuntu/workspace/el-experimental-release_PR-23373/_bazel_ubuntu/0ec80af814994c9ee2147aa241705b51/external/+internal_repositories+ipopt_internal/BUILD.bazel:346:16: Compiling external/+internal_repositories+ipopt_internal/drake_src/Interfaces/IpIpoptApplication.cpp failed: (Exit 1): clang failed: error executing CppCompile command (from target @@+internal_repositories+ipopt_internal//:_build) /usr/lib/llvm-15/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object -fcolor-diagnostics -fno-omit-frame-pointer -g0 ... (remaining 100 arguments skipped)
[12:12:26 PM] …
```
> [workspace] Upgrade ipopt_internal to latest release 3.14.19

- doc/_pages/buildcop.md
See https://drakedevelopers.slack.com/archives/C270MN28G/p1757007330399009.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23385)
> [doc] Rename #buildcop Slack to #ci

- doc/_pages/issues.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23388)
> [doc] New component owner for geometry/general

- MODULE.bazel
- doc/styleguide/BUILD.bazel
- doc/styleguide/build.py
- tools/workspace/default.bzl
- tools/workspace/styleguide/package-deprecated.BUILD.bazel
- tools/workspace/styleguide/repository.bzl
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23393)
> [workspace] Deprecate the styleguide external

- .jenkins/Jenkinsfile-experimental
- .jenkins/Jenkinsfile-external-examples
- .jenkins/Jenkinsfile-production
- .jenkins/Jenkinsfile-staging
- .jenkins/templates/Jenkinsfile-experimental.in
- .jenkins/templates/Jenkinsfile-production.in
- .jenkins/templates/Jenkinsfile-staging.in
- .jenkins/utils/utils.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23387)
> [Jenkins] Clean up workspace before builds

- MODULE.bazel
This makes it easier (at least for me) to survey our dependencies as we renovate the build system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23430)
> [workspace] Group internal_repositories by category, with comments

- tools/workspace/new_release.py
Amends #23248, closes #23376.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23448)
> [tools] Mark xmlrunner_py 'internal' for new_release

- planning/iris/test/iris_np2_test.cc
Reverts RobotLocomotion/drake#23447
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23454)
> Revert "Speed up IrisNp2 test cases."

- planning/iris/BUILD.bazel
Closes #23445 (assuming this actually works).
Alternative to #23447
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23449)
> Disable memcheck for the IrisNp2 tests

- .gitattributes
Towards #23431.  Landing this first will make that review much easier to read.
+assignee:@rpoyner-tri for both reviews, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23451)
> Reviewable ignores diffs of generated_docstrings

- tools/workspace/msgpack_internal/patches/upstream/type_traits_remove_volatile.patch
- tools/workspace/msgpack_internal/repository.bzl
Towards #23437.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23453)
> [workspace] Patch msgpack_internal for Xcode 26.0

- tools/bazel.rc
For consistency with the other external flags.
Amends #22432.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23466)
> [tools] Fix spdlog flag level in bazelrc

- .github/ISSUE_TEMPLATE/BUG.yml
- CMakeLists.txt
- doc/_pages/buildcop.md
- doc/_pages/code_review_checklist.md
- doc/_pages/from_source.md
- doc/_pages/getting_help.md
- doc/_pages/installation.md
- doc/_pages/jenkins.md
- doc/_pages/release_playbook.md
Towards #23440.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23461)
> [doc] Drop support for macOS Sonoma

- BUILD.bazel
- CMakeLists.txt
- common/BUILD.bazel
- doc/_pages/from_source.md
- third_party/BUILD.bazel
- third_party/com_github_bazelbuild_rules_cc/cc_static_libary.bzl
- third_party/com_github_bazelbuild_rules_cc/find_cc_toolchain.bzl
- third_party/com_github_bazelbuild_rules_cc/whole_archive.bzl
- tools/flags/BUILD.bazel
- tools/install/install.bzl
- tools/install/libdrake/BUILD.bazel
- tools/install/libdrake/build_components.bzl
- tools/install/libdrake/drake-config.cmake.in
- tools/install/libdrake/test/find_package_drake_install_test.py
Towards #16882.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23298)
> [build] Optionally install a static `libdrake.a`

- tools/dynamic_analysis/tsan.supp
Amends #23474.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23480)
> [workspace] Amend tsan.supp for new drake_vendor_lcm symbol prefix

- bindings/generated_docstrings/planning_iris.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23505)
> Amend docstrings for "Fix IrisZo bug ..."

- tools/workspace/dm_control_internal/repository.bzl
- tools/workspace/gymnasium_py_internal/repository.bzl
- tools/workspace/mujoco_menagerie_internal/repository.bzl
- tools/workspace/mypy_internal/repository.bzl
- tools/workspace/ros_xacro_internal/repository.bzl
- tools/workspace/spral_internal/repository.bzl
Towards #23484 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23498)
> Upgrade externals October 2025

- doc/_pages/jenkins.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23532)
> [doc] Add note on wait time for job requests

- bindings/pydrake/geometry/test/visualizers_test.py
- geometry/test/meshcat_test.cc
- setup/ubuntu/source_distribution/packages-jammy-test-only.txt
- setup/ubuntu/source_distribution/packages-noble-test-only.txt
- tools/dynamic_analysis/drd.sh
- tools/dynamic_analysis/helgrind.sh
- tools/dynamic_analysis/valgrind.sh
Using a non-sandbox program for tests is non-hermetic.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23512)
> [setup] Remove curl from test prereqs

- examples/acrobot/BUILD.bazel
- examples/acrobot/acrobot_io.py
- examples/acrobot/metrics.py
- examples/acrobot/optimizer_demo.py
- examples/acrobot/spong_sim.py
- examples/acrobot/test/acrobot_io_test.py
- examples/acrobot/test/metrics_test.py
- examples/acrobot/test/spong_sim_lib_py_test.py
- examples/acrobot/test/spong_sim_main_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23536)
> [ruff] Format examples/acrobot

- multibody/parsing/BUILD.bazel
- multibody/parsing/package_downloader.py
- multibody/parsing/test/package_downloader_stress_test.py
- multibody/parsing/test/package_downloader_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23546)
> [ruff] Format multibody/parsing

- tools/install/BUILD.bazel
- tools/install/install_test.py
- tools/install/install_test_helper.py
- tools/install/installer.py
- tools/install/otool.py
- tools/install/test/install_meta_test.py
- tools/install/test/install_test_helper_test.py
- tools/install/test/installer_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23552)
> [ruff] Format tools/install

- tools/lint/BUILD.bazel
- tools/lint/buildifier.py
- tools/lint/clang_format.py
- tools/lint/clang_format_lint.py
- tools/lint/drakelint.py
- tools/lint/install_lint_reporter.py
- tools/lint/library_lint_reporter.py
- tools/lint/test/buildifier_test.py
- tools/lint/test/util_test.py
- tools/lint/util.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23555)
> [ruff] Format tools/lint

- tools/workspace/mkdoc_internal/BUILD.bazel
- tools/workspace/mkdoc_internal/libclang_setup.py
- tools/workspace/mkdoc_internal/mkdoc.py
- tools/workspace/mkdoc_internal/mkdoc_comment.py
- tools/workspace/mkdoc_internal/test/mkdoc_comment_test.py
- tools/workspace/mkdoc_internal/test/sample_header_documentation_py_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23562)
> [ruff] Format tools/workspace/mkdoc_internal

- multibody/plant/images/BUILD.bazel
- multibody/plant/images/ideal_stiction.py
- multibody/plant/images/stiction.py
- multibody/plant/images/test/scripts_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23547)
> [ruff] Format multibody/plant/images

- tools/clion/BUILD.bazel
- tools/clion/test/bazel_wrapper_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23550)
> [ruff] Format tools/clion

- examples/hardware_sim/BUILD.bazel
- examples/hardware_sim/hardware_sim.py
- examples/hardware_sim/test/hardware_sim_test_common.py
- examples/hardware_sim/test/robot_commander_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23538)
> [ruff] Format examples/hardware_sim

- geometry/proximity/BUILD.bazel
- geometry/proximity/test/refine_mesh_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23543)
> [ruff] Format geometry/proximity

- doc/BUILD.bazel
- doc/build.py
- doc/defs.py
- doc/doxygen_cxx/BUILD.bazel
- doc/doxygen_cxx/build.py
- doc/doxygen_cxx/system_doxygen.py
- doc/doxygen_cxx/test/system_doxygen_test.py
- doc/pages.py
- doc/pydrake/BUILD.bazel
- doc/pydrake/build.py
- doc/pydrake/conf.py
- doc/pydrake/pydrake_sphinx_extension.py
- doc/styleguide/BUILD.bazel
- doc/styleguide/build.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23535)
> [ruff] Format doc

- examples/hydroelastic/python_ball_paddle/BUILD.bazel
- examples/hydroelastic/python_ball_paddle/contact_sim_demo.py
- examples/hydroelastic/python_nonconvex_mesh/BUILD.bazel
- examples/hydroelastic/python_nonconvex_mesh/drop_pepper.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23539)
> [ruff] Format examples/hydroelastic

- geometry/BUILD.bazel
- geometry/test/meshcat_websocket_client.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23542)
> [ruff] Format geometry

- examples/van_der_pol/BUILD.bazel
- examples/van_der_pol/plot_limit_cycle.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23541)
> [ruff] Format examples/van_der_pol

- geometry/render_gltf_client/BUILD.bazel
- geometry/render_gltf_client/test/acceptance_test.py
- geometry/render_gltf_client/test/integration_test.py
- geometry/render_gltf_client/test/server_demo.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23544)
> [ruff] Format geometry/render_gltf_client

- tools/workspace/BUILD.bazel
- tools/workspace/bzlmod_sync_test.py
- tools/workspace/cmake_configure_file.py
- tools/workspace/metadata.py
- tools/workspace/mirror_to_s3.py
- tools/workspace/new_release.py
- tools/workspace/vendor_cxx.py
- tools/workspace/vendor_cxx_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23561)
> [ruff] Format tools/workspace

- common/BUILD.bazel
- common/test/cpu_capabilities_test.py
- common/test/drake_cc_googletest_main_test.py
- common/test/find_runfiles_subprocess_test.py
- common/test/resource_tool_installed_test.py
- common/test/resource_tool_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23533)
> [ruff] Format common

- common/proto/BUILD.bazel
- common/proto/call_python_client.py
- common/proto/test/call_python_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23534)
> [ruff] Format common/proto

- tools/install/libdrake/BUILD.bazel
- tools/install/libdrake/build_components_refresh.py
- tools/install/libdrake/parse_version.py
- tools/install/libdrake/test/drake_python_dir_install_test.py
- tools/install/libdrake/test/exported_symbols_test.py
- tools/install/libdrake/test/header_dependency_test.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23553)
> [ruff] Format tools/install/libdrake

- tools/release_engineering/BUILD.bazel
- tools/release_engineering/download_release_candidate.py
- tools/release_engineering/relnotes.py
- tools/release_engineering/repack_deb.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23557)
> [ruff] Format tools/release_engineering

- tools/wheel/BUILD.bazel
- tools/wheel/macos/change_lpath.py
- tools/wheel/macos/strip_rpath.py
- tools/wheel/wheel_builder/common.py
- tools/wheel/wheel_builder/linux.py
- tools/wheel/wheel_builder/linux_types.py
- tools/wheel/wheel_builder/macos.py
- tools/wheel/wheel_builder/macos_types.py
- tools/wheel/wheel_builder/main.py
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23560)
> [ruff] Format tools/wheel
