setup/ubuntu/source_distribution/install_bazel.sh, setup/ubuntu/source_distribution/install_prereqs_user_environment.sh
Towards #13514.
You can see the [build log](https://drake-jenkins.csail.mit.edu/job/linux-arm-jammy-unprovisioned-gcc-bazel-experimental-release/17/consoleFull) for what this accomplishes.  There are build (loading) errors but that's a _good_ thing -- previously, we couldn't even run a build at all.
We need to have some Bazel installed in order to build on `arm64`.  Since Bazel doesn't provide `.deb` files for that architecture, instead we'll have Drake install a `*.deb` file for `bazelisk`, which I've compiled and uploaded to S3 for us to use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21201)
=> [setup] Install bazelisk on Ubuntu arm64

examples/quadrotor/BUILD.bazel, examples/quadrotor/quadrotor.urdf, examples/quadrotor/quadrotor_geometry.cc, examples/quadrotor/quadrotor_plant.h, examples/quadrotor/run_quadrotor_dynamics.cc, examples/quadrotor/test/quadrotor_dynamics_test.cc, tools/workspace/drake_models/repository.bzl
We'll remove the file from Drake after the next release, to provide a smoother glide path for `underactuated.csail.mit.edu` which is being taught this spring.
---
Even though this model is "deprecated", I'm not going to mark it as such in that section of the release notes.  Instead, it'll just be part of the broader "model files move" announcement.
Towards #13942.
Twin PR: https://github.com/RobotLocomotion/models/pull/55
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21238)
=> [examples] Copy quadrotor.urdf to drake_models

tools/workspace/drake_models/repository.bzl
Towards #20935.
Twin PR: https://github.com/RobotLocomotion/models/pull/58
I tested this using Meldis and `bazel run //examples/atlas:atlas_run_dynamics -- --simulator_target_realtime_rate=0.2`, comparing master to this PR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21250)
=> [examples] Switch Atlas to glTF meshes

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
The mjcf specs recently added 'autolimits' as a compiler option and then make a (minor) breaking change to the default values. https://mujoco.readthedocs.io/en/stable/changelog.html#version-3-0-0-october-18-2023
This PR updates Drake's parser to the latest standard.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21205)
=> Mujoco parser: support new 'autolimits' compiler attribute

multibody/topology/BUILD.bazel, multibody/topology/forest.h, multibody/topology/link_joint_graph.h, multibody/topology/link_joint_graph_joint.h, multibody/topology/spanning_forest.cc, multibody/topology/spanning_forest.h, multibody/topology/spanning_forest_inlines.h, multibody/topology/spanning_forest_loop_constraint.h, multibody/topology/spanning_forest_mobod.cc, multibody/topology/spanning_forest_mobod.h, multibody/topology/spanning_forest_tree.h, multibody/topology/test/spanning_forest_test.cc
This is the third installment towards #20225, following PR #21142.
git_cloc says half the added lines of code here are comments:
- A large class-doc block describes SpanningForest and what you can do with it.
- A large internal block describes the multi-stage algorithm used to create a SpanningForest from a LinkJointGraph.
- The APIs for SpanningForest sub-objects (Mobod, LoopConstraint, Tree) are fully documented.
These comments describe the full implementation (in #20225), but the code here is stubbed. I'd like to get the comments reviewed for readability, clarity, logical flaws and so on. IMO it is too much to ask to review both the long text discussion and the hairy implementation code (and those require different frames of mind), so the code will come in a follow on PR. This one …
=> [multibody] SpanningForest structure and documentation

bindings/pydrake/planning/planning_py_robot_diagram.cc, bindings/pydrake/planning/test/robot_diagram_test.py, planning/robot_diagram_builder.h, planning/test/robot_diagram_test.cc
This fixes some crashes when using models that need discrete-time-only modeling features, such as implicit PD control.
Closes #21095.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21098)
=> [planning] Match RobotDiagram default time step to MbP's default

multibody/tree/multibody_tree_system.cc, multibody/tree/multibody_tree_system.h, systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/leaf_system.cc, systems/framework/leaf_system.h, systems/framework/system.cc, systems/framework/system.h, systems/framework/test/system_test.cc
`System::SetDefaultContext()` calls `SetDefaultState()` and `SetDefaultParameters()` by passing a `const Context&` and a mutable `State` or `Parameters`. However, that mutable output parameter was actually a view into the `const Context`.
This *undocumented* relationship between the two parameters is dangerous. The relationship should either be documented or
ended. Here we opt to document (supported by a suitable regression test).
Furthermore, `SetDefaultContext()` doesn't document the order in which state and parameters are set. In this case, we document that the default parameter values have been set prior to setting the default state (and provide regression tests).
Related to #20948 (We'll need to evaluate kinematics while writing default state, so we need to make sure the default …
=> Clarify some contracts relating to System::SetDefaultContext()

planning/iris/iris_from_clique_cover.cc, planning/iris/test/iris_from_clique_cover_test.cc
The function IrisInConfigurationSpaceFromCliqueCover had ill defined behavior when a clique with a degenerate MinimumVolumeCircumscribedEllipsoid is encountered. The corresponding IrisWorker would get stuck attempting to build the set from the degenerate clique and repeatedly triggering the same runtime error without discarding the clique after one try. The fix is to pop the clique from the queue when the circumscribed ellipsoid fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21237)
=> Fixes bug in IrisInConfigurationSpaceFromCliqueCover

multibody/tree/BUILD.bazel, multibody/tree/multibody_tree_topology.cc, multibody/tree/multibody_tree_topology.h
Per discussion in #20711, definitions of non-inlinable functions (per the styleguide) in `multibody_tree_topology.h` are moved to a separate cc file.
Changes here depend on the resolution of #20711 and should not be merged until the pre-requisite PR is merged. Expect a rebase onto master as soon as #20711 is merged. However all of the changes are trivial moving of code or redefinitions using a default `==` operator, thus review can proceed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21158)
=> [multibody] Refactor multibody_tree_topology.h

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/primitives/BUILD.bazel, systems/primitives/discrete_time_integrator.cc, systems/primitives/discrete_time_integrator.h, systems/primitives/integrator.h, systems/primitives/test/discrete_time_integrator_test.cc
Note: unfortunately, there is already an
multibody::fem::internal::DiscreteTimeIntegrator. My thinking is that, while not ideal, this is ok because that class in internal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21222)
=> Implements DiscreteTimeIntegrator primitive

common/symbolic/expression/test/formula_test.cc
Add a dummy namespace to perturb the ELF header
Fixes CI failure https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-jammy-gcc-bazel-nightly-coverage/184/
See #17978
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21280)
=> Workaround test error in coverage build (kcov 339)

bindings/pydrake/visualization/_meldis.py, geometry/drake_visualizer.cc, geometry/test/drake_visualizer_test.cc
DrakeVisualizer now takes responsibility for accounting for the *role* in dispatching Mesh-based meshes.
Indirectly, we also tweak a message in meldis to indicate which visualization "channel" is ignoring a load message. It has been mildly confusing to see multiple instances of "Ignoring load message" appear while the scene nevertheless updates. The addition of the channel name helps clarify the messages.
To test:
1. Launch meldis
2. `bazel run //tools:model_visualizer_private -- package://drake/examples/scene_graph/cuboctahedron_with_hole.obj`
3. Make sure you open the browser to the meldis URL.
Run in master, what is shown when "Collision Geometry" is the textured cuboctahedron. In this branch, it is replaced with the red convex hull.
- - - …
=> Meldis shows convex hull for Mesh shapes with the proximity role

geometry/geometry_state.cc, geometry/render/render_material.cc, geometry/render/render_material.h, geometry/render/render_mesh.cc, geometry/render/render_mesh.h, geometry/render/test/render_material_test.cc, geometry/render/test/render_mesh_test.cc, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_vtk/internal_render_engine_vtk.cc
@SeanCurtis-TRI I thought a bit more about allowing the render mesh to defer render material to its consumer. I still think it's cleaner to make the render material optional. 
The only time render mesh wants to defer the material to the consumer is when no valid material is specified either through the properties or through parsing the mesh. In that case, we can simply leave the material empty and the consumer doesn't need any heuristic data to create a material because the material we need at that point is just a simple material with a uniform default diffuse color.
Here is a sketch of the idea. I can clean this up into a proper PR if you agree with the strategy.
- - - …
=> Make RenderMaterial optional in RenderMesh

tools/workspace/common_robotics_utilities/package.BUILD.bazel, tools/workspace/conex_internal/vendor.bzl, tools/workspace/csdp_internal/package.BUILD.bazel, tools/workspace/qhull_internal/package.BUILD.bazel
- Drake code:
- antiquated use of `move` instead of `std::move` restored to standard.
- Initialization of scalar corrected (no need for braces).
- Externals
- qhull_internal c-code has unused but initialized variables.
- common_robotics_utilities has an unnecessary lambda capture
- csdp has a host of C-functions definitions without prototypes
(mac uniquely barks about that)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21292)
=> Silence various compiler warnings in CI logs

geometry/BUILD.bazel, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/test/geometry_state_test.cc
This is progress toward simpler hydroelastic configuration. More patches will follow to complete the integration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21272)
=> [geometry] Introduce internal::ApplyProximityDefaults

.bazeliskrc, doc/_pages/bazel.md, doc/_pages/developers.md, setup/ubuntu/install_prereqs.sh, setup/ubuntu/source_distribution/install_bazelisk.sh, setup/ubuntu/source_distribution/install_prereqs.sh, setup/ubuntu/source_distribution/install_prereqs_user_environment.sh
This removes Drake's forcing of a specific version of Bazel being installed system-wide.  This is easier for users, and will make Bazel upgrades easier in CI (no more need for Unprovisioned jobs).
(Note that on macOS we've already been using bazelisk by default for several years; this is an Ubuntu-only change.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21321)
=> [setup] Install bazelisk instead of bazel

tools/workspace/csdp_internal/package.BUILD.bazel
The recently added flag `-Wno-deprecated-non-prototype` causes console spam with Ubuntu's Clang:
```
INFO: From Compiling lib/op_at.c:
warning: unknown warning option '-Wno-deprecated-non-prototype'; did you mean '-Wno-deprecated-coroutine'? [-Wunknown-warning-option]
1 warning generated.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21334)
=> [workspace] Simplify CSDP warning suppressions

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/test/graph_of_convex_sets_test.cc
PR #21053 to upgrade clarabel fell over on some numerical problems in the PhiConstraint unit test.  I've captured that failure and reported it in https://github.com/oxfordcontrol/Clarabel.rs/issues/96 .
In examining the problem, I found a number of small errors in the existing test. Resolving those errors allows clarabel 7.1 to pass the tests without any upstream changes required.
The changes in the PhiConstraint test are:
- QuadraticCost was being used incorrectly (we forgot the factor of 2). It was also documented as being the L2 norm, instead of the L2 norm squared.
- Added a diagram to the doc and minor code cleanup.
In GCS, I made two changes, both of which have no functional impact:
- The bounding box constraint with lb==ub was replaced with a linear equality constraint (which …
=> FixUp GCS PhiConstraint test

tools/lint/buildifier.py, tools/lint/test/buildifier_test.py
When we wrote this back in the days of Bazel 0.12 or whatever, I don't think `BUILD_WORKING_DIRECTORY` existed (or at least, we didn't know about it).
Towards #20731 -- the deleted test fails under bzlmod.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21329)
=> [lint] Allow running buildifier via `bazel run`

setup/ubuntu/binary_distribution/packages-noble.txt, tools/skylark/drake_cc.bzl, tools/workspace/nlohmann_internal/package.BUILD.bazel
Towards #21335.  (I locally developed & tested this in an Ubuntu 24.04 docker container. We don't have CI images ready for testing yet.)
Fix Python version in setup scripts; since the last time we prepped for Noble, the default Python switched from 3.11 to 3.12.  (FYI https://packages.ubuntu.com/noble/libpython3-dev.)
Add several GCC 13 error suppressions.  We'll need to circle back and deal with these later (#21337), but for now it's better to silence them so we can focus on any other build problems.
Override nlohmann/json spaceship probing. It's broken on GCC 13.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21338)
=> [tools] Prepare for Noble

tools/macos-arch-i386.bazelrc, tools/wheel/image/dependencies/projects.cmake, tools/wheel/test/tests/sanity-test.py
Until Homebrew offers standalone MUMPS (https://github.com/RobotLocomotion/drake/issues/20429), it's too much build hassle to enable IPOPT on macOS x86_64.  (With no Bazel caching, the iteration time is too slow.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21346)
=> [wheel] Disable IPOPT on macOS x86_64

bindings/pydrake/visualization/_meldis.py, examples/multibody/deformable/bubble_gripper.cc, geometry/drake_visualizer.cc, geometry/drake_visualizer.h, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/internal_geometry.cc, geometry/internal_geometry.h, geometry/query_object.cc, geometry/query_object.h, geometry/scene_graph.cc, geometry/scene_graph_inspector.cc, geometry/scene_graph_inspector.h, geometry/test/drake_visualizer_test.cc, geometry/test/geometry_state_test.cc, geometry/test/internal_geometry_test.cc, geometry/test/query_object_test.cc, geometry/test/scene_graph_inspector_test.cc, multibody/plant/deformable_model.cc
To allow for that, implement
QueryObject::GetIllustrationMeshConfigurationsInWorld() that computes the current vertex positions in world for driven illustration meshes and SceneGraphInspector::GetDrivenIllustrationRenderMeshes() that computes the render mesh representation of the illustration driven meshes.
This PR also includes an update to the bubble gripper example demonstrating that we can now configure the diffuse color of deformable geometries for visualization.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21298)
=> DrakeVisualizer uses driven mesh data

bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/_model_visualizer.py, bindings/pydrake/visualization/_triad.py, bindings/pydrake/visualization/test/model_visualizer_test.py, bindings/pydrake/visualization/test/triad_test.py, geometry/BUILD.bazel, geometry/meshcat_internal.cc, geometry/meshcat_internal.h, geometry/meshcat_visualizer.cc, geometry/test/meshcat_internal_test.cc, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_visualizer_test.cc
Rather than visualizing the frames registered with scene graph, it visualizes all frames with a fixed offset w.r.t. the corresponding body.
In support of that, some further changes have been made:
- MeshcatVisualizer now makes use of geometry *name* and geometry id to produce paths.
- AddFrameTriadIllustration() takes a new "brightness" parameters to use brightness as a means to distinguish different kinds of frames.
Closes #19983.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21318)
=> ModelVisualizer draw all MultibodyPlant frames when requested

bindings/pydrake/geometry/geometry_py_common.cc, bindings/pydrake/geometry/geometry_py_visualizers.cc, geometry/meshcat.cc, geometry/meshcat.h, geometry/proximity_properties.cc, geometry/proximity_properties.h
Towards #21279.
The style guide [requires that `optional<POD>` be passed by-value](https://drake.mit.edu/styleguide/cppguide.html#Pass_By_Value_Primitives) so that the ABI can use registers to pass it instead of the stack.
While we're here, also fix the mismatch argument names between header and cc files and add TODOs for apparently missing checks.
+@DamrongGuoy for feature review, please.
+@sammy-tri for platform review per schedule, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21356)
=> [geometry] Fix pass-by-value style for POD optionals

bindings/pydrake/geometry/geometry_py_visualizers.cc, geometry/BUILD.bazel, geometry/meshcat.cc, geometry/meshcat_animation.cc, geometry/meshcat_animation.h
Towards #21279.  (The conversion calls in Meshcat using `std::string()` wrappers are already awkward in the current code, and that awkwardness will explode as we start to add animation support to even more functions in Meshcat.)
Also move a function body from h to cc as required by the styleguide.
+@sammy-tri for both reviews per schedule, please.
\CC @DamrongGuoy FYI
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21358)
=> [geometry] Port MeshcatAnimation to string_view

doc/_pages/release_playbook.md
Staging builds recently switched from being Bazel-driven to CMake-driven. Update the release playbook accordingly.
Toward #18145.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21359)
=> Update release playbook for recent changes

bindings/pydrake/geometry/geometry_py_visualizers.cc, geometry/meshcat.cc, geometry/meshcat.h, geometry/meshcat_animation.h, geometry/test/meshcat_test.cc, geometry/test/meshcat_visualizer_test.cc
Having an occasionally-null recording is a segfault beacon. Either we need to add more nullptr checks and nice error messages, or just do the obvious thing and have a non-null default.
Closes #21352, and has some chance of making #21279 simpler.
+@DamrongGuoy for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21360)
=> [geometry] Meshcat has a default recording

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
A user can now decide to add a constraint to the relaxed, rounded or both problems.
I also cleaned up two minor logging issues:
- When the pre-processing step finds that a source/target is not connected, it returns the vertex name in addition to the id.
- The if statement in the logging step to display if we are rounding or not was not quite correct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21179)
=> [gcs] Enable adding constraints to the relaxed, rounded or both problems

math/rotation_matrix.h
The implementation inside Eigen uses expression templates for some elementwise operations, which ends up tickling a bug in Clang 15's codegen back-end which leaves R(2, 0) as uninitialized memory.  (See [demo on godbolt](https://godbolt.org/).)
Writing the math using elementary flops keeps the codegen happy.
Note that the codegen bug only occurs in a Release build (`-O2`) with assertions enabled.  Drake's binary releases are not affected (assertions not enabled, and we don't use Clang for release binaries anyway).  Switching to `-O1` or `-O0` or leaving assertions disabled both will avoid the codegen bug.
Follow-up from #21339.
Closes #21363.
- - - …
=> [math] Implement AngleAxis -> RotationMatrix from scratch

tools/release_engineering/debian/changelog.in, tools/release_engineering/repack_deb.py
After recent changes, `VERSION.TXT` should always contain a meaningful and correct version number. Accordingly, we a) should stop assuming it is an unprefixed timestamp, and b) no longer need the ability to override `VERSION.TXT`, which allows for some modest simplification.
For now, the option is retained but ignored, because we will first need to change CI to stop passing it, after which it can be removed entirely.
Toward #18145.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21364)
=> Deprecate --version in repack_deb.py

tools/release_engineering/repack_deb.py
Remove --version argument from repack_deb. It was previously deprecated in #21364, and CI was subsequently modified (RobotLocomotion/drake-ci#284) to stop passing it, therefore it is now dead code and can be safely dropped.
Relates to #18145, and since this is the last known bit of clean-up from the changes for that, closes  #18145.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21378)
=> Remove repack_deb --version

tools/workspace/boost_internal/repository.bzl
Towards #21372 
The semi-automated upgrade script failed as described in #21388, so these updates were made by hand.
Note that the archive names now have a `-cmake` suffix
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21389)
=> [workspace] Upgrade boost_internal from boost-1.84.0 to boost-1.85.0

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, common/test_utilities/symbolic_test_util.h, solvers/BUILD.bazel, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
Remove a decision variable from the MathematicalProgram. The decision variable cannot be bound with any cost/constraint.
Towards #20842 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21392)
=> Add MathematicalProgram::RemoveDecisionVariable.

bindings/pydrake/symbolic/test/symbolic_test.py
On the Ubuntu 24.04 version of numpy, `np.tan(1.0)` differs by 1 ulp compared to Ubuntu 22.04 and earlier.
Towards #21335.
Note that the Noble CI job here still shows 2 failures, but notably the failure on _this_ test case is no longer there (as compared to [the baseline](https://drake-jenkins.csail.mit.edu/view/Linux%20Noble%20Unprovisioned/job/linux-noble-unprovisioned-gcc-bazel-experimental-release/7/)).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21395)
=> [py symbolic] Loosen test of np.tan

bindings/pydrake/math/math_py_monolith.cc, bindings/pydrake/math/test/math_test.py, math/rigid_transform.h, math/rotation_matrix.h, math/test/rigid_transform_test.cc, math/test/rotation_matrix_test.cc
One might initially worry that `MakeUnchecked` is too dangerous of a tool to add to public API.  However, in practice nearly all users run a Release build of Drake, which means that the everyday constructors being used today are not checking for valid rotation matrices, either.  This isn't any more dangerous than the status quo.
Closes #21374.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21393)
=> [math] Add RigidTransform (etc) factory methods without checks

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, examples/manipulation_station/manipulation_station.cc, multibody/inverse_kinematics/test/inverse_kinematics_test.cc, multibody/plant/multibody_plant.h, multibody/plant/test/floating_body_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/tree/ball_rpy_joint.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/quaternion_floating_joint.h, multibody/tree/quaternion_floating_mobilizer.cc, multibody/tree/quaternion_floating_mobilizer.h, multibody/tree/rpy_ball_mobilizer.cc, multibody/tree/rpy_ball_mobilizer.h, multibody/tree/rpy_floating_joint.h, multibody/tree/rpy_floating_mobilizer.cc, multibody/tree/rpy_floating_mobilizer.h, multibody/tree/test/linear_bushing_roll_pitch_yaw_test.cc, multibody/tree/test/quaternion_floating_joint_test.cc, multibody/tree/test/quaternion_floating_mobilizer_test.cc, multibody/tree/test/rpy_ball_mobilizer_test.cc, multibody/tree/test/rpy_floating_joint_test.cc, multibody/tree/test/rpy_floating_mobilizer_test.cc, multibody/tree/test/universal_mobilizer_test.cc
Better consistency between QuaternionFloatingJoint and RpyFloatingJointClasses.
Deprecate the following in the QuaternionFloatingJoint class in favor of new names.
get_position() - > get_translation().
set_position() -> SetTranslation().
get_default_position() -> get_default_translation().
set_default_position() -> set_default_translation().
SetFromRotationMatrix()  ->  SetOrientation().
set_quaternion()  ->  SetQuaternion().
get_pose() -> GetPose().
set_pose() -> SetPose().
set_random_position_distribution()  ->  set_random_translation_distribution().
Deprecate the following in the RpyFloatingJoint class in favor of new names.
set_translation() -> SetTranslation().
set_orientation() -> SetOrientation().
MutibodyPlant::SetFreeBodyRandomPositionDistribution() -> …
=> Deprecate QuaternionFloatingJoint::get_position(), set_position() for get_translation(), set_translation(), etc.

solvers/constraint.cc, solvers/test/constraint_test.cc
When deciding the Hessian type of Quadratic Constraint, we use Eigen's LDLT method. If this computation fails, the Hessian type was being mis-identified as PositiveSemidefinite. We now correctly fall back to kIndefinite in these circumstances.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21411)
=> Fall Back To Indefinite Hessian when LDLT fails.

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, examples/multibody/deformable/bubble_gripper.cc, examples/multibody/deformable/deformable_torus.cc, multibody/plant/BUILD.bazel, multibody/plant/constraint_specs.h, multibody/plant/deformable_driver.cc, multibody/plant/deformable_model.cc, multibody/plant/deformable_model.h, multibody/plant/dummy_physical_model.cc, multibody/plant/dummy_physical_model.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/physical_model.cc, multibody/plant/physical_model.h, multibody/plant/test/deformable_boundary_condition_test.cc, multibody/plant/test/deformable_collision_filter_test.cc, multibody/plant/test/deformable_contact_results_test.cc, multibody/plant/test/deformable_driver_contact_kinematics_test.cc, multibody/plant/test/deformable_driver_contact_test.cc, multibody/plant/test/deformable_driver_test.cc, multibody/plant/test/deformable_fixed_constraint_test.cc, multibody/plant/test/deformable_integration_test.cc, multibody/plant/test/deformable_model_test.cc, multibody/plant/test/discrete_update_manager_test.cc, multibody/plant/test/multibody_plant_scalar_conversion_test.cc, multibody/plant/test/physical_model_test.cc
Towards #21355. Part of #21357.
Cloning to double is always allowed. Cloning to non-double scalar types is only allowed when the DeformableModel is empty.
Move the deformable configuration port accessor from DeformableModel to MultibodyPlant to help facilitate AddMultibodyPlantSceneGraph in the future. In particular, the port is allocated pre-finalize now.
Instead of offering a pointer to the owning MbP at DeclareSystemResources, PhysicalModel now takes a mutable pointer to the prefinalized owning pointer at construction and nulls the pointer at DeclareSystemResources.
Change DummyModel into DummyPhysicalModel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21409) …
=> DeformableModel allows scalar conversion

common/drake_copyable.h, common/test/drake_copyable_test.cc, doc/doxygen_cxx/Doxyfile_CXX.in, multibody/parsing/package_map.h, multibody/topology/link_joint_graph.h, multibody/topology/spanning_forest.h
Adds a macro to use when all the copy & move builtins are defined for a class and behave normally, but can't use the compiler-generated defaults. This provides uniform documentation like we get for DRAKE_DEFAULT_COPY_AND_MOVE_AND_ASSIGN.
(Per review discussion in #21349)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21419)
=> Adds DRAKE_DECLARE_COPY_AND_MOVE_AND_ASSIGN macro.

tools/bazel.rc
I convinced myself this was necessary by doing manual hero testing using a 24.04 laptop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21422)
=> [tools] Allow XAUTHORITY in tests

multibody/contact_solvers/sap/sap_solver.cc, multibody/contact_solvers/sap/sap_solver.h, multibody/contact_solvers/sap/test/sap_solver_test.cc
In preparation for the support of gradients through SAP, see #21370, this PR refactors the implementation of the solver so that common data and implementation can be used when propagating gradients.
There are no functional nor behavior changes. 
There are essentially two changes:
1. struct SolverStats is no longer nested in SapSolver but is now refactored to SapSolverStats.
2. SapSolver<T>::model_ is not longer a member. A SapModel is now created with each call to SolveWithGuess. We pass "model" as needed by argument.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21414)
=> Refactors SAP solver implementation

multibody/contact_solvers/sap/dense_supernodal_solver.cc
Hotfix for #21421:
```
[ RUN      ] DenseSuperNodalSolver.InterfaceTest
==20== Conditional jump or move depends on uninitialised value(s)
==20==    at 0x14A588: Eigen::LDLT<Eigen::Ref<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::OuterStride<-1> >, 1>& Eigen::LDLT<Eigen::Ref<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::OuterStride<-1> >, 1>::compute<Eigen::Matrix<double, -1, -1, 0, -1, -1> >(Eigen::EigenBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> > const&) (LDLT.h:517)
==20==    by 0x14A1A7: Eigen::LDLT<Eigen::Ref<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0, Eigen::OuterStride<-1> >, 1>::LDLT<Eigen::Matrix<double, -1, -1, 0, -1, -1> >(Eigen::EigenBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >&) (LDLT.h:137)
==20==    by 0x149A53: …
```
=> [sap] Avoid factoring ununitialized memory

multibody/topology/BUILD.bazel, multibody/topology/link_joint_graph.cc, multibody/topology/link_joint_graph.h, multibody/topology/link_joint_graph_defs.h, multibody/topology/link_joint_graph_inlines.h, multibody/topology/link_joint_graph_joint.h, multibody/topology/link_joint_graph_link.h, multibody/topology/spanning_forest.cc, multibody/topology/spanning_forest.h, multibody/topology/spanning_forest_mobod.h, multibody/topology/test/link_joint_graph_test.cc, multibody/topology/test/spanning_forest_test.cc
This is the fifth installment in the PR train for #20225, following #21295.
What's here:
- Straightforward loop breaking using the "one-level-at-a-time" algorithm depicted [here](https://docs.google.com/presentation/d/1oYhX36T9JP5JZJMyRzVyh3FrkvqRCQSWZpKT0VPenFs).
- Status return indicating whether the resulting forest can be used for dynamics
- Unit tests for that
- ChangeJointType() (added for testing convenience now but could be useful later)
What's not here:
- Special handling of massless bodies to avoid terminal massless bodies
- Combining LinkComposites onto a single Mobod
- Some standalone graph-walking algorithms needed by MbP
-  Modifications to MbP to use this stuff
There are still no user-visible changes here and MbP still uses the old topology.
- - - …
=> [multibody] Adds loop-breaking to MbP topology

bindings/pydrake/multibody/inverse_kinematics_py_differential.cc, bindings/pydrake/multibody/test/inverse_kinematics_differential_test.py, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/differential_inverse_kinematics.cc, multibody/inverse_kinematics/differential_inverse_kinematics.h, multibody/inverse_kinematics/test/differential_inverse_kinematics_test.cc
This is a mitigation for #18711, so that downstream code can opt-in to determinism until the underlying problem is fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21433)
=> [multibody] Allow setting DiffIK solver options

solvers/osqp_solver.cc, solvers/osqp_solver.h, solvers/test/osqp_solver_test.cc
When adaptive_rho is enabled (the default) and adaptive_rho_interval is zero (the default), OSQP will guesstimate a suitable interval using wall clock timing measurements. This leads to non-reproducible results based on changes in CPU timing. In Drake we treasure reproducibility, so we should set our own default using a fixed schedule. We'll choose adaptive_rho_interval=ADAPTIVE_RHO_FIXED, which is OSQP's default value on embedded platforms that lack access to timing measurements.
Users who wish to keep using adaptive_rho_interval=0 can customize their SolverOptions to override the default. Refer to the OSQP docs for other adaptive_rho-related options.
Closes #18711.
- - - …
=> [solvers] Put OsqpSolver in deterministic mode by default

bindings/pydrake/geometry/geometry_py_scene_graph.cc, bindings/pydrake/geometry/test/scene_graph_test.py, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, examples/simple_gripper/simple_gripper.cc, geometry/BUILD.bazel, geometry/benchmarking/BUILD.bazel, geometry/benchmarking/proximity_defaults_benchmark.cc, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/scene_graph_config.cc, geometry/scene_graph_config.h, geometry/test/scene_graph_test.cc, multibody/hydroelastics/hydroelastic_user_guide_doxygen.h, multibody/plant/multibody_plant_config_functions.cc, multibody/plant/multibody_plant_config_functions.h, multibody/plant/test/multibody_plant_config_functions_test.cc, tutorials/BUILD.bazel
This patch integrates SceneGraphConfig into scene graph, and completes the implementation of easy, no-annotation hydroelastic configuration.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21366)
=> [geometry, multibody] Integrate scene graph configuration

tools/workspace/drake_models/repository.bzl
Twin PR: https://github.com/RobotLocomotion/models/pull/67
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21442)
=> [workspace] Upgrade drake_models to latest commit (fix plate_8in.gltf)

tools/lint/test/buildifier_test.py
Unit tests should never write to cwd, rather always to TEST_TMPDIR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21451)
=> [tools] Fix buildifier_test to not scribble in runfiles

examples/acrobot/BUILD.bazel, examples/acrobot/test/optimizer_demo_smoke_test.sh, examples/allegro_hand/joint_control/BUILD.bazel, examples/allegro_hand/joint_control/test/run_twisting_mug_test.py
Hard-coding paths to runfiles is incompatible with bzlmod. We should always use `python.runfiles`, or (in the case of acrobot) just use our simple `add_test_rule` pattern.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21452)
=> [examples] Fix some smoke test path snafus

geometry/render_gl/BUILD.bazel, systems/sensors/BUILD.bazel, tools/BUILD.bazel, tools/skylark/drake_cc.bzl, tools/ubuntu-jammy.bazelrc, tools/ubuntu-noble.bazelrc
Towards #21335.
See #21420 for a description of the problem. We're temporarily disabling the tests in order to spin up CI, and will circle back later with changes to re-enable.
Making tests conditional on the platform requires some new skylark:
- The "linux only" gains an "enable condition" which can narrow further.
- Add rcfile definitions for our two linux platforms to opt-in.
- Allow setting a test timeout on a linux-only test, which requires switching our stub file from h to cc to avoid confusing the private headers helper macro with an unknown kwarg.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21455)
=> [render_gl] Disable multithreaded tests on Ubuntu 24.04

multibody/contact_solvers/sap/sap_solver.cc, multibody/contact_solvers/sap/sap_solver.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21440)
=> [sap] Use C++20 'requires' syntax for double-only functions

multibody/contact_solvers/sap/test/sap_ball_constraint_test.cc, multibody/contact_solvers/sap/test/sap_fixed_constraint_test.cc, multibody/math/spatial_acceleration.h, multibody/math/spatial_force.h, multibody/math/spatial_momentum.h, multibody/math/spatial_velocity.h, multibody/tree/articulated_body_inertia.h, multibody/tree/multibody_tree.cc, multibody/tree/rotational_inertia.h, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/unit_inertia.cc, multibody/tree/unit_inertia.h
Closes #21436, as a broader swipe at the same respelling.
---
Here's a tiny demo program that mimics the problem (see also [godbolt](https://godbolt.org/z/a7cEq91qx)):
```c++
#include <Eigen/Dense>
using Eigen::Vector3d;
using Vector6d = Eigen::Matrix<double, 6, 1>;
struct SpatialVelocity {
Vector6d V_;
const Vector3d& rotational() const {
return *reinterpret_cast<const Vector3d*>(V_.data());
}
Vector3d& rotational() {
return *reinterpret_cast<Vector3d*>(V_.data());
}
const Vector3d& translational() const {
return *reinterpret_cast<const Vector3d*>(V_.data() + 3);
}
Vector3d& translational() {
return *reinterpret_cast<Vector3d*>(V_.data() + 3);
}
SpatialVelocity& ShiftInPlace(const Vector3d& offset) {
this->translational() += this->rotational().cross(offset);
return *this;
} …
```
=> [multibody] Change "InPlace" functions to return void

bindings/pydrake/math/math_py_monolith.cc, bindings/pydrake/math/test/math_test.py, bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, bindings/pydrake/symbolic/symbolic_py_monolith.cc, bindings/pydrake/symbolic/test/symbolic_test.py, common/symbolic/BUILD.bazel, common/symbolic/decompose.cc, common/symbolic/decompose.h, common/symbolic/test/decompose_test.cc, math/matrix_util.h, math/quadratic_form.cc, math/quadratic_form.h, math/test/quadratic_form_test.cc, solvers/create_cost.cc, solvers/create_cost.h, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
In a recent underactuated pset, we found that *lots* of people wanted to pass e.g. np.linalg.norm(x1-x2) to the AddCost methods, and were stymied by a lack of support there. Asking them to instead suddenly understand how to create an L2NormCost, create the binding, and pass _that_ to (GCS's version of) AddCost was too much.
This PR adds DecomposeL2NormExpression, and uses it in prog.AddCost(expression). Consistent with the other Add*Cost methods, it also adds prog.AddL2NormCost(expression), with all of the specific tolerance arguments.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21394)
=> Add support for parsing symbolic L2 norm costs

geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/test/internal_render_engine_gl_test.cc
Multiple RenderEngineGl instances share OpenGl objects in their shared context. Historically, this has included render buffers. A recent upgrade to NVidia drivers exposed this as problematic. Now, each clone is responsible for creating its own render targets.
Resolves #21326
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21466)
=> Enforce uniqueness of render buffers between RenderEngineGl instances

multibody/plant/sap_driver.cc
We added a number of DRAKE_DEMANDs in SapDriver::AddContactConstraints() during a transition period in PR #20913. In that PR we explicitly loaded NANs to mark not yet supported configurations (in this case deformables + HuntCrossley contact constraints). Now that the feature is complete and those configurations are supported, these DEMANDs can go away.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21469)
=> Remove temporary DRAKE_DEMANDs

multibody/tree/planar_joint.h, multibody/tree/planar_mobilizer.cc, multibody/tree/planar_mobilizer.h, multibody/tree/revolute_joint.h, multibody/tree/revolute_mobilizer.cc, multibody/tree/revolute_mobilizer.h, multibody/tree/screw_joint.h, multibody/tree/screw_mobilizer.cc, multibody/tree/screw_mobilizer.h, multibody/tree/test/planar_mobilizer_test.cc, multibody/tree/test/revolute_mobilizer_test.cc, multibody/tree/test/screw_mobilizer_test.cc, multibody/tree/test/tree_from_mobilizers_test.cc
PR #21468 is a step towards resolving issue #21284.
It changes internal Multibody/tree/ mobilizer usage of set_angle() to SetAngle().
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21468)
=> In internal code, change mobilizer set_angle() to SetAngle().

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, geometry/optimization/graph_of_convex_sets.h, planning/trajectory_optimization/BUILD.bazel, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
This adds nonlinear derivative bounds to subgraphs and edges between subgraphs in GCS TrajOpt.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21459)
=> [GcsTrajOpt] Add nonlinear derivative bounds

setup/mac/binary_distribution/Brewfile, setup/mac/source_distribution/Brewfile
No need to tap 'robotlocomotion' anymore.
Switch 'cmake' to a source prereq.
Drop unused 'xz' (vestigial from VTK).
Drop unused 'yaml-cpp' (now built from source).
Drop unused 'zeromq' (vestigial from meshcat).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21454)
=> [setup] Prune some unused macOS dependencies

tools/release_engineering/repack_deb.py
Refactor repack_deb to directly read `os-release`, as Python bindings for `lsb_release` are no longer included on Noble. (Anyway, LSB is essentially abandoned since 2015, and the Python bindings were already just reading `/etc/os-release`.)
Fixes #21488.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21489)
=> Don't use lsb_release in repack_deb

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/test/sap_solver_autodiff_test.cc, multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.cc, multibody/plant/sap_driver.h, multibody/plant/test/multibody_plant_scalar_conversion_test.cc, multibody/test_utilities/BUILD.bazel, multibody/test_utilities/robot_model.cc, multibody/test_utilities/robot_model.h
Updates the multibody plant scalar conversion tests to reflect the current state of the support matrix for discrete models.
An important conclusion is that for TAMSI (and SAP), we do not support discrete updates when `T = Symbolic` at all. We (meaning I really) were expecting this to be supported when num_contacts=0, but it turns out that the proximity engine does not even allow queres on symbolic, regardelss the state of the system.
cc'ing @jwnimmer-tri. I know we talked about a Python script instead, but I already had this and it's not an extra large of lines (~150) to put together in C++ if I reuse the code from #21431
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/d …
=> Unit tests support matrix for discrete MultibodyPlant models

setup/ubuntu/binary_distribution/packages-noble.txt, tools/install/dockerhub/noble/Dockerfile, tools/workspace/gfortran/package.BUILD.bazel
Towards #21335.
This fixes the specific packaging build highlighted below.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21491)
=> [setup,tools] Fix Noble missing deps and Python version typo

geometry/BUILD.bazel, geometry/meshcat_visualizer.h, systems/analysis/BUILD.bazel, systems/analysis/realtime_rate_calculator.cc, systems/analysis/realtime_rate_calculator.h, systems/analysis/test/realtime_rate_calculator_test.cc
We anticipate adding smoothing logic (#16486), so the name will become misleading soon.  We'll rename it in this PR before modifying the logic too heavily in a future PR, so that we keep the history intact.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21474)
=> [systems] Drop "instantaneous" from realtime rate calculator

multibody/plant/slicing_and_indexing.cc, tools/skylark/drake_cc.bzl
Remove a counterproductive call to std::move. Enable (as an error) the warning that catches these.
Toward #21337.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21513)
=> Fix -Wpessimizing-move

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/spatial_inertia_test.cc
This fixes hex addresses in our docs, towards #13987.
Examples of the docs spam: https://github.com/RobotLocomotion/RobotLocomotion.github.io/commit/3545db73dacc5a8bf075352f168bf9182fc6b7b7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21515)
=> [pydrake] Add repr for SpatialInertia.Zero

tools/workspace/openusd_internal/patches/usd_sdf_flex_hidden.patch, tools/workspace/openusd_internal/repository.bzl
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21477)
=> [openusd_internal] Hide symbols from GNU flex output

doc/_pages/buildcop.md
The Linux Bazel Continuous Release job was changed from Jammy to Noble, update the buildcop cache server check documentation to reference the Noble job.
Follow-up to #21475
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21518)
=> [doc] Update Linux link for buildcop cache server check

bindings/pydrake/common/module_py.cc, bindings/pydrake/common/test/module_test.py
This fixes hex addresses in our docs, towards #13987.
Examples of the docs spam: https://github.com/RobotLocomotion/RobotLocomotion.github.io/commit/3545db73dacc5a8bf075352f168bf9182fc6b7b7
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21517)
=> [pydrake] Add repr for Parallelism

examples/manipulation_station/manipulation_station.cc, examples/manipulation_station/manipulation_station.h
Manually connecting the MbP to a SG is error-prone and not future-proof.  Our examples should not do it, since we don't want users to do it either.
Towards #20545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21531)
=> [examples] Fix bad habit in manipulation station

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
For some reason, the tolerance argument wasn't bound in the constructor.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21536)
=> Bind the tolerance argument when constructing a VPolytope from an HPolyhedron.

multibody/plant/test/multibody_plant_hydroelastic_test.cc
Per this [slack conversation](https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1717686251170419) and related to #21533.
Replaces call to `EvalHydroelasticContactForces()` (which will be made continuous plant only in #21533) in a unit test using a discrete plant. Instead the total hydro contact force acting on the body is calculated using the forces reported by `ContactResults`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21539)
=> [multibody] Use ContactResults for hydro forces in discrete plant unit test.

bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/_model_visualizer.py, bindings/pydrake/visualization/model_visualizer.py, bindings/pydrake/visualization/test/model_visualizer_test.py
Towards #19709.
This offers a way for model authors to understand the pressure field of their model (by moving it around on/in a ground plane), even if the model's native properties default to point contact.
```
bazel run //tools:model_visualizer -- \
--compliance_type=compliant \
package://drake_models/ycb/004_sugar_box.sdf \
planning/test_utilities/collision_ground_plane.sdf
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21548)
=> [py visualization] Add model visualizer option for hydro type

planning/trajectory_optimization/BUILD.bazel
Two of the SimpleEnv2D unit tests have proven consistently problematic under coverage tests. So, we'll simply omit the whole thing to save the bother.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21556)
=> Removes the GCS trajectory optimization test from kcov builds

multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_hydroelastic_test.cc
Changing this value in the middle of a simulation fails to properly invalidate the contact surface cache entries. Rather than try to fix that (which would be extremely complicated), instead we fail-fast. The contact surface representation (triangle vs polygon) must now be configured pre-Finalize.
Towards #20545.
(I'm not using deprecation here because computing wrong answers is one of the better reasons to break users, and because we will not be able to support post-Finalize changes as we work on #20545.  This function is never called from Anzu.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21559)
=> [multibody] Deny set_contact_surface_representation post-Finalize

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/test/graph_of_convex_sets_test.cc, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Fixes #21383.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21384)
=> Lower bound in GcsTrajectoryOptimization subspace constraint should be -inf.

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Resolves #21482. At minimum, this enables one to remove constraints from the plant that might have been added during parsing, without using internal methods (which are not bound in pydrake).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21483)
=> Implements MultibodyPlant::GetConstraintIds()

examples/hardware_sim/BUILD.bazel, examples/hardware_sim/example_scenarios.yaml
This is a nice example of the syntax for posing a free body, towards #19651.
(It also serves as a more useful test case for #21512.)
(Note that due to https://github.com/RobotLocomotion/drake/issues/16538#issuecomment-2019190414 you can't see the contact force arrow unless you look under the table.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21558)
=> [examples] Add bell pepper to hardware_sim

multibody/parsing/parser.h, multibody/parsing/test/parser_manual_test.cc, multibody/parsing/test/process_model_directives_test.cc
Its replacement will get an improved implementation in the near future.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21562)
=> [parsing] Deprecate parser.collision_filter_groups() API

geometry/render_gl/internal_opengl_geometry.h, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/internal_render_engine_gl.h, geometry/render_gl/internal_shader_program.cc, geometry/render_gl/internal_shader_program.h, geometry/render_gl/test/internal_opengl_geometry_test.cc, geometry/render_gl/test/internal_render_engine_gl_test.cc, geometry/render_gl/test/internal_shader_program_test.cc
Previously, RenderEngineGl would assume a great deal about the geometries and how they get posed in the world. This changes those assumptions:
- Geometry primitives are no longer assumed by RenderEngineGl::RenderAt().
- Each OpenGlGeometry records the nature of its primitives and that is used at render time.
- The vertex attributes can be organized more generally in a dat array. I.e, rather than the previous hard-coded grouping, a source could choose to present them interleaved (this can happen in future glTF parsing).
- Each OpenGlGeometry stores the interepretation of its vertex data as stored in the associated buffer object (to facilitate cloning).
- We no longer assume the OpenGlGeometry data is measured and expressed in a frame that only differs from Drake's geometry frame by an …
=> Generalize RenderEngineGl's geometries and instances

multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/tamsi_driver.cc, multibody/plant/test/joint_locking_test.cc, multibody/plant/test/multibody_plant_hydroelastic_test.cc
Towards #20545: before we can fix the discrete time dependencies, we need to be very clear about which parts are _not_ used in discrete time plants.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21533)
=> [multibody] Clean up internal plant continuous time naming

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/contact_solvers/test/multibody_sim_driver.cc, multibody/plant/deformable_driver.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/hydroelastic_traction_test.cc, multibody/plant/test/multibody_plant_test.cc
Towards https://github.com/RobotLocomotion/drake/issues/20545.
Distinguishing between property changes (only) vs configuration or contact changes is important for performance and caching. Refactor the plant to only directly touch the query object when doing a configuration-dependent query. Use the new inspector sugar when only properties are being accessed.
Note that this does not change any input ports or add any cache entries, so no changes to cache dependency tickets are required.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21563)
=> [multibody] Add MultibodyPlant::EvalSceneGraphInspector

setup/mac/binary_distribution/requirements.txt, tools/wheel/image/provision-python.sh, tools/wheel/image/setup.py
At the moment, pydrake fails during import with NumPy 2 (#21577).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21582)
=> [wheel] Pin numpy to 1.x

solvers/BUILD.bazel, solvers/semidefinite_relaxation.cc, solvers/semidefinite_relaxation_internal.cc, solvers/semidefinite_relaxation_internal.h
This is prep work for #21500, to make the code review more practical.
The first commit is *only* moving some functions from one file to another, with the minimal changes -- splitting declaration out from definition, adding namespace qualifiers instead of leaning on `using`, and fixing includes.  The second commit fixes some GSG defects in the moved code.
The two commit split is just to aid in the review.  We'll plan to squash this into master.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21585)
=> [solvers] Hoist semidefinite relaxation code from anon to internal

solvers/cost.h
Resolves #21578
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21583)
=> Use DRAKE_THROW_UNLESS for quadratic cost size check.

planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
It turns out this was helpful for debugging, even if the primary workflow doesn't use it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21505)
=> [GcsTrajOpt] Support symbolic eval of nonconvex derivative constraints

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/BUILD.bazel, multibody/parsing/collision_filter_groups.cc, multibody/parsing/collision_filter_groups.h, multibody/parsing/detail_collision_filter_group_resolver.cc, multibody/parsing/detail_collision_filter_group_resolver.h, multibody/parsing/detail_collision_filter_groups_impl.cc, multibody/parsing/detail_collision_filter_groups_impl.h, multibody/parsing/detail_composite_parse.cc, multibody/parsing/detail_composite_parse.h, multibody/parsing/detail_instanced_name.cc, multibody/parsing/detail_instanced_name.h, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/process_model_directives.cc, multibody/parsing/test/collision_filter_groups_test.cc, multibody/parsing/test/detail_collision_filter_group_resolver_test.cc, multibody/parsing/test/detail_dmd_parser_test.cc, multibody/parsing/test/detail_instanced_name_test.cc, multibody/parsing/test/detail_make_model_name_test.cc, multibody/parsing/test/detail_mesh_parser_test.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_select_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/detail_usd_parser_test.cc, multibody/parsing/test/parser_manual_test.cc, multibody/parsing/test/parser_test.cc
This patch fixes a name clash of collision filter groups when loading the same model multiple times using auto-renaming and plant.RenameModel().
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21529)
=> [parsing] Fix name clash of collision filter groups

planning/trajectory_optimization/kinematic_trajectory_optimization.h
Based on this SO post:
https://stackoverflow.com/questions/78645004/clarification-on-the-distinction-between-addpathvelocityconstraint-and-addveloci
+@xuchenhan-tri for both reviews, please
cc @cohnt
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21601)
=> Improve docstring for KinematicTrajectoryOptimization velocity constraints

bindings/pydrake/BUILD.bazel, bindings/pydrake/examples/examples_py_acrobot.cc, bindings/pydrake/examples/test/acrobot_test.py, bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/all.py, bindings/pydrake/systems/estimators_py.cc, bindings/pydrake/systems/sensors_py.cc, bindings/pydrake/systems/sensors_py.h, bindings/pydrake/systems/sensors_py_rotary_encoders.cc, bindings/pydrake/systems/test/estimators_test.py, bindings/pydrake/systems/test/sensors_test.py, systems/estimators/kalman_filter.h, systems/estimators/luenberger_observer.h, systems/primitives/pass_through.h, systems/sensors/rotary_encoders.cc, systems/sensors/rotary_encoders.h
This PR adds the missing bindings required to port the examples/acrobot/run_lqr_w_estimator.cc example to python.
(I'm slowing landing the dev branches remaining from my teaching this spring)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21610)
=> Add bindings for systems/estimators and acrobot w/ encoders example

geometry/optimization/graph_of_convex_sets.h
A few people have been confused about this. Currently and most notably, GcsTrajOpt chooses different default values than GCS, but I've stopped short of saying that in the docstring, because I would not want that detail registered in two different places where it could get stale.
+@AlexandreAmice for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21602)
=> Improve docstring for GcsOptions tribools.

doc/_pages/buildcop.md
Update the build cop instructions to remind build cops to check for instances like last week's Mac issues (https://drakedevelopers.slack.com/archives/C270MN28G/p1718890006571899). A weekly reminder has also been created in Slack on the #buildcop channel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21614)
=> [doc] Add reminder for build cops to check the build queue status

multibody/plant/BUILD.bazel, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/geometry_contact_data.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/compliant_contact_manager_tester.h, multibody/plant/test/joint_locking_test.cc, multibody/plant/test/multibody_plant_scalar_conversion_test.cc, multibody/plant/test/multibody_plant_test.cc
There is nowhere in the plant or its helpers that only ever needs a subset of the geometry contacts. Putting all of the contact geometry into a single struct is an order of magnitude simpler.
---
Towards #21597 and therefore also #20545.
Originally, I had planned on consolidating this all the way up into the SceneGraph as an output port (#21568), but this smaller first step is probably best.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21608)
=> [multibody] Consolidate MbP geometry contact caching

bindings/pydrake/multibody/plant_py.cc, geometry/proximity/polygon_surface_mesh.cc, geometry/proximity/polygon_surface_mesh.h, geometry/proximity/triangle_surface_mesh.cc, geometry/proximity/triangle_surface_mesh.h, geometry/query_results/contact_surface.cc, geometry/query_results/contact_surface.h, multibody/plant/contact_results_to_lcm.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/geometry_contact_data.h, multibody/plant/hydroelastic_contact_info.h, multibody/plant/multibody_plant.cc, multibody/plant/tamsi_driver.cc, multibody/plant/test/contact_results_to_lcm_test.cc
Towards #21597 and therefore also #20545.
The large chunks of code moved from h to cc file are unchanged.
The breaking change is that any users who were calling any accessor functions (e.g., the `F_Ac_W()` getter) with T=Expression will fail to compile now.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21618)
=> [multibody] HydroelasticContactInfo<Expression> is empty

math/BUILD.bazel, math/fast_pose_composition_functions_wrapper.cc
We are going to combine both `fast_pose_composition_functions*.cc` implementations in a single file, using highway to dispatch to a target at runtime.  That means only one the two git histories of the `*.cc` files can survive.  I think we should keep the SIMD git history in preference to the portable-C git history, so we need to move the non-wanted file out of the way in preparation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21621)
=> [math] Rename fast_pose_composition sources for git history

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, examples/manipulation_station/manipulation_station.cc, examples/multibody/acrobot/passive_simulation.cc, examples/multibody/pendulum/passive_simulation.cc, geometry/optimization/test/c_iris_test_utilities.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/frame_kinematics_test.cc, multibody/plant/test/multibody_plant_query_object_connect_test.cc, multibody/plant/test/multibody_plant_scalar_conversion_test.cc, multibody/plant/test/multibody_plant_test.cc, systems/rendering/multibody_position_to_geometry_pose.cc, visualization/inertia_visualizer.cc
The output port named foo_bar is calculated via a member function named CalcFooBarOutput, with the output argument named 'output'.
Always use member functions for output ports, not gratuitously long lambdas with actual logic hiding inside of them.
Move the documentation about a ports' semantics from the private calc functions where nobody can find it, to the Doxygen public exposition of the ports. (In most cases it was already there, so we just remove the copy-pasted information.)
Deprecate some mis-matched port names and port getter names.
---
Towards #21597 and therefore also #20545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21609)
=> [multibody] Rename MbP output calc functions for uniformity

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, examples/multibody/deformable/bubble_gripper.cc, examples/multibody/deformable/deformable_torus.cc, multibody/plant/BUILD.bazel, multibody/plant/deformable_model.cc, multibody/plant/deformable_model.h, multibody/plant/discrete_update_manager.cc, multibody/plant/dummy_physical_model.cc, multibody/plant/dummy_physical_model.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/physical_model.cc, multibody/plant/physical_model.h, multibody/plant/physical_model_collection.cc, multibody/plant/physical_model_collection.h, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/deformable_boundary_condition_test.cc, multibody/plant/test/deformable_collision_filter_test.cc, multibody/plant/test/deformable_contact_results_test.cc, multibody/plant/test/deformable_driver_contact_kinematics_test.cc, multibody/plant/test/deformable_driver_contact_test.cc, multibody/plant/test/deformable_driver_test.cc, multibody/plant/test/deformable_fixed_constraint_test.cc, multibody/plant/test/deformable_integration_test.cc, multibody/plant/test/deformable_model_test.cc, multibody/plant/test/discrete_update_manager_test.cc, multibody/plant/test/multibody_plant_scalar_conversion_test.cc, multibody/plant/test/physical_model_collection_test.cc, multibody/plant/test/physical_model_test.cc
In addition, AddMultibodyPlantSceneGraph connects the deformable related SceneGraph ports automatically.
Closes #21355 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21357)
=>  MultibodyPlant adds DeformableModel by default

geometry/render_gl/internal_render_engine_gl.cc
Hotfix for #21520.
https://drake-jenkins.csail.mit.edu/view/Production/job/linux-jammy-clang-bazel-nightly-thread-sanitizer/229/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21627)
=> [render_gl] Fix reading past end of glTF buffer

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py
Very quick PR -- just adding python bindings for a static method in GcsTrajectoryOptimization that didn't have them yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21622)
=> Add Python bindings for UnwrapToContinousTrajectory.

multibody/plant/deformable_driver.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
Towards #21623 and therefore also #20545.
The primary upside here is that changes to `discrete_update_manager.h` only rebuild a dozen files in the plant folder, rather than everything in Drake.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21625)
=> [multibody] Remove unnecessary MbP includes

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/general_test.py, systems/framework/system.h, systems/framework/test/system_test.cc
This is useful when code wants to scan all ports (and has its own, higher-layer deprecation handler logic).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21631)
=> [framework] Offer warn_deprecated=false option on port getters

doc/_pages/bazel.md, tools/skylark/drake_cc.bzl, tools/skylark/drake_py.bzl
This patch should mitigate some of the random timeouts occurring in kcov CI builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21620)
=> [tools] Skip kcov for non-small tests

common/default_scalars.h, common/drake_copyable.h
The lack of semicolons after these macros is deprecated and we plan to re-enforce this requirement in a future release (after 2024-08-01). Macros that will require trailing semicolons at call sites are:
DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS DRAKE_DEFINE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS DRAKE_DECLARE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS DRAKE_DECLARE_CLASS_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS DRAKE_DEFINE_FUNCTION_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_SCALARS DRAKE_DEFINE_FUNCTION_TEMPLATE_INSTANTIATIONS_ON_DEFAULT_NONSYMBOLIC_SCALARS
---
Amends #21603.  If this merges, I'll go back and change the notes tag on that PR to "none" instead of "breaking".
- - - …
=> Don't (yet) require semicolons on statement-like macros

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Per our discussion in the weekly GCS standup, the default tolerance for this function is a bit too tight. I've set a looser default, and added it as an argument so users can further specify depending on their needs.
+@sadraddini for feature review, please!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21629)
=> Add tolerance argument to UnwrapToContinousTrajectory.

tools/workspace/new_release.py
Resolves  #21535
Prior to these updates, the output from the `new_release` script was:
```
abseil_cpp_internal needs upgrade from ed34153e0d9cd15f9b9eb45e86b457e0a495aeea to 0ccc51f9ddbb407d579f8158d5421fbf3eea0524
crate_universe may need upgrade
gymnasium_py needs upgrade from v0.29.1 to v1.0.0a2
gz_math_internal needs upgrade from gz-math7_7.4.0 to gz-math7_7.5.0
msgpack_internal needs upgrade from cpp-6.1.1 to c-6.0.2
mypy_internal needs upgrade from v1.10.0 to v1.10.1
pycodestyle needs upgrade from 2.11.1 to 2.12.0
ros_xacro_internal needs upgrade from 2.0.10 to xacro-1.7.5
rules_python needs upgrade from 0.33.0 to 0.33.2
rust_toolchain may need upgrade
sdformat_internal needs upgrade from sdformat14_14.2.0 to sdformat14_14.4.0
Skipping prerelease 1.13.0rc3 for sympy_py_internal …
```
=> Add more tags to ignore to the new_release script

geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/scene_graph_test.cc
Use an explicit list of dependency tickets in SceneGraph to avoid a pile of useless reifications of proximity geometry. The useless work is triggered if the base class LeafSystem::GetDirectFeedthroughs() implementation falls back on its technique of making a SystemSymbolicInspector, which needs to build an Expression-typed SceneGraph context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21630)
=> [geometry] Avoid slowdown of SceneGraph::GetDirectFeedthroughs()

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/BUILD.bazel, solvers/clarabel_solver.cc, solvers/common_solver_option.cc, solvers/common_solver_option.h, solvers/solver_options.cc, solvers/solver_options.h, solvers/test/clarabel_solver_test.cc, solvers/test/solver_options_test.cc
and adds support for it to ClarabelSolver.
Our slack discussion was [here](https://drakedevelopers.slack.com/archives/C0557S260N8/p1713492966311459?thread_ts=1709046236.828909&cid=C0557S260N8).
I was encouraged to finish this because bumping to the latest Drake (which had bumped Clarabel) broke one of my simple examples in underactuated again.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21607)
=> Adds CommonSolverOption::kStandaloneReproductionFileName

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, common/symbolic/decompose.cc, common/symbolic/decompose.h, common/symbolic/test/decompose_test.cc, solvers/create_constraint.cc, solvers/create_constraint.h, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/create_constraint_test.cc, solvers/test/mathematical_program_test.cc
Now we can write, e.g.
```
prog.AddConstraint(y[0] >= np.linalg.norm(x))
```
and get a Lorentz cone constraint back out.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21612)
=> Parse Lorentz cone constraints from formula

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
- Split up inputs ports / output ports / events / physical model / etc.
- Re-order port declaration calls to match our header summary order.
- Group per-instance port indices into helper struct for compactness.
Towards https://github.com/RobotLocomotion/drake/pull/21623 and therefore also https://github.com/RobotLocomotion/drake/issues/20545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21639)
=> [multibody] Adjust MbP declaration helpers for uniformity

tools/performance/benchmark_tool.py
Contemporary AMD processors have a frequency boost feature, called "Precision Boost". Sadly, the Linux kernel driver configuration as of Ubuntu Jammy + Linux 6.5 does not expose boost control. Some user land control does appear to be promised for future kernels.
In the mean time, this patch permits benchmark experiments to run, but prints a console warning that results may be noisy.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21640)
=> [tools] Permit benchmark experiments without boost control

tools/performance/defs.bzl
Similar in spirit to #21620, motivated by [timeout last night](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/linux-jammy-gcc-bazel-nightly-coverage/268/).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21652)
=> [tools] Disable code coverage on benchmarks

geometry/geometry_state.cc
The user can't really solve the problem unless they know the name of the troublesome geometry.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21633)
=> [geometry] Add more detail to a diffuse_map warning message

multibody/parsing/BUILD.bazel, multibody/parsing/test/detail_mujoco_parser_test.cc, tools/workspace/default.bzl, tools/workspace/mujoco_menagerie_internal/BUILD.bazel, tools/workspace/mujoco_menagerie_internal/package.BUILD.bazel, tools/workspace/mujoco_menagerie_internal/repository.bzl
And use it for testing the mujoco parser.
Towards #20444 and #21648.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21649)
=> Add mujoco_menagerie as a test-only dependency

planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
If the user manually specifies the edges between regions and provides an index which is out-of-range, GcsTrajectoryOptimization segfaults. This PR adds a test that reveals the problem, and switches to indexing with `.at(...)` to prevent the segmentation fault.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21658)
=> Fix Segmentation Fault in GcsTrajectoryOptimization::AddRegions

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py, systems/framework/system.cc, systems/framework/system.h, systems/framework/test/leaf_system_test.cc
Adds `ExecuteForcedEvents()` to trigger all the forced events in a System (or Diagram) and write any modified variables back to a Context.
This is like the existing `System::ExecuteInitializationEvents()`, but for Forced triggers rather than Initialization triggers. `ExecuteForcedEvents()` sequences the events in the same way as the Simulator does: unrestricted events, then discrete events, then publish events. There is an option to suppress publish events.
Unit tests and python bindings are included.
Resolves #21659
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21664)
=> [framework] Add ExecuteForcedEvents() to System API

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
PR #21179 introduced the ability for constraints in GCS to be applied to subsets of the possible transcriptions. This PR is the follow-up which provides the same functionality when adding costs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21650)
=> [GCS] Support use_in_transcription in AddCost.

multibody/parsing/BUILD.bazel, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, tools/workspace/mujoco_menagerie_internal/package.BUILD.bazel
Resolves #21648.
This defers the call to CalcSpatialInertia until/unless it is actually needed. If inertia values are specified for the body in the xml file, then we don't call CalcSpatialInertia. This allows us to successfully parse models where CalcSpatialInertia fails on the obj, but the calculation was not needed.
Adds the Rethink Robotics Sawyer (Apache 2.0) model to the detail_mujoco_parser_test; parsing fails on this model without the fix in this PR.
+@SeanCurtis-tri for feature review, please. (Rico is platform tomorrow).  I will open a separate issue for the (seemingly very common) failures in CalcSpatialInertia from obj.
- - - …
=> [Mujoco parser] Don't call CalcSpatialInertia unless needed

multibody/plant/multibody_plant.cc, multibody/tree/joint_actuator.h, multibody/tree/mobilizer.h
This was carved out of a larger, abandoned PR (#21644). It's somewhat of a hodge-podge:
- Clarify that inertia getters only depend on Parameters.
- Clarify that some mobilizer functions only depend on a subset of the entire Context.
- Clean up MbP using statements.
The purpose of the first two changes is that me as a developer working on MbP could not easily reason through the code.  By better documenting our assumptions in API contracts, it lets us more quickly understand what each piece of MbP/MbT/MbTS is doing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21660)
=> [multibody] Clarify some docs, and other cleanups

bindings/pydrake/multibody/plant_py.cc, multibody/plant/contact_results.cc, multibody/plant/contact_results.h, multibody/plant/test/contact_results_test.cc
Users need a way to populate contact results without calling internal functions. We are going to remove the internal functions soon, so now is a good time to add the missing API.
Towards removing `AddContactInfo()` as part of https://github.com/RobotLocomotion/drake/pull/21623, and therefore towards https://github.com/RobotLocomotion/drake/issues/20545.  (Our dear friends in Anzu have decided to call the internal-use-only `ContactResults::AddContactInfo()` function, so we need a replacement before I remove it.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21685)
=> [multibody] Add ContactResults non-default constructor

bindings/pydrake/examples/gym/BUILD.bazel, bindings/pydrake/gym/BUILD.bazel
We no longer support Ubuntu 20.04 Focal, so we don't need to guard our CI against too-old Python versions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21690)
=> [pydrake] Remove vestigial build details

planning/trajectory_optimization/BUILD.bazel, planning/trajectory_optimization/direct_transcription.cc, planning/trajectory_optimization/test/direct_transcription_test.cc
Towards https://github.com/RobotLocomotion/drake/pull/21623 (which will add abstract state, and trip the old error message which was not helpful in this situation), and therefore towards https://github.com/RobotLocomotion/drake/issues/20545.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21688)
=> [planning] Improve direct transcription error messages

solvers/constraint.cc, solvers/constraint.h
It is better to impose a linear inequality constraint or rotated Lorentz cone constraint in this case.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21657)
=> Warn the user if the psd constraint has 1 or 2 rows.

planning/collision_checker.cc, planning/edge_measure.h
From discussion with @tomstewart-woven and @aochiai, `CollisionChecker`'s parallel edge checks can be improved by using the range-based parallel-for loops rather than the naive index-based versions. Using the range-based loops means less work is performed once a colliding configuration is found, since it allows the entire rest of a thread's range to be skipped.
Also contains two other revisions:
- `MeasureEdgeCollisionFreeParallel` now uses an implementation of the behavior of `std::atomic<T>::fetch_min` instead of separate `std:atomic<double>` + `std::mutex`.
- `CheckEdgeCollisionFreeParallel` now special-cases the `q1` check so that it is performed before parallel dispatch.
- - - …
=> [planning] Revise CollisionChecker parallel edge checks

multibody/plant/BUILD.bazel, multibody/plant/contact_results.cc, multibody/plant/contact_results.h, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/geometry_contact_data.cc, multibody/plant/geometry_contact_data.h, multibody/plant/hydroelastic_contact_forces_continuous_cache_data.h, multibody/plant/hydroelastic_contact_info.cc, multibody/plant/hydroelastic_contact_info.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/contact_results_test.cc, multibody/plant/test/contact_results_to_lcm_test.cc, multibody/plant/test/hydroelastic_contact_info_test.cc
Towards #21623 by removing the reliance on cache entry lifetimes for bare pointer aliasing, and therefore towards #20545.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21694)
=> [multibody] Rework ContactResults for performance and safety

planning/scene_graph_collision_checker.cc
Following #21698, the existing sort in `SceneGraphCollisionChecker` is no longer required.
+@hongkai-dai for review, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21702)
=> [planning] Remove duplicate sort from SceneGraphCollisionChecker

multibody/plant/test/multibody_plant_com_test.cc, multibody/plant/test/multibody_plant_kinematics_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/rigid_body.h
Work to enhance documentation and tests after PR #21599 recently merged.
Note: PR #21599 is work towards issue #14269.
This PR has the following.
1.  Better comments before each TEST_F function in multibody_plant_kinematics_test.cc
2.  Remove antiquated TODO(Mitiguy) commented-out block of code.
3.  Fix varios typos.
4.  Improve exception messages for the center of mass functions MultibodyPlant::CalcJacobianCenterOfMassTranslationalVelocity() and 
MultibodyPlant::CalcBiasCenterOfMassTranslationalAcceleration() so they match similar exceptions messages in other center of mass functions.  Adds tests for those two exceptions messages (these tests were missing).
5. Most importantly, added the following comment in rigidy_body.h to 
RigidBody:: CalcCenterOfMassTranslationalAccelerationInWorld() …
=> Enhance documentation and tests for center of mass functions; clarify relationship to forward dynamics

bindings/pydrake/multibody/jupyter_widgets.py, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/_resample_log_interp1d_test.py, bindings/pydrake/systems/test/custom_test.py, bindings/pydrake/systems/test/pyplot_visualizer_test.py, examples/cubic_polynomial/backward_reachability.cc, examples/cubic_polynomial/region_of_attraction.cc, manipulation/schunk_wsg/schunk_wsg_constants.h, systems/analysis/test/lyapunov_test.cc, systems/analysis/test/monte_carlo_test.cc, systems/framework/test/thread_sanitizer_test.cc, systems/framework/test/vector_system_test.cc, systems/framework/vector_system.h, systems/primitives/BUILD.bazel, systems/primitives/barycentric_system.cc, systems/primitives/first_order_low_pass_filter.cc, systems/primitives/gain.cc, systems/primitives/integrator.cc, systems/primitives/test/first_order_low_pass_filter_test.cc, systems/sensors/rotary_encoders.cc
Output ports were performing scalar conversion during inner loops.  This showed up as a hot spot in our simulations.  This is embarassing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21707)
=> [systems] Fix VectorSystem terrible computational performance

multibody/parsing/BUILD.bazel, multibody/parsing/detail_usd_geometry.cc, multibody/parsing/test/detail_usd_geometry_test.cc
This is a follow-up to #21616, which was missing unit tests for USD geometry parsing functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21686)
=> Implement USD geometry parsing tests (#17833)

bindings/pydrake/geometry/geometry_py_optimization.cc, geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/test/hpolyhedron_test.cc
This allows you to draw samples from a measure-zero HPolyhedron, by passing in an appropriate basis of its affine hull.
Closes #21026.
Note that there's an issue with the python bindings, but hopefully, we can get started with feature review while I work on fixing that.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21667)
=> Fix UniformSample for Zero-Measure HPolyhedron

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
This addresses https://github.com/RobotLocomotion/drake/issues/21003.
The unit tests implement the two examples from the issue above.
**Note 1:** I named the function `NewSlackVariables`. It could alternatively be called `NewContinuousSlackVariables` to be closer to the naming conventions of the member functions in `MathematicalProgram`.
**Note 2:** I could also add another helper function called `NewSlackVariable` (or `NewContinuousSlackVariable`) (singular, in addition to plural) if we think that would be natural. I imagine that for most use-cases, most people will only add one slack variable at a time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21403)
=> Implement support for slack variables on edges in GraphOfConvexSets

geometry/optimization/test/affine_subspace_test.cc, geometry/optimization/test/hyperrectangle_test.cc, geometry/proximity/test/contact_surface_utility_test.cc, geometry/proximity/test/distance_to_point_callback_test.cc, geometry/render_gl/test/internal_shape_meshes_test.cc, math/test/linear_solve_test.cc, multibody/math/spatial_vector.h, multibody/tree/test/geometry_spatial_inertia_test.cc, multibody/tree/test/quaternion_floating_joint_test.cc, multibody/tree/test/rotational_inertia_test.cc, solvers/unrevised_lemke_solver.h, systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
Given there are many tests that fail when run on ARM because of the tight floating point tolerance, this PR relaxes some of these tolerances arbitrarily just enough to pass on ARM.
The goal is not to increase all tolerances but to selectively relax those that fail on ARM, maintaining test strictness where possible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21713)
=> Relaxed tolerance on tests to pass on ARM

multibody/math/spatial_acceleration.h, multibody/math/spatial_force.h, multibody/math/spatial_momentum.h, multibody/math/spatial_vector.h, multibody/math/spatial_velocity.h
Addresses #21706 
Changes the implementation of some `operator<op>` in the spatial algebra package to avoid UB when the operator relies on the `operator<op>=` of the base class if running on ARM.
Additionally, relaxes the tolerance used for `IsApprox`, making the `spatial_algebra_test` pass on ARM.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21712)
=> Adds patch to prevent UB when running on ARM

geometry/proximity/make_convex_hull_mesh_impl.cc, geometry/proximity/make_convex_hull_mesh_impl.h, geometry/proximity/test/make_convex_hull_mesh_impl_test.cc
Implements internal code to inflate a convex geometry by a given margin amount.
Note: a marked this as `release notes: fix` given that I did find a bug in the convex hull code. However, I was unable to come up with a simpler unit test for just the fix. Now, the newly introduced unit tests would not pass without the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21655)
=> Implements margin for convex hulls

multibody/parsing/detail_mujoco_parser.cc, multibody/tree/BUILD.bazel, multibody/tree/geometry_spatial_inertia.cc, multibody/tree/geometry_spatial_inertia.h, multibody/tree/test/geometry_spatial_inertia_test.cc
`CalcSpatialInertia()` was trying to operate directly on the mesh file, counter to the documented contract that a `Convex` shape is *always* its convex hull.
Updates mujoco parser to use the convex hull's spatial inertia when attempts to compute *a* physically valid spatial inertia for a mesh fails. Note: the warning stays (but is updated). The mujoco parser likewise posts a warning when the mesh is replaced by its convex hull.
Resolves #21681
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21693)
=> CalcSpatialInertia handles Convex correctly

multibody/topology/link_joint_graph.cc, multibody/topology/link_joint_graph.h, multibody/topology/link_joint_graph_defs.h, multibody/topology/link_joint_graph_inlines.h, multibody/topology/link_joint_graph_joint.h, multibody/topology/link_joint_graph_link.h, multibody/topology/spanning_forest.cc, multibody/topology/spanning_forest.h, multibody/topology/spanning_forest_inlines.h, multibody/topology/spanning_forest_mobod.cc, multibody/topology/spanning_forest_mobod.h, multibody/topology/test/link_joint_graph_test.cc, multibody/topology/test/spanning_forest_test.cc
This is the sixth installment in the PR train for #20225, following #21349.
MultibodyPlant gained the ability to remove joints and supports that in the old multibody graph. This PR updates the new multibody topology code to match, so that #20225 still works with MbP using the new topology.
What's here:
- Distinguish index from ordinal for links and joints. Wherever possible the forest-building code is modified to work with ordinals rather than indices so that performance is unchanged.
- APIs for use by RemoveJoint() and related
- Some improvements to variable names for clarity
- Mark some APIs [[nodiscard]]
- Bonus: remembers where the quaternions are in the state
- Unit tests for new stuff
What's not here:
- Special handling of massless bodies to avoid terminal massless bodies
- …
=> [multibody topology] Update to support MbP's RemoveJoint feature

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py
PR #21710 created C++ code for the new function Multibody::CalcCenterOfMassTranslationalAccelerationInWorld(), which is work towards issue #14269.
This PR creates Python bindings for this new function along with the older C++ function Multibody::CalcCenterOfMassTranslationalVelocityInWorld() (which is missing Python bindings).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21730)
=> Python bind CalcCenterOfMassTranslationalVelocity/Acceleration()

tools/workspace/gfortran/repository.bzl
The `which()` function returns `None` on error. We need to check for that before converting to a string.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21732)
=> [workspace] Fix "gfortran not found" error reporting

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h
Adds a few features to the GCS Graphviz code when a `result` is passed, and additionally make it possible to turn on/off the visualization of different quantities.j
Changes:
- `show_vars`: Decide to show vertex var results
- `show_costs`: Decide to show costs AND also plot vertex costs (these were not currently shown)
- `show_flows`: Plots the flow values as `\phi = ..` and also dims the edge based on the flow value
- `active_path`: If provided, the graph will show the path in red on the graph. This is useful when debugging workflows with multiple different paths through the graph, to quickly be able to show a path in the graph.
- - - …
=> Improve GCS graphviz

multibody/topology/link_joint_graph.h, multibody/topology/spanning_forest.cc, multibody/topology/test/spanning_forest_test.cc
This is the 7th installment in the PR train for #20225, following #21695. This is a small one for a change!
What's here:
- Careful handling of massless links to avoid cutting loops in a way that would unnecessarily leave a terminal massless link.
- Modified existing massless-body unit tests to test for the improved behavior.
What's not here:
- Combining LinkComposites onto a single Mobod
- Some standalone graph-walking algorithms needed by MbP
- RemoveLink()
- Modifications to MbP to use this stuff
There are no user-visible changes here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21731)
=> Adds careful handling of massless links to avoid singular forests

multibody/tree/joint_actuator.cc, multibody/tree/joint_actuator.h, multibody/tree/test/joint_actuator_test.cc
The old contract seemed quite restrictive (and led to maze-of-twisty-passages sim setup code in anzu), yet seemed easy to make a lot more gentle.  I haven't checked whether this lets us unwind the bad code in Anzu, but since this is so easy to fix it seemed a good starting point.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21741)
=> [multibody] Allow implicit PD gain tweaks post-finalize

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
If the user already knows which regions overlap, then it's unnecessary for GCS to compute pairwise intersections. This allows the user to pass in an adjacency list of edges in the graph, bypassing the potentially costly recomputations. This functionality already exists for `GcsTrajectoryOptimization::AddRegions`, so it makes sense to add it for the `AddEdges` method as well.
Closes #21704
+@sadraddini for feature review?
cc @wrangelvid
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21723)
=> Option to manually specify edges (and offsets) in GcsTrajectoryOptimization::AddEdges.

geometry/benchmarking/BUILD.bazel, geometry/benchmarking/compliant_mesh_intersection_benchmark.cc, geometry/proximity/BUILD.bazel
Adds a new benchmark for compliant/compliant intersection code for the purpose of comparing a new intersection algorithm. Based on the benchmark in `//geometry/benchmarking:mesh_intersection_benchmark`.
Towards #21744.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21742)
=> [geometry] Introduce CompliantCompliant intersection benchmark.

geometry/proximity/BUILD.bazel, tools/workspace/highway_internal/patches/target_get_index_inline_always.patch, tools/workspace/highway_internal/repository.bzl
Add a local patch for `highway` to fix the bug that was crashing debug builds with the boxes overlap SIMD port. Also withdraw claims about that crashiness from a comment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21751)
=> [highway_internal] Patch crash bug in debug builds

multibody/parsing/detail_mesh_parser.cc, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mesh_parser_test.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/tree/geometry_spatial_inertia.h, multibody/tree/test/geometry_spatial_inertia_test.cc
In geometry_spatial_inertia.h, delete the nonsensical default density value = 1 kg/m³ (air density ≈ 1 kg/m³) in the function
```
SpatialInertia<double> CalcSpatialInertia(
const geometry::TriangleSurfaceMesh<double>& mesh, double density = 1 );
```
Note: Since this default value is not used in Drake C++ code and the default value is absent in Drake's Python bindings, this change is unlikely to affect caller code (there does not seem to be any in ANZU).  The deprecation does not affect Python, only C++.  
Note: Removing this default value makes this function's density argument signature match the overload in geometry_spatial_inertia.h.
Resolves issue #21728.
- - - …
=> Remove/deprecate default value in CalcSpatialInertia(TriangleSurfaceMesh, density = 1).

geometry/proximity/BUILD.bazel, geometry/proximity/make_box_field.cc, geometry/proximity/make_box_field.h, geometry/proximity/make_capsule_field.h, geometry/proximity/make_cylinder_field.cc, geometry/proximity/make_cylinder_field.h, geometry/proximity/make_ellipsoid_field.h, geometry/proximity/make_mesh_field.cc, geometry/proximity/make_mesh_field.h, geometry/proximity/make_sphere_field.h, geometry/proximity/mesh_half_space_intersection.cc, geometry/proximity/mesh_half_space_intersection.h, geometry/proximity/test/make_box_field_test.cc, geometry/proximity/test/make_capsule_field_test.cc, geometry/proximity/test/make_cylinder_field_test.cc, geometry/proximity/test/make_ellipsoid_field_test.cc, geometry/proximity/test/make_mesh_field_test.cc, geometry/proximity/test/make_sphere_field_test.cc, geometry/proximity/test/mesh_half_space_intersection_test.cc, geometry/proximity/test/pressure_field_invariants.cc, geometry/proximity/test/pressure_field_invariants.h
Part of the larger PR #21528.
This PR focuses solely on the internal functions that define the pressure fields. 
This way we can delay public APIs and contracts to follow up PRs.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21726)
=> Incorporates margin in the compuation of hydroelastic fields

multibody/topology/spanning_forest.cc, multibody/topology/spanning_forest_mobod.cc, multibody/topology/spanning_forest_mobod.h
This removes the bespoke `Mobod::Swap()` since the standard library `std::swap()` works just as well.
Thanks to @SeanCurtis-TRI for pointing out that since Mobods have move semantics, no silly shenanigans are required for swapping.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21762)
=> [multibody topology] Use std::swap() instead of bespoke Swap()

common/test/copyable_unique_ptr_test.cc, common/test_utilities/test/is_memcpy_movable_test.cc, tools/skylark/drake_cc.bzl
Modify default compile flags to make `-Wunqualified-std-cast-call` an error. Fix unqualified instances of `std::move` that were tripping this.
Fixes #19646.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21760)
=> Promote -Wunqualified-std-cast-call to an error

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/planning/planning_py_trajectory_optimization.cc, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Per a discussion with @xuchenhan-tri in #21723 (and a similar one with @SeanCurtis-TRI in the Drake Developers Slack), we should use pointers instead of `std::optional` for optional arguments when we want to avoid data copying. This PR overhauls several methods of GcsTrajectoryOptimization (and one method of GraphOfConvexSets) where potentially large objects were being copied to use pointers.
Note that Pybind11 does not allow None arguments to be used for arguments of type `std::vector<T>*`, so I think we're stuck using `std::optional` for Python users? Alternatively, I could add additional function overloads?
I've tagged this as a breaking change since the argument types have changed (at least for C++ users).
- - - …
=> [gcs] Use pointers for optional arguments

tools/workspace/scs_internal/repository.bzl
Reverts RobotLocomotion/drake#21769
Revert to fix ASan failures in CI: https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-jammy-clang-bazel-continuous-everything-address-sanitizer/788/
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21771)
=> Revert "[workspace] Upgrade scs_internal to latest release 3.2.6"

multibody/topology/link_joint_graph.cc, multibody/topology/link_joint_graph.h, multibody/topology/link_joint_graph_defs.h, multibody/topology/link_joint_graph_inlines.h, multibody/topology/link_joint_graph_link.h, multibody/topology/spanning_forest.cc, multibody/topology/spanning_forest.h, multibody/topology/spanning_forest_mobod.h, multibody/topology/test/link_joint_graph_test.cc, multibody/topology/test/spanning_forest_test.cc
This is the 8th installment in the PR train for #20225, following #21731.
This is the last missing piece of basic topology functionality: the ability to merge welded-together links in the graph so that they follow only a single mobilized body in the forest.
What's here:
- Merge welded-together links ("link composites") onto a single mobilized body
- Proper handling of massless composites (logically like massless links)
- Lots of unit tests to verify behavior of merged composites
- A unit test of copy, move, and assign that got lost earlier
What's not here:
- Some standalone graph-walking algorithms needed by MbP
- RemoveLink()
- Modifications to MbP to use this stuff
There are no user-visible changes in this PR.
- - - …
=> [multibody topology] Handle merged composites

geometry/proximity/BUILD.bazel, geometry/proximity/test/volume_mesh_topology_test.cc, geometry/proximity/volume_mesh_topology.cc, geometry/proximity/volume_mesh_topology.h
Adds a class `VolumeMeshTopology` to compute associated topology data for a given `VolumeMesh`. As of now, this class only computes tetrahedra adjacencies, but can be further improved to compute and store other variouis topological data.
Towards #21744.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21746)
=> [proximity] Adds VolumeMeshTopology

planning/robot_diagram_builder.cc, planning/test/robot_diagram_test.cc, systems/framework/system.cc
Also add a missing warning suppression in the framework when preparing an error message.
---
Without this, the building step always spams the console with deprecation warnings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21783)
=> [planning] RobotDiagramBuilder skips deprecated ports

geometry/proximity/make_ellipsoid_field.h, geometry/proximity/make_mesh_field.cc, geometry/proximity/make_mesh_field.h, geometry/proximity/test/make_ellipsoid_field_test.cc, geometry/proximity/test/make_mesh_field_test.cc
Additional experimentation and testing revealed better ways to compute the pressure fields for these gometries.
**For the elliposoid field**, a convex geometry, the inititial method to compute pressure field would become singular if the margin was equal or larger than the minimum semi-axis lenght. This is obviously wrong. For convex geometries inflation and pressure field defintion must be valid for any value of the margin. 
The new filed then pairs up in #21773 with an inflated ellipsoid of semi-axis aᵢ+δ so that the zero-level pressure field exactly matches the original geometry.
**For the mesh field**, being non-convex, the inflation process might lead to cracks that, though negligible for the computation of forces, introduce topological gaps that completely change the computation of …
=> Updates hydroelastic field computation for the ellipsoid and meshes.

geometry/BUILD.bazel, geometry/proximity/BUILD.bazel, geometry/proximity/make_convex_mesh.cc, geometry/proximity/test/make_convex_mesh_test.cc, geometry/shape_specification.cc, geometry/test/shape_specification_test.cc
The Convex is documented with the semantics that where decalre Convex, the mesh is merely the specification of the source of vertices and the actual geometry *is* the convex hull.
This corrects a couple of calculations that mistakenly used the underlying mesh and not the convex hull.
- `CalcVolume(Convex)` now explicitly uses the convex hull.
- `MakeConvexVolumeMesh()` likewise is limited to Convex shapes.
See #21147 for the definition of `Convex`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21779)
=> Always use the convex hull for Convex shapes

multibody/inverse_kinematics/orientation_cost.cc, multibody/inverse_kinematics/test/inverse_kinematics_test.cc, multibody/inverse_kinematics/test/orientation_cost_test.cc
The previous implementation has cost c * (1 + cos(theta)), where theta is the rotation angle. Namely the previous (wrong implementation) would achieve minimum at theta = 180 degree.The fixed implementation has cost c * (1 - cos(theta)).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21785)
=> Fix a bug in computing OrientationCost.

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/geodesic_convexity.cc, geometry/optimization/geodesic_convexity.h, geometry/optimization/test/geodesic_convexity_test.cc
Per our discussion in #21593, this adds an additional argument to `GeodesicConvexity::CalcPairwiseIntersections` that takes in axis-aligned bounding boxes. If the user computes the AABBs themselves, they can be reused, saving time on recomputation.
+@sadraddini for feature review, please
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21718)
=> Option to specify AABBs when calculating pairwise intersections for GCS.

multibody/plant/multibody_plant.h
To group two overloaded functions (as part of issue #21711), the following doxygen group was added to multibody_plant.h
@name Bias acceleration functions
CalcBiasCenterOfMassTranslationalAcceleration() -- Overload 1 of 2.
CalcBiasCenterOfMassTranslationalAcceleration() -- Overload 2 of 2.
In this subsequent PR, and (to work towards issue #21761),  the following functions are also grouped under that same name.
CalcBiasTranslationalAcceleration()
CalcBiasSpatialAcceleration()
CalcBiasTerm() -- albeit this is somewhat different in spirit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21784)
=> Consolidate documentation for CalcBias functions into one group.

geometry/proximity_engine.cc
This patch clears up some loose ends from prior work:
* It turns out we don't need to sort results an extra time in the new implementations of contact surface calculations.
* Now we check the actual desired post-conditions in debug builds.
* Prior work had some hidden defects in handling of template parameter types.
* There is no predefined type for the dereferenced type that applies to both pointer types and optional, but we can derive the type from an expression.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21791)
=> [geometry] Clarify some implementation details in proximity engine

multibody/plant/multibody_plant.h
To prepare for grouping of the Jacobian functions, copy/paste documentation in multibody_plant.h to consolidate system matrix computations and separate them from Jacobian functions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21796)
=> Simple copy/paste to separate Jacobian and system matrix documentation

multibody/plant/multibody_plant.h
Previous completed PR #21784 grouped CalcBiasAcceleration functions.
In this PR, group Jacobian functions, including:
CalcJacobianSpatialVelocity().
CalcJacobianAngularVelocity().
CalcJacobianTranslationalVelocity().
CalcJacobianCenterOfMassTranslationalVelocity()
CalcJacobianPositionVector().
Resolves issue #21761
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21793)
=> Consolidate documentation for Jacobian functions into one group.

multibody/topology/BUILD.bazel, multibody/topology/link_joint_graph.h, multibody/topology/link_joint_graph_debug.cc, multibody/topology/spanning_forest.cc, multibody/topology/spanning_forest.h, multibody/topology/spanning_forest_debug.cc, multibody/topology/spanning_forest_mobod.h, multibody/topology/test/spanning_forest_test.cc
This is the 9th installment in the PR train for #20225, following #21755.
For debugging and presentations it is very useful to see the multibody graph and generated spanning forest drawn out with boxes and lines. This PR adds generators for graphviz strings, and a helper function for generating .png files from those. 
This code is still internal so there are no user-visible changes here.
For example, this input graph with two loops:
Generates this spanning forest plus welds:
A third visualization shows the "augmented graph" including ephemeral elements added as a result of modeling. This shows what had to be done to the input graph in order to model it, in the original link/joint terminology.
- - - …
=> [multibody topology] Added Graphviz visualization

multibody/topology/spanning_forest.cc, multibody/topology/spanning_forest.h, multibody/topology/test/spanning_forest_test.cc
Just a small cleanup: One unit test depended on some stubbed code due to missing functionality. Now that all the functionality is there the test can depend on that instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21805)
=> [multibody topology] Removed some stub code that is no longer needed

multibody/topology/link_joint_graph.cc, multibody/topology/link_joint_graph.h, multibody/topology/link_joint_graph_debug.cc, multibody/topology/link_joint_graph_defs.h, multibody/topology/link_joint_graph_inlines.h, multibody/topology/link_joint_graph_joint.h, multibody/topology/link_joint_graph_link.h, multibody/topology/link_joint_graph_loop_constraint.h, multibody/topology/spanning_forest.cc, multibody/topology/spanning_forest.h, multibody/topology/test/link_joint_graph_test.cc, multibody/topology/test/spanning_forest_test.cc, multibody/tree/multibody_tree_indexes.h
This defines an alias LinkIndex for BodyIndex and uses it exclusively in the new topology code where we use the term "Link" exclusively. I should have done this much earlier, sorry for the pain previous reviewers! The code is much more readable like this.
The symbol `drake::multibody::LinkIndex` is defined as an alias for `drake::multibody::BodyIndex`. I'm not sure whether we need to mention that in release notes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21811)
=> [multibody topology] Replace BodyIndex with LinkIndex alias

tools/workspace/common_robotics_utilities/repository.bzl, tools/workspace/voxelized_geometry_tools/repository.bzl
Bumps CRU and VGT to latest, upstream changes address new warnings on 24.04 and `-Wmissing-declarations`.
+@ggould-tri for review, thanks!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21812)
=> [workspace] Bump CRU and VGT 2024-08-14

multibody/topology/link_joint_graph.cc, multibody/topology/link_joint_graph.h, multibody/topology/spanning_forest.cc, multibody/topology/spanning_forest.h, multibody/topology/test/link_joint_graph_test.cc, multibody/topology/test/spanning_forest_test.cc
This is the 10th installment in the PR train for #20225, following #21800.
Adds simple algorithms that act on LinkJointGraphs or SpanningForests. These are needed by MultibodyPlant for the switchover to the new topology code. The current signatures are chosen for compatibility with existing MbP functions that are being replaced. These will likely be improved later (they are all internal). For example, some of them use sets unnecessarily or define ordering expectations ("sorted by BodyIndex", e.g.) that may not be necessary.
```
LinkJointGraph::
// Fast functions that depend on the forest having been built.
- FindPathFromWorld(link) -> vector<link>
- FindFirstCommonAncestor(link1, link2) -> link
- FindSubtreeLinks(link) -> vector<link>
- GetSubgraphsOfWeldedLinks() -> vector<set<link>>
- …
```
=> [multibody topology] Adds misc algorithms over graph and forest

multibody/topology/spanning_forest.cc, multibody/topology/spanning_forest.h, multibody/topology/spanning_forest_debug.cc, multibody/topology/test/link_joint_graph_test.cc, multibody/topology/test/spanning_forest_test.cc
Copies the graph & forest sanity checker over from #20225. This does a bunch of internal consistency checks and throws if anything looks wrong. It's called in Debug builds and in many unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21818)
=> [multibody topology] Adds a sanity checker for graph & forest

geometry/optimization/geodesic_convexity.h
Right now, these functions are pretty hard to find if you don't know they exist. This PR creates a new subgroup, which gets nested under geometry_optimization.
Here's what the new "Geodesic Convexity" group looks like, as a subgroup of "Geometry Optimization":
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21826)
=> Create new doxygen group for the geodesic convexity functions, nested under geometry_optimization.

multibody/topology/forest.h, multibody/topology/graph.h, multibody/topology/link_joint_graph.h, multibody/topology/link_joint_graph_defs.h, multibody/topology/link_joint_graph_joint.h, multibody/topology/link_joint_graph_link.h, multibody/topology/link_joint_graph_loop_constraint.h, multibody/topology/spanning_forest.h, multibody/topology/spanning_forest_loop_constraint.h, multibody/topology/spanning_forest_mobod.h, multibody/topology/spanning_forest_tree.h
Currently the LinkJointGraph and SpanningForest topology classes are internal. Per agreement with @jwnimmer-tri I used full `/**` doxygen comments during development for syntax checking in anticipation of these being promoted eventually to public. Now that is done, this PR puts the comments back to internal-appropriate `/*`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21840)
=> [multibody topology] Replace Doxygen /** with /* for internal API

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, bindings/pydrake/planning/test/trajectory_optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
**This is a breaking change** (Note that GCS is still marked experimental)
During the review of #21530, we realized that cost slack variables were not being written to the MathematicalProgramResult in a consistent way between SolveShortestPath and SolveConvexRestriction. This PR addresses this by:
1) The "ell" slack variables associated with the AddCost methods are not returned to the user. Users should call vertex->GetSolutionCost() or edge->GetSolutionCost() to retrieve them. SolveConvexRestriction doesn't use ell, and it's an implementation detail that shouldn't have ever been exposed to the user.
2) GetSolutionCost and GetSolution are now more robust... if the placeholder variables are not in the MathematicalProgramResult, they return the implied values.
3) SolveConvexRestriction no …
=> [GCS] Resolve inconsistencies in results from shortest path vs convex restriction

bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/BUILD.bazel, common/trajectories/composite_trajectory.cc, common/trajectories/composite_trajectory.h, common/trajectories/test/composite_trajectory_test.cc
I have a scenario where I'm generating multiple trajectories (by solving KinematicTrajectoryOptimization problems), and then want to stitch them together into a single long trajectory. However, the start and end times might not line up, so the CompositeTrajectory constructor throws. This provides a convenient class to retime the start and end of each segment, so they align properly.
Not sure who makes sense for this PR -- feel free to assign anyone.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21656)
=> Static constructor for CompositeTrajectory that automatically aligns segment timings.

setup/mac/binary_distribution/requirements.txt, tools/wheel/image/setup.py, tools/wheel/wheel_builder/macos.py
Reverts RobotLocomotion/drake#21829.  Towards #21830.
The root cause of the failure is that NumPy 2.1.0 did not ship any wheels that are compatible with Ventura (macOS 13).  Upstream issue: https://github.com/numpy/numpy/issues/27283.  That means for now, we can't ship Drake wheels for Ventura, either.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21845)
=> [setup] Adjust macOS pip dependencies

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/parsing/model_directives.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc, multibody/tree/rigid_body.h
Much of the free body documentation still assumes that all free bodies have the world as parent. That's not generally true. In fact, we advocate simulating things like suction by putting a floating joint between end effector and manipuland and simply locking the joint when the end effector is "holding" the manipuland. The configuration of the joint is always relative to the inboard frame which, in this case, is not the world.
Furthermore, the API Mbp::SetFreeBodyPoseInWorldFrame() doesn't serve its documented purpose anymore because it doesn't perform the necessary kinematics.
This addresses this in several ways:
1. Update the documentation on the methods that work for floating/non-floating free bodies.
2. SetFreeBodyPoseInWorldFrame() has updated documentation and now explicitly throws …
=> Correct MultibodyPlant free body documentation to reflect current implementations

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/cartesian_product.h, geometry/optimization/test/cartesian_product_test.cc
`CartesianProduct` has optional members `A_` and `b_`, which are essential to the properties of the set, but can only be accessed indirectly (i.e., via checking if a point is in the set, or calculating its volume). Currently, we can't even determine if these values have been set, let alone what the values actually are. This PR adds methods to get the values.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21827)
=> CartesianProduct Getters for A and b Properties

bindings/pydrake/geometry/geometry_py_meshes.cc, bindings/pydrake/multibody/test/mesh_to_model_test.py, geometry/BUILD.bazel, geometry/proximity/BUILD.bazel, geometry/proximity/obj_to_surface_mesh.cc, geometry/proximity/obj_to_surface_mesh.h, geometry/proximity/test/obj_to_surface_mesh_test.cc, geometry/read_obj.cc, geometry/read_obj.h, geometry/test/proximity_engine_test.cc, geometry/test/shape_specification_test.cc, multibody/parsing/detail_mesh_parser.cc, multibody/parsing/test/detail_mesh_parser_test.cc, tools/workspace/tinyobjloader_internal/patches/silence_materials.patch, tools/workspace/tinyobjloader_internal/repository.bzl
We had two different sets of functions that would parse *just* the geometry out of an .obj file. They also had slightly different semantics. There was no value in the separation.
In this case, we maintain the two APIs, but we have one API simply call into the other API, limiting the spread of tinyobjloader.
There is a slight implication to the mesh parser. It previously enforced that parsed meshes *must* have a single object. This has now been relaxed. As the parsed geometry was only used to compute mass properties, this relaxation seems harmless, and makes it more compatible with a larger set of valid .obj files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/218 …
=> Consolidate .obj parsing

common/yaml/test/yaml_doxygen_test.cc, common/yaml/yaml_read_archive.cc, geometry/geometry_state.cc, geometry/meshcat.cc, geometry/optimization/vpolytope.cc, geometry/render/render_material.cc, geometry/render_gltf_client/internal_http_service.cc, multibody/plant/internal_geometry_names.cc, multibody/plant/multibody_plant.cc, multibody/tree/multibody_tree.cc, solvers/clarabel_solver.cc, systems/framework/diagram.cc, systems/framework/system.cc, systems/framework/system_base.cc, systems/framework/test/diagram_test.cc, systems/lcm/test/lcm_system_graphviz_test.cc
For v11, fmt moved the "range and iterator overloads" of fmt::join into the fmt/ranges.h header file. This mindlessly adds that header to all of the compilation units that make use of fmt::join to offer v10->v11 compatibility.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21856)
=> Usages of fmt::join made compatible with fmt v11

setup/ubuntu/source_distribution/packages-jammy-test-only.txt, setup/ubuntu/source_distribution/packages-noble-test-only.txt
Lack of zip has been breaking our coverage reporting in CI, probably for months. Add it to Drake setup to stop the bleeding.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21863)
=> [setup] Satisfy bazel_tools implicit zip dependency

common/test/text_logging_test.cc, common/text_logging.h
Calls that used fmt_runtime with substitution arguments were not being stubbed correctly (there was no matching overload).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21864)
=> [common] Adjust non-spdlog stub to be more generous

multibody/parsing/BUILD.bazel, multibody/parsing/detail_dmd_parser.cc, multibody/parsing/model_directives.h, multibody/parsing/test/detail_dmd_parser_test.cc, multibody/parsing/test/process_model_directives_test.cc, multibody/parsing/test/process_model_directives_test/default_positions.dmd.yaml
The use case here is to allow users to more easily add manipulands to a scene.
Under the status quo, to pose a manipuland the user must type in the URL for the model and then also some _valid_ frame name within that model.  That means looking inside the model file to figure out a good name, which _couples_ a detail inside the model file with the scenario that's using it.  If the user cares about the frame details then they are still welcome to do that, but in many cases the user is happy to just pose the body frame.
With this change, they can specify the empty string for the manipuland frame to be posed, which is then taken to refer to the body frame of the sole body.  For scenarios with dozens of models whose initial poses are just randomly sampled within some domain, this is much nicer …
=> [multibody] Add dmd support for canonical frames for default poses

tools/workspace/styleguide/BUILD.bazel, tools/workspace/styleguide/package.BUILD.bazel
Having both `py_binary` and `py_test` targets is brittle and confusing for maintainers. Remove the `py_binary` and use a filegroup instead.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21877)
=> [tools] Clarify cpplint_unittest spelling

tools/wheel/wheel_builder/macos.py
This is safe now that NumPy has published a new fixed version (2.1.1).
Closes #21830.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21883)
=> [wheel] Re-enable macOS Python 3.11 builds

multibody/plant/BUILD.bazel
Everything in these files is `namespace internal` so isn't stable API.
Towards #21605.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21882)
=> [multibody] Move two classes to implementation_deps and internal

geometry/optimization/affine_subspace.cc, geometry/optimization/test/affine_subspace_test.cc
Previously, this method had not been implemented, since it's only used in `GraphOfConvexSets`, where one generally doesn't want to deal with unbounded sets. However, if a user creates an `Intersection` of a bounded set with an `AffineSubspace`, the resulting set will also be bounded.
One may want to do this, for example, to restrict motion along an affine subspace in GcsTrajectoryOptimization. (We did this for our bimanual manipulation paper to fix the grasp distance, whereas our regions allowed varying grasp distance. Having this feature implemented would have simplified our code.)
cc @lujieyang @hjsuh94 
Not sure who makes the most sense for feature review. Maybe +@hongkai-dai? @TobiaMarcucci, it would be great if you could give my math a sanity check.
- - - …
=> Implement AffineSubspace::DoAddPointInNonnegativeScalingConstraints

planning/linear_distance_and_interpolation_provider.cc, planning/test/linear_distance_and_interpolation_provider_test.cc
Adding a test case and changing for loop to fix the issue documented here #21860.
Closes #21860.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21867)
=> Fix LinearDistanceAndInterpolationProvider vs removed joint

geometry/optimization/affine_ball.cc, geometry/optimization/affine_ball.h, geometry/optimization/affine_subspace.cc, geometry/optimization/affine_subspace.h, geometry/optimization/cartesian_product.cc, geometry/optimization/cartesian_product.h, geometry/optimization/convex_set.cc, geometry/optimization/convex_set.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/hyperrectangle.cc, geometry/optimization/hyperrectangle.h, geometry/optimization/test/affine_subspace_test.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
`AffineSubspace` provides a generic method to compute the affine hull of an arbitrary convex set, by repeatedly solving convex optimization problems. However, for certain subclasses of `ConvexSet`, it's possible to compute the affine hull with a simpler numerical procedure, or even in closed-form. For example, we can compute the affine hull of a `VPolytope` with a singular value decomposition, and the affine hull of a `Hyperellipsoid` is always the whole space.
Holding off on looking for a reviewer until #21827 lands, since this PR builds off its functionality.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21828)
=> More Efficient Affine Hull Computation for Certain Subclasses of ConvexSet

geometry/BUILD.bazel, geometry/geometry_file_formats_doxygen.h, geometry/meshcat.cc, geometry/test/meshcat_test.cc
Towards #20444. Like many mujoco assets, the
`mujoco_menagerie/boston_dynamics_spot/spot.xml` has obj files that reference missing `.mtl` files. For `spot.xml`, the mujoco parser correctly reads the rgba texture, but the meshcat parser did not publish it (because it went down the branch expecting the mtl).
This change makes meshcat slightly more robust... if the mtl file is missing, it publishes the file in the format that will accept the color property instead.
Example code:
```
from pydrake.all import ModelVisualizer, StartMeshcat, PackageMap
visualizer = ModelVisualizer(meshcat=meshcat)
visualizer.parser().package_map().AddRemote(
package_name="mujoco_menagerie",
params=PackageMap.RemoteParams(
urls=[
f"https://github.com/google-deepmind/mujoco_menagerie/archive/bf110a75a56e5bd146c7ed76 …
```
=> [meshcat] when .mtl files are missing, render colors instead

bindings/pydrake/geometry/test/optimization_test.py
Towards #21345.  CLP will soon starting barking about unknown options.
Amends #18875.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21902)
=> [py optimization] Fix option name in unit test

bindings/pydrake/math/math_py_monolith.cc, bindings/pydrake/symbolic/symbolic_py_monolith.cc
Adjust bindings to follow topological order, so that function signatures can look up their requisite python types.
Here's one example of broken docs / types: [`RigidTransform.__init__`](https://drake.mit.edu/pydrake/pydrake.math.html#pydrake.math.RigidTransform.__init__).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21908)
=> [py math] Fix signatures to use Python types (not C++)

bindings/pydrake/manipulation/BUILD.bazel, bindings/pydrake/manipulation/manipulation_py.cc, bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/optimization_py.cc, bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/tree_py.cc, bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/estimators_py.cc, bindings/pydrake/systems/primitives_py.cc
These were all identified by my automated regression tooling WIP (not on master yet).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21911)
=> [pydrake] Fix signatures to use Python types (not C++)

bindings/pydrake/common/_common_extra.py, bindings/pydrake/geometry/_geometry_extra.py, bindings/pydrake/geometry/geometry_py_common.cc, bindings/pydrake/geometry/test/common_test.py, common/memory_file.cc, common/memory_file.h, geometry/BUILD.bazel, geometry/in_memory_mesh.cc, geometry/in_memory_mesh.h, geometry/mesh_source.cc, geometry/mesh_source.h, geometry/proximity/BUILD.bazel, geometry/proximity/make_convex_hull_mesh_impl.cc, geometry/proximity/make_convex_hull_mesh_impl.h, geometry/proximity/refine_mesh.cc, geometry/proximity/test/vtk_to_volume_mesh_test.cc, geometry/proximity/test/zero_simplex_manual_test.cc, geometry/proximity/vtk_to_volume_mesh.cc, geometry/proximity/vtk_to_volume_mesh.h, geometry/test/in_memory_mesh_test.cc, geometry/test/mesh_source_test.cc
These provide the foundation of in-memory mesh specification. `InMemoryMesh` tracks a `MemoryFile` for a mesh file (and an optional set of supporting files in the near future).
`MeshSource` acts as a sugared-up variant between a `filesystem::path` and an `InMemoryMesh`. This will, ultimately, serve as the storage for `Mesh` and `Convex` specifications.
While it is not integrated with `Mesh` or `Convex` yet, we exercise the new APIs in `vtk_to_volume_mesh` -- which consumes the `MeshSource` and creates the `VolumeMesh` from both in-memory as well as on-disk .vtk files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21890)
=> Introduce InMemoryMesh and MeshSource

bindings/pydrake/geometry/geometry_py_common.cc, bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/geometry_py_render.cc, bindings/pydrake/geometry/geometry_py_scene_graph.cc, bindings/pydrake/geometry/geometry_py_visualizers.cc
Adjust bindings to follow topological order, so that function signatures can look up their requisite python types.
This is not a 100% fix -- dependencies on other modules (`perception` and `multibody.math`) still show up as dangling due to module cycles.
Here's one example of broken docs / types: [`QueryObject.ComputeContactSurfaces`](https://drake.mit.edu/pydrake/pydrake.geometry.html#pydrake.geometry.QueryObject.ComputeContactSurfaces).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21907)
=> [py geometry] Fix signatures to use Python types (not C++)

bindings/pydrake/planning/planning_py_collision_checker_interface_types.cc
Here's one example of broken docs / types: [RobotClearance.collision_types](https://drake.mit.edu/pydrake/pydrake.planning.html#pydrake.planning.RobotClearance.collision_types).  On master, it erroneously uses the C++ type name in the documentation.  With this fix, it now says `pydrake.planning.RobotCollisionType` with a nice hyperlink.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21916)
=> [py planning] Fix signatures to use Python types (not C++)

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
Adjust bindings to follow topological order, so that function signatures can look up their requisite python types.
Here's one example of broken docs / types: [`MathematicalProgramResult.get_solution_result`](https://drake.mit.edu/pydrake/pydrake.solvers.html#pydrake.solvers.MathematicalProgramResult.get_solution_result).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21909)
=> [py solvers] Fix signatures to use Python types (not C++)

geometry/optimization/hpolyhedron.cc, geometry/optimization/hpolyhedron.h, geometry/optimization/hyperellipsoid.cc, geometry/optimization/hyperellipsoid.h, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h
This is part of a slow-moving PR train to rid ourselves of unnecessary reifier-related complexity.  The idea is to make the control flow (and return values) more obvious, instead of routing through obscure private virtual functions with static casts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21210)
=> [geometry] Port the remaining convex set types to Shape::Visit

bindings/pydrake/geometry/geometry_py_common.cc, bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/geometry_py_scene_graph.cc, bindings/pydrake/geometry/geometry_py_visualizers.cc, bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc
(The prior fix to this module at #21913 only cleaned up the `ConvexSet` items; this PR tackles the IRIS stuff.)
Here's one example of broken docs / types: [CspaceFreePolytope.BinarySearch](https://drake.mit.edu/pydrake/pydrake.geometry.optimization.html#pydrake.geometry.optimization.CspaceFreePolytope.BinarySearch).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21919)
=> [py optimization] Fix signatures to use Python types (not C++)

bindings/pydrake/multibody/rational_py.cc
The best place to see the resulting effects is the docs. Here's one example of broken docs / types: [RationalForwardKinematics](https://drake.mit.edu/pydrake/pydrake.multibody.rational.html#pydrake.multibody.rational.RationalForwardKinematics).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21917)
=> [py rational] Fix signatures to use Python types (not C++)

tools/workspace/openusd_internal/BUILD.bazel, tools/workspace/openusd_internal/package.BUILD.bazel, tools/workspace/openusd_internal/upgrade.py
* enable upgrade.py to work vs OpenUSD dev branch
* steal a symbol hiding trick from patches into the build system
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21886)
=> openusd_internal: patch reduction progress

manipulation/schunk_wsg/schunk_wsg_trajectory_generator.cc, manipulation/schunk_wsg/test/build_schunk_wsg_control_test.cc
Update trajectory when trajectory_ is empty, so that the gripper can close its fingers at the beginning of the simulation.
resolves #21920
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21925)
=> [schunk_wsg] Fix trajectory bug with initial zero target

bindings/pydrake/multibody/test/plant_test.py, bindings/pydrake/multibody/tree_py.cc, multibody/tree/rigid_body.h
Python bindings for C++ public functions RigidBody::CalcCenterOfMassTranslationalVelocityInWorld() 
and RigidBody::CalcCenterOfMassTranslationalAccelerationInWorld() .
Perhaps these Python bindings could have been done as part of issue #14269. However, binding RigidBody::CalcCenterOfMassTranslationalVelocityInWorld() was overlooked a while ago and binding RigidBody::CalcCenterOfMassTranslationalAccelerationInWorld() was delayed to this PR.  
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21926)
=> Python binding for Body::CalcCenterOfMassTranslationalVelocityInWorld().

multibody/tree/body_node.cc, multibody/tree/body_node.h, multibody/tree/body_node_impl.cc, multibody/tree/body_node_impl.h, multibody/tree/body_node_world.h, multibody/tree/mobilizer.h, multibody/tree/mobilizer_impl.cc, multibody/tree/mobilizer_impl.h, multibody/tree/multibody_tree.cc, multibody/tree/planar_mobilizer.cc, multibody/tree/planar_mobilizer.h, multibody/tree/prismatic_mobilizer.cc, multibody/tree/prismatic_mobilizer.h, multibody/tree/quaternion_floating_mobilizer.cc, multibody/tree/quaternion_floating_mobilizer.h, multibody/tree/revolute_mobilizer.cc, multibody/tree/revolute_mobilizer.h, multibody/tree/rpy_ball_mobilizer.cc, multibody/tree/rpy_ball_mobilizer.h, multibody/tree/rpy_floating_mobilizer.cc, multibody/tree/rpy_floating_mobilizer.h, multibody/tree/screw_joint.h, multibody/tree/screw_mobilizer.cc, multibody/tree/screw_mobilizer.h, multibody/tree/test/body_node_test.cc, multibody/tree/universal_mobilizer.cc, multibody/tree/universal_mobilizer.h, multibody/tree/weld_mobilizer.cc, multibody/tree/weld_mobilizer.h
Templatizes BodyNodeImpl on concrete Mobilizer type to permit inlines rather than virtuals. This is part of the MbP performance epic #18442.
This PR doesn't change how we compute anything or attempt to reduce flop count. It just rearranges what's there to allow the compiler to generate better code. There are many further changes to come but I want to merge this now since the shuffling around would make it hard to review with substantive changes. This is a step towards a templatized kernel using only fixed-size objects, and reduces the amount of context-digging being done (but doesn't yet eliminate it all).
As a proof of concept, in addition to the newly-templatized BodyNodeImpl, I moved the position and velocity kinematics methods to take advantage of that. Everything else is unchanged. I …
=> [multibody] Templatize body node

geometry/proximity/BUILD.bazel, geometry/proximity/calc_signed_distance_to_surface_mesh.cc, geometry/proximity/calc_signed_distance_to_surface_mesh.h, geometry/proximity/test/calc_signed_distance_to_surface_mesh_test.cc
Support:
- #21471
- #21323
- #3220
Another PR will use it in ProximityEngine for ComputeSignedDistanceToPoint for non-convex Mesh() and convex hull Convex() of both .vtk files (tetrahedral meshes) and .obj files (triangle meshes).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21566)
=> [geometry] Calculate signed distance from point to closed meshes

bindings/pydrake/systems/framework_py.cc, bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_semantics.h, bindings/pydrake/systems/framework_py_systems.cc
The best place to see the resulting effects is the docs. Here's an example of broken docs / types: [Context.get_mutable_state](https://drake.mit.edu/pydrake/pydrake.systems.framework.html#pydrake.systems.framework.Context.get_mutable_state).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21921)
=> [py framework] Fix signatures to use Python types (not C++)

bindings/pydrake/geometry/_geometry_extra.py, bindings/pydrake/geometry/geometry_py_common.cc, bindings/pydrake/geometry/test/common_test.py, common/BUILD.bazel, common/file_source.cc, common/file_source.h, common/memory_file.cc, common/memory_file.h, common/test/file_source_test.cc, common/test/memory_file_test.cc, geometry/BUILD.bazel, geometry/in_memory_mesh.cc, geometry/in_memory_mesh.h, geometry/mesh_source.cc, geometry/proximity/obj_to_surface_mesh.cc, geometry/proximity/test/obj_to_surface_mesh_test.cc, geometry/proximity/test/vtk_to_volume_mesh_test.cc, geometry/proximity/vtk_to_volume_mesh.cc, geometry/read_obj.cc, geometry/test/in_memory_mesh_test.cc, geometry/test/mesh_source_test.cc, geometry/test/read_obj_test.cc, multibody/parsing/detail_mesh_parser.cc
This requires a new basic file: FileSource which allows a file specification to be either a path or a MemoryFile. This allows an in-memory mesh's supporting files to reference resources on disk as well as other in-memory files.
Relates #15263
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21923)
=> Add supporting files to InMemoryMesh

bindings/pydrake/geometry/_geometry_extra.py, bindings/pydrake/geometry/geometry_py_common.cc, bindings/pydrake/geometry/test/common_test.py, geometry/BUILD.bazel, geometry/in_memory_mesh.h, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/make_mesh_from_vtk.cc, geometry/proximity/make_mesh_from_vtk.h, geometry/proximity/test/hydroelastic_internal_test.cc, geometry/shape_specification.cc, geometry/shape_specification.h, geometry/test/shape_specification_test.cc
MeshSource replaces the "filename" and "extension" members. For now, the InMemoryMesh-valued constructors are hidden from documentation and filename() semantics is changed to throw if someone attempts to call filename on an in-memory mesh. This throwing behavior is equivalent to placing a `DRAKE_DEMAND(mesh.source().IsPath())` *everywhere* a mesh.filename() is currently used. As support for MeshSource spreads, errors will evaporate.
We exercise the new storage in a limited case: creating a rigid hydro mesh from a MeshSource.
Furthermore, we update MakeVolumeMeshFromVtk:
- That function should not be used on Convex -- we should be computing a VolumeMesh from its convex hull.
- Rather than taking a path, it takes a Mesh and passes the mesh's source to ReadVtkToVolumeMesh().
relates #15263
- …
=> Mesh and Convex now uses MeshSource as storage

geometry/geometry_state.cc, geometry/render/BUILD.bazel, geometry/render/render_material.cc, geometry/render/render_material.h, geometry/render/render_mesh.cc, geometry/render/render_mesh.h, geometry/render/test/render_material_test.cc, geometry/render/test/render_mesh_test.cc, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/test/internal_render_engine_gl_test.cc, geometry/render_gltf_client/internal_render_engine_gltf_client.cc, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/internal_render_engine_vtk.h
This builds on the addition of MeshSource having supporting files (as material definitions require .mtl and possibly texture images).
The RenderMesh infrastructure includes a custom tinyobj::MaterialReader in order to host .mtl file data from disk or memory.
This introduces a new internal class: TextureSource. This is akin to a FileSource, but where FileSource has two modes, TextureSource has four to span a greater number of definitions for glTFs embedded textures.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21944)
=> RenderMesh and RenderMaterial parse .obj files from MeshSource

geometry/BUILD.bazel, geometry/read_gltf_to_memory.cc, geometry/read_gltf_to_memory.h, geometry/test/read_gltf_to_memory_test.cc
This converts a path to a glTF file into a fully-specified `InMemoryMesh` of same by chasing down the buffer and image references to external files and packing them into the in-memory mesh's supporting files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21949)
=> Add utility for working with glTF files

geometry/proximity/BUILD.bazel, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/make_convex_hull_mesh.cc, geometry/proximity/make_convex_hull_mesh_impl.cc, geometry/proximity/make_convex_hull_mesh_impl.h, geometry/proximity/test/make_convex_hull_mesh_impl_test.cc, geometry/shape_specification.cc, geometry/test/shape_specification_test.cc
Implementation of making the convex hull mesh updates based on mesh file extension:
- .obj: Make use of ReadObj based on MeshSource.
- .vtk: Make use of ReadVtkToVolumeMesh based on MeshSource.
- .gltf: deferred to next PR.
The soft hydro Convex shape makes use of this to inflate the convex shape.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21945)
=> Convex hull computation uses MeshSource

solvers/BUILD.bazel, solvers/test/csdp_solver_test.cc, solvers/test/mosek_solver_test.cc, solvers/test/nlopt_solver_test.cc, solvers/test/snopt_solver_test.cc
In preparation for #21345.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21939)
=> [solvers] Add missing unit tests for options handling

tools/workspace/abseil_cpp_internal/patches/civil_time_linkopts.patch, tools/workspace/abseil_cpp_internal/repository.bzl
Amend the patch commands to convert all of the cc_library() rules in the upstream's bazel files to use "linkstatic = 1". This prevents generation of "accidental" shared libraries, which in turn were causing link failures with more modern linkers (.i.e., ld.mold).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21961)
=> [abseil_cpp_internal] Fix static linking patch commands

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/iris.cc, geometry/optimization/iris.h, geometry/optimization/test/iris_in_configuration_space_test.cc, geometry/optimization/test/iris_test.cc
We allow the user to pass in a bounding region for IRIS (and IrisInConfigurationSpace, but I'll use IRIS as a catchall here), such that the region the algorithm produces will be properly contained within that set. As long as the intersection of that bounding region with the underlying domain (the user-specified HPolyhedron in IRIS, or the joint limits in IrisInConfigurationSpace) is bounded, then the algorithm can function properly. However, we currently throw an error if the domain (or the joint limits) are unbounded, no matter what is specified for the bounding region. This PR modifies the check to occur after the two have been intersected, making it much more user-friendly to grow IRIS regions when there are unbounded joints.
This PR also adds a flag `skip_domain_boundedness_check` to …
=> More Reasonable Behavior for IRIS Boundedness Check when an Initial Region is Provided

planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
Resolves #21941.
I thought we would need an overload to handle the case where the user doesn't provide edge offsets because there are no continuous revolute joints, but actually, I don't think that's necessary. If there are no such joints, then no optimization problems will be solved, so the added computational load should be negligible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21946)
=> Adjust GcsTrajectoryOptimization methods AddEdges and AddRegions to automatically compute edge offsets if they're not provided.

bindings/pydrake/BUILD.bazel, bindings/pydrake/test/memory_leak_test.py
Towards #14387.
The objective of this PR is to bootstrap the virtuous cycle of making reproducers of the problem, finding good diagnostic tools to help explain the problem, fixing bugs in prototypes, re-instrumenting, adding more examples, etc.
---
Sample output of `bazel run //bindings/pydrake:memory_leak_test` as of today:
```
RUNNING: dut_simple_source
RepetitionDetail(i=0, blocks=3)
RepetitionDetail(i=1, blocks=4)
RepetitionDetail(i=2, blocks=5)
RepetitionDetail(i=3, blocks=5)
RepetitionDetail(i=4, blocks=6)
RepetitionDetail(i=5, blocks=7)
RepetitionDetail(i=6, blocks=8)
RepetitionDetail(i=7, blocks=8)
RepetitionDetail(i=8, blocks=9)
RepetitionDetail(i=9, blocks=9)
RepetitionDetail(i=10, blocks=9)
RepetitionDetail(i=11, blocks=10)
RepetitionDetail(i=12, blocks=10) …
```
=> [pydrake] Add example of memory leaks

planning/trajectory_optimization/gcs_trajectory_optimization.cc
Hotfix for #21946.
The prior code on master relied on `vector::at()` to validate its input indices, but #21946 changed that to `vector::operator[]`.  Here we just switch it back to `vector::at()`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21980)
=> [trajopt] Add missing bounds checks

bindings/pydrake/examples/examples_py_acrobot.cc, bindings/pydrake/examples/examples_py_pendulum.cc, bindings/pydrake/examples/examples_py_rimless_wheel.cc
The best place to see the resulting effects is the docs.  Here's one example of broken docs / types: [AcrobotPlant.get_parameters](https://drake.mit.edu/pydrake/pydrake.examples.html#pydrake.examples.AcrobotPlant.get_parameters).  After this PR, the docs would use correct names for the types, with xref hyperlinks, etc.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21918)
=> [py examples] Fix signatures to use Python types (not C++)

bindings/pydrake/multibody/optimization_py.cc, bindings/pydrake/multibody/test/optimization_test.py, multibody/optimization/test/toppra_test.cc, multibody/optimization/toppra.cc, multibody/optimization/toppra.h
Toppra can handle non-zero `ṡ` (time-derivative of path parameter), but zero defaults were hard coded. This PR makes them an argument that the user can change.
The use case is obtaining trajectories with non-zero start/end velocities.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21975)
=> Derivative Boundary conditions in Toppra::SolvePathParameterization 

multibody/tree/body_node.cc, multibody/tree/body_node.h, multibody/tree/body_node_impl.cc, multibody/tree/body_node_impl.h, multibody/tree/body_node_world.h, multibody/tree/multibody_tree.cc, multibody/tree/test/body_node_test.cc
This PR just relocates a bunch of multibody algorithms from the generic BodyNode class to the templatized BodyNodeImpl class (which derives from BodyNode) in preparation for taking advantage of the template arguments for speed. A bunch of private helper methods were moved over also. In most cases there were no changes at all but in a few places I had to make minor changes to get things to compile, e.g. add `this->` to call the few BodyNode functions that remain.
Also, these sizeable algorithms were in the body_node.h header; they are now in body_node_impl.cc so many compilation units are somewhat faster to compile now.
There is small performance cost (~5%) of this change, likely due to (a) making these functions virtual, and (b) using more code memory due to per-mobilizer instantiation, …
=> [multibody] Move almost all code from BodyNode to templatized BodyNodeImpl

doc/_pages/buildcop.md, doc/_pages/code_review_checklist.md, doc/_pages/getting_help.md, doc/_pages/jenkins.md
Towards https://github.com/RobotLocomotion/drake/issues/21978
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21983)
=> [doc] Move Mac examples from Ventura to Sonoma

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
fyi @yuvaltassa: the [xml spec](https://mujoco.readthedocs.io/en/stable/XMLreference.html#actuator) indicates that gear must be specified with 6 numbers, but [clearly](https://github.com/search?q=repo%3Agoogle-deepmind%2Fdm_control%20gear&type=code) specifying only a single number works, too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21967)
=> [MuJoCo parser] Support "gear", "armature", and "position"

bindings/pydrake/BUILD.bazel, bindings/pydrake/test/memory_leak_test.py
Towards #14387.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21986)
=> [pydrake] Add more examples of memory leaks

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, examples/multibody/strandbeest/run_with_motor.cc, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/plant/constraint_specs.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/sap_driver.cc, multibody/plant/test/multibody_plant_test.cc, multibody/plant/test/sap_driver_ball_constraints_test.cc
Implements initial support for equality constraints in the MuJoCo parser.
As discussed in #21943, this generalizes
`MultibodyPlant::AddBallConstraint()` to take a partial specification of constraint, which uses the kinematics during FinalizePlantOnly() to compute the point on body B which satisfies the constraints.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21970)
=> [Mujoco Parser] Support equality "connect" constraints.

tools/workspace/libtiff_internal/package.BUILD.bazel, tools/workspace/libtiff_internal/repository.bzl
Toward #21979.
When merging, we should squash this (nixing the irrelevant subject line of the second commit).  The release note we want is just the version bump.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21994)
=> [workspace] Upgrade libtiff_internal to latest release v4.7.0

geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc
Implements a "fail fast check" that attempts to guess a separating hyperplane to avoid having to solve the point containment LP for PointInSet for VPolytopes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21988)
=> Implements fail fast in DoPointInSet for VPolytopes

doc/_pages/jenkins.md, doc/_pages/release_playbook.md, tools/release_engineering/download_release_candidate.py
Towards https://github.com/RobotLocomotion/drake/issues/21978
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21984)
=> Move Mac packaging and wheel jobs to Sonoma

doc/_pages/issues.md
#22000 introduced a new issue component, but the new entry was not in alphabetical order. This moves it into place.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22001)
=> Alphabetize issue components

tools/skylark/drake_cc.bzl, tools/skylark/drake_py.bzl
Sample programs neither need nor deserve coverage reporting. This slightly helps reduce CI flakes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22006)
=> [skylark] Skip kcov on add_test_rule tests

bindings/pydrake/visualization/_meldis.py, bindings/pydrake/visualization/test/meldis_test.py, examples/scene_graph/BUILD.bazel, examples/scene_graph/solar_system.cc, examples/scene_graph/solar_system_run_dynamics.cc, geometry/BUILD.bazel, geometry/drake_visualizer.cc, geometry/meshcat.cc, geometry/meshcat_internal.cc, geometry/meshcat_internal.h, geometry/test/drake_visualizer_test.cc, geometry/test/meshcat_internal_test.cc, geometry/test/meshcat_manual_test.cc, geometry/test/meshcat_test.cc, lcmtypes/lcmt_viewer_geometry_data.lcm
- Meshcat operates on MeshSource
- DrakeVisualizer serializes a FileSource into javascript that subsequently gets decoded by meldis (and then passed to its own Meshcat as in-memory Mesh).
- To evaluate the result:
- meshcat_manual_test has been updated to include both on-disk and in-memory representations. (Doesn't support meldis.)
- The solar system example has been updated to perform a similar role and now supports both meshcat and meldis.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21952)
=> Illustration supports in-memory meshes

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/planar_scenegraph_visualizer.py, bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py
All "mesh"-type objects (Mesh and Convex) ultimately are represented by their convex hulls. This clarifies this fact. Furthermore, the logic for searching for an alternative mesh file has been updated to respect the MeshSource for the Mesh/Convex (we only search if the source was a path and not in-memory).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21950)
=> Planar scene graph visualizer updated

common/trajectories/bezier_curve.cc, common/trajectories/bezier_curve.h, common/trajectories/bspline_trajectory.cc, common/trajectories/bspline_trajectory.h, common/trajectories/composite_trajectory.cc, common/trajectories/composite_trajectory.h, common/trajectories/discrete_time_trajectory.cc, common/trajectories/discrete_time_trajectory.h, common/trajectories/exponential_plus_piecewise_polynomial.cc, common/trajectories/exponential_plus_piecewise_polynomial.h, common/trajectories/path_parameterized_trajectory.cc, common/trajectories/path_parameterized_trajectory.h, common/trajectories/piecewise_polynomial.cc, common/trajectories/piecewise_polynomial.h, common/trajectories/piecewise_pose.cc, common/trajectories/piecewise_pose.h, common/trajectories/piecewise_quaternion.cc, common/trajectories/piecewise_quaternion.h, common/trajectories/piecewise_trajectory.cc, common/trajectories/piecewise_trajectory.h, common/trajectories/trajectory.cc, common/trajectories/trajectory.h
We noticed this problem in an `#onramp` slack thread from yesterday.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22010)
=> [trajectories] Add GSG-required out-of-line destructors

.github/ISSUE_TEMPLATE/BUG.yml, doc/_pages/from_source.md, doc/_pages/installation.md, tools/wheel/wheel_builder/macos.py
Towards https://github.com/RobotLocomotion/drake/issues/21978
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22004)
=> [doc] Remove official support of macOS 13 (Ventura)

solvers/constraint.cc, solvers/constraint.h, solvers/cost.cc, solvers/cost.h, solvers/evaluator_base.cc, solvers/evaluator_base.h, solvers/ipopt_solver_internal.cc, solvers/ipopt_solver_internal.h, solvers/minimum_value_constraint.cc, solvers/minimum_value_constraint.h
Towards #22015
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22018)
=> Remove inline destructor in solvers folder.

multibody/tree/BUILD.bazel, multibody/tree/body_node.cc, multibody/tree/body_node.h, multibody/tree/body_node_impl.cc, multibody/tree/body_node_impl.h, multibody/tree/body_node_impl_mass_matrix.cc, multibody/tree/body_node_world.h, multibody/tree/multibody_tree.cc, multibody/tree/test/body_node_test.cc
Moves CalcMassMatrix() from high-level multibody tree code to low level templatized body node code where it can use its mobilizer-specific knowledge to work with fixed-size matrices.
This is an O(n²) algorithm so requires an awkward double-dispatch so that we always know both dimensions of the current mass matrix block being computed.
This provides a modest performance improvement to CalcMassMatrix(): 10% with gcc 11.4.0, 24% with clang 14.0.0 and sets us up for more gains with internal changes.
Minor:
- added body_node_impl_mass_matrix.cc with mass matrix inertia functions defined there to keep compile times balanced
- made some minor changes to the composite body inertia function
- moved composite body inertia and an unrelated function back from the templatized class to the base class …
=> [multibody] Move mass matrix computation to body_node_impl for speed

bindings/pydrake/systems/primitives_py.cc, systems/primitives/test/zero_order_hold_test.cc, systems/primitives/zero_order_hold.cc, systems/primitives/zero_order_hold.h
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22005)
=> Added method to set x(n) in the context for vector-valued ZeroOrderHold

bindings/pydrake/geometry/geometry_py_common.cc, bindings/pydrake/geometry/test/common_test.py, geometry/shape_specification.h, geometry/test/geometry_state_test.cc, geometry/test/proximity_engine_test.cc, geometry/test/shape_specification_test.cc, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/parsing/test/detail_sdf_geometry_test.cc, multibody/parsing/test/detail_urdf_geometry_test.cc, multibody/tree/geometry_spatial_inertia.cc
This represents the scope and coarse sequence of PRs to fully implement in-memory meshes in Drake.
Closes #15263
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21881)
=> Deprecate Mesh and Convex::filename() method (in favor of source())

bindings/pydrake/geometry/geometry_py_visualizers.cc, bindings/pydrake/geometry/test/visualizers_test.py
Previously, this lead to unintuitive behavior. For example, if you call `meshcat.SetProperty("/Lights/AmbientLight/<object>", "intensity", 2)`, then the light intensity is set to 1.
Closes #21982.
Since we don't have any sort of `meshcat::GetProperty` method, I don't think we have a way of testing this change?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22021)
=> Do not convert an int to a bool in Python binding of Meshcat::SetProperty

bindings/pydrake/geometry/geometry_py_visualizers.cc, bindings/pydrake/geometry/test/visualizers_test.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_test.cc, multibody/meshcat/joint_sliders.cc, visualization/meshcat_pose_sliders.cc
Fix a footgun that has been hiding in plain sight for some time: the mismatch among the meshcat controls API, its (mis-)uses, and the fact that Python bindings make destructor ordering unpredictable.
Why hasn't it fired? Largely because pybind memory management was configured to leak diagrams and leaf systems forever, so destructors would never run. In order to open the way to a fix for memory leaks, the destructor hazard(s) must be addressed first.
* Introduce a non-strict deletion mode, that warns instead of throws.
* Use non-strict deletion when called from destructors.
* In addition, catch all exceptions in destructors, and abort if any are raised.
* Update bindings, doc, and tests.
Note that this patch does *not* solve any of the inherent hazards of the meshcat controls API: the …
=> [visualization] Fix meshcat control deletion paths

geometry/render_gltf_client/test/server_vtk_backend.cc, geometry/render_vtk/BUILD.bazel, geometry/render_vtk/internal_make_render_window.cc, geometry/render_vtk/internal_make_render_window.h, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/internal_render_engine_vtk.h, geometry/render_vtk/render_engine_vtk_params.cc, geometry/render_vtk/render_engine_vtk_params.h, geometry/render_vtk/test/internal_render_engine_vtk_no_display_test.cc, geometry/render_vtk/test/internal_render_engine_vtk_test.cc, geometry/render_vtk/test/render_engine_vtk_params_test.cc, tools/workspace/vtk_internal/settings.bzl
Towards #21700.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22025)
=> [render_vtk] New option to choose EGL instead of GLX

bindings/pydrake/common/cpp_template_pybind.h, bindings/pydrake/common/test/cpp_template_pybind_test.cc
Towards #22022.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22037)
=> [pydrake] Add dynamic_attr support to cpp_template_pybind

tools/workspace/vtk_internal/patches/fix_illumination_bugs.patch
The patch stored and restored light matrix values to correct handling multiple shadow-casting lights. However, it did so in a way that advanced the light matrix's modified time out of the expected code path.
This uses a different technique for restoring the light matrix values that doesn't advance the matrix's modified time.
To see the effect run:
```bash
bazel test geometry/render_vtk:internal_render_engine_vtk_test \
--test_filter="*WholeImageCustomParams" --test_output=all
```
At the end of the blob of warnings you'll see:
```bash
Warning: In vtkTransform.cxx, line 180
vtkTransform (0x5b4ba1d22810): InternalUpdate: doing hack to support legacy code.  This is deprecated in VTK 4.2.  May be removed in a future version.
```
This commit removes that message.
- - - …
=> Silence erroneous VTK warning

tools/workspace/new_release.py, tools/workspace/python/venv_upgrade
Modify `venv_upgrade` script, adding a `--commit` option, so that it can also commit the changes made. Modify `new_release` to remind users that the `python` workspace needs to checked manually.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22050)
=> Teach venv_upgrade to commit changes

multibody/contact_solvers/sap/sap_holonomic_constraint.cc, multibody/plant/sap_driver.cc, multibody/plant/test/sap_driver_weld_constraints_test.cc
A separate comits for each fix:
- Fixes math in the computation of the weld constraint Jacobian
- Fixes DEMAND of already moved variables in holonomic constraints
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22057)
=> Bug fixes for holonomic and weld constraints

tools/workspace/coinutils_internal/defs.bzl
Towards #21957.
One example: https://github.com/coin-or/CoinUtils/blob/b6ed55a0/src/CoinFactorization2.cpp#L158-L190.  If you grep for `NDEBUG` in CoinUtils and Clp, there is a lot more.  In Ipopt there is almost nothing, but there are calls to `assert(...)` to we might as well nerf those here, too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22063)
=> [workspace] Force-disable CoinUtils debugging hooks

solvers/BUILD.bazel, solvers/ipopt_solver.cc, solvers/test/ipopt_solver_test.cc
Noticed during #21957.  When we set the linear_solver to "ma27", IPOPT was just ignoring us.
Across the board, our policy for solver options is:
- If a "common solver option" cannot be set, then ignore it.
- If a solver-specific option cannot be set, then that's an error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22062)
=> [solvers] Throw when IpoptSolver options are invalid

solvers/BUILD.bazel, solvers/common_solver_option.h, solvers/specific_options.cc, solvers/specific_options.h, solvers/test/specific_options_test.cc
Towards #21345 (which ports all solvers to use this new sugar) and thus also #20967.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22043)
=> [solvers] Add SpecificOptions sugar for solvers to map their options

multibody/tree/body_node.cc, multibody/tree/body_node.h, multibody/tree/body_node_impl.cc, multibody/tree/body_node_impl.h, multibody/tree/body_node_world.h, multibody/tree/mobilizer_impl.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/planar_mobilizer.cc, multibody/tree/planar_mobilizer.h, multibody/tree/prismatic_mobilizer.cc, multibody/tree/prismatic_mobilizer.h, multibody/tree/quaternion_floating_mobilizer.cc, multibody/tree/quaternion_floating_mobilizer.h, multibody/tree/revolute_mobilizer.cc, multibody/tree/revolute_mobilizer.h, multibody/tree/rpy_ball_mobilizer.cc, multibody/tree/rpy_ball_mobilizer.h, multibody/tree/rpy_floating_mobilizer.cc, multibody/tree/rpy_floating_mobilizer.h, multibody/tree/screw_mobilizer.cc, multibody/tree/screw_mobilizer.h, multibody/tree/test/body_node_test.cc, multibody/tree/universal_mobilizer.cc, multibody/tree/universal_mobilizer.h, multibody/tree/weld_mobilizer.cc, multibody/tree/weld_mobilizer.h
- Removes passed-in context from some calls in favor of passing in positions and velocities. (This is moving in the direction of standardizing the parameter lists so they can be replaced with preloaded structs.)
- Added inlines calc_A_FM() and calc_tau() to all mobilizers and replaces calls to the equivalent virtuals.
- Reimplements the virtuals using the inlines.
- Updates both CalcSpatialAcceleration and CalcInverseDynamics because the latter depends on the former.
- Profiled with valgrind, improved inlining
With gcc, this PR is a 12% speedup of inverse dynamics, 29% since start of this PR sequence begining with #21853. (Likely more gain with clang but I didn't measure it this time.)
- Any algorithmic changes 
- - - …
=> [multibody] Speed up inverse dynamics by exploiting new templatized code

geometry/scene_graph_config.h
Adds missing cross reference and resolves TODO.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22067)
=> Cross references margin documentation in DefaultProximityProperties

bindings/pydrake/BUILD.bazel, bindings/pydrake/test/memory_leak_test.py
Convert the test to unittest format, rewrite the instrumentation, and track the current numbers of leaks, with the goal of reaching 0 once fixes are landed.
As leaks are fixed, the test will complain about allowing more leaks than actually occurred, prompting update or removal of the leaks allowed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22059)
=> [bindings] Update memory leak test

multibody/tree/body_node_impl.cc, multibody/tree/body_node_impl.h, multibody/tree/mobilizer_impl.h, multibody/tree/planar_mobilizer.h, multibody/tree/prismatic_mobilizer.h, multibody/tree/quaternion_floating_mobilizer.cc, multibody/tree/quaternion_floating_mobilizer.h, multibody/tree/revolute_mobilizer.h, multibody/tree/rpy_ball_mobilizer.h, multibody/tree/rpy_floating_mobilizer.h, multibody/tree/screw_mobilizer.h, multibody/tree/universal_mobilizer.h, multibody/tree/weld_mobilizer.h
Previously these MultibodyTree mobilizer-specific type aliases had the "T" built in, so couldn't be used when a different scalar type was required, such as initial values that have to be `double` or in scalar type conversion.
This PR leaves the scalar type templated so most usages change from `QVector blah;` to `QVector<T> blah;`. In addition to being more flexible this looks better in code alongside things like `Vector3<T>`.
These are entirely internal to MbT and have no effect anywhere else.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22072)
=> [multibody] Templatize internal types QVector, VVector, HMatrix

solvers/common_solver_option.cc, solvers/common_solver_option.h, solvers/test/solver_options_test.cc
Deprecate `operator<<`.  I'm using a 6-month window since the deprecations for #22078 might be intrusive, and it's not that costly to keep around the shims a little extra while.
Towards #22078.  Efficient string look-up of common option names is important for that feature.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22079)
=> [solvers] Add CommonSolverOption::to_string

bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/ref_cycle_pybind.cc, bindings/pydrake/common/ref_cycle_pybind.h, bindings/pydrake/common/test/ref_cycle_test.py, bindings/pydrake/common/test/ref_cycle_test_util_py.cc
Introduce the new annotation internal::ref_cycle<M, N>(). It will eventually replace existing cyclic py::keep_alive<>() annotations (which do their job, but leak their participants forever). The participants of ref_cycle<>() will be garbage collectable, so that applications can run loops that use various drake components without exhausting memory.
This patch just adds the implementation and its unit test.
Full WIP at #22022.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22068)
=> [bindings] Add custom ref_cycle annotation

solvers/test/mosek_solver_test.cc, solvers/test/semidefinite_program_examples.cc, solvers/test/semidefinite_program_examples.h
The 2x2 psd matrix is in fact a second order cone constraint, which will not be imposed as a psd constraint in the solvers in the future.
towards #21663
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22071)
=> Remove the 2x2 psd matrix constraint with larger psd matrix.

bindings/pydrake/geometry/BUILD.bazel, bindings/pydrake/visualization/test/multicam_scenario.yaml, common/test_utilities/BUILD.bazel, examples/kuka_iiwa_arm/BUILD.bazel, geometry/benchmarking/BUILD.bazel, geometry/render/render_camera.h, geometry/render_gl/BUILD.bazel, geometry/render_vtk/BUILD.bazel, geometry/render_vtk/factory.h, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/render_engine_vtk_params.cc, geometry/render_vtk/render_engine_vtk_params.h, geometry/render_vtk/test/render_engine_vtk_params_test.cc, systems/sensors/BUILD.bazel, systems/sensors/camera_config.h, tools/bazel.rc, tools/lint/BUILD.bazel, tools/performance/defs.bzl, tools/skylark/README.md, tools/skylark/drake_cc.bzl, tools/skylark/drake_py.bzl, tools/skylark/drake_sh.bzl, tools/skylark/kwargs.bzl
This also fixes RenderEngineGltfClient to not require a DISPLAY.
Closes #21700.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22081)
=> [render_vtk] Use EGL by default on Ubuntu

common/default_scalars.h, geometry/render_gl/internal_render_engine_gl.cc, math/rigid_transform.h, math/rotation_matrix.h, perception/depth_image_to_point_cloud.cc
In slack, a user reported trying to use `RigidTransform<float>` in their own code (inspired by one of these examples) and got a linker error.  This fixes both the bad examples, and now the compiler will also bark about invalid casts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22094)
=> [math] Add requires clause to RigidTransform and RotationMatrix cast

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
Right now the behavior of GraphOfConvexSets is to only use options.preprocessing_solver_options if the user also specifies an options.preprocessing_solver. This PR changes the behavior so these options are used if provided, regardless of whether or not the user specified a solver.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22077)
=> Use the preprocessing solver options even if a specific preprocessing solver is not specified.

solvers/BUILD.bazel, solvers/create_constraint.cc, solvers/create_cost.h, solvers/evaluator_base.cc, solvers/mathematical_program.h, solvers/solver_base.h, solvers/test/clarabel_solver_test.cc, solvers/test/cost_test.cc, solvers/test/create_constraint_test.cc, solvers/test/osqp_solver_test.cc, solvers/test/semidefinite_relaxation_internal_test.cc, solvers/test/snopt_solver_test.cc
+@xuchenhan-tri for both reviews per schedule, please.
FYI @AlexandreAmice @hongkai-dai
Towards #4843 and #20967.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22096)
=> [solvers] Opt-in to clang-format-lint

tools/workspace/vtk_internal/BUILD.bazel, tools/workspace/vtk_internal/data_to_header.py, tools/workspace/vtk_internal/package.BUILD.bazel, tools/workspace/vtk_internal/rules.bzl, tools/workspace/vtk_internal/test/data_to_header_test.cc
The technique we were using to emulate vtkEncodeString.cmake was insufficient for binary files. Up til now, we were only dependent on ascii files and it was fine.
However, when use SSAO we'll be dependent on a texture. That texture doesn't get converted properly. The solution is to initialize the char array as unsigned char with an array of one-byte hex values.
We don't currently depend on it so we have a smoke test in place to confirm correctness.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22092)
=> Correct VTK header generation from binary files

common/fmt_eigen.cc, common/fmt_eigen.h, common/test/fmt_eigen_test.cc, common/test_utilities/eigen_printer.h
+@rpoyner-tri for feature review, please:
* Does this help with #22061?
* Even if not, is this simplification still useful to land anyway?  (It is actually a simplification?)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22095)
=> [common] Simplify fmt_eigen implementation

geometry/proximity/refine_mesh.cc
When the user does 'bazel run :refine_mesh' we should still allow a relative path for input or output. We call chdir here to undo the chdir performed by 'bazel run' into the runfiles tree.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22106)
=> [geometry] Fix refine_mesh for cwd-relative paths

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/BUILD.bazel, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/implicit_graph_of_convex_sets.cc, geometry/optimization/implicit_graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc, geometry/optimization/test/implicit_graph_of_convex_sets_test.cc
Resolves #22033.
Implements a base class defining the Successor() method, and a number of simple tests showing how to create various types of implicit graphs.
+@shaoyuancc for feature review, please.
cc @iamsavva @rhjiang
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22074)
=> [experimental] Implicit Graphs of Convex Sets

bindings/pydrake/systems/test/controllers_test.py
In anticipation of removing the object immortality workaround, add explicit garbage collection to a test that is likely to fail if subsequent fixes don't have adequate object lifetimes.
In the current regime, the objects in question are still immortal, so the test will still succeed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22127)
=> [pydrake] Make controllers test harder to pass

geometry/optimization/hpolyhedron.cc, geometry/optimization/test/hpolyhedron_test.cc
If an HPolyhedron has fewer inequalities than the dimension of the ambient space, it's generally unbounded. The only exception to this case is when a subset of the inequalities are mutually exclusive; then the HPolyhedron is empty, and hence, bounded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22117)
=> Fix Bug Where Infeasible HPolyhedron with Few Constraints is Tagged as Unbounded

bindings/pydrake/BUILD.bazel, bindings/pydrake/common/BUILD.bazel, bindings/pydrake/common/test/ref_cycle_test.py, bindings/pydrake/common/test_utilities/BUILD.bazel, bindings/pydrake/common/test_utilities/memory_test_util.py, bindings/pydrake/test/memory_leak_test.py
Move a quirky, but useful piece of memory test code to infrastructure, so it can be more easily reused.
This is progress toward fine-tuning pydrake object lifetimes, so they neither leak, nor get finalized too early.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22126)
=> [pydrake] Factor out actual_ref_count() for tests

geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/test/graph_of_convex_sets_test.cc
There was a slight logic error, where we were checking the lower bound instead of the upper bound. The current test cases didn't cover it because they didn't make sure that code path was tested. This PR adds test cases to reveal the bug, and implements the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22090)
=> Fix a Bug in GCS When Passing in a Trivially-Infeasible Upper Bound

bindings/pydrake/examples/gym/envs/cart_pole.py, bindings/pydrake/examples/gym/play_cart_pole.py, bindings/pydrake/gym/test/drake_gym_test.py
This involves deferring the import of the non-hermetic dumpster fire known as `matplotlib.pyplot` until it is needed, so that unit tests are not exposed to it.
Closes #21577.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22112)
=> [bindings] Re-enable some gym test cases on macOS

solvers/gurobi_solver.cc
Closes #22107, again.
The bug was introduced subsequent to the most recent release, so we don't need a release note announcing the fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22134)
=> [solvers] Fix Gurobi console logging config to happen first

solvers/aggregate_costs_constraints.cc, solvers/constraint.cc, solvers/constraint.h, solvers/mosek_solver_internal.cc
Since I am going to change each solver (Mosek, SCS, Clarabel) such that they handle the special-case small-size PSD matrix constraint, I move the warning to each solver. So in the future when the specific solver (like MosekSolver) can handle these small-size PSD constraint, I will only remove the warning for that single solver.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22136)
=> Move the warning on small-size PSD matrix to each solver backend.

bindings/pydrake/geometry/geometry_py_common.cc, bindings/pydrake/geometry/test/common_test.py, bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, geometry/BUILD.bazel, geometry/geometry_roles.cc, geometry/geometry_roles.h, geometry/test/geometry_roles_test.cc, multibody/parsing/detail_sdf_geometry.cc, multibody/parsing/detail_sdf_geometry.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/test/detail_sdf_geometry_test.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
1. MultibodyPlant::RegisterVisualGeometry() can now take a GeometryInstance.
- Clean up documentation.
- Extend tests to include what is *actually* done.
2. SDF parser makes use of new API.
- Stop returning optional<unique_ptr<>> (simply return the unique ptr).
- Instead of constructing, deconstructing, and reconstructing geometry instances, we just pass the instance.
Relates #13689
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22102)
=> Update parsing infrastructure

solvers/test/clarabel_solver_test.cc, solvers/test/csdp_solver_test.cc, solvers/test/mosek_solver_test.cc, solvers/test/scs_solver_test.cc, solvers/test/semidefinite_program_examples.cc, solvers/test/semidefinite_program_examples.h
Include psd constraints on 1x1 or 2x2 matrices.
Towards #21663
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22114)
=> Add degenerate examples to SDP test.

bindings/pydrake/geometry/geometry_py_meshes.cc, bindings/pydrake/geometry/test/meshes_test.py, geometry/proximity/mesh_field_linear.h, geometry/proximity/test/mesh_field_linear_test.cc, geometry/proximity/test/volume_mesh_test.cc, geometry/proximity/volume_mesh.cc, geometry/proximity/volume_mesh.h
Towards #21744.
Adds precomputed face normals and edge vectors to `VolumeMesh`.
Adds precomputed Min/Max/Origin pressure values for `MeshFieldLinear` .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22097)
=> [geometry] Add precomputed values to mesh/field types

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/floating_body_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/tree/joint.cc, multibody/tree/joint.h, multibody/tree/mobilizer.cc, multibody/tree/mobilizer.h, multibody/tree/mobilizer_impl.cc, multibody/tree/mobilizer_impl.h, multibody/tree/multibody_tree-inl.h, multibody/tree/multibody_tree.cc, multibody/tree/multibody_tree.h, multibody/tree/multibody_tree_topology.cc, multibody/tree/multibody_tree_topology.h, multibody/tree/prismatic_mobilizer.h, multibody/tree/quaternion_floating_mobilizer.cc, multibody/tree/quaternion_floating_mobilizer.h, multibody/tree/rigid_body.h, multibody/tree/rpy_floating_mobilizer.cc, multibody/tree/rpy_floating_mobilizer.h, multibody/tree/test/mobilizer_tester.h, multibody/tree/test/quaternion_floating_mobilizer_test.cc, multibody/tree/test/rpy_floating_mobilizer_test.cc
Removes MbP's assumption that floating bodies use quaternion floating joints, allowing rpy floating joints instead. The setting can be global or model instance-specific. Weld joints may also be selected (the new topology code already supports these three types). The following MultibodyPlant method is added to convey the desired base-body joint type pre-finalize:
```c++
MultibodyPlant::SetBaseBodyJointType(BaseBodyJointType, optional<ModelInstance>)
```
where BaseBodyJointType is an enum selecting quaternion/rpy floating, or weld (fixed) joint.
The existing `SetFreeBodyRandomRotationDistribution()` methods remain restricted to free bodies that use a QuaternionFloatingJoint because the rotation is expressed as a quaternion. I added
```c++ …
```
=> [multibody] Allow Rpy floating joints for free bodies

bindings/pydrake/perception_py.cc, bindings/pydrake/test/perception_test.py
This fixes the problem reported in [SO #79142422](https://stackoverflow.com/questions/79142422/cannot-use-an-abstractvalue-holding-a-list-of-pointclouds-as-an-abstractport-or).
FYI r2 has a test case that attempts to reproduce the user's problem. They did not provide an actual fully-worked repro, so this is my best guess.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22148)
=> [py perception] Add bindings for PointCloud copy

bindings/pydrake/symbolic/symbolic_py_monolith.cc, bindings/pydrake/symbolic/test/symbolic_test.py, common/symbolic/expression/expression.h, common/symbolic/expression/test/expression_test.cc
We have Expression::GetVariables() and Formula::GetFreeVariables(). In #22091, we could see that this difference (which is mostly unnecessary) made the downstream code unnecessarily clunky. This simple overload resolves it.
+@cohnt for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22145)
=> Add GetFreeVariables() overload to Expression

bindings/pydrake/common/ref_cycle_pybind.cc, bindings/pydrake/common/ref_cycle_pybind.h, bindings/pydrake/common/test/ref_cycle_test.py, bindings/pydrake/common/test/ref_cycle_test_util_py.cc
This patch adds internal::make_arbitrary_ref_cycle(), which will prove useful for awkward bindings like those involving multiple return values.
While in the neighborhood, it also adds a few previously missing tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22146)
=> [pydrake] Add function to make arbitrary ref cycles

bindings/pydrake/solvers/solvers_py_evaluators.cc, bindings/pydrake/solvers/test/evaluators_test.py, solvers/cost.cc, solvers/cost.h, solvers/test/cost_test.cc
Towards #22131 
I tested with and without this change. For updating the coefficient in LinearCost for 1000 times
```
Use UpdateCoefficients: takes 0.130985ms
Use UpdateCoefficientEntry: takes 0.008051ms
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22152)
=> Update single entry of coefficients in LinearCost and QuadraticCost.

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, bindings/pydrake/planning/planning_py_trajectory_optimization.cc, geometry/optimization/BUILD.bazel, geometry/optimization/geodesic_convexity.cc, geometry/optimization/geodesic_convexity.h, geometry/optimization/test/geodesic_convexity_test.cc
Closes #21351. (Although once we have a `parallelism` option added to GCS, as is being discussed in #21965, we should make sure that gets plumbed through.)
Note that the parallelism here is used in two ways -- the computation of AABBs of the constituent sets is handled with a parallel for loop, and then the pairwise intersections themselves are checked with `SolveInParallel`.
This leads to significant speedups, especially on faster graphs. With 224 sets (resulting in 5928 edges), we have the following computation times:
```
Parallel? No AABB Preprocessing? No 	Runtime: 1.174356460571289
Parallel? No AABB Preprocessing? Yes 	Runtime: 1.1098930835723877
Parallel? Yes AABB Preprocessing? No 	Runtime: 0.2572915554046631
Parallel? Yes AABB Preprocessing? Yes 	Runtime: 0.2135148048400879
``` …
=> Parallelize the Pairwise Set Intersection Checking for GCS (with or without Continuous Revolute Joints)

solvers/test/clarabel_solver_test.cc, solvers/test/csdp_solver_test.cc, solvers/test/mosek_solver_test.cc, solvers/test/scs_solver_test.cc, solvers/test/semidefinite_program_examples.cc, solvers/test/semidefinite_program_examples.h
LMI with matrix size 1x1 and 2x2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22143)
=> Add tests for small-size LMI.

geometry/proximity/BUILD.bazel, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/hydroelastic_internal.h, geometry/proximity/test/hydroelastic_internal_test.cc, geometry/proximity/volume_mesh_topology.cc, geometry/proximity/volume_mesh_topology.h, geometry/proximity/volume_to_surface_mesh.cc, geometry/proximity/volume_to_surface_mesh.h
Towards #21744.
This adds a surface mesh, surface mesh bvh, surface element to volume element mapping, and mesh topology to `SoftMesh` and `SoftGeometry`. These data structures are necessary for implementing the improved Compliant-Compliant intersection algorithm described in #21744.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22098)
=> [geometry] Add surface mesh, bvh, mapping and topology to SoftGeometry and SoftMesh

systems/framework/diagram.cc, systems/framework/diagram.h, systems/framework/diagram_builder.cc, systems/framework/diagram_builder.h, systems/framework/test/diagram_test.cc
This patch adds an internal properties interface that allows arbitrary objects to track the lifetime of systems that get transferred from a diagram builder to a diagram.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22132)
=> [systems] Add diagram life support

common/eigen_types.h
This patch avoids linker errors seen with clang 16 through 18 seen on both macos and ubuntu noble. Somehow, without this patch, the compiler emits undefined symbols containing the Drake-only using-statement type `MatrixX`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22172)
=> [common] Work around linker error with clang 16+

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py
Towards #21981. Adds python bindings to the methods introduced in #22091.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22156)
=> Python bindings for methods of GcsTrajectoryOptimization::Subgraph for adding generic costs and constraints.

bindings/pydrake/solvers/BUILD.bazel, bindings/pydrake/solvers/solvers_py.cc, bindings/pydrake/solvers/solvers_py.h, bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/solvers_py_options.cc
Once CI is passing, this is OK to review and merge.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22154)
=> [py solvers] Split options bindings into their own file

multibody/parsing/detail_dmd_parser.cc
First seen on macos with xcode 16.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22175)
=> [parsing] Fix a shadowed variable error in dmd parser

common/BUILD.bazel, common/fmt.cc, common/fmt.h, common/test/fmt_test.cc
---
Sometimes we want to print or log a string.  Imagine this function:
```c++
void DoFoo(const std::string& arg);
```
For logging, we might try:
```c++
void DoFoo(const std::string& arg) {
if (condition) {
drake::log()->warn("Suspicious arg = {}", arg);
}
...
}
```
That would print e.g.
```
WARNING Suspicious arg = Hello, world!
````
However, we'll usually want to print the _quoted_ string value, so that the user can see e.g. if they have training whitespace:
```c++
void DoFoo(const std::string& arg) {
if (condition) {
drake::log()->warn("Suspicious arg = \"{}\"", arg);
}
...
}
```
That would print e.g.
```
WARNING Suspicious arg = "Hello, world!"
````
That's great!  But what if the string itself has double quotes inside of it?  The output would be confusing.  Or, some …
=> [common] Add fmt_debug_string polyfill

tools/skylark/drake_java.bzl, tools/skylark/java.bzl, tools/workspace/java.bzl, tools/workspace/lcm/lcm.bzl, tools/workspace/lcm/package.BUILD.bazel
In Bazel 8, most rules not loaded via a 'load' statement are deprecated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22184)
=> [tools] Add single point of control for rules_java

bindings/pydrake/solvers/solvers_py_semidefinite_relaxation.cc, bindings/pydrake/solvers/test/semidefinite_relaxation_test.py, solvers/semidefinite_relaxation.cc, solvers/semidefinite_relaxation.h, solvers/semidefinite_relaxation_internal.cc, solvers/semidefinite_relaxation_internal.h, solvers/test/semidefinite_relaxation_internal_test.cc, solvers/test/semidefinite_relaxation_test.cc
Addressing #20777 .
As discussed, given a convex quadratic constraint xᵀP x + xᵀq + r <= 0, it is always stronger to add the linearized constraint Tr(PX) + xᵀq + r <= 0 (as is already done for all convex and nonconvex quadratic constraints in `MakeSemidefiniteRelaxation), rendering the original convex quadratic constraints unnecessary. Hence, we want to remove the code that we currently have implemented in Drake that supports keeping these constraints around in their conic form.
Removing the flag `preserve_convex_quadratic_constraints` in the struct `SemidefiniteRelaxationOptions` would be a breaking change, hence I have added the `DRAKE_DEPRECATED` flag to the attribute, and removed all the code where the flag is used so the flag does nothing (mathematically, it already does nothing, but …
=> Deprecate SemidefiniteRelaxationOptions flag `preserve_convex_quadratic_constraints`

math/test/jacobian_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22191)
=> [math] Remove obsolete compiler workaround

tools/skylark/drake_cc.bzl, tools/workspace/metadata.bzl
In Bazel 8, certain skylark API are deprecated:
- Stop using the deprecated to_json method.
- Fix gather_transitive_hdrs to use a provider; using a bare struct is deprecated.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22187)
=> [tools] Fix some skylark deprecations

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py
Towards #21981. Adds python bindings to the methods introduced in #22155.
+@rpoyner-tri for review, please! (This PR only adds bindings, so I've tagged it as single reviewer ok.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22177)
=> Python bindings for methods of GcsTrajectoryOptimization::EdgesBetweenSubgraphs for adding generic costs and constraints.

multibody/mpm/BUILD.bazel, multibody/mpm/spgrid.h, multibody/mpm/test/spgrid_test.cc
Valgrind tests time out with mmap calls that reserve large span of virtual memory. So we add a knob to allow limiting the size of that reservation in unit tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22198)
=> Restore "Implement SpGrid for MPM (#22163)"

multibody/tree/ball_rpy_joint.h, multibody/tree/joint.h, multibody/tree/planar_joint.h, multibody/tree/prismatic_joint.h, multibody/tree/quaternion_floating_joint.h, multibody/tree/revolute_joint.h, multibody/tree/rpy_floating_joint.h, multibody/tree/screw_joint.h, multibody/tree/test/multibody_tree_creation_test.cc, multibody/tree/test/tree_from_mobilizers_test.cc, multibody/tree/universal_joint.h, multibody/tree/weld_joint.h
Using `dynamic_cast` in an inline function is verboten per our style guide.  This commit replaces it with a `static_cast`.  This change is tangentially inspired by #22204.
We could move the existing implementation to the cc file instead, but fixing the cast seems to me like the better approach.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22205)
=> [multibody] Remove dynamic_cast from snake_case inline functions

solvers/common_solver_option.h
This edits the text to improve the uniformity across the various solver options, and emphasizes the "ignore if unknown" which was already documented in `class SolverOptions` but sometimes users don't see that note.
+@hongkai-dai for feature review, please.  Low priority.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22193)
=> [solvers] Clean up common options doc

common/symbolic/decompose.cc, common/symbolic/decompose.h, common/symbolic/test/decompose_test.cc
Use std::vector<symbolic::Variable> instead of Eigen::VectorX<symbolic::Variable> for faster resizing.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22201)
=> Improve ExtractAndAppendVariablesFromExpression.

multibody/plant/BUILD.bazel, multibody/plant/deformable_driver.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/test/compliant_contact_manager_test.cc, multibody/plant/test/discrete_update_manager_test.cc, multibody/plant/test/multibody_plant_test.cc
Closes #22164.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22178)
=> Improve error message when MbP meets unknown geometries

examples/scene_graph/BUILD.bazel, multibody/benchmarks/acrobot/BUILD.bazel, multibody/benchmarks/free_body/BUILD.bazel, tools/lint/bazel_lint.bzl, tools/lint/cpplint.bzl, tools/workspace/gurobi/package-darwin.BUILD.bazel.in, tools/workspace/gurobi/package-linux.BUILD.bazel.in, tools/workspace/mosek/package.BUILD.bazel, tools/workspace/pkg_config.bzl, tools/workspace/vtk_internal/rules.bzl
In Bazel 8, glob lines that don't match anything are an error.  (If we have lines that are _expected_ to sometimes not match anything, then we need to mark that with `allow_empty = True` on the glob call.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22185)
=> [tools] Prepare glob changing default to allow_empty=False

solvers/mosek_solver_internal.cc, solvers/test/clarabel_solver_test.cc, solvers/test/mosek_solver_internal_test.cc, solvers/test/mosek_solver_test.cc, solvers/test/scs_solver_test.cc, solvers/test/semidefinite_program_examples.cc, solvers/test/semidefinite_program_examples.h
When the PSD matrix contains repeated entries, the MosekSolver imposed a wrong constraint. This PR fixes the bug.
resolves #22158
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22173)
=> Fix a bug in MosekSolver with psd matrix containing repeated entries.

geometry/proximity/BUILD.bazel, geometry/proximity/calc_signed_distance_to_surface_mesh.cc, geometry/proximity/calc_signed_distance_to_surface_mesh.h, geometry/proximity/distance_to_point_callback.cc, geometry/proximity/distance_to_point_callback.h, geometry/proximity/mesh_distance_boundary.cc, geometry/proximity/mesh_distance_boundary.h, geometry/proximity/test/calc_signed_distance_to_surface_mesh_test.cc, geometry/proximity/test/characterization_utilities.cc, geometry/proximity/test/characterization_utilities.h, geometry/proximity/test/distance_to_point_callback_test.cc, geometry/proximity/test/distance_to_point_characterize_test.cc, geometry/proximity/test/distance_to_shape_characterize_test.cc, geometry/proximity/test/mesh_distance_boundary_test.cc, geometry/proximity/test/penetration_as_point_pair_characterize_test.cc, geometry/proximity_engine.cc, geometry/query_object.h, geometry/shape_specification.h
Fix #21323.
We need two tasks:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21471)
=> [geometry] ComputeSignedDistanceToPoint from meshes

geometry/render/BUILD.bazel, multibody/parsing/detail_sdf_geometry.cc, multibody/parsing/detail_sdf_geometry.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/parsing_doxygen.h, multibody/parsing/test/detail_sdf_geometry_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, tools/workspace/sdformat_internal/patches/upstream/support_drake_visual.patch, tools/workspace/sdformat_internal/repository.bzl
This introduces a working example of an sdf file.
Closes: #13689
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22013)
=> Introduce sdformat semantics for Drake's visual roles

solvers/aggregate_costs_constraints.cc, solvers/aggregate_costs_constraints.h, solvers/clarabel_solver.cc, solvers/scs_clarabel_common.cc, solvers/scs_clarabel_common.h, solvers/scs_solver.cc, solvers/test/aggregate_costs_constraints_test.cc, solvers/test/clarabel_solver_test.cc, solvers/test/scs_solver_test.cc
A second order cone problem is easier to solve than a positive semidefinite programming problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22219)
=> Scs and Clarabel parses 2x2 PSD/LMI constraints as second order cone constraints.

geometry/render/BUILD.bazel
Amends #22013.
TANSTA `test/configure_visual_roles.sdf`, which is an error in Bazel >= 8.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22236)
=> [render] Hotfix missing glob in "Differentiate visual roles ..."

tools/workspace/rules_python/BUILD.bazel, tools/workspace/rules_python/repository.bzl
Between `8.0.0rc2` and `8.0.0rc3` (and still in `8.0.0rc4`), Bazel has started rejecting our `rules_python` pin with this error:
```console
env USE_BAZEL_VERSION=8.0.0rc3 bazel test //...
Computing main repo mapping: 
...
ERROR: external/rules_python/python/py_cc_link_params_info.bzl:6:84: name 'PyCcLinkParamsProvider' is not defined
ERROR: external/rules_python/python/private/reexports.bzl:37:17: name 'PyInfo' is not defined (did you mean 'CcInfo'?)
ERROR: external/rules_python/python/private/reexports.bzl:40:24: name 'PyRuntimeInfo' is not defined
```
That is fixed in newer releases of rules_python, but we are having trouble upgrading to that (see #22129).
Thus, for bazel 8 we will rely on Bazel's own vendored copy of `@rules_python`.  This means that our version pinning …
=> [workspace] Use built-in rules_python for Bazel >= 8

geometry/optimization/spectrahedron.cc, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/rotation_constraint.cc, solvers/test/clarabel_solver_test.cc, solvers/test/exponential_cone_program_examples.cc, solvers/test/get_program_type_test.cc, solvers/test/mathematical_program_test.cc, solvers/test/semidefinite_program_examples.cc
Instead should use AddLinearMatrixInequalityConstraint() which adds a linear matrix inequality constraint. This avoids adding additional PSD matrix variable and linear equality constraints.
This also changes the return type of some functions, including
- AddPrincipalSubmatrixIsPsdConstraint() returns Binding<LinearMatrixInequalityConstraint> instead of Binding<PositiveSemidefiniteConstraint>
- Spechedron::AddPointInNonnegativeScalingConstraints() returns Binding<LinearMatrixInequalityConstraint> instead of Binding<PositiveSemidefiniteConstraint>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22234)
=> Discourage AddPositiveSemidefiniteConstraint() for a matrix of symbolic::Expression.

geometry/optimization/convex_set.cc, geometry/optimization/geodesic_convexity.cc, geometry/optimization/graph_of_convex_sets.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22228)
=> Add DRAKE_ASSERT statements to ensure programs being solved in parallel are actually threadsafe.

planning/iris/iris_from_clique_cover.cc, planning/iris/test/iris_from_clique_cover_test.cc
We had a bug in how we were selecting the ellipsoid center if the center of the minimum volume circumscribing ellipsoid of a clique was in collision. The center and the A-matrix were flipped. This PR corrects the bug and adds test coverage for it. This issue was brought up in #22233 . 
Thank you @dkreho1 for finding the bug!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22239)
=> Fixes bug in IrisFromCliqueCover edge case

solvers/mosek_solver_internal.cc, solvers/mosek_solver_internal.h
For LMI on a 1x1 matrix, we impose linear inequality constraint. For LMI on a 2x2 matrix, we impose a rotated quadratic constraint (rotated Lorentz cone constraint)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22238)
=> Mosek uses imposes linear or rotated quadratic constraint for small-size LMI constraints.

setup/mac/binary_distribution/Brewfile
Removes the outdated Ruby code associated with the mac temurin installation as it is no longer necessary for successful builds.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22242)
=> Remove outdated code from mac temurin install

multibody/contact_solvers/sap/partial_permutation.cc, multibody/contact_solvers/sap/test/partial_permutation_test.cc
Prevents segfaulting when constructing `PartialPermutation` with an empty `std::vector`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22229)
=> Allow PartialPermutation to accept empty vector

geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/render_engine_vtk_params.h, geometry/render_vtk/test/internal_render_engine_vtk_test.cc, geometry/render_vtk/test/render_engine_vtk_params_test.cc
Adds a new parameter to RenderEngineVtkParams. Rather than waiting for the engine's lighting model to get promoted based on its content, it can be pushed into that mode upon construction.
This also fixes a bug in which cloned instances forgot whether or not phong materials should be automatically promoted to PBR.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22170)
=> RenderEngineVtk can be forced into PBR mode

solvers/mosek_solver.cc, solvers/mosek_solver_internal.cc, solvers/mosek_solver_internal.h, solvers/test/mosek_solver_internal_test.cc, solvers/test/mosek_solver_test.cc, solvers/test/non_convex_optimization_util_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22231)
=> Mosek parse PSD constraint on 2x2 matrices as RotatedLorentzCone.

geometry/optimization/BUILD.bazel, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc
This ended up being pretty simple -- solve all the restrictions in a parallel for loop, and override `options.parallelism` to set the number of threads to one if any not-thread-safe costs or constraints are included in the GCS.
Gonna test this with the various debug builds before I send it up for review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22222)
=> Parallelize the Rounding Stage of GCS

CPPLINT.cfg
When using `--enable_bzlmod=true`, the default runfiles layout is not compatible with how `cpplint` expects things to work.  (In particular, the root of our runfiles is named `_main` instead of `drake` now.)  With some major surgery to our skylark lint rules we could probably get it working, but I don't think this feature is important enough to merit that level of surgery and maintenance.  We have `clang-format-includes` which ensures the self-include statement is always first atop the file, and that seems good enough; forgetting the self-include entirely is not a common failure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22264)
=> [tools] Disable cpplint's build/include checks

math/matrix_util.cc, math/matrix_util.h, math/test/matrix_util_test.cc, solvers/clarabel_solver.cc, solvers/scs_solver.cc
Even considering this specific change in isolation, it is clearly monotonically better.
Bigger picture, C++ streams are _terrible_ and we should be skeptical during platform review of any new uses of them.  Sometimes inside function bodies a temporary local stream is nice, but we should absolutely never use streams in API, nevermind public-stable API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22268)
=> [math] Fix GeneratePythonCsc to eschew C++ streams

BUILD.bazel, __init__.py, bindings/pydrake/BUILD.bazel, bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/visualization/BUILD.bazel, common/proto/call_python_client_notebook.ipynb, lcmtypes/BUILD.bazel, lcmtypes/__init__.py, multibody/parsing/test/package_downloader_test.py, tools/skylark/drake_py.bzl
Towards #20731.  See #21453 for prior art.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22265)
=> [build] Fully retire the non-lcmtypes drake module

math/BUILD.bazel, math/fourth_order_tensor.cc, math/fourth_order_tensor.h, math/test/fourth_order_tensor_test.cc, multibody/fem/BUILD.bazel, multibody/fem/constitutive_model.h, multibody/fem/corotated_model.cc, multibody/fem/corotated_model.h, multibody/fem/linear_constitutive_model.cc, multibody/fem/linear_constitutive_model.h, multibody/fem/linear_corotated_model.cc, multibody/fem/linear_corotated_model.h, multibody/fem/matrix_utilities.cc, multibody/fem/matrix_utilities.h, multibody/fem/test/constitutive_model_test.cc, multibody/fem/test/constitutive_model_test_utilities.cc, multibody/fem/test/matrix_utilities_test.cc, multibody/fem/volumetric_element.h
Make the abstraction for 3x3x3x3 fourth-order tensors and move it from fem::internal namespace to math namespace to prepare it to be used for MPM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22190)
=> Add math::FourthOrderTensor

CPPLINT.cfg, math/matrix_util.h
Amends #22264.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22274)
=> [tools] Add back an accidentally-disabled linter config

doc/doxygen_cxx/doxygen.h, examples/allegro_hand/joint_control/allegro_single_object_simulation.cc, geometry/scene_graph_config.h, geometry/test/scene_graph_test.cc, multibody/plant/BUILD.bazel, multibody/plant/contact_defaults_doxygen.h, multibody/plant/contact_model_doxygen.h, multibody/plant/deformable_driver.cc, multibody/plant/discrete_update_manager.cc, multibody/plant/hydroelastic_parameters_doxygen.h, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_config.h, multibody/plant/test/box_test.cc, multibody/plant/test/deformable_driver_contact_kinematics_test.cc, multibody/plant/test/deformable_driver_contact_test.cc, multibody/plant/test/deformable_integration_test.cc, multibody/plant/test/inclined_plane_test.cc, multibody/plant/test/multibody_plant_hydroelastic_test.cc, systems/sensors/test/rgbd_sensor_async_gl_test.cc
Towards making SAP the default solver, #21294 .
This PR updates the default value of proximity properties used by MbP.
The idea is that a user can create a model without specifying any contact parameters and run a first simulation with a reasonable approximation of rigid contact. For tighter "rigid contact" or furhter compliance, users of course must provide their contact parameters estimations. This workflow and guidelines for estimation are documented in a new module.
Label "release:fix" is related to the fact that these new contact parameters defaults affect the behavior of Drake's simulations.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/21463)
=> Updates MultibodyPlant's default proximity values

tools/workspace/clarabel_cpp_internal/patches/upstream/allow_unused_must_use.patch, tools/workspace/clarabel_cpp_internal/repository.bzl, tools/workspace/rules_rust/repository.bzl, tools/workspace/rust_toolchain/lock/archives.bzl, tools/workspace/rust_toolchain/upgrade.py
Upgrade rules_rust to latest release 0.54.1.
Upgrade rust_toolchain to 1.82.0.
Fix our automated call to buildifier to avoid runfiles confusion.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22272)
=> [workspace] Upgrade rules_rust and rust_toolchain

multibody/tree/rotational_inertia.cc, multibody/tree/rotational_inertia.h, multibody/tree/test/rotational_inertia_test.cc
The epsilon used to test for an invalid inertia differs from the epsilon = 0 used to report an error (in the error message).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22217)
=> Use consistent epsilon values for testing inertia and reporting errors.

bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
It was spelled incorrectly in an impressive number of places, including the public (experimental) API.
fyi @sadraddini
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22280)
=> Fix typo: UnwrapToContinous => UnwrapToContinuous

solvers/ipopt_solver.cc, solvers/ipopt_solver_common.cc, solvers/ipopt_solver_internal.cc, solvers/ipopt_solver_internal.h, solvers/no_ipopt.cc, solvers/test/ipopt_solver_internal_test.cc
Towards #21476.  This will simplify the work of changing which linear solver(s) the build system provides.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22275)
=> [solvers] IpoptSolver doesn't hard-code the linear solver

multibody/plant/test/multibody_plant_test.cc, multibody/tree/multibody_tree_system.cc
This was inspired by a user's trouble report on slack.  The prior message was: `discrete_values.h:201 in get_mutable_vector(): condition '0 <= index && index < num_groups()' failed.`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22283)
=> [multibody] Better message for pre-Finalize CreateDefaultContext

multibody/tree/rotational_inertia.h, multibody/tree/spatial_inertia.cc, multibody/tree/test/spatial_inertia_test.cc
Profiling the M-frame Inverse Dynamics in #22253 I found that a substantial fraction of the time was spent in the computation of the inertial force `SpatialInertia*SpatialAcceleration`. This PR makes some minor changes to the functions involved to make life easier on dumb compilers.
This tiny change speeds up the isolated (kinematics not included) ID-M calculation by 26% when compiled by gcc. It also speeds up the _existing_ isolated ID-W calculation by 10% so is worth checking in separately.  Including kinematics + ID the overall speedup is 7% for k + ID-M and 4% for k + ID-W.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22287)
=> [multibody] Some speedups for inertia * vector

bindings/pydrake/solvers/solvers_py_options.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/BUILD.bazel, solvers/solver_options.cc, solvers/solver_options.h
This simplifies our API surface for users, and makes the implementation of #22078 easier.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22282)
=> [solvers] Reformulate SolverOptions.SetOption to use our variant

geometry/proximity_engine.cc, geometry/test/proximity_engine_test.cc
Fixes #22157.
There are two bugs fixed in this PR:
1. When the GeometryState gets copied, margin does not propagate correctly (context creation). Fix in `CopyFclOjbectOrThrow()`, which gets invoked by `ProximityEngine::Impl`'s copy ctor.
2. If we update an geometry's proximity properties, we must also update the underlying FCL's AABB to propagate margin changes accordingly.
The new unit tests do not pass without these fixes. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22153)
=> Fix bug with hydro geometries in marginal contact

MODULE.bazel, WORKSPACE.bzlmod, tools/workspace/BUILD.bazel, tools/workspace/build_bazel_apple_support/BUILD.bazel, tools/workspace/build_bazel_apple_support/repository.bzl, tools/workspace/default.bzl, tools/workspace/platforms/BUILD.bazel, tools/workspace/platforms/repository.bzl, tools/workspace/rules_rust/BUILD.bazel, tools/workspace/rules_rust/repository.bzl, tools/workspace/workspace_bzlmod_sync_test.py
Towards #20731.  Does not matter to release notes until we can announce reaching 100% on the porting.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22294)
=> [build] All starlark externals are bazel modules

MODULE.bazel, tools/macos.bazelrc, tools/workspace/default.bzl, tools/workspace/workspace_bzlmod_sync_test.py
Hotfix for #22294.  This external is only used on macOS (currently).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22296)
=> [build] Fix missing macOS details in MODULE

multibody/parsing/detail_sdf_parser.cc
ElementPtr::GetElement() adds an element if missing. FindElement() simply returns it. The addition of imaginary elements was causing sdformat to spew errors.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22301)
=> Fix error spew in sdf parsing

doc/_pages/from_source.md, doc/_pages/installation.md, tools/macos.bazelrc
Closes https://github.com/RobotLocomotion/drake/issues/22204.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22227)
=> [setup] Add Xcode 16 specific build configuration

bindings/pydrake/common/test/yaml_typed_test.py, common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_write_archive.cc, common/yaml/yaml_write_archive.h
This isn't quite a comprehensive audit of all things string (with comprehensive test cases), rather just a starting point.  I imagine it makes sense to get this landed first to unblock us, and then later I can circle back and do a more careful study.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22299)
=> [yaml] Fix edge cases in C++ string writing

CMakeLists.txt, MODULE.bazel, WORKSPACE, WORKSPACE.bzlmod, examples/hardware_sim/BUILD.bazel, third_party/com_github_bazelbuild_rules_cc/whole_archive.bzl, tools/bazel.rc, tools/cc_toolchain/BUILD.bazel, tools/dynamic_analysis/BUILD.bazel, tools/install/install.bzl, tools/install/libdrake/header_lint.bzl, tools/skylark/cc.bzl, tools/skylark/drake_cc.bzl, tools/skylark/drake_java.bzl, tools/skylark/drake_sh.bzl, tools/skylark/java.bzl, tools/skylark/py.bzl, tools/skylark/pybind.bzl, tools/skylark/sh.bzl, tools/workspace/BUILD.bazel, tools/workspace/default.bzl, tools/workspace/gfortran/package.BUILD.bazel, tools/workspace/java.bzl, tools/workspace/rules_java/BUILD.bazel, tools/workspace/rules_java/repository.bzl, tools/workspace/rules_shell/BUILD.bazel, tools/workspace/rules_shell/repository.bzl, tools/workspace/vtk_internal/rules.bzl, tools/workspace/workspace_bzlmod_sync_test.py
The autoloading behavior will become deprecated and eventually go away in future bazel versions.  This gets out ahead of the problem by opting-out of the autoloading.  Note that the opt-out in `bazel.rc` is *not* inherited by downstream projects; it is only for Drake.
Loading the specific rules versions also helps make it crystal clear to us which versions of starlark rules we are running.  We definitely do not want to be mixing and matching versions in different places.  With autoloading turned off, we know for sure what we're running, based on either the MODULE or WORKSPACE file (depending on which mode we're using).
- - - …
=> [build] Disable autoloaded (built-in) bazel rules

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/primitives/BUILD.bazel, systems/primitives/sparse_matrix_gain.cc, systems/primitives/sparse_matrix_gain.h, systems/primitives/test/sparse_matrix_gain_test.cc
In service of #20971 (to support using a sparse actuation matrix in controllers). This is a follow-up to a previous failed attempt in of LinearSystem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22314)
=> Adds SparseMatrixGain as a primitive system.

bindings/pydrake/test/memory_leak_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22313)
=> [pydrake] Shorten memory_leak_test to mitigate timeouts

bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py, manipulation/kuka_iiwa/sim_iiwa_driver.cc, systems/controllers/BUILD.bazel, systems/controllers/inverse_dynamics_controller.cc, systems/controllers/inverse_dynamics_controller.h, systems/controllers/test/inverse_dynamics_controller_test.cc
Clarifies that the control output of the inverse dynamics controller
is actuation, not generalized forces, and uses the actuation matrix to
achieve this. Previously, by connecting the output of the
InverseDynamicsController system to an actuation input port of the
MultibodyPlant, we implicitly assumed that the actuator matrix was the
identity matrix. If the actuators were in a different order than the
joints (generalized forces), then our method produced the wrong
actuator inputs.
The generalized_force output port is still available, partly for
backwards compatibility, and because it's possible that there are
applications that prefer this.
This is a rewrite of PR #20971.
+@sherm1 for feature review, please (as the reviewer of #20971)
cc @EricCousineau-TRI who was involved in the first PR. …
=> Fixes up InverseDynamicsController to use the actuation matrix

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/test/parser_test.cc
Currently the Parser uses GetMutableSceneGraphPreFinalize() to access the scene_graph, but per slack, this is not the long-term solution.
Nevertheless, conceptually the Parser _does_ have access to the scene_graph (unless no scene_graph is registered) as well as the plant, so adding this API should be durable even the GetMutableSceneGraphPreFinalize() workflow goes away.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22317)
=> Adds a scene_graph() accessor to multibody::Parser.

bindings/pydrake/common/test/yaml_typed_test.py, bindings/pydrake/common/yaml.py, common/BUILD.bazel, common/memory_file.h, common/test/file_source_test.cc, common/test/memory_file_test.cc, common/yaml/test/example_structs.h, common/yaml/test/json_test.cc, common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_read_archive.cc, common/yaml/yaml_read_archive.h, common/yaml/yaml_write_archive.h
Serializable structs can now have members that are either std::filesystem::path (or pathlib.Path) or drake::FileSource.
The FileSource support is limited. FileSource is a variant containing either a std::filesystem::path or MemoryFile. If it contains a path (its default configuration), serialization is fine. If it contains a MemoryFile it throws. The throwing behavior will be updated later when we've decided what we're going to do about bytestrings and the !!binary yaml tag.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22288)
=> Yaml serialization includes std::filesystem::path and FileSource

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/inverse_kinematics/BUILD.bazel, multibody/inverse_kinematics/add_multibody_plant_constraints.cc, multibody/inverse_kinematics/add_multibody_plant_constraints.h, multibody/inverse_kinematics/test/add_multibody_plant_constraints_test.cc, multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc, multibody/inverse_kinematics/unit_quaternion_constraint.cc, multibody/inverse_kinematics/unit_quaternion_constraint.h, multibody/plant/constraint_specs.h, multibody/plant/test/multibody_plant_test.cc
This method creates a mapping from the constraints used in MultibodyPlant/SAP to the constraints used in MathematicalProgram.
Towards #18917.
+@hongkai-dai for feature review, please (for the mathematical program side).
+@joemasterjohn for additional feature review, please (for the multibody plant side).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22327)
=> Implements AddMultibodyPlantConstraints()

BUILD.bazel, MODULE.bazel, WORKSPACE, WORKSPACE.bzlmod, cmake/WORKSPACE.bzlmod.in, cmake/bazel.rc.in, common/find_runfiles.cc, common/find_runfiles.h, common/find_runfiles_stub.cc, common/test/resource_tool_test.py, common/test_utilities/drake_py_unittest_main.py, tools/bazel.rc, tools/lint/util.py, tools/workspace/BUILD.bazel, tools/workspace/crate_universe/upgrade.sh, tools/workspace/workspace_bzlmod_sync_test.py
Towards #20731.  See the commit message for details.
Given that there are now two "modes" for how Drake declares its externals (workspace vs bzlmod), it's important to consider how we achieve good CI coverage for both.
(1) As of this PR, Bzlmod mode will be tested in our main CI since it is on by default for all first-party Bazel and CMake builds -- pre-merge jobs will run it, as will Continuous, Nightly, Packaging, Wheel, etc.
(2) Workspace mode will only be tested nightly by the [drake_bazel_external_legacy](https://github.com/RobotLocomotion/drake-external-examples/tree/main/drake_bazel_external_legacy) example downstream project.  For PRs with acute risk, we can run that project by hand to check for any failures.  I anticipate this will be good enough, but if we find lots of bugs …
=> [build] Use bzlmod for development and testing

geometry/proximity/test/make_cylinder_mesh_test.cc
Removes unnecessarily fine geometry from `make_cylinder_mesh_test` that is causing timeouts in nightly debug builds (see https://drake-jenkins.csail.mit.edu/job/linux-jammy-gcc-bazel-nightly-everything-debug/302/).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22337)
=> [geometry] Remove ultra-fine resolution testing from cylinder mesh test

multibody/fem/calc_lame_parameters.cc, multibody/fem/calc_lame_parameters.h, multibody/fem/corotated_model.cc, multibody/fem/corotated_model.h, multibody/fem/corotated_model_data.cc, multibody/fem/corotated_model_data.h, multibody/fem/deformable_body_config.h, multibody/fem/linear_constitutive_model.cc, multibody/fem/linear_constitutive_model.h, multibody/fem/linear_constitutive_model_data.cc, multibody/fem/linear_constitutive_model_data.h, multibody/fem/linear_corotated_model.cc, multibody/fem/linear_corotated_model.h, multibody/fem/linear_corotated_model_data.cc, multibody/fem/linear_corotated_model_data.h, multibody/fem/matrix_utilities.cc, multibody/fem/matrix_utilities.h, multibody/mpm/BUILD.bazel, multibody/mpm/particle_data.cc, multibody/mpm/particle_data.h, multibody/mpm/test/particle_data_test.cc
Also extend a few matrix utility functions to support single precision floats.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22286)
=> Add ParticleData for MPM

tools/workspace/gtest/package.BUILD.bazel, tools/workspace/nlopt_internal/package.BUILD.bazel, tools/workspace/spdlog/package.BUILD.bazel
In #22330, I missed a couple more instances of `@//` which didn't show up in drake-external-examples testing but did show up in Anzu.  Now I've grepped the whole tree and fixed all of the stragglers.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22342)
=> [build] Small fixes in prep for bzlmod (part deux)

bindings/pydrake/common/ref_cycle_pybind.h, bindings/pydrake/geometry/BUILD.bazel, bindings/pydrake/geometry/geometry_py_visualizers.cc, bindings/pydrake/geometry/test/visualizers_test.py, bindings/pydrake/manipulation/BUILD.bazel, bindings/pydrake/manipulation/manipulation_py_kuka_iiwa.cc, bindings/pydrake/manipulation/test/kuka_iiwa_test.py, bindings/pydrake/planning/BUILD.bazel, bindings/pydrake/planning/planning_py_robot_diagram.cc, bindings/pydrake/planning/test/robot_diagram_test.py, bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/builder_life_support_pybind.h, bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/builder_life_support_test.py, bindings/pydrake/systems/test/controllers_test.py, bindings/pydrake/systems/test/lifetime_test.py, bindings/pydrake/systems/test/test_util_py.cc, bindings/pydrake/test/memory_leak_test.py
This re-applies 0bbde17e (by reverting the revert 7b5bb38f).
Adjust the original commit by disabling one test under kcov. Somehow kcov spoils reference counting checks for pybind11 objects only.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22343)
=> Re-apply fixed "[pydrake] Fix diagram memory leaks"

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py, systems/controllers/BUILD.bazel, systems/controllers/joint_stiffness_controller.cc, systems/controllers/joint_stiffness_controller.h, systems/controllers/test/joint_stiffness_controller_test.cc
Follows #22315, which implemented the same fix for InverseDynamicsController.
Previously there was a tacit assumption that the actuators were declared in the same order as the joints. This PR resolves that, and (to make this clear) renames the output port from `generalized_force` to `actuation`.
+@sammy-tri for feature review, please?
+@sherm1 for platform review, please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22329)
=> Fixup JointStiffnessController to output actuation instead of generalized_force

systems/analysis/initial_value_problem.cc, systems/analysis/initial_value_problem.h
Scalar-typed variables cannot be globals, since they have non-trivial destructors.
This is a (probably un-noticable) breaking change to the data type of a constant.
---
This was flagged by a new linter I'm working on to find global destructors in libdrake.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22358)
=> [systems] Remove global destructors in initial_value_program

examples/manipulation_station/manipulation_station_hardware_interface.cc
Printing to cout is unsuitable for library code.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22360)
=> [manipulation_station] Use log() instead of cout

setup/mac/binary_distribution/install_prereqs.sh, setup/mac/install_prereqs.sh, setup/mac/source_distribution/install_prereqs.sh, tools/macos-arch-i386.bazelrc
I noticed this during the rewrite of the Ubuntu side in #22055.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22364)
=> [setup] Remove dead code from macOS install_prereqs

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/run_installed_fix_inertia.py, bindings/pydrake/multibody/run_installed_mesh_to_model.py, bindings/pydrake/visualization/BUILD.bazel, bindings/pydrake/visualization/run_installed_meldis.py, bindings/pydrake/visualization/run_installed_model_visualizer.py, tools/workspace/stable_baselines3_internal/BUILD.bazel
Towards #22346 and #20731.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22345)
=> [pydrake] Remove some gratuitous uses of python repo constants

bindings/pydrake/systems/estimators_py.cc, systems/estimators/kalman_filter.cc, systems/estimators/kalman_filter.h, systems/estimators/luenberger_observer.cc, systems/estimators/luenberger_observer.h, systems/estimators/test/kalman_filter_test.cc, systems/estimators/test/luenberger_observer_test.cc
Towards #5842 and #21968.  We must stop passing `unique_ptr` as an argument from Python down to C++... passing `unique_ptr` in an argument of a call from Python into C++ is made possible by Drake-specific hacks to pybind11, and we need to get rid of the hacks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22351)
=> [systems] LuenbergerObserver and KalmanFilter use shared_ptr

bindings/pydrake/multibody/test/inverse_kinematics_test.py, multibody/inverse_kinematics/test/add_multibody_plant_constraints_test.cc, multibody/inverse_kinematics/test/unit_quaternion_constraint_test.cc, multibody/inverse_kinematics/unit_quaternion_constraint.cc, multibody/inverse_kinematics/unit_quaternion_constraint.h
As [discussed](https://drakedevelopers.slack.com/archives/C3L92BM2Q/p1734528939754169) on drake-developers slack.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22373)
=> AddUnitQuaternionConstraintOnPlant also adds quat ∈ [-1,1]

doc/_pages/gallery.md
Hello!
I'm submitting this PR to suggest that [brom_drake](https://github.com/kwesiRutledge/brom_drake-py) be included in the gallery of projects using Drake! We think that Drake is a powerful tool that enables a lot of great experimentation on our end! Our team created a few extra features on top of Drake that we think would be helpful for the broader community including:
- the `DiagramWatcher`,
- the `drakeify_my_urdf` function, and
- the concept of `brom_drake` `Production` objects.
Would you mind including this project in the gallery?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22371)
=> Adding Brom to the list of Third-Party Drake Projects?

multibody/parsing/BUILD.bazel, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_examples_test.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, tools/workspace/mujoco_menagerie_internal/package.BUILD.bazel, tools/workspace/mujoco_menagerie_internal/repository.bzl
Towards #20444
Brings the remaining models from the menagerie under test for the mujoco parser. All of them are permissively licensed (but this requires manual confirmation).
The non-uniform mesh error is being tracked in #22046. My plan is to follow-up immediately with fixes for the other two known errors that are being documented in the expanded test.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22370)
=> Add remaining menagerie models

solvers/BUILD.bazel, solvers/benchmarking/BUILD.bazel, solvers/benchmarking/benchmark_ipopt_solver.cc, solvers/ipopt_solver.h, solvers/ipopt_solver_internal.cc, solvers/solve.cc, solvers/test/ipopt_solver_internal_test.cc, tools/wheel/image/build-dependencies.sh, tools/wheel/image/packages-jammy, tools/workspace/default.bzl
Users can temporarily revert to MUMPS by setting the Ipopt solver option "linear_solver" to "mumps", but that option is deprecated and will be removed on 2025-05-01. Please let us know if you find programs that SPRAL does not handle well.
Note that this only affects Ubuntu.  On macOS, SPRAL is already the sole option.
Closes #21476.
Towards #17231 and #14967.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22385)
=> [solvers] Ipopt uses SPRAL (not MUMPS) by default

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_examples_test.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
Towards #20444.  Related to #22372.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22389)
=> Mujoco parser: improve error message for "size from mesh"

multibody/plant/multibody_plant.h
Resolves #20993. We've decided to document the existing case: the inputs are in joint coordinates, not motor coordinates.
cc @amcastro-tri , @sherm1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22367)
=> Clarify coordinates of MultibodyPlant's actuation input ports

common/test_utilities/diagnostic_policy_test_base.h
e.g. calling `policy.ClearDiagnositics()` then either `TakeWarning()` or `TakeError()` resulted in throwing an out of range exception.
I don't see any local test coverage for these methods, but I think that the two one-line fixes are an obvious improvement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22402)
=> fix: DiagnosticPolicy was going out of range if records were empty

bindings/pydrake/common/test/yaml_typed_test.py, bindings/pydrake/common/yaml.py, common/yaml/test/example_structs.h, common/yaml/test/json_test.cc, common/yaml/test/yaml_read_archive_test.cc, common/yaml/test/yaml_write_archive_test.cc, common/yaml/yaml_node.h, common/yaml/yaml_read_archive.cc, common/yaml/yaml_read_archive.h, common/yaml/yaml_write_archive.cc, common/yaml/yaml_write_archive.h, tools/workspace/yaml_cpp_internal/patches/upstream/b64_decode_failure_is_empty.patch, tools/workspace/yaml_cpp_internal/repository.bzl
Adds the ability for Drake to treat the yaml `!!binary` tag in a consistent and coherent manner.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22318)
=> Drake application yaml logic handles !!binary tag

tools/workspace/gfortran/BUILD.bazel, tools/workspace/gfortran/fortran.bzl, tools/workspace/snopt/package.BUILD.bazel, tools/workspace/snopt/repository.bzl, tools/workspace/spral_internal/package.BUILD.bazel
As with recent work on to centralize C++ and Python toolchains, changes Drake's citations for Fortran targets and macros to use a single point of control.
Towards #20731.  (This will allow downstream code like Anzu to call the `snopt_repository` rule without ever directly depending on `@gfortran`.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22398)
=> [workspace] Factor to single point of control for Fortran

bindings/pydrake/common/serialize_pybind.h, bindings/pydrake/geometry/test/optimization_test.py, bindings/pydrake/planning/test/graph_algorithms_test.py, bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/solvers_py_options.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc, solvers/BUILD.bazel, solvers/mathematical_program.h, solvers/solver_options.cc, solvers/solver_options.h, solvers/specific_options.cc, solvers/specific_options.h, solvers/test/mathematical_program_test.cc, solvers/test/solver_base_test.cc, solvers/test/solver_options_test.cc, solvers/test/specific_options_test.cc
Closes #20967.
The options are now just plain nested dictionaries, no longer hidden behind an API.
The API to set options remains unchanged. (Setting the dictionary values directly is also fine, now.)
The API to get options is all deprecated now.  Users should access the data directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22078)
=> [solvers] SolverOptions is serializable

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_examples_test.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/tree/geometry_spatial_inertia.cc
The InertiaCalculator is not supposed to throw, but could still throw in debug mode based on how it was constructing an intermediate RotationalInertia. Now we skip the intermediate check and properly catch the error to display a helpful message in the parser.
Towards #20444.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22401)
=> [mujoco parser] Fix debug throw from RotationalInertia

multibody/tree/rotational_inertia.cc, multibody/tree/rotational_inertia.h, multibody/tree/test/rotational_inertia_test.cc
This PR is work towards a unified and logical sequence for inertia validity checks.
This PR is specifically for RotationalInertia().  
A subsequent one will follow for SpatialInertia() and its cousin in the Geometry class.
All of the testing for validity is delegated to one function, namely GetInvalidityReport().
It reports an empty string if all seems well, otherwise it returns a string with why the inertia is invalid.
This process will be repeated for each of the three classes (RotationalInertia, SpatialInertia, and its cousin in the Geometry class) and provide a better mechanism for error handling and for ensuring that inertia validity checks provide consistently sensible messages.
- - - …
=> Unify RotationalInertia validity tests and exception messages.

bindings/pydrake/solvers/BUILD.bazel, doc/_pages/stable.md, solvers/BUILD.bazel, solvers/defs.bzl, solvers/test/disabled_solvers_test.cc, tools/BUILD.bazel, tools/bazel.rc, tools/dynamic_analysis/bazel.rc, tools/flags/BUILD.bazel, tools/install/libdrake/BUILD.bazel, tools/skylark/drake_cc.bzl, tools/workspace/BUILD.bazel, tools/workspace/clarabel_cpp_internal/BUILD.bazel, tools/workspace/clp_internal/BUILD.bazel, tools/workspace/csdp_internal/BUILD.bazel, tools/workspace/gurobi/BUILD.bazel, tools/workspace/ipopt_internal/BUILD.bazel, tools/workspace/mosek/BUILD.bazel, tools/workspace/nlopt_internal/BUILD.bazel, tools/workspace/osqp_internal/BUILD.bazel, tools/workspace/scs_internal/BUILD.bazel, tools/workspace/snopt/BUILD.bazel
See https://bazel.build/configure/attributes for background.
This just gets us started with the solvers flags.  More flags are on the way in the future (eigen, fmt, spdlog).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22393)
=> [build] Use modern spelling for Bazel config options

multibody/parsing/test/detail_mujoco_parser_examples_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22416)
=> Mujoco examples skip slow debug only

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/parsing/test/neg_volume.obj
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22414)
=> Mujoco bad inertia test case

tools/workspace/deprecation.bzl
The load statements are not always required due to Bazel's built-in rules, so I guess we never noticed this before.
Amends #20230.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22422)
=> [workspace] Fix typo in deprecation.bzl

bindings/pydrake/geometry/geometry_py_render.cc, bindings/pydrake/geometry/geometry_py_scene_graph.cc, bindings/pydrake/geometry/test/render_engine_subclass_test.py, bindings/pydrake/geometry/test/render_test.py, geometry/geometry_state.cc, geometry/geometry_state.h, geometry/render/render_engine.cc, geometry/render/render_engine.h, geometry/render/test/render_engine_test.cc, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/geometry_state_test.cc, geometry/test/scene_graph_test.cc
Towards #5842 and #21968.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22353)
=> [geometry] Add RenderEngine support for shared_ptr

bindings/pydrake/_trajectories_extra.py, bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/BUILD.bazel, common/trajectories/test/wrapped_trajectory_test.cc, common/trajectories/wrapped_trajectory.cc, common/trajectories/wrapped_trajectory.h
Towards #5842 and #21968.
The situation with `Trajectory` is a bit different that some of our other similar changes to bindings for those issues.  In most other cases, the only trouble comes from `Clone`, but with `Trajectory` we also have an instance factory method `MakeDerivative()` that also needs a solution.  So in this case, we'll use the **decorator** pattern to solve the ownership problem (via `internal::WrappedTrajectory`) instead of trying to deal with `Clone` directly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22399)
=> [py trajectories] Adjust Clone and MakeDerivative for unique_ptr

CTestCustom.cmake.in
Amends #22338.
Closes #21105.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22430)
=> [build] Hotfix CTest regex for MODULE.bazel build output

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
Adds one more entry point to make the most common case cleaner. Mostly this will improve code readability.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22424)
=> Adds MathematicalProgram::AddQuadraticCost w*|x-x_d|^2

cmake/MODULE.bazel.in
The ObjC toolchain must be registered by the main MODULE (which is here, in our CMake builds).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22435)
=> [build] Hotfix macOS CMake builds for MODULE.bazel

CMakeLists.txt, cmake/bazel.rc.in
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22420)
=> [build] Change how CMake details are printed

common/BUILD.bazel, common/cpu_capabilities.cc, common/cpu_capabilities.h, common/hwy_dynamic_impl.h, common/test/cpu_capabilities_test.py, common/test/cpu_capabilities_test_device.cc, doc/doxygen_cxx/doxygen.h
Towards #21850.  This doesn't yet solve the part (3) of cleaning up the build system; I'll do that in a follow-up that only focused on the build.
I didn't run a careful benchmark, but it looks like on my computer for the boxes overlap benchmark, AVX3 is about 10% faster than AVX2.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22423)
=> [common] Enable AVX512 when available

solvers/moby_lcp_solver.cc, solvers/moby_lcp_solver.h, solvers/test/moby_lcp_solver_test.cc
Deprecate its bespoke SetLoggingEnabled.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22359)
=> [solvers] Fix MobyLCPSolver to use Drake logging not cerr

tools/workspace/snopt/repository.bzl
It seems bzlmod mode is better about forwarding gripes from repository rules back to the console than workspace mode was.
```
[6:44:29 PM]  DEBUG: Rule 'drake++drake_dep_repositories+snopt' indicated that a canonical reproducible form can be obtained by dropping arguments ["tag", "branch"]
[6:44:29 PM]  DEBUG: Repository drake++drake_dep_repositories+snopt instantiated at:
[6:44:29 PM]    <builtin>: in <toplevel>
[6:44:29 PM]  Repository rule _snopt_repository defined at:
[6:44:29 PM]    external/drake+/tools/workspace/snopt/repository.bzl:209:36: in <toplevel>
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22431)
=> [build] Silence console spam from the snopt repository rule

CMakeLists.txt, tools/wheel/image/build-drake.sh
When we still used to support Ubuntu 18.04 we couldn't do this (since Bazel didn't use pkg-config there), but today Bazel is always just a veneer over pkg-config (for these three externals (except in wheel builds)) so doesn't add anything useful anymore.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22421)
=> [build] CMake prefers find_package over pkg-config

geometry/optimization/test/vpolytope_test.cc, geometry/optimization/vpolytope.cc, geometry/optimization/vpolytope.h, geometry/shape_specification.cc, geometry/shape_specification.h, geometry/test/shape_specification_test.cc
This PR adds functionality to create Convex Shapes given sets of vertices. It addresses issue #22386.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22390)
=> Add functionality to create Convex shapes from vertices

planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc, solvers/ipopt_solver.cc, solvers/test/ipopt_solver_test.cc, solvers/test/optimization_examples.cc
Previously we set the tolerance to 1.05E-10, this tolerance is too tight and causing numeric problems. We switch back to IPOPT default tolerance.
This is motivated by https://github.com/RobotLocomotion/drake/pull/22361#pullrequestreview-2538121269
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22426)
=> Relax the tolerance in IpoptSolver.

bindings/pydrake/multibody/parsing_py.cc
Towards #22450 and #17520.  Amends #22317.
See [here](https://drake.mit.edu/pydrake/pydrake.multibody.parsing.html#pydrake.multibody.parsing.Parser.scene_graph) for the C++ infection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22451)
=> [py parsing] Fix signatures to use Python types (not C++)

tools/workspace/github.bzl
The native rules are no longer available to us. We must use the Starlark versions from now on.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22443)
=> [build] Fix github local_repository_override for bzlmod

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
The Cassie model in the menagerie sets the default positions of some joints using this element. The default positions define the loop joints. The loop joints were visibly incorrect without this implementation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22446)
=> [mujoco parser] implement "ref" attribute for joints

common/BUILD.bazel, common/test/hwy_dynamic_test.cc, geometry/proximity/BUILD.bazel, geometry/proximity/test/boxes_overlap_test.cc, math/BUILD.bazel, math/fast_pose_composition_functions.cc, math/test/fast_pose_composition_functions_test.cc, tools/workspace/highway_internal/patches/disabled_targets.patch, tools/workspace/highway_internal/repository.bzl
This reduces the risk of accidental ODR violations.
Also tidies up some other highway residue:
- Upgrade the boxes_overlap_test to loop through all targets.
- Finish renaming the pose functions file.
Closes #21850.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22456)
=> [workspace] Disable unwanted highway targets globally

tools/workspace/spdlog/repository.bzl
Amends #22432.
When using bzlmod this line defines the constant:
https://github.com/RobotLocomotion/drake/blob/7e2582fd4b60267ea91aa1cdc5e82b1730a041b1/tools/workspace/spdlog/BUILD.bazel#L54
However, legacy WORKSPACE users don't end up interacting with that line, so it turns out that still need to define it in the repository rule, too.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22465)
=> [build] Hotfix for legacy downstreams that reuse our spdlog

cmake/bazel.rc.in, tools/install/libdrake/BUILD.bazel, tools/wheel/image/build-drake.sh, tools/wheel/macos/build-wheel.sh
Amends #22432.
When using CMake (but not during wheel builds, which link spdlog statically into libdrake), we must preserve the linker flags to find `libspdlog.so.#` and `libfmt.so.#`.  This is tested by [drake_cmake_external](https://github.com/RobotLocomotion/drake-external-examples/tree/main/drake_cmake_external) downstream.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22467)
=> [build] Hotfix for drake_cmake_external

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/test/custom_test.py, bindings/pydrake/systems/test/general_test.py
For the following classes ...
- ContinuousState
- DiscreteValues
- Parameters
... when setting a new value from Python (either in the constructor, or with a set function) the value is now copied instead of aliased.  Having the context keep mutable aliases to objects that the user provided is not only too dangerous in the first place, but also incompatible with forthcoming upstream `pybind11` semantics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22455)
=> [py framework] Setting context values now clones instead of owns

common/trajectories/BUILD.bazel, common/trajectories/piecewise_constant_curvature_trajectory.cc, common/trajectories/piecewise_constant_curvature_trajectory.h, common/trajectories/test/piecewise_constant_curvature_trajectory_test.cc, multibody/tree/BUILD.bazel, multibody/tree/body_node_impl.cc, multibody/tree/body_node_impl_mass_matrix.cc, multibody/tree/curvilinear_joint.cc, multibody/tree/curvilinear_joint.h, multibody/tree/curvilinear_mobilizer.cc, multibody/tree/curvilinear_mobilizer.h, multibody/tree/test/curvilinear_joint_test.cc, multibody/tree/test/curvilinear_mobilizer_test.cc
Adds a `Joint` and corresponding `Mobilizer` which model a single-DoF joint along a path composed of circular arcs and line segments within a plane, implementing part of #22196 
Mobilizer is implemented as a thin wrapper around `PiecewiseConstantCurvatureTrajectory`. If the trajectory is a closed loop, the `Joint` can be flagged as periodic, in which case the mobilized frame can "wrap" around back to the beginning of the trajectory. In this case, the generalized coordinate `q` models the total distance traveled, with an intermediate function `CurvilinearMobilizer::calc_s` remapping to the trajectory's domain with `drake::math::wrap_to`.
The PR is longer than the recommended range of 500-1000 lines. We did not elect to split the PR into two due to the coupled nature of unit testing …
=> [multibody] Add CurvilinearJoint (#22196)

multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc
#22469  clangs-formats some files in `multibody/parsing` by hand. That makes reviewing difficult. 
The entire `multibody/parsing` is marked with `enable_clang_format_lint = False`. While probably a good idea to removew this filter in the future, here I simply limit myself to formating only a subset of files relevant to #22469.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22472)
=> Clang formats some of the files in multibody/parsing

bindings/pydrake/geometry/geometry_py_optimization.cc, bindings/pydrake/geometry/test/optimization_test.py, geometry/optimization/graph_of_convex_sets.cc, geometry/optimization/graph_of_convex_sets.h, geometry/optimization/implicit_graph_of_convex_sets.cc, geometry/optimization/implicit_graph_of_convex_sets.h, geometry/optimization/test/graph_of_convex_sets_test.cc, geometry/optimization/test/implicit_graph_of_convex_sets_test.cc
Resolves #22307.
+@shaoyuancc for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22369)
=> Makes GCS clonable and implements ImplicitGcsFromExplicit

setup/python/pyproject.toml, tools/workspace/python/venv_upgrade
Modify `venv_upgrade` to create a completely separate project to use to pin PDM itself. This avoids any conflation with PDM and its dependencies compared to Drake's dependencies.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22473)
=> Use separate project to manage PDM

bindings/pydrake/systems/lcm_py.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22463)
=> [py lcm] Adjust CreateDefaultValue to avoid unique_ptr

setup/python/pdm.lock, setup/python/pyproject.toml, tools/wheel/image/provision-python.sh, tools/wheel/macos/build-wheel.sh, tools/wheel/wheel_builder/macos.py, tools/workspace/python/repository.bzl
Use Drake's PDM-managed virtual environment (@python), rather than a separate virtual environment, to manage the additional Python bits that are needed to build a wheel. This allows us to pin the versions of these dependencies, for better reproducibility and is one less place where such things are being managed. Having the wheel dependencies installed "up front" is also in line with how Linux wheels are built.
Toward #22042.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22437)
=> Use PDM to manage macOS wheel dependencies

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py, bindings/pydrake/systems/value_producer_pybind.cc, bindings/pydrake/systems/value_producer_pybind.h, systems/framework/leaf_system.h, systems/framework/value_producer.h
(1) Add better error reporting in case the user's function is incorrectly implemented or otherwise misbehaves.
(2) Don't rely on pybind11 to cast the result of allocate() to a unique_ptr (this is an RLG/pybind11-specific feature).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22470)
=> [py systems] Change how ValueProducer callbacks work

systems/framework/system.h
Closes #17649.
+@sherm1 for both reviews, please!
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22479)
=> [systems] Clarify doc that AllocateContext is a trap

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/sensors_py_rgbd.cc, bindings/pydrake/systems/test/sensors_test.py, systems/sensors/BUILD.bazel, systems/sensors/rgbd_sensor_async.cc, systems/sensors/rgbd_sensor_async.h, systems/sensors/test/rgbd_sensor_async_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22427)
=> Parameterize RgbdSensorAsync

planning/dev/BUILD.bazel, planning/dev/test/mbp_environment_collision_checker_test.cc, planning/dev/test/sphere_robot_model_collision_checker_abstract_test_suite.cc, planning/dev/test/sphere_robot_model_collision_checker_abstract_test_suite.h, planning/dev/test/voxelized_environment_collision_checker_test.cc, planning/test_utilities/BUILD.bazel, planning/test_utilities/collision_checker_abstract_test_suite.cc
We should print the type of the checker, not dump its memory buffer.
Amends #21561.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22485)
=> [planning] Fix GetParam-based gtest names

geometry/meshcat.cc, geometry/test/meshcat_test.cc
Previously it failed to find map_* lines which were on the last line of the file (with no trailing newline).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22487)
=> Improve meshcat mtl processing

bindings/pydrake/visualization/_model_visualizer.py
Opening a preview window requires opting-in to use Xorg.
Manually tested with `bazel run //tools:model_visualizer -- package://drake_models/iiwa_description/sdf/iiwa7_with_box_collision.sdf --show_rgbd_sensor`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22492)
=> Fix model_visualizer --show_rgbd_sensor on Ubuntu

bindings/pydrake/geometry/geometry_py_render.cc, bindings/pydrake/pydrake_pybind.h
I am finding more places where we're going to need this technique.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22478)
=> [pydrake] Factor out make_shared_ptr_from_py_object for reuse

bindings/pydrake/planning/planning_py_graph_algorithms.cc, planning/graph_algorithms/max_clique_solver_base.cc, planning/graph_algorithms/max_clique_solver_base.h, planning/graph_algorithms/min_clique_cover_solver_base.cc, planning/graph_algorithms/min_clique_cover_solver_base.h, planning/graph_algorithms/min_clique_cover_solver_via_greedy.cc, planning/graph_algorithms/min_clique_cover_solver_via_greedy.h, planning/graph_algorithms/test/max_clique_solver_via_greedy_test.cc, planning/graph_algorithms/test/max_clique_solver_via_mip_test.cc, planning/graph_algorithms/test/min_clique_cover_solver_via_greedy_test.cc
Amends #21892.  I don't understand why we offered cloning in the first place.  All of the base class methods are const.
Towards #21968.  Specifically, `PYBIND11_OVERRIDE_...(std::unique_ptr<...>, ...)` is no longer an allowed concept (Python cannot return uniquely-owned objects).  There are complicated ways around this, but in this case dropping the feature seems easiest.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22425)
=> [planning] Deprecate MaxCliqueSolverBase::Clone

tools/workspace/pybind11/pybind11-config.cmake
Improves logic so Python3 will not be set by pybind11-config file unless a user has not already set the python version
Resolves [#22051](https://github.com/RobotLocomotion/drake/issues/22051)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22333)
=> Find correct python3 version in pybind11-config

geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_test.cc
They are computing this anyhow, so it is no burden to return them. And it turns out to be useful for my follow-up PR to JointSliders which has to reason explicitly about the rounding happening in the sliders.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22495)
=> Meschat AddSlider and SetSliderValue return rounded/truncated value

bindings/pydrake/multibody/inverse_kinematics_py.cc, multibody/inverse_kinematics/add_multibody_plant_constraints.cc, multibody/inverse_kinematics/add_multibody_plant_constraints.h, multibody/inverse_kinematics/inverse_kinematics.cc, multibody/inverse_kinematics/test/add_multibody_plant_constraints_test.cc
Amends #22327.
(Not breaking Stable API because this function has only be published in 1 release so far.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22502)
=> [inverse_kinematics] Fix plant lifetime in AddMultibodyPlantConstraints

doc/_pages/bazel.md, doc/_pages/developers.md, doc/_pages/documentation_instructions.md, doc/_pages/from_source.md, doc/_pages/installation.md, doc/defs.bzl, doc/pydrake/build.py, setup/install_prereqs, setup/mac/install_prereqs.sh, setup/mac/source_distribution/install_prereqs.sh, setup/ubuntu/install_prereqs.sh, setup/ubuntu/source_distribution/install_prereqs.sh
There is now a single install_prereqs script for all platforms, which defaults to installing only the build prereqs (not developer prereqs). (Future work will further consolidate the implementation of the prereqs into simpler files.)
Retool our from_source (user) and bazel (developer) pages to use the new script and generally rewrite large chunks for improved clarity.
---
There are basically four main flows we focus on now:
(1) Typical users who install from binary (`installation.html`).
(2) Advanced users who need/decide to install from source (`from_source.html`).
(3) Drake developers/contributors (`bazel.html`).
(4) Downstream projects that already use Bazel (the small tail end of `from_source.html`).
The goal here is to make each of those four flows have a particular home in our docs, …
=> [doc] Streamline Drake build instructions

bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/general_test.py, bindings/pydrake/systems/test/scalar_conversion_test.py, systems/framework/diagram.cc, systems/framework/system.h, systems/framework/system_scalar_conversion_doxygen.h, systems/framework/test/diagram_test.cc
When a subsystem in a diagram had an ExternalSystemConstraint attached to it, the constraint wasn't being propagated through scalar conversion.
(I noticed this while testing the forthcoming new Python logic for scalar conversion in #21968.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22490)
=> [framework] Fix diagram scalar conversion losing external constraints

tools/workspace/pybind11/package.BUILD.bazel
If our repository rules patch leaves behind an *.orig file, then the check_lists_consistency would (spuriously) fail. Avoid that by only globbing the files we care about (i.e., headers).
Amends #22450.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22506)
=> [workspace] Tweak glob in pybind11 rules

MODULE.bazel, tools/workspace/metadata.bzl, tools/workspace/metadata.py
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22482)
=> [build] Adjust new_release for bzlmod spellings

lcmtypes/benchmarking/BUILD.bazel, lcmtypes/benchmarking/benchmark.cc, tools/performance/BUILD.bazel
Towards #20761 and therefore towards #17231 and #21868.
The objective here is to have sufficient benchmark coverage that we feel confident switching over the implementation.
Sample output:
```
----------------------------------------------------------------------------------
Benchmark                              Time             CPU    Allocs   Iterations
----------------------------------------------------------------------------------
LcmFixture/ImageArrayEncode         82.9 us         82.9 us     1.375         7994
LcmFixture/ImageArrayDecode         80.1 us         80.1 us    3.4375         8633
LcmFixture/PandaCommandEncode       29.6 ns         29.6 ns      1.25     24645732
LcmFixture/PandaCommandDecode       3.28 ns         3.28 ns    0.3125    216860095 …
```
=> [lcmtypes] Add benchmark

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
Resolves #22462 (and the extensive discussion therein). MuJoCo's ref doesn't change the posture of the model, it says that the posture in the mjcf should be treated not as zero, but as ref.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22497)
=> Fix "ref" attribute handling in mujoco parser

bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/scalar_conversion.py, bindings/pydrake/systems/test/general_test.py, bindings/pydrake/systems/test/scalar_conversion_test.py, systems/framework/BUILD.bazel, systems/framework/diagram.cc, systems/framework/system_base.cc, systems/framework/system_base.h, systems/framework/test/diagram_test.cc, systems/framework/test/wrapped_system_test.cc, systems/framework/wrapped_system.cc, systems/framework/wrapped_system.h, systems/framework/wrapped_system_builder.cc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22491)
=> [py systems] Adjust scalar conversion to avoid unique_ptr

lcmtypes/BUILD.bazel, tools/install/libdrake/drake-config.cmake.in
We'll be happier without the added complexity of twisty include paths.
Using the nested path requires users to run CMake in order to discover the proper include directories.  This was plausible when we had a dozen external dependencies like TinyXML2 and Ipopt and all of that stuff, but now that our exposed dependencies are slim and getting slimmer, the extra path complexity seems like overkill.
Towards #20761 (so #17231).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22521)
=> [build] Move installed lcmtypes into the main Drake library

geometry/render/test/render_mesh_test.cc, tools/workspace/tinyobjloader_internal/patches/upstream/reset_default_kd.patch, tools/workspace/tinyobjloader_internal/repository.bzl
If a material specifies a diffuse map (map_Kd) but doesn't specify a Kd value, it *should* default to white. However, for multiple materials in the file, the parser makes an error. It attempts to track whether the material has specified Kd. But it never resets that record. So, as soon as any material specifies Kd, all subsequent material definitions are classified as *also* having provided one -- even if they haven't. This leads to the correctly reset diffuse color of black being used with diffuse textures (producing black meshes).
This simply resets the `has_kd` flag every time a new material definition starts.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22524 …
=> Correct parsing for multiple materials

geometry/render_gltf_client/test/integration_test.py
Resolves #19305 
Various updates have been made to VTK since these test were disabled. Re-enable render_gltf_client integration tests to see if they now work as intended.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22516)
=> [render_client] Re-enable integration tests on Mac

multibody/mpm/BUILD.bazel, multibody/mpm/grid_data.h, multibody/mpm/particle_sorter.cc, multibody/mpm/particle_sorter.h, multibody/mpm/spgrid.h, multibody/mpm/spgrid_flags.h, multibody/mpm/test/grid_data_test.cc, multibody/mpm/test/particle_sorter_test.cc, multibody/mpm/test/spgrid_test.cc
In addition:
SpGrid reports the flags it uses.
Add the missing set_zero() method for GridData.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22457)
=> [mpm] Add ParticleSorter

tools/release_engineering/dev/README.md, tools/release_engineering/dev/push_release, tools/release_engineering/dev/push_release.py
Issue: #19735 
* Change `_push_deb` in `push_release.py` to copy artifacts directly to the `drake_release` folder in S3, rather than the per-distro subdirectories. The platform name is hyphenated at the end of the filename.
* Change `push_release` to copy the corresponding filename convention.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22471)
=> Rename .deb files to skip per-distro subdirectories in S3

setup/python/pdm.lock, setup/python/pyproject.toml, tools/wheel/image/build-wheel.sh, tools/wheel/image/packages-jammy, tools/wheel/image/provision-python.sh, tools/wheel/macos/build-wheel.sh, tools/workspace/python/repository.bzl, tools/workspace/python/venv_sync
Use the managed virtual environment to provide Python dependencies for Linux wheel builds. This allows Linux wheels to version-pin their dependencies the same way we're already doing for macOS.
This includes several additional changes:
- Modify `venv_sync` to make the virtual environment available in a known location for wheel builds.
- Use `patchelf` from Ubuntu's repositories rather than PyPI. We originally needed a newer version to avoid problems with auditwheel (n.b. https://github.com/pypa/auditwheel/issues/103), but this is no longer necessary.
- When making the virtual environment available to Bazel, symlink the root, not just the `bin` subdirectory. The latter seems to be sufficient on macOS, but not on Linux.
Fixes #22042.
- - - …
=> Use @python to provide Linux wheel dependencies

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/parsing_doxygen.h
Now that MuJoCo has space in `parsing_doxygen.h` where we can list "silently ignored" attributes and elements, this PR goes through and silences those elements that we will never support (and reasonable users would not expected us to support).
This will help cut down a bit on the substantial noise coming out of the parser.
It also adds a few new warnings for new attributes and elements that have managed to spring up in the mujoco documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22493)
=> [Mujoco parser] Silently ignore some attributes/elements.

bindings/pydrake/systems/analysis_py.cc, systems/analysis/monte_carlo.cc, systems/analysis/monte_carlo.h, systems/analysis/test/monte_carlo_test.cc
Deprecate the previous typedef that used unique_ptr.
Adjust pydrake bindings to use the shared_ptr callback, and fix wrong grouping scope for unrelated classes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22528)
=> [analysis] Use shared_ptr for MonteCarlo simulator factory

geometry/render/test/render_mesh_test.cc
This patches the test so it passes for the *right* reason.
Hot fix for #22524 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22541)
=> The test passed erroneously

CMakeLists.txt, MODULE.bazel, cmake/bazel.rc.in, doc/_pages/from_source.md, tools/install/install.bzl, tools/install/libdrake/BUILD.bazel, tools/install/libdrake/drake-config.cmake.in, tools/wheel/image/build-drake.sh, tools/wheel/macos/build-wheel.sh, tools/workspace/README.md, tools/workspace/eigen/BUILD.bazel, tools/workspace/fmt/BUILD.bazel, tools/workspace/spdlog/BUILD.bazel
When installing from an internally vendored eigen, fmt, or spdlog, install their headers alongside Drake's headers and omit them from INTERFACE_LINK_LIBRARIES when Drake is consumed as a CMake external project.
Since #22432 landed, if the user explicitly sets `WITH_USER_...=OFF` when installing Drake, the installed copy would be unusable from C++ (if they didn't have the dep installed system-wide) or ODR-violating (if they did).  This is probably not a big deal since really only Python users should be setting that, but anyway it's fixed now.
Also remove some related cruft in drake-config.cmake when they are user-supplied -- cross-checking the version is not Drake's job, and the config hint is irrelevant since Drake doesn't install config scripts for them when user-supplied.
Amends #22432. …
=> [build] CMake installs eigen,fmt,spdlog when not user-supplied

tools/lcm_gen/__init__.py, tools/lcm_gen/test/functional_test.cc, tools/lcm_gen/test/goal/lima.hpp, tools/lcm_gen/test/goal/mike.hpp, tools/lcm_gen/test/goal/november.hpp
The meaning of 'maxlen' is the number of bytes to read/write, not the overall number of bytes in the buffer.
Towards #20761.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22527)
=> [lcm_gen] Fix bounds checking in legacy API

bindings/pydrake/systems/drawing.py
Protect the drawing import from actually depending on IPython.
The dependency is only there to indicate if we're part of a notebook. If the module is not available, we're definitely not in a notebook.
FIxes #22526
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22546)
=> Hotfix for 22526

tools/lcm_gen/__init__.py, tools/lcm_gen/test/goal/lima.hpp, tools/lcm_gen/test/goal/mike.hpp, tools/lcm_gen/test/goal/november.hpp
As is turns out, the compiler doesn't inline recursive calls to encode or decode, even though the call graph and constexpr branches are known ahead of time. Instead, we'll directly check for the case of copying contiguous memory with a special case.
```
lcm-gen  lcm_gen  lcm_gen
upstream   before    after
ImageArrayEncode     77.9 us   975 us  78.3 us
ImageArrayDecode     80.0 us   979 us  81.3 us
PandaCommandEncode   29.3 ns  21.0 ns  20.9 ns
PandaCommandDecode   3.12 ns  3.08 ns  3.10 ns
PandaStatusEncode    69.2 ns  43.0 ns  34.9 ns
PandaStatusDecode    3.11 ns  3.08 ns  3.10 ns
ViewerDrawEncode     4.97 us  3.42 us  2.53 us
ViewerDrawDecode     3.11 ns  3.22 ns  3.09 ns
```
Note that by default all of our messages still use the lcm-gen (legacy upstream) message generator. This commit …
=> [lcm_gen] Optimize encoding and decoding of arrays

multibody/mpm/test/particle_sorter_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22548)
=> [hotfix] SpGrid reserves smaller memory span in tests

common/trajectories/piecewise_constant_curvature_trajectory.cc, common/trajectories/piecewise_constant_curvature_trajectory.h, common/trajectories/test/piecewise_constant_curvature_trajectory_test.cc, multibody/tree/curvilinear_joint.h, multibody/tree/curvilinear_mobilizer.cc, multibody/tree/curvilinear_mobilizer.h, multibody/tree/mobilizer_impl.h, multibody/tree/test/curvilinear_mobilizer_test.cc
This is a yak shave for the upcoming M-frame inverse dynamics PR (see #22253).
The new Curvilinear mobilizer (and its underlying PiecewiseConstantCurvatureTrajectory) provide velocity, acceleration, and force projection in the "fixed" frame rather than the moving M frame. Additional methods required for M frame support are added here. Incidentally, everything is much nicer in M for this mobilizer.
There was a terminology conflict between the trajectory which used frames A (fixed) and F (moving) and the mobilizer -- all mobilizers use frames F (fixed) and M (moving). I renamed the moving frame in the trajectory to M to avoid the inevitable disaster of using "F" for opposite meanings!
All code here is internal so there is no release note needed.
cc @mshalm
- - - …
=> Adds M-frame methods for curvilinear mobilizer.

bindings/pydrake/math/math_py_monolith.cc, bindings/pydrake/math/test/math_test.py, bindings/pydrake/test/trajectories_test.py, bindings/pydrake/trajectories_py.cc, common/trajectories/bezier_curve.h, common/trajectories/bspline_trajectory.cc, common/trajectories/bspline_trajectory.h, common/trajectories/test/bspline_trajectory_test.cc, math/bspline_basis.cc, math/bspline_basis.h, math/test/bspline_basis_test.cc
For BsplineBasis and BsplineTrajectory.
Towards #22533 which is towards #22500.
+@cohnt for feature review, please?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22535)
=> Implement Bspline "linear in control points" logic

MODULE.bazel, doc/_pages/clion.md, doc/_pages/code_style_tools.md, doc/_pages/emacs.md, doc/_pages/vscode.md, setup/BUILD.bazel, setup/mac/source_distribution/Brewfile-test-only, setup/mac/source_distribution/install_prereqs.sh, setup/ubuntu/source_distribution/packages-jammy-test-only.txt, setup/ubuntu/source_distribution/packages-noble-test-only.txt, tools/lint/BUILD.bazel, tools/lint/clang_format.py, tools/lint/clang_format_lint.py, tools/workspace/default.bzl, tools/workspace/workspace_bzlmod_sync_test.py
Towards #20731 and #21714 and #14967 and #4843.
For now, the clang-format remains pinned to 15 (no change).  In a future PR, I'll aim to upgrade that to the latest and greatest.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22504)
=> [build] Use clang-format from bzlmod

tools/skylark/py_env_runner.py
Modify py_env_runner to export the PYTHONPATH. This is needed to ensure that CPython can find everything the Python interpreter in use can find (particularly when using a virtual environment).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22549)
=> Fix py_env_runner

bindings/pydrake/visualization/_model_visualizer.py
We are currently lucky that this doesn't hurt anything, but best not to tempt fate or provide bad examples to our users.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22550)
=> [py visualization] Avoid writing to const contexts

solvers/cost.cc
As suggested by the camel case, we should always prefer get_as_sparse() when possible.
fyi @hongkai-dai
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22551)
=> prefer get_as_sparse() in L2NormCost

MODULE.bazel, tools/lint/BUILD.bazel, tools/lint/clang_format.py
Apparently only the use_repo_rule form (not the use_extension form) can be inherited by downstream projects.
Amends #22504.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22555)
=> [build] Switch bzlmod clang-format to use_repo_rule

examples/acrobot/run_lqr_w_estimator.cc, systems/estimators/kalman_filter.h, systems/estimators/test/kalman_filter_test.cc
Follow-up from #22351.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22563)
=> [estimators] Deprecate one overload of SteadyStateKalmanFilter

doc/_pages/clion.md
The instructions for setting up clang-format External Tools in CLion didn't work when I tried them today in CLion 2024.3.2. The commands were unable to find the file name to be processed. Changing from FileName to FilePath fixes the problem.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22559)
=> fix clion external tool instructions

CMakeLists.txt, setup/mac/binary_distribution/Brewfile, setup/mac/source_distribution/Brewfile
When making a `*.tar.gz` binary release, don't use Homebrew for C++ dependencies (eigen, fmt, spdlog), because it offers absolutely no version stability.
Instead, our packages incorporate fmt and spdlog inside libdrake.so and install the eigen,fmt,spdlog headers alongside Drake's headers.
Also demote pkg-config to source_distribution; it hasn't been needed in binary_distribution since 78eaea83.
Closes #21714.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22519)
=> [build] macOS binary packages no longer use brew eigen/fmt/spdlog

cmake/external/workspace/eigen/BUILD.bazel.in, cmake/external/workspace/eigen/MODULE.bazel.in, cmake/external/workspace/fmt/BUILD.bazel.in, cmake/external/workspace/fmt/MODULE.bazel.in, cmake/external/workspace/spdlog/BUILD.bazel.in, cmake/external/workspace/spdlog/MODULE.bazel.in, tools/workspace/eigen/BUILD.bazel, tools/workspace/fmt/BUILD.bazel, tools/workspace/spdlog/BUILD.bazel
As of #22520, I should have realized that we now can drop the install-a-dummy-license-file boilerplate, since we know for certain whether the dependency is external or internal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22569)
=> [build] Remove unnecessary install boilerplate

tools/install/libdrake/BUILD.bazel, tools/install/libdrake/cc_defines.bzl, tools/install/libdrake/drake-config.cmake.in
Amends #22519.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22573)
=> [build] Fix CMake interface definitions for bundled eigen/fmt/spdlog

common/trajectories/piecewise_constant_curvature_trajectory.cc, common/trajectories/piecewise_constant_curvature_trajectory.h, common/trajectories/test/piecewise_constant_curvature_trajectory_test.cc, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/sdf_parser_test/joint_parsing_test.sdf, multibody/parsing/test/urdf_parser_test/joint_parsing_test.urdf, multibody/tree/curvilinear_joint.h, multibody/tree/test/curvilinear_mobilizer_test.cc
Adds tags and joint configuration structure to URDF and SDF parsers for CurvilinearJoint, completing implementation of #22196.
Implements new `drake:` namespace XML tags to handle description of line segment and curve shapes. Format prioritizes human readability without knowledge of the particular API for the internal PiecewiseConstantCurvatureTrajectory -- for instance expressing the curves with a radius and clockwise/counterclockwise direction rather than a `turning_rate`. A sample URDF specification is provided below.
```
<drake:joint name="curvilinear_periodic" type="curvilinear">
<origin xyz="3 2 1" rpy="0 0 0"/>
<parent link="link12"/>
<child link="link13"/>
<drake:initial_curve_tangent xyz="0 0 1"/>
<drake:plane_normal xyz="1 0 0"/>
<drake:is_periodic value="true"/>
<dynamics …
```
=> [multibody] Add URDF and SDF Parsing for Curvilinear Joints (#22196)

tools/workspace/default.bzl, tools/workspace/spgrid_internal/repository.bzl
When consumed in a downstream workspace, new_local_repository does not work correctly with a relative path.
I've manually tested that both DEE `drake_bazel_external{,_legacy}` pass with this change.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22561)
=> [build] Fix spgrid_internal compatibility with bzlmod

multibody/inverse_kinematics/add_multibody_plant_constraints.cc, multibody/inverse_kinematics/test/add_multibody_plant_constraints_test.cc
Also fix missing initial guess for locked non-quaternion dofs.
Closes #22543.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22578)
=> [ik] Allow non-world floating joints without crashing

multibody/meshcat/joint_sliders.cc, multibody/meshcat/joint_sliders.h
The plant guarantees that all positions are covered by exactly one joint. We no longer need to use a map from position to slider, or deal with non-slider default values.
Towards #22496.
+@RussTedrake for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22553)
=> [meshcat] Simplify JointSliders now that all positions have joints

tools/flags/BUILD.bazel
Amends #22432.
While working with this flag in WIP branches lately, I'm not sure we should keep this option.  I anticipate adding a new "how should logging behave" flag, separate from this one which is more about choosing a version.  This would become Stable API in the next release, so we should mark it experimental for now.
+@xuchenhan-tri for both reviews (Monday), please.  No rush.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22577)
=> [build] Document the new "spdlog disabled" flag as experimental

bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/general_test.py, systems/analysis/simulator.cc, systems/analysis/simulator.h, systems/analysis/test/simulator_test.cc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22511)
=> [analysis] Avoid unique_ptr in simulator context bindings

planning/trajectory_optimization/kinematic_trajectory_optimization.cc, planning/trajectory_optimization/kinematic_trajectory_optimization.h, planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Resolves #22533.
This includes a small breaking change. The vector<vector<Binding>> return types for KinematicTrajectoryOptimization AddAccelerationBounds and AddJerkBounds are now vector<Bindings>.
+@cohnt for feature review, please?  This cleaning things up significantly, imo.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22552)
=> Convert kintrajopt to use AsLinearInControlPoints

common/memory_file.h, geometry/rgba.h
1. MemoryFile's documentation choked doxygen. There was no documentation rendered for Serialize(). The minimum fix led to really ugly layout. (Code block immediately followed indented block.) So, we shuffled the rhetoric so the layout looked better.
2. Rgba suffered from a similar layout problem. Furthermore, it wasn't clear that it had particularly weird yaml semantics. The documentation has been extended to help that become clearer.
closes #22582
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22584)
=> Tweak some yaml serialization documentation

setup/ubuntu/install_prereqs.sh, setup/ubuntu/source_distribution/install_prereqs_user_environment.sh
This follows from #22461. When installing `--without-bazel`, we need to skip a step in `install_prereqs_user_environment` which does a prefetch of the bazelisk download of bazel.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22575)
=> Skip Bazel prefetch in prerequisite installation

doc/_pages/troubleshooting.md, examples/hardware_sim/test/hardware_sim_test_common.py, lcm/drake_lcm.h
Addresses #22322 and re-enables the unit test that was failing. See [here](https://github.com/RobotLocomotion/drake/issues/22322#issuecomment-2619688764) for a description of the network config fix.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22572)
=> Re-enable hardware_sim test on macOS Sequoia and add documentation

bindings/pydrake/planning/BUILD.bazel, bindings/pydrake/planning/planning_py_trajectory_optimization.cc, bindings/pydrake/planning/test/trajectory_optimization_test.py, planning/trajectory_optimization/BUILD.bazel, planning/trajectory_optimization/kinematic_trajectory_optimization.cc, planning/trajectory_optimization/kinematic_trajectory_optimization.h, planning/trajectory_optimization/test/kinematic_trajectory_optimization_test.cc
Resolves https://github.com/RobotLocomotion/drake/issues/22500.
Note: I've included PR #22552 as the first commit here; the request is only to review the second commit.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22579)
=> Effort limits for Kinematic Trajectory Optimization 

geometry/kinematics_vector.cc, geometry/kinematics_vector.h, geometry/scene_graph.cc, geometry/test/kinematics_vector_test.cc, geometry/test/scene_graph_test.cc
The various kinematics vectors (pose and deformable configuration) can now detect if they have been populated with any NaN values.
SceneGraph uses that functionality to detect if it's input has NaN values and throw exceptions attributing NaN to the appropriate input port.
Relates #22586.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22592)
=> SceneGraph protects itself from non-finite values on its inputs

setup/mac/binary_distribution/install_prereqs.sh
Modify how we set up the virtual environment for macOS installs to keep PDM in a separate environment. This avoids PDM modifying its own environment (which appears to have possible race conditions).
Amends #22477.
Closes #22040.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22607)
=> Use separate venv for installation PDM

doc/doxygen_cxx/build.py
Addresses #18554. Doxygen generates `*.md5` and `*.map` files as part of its build process which can be used to speed up build regeneration. Currently, these are ignored and excluded from the [website publication in CI](https://github.com/RobotLocomotion/drake-ci/blob/70e4326ab22049db3ae5ac16ad59c9f48bcd5b9d/tools/publish_documentation.bash#L40). This PR moves this logic to `drake/doc` by inserting a post-build removal step. (Unfortunately, Doxygen doesn't provide any command-line option to never generate these files in the first place). 
Tested locally with the following cases. The website preview remains unchanged, and the files are removed from either the output or temp directory:
* `bazel run //doc:build -- --serve`
* `bazel run //doc:build -- --out_dir=...`
* `bazel run …
=> [doc] Cleanup extraneous Doxygen files

MODULE.bazel
This is a work-around until we upgrade past https://github.com/bazel-contrib/toolchains_llvm/pull/458.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22612)
=> [build] Add missing clang-format for linux-aarch64

planning/trajectory_optimization/gcs_trajectory_optimization.cc, planning/trajectory_optimization/gcs_trajectory_optimization.h, planning/trajectory_optimization/test/gcs_trajectory_optimization_test.cc
These two joints internally have revolute components, so if there are no limits, we include them in the "continuous revolute joints" framework.
Not sure if changing the return values technically counts as a breaking change, but `GcsTrajectoryOptimization` is tagged as `@experimental`, so we're fine either way.
This removes the TODO introduced in #21861
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22585)
=> Make GetContinuousRevoluteJointIndices Include UniversalJoint and BallRpyJoint

multibody/parsing/detail_dmd_parser.cc, multibody/parsing/detail_path_utils.cc, multibody/parsing/detail_path_utils.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/package_map.cc, multibody/parsing/parser.cc, multibody/parsing/process_model_directives.cc, multibody/parsing/test/detail_path_utils_test.cc
This is in anticipation of adding speculative meshes to SceneGraph (#22510).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22600)
=> [parsing] Enhance ResolveUri to return non-existent paths

multibody/plant/test/sap_driver_multidof_joints_test.cc, multibody/tree/ball_rpy_joint.cc, multibody/tree/ball_rpy_joint.h, multibody/tree/curvilinear_joint.cc, multibody/tree/curvilinear_joint.h, multibody/tree/joint.h, multibody/tree/multibody_tree.cc, multibody/tree/planar_joint.cc, multibody/tree/planar_joint.h, multibody/tree/prismatic_joint.h, multibody/tree/quaternion_floating_joint.cc, multibody/tree/quaternion_floating_joint.h, multibody/tree/revolute_joint.cc, multibody/tree/revolute_joint.h, multibody/tree/rpy_floating_joint.cc, multibody/tree/rpy_floating_joint.h, multibody/tree/screw_joint.cc, multibody/tree/screw_joint.h, multibody/tree/universal_joint.cc, multibody/tree/universal_joint.h, multibody/tree/weld_joint.cc, multibody/tree/weld_joint.h
MultibodyPlant's Joint implementation code has an unneeded intermediate "Blueprint" class. This PR nukes that to somewhat simplify MbP's baroque construction of a Joint's internal implementation. This is a yak shave for some upcoming changes to joint modeling.
All changes are internal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22608)
=> [multibody] Eliminate unneeded BluePrint class

planning/iris/iris_zo.cc, planning/iris/iris_zo.h, planning/iris/test/iris_zo_test.cc
Ordinarily, IRIS-ZO grows collision free regions in the robot's configuration space $\mathcal C$. This allows the user to specify a function $f:\mathcal Q\to\mathcal C$, and grow the region in $\mathcal Q$ instead. This has the following use cases:
- Supporting mimic joints (@sadraddini enjoy)
- [Growing regions in tangent-configuration space](https://journals.sagepub.com/doi/full/10.1177/02783649231201437) ([so that trajectories can be certified](https://ieeexplore.ieee.org/abstract/document/10611296))
- [Growing regions along the manifold of constraint-satisfying configurations for bimanual manipulation](https://ieeexplore.ieee.org/abstract/document/10610675) (although this still requires support for additional arbitrary user-specified constraints)
@wernerpe: I've currently implemented …
=> Growing IRIS-ZO Regions Along a Parametrized Subspace

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
MultibodyPlant::SetFoo(context, vector): when writing user-provided configuration values (qs and vs) into the context, we throw if the input has NaNs.
Includes the following APIs:
- SetPositions() - 3 overloads
- SetPositionsAndVelocities() - 2 overloads
- SetDefaultPositions() - 2 overloads
- SetVelocities() - 3 overloads
- SetVelocitiesInArray()
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22594)
=> MultibodyPlant hinders writing user non-finite values to context

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/primitives/linear_system.cc, systems/primitives/linear_system.h, systems/primitives/test/linear_system_test.cc
Added functionality for converting continuous-time LinearSystem and AffineSystem to discrete-time zero-order hold equivalents.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22601)
=> Implement continuous- to discrete-time conversion for linear systems

planning/collision_checker.cc, planning/collision_checker.h, planning/distance_and_interpolation_provider.cc, planning/distance_and_interpolation_provider.h, planning/test/collision_checker_test.cc, planning/test/distance_and_interpolation_provider_test.cc
When users provide the configuration vector, we immediately test for NaNs.
Some context-variants of the public APIs are implicitly tested (as they were in the tests before this change).
Furthermore, the API CheckConfigsCollisionFree() wasn't tested before and still isn't tested.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22593)
=> Collision checker protects itself from user-provided NaN

tools/workspace/README.md, tools/workspace/bazelisk/repository.bzl
Towards #22087
When performing upgrades using the semi-automated script, most externals only require the standard pre-merge jobs to test. In the case of bazelisk, however, an unprovisioned Linux job should also be run. Add a reminder to the documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22171)
=> Clarify upgrade advice for bazelisk

multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/test/detail_mujoco_parser_test.cc
This adds immediate support for defaults in actuators and contact pairs and makes it easier to support defaults for future parsing features.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22625)
=> Generalize mujoco defaults parsing

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/scoped_names.cc, multibody/parsing/scoped_names.h, multibody/parsing/test/scoped_names_test.cc, multibody/plant/multibody_plant.h
Closes #22590
Also fix related docs markup (closes #22622).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22644)
=> [multibody] Add GetScopedFrameByName overloads on scalar type

bindings/pydrake/multibody/parsing_py.cc, bindings/pydrake/multibody/test/parsing_test.py, multibody/parsing/BUILD.bazel, multibody/parsing/detail_composite_parse.cc, multibody/parsing/detail_dmd_parser.cc, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/detail_parsing_workspace.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/parser.cc, multibody/parsing/parser.h, multibody/parsing/parsing_doxygen.h, multibody/parsing/test/detail_dmd_parser_test.cc, multibody/parsing/test/detail_make_model_name_test.cc, multibody/parsing/test/detail_mesh_parser_test.cc, multibody/parsing/test/detail_mujoco_parser_examples_test.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_select_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc, multibody/parsing/test/detail_usd_parser_test.cc, multibody/parsing/test/parser_test.cc
Generalizes Parser() to take a DiagramBuilder, and uses this in the mujoco parser to add an RgbdSensor.
@jwnimmer-tri , @rpoyner-tri -- here is one concrete proposal on how we can parse ≫ MultibodyPlant from mujoco.  It was cleaner than I thought it might be... it means multibody/parsing gets new dependencies on systems/sensors , but multibody already depends on systems (the order is reasonable). 
The alternative I had considered was having two parsing entry points, one for multibodyplant related elements, and the other for diagram-related elements. But I do think this is better.
WDYT?  Should I continue and clean it up?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/dr …
=> Parse cameras from mujoco

geometry/proximity/hydroelastic_internal.cc, geometry/proximity/make_box_mesh.cc, geometry/proximity/make_box_mesh.h, geometry/proximity/test/hydroelastic_internal_test.cc, geometry/proximity/test/make_box_mesh_test.cc, multibody/plant/test/deformable_integration_test.cc
Closes #22213.
As discussed in #22213, our hydro boxes customized to discretize the MA with a minimum number of tetrahedra do not play well with discrete schemes.
The solution proposed in #22213 is a custom box mesh that respects the MA, uses a coarse discretization of the box, but that it splits each face into four triangles for a more symmetric tesselation that more accurate predicts restoring moments in the discrete case.
**Note:**
I tried to reuse the already existing implementation. The current implementation is highly customized for the case of splitting each face into two triangles, and even though I could modify the code to do what I wanted, the solution ended up being a collection of hacks piled on top of each other. Even if we liked it, it'd be very hard to explain and document. …
=> Implements hydro box mesh with faces split into four triangles

doc/_pages/credits.md, systems/controllers/finite_horizon_linear_quadratic_regulator.cc, systems/controllers/finite_horizon_linear_quadratic_regulator.h, systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc
In the implementation, calling `FiniteHorizonLinearQuadraticRegulator(system, contex, t0, tf, Q, R, options)` will invoke discrete-time finite-horizon LQR if
1. `system` is a difference equation system, or
2. `system` is continuous and `options.x0`/`options.u0` is of type `DiscreteTimeTrajectory`. 
The second case is useful when we have a trajectory for a continuous-time system, e.g., cart-pole swing-up, but we want to track the (sampled) trajectory using a discrete-time controller.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22609)
=> Implement discrete-time finite-horizon LQR

multibody/tree/rotational_inertia.cc, multibody/tree/rotational_inertia.h, multibody/tree/test/rotational_inertia_test.cc
Check moments/products of inertia with IsFinite() instead of IsNan() and add missing test of infinity -- which somehow used to pass IsPhysicallyValid().  This is work towards issue #22651.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22642)
=> Check RotationalInertia moments/products with IsFinite() instead of IsNaN(). 

geometry/render_vtk/test/internal_render_engine_vtk_test.cc, tools/workspace/vtk_internal/patches/preserve_direct_light_specular_reflections.patch, tools/workspace/vtk_internal/repository.bzl
This tweaks the mathematical model so that perfect reflections of our direct lighting don't dwindle away to nothing (counter to how they would behave in the real world).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22632)
=> Preserve direct light specular reflections for smooth materials

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, manipulation/schunk_wsg/schunk_wsg_plain_controller.cc, systems/primitives/BUILD.bazel, systems/primitives/selector.cc, systems/primitives/selector.h, systems/primitives/selector_internal.h, systems/primitives/test/selector_test.cc, tools/workspace/pybind11/mkdoc_comment.py
**Is your feature request related to a problem? Please describe.**
When wiring up all of the various MultibodyPlant input and output ports to controllers, it's often the case that we need to multiplex and/or split up the data on those ports.  Sometimes we need to stack per-model q, v, or x together (e.g., arm model + gripper model), sometimes we need to slice out actuated dofs from unactuated dofs, sometimes we need to interleave q with v, sometimes we need to switch between velocity-based indexing and actuator-based indexing, or any number of other permutations.
Each time this comes up, of course it's possible to write a custom LeafSystem to do the exact rearrangement that's needed, or put lots of Multiplexer and Demultiplexer systems in series, or use a SparseMatrixGain to formulate the …
=> [primitives] Add Selector primitive system

multibody/parsing/parsing_doxygen.h
Adds Doxygen documentation for URDF/SDF parsing for curvilinear joints. Parsing logic was previously commited as part of #22469 .
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22591)
=> Add CurvilinearJoint URDF/SDF parsing documentation (#22196)

multibody/parsing/detail_mujoco_parser.cc, multibody/tree/geometry_spatial_inertia.cc, multibody/tree/spatial_inertia.cc, multibody/tree/spatial_inertia.h, multibody/tree/test/spatial_inertia_test.cc
Unifies SpatialInertia tests and error messages for mass, center of mass, and inertia properties.  Code is consolidated (reduced) and inconsistent detection and message construction are fixed.  The public SpatialInertia method CriticizeNotPhysicallyValid() was deprecated in favor of the new internal-use only function CreateInvalidityReport().
Resolves #22017, resolves #22651.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22474)
=> Unify validity tests and messages for SpatialInertia class.

geometry/render_vtk/render_engine_vtk_params.h, systems/sensors/camera_config.h
Tweak the documentation to make the requirements for `show_rgb` to actually work clearer.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22667)
=> Clarify render engine backed and show_rgb

multibody/parsing/detail_mesh_parser.cc, multibody/parsing/test/detail_mesh_parser_test.cc, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h
Previously, a proximity property with zero friction is hardcoded, and it prevents the default proximity property being backfilled.
Downstream symptom was observed here: https://drakedevelopers.slack.com/archives/C2WBPQDB7/p1739978811296609
In addition, nuke the necessary check in MbP::RegisterCollisionGeometry and fix a typo in its documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22674)
=> [parsing] Parsed mesh geometries use default proximity props

multibody/tree/fixed_offset_frame.cc, multibody/tree/fixed_offset_frame.h, multibody/tree/test/frames_test.cc
Makes ShallowClone() and CloneToScalar() preserve the model instance for a FixedOffsetFrame.
Also corrects a class comment for FixedOffsetFrame (model instance has always been inherited from the parent frame's model instance, not the parent frame's _body's_ model instance)
Adds missing test cases in frames_test.cc.
Resolves #22695
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22696)
=> [multibody] Fix and unit test Clone functions for Frames

tools/workspace/spral_internal/package.BUILD.bazel, tools/workspace/spral_internal/repository.bzl
Towards: #22666
Edit: Once approved, this should be squash-and-merged (not curated).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22693)
=> [workspace] Upgrade spral_internal to latest release v2025.03.03

bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, systems/framework/vector_system.h, systems/primitives/BUILD.bazel, systems/primitives/integrator.cc, systems/primitives/integrator.h, systems/primitives/test/integrator_test.cc
Adds a constructor and setter to the Integrator primitive that allows specification of a non-zero (but numerical) initial value.
Also adds missing tests and cleans up some error handling.
Resolves #22673
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22682)
=> [primitives] Allow an initial value to be specified for Integrator

multibody/plant/BUILD.bazel, multibody/plant/desired_state_input.cc, multibody/plant/desired_state_input.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/test/actuated_models_test.cc, multibody/plant/test/sap_driver_pd_controller_constraints_test.cc, multibody/tree/joint_actuator.h
Closes #22444.
Per discussion in #22444, we allow the desired state input ports for a model instance to be disconneted. This "disarms" PD control for such model instance, meaning that this controller won't have any effect on the dynamics.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22542)
=> Desired state input ports are no longer required to be connected

multibody/mpm/BUILD.bazel, multibody/mpm/grid_data.h, multibody/mpm/mass_and_momentum.h, multibody/mpm/sparse_grid.cc, multibody/mpm/sparse_grid.h, multibody/mpm/spgrid.h, multibody/mpm/test/grid_data_test.cc, multibody/mpm/test/particle_sorter_test.cc, multibody/mpm/test/sparse_grid_test.cc
In addition:
- Fix a couple of stale documentation in SpGrid
- Add a sugar for GridState.
- Add MassAndMomentum struct.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22540)
=> [mpm] Add SparseGrid

multibody/tree/mobilizer.cc, multibody/tree/mobilizer.h, multibody/tree/planar_mobilizer.cc, multibody/tree/planar_mobilizer.h, multibody/tree/prismatic_mobilizer.cc, multibody/tree/prismatic_mobilizer.h, multibody/tree/revolute_mobilizer.cc, multibody/tree/revolute_mobilizer.h, multibody/tree/screw_mobilizer.cc, multibody/tree/screw_mobilizer.h, multibody/tree/test/planar_mobilizer_test.cc, multibody/tree/test/prismatic_mobilizer_test.cc, multibody/tree/test/revolute_mobilizer_test.cc, multibody/tree/test/screw_mobilizer_test.cc, multibody/tree/weld_mobilizer.cc, multibody/tree/weld_mobilizer.h
This is the first PR of several to help address issue #22630.  It creates MapQDDotToAcceleration() and MapAccelerationToQDDot() for simple mobilizers.  
Subsequent PRs will create helper methods for more complex mobilizers (e.g., rpy_ball_mobilizer, curvilinear_mobilizer, quaternion_floating_mobilizer, etc.) to consolidate creation of the N(q) and  N⁺(q) matrices that is shared between MapQDotToVelocity() and MapQDDotToAcceleration()  as well as MapVelocityToQDDot() and MapAccelerationToQDDot().
In conjunction with each of the subsequent PRs, each more complex mobilizer will implement its functions MapQDDotToAcceleration() and MapAccelerationToQDDot().
FYI: Since mobilizers are Drake internal classes, after the internal mobilizer work is complete, there will be PRs (code and testing) for …
=> MapQDDotToAcceleration() and MapAccelerationToQDDot() for simple mobilizers

tools/workspace/libpng_internal/repository.bzl
This reverts commit 4ed4d749a8d82fb16515f8755161f8cd69e4b6e5.
---
The upgrade caused our tests (e.g., `bazel test //geometry/render_vtk:internal_render_engine_vtk_test --test_output=streamed`) spam the console with png warnings:
```
[==========] Running 28 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 28 tests from RenderEngineVtkTest
[ RUN      ] RenderEngineVtkTest.NoBodyTest
[       OK ] RenderEngineVtkTest.NoBodyTest (488 ms)
[ RUN      ] RenderEngineVtkTest.ControlBackgroundColor
[       OK ] RenderEngineVtkTest.ControlBackgroundColor (607 ms)
[ RUN      ] RenderEngineVtkTest.MeshTest
[2025-03-04 16:28:18.685] [console] [warning] warning: The mesh /mnt/nobackup/cache/bazel/_bazel_jwnimmer/10ee8aea36b37b216ef85df1451b64ad/execroot/_main/bazel-out/k8 …
```
=> Revert "[workspace] Upgrade libpng_internal to latest release v1.6.47"

bindings/pydrake/systems/framework_py_values.cc, bindings/pydrake/systems/primitives_py.cc, bindings/pydrake/systems/test/primitives_test.py, bindings/pydrake/systems/test/value_test.py, multibody/plant/multibody_plant.h, systems/framework/BUILD.bazel, systems/framework/bus_value.cc, systems/framework/bus_value.h, systems/framework/test/bus_value_test.cc, systems/primitives/BUILD.bazel, systems/primitives/bus_creator.cc, systems/primitives/bus_creator.h, systems/primitives/bus_selector.cc, systems/primitives/bus_selector.h, systems/primitives/test/bus_creator_test.cc, systems/primitives/test/bus_selector_test.cc
**Is your feature request related to a problem? Please describe.**
It is not uncommon for a set of signals form a logical group, where they are always routed together (e.g., in and out of a diagram with a single port instead of one port per signal).
Consider the case of a controller system, which takes commanded RigidTransform poses as input.  Each pose has a name, perhaps `X_WL` and `X_WR` for the left and right hand pose.  Sometimes there might be more or fewer hands, or the poses willl have different names.  Even if we added "X_WL_input" and  "X_WR_input" ports to the controller, now we need to connect them to some sources, which might not be in the diagram so we'd need to export a bunch of specific ports and connect those elsewhere.  Even more troublesome, the set of poses being …
=> [framework] Introduce BusCreator, BusSelector, BusValue

planning/iris/iris_zo.cc, planning/iris/iris_zo.h, planning/iris/test/iris_zo_test.cc
Closes #22714
Note that we make two changes here:
1. We throw an error if the user provides a seed point that is in-collision (or violates one of the additional constraints the user has provided)
2. If after the first iteration, the center of the ellipsoid moves to a configuration that's in-collision, we return the polytope from the previous iteration, and warn the user that this has occurred.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22737)
=> IrisZo: Better Handle Cases when the Center of the Ellipsoid is In-Collision

multibody/tree/joint_actuator.cc, multibody/tree/joint_actuator.h, multibody/tree/test/joint_actuator_test.cc
As long as the plant is discrete, changing the PD gains (even back to zero, to remove the controller) should be allowed.  This makes simulator setup code even simpler, and no longer requires users to type drake-specific XML gains into all of their robot files.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22715)
=> [multibody] Remove all temporal setup limitations on PD gains

examples/allegro_hand/joint_control/BUILD.bazel, examples/allegro_hand/joint_control/run_twisting_mug.cc, examples/kinova_jaco_arm/BUILD.bazel, examples/kinova_jaco_arm/move_jaco_ee.cc, examples/kuka_iiwa_arm/BUILD.bazel, examples/kuka_iiwa_arm/kuka_plan_runner.cc, examples/kuka_iiwa_arm/move_iiwa_ee.cc
Towards #17231.  This is the last piece of Drake (other than `DrakeLcm` itself) that still directly uses the upstream API.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22724)
=> [examples] Port to always use DrakeLcm API

tools/wheel/image/build-python.sh, tools/wheel/image/packages-jammy, tools/wheel/image/provision-base.sh, tools/wheel/wheel_builder/linux.py
Change wheel builds to always build Python from source. This provides better insulation against what Python versions are or are not packaged by the build host. Move dependencies for building Python to the base package list, which allows us to remove logic to install them from `build-python.sh`. Improve reporting if the Python source tarball doesn't match the expected hash. Tweak `provision-base.sh` to "allow" blank lines in the package list. (In practice, it seems they were harmless anyway, but we now explicitly ignore them, as well as comments.)
This does not, however, remove support for using the distro-provided Python, as we may or may not stick with "always build our own".
Toward #22403.
- - - …
=> Always build Python for wheels

doc/_pages/installation.md, doc/_pages/release_playbook.md, tools/release_engineering/download_release_candidate.py, tools/wheel/wheel_builder/linux.py
Blocked on #21968.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22580)
=> [build] Publish linux wheels for Python 3.13

visualization/colorize_depth_image.cc, visualization/test/colorize_depth_image_test.cc
This error is only detectable with UBSan.  Hotfix for #22740.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22765)
=> [visualization] Fix divide-by-zero in ColorizeDepthImage

CMakeLists.txt
Add an explicit dependency on the drake_version target to the drake_cxx_python target. Previously, the latter depended on the generated version script, but that isn't understood as an output of the drake_version target, which would sometimes lead to build errors due to the file not existing and the tool not knowing how to build it. (This is more likely to be a problem with build parallelism enabled, and especially was hitting Ninja builds.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22766)
=> Fix CMake dependencies

common/ssize.h
Use `<iterator>` instead of `<vector>` in Drake's `ssize` wrapper header. Of the several headers that provide `ssize`, only `<iterator>` is guaranteed to also provide the `__cpp_lib_ssize` feature test macro.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22767)
=> Fix Drake's ssize wrapper

bindings/pydrake/systems/controllers_py.cc, bindings/pydrake/systems/test/controllers_test.py, systems/controllers/linear_quadratic_regulator.cc, systems/controllers/linear_quadratic_regulator.h, systems/controllers/test/finite_horizon_linear_quadratic_regulator_test.cc, systems/controllers/test/linear_quadratic_regulator_test.cc
The current discrete-time LQR implementation only supports minimizing  
$$ \sum_{n=0}^\infty x^\top Q x + u^\top R u. $$  
This PR completes the TODOs in the code and extends support for minimizing  
$$ \sum_{n=0}^\infty x^\top Q x + u^\top R u + 2 x^\top N u. $$
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22686)
=> Support x'Nu term in discrete-time LQR

multibody/contact_solvers/sap/BUILD.bazel, multibody/contact_solvers/sap/sap_tendon_constraint.cc, multibody/contact_solvers/sap/sap_tendon_constraint.h, multibody/contact_solvers/sap/test/sap_tendon_constraint_test.cc
Towards #22664. Adds the necessary SAP constraint to implement MuJoCo's [fixed tendon](https://mujoco.readthedocs.io/en/stable/XMLreference.html#tendon-fixed).
@amcastro-tri I'm pushing this as a draft for now since I've yet to finish the tests. But I just wanted to get your eyes on it for a design review. The tests will probably be ready by the time you take a pass.
cc: @RussTedrake
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22711)
=> [multibody] Adds SapFixedTendonConstraint

bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/general_test.py
The prior implementation of the Simulator() binding yielded two possible lifetime regimes for the context:
* internally allocated contexts were effectively C++ unique_ptr
* passed-from-python contexts were Python ref-counted
This patch causes both cases to yield Python-ref-counted contexts, and it adds documentation to warn against attempts to "share" contexts across Simulators.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22781)
=> [pydrake] Fix a bug in the Simulator constructor

solvers/semidefinite_relaxation_internal.cc, solvers/test/semidefinite_relaxation_internal_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22760)
=> MakeSemidefiniteRelaxation parse quadratic equality constraints in linear equality constraints instead of two linear inequalities.

bindings/pydrake/geometry/geometry_py_meshes.cc, bindings/pydrake/geometry/test/meshes_test.py, geometry/proximity/hydroelastic_internal.cc, geometry/proximity/make_convex_hull_mesh.cc, geometry/proximity/make_convex_hull_mesh_impl.cc, geometry/proximity/make_convex_hull_mesh_impl.h, geometry/proximity/make_mesh_from_vtk.cc, geometry/proximity/obj_to_surface_mesh.cc, geometry/proximity/obj_to_surface_mesh.h, geometry/proximity/test/make_convex_hull_mesh_impl_test.cc, geometry/proximity/test/obj_to_surface_mesh_test.cc, geometry/proximity/test/vtk_to_volume_mesh_test.cc, geometry/proximity/vtk_to_volume_mesh.cc, geometry/proximity/vtk_to_volume_mesh.h, geometry/read_obj.cc, geometry/read_obj.h, geometry/shape_specification.cc, geometry/shape_specification.h, geometry/test/read_obj_test.cc, multibody/parsing/detail_mesh_parser.cc
This includes parsing mesh into Drake constructs and computing convex hulls.
When parsing mesh files (e.g., obj, vtk, etc.) we explicitly handle the case where the scale includes mirroring which may cause the mesh windings to be wound incorrectly.
This also attempts to unify the internal APIs with regards to what scale factors are accepted. We accept any scale factor -- even zero. Because these are internal, if some limit needs to be placed by some application, we rely on the application to enforce that constraint.
Relates #22046.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22772)
=> [geometry] Introduce 3D scale in mesh processing algorithms

geometry/proximity/obj_to_surface_mesh.h
The parameter name in the doxygen didn't match the C++ parameter name.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22786)
=> Fix doxygen error in obj_to_surface_mesh.h

tools/workspace/scs_internal/patches/upstream/fix_arg.patch, tools/workspace/scs_internal/repository.bzl
Patch SCS passing an incorrect argument type to QDLDL_factor. For some reason, this causes a warning (which gets treated as an error) about the incompatible argument type on manylinux, but apparently not on Ubuntu.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22771)
=> Fix improper use of QDLDL by SCS

bindings/pydrake/visualization/test/visualization_install_tests.py
Closes https://github.com/RobotLocomotion/drake/issues/21023.
The shebangs present in `run_installed_meldis.py` and `run_installed_model_visualizer.py` were causing these tests to use two different interpreters on macOS. When the `visualiztion_install_tests` would dispatch subprocesses to execute the installed binaries of `meldis` and `model_visualizer` , the subprocess would select the interpreter to run the two aforementioned python files based on the shebang in the executable file. This would make it so the installation portion of the test would use the python interpreter in Drake’s `venv` (which is the desired behavior), but the actual handling of the executable would be kicked to the mac’s globally installed python interpreter. This misalignment is what caused the three install tests …
=> Patch brittle `visualization_install_tests` for macOS

multibody/plant/BUILD.bazel, multibody/plant/constraint_specs.h, multibody/plant/discrete_update_manager.cc, multibody/plant/discrete_update_manager.h, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/multibody_plant_discrete_update_manager_attorney.h, multibody/plant/sap_driver.cc, multibody/plant/sap_driver.h, multibody/plant/test/multibody_plant_test.cc, multibody/plant/test/sap_driver_tendon_constraints_test.cc
Towards #22664. Creates the API `MultibodyPlant::AddTendonConstraint()` and all of its relatives.
Hooks up constraints specified by the plant to the SAP problem through `SapDriver`.
The first commit in this PR contains the content from #22711, and will be dropped once that has merged. 
cc: @RussTedrake @amcastro-tri
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22717)
=> [multibody] Adds MultibodyPlant::AddTendonConstraint()

bindings/pydrake/geometry/geometry_py_visualizers.cc, bindings/pydrake/geometry/test/visualizers_test.py, geometry/meshcat.cc, geometry/meshcat.h, geometry/test/meshcat_test.cc
This PR adds and binds a `Meshcat::GetButtonNames()` function, similar to `Meshcat::GetSliderNames()`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22806)
=> [meshcat] Add `GetButtonNames()`

bindings/pydrake/common/yaml.py
When porting this file for Anzu, its linter flagged the mistake here.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22810)
=> [py yaml] Alphabetize imports

tools/wheel/.dockerignore, tools/wheel/Dockerfile, tools/wheel/image/build-wheel.sh, tools/wheel/image/packages-almalinux, tools/wheel/image/provision-base.sh, tools/wheel/image/provision-python.sh, tools/wheel/licenses/gcc/copyright, tools/wheel/wheel_builder/linux.py, tools/workspace/pybind11/libclang_setup.py
Change wheel builds to use AlmaLinux instead of Ubuntu as the host platform. The motivating effect of this is to "downgrades" our required glibc version from 2.35 to 2.34.
Note that AlmaLinux 9 is the base of manylinux_2_34_x86_64:2025.01.05-1. The reason we are not using manylinux is because a) it provides Python interpreters that do not have headers or libraries, and so are not useful for building Drake, and b) its compilers interfere with use of the underlying AlmaLinux compilers and attempts to use them result in obscure failures.
Fixes #22403.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22779)
=> Build wheels on AlmaLinux instead of Ubuntu

bindings/pydrake/systems/analysis_py.cc, systems/analysis/BUILD.bazel, systems/analysis/bogacki_shampine3_integrator.cc, systems/analysis/bogacki_shampine3_integrator.h, systems/analysis/explicit_euler_integrator.cc, systems/analysis/explicit_euler_integrator.h, systems/analysis/implicit_euler_integrator.cc, systems/analysis/implicit_euler_integrator.h, systems/analysis/implicit_integrator.cc, systems/analysis/implicit_integrator.h, systems/analysis/integrator_base.cc, systems/analysis/integrator_base.h, systems/analysis/radau_integrator.cc, systems/analysis/radau_integrator.h, systems/analysis/runge_kutta2_integrator.cc, systems/analysis/runge_kutta2_integrator.h, systems/analysis/runge_kutta3_integrator.cc, systems/analysis/runge_kutta3_integrator.h, systems/analysis/runge_kutta5_integrator.cc, systems/analysis/runge_kutta5_integrator.h, systems/analysis/semi_explicit_euler_integrator.cc, systems/analysis/semi_explicit_euler_integrator.h, systems/analysis/test/implicit_integrator_test.cc, systems/analysis/test/integrator_base_test.cc, systems/analysis/velocity_implicit_euler_integrator.cc, systems/analysis/velocity_implicit_euler_integrator.h
As per [slack](https://drakedevelopers.slack.com/archives/C2CHRT98E/p1740326203692399?thread_ts=1740326158.413159&cid=C2CHRT98E) discussion, this PR implements the `Clone()` method for `IntegratorBase` so it can be put in a cache entry. This is guaranteed to be a thread-safe method for using integrators inside a `LeafSystem`. 
Another approach #22720 where we tried to add an entry point `IntegratorBase<T>::IntegrateWithSingleFixedStepToTime(const T& t_target, Context<T>* context) const`, is not thread-safe due to the fact that the integrator preallocates memory and rerads/writes to them during the integration
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22773)
=> Add cloning functionality for IntegratorBase

bindings/pydrake/systems/BUILD.bazel, bindings/pydrake/systems/framework_py_semantics.cc, bindings/pydrake/systems/framework_py_systems.cc, bindings/pydrake/systems/test/custom_test.py, bindings/pydrake/systems/test/general_test.py, bindings/pydrake/systems/test_utilities/BUILD.bazel, bindings/pydrake/systems/test_utilities/__init__.py, bindings/pydrake/systems/test_utilities/framework_test_util.py, bindings/pydrake/test/memory_leak_test.py
Stop using keep_alive with returned port references; use ref_cycle instead. The most common place where this problem can arise is when writing leaf systems in Python. However, since systems have dynamic_attr() now, it can be induced anywhere. So, to avoid immortality problems across the board, re-annotate all APIs that return port references.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22775)
=> [pydrake] Avoid lifetime hazards with port references

multibody/parsing/test/detail_sdf_parser_test.cc
That name already had a using statement.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22839)
=> [parsing] Drop FQNs for MatchesRegex in sdf parser test

tools/workspace/metadata.py, tools/workspace/new_release.py
During the workspace-bzlmod transition, we do not want to upgrade the workspace's toolchain.
Closes #22684.
+@nicolecheetham for feature review, please.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22828)
=> [workspace] Disable monthly upgrades of rust_toolchain

multibody/plant/test/multibody_plant_test.cc, multibody/tree/BUILD.bazel, multibody/tree/frame.h, multibody/tree/multibody_element.h, multibody/tree/test/frames_test.cc
Resolves #22804.
Fixes segmentation fault for a calculation involving a frame that was not added to a MultibodyTree.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22821)
=> [multibody] Fix crash on frame elements not added to a plant

doc/_pages/release_playbook.md
Per #22819, macOS packaging jobs will now be provisioned.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22830)
=> [doc] Update Jenkins links in release playbook

bindings/pydrake/systems/estimators_py.cc, bindings/pydrake/systems/test/estimators_test.py, systems/estimators/BUILD.bazel, systems/estimators/kalman_filter.cc, systems/estimators/kalman_filter.h, systems/estimators/luenberger_observer.cc, systems/estimators/luenberger_observer.h, systems/estimators/test/kalman_filter_test.cc, systems/estimators/test/luenberger_observer_test.cc
This PR implements the discrete-time steady-state Kalman filter and Luenberger observer.
For reference, the Kalman filter dynamics is given by:
$$
K = \hat{P} C^\top (C \hat{P} C^\top+ V)^{-1}
$$
$$
\hat{x}[n|n] = \hat{x}[n|n-1] + K(y - \hat{y})
$$
$$
\hat{x}[n+1|n] = A \hat{x}[n|n] + B u[n]
$$
At steady-state, the dynamics is given by:
$$
\hat{x}[n+1|n] = A \hat{x}[n|n-1] + B u[n] + L(y - \hat{y})
$$
Thus, the observer gain is:
$$
L = A \hat{P} C^\top (C \hat{P} C^\top + V)^{-1}
$$
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22687)
=> Add discrete-time steady-state Kalman filter

systems/analysis/BUILD.bazel, systems/analysis/simulator_config_functions.cc, systems/analysis/simulator_config_functions.h, systems/analysis/simulator_gflags.cc, systems/analysis/test/simulator_config_functions_test.cc
Adds a factory function `std::unique_ptr<IntegratorBase<T>> CreateIntegratorFromFlags(const System<T>& system, const SimulatorConfig& config)` as required [here](https://reviewable.io/reviews/RobotLocomotion/drake/22652#-OMbihXP4FvHphI2nDQZ).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22838)
=> Implement create IntegratorBase from integration scheme

geometry/test/proximity_engine_test.cc
There were hundreds of misformatted floating point literals (1., 2., etc.). This cleans them all up by removing the '.' in most cases. To make the code more consistent, it also converted x.0 floating point literals to x where feasible.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22853)
=> Clean up float format in proximity engine tests

examples/allegro_hand/joint_control/test/run_twisting_mug_test.py
Closes #22815. As it's a relatively non-important test, we're just going to disable on macOS -- any *actual* LCM multicast errors would be reported via `//examples/hardware_sim:py/hardware_sim_py_test`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22859)
=> [examples] Disable test case on macOS

geometry/proximity/hydroelastic_internal.cc, geometry/proximity/make_mesh_from_vtk.cc, geometry/proximity/test/hydroelastic_internal_test.cc, geometry/proximity_engine.cc, geometry/proximity_engine.h, geometry/test/geometry_state_test.cc, geometry/test/proximity_engine_test.cc, multibody/parsing/detail_mujoco_parser.cc, multibody/parsing/detail_sdf_geometry.cc, multibody/parsing/detail_urdf_geometry.cc, multibody/parsing/detail_usd_geometry.cc, multibody/parsing/detail_usd_geometry.h, multibody/parsing/test/detail_mujoco_parser_examples_test.cc, multibody/parsing/test/detail_mujoco_parser_test.cc, multibody/parsing/test/detail_sdf_geometry_test.cc, multibody/parsing/test/detail_urdf_geometry_test.cc, multibody/parsing/test/detail_usd_geometry_test.cc, multibody/tree/geometry_spatial_inertia.cc, multibody/tree/test/geometry_spatial_inertia_test.cc
NOTE TO RELEASE ENGINEER:
This is one of multiple PRs that enable non-uniform scaling (see also #22772, #22785, and others).  For the release, they should all be lumped together. The total feature description is:
Enable non-uniform scaling for Mesh and Convex geometries.
Relates https://github.com/RobotLocomotion/drake/issues/22046.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22824)
=> Proxmity and Parsing use non-uniform scale

bindings/pydrake/systems/planar_scenegraph_visualizer.py, bindings/pydrake/systems/test/planar_scenegraph_visualizer_test.py, bindings/pydrake/visualization/_meldis.py, bindings/pydrake/visualization/test/meldis_test.py, geometry/drake_visualizer.cc, geometry/meshcat.cc, geometry/test/drake_visualizer_test.cc, geometry/test/meshcat_test.cc
NOTE TO RELEASE ENGINEER:
This is one of multiple PRs that enable non-uniform scaling (see also #22772, #22785, and others).  For the release, they should all be lumped together. The total feature description is:
Enable non-uniform scaling for Mesh and Convex geometries.
Relates https://github.com/RobotLocomotion/drake/issues/22046.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22823)
=> Adapt visualizers to non-uniform scale

.github/ISSUE_TEMPLATE/POST_RELEASE_ACTIONS.yml, doc/_pages/release_playbook.md
Closes #22774
These changes introduce a formal structure for creating and tracking post-release action issues. The new github issue template links to documentation explaining what actions are required for a new release and provides a user-friendly interface for keeping track of these tasks. These changes are reflected in the release playbook documentation, allowing contributors from TRI, kitware, and the open source community to follow this procedure.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22796)
=> Added gh issue template for post-release actions

tools/workspace/vtk_internal/gen/vtkRenderingOpenGL2ObjectFactory.cxx, tools/workspace/vtk_internal/gen/vtkRenderingOpenGL2ObjectFactory.h, tools/workspace/vtk_internal/repository.bzl
Towards https://github.com/RobotLocomotion/drake/issues/22836
This commit had problematic output in local testing and caused CI jobs to fail. Most recent CI run passed locally, but will await Jenkins ci builds for confirmation.
It would appear these upgrades are indeed problematic: [linux-jammy-clang-bazel-experimental-everything-release](https://drake-jenkins.csail.mit.edu/job/linux-jammy-clang-bazel-experimental-everything-release/7901/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22857)
=> [workspace] Upgrade vtk_internal to latest commit

tools/workspace/googlebenchmark/patches/console_allocs.patch, tools/workspace/googlebenchmark/repository.bzl
Towards #22836 
This commit had problematic output in local testing and caused CI jobs to fail. Most recent CI run passed locally, but will await Jenkins ci builds for confirmation.
It would appear these upgrades are indeed problematic: [linux-jammy-clang-bazel-experimental-everything-release](https://drake-jenkins.csail.mit.edu/job/linux-jammy-clang-bazel-experimental-everything-release/7899/)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22854)
=> [workspace] Upgrade googlebenchmark to latest release v1.9.2

tools/workspace/libpng_internal/png_drake_vendor.h, tools/workspace/libpng_internal/repository.bzl
Closes #22728, unblocks #22862, and towards #22836
Modifies list of custom, drake-specific adjustments to libpng to disable eXIf read support. Disabling this option effectively suppresses the `libpng warning: eXIf: invalid` output that we would observe running the drake vtk rendering tests on Linux. As eXIf chunks are optional and tend to contain image metadata (particularly metadata relevant to images taken with physical cameras, e.g. aperture and shutter speed), reads for these kinds of chunks can be safely disabled for the rendered test images used for this test suite.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22861)
=> Suppress benign eXIf warnings from libpng 1.6.47

CMakeLists.txt, bindings/pydrake/common/test/deprecation_autocomplete_test.py, bindings/pydrake/common/test/yaml_typed_test.py, doc/_pages/from_source.md, doc/_pages/installation.md, doc/_pages/release_playbook.md, doc/_release-notes/end_of_support.md, setup/mac/binary_distribution/Brewfile, setup/mac/binary_distribution/install_prereqs.sh, tools/release_engineering/download_release_candidate.py, tools/wheel/wheel_builder/macos.py, tools/workspace/python/repository.bzl
Towards #22581. Updates to all references of Python 3.12 are updated:
* `CMakeLists.txt` and `tools/workspace/python/repository.bzl`
* `setup/mac/binary_distribution/Brewfile`
* Wheel builds, including release artifacts
* Documentation for supported versions, including the release playbook
* Fixes a test case with new class attributes defined in 3.13
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22827)
=> Upgrade macOS to Python3.13

math/rigid_transform.h, math/rotation_matrix.cc, math/rotation_matrix.h, math/test/rigid_transform_test.cc, math/test/rotation_matrix_test.cc
Adds public but `(Internal use only)` rotation matrix and rigid transform functions for exploiting known special structure of those matrices. These arise for common 1-dof revolute and prismatic joints when implemented with axis-aligned mobilizers.
This is yak shave for using optimal F & M frames for these joints (milestone 3 in [this doc](https://docs.google.com/document/d/1KT2hlRc1eeIPSZ_Oo4tqESy0MadteJeAhFINwTZqfFY)). These functions need specialized feature review so get their own PR. You can see these functions in use for revolute mobilizers in WIP PR #22253.
The new functions are templated inlines that are specialized implementations of existing more-general functions so they would add no value in Python and are not intended to be wrapped.
- - - …
=> [math] Add axial rotation and transform functions

bindings/pydrake/multibody/plant_py.cc, bindings/pydrake/multibody/test/plant_test.py, multibody/plant/deformable_contact_info.h, multibody/plant/test/deformable_contact_info_test.cc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22868)
=> [pydrake] Bind DeformableContactInfo and ContactResults access

common/extract_double.h, common/test/extract_double_test.cc, multibody/mpm/BUILD.bazel, multibody/mpm/mock_sparse_grid.cc, multibody/mpm/mock_sparse_grid.h, multibody/mpm/particle_data.cc, multibody/mpm/particle_data.h, multibody/mpm/sparse_grid.cc, multibody/mpm/sparse_grid.h, multibody/mpm/test/particle_data_test.cc, multibody/mpm/test/particle_sorter_test.cc, multibody/mpm/test/sparse_grid_test.cc, multibody/mpm/test/transfer_test.cc, multibody/mpm/transfer.cc, multibody/mpm/transfer.h
Add related testing infra -- ComputeTotalMassAndMomentum for particles.
Fix a bug in SparseGrid::GetGridData().
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22807)
=> [mpm] Add Transfer

setup/mac/source_distribution/Brewfile-developer, setup/mac/source_distribution/install_prereqs.sh
Towards #22848 
Installs additional `brew` dependencies for building drake wheels on macOS if the `setup/install_prereqs` script is run with the `--developer` flag passed to it. Eventually, the provisioning logic which previously installed these dependencies (contained within the wheel builder scripts themselves) will have to be removed in order to prevent build contamination between CI jobs on AWS Mac hosts.
Sample console output of this impl with the `--developer` flag set:
```Bash
++ command -v brew
++ brew bundle --file=/Users/aiden.mccormack/Code/tri/drake-build-local/drake/setup/mac/source_distribution/Brewfile
Using bazelisk
Using cmake
Using eigen
Using fmt
Using nasm
Using pkg-config
Using spdlog
`brew bundle` complete! 7 Brewfile dependencies now installed.
++ [[ 1 -eq 1 ]]
++ …
```
=> Install macOS wheel builder deps with `--developer` flag

bindings/pydrake/geometry/geometry_py_render.cc, bindings/pydrake/geometry/geometry_py_scene_graph.cc, bindings/pydrake/geometry/test/render_test.py, bindings/pydrake/geometry/test/scene_graph_test.py, geometry/render/render_engine.cc, geometry/render/render_engine.h, geometry/render_gl/BUILD.bazel, geometry/render_gl/internal_render_engine_gl.cc, geometry/render_gl/internal_render_engine_gl.h, geometry/render_gl/test/internal_render_engine_gl_test.cc, geometry/render_gltf_client/BUILD.bazel, geometry/render_gltf_client/internal_render_engine_gltf_client.cc, geometry/render_gltf_client/internal_render_engine_gltf_client.h, geometry/render_gltf_client/test/internal_render_engine_gltf_client_test.cc, geometry/render_vtk/BUILD.bazel, geometry/render_vtk/internal_render_engine_vtk.cc, geometry/render_vtk/internal_render_engine_vtk.h, geometry/render_vtk/test/internal_render_engine_vtk_test.cc, geometry/scene_graph.cc, geometry/scene_graph.h, geometry/test/scene_graph_test.cc, geometry/test_utilities/dummy_render_engine.h, systems/sensors/BUILD.bazel, systems/sensors/camera_config.h, systems/sensors/camera_config_functions.cc, systems/sensors/test/camera_config_functions_test.cc
This provides the ability to ask a RenderEngine instance if a set of parameters describes the engine.
We apply this new ability when processing CameraConfig instances. It makes the process more forgiving as multiple CameraConfig can reference otherwise equivalent RenderEngine instances (whereas before, it was more brittle and inclined to throw).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22871)
=> Compare RenderEngineParams with existing RenderEngine instances

doc/_pages/developers.md, doc/_pages/downstream_testing.md, doc/_pages/jenkins.md
Towards #22574, associated with [#374](https://github.com/RobotLocomotion/drake-external-examples/pull/374) and [#376](https://github.com/RobotLocomotion/drake-external-examples/pull/376) on drake-external-examples.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22721)
=> [doc] Add documentation for running drake-external-examples CI jobs on Drake PRs

math/BUILD.bazel, math/autodiff.h, math/autodiff_gradient.h, math/test/autodiff_test.cc
Currently, the functions `ExtractValue` and `ExtractGradient` **returns** the value and gradient part of a `Eigen::MatrixX<AutoDiffXd>`. This PR adds overloads accepting an additional argument `Eigen::MatrixXd*`, giving users the ability to preallocate the output matrices.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22895)
=>  Overload `ExtractValue` and `ExtractGradient` to allow preallocated output matrix

doc/_pages/buildcop.md
As #22700 is now closed, we need to update the buildcop documentation to reflect our departure from MacStadium and our discontinued use of a macOS cache server. This is strictly a change to documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22886)
=> [doc] Purge MacStadium and macOS cache server refs from buildcop docs

setup/ubuntu/source_distribution/packages-jammy.txt, setup/ubuntu/source_distribution/packages-noble.txt, tools/wheel/image/packages-almalinux
Our patch-applying process somewhere appears to rely on `diff` (normally provided on Linux via the GNU diffutils package). Previously, we have taken it for granted that this was available, but AlmaLinux appears to have "trimmed" their Docker image recently to omit it, resulting in build failures. Add the providing package to our various dependency lists to ensure it is available.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22903)
=> Add explicit requirement for diffutils

bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/analysis_test.py, systems/analysis/BUILD.bazel, systems/analysis/discrete_time_approximation.cc, systems/analysis/discrete_time_approximation.h, systems/analysis/test/discrete_time_approximation_test.cc
This is an extension of #22601.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22652)
=> Add DiscreteTimeApproximation for general continuous-time systems

multibody/mpm/BUILD.bazel, multibody/mpm/mock_sparse_grid.cc, multibody/mpm/mock_sparse_grid.h, multibody/mpm/mpm_model.cc, multibody/mpm/mpm_model.h, multibody/mpm/particle_data.h, multibody/mpm/particle_sorter.h, multibody/mpm/solver_state.cc, multibody/mpm/solver_state.h, multibody/mpm/sparse_grid.cc, multibody/mpm/sparse_grid.h, multibody/mpm/spgrid.h, multibody/mpm/test/mpm_model_test.cc, multibody/mpm/test/particle_sorter_test.cc, multibody/mpm/test/sparse_grid_test.cc, multibody/mpm/test/spgrid_test.cc, multibody/mpm/transfer.h
In support of these two new classes and their tests, also add SparseGrid::IterateConstGrid(), MockSparseGrid::IterateConstGrid(), SparseGrid::SetNodeIndices(), MockSparseGrid::SetNodeIndices().
Make Transfer class copyable.
Add a missing const in ParticleData.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22882)
=> Add MpmModel and SolverState

tools/wheel/wheel_builder/macos.py
Towards #22848 
Unblocks drake-ci [#320](https://github.com/RobotLocomotion/drake-ci/pull/320)
This is a small change that prevents the wheel builds from failing if one of the paths that it attempts to remove is a symlink. The desired condition for the wheel builder path removal is for the path to not exist at all in any form, but if it exists as a symlink it was likely left over from a previous build and/or doesn't contain any data itself and can be safely removed. We only want the builds to fail if the path exists and it is NOT a symlink, as the directory may not be safe to remove automatically.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22904)
=> Don't fail wheel build if symlink exists

doc/_pages/jenkins.md, doc/_pages/release_playbook.md
All macOS jobs are now provisioned, so these links should be updated accordingly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22902)
=> [doc] Remove links & references to macOS unprovisioned jobs

MODULE.bazel
This works around a problem with GitLab-hosted archives changing out from under us (see https://github.com/bazelbuild/bazel-central-registry/issues/4355). Only the hosting URL is changed (not the code).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22918)
=> [workspace] Upgrade bzlmod eigen to 3.4.0.bcr.3

bindings/pydrake/systems/analysis_py.cc, bindings/pydrake/systems/test/analysis_test.py, systems/analysis/BUILD.bazel, systems/analysis/discrete_time_approximation.cc, systems/analysis/discrete_time_approximation.h, systems/analysis/simulator_config_functions.cc, systems/analysis/simulator_config_functions.h, systems/analysis/test/discrete_time_approximation_test.cc, systems/analysis/test/simulator_config_functions_test.cc
The recently added function `DiscreteTimeApproximation<T>(const System<T>&, double, const SimulatorConfig&)` in #22652 only supports `T=double` and `T=AutoDiffXd`. This PR adds support for `T=symbolic::Expression`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22913)
=> Support symbolic scalar type integrators in DiscreteTimeApproximation

doc/_pages/troubleshooting.md, multibody/plant/test/multibody_plant_test.cc, multibody/tree/multibody_tree.cc, multibody/tree/test/multibody_tree_creation_test.cc
PR #22873 implemented reverse revolute joints as a side effect of choosing optimal F & M frames for revolute mobilizers but did not enable the feature. This PR enables reverse revolute joints and adds test cases to show that they are working.
This is half of issue #22212; prismatic joints still remain to be reversed.
This also adds a missing error message for systems whose links and joints form topological loops since we don't have automatic support for those yet. This prevents issuing a confusing "this joint can't be reversed" error message when the cause of the reversal was the presence of a loop. A short troubleshooting section on how to model systems with loops is added also.
Unit tests are provided for (a) loop detection, (b) reversed revolute functionality, and (c) rejection of …
=> [multibody] Allow reversed revolute joints

math/rigid_transform.h, math/test/rigid_transform_test.cc, multibody/tree/body_node_impl.cc, multibody/tree/body_node_impl_mass_matrix.cc, multibody/tree/joint.cc, multibody/tree/joint.h, multibody/tree/mobilizer_impl.h, multibody/tree/prismatic_joint.cc, multibody/tree/prismatic_joint.h, multibody/tree/prismatic_mobilizer.cc, multibody/tree/prismatic_mobilizer.h, multibody/tree/revolute_joint.cc, multibody/tree/revolute_joint.h, multibody/tree/revolute_mobilizer.cc, multibody/tree/revolute_mobilizer.h, multibody/tree/test/body_node_test.cc, multibody/tree/test/multibody_tree_test.cc, multibody/tree/test/prismatic_mobilizer_test.cc, multibody/tree/test/revolute_mobilizer_test.cc, multibody/tree/weld_joint.cc
Following PR #22873 (optimal frames for revolute joints), this PR does the same for prismatic joints.
Makes some minor changes to bring revolute_mobilizer and prismatic_mobilizer into nicely-matching terminology, implementation, and tests. Adds two missing unit tests to prismatic_mobilizer_test.cc. Adds two more RigidTransform internal-use-only specialized methods & unit tests.
Does not yet permit reversal of prismatic joints. There will be a follow-on similar to #22883 (reverse revolute joint) for prismatics.
Completes milestone 3 of [this document](https://docs.google.com/document/d/1KT2hlRc1eeIPSZ_Oo4tqESy0MadteJeAhFINwTZqfFY).
All changes are internal so no release note is required.
- - - …
=> [multibody] Optimize F & M frames for prismatic joint's mobilizer.

planning/iris/BUILD.bazel, planning/iris/test/iris_test_utilities.cc, planning/iris/test/iris_test_utilities.h, planning/iris/test/iris_zo_test.cc
This is the first of a series of PRs designed to clean up `iris_zo_test.cc`. Aside from the general benefits of cleanup, by modularizing these tests with test fixtures, we can reuse them with IRIS-NP2 (discussed in #21822).
This PR adds test fixtures for the first two test environments. Future PRs will add test fixtures for the remaining environments, and potentially break out the parameterization machinery to have its own test files.
+@wernerpe for feature review.
cc @RussTedrake since I believe you wrote a lot of these tests originally?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22945)
=> Test Fixtures and Cleanup for IrisZo (Part 1)

multibody/plant/test/multibody_plant_test.cc, multibody/tree/multibody_tree.cc
PR #22925 modified prismatic joints to be reversible but did not enable the feature. This PR turns on that feature and adds a test to show that it works, similar to what PR #22883 did for revolute joints.
This completes milestone 4 in [this document](https://docs.google.com/document/d/1KT2hlRc1eeIPSZ_Oo4tqESy0MadteJeAhFINwTZqfFY).
This _may_ resolve issue #17429 (finally!) but I haven't tested that yet.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22949)
=> [multibody] Allow reversed prismatic joints

multibody/tree/mobilizer.cc, multibody/tree/mobilizer.h, multibody/tree/prismatic_mobilizer.cc, multibody/tree/prismatic_mobilizer.h, multibody/tree/revolute_mobilizer.cc, multibody/tree/revolute_mobilizer.h, multibody/tree/test/prismatic_mobilizer_test.cc, multibody/tree/test/revolute_mobilizer_test.cc
This is one in a series of PRs to help address issue  #22630. It creates CalcNDotMatrix(), CalcNplusDotMatrix() and DoCalcNDotMatrix(), DoCalcNplusDotMatrix() for a generic mobilizer and overrides DoCalcNDotMatrix(), DoCalcNplusDotMatrix() for two simple mobilizers (namely revolute and prismatic).
Subsequent PRs will create additional instances for others mobilizers (e.g., rpy_ball_mobilizer, curvilinear_mobilizer, quaternion_floating_mobilizer, etc.) to facilitate implementation of MapQDDotToAcceleration() and MapAccelerationToQDDot().
- - - …
=> Create mobilizer functions CalcNDotMatrix() and CalcNplusDotMatrix().

planning/iris/BUILD.bazel, planning/iris/test/iris_test_utilities.cc, planning/iris/test/iris_test_utilities.h, planning/iris/test/iris_zo_test.cc
This is the second PR in a series cleaning up the test cases for IrisZo. See #22945 for further details.
This PR does a bit of cleanup on how the double pendulum test works with the rational forward kinematics parameterization, and handles the test fixtures for the convex configuration space (and its many variants).
+@wernerpe for feature review
Marking "do not merge" so I can update the commit message later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22954)
=> Test Fixtures and Cleanup for IrisZo (Part 2)

tools/wheel/image/packages-almalinux
Likely related to the "trimming" that we experienced and resolved in #22903 with `diffutils`, and the change of packages for Noble in #22919 broke us as we're falling back on the wrong `libclang` version for `mkdoc`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22956)
=> [setup] Add explicit requirement for `lsb_release` on Linux wheel builds

tools/wheel/Dockerfile, tools/wheel/README.rst, tools/wheel/image/build-drake.sh, tools/wheel/image/build-python.sh, tools/wheel/image/build-wheel.sh, tools/wheel/image/provision-build.sh, tools/wheel/image/provision-python.sh, tools/wheel/macos/build-wheel.sh, tools/wheel/macos/provision-test-python.sh, tools/wheel/test/install-wheel.sh, tools/wheel/test/provision.sh, tools/wheel/test/test-wheel.sh, tools/wheel/test/tests/hermetic/import-error-test.sh, tools/wheel/wheel_builder/common.py, tools/wheel/wheel_builder/linux.py, tools/wheel/wheel_builder/macos.py
Towards #22848 
Modify wheel builds to create a unique build directory for each build in
a unique temporary directory. This has two effects; first, builds no
longer rely on `/opt` being writable; and second, macOS builds (which
cannot be done inside a container) are better isolated.
Additionally, some directory names are changed to improve naming
consistency.
Co-Authored-By: Matthew Woehlke <matthew.woehlke@kitware.com>
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22931)
=> Perform wheel builds in a unique directory

planning/iris/test/iris_test_utilities.cc, planning/iris/test/iris_test_utilities.h, planning/iris/test/iris_zo_test.cc
This is the third and final PR in a series cleaning up the test cases for IrisZo. See #22945 for further details.
This test cleans up the final test case in IrisZo (and removes some code that was only still needed for that test, and is now only needed in `iris_test_fixtures.cc`).
+@wernerpe for feature review
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22958)
=>  Test Fixtures and Cleanup for IrisZo (Part 3)

multibody/tree/BUILD.bazel, multibody/tree/curvilinear_mobilizer.cc, multibody/tree/curvilinear_mobilizer.h, multibody/tree/planar_mobilizer.cc, multibody/tree/planar_mobilizer.h, multibody/tree/screw_mobilizer.cc, multibody/tree/screw_mobilizer.h, multibody/tree/test/curvilinear_mobilizer_test.cc, multibody/tree/test/planar_mobilizer_test.cc, multibody/tree/test/quaternion_floating_mobilizer_test.cc, multibody/tree/test/screw_mobilizer_test.cc, multibody/tree/test/universal_mobilizer_test.cc, multibody/tree/test/weld_mobilizer_test.cc, multibody/tree/universal_mobilizer.cc, multibody/tree/universal_mobilizer.h, multibody/tree/weld_mobilizer.cc, multibody/tree/weld_mobilizer.h
This is another PR in a series of PRs to help address issue #22630. It overrides DoCalcNDotMatrix() and DoCalcNplusDotMatrix() for five more mobilizers: WeldMobilizer, PlanarMobilizer, ScrewMobilizer, UniversalMobilizer, CurvilinearMobilizer.  
Note: Already done is RevoluteMobilizer and PrismaticMobilizer.
Subsequent PRs will create additional overrides for RpyBallMobilizer, RpyFloatingMobilizer, QuaternionFloatingMobilizer.  Collectively, all these PRs help facilitate implementation of MapQDDotToAcceleration() and MapAccelerationToQDDot().
FYI: Mobilizers are Drake internal classes.  After the internal mobilizer work is complete, there will be subsequent PRs for the public API in MultibodyPlant to address issue #22630.
- - - …
=> Implement CalcNDotMatrix() for more mobilizers.

geometry/meshcat.cc, geometry/meshcat_types_internal.h
The updated three.js version from #22932 changed the spelling of `capsule.length` to `capsule.height`, causing parsing problems (#22973). This fixes that spelling so capsules parse correctly.
Hotfix for #22932.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22975)
=> Fix meshcat capsule parsing

multibody/plant/BUILD.bazel
Simulating for 5 seconds (needed for the body to come to rest) takes a while in debug mode in CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22980)
=> Give deformable integration test more time

multibody/tree/mobilizer.cc, multibody/tree/mobilizer.h, multibody/tree/planar_mobilizer.cc, multibody/tree/planar_mobilizer.h, multibody/tree/prismatic_mobilizer.cc, multibody/tree/prismatic_mobilizer.h, multibody/tree/revolute_mobilizer.cc, multibody/tree/revolute_mobilizer.h, multibody/tree/screw_mobilizer.cc, multibody/tree/screw_mobilizer.h, multibody/tree/weld_mobilizer.cc, multibody/tree/weld_mobilizer.h
This is one in a series of PRs to help address issue #22630. It improves MapQDDotToAcceleration() so it is no longer a virtual function.  Instead, it does basic argument checking (which was formerly done in _all_ Mobilizer sub-classes) and then calls the newly created virtual function DoMapQDDotToAcceleration().  This technique is used also for and MapAccelerationToQDDot().
A subsequent PR will clean up MapQDotToVelocity() and MapVelocityToQDot().
- - - …
=> Use NVI to consolidate code in MapAccelerationToQDDot().

bindings/pydrake/multibody/fem_py.cc, bindings/pydrake/multibody/test/fem_test.py, multibody/fem/BUILD.bazel, multibody/fem/constitutive_model.h, multibody/fem/deformable_body_config.h, multibody/fem/linear_constitutive_model.cc, multibody/fem/linear_constitutive_model.h, multibody/fem/linear_corotated_model.cc, multibody/fem/linear_corotated_model.h, multibody/fem/matrix_utilities.cc, multibody/fem/matrix_utilities.h, multibody/fem/neohookean_model.cc, multibody/fem/neohookean_model.h, multibody/fem/neohookean_model_data.cc, multibody/fem/neohookean_model_data.h, multibody/fem/test/constitutive_model_test_utilities.cc, multibody/fem/test/constitutive_model_test_utilities.h, multibody/fem/test/corotated_model_test.cc, multibody/fem/test/linear_constitutive_model_test.cc, multibody/fem/test/linear_corotated_model_test.cc, multibody/fem/test/matrix_utilities_test.cc, multibody/fem/test/neohookean_model_data_test.cc, multibody/fem/test/neohookean_model_test.cc, multibody/fem/test/volumetric_element_test.cc, multibody/fem/volumetric_element.h, multibody/mpm/particle_data.cc, multibody/mpm/particle_data.h, multibody/plant/deformable_model.cc
In addtion, add FemModel::CalcFilteredHessian that computes an SPD approximation of the tangent matrix of the model. The approximation is computed by assembling filtered element Hessians. In particular, the new NeoHookean model supports an efficient Hessian filtering through analytic eigen-decomposition.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22968)
=> [fem] Add NeoHookean model

solvers/projected_gradient_descent_solver.cc, solvers/test/projected_gradient_descent_solver_test.cc, solvers/test/quadratic_program_examples.cc, solvers/test/quadratic_program_examples.h
+@hongkai-dai for feature review.
cc @rpoyner-tri since you were platform review for that PR -- I assume we'll want to get this fix in pretty quickly?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22987)
=> ProjectedGradientDescentSolver Bugfix where the Wrong Projection Solver is Selected

bindings/pydrake/multibody/BUILD.bazel, bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/planning/BUILD.bazel, bindings/pydrake/planning/planning_py.cc, bindings/pydrake/planning/planning_py.h, bindings/pydrake/planning/planning_py_iris_common.cc, bindings/pydrake/planning/planning_py_iris_zo.cc, bindings/pydrake/planning/test/iris_test.py, bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, planning/iris/BUILD.bazel, planning/iris/iris_common.cc, planning/iris/iris_common.h, planning/iris/iris_zo.cc, planning/iris/iris_zo.h, planning/iris/test/iris_zo_test.cc
Many of the options in IrisZoOptions are actually shared between IRIS-ZO and the soon-to-be-implemented IRIS-NP2 (#21822). This PR factors those options into two new classes, CommonSampledIrisOptions and IrisParameterizationFunction.
+@wernerpe for feature review
Because IrisZo is `@experimental`, I think we don't need to tag this as a breaking change? Not sure how to classify it, really, but given that it will break existing code, we should probably make some mention of it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22982)
=> Factor Out Common Options Between IRIS-ZO and IRIS-NP2

multibody/fem/acceleration_newmark_scheme.cc, multibody/fem/acceleration_newmark_scheme.h, multibody/fem/discrete_time_integrator.cc, multibody/fem/discrete_time_integrator.h, multibody/fem/fem_element.h, multibody/fem/fem_model.cc, multibody/fem/fem_model.h, multibody/fem/fem_model_impl.h, multibody/fem/fem_solver.cc, multibody/fem/test/discrete_time_integrator_test.cc, multibody/fem/test/dummy_element.h, multibody/fem/test/dummy_model.h, multibody/fem/test/fem_element_test.cc, multibody/fem/test/fem_model_test.cc, multibody/fem/test/fem_solver_test.cc, multibody/fem/test/volumetric_element_test.cc, multibody/fem/test/volumetric_model_test.cc, multibody/fem/velocity_newmark_scheme.cc, multibody/fem/velocity_newmark_scheme.h, multibody/fem/volumetric_element.h, multibody/fem/volumetric_model.h, multibody/plant/deformable_driver.cc, multibody/plant/deformable_driver.h, multibody/plant/deformable_model.cc, multibody/plant/deformable_model.h, multibody/plant/test/deformable_driver_contact_test.cc
Push more per-element computation into the parallel ComputeData function. This includes the inverser dynamics force, stiffness matrix, damping matrix, and the tangent matrix.
Remove the corresponding Calc methods from the FemElement class so that derived elements use their own signature to compute these quantities that better indicates the dependencies and allows more opportunistic optimizations.
The integrator weights are added to the FemState class as a parameter so that they could be passed to the element computation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/22990)
=> [fem] Parallel residual and tangent matrix computation

multibody/tree/curvilinear_mobilizer.cc, multibody/tree/curvilinear_mobilizer.h, multibody/tree/mobilizer.h, multibody/tree/planar_mobilizer.cc, multibody/tree/planar_mobilizer.h, multibody/tree/prismatic_mobilizer.cc, multibody/tree/prismatic_mobilizer.h, multibody/tree/quaternion_floating_mobilizer.cc, multibody/tree/quaternion_floating_mobilizer.h, multibody/tree/revolute_mobilizer.cc, multibody/tree/revolute_mobilizer.h, multibody/tree/rpy_ball_mobilizer.cc, multibody/tree/rpy_ball_mobilizer.h, multibody/tree/rpy_floating_mobilizer.cc, multibody/tree/rpy_floating_mobilizer.h, multibody/tree/screw_mobilizer.cc, multibody/tree/screw_mobilizer.h, multibody/tree/universal_mobilizer.cc, multibody/tree/universal_mobilizer.h, multibody/tree/weld_mobilizer.cc, multibody/tree/weld_mobilizer.h
This is one in a series of PRs to help address issue #22630. It improves MapQDotToVelocity() so it is no longer a virtual function. Instead, it does basic argument checking (which was formerly done in all Mobilizer sub-classes) and then calls the newly created virtual function DoMapQDotToVelocity(). This technique is used also for and MapVelocityToQDot().
The prior PR #22983 was a similar clean up MapQDDotToAcceleration() and MapAccelerationToQDDot().
- - - …
=> Use NVI to consolidate code in MapVelocityToQDot().

multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/multibody_plant_test.cc
Previously, it would throw if the index of a weld joint is provided. The underlying implementation already did the "right" thing in the face of a weld joint -- nothing. So, rather than throwing, we simply clarify the documentation.
This isn't breaking, because all code that currently works will continue to work. The function just becomes more relaxed.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23004)
=> GetBodiesKinematicallyAffectedBy no longer throws on welds

multibody/tree/rpy_ball_mobilizer.cc
This is one in a series of PRs to help address issue #22630. It updates documentation in rpy_ball_mobilizer.cc and replaces an inconsistent "E" matrix notation with the "N" matrix. 
This PR is in preparation for implementation of CalcNDotMatrix(),  CalcNplusDotMatrix(), MapQDDotToAcceleration() and MapAccelerationToQDDot() in the rpy_ball_mobilizer class as was done in PR #22698 and PR #22950.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23006)
=> Correct and improve rpy_ball_mobilizer documentation, replace E matrix with standard N matrix.

bindings/pydrake/solvers/solvers_py_options.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py
Partially reverts #22938 for a handful of bindings that were dated 2025-09 not 2025-05.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23015)
=> [py solvers] Partially revert "Remove deprecated API 2025-05"

bindings/pydrake/geometry/geometry_py_scene_graph.cc, bindings/pydrake/geometry/test/scene_graph_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23011)
=> [pydrake] Add python binding for QueryObject::GetConfigurationsInWorld

multibody/plant/test/multibody_plant_test.cc, multibody/tree/parameter_conversion.h, multibody/tree/spatial_inertia.cc
PR #22977 added a precalculation for body spatial inertias that broke some symbolic calculations (it did some numerical checks for NaNs and zeroes). This PR limits those checks to numerical scalars, and adds a missing unit test (thanks, Russ!) that will prevent recurrence.
Resolves #23025
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23027)
=> Fix symbolic mass matrix computation

multibody/plant/BUILD.bazel, multibody/plant/multibody_plant.cc, multibody/plant/sap_driver.cc, multibody/plant/test/deformable_box.sdf, multibody/plant/test/multibody_plant_reaction_forces_test.cc
Adds support for reporting reaction forces on rigid bodies when a deformable is present (fixes https://github.com/RobotLocomotion/drake/issues/22942).
Specific changes include:
- Unit test to validate the reported reaction force for a scene including one rigid body and one deformable
- `CalcReactionForces` not skipped when a deformable is present (see `MultibodyPlant<T>::CalcStepUnrestricted`)
- Update `CalcDiscreteUpdateMultibodyForces` to properly account for deformable bodies (e.g. set the correct size of `constraint_spatial_forces`)
- Remove instances where Drake would throw in this scenario (i.e. `throw std::logic_error(
"The computation of MultibodyForces must be updated to include deformable objects.");` )
- - - …
=> [deformable] Report reaction force for rigid bodies

.github/ISSUE_TEMPLATE/POST_RELEASE_ACTIONS.yml, doc/_pages/from_source.md, doc/_pages/release_playbook.md, tools/release_engineering/dev/README.md, tools/release_engineering/dev/push_release.py
Closes #19734. Drake's release process currently relies on GitHub's automated source archival, for which the creation and checksums aren't necessarily stable over time. This PR introduces an additional step in the post-release process to download GitHub's source code archive, calculate sha256 and sha512 checksums, and re-upload those three files as `drake-<version>-src.tar.gz(.sha256|.sha512)`.
* Factors out some common logic from `push_archive`
* Adds a push of the source code archive to GitHub using the `github3` API in `_push_archive`
* Adds some clarification to existing comments about binary vs. source artifacts
Other incidental changes:
* Documents everything in the post-release actions issue template, release README, and `doc/_pages/from_source.md`
* Adds a check to …
=> [tools] Push an official source code archive to GitHub releases

solvers/csdp_solver.cc, solvers/gurobi_solver.cc, solvers/snopt_solver.cc, solvers/test/snopt_solver_test.cc
Also unify our spelling of Pop vs 'template' keyword across all solvers.
Closes #23032.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23039)
=> [solvers] SnoptSolver honors user requests to allocate extra memory

solvers/osqp_solver.cc, solvers/osqp_solver.h, solvers/test/mathematical_program_result_test.cc, solvers/test/osqp_solver_test.cc
Even when the problem is infeasible/unbounded/numerical_error.
This is requested by @AdityaBhat-TRI because he wants the OSQP solution of the diff IK even when the solver fails.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23028)
=> OSQP always reports primal and dual values regardless of the solver status.

setup/ubuntu/source_distribution/packages-noble-clang.txt
Towards #22996, fixing this error message:
```
/usr/bin/ld.gold: error: cannot open /usr/lib/llvm-15/lib/clang/15.0.7/lib/linux/libclang_rt.lsan-x86_64.a: No such file or directory
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23054)
=> [setup] Add missing Clang library on Noble

multibody/tree/BUILD.bazel, multibody/tree/rpy_ball_mobilizer.cc, multibody/tree/rpy_ball_mobilizer.h, multibody/tree/test/rpy_ball_mobilizer_test.cc
This is one in a series of PRs to help address issue #22630. It creates DoCalcNDotMatrix() and DoCalcNplusDotMatrix() for an RPY ball mobilizer.
PR #22950 was already merged to handle simple mobilizers for the aforementioned methods.  Subsequent PRs will create similar functions for other complex mobilizers (e.g., quaternion_floating_mobilizer). A follow-on PR will create MapQDDotToAcceleration() and MapAccelerationToQDDot() for the rpy_ball_mobilizer.
- - - …
=> Create CalcNDotMatrix() and CalcNplusDotMatrix() for rpy_ball_mobilizer.

perception/point_cloud.cc, perception/test/point_cloud_test.cc, solvers/sos_basis_generator.cc
Calling 'realloc(size=0)' is typically a synonym for 'free', but this is not portable, and newer Valgrind has started flagging this.
Eigen 3.4.0 assumes the non-portable semantics during conservativeResize, so we need to clean up some our call sites that tickle that case.
This has been fixed upstream but not released yet: https://gitlab.com/libeigen/eigen/-/merge_requests/1148.
---
Towards #22996.
This is ready for review and merge anytime.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23056)
=> Guard some Eigen realloc calls against zero

tools/workspace/usockets_internal/package.BUILD.bazel
Here's the current warning being suppressed:
```
external/+internal_repositories+usockets_internal/src/eventing/epoll_kqueue.c:220:9: warning: pointer 'p' may be used after 'realloc' [-Wuse-after-free]
220 |         us_internal_loop_update_pending_ready_polls(loop, p, new_p, events, events);
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23077)
=> [workspace] Suppress usockets warnings from GCC 13

MODULE.bazel, tools/workspace/default.bzl, tools/workspace/mypy_internal/package.BUILD.bazel, tools/workspace/mypy_internal/repository.bzl, tools/workspace/pathspec_internal/BUILD.bazel, tools/workspace/pathspec_internal/package.BUILD.bazel, tools/workspace/pathspec_internal/repository.bzl
Towards #23055
`mypy_internal` did not break the local `new_release` workflow but failed post merge in CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23070)
=> [workspace] Upgrade mypy_internal to latest release v1.16.0

doc/pydrake/pydrake_sphinx_extension.py
Towards #23057.  For the Noble version of Sphinx, we need to adjust the number and meaning of regex match groups to track https://github.com/sphinx-doc/sphinx/pull/11444.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23078)
=> [doc] Allow pydrake docs to build on either Jammy or Noble

CMakeLists.txt
Amend d8b670b0 and make additional cleanup to ensure consistent minimum versioning policies in Drake's CMake code for macOS.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23082)
=> [build] Fix minimum supported macOS versions in CMake

CMakeLists.txt
The existing warning message for an older macOS version is much clearer than the Ubuntu, where it just says the .bazelrc file cannot be found. Clarify the warning to additionally point to the officially supported OS and OS versions when building from source.
See discussion on #23082 for context.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23087)
=> [build] Adjust CMake warning for non-officially-supported Ubuntu

planning/trajectory_optimization/gcs_trajectory_optimization.h
+@Russtedrake for feature review
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23018)
=> Fix unclear documentation in GcsTrajectoryOptimization::AddPathContinuityConstraints and related methods.

geometry/optimization/iris.cc, geometry/optimization/iris_internal.cc, geometry/optimization/iris_internal.h, planning/iris/BUILD.bazel, planning/iris/iris_common.cc, planning/iris/iris_common.h, planning/iris/iris_np2.cc, planning/iris/iris_np2.h, planning/iris/iris_zo.cc, planning/iris/iris_zo.h, planning/iris/test/iris_np2_test.cc
This adds the minimal functionality for IRIS-NP2 to begin being used. Additional features will be added following this PR, but we're already over 1000 lines. This does _not_ close #21822.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23001)
=> Implement IRIS-NP2

bindings/pydrake/pydrake_doxygen.h, doc/_pages/apt.md, doc/_pages/docker.md, doc/_pages/documentation_instructions.md, doc/_pages/from_binary.md, doc/_pages/from_source.md, doc/_pages/getting_help.md, doc/_pages/jenkins.md, doc/_pages/release_playbook.md, tools/install/dockerhub/jammy/README.md
Towards #22996, closes #23052.
This coincides with CI changes to jobs that were previously Jammy-only now being Noble-only.
Include changing the 'default' Dockerhub image (i.e. only specifying `X.Y.Z` or `YYYYMMDD`, without an OS version) to Noble. Exclude documentation changes which are not ready to switch yet:
* tools/release_engineering and tools/workspace/new_release.py
* Deepnote tutorials
* CLion docs
Also fix the language of the Packaging section of jenkins.md to mirror the Wheel section.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23066)
=> [doc] Switch to Ubuntu Noble as the primary development platform

bindings/pydrake/planning/planning_py_iris_np2.cc, bindings/pydrake/planning/test/iris_test.py, planning/iris/iris_np2.cc, planning/iris/iris_np2.h, planning/iris/test/iris_np2_test.cc
Holding off on review until #23096 lands.
This PR also adds a warning to the user if the counterexample programs are failing frequently. This is a known pathology when using SNOPT or NLOPT (it happens particularly frequently in the "convex configuration space" test environment), so we suggest the user try IPOPT if this is happening. See the following images (each black dot indicates where a solve failed).
SNOPT:
NLOPT:
IPOPT:
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23101)
=> Allow the User to Set the Solver for IrisNp2

systems/lcm/BUILD.bazel
Towards #23110
This test reported TSAN errors after the Jammy -> Noble platform switch. These changes temporarily disable TSAN for this test while we triage this error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23112)
=> Disable TSAN for `lcm_interface_system_test`

geometry/render_gl/BUILD.bazel
Towards #23107
This test began failing after the Jammy -> Noble platform switch. These changes temporarily disable ASAN for this test to allow CI to run gracefully while we triage this error.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23109)
=> Disable ASAN for `internal_opengl_context` test

bindings/pydrake/planning/planning_py_iris_common.cc, bindings/pydrake/planning/test/iris_test.py, planning/iris/iris_common.h, planning/iris/iris_np2.cc, planning/iris/iris_zo.cc, planning/iris/test/iris_np2_test.cc, planning/iris/test/iris_zo_test.cc
Closes #23050. Holding off on review until #23096 lands.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23102)
=> IrisNp2 Option to Add Hyperplanes Even After Passing the Probabilistic Test

bindings/pydrake/multibody/inverse_kinematics_py.cc, bindings/pydrake/multibody/test/inverse_kinematics_test.py
@lunatic006 and I are using GlobalInverseKinematics and realized these bindings (which we need) are missing. I'll also take responsibility for the TODO to support subclasses of ConvexSet (instead of the bespoke `Polytope3D`), although I'll probably defer that to later.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23122)
=> Implement Missing Bindings for GlobalInverseKinematics

planning/iris/iris_zo.cc
cc @jwnimmer-tri 
I'm not sure how to properly test this, since it's functionally a no-op. `particles` doesn't get touched by anything after this through the end of the loop's current iteration, and then at the start of the next loop, it's immediately overwritten again. Is the fact that the test cases still pass sufficient justification for the fix being valid?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23127)
=> Remove an Extra Sampling Step that Was Potentially Slowing IrisZo Down.

doc/_pages/from_source.md, geometry/shape_specification.cc, setup/ubuntu/source_distribution/packages-noble-clang.txt, setup/ubuntu/source_distribution/packages-noble.txt, tools/dynamic_analysis/asan.sh, tools/dynamic_analysis/lsan.sh, tools/dynamic_analysis/tsan.sh, tools/dynamic_analysis/ubsan.sh, tools/ubuntu-noble.bazelrc, tools/workspace/common_robotics_utilities_internal/package.BUILD.bazel, tools/workspace/pybind11/libclang_setup.py
The current Clang 15 is incompatible with GCC 14, which is installed on Noble by default when we apt-install Emacs.
This solves #22905 more thoroughly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23124)
=> [setup] Switch Noble's preferred Clang to clang-19

tools/workspace/abseil_cpp_internal/patches/inline_namespace.patch, tools/workspace/abseil_cpp_internal/repository.bzl
Towards #23138 
Reason for separation: fails locally
```
ERROR: /home/local/KHQ/aiden.mccormack/.cache/bazel/_bazel_aiden.mccormack/d8f67396fa92625d9dd7f1218b66f6d2/external/bazel_tools/tools/build_defs/repo/utils.bzl:220:21: An error occurred during the fetch of repository '+internal_repositories+abseil_cpp_internal':
Traceback (most recent call last):
File "/home/local/KHQ/aiden.mccormack/drake-aiden2244/drake/tools/workspace/github.bzl", line 128, column 37, in _github_archive_real_impl
result = setup_github_repository(repository_ctx)
File "/home/local/KHQ/aiden.mccormack/drake-aiden2244/drake/tools/workspace/github.bzl", line 207, column 14, in setup_github_repository
patch(repository_ctx)
File "/home/local/KHQ/aiden.mccormack/.cache/bazel/_bazel_aiden.mccormack/d8f67396fa92625d9dd7f12 …
```
=> [workspace] Upgrade abseil_cpp_internal to latest commit

common/eigen_types.h, common/never_destroyed.h, common/test_utilities/is_memcpy_movable.h, common/test_utilities/limit_malloc.cc
As of C++23, this generates deprecation warnings.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23145)
=> Remove uses of deprecated std::aligned_storage

.jenkins/Jenkinsfile-cache-server-health-check, .jenkins/Jenkinsfile-experimental, .jenkins/Jenkinsfile-external-examples, .jenkins/Jenkinsfile-production, .jenkins/Jenkinsfile-staging, .jenkins/utils/utils.groovy, doc/_pages/jenkins.md
Towards #22826. Adds `.jenkins/` for defining Jenkins job logic in Drake itself, rather than dynamically generating it in job definitions:
* Adds production, experimental, staging, cache server health check, and external examples pipelines in `Jenkinsfile`s
* Adds shared utils in `utils/utils.groovy`
* Fixes documentation in `jenkins.md` for how to use the new experimental jobs
The continuous, nightly, experimental, and pre-merge jobs will all use these files. Experimental and pre-merge jobs will look a little different, but function the same way in terms of providing parameters to run branches/PRs of drake and CI, running automatically on PRs, keeping the "@drake-jenkins-bot ..." comment triggers, etc.
- - - …
=> Add `Jenkinsfile`s

CMakeLists.txt, tools/cc_toolchain/BUILD.bazel, tools/skylark/drake_cc.bzl, tools/skylark/pybind.bzl
Closes #23119.
Add a Bazel flag to opt in to tweaking compiler-specific flags, so that CMake can use it when checking against `CMAKE_<LANG>_COMPILER_ID`. This allows Linux CMake users to inherit Bazel's `cc_toolchain` logic without having to specify `CMAKE_<LANG>_COMPILER` (notably, when the compiler is 'cc'/'c++').
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23117)
=> [build] Pass a more specific compiler from CMake to Bazel

doc/_pages/installation.md, tools/ubuntu-noble.bazelrc, tools/workspace/vtk_internal/patches/upstream/common_executionmodel_vtkalgorithm_ternary.patch, tools/workspace/vtk_internal/repository.bzl
This updates our Noble release packages to use C++23, which allows downstream projects to use C++23 features in their own code if they like.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23147)
=> [tools] Default to C++23 on Noble

multibody/tree/rpy_ball_mobilizer.cc, multibody/tree/rpy_ball_mobilizer.h, multibody/tree/test/rpy_ball_mobilizer_test.cc
This is one in a series of PRs to help address issue #22630. It creates DoMapAccelerationToQDDot() and DoMapQDDotToAcceleration() for an RPY ball mobilizer.
PR #22698 was already merged to handle simple mobilizers for the aforementioned methods. Subsequent PRs will create similar functions for other complex mobilizers (e.g., quaternion_floating_mobilizer).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23092)
=> MapQDDotToAcceleration() and MapAccelerationToQDDot() for rpy mobilizer.

solvers/clp_solver.cc, solvers/test/clp_solver_test.cc
Give a more appropriate warning when a user tries to solve a QP with CLP. This serves as a band-aid for #22985 until we actually decide what to do about CLP and QPs.
@jwnimmer-tri maybe you could take feature review for this one, since you've been active in that discussion?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23199)
=> Warn when solving a QP with CLP.

multibody/plant/test/multibody_plant_reaction_forces_test.cc, multibody/plant/test/multibody_plant_test.cc, multibody/topology/link_joint_graph_defs.h, multibody/tree/joint.h, multibody/tree/multibody_element.h, multibody/tree/multibody_tree_indexes.h
(Tech debt cleanup)
Because Joints are removable, we have both the persistent JointIndex and possibly-changing JointOrdinal for each Joint (both of those are TypeSafeIndex specializations). Code in `multibody/topology` uses both types but code in `multibody/tree` is using just a raw int for JointOrdinal.
This PR promotes JointOrdinal from `drake::multibody::internal` to `drake::multibody` and uses it where needed in MbT.
The return type of the MbP public method `Joint::ordinal()` is changed here from int to JointOrdinal. However, all TypeSafeIndex specializations have an implicit conversion to int64_t so any place where joint.ordinal() is used as an index (into reaction force results, e.g.) it still works unchanged. The reverse conversion of int to JointOrdinal must now be explicit; …
=> [multibody] Expose the JointOrdinal type and use it instead of a raw int.

multibody/plant/test/multibody_plant_test.cc, multibody/tree/fixed_offset_frame.h
For `FixedOffsetFrame`, parent frame variable `parent_frame_` is encapsulated and there is no easy way to get it- adding a constant getter so one can use.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23221)
=> Add a getter for `parent_frame` in FixedOffsetFrame

bindings/pydrake/solvers/solvers_py_mathematicalprogram.cc, bindings/pydrake/solvers/test/mathematicalprogram_test.py, solvers/mathematical_program.cc, solvers/mathematical_program.h, solvers/test/mathematical_program_test.cc
Note that the existing L1NormCost object is treated as a generic cost, so you can't use it with solvers like Gurobi.
+@alexandreamice for feature review
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23241)
=> Add an L1 norm cost to MathematicalProgram using slack variables.

multibody/parsing/BUILD.bazel, multibody/parsing/detail_collision_filter_group_resolver.cc, multibody/parsing/detail_collision_filter_group_resolver.h, multibody/parsing/test/detail_collision_filter_group_resolver_test.cc, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/process_model_directives_test.cc, multibody/parsing/test/process_model_directives_test/deformable_model.sdf, multibody/plant/multibody_plant.cc, multibody/plant/multibody_plant.h, multibody/plant/test/deformable_collision_filter_test.cc
Allows collisions involving deformable bodies to be filtered via the MbP collision exclusion API and via collision filter groups in SDF or dmd files. Closes https://github.com/RobotLocomotion/drake/issues/22953.
**Primary design considerations:**
- When adding automatic collision filters for adjacent bodies during plant finalization, deformable bodies are ignored. All deformable bodies are children of the world body, so they are all adjacent and would otherwise have their collisions filtered. This is unchanged from the current behavior.
- Users can explicitly specify a collision filter involving deformable bodies either by `MultibodyPlant.ExcludeCollisionGeometriesWithCollisionFilterGroupPair()` or in the SDF file or dmd . This is changed from the current behavior.
- The internal …
=> [deformable] Enable deformable body collision filtering via MbP and parsing

doc/_pages/vscode.md
Also on generating compile_commands.json.
Replaces #23260
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23274)
=> Add instruction on enabling semantic analysis in VSCode.

multibody/parsing/detail_common.cc, multibody/parsing/detail_common.h, multibody/parsing/detail_sdf_parser.cc, multibody/parsing/detail_urdf_parser.cc, multibody/parsing/parsing_doxygen.h, multibody/parsing/test/detail_sdf_parser_test.cc, multibody/parsing/test/detail_urdf_parser_test.cc
Implements SDF/URDF parsing support for tendon constraints on the MbP. The parsing code mostly mimics what already exists for other constraints, like `drake:ball_constraint`.
---
Let me know what you think is the correct SDF/URDF format for the joint name/coefficient pairs. Because they are associated pairwise (`joints[i]` references `a[i]`), it makes sense to specify them together. In both SDF and URDF, I have chosen this syntax:
```xml
<drake:tendon_constraint_joint name='revolute_AB' a='10'/>
```
But there may be other options, for example:
```xml
// SDF
<drake:tendon_constraint_joint a='10'>revolute_AB</drake:tendon_constraint_joint>
<drake:tendon_constraint_joint a='10'>revolute_BC</drake:tendon_constraint_joint>
// URDF
<drake:tendon_constraint_joint name='revolute_AB' a='10'/> …
```
=> [parsing] Parse custom tendon constraint elements

.jenkins/Jenkinsfile-experimental, .jenkins/templates/Jenkinsfile-experimental.in, doc/_pages/jenkins.md, doc/_pages/release_playbook.md
Use the [pipeline-github-plugin](https://github.com/jenkinsci/pipeline-github-plugin) to check if a PR is labeled `status: defer ci`, in which case, abort. Update the release playbook to use the new method (instead of making a dummy commit which fails the build, as before), and add instructions to the Jenkins page.
Closes #23169.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23287)
=> [Jenkins] Add check for label to defer CI

multibody/multibody_doxygen.h
During review of PR #23135, there was a recognition of inconsistencies and ambiguities with Drake quaternion notation. This PR addresses one of the items in issue #23210, namely to include the rotation quaternion in Drake Multibody Quantities [monogram notation.](https://drake.mit.edu/doxygen_cxx/group__multibody__quantities.html)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23283)
=> Document monogram notation for a rotation quaternion (Drake Multibody Quantities).

setup/python/pdm.lock, setup/python/pyproject.toml, tools/wheel/image/build-wheel.sh
Update the wheel build process to use the 'build' package to build the wheels instead of invoking 'setup.py' directly (which is deprecated).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23297)
=> Build wheels with 'build'

tools/skylark/drake_cc.bzl
These warnings had been marked with a TODO to try to enable them:
* array-bounds
* dangling-reference
* maybe-uninitialized
* stringop-overflow
* stringop-overread
After exploring their false positive rate, it is not realistic to enable them.
Towards #21337.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23307)
=> [tools] Final decision on most GCC 13 warnings

.github/renovate.json
Closes #23341.
Adds the "bazel-module" package manager to the "enabledManagers" array in `//.github/renovate.json`. Parses the MODULE.bazel file for "bazel_deps()" calls and recommends version bumps whenever they are detected.
Presently detected Renovate dependencies:
```
bazelisk
.bazelversion
bazel 8.3.1
bazel-module
MODULE.bazel
apple_support 1.17.1
bazel_features 1.30.0
bazel_skylib 1.8.0
platforms 0.0.11
rules_cc 0.1.1
rules_java 8.12.0
rules_license 1.0.0
rules_python 0.40.0
rules_rust 0.56.0
rules_shell 0.3.0
eigen 3.4.0.bcr.3
fmt 11.0.2.bcr.1
spdlog 1.15.0.bcr.4
zlib 1.3.1.bcr.5
toolchains_llvm 1.4.0
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23342 …
=> [build] Configure Renovate to upgrade BCR deps in MODULE.bazel

geometry/proximity/bvh.cc, geometry/proximity/bvh.h, geometry/proximity/bvh_updater.h
Using a made-up alias that indirects through a header file serves only to obscure the reality of what's going on.  Any given idea should have exactly one name, which we should use everywhere.
(Noticed while reviewing our GSG's new test about the naming for static constants.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23351)
=> [geometry] Remove obscure constant

geometry/render_gl/BUILD.bazel
This one has already been disabled under ASAN, and it's holding up image upgrades.
Closes #23366, FYI #23107.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23378)
=> Disable render_gl test under LSAN

tools/skylark/drake_cc.bzl
Our rules_cc (and bazel) versions are new enough to offer this natively.
The polyfilll interacts poorly with our newer cpplint (#22689).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23384)
=> [tools] Remove polyfill of implementation_deps

CMakeLists.txt, doc/_pages/from_source.md
Drake's build takes a number of `CMAKE_` options and converts them to Bazel flags. We should document such logic similar to the Drake-specific CMake options.
Also, remove the `CMAKE_` prefix from the install name tool and strip tool options. These are not (and have never been) native CMake variables, and aside from the issue that CMake reserves that naming convention, it's just confusing for developers.
Raised by discussion on https://github.com/RobotLocomotion/drake/pull/23298#pullrequestreview-3161594349.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23339)
=> [doc] Document supported native CMake options

.github/renovate.json
Closes #23371
Additionally changes scheduling logic from "at 6am on the first of every month" to "at any hour on the first of every month."
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23372)
=> Use cron syntax for Renovate scheduler

tools/workspace/new_release.py
This overcomes the error seen in #23401.
+@Aiden2244 for feature review, please.  It's probably worth checking that this works both for SCS, as well as a repository that doesn't use tags (e.g., `drake_models`).
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23402)
=> [workspace] Adjust new_release for downloading from tag vs commit

planning/iris/iris_np2.cc
+@rhjiang for feature review.
I was unable to produce a specific test case to exhibit this bug, since in practice, the algorithm will work eventually -- it will just require more runtime and more hyperplanes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23408)
=> Fix bug in IrisNp2 where all but the last hyperplane was being used when there are additional constraints.

tools/lint/BUILD.bazel, tools/lint/lint.bzl, tools/lint/python_lint.bzl
This prep work helps simplify #23427.
If we don't pass any ignore flags to pycodestyle, it uses its built-in default automatically.  We don't need to repeat it in our code unless we're going to customize it.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23452)
=> [tools] Remove unused python_lint_ignore customization

tools/workspace/highway_internal/patches/target_get_index_inline_always.patch
This fixes the `exported_symbols_test` errors in #23456.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23457)
=> [workspace] Fix a little more highway symbol leakage

lcm/BUILD.bazel, lcm/drake_lcm_log.cc, lcm/test/drake_lcm_test.cc, lcm/test/drake_lcm_thread_test.cc, tools/install/libdrake/BUILD.bazel, tools/workspace/BUILD.bazel, tools/workspace/lcm/BUILD.bazel, tools/workspace/lcm/package.BUILD.bazel, tools/workspace/lcm_internal/BUILD.bazel, tools/workspace/lcm_internal/patches/copts.patch, tools/workspace/lcm_internal/patches/vendor_namespace.patch, tools/workspace/lcm_internal/repository.bzl
We now use the upstream Bazel build rules for the shared library (with a few customizations for our vendoring).
This is the last part of `@lcm` we were using, so the next commit after this one will deprecate it for removal.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23474)
=> [workspace] Use LCM runtime from lcm_internal (not lcm)

bindings/pydrake/common/eigen_pybind.h, bindings/pydrake/common/sorted_pair_pybind.h
Amends commit 30bda2d9237b034bd85e6035542c2657a2c75633; more call sites found.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23481)
=> [pydrake] Stop relying on a deprecated internal pybind11 name

tools/workspace/metadata.py
Follow-up to #23455 
Tweak variable name in `metadata.py` which caused `new_release` script to break.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23497)
=> [workspace] fix variable rename in metadata script

tools/wheel/image/build-wheel.sh
```
$  [[ "$(brew config | \grep -E '^HOMEBREW_PREFIX' | cut -c18-)" = "$(brew --prefix)" ]] && echo "true"
true
```
Also used here: 
https://github.com/RobotLocomotion/drake/blob/3bb881e305e999527c6c11283b50f1c6544391c9/tools/wheel/macos/build-wheel.sh#L26
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23443)
=> [wheel] Refactor HOMEBREW_PREFIX computation in image/build-wheel.sh

examples/multibody/cart_pole/test/cart_pole_test.cc, math/test/rigid_transform_test.cc, math/test/rotation_matrix_test.cc, solvers/mixed_integer_rotation_constraint.cc, solvers/test/mathematical_program_test.cc, systems/primitives/test/affine_system_test.cc, systems/primitives/test/multilayer_perceptron_test.cc
Towards #23477.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23526)
=> Fix Eigen-related constructor snafus in tests

common/BUILD.bazel, common/resource_tool.cc, setup/ubuntu/source_distribution/packages-jammy.txt, setup/ubuntu/source_distribution/packages-noble.txt, tools/install/installer.py, tools/lint/clang_format_lint.py
The `resource_tool` program was one of the earliest parts of Drake, preceding even `pydrake`.  Now that we have `pydrake` which can handle this function and more, there is no longer a need to install a platform-specific binary (into `$prefix/share/drake`!).
I considered having `resource_tool` print a warning to stderr, but that might conceivably break people, so the deprecation will be announced in release notes but not with a runtime warning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23523)
=> [setup] Remove diff and file as source prereqs

bindings/generated_docstrings/geometry_proximity.h, geometry/proximity/mesh_field_linear.h, geometry/proximity/polygon_surface_mesh.cc, geometry/proximity/polygon_surface_mesh.h, geometry/proximity/triangle_surface_mesh.cc, geometry/proximity/triangle_surface_mesh.h, geometry/proximity/volume_mesh.cc, geometry/proximity/volume_mesh.h
Towards #23477.  (Eigen 5's updated linear solvers cause Drake a bit of trouble; having that isolated into a few files instead of spammed into everything downstream of these headers improves developer iteration speed.)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/RobotLocomotion/drake/23527)
=> [geometry] Move CalcBarycentric to be non-inline
